QT += network

HEADERS += \
# Models
    $${PWD}/OAIAdvancedFilter.h \
    $${PWD}/OAIAzureFunctionEventSubscriptionDestination.h \
    $${PWD}/OAIAzureFunctionEventSubscriptionDestinationProperties.h \
    $${PWD}/OAIBoolEqualsAdvancedFilter.h \
    $${PWD}/OAIDeadLetterDestination.h \
    $${PWD}/OAIDomain.h \
    $${PWD}/OAIDomainProperties.h \
    $${PWD}/OAIDomainRegenerateKeyRequest.h \
    $${PWD}/OAIDomainSharedAccessKeys.h \
    $${PWD}/OAIDomainTopic.h \
    $${PWD}/OAIDomainTopicProperties.h \
    $${PWD}/OAIDomainTopicsListResult.h \
    $${PWD}/OAIDomainUpdateParameters.h \
    $${PWD}/OAIDomainsListResult.h \
    $${PWD}/OAIEventHubEventSubscriptionDestination.h \
    $${PWD}/OAIEventHubEventSubscriptionDestinationProperties.h \
    $${PWD}/OAIEventSubscription.h \
    $${PWD}/OAIEventSubscriptionDestination.h \
    $${PWD}/OAIEventSubscriptionFilter.h \
    $${PWD}/OAIEventSubscriptionFullUrl.h \
    $${PWD}/OAIEventSubscriptionProperties.h \
    $${PWD}/OAIEventSubscriptionUpdateParameters.h \
    $${PWD}/OAIEventSubscriptionsListResult.h \
    $${PWD}/OAIEventType.h \
    $${PWD}/OAIEventTypeProperties.h \
    $${PWD}/OAIEventTypesListResult.h \
    $${PWD}/OAIHybridConnectionEventSubscriptionDestination.h \
    $${PWD}/OAIHybridConnectionEventSubscriptionDestinationProperties.h \
    $${PWD}/OAIInboundIpRule.h \
    $${PWD}/OAIInputSchemaMapping.h \
    $${PWD}/OAIJsonField.h \
    $${PWD}/OAIJsonFieldWithDefault.h \
    $${PWD}/OAIJsonInputSchemaMapping.h \
    $${PWD}/OAIJsonInputSchemaMappingProperties.h \
    $${PWD}/OAINumberGreaterThanAdvancedFilter.h \
    $${PWD}/OAINumberGreaterThanOrEqualsAdvancedFilter.h \
    $${PWD}/OAINumberInAdvancedFilter.h \
    $${PWD}/OAINumberLessThanAdvancedFilter.h \
    $${PWD}/OAINumberLessThanOrEqualsAdvancedFilter.h \
    $${PWD}/OAINumberNotInAdvancedFilter.h \
    $${PWD}/OAIOperation.h \
    $${PWD}/OAIOperationInfo.h \
    $${PWD}/OAIOperationsListResult.h \
    $${PWD}/OAIResource.h \
    $${PWD}/OAIRetryPolicy.h \
    $${PWD}/OAIServiceBusQueueEventSubscriptionDestination.h \
    $${PWD}/OAIServiceBusQueueEventSubscriptionDestinationProperties.h \
    $${PWD}/OAIServiceBusTopicEventSubscriptionDestination.h \
    $${PWD}/OAIServiceBusTopicEventSubscriptionDestinationProperties.h \
    $${PWD}/OAIStorageBlobDeadLetterDestination.h \
    $${PWD}/OAIStorageBlobDeadLetterDestinationProperties.h \
    $${PWD}/OAIStorageQueueEventSubscriptionDestination.h \
    $${PWD}/OAIStorageQueueEventSubscriptionDestinationProperties.h \
    $${PWD}/OAIStringBeginsWithAdvancedFilter.h \
    $${PWD}/OAIStringContainsAdvancedFilter.h \
    $${PWD}/OAIStringEndsWithAdvancedFilter.h \
    $${PWD}/OAIStringInAdvancedFilter.h \
    $${PWD}/OAIStringNotInAdvancedFilter.h \
    $${PWD}/OAITopic.h \
    $${PWD}/OAITopicProperties.h \
    $${PWD}/OAITopicRegenerateKeyRequest.h \
    $${PWD}/OAITopicSharedAccessKeys.h \
    $${PWD}/OAITopicTypeInfo.h \
    $${PWD}/OAITopicTypeProperties.h \
    $${PWD}/OAITopicTypesListResult.h \
    $${PWD}/OAITopicUpdateParameters.h \
    $${PWD}/OAITopicsListResult.h \
    $${PWD}/OAITrackedResource.h \
    $${PWD}/OAIWebHookEventSubscriptionDestination.h \
    $${PWD}/OAIWebHookEventSubscriptionDestinationProperties.h \
# APIs
    $${PWD}/OAIDomainTopicsApi.h \
    $${PWD}/OAIDomainsApi.h \
    $${PWD}/OAIEventSubscriptionsApi.h \
    $${PWD}/OAIOperationsApi.h \
    $${PWD}/OAITopicTypesApi.h \
    $${PWD}/OAITopicsApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAdvancedFilter.cpp \
    $${PWD}/OAIAzureFunctionEventSubscriptionDestination.cpp \
    $${PWD}/OAIAzureFunctionEventSubscriptionDestinationProperties.cpp \
    $${PWD}/OAIBoolEqualsAdvancedFilter.cpp \
    $${PWD}/OAIDeadLetterDestination.cpp \
    $${PWD}/OAIDomain.cpp \
    $${PWD}/OAIDomainProperties.cpp \
    $${PWD}/OAIDomainRegenerateKeyRequest.cpp \
    $${PWD}/OAIDomainSharedAccessKeys.cpp \
    $${PWD}/OAIDomainTopic.cpp \
    $${PWD}/OAIDomainTopicProperties.cpp \
    $${PWD}/OAIDomainTopicsListResult.cpp \
    $${PWD}/OAIDomainUpdateParameters.cpp \
    $${PWD}/OAIDomainsListResult.cpp \
    $${PWD}/OAIEventHubEventSubscriptionDestination.cpp \
    $${PWD}/OAIEventHubEventSubscriptionDestinationProperties.cpp \
    $${PWD}/OAIEventSubscription.cpp \
    $${PWD}/OAIEventSubscriptionDestination.cpp \
    $${PWD}/OAIEventSubscriptionFilter.cpp \
    $${PWD}/OAIEventSubscriptionFullUrl.cpp \
    $${PWD}/OAIEventSubscriptionProperties.cpp \
    $${PWD}/OAIEventSubscriptionUpdateParameters.cpp \
    $${PWD}/OAIEventSubscriptionsListResult.cpp \
    $${PWD}/OAIEventType.cpp \
    $${PWD}/OAIEventTypeProperties.cpp \
    $${PWD}/OAIEventTypesListResult.cpp \
    $${PWD}/OAIHybridConnectionEventSubscriptionDestination.cpp \
    $${PWD}/OAIHybridConnectionEventSubscriptionDestinationProperties.cpp \
    $${PWD}/OAIInboundIpRule.cpp \
    $${PWD}/OAIInputSchemaMapping.cpp \
    $${PWD}/OAIJsonField.cpp \
    $${PWD}/OAIJsonFieldWithDefault.cpp \
    $${PWD}/OAIJsonInputSchemaMapping.cpp \
    $${PWD}/OAIJsonInputSchemaMappingProperties.cpp \
    $${PWD}/OAINumberGreaterThanAdvancedFilter.cpp \
    $${PWD}/OAINumberGreaterThanOrEqualsAdvancedFilter.cpp \
    $${PWD}/OAINumberInAdvancedFilter.cpp \
    $${PWD}/OAINumberLessThanAdvancedFilter.cpp \
    $${PWD}/OAINumberLessThanOrEqualsAdvancedFilter.cpp \
    $${PWD}/OAINumberNotInAdvancedFilter.cpp \
    $${PWD}/OAIOperation.cpp \
    $${PWD}/OAIOperationInfo.cpp \
    $${PWD}/OAIOperationsListResult.cpp \
    $${PWD}/OAIResource.cpp \
    $${PWD}/OAIRetryPolicy.cpp \
    $${PWD}/OAIServiceBusQueueEventSubscriptionDestination.cpp \
    $${PWD}/OAIServiceBusQueueEventSubscriptionDestinationProperties.cpp \
    $${PWD}/OAIServiceBusTopicEventSubscriptionDestination.cpp \
    $${PWD}/OAIServiceBusTopicEventSubscriptionDestinationProperties.cpp \
    $${PWD}/OAIStorageBlobDeadLetterDestination.cpp \
    $${PWD}/OAIStorageBlobDeadLetterDestinationProperties.cpp \
    $${PWD}/OAIStorageQueueEventSubscriptionDestination.cpp \
    $${PWD}/OAIStorageQueueEventSubscriptionDestinationProperties.cpp \
    $${PWD}/OAIStringBeginsWithAdvancedFilter.cpp \
    $${PWD}/OAIStringContainsAdvancedFilter.cpp \
    $${PWD}/OAIStringEndsWithAdvancedFilter.cpp \
    $${PWD}/OAIStringInAdvancedFilter.cpp \
    $${PWD}/OAIStringNotInAdvancedFilter.cpp \
    $${PWD}/OAITopic.cpp \
    $${PWD}/OAITopicProperties.cpp \
    $${PWD}/OAITopicRegenerateKeyRequest.cpp \
    $${PWD}/OAITopicSharedAccessKeys.cpp \
    $${PWD}/OAITopicTypeInfo.cpp \
    $${PWD}/OAITopicTypeProperties.cpp \
    $${PWD}/OAITopicTypesListResult.cpp \
    $${PWD}/OAITopicUpdateParameters.cpp \
    $${PWD}/OAITopicsListResult.cpp \
    $${PWD}/OAITrackedResource.cpp \
    $${PWD}/OAIWebHookEventSubscriptionDestination.cpp \
    $${PWD}/OAIWebHookEventSubscriptionDestinationProperties.cpp \
# APIs
    $${PWD}/OAIDomainTopicsApi.cpp \
    $${PWD}/OAIDomainsApi.cpp \
    $${PWD}/OAIEventSubscriptionsApi.cpp \
    $${PWD}/OAIOperationsApi.cpp \
    $${PWD}/OAITopicTypesApi.cpp \
    $${PWD}/OAITopicsApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
