QT += network

HEADERS += \
# Models
    $${PWD}/OAIAbridgedVideoView.h \
    $${PWD}/OAIAsset.h \
    $${PWD}/OAIAssetGeneratedSubtitleSettings.h \
    $${PWD}/OAIAssetResponse.h \
    $${PWD}/OAIAsset_errors.h \
    $${PWD}/OAIAsset_master.h \
    $${PWD}/OAIAsset_non_standard_input_reasons.h \
    $${PWD}/OAIAsset_recording_times_inner.h \
    $${PWD}/OAIAsset_static_renditions.h \
    $${PWD}/OAIAsset_static_renditions_files_inner.h \
    $${PWD}/OAIBreakdownValue.h \
    $${PWD}/OAIBroadcast.h \
    $${PWD}/OAIBroadcastLayout.h \
    $${PWD}/OAIBroadcastResolution.h \
    $${PWD}/OAIBroadcastResponse.h \
    $${PWD}/OAIBroadcastStatus.h \
    $${PWD}/OAICreateAssetRequest.h \
    $${PWD}/OAICreateBroadcastRequest.h \
    $${PWD}/OAICreateLiveStreamRequest.h \
    $${PWD}/OAICreatePlaybackIDRequest.h \
    $${PWD}/OAICreatePlaybackIDResponse.h \
    $${PWD}/OAICreatePlaybackRestrictionRequest.h \
    $${PWD}/OAICreateSimulcastTargetRequest.h \
    $${PWD}/OAICreateSpaceRequest.h \
    $${PWD}/OAICreateTrackRequest.h \
    $${PWD}/OAICreateTrackResponse.h \
    $${PWD}/OAICreateTranscriptionVocabularyRequest.h \
    $${PWD}/OAICreateUploadRequest.h \
    $${PWD}/OAIDeliveryReport.h \
    $${PWD}/OAIDeliveryReport_delivered_seconds_by_resolution.h \
    $${PWD}/OAIDimensionValue.h \
    $${PWD}/OAIDisableLiveStreamResponse.h \
    $${PWD}/OAIEnableLiveStreamResponse.h \
    $${PWD}/OAIError.h \
    $${PWD}/OAIExportDate.h \
    $${PWD}/OAIExportFile.h \
    $${PWD}/OAIFilterValue.h \
    $${PWD}/OAIGetAssetInputInfoResponse.h \
    $${PWD}/OAIGetAssetOrLiveStreamIdResponse.h \
    $${PWD}/OAIGetAssetOrLiveStreamIdResponse_data.h \
    $${PWD}/OAIGetAssetOrLiveStreamIdResponse_data_object.h \
    $${PWD}/OAIGetAssetPlaybackIDResponse.h \
    $${PWD}/OAIGetLiveStreamPlaybackIDResponse.h \
    $${PWD}/OAIGetMetricTimeseriesDataResponse.h \
    $${PWD}/OAIGetMonitoringBreakdownResponse.h \
    $${PWD}/OAIGetMonitoringBreakdownTimeseriesResponse.h \
    $${PWD}/OAIGetMonitoringHistogramTimeseriesResponse.h \
    $${PWD}/OAIGetMonitoringHistogramTimeseriesResponse_meta.h \
    $${PWD}/OAIGetMonitoringTimeseriesResponse.h \
    $${PWD}/OAIGetOverallValuesResponse.h \
    $${PWD}/OAIGetRealTimeBreakdownResponse.h \
    $${PWD}/OAIGetRealTimeHistogramTimeseriesResponse.h \
    $${PWD}/OAIGetRealTimeHistogramTimeseriesResponse_meta.h \
    $${PWD}/OAIGetRealTimeTimeseriesResponse.h \
    $${PWD}/OAIIncident.h \
    $${PWD}/OAIIncidentBreakdown.h \
    $${PWD}/OAIIncidentNotification.h \
    $${PWD}/OAIIncidentNotificationRule.h \
    $${PWD}/OAIIncidentResponse.h \
    $${PWD}/OAIInputFile.h \
    $${PWD}/OAIInputInfo.h \
    $${PWD}/OAIInputSettings.h \
    $${PWD}/OAIInputSettings_overlay_settings.h \
    $${PWD}/OAIInputTrack.h \
    $${PWD}/OAIInsight.h \
    $${PWD}/OAIListAllMetricValuesResponse.h \
    $${PWD}/OAIListAssetsResponse.h \
    $${PWD}/OAIListBreakdownValuesResponse.h \
    $${PWD}/OAIListDeliveryUsageResponse.h \
    $${PWD}/OAIListDimensionValuesResponse.h \
    $${PWD}/OAIListDimensionsResponse.h \
    $${PWD}/OAIListDimensionsResponse_data.h \
    $${PWD}/OAIListErrorsResponse.h \
    $${PWD}/OAIListExportsResponse.h \
    $${PWD}/OAIListFilterValuesResponse.h \
    $${PWD}/OAIListFiltersResponse.h \
    $${PWD}/OAIListIncidentsResponse.h \
    $${PWD}/OAIListInsightsResponse.h \
    $${PWD}/OAIListLiveStreamsResponse.h \
    $${PWD}/OAIListMonitoringDimensionsResponse.h \
    $${PWD}/OAIListMonitoringDimensionsResponse_data_inner.h \
    $${PWD}/OAIListMonitoringMetricsResponse.h \
    $${PWD}/OAIListPlaybackRestrictionsResponse.h \
    $${PWD}/OAIListRealTimeDimensionsResponse.h \
    $${PWD}/OAIListRealTimeMetricsResponse.h \
    $${PWD}/OAIListRelatedIncidentsResponse.h \
    $${PWD}/OAIListSigningKeysResponse.h \
    $${PWD}/OAIListSpacesResponse.h \
    $${PWD}/OAIListTranscriptionVocabulariesResponse.h \
    $${PWD}/OAIListUploadsResponse.h \
    $${PWD}/OAIListVideoViewExportsResponse.h \
    $${PWD}/OAIListVideoViewsResponse.h \
    $${PWD}/OAILiveStream.h \
    $${PWD}/OAILiveStreamEmbeddedSubtitleSettings.h \
    $${PWD}/OAILiveStreamGeneratedSubtitleSettings.h \
    $${PWD}/OAILiveStreamResponse.h \
    $${PWD}/OAILiveStreamStatus.h \
    $${PWD}/OAIMetric.h \
    $${PWD}/OAIMonitoringBreakdownTimeseriesDatapoint.h \
    $${PWD}/OAIMonitoringBreakdownTimeseriesValues.h \
    $${PWD}/OAIMonitoringBreakdownValue.h \
    $${PWD}/OAIMonitoringHistogramTimeseriesBucket.h \
    $${PWD}/OAIMonitoringHistogramTimeseriesBucketValues.h \
    $${PWD}/OAIMonitoringHistogramTimeseriesDatapoint.h \
    $${PWD}/OAIMonitoringTimeseriesDatapoint.h \
    $${PWD}/OAINotificationRule.h \
    $${PWD}/OAIOverallValues.h \
    $${PWD}/OAIPlaybackID.h \
    $${PWD}/OAIPlaybackPolicy.h \
    $${PWD}/OAIPlaybackRestriction.h \
    $${PWD}/OAIPlaybackRestrictionResponse.h \
    $${PWD}/OAIRealTimeBreakdownValue.h \
    $${PWD}/OAIRealTimeHistogramTimeseriesBucket.h \
    $${PWD}/OAIRealTimeHistogramTimeseriesBucketValues.h \
    $${PWD}/OAIRealTimeHistogramTimeseriesDatapoint.h \
    $${PWD}/OAIRealTimeTimeseriesDatapoint.h \
    $${PWD}/OAIReferrerDomainRestriction.h \
    $${PWD}/OAIScore.h \
    $${PWD}/OAISignalLiveStreamCompleteResponse.h \
    $${PWD}/OAISigningKey.h \
    $${PWD}/OAISigningKeyResponse.h \
    $${PWD}/OAISimulcastTarget.h \
    $${PWD}/OAISimulcastTargetResponse.h \
    $${PWD}/OAISpace.h \
    $${PWD}/OAISpaceResponse.h \
    $${PWD}/OAISpaceStatus.h \
    $${PWD}/OAISpaceType.h \
    $${PWD}/OAIStartSpaceBroadcastResponse.h \
    $${PWD}/OAIStopSpaceBroadcastResponse.h \
    $${PWD}/OAITrack.h \
    $${PWD}/OAITranscriptionVocabulary.h \
    $${PWD}/OAITranscriptionVocabularyResponse.h \
    $${PWD}/OAIUpdateAssetMP4SupportRequest.h \
    $${PWD}/OAIUpdateAssetMasterAccessRequest.h \
    $${PWD}/OAIUpdateAssetRequest.h \
    $${PWD}/OAIUpdateLiveStreamEmbeddedSubtitlesRequest.h \
    $${PWD}/OAIUpdateLiveStreamGeneratedSubtitlesRequest.h \
    $${PWD}/OAIUpdateLiveStreamRequest.h \
    $${PWD}/OAIUpdateReferrerDomainRestrictionRequest.h \
    $${PWD}/OAIUpdateTranscriptionVocabularyRequest.h \
    $${PWD}/OAIUpload.h \
    $${PWD}/OAIUploadResponse.h \
    $${PWD}/OAIUpload_error.h \
    $${PWD}/OAIVideoView.h \
    $${PWD}/OAIVideoViewEvent.h \
    $${PWD}/OAIVideoViewResponse.h \
# APIs
    $${PWD}/OAIAssetsApi.h \
    $${PWD}/OAIDeliveryUsageApi.h \
    $${PWD}/OAIDimensionsApi.h \
    $${PWD}/OAIDirectUploadsApi.h \
    $${PWD}/OAIErrorsApi.h \
    $${PWD}/OAIExportsApi.h \
    $${PWD}/OAIFiltersApi.h \
    $${PWD}/OAIIncidentsApi.h \
    $${PWD}/OAILiveStreamsApi.h \
    $${PWD}/OAIMetricsApi.h \
    $${PWD}/OAIMonitoringApi.h \
    $${PWD}/OAIPlaybackIDApi.h \
    $${PWD}/OAIPlaybackRestrictionsApi.h \
    $${PWD}/OAIRealTimeApi.h \
    $${PWD}/OAISigningKeysApi.h \
    $${PWD}/OAISpacesApi.h \
    $${PWD}/OAITranscriptionVocabulariesApi.h \
    $${PWD}/OAIURLSigningKeysApi.h \
    $${PWD}/OAIVideoViewsApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAbridgedVideoView.cpp \
    $${PWD}/OAIAsset.cpp \
    $${PWD}/OAIAssetGeneratedSubtitleSettings.cpp \
    $${PWD}/OAIAssetResponse.cpp \
    $${PWD}/OAIAsset_errors.cpp \
    $${PWD}/OAIAsset_master.cpp \
    $${PWD}/OAIAsset_non_standard_input_reasons.cpp \
    $${PWD}/OAIAsset_recording_times_inner.cpp \
    $${PWD}/OAIAsset_static_renditions.cpp \
    $${PWD}/OAIAsset_static_renditions_files_inner.cpp \
    $${PWD}/OAIBreakdownValue.cpp \
    $${PWD}/OAIBroadcast.cpp \
    $${PWD}/OAIBroadcastLayout.cpp \
    $${PWD}/OAIBroadcastResolution.cpp \
    $${PWD}/OAIBroadcastResponse.cpp \
    $${PWD}/OAIBroadcastStatus.cpp \
    $${PWD}/OAICreateAssetRequest.cpp \
    $${PWD}/OAICreateBroadcastRequest.cpp \
    $${PWD}/OAICreateLiveStreamRequest.cpp \
    $${PWD}/OAICreatePlaybackIDRequest.cpp \
    $${PWD}/OAICreatePlaybackIDResponse.cpp \
    $${PWD}/OAICreatePlaybackRestrictionRequest.cpp \
    $${PWD}/OAICreateSimulcastTargetRequest.cpp \
    $${PWD}/OAICreateSpaceRequest.cpp \
    $${PWD}/OAICreateTrackRequest.cpp \
    $${PWD}/OAICreateTrackResponse.cpp \
    $${PWD}/OAICreateTranscriptionVocabularyRequest.cpp \
    $${PWD}/OAICreateUploadRequest.cpp \
    $${PWD}/OAIDeliveryReport.cpp \
    $${PWD}/OAIDeliveryReport_delivered_seconds_by_resolution.cpp \
    $${PWD}/OAIDimensionValue.cpp \
    $${PWD}/OAIDisableLiveStreamResponse.cpp \
    $${PWD}/OAIEnableLiveStreamResponse.cpp \
    $${PWD}/OAIError.cpp \
    $${PWD}/OAIExportDate.cpp \
    $${PWD}/OAIExportFile.cpp \
    $${PWD}/OAIFilterValue.cpp \
    $${PWD}/OAIGetAssetInputInfoResponse.cpp \
    $${PWD}/OAIGetAssetOrLiveStreamIdResponse.cpp \
    $${PWD}/OAIGetAssetOrLiveStreamIdResponse_data.cpp \
    $${PWD}/OAIGetAssetOrLiveStreamIdResponse_data_object.cpp \
    $${PWD}/OAIGetAssetPlaybackIDResponse.cpp \
    $${PWD}/OAIGetLiveStreamPlaybackIDResponse.cpp \
    $${PWD}/OAIGetMetricTimeseriesDataResponse.cpp \
    $${PWD}/OAIGetMonitoringBreakdownResponse.cpp \
    $${PWD}/OAIGetMonitoringBreakdownTimeseriesResponse.cpp \
    $${PWD}/OAIGetMonitoringHistogramTimeseriesResponse.cpp \
    $${PWD}/OAIGetMonitoringHistogramTimeseriesResponse_meta.cpp \
    $${PWD}/OAIGetMonitoringTimeseriesResponse.cpp \
    $${PWD}/OAIGetOverallValuesResponse.cpp \
    $${PWD}/OAIGetRealTimeBreakdownResponse.cpp \
    $${PWD}/OAIGetRealTimeHistogramTimeseriesResponse.cpp \
    $${PWD}/OAIGetRealTimeHistogramTimeseriesResponse_meta.cpp \
    $${PWD}/OAIGetRealTimeTimeseriesResponse.cpp \
    $${PWD}/OAIIncident.cpp \
    $${PWD}/OAIIncidentBreakdown.cpp \
    $${PWD}/OAIIncidentNotification.cpp \
    $${PWD}/OAIIncidentNotificationRule.cpp \
    $${PWD}/OAIIncidentResponse.cpp \
    $${PWD}/OAIInputFile.cpp \
    $${PWD}/OAIInputInfo.cpp \
    $${PWD}/OAIInputSettings.cpp \
    $${PWD}/OAIInputSettings_overlay_settings.cpp \
    $${PWD}/OAIInputTrack.cpp \
    $${PWD}/OAIInsight.cpp \
    $${PWD}/OAIListAllMetricValuesResponse.cpp \
    $${PWD}/OAIListAssetsResponse.cpp \
    $${PWD}/OAIListBreakdownValuesResponse.cpp \
    $${PWD}/OAIListDeliveryUsageResponse.cpp \
    $${PWD}/OAIListDimensionValuesResponse.cpp \
    $${PWD}/OAIListDimensionsResponse.cpp \
    $${PWD}/OAIListDimensionsResponse_data.cpp \
    $${PWD}/OAIListErrorsResponse.cpp \
    $${PWD}/OAIListExportsResponse.cpp \
    $${PWD}/OAIListFilterValuesResponse.cpp \
    $${PWD}/OAIListFiltersResponse.cpp \
    $${PWD}/OAIListIncidentsResponse.cpp \
    $${PWD}/OAIListInsightsResponse.cpp \
    $${PWD}/OAIListLiveStreamsResponse.cpp \
    $${PWD}/OAIListMonitoringDimensionsResponse.cpp \
    $${PWD}/OAIListMonitoringDimensionsResponse_data_inner.cpp \
    $${PWD}/OAIListMonitoringMetricsResponse.cpp \
    $${PWD}/OAIListPlaybackRestrictionsResponse.cpp \
    $${PWD}/OAIListRealTimeDimensionsResponse.cpp \
    $${PWD}/OAIListRealTimeMetricsResponse.cpp \
    $${PWD}/OAIListRelatedIncidentsResponse.cpp \
    $${PWD}/OAIListSigningKeysResponse.cpp \
    $${PWD}/OAIListSpacesResponse.cpp \
    $${PWD}/OAIListTranscriptionVocabulariesResponse.cpp \
    $${PWD}/OAIListUploadsResponse.cpp \
    $${PWD}/OAIListVideoViewExportsResponse.cpp \
    $${PWD}/OAIListVideoViewsResponse.cpp \
    $${PWD}/OAILiveStream.cpp \
    $${PWD}/OAILiveStreamEmbeddedSubtitleSettings.cpp \
    $${PWD}/OAILiveStreamGeneratedSubtitleSettings.cpp \
    $${PWD}/OAILiveStreamResponse.cpp \
    $${PWD}/OAILiveStreamStatus.cpp \
    $${PWD}/OAIMetric.cpp \
    $${PWD}/OAIMonitoringBreakdownTimeseriesDatapoint.cpp \
    $${PWD}/OAIMonitoringBreakdownTimeseriesValues.cpp \
    $${PWD}/OAIMonitoringBreakdownValue.cpp \
    $${PWD}/OAIMonitoringHistogramTimeseriesBucket.cpp \
    $${PWD}/OAIMonitoringHistogramTimeseriesBucketValues.cpp \
    $${PWD}/OAIMonitoringHistogramTimeseriesDatapoint.cpp \
    $${PWD}/OAIMonitoringTimeseriesDatapoint.cpp \
    $${PWD}/OAINotificationRule.cpp \
    $${PWD}/OAIOverallValues.cpp \
    $${PWD}/OAIPlaybackID.cpp \
    $${PWD}/OAIPlaybackPolicy.cpp \
    $${PWD}/OAIPlaybackRestriction.cpp \
    $${PWD}/OAIPlaybackRestrictionResponse.cpp \
    $${PWD}/OAIRealTimeBreakdownValue.cpp \
    $${PWD}/OAIRealTimeHistogramTimeseriesBucket.cpp \
    $${PWD}/OAIRealTimeHistogramTimeseriesBucketValues.cpp \
    $${PWD}/OAIRealTimeHistogramTimeseriesDatapoint.cpp \
    $${PWD}/OAIRealTimeTimeseriesDatapoint.cpp \
    $${PWD}/OAIReferrerDomainRestriction.cpp \
    $${PWD}/OAIScore.cpp \
    $${PWD}/OAISignalLiveStreamCompleteResponse.cpp \
    $${PWD}/OAISigningKey.cpp \
    $${PWD}/OAISigningKeyResponse.cpp \
    $${PWD}/OAISimulcastTarget.cpp \
    $${PWD}/OAISimulcastTargetResponse.cpp \
    $${PWD}/OAISpace.cpp \
    $${PWD}/OAISpaceResponse.cpp \
    $${PWD}/OAISpaceStatus.cpp \
    $${PWD}/OAISpaceType.cpp \
    $${PWD}/OAIStartSpaceBroadcastResponse.cpp \
    $${PWD}/OAIStopSpaceBroadcastResponse.cpp \
    $${PWD}/OAITrack.cpp \
    $${PWD}/OAITranscriptionVocabulary.cpp \
    $${PWD}/OAITranscriptionVocabularyResponse.cpp \
    $${PWD}/OAIUpdateAssetMP4SupportRequest.cpp \
    $${PWD}/OAIUpdateAssetMasterAccessRequest.cpp \
    $${PWD}/OAIUpdateAssetRequest.cpp \
    $${PWD}/OAIUpdateLiveStreamEmbeddedSubtitlesRequest.cpp \
    $${PWD}/OAIUpdateLiveStreamGeneratedSubtitlesRequest.cpp \
    $${PWD}/OAIUpdateLiveStreamRequest.cpp \
    $${PWD}/OAIUpdateReferrerDomainRestrictionRequest.cpp \
    $${PWD}/OAIUpdateTranscriptionVocabularyRequest.cpp \
    $${PWD}/OAIUpload.cpp \
    $${PWD}/OAIUploadResponse.cpp \
    $${PWD}/OAIUpload_error.cpp \
    $${PWD}/OAIVideoView.cpp \
    $${PWD}/OAIVideoViewEvent.cpp \
    $${PWD}/OAIVideoViewResponse.cpp \
# APIs
    $${PWD}/OAIAssetsApi.cpp \
    $${PWD}/OAIDeliveryUsageApi.cpp \
    $${PWD}/OAIDimensionsApi.cpp \
    $${PWD}/OAIDirectUploadsApi.cpp \
    $${PWD}/OAIErrorsApi.cpp \
    $${PWD}/OAIExportsApi.cpp \
    $${PWD}/OAIFiltersApi.cpp \
    $${PWD}/OAIIncidentsApi.cpp \
    $${PWD}/OAILiveStreamsApi.cpp \
    $${PWD}/OAIMetricsApi.cpp \
    $${PWD}/OAIMonitoringApi.cpp \
    $${PWD}/OAIPlaybackIDApi.cpp \
    $${PWD}/OAIPlaybackRestrictionsApi.cpp \
    $${PWD}/OAIRealTimeApi.cpp \
    $${PWD}/OAISigningKeysApi.cpp \
    $${PWD}/OAISpacesApi.cpp \
    $${PWD}/OAITranscriptionVocabulariesApi.cpp \
    $${PWD}/OAIURLSigningKeysApi.cpp \
    $${PWD}/OAIVideoViewsApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
