openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: "Manage properties in Google Analytics. Warning: Creating multiple\
    \ Customer Applications, Accounts, or Projects to simulate or act as a single\
    \ Customer Application, Account, or Project (respectively) or to circumvent Service-specific\
    \ usage limits or quotas is a direct violation of Google Cloud Platform Terms\
    \ of Service as well as Google APIs Terms of Service. These actions can result\
    \ in immediate termination of your GCP project(s) without any warning."
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Google Analytics Admin API
  version: v1alpha
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://upload.wikimedia.org/wikipedia/commons/e/e1/YouTube_play_buttom_icon_%282013-2017%29.svg
  x-origin:
  - format: google
    url: https://analyticsadmin.googleapis.com/$discovery/rest?version=v1alpha
    version: v1
  x-preferred: false
  x-providerName: googleapis.com
  x-serviceName: analyticsadmin
servers:
- url: https://analyticsadmin.googleapis.com/
tags:
- name: accounts
- name: accountSummaries
- name: properties
paths:
  /v1alpha/accountSummaries:
    get:
      description: Returns summaries of all accounts accessible by the caller.
      operationId: analyticsadmin.accountSummaries.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - accountSummaries
      x-accepts:
      - application/json
  /v1alpha/accounts:
    get:
      description: "Returns all accounts accessible by the caller. Note that these\
        \ accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\"\
        ) accounts are excluded by default. Returns an empty list if no relevant accounts\
        \ are found."
      operationId: analyticsadmin.accounts.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - accounts
      x-accepts:
      - application/json
  /v1alpha/accounts:provisionAccountTicket:
    post:
      description: Requests a ticket for creating an account.
      operationId: analyticsadmin.accounts.provisionAccountTicket
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - accounts
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/properties:
    get:
      description: "Returns child Properties under the specified parent Account. Only\
        \ \"GA4\" properties will be returned. Properties will be excluded if the\
        \ caller does not have access. Soft-deleted (ie: \"trashed\") properties are\
        \ excluded by default. Returns an empty list if no relevant properties are\
        \ found."
      operationId: analyticsadmin.properties.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-accepts:
      - application/json
    post:
      description: Creates an "GA4" property with the specified location and attributes.
      operationId: analyticsadmin.properties.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/properties:createConnectedSiteTag:
    post:
      description: "Creates a connected site tag for a Universal Analytics property.\
        \ You can create a maximum of 20 connected site tags per property. Note: This\
        \ API cannot be used on GA4 properties."
      operationId: analyticsadmin.properties.createConnectedSiteTag
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/properties:createRollupProperty:
    post:
      description: Create a roll-up property and all roll-up property source links.
      operationId: analyticsadmin.properties.createRollupProperty
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/properties:createSubproperty:
    post:
      description: Create a subproperty and a subproperty event filter that applies
        to the created subproperty.
      operationId: analyticsadmin.properties.createSubproperty
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/properties:deleteConnectedSiteTag:
    post:
      description: "Deletes a connected site tag for a Universal Analytics property.\
        \ Note: this has no effect on GA4 properties."
      operationId: analyticsadmin.properties.deleteConnectedSiteTag
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/properties:fetchAutomatedGa4ConfigurationOptOut:
    post:
      description: "Fetches the opt out status for the automated GA4 setup process\
        \ for a UA property. Note: this has no effect on GA4 property."
      operationId: analyticsadmin.properties.fetchAutomatedGa4ConfigurationOptOut
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/properties:fetchConnectedGa4Property:
    get:
      description: "Given a specified UA property, looks up the GA4 property connected\
        \ to it. Note: this cannot be used with GA4 properties."
      operationId: analyticsadmin.properties.fetchConnectedGa4Property
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-accepts:
      - application/json
  /v1alpha/properties:listConnectedSiteTags:
    post:
      description: "Lists the connected site tags for a Universal Analytics property.\
        \ A maximum of 20 connected site tags will be returned. Note: this has no\
        \ effect on GA4 property."
      operationId: analyticsadmin.properties.listConnectedSiteTags
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/properties:setAutomatedGa4ConfigurationOptOut:
    post:
      description: "Sets the opt out status for the automated GA4 setup process for\
        \ a UA property. Note: this has no effect on GA4 property."
      operationId: analyticsadmin.properties.setAutomatedGa4ConfigurationOptOut
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{account}:searchChangeHistoryEvents:
    post:
      description: Searches through all changes to an account or its children given
        the specified set of filters.
      operationId: analyticsadmin.accounts.searchChangeHistoryEvents
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - accounts
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{entity}:runAccessReport:
    post:
      description: "Returns a customized report of data access records. The report\
        \ provides records of each time a user reads Google Analytics reporting data.\
        \ Access records are retained for up to 2 years. Data Access Reports can be\
        \ requested for a property. Reports may be requested for any property, but\
        \ dimensions that aren't related to quota can only be requested on Google\
        \ Analytics 360 properties. This method is only available to Administrators.\
        \ These data access records include GA4 UI Reporting, GA4 UI Explorations,\
        \ GA4 Data API, and other products like Firebase & Admob that can retrieve\
        \ data from Google Analytics through a linkage. These records don't include\
        \ property configuration changes like adding a stream or changing a property's\
        \ time zone. For configuration change history, see [searchChangeHistoryEvents](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/accounts/searchChangeHistoryEvents)."
      operationId: analyticsadmin.properties.runAccessReport
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{name}:
    delete:
      description: Deletes a subproperty event filter.
      operationId: analyticsadmin.properties.subpropertyEventFilters.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-accepts:
      - application/json
    get:
      description: Lookup for a single subproperty Event Filter.
      operationId: analyticsadmin.properties.subpropertyEventFilters.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-accepts:
      - application/json
    patch:
      description: Updates a subproperty Event Filter.
      operationId: analyticsadmin.properties.subpropertyEventFilters.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{name}:approve:
    post:
      description: Approves a DisplayVideo360AdvertiserLinkProposal. The DisplayVideo360AdvertiserLinkProposal
        will be deleted and a new DisplayVideo360AdvertiserLink will be created.
      operationId: analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.approve
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{name}:archive:
    post:
      description: Archives a CustomMetric on a property.
      operationId: analyticsadmin.properties.customMetrics.archive
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{name}:cancel:
    post:
      description: "Cancels a DisplayVideo360AdvertiserLinkProposal. Cancelling can\
        \ mean either: - Declining a proposal initiated from Display & Video 360 -\
        \ Withdrawing a proposal initiated from Google Analytics After being cancelled,\
        \ a proposal will eventually be deleted automatically."
      operationId: analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.cancel
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{parent}/accessBindings:
    get:
      description: Lists all access bindings on an account or property.
      operationId: analyticsadmin.properties.accessBindings.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.manage.users
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.manage.users.readonly
      tags:
      - properties
      x-accepts:
      - application/json
    post:
      description: Creates an access binding on an account or property.
      operationId: analyticsadmin.properties.accessBindings.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.manage.users
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{parent}/accessBindings:batchCreate:
    post:
      description: "Creates information about multiple access bindings to an account\
        \ or property. This method is transactional. If any AccessBinding cannot be\
        \ created, none of the AccessBindings will be created."
      operationId: analyticsadmin.properties.accessBindings.batchCreate
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.manage.users
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{parent}/accessBindings:batchDelete:
    post:
      description: Deletes information about multiple users' links to an account or
        property.
      operationId: analyticsadmin.properties.accessBindings.batchDelete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.manage.users
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{parent}/accessBindings:batchGet:
    get:
      description: Gets information about multiple access bindings to an account or
        property.
      operationId: analyticsadmin.properties.accessBindings.batchGet
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.manage.users
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.manage.users.readonly
      tags:
      - properties
      x-accepts:
      - application/json
  /v1alpha/{parent}/accessBindings:batchUpdate:
    post:
      description: Updates information about multiple access bindings to an account
        or property.
      operationId: analyticsadmin.properties.accessBindings.batchUpdate
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.manage.users
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{parent}/adSenseLinks:
    get:
      description: Lists AdSenseLinks on a property.
      operationId: analyticsadmin.properties.adSenseLinks.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-accepts:
      - application/json
    post:
      description: Creates an AdSenseLink.
      operationId: analyticsadmin.properties.adSenseLinks.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{parent}/audiences:
    get:
      description: Lists Audiences on a property. Audiences created before 2020 may
        not be supported. Default audiences will not show filter definitions.
      operationId: analyticsadmin.properties.audiences.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-accepts:
      - application/json
    post:
      description: Creates an Audience.
      operationId: analyticsadmin.properties.audiences.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{parent}/bigQueryLinks:
    get:
      description: Lists BigQuery Links on a property.
      operationId: analyticsadmin.properties.bigQueryLinks.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-accepts:
      - application/json
  /v1alpha/{parent}/calculatedMetrics:
    get:
      description: Lists CalculatedMetrics on a property.
      operationId: analyticsadmin.properties.calculatedMetrics.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-accepts:
      - application/json
    post:
      description: Creates a CalculatedMetric.
      operationId: analyticsadmin.properties.calculatedMetrics.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{parent}/channelGroups:
    get:
      description: Lists ChannelGroups on a property.
      operationId: analyticsadmin.properties.channelGroups.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-accepts:
      - application/json
    post:
      description: Creates a ChannelGroup.
      operationId: analyticsadmin.properties.channelGroups.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{parent}/conversionEvents:
    get:
      description: Returns a list of conversion events in the specified parent property.
        Returns an empty list if no conversion events are found.
      operationId: analyticsadmin.properties.conversionEvents.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-accepts:
      - application/json
    post:
      description: Creates a conversion event with the specified attributes.
      operationId: analyticsadmin.properties.conversionEvents.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{parent}/customDimensions:
    get:
      description: Lists CustomDimensions on a property.
      operationId: analyticsadmin.properties.customDimensions.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-accepts:
      - application/json
    post:
      description: Creates a CustomDimension.
      operationId: analyticsadmin.properties.customDimensions.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{parent}/customMetrics:
    get:
      description: Lists CustomMetrics on a property.
      operationId: analyticsadmin.properties.customMetrics.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-accepts:
      - application/json
    post:
      description: Creates a CustomMetric.
      operationId: analyticsadmin.properties.customMetrics.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{parent}/dataStreams:
    get:
      description: Lists DataStreams on a property.
      operationId: analyticsadmin.properties.dataStreams.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-accepts:
      - application/json
    post:
      description: Creates a DataStream.
      operationId: analyticsadmin.properties.dataStreams.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{parent}/displayVideo360AdvertiserLinkProposals:
    get:
      description: Lists DisplayVideo360AdvertiserLinkProposals on a property.
      operationId: analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-accepts:
      - application/json
    post:
      description: Creates a DisplayVideo360AdvertiserLinkProposal.
      operationId: analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{parent}/displayVideo360AdvertiserLinks:
    get:
      description: Lists all DisplayVideo360AdvertiserLinks on a property.
      operationId: analyticsadmin.properties.displayVideo360AdvertiserLinks.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-accepts:
      - application/json
    post:
      description: Creates a DisplayVideo360AdvertiserLink. This can only be utilized
        by users who have proper authorization both on the Google Analytics property
        and on the Display & Video 360 advertiser. Users who do not have access to
        the Display & Video 360 advertiser should instead seek to create a DisplayVideo360LinkProposal.
      operationId: analyticsadmin.properties.displayVideo360AdvertiserLinks.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{parent}/eventCreateRules:
    get:
      description: Lists EventCreateRules on a web data stream.
      operationId: analyticsadmin.properties.dataStreams.eventCreateRules.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-accepts:
      - application/json
    post:
      description: Creates an EventCreateRule.
      operationId: analyticsadmin.properties.dataStreams.eventCreateRules.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{parent}/expandedDataSets:
    get:
      description: Lists ExpandedDataSets on a property.
      operationId: analyticsadmin.properties.expandedDataSets.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-accepts:
      - application/json
    post:
      description: Creates a ExpandedDataSet.
      operationId: analyticsadmin.properties.expandedDataSets.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{parent}/firebaseLinks:
    get:
      description: Lists FirebaseLinks on a property. Properties can have at most
        one FirebaseLink.
      operationId: analyticsadmin.properties.firebaseLinks.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-accepts:
      - application/json
    post:
      description: Creates a FirebaseLink. Properties can have at most one FirebaseLink.
      operationId: analyticsadmin.properties.firebaseLinks.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{parent}/googleAdsLinks:
    get:
      description: Lists GoogleAdsLinks on a property.
      operationId: analyticsadmin.properties.googleAdsLinks.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-accepts:
      - application/json
    post:
      description: Creates a GoogleAdsLink.
      operationId: analyticsadmin.properties.googleAdsLinks.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{parent}/measurementProtocolSecrets:
    get:
      description: Returns child MeasurementProtocolSecrets under the specified parent
        Property.
      operationId: analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-accepts:
      - application/json
    post:
      description: Creates a measurement protocol secret.
      operationId: analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{parent}/rollupPropertySourceLinks:
    get:
      description: "Lists roll-up property source Links on a property. Only roll-up\
        \ properties can have source links, so this method will throw an error if\
        \ used on other types of properties."
      operationId: analyticsadmin.properties.rollupPropertySourceLinks.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-accepts:
      - application/json
    post:
      description: "Creates a roll-up property source link. Only roll-up properties\
        \ can have source links, so this method will throw an error if used on other\
        \ types of properties."
      operationId: analyticsadmin.properties.rollupPropertySourceLinks.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{parent}/sKAdNetworkConversionValueSchema:
    get:
      description: Lists SKAdNetworkConversionValueSchema on a stream. Properties
        can have at most one SKAdNetworkConversionValueSchema.
      operationId: analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-accepts:
      - application/json
    post:
      description: Creates a SKAdNetworkConversionValueSchema.
      operationId: analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{parent}/searchAds360Links:
    get:
      description: Lists all SearchAds360Links on a property.
      operationId: analyticsadmin.properties.searchAds360Links.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-accepts:
      - application/json
    post:
      description: Creates a SearchAds360Link.
      operationId: analyticsadmin.properties.searchAds360Links.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{parent}/subpropertyEventFilters:
    get:
      description: List all subproperty Event Filters on a property.
      operationId: analyticsadmin.properties.subpropertyEventFilters.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-accepts:
      - application/json
    post:
      description: Creates a subproperty Event Filter.
      operationId: analyticsadmin.properties.subpropertyEventFilters.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1alpha/{property}:acknowledgeUserDataCollection:
    post:
      description: Acknowledges the terms of user data collection for the specified
        property. This acknowledgement must be completed (either in the Google Analytics
        UI or through this API) before MeasurementProtocolSecret resources may be
        created.
      operationId: analyticsadmin.properties.acknowledgeUserDataCollection
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/analytics.edit: Edit Google Analytics
              management entities
            https://www.googleapis.com/auth/analytics.manage.users: Manage Google
              Analytics Account users by email address
            https://www.googleapis.com/auth/analytics.manage.users.readonly: View
              Google Analytics user permissions
            https://www.googleapis.com/auth/analytics.readonly: See and download your
              Google Analytics data
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/analytics.edit: Edit Google Analytics
              management entities
            https://www.googleapis.com/auth/analytics.manage.users: Manage Google
              Analytics Account users by email address
            https://www.googleapis.com/auth/analytics.manage.users.readonly: View
              Google Analytics user permissions
            https://www.googleapis.com/auth/analytics.readonly: See and download your
              Google Analytics data
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2

