QT += network

HEADERS += \
# Models
    $${PWD}/OAIAnalysisCompleted.h \
    $${PWD}/OAIArtifact.h \
    $${PWD}/OAIAssessment.h \
    $${PWD}/OAIAttestation.h \
    $${PWD}/OAIAttestationAuthority.h \
    $${PWD}/OAIAttestationAuthorityHint.h \
    $${PWD}/OAIBasis.h \
    $${PWD}/OAIBinding.h \
    $${PWD}/OAIBuildDefinition.h \
    $${PWD}/OAIBuildDetails.h \
    $${PWD}/OAIBuildMetadata.h \
    $${PWD}/OAIBuildProvenance.h \
    $${PWD}/OAIBuildSignature.h \
    $${PWD}/OAIBuildStep.h \
    $${PWD}/OAIBuildType.h \
    $${PWD}/OAIBuilderConfig.h \
    $${PWD}/OAICVSS.h \
    $${PWD}/OAICisBenchmark.h \
    $${PWD}/OAICommand.h \
    $${PWD}/OAICompleteness.h \
    $${PWD}/OAIComplianceNote.h \
    $${PWD}/OAIComplianceOccurrence.h \
    $${PWD}/OAIComplianceVersion.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1ApprovalConfig.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1ApprovalResult.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1Artifacts.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1ArtifactsArtifactObjects.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1ArtifactsMavenArtifact.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1ArtifactsNpmPackage.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1ArtifactsPythonPackage.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1Build.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1BuildApproval.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1BuildFailureInfo.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1BuildOptions.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1BuildOptionsPoolOption.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1BuildStep.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1BuildWarning.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1BuiltImage.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1ConnectedRepository.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1FileHashes.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1GitSource.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1Hash.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1InlineSecret.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1RepoSource.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1Results.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1Secret.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1SecretManagerSecret.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1Secrets.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1Source.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1SourceProvenance.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1StorageSource.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1StorageSourceManifest.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1TimeSpan.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1UploadedMavenArtifact.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1UploadedNpmPackage.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1UploadedPythonPackage.h \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1Volume.h \
    $${PWD}/OAICreateOperationRequest.h \
    $${PWD}/OAIDSSEAttestationNote.h \
    $${PWD}/OAIDSSEAttestationOccurrence.h \
    $${PWD}/OAIDSSEHint.h \
    $${PWD}/OAIDeployable.h \
    $${PWD}/OAIDeployment.h \
    $${PWD}/OAIDerived.h \
    $${PWD}/OAIDetail.h \
    $${PWD}/OAIDigest.h \
    $${PWD}/OAIDiscovered.h \
    $${PWD}/OAIDiscovery.h \
    $${PWD}/OAIDistribution.h \
    $${PWD}/OAIDocumentNote.h \
    $${PWD}/OAIDocumentOccurrence.h \
    $${PWD}/OAIEnvelope.h \
    $${PWD}/OAIEnvelopeSignature.h \
    $${PWD}/OAIExpr.h \
    $${PWD}/OAIExternalRef.h \
    $${PWD}/OAIFileHashes.h \
    $${PWD}/OAIFileLocation.h \
    $${PWD}/OAIFileNote.h \
    $${PWD}/OAIFileOccurrence.h \
    $${PWD}/OAIFingerprint.h \
    $${PWD}/OAIGetIamPolicyRequest.h \
    $${PWD}/OAIGetPolicyOptions.h \
    $${PWD}/OAIGetVulnzOccurrencesSummaryResponse.h \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1AliasContext.h \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1CloudRepoSourceContext.h \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1GerritSourceContext.h \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1GitSourceContext.h \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1OperationMetadata.h \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1ProjectRepoId.h \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1RepoId.h \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1SlsaProvenanceZeroTwoSlsaBuilder.h \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1SlsaProvenanceZeroTwoSlsaCompleteness.h \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1SlsaProvenanceZeroTwoSlsaConfigSource.h \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1SlsaProvenanceZeroTwoSlsaInvocation.h \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1SlsaProvenanceZeroTwoSlsaMaterial.h \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1SlsaProvenanceZeroTwoSlsaMetadata.h \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1SourceContext.h \
    $${PWD}/OAIHash.h \
    $${PWD}/OAIIdentifierHelper.h \
    $${PWD}/OAIInTotoProvenance.h \
    $${PWD}/OAIInTotoSlsaProvenanceV1.h \
    $${PWD}/OAIInTotoStatement.h \
    $${PWD}/OAIInstallation.h \
    $${PWD}/OAIJustification.h \
    $${PWD}/OAILayer.h \
    $${PWD}/OAILicense.h \
    $${PWD}/OAIListNoteOccurrencesResponse.h \
    $${PWD}/OAIListNotesResponse.h \
    $${PWD}/OAIListOccurrencesResponse.h \
    $${PWD}/OAIListScanConfigsResponse.h \
    $${PWD}/OAILocation.h \
    $${PWD}/OAIMaterial.h \
    $${PWD}/OAIMetadata.h \
    $${PWD}/OAINonCompliantFile.h \
    $${PWD}/OAINote.h \
    $${PWD}/OAIOccurrence.h \
    $${PWD}/OAIOperation.h \
    $${PWD}/OAIPackage.h \
    $${PWD}/OAIPackageInfoNote.h \
    $${PWD}/OAIPackageInfoOccurrence.h \
    $${PWD}/OAIPackageIssue.h \
    $${PWD}/OAIPgpSignedAttestation.h \
    $${PWD}/OAIPolicy.h \
    $${PWD}/OAIProduct.h \
    $${PWD}/OAIProvenanceBuilder.h \
    $${PWD}/OAIPublisher.h \
    $${PWD}/OAIRecipe.h \
    $${PWD}/OAIRelatedUrl.h \
    $${PWD}/OAIRelationshipNote.h \
    $${PWD}/OAIRelationshipOccurrence.h \
    $${PWD}/OAIRemediation.h \
    $${PWD}/OAIRepoSource.h \
    $${PWD}/OAIResource.h \
    $${PWD}/OAIResourceDescriptor.h \
    $${PWD}/OAIRunDetails.h \
    $${PWD}/OAISBOMReferenceNote.h \
    $${PWD}/OAISBOMReferenceOccurrence.h \
    $${PWD}/OAISBOMStatus.h \
    $${PWD}/OAISbomReferenceIntotoPayload.h \
    $${PWD}/OAISbomReferenceIntotoPredicate.h \
    $${PWD}/OAIScanConfig.h \
    $${PWD}/OAISetIamPolicyRequest.h \
    $${PWD}/OAISeverityCount.h \
    $${PWD}/OAISlsaBuilder.h \
    $${PWD}/OAISlsaCompleteness.h \
    $${PWD}/OAISlsaMetadata.h \
    $${PWD}/OAISlsaProvenance.h \
    $${PWD}/OAISlsaProvenanceV1.h \
    $${PWD}/OAISlsaProvenanceZeroTwo.h \
    $${PWD}/OAISlsaRecipe.h \
    $${PWD}/OAISource.h \
    $${PWD}/OAIStatus.h \
    $${PWD}/OAIStorageSource.h \
    $${PWD}/OAISubject.h \
    $${PWD}/OAITestIamPermissionsRequest.h \
    $${PWD}/OAITestIamPermissionsResponse.h \
    $${PWD}/OAITimeSpan.h \
    $${PWD}/OAIUpdateOperationRequest.h \
    $${PWD}/OAIUpgradeDistribution.h \
    $${PWD}/OAIUpgradeNote.h \
    $${PWD}/OAIUpgradeOccurrence.h \
    $${PWD}/OAIVersion.h \
    $${PWD}/OAIVexAssessment.h \
    $${PWD}/OAIVolume.h \
    $${PWD}/OAIVulnerabilityAssessmentNote.h \
    $${PWD}/OAIVulnerabilityDetails.h \
    $${PWD}/OAIVulnerabilityLocation.h \
    $${PWD}/OAIVulnerabilityType.h \
    $${PWD}/URI.h \
# APIs
    $${PWD}/OAIProjectsApi.h \
    $${PWD}/OAIProvidersApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAnalysisCompleted.cpp \
    $${PWD}/OAIArtifact.cpp \
    $${PWD}/OAIAssessment.cpp \
    $${PWD}/OAIAttestation.cpp \
    $${PWD}/OAIAttestationAuthority.cpp \
    $${PWD}/OAIAttestationAuthorityHint.cpp \
    $${PWD}/OAIBasis.cpp \
    $${PWD}/OAIBinding.cpp \
    $${PWD}/OAIBuildDefinition.cpp \
    $${PWD}/OAIBuildDetails.cpp \
    $${PWD}/OAIBuildMetadata.cpp \
    $${PWD}/OAIBuildProvenance.cpp \
    $${PWD}/OAIBuildSignature.cpp \
    $${PWD}/OAIBuildStep.cpp \
    $${PWD}/OAIBuildType.cpp \
    $${PWD}/OAIBuilderConfig.cpp \
    $${PWD}/OAICVSS.cpp \
    $${PWD}/OAICisBenchmark.cpp \
    $${PWD}/OAICommand.cpp \
    $${PWD}/OAICompleteness.cpp \
    $${PWD}/OAIComplianceNote.cpp \
    $${PWD}/OAIComplianceOccurrence.cpp \
    $${PWD}/OAIComplianceVersion.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1ApprovalConfig.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1ApprovalResult.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1Artifacts.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1ArtifactsArtifactObjects.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1ArtifactsMavenArtifact.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1ArtifactsNpmPackage.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1ArtifactsPythonPackage.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1Build.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1BuildApproval.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1BuildFailureInfo.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1BuildOptions.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1BuildOptionsPoolOption.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1BuildStep.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1BuildWarning.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1BuiltImage.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1ConnectedRepository.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1FileHashes.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1GitSource.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1Hash.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1InlineSecret.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1RepoSource.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1Results.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1Secret.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1SecretManagerSecret.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1Secrets.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1Source.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1SourceProvenance.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1StorageSource.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1StorageSourceManifest.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1TimeSpan.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1UploadedMavenArtifact.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1UploadedNpmPackage.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1UploadedPythonPackage.cpp \
    $${PWD}/OAIContaineranalysisGoogleDevtoolsCloudbuildV1Volume.cpp \
    $${PWD}/OAICreateOperationRequest.cpp \
    $${PWD}/OAIDSSEAttestationNote.cpp \
    $${PWD}/OAIDSSEAttestationOccurrence.cpp \
    $${PWD}/OAIDSSEHint.cpp \
    $${PWD}/OAIDeployable.cpp \
    $${PWD}/OAIDeployment.cpp \
    $${PWD}/OAIDerived.cpp \
    $${PWD}/OAIDetail.cpp \
    $${PWD}/OAIDigest.cpp \
    $${PWD}/OAIDiscovered.cpp \
    $${PWD}/OAIDiscovery.cpp \
    $${PWD}/OAIDistribution.cpp \
    $${PWD}/OAIDocumentNote.cpp \
    $${PWD}/OAIDocumentOccurrence.cpp \
    $${PWD}/OAIEnvelope.cpp \
    $${PWD}/OAIEnvelopeSignature.cpp \
    $${PWD}/OAIExpr.cpp \
    $${PWD}/OAIExternalRef.cpp \
    $${PWD}/OAIFileHashes.cpp \
    $${PWD}/OAIFileLocation.cpp \
    $${PWD}/OAIFileNote.cpp \
    $${PWD}/OAIFileOccurrence.cpp \
    $${PWD}/OAIFingerprint.cpp \
    $${PWD}/OAIGetIamPolicyRequest.cpp \
    $${PWD}/OAIGetPolicyOptions.cpp \
    $${PWD}/OAIGetVulnzOccurrencesSummaryResponse.cpp \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1AliasContext.cpp \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1CloudRepoSourceContext.cpp \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1GerritSourceContext.cpp \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1GitSourceContext.cpp \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1OperationMetadata.cpp \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1ProjectRepoId.cpp \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1RepoId.cpp \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1SlsaProvenanceZeroTwoSlsaBuilder.cpp \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1SlsaProvenanceZeroTwoSlsaCompleteness.cpp \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1SlsaProvenanceZeroTwoSlsaConfigSource.cpp \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1SlsaProvenanceZeroTwoSlsaInvocation.cpp \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1SlsaProvenanceZeroTwoSlsaMaterial.cpp \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1SlsaProvenanceZeroTwoSlsaMetadata.cpp \
    $${PWD}/OAIGoogleDevtoolsContaineranalysisV1alpha1SourceContext.cpp \
    $${PWD}/OAIHash.cpp \
    $${PWD}/OAIIdentifierHelper.cpp \
    $${PWD}/OAIInTotoProvenance.cpp \
    $${PWD}/OAIInTotoSlsaProvenanceV1.cpp \
    $${PWD}/OAIInTotoStatement.cpp \
    $${PWD}/OAIInstallation.cpp \
    $${PWD}/OAIJustification.cpp \
    $${PWD}/OAILayer.cpp \
    $${PWD}/OAILicense.cpp \
    $${PWD}/OAIListNoteOccurrencesResponse.cpp \
    $${PWD}/OAIListNotesResponse.cpp \
    $${PWD}/OAIListOccurrencesResponse.cpp \
    $${PWD}/OAIListScanConfigsResponse.cpp \
    $${PWD}/OAILocation.cpp \
    $${PWD}/OAIMaterial.cpp \
    $${PWD}/OAIMetadata.cpp \
    $${PWD}/OAINonCompliantFile.cpp \
    $${PWD}/OAINote.cpp \
    $${PWD}/OAIOccurrence.cpp \
    $${PWD}/OAIOperation.cpp \
    $${PWD}/OAIPackage.cpp \
    $${PWD}/OAIPackageInfoNote.cpp \
    $${PWD}/OAIPackageInfoOccurrence.cpp \
    $${PWD}/OAIPackageIssue.cpp \
    $${PWD}/OAIPgpSignedAttestation.cpp \
    $${PWD}/OAIPolicy.cpp \
    $${PWD}/OAIProduct.cpp \
    $${PWD}/OAIProvenanceBuilder.cpp \
    $${PWD}/OAIPublisher.cpp \
    $${PWD}/OAIRecipe.cpp \
    $${PWD}/OAIRelatedUrl.cpp \
    $${PWD}/OAIRelationshipNote.cpp \
    $${PWD}/OAIRelationshipOccurrence.cpp \
    $${PWD}/OAIRemediation.cpp \
    $${PWD}/OAIRepoSource.cpp \
    $${PWD}/OAIResource.cpp \
    $${PWD}/OAIResourceDescriptor.cpp \
    $${PWD}/OAIRunDetails.cpp \
    $${PWD}/OAISBOMReferenceNote.cpp \
    $${PWD}/OAISBOMReferenceOccurrence.cpp \
    $${PWD}/OAISBOMStatus.cpp \
    $${PWD}/OAISbomReferenceIntotoPayload.cpp \
    $${PWD}/OAISbomReferenceIntotoPredicate.cpp \
    $${PWD}/OAIScanConfig.cpp \
    $${PWD}/OAISetIamPolicyRequest.cpp \
    $${PWD}/OAISeverityCount.cpp \
    $${PWD}/OAISlsaBuilder.cpp \
    $${PWD}/OAISlsaCompleteness.cpp \
    $${PWD}/OAISlsaMetadata.cpp \
    $${PWD}/OAISlsaProvenance.cpp \
    $${PWD}/OAISlsaProvenanceV1.cpp \
    $${PWD}/OAISlsaProvenanceZeroTwo.cpp \
    $${PWD}/OAISlsaRecipe.cpp \
    $${PWD}/OAISource.cpp \
    $${PWD}/OAIStatus.cpp \
    $${PWD}/OAIStorageSource.cpp \
    $${PWD}/OAISubject.cpp \
    $${PWD}/OAITestIamPermissionsRequest.cpp \
    $${PWD}/OAITestIamPermissionsResponse.cpp \
    $${PWD}/OAITimeSpan.cpp \
    $${PWD}/OAIUpdateOperationRequest.cpp \
    $${PWD}/OAIUpgradeDistribution.cpp \
    $${PWD}/OAIUpgradeNote.cpp \
    $${PWD}/OAIUpgradeOccurrence.cpp \
    $${PWD}/OAIVersion.cpp \
    $${PWD}/OAIVexAssessment.cpp \
    $${PWD}/OAIVolume.cpp \
    $${PWD}/OAIVulnerabilityAssessmentNote.cpp \
    $${PWD}/OAIVulnerabilityDetails.cpp \
    $${PWD}/OAIVulnerabilityLocation.cpp \
    $${PWD}/OAIVulnerabilityType.cpp \
    $${PWD}/URI.cpp \
# APIs
    $${PWD}/OAIProjectsApi.cpp \
    $${PWD}/OAIProvidersApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
