QT += network

HEADERS += \
# Models
    $${PWD}/OAIAccountRecoverySettingType.h \
    $${PWD}/OAIAccountTakeoverActionType.h \
    $${PWD}/OAIAccountTakeoverActionsType.h \
    $${PWD}/OAIAccountTakeoverActionsType_HighAction.h \
    $${PWD}/OAIAccountTakeoverActionsType_LowAction.h \
    $${PWD}/OAIAccountTakeoverActionsType_MediumAction.h \
    $${PWD}/OAIAccountTakeoverEventActionType.h \
    $${PWD}/OAIAccountTakeoverRiskConfigurationType.h \
    $${PWD}/OAIAccountTakeoverRiskConfigurationType_Actions.h \
    $${PWD}/OAIAccountTakeoverRiskConfigurationType_NotifyConfiguration.h \
    $${PWD}/OAIAddCustomAttributesRequest.h \
    $${PWD}/OAIAdminAddUserToGroupRequest.h \
    $${PWD}/OAIAdminConfirmSignUpRequest.h \
    $${PWD}/OAIAdminCreateUserConfigType.h \
    $${PWD}/OAIAdminCreateUserConfigType_InviteMessageTemplate.h \
    $${PWD}/OAIAdminCreateUserRequest.h \
    $${PWD}/OAIAdminCreateUserResponse.h \
    $${PWD}/OAIAdminCreateUserResponse_User.h \
    $${PWD}/OAIAdminDeleteUserAttributesRequest.h \
    $${PWD}/OAIAdminDeleteUserRequest.h \
    $${PWD}/OAIAdminDisableProviderForUserRequest.h \
    $${PWD}/OAIAdminDisableProviderForUserRequest_User.h \
    $${PWD}/OAIAdminDisableUserRequest.h \
    $${PWD}/OAIAdminEnableUserRequest.h \
    $${PWD}/OAIAdminForgetDeviceRequest.h \
    $${PWD}/OAIAdminGetDeviceRequest.h \
    $${PWD}/OAIAdminGetDeviceResponse.h \
    $${PWD}/OAIAdminGetDeviceResponse_Device.h \
    $${PWD}/OAIAdminGetUserRequest.h \
    $${PWD}/OAIAdminGetUserResponse.h \
    $${PWD}/OAIAdminInitiateAuthRequest.h \
    $${PWD}/OAIAdminInitiateAuthRequest_AnalyticsMetadata.h \
    $${PWD}/OAIAdminInitiateAuthRequest_ContextData.h \
    $${PWD}/OAIAdminInitiateAuthResponse.h \
    $${PWD}/OAIAdminInitiateAuthResponse_AuthenticationResult.h \
    $${PWD}/OAIAdminLinkProviderForUserRequest.h \
    $${PWD}/OAIAdminLinkProviderForUserRequest_DestinationUser.h \
    $${PWD}/OAIAdminLinkProviderForUserRequest_SourceUser.h \
    $${PWD}/OAIAdminListDevicesRequest.h \
    $${PWD}/OAIAdminListDevicesResponse.h \
    $${PWD}/OAIAdminListGroupsForUserRequest.h \
    $${PWD}/OAIAdminListGroupsForUserResponse.h \
    $${PWD}/OAIAdminListUserAuthEventsRequest.h \
    $${PWD}/OAIAdminListUserAuthEventsResponse.h \
    $${PWD}/OAIAdminRemoveUserFromGroupRequest.h \
    $${PWD}/OAIAdminResetUserPasswordRequest.h \
    $${PWD}/OAIAdminRespondToAuthChallengeRequest.h \
    $${PWD}/OAIAdminRespondToAuthChallengeRequest_AnalyticsMetadata.h \
    $${PWD}/OAIAdminRespondToAuthChallengeResponse.h \
    $${PWD}/OAIAdminRespondToAuthChallengeResponse_AuthenticationResult.h \
    $${PWD}/OAIAdminSetUserMFAPreferenceRequest.h \
    $${PWD}/OAIAdminSetUserMFAPreferenceRequest_SMSMfaSettings.h \
    $${PWD}/OAIAdminSetUserMFAPreferenceRequest_SoftwareTokenMfaSettings.h \
    $${PWD}/OAIAdminSetUserPasswordRequest.h \
    $${PWD}/OAIAdminSetUserSettingsRequest.h \
    $${PWD}/OAIAdminUpdateAuthEventFeedbackRequest.h \
    $${PWD}/OAIAdminUpdateDeviceStatusRequest.h \
    $${PWD}/OAIAdminUpdateUserAttributesRequest.h \
    $${PWD}/OAIAdminUserGlobalSignOutRequest.h \
    $${PWD}/OAIAdvancedSecurityModeType.h \
    $${PWD}/OAIAliasAttributeType.h \
    $${PWD}/OAIAnalyticsConfigurationType.h \
    $${PWD}/OAIAnalyticsMetadataType.h \
    $${PWD}/OAIAssociateSoftwareTokenRequest.h \
    $${PWD}/OAIAssociateSoftwareTokenResponse.h \
    $${PWD}/OAIAttributeDataType.h \
    $${PWD}/OAIAttributeType.h \
    $${PWD}/OAIAuthEventType.h \
    $${PWD}/OAIAuthEventType_EventContextData.h \
    $${PWD}/OAIAuthEventType_EventFeedback.h \
    $${PWD}/OAIAuthEventType_EventRisk.h \
    $${PWD}/OAIAuthFlowType.h \
    $${PWD}/OAIAuthenticationResultType.h \
    $${PWD}/OAIAuthenticationResultType_NewDeviceMetadata.h \
    $${PWD}/OAIChallengeName.h \
    $${PWD}/OAIChallengeNameType.h \
    $${PWD}/OAIChallengeResponse.h \
    $${PWD}/OAIChallengeResponseType.h \
    $${PWD}/OAIChangePasswordRequest.h \
    $${PWD}/OAICloudWatchLogsConfigurationType.h \
    $${PWD}/OAICodeDeliveryDetailsType.h \
    $${PWD}/OAICompromisedCredentialsActionsType.h \
    $${PWD}/OAICompromisedCredentialsEventActionType.h \
    $${PWD}/OAICompromisedCredentialsRiskConfigurationType.h \
    $${PWD}/OAICompromisedCredentialsRiskConfigurationType_Actions.h \
    $${PWD}/OAIConfirmDeviceRequest.h \
    $${PWD}/OAIConfirmDeviceRequest_DeviceSecretVerifierConfig.h \
    $${PWD}/OAIConfirmDeviceResponse.h \
    $${PWD}/OAIConfirmForgotPasswordRequest.h \
    $${PWD}/OAIConfirmForgotPasswordRequest_AnalyticsMetadata.h \
    $${PWD}/OAIConfirmForgotPasswordRequest_UserContextData.h \
    $${PWD}/OAIConfirmSignUpRequest.h \
    $${PWD}/OAIConfirmSignUpRequest_AnalyticsMetadata.h \
    $${PWD}/OAIContextDataType.h \
    $${PWD}/OAICreateGroupRequest.h \
    $${PWD}/OAICreateGroupResponse.h \
    $${PWD}/OAICreateGroupResponse_Group.h \
    $${PWD}/OAICreateIdentityProviderRequest.h \
    $${PWD}/OAICreateIdentityProviderResponse.h \
    $${PWD}/OAICreateIdentityProviderResponse_IdentityProvider.h \
    $${PWD}/OAICreateResourceServerRequest.h \
    $${PWD}/OAICreateResourceServerResponse.h \
    $${PWD}/OAICreateResourceServerResponse_ResourceServer.h \
    $${PWD}/OAICreateUserImportJobRequest.h \
    $${PWD}/OAICreateUserImportJobResponse.h \
    $${PWD}/OAICreateUserImportJobResponse_UserImportJob.h \
    $${PWD}/OAICreateUserPoolClientRequest.h \
    $${PWD}/OAICreateUserPoolClientRequest_AnalyticsConfiguration.h \
    $${PWD}/OAICreateUserPoolClientRequest_TokenValidityUnits.h \
    $${PWD}/OAICreateUserPoolClientResponse.h \
    $${PWD}/OAICreateUserPoolClientResponse_UserPoolClient.h \
    $${PWD}/OAICreateUserPoolDomainRequest.h \
    $${PWD}/OAICreateUserPoolDomainRequest_CustomDomainConfig.h \
    $${PWD}/OAICreateUserPoolDomainResponse.h \
    $${PWD}/OAICreateUserPoolRequest.h \
    $${PWD}/OAICreateUserPoolRequest_AccountRecoverySetting.h \
    $${PWD}/OAICreateUserPoolRequest_AdminCreateUserConfig.h \
    $${PWD}/OAICreateUserPoolRequest_DeviceConfiguration.h \
    $${PWD}/OAICreateUserPoolRequest_EmailConfiguration.h \
    $${PWD}/OAICreateUserPoolRequest_LambdaConfig.h \
    $${PWD}/OAICreateUserPoolRequest_Policies.h \
    $${PWD}/OAICreateUserPoolRequest_SmsConfiguration.h \
    $${PWD}/OAICreateUserPoolRequest_UserAttributeUpdateSettings.h \
    $${PWD}/OAICreateUserPoolRequest_UserPoolAddOns.h \
    $${PWD}/OAICreateUserPoolRequest_UsernameConfiguration.h \
    $${PWD}/OAICreateUserPoolRequest_VerificationMessageTemplate.h \
    $${PWD}/OAICreateUserPoolResponse.h \
    $${PWD}/OAICreateUserPoolResponse_UserPool.h \
    $${PWD}/OAICustomDomainConfigType.h \
    $${PWD}/OAICustomEmailLambdaVersionConfigType.h \
    $${PWD}/OAICustomEmailSenderLambdaVersionType.h \
    $${PWD}/OAICustomSMSLambdaVersionConfigType.h \
    $${PWD}/OAICustomSMSSenderLambdaVersionType.h \
    $${PWD}/OAIDefaultEmailOptionType.h \
    $${PWD}/OAIDeleteGroupRequest.h \
    $${PWD}/OAIDeleteIdentityProviderRequest.h \
    $${PWD}/OAIDeleteResourceServerRequest.h \
    $${PWD}/OAIDeleteUserAttributesRequest.h \
    $${PWD}/OAIDeleteUserPoolClientRequest.h \
    $${PWD}/OAIDeleteUserPoolDomainRequest.h \
    $${PWD}/OAIDeleteUserPoolRequest.h \
    $${PWD}/OAIDeleteUserRequest.h \
    $${PWD}/OAIDeletionProtectionType.h \
    $${PWD}/OAIDeliveryMediumType.h \
    $${PWD}/OAIDescribeIdentityProviderRequest.h \
    $${PWD}/OAIDescribeIdentityProviderResponse.h \
    $${PWD}/OAIDescribeIdentityProviderResponse_IdentityProvider.h \
    $${PWD}/OAIDescribeResourceServerRequest.h \
    $${PWD}/OAIDescribeResourceServerResponse.h \
    $${PWD}/OAIDescribeResourceServerResponse_ResourceServer.h \
    $${PWD}/OAIDescribeRiskConfigurationRequest.h \
    $${PWD}/OAIDescribeRiskConfigurationResponse.h \
    $${PWD}/OAIDescribeRiskConfigurationResponse_RiskConfiguration.h \
    $${PWD}/OAIDescribeUserImportJobRequest.h \
    $${PWD}/OAIDescribeUserImportJobResponse.h \
    $${PWD}/OAIDescribeUserPoolClientRequest.h \
    $${PWD}/OAIDescribeUserPoolClientResponse.h \
    $${PWD}/OAIDescribeUserPoolClientResponse_UserPoolClient.h \
    $${PWD}/OAIDescribeUserPoolDomainRequest.h \
    $${PWD}/OAIDescribeUserPoolDomainResponse.h \
    $${PWD}/OAIDescribeUserPoolDomainResponse_DomainDescription.h \
    $${PWD}/OAIDescribeUserPoolRequest.h \
    $${PWD}/OAIDescribeUserPoolResponse.h \
    $${PWD}/OAIDescribeUserPoolResponse_UserPool.h \
    $${PWD}/OAIDeviceConfigurationType.h \
    $${PWD}/OAIDeviceRememberedStatusType.h \
    $${PWD}/OAIDeviceSecretVerifierConfigType.h \
    $${PWD}/OAIDeviceType.h \
    $${PWD}/OAIDomainDescriptionType.h \
    $${PWD}/OAIDomainDescriptionType_CustomDomainConfig.h \
    $${PWD}/OAIDomainStatusType.h \
    $${PWD}/OAIEmailConfigurationType.h \
    $${PWD}/OAIEmailSendingAccountType.h \
    $${PWD}/OAIEventContextDataType.h \
    $${PWD}/OAIEventFeedbackType.h \
    $${PWD}/OAIEventFilterType.h \
    $${PWD}/OAIEventResponseType.h \
    $${PWD}/OAIEventRiskType.h \
    $${PWD}/OAIEventSourceName.h \
    $${PWD}/OAIEventType.h \
    $${PWD}/OAIExplicitAuthFlowsType.h \
    $${PWD}/OAIFeedbackValueType.h \
    $${PWD}/OAIForgetDeviceRequest.h \
    $${PWD}/OAIForgotPasswordRequest.h \
    $${PWD}/OAIForgotPasswordRequest_AnalyticsMetadata.h \
    $${PWD}/OAIForgotPasswordResponse.h \
    $${PWD}/OAIForgotPasswordResponse_CodeDeliveryDetails.h \
    $${PWD}/OAIGetCSVHeaderRequest.h \
    $${PWD}/OAIGetCSVHeaderResponse.h \
    $${PWD}/OAIGetDeviceRequest.h \
    $${PWD}/OAIGetDeviceResponse.h \
    $${PWD}/OAIGetGroupRequest.h \
    $${PWD}/OAIGetGroupResponse.h \
    $${PWD}/OAIGetIdentityProviderByIdentifierRequest.h \
    $${PWD}/OAIGetIdentityProviderByIdentifierResponse.h \
    $${PWD}/OAIGetLogDeliveryConfigurationRequest.h \
    $${PWD}/OAIGetLogDeliveryConfigurationResponse.h \
    $${PWD}/OAIGetLogDeliveryConfigurationResponse_LogDeliveryConfiguration.h \
    $${PWD}/OAIGetSigningCertificateRequest.h \
    $${PWD}/OAIGetSigningCertificateResponse.h \
    $${PWD}/OAIGetUICustomizationRequest.h \
    $${PWD}/OAIGetUICustomizationResponse.h \
    $${PWD}/OAIGetUICustomizationResponse_UICustomization.h \
    $${PWD}/OAIGetUserAttributeVerificationCodeRequest.h \
    $${PWD}/OAIGetUserAttributeVerificationCodeResponse.h \
    $${PWD}/OAIGetUserAttributeVerificationCodeResponse_CodeDeliveryDetails.h \
    $${PWD}/OAIGetUserPoolMfaConfigRequest.h \
    $${PWD}/OAIGetUserPoolMfaConfigResponse.h \
    $${PWD}/OAIGetUserPoolMfaConfigResponse_SmsMfaConfiguration.h \
    $${PWD}/OAIGetUserPoolMfaConfigResponse_SoftwareTokenMfaConfiguration.h \
    $${PWD}/OAIGetUserRequest.h \
    $${PWD}/OAIGetUserResponse.h \
    $${PWD}/OAIGlobalSignOutRequest.h \
    $${PWD}/OAIGroupType.h \
    $${PWD}/OAIHttpHeader.h \
    $${PWD}/OAIIdentityProviderType.h \
    $${PWD}/OAIIdentityProviderTypeType.h \
    $${PWD}/OAIInitiateAuthRequest.h \
    $${PWD}/OAIInitiateAuthRequest_AnalyticsMetadata.h \
    $${PWD}/OAIInitiateAuthResponse.h \
    $${PWD}/OAIInitiateAuthResponse_AuthenticationResult.h \
    $${PWD}/OAILambdaConfigType.h \
    $${PWD}/OAILambdaConfigType_CustomEmailSender.h \
    $${PWD}/OAILambdaConfigType_CustomSMSSender.h \
    $${PWD}/OAIListDevicesRequest.h \
    $${PWD}/OAIListDevicesResponse.h \
    $${PWD}/OAIListGroupsRequest.h \
    $${PWD}/OAIListGroupsResponse.h \
    $${PWD}/OAIListIdentityProvidersRequest.h \
    $${PWD}/OAIListIdentityProvidersResponse.h \
    $${PWD}/OAIListResourceServersRequest.h \
    $${PWD}/OAIListResourceServersResponse.h \
    $${PWD}/OAIListTagsForResourceRequest.h \
    $${PWD}/OAIListTagsForResourceResponse.h \
    $${PWD}/OAIListUserImportJobsRequest.h \
    $${PWD}/OAIListUserImportJobsResponse.h \
    $${PWD}/OAIListUserPoolClientsRequest.h \
    $${PWD}/OAIListUserPoolClientsResponse.h \
    $${PWD}/OAIListUserPoolsRequest.h \
    $${PWD}/OAIListUserPoolsResponse.h \
    $${PWD}/OAIListUsersInGroupRequest.h \
    $${PWD}/OAIListUsersInGroupResponse.h \
    $${PWD}/OAIListUsersRequest.h \
    $${PWD}/OAIListUsersResponse.h \
    $${PWD}/OAILogConfigurationType.h \
    $${PWD}/OAILogConfigurationType_CloudWatchLogsConfiguration.h \
    $${PWD}/OAILogDeliveryConfigurationType.h \
    $${PWD}/OAILogLevel.h \
    $${PWD}/OAIMFAOptionType.h \
    $${PWD}/OAIMessageActionType.h \
    $${PWD}/OAIMessageTemplateType.h \
    $${PWD}/OAINewDeviceMetadataType.h \
    $${PWD}/OAINotifyConfigurationType.h \
    $${PWD}/OAINotifyConfigurationType_BlockEmail.h \
    $${PWD}/OAINotifyConfigurationType_MfaEmail.h \
    $${PWD}/OAINotifyConfigurationType_NoActionEmail.h \
    $${PWD}/OAINotifyEmailType.h \
    $${PWD}/OAINumberAttributeConstraintsType.h \
    $${PWD}/OAIOAuthFlowType.h \
    $${PWD}/OAIPasswordPolicyType.h \
    $${PWD}/OAIPreventUserExistenceErrorTypes.h \
    $${PWD}/OAIProviderDescription.h \
    $${PWD}/OAIProviderUserIdentifierType.h \
    $${PWD}/OAIRecoveryOptionNameType.h \
    $${PWD}/OAIRecoveryOptionType.h \
    $${PWD}/OAIResendConfirmationCodeRequest.h \
    $${PWD}/OAIResendConfirmationCodeRequest_AnalyticsMetadata.h \
    $${PWD}/OAIResendConfirmationCodeResponse.h \
    $${PWD}/OAIResendConfirmationCodeResponse_CodeDeliveryDetails.h \
    $${PWD}/OAIResourceServerScopeType.h \
    $${PWD}/OAIResourceServerType.h \
    $${PWD}/OAIRespondToAuthChallengeRequest.h \
    $${PWD}/OAIRespondToAuthChallengeRequest_AnalyticsMetadata.h \
    $${PWD}/OAIRespondToAuthChallengeResponse.h \
    $${PWD}/OAIRespondToAuthChallengeResponse_AuthenticationResult.h \
    $${PWD}/OAIRevokeTokenRequest.h \
    $${PWD}/OAIRiskConfigurationType.h \
    $${PWD}/OAIRiskConfigurationType_AccountTakeoverRiskConfiguration.h \
    $${PWD}/OAIRiskConfigurationType_CompromisedCredentialsRiskConfiguration.h \
    $${PWD}/OAIRiskDecisionType.h \
    $${PWD}/OAIRiskExceptionConfigurationType.h \
    $${PWD}/OAIRiskLevelType.h \
    $${PWD}/OAISMSMfaSettingsType.h \
    $${PWD}/OAISchemaAttributeType.h \
    $${PWD}/OAISchemaAttributeType_NumberAttributeConstraints.h \
    $${PWD}/OAISchemaAttributeType_StringAttributeConstraints.h \
    $${PWD}/OAISetLogDeliveryConfigurationRequest.h \
    $${PWD}/OAISetLogDeliveryConfigurationResponse.h \
    $${PWD}/OAISetLogDeliveryConfigurationResponse_LogDeliveryConfiguration.h \
    $${PWD}/OAISetRiskConfigurationRequest.h \
    $${PWD}/OAISetRiskConfigurationRequest_AccountTakeoverRiskConfiguration.h \
    $${PWD}/OAISetRiskConfigurationRequest_CompromisedCredentialsRiskConfiguration.h \
    $${PWD}/OAISetRiskConfigurationRequest_RiskExceptionConfiguration.h \
    $${PWD}/OAISetRiskConfigurationResponse.h \
    $${PWD}/OAISetUICustomizationRequest.h \
    $${PWD}/OAISetUICustomizationResponse.h \
    $${PWD}/OAISetUserMFAPreferenceRequest.h \
    $${PWD}/OAISetUserMFAPreferenceRequest_SMSMfaSettings.h \
    $${PWD}/OAISetUserMFAPreferenceRequest_SoftwareTokenMfaSettings.h \
    $${PWD}/OAISetUserPoolMfaConfigRequest.h \
    $${PWD}/OAISetUserPoolMfaConfigResponse.h \
    $${PWD}/OAISetUserPoolMfaConfigResponse_SmsMfaConfiguration.h \
    $${PWD}/OAISetUserPoolMfaConfigResponse_SoftwareTokenMfaConfiguration.h \
    $${PWD}/OAISetUserSettingsRequest.h \
    $${PWD}/OAISignUpRequest.h \
    $${PWD}/OAISignUpRequest_AnalyticsMetadata.h \
    $${PWD}/OAISignUpResponse.h \
    $${PWD}/OAISignUpResponse_CodeDeliveryDetails.h \
    $${PWD}/OAISmsConfigurationType.h \
    $${PWD}/OAISmsMfaConfigType.h \
    $${PWD}/OAISmsMfaConfigType_SmsConfiguration.h \
    $${PWD}/OAISoftwareTokenMfaConfigType.h \
    $${PWD}/OAISoftwareTokenMfaSettingsType.h \
    $${PWD}/OAIStartUserImportJobRequest.h \
    $${PWD}/OAIStartUserImportJobResponse.h \
    $${PWD}/OAIStatusType.h \
    $${PWD}/OAIStopUserImportJobRequest.h \
    $${PWD}/OAIStopUserImportJobResponse.h \
    $${PWD}/OAIStringAttributeConstraintsType.h \
    $${PWD}/OAITagResourceRequest.h \
    $${PWD}/OAITimeUnitsType.h \
    $${PWD}/OAITokenValidityUnitsType.h \
    $${PWD}/OAIUICustomizationType.h \
    $${PWD}/OAIUntagResourceRequest.h \
    $${PWD}/OAIUpdateAuthEventFeedbackRequest.h \
    $${PWD}/OAIUpdateDeviceStatusRequest.h \
    $${PWD}/OAIUpdateGroupRequest.h \
    $${PWD}/OAIUpdateGroupResponse.h \
    $${PWD}/OAIUpdateIdentityProviderRequest.h \
    $${PWD}/OAIUpdateIdentityProviderResponse.h \
    $${PWD}/OAIUpdateResourceServerRequest.h \
    $${PWD}/OAIUpdateResourceServerResponse.h \
    $${PWD}/OAIUpdateUserAttributesRequest.h \
    $${PWD}/OAIUpdateUserAttributesResponse.h \
    $${PWD}/OAIUpdateUserPoolClientRequest.h \
    $${PWD}/OAIUpdateUserPoolClientRequest_AnalyticsConfiguration.h \
    $${PWD}/OAIUpdateUserPoolClientRequest_TokenValidityUnits.h \
    $${PWD}/OAIUpdateUserPoolClientResponse.h \
    $${PWD}/OAIUpdateUserPoolClientResponse_UserPoolClient.h \
    $${PWD}/OAIUpdateUserPoolDomainRequest.h \
    $${PWD}/OAIUpdateUserPoolDomainRequest_CustomDomainConfig.h \
    $${PWD}/OAIUpdateUserPoolDomainResponse.h \
    $${PWD}/OAIUpdateUserPoolRequest.h \
    $${PWD}/OAIUpdateUserPoolRequest_EmailConfiguration.h \
    $${PWD}/OAIUpdateUserPoolRequest_LambdaConfig.h \
    $${PWD}/OAIUpdateUserPoolRequest_Policies.h \
    $${PWD}/OAIUpdateUserPoolRequest_VerificationMessageTemplate.h \
    $${PWD}/OAIUserAttributeUpdateSettingsType.h \
    $${PWD}/OAIUserContextDataType.h \
    $${PWD}/OAIUserImportJobStatusType.h \
    $${PWD}/OAIUserImportJobType.h \
    $${PWD}/OAIUserPoolAddOnsType.h \
    $${PWD}/OAIUserPoolClientDescription.h \
    $${PWD}/OAIUserPoolClientType.h \
    $${PWD}/OAIUserPoolClientType_AnalyticsConfiguration.h \
    $${PWD}/OAIUserPoolClientType_TokenValidityUnits.h \
    $${PWD}/OAIUserPoolDescriptionType.h \
    $${PWD}/OAIUserPoolDescriptionType_LambdaConfig.h \
    $${PWD}/OAIUserPoolMfaType.h \
    $${PWD}/OAIUserPoolPolicyType.h \
    $${PWD}/OAIUserPoolPolicyType_PasswordPolicy.h \
    $${PWD}/OAIUserPoolType.h \
    $${PWD}/OAIUserPoolType_LambdaConfig.h \
    $${PWD}/OAIUserPoolType_Policies.h \
    $${PWD}/OAIUserPoolType_UsernameConfiguration.h \
    $${PWD}/OAIUserStatusType.h \
    $${PWD}/OAIUserType.h \
    $${PWD}/OAIUsernameAttributeType.h \
    $${PWD}/OAIUsernameConfigurationType.h \
    $${PWD}/OAIVerificationMessageTemplateType.h \
    $${PWD}/OAIVerifiedAttributeType.h \
    $${PWD}/OAIVerifySoftwareTokenRequest.h \
    $${PWD}/OAIVerifySoftwareTokenResponse.h \
    $${PWD}/OAIVerifySoftwareTokenResponseType.h \
    $${PWD}/OAIVerifyUserAttributeRequest.h \
# APIs
    $${PWD}/OAIDefaultApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAccountRecoverySettingType.cpp \
    $${PWD}/OAIAccountTakeoverActionType.cpp \
    $${PWD}/OAIAccountTakeoverActionsType.cpp \
    $${PWD}/OAIAccountTakeoverActionsType_HighAction.cpp \
    $${PWD}/OAIAccountTakeoverActionsType_LowAction.cpp \
    $${PWD}/OAIAccountTakeoverActionsType_MediumAction.cpp \
    $${PWD}/OAIAccountTakeoverEventActionType.cpp \
    $${PWD}/OAIAccountTakeoverRiskConfigurationType.cpp \
    $${PWD}/OAIAccountTakeoverRiskConfigurationType_Actions.cpp \
    $${PWD}/OAIAccountTakeoverRiskConfigurationType_NotifyConfiguration.cpp \
    $${PWD}/OAIAddCustomAttributesRequest.cpp \
    $${PWD}/OAIAdminAddUserToGroupRequest.cpp \
    $${PWD}/OAIAdminConfirmSignUpRequest.cpp \
    $${PWD}/OAIAdminCreateUserConfigType.cpp \
    $${PWD}/OAIAdminCreateUserConfigType_InviteMessageTemplate.cpp \
    $${PWD}/OAIAdminCreateUserRequest.cpp \
    $${PWD}/OAIAdminCreateUserResponse.cpp \
    $${PWD}/OAIAdminCreateUserResponse_User.cpp \
    $${PWD}/OAIAdminDeleteUserAttributesRequest.cpp \
    $${PWD}/OAIAdminDeleteUserRequest.cpp \
    $${PWD}/OAIAdminDisableProviderForUserRequest.cpp \
    $${PWD}/OAIAdminDisableProviderForUserRequest_User.cpp \
    $${PWD}/OAIAdminDisableUserRequest.cpp \
    $${PWD}/OAIAdminEnableUserRequest.cpp \
    $${PWD}/OAIAdminForgetDeviceRequest.cpp \
    $${PWD}/OAIAdminGetDeviceRequest.cpp \
    $${PWD}/OAIAdminGetDeviceResponse.cpp \
    $${PWD}/OAIAdminGetDeviceResponse_Device.cpp \
    $${PWD}/OAIAdminGetUserRequest.cpp \
    $${PWD}/OAIAdminGetUserResponse.cpp \
    $${PWD}/OAIAdminInitiateAuthRequest.cpp \
    $${PWD}/OAIAdminInitiateAuthRequest_AnalyticsMetadata.cpp \
    $${PWD}/OAIAdminInitiateAuthRequest_ContextData.cpp \
    $${PWD}/OAIAdminInitiateAuthResponse.cpp \
    $${PWD}/OAIAdminInitiateAuthResponse_AuthenticationResult.cpp \
    $${PWD}/OAIAdminLinkProviderForUserRequest.cpp \
    $${PWD}/OAIAdminLinkProviderForUserRequest_DestinationUser.cpp \
    $${PWD}/OAIAdminLinkProviderForUserRequest_SourceUser.cpp \
    $${PWD}/OAIAdminListDevicesRequest.cpp \
    $${PWD}/OAIAdminListDevicesResponse.cpp \
    $${PWD}/OAIAdminListGroupsForUserRequest.cpp \
    $${PWD}/OAIAdminListGroupsForUserResponse.cpp \
    $${PWD}/OAIAdminListUserAuthEventsRequest.cpp \
    $${PWD}/OAIAdminListUserAuthEventsResponse.cpp \
    $${PWD}/OAIAdminRemoveUserFromGroupRequest.cpp \
    $${PWD}/OAIAdminResetUserPasswordRequest.cpp \
    $${PWD}/OAIAdminRespondToAuthChallengeRequest.cpp \
    $${PWD}/OAIAdminRespondToAuthChallengeRequest_AnalyticsMetadata.cpp \
    $${PWD}/OAIAdminRespondToAuthChallengeResponse.cpp \
    $${PWD}/OAIAdminRespondToAuthChallengeResponse_AuthenticationResult.cpp \
    $${PWD}/OAIAdminSetUserMFAPreferenceRequest.cpp \
    $${PWD}/OAIAdminSetUserMFAPreferenceRequest_SMSMfaSettings.cpp \
    $${PWD}/OAIAdminSetUserMFAPreferenceRequest_SoftwareTokenMfaSettings.cpp \
    $${PWD}/OAIAdminSetUserPasswordRequest.cpp \
    $${PWD}/OAIAdminSetUserSettingsRequest.cpp \
    $${PWD}/OAIAdminUpdateAuthEventFeedbackRequest.cpp \
    $${PWD}/OAIAdminUpdateDeviceStatusRequest.cpp \
    $${PWD}/OAIAdminUpdateUserAttributesRequest.cpp \
    $${PWD}/OAIAdminUserGlobalSignOutRequest.cpp \
    $${PWD}/OAIAdvancedSecurityModeType.cpp \
    $${PWD}/OAIAliasAttributeType.cpp \
    $${PWD}/OAIAnalyticsConfigurationType.cpp \
    $${PWD}/OAIAnalyticsMetadataType.cpp \
    $${PWD}/OAIAssociateSoftwareTokenRequest.cpp \
    $${PWD}/OAIAssociateSoftwareTokenResponse.cpp \
    $${PWD}/OAIAttributeDataType.cpp \
    $${PWD}/OAIAttributeType.cpp \
    $${PWD}/OAIAuthEventType.cpp \
    $${PWD}/OAIAuthEventType_EventContextData.cpp \
    $${PWD}/OAIAuthEventType_EventFeedback.cpp \
    $${PWD}/OAIAuthEventType_EventRisk.cpp \
    $${PWD}/OAIAuthFlowType.cpp \
    $${PWD}/OAIAuthenticationResultType.cpp \
    $${PWD}/OAIAuthenticationResultType_NewDeviceMetadata.cpp \
    $${PWD}/OAIChallengeName.cpp \
    $${PWD}/OAIChallengeNameType.cpp \
    $${PWD}/OAIChallengeResponse.cpp \
    $${PWD}/OAIChallengeResponseType.cpp \
    $${PWD}/OAIChangePasswordRequest.cpp \
    $${PWD}/OAICloudWatchLogsConfigurationType.cpp \
    $${PWD}/OAICodeDeliveryDetailsType.cpp \
    $${PWD}/OAICompromisedCredentialsActionsType.cpp \
    $${PWD}/OAICompromisedCredentialsEventActionType.cpp \
    $${PWD}/OAICompromisedCredentialsRiskConfigurationType.cpp \
    $${PWD}/OAICompromisedCredentialsRiskConfigurationType_Actions.cpp \
    $${PWD}/OAIConfirmDeviceRequest.cpp \
    $${PWD}/OAIConfirmDeviceRequest_DeviceSecretVerifierConfig.cpp \
    $${PWD}/OAIConfirmDeviceResponse.cpp \
    $${PWD}/OAIConfirmForgotPasswordRequest.cpp \
    $${PWD}/OAIConfirmForgotPasswordRequest_AnalyticsMetadata.cpp \
    $${PWD}/OAIConfirmForgotPasswordRequest_UserContextData.cpp \
    $${PWD}/OAIConfirmSignUpRequest.cpp \
    $${PWD}/OAIConfirmSignUpRequest_AnalyticsMetadata.cpp \
    $${PWD}/OAIContextDataType.cpp \
    $${PWD}/OAICreateGroupRequest.cpp \
    $${PWD}/OAICreateGroupResponse.cpp \
    $${PWD}/OAICreateGroupResponse_Group.cpp \
    $${PWD}/OAICreateIdentityProviderRequest.cpp \
    $${PWD}/OAICreateIdentityProviderResponse.cpp \
    $${PWD}/OAICreateIdentityProviderResponse_IdentityProvider.cpp \
    $${PWD}/OAICreateResourceServerRequest.cpp \
    $${PWD}/OAICreateResourceServerResponse.cpp \
    $${PWD}/OAICreateResourceServerResponse_ResourceServer.cpp \
    $${PWD}/OAICreateUserImportJobRequest.cpp \
    $${PWD}/OAICreateUserImportJobResponse.cpp \
    $${PWD}/OAICreateUserImportJobResponse_UserImportJob.cpp \
    $${PWD}/OAICreateUserPoolClientRequest.cpp \
    $${PWD}/OAICreateUserPoolClientRequest_AnalyticsConfiguration.cpp \
    $${PWD}/OAICreateUserPoolClientRequest_TokenValidityUnits.cpp \
    $${PWD}/OAICreateUserPoolClientResponse.cpp \
    $${PWD}/OAICreateUserPoolClientResponse_UserPoolClient.cpp \
    $${PWD}/OAICreateUserPoolDomainRequest.cpp \
    $${PWD}/OAICreateUserPoolDomainRequest_CustomDomainConfig.cpp \
    $${PWD}/OAICreateUserPoolDomainResponse.cpp \
    $${PWD}/OAICreateUserPoolRequest.cpp \
    $${PWD}/OAICreateUserPoolRequest_AccountRecoverySetting.cpp \
    $${PWD}/OAICreateUserPoolRequest_AdminCreateUserConfig.cpp \
    $${PWD}/OAICreateUserPoolRequest_DeviceConfiguration.cpp \
    $${PWD}/OAICreateUserPoolRequest_EmailConfiguration.cpp \
    $${PWD}/OAICreateUserPoolRequest_LambdaConfig.cpp \
    $${PWD}/OAICreateUserPoolRequest_Policies.cpp \
    $${PWD}/OAICreateUserPoolRequest_SmsConfiguration.cpp \
    $${PWD}/OAICreateUserPoolRequest_UserAttributeUpdateSettings.cpp \
    $${PWD}/OAICreateUserPoolRequest_UserPoolAddOns.cpp \
    $${PWD}/OAICreateUserPoolRequest_UsernameConfiguration.cpp \
    $${PWD}/OAICreateUserPoolRequest_VerificationMessageTemplate.cpp \
    $${PWD}/OAICreateUserPoolResponse.cpp \
    $${PWD}/OAICreateUserPoolResponse_UserPool.cpp \
    $${PWD}/OAICustomDomainConfigType.cpp \
    $${PWD}/OAICustomEmailLambdaVersionConfigType.cpp \
    $${PWD}/OAICustomEmailSenderLambdaVersionType.cpp \
    $${PWD}/OAICustomSMSLambdaVersionConfigType.cpp \
    $${PWD}/OAICustomSMSSenderLambdaVersionType.cpp \
    $${PWD}/OAIDefaultEmailOptionType.cpp \
    $${PWD}/OAIDeleteGroupRequest.cpp \
    $${PWD}/OAIDeleteIdentityProviderRequest.cpp \
    $${PWD}/OAIDeleteResourceServerRequest.cpp \
    $${PWD}/OAIDeleteUserAttributesRequest.cpp \
    $${PWD}/OAIDeleteUserPoolClientRequest.cpp \
    $${PWD}/OAIDeleteUserPoolDomainRequest.cpp \
    $${PWD}/OAIDeleteUserPoolRequest.cpp \
    $${PWD}/OAIDeleteUserRequest.cpp \
    $${PWD}/OAIDeletionProtectionType.cpp \
    $${PWD}/OAIDeliveryMediumType.cpp \
    $${PWD}/OAIDescribeIdentityProviderRequest.cpp \
    $${PWD}/OAIDescribeIdentityProviderResponse.cpp \
    $${PWD}/OAIDescribeIdentityProviderResponse_IdentityProvider.cpp \
    $${PWD}/OAIDescribeResourceServerRequest.cpp \
    $${PWD}/OAIDescribeResourceServerResponse.cpp \
    $${PWD}/OAIDescribeResourceServerResponse_ResourceServer.cpp \
    $${PWD}/OAIDescribeRiskConfigurationRequest.cpp \
    $${PWD}/OAIDescribeRiskConfigurationResponse.cpp \
    $${PWD}/OAIDescribeRiskConfigurationResponse_RiskConfiguration.cpp \
    $${PWD}/OAIDescribeUserImportJobRequest.cpp \
    $${PWD}/OAIDescribeUserImportJobResponse.cpp \
    $${PWD}/OAIDescribeUserPoolClientRequest.cpp \
    $${PWD}/OAIDescribeUserPoolClientResponse.cpp \
    $${PWD}/OAIDescribeUserPoolClientResponse_UserPoolClient.cpp \
    $${PWD}/OAIDescribeUserPoolDomainRequest.cpp \
    $${PWD}/OAIDescribeUserPoolDomainResponse.cpp \
    $${PWD}/OAIDescribeUserPoolDomainResponse_DomainDescription.cpp \
    $${PWD}/OAIDescribeUserPoolRequest.cpp \
    $${PWD}/OAIDescribeUserPoolResponse.cpp \
    $${PWD}/OAIDescribeUserPoolResponse_UserPool.cpp \
    $${PWD}/OAIDeviceConfigurationType.cpp \
    $${PWD}/OAIDeviceRememberedStatusType.cpp \
    $${PWD}/OAIDeviceSecretVerifierConfigType.cpp \
    $${PWD}/OAIDeviceType.cpp \
    $${PWD}/OAIDomainDescriptionType.cpp \
    $${PWD}/OAIDomainDescriptionType_CustomDomainConfig.cpp \
    $${PWD}/OAIDomainStatusType.cpp \
    $${PWD}/OAIEmailConfigurationType.cpp \
    $${PWD}/OAIEmailSendingAccountType.cpp \
    $${PWD}/OAIEventContextDataType.cpp \
    $${PWD}/OAIEventFeedbackType.cpp \
    $${PWD}/OAIEventFilterType.cpp \
    $${PWD}/OAIEventResponseType.cpp \
    $${PWD}/OAIEventRiskType.cpp \
    $${PWD}/OAIEventSourceName.cpp \
    $${PWD}/OAIEventType.cpp \
    $${PWD}/OAIExplicitAuthFlowsType.cpp \
    $${PWD}/OAIFeedbackValueType.cpp \
    $${PWD}/OAIForgetDeviceRequest.cpp \
    $${PWD}/OAIForgotPasswordRequest.cpp \
    $${PWD}/OAIForgotPasswordRequest_AnalyticsMetadata.cpp \
    $${PWD}/OAIForgotPasswordResponse.cpp \
    $${PWD}/OAIForgotPasswordResponse_CodeDeliveryDetails.cpp \
    $${PWD}/OAIGetCSVHeaderRequest.cpp \
    $${PWD}/OAIGetCSVHeaderResponse.cpp \
    $${PWD}/OAIGetDeviceRequest.cpp \
    $${PWD}/OAIGetDeviceResponse.cpp \
    $${PWD}/OAIGetGroupRequest.cpp \
    $${PWD}/OAIGetGroupResponse.cpp \
    $${PWD}/OAIGetIdentityProviderByIdentifierRequest.cpp \
    $${PWD}/OAIGetIdentityProviderByIdentifierResponse.cpp \
    $${PWD}/OAIGetLogDeliveryConfigurationRequest.cpp \
    $${PWD}/OAIGetLogDeliveryConfigurationResponse.cpp \
    $${PWD}/OAIGetLogDeliveryConfigurationResponse_LogDeliveryConfiguration.cpp \
    $${PWD}/OAIGetSigningCertificateRequest.cpp \
    $${PWD}/OAIGetSigningCertificateResponse.cpp \
    $${PWD}/OAIGetUICustomizationRequest.cpp \
    $${PWD}/OAIGetUICustomizationResponse.cpp \
    $${PWD}/OAIGetUICustomizationResponse_UICustomization.cpp \
    $${PWD}/OAIGetUserAttributeVerificationCodeRequest.cpp \
    $${PWD}/OAIGetUserAttributeVerificationCodeResponse.cpp \
    $${PWD}/OAIGetUserAttributeVerificationCodeResponse_CodeDeliveryDetails.cpp \
    $${PWD}/OAIGetUserPoolMfaConfigRequest.cpp \
    $${PWD}/OAIGetUserPoolMfaConfigResponse.cpp \
    $${PWD}/OAIGetUserPoolMfaConfigResponse_SmsMfaConfiguration.cpp \
    $${PWD}/OAIGetUserPoolMfaConfigResponse_SoftwareTokenMfaConfiguration.cpp \
    $${PWD}/OAIGetUserRequest.cpp \
    $${PWD}/OAIGetUserResponse.cpp \
    $${PWD}/OAIGlobalSignOutRequest.cpp \
    $${PWD}/OAIGroupType.cpp \
    $${PWD}/OAIHttpHeader.cpp \
    $${PWD}/OAIIdentityProviderType.cpp \
    $${PWD}/OAIIdentityProviderTypeType.cpp \
    $${PWD}/OAIInitiateAuthRequest.cpp \
    $${PWD}/OAIInitiateAuthRequest_AnalyticsMetadata.cpp \
    $${PWD}/OAIInitiateAuthResponse.cpp \
    $${PWD}/OAIInitiateAuthResponse_AuthenticationResult.cpp \
    $${PWD}/OAILambdaConfigType.cpp \
    $${PWD}/OAILambdaConfigType_CustomEmailSender.cpp \
    $${PWD}/OAILambdaConfigType_CustomSMSSender.cpp \
    $${PWD}/OAIListDevicesRequest.cpp \
    $${PWD}/OAIListDevicesResponse.cpp \
    $${PWD}/OAIListGroupsRequest.cpp \
    $${PWD}/OAIListGroupsResponse.cpp \
    $${PWD}/OAIListIdentityProvidersRequest.cpp \
    $${PWD}/OAIListIdentityProvidersResponse.cpp \
    $${PWD}/OAIListResourceServersRequest.cpp \
    $${PWD}/OAIListResourceServersResponse.cpp \
    $${PWD}/OAIListTagsForResourceRequest.cpp \
    $${PWD}/OAIListTagsForResourceResponse.cpp \
    $${PWD}/OAIListUserImportJobsRequest.cpp \
    $${PWD}/OAIListUserImportJobsResponse.cpp \
    $${PWD}/OAIListUserPoolClientsRequest.cpp \
    $${PWD}/OAIListUserPoolClientsResponse.cpp \
    $${PWD}/OAIListUserPoolsRequest.cpp \
    $${PWD}/OAIListUserPoolsResponse.cpp \
    $${PWD}/OAIListUsersInGroupRequest.cpp \
    $${PWD}/OAIListUsersInGroupResponse.cpp \
    $${PWD}/OAIListUsersRequest.cpp \
    $${PWD}/OAIListUsersResponse.cpp \
    $${PWD}/OAILogConfigurationType.cpp \
    $${PWD}/OAILogConfigurationType_CloudWatchLogsConfiguration.cpp \
    $${PWD}/OAILogDeliveryConfigurationType.cpp \
    $${PWD}/OAILogLevel.cpp \
    $${PWD}/OAIMFAOptionType.cpp \
    $${PWD}/OAIMessageActionType.cpp \
    $${PWD}/OAIMessageTemplateType.cpp \
    $${PWD}/OAINewDeviceMetadataType.cpp \
    $${PWD}/OAINotifyConfigurationType.cpp \
    $${PWD}/OAINotifyConfigurationType_BlockEmail.cpp \
    $${PWD}/OAINotifyConfigurationType_MfaEmail.cpp \
    $${PWD}/OAINotifyConfigurationType_NoActionEmail.cpp \
    $${PWD}/OAINotifyEmailType.cpp \
    $${PWD}/OAINumberAttributeConstraintsType.cpp \
    $${PWD}/OAIOAuthFlowType.cpp \
    $${PWD}/OAIPasswordPolicyType.cpp \
    $${PWD}/OAIPreventUserExistenceErrorTypes.cpp \
    $${PWD}/OAIProviderDescription.cpp \
    $${PWD}/OAIProviderUserIdentifierType.cpp \
    $${PWD}/OAIRecoveryOptionNameType.cpp \
    $${PWD}/OAIRecoveryOptionType.cpp \
    $${PWD}/OAIResendConfirmationCodeRequest.cpp \
    $${PWD}/OAIResendConfirmationCodeRequest_AnalyticsMetadata.cpp \
    $${PWD}/OAIResendConfirmationCodeResponse.cpp \
    $${PWD}/OAIResendConfirmationCodeResponse_CodeDeliveryDetails.cpp \
    $${PWD}/OAIResourceServerScopeType.cpp \
    $${PWD}/OAIResourceServerType.cpp \
    $${PWD}/OAIRespondToAuthChallengeRequest.cpp \
    $${PWD}/OAIRespondToAuthChallengeRequest_AnalyticsMetadata.cpp \
    $${PWD}/OAIRespondToAuthChallengeResponse.cpp \
    $${PWD}/OAIRespondToAuthChallengeResponse_AuthenticationResult.cpp \
    $${PWD}/OAIRevokeTokenRequest.cpp \
    $${PWD}/OAIRiskConfigurationType.cpp \
    $${PWD}/OAIRiskConfigurationType_AccountTakeoverRiskConfiguration.cpp \
    $${PWD}/OAIRiskConfigurationType_CompromisedCredentialsRiskConfiguration.cpp \
    $${PWD}/OAIRiskDecisionType.cpp \
    $${PWD}/OAIRiskExceptionConfigurationType.cpp \
    $${PWD}/OAIRiskLevelType.cpp \
    $${PWD}/OAISMSMfaSettingsType.cpp \
    $${PWD}/OAISchemaAttributeType.cpp \
    $${PWD}/OAISchemaAttributeType_NumberAttributeConstraints.cpp \
    $${PWD}/OAISchemaAttributeType_StringAttributeConstraints.cpp \
    $${PWD}/OAISetLogDeliveryConfigurationRequest.cpp \
    $${PWD}/OAISetLogDeliveryConfigurationResponse.cpp \
    $${PWD}/OAISetLogDeliveryConfigurationResponse_LogDeliveryConfiguration.cpp \
    $${PWD}/OAISetRiskConfigurationRequest.cpp \
    $${PWD}/OAISetRiskConfigurationRequest_AccountTakeoverRiskConfiguration.cpp \
    $${PWD}/OAISetRiskConfigurationRequest_CompromisedCredentialsRiskConfiguration.cpp \
    $${PWD}/OAISetRiskConfigurationRequest_RiskExceptionConfiguration.cpp \
    $${PWD}/OAISetRiskConfigurationResponse.cpp \
    $${PWD}/OAISetUICustomizationRequest.cpp \
    $${PWD}/OAISetUICustomizationResponse.cpp \
    $${PWD}/OAISetUserMFAPreferenceRequest.cpp \
    $${PWD}/OAISetUserMFAPreferenceRequest_SMSMfaSettings.cpp \
    $${PWD}/OAISetUserMFAPreferenceRequest_SoftwareTokenMfaSettings.cpp \
    $${PWD}/OAISetUserPoolMfaConfigRequest.cpp \
    $${PWD}/OAISetUserPoolMfaConfigResponse.cpp \
    $${PWD}/OAISetUserPoolMfaConfigResponse_SmsMfaConfiguration.cpp \
    $${PWD}/OAISetUserPoolMfaConfigResponse_SoftwareTokenMfaConfiguration.cpp \
    $${PWD}/OAISetUserSettingsRequest.cpp \
    $${PWD}/OAISignUpRequest.cpp \
    $${PWD}/OAISignUpRequest_AnalyticsMetadata.cpp \
    $${PWD}/OAISignUpResponse.cpp \
    $${PWD}/OAISignUpResponse_CodeDeliveryDetails.cpp \
    $${PWD}/OAISmsConfigurationType.cpp \
    $${PWD}/OAISmsMfaConfigType.cpp \
    $${PWD}/OAISmsMfaConfigType_SmsConfiguration.cpp \
    $${PWD}/OAISoftwareTokenMfaConfigType.cpp \
    $${PWD}/OAISoftwareTokenMfaSettingsType.cpp \
    $${PWD}/OAIStartUserImportJobRequest.cpp \
    $${PWD}/OAIStartUserImportJobResponse.cpp \
    $${PWD}/OAIStatusType.cpp \
    $${PWD}/OAIStopUserImportJobRequest.cpp \
    $${PWD}/OAIStopUserImportJobResponse.cpp \
    $${PWD}/OAIStringAttributeConstraintsType.cpp \
    $${PWD}/OAITagResourceRequest.cpp \
    $${PWD}/OAITimeUnitsType.cpp \
    $${PWD}/OAITokenValidityUnitsType.cpp \
    $${PWD}/OAIUICustomizationType.cpp \
    $${PWD}/OAIUntagResourceRequest.cpp \
    $${PWD}/OAIUpdateAuthEventFeedbackRequest.cpp \
    $${PWD}/OAIUpdateDeviceStatusRequest.cpp \
    $${PWD}/OAIUpdateGroupRequest.cpp \
    $${PWD}/OAIUpdateGroupResponse.cpp \
    $${PWD}/OAIUpdateIdentityProviderRequest.cpp \
    $${PWD}/OAIUpdateIdentityProviderResponse.cpp \
    $${PWD}/OAIUpdateResourceServerRequest.cpp \
    $${PWD}/OAIUpdateResourceServerResponse.cpp \
    $${PWD}/OAIUpdateUserAttributesRequest.cpp \
    $${PWD}/OAIUpdateUserAttributesResponse.cpp \
    $${PWD}/OAIUpdateUserPoolClientRequest.cpp \
    $${PWD}/OAIUpdateUserPoolClientRequest_AnalyticsConfiguration.cpp \
    $${PWD}/OAIUpdateUserPoolClientRequest_TokenValidityUnits.cpp \
    $${PWD}/OAIUpdateUserPoolClientResponse.cpp \
    $${PWD}/OAIUpdateUserPoolClientResponse_UserPoolClient.cpp \
    $${PWD}/OAIUpdateUserPoolDomainRequest.cpp \
    $${PWD}/OAIUpdateUserPoolDomainRequest_CustomDomainConfig.cpp \
    $${PWD}/OAIUpdateUserPoolDomainResponse.cpp \
    $${PWD}/OAIUpdateUserPoolRequest.cpp \
    $${PWD}/OAIUpdateUserPoolRequest_EmailConfiguration.cpp \
    $${PWD}/OAIUpdateUserPoolRequest_LambdaConfig.cpp \
    $${PWD}/OAIUpdateUserPoolRequest_Policies.cpp \
    $${PWD}/OAIUpdateUserPoolRequest_VerificationMessageTemplate.cpp \
    $${PWD}/OAIUserAttributeUpdateSettingsType.cpp \
    $${PWD}/OAIUserContextDataType.cpp \
    $${PWD}/OAIUserImportJobStatusType.cpp \
    $${PWD}/OAIUserImportJobType.cpp \
    $${PWD}/OAIUserPoolAddOnsType.cpp \
    $${PWD}/OAIUserPoolClientDescription.cpp \
    $${PWD}/OAIUserPoolClientType.cpp \
    $${PWD}/OAIUserPoolClientType_AnalyticsConfiguration.cpp \
    $${PWD}/OAIUserPoolClientType_TokenValidityUnits.cpp \
    $${PWD}/OAIUserPoolDescriptionType.cpp \
    $${PWD}/OAIUserPoolDescriptionType_LambdaConfig.cpp \
    $${PWD}/OAIUserPoolMfaType.cpp \
    $${PWD}/OAIUserPoolPolicyType.cpp \
    $${PWD}/OAIUserPoolPolicyType_PasswordPolicy.cpp \
    $${PWD}/OAIUserPoolType.cpp \
    $${PWD}/OAIUserPoolType_LambdaConfig.cpp \
    $${PWD}/OAIUserPoolType_Policies.cpp \
    $${PWD}/OAIUserPoolType_UsernameConfiguration.cpp \
    $${PWD}/OAIUserStatusType.cpp \
    $${PWD}/OAIUserType.cpp \
    $${PWD}/OAIUsernameAttributeType.cpp \
    $${PWD}/OAIUsernameConfigurationType.cpp \
    $${PWD}/OAIVerificationMessageTemplateType.cpp \
    $${PWD}/OAIVerifiedAttributeType.cpp \
    $${PWD}/OAIVerifySoftwareTokenRequest.cpp \
    $${PWD}/OAIVerifySoftwareTokenResponse.cpp \
    $${PWD}/OAIVerifySoftwareTokenResponseType.cpp \
    $${PWD}/OAIVerifyUserAttributeRequest.cpp \
# APIs
    $${PWD}/OAIDefaultApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
