QT += network

HEADERS += \
# Models
    $${PWD}/OAIAadMetadata.h \
    $${PWD}/OAIAadMetadataObject.h \
    $${PWD}/OAIAddRemoveIncrementalNamedPartitionScalingMechanism.h \
    $${PWD}/OAIAnalysisEventMetadata.h \
    $${PWD}/OAIApplicationBackupConfigurationInfo.h \
    $${PWD}/OAIApplicationBackupEntity.h \
    $${PWD}/OAIApplicationCapacityDescription.h \
    $${PWD}/OAIApplicationCreatedEvent.h \
    $${PWD}/OAIApplicationDefinitionKind.h \
    $${PWD}/OAIApplicationDeletedEvent.h \
    $${PWD}/OAIApplicationDescription.h \
    $${PWD}/OAIApplicationEvent.h \
    $${PWD}/OAIApplicationHealth.h \
    $${PWD}/OAIApplicationHealthEvaluation.h \
    $${PWD}/OAIApplicationHealthPolicies.h \
    $${PWD}/OAIApplicationHealthPolicy.h \
    $${PWD}/OAIApplicationHealthPolicyMapItem.h \
    $${PWD}/OAIApplicationHealthReportCreatedEvent.h \
    $${PWD}/OAIApplicationHealthReportExpiredEvent.h \
    $${PWD}/OAIApplicationHealthState.h \
    $${PWD}/OAIApplicationHealthStateChunk.h \
    $${PWD}/OAIApplicationHealthStateChunkList.h \
    $${PWD}/OAIApplicationHealthStateFilter.h \
    $${PWD}/OAIApplicationInfo.h \
    $${PWD}/OAIApplicationLoadInfo.h \
    $${PWD}/OAIApplicationMetricDescription.h \
    $${PWD}/OAIApplicationNameInfo.h \
    $${PWD}/OAIApplicationPackageCleanupPolicy.h \
    $${PWD}/OAIApplicationParameter.h \
    $${PWD}/OAIApplicationStatus.h \
    $${PWD}/OAIApplicationTypeApplicationsHealthEvaluation.h \
    $${PWD}/OAIApplicationTypeDefinitionKind.h \
    $${PWD}/OAIApplicationTypeHealthPolicyMapItem.h \
    $${PWD}/OAIApplicationTypeImageStorePath.h \
    $${PWD}/OAIApplicationTypeInfo.h \
    $${PWD}/OAIApplicationTypeManifest.h \
    $${PWD}/OAIApplicationTypeStatus.h \
    $${PWD}/OAIApplicationUpgradeCompleteEvent.h \
    $${PWD}/OAIApplicationUpgradeDescription.h \
    $${PWD}/OAIApplicationUpgradeDomainCompleteEvent.h \
    $${PWD}/OAIApplicationUpgradeProgressInfo.h \
    $${PWD}/OAIApplicationUpgradeRollbackCompleteEvent.h \
    $${PWD}/OAIApplicationUpgradeRollbackStartEvent.h \
    $${PWD}/OAIApplicationUpgradeStartEvent.h \
    $${PWD}/OAIApplicationUpgradeUpdateDescription.h \
    $${PWD}/OAIApplicationsHealthEvaluation.h \
    $${PWD}/OAIAveragePartitionLoadScalingTrigger.h \
    $${PWD}/OAIAverageServiceLoadScalingTrigger.h \
    $${PWD}/OAIAzureBlobBackupStorageDescription.h \
    $${PWD}/OAIBackupConfigurationInfo.h \
    $${PWD}/OAIBackupEntity.h \
    $${PWD}/OAIBackupEntityKind.h \
    $${PWD}/OAIBackupEpoch.h \
    $${PWD}/OAIBackupInfo.h \
    $${PWD}/OAIBackupPartitionDescription.h \
    $${PWD}/OAIBackupPolicyDescription.h \
    $${PWD}/OAIBackupPolicyScope.h \
    $${PWD}/OAIBackupProgressInfo.h \
    $${PWD}/OAIBackupScheduleDescription.h \
    $${PWD}/OAIBackupScheduleFrequencyType.h \
    $${PWD}/OAIBackupScheduleKind.h \
    $${PWD}/OAIBackupState.h \
    $${PWD}/OAIBackupStorageDescription.h \
    $${PWD}/OAIBackupStorageKind.h \
    $${PWD}/OAIBackupSuspensionInfo.h \
    $${PWD}/OAIBackupSuspensionScope.h \
    $${PWD}/OAIBackupType.h \
    $${PWD}/OAIBinaryPropertyValue.h \
    $${PWD}/OAIChaos.h \
    $${PWD}/OAIChaosContext.h \
    $${PWD}/OAIChaosEvent.h \
    $${PWD}/OAIChaosEventKind.h \
    $${PWD}/OAIChaosEventWrapper.h \
    $${PWD}/OAIChaosEventsSegment.h \
    $${PWD}/OAIChaosMovePrimaryFaultScheduledEvent.h \
    $${PWD}/OAIChaosMoveSecondaryFaultScheduledEvent.h \
    $${PWD}/OAIChaosParameters.h \
    $${PWD}/OAIChaosParametersDictionaryItem.h \
    $${PWD}/OAIChaosRemoveReplicaFaultCompletedEvent.h \
    $${PWD}/OAIChaosRemoveReplicaFaultScheduledEvent.h \
    $${PWD}/OAIChaosRestartCodePackageFaultCompletedEvent.h \
    $${PWD}/OAIChaosRestartCodePackageFaultScheduledEvent.h \
    $${PWD}/OAIChaosRestartNodeFaultCompletedEvent.h \
    $${PWD}/OAIChaosRestartNodeFaultScheduledEvent.h \
    $${PWD}/OAIChaosRestartReplicaFaultScheduledEvent.h \
    $${PWD}/OAIChaosSchedule.h \
    $${PWD}/OAIChaosScheduleDescription.h \
    $${PWD}/OAIChaosScheduleJob.h \
    $${PWD}/OAIChaosScheduleJobActiveDaysOfWeek.h \
    $${PWD}/OAIChaosScheduleStatus.h \
    $${PWD}/OAIChaosStartedEvent.h \
    $${PWD}/OAIChaosStatus.h \
    $${PWD}/OAIChaosStoppedEvent.h \
    $${PWD}/OAIChaosTargetFilter.h \
    $${PWD}/OAICheckExistsPropertyBatchOperation.h \
    $${PWD}/OAICheckSequencePropertyBatchOperation.h \
    $${PWD}/OAICheckValuePropertyBatchOperation.h \
    $${PWD}/OAIClusterConfiguration.h \
    $${PWD}/OAIClusterConfigurationUpgradeDescription.h \
    $${PWD}/OAIClusterConfigurationUpgradeStatusInfo.h \
    $${PWD}/OAIClusterEvent.h \
    $${PWD}/OAIClusterHealth.h \
    $${PWD}/OAIClusterHealthChunk.h \
    $${PWD}/OAIClusterHealthChunkQueryDescription.h \
    $${PWD}/OAIClusterHealthPolicies.h \
    $${PWD}/OAIClusterHealthPolicy.h \
    $${PWD}/OAIClusterHealthReportCreatedEvent.h \
    $${PWD}/OAIClusterHealthReportExpiredEvent.h \
    $${PWD}/OAIClusterManifest.h \
    $${PWD}/OAIClusterUpgradeCompleteEvent.h \
    $${PWD}/OAIClusterUpgradeDescriptionObject.h \
    $${PWD}/OAIClusterUpgradeDomainCompleteEvent.h \
    $${PWD}/OAIClusterUpgradeHealthPolicyObject.h \
    $${PWD}/OAIClusterUpgradeProgressObject.h \
    $${PWD}/OAIClusterUpgradeRollbackCompleteEvent.h \
    $${PWD}/OAIClusterUpgradeRollbackStartEvent.h \
    $${PWD}/OAIClusterUpgradeStartEvent.h \
    $${PWD}/OAICodePackageEntryPoint.h \
    $${PWD}/OAICodePackageEntryPointStatistics.h \
    $${PWD}/OAIComposeDeploymentStatus.h \
    $${PWD}/OAIComposeDeploymentStatusInfo.h \
    $${PWD}/OAIComposeDeploymentUpgradeDescription.h \
    $${PWD}/OAIComposeDeploymentUpgradeProgressInfo.h \
    $${PWD}/OAIComposeDeploymentUpgradeState.h \
    $${PWD}/OAIContainerApiRequestBody.h \
    $${PWD}/OAIContainerApiResponse.h \
    $${PWD}/OAIContainerApiResult.h \
    $${PWD}/OAIContainerDeactivatedEvent.h \
    $${PWD}/OAIContainerInstanceEvent.h \
    $${PWD}/OAIContainerLogs.h \
    $${PWD}/OAICreateComposeDeploymentDescription.h \
    $${PWD}/OAICurrentUpgradeDomainProgressInfo.h \
    $${PWD}/OAIDayOfWeek.h \
    $${PWD}/OAIDeactivationIntentDescription.h \
    $${PWD}/OAIDeletePropertyBatchOperation.h \
    $${PWD}/OAIDeltaNodesCheckHealthEvaluation.h \
    $${PWD}/OAIDeployServicePackageToNodeDescription.h \
    $${PWD}/OAIDeployedApplicationHealth.h \
    $${PWD}/OAIDeployedApplicationHealthEvaluation.h \
    $${PWD}/OAIDeployedApplicationHealthReportCreatedEvent.h \
    $${PWD}/OAIDeployedApplicationHealthReportExpiredEvent.h \
    $${PWD}/OAIDeployedApplicationHealthState.h \
    $${PWD}/OAIDeployedApplicationHealthStateChunk.h \
    $${PWD}/OAIDeployedApplicationHealthStateChunkList.h \
    $${PWD}/OAIDeployedApplicationHealthStateFilter.h \
    $${PWD}/OAIDeployedApplicationInfo.h \
    $${PWD}/OAIDeployedApplicationStatus.h \
    $${PWD}/OAIDeployedApplicationsHealthEvaluation.h \
    $${PWD}/OAIDeployedCodePackageInfo.h \
    $${PWD}/OAIDeployedServiceHealthReportCreatedEvent.h \
    $${PWD}/OAIDeployedServiceHealthReportExpiredEvent.h \
    $${PWD}/OAIDeployedServicePackageHealth.h \
    $${PWD}/OAIDeployedServicePackageHealthEvaluation.h \
    $${PWD}/OAIDeployedServicePackageHealthState.h \
    $${PWD}/OAIDeployedServicePackageHealthStateChunk.h \
    $${PWD}/OAIDeployedServicePackageHealthStateChunkList.h \
    $${PWD}/OAIDeployedServicePackageHealthStateFilter.h \
    $${PWD}/OAIDeployedServicePackageInfo.h \
    $${PWD}/OAIDeployedServicePackagesHealthEvaluation.h \
    $${PWD}/OAIDeployedServiceReplicaDetailInfo.h \
    $${PWD}/OAIDeployedServiceReplicaInfo.h \
    $${PWD}/OAIDeployedServiceTypeInfo.h \
    $${PWD}/OAIDeployedStatefulServiceReplicaDetailInfo.h \
    $${PWD}/OAIDeployedStatefulServiceReplicaInfo.h \
    $${PWD}/OAIDeployedStatelessServiceInstanceDetailInfo.h \
    $${PWD}/OAIDeployedStatelessServiceInstanceInfo.h \
    $${PWD}/OAIDeploymentStatus.h \
    $${PWD}/OAIDoublePropertyValue.h \
    $${PWD}/OAIEnableBackupDescription.h \
    $${PWD}/OAIEnsureAvailabilitySafetyCheck.h \
    $${PWD}/OAIEnsurePartitionQurumSafetyCheck.h \
    $${PWD}/OAIEntityHealth.h \
    $${PWD}/OAIEntityHealthState.h \
    $${PWD}/OAIEntityHealthStateChunk.h \
    $${PWD}/OAIEntityHealthStateChunkList.h \
    $${PWD}/OAIEntityKind.h \
    $${PWD}/OAIEntityKindHealthStateCount.h \
    $${PWD}/OAIEntryPointStatus.h \
    $${PWD}/OAIEpoch.h \
    $${PWD}/OAIEventHealthEvaluation.h \
    $${PWD}/OAIExecutingFaultsChaosEvent.h \
    $${PWD}/OAIExternalStoreProvisionApplicationTypeDescription.h \
    $${PWD}/OAIFabricCodeVersionInfo.h \
    $${PWD}/OAIFabricConfigVersionInfo.h \
    $${PWD}/OAIFabricError.h \
    $${PWD}/OAIFabricErrorCodes.h \
    $${PWD}/OAIFabricErrorError.h \
    $${PWD}/OAIFabricEvent.h \
    $${PWD}/OAIFabricEventKind.h \
    $${PWD}/OAIFabricReplicaStatus.h \
    $${PWD}/OAIFailedPropertyBatchInfo.h \
    $${PWD}/OAIFailedUpgradeDomainProgressObject.h \
    $${PWD}/OAIFailureAction.h \
    $${PWD}/OAIFailureReason.h \
    $${PWD}/OAIFailureUpgradeDomainProgressInfo.h \
    $${PWD}/OAIFileInfo.h \
    $${PWD}/OAIFileShareBackupStorageDescription.h \
    $${PWD}/OAIFileVersion.h \
    $${PWD}/OAIFolderInfo.h \
    $${PWD}/OAIFrequencyBasedBackupScheduleDescription.h \
    $${PWD}/OAIGetBackupByStorageQueryDescription.h \
    $${PWD}/OAIGetPropertyBatchOperation.h \
    $${PWD}/OAIGuidPropertyValue.h \
    $${PWD}/OAIHealthEvaluation.h \
    $${PWD}/OAIHealthEvaluationKind.h \
    $${PWD}/OAIHealthEvaluationWrapper.h \
    $${PWD}/OAIHealthEvent.h \
    $${PWD}/OAIHealthInformation.h \
    $${PWD}/OAIHealthState.h \
    $${PWD}/OAIHealthStateCount.h \
    $${PWD}/OAIHealthStatistics.h \
    $${PWD}/OAIHostIsolationMode.h \
    $${PWD}/OAIHostType.h \
    $${PWD}/OAIImageStoreContent.h \
    $${PWD}/OAIImageStoreCopyDescription.h \
    $${PWD}/OAIInt64PropertyValue.h \
    $${PWD}/OAIInt64RangePartitionInformation.h \
    $${PWD}/OAIInvokeDataLossResult.h \
    $${PWD}/OAIInvokeQuorumLossResult.h \
    $${PWD}/OAIKeyValueStoreReplicaStatus.h \
    $${PWD}/OAILoadMetricReport.h \
    $${PWD}/OAILoadMetricReportInfo.h \
    $${PWD}/OAIMonitoringPolicyDescription.h \
    $${PWD}/OAIMoveCost.h \
    $${PWD}/OAINameDescription.h \
    $${PWD}/OAINamedPartitionInformation.h \
    $${PWD}/OAINamedPartitionSchemeDescription.h \
    $${PWD}/OAINodeAbortedEvent.h \
    $${PWD}/OAINodeAbortingEvent.h \
    $${PWD}/OAINodeAddedEvent.h \
    $${PWD}/OAINodeCloseEvent.h \
    $${PWD}/OAINodeClosingEvent.h \
    $${PWD}/OAINodeDeactivateCompleteEvent.h \
    $${PWD}/OAINodeDeactivateStartEvent.h \
    $${PWD}/OAINodeDeactivationInfo.h \
    $${PWD}/OAINodeDeactivationIntent.h \
    $${PWD}/OAINodeDeactivationStatus.h \
    $${PWD}/OAINodeDeactivationTask.h \
    $${PWD}/OAINodeDeactivationTaskId.h \
    $${PWD}/OAINodeDeactivationTaskType.h \
    $${PWD}/OAINodeDownEvent.h \
    $${PWD}/OAINodeEvent.h \
    $${PWD}/OAINodeHealth.h \
    $${PWD}/OAINodeHealthEvaluation.h \
    $${PWD}/OAINodeHealthReportCreatedEvent.h \
    $${PWD}/OAINodeHealthReportExpiredEvent.h \
    $${PWD}/OAINodeHealthState.h \
    $${PWD}/OAINodeHealthStateChunk.h \
    $${PWD}/OAINodeHealthStateChunkList.h \
    $${PWD}/OAINodeHealthStateFilter.h \
    $${PWD}/OAINodeId.h \
    $${PWD}/OAINodeImpact.h \
    $${PWD}/OAINodeInfo.h \
    $${PWD}/OAINodeLoadInfo.h \
    $${PWD}/OAINodeLoadMetricInformation.h \
    $${PWD}/OAINodeOpenFailedEvent.h \
    $${PWD}/OAINodeOpenedSuccessEvent.h \
    $${PWD}/OAINodeOpeningEvent.h \
    $${PWD}/OAINodeRemovedEvent.h \
    $${PWD}/OAINodeRepairImpactDescription.h \
    $${PWD}/OAINodeRepairTargetDescription.h \
    $${PWD}/OAINodeResult.h \
    $${PWD}/OAINodeStatus.h \
    $${PWD}/OAINodeTransitionProgress.h \
    $${PWD}/OAINodeTransitionResult.h \
    $${PWD}/OAINodeUpEvent.h \
    $${PWD}/OAINodeUpgradePhase.h \
    $${PWD}/OAINodeUpgradeProgressInfo.h \
    $${PWD}/OAINodesHealthEvaluation.h \
    $${PWD}/OAIOperationState.h \
    $${PWD}/OAIOperationStatus.h \
    $${PWD}/OAIOperationType.h \
    $${PWD}/OAIPackageSharingPolicyInfo.h \
    $${PWD}/OAIPackageSharingPolicyScope.h \
    $${PWD}/OAIPagedApplicationInfoList.h \
    $${PWD}/OAIPagedApplicationTypeInfoList.h \
    $${PWD}/OAIPagedBackupConfigurationInfoList.h \
    $${PWD}/OAIPagedBackupEntityList.h \
    $${PWD}/OAIPagedBackupInfoList.h \
    $${PWD}/OAIPagedBackupPolicyDescriptionList.h \
    $${PWD}/OAIPagedComposeDeploymentStatusInfoList.h \
    $${PWD}/OAIPagedDeployedApplicationInfoList.h \
    $${PWD}/OAIPagedNodeInfoList.h \
    $${PWD}/OAIPagedPropertyInfoList.h \
    $${PWD}/OAIPagedReplicaInfoList.h \
    $${PWD}/OAIPagedServiceInfoList.h \
    $${PWD}/OAIPagedServicePartitionInfoList.h \
    $${PWD}/OAIPagedSubNameInfoList.h \
    $${PWD}/OAIPartitionAccessStatus.h \
    $${PWD}/OAIPartitionAnalysisEvent.h \
    $${PWD}/OAIPartitionBackupConfigurationInfo.h \
    $${PWD}/OAIPartitionBackupEntity.h \
    $${PWD}/OAIPartitionDataLossProgress.h \
    $${PWD}/OAIPartitionEvent.h \
    $${PWD}/OAIPartitionHealth.h \
    $${PWD}/OAIPartitionHealthEvaluation.h \
    $${PWD}/OAIPartitionHealthReportCreatedEvent.h \
    $${PWD}/OAIPartitionHealthReportExpiredEvent.h \
    $${PWD}/OAIPartitionHealthState.h \
    $${PWD}/OAIPartitionHealthStateChunk.h \
    $${PWD}/OAIPartitionHealthStateChunkList.h \
    $${PWD}/OAIPartitionHealthStateFilter.h \
    $${PWD}/OAIPartitionInformation.h \
    $${PWD}/OAIPartitionInstanceCountScaleMechanism.h \
    $${PWD}/OAIPartitionLoadInformation.h \
    $${PWD}/OAIPartitionPrimaryMoveAnalysisEvent.h \
    $${PWD}/OAIPartitionQuorumLossProgress.h \
    $${PWD}/OAIPartitionReconfigurationCompletedEvent.h \
    $${PWD}/OAIPartitionRestartProgress.h \
    $${PWD}/OAIPartitionSafetyCheck.h \
    $${PWD}/OAIPartitionScheme.h \
    $${PWD}/OAIPartitionSchemeDescription.h \
    $${PWD}/OAIPartitionsHealthEvaluation.h \
    $${PWD}/OAIPrimaryReplicatorStatus.h \
    $${PWD}/OAIProcessDeactivatedEvent.h \
    $${PWD}/OAIPropertyBatchDescriptionList.h \
    $${PWD}/OAIPropertyBatchInfo.h \
    $${PWD}/OAIPropertyBatchInfoKind.h \
    $${PWD}/OAIPropertyBatchOperation.h \
    $${PWD}/OAIPropertyBatchOperationKind.h \
    $${PWD}/OAIPropertyDescription.h \
    $${PWD}/OAIPropertyInfo.h \
    $${PWD}/OAIPropertyMetadata.h \
    $${PWD}/OAIPropertyValue.h \
    $${PWD}/OAIPropertyValueKind.h \
    $${PWD}/OAIProvisionApplicationTypeDescription.h \
    $${PWD}/OAIProvisionApplicationTypeDescriptionBase.h \
    $${PWD}/OAIProvisionApplicationTypeKind.h \
    $${PWD}/OAIProvisionFabricDescription.h \
    $${PWD}/OAIPutPropertyBatchOperation.h \
    $${PWD}/OAIReconfigurationInformation.h \
    $${PWD}/OAIReconfigurationPhase.h \
    $${PWD}/OAIReconfigurationType.h \
    $${PWD}/OAIRegistryCredential.h \
    $${PWD}/OAIRemoteReplicatorAcknowledgementDetail.h \
    $${PWD}/OAIRemoteReplicatorAcknowledgementStatus.h \
    $${PWD}/OAIRemoteReplicatorStatus.h \
    $${PWD}/OAIRepairImpactDescriptionBase.h \
    $${PWD}/OAIRepairImpactKind.h \
    $${PWD}/OAIRepairTargetDescriptionBase.h \
    $${PWD}/OAIRepairTargetKind.h \
    $${PWD}/OAIRepairTask.h \
    $${PWD}/OAIRepairTaskApproveDescription.h \
    $${PWD}/OAIRepairTaskCancelDescription.h \
    $${PWD}/OAIRepairTaskDeleteDescription.h \
    $${PWD}/OAIRepairTaskHealthCheckState.h \
    $${PWD}/OAIRepairTaskHistory.h \
    $${PWD}/OAIRepairTaskUpdateHealthPolicyDescription.h \
    $${PWD}/OAIRepairTaskUpdateInfo.h \
    $${PWD}/OAIReplicaEvent.h \
    $${PWD}/OAIReplicaHealth.h \
    $${PWD}/OAIReplicaHealthEvaluation.h \
    $${PWD}/OAIReplicaHealthState.h \
    $${PWD}/OAIReplicaHealthStateChunk.h \
    $${PWD}/OAIReplicaHealthStateChunkList.h \
    $${PWD}/OAIReplicaHealthStateFilter.h \
    $${PWD}/OAIReplicaInfo.h \
    $${PWD}/OAIReplicaKind.h \
    $${PWD}/OAIReplicaRole.h \
    $${PWD}/OAIReplicaStatus.h \
    $${PWD}/OAIReplicaStatusBase.h \
    $${PWD}/OAIReplicasHealthEvaluation.h \
    $${PWD}/OAIReplicatorOperationName.h \
    $${PWD}/OAIReplicatorQueueStatus.h \
    $${PWD}/OAIReplicatorStatus.h \
    $${PWD}/OAIResolvedServiceEndpoint.h \
    $${PWD}/OAIResolvedServicePartition.h \
    $${PWD}/OAIRestartDeployedCodePackageDescription.h \
    $${PWD}/OAIRestartNodeDescription.h \
    $${PWD}/OAIRestartPartitionResult.h \
    $${PWD}/OAIRestorePartitionDescription.h \
    $${PWD}/OAIRestoreProgressInfo.h \
    $${PWD}/OAIRestoreState.h \
    $${PWD}/OAIResumeApplicationUpgradeDescription.h \
    $${PWD}/OAIResumeClusterUpgradeDescription.h \
    $${PWD}/OAIRollingUpgradeUpdateDescription.h \
    $${PWD}/OAISafetyCheck.h \
    $${PWD}/OAISafetyCheckKind.h \
    $${PWD}/OAISafetyCheckWrapper.h \
    $${PWD}/OAIScalingMechanismDescription.h \
    $${PWD}/OAIScalingMechanismKind.h \
    $${PWD}/OAIScalingPolicyDescription.h \
    $${PWD}/OAIScalingTriggerDescription.h \
    $${PWD}/OAIScalingTriggerKind.h \
    $${PWD}/OAISecondaryActiveReplicatorStatus.h \
    $${PWD}/OAISecondaryIdleReplicatorStatus.h \
    $${PWD}/OAISecondaryReplicatorStatus.h \
    $${PWD}/OAISeedNodeSafetyCheck.h \
    $${PWD}/OAISelectedPartition.h \
    $${PWD}/OAIServiceBackupConfigurationInfo.h \
    $${PWD}/OAIServiceBackupEntity.h \
    $${PWD}/OAIServiceCorrelationDescription.h \
    $${PWD}/OAIServiceCorrelationScheme.h \
    $${PWD}/OAIServiceCreatedEvent.h \
    $${PWD}/OAIServiceDeletedEvent.h \
    $${PWD}/OAIServiceDescription.h \
    $${PWD}/OAIServiceEndpointRole.h \
    $${PWD}/OAIServiceEvent.h \
    $${PWD}/OAIServiceFromTemplateDescription.h \
    $${PWD}/OAIServiceHealth.h \
    $${PWD}/OAIServiceHealthEvaluation.h \
    $${PWD}/OAIServiceHealthReportCreatedEvent.h \
    $${PWD}/OAIServiceHealthReportExpiredEvent.h \
    $${PWD}/OAIServiceHealthState.h \
    $${PWD}/OAIServiceHealthStateChunk.h \
    $${PWD}/OAIServiceHealthStateChunkList.h \
    $${PWD}/OAIServiceHealthStateFilter.h \
    $${PWD}/OAIServiceInfo.h \
    $${PWD}/OAIServiceKind.h \
    $${PWD}/OAIServiceLoadMetricDescription.h \
    $${PWD}/OAIServiceLoadMetricWeight.h \
    $${PWD}/OAIServiceNameInfo.h \
    $${PWD}/OAIServiceOperationName.h \
    $${PWD}/OAIServicePackageActivationMode.h \
    $${PWD}/OAIServicePartitionInfo.h \
    $${PWD}/OAIServicePartitionKind.h \
    $${PWD}/OAIServicePartitionStatus.h \
    $${PWD}/OAIServicePlacementInvalidDomainPolicyDescription.h \
    $${PWD}/OAIServicePlacementNonPartiallyPlaceServicePolicyDescription.h \
    $${PWD}/OAIServicePlacementPolicyDescription.h \
    $${PWD}/OAIServicePlacementPolicyType.h \
    $${PWD}/OAIServicePlacementPreferPrimaryDomainPolicyDescription.h \
    $${PWD}/OAIServicePlacementRequireDomainDistributionPolicyDescription.h \
    $${PWD}/OAIServicePlacementRequiredDomainPolicyDescription.h \
    $${PWD}/OAIServiceStatus.h \
    $${PWD}/OAIServiceTypeDescription.h \
    $${PWD}/OAIServiceTypeExtensionDescription.h \
    $${PWD}/OAIServiceTypeHealthPolicy.h \
    $${PWD}/OAIServiceTypeHealthPolicyMapItem.h \
    $${PWD}/OAIServiceTypeInfo.h \
    $${PWD}/OAIServiceTypeManifest.h \
    $${PWD}/OAIServiceTypeRegistrationStatus.h \
    $${PWD}/OAIServiceUpdateDescription.h \
    $${PWD}/OAIServicesHealthEvaluation.h \
    $${PWD}/OAISingletonPartitionInformation.h \
    $${PWD}/OAISingletonPartitionSchemeDescription.h \
    $${PWD}/OAIStartClusterUpgradeDescription.h \
    $${PWD}/OAIStartedChaosEvent.h \
    $${PWD}/OAIStatefulReplicaHealthReportCreatedEvent.h \
    $${PWD}/OAIStatefulReplicaHealthReportExpiredEvent.h \
    $${PWD}/OAIStatefulServiceDescription.h \
    $${PWD}/OAIStatefulServiceInfo.h \
    $${PWD}/OAIStatefulServicePartitionInfo.h \
    $${PWD}/OAIStatefulServiceReplicaHealth.h \
    $${PWD}/OAIStatefulServiceReplicaHealthState.h \
    $${PWD}/OAIStatefulServiceReplicaInfo.h \
    $${PWD}/OAIStatefulServiceTypeDescription.h \
    $${PWD}/OAIStatefulServiceUpdateDescription.h \
    $${PWD}/OAIStatelessReplicaHealthReportCreatedEvent.h \
    $${PWD}/OAIStatelessReplicaHealthReportExpiredEvent.h \
    $${PWD}/OAIStatelessServiceDescription.h \
    $${PWD}/OAIStatelessServiceInfo.h \
    $${PWD}/OAIStatelessServiceInstanceHealth.h \
    $${PWD}/OAIStatelessServiceInstanceHealthState.h \
    $${PWD}/OAIStatelessServiceInstanceInfo.h \
    $${PWD}/OAIStatelessServicePartitionInfo.h \
    $${PWD}/OAIStatelessServiceTypeDescription.h \
    $${PWD}/OAIStatelessServiceUpdateDescription.h \
    $${PWD}/OAIStoppedChaosEvent.h \
    $${PWD}/OAIStringPropertyValue.h \
    $${PWD}/OAISuccessfulPropertyBatchInfo.h \
    $${PWD}/OAISystemApplicationHealthEvaluation.h \
    $${PWD}/OAITestErrorChaosEvent.h \
    $${PWD}/OAITimeBasedBackupScheduleDescription.h \
    $${PWD}/OAITimeOfDay.h \
    $${PWD}/OAITimeRange.h \
    $${PWD}/OAIUniformInt64RangePartitionSchemeDescription.h \
    $${PWD}/OAIUnprovisionApplicationTypeDescriptionInfo.h \
    $${PWD}/OAIUnprovisionFabricDescription.h \
    $${PWD}/OAIUpdateClusterUpgradeDescription.h \
    $${PWD}/OAIUpgradeDomainDeltaNodesCheckHealthEvaluation.h \
    $${PWD}/OAIUpgradeDomainInfo.h \
    $${PWD}/OAIUpgradeDomainNodesHealthEvaluation.h \
    $${PWD}/OAIUpgradeDomainState.h \
    $${PWD}/OAIUpgradeKind.h \
    $${PWD}/OAIUpgradeMode.h \
    $${PWD}/OAIUpgradeOrchestrationServiceState.h \
    $${PWD}/OAIUpgradeOrchestrationServiceStateSummary.h \
    $${PWD}/OAIUpgradeState.h \
    $${PWD}/OAIUpgradeType.h \
    $${PWD}/OAIUploadChunkRange.h \
    $${PWD}/OAIUploadSession.h \
    $${PWD}/OAIUploadSessionInfo.h \
    $${PWD}/OAIValidationFailedChaosEvent.h \
    $${PWD}/OAIWaitForInbuildReplicaSafetyCheck.h \
    $${PWD}/OAIWaitForPrimaryPlacementSafetyCheck.h \
    $${PWD}/OAIWaitForPrimarySwapSafetyCheck.h \
    $${PWD}/OAIWaitForReconfigurationSafetyCheck.h \
    $${PWD}/OAIWaitingChaosEvent.h \
# APIs
    $${PWD}/OAIApplicationApi.h \
    $${PWD}/OAIApplicationTypeApi.h \
    $${PWD}/OAIBackupRestoreApi.h \
    $${PWD}/OAIChaosApi.h \
    $${PWD}/OAIClusterApi.h \
    $${PWD}/OAICodePackageApi.h \
    $${PWD}/OAIComposeDeploymentApi.h \
    $${PWD}/OAIEventsStoreApi.h \
    $${PWD}/OAIFaultsApi.h \
    $${PWD}/OAIImageStoreApi.h \
    $${PWD}/OAIInfrastructureApi.h \
    $${PWD}/OAINodeApi.h \
    $${PWD}/OAIPartitionApi.h \
    $${PWD}/OAIPropertyManagementApi.h \
    $${PWD}/OAIRepairManagementApi.h \
    $${PWD}/OAIReplicaApi.h \
    $${PWD}/OAIServiceApi.h \
    $${PWD}/OAIServicePackageApi.h \
    $${PWD}/OAIServiceTypeApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAadMetadata.cpp \
    $${PWD}/OAIAadMetadataObject.cpp \
    $${PWD}/OAIAddRemoveIncrementalNamedPartitionScalingMechanism.cpp \
    $${PWD}/OAIAnalysisEventMetadata.cpp \
    $${PWD}/OAIApplicationBackupConfigurationInfo.cpp \
    $${PWD}/OAIApplicationBackupEntity.cpp \
    $${PWD}/OAIApplicationCapacityDescription.cpp \
    $${PWD}/OAIApplicationCreatedEvent.cpp \
    $${PWD}/OAIApplicationDefinitionKind.cpp \
    $${PWD}/OAIApplicationDeletedEvent.cpp \
    $${PWD}/OAIApplicationDescription.cpp \
    $${PWD}/OAIApplicationEvent.cpp \
    $${PWD}/OAIApplicationHealth.cpp \
    $${PWD}/OAIApplicationHealthEvaluation.cpp \
    $${PWD}/OAIApplicationHealthPolicies.cpp \
    $${PWD}/OAIApplicationHealthPolicy.cpp \
    $${PWD}/OAIApplicationHealthPolicyMapItem.cpp \
    $${PWD}/OAIApplicationHealthReportCreatedEvent.cpp \
    $${PWD}/OAIApplicationHealthReportExpiredEvent.cpp \
    $${PWD}/OAIApplicationHealthState.cpp \
    $${PWD}/OAIApplicationHealthStateChunk.cpp \
    $${PWD}/OAIApplicationHealthStateChunkList.cpp \
    $${PWD}/OAIApplicationHealthStateFilter.cpp \
    $${PWD}/OAIApplicationInfo.cpp \
    $${PWD}/OAIApplicationLoadInfo.cpp \
    $${PWD}/OAIApplicationMetricDescription.cpp \
    $${PWD}/OAIApplicationNameInfo.cpp \
    $${PWD}/OAIApplicationPackageCleanupPolicy.cpp \
    $${PWD}/OAIApplicationParameter.cpp \
    $${PWD}/OAIApplicationStatus.cpp \
    $${PWD}/OAIApplicationTypeApplicationsHealthEvaluation.cpp \
    $${PWD}/OAIApplicationTypeDefinitionKind.cpp \
    $${PWD}/OAIApplicationTypeHealthPolicyMapItem.cpp \
    $${PWD}/OAIApplicationTypeImageStorePath.cpp \
    $${PWD}/OAIApplicationTypeInfo.cpp \
    $${PWD}/OAIApplicationTypeManifest.cpp \
    $${PWD}/OAIApplicationTypeStatus.cpp \
    $${PWD}/OAIApplicationUpgradeCompleteEvent.cpp \
    $${PWD}/OAIApplicationUpgradeDescription.cpp \
    $${PWD}/OAIApplicationUpgradeDomainCompleteEvent.cpp \
    $${PWD}/OAIApplicationUpgradeProgressInfo.cpp \
    $${PWD}/OAIApplicationUpgradeRollbackCompleteEvent.cpp \
    $${PWD}/OAIApplicationUpgradeRollbackStartEvent.cpp \
    $${PWD}/OAIApplicationUpgradeStartEvent.cpp \
    $${PWD}/OAIApplicationUpgradeUpdateDescription.cpp \
    $${PWD}/OAIApplicationsHealthEvaluation.cpp \
    $${PWD}/OAIAveragePartitionLoadScalingTrigger.cpp \
    $${PWD}/OAIAverageServiceLoadScalingTrigger.cpp \
    $${PWD}/OAIAzureBlobBackupStorageDescription.cpp \
    $${PWD}/OAIBackupConfigurationInfo.cpp \
    $${PWD}/OAIBackupEntity.cpp \
    $${PWD}/OAIBackupEntityKind.cpp \
    $${PWD}/OAIBackupEpoch.cpp \
    $${PWD}/OAIBackupInfo.cpp \
    $${PWD}/OAIBackupPartitionDescription.cpp \
    $${PWD}/OAIBackupPolicyDescription.cpp \
    $${PWD}/OAIBackupPolicyScope.cpp \
    $${PWD}/OAIBackupProgressInfo.cpp \
    $${PWD}/OAIBackupScheduleDescription.cpp \
    $${PWD}/OAIBackupScheduleFrequencyType.cpp \
    $${PWD}/OAIBackupScheduleKind.cpp \
    $${PWD}/OAIBackupState.cpp \
    $${PWD}/OAIBackupStorageDescription.cpp \
    $${PWD}/OAIBackupStorageKind.cpp \
    $${PWD}/OAIBackupSuspensionInfo.cpp \
    $${PWD}/OAIBackupSuspensionScope.cpp \
    $${PWD}/OAIBackupType.cpp \
    $${PWD}/OAIBinaryPropertyValue.cpp \
    $${PWD}/OAIChaos.cpp \
    $${PWD}/OAIChaosContext.cpp \
    $${PWD}/OAIChaosEvent.cpp \
    $${PWD}/OAIChaosEventKind.cpp \
    $${PWD}/OAIChaosEventWrapper.cpp \
    $${PWD}/OAIChaosEventsSegment.cpp \
    $${PWD}/OAIChaosMovePrimaryFaultScheduledEvent.cpp \
    $${PWD}/OAIChaosMoveSecondaryFaultScheduledEvent.cpp \
    $${PWD}/OAIChaosParameters.cpp \
    $${PWD}/OAIChaosParametersDictionaryItem.cpp \
    $${PWD}/OAIChaosRemoveReplicaFaultCompletedEvent.cpp \
    $${PWD}/OAIChaosRemoveReplicaFaultScheduledEvent.cpp \
    $${PWD}/OAIChaosRestartCodePackageFaultCompletedEvent.cpp \
    $${PWD}/OAIChaosRestartCodePackageFaultScheduledEvent.cpp \
    $${PWD}/OAIChaosRestartNodeFaultCompletedEvent.cpp \
    $${PWD}/OAIChaosRestartNodeFaultScheduledEvent.cpp \
    $${PWD}/OAIChaosRestartReplicaFaultScheduledEvent.cpp \
    $${PWD}/OAIChaosSchedule.cpp \
    $${PWD}/OAIChaosScheduleDescription.cpp \
    $${PWD}/OAIChaosScheduleJob.cpp \
    $${PWD}/OAIChaosScheduleJobActiveDaysOfWeek.cpp \
    $${PWD}/OAIChaosScheduleStatus.cpp \
    $${PWD}/OAIChaosStartedEvent.cpp \
    $${PWD}/OAIChaosStatus.cpp \
    $${PWD}/OAIChaosStoppedEvent.cpp \
    $${PWD}/OAIChaosTargetFilter.cpp \
    $${PWD}/OAICheckExistsPropertyBatchOperation.cpp \
    $${PWD}/OAICheckSequencePropertyBatchOperation.cpp \
    $${PWD}/OAICheckValuePropertyBatchOperation.cpp \
    $${PWD}/OAIClusterConfiguration.cpp \
    $${PWD}/OAIClusterConfigurationUpgradeDescription.cpp \
    $${PWD}/OAIClusterConfigurationUpgradeStatusInfo.cpp \
    $${PWD}/OAIClusterEvent.cpp \
    $${PWD}/OAIClusterHealth.cpp \
    $${PWD}/OAIClusterHealthChunk.cpp \
    $${PWD}/OAIClusterHealthChunkQueryDescription.cpp \
    $${PWD}/OAIClusterHealthPolicies.cpp \
    $${PWD}/OAIClusterHealthPolicy.cpp \
    $${PWD}/OAIClusterHealthReportCreatedEvent.cpp \
    $${PWD}/OAIClusterHealthReportExpiredEvent.cpp \
    $${PWD}/OAIClusterManifest.cpp \
    $${PWD}/OAIClusterUpgradeCompleteEvent.cpp \
    $${PWD}/OAIClusterUpgradeDescriptionObject.cpp \
    $${PWD}/OAIClusterUpgradeDomainCompleteEvent.cpp \
    $${PWD}/OAIClusterUpgradeHealthPolicyObject.cpp \
    $${PWD}/OAIClusterUpgradeProgressObject.cpp \
    $${PWD}/OAIClusterUpgradeRollbackCompleteEvent.cpp \
    $${PWD}/OAIClusterUpgradeRollbackStartEvent.cpp \
    $${PWD}/OAIClusterUpgradeStartEvent.cpp \
    $${PWD}/OAICodePackageEntryPoint.cpp \
    $${PWD}/OAICodePackageEntryPointStatistics.cpp \
    $${PWD}/OAIComposeDeploymentStatus.cpp \
    $${PWD}/OAIComposeDeploymentStatusInfo.cpp \
    $${PWD}/OAIComposeDeploymentUpgradeDescription.cpp \
    $${PWD}/OAIComposeDeploymentUpgradeProgressInfo.cpp \
    $${PWD}/OAIComposeDeploymentUpgradeState.cpp \
    $${PWD}/OAIContainerApiRequestBody.cpp \
    $${PWD}/OAIContainerApiResponse.cpp \
    $${PWD}/OAIContainerApiResult.cpp \
    $${PWD}/OAIContainerDeactivatedEvent.cpp \
    $${PWD}/OAIContainerInstanceEvent.cpp \
    $${PWD}/OAIContainerLogs.cpp \
    $${PWD}/OAICreateComposeDeploymentDescription.cpp \
    $${PWD}/OAICurrentUpgradeDomainProgressInfo.cpp \
    $${PWD}/OAIDayOfWeek.cpp \
    $${PWD}/OAIDeactivationIntentDescription.cpp \
    $${PWD}/OAIDeletePropertyBatchOperation.cpp \
    $${PWD}/OAIDeltaNodesCheckHealthEvaluation.cpp \
    $${PWD}/OAIDeployServicePackageToNodeDescription.cpp \
    $${PWD}/OAIDeployedApplicationHealth.cpp \
    $${PWD}/OAIDeployedApplicationHealthEvaluation.cpp \
    $${PWD}/OAIDeployedApplicationHealthReportCreatedEvent.cpp \
    $${PWD}/OAIDeployedApplicationHealthReportExpiredEvent.cpp \
    $${PWD}/OAIDeployedApplicationHealthState.cpp \
    $${PWD}/OAIDeployedApplicationHealthStateChunk.cpp \
    $${PWD}/OAIDeployedApplicationHealthStateChunkList.cpp \
    $${PWD}/OAIDeployedApplicationHealthStateFilter.cpp \
    $${PWD}/OAIDeployedApplicationInfo.cpp \
    $${PWD}/OAIDeployedApplicationStatus.cpp \
    $${PWD}/OAIDeployedApplicationsHealthEvaluation.cpp \
    $${PWD}/OAIDeployedCodePackageInfo.cpp \
    $${PWD}/OAIDeployedServiceHealthReportCreatedEvent.cpp \
    $${PWD}/OAIDeployedServiceHealthReportExpiredEvent.cpp \
    $${PWD}/OAIDeployedServicePackageHealth.cpp \
    $${PWD}/OAIDeployedServicePackageHealthEvaluation.cpp \
    $${PWD}/OAIDeployedServicePackageHealthState.cpp \
    $${PWD}/OAIDeployedServicePackageHealthStateChunk.cpp \
    $${PWD}/OAIDeployedServicePackageHealthStateChunkList.cpp \
    $${PWD}/OAIDeployedServicePackageHealthStateFilter.cpp \
    $${PWD}/OAIDeployedServicePackageInfo.cpp \
    $${PWD}/OAIDeployedServicePackagesHealthEvaluation.cpp \
    $${PWD}/OAIDeployedServiceReplicaDetailInfo.cpp \
    $${PWD}/OAIDeployedServiceReplicaInfo.cpp \
    $${PWD}/OAIDeployedServiceTypeInfo.cpp \
    $${PWD}/OAIDeployedStatefulServiceReplicaDetailInfo.cpp \
    $${PWD}/OAIDeployedStatefulServiceReplicaInfo.cpp \
    $${PWD}/OAIDeployedStatelessServiceInstanceDetailInfo.cpp \
    $${PWD}/OAIDeployedStatelessServiceInstanceInfo.cpp \
    $${PWD}/OAIDeploymentStatus.cpp \
    $${PWD}/OAIDoublePropertyValue.cpp \
    $${PWD}/OAIEnableBackupDescription.cpp \
    $${PWD}/OAIEnsureAvailabilitySafetyCheck.cpp \
    $${PWD}/OAIEnsurePartitionQurumSafetyCheck.cpp \
    $${PWD}/OAIEntityHealth.cpp \
    $${PWD}/OAIEntityHealthState.cpp \
    $${PWD}/OAIEntityHealthStateChunk.cpp \
    $${PWD}/OAIEntityHealthStateChunkList.cpp \
    $${PWD}/OAIEntityKind.cpp \
    $${PWD}/OAIEntityKindHealthStateCount.cpp \
    $${PWD}/OAIEntryPointStatus.cpp \
    $${PWD}/OAIEpoch.cpp \
    $${PWD}/OAIEventHealthEvaluation.cpp \
    $${PWD}/OAIExecutingFaultsChaosEvent.cpp \
    $${PWD}/OAIExternalStoreProvisionApplicationTypeDescription.cpp \
    $${PWD}/OAIFabricCodeVersionInfo.cpp \
    $${PWD}/OAIFabricConfigVersionInfo.cpp \
    $${PWD}/OAIFabricError.cpp \
    $${PWD}/OAIFabricErrorCodes.cpp \
    $${PWD}/OAIFabricErrorError.cpp \
    $${PWD}/OAIFabricEvent.cpp \
    $${PWD}/OAIFabricEventKind.cpp \
    $${PWD}/OAIFabricReplicaStatus.cpp \
    $${PWD}/OAIFailedPropertyBatchInfo.cpp \
    $${PWD}/OAIFailedUpgradeDomainProgressObject.cpp \
    $${PWD}/OAIFailureAction.cpp \
    $${PWD}/OAIFailureReason.cpp \
    $${PWD}/OAIFailureUpgradeDomainProgressInfo.cpp \
    $${PWD}/OAIFileInfo.cpp \
    $${PWD}/OAIFileShareBackupStorageDescription.cpp \
    $${PWD}/OAIFileVersion.cpp \
    $${PWD}/OAIFolderInfo.cpp \
    $${PWD}/OAIFrequencyBasedBackupScheduleDescription.cpp \
    $${PWD}/OAIGetBackupByStorageQueryDescription.cpp \
    $${PWD}/OAIGetPropertyBatchOperation.cpp \
    $${PWD}/OAIGuidPropertyValue.cpp \
    $${PWD}/OAIHealthEvaluation.cpp \
    $${PWD}/OAIHealthEvaluationKind.cpp \
    $${PWD}/OAIHealthEvaluationWrapper.cpp \
    $${PWD}/OAIHealthEvent.cpp \
    $${PWD}/OAIHealthInformation.cpp \
    $${PWD}/OAIHealthState.cpp \
    $${PWD}/OAIHealthStateCount.cpp \
    $${PWD}/OAIHealthStatistics.cpp \
    $${PWD}/OAIHostIsolationMode.cpp \
    $${PWD}/OAIHostType.cpp \
    $${PWD}/OAIImageStoreContent.cpp \
    $${PWD}/OAIImageStoreCopyDescription.cpp \
    $${PWD}/OAIInt64PropertyValue.cpp \
    $${PWD}/OAIInt64RangePartitionInformation.cpp \
    $${PWD}/OAIInvokeDataLossResult.cpp \
    $${PWD}/OAIInvokeQuorumLossResult.cpp \
    $${PWD}/OAIKeyValueStoreReplicaStatus.cpp \
    $${PWD}/OAILoadMetricReport.cpp \
    $${PWD}/OAILoadMetricReportInfo.cpp \
    $${PWD}/OAIMonitoringPolicyDescription.cpp \
    $${PWD}/OAIMoveCost.cpp \
    $${PWD}/OAINameDescription.cpp \
    $${PWD}/OAINamedPartitionInformation.cpp \
    $${PWD}/OAINamedPartitionSchemeDescription.cpp \
    $${PWD}/OAINodeAbortedEvent.cpp \
    $${PWD}/OAINodeAbortingEvent.cpp \
    $${PWD}/OAINodeAddedEvent.cpp \
    $${PWD}/OAINodeCloseEvent.cpp \
    $${PWD}/OAINodeClosingEvent.cpp \
    $${PWD}/OAINodeDeactivateCompleteEvent.cpp \
    $${PWD}/OAINodeDeactivateStartEvent.cpp \
    $${PWD}/OAINodeDeactivationInfo.cpp \
    $${PWD}/OAINodeDeactivationIntent.cpp \
    $${PWD}/OAINodeDeactivationStatus.cpp \
    $${PWD}/OAINodeDeactivationTask.cpp \
    $${PWD}/OAINodeDeactivationTaskId.cpp \
    $${PWD}/OAINodeDeactivationTaskType.cpp \
    $${PWD}/OAINodeDownEvent.cpp \
    $${PWD}/OAINodeEvent.cpp \
    $${PWD}/OAINodeHealth.cpp \
    $${PWD}/OAINodeHealthEvaluation.cpp \
    $${PWD}/OAINodeHealthReportCreatedEvent.cpp \
    $${PWD}/OAINodeHealthReportExpiredEvent.cpp \
    $${PWD}/OAINodeHealthState.cpp \
    $${PWD}/OAINodeHealthStateChunk.cpp \
    $${PWD}/OAINodeHealthStateChunkList.cpp \
    $${PWD}/OAINodeHealthStateFilter.cpp \
    $${PWD}/OAINodeId.cpp \
    $${PWD}/OAINodeImpact.cpp \
    $${PWD}/OAINodeInfo.cpp \
    $${PWD}/OAINodeLoadInfo.cpp \
    $${PWD}/OAINodeLoadMetricInformation.cpp \
    $${PWD}/OAINodeOpenFailedEvent.cpp \
    $${PWD}/OAINodeOpenedSuccessEvent.cpp \
    $${PWD}/OAINodeOpeningEvent.cpp \
    $${PWD}/OAINodeRemovedEvent.cpp \
    $${PWD}/OAINodeRepairImpactDescription.cpp \
    $${PWD}/OAINodeRepairTargetDescription.cpp \
    $${PWD}/OAINodeResult.cpp \
    $${PWD}/OAINodeStatus.cpp \
    $${PWD}/OAINodeTransitionProgress.cpp \
    $${PWD}/OAINodeTransitionResult.cpp \
    $${PWD}/OAINodeUpEvent.cpp \
    $${PWD}/OAINodeUpgradePhase.cpp \
    $${PWD}/OAINodeUpgradeProgressInfo.cpp \
    $${PWD}/OAINodesHealthEvaluation.cpp \
    $${PWD}/OAIOperationState.cpp \
    $${PWD}/OAIOperationStatus.cpp \
    $${PWD}/OAIOperationType.cpp \
    $${PWD}/OAIPackageSharingPolicyInfo.cpp \
    $${PWD}/OAIPackageSharingPolicyScope.cpp \
    $${PWD}/OAIPagedApplicationInfoList.cpp \
    $${PWD}/OAIPagedApplicationTypeInfoList.cpp \
    $${PWD}/OAIPagedBackupConfigurationInfoList.cpp \
    $${PWD}/OAIPagedBackupEntityList.cpp \
    $${PWD}/OAIPagedBackupInfoList.cpp \
    $${PWD}/OAIPagedBackupPolicyDescriptionList.cpp \
    $${PWD}/OAIPagedComposeDeploymentStatusInfoList.cpp \
    $${PWD}/OAIPagedDeployedApplicationInfoList.cpp \
    $${PWD}/OAIPagedNodeInfoList.cpp \
    $${PWD}/OAIPagedPropertyInfoList.cpp \
    $${PWD}/OAIPagedReplicaInfoList.cpp \
    $${PWD}/OAIPagedServiceInfoList.cpp \
    $${PWD}/OAIPagedServicePartitionInfoList.cpp \
    $${PWD}/OAIPagedSubNameInfoList.cpp \
    $${PWD}/OAIPartitionAccessStatus.cpp \
    $${PWD}/OAIPartitionAnalysisEvent.cpp \
    $${PWD}/OAIPartitionBackupConfigurationInfo.cpp \
    $${PWD}/OAIPartitionBackupEntity.cpp \
    $${PWD}/OAIPartitionDataLossProgress.cpp \
    $${PWD}/OAIPartitionEvent.cpp \
    $${PWD}/OAIPartitionHealth.cpp \
    $${PWD}/OAIPartitionHealthEvaluation.cpp \
    $${PWD}/OAIPartitionHealthReportCreatedEvent.cpp \
    $${PWD}/OAIPartitionHealthReportExpiredEvent.cpp \
    $${PWD}/OAIPartitionHealthState.cpp \
    $${PWD}/OAIPartitionHealthStateChunk.cpp \
    $${PWD}/OAIPartitionHealthStateChunkList.cpp \
    $${PWD}/OAIPartitionHealthStateFilter.cpp \
    $${PWD}/OAIPartitionInformation.cpp \
    $${PWD}/OAIPartitionInstanceCountScaleMechanism.cpp \
    $${PWD}/OAIPartitionLoadInformation.cpp \
    $${PWD}/OAIPartitionPrimaryMoveAnalysisEvent.cpp \
    $${PWD}/OAIPartitionQuorumLossProgress.cpp \
    $${PWD}/OAIPartitionReconfigurationCompletedEvent.cpp \
    $${PWD}/OAIPartitionRestartProgress.cpp \
    $${PWD}/OAIPartitionSafetyCheck.cpp \
    $${PWD}/OAIPartitionScheme.cpp \
    $${PWD}/OAIPartitionSchemeDescription.cpp \
    $${PWD}/OAIPartitionsHealthEvaluation.cpp \
    $${PWD}/OAIPrimaryReplicatorStatus.cpp \
    $${PWD}/OAIProcessDeactivatedEvent.cpp \
    $${PWD}/OAIPropertyBatchDescriptionList.cpp \
    $${PWD}/OAIPropertyBatchInfo.cpp \
    $${PWD}/OAIPropertyBatchInfoKind.cpp \
    $${PWD}/OAIPropertyBatchOperation.cpp \
    $${PWD}/OAIPropertyBatchOperationKind.cpp \
    $${PWD}/OAIPropertyDescription.cpp \
    $${PWD}/OAIPropertyInfo.cpp \
    $${PWD}/OAIPropertyMetadata.cpp \
    $${PWD}/OAIPropertyValue.cpp \
    $${PWD}/OAIPropertyValueKind.cpp \
    $${PWD}/OAIProvisionApplicationTypeDescription.cpp \
    $${PWD}/OAIProvisionApplicationTypeDescriptionBase.cpp \
    $${PWD}/OAIProvisionApplicationTypeKind.cpp \
    $${PWD}/OAIProvisionFabricDescription.cpp \
    $${PWD}/OAIPutPropertyBatchOperation.cpp \
    $${PWD}/OAIReconfigurationInformation.cpp \
    $${PWD}/OAIReconfigurationPhase.cpp \
    $${PWD}/OAIReconfigurationType.cpp \
    $${PWD}/OAIRegistryCredential.cpp \
    $${PWD}/OAIRemoteReplicatorAcknowledgementDetail.cpp \
    $${PWD}/OAIRemoteReplicatorAcknowledgementStatus.cpp \
    $${PWD}/OAIRemoteReplicatorStatus.cpp \
    $${PWD}/OAIRepairImpactDescriptionBase.cpp \
    $${PWD}/OAIRepairImpactKind.cpp \
    $${PWD}/OAIRepairTargetDescriptionBase.cpp \
    $${PWD}/OAIRepairTargetKind.cpp \
    $${PWD}/OAIRepairTask.cpp \
    $${PWD}/OAIRepairTaskApproveDescription.cpp \
    $${PWD}/OAIRepairTaskCancelDescription.cpp \
    $${PWD}/OAIRepairTaskDeleteDescription.cpp \
    $${PWD}/OAIRepairTaskHealthCheckState.cpp \
    $${PWD}/OAIRepairTaskHistory.cpp \
    $${PWD}/OAIRepairTaskUpdateHealthPolicyDescription.cpp \
    $${PWD}/OAIRepairTaskUpdateInfo.cpp \
    $${PWD}/OAIReplicaEvent.cpp \
    $${PWD}/OAIReplicaHealth.cpp \
    $${PWD}/OAIReplicaHealthEvaluation.cpp \
    $${PWD}/OAIReplicaHealthState.cpp \
    $${PWD}/OAIReplicaHealthStateChunk.cpp \
    $${PWD}/OAIReplicaHealthStateChunkList.cpp \
    $${PWD}/OAIReplicaHealthStateFilter.cpp \
    $${PWD}/OAIReplicaInfo.cpp \
    $${PWD}/OAIReplicaKind.cpp \
    $${PWD}/OAIReplicaRole.cpp \
    $${PWD}/OAIReplicaStatus.cpp \
    $${PWD}/OAIReplicaStatusBase.cpp \
    $${PWD}/OAIReplicasHealthEvaluation.cpp \
    $${PWD}/OAIReplicatorOperationName.cpp \
    $${PWD}/OAIReplicatorQueueStatus.cpp \
    $${PWD}/OAIReplicatorStatus.cpp \
    $${PWD}/OAIResolvedServiceEndpoint.cpp \
    $${PWD}/OAIResolvedServicePartition.cpp \
    $${PWD}/OAIRestartDeployedCodePackageDescription.cpp \
    $${PWD}/OAIRestartNodeDescription.cpp \
    $${PWD}/OAIRestartPartitionResult.cpp \
    $${PWD}/OAIRestorePartitionDescription.cpp \
    $${PWD}/OAIRestoreProgressInfo.cpp \
    $${PWD}/OAIRestoreState.cpp \
    $${PWD}/OAIResumeApplicationUpgradeDescription.cpp \
    $${PWD}/OAIResumeClusterUpgradeDescription.cpp \
    $${PWD}/OAIRollingUpgradeUpdateDescription.cpp \
    $${PWD}/OAISafetyCheck.cpp \
    $${PWD}/OAISafetyCheckKind.cpp \
    $${PWD}/OAISafetyCheckWrapper.cpp \
    $${PWD}/OAIScalingMechanismDescription.cpp \
    $${PWD}/OAIScalingMechanismKind.cpp \
    $${PWD}/OAIScalingPolicyDescription.cpp \
    $${PWD}/OAIScalingTriggerDescription.cpp \
    $${PWD}/OAIScalingTriggerKind.cpp \
    $${PWD}/OAISecondaryActiveReplicatorStatus.cpp \
    $${PWD}/OAISecondaryIdleReplicatorStatus.cpp \
    $${PWD}/OAISecondaryReplicatorStatus.cpp \
    $${PWD}/OAISeedNodeSafetyCheck.cpp \
    $${PWD}/OAISelectedPartition.cpp \
    $${PWD}/OAIServiceBackupConfigurationInfo.cpp \
    $${PWD}/OAIServiceBackupEntity.cpp \
    $${PWD}/OAIServiceCorrelationDescription.cpp \
    $${PWD}/OAIServiceCorrelationScheme.cpp \
    $${PWD}/OAIServiceCreatedEvent.cpp \
    $${PWD}/OAIServiceDeletedEvent.cpp \
    $${PWD}/OAIServiceDescription.cpp \
    $${PWD}/OAIServiceEndpointRole.cpp \
    $${PWD}/OAIServiceEvent.cpp \
    $${PWD}/OAIServiceFromTemplateDescription.cpp \
    $${PWD}/OAIServiceHealth.cpp \
    $${PWD}/OAIServiceHealthEvaluation.cpp \
    $${PWD}/OAIServiceHealthReportCreatedEvent.cpp \
    $${PWD}/OAIServiceHealthReportExpiredEvent.cpp \
    $${PWD}/OAIServiceHealthState.cpp \
    $${PWD}/OAIServiceHealthStateChunk.cpp \
    $${PWD}/OAIServiceHealthStateChunkList.cpp \
    $${PWD}/OAIServiceHealthStateFilter.cpp \
    $${PWD}/OAIServiceInfo.cpp \
    $${PWD}/OAIServiceKind.cpp \
    $${PWD}/OAIServiceLoadMetricDescription.cpp \
    $${PWD}/OAIServiceLoadMetricWeight.cpp \
    $${PWD}/OAIServiceNameInfo.cpp \
    $${PWD}/OAIServiceOperationName.cpp \
    $${PWD}/OAIServicePackageActivationMode.cpp \
    $${PWD}/OAIServicePartitionInfo.cpp \
    $${PWD}/OAIServicePartitionKind.cpp \
    $${PWD}/OAIServicePartitionStatus.cpp \
    $${PWD}/OAIServicePlacementInvalidDomainPolicyDescription.cpp \
    $${PWD}/OAIServicePlacementNonPartiallyPlaceServicePolicyDescription.cpp \
    $${PWD}/OAIServicePlacementPolicyDescription.cpp \
    $${PWD}/OAIServicePlacementPolicyType.cpp \
    $${PWD}/OAIServicePlacementPreferPrimaryDomainPolicyDescription.cpp \
    $${PWD}/OAIServicePlacementRequireDomainDistributionPolicyDescription.cpp \
    $${PWD}/OAIServicePlacementRequiredDomainPolicyDescription.cpp \
    $${PWD}/OAIServiceStatus.cpp \
    $${PWD}/OAIServiceTypeDescription.cpp \
    $${PWD}/OAIServiceTypeExtensionDescription.cpp \
    $${PWD}/OAIServiceTypeHealthPolicy.cpp \
    $${PWD}/OAIServiceTypeHealthPolicyMapItem.cpp \
    $${PWD}/OAIServiceTypeInfo.cpp \
    $${PWD}/OAIServiceTypeManifest.cpp \
    $${PWD}/OAIServiceTypeRegistrationStatus.cpp \
    $${PWD}/OAIServiceUpdateDescription.cpp \
    $${PWD}/OAIServicesHealthEvaluation.cpp \
    $${PWD}/OAISingletonPartitionInformation.cpp \
    $${PWD}/OAISingletonPartitionSchemeDescription.cpp \
    $${PWD}/OAIStartClusterUpgradeDescription.cpp \
    $${PWD}/OAIStartedChaosEvent.cpp \
    $${PWD}/OAIStatefulReplicaHealthReportCreatedEvent.cpp \
    $${PWD}/OAIStatefulReplicaHealthReportExpiredEvent.cpp \
    $${PWD}/OAIStatefulServiceDescription.cpp \
    $${PWD}/OAIStatefulServiceInfo.cpp \
    $${PWD}/OAIStatefulServicePartitionInfo.cpp \
    $${PWD}/OAIStatefulServiceReplicaHealth.cpp \
    $${PWD}/OAIStatefulServiceReplicaHealthState.cpp \
    $${PWD}/OAIStatefulServiceReplicaInfo.cpp \
    $${PWD}/OAIStatefulServiceTypeDescription.cpp \
    $${PWD}/OAIStatefulServiceUpdateDescription.cpp \
    $${PWD}/OAIStatelessReplicaHealthReportCreatedEvent.cpp \
    $${PWD}/OAIStatelessReplicaHealthReportExpiredEvent.cpp \
    $${PWD}/OAIStatelessServiceDescription.cpp \
    $${PWD}/OAIStatelessServiceInfo.cpp \
    $${PWD}/OAIStatelessServiceInstanceHealth.cpp \
    $${PWD}/OAIStatelessServiceInstanceHealthState.cpp \
    $${PWD}/OAIStatelessServiceInstanceInfo.cpp \
    $${PWD}/OAIStatelessServicePartitionInfo.cpp \
    $${PWD}/OAIStatelessServiceTypeDescription.cpp \
    $${PWD}/OAIStatelessServiceUpdateDescription.cpp \
    $${PWD}/OAIStoppedChaosEvent.cpp \
    $${PWD}/OAIStringPropertyValue.cpp \
    $${PWD}/OAISuccessfulPropertyBatchInfo.cpp \
    $${PWD}/OAISystemApplicationHealthEvaluation.cpp \
    $${PWD}/OAITestErrorChaosEvent.cpp \
    $${PWD}/OAITimeBasedBackupScheduleDescription.cpp \
    $${PWD}/OAITimeOfDay.cpp \
    $${PWD}/OAITimeRange.cpp \
    $${PWD}/OAIUniformInt64RangePartitionSchemeDescription.cpp \
    $${PWD}/OAIUnprovisionApplicationTypeDescriptionInfo.cpp \
    $${PWD}/OAIUnprovisionFabricDescription.cpp \
    $${PWD}/OAIUpdateClusterUpgradeDescription.cpp \
    $${PWD}/OAIUpgradeDomainDeltaNodesCheckHealthEvaluation.cpp \
    $${PWD}/OAIUpgradeDomainInfo.cpp \
    $${PWD}/OAIUpgradeDomainNodesHealthEvaluation.cpp \
    $${PWD}/OAIUpgradeDomainState.cpp \
    $${PWD}/OAIUpgradeKind.cpp \
    $${PWD}/OAIUpgradeMode.cpp \
    $${PWD}/OAIUpgradeOrchestrationServiceState.cpp \
    $${PWD}/OAIUpgradeOrchestrationServiceStateSummary.cpp \
    $${PWD}/OAIUpgradeState.cpp \
    $${PWD}/OAIUpgradeType.cpp \
    $${PWD}/OAIUploadChunkRange.cpp \
    $${PWD}/OAIUploadSession.cpp \
    $${PWD}/OAIUploadSessionInfo.cpp \
    $${PWD}/OAIValidationFailedChaosEvent.cpp \
    $${PWD}/OAIWaitForInbuildReplicaSafetyCheck.cpp \
    $${PWD}/OAIWaitForPrimaryPlacementSafetyCheck.cpp \
    $${PWD}/OAIWaitForPrimarySwapSafetyCheck.cpp \
    $${PWD}/OAIWaitForReconfigurationSafetyCheck.cpp \
    $${PWD}/OAIWaitingChaosEvent.cpp \
# APIs
    $${PWD}/OAIApplicationApi.cpp \
    $${PWD}/OAIApplicationTypeApi.cpp \
    $${PWD}/OAIBackupRestoreApi.cpp \
    $${PWD}/OAIChaosApi.cpp \
    $${PWD}/OAIClusterApi.cpp \
    $${PWD}/OAICodePackageApi.cpp \
    $${PWD}/OAIComposeDeploymentApi.cpp \
    $${PWD}/OAIEventsStoreApi.cpp \
    $${PWD}/OAIFaultsApi.cpp \
    $${PWD}/OAIImageStoreApi.cpp \
    $${PWD}/OAIInfrastructureApi.cpp \
    $${PWD}/OAINodeApi.cpp \
    $${PWD}/OAIPartitionApi.cpp \
    $${PWD}/OAIPropertyManagementApi.cpp \
    $${PWD}/OAIRepairManagementApi.cpp \
    $${PWD}/OAIReplicaApi.cpp \
    $${PWD}/OAIServiceApi.cpp \
    $${PWD}/OAIServicePackageApi.cpp \
    $${PWD}/OAIServiceTypeApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
