openapi: 3.0.1
info:
  contact: {}
  description: "Welcome to the autogenerated documentation & test tool for Avaza's\
    \ API. <br/><br/><strong>API Security & Authentication</strong><br/>Authentication\
    \ options include OAuth2 Implicit and Authorization Code flows, and Personal Access\
    \ Token. All connections should be encrypted over SSL/TLS <br/><br/>You can set\
    \ up and manage your api authentication credentials from within your Avaza account.\
    \ (requires Administrator permissions on your Avaza account).<br/><br/> OAuth2\
    \ Authorization endpoint: https://any.avaza.com/oauth2/authorize  <br/>OAuth2\
    \ Token endpoint: https://any.avaza.com/oauth2/token<br/>Base URL for subsequent\
    \ API Requests: https://api.avaza.com/ <br/><br/>Blogpost about authenticating\
    \ with Avaza's API:  https://www.avaza.com/avaza-api-oauth2-authentication/ <br/>Blogpost\
    \ on using Avaza's webhooks: https://www.avaza.com/avaza-api-webhook-notifications/<br/>The\
    \ OAuth flow currently issues Access Tokens that last 1 day, and Refresh tokens\
    \ that last 180 days<br/>The Api respects the security Roles assigned to the authenticating\
    \ Avaza user and filters the data return appropriately. <br/><br><strong>Support</strong><br/>For\
    \ API Support, and to request access please contact Avaza Support Team via our\
    \ support chat. <br/><br/><strong>User Contributed Libraries:</strong><br/>Graciously\
    \ contributed by 3rd party users like you. <br/>Note these are not tested or endorsesd\
    \ by Avaza. We encourage you to review before use, and use at own risk.<br/> <ul><li>\
    \ - <a target='blank' href='https://packagist.org/packages/debiprasad/oauth2-avaza'>PHP\
    \ OAuth Client Package for Azava API (by Debiprasad Sahoo)</a></li></ul>"
  title: Avaza API Documentation
  version: v1
  x-apisguru-categories:
  - collaboration
  x-logo:
    url: https://twitter.com/AvazaHq/profile_image?size=original
  x-origin:
  - format: swagger
    url: https://api.avaza.com/swagger/docs/v1
    version: "2.0"
  x-providerName: avaza.com
servers:
- url: https://api.avaza.com/
paths:
  /ScheduleSeries/AddBooking:
    post:
      operationId: schedule_series_add_booking
      security:
      - oauth2:
        - write_schedule
      summary: Create new Schedule Booking
      tags:
      - ScheduleSeries
      x-openapi-router-controller: openapi_server.controllers.schedule_series_controller
  /ScheduleSeries/AddLeave:
    post:
      operationId: schedule_series_add_leave
      security:
      - oauth2:
        - write_schedule
      summary: Create new Leave Booking
      tags:
      - ScheduleSeries
      x-openapi-router-controller: openapi_server.controllers.schedule_series_controller
  /ScheduleSeries/EditBooking:
    put:
      operationId: schedule_series_edit_booking
      security:
      - oauth2:
        - write_schedule
      summary: Edit Booking
      tags:
      - ScheduleSeries
      x-openapi-router-controller: openapi_server.controllers.schedule_series_controller
  /ScheduleSeries/EditLeave:
    put:
      operationId: schedule_series_edit_leave
      security:
      - oauth2:
        - write_schedule
      summary: Edit Leave Booking
      tags:
      - ScheduleSeries
      x-openapi-router-controller: openapi_server.controllers.schedule_series_controller
  /api/Account:
    get:
      operationId: account_get
      security:
      - oauth2:
        - read_account
      summary: Account Details
      tags:
      - Account
      x-openapi-router-controller: openapi_server.controllers.account_controller
  /api/Bill:
    get:
      description: "TransactionStatusCode values are: \"Draft\", \"Verified\", \"\
        Late\", \"Paid\", \"Partial\", \"Void\""
      operationId: bill_get
      security:
      - oauth2:
        - read_financials
      summary: Gets list of Bills
      tags:
      - Bill
      x-openapi-router-controller: openapi_server.controllers.bill_controller
    post:
      operationId: bill_post
      security:
      - oauth2:
        - write_financials
      summary: Create a new draft Bill
      tags:
      - Bill
      x-openapi-router-controller: openapi_server.controllers.bill_controller
  /api/Bill/{id}:
    get:
      operationId: bill_get_by_id
      security:
      - oauth2:
        - read_financials
      summary: Gets a Bill by Bill ID
      tags:
      - Bill
      x-openapi-router-controller: openapi_server.controllers.bill_controller
  /api/BillPayment:
    get:
      operationId: bill_payment_get
      security:
      - oauth2:
        - read_financials
      summary: Gets list of Bill Payments
      tags:
      - BillPayment
      x-openapi-router-controller: openapi_server.controllers.bill_payment_controller
    post:
      operationId: bill_payment_post
      security:
      - oauth2:
        - write_financials
      summary: Create new Bill Payment and optionally assign payment allocations to
        Bills
      tags:
      - BillPayment
      x-openapi-router-controller: openapi_server.controllers.bill_payment_controller
  /api/BillPayment/{id}:
    get:
      operationId: bill_payment_get_by_id
      security:
      - oauth2:
        - read_financials
      summary: Gets a Bill Payment by Payment Transaction ID
      tags:
      - BillPayment
      x-openapi-router-controller: openapi_server.controllers.bill_payment_controller
  /api/Company:
    get:
      operationId: company_get
      security:
      - oauth2:
        - read_contacts
      summary: Gets list of Companies
      tags:
      - Company
      x-openapi-router-controller: openapi_server.controllers.company_controller
    post:
      operationId: company_post
      security:
      - oauth2:
        - write_contacts
      summary: Create a Company
      tags:
      - Company
      x-openapi-router-controller: openapi_server.controllers.company_controller
    put:
      description: Requires CompanyID and a list of field names to update. The FieldsToUpdate
        field accepts a string array containing field names that should be updated.
      operationId: company_put
      security:
      - oauth2:
        - write_contacts
      summary: Update a Company record.
      tags:
      - Company
      x-openapi-router-controller: openapi_server.controllers.company_controller
  /api/Company/Lookup:
    get:
      description: Certain roles see a restricted set of companies based on their
        project memberships
      operationId: company_lookup
      security:
      - oauth2:
        - read_contacts
      summary: Gets minimal list of Companies.
      tags:
      - Company
      x-openapi-router-controller: openapi_server.controllers.company_controller
  /api/Company/{id}:
    get:
      operationId: company_get_by_id
      security:
      - oauth2:
        - read_contacts
      summary: Gets Company by Company ID
      tags:
      - Company
      x-openapi-router-controller: openapi_server.controllers.company_controller
  /api/Contact:
    get:
      operationId: contact_get
      security:
      - oauth2:
        - read_contacts
      summary: Gets list of Contacts
      tags:
      - Contact
      x-openapi-router-controller: openapi_server.controllers.contact_controller
    post:
      operationId: contact_post
      security:
      - oauth2:
        - write_contacts
      summary: Create a Contact
      tags:
      - Contact
      x-openapi-router-controller: openapi_server.controllers.contact_controller
  /api/Contact/{id}:
    get:
      operationId: contact_get_by_id
      security:
      - oauth2:
        - read_contacts
      summary: Gets Contact by Contact ID
      tags:
      - Contact
      x-openapi-router-controller: openapi_server.controllers.contact_controller
  /api/CreditNote:
    get:
      operationId: credit_note_get
      security:
      - oauth2:
        - read_financials
      summary: Gets list of CreditNotes
      tags:
      - CreditNote
      x-openapi-router-controller: openapi_server.controllers.credit_note_controller
  /api/CreditNote/{id}:
    get:
      operationId: credit_note_get_by_id
      security:
      - oauth2:
        - read_financials
      summary: Gets Credit Note by CreditNoteID
      tags:
      - CreditNote
      x-openapi-router-controller: openapi_server.controllers.credit_note_controller
  /api/Currency:
    get:
      operationId: currency_get
      summary: Gets list of Currencies
      tags:
      - Currency
      x-openapi-router-controller: openapi_server.controllers.currency_controller
  /api/Estimate:
    get:
      description: "EstimateStatusCode values are: \"Draft\", \"Sent\", \"Accepted\"\
        , \"Converted\", \"Expired\", \"Rejected\""
      operationId: estimate_get
      security:
      - oauth2:
        - read_financials
      summary: Gets list of Estimates
      tags:
      - Estimate
      x-openapi-router-controller: openapi_server.controllers.estimate_controller
    post:
      operationId: estimate_post
      security:
      - oauth2:
        - write_financials
      summary: Create a new draft Estimate
      tags:
      - Estimate
      x-openapi-router-controller: openapi_server.controllers.estimate_controller
  /api/Estimate/{id}:
    get:
      operationId: estimate_get_by_id
      security:
      - oauth2:
        - read_financials
      summary: Gets Estimate by Estimate ID
      tags:
      - Estimate
      x-openapi-router-controller: openapi_server.controllers.estimate_controller
  /api/Expense:
    delete:
      operationId: expense_delete
      security:
      - oauth2:
        - write_expenses
      summary: Delete a Timesheet Entry
      tags:
      - Expense
      x-openapi-router-controller: openapi_server.controllers.expense_controller
    get:
      operationId: expense_get
      security:
      - oauth2:
        - read_expenses
      summary: Gets list of Expenses
      tags:
      - Expense
      x-openapi-router-controller: openapi_server.controllers.expense_controller
    post:
      description: Create an Expense
      operationId: expense_post
      security:
      - oauth2:
        - write_expenses
      summary: Create an Expense
      tags:
      - Expense
      x-openapi-router-controller: openapi_server.controllers.expense_controller
    put:
      description: Update an Expense
      operationId: expense_put
      security:
      - oauth2:
        - write_expenses
      summary: Update an Expense
      tags:
      - Expense
      x-openapi-router-controller: openapi_server.controllers.expense_controller
  /api/Expense/Attachment:
    post:
      operationId: expense_attachment
      security:
      - oauth2:
        - write_expenses
      tags:
      - Expense
      x-openapi-router-controller: openapi_server.controllers.expense_controller
  /api/Expense/{id}:
    get:
      operationId: expense_get_by_id
      security:
      - oauth2:
        - read_expenses
      summary: Gets an Expense Entry by Expense ID
      tags:
      - Expense
      x-openapi-router-controller: openapi_server.controllers.expense_controller
  /api/ExpenseApproval/Submit:
    post:
      operationId: expense_approval
      security:
      - oauth2:
        - write_expenses
      summary: Submit Expenses for Approval.
      tags:
      - Expense
      x-openapi-router-controller: openapi_server.controllers.expense_controller
  /api/ExpenseCategory:
    get:
      description: The default sort order is by Name asc
      operationId: expense_category_get
      security:
      - oauth2:
        - read_expenses
      summary: Gets list of Expense Categories
      tags:
      - ExpenseCategory
      x-openapi-router-controller: openapi_server.controllers.expense_category_controller
  /api/ExpenseGroup/Lookup:
    get:
      description: Expense Groups are for adhoc grouping of reported expenses. e.g.
        for expenses incurred on a Trip
      operationId: expense_group_lookup
      security:
      - oauth2:
        - read_expenses
      summary: Gets minimal list of Expense Groups.
      tags:
      - ExpenseGroup
      x-openapi-router-controller: openapi_server.controllers.expense_group_controller
  /api/ExpenseMerchant/Lookup:
    get:
      operationId: expense_merchange_lookup
      security:
      - oauth2:
        - read_expenses
      summary: Gets minimal list of Expense Merchants.
      tags:
      - ExpenseMerchant
      x-openapi-router-controller: openapi_server.controllers.expense_merchant_controller
  /api/ExpensePaymentMethod/Lookup:
    get:
      operationId: expense_payment_method_lookup
      security:
      - oauth2:
        - read_expenses
      summary: Gets minimal list of Expense Payment Methods.
      tags:
      - ExpensePaymentMethod
      x-openapi-router-controller: openapi_server.controllers.expense_payment_method_controller
  /api/ExpenseSummary:
    get:
      operationId: expense_summary_get
      security:
      - oauth2:
        - read_expenses
      summary: Gets Basic Summary of Expense Statistics
      tags:
      - ExpenseSummary
      x-openapi-router-controller: openapi_server.controllers.expense_summary_controller
  /api/FixedAmount:
    get:
      operationId: fixed_amount_get
      security:
      - oauth2:
        - read_financials
      summary: Gets list of Fixed Amounts
      tags:
      - FixedAmount
      x-openapi-router-controller: openapi_server.controllers.fixed_amount_controller
  /api/Inventory:
    get:
      operationId: inventory_get
      security:
      - oauth2:
        - read_financials
      summary: Gets list of Inventory
      tags:
      - Inventory
      x-openapi-router-controller: openapi_server.controllers.inventory_controller
  /api/Inventory/{id}:
    get:
      operationId: inventory_get_by_id
      security:
      - oauth2:
        - read_financials
      summary: Gets InventoryItem by InventoryItem ID
      tags:
      - Inventory
      x-openapi-router-controller: openapi_server.controllers.inventory_controller
  /api/Invoice:
    get:
      description: "TransactionStatusCode values are: \"Draft\", \"Sent\", \"Late\"\
        , \"Paid\", \"Partial\", \"Void\""
      operationId: invoice_get
      security:
      - oauth2:
        - read_financials
      summary: Gets list of Invoices
      tags:
      - Invoice
      x-openapi-router-controller: openapi_server.controllers.invoice_controller
    post:
      operationId: invoice_post
      security:
      - oauth2:
        - write_financials
      summary: Create a new draft invoice
      tags:
      - Invoice
      x-openapi-router-controller: openapi_server.controllers.invoice_controller
  /api/Invoice/{id}:
    get:
      operationId: invoice_get_by_id
      security:
      - oauth2:
        - read_financials
      summary: Gets Invoice by Invoice ID
      tags:
      - Invoice
      x-openapi-router-controller: openapi_server.controllers.invoice_controller
  /api/Payment:
    get:
      operationId: payment_get
      security:
      - oauth2:
        - read_financials
      summary: Gets list of Payments
      tags:
      - Payment
      x-openapi-router-controller: openapi_server.controllers.payment_controller
    post:
      operationId: payment_post
      security:
      - oauth2:
        - write_financials
      summary: Create new Payment and optionally assign payment allocations to Invoices
      tags:
      - Payment
      x-openapi-router-controller: openapi_server.controllers.payment_controller
  /api/Payment/{id}:
    get:
      operationId: payment_get_by_id
      security:
      - oauth2:
        - read_financials
      summary: Gets Payment by Payment Transaction ID
      tags:
      - Payment
      x-openapi-router-controller: openapi_server.controllers.payment_controller
  /api/Project:
    get:
      operationId: project_get
      security:
      - oauth2:
        - read_projects
      summary: Gets list of Projects
      tags:
      - Project
      x-openapi-router-controller: openapi_server.controllers.project_controller
    post:
      operationId: project_post
      security:
      - oauth2:
        - write_projects
      summary: Create a Project
      tags:
      - Project
      x-openapi-router-controller: openapi_server.controllers.project_controller
    put:
      description: Update a Project
      operationId: project_put
      security:
      - oauth2:
        - write_projects
      summary: Update an Project
      tags:
      - Project
      x-openapi-router-controller: openapi_server.controllers.project_controller
  /api/Project/Lookup:
    get:
      operationId: project_lookup
      security:
      - oauth2:
        - read_projects
      summary: Gets minimal list of active Projects for the current user
      tags:
      - Project
      x-openapi-router-controller: openapi_server.controllers.project_controller
  /api/Project/{id}:
    get:
      operationId: project_get_by_id
      security:
      - oauth2:
        - read_projects
      summary: Gets Project by Project ID
      tags:
      - Project
      x-openapi-router-controller: openapi_server.controllers.project_controller
  /api/ProjectMember:
    get:
      description: Include at least one of ProjectID or UserID parameters.
      operationId: project_member_get
      security:
      - oauth2:
        - read_projects
      summary: Gets list of Project Members
      tags:
      - ProjectMember
      x-openapi-router-controller: openapi_server.controllers.project_member_controller
    post:
      description: "the Amount columns for Cost, Budget, Rates should be specified\
        \ as a decimal. Financial amounts assume the currency of the Customer company.\
        \ Budget units depend on the Budget method set on the Project."
      operationId: project_member_post
      security:
      - oauth2:
        - write_projects
      summary: Assign a user as a Member of a Project
      tags:
      - ProjectMember
      x-openapi-router-controller: openapi_server.controllers.project_member_controller
    put:
      description: "Fields are only updated if their field name is in the FieldsToUpdate\
        \ string collection. The Amount columns for Cost, Budget, Rates if specified\
        \ should be a decimal. Financial amounts assume the currency of the parent\
        \ Company. Budget units depend on the Budget method set on the Project."
      operationId: project_member_put
      security:
      - oauth2:
        - write_projects
      summary: Update a Member of a Project
      tags:
      - ProjectMember
      x-openapi-router-controller: openapi_server.controllers.project_member_controller
  /api/ProjectTimesheetCategory:
    get:
      description: "The default sort order is by isBillable desc, Name asc"
      operationId: project_timesheet_category_get
      security:
      - oauth2:
        - read_timesheets
      summary: Gets list of Project Timesheet Categories
      tags:
      - ProjectTimesheetCategory
      x-openapi-router-controller: openapi_server.controllers.project_timesheet_category_controller
    post:
      operationId: project_timesheet_category_post
      security:
      - oauth2:
        - write_projects
      summary: Assign a TimeSheetCategory to a Project.
      tags:
      - ProjectTimesheetCategory
      x-openapi-router-controller: openapi_server.controllers.project_timesheet_category_controller
  /api/ScheduleAssignment:
    get:
      description: "Schedule assignments are per-day, and link to a parent Schedule\
        \ Series."
      operationId: schedule_assignment_get
      security:
      - oauth2:
        - read_schedule
      summary: Gets list of Schedule Assignments.
      tags:
      - ScheduleAssignment
      x-openapi-router-controller: openapi_server.controllers.schedule_assignment_controller
  /api/ScheduleSeries:
    get:
      description: "Schedule Series represents a strip of time assigned to a user\
        \ over a date range, for a certain number of hours per day. They can be for\
        \ Leave or for project work Bookings."
      operationId: schedule_series_get
      security:
      - oauth2:
        - read_schedule
      summary: Gets list of Schedule Series
      tags:
      - ScheduleSeries
      x-openapi-router-controller: openapi_server.controllers.schedule_series_controller
  /api/Section:
    delete:
      operationId: section_delete
      security:
      - oauth2:
        - write_projects
      summary: Delete a Section
      tags:
      - Section
      x-openapi-router-controller: openapi_server.controllers.section_controller
    get:
      operationId: section_get
      security:
      - oauth2:
        - read_projects
      summary: Gets list of Sections
      tags:
      - Section
      x-openapi-router-controller: openapi_server.controllers.section_controller
    post:
      operationId: section_post
      security:
      - oauth2:
        - write_projects
      summary: Create a Section
      tags:
      - Section
      x-openapi-router-controller: openapi_server.controllers.section_controller
  /api/Task:
    delete:
      operationId: task_delete
      security:
      - oauth2:
        - write_projects
      summary: Delete a Task
      tags:
      - Task
      x-openapi-router-controller: openapi_server.controllers.task_controller
    get:
      operationId: task_get
      security:
      - oauth2:
        - read_projects
      summary: Gets list of Tasks
      tags:
      - Task
      x-openapi-router-controller: openapi_server.controllers.task_controller
    post:
      operationId: task_post
      security:
      - oauth2:
        - write_projects
      summary: Create a Task
      tags:
      - Task
      x-openapi-router-controller: openapi_server.controllers.task_controller
    put:
      description: Requires TaskID and a list of field names to update. The FieldsToUpdate
        field accepts a string array containing field names that should be updated.
      operationId: task_put
      security:
      - oauth2:
        - write_projects
      summary: Update a Task.
      tags:
      - Task
      x-openapi-router-controller: openapi_server.controllers.task_controller
  /api/Task/Lookup:
    get:
      description: Groups Tasks by Section. Default sort is by Section Title followed
        by Task Title
      operationId: task_lookup
      security:
      - oauth2:
        - read_projects
      summary: Gets minimal list of Tasks for the current user
      tags:
      - Task
      x-openapi-router-controller: openapi_server.controllers.task_controller
  /api/Task/{id}:
    get:
      operationId: task_get_by_id
      security:
      - oauth2:
        - read_projects
      summary: Gets Task by Task ID
      tags:
      - Task
      x-openapi-router-controller: openapi_server.controllers.task_controller
  /api/TaskStatus:
    get:
      operationId: task_status_get
      security:
      - oauth2:
        - read_projects
      summary: Gets list of Task Statuses
      tags:
      - TaskStatus
      x-openapi-router-controller: openapi_server.controllers.task_status_controller
  /api/TaskType:
    get:
      operationId: task_type_get
      security:
      - oauth2:
        - read_projects
      summary: Gets list of Task Types
      tags:
      - TaskType
      x-openapi-router-controller: openapi_server.controllers.task_type_controller
  /api/Tax:
    get:
      operationId: tax_get
      security:
      - oauth2:
        - read_financials
      summary: Get List of Taxes configured in the Avaza account.
      tags:
      - Tax
      x-openapi-router-controller: openapi_server.controllers.tax_controller
  /api/Timesheet:
    get:
      operationId: timesheet_get
      security:
      - oauth2:
        - read_timesheets
      summary: Gets list of Timsheets
      tags:
      - Timesheet
      x-openapi-router-controller: openapi_server.controllers.timesheet_controller
    post:
      operationId: timesheet_post
      security:
      - oauth2:
        - write_timesheets
      summary: Create a new Timesheet Entry
      tags:
      - Timesheet
      x-openapi-router-controller: openapi_server.controllers.timesheet_controller
    put:
      description: "The FieldsToUpdate field expects a string array collection of\
        \ the field names you would like updated. Valid fields to update inlcude \"\
        ProjectIDFK\", \"TimeSheetCategoryIDFK\", \"TaskIDFK\", \"Duration\", \"EntryDate\"\
        , \"Notes\", \"hasStartEndTime\", \"CustomMetadata\". If you intend to provide\
        \ start/end times on timesheets, this is achieved by including the start time\
        \ in the EntryDate field (Iso date format), along with a Duration (decimal\
        \ format)."
      operationId: timesheet_put
      security:
      - oauth2:
        - write_timesheets
      summary: Update a Timesheet
      tags:
      - Timesheet
      x-openapi-router-controller: openapi_server.controllers.timesheet_controller
  /api/Timesheet/{id}:
    delete:
      operationId: timesheet_delete
      security:
      - oauth2:
        - write_timesheets
      summary: Delete a Timesheet Entry
      tags:
      - Timesheet
      x-openapi-router-controller: openapi_server.controllers.timesheet_controller
    get:
      operationId: timesheet_get_by_id
      security:
      - oauth2:
        - read_timesheets
      summary: Gets a Timesheet Entry by Timesheet ID
      tags:
      - Timesheet
      x-openapi-router-controller: openapi_server.controllers.timesheet_controller
  /api/TimesheetSubmission:
    post:
      description: Either provide a a specific Day (WholeDayOf) or any day in a Week
        (WholeWeekOf) to submit all draft timesheets in that day or week
      operationId: timesheet_submission_post
      security:
      - oauth2:
        - write_timesheets
      summary: Submit Timesheets for Approval.
      tags:
      - TimesheetSubmission
      x-openapi-router-controller: openapi_server.controllers.timesheet_submission_controller
  /api/TimesheetSummary:
    get:
      operationId: timesheet_summary_get
      security:
      - oauth2:
        - read_timesheets
      summary: Gets Basic Summary of Timesheet Statistics
      tags:
      - TimesheetSummary
      x-openapi-router-controller: openapi_server.controllers.timesheet_summary_controller
  /api/TimesheetTimer:
    get:
      operationId: timesheet_timer_get_running_timer
      security:
      - oauth2:
        - read_timesheets
      summary: Gets the  Running Timer if there is one for a user.
      tags:
      - TimesheetTimer
      x-openapi-router-controller: openapi_server.controllers.timesheet_timer_controller
  /api/TimesheetTimer/{id}:
    delete:
      operationId: timesheet_timer_stop_timer
      security:
      - oauth2:
        - write_timesheets
      summary: Stop the timer running on an existing Timesheet Entry
      tags:
      - TimesheetTimer
      x-openapi-router-controller: openapi_server.controllers.timesheet_timer_controller
    post:
      operationId: timesheet_timer_start_timer
      security:
      - oauth2:
        - write_timesheets
      summary: Starts a Timer running on an existing Timesheet Entry
      tags:
      - TimesheetTimer
      x-openapi-router-controller: openapi_server.controllers.timesheet_timer_controller
  /api/UserProfile:
    get:
      description: Admin and Invoice Managers can see all. Other users are limited
        to seeing their own profile.
      operationId: user_profile_get
      security:
      - oauth2:
        - read_users
      summary: Get Collection of Users who have roles in the current Avaza account.
      tags:
      - UserProfile
      x-openapi-router-controller: openapi_server.controllers.user_profile_controller
  /api/Webhook:
    delete:
      operationId: webhook_delete_by_url
      security:
      - oauth2:
        - webhook_notifications
      summary: Delete webhook subscription by URL
      tags:
      - Webhook
      x-openapi-router-controller: openapi_server.controllers.webhook_controller
    get:
      operationId: webhook_get
      security:
      - oauth2:
        - webhook_notifications
      summary: Get list of Webhook Subscriptions
      tags:
      - Webhook
      x-openapi-router-controller: openapi_server.controllers.webhook_controller
    post:
      description: "When you receive a webhook, you should respond with Http 200 OK\
        \ Status Code, otherwise we will retry. To create a webhook, you need both\
        \ the webhook_notifications scope, as well as the scope for the required entity\
        \ being monitored.  Event values are: \"company_created\", \"company_deleted\"\
        , \"company_updated\", \"contact_created\", \"contact_deleted\", \"contact_updated\"\
        , \"invoice_created\", \"invoice_sent\",\"invoice_updated\",\"invoice_deleted\"\
        , \"project_created\", \"project_deleted\", \"project_updated\", \"task_created\"\
        , \"task_updated\",\"task_deleted\", \"timesheet_created\", \"timesheet_deleted\"\
        , \"timesheet_updated, \"bill_created\", \"bill_updated\".  You can subscribe\
        \ to any webhook, but you will only receive notifications for data appropriate\
        \ to the roles of your user account. There is an optional  Secret parameter\
        \ (string 255 char max). This allows for webhook authentication. If provided,\
        \ the Secret will be BASE 64 encoded and passed with notications as a basic\
        \ authentication http header. i.e. Authorization Basic [BASE64 of Secret]\""
      operationId: webhook_post
      security:
      - oauth2:
        - webhook_notifications
        - read_contacts
        - read_account
        - read_users
        - read_financials
        - read_projects
        - read_schedule
        - read_timesheets
        - read_expenses
        - write_contacts
        - write_account
        - write_users
        - write_financials
        - write_projects
        - write_schedule
        - write_timesheets
        - write_expenses
      summary: "Subscribe to Webhook. On success, returns ID of webhook subscription."
      tags:
      - Webhook
      x-openapi-router-controller: openapi_server.controllers.webhook_controller
  /api/Webhook/{id}:
    delete:
      operationId: webhook_delete
      security:
      - oauth2:
        - webhook_notifications
      summary: Delete Webhook Subscription by ID
      tags:
      - Webhook
      x-openapi-router-controller: openapi_server.controllers.webhook_controller
    get:
      operationId: webhook_get_by_id
      security:
      - oauth2:
        - webhook_notifications
      summary: Get Webhook Subscription by SubscriptionID
      tags:
      - Webhook
      x-openapi-router-controller: openapi_server.controllers.webhook_controller
components:
  securitySchemes:
    oauth2:
      description: OAuth2 Implicit Grant
      flows:
        implicit:
          authorizationUrl: https://any.avaza.com/oauth2/authorize
          scopes:
            read_account: Read access to Account metadata
            read_contacts: "Read access to Customers, Contacts"
            read_expenses: Read access to Expense Details
            read_financials: "Read access to Estimates, Invoices, Payments, Credit\
              \ Notes"
            read_projects: "Read access to Projects, Project Settings, Tasks"
            read_schedule: Read access to Schedule Details
            read_timesheets: Read access to Timesheet Details
            read_users: Read access to User Profiles
            webhook_notifications: Read access to webhook notification events
            write_account: Write access to Account metadata
            write_contacts: "Write access to Customers, Contacts"
            write_expenses: Write access to Expense module
            write_financials: "Write access to Estimates, Invoices, Payments, Credit\
              \ Notes"
            write_projects: "Write access to Projects, Project Settings, Tasks"
            write_schedule: Write access to Schedule module
            write_timesheets: Write access to Timesheets module
            write_users: Write access to User Profiles
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_oauth2
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_oauth2
x-original-swagger-version: "2.0"
