QT += network

HEADERS += \
# Models
    $${PWD}/OAIActiveViewVideoViewabilityMetricConfig.h \
    $${PWD}/OAIAdloox.h \
    $${PWD}/OAIAdvertiser.h \
    $${PWD}/OAIAdvertiserAdServerConfig.h \
    $${PWD}/OAIAdvertiserCreativeConfig.h \
    $${PWD}/OAIAdvertiserDataAccessConfig.h \
    $${PWD}/OAIAdvertiserGeneralConfig.h \
    $${PWD}/OAIAdvertiserSdfConfig.h \
    $${PWD}/OAIAdvertiserTargetingConfig.h \
    $${PWD}/OAIAgeRangeAssignedTargetingOptionDetails.h \
    $${PWD}/OAIAgeRangeTargetingOptionDetails.h \
    $${PWD}/OAIAppAssignedTargetingOptionDetails.h \
    $${PWD}/OAIAppCategoryAssignedTargetingOptionDetails.h \
    $${PWD}/OAIAppCategoryTargetingOptionDetails.h \
    $${PWD}/OAIAsset.h \
    $${PWD}/OAIAssetAssociation.h \
    $${PWD}/OAIAssignedInventorySource.h \
    $${PWD}/OAIAssignedLocation.h \
    $${PWD}/OAIAssignedTargetingOption.h \
    $${PWD}/OAIAssignedUserRole.h \
    $${PWD}/OAIAudienceGroupAssignedTargetingOptionDetails.h \
    $${PWD}/OAIAudioContentTypeAssignedTargetingOptionDetails.h \
    $${PWD}/OAIAudioContentTypeTargetingOptionDetails.h \
    $${PWD}/OAIAudioVideoOffset.h \
    $${PWD}/OAIAuditAdvertiserResponse.h \
    $${PWD}/OAIAuthorizedSellerStatusAssignedTargetingOptionDetails.h \
    $${PWD}/OAIAuthorizedSellerStatusTargetingOptionDetails.h \
    $${PWD}/OAIBiddingStrategy.h \
    $${PWD}/OAIBrowserAssignedTargetingOptionDetails.h \
    $${PWD}/OAIBrowserTargetingOptionDetails.h \
    $${PWD}/OAIBudgetSummary.h \
    $${PWD}/OAIBulkEditAdvertiserAssignedTargetingOptionsRequest.h \
    $${PWD}/OAIBulkEditAdvertiserAssignedTargetingOptionsResponse.h \
    $${PWD}/OAIBulkEditAssignedInventorySourcesRequest.h \
    $${PWD}/OAIBulkEditAssignedInventorySourcesResponse.h \
    $${PWD}/OAIBulkEditAssignedLocationsRequest.h \
    $${PWD}/OAIBulkEditAssignedLocationsResponse.h \
    $${PWD}/OAIBulkEditAssignedUserRolesRequest.h \
    $${PWD}/OAIBulkEditAssignedUserRolesResponse.h \
    $${PWD}/OAIBulkEditLineItemAssignedTargetingOptionsRequest.h \
    $${PWD}/OAIBulkEditLineItemAssignedTargetingOptionsResponse.h \
    $${PWD}/OAIBulkEditNegativeKeywordsRequest.h \
    $${PWD}/OAIBulkEditNegativeKeywordsResponse.h \
    $${PWD}/OAIBulkEditPartnerAssignedTargetingOptionsRequest.h \
    $${PWD}/OAIBulkEditPartnerAssignedTargetingOptionsResponse.h \
    $${PWD}/OAIBulkEditSitesRequest.h \
    $${PWD}/OAIBulkEditSitesResponse.h \
    $${PWD}/OAIBulkListAdvertiserAssignedTargetingOptionsResponse.h \
    $${PWD}/OAIBulkListCampaignAssignedTargetingOptionsResponse.h \
    $${PWD}/OAIBulkListInsertionOrderAssignedTargetingOptionsResponse.h \
    $${PWD}/OAIBulkListLineItemAssignedTargetingOptionsResponse.h \
    $${PWD}/OAIBusinessChainAssignedTargetingOptionDetails.h \
    $${PWD}/OAIBusinessChainSearchTerms.h \
    $${PWD}/OAIBusinessChainTargetingOptionDetails.h \
    $${PWD}/OAICampaign.h \
    $${PWD}/OAICampaignBudget.h \
    $${PWD}/OAICampaignFlight.h \
    $${PWD}/OAICampaignGoal.h \
    $${PWD}/OAICarrierAndIspAssignedTargetingOptionDetails.h \
    $${PWD}/OAICarrierAndIspTargetingOptionDetails.h \
    $${PWD}/OAICategoryAssignedTargetingOptionDetails.h \
    $${PWD}/OAICategoryTargetingOptionDetails.h \
    $${PWD}/OAIChannel.h \
    $${PWD}/OAIChannelAssignedTargetingOptionDetails.h \
    $${PWD}/OAICmHybridConfig.h \
    $${PWD}/OAICmTrackingAd.h \
    $${PWD}/OAICombinedAudience.h \
    $${PWD}/OAICombinedAudienceGroup.h \
    $${PWD}/OAICombinedAudienceTargetingSetting.h \
    $${PWD}/OAIConsent.h \
    $${PWD}/OAIContactInfo.h \
    $${PWD}/OAIContactInfoList.h \
    $${PWD}/OAIContentDurationAssignedTargetingOptionDetails.h \
    $${PWD}/OAIContentDurationTargetingOptionDetails.h \
    $${PWD}/OAIContentGenreAssignedTargetingOptionDetails.h \
    $${PWD}/OAIContentGenreTargetingOptionDetails.h \
    $${PWD}/OAIContentInstreamPositionAssignedTargetingOptionDetails.h \
    $${PWD}/OAIContentInstreamPositionTargetingOptionDetails.h \
    $${PWD}/OAIContentOutstreamPositionAssignedTargetingOptionDetails.h \
    $${PWD}/OAIContentOutstreamPositionTargetingOptionDetails.h \
    $${PWD}/OAIContentStreamTypeAssignedTargetingOptionDetails.h \
    $${PWD}/OAIContentStreamTypeTargetingOptionDetails.h \
    $${PWD}/OAIConversionCountingConfig.h \
    $${PWD}/OAICounterEvent.h \
    $${PWD}/OAICreateAssetRequest.h \
    $${PWD}/OAICreateAssetResponse.h \
    $${PWD}/OAICreateAssignedTargetingOptionsRequest.h \
    $${PWD}/OAICreateSdfDownloadTaskRequest.h \
    $${PWD}/OAICreative.h \
    $${PWD}/OAICreativeConfig.h \
    $${PWD}/OAICustomBiddingAlgorithm.h \
    $${PWD}/OAICustomBiddingModelReadinessState.h \
    $${PWD}/OAICustomBiddingScript.h \
    $${PWD}/OAICustomBiddingScriptRef.h \
    $${PWD}/OAICustomList.h \
    $${PWD}/OAICustomListGroup.h \
    $${PWD}/OAICustomListTargetingSetting.h \
    $${PWD}/OAIDate.h \
    $${PWD}/OAIDateRange.h \
    $${PWD}/OAIDayAndTimeAssignedTargetingOptionDetails.h \
    $${PWD}/OAIDeleteAssignedTargetingOptionsRequest.h \
    $${PWD}/OAIDeviceMakeModelAssignedTargetingOptionDetails.h \
    $${PWD}/OAIDeviceMakeModelTargetingOptionDetails.h \
    $${PWD}/OAIDeviceTypeAssignedTargetingOptionDetails.h \
    $${PWD}/OAIDeviceTypeTargetingOptionDetails.h \
    $${PWD}/OAIDigitalContentLabelAssignedTargetingOptionDetails.h \
    $${PWD}/OAIDigitalContentLabelTargetingOptionDetails.h \
    $${PWD}/OAIDimensions.h \
    $${PWD}/OAIDoubleVerify.h \
    $${PWD}/OAIDoubleVerifyAppStarRating.h \
    $${PWD}/OAIDoubleVerifyBrandSafetyCategories.h \
    $${PWD}/OAIDoubleVerifyDisplayViewability.h \
    $${PWD}/OAIDoubleVerifyFraudInvalidTraffic.h \
    $${PWD}/OAIDoubleVerifyVideoViewability.h \
    $${PWD}/OAIEditCustomerMatchMembersRequest.h \
    $${PWD}/OAIEditCustomerMatchMembersResponse.h \
    $${PWD}/OAIEditGuaranteedOrderReadAccessorsRequest.h \
    $${PWD}/OAIEditGuaranteedOrderReadAccessorsResponse.h \
    $${PWD}/OAIEditInventorySourceReadWriteAccessorsRequest.h \
    $${PWD}/OAIEditInventorySourceReadWriteAccessorsRequestAdvertisersUpdate.h \
    $${PWD}/OAIEnvironmentAssignedTargetingOptionDetails.h \
    $${PWD}/OAIEnvironmentTargetingOptionDetails.h \
    $${PWD}/OAIExchangeAssignedTargetingOptionDetails.h \
    $${PWD}/OAIExchangeConfig.h \
    $${PWD}/OAIExchangeConfigEnabledExchange.h \
    $${PWD}/OAIExchangeReviewStatus.h \
    $${PWD}/OAIExchangeTargetingOptionDetails.h \
    $${PWD}/OAIExitEvent.h \
    $${PWD}/OAIFirstAndThirdPartyAudience.h \
    $${PWD}/OAIFirstAndThirdPartyAudienceGroup.h \
    $${PWD}/OAIFirstAndThirdPartyAudienceTargetingSetting.h \
    $${PWD}/OAIFixedBidStrategy.h \
    $${PWD}/OAIFloodlightGroup.h \
    $${PWD}/OAIFrequencyCap.h \
    $${PWD}/OAIGenderAssignedTargetingOptionDetails.h \
    $${PWD}/OAIGenderTargetingOptionDetails.h \
    $${PWD}/OAIGenerateDefaultLineItemRequest.h \
    $${PWD}/OAIGeoRegionAssignedTargetingOptionDetails.h \
    $${PWD}/OAIGeoRegionSearchTerms.h \
    $${PWD}/OAIGeoRegionTargetingOptionDetails.h \
    $${PWD}/OAIGoogleAudience.h \
    $${PWD}/OAIGoogleAudienceGroup.h \
    $${PWD}/OAIGoogleAudienceTargetingSetting.h \
    $${PWD}/OAIGoogleBytestreamMedia.h \
    $${PWD}/OAIGuaranteedOrder.h \
    $${PWD}/OAIGuaranteedOrderStatus.h \
    $${PWD}/OAIHouseholdIncomeAssignedTargetingOptionDetails.h \
    $${PWD}/OAIHouseholdIncomeTargetingOptionDetails.h \
    $${PWD}/OAIIdFilter.h \
    $${PWD}/OAIInsertionOrder.h \
    $${PWD}/OAIInsertionOrderBudget.h \
    $${PWD}/OAIInsertionOrderBudgetSegment.h \
    $${PWD}/OAIIntegralAdScience.h \
    $${PWD}/OAIIntegrationDetails.h \
    $${PWD}/OAIInventorySource.h \
    $${PWD}/OAIInventorySourceAccessors.h \
    $${PWD}/OAIInventorySourceAccessorsAdvertiserAccessors.h \
    $${PWD}/OAIInventorySourceAccessorsPartnerAccessor.h \
    $${PWD}/OAIInventorySourceAssignedTargetingOptionDetails.h \
    $${PWD}/OAIInventorySourceDisplayCreativeConfig.h \
    $${PWD}/OAIInventorySourceFilter.h \
    $${PWD}/OAIInventorySourceGroup.h \
    $${PWD}/OAIInventorySourceGroupAssignedTargetingOptionDetails.h \
    $${PWD}/OAIInventorySourceStatus.h \
    $${PWD}/OAIInventorySourceVideoCreativeConfig.h \
    $${PWD}/OAIInvoice.h \
    $${PWD}/OAIKeywordAssignedTargetingOptionDetails.h \
    $${PWD}/OAILanguageAssignedTargetingOptionDetails.h \
    $${PWD}/OAILanguageTargetingOptionDetails.h \
    $${PWD}/OAILineItem.h \
    $${PWD}/OAILineItemBudget.h \
    $${PWD}/OAILineItemFlight.h \
    $${PWD}/OAIListAdvertiserAssignedTargetingOptionsResponse.h \
    $${PWD}/OAIListAdvertisersResponse.h \
    $${PWD}/OAIListAssignedInventorySourcesResponse.h \
    $${PWD}/OAIListAssignedLocationsResponse.h \
    $${PWD}/OAIListCampaignAssignedTargetingOptionsResponse.h \
    $${PWD}/OAIListCampaignsResponse.h \
    $${PWD}/OAIListChannelsResponse.h \
    $${PWD}/OAIListCombinedAudiencesResponse.h \
    $${PWD}/OAIListCreativesResponse.h \
    $${PWD}/OAIListCustomBiddingAlgorithmsResponse.h \
    $${PWD}/OAIListCustomBiddingScriptsResponse.h \
    $${PWD}/OAIListCustomListsResponse.h \
    $${PWD}/OAIListFirstAndThirdPartyAudiencesResponse.h \
    $${PWD}/OAIListGoogleAudiencesResponse.h \
    $${PWD}/OAIListGuaranteedOrdersResponse.h \
    $${PWD}/OAIListInsertionOrderAssignedTargetingOptionsResponse.h \
    $${PWD}/OAIListInsertionOrdersResponse.h \
    $${PWD}/OAIListInventorySourceGroupsResponse.h \
    $${PWD}/OAIListInventorySourcesResponse.h \
    $${PWD}/OAIListInvoicesResponse.h \
    $${PWD}/OAIListLineItemAssignedTargetingOptionsResponse.h \
    $${PWD}/OAIListLineItemsResponse.h \
    $${PWD}/OAIListLocationListsResponse.h \
    $${PWD}/OAIListManualTriggersResponse.h \
    $${PWD}/OAIListNegativeKeywordListsResponse.h \
    $${PWD}/OAIListNegativeKeywordsResponse.h \
    $${PWD}/OAIListPartnerAssignedTargetingOptionsResponse.h \
    $${PWD}/OAIListPartnersResponse.h \
    $${PWD}/OAIListSitesResponse.h \
    $${PWD}/OAIListTargetingOptionsResponse.h \
    $${PWD}/OAIListUsersResponse.h \
    $${PWD}/OAILocationList.h \
    $${PWD}/OAILookbackWindow.h \
    $${PWD}/OAILookupInvoiceCurrencyResponse.h \
    $${PWD}/OAIManualTrigger.h \
    $${PWD}/OAIMaximizeSpendBidStrategy.h \
    $${PWD}/OAIMeasurementConfig.h \
    $${PWD}/OAIMobileApp.h \
    $${PWD}/OAIMobileDeviceIdList.h \
    $${PWD}/OAIMoney.h \
    $${PWD}/OAINativeContentPositionAssignedTargetingOptionDetails.h \
    $${PWD}/OAINativeContentPositionTargetingOptionDetails.h \
    $${PWD}/OAINegativeKeyword.h \
    $${PWD}/OAINegativeKeywordList.h \
    $${PWD}/OAINegativeKeywordListAssignedTargetingOptionDetails.h \
    $${PWD}/OAIObaIcon.h \
    $${PWD}/OAIOmidAssignedTargetingOptionDetails.h \
    $${PWD}/OAIOmidTargetingOptionDetails.h \
    $${PWD}/OAIOnScreenPositionAssignedTargetingOptionDetails.h \
    $${PWD}/OAIOnScreenPositionTargetingOptionDetails.h \
    $${PWD}/OAIOperatingSystemAssignedTargetingOptionDetails.h \
    $${PWD}/OAIOperatingSystemTargetingOptionDetails.h \
    $${PWD}/OAIOperation.h \
    $${PWD}/OAIPacing.h \
    $${PWD}/OAIParentEntityFilter.h \
    $${PWD}/OAIParentalStatusAssignedTargetingOptionDetails.h \
    $${PWD}/OAIParentalStatusTargetingOptionDetails.h \
    $${PWD}/OAIPartner.h \
    $${PWD}/OAIPartnerAdServerConfig.h \
    $${PWD}/OAIPartnerCost.h \
    $${PWD}/OAIPartnerDataAccessConfig.h \
    $${PWD}/OAIPartnerGeneralConfig.h \
    $${PWD}/OAIPartnerRevenueModel.h \
    $${PWD}/OAIPerformanceGoal.h \
    $${PWD}/OAIPerformanceGoalBidStrategy.h \
    $${PWD}/OAIPoiAssignedTargetingOptionDetails.h \
    $${PWD}/OAIPoiSearchTerms.h \
    $${PWD}/OAIPoiTargetingOptionDetails.h \
    $${PWD}/OAIPrismaConfig.h \
    $${PWD}/OAIPrismaCpeCode.h \
    $${PWD}/OAIProximityLocationListAssignedTargetingOptionDetails.h \
    $${PWD}/OAIPublisherReviewStatus.h \
    $${PWD}/OAIRateDetails.h \
    $${PWD}/OAIRegionalLocationListAssignedTargetingOptionDetails.h \
    $${PWD}/OAIReplaceNegativeKeywordsRequest.h \
    $${PWD}/OAIReplaceNegativeKeywordsResponse.h \
    $${PWD}/OAIReplaceSitesRequest.h \
    $${PWD}/OAIReplaceSitesResponse.h \
    $${PWD}/OAIReviewStatusInfo.h \
    $${PWD}/OAIScriptError.h \
    $${PWD}/OAISdfConfig.h \
    $${PWD}/OAISdfDownloadTask.h \
    $${PWD}/OAISdfDownloadTaskMetadata.h \
    $${PWD}/OAISearchTargetingOptionsRequest.h \
    $${PWD}/OAISearchTargetingOptionsResponse.h \
    $${PWD}/OAISensitiveCategoryAssignedTargetingOptionDetails.h \
    $${PWD}/OAISensitiveCategoryTargetingOptionDetails.h \
    $${PWD}/OAISite.h \
    $${PWD}/OAIStatus.h \
    $${PWD}/OAISubExchangeAssignedTargetingOptionDetails.h \
    $${PWD}/OAISubExchangeTargetingOptionDetails.h \
    $${PWD}/OAITargetingExpansionConfig.h \
    $${PWD}/OAITargetingOption.h \
    $${PWD}/OAIThirdPartyOnlyConfig.h \
    $${PWD}/OAIThirdPartyUrl.h \
    $${PWD}/OAIThirdPartyVerifierAssignedTargetingOptionDetails.h \
    $${PWD}/OAITimeRange.h \
    $${PWD}/OAITimerEvent.h \
    $${PWD}/OAITrackingFloodlightActivityConfig.h \
    $${PWD}/OAITranscode.h \
    $${PWD}/OAIUniversalAdId.h \
    $${PWD}/OAIUrlAssignedTargetingOptionDetails.h \
    $${PWD}/OAIUser.h \
    $${PWD}/OAIUserRewardedContentAssignedTargetingOptionDetails.h \
    $${PWD}/OAIUserRewardedContentTargetingOptionDetails.h \
    $${PWD}/OAIVideoPlayerSizeAssignedTargetingOptionDetails.h \
    $${PWD}/OAIVideoPlayerSizeTargetingOptionDetails.h \
    $${PWD}/OAIViewabilityAssignedTargetingOptionDetails.h \
    $${PWD}/OAIViewabilityTargetingOptionDetails.h \
# APIs
    $${PWD}/OAIAdvertisersApi.h \
    $${PWD}/OAICombinedAudiencesApi.h \
    $${PWD}/OAICustomBiddingAlgorithmsApi.h \
    $${PWD}/OAICustomListsApi.h \
    $${PWD}/OAIFirstAndThirdPartyAudiencesApi.h \
    $${PWD}/OAIFloodlightGroupsApi.h \
    $${PWD}/OAIGoogleAudiencesApi.h \
    $${PWD}/OAIGuaranteedOrdersApi.h \
    $${PWD}/OAIInventorySourceGroupsApi.h \
    $${PWD}/OAIInventorySourcesApi.h \
    $${PWD}/OAIMediaApi.h \
    $${PWD}/OAIPartnersApi.h \
    $${PWD}/OAISdfdownloadtasksApi.h \
    $${PWD}/OAITargetingTypesApi.h \
    $${PWD}/OAIUsersApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIActiveViewVideoViewabilityMetricConfig.cpp \
    $${PWD}/OAIAdloox.cpp \
    $${PWD}/OAIAdvertiser.cpp \
    $${PWD}/OAIAdvertiserAdServerConfig.cpp \
    $${PWD}/OAIAdvertiserCreativeConfig.cpp \
    $${PWD}/OAIAdvertiserDataAccessConfig.cpp \
    $${PWD}/OAIAdvertiserGeneralConfig.cpp \
    $${PWD}/OAIAdvertiserSdfConfig.cpp \
    $${PWD}/OAIAdvertiserTargetingConfig.cpp \
    $${PWD}/OAIAgeRangeAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIAgeRangeTargetingOptionDetails.cpp \
    $${PWD}/OAIAppAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIAppCategoryAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIAppCategoryTargetingOptionDetails.cpp \
    $${PWD}/OAIAsset.cpp \
    $${PWD}/OAIAssetAssociation.cpp \
    $${PWD}/OAIAssignedInventorySource.cpp \
    $${PWD}/OAIAssignedLocation.cpp \
    $${PWD}/OAIAssignedTargetingOption.cpp \
    $${PWD}/OAIAssignedUserRole.cpp \
    $${PWD}/OAIAudienceGroupAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIAudioContentTypeAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIAudioContentTypeTargetingOptionDetails.cpp \
    $${PWD}/OAIAudioVideoOffset.cpp \
    $${PWD}/OAIAuditAdvertiserResponse.cpp \
    $${PWD}/OAIAuthorizedSellerStatusAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIAuthorizedSellerStatusTargetingOptionDetails.cpp \
    $${PWD}/OAIBiddingStrategy.cpp \
    $${PWD}/OAIBrowserAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIBrowserTargetingOptionDetails.cpp \
    $${PWD}/OAIBudgetSummary.cpp \
    $${PWD}/OAIBulkEditAdvertiserAssignedTargetingOptionsRequest.cpp \
    $${PWD}/OAIBulkEditAdvertiserAssignedTargetingOptionsResponse.cpp \
    $${PWD}/OAIBulkEditAssignedInventorySourcesRequest.cpp \
    $${PWD}/OAIBulkEditAssignedInventorySourcesResponse.cpp \
    $${PWD}/OAIBulkEditAssignedLocationsRequest.cpp \
    $${PWD}/OAIBulkEditAssignedLocationsResponse.cpp \
    $${PWD}/OAIBulkEditAssignedUserRolesRequest.cpp \
    $${PWD}/OAIBulkEditAssignedUserRolesResponse.cpp \
    $${PWD}/OAIBulkEditLineItemAssignedTargetingOptionsRequest.cpp \
    $${PWD}/OAIBulkEditLineItemAssignedTargetingOptionsResponse.cpp \
    $${PWD}/OAIBulkEditNegativeKeywordsRequest.cpp \
    $${PWD}/OAIBulkEditNegativeKeywordsResponse.cpp \
    $${PWD}/OAIBulkEditPartnerAssignedTargetingOptionsRequest.cpp \
    $${PWD}/OAIBulkEditPartnerAssignedTargetingOptionsResponse.cpp \
    $${PWD}/OAIBulkEditSitesRequest.cpp \
    $${PWD}/OAIBulkEditSitesResponse.cpp \
    $${PWD}/OAIBulkListAdvertiserAssignedTargetingOptionsResponse.cpp \
    $${PWD}/OAIBulkListCampaignAssignedTargetingOptionsResponse.cpp \
    $${PWD}/OAIBulkListInsertionOrderAssignedTargetingOptionsResponse.cpp \
    $${PWD}/OAIBulkListLineItemAssignedTargetingOptionsResponse.cpp \
    $${PWD}/OAIBusinessChainAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIBusinessChainSearchTerms.cpp \
    $${PWD}/OAIBusinessChainTargetingOptionDetails.cpp \
    $${PWD}/OAICampaign.cpp \
    $${PWD}/OAICampaignBudget.cpp \
    $${PWD}/OAICampaignFlight.cpp \
    $${PWD}/OAICampaignGoal.cpp \
    $${PWD}/OAICarrierAndIspAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAICarrierAndIspTargetingOptionDetails.cpp \
    $${PWD}/OAICategoryAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAICategoryTargetingOptionDetails.cpp \
    $${PWD}/OAIChannel.cpp \
    $${PWD}/OAIChannelAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAICmHybridConfig.cpp \
    $${PWD}/OAICmTrackingAd.cpp \
    $${PWD}/OAICombinedAudience.cpp \
    $${PWD}/OAICombinedAudienceGroup.cpp \
    $${PWD}/OAICombinedAudienceTargetingSetting.cpp \
    $${PWD}/OAIConsent.cpp \
    $${PWD}/OAIContactInfo.cpp \
    $${PWD}/OAIContactInfoList.cpp \
    $${PWD}/OAIContentDurationAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIContentDurationTargetingOptionDetails.cpp \
    $${PWD}/OAIContentGenreAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIContentGenreTargetingOptionDetails.cpp \
    $${PWD}/OAIContentInstreamPositionAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIContentInstreamPositionTargetingOptionDetails.cpp \
    $${PWD}/OAIContentOutstreamPositionAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIContentOutstreamPositionTargetingOptionDetails.cpp \
    $${PWD}/OAIContentStreamTypeAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIContentStreamTypeTargetingOptionDetails.cpp \
    $${PWD}/OAIConversionCountingConfig.cpp \
    $${PWD}/OAICounterEvent.cpp \
    $${PWD}/OAICreateAssetRequest.cpp \
    $${PWD}/OAICreateAssetResponse.cpp \
    $${PWD}/OAICreateAssignedTargetingOptionsRequest.cpp \
    $${PWD}/OAICreateSdfDownloadTaskRequest.cpp \
    $${PWD}/OAICreative.cpp \
    $${PWD}/OAICreativeConfig.cpp \
    $${PWD}/OAICustomBiddingAlgorithm.cpp \
    $${PWD}/OAICustomBiddingModelReadinessState.cpp \
    $${PWD}/OAICustomBiddingScript.cpp \
    $${PWD}/OAICustomBiddingScriptRef.cpp \
    $${PWD}/OAICustomList.cpp \
    $${PWD}/OAICustomListGroup.cpp \
    $${PWD}/OAICustomListTargetingSetting.cpp \
    $${PWD}/OAIDate.cpp \
    $${PWD}/OAIDateRange.cpp \
    $${PWD}/OAIDayAndTimeAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIDeleteAssignedTargetingOptionsRequest.cpp \
    $${PWD}/OAIDeviceMakeModelAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIDeviceMakeModelTargetingOptionDetails.cpp \
    $${PWD}/OAIDeviceTypeAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIDeviceTypeTargetingOptionDetails.cpp \
    $${PWD}/OAIDigitalContentLabelAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIDigitalContentLabelTargetingOptionDetails.cpp \
    $${PWD}/OAIDimensions.cpp \
    $${PWD}/OAIDoubleVerify.cpp \
    $${PWD}/OAIDoubleVerifyAppStarRating.cpp \
    $${PWD}/OAIDoubleVerifyBrandSafetyCategories.cpp \
    $${PWD}/OAIDoubleVerifyDisplayViewability.cpp \
    $${PWD}/OAIDoubleVerifyFraudInvalidTraffic.cpp \
    $${PWD}/OAIDoubleVerifyVideoViewability.cpp \
    $${PWD}/OAIEditCustomerMatchMembersRequest.cpp \
    $${PWD}/OAIEditCustomerMatchMembersResponse.cpp \
    $${PWD}/OAIEditGuaranteedOrderReadAccessorsRequest.cpp \
    $${PWD}/OAIEditGuaranteedOrderReadAccessorsResponse.cpp \
    $${PWD}/OAIEditInventorySourceReadWriteAccessorsRequest.cpp \
    $${PWD}/OAIEditInventorySourceReadWriteAccessorsRequestAdvertisersUpdate.cpp \
    $${PWD}/OAIEnvironmentAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIEnvironmentTargetingOptionDetails.cpp \
    $${PWD}/OAIExchangeAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIExchangeConfig.cpp \
    $${PWD}/OAIExchangeConfigEnabledExchange.cpp \
    $${PWD}/OAIExchangeReviewStatus.cpp \
    $${PWD}/OAIExchangeTargetingOptionDetails.cpp \
    $${PWD}/OAIExitEvent.cpp \
    $${PWD}/OAIFirstAndThirdPartyAudience.cpp \
    $${PWD}/OAIFirstAndThirdPartyAudienceGroup.cpp \
    $${PWD}/OAIFirstAndThirdPartyAudienceTargetingSetting.cpp \
    $${PWD}/OAIFixedBidStrategy.cpp \
    $${PWD}/OAIFloodlightGroup.cpp \
    $${PWD}/OAIFrequencyCap.cpp \
    $${PWD}/OAIGenderAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIGenderTargetingOptionDetails.cpp \
    $${PWD}/OAIGenerateDefaultLineItemRequest.cpp \
    $${PWD}/OAIGeoRegionAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIGeoRegionSearchTerms.cpp \
    $${PWD}/OAIGeoRegionTargetingOptionDetails.cpp \
    $${PWD}/OAIGoogleAudience.cpp \
    $${PWD}/OAIGoogleAudienceGroup.cpp \
    $${PWD}/OAIGoogleAudienceTargetingSetting.cpp \
    $${PWD}/OAIGoogleBytestreamMedia.cpp \
    $${PWD}/OAIGuaranteedOrder.cpp \
    $${PWD}/OAIGuaranteedOrderStatus.cpp \
    $${PWD}/OAIHouseholdIncomeAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIHouseholdIncomeTargetingOptionDetails.cpp \
    $${PWD}/OAIIdFilter.cpp \
    $${PWD}/OAIInsertionOrder.cpp \
    $${PWD}/OAIInsertionOrderBudget.cpp \
    $${PWD}/OAIInsertionOrderBudgetSegment.cpp \
    $${PWD}/OAIIntegralAdScience.cpp \
    $${PWD}/OAIIntegrationDetails.cpp \
    $${PWD}/OAIInventorySource.cpp \
    $${PWD}/OAIInventorySourceAccessors.cpp \
    $${PWD}/OAIInventorySourceAccessorsAdvertiserAccessors.cpp \
    $${PWD}/OAIInventorySourceAccessorsPartnerAccessor.cpp \
    $${PWD}/OAIInventorySourceAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIInventorySourceDisplayCreativeConfig.cpp \
    $${PWD}/OAIInventorySourceFilter.cpp \
    $${PWD}/OAIInventorySourceGroup.cpp \
    $${PWD}/OAIInventorySourceGroupAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIInventorySourceStatus.cpp \
    $${PWD}/OAIInventorySourceVideoCreativeConfig.cpp \
    $${PWD}/OAIInvoice.cpp \
    $${PWD}/OAIKeywordAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAILanguageAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAILanguageTargetingOptionDetails.cpp \
    $${PWD}/OAILineItem.cpp \
    $${PWD}/OAILineItemBudget.cpp \
    $${PWD}/OAILineItemFlight.cpp \
    $${PWD}/OAIListAdvertiserAssignedTargetingOptionsResponse.cpp \
    $${PWD}/OAIListAdvertisersResponse.cpp \
    $${PWD}/OAIListAssignedInventorySourcesResponse.cpp \
    $${PWD}/OAIListAssignedLocationsResponse.cpp \
    $${PWD}/OAIListCampaignAssignedTargetingOptionsResponse.cpp \
    $${PWD}/OAIListCampaignsResponse.cpp \
    $${PWD}/OAIListChannelsResponse.cpp \
    $${PWD}/OAIListCombinedAudiencesResponse.cpp \
    $${PWD}/OAIListCreativesResponse.cpp \
    $${PWD}/OAIListCustomBiddingAlgorithmsResponse.cpp \
    $${PWD}/OAIListCustomBiddingScriptsResponse.cpp \
    $${PWD}/OAIListCustomListsResponse.cpp \
    $${PWD}/OAIListFirstAndThirdPartyAudiencesResponse.cpp \
    $${PWD}/OAIListGoogleAudiencesResponse.cpp \
    $${PWD}/OAIListGuaranteedOrdersResponse.cpp \
    $${PWD}/OAIListInsertionOrderAssignedTargetingOptionsResponse.cpp \
    $${PWD}/OAIListInsertionOrdersResponse.cpp \
    $${PWD}/OAIListInventorySourceGroupsResponse.cpp \
    $${PWD}/OAIListInventorySourcesResponse.cpp \
    $${PWD}/OAIListInvoicesResponse.cpp \
    $${PWD}/OAIListLineItemAssignedTargetingOptionsResponse.cpp \
    $${PWD}/OAIListLineItemsResponse.cpp \
    $${PWD}/OAIListLocationListsResponse.cpp \
    $${PWD}/OAIListManualTriggersResponse.cpp \
    $${PWD}/OAIListNegativeKeywordListsResponse.cpp \
    $${PWD}/OAIListNegativeKeywordsResponse.cpp \
    $${PWD}/OAIListPartnerAssignedTargetingOptionsResponse.cpp \
    $${PWD}/OAIListPartnersResponse.cpp \
    $${PWD}/OAIListSitesResponse.cpp \
    $${PWD}/OAIListTargetingOptionsResponse.cpp \
    $${PWD}/OAIListUsersResponse.cpp \
    $${PWD}/OAILocationList.cpp \
    $${PWD}/OAILookbackWindow.cpp \
    $${PWD}/OAILookupInvoiceCurrencyResponse.cpp \
    $${PWD}/OAIManualTrigger.cpp \
    $${PWD}/OAIMaximizeSpendBidStrategy.cpp \
    $${PWD}/OAIMeasurementConfig.cpp \
    $${PWD}/OAIMobileApp.cpp \
    $${PWD}/OAIMobileDeviceIdList.cpp \
    $${PWD}/OAIMoney.cpp \
    $${PWD}/OAINativeContentPositionAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAINativeContentPositionTargetingOptionDetails.cpp \
    $${PWD}/OAINegativeKeyword.cpp \
    $${PWD}/OAINegativeKeywordList.cpp \
    $${PWD}/OAINegativeKeywordListAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIObaIcon.cpp \
    $${PWD}/OAIOmidAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIOmidTargetingOptionDetails.cpp \
    $${PWD}/OAIOnScreenPositionAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIOnScreenPositionTargetingOptionDetails.cpp \
    $${PWD}/OAIOperatingSystemAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIOperatingSystemTargetingOptionDetails.cpp \
    $${PWD}/OAIOperation.cpp \
    $${PWD}/OAIPacing.cpp \
    $${PWD}/OAIParentEntityFilter.cpp \
    $${PWD}/OAIParentalStatusAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIParentalStatusTargetingOptionDetails.cpp \
    $${PWD}/OAIPartner.cpp \
    $${PWD}/OAIPartnerAdServerConfig.cpp \
    $${PWD}/OAIPartnerCost.cpp \
    $${PWD}/OAIPartnerDataAccessConfig.cpp \
    $${PWD}/OAIPartnerGeneralConfig.cpp \
    $${PWD}/OAIPartnerRevenueModel.cpp \
    $${PWD}/OAIPerformanceGoal.cpp \
    $${PWD}/OAIPerformanceGoalBidStrategy.cpp \
    $${PWD}/OAIPoiAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIPoiSearchTerms.cpp \
    $${PWD}/OAIPoiTargetingOptionDetails.cpp \
    $${PWD}/OAIPrismaConfig.cpp \
    $${PWD}/OAIPrismaCpeCode.cpp \
    $${PWD}/OAIProximityLocationListAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIPublisherReviewStatus.cpp \
    $${PWD}/OAIRateDetails.cpp \
    $${PWD}/OAIRegionalLocationListAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIReplaceNegativeKeywordsRequest.cpp \
    $${PWD}/OAIReplaceNegativeKeywordsResponse.cpp \
    $${PWD}/OAIReplaceSitesRequest.cpp \
    $${PWD}/OAIReplaceSitesResponse.cpp \
    $${PWD}/OAIReviewStatusInfo.cpp \
    $${PWD}/OAIScriptError.cpp \
    $${PWD}/OAISdfConfig.cpp \
    $${PWD}/OAISdfDownloadTask.cpp \
    $${PWD}/OAISdfDownloadTaskMetadata.cpp \
    $${PWD}/OAISearchTargetingOptionsRequest.cpp \
    $${PWD}/OAISearchTargetingOptionsResponse.cpp \
    $${PWD}/OAISensitiveCategoryAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAISensitiveCategoryTargetingOptionDetails.cpp \
    $${PWD}/OAISite.cpp \
    $${PWD}/OAIStatus.cpp \
    $${PWD}/OAISubExchangeAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAISubExchangeTargetingOptionDetails.cpp \
    $${PWD}/OAITargetingExpansionConfig.cpp \
    $${PWD}/OAITargetingOption.cpp \
    $${PWD}/OAIThirdPartyOnlyConfig.cpp \
    $${PWD}/OAIThirdPartyUrl.cpp \
    $${PWD}/OAIThirdPartyVerifierAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAITimeRange.cpp \
    $${PWD}/OAITimerEvent.cpp \
    $${PWD}/OAITrackingFloodlightActivityConfig.cpp \
    $${PWD}/OAITranscode.cpp \
    $${PWD}/OAIUniversalAdId.cpp \
    $${PWD}/OAIUrlAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIUser.cpp \
    $${PWD}/OAIUserRewardedContentAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIUserRewardedContentTargetingOptionDetails.cpp \
    $${PWD}/OAIVideoPlayerSizeAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIVideoPlayerSizeTargetingOptionDetails.cpp \
    $${PWD}/OAIViewabilityAssignedTargetingOptionDetails.cpp \
    $${PWD}/OAIViewabilityTargetingOptionDetails.cpp \
# APIs
    $${PWD}/OAIAdvertisersApi.cpp \
    $${PWD}/OAICombinedAudiencesApi.cpp \
    $${PWD}/OAICustomBiddingAlgorithmsApi.cpp \
    $${PWD}/OAICustomListsApi.cpp \
    $${PWD}/OAIFirstAndThirdPartyAudiencesApi.cpp \
    $${PWD}/OAIFloodlightGroupsApi.cpp \
    $${PWD}/OAIGoogleAudiencesApi.cpp \
    $${PWD}/OAIGuaranteedOrdersApi.cpp \
    $${PWD}/OAIInventorySourceGroupsApi.cpp \
    $${PWD}/OAIInventorySourcesApi.cpp \
    $${PWD}/OAIMediaApi.cpp \
    $${PWD}/OAIPartnersApi.cpp \
    $${PWD}/OAISdfdownloadtasksApi.cpp \
    $${PWD}/OAITargetingTypesApi.cpp \
    $${PWD}/OAIUsersApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
