QT += network

HEADERS += \
# Models
    $${PWD}/OAIAddressResponse.h \
    $${PWD}/OAIAddressResponse_vipMappings_inner.h \
    $${PWD}/OAIAppServiceEnvironmentCollection.h \
    $${PWD}/OAIAppServiceEnvironmentPatchResource.h \
    $${PWD}/OAIAppServiceEnvironmentResource.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_identity.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_identity_userAssignedIdentities_value.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_cloningInfo.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_geoDistributions_inner.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_hostNameSslStates_inner.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_hostingEnvironmentProfile.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_apiDefinition.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_appSettings_inner.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_autoHealRules.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_autoHealRules_actions.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_autoHealRules_actions_customAction.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_autoHealRules_triggers.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_autoHealRules_triggers_requests.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_autoHealRules_triggers_slowRequests.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_autoHealRules_triggers_statusCodes_inner.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_azureStorageAccounts_value.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_connectionStrings_inner.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_cors.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_experiments.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_experiments_rampUpRules_inner.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_handlerMappings_inner.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_ipSecurityRestrictions_inner.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_limits.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_machineKey.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_push.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_push_properties.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_virtualApplications_inner.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_virtualApplications_inner_virtualDirectories_inner.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_slotSwapStatus.h \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_request.h \
    $${PWD}/OAIAppServiceEnvironments_ListAppServicePlans_200_response.h \
    $${PWD}/OAIAppServiceEnvironments_ListAppServicePlans_200_response_value_inner.h \
    $${PWD}/OAIAppServiceEnvironments_ListAppServicePlans_200_response_value_inner_properties.h \
    $${PWD}/OAIAppServiceEnvironments_ListAppServicePlans_200_response_value_inner_sku.h \
    $${PWD}/OAIAppServiceEnvironments_ListAppServicePlans_200_response_value_inner_sku_capabilities_inner.h \
    $${PWD}/OAIAppServiceEnvironments_ListAppServicePlans_200_response_value_inner_sku_skuCapacity.h \
    $${PWD}/OAIAppServiceEnvironments_ListMetrics_200_response.h \
    $${PWD}/OAIAppServiceEnvironments_ListMetrics_200_response_value_inner.h \
    $${PWD}/OAIAppServiceEnvironments_ListMetrics_200_response_value_inner_metricValues_inner.h \
    $${PWD}/OAIAppServiceEnvironments_ListMetrics_200_response_value_inner_metricValues_inner_properties_inner.h \
    $${PWD}/OAIAppServiceEnvironments_ListMetrics_200_response_value_inner_name.h \
    $${PWD}/OAIAppServiceEnvironments_ListMultiRolePoolInstanceMetricDefinitions_200_response.h \
    $${PWD}/OAIAppServiceEnvironments_ListMultiRolePoolInstanceMetricDefinitions_200_response_value_inner.h \
    $${PWD}/OAIAppServiceEnvironments_ListMultiRolePoolInstanceMetricDefinitions_200_response_value_inner_properties.h \
    $${PWD}/OAIAppServiceEnvironments_ListMultiRolePoolInstanceMetricDefinitions_200_response_value_inner_properties_metricAvailabilities_inner.h \
    $${PWD}/OAIAppServiceEnvironments_ListOperations_200_response_inner.h \
    $${PWD}/OAIAppServiceEnvironments_ListOperations_200_response_inner_errors_inner.h \
    $${PWD}/OAIAppServiceEnvironments_ListUsages_200_response.h \
    $${PWD}/OAIAppServiceEnvironments_ListUsages_200_response_value_inner.h \
    $${PWD}/OAIAppServiceEnvironments_ListUsages_200_response_value_inner_name.h \
    $${PWD}/OAIAppServiceEnvironments_List_default_response.h \
    $${PWD}/OAIAppServiceEnvironments_List_default_response_error.h \
    $${PWD}/OAIAppServiceEnvironments_List_default_response_error_details_inner.h \
    $${PWD}/OAIEndpointDependency.h \
    $${PWD}/OAIEndpointDetail.h \
    $${PWD}/OAIHostingEnvironmentDiagnostics.h \
    $${PWD}/OAIInboundEnvironmentEndpoint.h \
    $${PWD}/OAIInboundEnvironmentEndpointCollection.h \
    $${PWD}/OAIMetricAvailabilily.h \
    $${PWD}/OAIMetricDefinition.h \
    $${PWD}/OAIOutboundEnvironmentEndpoint.h \
    $${PWD}/OAIOutboundEnvironmentEndpointCollection.h \
    $${PWD}/OAISkuInfo.h \
    $${PWD}/OAISkuInfoCollection.h \
    $${PWD}/OAIStampCapacityCollection.h \
    $${PWD}/OAIStampCapacityCollection_value_inner.h \
    $${PWD}/OAIUsage.h \
    $${PWD}/OAIUsageCollection.h \
    $${PWD}/OAIWorkerPoolCollection.h \
    $${PWD}/OAIWorkerPoolResource.h \
# APIs
    $${PWD}/OAIAppServiceEnvironmentsApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAddressResponse.cpp \
    $${PWD}/OAIAddressResponse_vipMappings_inner.cpp \
    $${PWD}/OAIAppServiceEnvironmentCollection.cpp \
    $${PWD}/OAIAppServiceEnvironmentPatchResource.cpp \
    $${PWD}/OAIAppServiceEnvironmentResource.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_identity.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_identity_userAssignedIdentities_value.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_cloningInfo.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_geoDistributions_inner.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_hostNameSslStates_inner.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_hostingEnvironmentProfile.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_apiDefinition.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_appSettings_inner.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_autoHealRules.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_autoHealRules_actions.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_autoHealRules_actions_customAction.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_autoHealRules_triggers.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_autoHealRules_triggers_requests.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_autoHealRules_triggers_slowRequests.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_autoHealRules_triggers_statusCodes_inner.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_azureStorageAccounts_value.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_connectionStrings_inner.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_cors.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_experiments.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_experiments_rampUpRules_inner.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_handlerMappings_inner.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_ipSecurityRestrictions_inner.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_limits.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_machineKey.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_push.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_push_properties.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_virtualApplications_inner.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_siteConfig_virtualApplications_inner_virtualDirectories_inner.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_200_response_value_inner_properties_slotSwapStatus.cpp \
    $${PWD}/OAIAppServiceEnvironments_ChangeVnet_request.cpp \
    $${PWD}/OAIAppServiceEnvironments_ListAppServicePlans_200_response.cpp \
    $${PWD}/OAIAppServiceEnvironments_ListAppServicePlans_200_response_value_inner.cpp \
    $${PWD}/OAIAppServiceEnvironments_ListAppServicePlans_200_response_value_inner_properties.cpp \
    $${PWD}/OAIAppServiceEnvironments_ListAppServicePlans_200_response_value_inner_sku.cpp \
    $${PWD}/OAIAppServiceEnvironments_ListAppServicePlans_200_response_value_inner_sku_capabilities_inner.cpp \
    $${PWD}/OAIAppServiceEnvironments_ListAppServicePlans_200_response_value_inner_sku_skuCapacity.cpp \
    $${PWD}/OAIAppServiceEnvironments_ListMetrics_200_response.cpp \
    $${PWD}/OAIAppServiceEnvironments_ListMetrics_200_response_value_inner.cpp \
    $${PWD}/OAIAppServiceEnvironments_ListMetrics_200_response_value_inner_metricValues_inner.cpp \
    $${PWD}/OAIAppServiceEnvironments_ListMetrics_200_response_value_inner_metricValues_inner_properties_inner.cpp \
    $${PWD}/OAIAppServiceEnvironments_ListMetrics_200_response_value_inner_name.cpp \
    $${PWD}/OAIAppServiceEnvironments_ListMultiRolePoolInstanceMetricDefinitions_200_response.cpp \
    $${PWD}/OAIAppServiceEnvironments_ListMultiRolePoolInstanceMetricDefinitions_200_response_value_inner.cpp \
    $${PWD}/OAIAppServiceEnvironments_ListMultiRolePoolInstanceMetricDefinitions_200_response_value_inner_properties.cpp \
    $${PWD}/OAIAppServiceEnvironments_ListMultiRolePoolInstanceMetricDefinitions_200_response_value_inner_properties_metricAvailabilities_inner.cpp \
    $${PWD}/OAIAppServiceEnvironments_ListOperations_200_response_inner.cpp \
    $${PWD}/OAIAppServiceEnvironments_ListOperations_200_response_inner_errors_inner.cpp \
    $${PWD}/OAIAppServiceEnvironments_ListUsages_200_response.cpp \
    $${PWD}/OAIAppServiceEnvironments_ListUsages_200_response_value_inner.cpp \
    $${PWD}/OAIAppServiceEnvironments_ListUsages_200_response_value_inner_name.cpp \
    $${PWD}/OAIAppServiceEnvironments_List_default_response.cpp \
    $${PWD}/OAIAppServiceEnvironments_List_default_response_error.cpp \
    $${PWD}/OAIAppServiceEnvironments_List_default_response_error_details_inner.cpp \
    $${PWD}/OAIEndpointDependency.cpp \
    $${PWD}/OAIEndpointDetail.cpp \
    $${PWD}/OAIHostingEnvironmentDiagnostics.cpp \
    $${PWD}/OAIInboundEnvironmentEndpoint.cpp \
    $${PWD}/OAIInboundEnvironmentEndpointCollection.cpp \
    $${PWD}/OAIMetricAvailabilily.cpp \
    $${PWD}/OAIMetricDefinition.cpp \
    $${PWD}/OAIOutboundEnvironmentEndpoint.cpp \
    $${PWD}/OAIOutboundEnvironmentEndpointCollection.cpp \
    $${PWD}/OAISkuInfo.cpp \
    $${PWD}/OAISkuInfoCollection.cpp \
    $${PWD}/OAIStampCapacityCollection.cpp \
    $${PWD}/OAIStampCapacityCollection_value_inner.cpp \
    $${PWD}/OAIUsage.cpp \
    $${PWD}/OAIUsageCollection.cpp \
    $${PWD}/OAIWorkerPoolCollection.cpp \
    $${PWD}/OAIWorkerPoolResource.cpp \
# APIs
    $${PWD}/OAIAppServiceEnvironmentsApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
