openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: The Chrome Policy API is a suite of services that allows Chrome administrators
    to control the policies applied to their managed Chrome OS devices and Chrome
    browsers.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Chrome Policy API
  version: v1
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://upload.wikimedia.org/wikipedia/commons/e/e1/YouTube_play_buttom_icon_%282013-2017%29.svg
  x-origin:
  - format: google
    url: https://chromepolicy.googleapis.com/$discovery/rest?version=v1
    version: v1
  x-providerName: googleapis.com
  x-serviceName: chromepolicy
servers:
- url: https://chromepolicy.googleapis.com/
tags:
- name: customers
- name: media
paths:
  /v1/{customer}/policies/files:uploadPolicyFile:
    post:
      description: Creates an enterprise file from the content provided by user. Returns
        a public download url for end user.
      operationId: chromepolicy_media_upload
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/chrome.management.policy
        Oauth2c:
        - https://www.googleapis.com/auth/chrome.management.policy
      tags:
      - media
      x-openapi-router-controller: openapi_server.controllers.media_controller
  /v1/{customer}/policies/groups:batchDelete:
    post:
      description: "Delete multiple policy values that are applied to a specific group.\
        \ All targets must have the same target format. That is to say that they must\
        \ point to the same target resource and must have the same keys specified\
        \ in `additionalTargetKeyNames`, though the values for those keys may be different.\
        \ On failure the request will return the error details as part of the google.rpc.Status."
      operationId: chromepolicy_customers_policies_groups_batch_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/chrome.management.policy
        Oauth2c:
        - https://www.googleapis.com/auth/chrome.management.policy
      tags:
      - customers
      x-openapi-router-controller: openapi_server.controllers.customers_controller
  /v1/{customer}/policies/groups:batchModify:
    post:
      description: "Modify multiple policy values that are applied to a specific group.\
        \ All targets must have the same target format. That is to say that they must\
        \ point to the same target resource and must have the same keys specified\
        \ in `additionalTargetKeyNames`, though the values for those keys may be different.\
        \ On failure the request will return the error details as part of the google.rpc.Status."
      operationId: chromepolicy_customers_policies_groups_batch_modify
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/chrome.management.policy
        Oauth2c:
        - https://www.googleapis.com/auth/chrome.management.policy
      tags:
      - customers
      x-openapi-router-controller: openapi_server.controllers.customers_controller
  /v1/{customer}/policies/groups:listGroupPriorityOrdering:
    post:
      description: Retrieve a group priority ordering for an app. The target app must
        be supplied in `additionalTargetKeyNames` in the PolicyTargetKey. On failure
        the request will return the error details as part of the google.rpc.Status.
      operationId: chromepolicy_customers_policies_groups_list_group_priority_ordering
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/chrome.management.policy
        Oauth2c:
        - https://www.googleapis.com/auth/chrome.management.policy
      - Oauth2:
        - https://www.googleapis.com/auth/chrome.management.policy.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/chrome.management.policy.readonly
      tags:
      - customers
      x-openapi-router-controller: openapi_server.controllers.customers_controller
  /v1/{customer}/policies/groups:updateGroupPriorityOrdering:
    post:
      description: Update a group priority ordering for an app. The target app must
        be supplied in `additionalTargetKeyNames` in the PolicyTargetKey. On failure
        the request will return the error details as part of the google.rpc.Status.
      operationId: chromepolicy_customers_policies_groups_update_group_priority_ordering
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/chrome.management.policy
        Oauth2c:
        - https://www.googleapis.com/auth/chrome.management.policy
      tags:
      - customers
      x-openapi-router-controller: openapi_server.controllers.customers_controller
  /v1/{customer}/policies/networks:defineCertificate:
    post:
      description: Creates a certificate at a specified OU for a customer.
      operationId: chromepolicy_customers_policies_networks_define_certificate
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/chrome.management.policy
        Oauth2c:
        - https://www.googleapis.com/auth/chrome.management.policy
      tags:
      - customers
      x-openapi-router-controller: openapi_server.controllers.customers_controller
  /v1/{customer}/policies/networks:defineNetwork:
    post:
      description: Define a new network.
      operationId: chromepolicy_customers_policies_networks_define_network
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/chrome.management.policy
        Oauth2c:
        - https://www.googleapis.com/auth/chrome.management.policy
      tags:
      - customers
      x-openapi-router-controller: openapi_server.controllers.customers_controller
  /v1/{customer}/policies/networks:removeCertificate:
    post:
      description: Remove an existing certificate by guid.
      operationId: chromepolicy_customers_policies_networks_remove_certificate
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/chrome.management.policy
        Oauth2c:
        - https://www.googleapis.com/auth/chrome.management.policy
      tags:
      - customers
      x-openapi-router-controller: openapi_server.controllers.customers_controller
  /v1/{customer}/policies/networks:removeNetwork:
    post:
      description: Remove an existing network by guid.
      operationId: chromepolicy_customers_policies_networks_remove_network
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/chrome.management.policy
        Oauth2c:
        - https://www.googleapis.com/auth/chrome.management.policy
      tags:
      - customers
      x-openapi-router-controller: openapi_server.controllers.customers_controller
  /v1/{customer}/policies/orgunits:batchInherit:
    post:
      description: "Modify multiple policy values that are applied to a specific org\
        \ unit so that they now inherit the value from a parent (if applicable). All\
        \ targets must have the same target format. That is to say that they must\
        \ point to the same target resource and must have the same keys specified\
        \ in `additionalTargetKeyNames`, though the values for those keys may be different.\
        \ On failure the request will return the error details as part of the google.rpc.Status."
      operationId: chromepolicy_customers_policies_orgunits_batch_inherit
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/chrome.management.policy
        Oauth2c:
        - https://www.googleapis.com/auth/chrome.management.policy
      tags:
      - customers
      x-openapi-router-controller: openapi_server.controllers.customers_controller
  /v1/{customer}/policies/orgunits:batchModify:
    post:
      description: "Modify multiple policy values that are applied to a specific org\
        \ unit. All targets must have the same target format. That is to say that\
        \ they must point to the same target resource and must have the same keys\
        \ specified in `additionalTargetKeyNames`, though the values for those keys\
        \ may be different. On failure the request will return the error details as\
        \ part of the google.rpc.Status."
      operationId: chromepolicy_customers_policies_orgunits_batch_modify
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/chrome.management.policy
        Oauth2c:
        - https://www.googleapis.com/auth/chrome.management.policy
      tags:
      - customers
      x-openapi-router-controller: openapi_server.controllers.customers_controller
  /v1/{customer}/policies:resolve:
    post:
      description: Gets the resolved policy values for a list of policies that match
        a search query.
      operationId: chromepolicy_customers_policies_resolve
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/chrome.management.policy
        Oauth2c:
        - https://www.googleapis.com/auth/chrome.management.policy
      - Oauth2:
        - https://www.googleapis.com/auth/chrome.management.policy.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/chrome.management.policy.readonly
      tags:
      - customers
      x-openapi-router-controller: openapi_server.controllers.customers_controller
  /v1/{name}:
    get:
      description: Get a specific policy schema for a customer by its resource name.
      operationId: chromepolicy_customers_policy_schemas_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/chrome.management.policy
        Oauth2c:
        - https://www.googleapis.com/auth/chrome.management.policy
      - Oauth2:
        - https://www.googleapis.com/auth/chrome.management.policy.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/chrome.management.policy.readonly
      tags:
      - customers
      x-openapi-router-controller: openapi_server.controllers.customers_controller
  /v1/{parent}/policySchemas:
    get:
      description: Gets a list of policy schemas that match a specified filter value
        for a given customer.
      operationId: chromepolicy_customers_policy_schemas_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/chrome.management.policy
        Oauth2c:
        - https://www.googleapis.com/auth/chrome.management.policy
      - Oauth2:
        - https://www.googleapis.com/auth/chrome.management.policy.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/chrome.management.policy.readonly
      tags:
      - customers
      x-openapi-router-controller: openapi_server.controllers.customers_controller
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/chrome.management.policy: "See, edit,\
              \ create or delete policies applied to Chrome OS and Chrome Browsers\
              \ managed within your organization"
            https://www.googleapis.com/auth/chrome.management.policy.readonly: See
              policies applied to Chrome OS and Chrome Browsers managed within your
              organization
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/chrome.management.policy: "See, edit,\
              \ create or delete policies applied to Chrome OS and Chrome Browsers\
              \ managed within your organization"
            https://www.googleapis.com/auth/chrome.management.policy.readonly: See
              policies applied to Chrome OS and Chrome Browsers managed within your
              organization
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2c
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2c
