openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: The Google Tasks API lets you manage your tasks and task lists.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Google Tasks API
  version: v1
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
  x-origin:
  - format: google
    url: https://tasks.googleapis.com/$discovery/rest?version=v1
    version: v1
  x-providerName: googleapis.com
  x-serviceName: tasks
servers:
- url: https://tasks.googleapis.com/
tags:
- name: tasklists
- name: tasks
paths:
  /tasks/v1/lists/{tasklist}/clear:
    post:
      description: Clears all completed tasks from the specified task list. The affected
        tasks will be marked as 'hidden' and no longer be returned by default when
        retrieving all tasks for a task list.
      operationId: tasks_tasks_clear
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tasks
        Oauth2c:
        - https://www.googleapis.com/auth/tasks
      tags:
      - tasks
      x-openapi-router-controller: openapi_server.controllers.tasks_controller
  /tasks/v1/lists/{tasklist}/tasks:
    get:
      description: Returns all tasks in the specified task list.
      operationId: tasks_tasks_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tasks
        Oauth2c:
        - https://www.googleapis.com/auth/tasks
      - Oauth2:
        - https://www.googleapis.com/auth/tasks.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tasks.readonly
      tags:
      - tasks
      x-openapi-router-controller: openapi_server.controllers.tasks_controller
    post:
      description: Creates a new task on the specified task list.
      operationId: tasks_tasks_insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tasks
        Oauth2c:
        - https://www.googleapis.com/auth/tasks
      tags:
      - tasks
      x-openapi-router-controller: openapi_server.controllers.tasks_controller
  /tasks/v1/lists/{tasklist}/tasks/{task}:
    delete:
      description: Deletes the specified task from the task list.
      operationId: tasks_tasks_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tasks
        Oauth2c:
        - https://www.googleapis.com/auth/tasks
      tags:
      - tasks
      x-openapi-router-controller: openapi_server.controllers.tasks_controller
    get:
      description: Returns the specified task.
      operationId: tasks_tasks_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tasks
        Oauth2c:
        - https://www.googleapis.com/auth/tasks
      - Oauth2:
        - https://www.googleapis.com/auth/tasks.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tasks.readonly
      tags:
      - tasks
      x-openapi-router-controller: openapi_server.controllers.tasks_controller
    patch:
      description: Updates the specified task. This method supports patch semantics.
      operationId: tasks_tasks_patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tasks
        Oauth2c:
        - https://www.googleapis.com/auth/tasks
      tags:
      - tasks
      x-openapi-router-controller: openapi_server.controllers.tasks_controller
    put:
      description: Updates the specified task.
      operationId: tasks_tasks_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tasks
        Oauth2c:
        - https://www.googleapis.com/auth/tasks
      tags:
      - tasks
      x-openapi-router-controller: openapi_server.controllers.tasks_controller
  /tasks/v1/lists/{tasklist}/tasks/{task}/move:
    post:
      description: Moves the specified task to another position in the task list.
        This can include putting it as a child task under a new parent and/or move
        it to a different position among its sibling tasks.
      operationId: tasks_tasks_move
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tasks
        Oauth2c:
        - https://www.googleapis.com/auth/tasks
      tags:
      - tasks
      x-openapi-router-controller: openapi_server.controllers.tasks_controller
  /tasks/v1/users/@me/lists:
    get:
      description: Returns all the authenticated user's task lists.
      operationId: tasks_tasklists_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tasks
        Oauth2c:
        - https://www.googleapis.com/auth/tasks
      - Oauth2:
        - https://www.googleapis.com/auth/tasks.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tasks.readonly
      tags:
      - tasklists
      x-openapi-router-controller: openapi_server.controllers.tasklists_controller
    post:
      description: Creates a new task list and adds it to the authenticated user's
        task lists.
      operationId: tasks_tasklists_insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tasks
        Oauth2c:
        - https://www.googleapis.com/auth/tasks
      tags:
      - tasklists
      x-openapi-router-controller: openapi_server.controllers.tasklists_controller
  /tasks/v1/users/@me/lists/{tasklist}:
    delete:
      description: Deletes the authenticated user's specified task list.
      operationId: tasks_tasklists_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tasks
        Oauth2c:
        - https://www.googleapis.com/auth/tasks
      tags:
      - tasklists
      x-openapi-router-controller: openapi_server.controllers.tasklists_controller
    get:
      description: Returns the authenticated user's specified task list.
      operationId: tasks_tasklists_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tasks
        Oauth2c:
        - https://www.googleapis.com/auth/tasks
      - Oauth2:
        - https://www.googleapis.com/auth/tasks.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tasks.readonly
      tags:
      - tasklists
      x-openapi-router-controller: openapi_server.controllers.tasklists_controller
    patch:
      description: Updates the authenticated user's specified task list. This method
        supports patch semantics.
      operationId: tasks_tasklists_patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tasks
        Oauth2c:
        - https://www.googleapis.com/auth/tasks
      tags:
      - tasklists
      x-openapi-router-controller: openapi_server.controllers.tasklists_controller
    put:
      description: Updates the authenticated user's specified task list.
      operationId: tasks_tasklists_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tasks
        Oauth2c:
        - https://www.googleapis.com/auth/tasks
      tags:
      - tasklists
      x-openapi-router-controller: openapi_server.controllers.tasklists_controller
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/tasks: "Create, edit, organize, and delete\
              \ all your tasks"
            https://www.googleapis.com/auth/tasks.readonly: View your tasks
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/tasks: "Create, edit, organize, and delete\
              \ all your tasks"
            https://www.googleapis.com/auth/tasks.readonly: View your tasks
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2c
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2c
