QT += network

HEADERS += \
# Models
    $${PWD}/OAIAbsenceEntitlement.h \
    $${PWD}/OAIAbsenceEntitlement_value_inner.h \
    $${PWD}/OAIAbsenceEntitlement_value_inner_attributes.h \
    $${PWD}/OAIAbsencePeriodsResponse.h \
    $${PWD}/OAIAbsencePeriodsResponse_allOf_data.h \
    $${PWD}/OAIAbsencePeriodsResponse_allOf_data_attributes.h \
    $${PWD}/OAIAbsencePeriodsResponse_allOf_data_certificate.h \
    $${PWD}/OAIAbsencePeriodsResponse_allOf_data_employee.h \
    $${PWD}/OAIAbsencePeriodsResponse_allOf_data_employee_attributes.h \
    $${PWD}/OAIAbsencePeriodsResponse_allOf_data_time_off_type.h \
    $${PWD}/OAIAbsencePeriodsResponse_allOf_data_time_off_type_attributes.h \
    $${PWD}/OAIAttendancePeriodsResponse.h \
    $${PWD}/OAIAttendancePeriodsResponse_allOf_attributes.h \
    $${PWD}/OAIAttendancePeriodsResponse_allOf_data.h \
    $${PWD}/OAIAttribute.h \
    $${PWD}/OAICostCenters.h \
    $${PWD}/OAICreateTimeOffPeriodRequest.h \
    $${PWD}/OAICreateTimeOffPeriodResponse.h \
    $${PWD}/OAICreateTimeOffPeriodResponse_allOf_data.h \
    $${PWD}/OAICreateTimeOffPeriodResponse_allOf_data_attributes.h \
    $${PWD}/OAIDepartment.h \
    $${PWD}/OAIDetailedErrorResponse.h \
    $${PWD}/OAIDetailedErrorResponse_error.h \
    $${PWD}/OAIDetailedErrorResponse_error_detailed_message_inner.h \
    $${PWD}/OAIEmployee.h \
    $${PWD}/OAIEmployeeResponse.h \
    $${PWD}/OAIEmployee_attributes_inner.h \
    $${PWD}/OAIEmployeesResponse.h \
    $${PWD}/OAIErrorResponse.h \
    $${PWD}/OAIErrorResponse_error.h \
    $${PWD}/OAIHolidayCalendar.h \
    $${PWD}/OAINewAttendancePeriodRequest.h \
    $${PWD}/OAINewAttendancePeriodRequest_attendances_inner.h \
    $${PWD}/OAINewAttendancePeriodResponse.h \
    $${PWD}/OAINewAttendancePeriodResponse_allOf_data.h \
    $${PWD}/OAIOffice.h \
    $${PWD}/OAIResponse.h \
    $${PWD}/OAISupervisor.h \
    $${PWD}/OAITimeOffTypeResource.h \
    $${PWD}/OAITimeOffTypeResource_attributes.h \
    $${PWD}/OAIUpdateAttendancePeriodRequest.h \
    $${PWD}/OAIWorkSchedule.h \
    $${PWD}/OAI_company_time_off_types_get_200_response.h \
    $${PWD}/OAI_company_time_offs_post_201_response.h \
# APIs
    $${PWD}/OAIDefaultApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAbsenceEntitlement.cpp \
    $${PWD}/OAIAbsenceEntitlement_value_inner.cpp \
    $${PWD}/OAIAbsenceEntitlement_value_inner_attributes.cpp \
    $${PWD}/OAIAbsencePeriodsResponse.cpp \
    $${PWD}/OAIAbsencePeriodsResponse_allOf_data.cpp \
    $${PWD}/OAIAbsencePeriodsResponse_allOf_data_attributes.cpp \
    $${PWD}/OAIAbsencePeriodsResponse_allOf_data_certificate.cpp \
    $${PWD}/OAIAbsencePeriodsResponse_allOf_data_employee.cpp \
    $${PWD}/OAIAbsencePeriodsResponse_allOf_data_employee_attributes.cpp \
    $${PWD}/OAIAbsencePeriodsResponse_allOf_data_time_off_type.cpp \
    $${PWD}/OAIAbsencePeriodsResponse_allOf_data_time_off_type_attributes.cpp \
    $${PWD}/OAIAttendancePeriodsResponse.cpp \
    $${PWD}/OAIAttendancePeriodsResponse_allOf_attributes.cpp \
    $${PWD}/OAIAttendancePeriodsResponse_allOf_data.cpp \
    $${PWD}/OAIAttribute.cpp \
    $${PWD}/OAICostCenters.cpp \
    $${PWD}/OAICreateTimeOffPeriodRequest.cpp \
    $${PWD}/OAICreateTimeOffPeriodResponse.cpp \
    $${PWD}/OAICreateTimeOffPeriodResponse_allOf_data.cpp \
    $${PWD}/OAICreateTimeOffPeriodResponse_allOf_data_attributes.cpp \
    $${PWD}/OAIDepartment.cpp \
    $${PWD}/OAIDetailedErrorResponse.cpp \
    $${PWD}/OAIDetailedErrorResponse_error.cpp \
    $${PWD}/OAIDetailedErrorResponse_error_detailed_message_inner.cpp \
    $${PWD}/OAIEmployee.cpp \
    $${PWD}/OAIEmployeeResponse.cpp \
    $${PWD}/OAIEmployee_attributes_inner.cpp \
    $${PWD}/OAIEmployeesResponse.cpp \
    $${PWD}/OAIErrorResponse.cpp \
    $${PWD}/OAIErrorResponse_error.cpp \
    $${PWD}/OAIHolidayCalendar.cpp \
    $${PWD}/OAINewAttendancePeriodRequest.cpp \
    $${PWD}/OAINewAttendancePeriodRequest_attendances_inner.cpp \
    $${PWD}/OAINewAttendancePeriodResponse.cpp \
    $${PWD}/OAINewAttendancePeriodResponse_allOf_data.cpp \
    $${PWD}/OAIOffice.cpp \
    $${PWD}/OAIResponse.cpp \
    $${PWD}/OAISupervisor.cpp \
    $${PWD}/OAITimeOffTypeResource.cpp \
    $${PWD}/OAITimeOffTypeResource_attributes.cpp \
    $${PWD}/OAIUpdateAttendancePeriodRequest.cpp \
    $${PWD}/OAIWorkSchedule.cpp \
    $${PWD}/OAI_company_time_off_types_get_200_response.cpp \
    $${PWD}/OAI_company_time_offs_post_201_response.cpp \
# APIs
    $${PWD}/OAIDefaultApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
