# coding: utf-8

import pytest
import json
from aiohttp import web

from openapi_server.models.api_v2010_account_call_siprec import ApiV2010AccountCallSiprec
from openapi_server.models.siprec_enum_track import SiprecEnumTrack
from openapi_server.models.siprec_enum_update_status import SiprecEnumUpdateStatus


pytestmark = pytest.mark.asyncio

@pytest.mark.skip("application/x-www-form-urlencoded not supported by Connexion")
async def test_create_siprec(client):
    """Test case for create_siprec

    
    """
    headers = { 
        'Accept': 'application/json',
        'Content-Type': 'application/x-www-form-urlencoded',
        'Authorization': 'BasicZm9vOmJhcg==',
    }
    data = {
        'connector_name': 'connector_name_example',
        'name': 'name_example',
        'parameter1_name': 'parameter1_name_example',
        'parameter1_value': 'parameter1_value_example',
        'parameter10_name': 'parameter10_name_example',
        'parameter10_value': 'parameter10_value_example',
        'parameter11_name': 'parameter11_name_example',
        'parameter11_value': 'parameter11_value_example',
        'parameter12_name': 'parameter12_name_example',
        'parameter12_value': 'parameter12_value_example',
        'parameter13_name': 'parameter13_name_example',
        'parameter13_value': 'parameter13_value_example',
        'parameter14_name': 'parameter14_name_example',
        'parameter14_value': 'parameter14_value_example',
        'parameter15_name': 'parameter15_name_example',
        'parameter15_value': 'parameter15_value_example',
        'parameter16_name': 'parameter16_name_example',
        'parameter16_value': 'parameter16_value_example',
        'parameter17_name': 'parameter17_name_example',
        'parameter17_value': 'parameter17_value_example',
        'parameter18_name': 'parameter18_name_example',
        'parameter18_value': 'parameter18_value_example',
        'parameter19_name': 'parameter19_name_example',
        'parameter19_value': 'parameter19_value_example',
        'parameter2_name': 'parameter2_name_example',
        'parameter2_value': 'parameter2_value_example',
        'parameter20_name': 'parameter20_name_example',
        'parameter20_value': 'parameter20_value_example',
        'parameter21_name': 'parameter21_name_example',
        'parameter21_value': 'parameter21_value_example',
        'parameter22_name': 'parameter22_name_example',
        'parameter22_value': 'parameter22_value_example',
        'parameter23_name': 'parameter23_name_example',
        'parameter23_value': 'parameter23_value_example',
        'parameter24_name': 'parameter24_name_example',
        'parameter24_value': 'parameter24_value_example',
        'parameter25_name': 'parameter25_name_example',
        'parameter25_value': 'parameter25_value_example',
        'parameter26_name': 'parameter26_name_example',
        'parameter26_value': 'parameter26_value_example',
        'parameter27_name': 'parameter27_name_example',
        'parameter27_value': 'parameter27_value_example',
        'parameter28_name': 'parameter28_name_example',
        'parameter28_value': 'parameter28_value_example',
        'parameter29_name': 'parameter29_name_example',
        'parameter29_value': 'parameter29_value_example',
        'parameter3_name': 'parameter3_name_example',
        'parameter3_value': 'parameter3_value_example',
        'parameter30_name': 'parameter30_name_example',
        'parameter30_value': 'parameter30_value_example',
        'parameter31_name': 'parameter31_name_example',
        'parameter31_value': 'parameter31_value_example',
        'parameter32_name': 'parameter32_name_example',
        'parameter32_value': 'parameter32_value_example',
        'parameter33_name': 'parameter33_name_example',
        'parameter33_value': 'parameter33_value_example',
        'parameter34_name': 'parameter34_name_example',
        'parameter34_value': 'parameter34_value_example',
        'parameter35_name': 'parameter35_name_example',
        'parameter35_value': 'parameter35_value_example',
        'parameter36_name': 'parameter36_name_example',
        'parameter36_value': 'parameter36_value_example',
        'parameter37_name': 'parameter37_name_example',
        'parameter37_value': 'parameter37_value_example',
        'parameter38_name': 'parameter38_name_example',
        'parameter38_value': 'parameter38_value_example',
        'parameter39_name': 'parameter39_name_example',
        'parameter39_value': 'parameter39_value_example',
        'parameter4_name': 'parameter4_name_example',
        'parameter4_value': 'parameter4_value_example',
        'parameter40_name': 'parameter40_name_example',
        'parameter40_value': 'parameter40_value_example',
        'parameter41_name': 'parameter41_name_example',
        'parameter41_value': 'parameter41_value_example',
        'parameter42_name': 'parameter42_name_example',
        'parameter42_value': 'parameter42_value_example',
        'parameter43_name': 'parameter43_name_example',
        'parameter43_value': 'parameter43_value_example',
        'parameter44_name': 'parameter44_name_example',
        'parameter44_value': 'parameter44_value_example',
        'parameter45_name': 'parameter45_name_example',
        'parameter45_value': 'parameter45_value_example',
        'parameter46_name': 'parameter46_name_example',
        'parameter46_value': 'parameter46_value_example',
        'parameter47_name': 'parameter47_name_example',
        'parameter47_value': 'parameter47_value_example',
        'parameter48_name': 'parameter48_name_example',
        'parameter48_value': 'parameter48_value_example',
        'parameter49_name': 'parameter49_name_example',
        'parameter49_value': 'parameter49_value_example',
        'parameter5_name': 'parameter5_name_example',
        'parameter5_value': 'parameter5_value_example',
        'parameter50_name': 'parameter50_name_example',
        'parameter50_value': 'parameter50_value_example',
        'parameter51_name': 'parameter51_name_example',
        'parameter51_value': 'parameter51_value_example',
        'parameter52_name': 'parameter52_name_example',
        'parameter52_value': 'parameter52_value_example',
        'parameter53_name': 'parameter53_name_example',
        'parameter53_value': 'parameter53_value_example',
        'parameter54_name': 'parameter54_name_example',
        'parameter54_value': 'parameter54_value_example',
        'parameter55_name': 'parameter55_name_example',
        'parameter55_value': 'parameter55_value_example',
        'parameter56_name': 'parameter56_name_example',
        'parameter56_value': 'parameter56_value_example',
        'parameter57_name': 'parameter57_name_example',
        'parameter57_value': 'parameter57_value_example',
        'parameter58_name': 'parameter58_name_example',
        'parameter58_value': 'parameter58_value_example',
        'parameter59_name': 'parameter59_name_example',
        'parameter59_value': 'parameter59_value_example',
        'parameter6_name': 'parameter6_name_example',
        'parameter6_value': 'parameter6_value_example',
        'parameter60_name': 'parameter60_name_example',
        'parameter60_value': 'parameter60_value_example',
        'parameter61_name': 'parameter61_name_example',
        'parameter61_value': 'parameter61_value_example',
        'parameter62_name': 'parameter62_name_example',
        'parameter62_value': 'parameter62_value_example',
        'parameter63_name': 'parameter63_name_example',
        'parameter63_value': 'parameter63_value_example',
        'parameter64_name': 'parameter64_name_example',
        'parameter64_value': 'parameter64_value_example',
        'parameter65_name': 'parameter65_name_example',
        'parameter65_value': 'parameter65_value_example',
        'parameter66_name': 'parameter66_name_example',
        'parameter66_value': 'parameter66_value_example',
        'parameter67_name': 'parameter67_name_example',
        'parameter67_value': 'parameter67_value_example',
        'parameter68_name': 'parameter68_name_example',
        'parameter68_value': 'parameter68_value_example',
        'parameter69_name': 'parameter69_name_example',
        'parameter69_value': 'parameter69_value_example',
        'parameter7_name': 'parameter7_name_example',
        'parameter7_value': 'parameter7_value_example',
        'parameter70_name': 'parameter70_name_example',
        'parameter70_value': 'parameter70_value_example',
        'parameter71_name': 'parameter71_name_example',
        'parameter71_value': 'parameter71_value_example',
        'parameter72_name': 'parameter72_name_example',
        'parameter72_value': 'parameter72_value_example',
        'parameter73_name': 'parameter73_name_example',
        'parameter73_value': 'parameter73_value_example',
        'parameter74_name': 'parameter74_name_example',
        'parameter74_value': 'parameter74_value_example',
        'parameter75_name': 'parameter75_name_example',
        'parameter75_value': 'parameter75_value_example',
        'parameter76_name': 'parameter76_name_example',
        'parameter76_value': 'parameter76_value_example',
        'parameter77_name': 'parameter77_name_example',
        'parameter77_value': 'parameter77_value_example',
        'parameter78_name': 'parameter78_name_example',
        'parameter78_value': 'parameter78_value_example',
        'parameter79_name': 'parameter79_name_example',
        'parameter79_value': 'parameter79_value_example',
        'parameter8_name': 'parameter8_name_example',
        'parameter8_value': 'parameter8_value_example',
        'parameter80_name': 'parameter80_name_example',
        'parameter80_value': 'parameter80_value_example',
        'parameter81_name': 'parameter81_name_example',
        'parameter81_value': 'parameter81_value_example',
        'parameter82_name': 'parameter82_name_example',
        'parameter82_value': 'parameter82_value_example',
        'parameter83_name': 'parameter83_name_example',
        'parameter83_value': 'parameter83_value_example',
        'parameter84_name': 'parameter84_name_example',
        'parameter84_value': 'parameter84_value_example',
        'parameter85_name': 'parameter85_name_example',
        'parameter85_value': 'parameter85_value_example',
        'parameter86_name': 'parameter86_name_example',
        'parameter86_value': 'parameter86_value_example',
        'parameter87_name': 'parameter87_name_example',
        'parameter87_value': 'parameter87_value_example',
        'parameter88_name': 'parameter88_name_example',
        'parameter88_value': 'parameter88_value_example',
        'parameter89_name': 'parameter89_name_example',
        'parameter89_value': 'parameter89_value_example',
        'parameter9_name': 'parameter9_name_example',
        'parameter9_value': 'parameter9_value_example',
        'parameter90_name': 'parameter90_name_example',
        'parameter90_value': 'parameter90_value_example',
        'parameter91_name': 'parameter91_name_example',
        'parameter91_value': 'parameter91_value_example',
        'parameter92_name': 'parameter92_name_example',
        'parameter92_value': 'parameter92_value_example',
        'parameter93_name': 'parameter93_name_example',
        'parameter93_value': 'parameter93_value_example',
        'parameter94_name': 'parameter94_name_example',
        'parameter94_value': 'parameter94_value_example',
        'parameter95_name': 'parameter95_name_example',
        'parameter95_value': 'parameter95_value_example',
        'parameter96_name': 'parameter96_name_example',
        'parameter96_value': 'parameter96_value_example',
        'parameter97_name': 'parameter97_name_example',
        'parameter97_value': 'parameter97_value_example',
        'parameter98_name': 'parameter98_name_example',
        'parameter98_value': 'parameter98_value_example',
        'parameter99_name': 'parameter99_name_example',
        'parameter99_value': 'parameter99_value_example',
        'status_callback': 'status_callback_example',
        'status_callback_method': 'status_callback_method_example',
        'track': openapi_server.SiprecEnumTrack()
        }
    response = await client.request(
        method='POST',
        path='/2010-04-01/Accounts/{account_sid}/Calls/{call_sid}/Siprec.json'.format(account_sid='account_sid_example', call_sid='call_sid_example'),
        headers=headers,
        data=data,
        )
    assert response.status == 200, 'Response body is : ' + (await response.read()).decode('utf-8')


pytestmark = pytest.mark.asyncio

@pytest.mark.skip("application/x-www-form-urlencoded not supported by Connexion")
async def test_update_siprec(client):
    """Test case for update_siprec

    
    """
    headers = { 
        'Accept': 'application/json',
        'Content-Type': 'application/x-www-form-urlencoded',
        'Authorization': 'BasicZm9vOmJhcg==',
    }
    data = {
        'status': openapi_server.SiprecEnumUpdateStatus()
        }
    response = await client.request(
        method='POST',
        path='/2010-04-01/Accounts/{account_sid}/Calls/{call_sid}/Siprec/{sid_jso}'.format(account_sid='account_sid_example', call_sid='call_sid_example', sid='sid_example'),
        headers=headers,
        data=data,
        )
    assert response.status == 200, 'Response body is : ' + (await response.read()).decode('utf-8')

