openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: Allows developers to manage billing for their Google Cloud Platform
    projects programmatically.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Cloud Billing API
  version: v1beta
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
  x-origin:
  - format: google
    url: https://cloudbilling.googleapis.com/$discovery/rest?version=v1beta
    version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: cloudbilling
servers:
- url: https://cloudbilling.googleapis.com/
tags:
- name: billingAccounts
- name: skuGroups
- name: skus
- name: v1beta
paths:
  /v1beta/skuGroups:
    get:
      description: Lists all publicly listed SKU groups.
      operationId: cloudbilling_sku_groups_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-billing
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-billing
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-billing.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-billing.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - skuGroups
      x-openapi-router-controller: openapi_server.controllers.sku_groups_controller
  /v1beta/{billingAccount}:estimateCostScenario:
    post:
      description: "Use custom pricing in the estimate, using a `CostScenario` with\
        \ a defined `billingAccount`."
      operationId: cloudbilling_billing_accounts_estimate_cost_scenario
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-billing
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-billing
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-billing.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-billing.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - billingAccounts
      x-openapi-router-controller: openapi_server.controllers.billing_accounts_controller
  /v1beta/{name}:
    get:
      description: Gets the latest price for the given SKU.
      operationId: cloudbilling_skus_price_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-billing
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-billing
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-billing.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-billing.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - skus
      x-openapi-router-controller: openapi_server.controllers.skus_controller
  /v1beta/{parent}/prices:
    get:
      description: Lists the latest prices for all SKUs.
      operationId: cloudbilling_skus_prices_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-billing
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-billing
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-billing.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-billing.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - skus
      x-openapi-router-controller: openapi_server.controllers.skus_controller
  /v1beta/{parent}/services:
    get:
      description: Lists services visible to a billing account.
      operationId: cloudbilling_billing_accounts_services_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-billing
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-billing
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-billing.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-billing.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - billingAccounts
      x-openapi-router-controller: openapi_server.controllers.billing_accounts_controller
  /v1beta/{parent}/skuGroups:
    get:
      description: Lists SKU groups visible to a billing account.
      operationId: cloudbilling_billing_accounts_sku_groups_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-billing
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-billing
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-billing.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-billing.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - billingAccounts
      x-openapi-router-controller: openapi_server.controllers.billing_accounts_controller
  /v1beta/{parent}/skus:
    get:
      description: Lists all publicly listed SKUs contained by a publicly listed SKU
        group.
      operationId: cloudbilling_sku_groups_skus_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-billing
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-billing
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-billing.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-billing.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - skuGroups
      x-openapi-router-controller: openapi_server.controllers.sku_groups_controller
  /v1beta:estimateCostScenario:
    post:
      description: Estimate list prices using a `CostScenario` without a defined `billingAccount`.
      operationId: cloudbilling_estimate_cost_scenario
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-billing
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-billing
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-billing.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-billing.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - v1beta
      x-openapi-router-controller: openapi_server.controllers.v1beta_controller
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/cloud-billing: View and manage your Google
              Cloud Platform billing accounts
            https://www.googleapis.com/auth/cloud-billing.readonly: View your Google
              Cloud Platform billing accounts
            https://www.googleapis.com/auth/cloud-platform: "See, edit, configure,\
              \ and delete your Google Cloud data and see the email address for your\
              \ Google Account."
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/cloud-billing: View and manage your Google
              Cloud Platform billing accounts
            https://www.googleapis.com/auth/cloud-billing.readonly: View your Google
              Cloud Platform billing accounts
            https://www.googleapis.com/auth/cloud-platform: "See, edit, configure,\
              \ and delete your Google Cloud data and see the email address for your\
              \ Google Account."
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2c
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2c
