QT += network

HEADERS += \
# Models
    $${PWD}/OAIGoogleApi__HttpBody.h \
    $${PWD}/OAIGoogleCloudMlV1_AutomatedStoppingConfig_DecayCurveAutomatedStoppingConfig.h \
    $${PWD}/OAIGoogleCloudMlV1_AutomatedStoppingConfig_MedianAutomatedStoppingConfig.h \
    $${PWD}/OAIGoogleCloudMlV1_HyperparameterOutput_HyperparameterMetric.h \
    $${PWD}/OAIGoogleCloudMlV1_Measurement_Metric.h \
    $${PWD}/OAIGoogleCloudMlV1_StudyConfigParameterSpec_CategoricalValueSpec.h \
    $${PWD}/OAIGoogleCloudMlV1_StudyConfigParameterSpec_DiscreteValueSpec.h \
    $${PWD}/OAIGoogleCloudMlV1_StudyConfigParameterSpec_DoubleValueSpec.h \
    $${PWD}/OAIGoogleCloudMlV1_StudyConfigParameterSpec_IntegerValueSpec.h \
    $${PWD}/OAIGoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentCategoricalValueSpec.h \
    $${PWD}/OAIGoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentDiscreteValueSpec.h \
    $${PWD}/OAIGoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentIntValueSpec.h \
    $${PWD}/OAIGoogleCloudMlV1_StudyConfig_MetricSpec.h \
    $${PWD}/OAIGoogleCloudMlV1_StudyConfig_ParameterSpec.h \
    $${PWD}/OAIGoogleCloudMlV1_Trial_Parameter.h \
    $${PWD}/OAIGoogleCloudMlV1__AcceleratorConfig.h \
    $${PWD}/OAIGoogleCloudMlV1__AddTrialMeasurementRequest.h \
    $${PWD}/OAIGoogleCloudMlV1__AutoScaling.h \
    $${PWD}/OAIGoogleCloudMlV1__AutomatedStoppingConfig.h \
    $${PWD}/OAIGoogleCloudMlV1__BuiltInAlgorithmOutput.h \
    $${PWD}/OAIGoogleCloudMlV1__Capability.h \
    $${PWD}/OAIGoogleCloudMlV1__CheckTrialEarlyStoppingStateMetatdata.h \
    $${PWD}/OAIGoogleCloudMlV1__CheckTrialEarlyStoppingStateResponse.h \
    $${PWD}/OAIGoogleCloudMlV1__CompleteTrialRequest.h \
    $${PWD}/OAIGoogleCloudMlV1__Config.h \
    $${PWD}/OAIGoogleCloudMlV1__ContainerPort.h \
    $${PWD}/OAIGoogleCloudMlV1__ContainerSpec.h \
    $${PWD}/OAIGoogleCloudMlV1__DiskConfig.h \
    $${PWD}/OAIGoogleCloudMlV1__EncryptionConfig.h \
    $${PWD}/OAIGoogleCloudMlV1__EnvVar.h \
    $${PWD}/OAIGoogleCloudMlV1__ExplainRequest.h \
    $${PWD}/OAIGoogleCloudMlV1__ExplanationConfig.h \
    $${PWD}/OAIGoogleCloudMlV1__GetConfigResponse.h \
    $${PWD}/OAIGoogleCloudMlV1__HyperparameterOutput.h \
    $${PWD}/OAIGoogleCloudMlV1__HyperparameterSpec.h \
    $${PWD}/OAIGoogleCloudMlV1__IntegratedGradientsAttribution.h \
    $${PWD}/OAIGoogleCloudMlV1__Job.h \
    $${PWD}/OAIGoogleCloudMlV1__ListJobsResponse.h \
    $${PWD}/OAIGoogleCloudMlV1__ListLocationsResponse.h \
    $${PWD}/OAIGoogleCloudMlV1__ListModelsResponse.h \
    $${PWD}/OAIGoogleCloudMlV1__ListOptimalTrialsResponse.h \
    $${PWD}/OAIGoogleCloudMlV1__ListStudiesResponse.h \
    $${PWD}/OAIGoogleCloudMlV1__ListTrialsResponse.h \
    $${PWD}/OAIGoogleCloudMlV1__ListVersionsResponse.h \
    $${PWD}/OAIGoogleCloudMlV1__Location.h \
    $${PWD}/OAIGoogleCloudMlV1__ManualScaling.h \
    $${PWD}/OAIGoogleCloudMlV1__Measurement.h \
    $${PWD}/OAIGoogleCloudMlV1__MetricSpec.h \
    $${PWD}/OAIGoogleCloudMlV1__Model.h \
    $${PWD}/OAIGoogleCloudMlV1__OperationMetadata.h \
    $${PWD}/OAIGoogleCloudMlV1__ParameterSpec.h \
    $${PWD}/OAIGoogleCloudMlV1__PredictRequest.h \
    $${PWD}/OAIGoogleCloudMlV1__PredictionInput.h \
    $${PWD}/OAIGoogleCloudMlV1__PredictionOutput.h \
    $${PWD}/OAIGoogleCloudMlV1__ReplicaConfig.h \
    $${PWD}/OAIGoogleCloudMlV1__RequestLoggingConfig.h \
    $${PWD}/OAIGoogleCloudMlV1__RouteMap.h \
    $${PWD}/OAIGoogleCloudMlV1__SampledShapleyAttribution.h \
    $${PWD}/OAIGoogleCloudMlV1__Scheduling.h \
    $${PWD}/OAIGoogleCloudMlV1__Study.h \
    $${PWD}/OAIGoogleCloudMlV1__StudyConfig.h \
    $${PWD}/OAIGoogleCloudMlV1__SuggestTrialsMetadata.h \
    $${PWD}/OAIGoogleCloudMlV1__SuggestTrialsRequest.h \
    $${PWD}/OAIGoogleCloudMlV1__SuggestTrialsResponse.h \
    $${PWD}/OAIGoogleCloudMlV1__TrainingInput.h \
    $${PWD}/OAIGoogleCloudMlV1__TrainingOutput.h \
    $${PWD}/OAIGoogleCloudMlV1__Trial.h \
    $${PWD}/OAIGoogleCloudMlV1__Version.h \
    $${PWD}/OAIGoogleCloudMlV1__XraiAttribution.h \
    $${PWD}/OAIGoogleIamV1__AuditConfig.h \
    $${PWD}/OAIGoogleIamV1__AuditLogConfig.h \
    $${PWD}/OAIGoogleIamV1__Binding.h \
    $${PWD}/OAIGoogleIamV1__Policy.h \
    $${PWD}/OAIGoogleIamV1__SetIamPolicyRequest.h \
    $${PWD}/OAIGoogleIamV1__TestIamPermissionsRequest.h \
    $${PWD}/OAIGoogleIamV1__TestIamPermissionsResponse.h \
    $${PWD}/OAIGoogleLongrunning__ListOperationsResponse.h \
    $${PWD}/OAIGoogleLongrunning__Operation.h \
    $${PWD}/OAIGoogleRpc__Status.h \
    $${PWD}/OAIGoogleType__Expr.h \
# APIs
    $${PWD}/OAIProjectsApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIGoogleApi__HttpBody.cpp \
    $${PWD}/OAIGoogleCloudMlV1_AutomatedStoppingConfig_DecayCurveAutomatedStoppingConfig.cpp \
    $${PWD}/OAIGoogleCloudMlV1_AutomatedStoppingConfig_MedianAutomatedStoppingConfig.cpp \
    $${PWD}/OAIGoogleCloudMlV1_HyperparameterOutput_HyperparameterMetric.cpp \
    $${PWD}/OAIGoogleCloudMlV1_Measurement_Metric.cpp \
    $${PWD}/OAIGoogleCloudMlV1_StudyConfigParameterSpec_CategoricalValueSpec.cpp \
    $${PWD}/OAIGoogleCloudMlV1_StudyConfigParameterSpec_DiscreteValueSpec.cpp \
    $${PWD}/OAIGoogleCloudMlV1_StudyConfigParameterSpec_DoubleValueSpec.cpp \
    $${PWD}/OAIGoogleCloudMlV1_StudyConfigParameterSpec_IntegerValueSpec.cpp \
    $${PWD}/OAIGoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentCategoricalValueSpec.cpp \
    $${PWD}/OAIGoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentDiscreteValueSpec.cpp \
    $${PWD}/OAIGoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentIntValueSpec.cpp \
    $${PWD}/OAIGoogleCloudMlV1_StudyConfig_MetricSpec.cpp \
    $${PWD}/OAIGoogleCloudMlV1_StudyConfig_ParameterSpec.cpp \
    $${PWD}/OAIGoogleCloudMlV1_Trial_Parameter.cpp \
    $${PWD}/OAIGoogleCloudMlV1__AcceleratorConfig.cpp \
    $${PWD}/OAIGoogleCloudMlV1__AddTrialMeasurementRequest.cpp \
    $${PWD}/OAIGoogleCloudMlV1__AutoScaling.cpp \
    $${PWD}/OAIGoogleCloudMlV1__AutomatedStoppingConfig.cpp \
    $${PWD}/OAIGoogleCloudMlV1__BuiltInAlgorithmOutput.cpp \
    $${PWD}/OAIGoogleCloudMlV1__Capability.cpp \
    $${PWD}/OAIGoogleCloudMlV1__CheckTrialEarlyStoppingStateMetatdata.cpp \
    $${PWD}/OAIGoogleCloudMlV1__CheckTrialEarlyStoppingStateResponse.cpp \
    $${PWD}/OAIGoogleCloudMlV1__CompleteTrialRequest.cpp \
    $${PWD}/OAIGoogleCloudMlV1__Config.cpp \
    $${PWD}/OAIGoogleCloudMlV1__ContainerPort.cpp \
    $${PWD}/OAIGoogleCloudMlV1__ContainerSpec.cpp \
    $${PWD}/OAIGoogleCloudMlV1__DiskConfig.cpp \
    $${PWD}/OAIGoogleCloudMlV1__EncryptionConfig.cpp \
    $${PWD}/OAIGoogleCloudMlV1__EnvVar.cpp \
    $${PWD}/OAIGoogleCloudMlV1__ExplainRequest.cpp \
    $${PWD}/OAIGoogleCloudMlV1__ExplanationConfig.cpp \
    $${PWD}/OAIGoogleCloudMlV1__GetConfigResponse.cpp \
    $${PWD}/OAIGoogleCloudMlV1__HyperparameterOutput.cpp \
    $${PWD}/OAIGoogleCloudMlV1__HyperparameterSpec.cpp \
    $${PWD}/OAIGoogleCloudMlV1__IntegratedGradientsAttribution.cpp \
    $${PWD}/OAIGoogleCloudMlV1__Job.cpp \
    $${PWD}/OAIGoogleCloudMlV1__ListJobsResponse.cpp \
    $${PWD}/OAIGoogleCloudMlV1__ListLocationsResponse.cpp \
    $${PWD}/OAIGoogleCloudMlV1__ListModelsResponse.cpp \
    $${PWD}/OAIGoogleCloudMlV1__ListOptimalTrialsResponse.cpp \
    $${PWD}/OAIGoogleCloudMlV1__ListStudiesResponse.cpp \
    $${PWD}/OAIGoogleCloudMlV1__ListTrialsResponse.cpp \
    $${PWD}/OAIGoogleCloudMlV1__ListVersionsResponse.cpp \
    $${PWD}/OAIGoogleCloudMlV1__Location.cpp \
    $${PWD}/OAIGoogleCloudMlV1__ManualScaling.cpp \
    $${PWD}/OAIGoogleCloudMlV1__Measurement.cpp \
    $${PWD}/OAIGoogleCloudMlV1__MetricSpec.cpp \
    $${PWD}/OAIGoogleCloudMlV1__Model.cpp \
    $${PWD}/OAIGoogleCloudMlV1__OperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudMlV1__ParameterSpec.cpp \
    $${PWD}/OAIGoogleCloudMlV1__PredictRequest.cpp \
    $${PWD}/OAIGoogleCloudMlV1__PredictionInput.cpp \
    $${PWD}/OAIGoogleCloudMlV1__PredictionOutput.cpp \
    $${PWD}/OAIGoogleCloudMlV1__ReplicaConfig.cpp \
    $${PWD}/OAIGoogleCloudMlV1__RequestLoggingConfig.cpp \
    $${PWD}/OAIGoogleCloudMlV1__RouteMap.cpp \
    $${PWD}/OAIGoogleCloudMlV1__SampledShapleyAttribution.cpp \
    $${PWD}/OAIGoogleCloudMlV1__Scheduling.cpp \
    $${PWD}/OAIGoogleCloudMlV1__Study.cpp \
    $${PWD}/OAIGoogleCloudMlV1__StudyConfig.cpp \
    $${PWD}/OAIGoogleCloudMlV1__SuggestTrialsMetadata.cpp \
    $${PWD}/OAIGoogleCloudMlV1__SuggestTrialsRequest.cpp \
    $${PWD}/OAIGoogleCloudMlV1__SuggestTrialsResponse.cpp \
    $${PWD}/OAIGoogleCloudMlV1__TrainingInput.cpp \
    $${PWD}/OAIGoogleCloudMlV1__TrainingOutput.cpp \
    $${PWD}/OAIGoogleCloudMlV1__Trial.cpp \
    $${PWD}/OAIGoogleCloudMlV1__Version.cpp \
    $${PWD}/OAIGoogleCloudMlV1__XraiAttribution.cpp \
    $${PWD}/OAIGoogleIamV1__AuditConfig.cpp \
    $${PWD}/OAIGoogleIamV1__AuditLogConfig.cpp \
    $${PWD}/OAIGoogleIamV1__Binding.cpp \
    $${PWD}/OAIGoogleIamV1__Policy.cpp \
    $${PWD}/OAIGoogleIamV1__SetIamPolicyRequest.cpp \
    $${PWD}/OAIGoogleIamV1__TestIamPermissionsRequest.cpp \
    $${PWD}/OAIGoogleIamV1__TestIamPermissionsResponse.cpp \
    $${PWD}/OAIGoogleLongrunning__ListOperationsResponse.cpp \
    $${PWD}/OAIGoogleLongrunning__Operation.cpp \
    $${PWD}/OAIGoogleRpc__Status.cpp \
    $${PWD}/OAIGoogleType__Expr.cpp \
# APIs
    $${PWD}/OAIProjectsApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
