/**
 * App Center Client
 * Microsoft Visual Studio App Center API
 *
 * The version of the OpenAPI document: v0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiTokenDeleteResponse model module.
 * @module model/ApiTokenDeleteResponse
 * @version v0.1
 */
class ApiTokenDeleteResponse {
    /**
     * Constructs a new <code>ApiTokenDeleteResponse</code>.
     * @alias module:model/ApiTokenDeleteResponse
     * @param id {String} The unique id (UUID) of the api token
     * @param tokenHash {String} The hashed value of api token
     */
    constructor(id, tokenHash) { 
        
        ApiTokenDeleteResponse.initialize(this, id, tokenHash);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, tokenHash) { 
        obj['id'] = id;
        obj['token_hash'] = tokenHash;
    }

    /**
     * Constructs a <code>ApiTokenDeleteResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiTokenDeleteResponse} obj Optional instance to populate.
     * @return {module:model/ApiTokenDeleteResponse} The populated <code>ApiTokenDeleteResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiTokenDeleteResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('token_hash')) {
                obj['token_hash'] = ApiClient.convertToType(data['token_hash'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiTokenDeleteResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiTokenDeleteResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiTokenDeleteResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['token_hash'] && !(typeof data['token_hash'] === 'string' || data['token_hash'] instanceof String)) {
            throw new Error("Expected the field `token_hash` to be a primitive type in the JSON string but got " + data['token_hash']);
        }

        return true;
    }


}

ApiTokenDeleteResponse.RequiredProperties = ["id", "token_hash"];

/**
 * The unique id (UUID) of the api token
 * @member {String} id
 */
ApiTokenDeleteResponse.prototype['id'] = undefined;

/**
 * The hashed value of api token
 * @member {String} token_hash
 */
ApiTokenDeleteResponse.prototype['token_hash'] = undefined;






export default ApiTokenDeleteResponse;

