QT += network

HEADERS += \
# Models
    $${PWD}/OAIApiDiagnostic_Get_200_response.h \
    $${PWD}/OAIApiDiagnostic_ListByService_200_response.h \
    $${PWD}/OAIApiDiagnostic_ListByService_200_response_value_inner.h \
    $${PWD}/OAIApiDiagnostic_ListByService_200_response_value_inner_properties.h \
    $${PWD}/OAIApiDiagnostic_ListByService_200_response_value_inner_properties_backend.h \
    $${PWD}/OAIApiDiagnostic_ListByService_200_response_value_inner_properties_backend_request.h \
    $${PWD}/OAIApiDiagnostic_ListByService_200_response_value_inner_properties_backend_request_body.h \
    $${PWD}/OAIApiDiagnostic_ListByService_200_response_value_inner_properties_sampling.h \
    $${PWD}/OAIApiIssueAttachment_Get_200_response.h \
    $${PWD}/OAIApiIssueAttachment_ListByService_200_response.h \
    $${PWD}/OAIApiIssueAttachment_ListByService_200_response_value_inner.h \
    $${PWD}/OAIApiIssueAttachment_ListByService_200_response_value_inner_properties.h \
    $${PWD}/OAIApiIssueComment_Get_200_response.h \
    $${PWD}/OAIApiIssueComment_ListByService_200_response.h \
    $${PWD}/OAIApiIssueComment_ListByService_200_response_value_inner.h \
    $${PWD}/OAIApiIssueComment_ListByService_200_response_value_inner_properties.h \
    $${PWD}/OAIApiIssue_Get_200_response.h \
    $${PWD}/OAIApiIssue_ListByService_200_response.h \
    $${PWD}/OAIApiIssue_ListByService_200_response_value_inner.h \
    $${PWD}/OAIApiIssue_ListByService_200_response_value_inner_properties.h \
    $${PWD}/OAIApiIssue_Update_request.h \
    $${PWD}/OAIApiIssue_Update_request_properties.h \
    $${PWD}/OAIApiOperationPolicy_Get_200_response.h \
    $${PWD}/OAIApiOperationPolicy_ListByOperation_200_response.h \
    $${PWD}/OAIApiOperationPolicy_ListByOperation_200_response_value_inner.h \
    $${PWD}/OAIApiOperationPolicy_ListByOperation_200_response_value_inner_properties.h \
    $${PWD}/OAIApiOperation_Get_200_response.h \
    $${PWD}/OAIApiOperation_ListByApi_200_response.h \
    $${PWD}/OAIApiOperation_ListByApi_200_response_value_inner.h \
    $${PWD}/OAIApiOperation_ListByApi_200_response_value_inner_properties.h \
    $${PWD}/OAIApiOperation_Update_request.h \
    $${PWD}/OAIApiOperation_Update_request_properties.h \
    $${PWD}/OAIApiProduct_ListByApis_200_response.h \
    $${PWD}/OAIApiProduct_ListByApis_200_response_value_inner.h \
    $${PWD}/OAIApiProduct_ListByApis_200_response_value_inner_properties.h \
    $${PWD}/OAIApiRelease_Get_200_response.h \
    $${PWD}/OAIApiRelease_List_200_response.h \
    $${PWD}/OAIApiRelease_List_200_response_value_inner.h \
    $${PWD}/OAIApiRelease_List_200_response_value_inner_properties.h \
    $${PWD}/OAIApiRevisions_List_200_response.h \
    $${PWD}/OAIApiRevisions_List_200_response_value_inner.h \
    $${PWD}/OAIApiSchema_Get_200_response.h \
    $${PWD}/OAIApiSchema_ListByApi_200_response.h \
    $${PWD}/OAIApiSchema_ListByApi_200_response_value_inner.h \
    $${PWD}/OAIApiSchema_ListByApi_200_response_value_inner_properties.h \
    $${PWD}/OAIApiSchema_ListByApi_200_response_value_inner_properties_document.h \
    $${PWD}/OAIApi_CreateOrUpdate_request.h \
    $${PWD}/OAIApi_CreateOrUpdate_request_properties.h \
    $${PWD}/OAIApi_CreateOrUpdate_request_properties_wsdlSelector.h \
    $${PWD}/OAIApi_Get_200_response.h \
    $${PWD}/OAIApi_ListByService_200_response.h \
    $${PWD}/OAIApi_ListByService_200_response_value_inner.h \
    $${PWD}/OAIApi_ListByService_200_response_value_inner_properties.h \
    $${PWD}/OAIApi_ListByService_200_response_value_inner_properties_apiVersionSet.h \
    $${PWD}/OAIApi_ListByService_default_response.h \
    $${PWD}/OAIApi_ListByService_default_response_error.h \
    $${PWD}/OAIApi_ListByService_default_response_error_details_inner.h \
    $${PWD}/OAIApi_Update_request.h \
    $${PWD}/OAIApi_Update_request_properties.h \
    $${PWD}/OAIOperation_ListByTags_200_response.h \
    $${PWD}/OAIOperation_ListByTags_200_response_value_inner.h \
    $${PWD}/OAIOperation_ListByTags_200_response_value_inner_api.h \
    $${PWD}/OAIOperation_ListByTags_200_response_value_inner_operation.h \
    $${PWD}/OAIOperation_ListByTags_200_response_value_inner_product.h \
    $${PWD}/OAIOperation_ListByTags_200_response_value_inner_tag.h \
    $${PWD}/OAITagDescription_CreateOrUpdate_request.h \
    $${PWD}/OAITagDescription_CreateOrUpdate_request_properties.h \
    $${PWD}/OAITagDescription_Get_200_response.h \
    $${PWD}/OAITagDescription_ListByApi_200_response.h \
    $${PWD}/OAITagDescription_ListByApi_200_response_value_inner.h \
    $${PWD}/OAITagDescription_ListByApi_200_response_value_inner_properties.h \
    $${PWD}/OAITag_GetByOperation_200_response.h \
    $${PWD}/OAITag_ListByOperation_200_response.h \
    $${PWD}/OAITag_ListByOperation_200_response_value_inner.h \
    $${PWD}/OAITag_ListByOperation_200_response_value_inner_properties.h \
# APIs
    $${PWD}/OAIApiApi.h \
    $${PWD}/OAIApiDiagnosticApi.h \
    $${PWD}/OAIApiIssueApi.h \
    $${PWD}/OAIApiIssueAttachmentApi.h \
    $${PWD}/OAIApiIssueCommentApi.h \
    $${PWD}/OAIApiOperationApi.h \
    $${PWD}/OAIApiOperationPolicyApi.h \
    $${PWD}/OAIApiOperationTagApi.h \
    $${PWD}/OAIApiOperationsByTagApi.h \
    $${PWD}/OAIApiPolicyApi.h \
    $${PWD}/OAIApiProductApi.h \
    $${PWD}/OAIApiReleaseApi.h \
    $${PWD}/OAIApiRevisionApi.h \
    $${PWD}/OAIApiSchemaApi.h \
    $${PWD}/OAIApiTagApi.h \
    $${PWD}/OAIApiTagDescriptionApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIApiDiagnostic_Get_200_response.cpp \
    $${PWD}/OAIApiDiagnostic_ListByService_200_response.cpp \
    $${PWD}/OAIApiDiagnostic_ListByService_200_response_value_inner.cpp \
    $${PWD}/OAIApiDiagnostic_ListByService_200_response_value_inner_properties.cpp \
    $${PWD}/OAIApiDiagnostic_ListByService_200_response_value_inner_properties_backend.cpp \
    $${PWD}/OAIApiDiagnostic_ListByService_200_response_value_inner_properties_backend_request.cpp \
    $${PWD}/OAIApiDiagnostic_ListByService_200_response_value_inner_properties_backend_request_body.cpp \
    $${PWD}/OAIApiDiagnostic_ListByService_200_response_value_inner_properties_sampling.cpp \
    $${PWD}/OAIApiIssueAttachment_Get_200_response.cpp \
    $${PWD}/OAIApiIssueAttachment_ListByService_200_response.cpp \
    $${PWD}/OAIApiIssueAttachment_ListByService_200_response_value_inner.cpp \
    $${PWD}/OAIApiIssueAttachment_ListByService_200_response_value_inner_properties.cpp \
    $${PWD}/OAIApiIssueComment_Get_200_response.cpp \
    $${PWD}/OAIApiIssueComment_ListByService_200_response.cpp \
    $${PWD}/OAIApiIssueComment_ListByService_200_response_value_inner.cpp \
    $${PWD}/OAIApiIssueComment_ListByService_200_response_value_inner_properties.cpp \
    $${PWD}/OAIApiIssue_Get_200_response.cpp \
    $${PWD}/OAIApiIssue_ListByService_200_response.cpp \
    $${PWD}/OAIApiIssue_ListByService_200_response_value_inner.cpp \
    $${PWD}/OAIApiIssue_ListByService_200_response_value_inner_properties.cpp \
    $${PWD}/OAIApiIssue_Update_request.cpp \
    $${PWD}/OAIApiIssue_Update_request_properties.cpp \
    $${PWD}/OAIApiOperationPolicy_Get_200_response.cpp \
    $${PWD}/OAIApiOperationPolicy_ListByOperation_200_response.cpp \
    $${PWD}/OAIApiOperationPolicy_ListByOperation_200_response_value_inner.cpp \
    $${PWD}/OAIApiOperationPolicy_ListByOperation_200_response_value_inner_properties.cpp \
    $${PWD}/OAIApiOperation_Get_200_response.cpp \
    $${PWD}/OAIApiOperation_ListByApi_200_response.cpp \
    $${PWD}/OAIApiOperation_ListByApi_200_response_value_inner.cpp \
    $${PWD}/OAIApiOperation_ListByApi_200_response_value_inner_properties.cpp \
    $${PWD}/OAIApiOperation_Update_request.cpp \
    $${PWD}/OAIApiOperation_Update_request_properties.cpp \
    $${PWD}/OAIApiProduct_ListByApis_200_response.cpp \
    $${PWD}/OAIApiProduct_ListByApis_200_response_value_inner.cpp \
    $${PWD}/OAIApiProduct_ListByApis_200_response_value_inner_properties.cpp \
    $${PWD}/OAIApiRelease_Get_200_response.cpp \
    $${PWD}/OAIApiRelease_List_200_response.cpp \
    $${PWD}/OAIApiRelease_List_200_response_value_inner.cpp \
    $${PWD}/OAIApiRelease_List_200_response_value_inner_properties.cpp \
    $${PWD}/OAIApiRevisions_List_200_response.cpp \
    $${PWD}/OAIApiRevisions_List_200_response_value_inner.cpp \
    $${PWD}/OAIApiSchema_Get_200_response.cpp \
    $${PWD}/OAIApiSchema_ListByApi_200_response.cpp \
    $${PWD}/OAIApiSchema_ListByApi_200_response_value_inner.cpp \
    $${PWD}/OAIApiSchema_ListByApi_200_response_value_inner_properties.cpp \
    $${PWD}/OAIApiSchema_ListByApi_200_response_value_inner_properties_document.cpp \
    $${PWD}/OAIApi_CreateOrUpdate_request.cpp \
    $${PWD}/OAIApi_CreateOrUpdate_request_properties.cpp \
    $${PWD}/OAIApi_CreateOrUpdate_request_properties_wsdlSelector.cpp \
    $${PWD}/OAIApi_Get_200_response.cpp \
    $${PWD}/OAIApi_ListByService_200_response.cpp \
    $${PWD}/OAIApi_ListByService_200_response_value_inner.cpp \
    $${PWD}/OAIApi_ListByService_200_response_value_inner_properties.cpp \
    $${PWD}/OAIApi_ListByService_200_response_value_inner_properties_apiVersionSet.cpp \
    $${PWD}/OAIApi_ListByService_default_response.cpp \
    $${PWD}/OAIApi_ListByService_default_response_error.cpp \
    $${PWD}/OAIApi_ListByService_default_response_error_details_inner.cpp \
    $${PWD}/OAIApi_Update_request.cpp \
    $${PWD}/OAIApi_Update_request_properties.cpp \
    $${PWD}/OAIOperation_ListByTags_200_response.cpp \
    $${PWD}/OAIOperation_ListByTags_200_response_value_inner.cpp \
    $${PWD}/OAIOperation_ListByTags_200_response_value_inner_api.cpp \
    $${PWD}/OAIOperation_ListByTags_200_response_value_inner_operation.cpp \
    $${PWD}/OAIOperation_ListByTags_200_response_value_inner_product.cpp \
    $${PWD}/OAIOperation_ListByTags_200_response_value_inner_tag.cpp \
    $${PWD}/OAITagDescription_CreateOrUpdate_request.cpp \
    $${PWD}/OAITagDescription_CreateOrUpdate_request_properties.cpp \
    $${PWD}/OAITagDescription_Get_200_response.cpp \
    $${PWD}/OAITagDescription_ListByApi_200_response.cpp \
    $${PWD}/OAITagDescription_ListByApi_200_response_value_inner.cpp \
    $${PWD}/OAITagDescription_ListByApi_200_response_value_inner_properties.cpp \
    $${PWD}/OAITag_GetByOperation_200_response.cpp \
    $${PWD}/OAITag_ListByOperation_200_response.cpp \
    $${PWD}/OAITag_ListByOperation_200_response_value_inner.cpp \
    $${PWD}/OAITag_ListByOperation_200_response_value_inner_properties.cpp \
# APIs
    $${PWD}/OAIApiApi.cpp \
    $${PWD}/OAIApiDiagnosticApi.cpp \
    $${PWD}/OAIApiIssueApi.cpp \
    $${PWD}/OAIApiIssueAttachmentApi.cpp \
    $${PWD}/OAIApiIssueCommentApi.cpp \
    $${PWD}/OAIApiOperationApi.cpp \
    $${PWD}/OAIApiOperationPolicyApi.cpp \
    $${PWD}/OAIApiOperationTagApi.cpp \
    $${PWD}/OAIApiOperationsByTagApi.cpp \
    $${PWD}/OAIApiPolicyApi.cpp \
    $${PWD}/OAIApiProductApi.cpp \
    $${PWD}/OAIApiReleaseApi.cpp \
    $${PWD}/OAIApiRevisionApi.cpp \
    $${PWD}/OAIApiSchemaApi.cpp \
    $${PWD}/OAIApiTagApi.cpp \
    $${PWD}/OAIApiTagDescriptionApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
