/**
 * Management API
 * Configure and manage your Adyen company and merchant accounts, stores, and payment terminals. ## Authentication Each request to the Management API must be signed with an API key. [Generate your API key](https://docs.adyen.com/development-resources/api-credentials#generate-api-key) in the Customer Area and then set this key to the `X-API-Key` header value.  To access the live endpoints, you need to generate a new API key in your live Customer Area. ## Versioning  Management API handles versioning as part of the endpoint URL. For example, to send a request to this version of the `/companies/{companyId}/webhooks` endpoint, use:  ```text https://management-test.adyen.com/v3/companies/{companyId}/webhooks ```  ## Going live  To access the live endpoints, you need an API key from your live Customer Area. Use this API key to make requests to:  ```text https://management-live.adyen.com/v3 ```  ## Release notes Have a look at the [release notes](https://docs.adyen.com/release-notes/management-api) to find out what changed in this version!
 *
 * The version of the OpenAPI document: 3
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIMinorUnitsMonetaryValue.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIMinorUnitsMonetaryValue::OAIMinorUnitsMonetaryValue(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIMinorUnitsMonetaryValue::OAIMinorUnitsMonetaryValue() {
    this->initializeModel();
}

OAIMinorUnitsMonetaryValue::~OAIMinorUnitsMonetaryValue() {}

void OAIMinorUnitsMonetaryValue::initializeModel() {

    m_amount_isSet = false;
    m_amount_isValid = false;

    m_currency_code_isSet = false;
    m_currency_code_isValid = false;
}

void OAIMinorUnitsMonetaryValue::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIMinorUnitsMonetaryValue::fromJsonObject(QJsonObject json) {

    m_amount_isValid = ::OpenAPI::fromJsonValue(m_amount, json[QString("amount")]);
    m_amount_isSet = !json[QString("amount")].isNull() && m_amount_isValid;

    m_currency_code_isValid = ::OpenAPI::fromJsonValue(m_currency_code, json[QString("currencyCode")]);
    m_currency_code_isSet = !json[QString("currencyCode")].isNull() && m_currency_code_isValid;
}

QString OAIMinorUnitsMonetaryValue::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIMinorUnitsMonetaryValue::asJsonObject() const {
    QJsonObject obj;
    if (m_amount_isSet) {
        obj.insert(QString("amount"), ::OpenAPI::toJsonValue(m_amount));
    }
    if (m_currency_code_isSet) {
        obj.insert(QString("currencyCode"), ::OpenAPI::toJsonValue(m_currency_code));
    }
    return obj;
}

qint32 OAIMinorUnitsMonetaryValue::getAmount() const {
    return m_amount;
}
void OAIMinorUnitsMonetaryValue::setAmount(const qint32 &amount) {
    m_amount = amount;
    m_amount_isSet = true;
}

bool OAIMinorUnitsMonetaryValue::is_amount_Set() const{
    return m_amount_isSet;
}

bool OAIMinorUnitsMonetaryValue::is_amount_Valid() const{
    return m_amount_isValid;
}

QString OAIMinorUnitsMonetaryValue::getCurrencyCode() const {
    return m_currency_code;
}
void OAIMinorUnitsMonetaryValue::setCurrencyCode(const QString &currency_code) {
    m_currency_code = currency_code;
    m_currency_code_isSet = true;
}

bool OAIMinorUnitsMonetaryValue::is_currency_code_Set() const{
    return m_currency_code_isSet;
}

bool OAIMinorUnitsMonetaryValue::is_currency_code_Valid() const{
    return m_currency_code_isValid;
}

bool OAIMinorUnitsMonetaryValue::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_amount_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_currency_code_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIMinorUnitsMonetaryValue::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
