openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: "Manage properties in Google Analytics. Warning: Creating multiple\
    \ Customer Applications, Accounts, or Projects to simulate or act as a single\
    \ Customer Application, Account, or Project (respectively) or to circumvent Service-specific\
    \ usage limits or quotas is a direct violation of Google Cloud Platform Terms\
    \ of Service as well as Google APIs Terms of Service. These actions can result\
    \ in immediate termination of your GCP project(s) without any warning."
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Google Analytics Admin API
  version: v1alpha
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://upload.wikimedia.org/wikipedia/commons/e/e1/YouTube_play_buttom_icon_%282013-2017%29.svg
  x-origin:
  - format: google
    url: https://analyticsadmin.googleapis.com/$discovery/rest?version=v1alpha
    version: v1
  x-preferred: false
  x-providerName: googleapis.com
  x-serviceName: analyticsadmin
servers:
- url: https://analyticsadmin.googleapis.com/
tags:
- name: accounts
- name: accountSummaries
- name: properties
paths:
  /v1alpha/accountSummaries:
    get:
      description: Returns summaries of all accounts accessible by the caller.
      operationId: analyticsadmin_account_summaries_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - accountSummaries
      x-openapi-router-controller: openapi_server.controllers.account_summaries_controller
  /v1alpha/accounts:
    get:
      description: "Returns all accounts accessible by the caller. Note that these\
        \ accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\"\
        ) accounts are excluded by default. Returns an empty list if no relevant accounts\
        \ are found."
      operationId: analyticsadmin_accounts_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /v1alpha/accounts:provisionAccountTicket:
    post:
      description: Requests a ticket for creating an account.
      operationId: analyticsadmin_accounts_provision_account_ticket
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /v1alpha/properties:
    get:
      description: "Returns child Properties under the specified parent Account. Only\
        \ \"GA4\" properties will be returned. Properties will be excluded if the\
        \ caller does not have access. Soft-deleted (ie: \"trashed\") properties are\
        \ excluded by default. Returns an empty list if no relevant properties are\
        \ found."
      operationId: analyticsadmin_properties_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates an "GA4" property with the specified location and attributes.
      operationId: analyticsadmin_properties_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/properties:createConnectedSiteTag:
    post:
      description: "Creates a connected site tag for a Universal Analytics property.\
        \ You can create a maximum of 20 connected site tags per property. Note: This\
        \ API cannot be used on GA4 properties."
      operationId: analyticsadmin_properties_create_connected_site_tag
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/properties:createRollupProperty:
    post:
      description: Create a roll-up property and all roll-up property source links.
      operationId: analyticsadmin_properties_create_rollup_property
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/properties:createSubproperty:
    post:
      description: Create a subproperty and a subproperty event filter that applies
        to the created subproperty.
      operationId: analyticsadmin_properties_create_subproperty
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/properties:deleteConnectedSiteTag:
    post:
      description: "Deletes a connected site tag for a Universal Analytics property.\
        \ Note: this has no effect on GA4 properties."
      operationId: analyticsadmin_properties_delete_connected_site_tag
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/properties:fetchAutomatedGa4ConfigurationOptOut:
    post:
      description: "Fetches the opt out status for the automated GA4 setup process\
        \ for a UA property. Note: this has no effect on GA4 property."
      operationId: analyticsadmin_properties_fetch_automated_ga4_configuration_opt_out
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/properties:fetchConnectedGa4Property:
    get:
      description: "Given a specified UA property, looks up the GA4 property connected\
        \ to it. Note: this cannot be used with GA4 properties."
      operationId: analyticsadmin_properties_fetch_connected_ga4_property
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/properties:listConnectedSiteTags:
    post:
      description: "Lists the connected site tags for a Universal Analytics property.\
        \ A maximum of 20 connected site tags will be returned. Note: this has no\
        \ effect on GA4 property."
      operationId: analyticsadmin_properties_list_connected_site_tags
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/properties:setAutomatedGa4ConfigurationOptOut:
    post:
      description: "Sets the opt out status for the automated GA4 setup process for\
        \ a UA property. Note: this has no effect on GA4 property."
      operationId: analyticsadmin_properties_set_automated_ga4_configuration_opt_out
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{account}:searchChangeHistoryEvents:
    post:
      description: Searches through all changes to an account or its children given
        the specified set of filters.
      operationId: analyticsadmin_accounts_search_change_history_events
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /v1alpha/{entity}:runAccessReport:
    post:
      description: "Returns a customized report of data access records. The report\
        \ provides records of each time a user reads Google Analytics reporting data.\
        \ Access records are retained for up to 2 years. Data Access Reports can be\
        \ requested for a property. Reports may be requested for any property, but\
        \ dimensions that aren't related to quota can only be requested on Google\
        \ Analytics 360 properties. This method is only available to Administrators.\
        \ These data access records include GA4 UI Reporting, GA4 UI Explorations,\
        \ GA4 Data API, and other products like Firebase & Admob that can retrieve\
        \ data from Google Analytics through a linkage. These records don't include\
        \ property configuration changes like adding a stream or changing a property's\
        \ time zone. For configuration change history, see [searchChangeHistoryEvents](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/accounts/searchChangeHistoryEvents)."
      operationId: analyticsadmin_properties_run_access_report
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{name}:
    delete:
      description: Deletes a subproperty event filter.
      operationId: analyticsadmin_properties_subproperty_event_filters_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    get:
      description: Lookup for a single subproperty Event Filter.
      operationId: analyticsadmin_properties_subproperty_event_filters_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    patch:
      description: Updates a subproperty Event Filter.
      operationId: analyticsadmin_properties_subproperty_event_filters_patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{name}:approve:
    post:
      description: Approves a DisplayVideo360AdvertiserLinkProposal. The DisplayVideo360AdvertiserLinkProposal
        will be deleted and a new DisplayVideo360AdvertiserLink will be created.
      operationId: analyticsadmin_properties_display_video360_advertiser_link_proposals_approve
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{name}:archive:
    post:
      description: Archives a CustomMetric on a property.
      operationId: analyticsadmin_properties_custom_metrics_archive
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{name}:cancel:
    post:
      description: "Cancels a DisplayVideo360AdvertiserLinkProposal. Cancelling can\
        \ mean either: - Declining a proposal initiated from Display & Video 360 -\
        \ Withdrawing a proposal initiated from Google Analytics After being cancelled,\
        \ a proposal will eventually be deleted automatically."
      operationId: analyticsadmin_properties_display_video360_advertiser_link_proposals_cancel
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{parent}/accessBindings:
    get:
      description: Lists all access bindings on an account or property.
      operationId: analyticsadmin_properties_access_bindings_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.manage.users
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.manage.users.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates an access binding on an account or property.
      operationId: analyticsadmin_properties_access_bindings_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.manage.users
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{parent}/accessBindings:batchCreate:
    post:
      description: "Creates information about multiple access bindings to an account\
        \ or property. This method is transactional. If any AccessBinding cannot be\
        \ created, none of the AccessBindings will be created."
      operationId: analyticsadmin_properties_access_bindings_batch_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.manage.users
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{parent}/accessBindings:batchDelete:
    post:
      description: Deletes information about multiple users' links to an account or
        property.
      operationId: analyticsadmin_properties_access_bindings_batch_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.manage.users
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{parent}/accessBindings:batchGet:
    get:
      description: Gets information about multiple access bindings to an account or
        property.
      operationId: analyticsadmin_properties_access_bindings_batch_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.manage.users
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.manage.users.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{parent}/accessBindings:batchUpdate:
    post:
      description: Updates information about multiple access bindings to an account
        or property.
      operationId: analyticsadmin_properties_access_bindings_batch_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.manage.users
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{parent}/adSenseLinks:
    get:
      description: Lists AdSenseLinks on a property.
      operationId: analyticsadmin_properties_ad_sense_links_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates an AdSenseLink.
      operationId: analyticsadmin_properties_ad_sense_links_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{parent}/audiences:
    get:
      description: Lists Audiences on a property. Audiences created before 2020 may
        not be supported. Default audiences will not show filter definitions.
      operationId: analyticsadmin_properties_audiences_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates an Audience.
      operationId: analyticsadmin_properties_audiences_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{parent}/bigQueryLinks:
    get:
      description: Lists BigQuery Links on a property.
      operationId: analyticsadmin_properties_big_query_links_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{parent}/calculatedMetrics:
    get:
      description: Lists CalculatedMetrics on a property.
      operationId: analyticsadmin_properties_calculated_metrics_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates a CalculatedMetric.
      operationId: analyticsadmin_properties_calculated_metrics_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{parent}/channelGroups:
    get:
      description: Lists ChannelGroups on a property.
      operationId: analyticsadmin_properties_channel_groups_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates a ChannelGroup.
      operationId: analyticsadmin_properties_channel_groups_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{parent}/conversionEvents:
    get:
      description: Returns a list of conversion events in the specified parent property.
        Returns an empty list if no conversion events are found.
      operationId: analyticsadmin_properties_conversion_events_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates a conversion event with the specified attributes.
      operationId: analyticsadmin_properties_conversion_events_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{parent}/customDimensions:
    get:
      description: Lists CustomDimensions on a property.
      operationId: analyticsadmin_properties_custom_dimensions_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates a CustomDimension.
      operationId: analyticsadmin_properties_custom_dimensions_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{parent}/customMetrics:
    get:
      description: Lists CustomMetrics on a property.
      operationId: analyticsadmin_properties_custom_metrics_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates a CustomMetric.
      operationId: analyticsadmin_properties_custom_metrics_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{parent}/dataStreams:
    get:
      description: Lists DataStreams on a property.
      operationId: analyticsadmin_properties_data_streams_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates a DataStream.
      operationId: analyticsadmin_properties_data_streams_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{parent}/displayVideo360AdvertiserLinkProposals:
    get:
      description: Lists DisplayVideo360AdvertiserLinkProposals on a property.
      operationId: analyticsadmin_properties_display_video360_advertiser_link_proposals_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates a DisplayVideo360AdvertiserLinkProposal.
      operationId: analyticsadmin_properties_display_video360_advertiser_link_proposals_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{parent}/displayVideo360AdvertiserLinks:
    get:
      description: Lists all DisplayVideo360AdvertiserLinks on a property.
      operationId: analyticsadmin_properties_display_video360_advertiser_links_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates a DisplayVideo360AdvertiserLink. This can only be utilized
        by users who have proper authorization both on the Google Analytics property
        and on the Display & Video 360 advertiser. Users who do not have access to
        the Display & Video 360 advertiser should instead seek to create a DisplayVideo360LinkProposal.
      operationId: analyticsadmin_properties_display_video360_advertiser_links_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{parent}/eventCreateRules:
    get:
      description: Lists EventCreateRules on a web data stream.
      operationId: analyticsadmin_properties_data_streams_event_create_rules_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates an EventCreateRule.
      operationId: analyticsadmin_properties_data_streams_event_create_rules_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{parent}/expandedDataSets:
    get:
      description: Lists ExpandedDataSets on a property.
      operationId: analyticsadmin_properties_expanded_data_sets_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates a ExpandedDataSet.
      operationId: analyticsadmin_properties_expanded_data_sets_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{parent}/firebaseLinks:
    get:
      description: Lists FirebaseLinks on a property. Properties can have at most
        one FirebaseLink.
      operationId: analyticsadmin_properties_firebase_links_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates a FirebaseLink. Properties can have at most one FirebaseLink.
      operationId: analyticsadmin_properties_firebase_links_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{parent}/googleAdsLinks:
    get:
      description: Lists GoogleAdsLinks on a property.
      operationId: analyticsadmin_properties_google_ads_links_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates a GoogleAdsLink.
      operationId: analyticsadmin_properties_google_ads_links_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{parent}/measurementProtocolSecrets:
    get:
      description: Returns child MeasurementProtocolSecrets under the specified parent
        Property.
      operationId: analyticsadmin_properties_data_streams_measurement_protocol_secrets_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates a measurement protocol secret.
      operationId: analyticsadmin_properties_data_streams_measurement_protocol_secrets_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{parent}/rollupPropertySourceLinks:
    get:
      description: "Lists roll-up property source Links on a property. Only roll-up\
        \ properties can have source links, so this method will throw an error if\
        \ used on other types of properties."
      operationId: analyticsadmin_properties_rollup_property_source_links_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: "Creates a roll-up property source link. Only roll-up properties\
        \ can have source links, so this method will throw an error if used on other\
        \ types of properties."
      operationId: analyticsadmin_properties_rollup_property_source_links_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{parent}/sKAdNetworkConversionValueSchema:
    get:
      description: Lists SKAdNetworkConversionValueSchema on a stream. Properties
        can have at most one SKAdNetworkConversionValueSchema.
      operationId: analyticsadmin_properties_data_streams_s_kad_network_conversion_value_schema_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates a SKAdNetworkConversionValueSchema.
      operationId: analyticsadmin_properties_data_streams_s_kad_network_conversion_value_schema_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{parent}/searchAds360Links:
    get:
      description: Lists all SearchAds360Links on a property.
      operationId: analyticsadmin_properties_search_ads360_links_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates a SearchAds360Link.
      operationId: analyticsadmin_properties_search_ads360_links_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{parent}/subpropertyEventFilters:
    get:
      description: List all subproperty Event Filters on a property.
      operationId: analyticsadmin_properties_subproperty_event_filters_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates a subproperty Event Filter.
      operationId: analyticsadmin_properties_subproperty_event_filters_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1alpha/{property}:acknowledgeUserDataCollection:
    post:
      description: Acknowledges the terms of user data collection for the specified
        property. This acknowledgement must be completed (either in the Google Analytics
        UI or through this API) before MeasurementProtocolSecret resources may be
        created.
      operationId: analyticsadmin_properties_acknowledge_user_data_collection
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/analytics.edit: Edit Google Analytics
              management entities
            https://www.googleapis.com/auth/analytics.manage.users: Manage Google
              Analytics Account users by email address
            https://www.googleapis.com/auth/analytics.manage.users.readonly: View
              Google Analytics user permissions
            https://www.googleapis.com/auth/analytics.readonly: See and download your
              Google Analytics data
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/analytics.edit: Edit Google Analytics
              management entities
            https://www.googleapis.com/auth/analytics.manage.users: Manage Google
              Analytics Account users by email address
            https://www.googleapis.com/auth/analytics.manage.users.readonly: View
              Google Analytics user permissions
            https://www.googleapis.com/auth/analytics.readonly: See and download your
              Google Analytics data
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2c
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2c
