QT += network

HEADERS += \
# Models
    $${PWD}/OAIGooglePrivacyDlpV2Action.h \
    $${PWD}/OAIGooglePrivacyDlpV2ActionDetails.h \
    $${PWD}/OAIGooglePrivacyDlpV2AnalyzeDataSourceRiskDetails.h \
    $${PWD}/OAIGooglePrivacyDlpV2AuxiliaryTable.h \
    $${PWD}/OAIGooglePrivacyDlpV2BigQueryDiscoveryTarget.h \
    $${PWD}/OAIGooglePrivacyDlpV2BigQueryField.h \
    $${PWD}/OAIGooglePrivacyDlpV2BigQueryKey.h \
    $${PWD}/OAIGooglePrivacyDlpV2BigQueryOptions.h \
    $${PWD}/OAIGooglePrivacyDlpV2BigQueryRegex.h \
    $${PWD}/OAIGooglePrivacyDlpV2BigQueryRegexes.h \
    $${PWD}/OAIGooglePrivacyDlpV2BigQueryTable.h \
    $${PWD}/OAIGooglePrivacyDlpV2BigQueryTableCollection.h \
    $${PWD}/OAIGooglePrivacyDlpV2BigQueryTableTypes.h \
    $${PWD}/OAIGooglePrivacyDlpV2BoundingBox.h \
    $${PWD}/OAIGooglePrivacyDlpV2Bucket.h \
    $${PWD}/OAIGooglePrivacyDlpV2BucketingConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2ByteContentItem.h \
    $${PWD}/OAIGooglePrivacyDlpV2CategoricalStatsConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2CategoricalStatsHistogramBucket.h \
    $${PWD}/OAIGooglePrivacyDlpV2CategoricalStatsResult.h \
    $${PWD}/OAIGooglePrivacyDlpV2CharacterMaskConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2CharsToIgnore.h \
    $${PWD}/OAIGooglePrivacyDlpV2CloudStorageFileSet.h \
    $${PWD}/OAIGooglePrivacyDlpV2CloudStorageOptions.h \
    $${PWD}/OAIGooglePrivacyDlpV2CloudStoragePath.h \
    $${PWD}/OAIGooglePrivacyDlpV2CloudStorageRegexFileSet.h \
    $${PWD}/OAIGooglePrivacyDlpV2Color.h \
    $${PWD}/OAIGooglePrivacyDlpV2ColumnDataProfile.h \
    $${PWD}/OAIGooglePrivacyDlpV2Condition.h \
    $${PWD}/OAIGooglePrivacyDlpV2Conditions.h \
    $${PWD}/OAIGooglePrivacyDlpV2Container.h \
    $${PWD}/OAIGooglePrivacyDlpV2ContentItem.h \
    $${PWD}/OAIGooglePrivacyDlpV2ContentLocation.h \
    $${PWD}/OAIGooglePrivacyDlpV2CreateDeidentifyTemplateRequest.h \
    $${PWD}/OAIGooglePrivacyDlpV2CreateDiscoveryConfigRequest.h \
    $${PWD}/OAIGooglePrivacyDlpV2CreateDlpJobRequest.h \
    $${PWD}/OAIGooglePrivacyDlpV2CreateInspectTemplateRequest.h \
    $${PWD}/OAIGooglePrivacyDlpV2CreateJobTriggerRequest.h \
    $${PWD}/OAIGooglePrivacyDlpV2CreateStoredInfoTypeRequest.h \
    $${PWD}/OAIGooglePrivacyDlpV2CryptoDeterministicConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2CryptoHashConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2CryptoKey.h \
    $${PWD}/OAIGooglePrivacyDlpV2CryptoReplaceFfxFpeConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2CustomInfoType.h \
    $${PWD}/OAIGooglePrivacyDlpV2DataProfileAction.h \
    $${PWD}/OAIGooglePrivacyDlpV2DataProfileBigQueryRowSchema.h \
    $${PWD}/OAIGooglePrivacyDlpV2DataProfileConfigSnapshot.h \
    $${PWD}/OAIGooglePrivacyDlpV2DataProfileJobConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2DataProfileLocation.h \
    $${PWD}/OAIGooglePrivacyDlpV2DataProfilePubSubCondition.h \
    $${PWD}/OAIGooglePrivacyDlpV2DataProfilePubSubMessage.h \
    $${PWD}/OAIGooglePrivacyDlpV2DataRiskLevel.h \
    $${PWD}/OAIGooglePrivacyDlpV2DataSourceType.h \
    $${PWD}/OAIGooglePrivacyDlpV2DatastoreKey.h \
    $${PWD}/OAIGooglePrivacyDlpV2DatastoreOptions.h \
    $${PWD}/OAIGooglePrivacyDlpV2DateShiftConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2DateTime.h \
    $${PWD}/OAIGooglePrivacyDlpV2Deidentify.h \
    $${PWD}/OAIGooglePrivacyDlpV2DeidentifyConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2DeidentifyContentRequest.h \
    $${PWD}/OAIGooglePrivacyDlpV2DeidentifyContentResponse.h \
    $${PWD}/OAIGooglePrivacyDlpV2DeidentifyDataSourceDetails.h \
    $${PWD}/OAIGooglePrivacyDlpV2DeidentifyDataSourceStats.h \
    $${PWD}/OAIGooglePrivacyDlpV2DeidentifyTemplate.h \
    $${PWD}/OAIGooglePrivacyDlpV2DeltaPresenceEstimationConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2DeltaPresenceEstimationHistogramBucket.h \
    $${PWD}/OAIGooglePrivacyDlpV2DeltaPresenceEstimationQuasiIdValues.h \
    $${PWD}/OAIGooglePrivacyDlpV2DeltaPresenceEstimationResult.h \
    $${PWD}/OAIGooglePrivacyDlpV2DetectionRule.h \
    $${PWD}/OAIGooglePrivacyDlpV2Dictionary.h \
    $${PWD}/OAIGooglePrivacyDlpV2DiscoveryBigQueryConditions.h \
    $${PWD}/OAIGooglePrivacyDlpV2DiscoveryBigQueryFilter.h \
    $${PWD}/OAIGooglePrivacyDlpV2DiscoveryConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2DiscoveryGenerationCadence.h \
    $${PWD}/OAIGooglePrivacyDlpV2DiscoverySchemaModifiedCadence.h \
    $${PWD}/OAIGooglePrivacyDlpV2DiscoveryStartingLocation.h \
    $${PWD}/OAIGooglePrivacyDlpV2DiscoveryTableModifiedCadence.h \
    $${PWD}/OAIGooglePrivacyDlpV2DiscoveryTarget.h \
    $${PWD}/OAIGooglePrivacyDlpV2DlpJob.h \
    $${PWD}/OAIGooglePrivacyDlpV2DocumentLocation.h \
    $${PWD}/OAIGooglePrivacyDlpV2EntityId.h \
    $${PWD}/OAIGooglePrivacyDlpV2Error.h \
    $${PWD}/OAIGooglePrivacyDlpV2ExcludeByHotword.h \
    $${PWD}/OAIGooglePrivacyDlpV2ExcludeInfoTypes.h \
    $${PWD}/OAIGooglePrivacyDlpV2ExclusionRule.h \
    $${PWD}/OAIGooglePrivacyDlpV2Export.h \
    $${PWD}/OAIGooglePrivacyDlpV2Expressions.h \
    $${PWD}/OAIGooglePrivacyDlpV2FieldId.h \
    $${PWD}/OAIGooglePrivacyDlpV2FieldTransformation.h \
    $${PWD}/OAIGooglePrivacyDlpV2FileSet.h \
    $${PWD}/OAIGooglePrivacyDlpV2Finding.h \
    $${PWD}/OAIGooglePrivacyDlpV2FindingLimits.h \
    $${PWD}/OAIGooglePrivacyDlpV2FixedSizeBucketingConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2HotwordRule.h \
    $${PWD}/OAIGooglePrivacyDlpV2HybridContentItem.h \
    $${PWD}/OAIGooglePrivacyDlpV2HybridFindingDetails.h \
    $${PWD}/OAIGooglePrivacyDlpV2HybridInspectDlpJobRequest.h \
    $${PWD}/OAIGooglePrivacyDlpV2HybridInspectJobTriggerRequest.h \
    $${PWD}/OAIGooglePrivacyDlpV2HybridInspectStatistics.h \
    $${PWD}/OAIGooglePrivacyDlpV2HybridOptions.h \
    $${PWD}/OAIGooglePrivacyDlpV2ImageLocation.h \
    $${PWD}/OAIGooglePrivacyDlpV2ImageRedactionConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2ImageTransformation.h \
    $${PWD}/OAIGooglePrivacyDlpV2ImageTransformations.h \
    $${PWD}/OAIGooglePrivacyDlpV2InfoType.h \
    $${PWD}/OAIGooglePrivacyDlpV2InfoTypeCategory.h \
    $${PWD}/OAIGooglePrivacyDlpV2InfoTypeDescription.h \
    $${PWD}/OAIGooglePrivacyDlpV2InfoTypeLikelihood.h \
    $${PWD}/OAIGooglePrivacyDlpV2InfoTypeLimit.h \
    $${PWD}/OAIGooglePrivacyDlpV2InfoTypeStats.h \
    $${PWD}/OAIGooglePrivacyDlpV2InfoTypeSummary.h \
    $${PWD}/OAIGooglePrivacyDlpV2InfoTypeTransformation.h \
    $${PWD}/OAIGooglePrivacyDlpV2InfoTypeTransformations.h \
    $${PWD}/OAIGooglePrivacyDlpV2InspectConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2InspectContentRequest.h \
    $${PWD}/OAIGooglePrivacyDlpV2InspectContentResponse.h \
    $${PWD}/OAIGooglePrivacyDlpV2InspectDataSourceDetails.h \
    $${PWD}/OAIGooglePrivacyDlpV2InspectJobConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2InspectResult.h \
    $${PWD}/OAIGooglePrivacyDlpV2InspectTemplate.h \
    $${PWD}/OAIGooglePrivacyDlpV2InspectionRule.h \
    $${PWD}/OAIGooglePrivacyDlpV2InspectionRuleSet.h \
    $${PWD}/OAIGooglePrivacyDlpV2JobTrigger.h \
    $${PWD}/OAIGooglePrivacyDlpV2KAnonymityConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2KAnonymityEquivalenceClass.h \
    $${PWD}/OAIGooglePrivacyDlpV2KAnonymityHistogramBucket.h \
    $${PWD}/OAIGooglePrivacyDlpV2KAnonymityResult.h \
    $${PWD}/OAIGooglePrivacyDlpV2KMapEstimationConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2KMapEstimationHistogramBucket.h \
    $${PWD}/OAIGooglePrivacyDlpV2KMapEstimationQuasiIdValues.h \
    $${PWD}/OAIGooglePrivacyDlpV2KMapEstimationResult.h \
    $${PWD}/OAIGooglePrivacyDlpV2Key.h \
    $${PWD}/OAIGooglePrivacyDlpV2KindExpression.h \
    $${PWD}/OAIGooglePrivacyDlpV2KmsWrappedCryptoKey.h \
    $${PWD}/OAIGooglePrivacyDlpV2LDiversityConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2LDiversityEquivalenceClass.h \
    $${PWD}/OAIGooglePrivacyDlpV2LDiversityHistogramBucket.h \
    $${PWD}/OAIGooglePrivacyDlpV2LDiversityResult.h \
    $${PWD}/OAIGooglePrivacyDlpV2LargeCustomDictionaryConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2LargeCustomDictionaryStats.h \
    $${PWD}/OAIGooglePrivacyDlpV2LikelihoodAdjustment.h \
    $${PWD}/OAIGooglePrivacyDlpV2ListColumnDataProfilesResponse.h \
    $${PWD}/OAIGooglePrivacyDlpV2ListDeidentifyTemplatesResponse.h \
    $${PWD}/OAIGooglePrivacyDlpV2ListDiscoveryConfigsResponse.h \
    $${PWD}/OAIGooglePrivacyDlpV2ListDlpJobsResponse.h \
    $${PWD}/OAIGooglePrivacyDlpV2ListInfoTypesResponse.h \
    $${PWD}/OAIGooglePrivacyDlpV2ListInspectTemplatesResponse.h \
    $${PWD}/OAIGooglePrivacyDlpV2ListJobTriggersResponse.h \
    $${PWD}/OAIGooglePrivacyDlpV2ListProjectDataProfilesResponse.h \
    $${PWD}/OAIGooglePrivacyDlpV2ListStoredInfoTypesResponse.h \
    $${PWD}/OAIGooglePrivacyDlpV2ListTableDataProfilesResponse.h \
    $${PWD}/OAIGooglePrivacyDlpV2Location.h \
    $${PWD}/OAIGooglePrivacyDlpV2MetadataLocation.h \
    $${PWD}/OAIGooglePrivacyDlpV2NumericalStatsConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2NumericalStatsResult.h \
    $${PWD}/OAIGooglePrivacyDlpV2OrConditions.h \
    $${PWD}/OAIGooglePrivacyDlpV2OrgConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2OtherInfoTypeSummary.h \
    $${PWD}/OAIGooglePrivacyDlpV2OutputStorageConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2PartitionId.h \
    $${PWD}/OAIGooglePrivacyDlpV2PathElement.h \
    $${PWD}/OAIGooglePrivacyDlpV2PrimitiveTransformation.h \
    $${PWD}/OAIGooglePrivacyDlpV2PrivacyMetric.h \
    $${PWD}/OAIGooglePrivacyDlpV2ProfileStatus.h \
    $${PWD}/OAIGooglePrivacyDlpV2ProjectDataProfile.h \
    $${PWD}/OAIGooglePrivacyDlpV2Proximity.h \
    $${PWD}/OAIGooglePrivacyDlpV2PubSubCondition.h \
    $${PWD}/OAIGooglePrivacyDlpV2PubSubExpressions.h \
    $${PWD}/OAIGooglePrivacyDlpV2PubSubNotification.h \
    $${PWD}/OAIGooglePrivacyDlpV2PublishToPubSub.h \
    $${PWD}/OAIGooglePrivacyDlpV2QuasiId.h \
    $${PWD}/OAIGooglePrivacyDlpV2QuasiIdField.h \
    $${PWD}/OAIGooglePrivacyDlpV2QuasiIdentifierField.h \
    $${PWD}/OAIGooglePrivacyDlpV2QuoteInfo.h \
    $${PWD}/OAIGooglePrivacyDlpV2Range.h \
    $${PWD}/OAIGooglePrivacyDlpV2RecordCondition.h \
    $${PWD}/OAIGooglePrivacyDlpV2RecordKey.h \
    $${PWD}/OAIGooglePrivacyDlpV2RecordLocation.h \
    $${PWD}/OAIGooglePrivacyDlpV2RecordSuppression.h \
    $${PWD}/OAIGooglePrivacyDlpV2RecordTransformation.h \
    $${PWD}/OAIGooglePrivacyDlpV2RecordTransformations.h \
    $${PWD}/OAIGooglePrivacyDlpV2RedactImageRequest.h \
    $${PWD}/OAIGooglePrivacyDlpV2RedactImageResponse.h \
    $${PWD}/OAIGooglePrivacyDlpV2Regex.h \
    $${PWD}/OAIGooglePrivacyDlpV2ReidentifyContentRequest.h \
    $${PWD}/OAIGooglePrivacyDlpV2ReidentifyContentResponse.h \
    $${PWD}/OAIGooglePrivacyDlpV2ReplaceDictionaryConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2ReplaceValueConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2RequestedDeidentifyOptions.h \
    $${PWD}/OAIGooglePrivacyDlpV2RequestedOptions.h \
    $${PWD}/OAIGooglePrivacyDlpV2RequestedRiskAnalysisOptions.h \
    $${PWD}/OAIGooglePrivacyDlpV2Result.h \
    $${PWD}/OAIGooglePrivacyDlpV2RiskAnalysisJobConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2Row.h \
    $${PWD}/OAIGooglePrivacyDlpV2SaveFindings.h \
    $${PWD}/OAIGooglePrivacyDlpV2Schedule.h \
    $${PWD}/OAIGooglePrivacyDlpV2SelectedInfoTypes.h \
    $${PWD}/OAIGooglePrivacyDlpV2SensitivityScore.h \
    $${PWD}/OAIGooglePrivacyDlpV2StatisticalTable.h \
    $${PWD}/OAIGooglePrivacyDlpV2StorageConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2StorageMetadataLabel.h \
    $${PWD}/OAIGooglePrivacyDlpV2StoredInfoType.h \
    $${PWD}/OAIGooglePrivacyDlpV2StoredInfoTypeConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2StoredInfoTypeStats.h \
    $${PWD}/OAIGooglePrivacyDlpV2StoredInfoTypeVersion.h \
    $${PWD}/OAIGooglePrivacyDlpV2StoredType.h \
    $${PWD}/OAIGooglePrivacyDlpV2SummaryResult.h \
    $${PWD}/OAIGooglePrivacyDlpV2Table.h \
    $${PWD}/OAIGooglePrivacyDlpV2TableDataProfile.h \
    $${PWD}/OAIGooglePrivacyDlpV2TableLocation.h \
    $${PWD}/OAIGooglePrivacyDlpV2TableOptions.h \
    $${PWD}/OAIGooglePrivacyDlpV2TaggedField.h \
    $${PWD}/OAIGooglePrivacyDlpV2TimePartConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2TimeZone.h \
    $${PWD}/OAIGooglePrivacyDlpV2TimespanConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2TransformationConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2TransformationDescription.h \
    $${PWD}/OAIGooglePrivacyDlpV2TransformationDetails.h \
    $${PWD}/OAIGooglePrivacyDlpV2TransformationDetailsStorageConfig.h \
    $${PWD}/OAIGooglePrivacyDlpV2TransformationErrorHandling.h \
    $${PWD}/OAIGooglePrivacyDlpV2TransformationLocation.h \
    $${PWD}/OAIGooglePrivacyDlpV2TransformationOverview.h \
    $${PWD}/OAIGooglePrivacyDlpV2TransformationResultStatus.h \
    $${PWD}/OAIGooglePrivacyDlpV2TransformationSummary.h \
    $${PWD}/OAIGooglePrivacyDlpV2TransientCryptoKey.h \
    $${PWD}/OAIGooglePrivacyDlpV2Trigger.h \
    $${PWD}/OAIGooglePrivacyDlpV2UnwrappedCryptoKey.h \
    $${PWD}/OAIGooglePrivacyDlpV2UpdateDeidentifyTemplateRequest.h \
    $${PWD}/OAIGooglePrivacyDlpV2UpdateDiscoveryConfigRequest.h \
    $${PWD}/OAIGooglePrivacyDlpV2UpdateInspectTemplateRequest.h \
    $${PWD}/OAIGooglePrivacyDlpV2UpdateJobTriggerRequest.h \
    $${PWD}/OAIGooglePrivacyDlpV2UpdateStoredInfoTypeRequest.h \
    $${PWD}/OAIGooglePrivacyDlpV2Value.h \
    $${PWD}/OAIGooglePrivacyDlpV2ValueFrequency.h \
    $${PWD}/OAIGooglePrivacyDlpV2VersionDescription.h \
    $${PWD}/OAIGooglePrivacyDlpV2WordList.h \
    $${PWD}/OAIGoogleRpcStatus.h \
    $${PWD}/OAIGoogleTypeDate.h \
    $${PWD}/OAIGoogleTypeTimeOfDay.h \
# APIs
    $${PWD}/OAIInfoTypesApi.h \
    $${PWD}/OAILocationsApi.h \
    $${PWD}/OAIProjectsApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIGooglePrivacyDlpV2Action.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ActionDetails.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2AnalyzeDataSourceRiskDetails.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2AuxiliaryTable.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2BigQueryDiscoveryTarget.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2BigQueryField.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2BigQueryKey.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2BigQueryOptions.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2BigQueryRegex.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2BigQueryRegexes.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2BigQueryTable.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2BigQueryTableCollection.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2BigQueryTableTypes.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2BoundingBox.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2Bucket.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2BucketingConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ByteContentItem.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2CategoricalStatsConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2CategoricalStatsHistogramBucket.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2CategoricalStatsResult.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2CharacterMaskConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2CharsToIgnore.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2CloudStorageFileSet.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2CloudStorageOptions.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2CloudStoragePath.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2CloudStorageRegexFileSet.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2Color.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ColumnDataProfile.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2Condition.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2Conditions.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2Container.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ContentItem.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ContentLocation.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2CreateDeidentifyTemplateRequest.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2CreateDiscoveryConfigRequest.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2CreateDlpJobRequest.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2CreateInspectTemplateRequest.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2CreateJobTriggerRequest.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2CreateStoredInfoTypeRequest.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2CryptoDeterministicConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2CryptoHashConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2CryptoKey.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2CryptoReplaceFfxFpeConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2CustomInfoType.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DataProfileAction.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DataProfileBigQueryRowSchema.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DataProfileConfigSnapshot.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DataProfileJobConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DataProfileLocation.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DataProfilePubSubCondition.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DataProfilePubSubMessage.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DataRiskLevel.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DataSourceType.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DatastoreKey.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DatastoreOptions.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DateShiftConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DateTime.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2Deidentify.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DeidentifyConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DeidentifyContentRequest.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DeidentifyContentResponse.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DeidentifyDataSourceDetails.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DeidentifyDataSourceStats.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DeidentifyTemplate.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DeltaPresenceEstimationConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DeltaPresenceEstimationHistogramBucket.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DeltaPresenceEstimationQuasiIdValues.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DeltaPresenceEstimationResult.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DetectionRule.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2Dictionary.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DiscoveryBigQueryConditions.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DiscoveryBigQueryFilter.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DiscoveryConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DiscoveryGenerationCadence.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DiscoverySchemaModifiedCadence.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DiscoveryStartingLocation.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DiscoveryTableModifiedCadence.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DiscoveryTarget.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DlpJob.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2DocumentLocation.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2EntityId.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2Error.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ExcludeByHotword.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ExcludeInfoTypes.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ExclusionRule.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2Export.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2Expressions.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2FieldId.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2FieldTransformation.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2FileSet.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2Finding.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2FindingLimits.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2FixedSizeBucketingConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2HotwordRule.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2HybridContentItem.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2HybridFindingDetails.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2HybridInspectDlpJobRequest.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2HybridInspectJobTriggerRequest.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2HybridInspectStatistics.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2HybridOptions.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ImageLocation.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ImageRedactionConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ImageTransformation.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ImageTransformations.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2InfoType.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2InfoTypeCategory.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2InfoTypeDescription.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2InfoTypeLikelihood.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2InfoTypeLimit.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2InfoTypeStats.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2InfoTypeSummary.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2InfoTypeTransformation.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2InfoTypeTransformations.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2InspectConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2InspectContentRequest.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2InspectContentResponse.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2InspectDataSourceDetails.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2InspectJobConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2InspectResult.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2InspectTemplate.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2InspectionRule.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2InspectionRuleSet.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2JobTrigger.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2KAnonymityConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2KAnonymityEquivalenceClass.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2KAnonymityHistogramBucket.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2KAnonymityResult.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2KMapEstimationConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2KMapEstimationHistogramBucket.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2KMapEstimationQuasiIdValues.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2KMapEstimationResult.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2Key.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2KindExpression.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2KmsWrappedCryptoKey.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2LDiversityConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2LDiversityEquivalenceClass.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2LDiversityHistogramBucket.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2LDiversityResult.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2LargeCustomDictionaryConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2LargeCustomDictionaryStats.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2LikelihoodAdjustment.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ListColumnDataProfilesResponse.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ListDeidentifyTemplatesResponse.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ListDiscoveryConfigsResponse.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ListDlpJobsResponse.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ListInfoTypesResponse.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ListInspectTemplatesResponse.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ListJobTriggersResponse.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ListProjectDataProfilesResponse.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ListStoredInfoTypesResponse.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ListTableDataProfilesResponse.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2Location.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2MetadataLocation.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2NumericalStatsConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2NumericalStatsResult.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2OrConditions.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2OrgConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2OtherInfoTypeSummary.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2OutputStorageConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2PartitionId.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2PathElement.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2PrimitiveTransformation.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2PrivacyMetric.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ProfileStatus.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ProjectDataProfile.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2Proximity.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2PubSubCondition.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2PubSubExpressions.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2PubSubNotification.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2PublishToPubSub.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2QuasiId.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2QuasiIdField.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2QuasiIdentifierField.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2QuoteInfo.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2Range.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2RecordCondition.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2RecordKey.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2RecordLocation.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2RecordSuppression.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2RecordTransformation.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2RecordTransformations.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2RedactImageRequest.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2RedactImageResponse.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2Regex.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ReidentifyContentRequest.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ReidentifyContentResponse.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ReplaceDictionaryConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ReplaceValueConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2RequestedDeidentifyOptions.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2RequestedOptions.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2RequestedRiskAnalysisOptions.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2Result.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2RiskAnalysisJobConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2Row.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2SaveFindings.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2Schedule.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2SelectedInfoTypes.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2SensitivityScore.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2StatisticalTable.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2StorageConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2StorageMetadataLabel.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2StoredInfoType.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2StoredInfoTypeConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2StoredInfoTypeStats.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2StoredInfoTypeVersion.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2StoredType.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2SummaryResult.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2Table.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2TableDataProfile.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2TableLocation.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2TableOptions.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2TaggedField.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2TimePartConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2TimeZone.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2TimespanConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2TransformationConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2TransformationDescription.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2TransformationDetails.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2TransformationDetailsStorageConfig.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2TransformationErrorHandling.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2TransformationLocation.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2TransformationOverview.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2TransformationResultStatus.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2TransformationSummary.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2TransientCryptoKey.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2Trigger.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2UnwrappedCryptoKey.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2UpdateDeidentifyTemplateRequest.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2UpdateDiscoveryConfigRequest.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2UpdateInspectTemplateRequest.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2UpdateJobTriggerRequest.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2UpdateStoredInfoTypeRequest.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2Value.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2ValueFrequency.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2VersionDescription.cpp \
    $${PWD}/OAIGooglePrivacyDlpV2WordList.cpp \
    $${PWD}/OAIGoogleRpcStatus.cpp \
    $${PWD}/OAIGoogleTypeDate.cpp \
    $${PWD}/OAIGoogleTypeTimeOfDay.cpp \
# APIs
    $${PWD}/OAIInfoTypesApi.cpp \
    $${PWD}/OAILocationsApi.cpp \
    $${PWD}/OAIProjectsApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
