openapi: 3.0.1
info:
  title: Lucidtech API
  version: 2023-03-23T15:40:40Z
  x-logo:
    url: https://assets-global.website-files.com/5d3e265ac89f6a3e64292efc/5d5595354de4fbdd8c554dba_default_webclip.png
  x-origin:
  - format: openapi
    url: https://raw.githubusercontent.com/LucidtechAI/cradl-docs/master/static/oas.yaml
    version: "3.0"
  x-providerName: webflow.com
servers:
- url: "https://api.lucidtech.ai/{basePath}"
  variables:
    basePath:
      default: v1
paths:
  /appClients:
    get:
      operationId: app_clients_get
      security:
      - OAuth2:
        - api.lucidtech.ai/appclients:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: app_clients_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      operationId: app_clients_post
      security:
      - OAuth2:
        - api.lucidtech.ai/appclients:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /appClients/{appClientId}:
    delete:
      operationId: app_clients_app_client_id_delete
      security: []
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: app_clients_app_client_id_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    patch:
      operationId: app_clients_app_client_id_patch
      security:
      - OAuth2:
        - api.lucidtech.ai/appclients:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /assets:
    get:
      operationId: assets_get
      security:
      - OAuth2:
        - api.lucidtech.ai/assets:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: assets_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      operationId: assets_post
      security:
      - OAuth2:
        - api.lucidtech.ai/assets:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /assets/{assetId}:
    delete:
      operationId: assets_asset_id_delete
      security:
      - OAuth2:
        - api.lucidtech.ai/assets:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    get:
      operationId: assets_asset_id_get
      security:
      - OAuth2:
        - api.lucidtech.ai/assets:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: assets_asset_id_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    patch:
      operationId: assets_asset_id_patch
      security:
      - OAuth2:
        - api.lucidtech.ai/assets:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /datasets:
    get:
      operationId: datasets_get
      security:
      - OAuth2:
        - api.lucidtech.ai/datasets:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: datasets_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      operationId: datasets_post
      security:
      - OAuth2:
        - api.lucidtech.ai/datasets:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /datasets/{datasetId}:
    delete:
      operationId: datasets_dataset_id_delete
      security:
      - OAuth2:
        - api.lucidtech.ai/datasets:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    get:
      operationId: datasets_dataset_id_get
      security:
      - OAuth2:
        - api.lucidtech.ai/datasets:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: datasets_dataset_id_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    patch:
      operationId: datasets_dataset_id_patch
      security:
      - OAuth2:
        - api.lucidtech.ai/datasets:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /deploymentEnvironments:
    get:
      operationId: deployment_environments_get
      security:
      - OAuth2:
        - api.lucidtech.ai/secrets:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: deployment_environments_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /deploymentEnvironments/{deploymentEnvironmentId}:
    get:
      operationId: deployment_environments_deployment_environment_id_get
      security:
      - OAuth2:
        - api.lucidtech.ai/organizations:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: deployment_environments_deployment_environment_id_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /documents:
    delete:
      operationId: documents_delete
      security:
      - OAuth2:
        - api.lucidtech.ai/documents:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
    get:
      operationId: documents_get
      security:
      - OAuth2:
        - api.lucidtech.ai/documents:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: documents_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      operationId: documents_post
      security:
      - OAuth2:
        - api.lucidtech.ai/documents:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /documents/{documentId}:
    delete:
      operationId: documents_document_id_delete
      security:
      - OAuth2:
        - api.lucidtech.ai/documents:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    get:
      operationId: documents_document_id_get
      security:
      - OAuth2:
        - api.lucidtech.ai/documents:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: documents_document_id_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    patch:
      operationId: documents_document_id_patch
      security:
      - OAuth2:
        - api.lucidtech.ai/documents:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /logs:
    get:
      operationId: logs_get
      security:
      - OAuth2:
        - api.lucidtech.ai/logs:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: logs_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /logs/{logId}:
    get:
      operationId: logs_log_id_get
      security:
      - OAuth2:
        - api.lucidtech.ai/logs:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: logs_log_id_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /models:
    get:
      operationId: models_get
      security:
      - OAuth2:
        - api.lucidtech.ai/models:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: models_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      operationId: models_post
      security:
      - OAuth2:
        - api.lucidtech.ai/models:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /models/{modelId}:
    delete:
      operationId: models_model_id_delete
      security:
      - OAuth2:
        - api.lucidtech.ai/models:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    get:
      operationId: models_model_id_get
      security:
      - OAuth2:
        - api.lucidtech.ai/models:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: models_model_id_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    patch:
      operationId: models_model_id_patch
      security:
      - OAuth2:
        - api.lucidtech.ai/models:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /models/{modelId}/dataBundles:
    get:
      operationId: models_model_id_data_bundles_get
      security:
      - OAuth2:
        - api.lucidtech.ai/databundles:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: models_model_id_data_bundles_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      operationId: models_model_id_data_bundles_post
      security:
      - OAuth2:
        - api.lucidtech.ai/databundles:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /models/{modelId}/dataBundles/{dataBundleId}:
    delete:
      operationId: models_model_id_data_bundles_data_bundle_id_delete
      security: []
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: models_model_id_data_bundles_data_bundle_id_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    patch:
      operationId: models_model_id_data_bundles_data_bundle_id_patch
      security:
      - OAuth2:
        - api.lucidtech.ai/databundles:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /models/{modelId}/trainings:
    get:
      operationId: models_model_id_trainings_get
      security:
      - OAuth2:
        - api.lucidtech.ai/workflows.executions:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: models_model_id_trainings_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      operationId: models_model_id_trainings_post
      security:
      - OAuth2:
        - api.lucidtech.ai/workflows.executions:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /models/{modelId}/trainings/{trainingId}:
    options:
      operationId: models_model_id_trainings_training_id_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    patch:
      operationId: models_model_id_trainings_training_id_patch
      security:
      - OAuth2:
        - api.lucidtech.ai/predictions:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /organizations:
    get:
      operationId: organizations_get
      security:
      - OAuth2:
        - api.lucidtech.ai/organizations:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: organizations_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      operationId: organizations_post
      security:
      - OAuth2:
        - api.lucidtech.ai/organizations:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /organizations/{organizationId}:
    get:
      operationId: organizations_organization_id_get
      security:
      - OAuth2:
        - api.lucidtech.ai/organizations:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: organizations_organization_id_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    patch:
      operationId: organizations_organization_id_patch
      security:
      - OAuth2:
        - api.lucidtech.ai/organizations:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /paymentMethods:
    get:
      operationId: payment_methods_get
      security:
      - OAuth2:
        - api.lucidtech.ai/paymentmethods:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: payment_methods_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      operationId: payment_methods_post
      security:
      - OAuth2:
        - api.lucidtech.ai/paymentmethods:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /paymentMethods/{paymentMethodId}:
    delete:
      operationId: payment_methods_payment_method_id_delete
      security:
      - OAuth2:
        - api.lucidtech.ai/paymentmethods:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    get:
      operationId: payment_methods_payment_method_id_get
      security:
      - OAuth2:
        - api.lucidtech.ai/paymentmethods:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: payment_methods_payment_method_id_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    patch:
      operationId: payment_methods_payment_method_id_patch
      security:
      - OAuth2:
        - api.lucidtech.ai/paymentmethods:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /plans:
    get:
      operationId: plans_get
      security:
      - OAuth2:
        - api.lucidtech.ai/plans:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: plans_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /plans/{planId}:
    get:
      operationId: plans_plan_id_get
      security:
      - OAuth2:
        - api.lucidtech.ai/plans:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: plans_plan_id_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /predictions:
    get:
      operationId: predictions_get
      security:
      - OAuth2:
        - api.lucidtech.ai/predictions:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: predictions_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      operationId: predictions_post
      security:
      - OAuth2:
        - api.lucidtech.ai/predictions:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /profiles/{profileId}:
    get:
      operationId: profiles_profile_id_get
      security:
      - OAuth2:
        - api.lucidtech.ai/assets:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: profiles_profile_id_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    patch:
      operationId: profiles_profile_id_patch
      security:
      - OAuth2:
        - api.lucidtech.ai/assets:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /secrets:
    get:
      operationId: secrets_get
      security:
      - OAuth2:
        - api.lucidtech.ai/secrets:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: secrets_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      operationId: secrets_post
      security:
      - OAuth2:
        - api.lucidtech.ai/secrets:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /secrets/{secretId}:
    delete:
      operationId: secrets_secret_id_delete
      security: []
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: secrets_secret_id_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    patch:
      operationId: secrets_secret_id_patch
      security:
      - OAuth2:
        - api.lucidtech.ai/secrets:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /transitions:
    get:
      operationId: transitions_get
      security:
      - OAuth2:
        - api.lucidtech.ai/transitions:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: transitions_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      operationId: transitions_post
      security:
      - OAuth2:
        - api.lucidtech.ai/transitions:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /transitions/{transitionId}:
    delete:
      operationId: transitions_transition_id_delete
      security:
      - OAuth2:
        - api.lucidtech.ai/transitions:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    get:
      operationId: transitions_transition_id_get
      security:
      - OAuth2:
        - api.lucidtech.ai/transitions:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: transitions_transition_id_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    patch:
      operationId: transitions_transition_id_patch
      security:
      - OAuth2:
        - api.lucidtech.ai/transitions:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /transitions/{transitionId}/executions:
    get:
      operationId: transitions_transition_id_executions_get
      security:
      - OAuth2:
        - api.lucidtech.ai/transitions.executions:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: transitions_transition_id_executions_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      operationId: transitions_transition_id_executions_post
      security:
      - OAuth2:
        - api.lucidtech.ai/transitions.executions:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /transitions/{transitionId}/executions/{executionId}:
    get:
      operationId: transitions_transition_id_executions_execution_id_get
      security:
      - OAuth2:
        - api.lucidtech.ai/transitions.executions:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: transitions_transition_id_executions_execution_id_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    patch:
      operationId: transitions_transition_id_executions_execution_id_patch
      security:
      - OAuth2:
        - api.lucidtech.ai/transitions.executions:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /transitions/{transitionId}/executions/{executionId}/heartbeats:
    options:
      operationId: transitions_transition_id_executions_execution_id_heartbeats_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      operationId: transitions_transition_id_executions_execution_id_heartbeats_post
      security:
      - OAuth2:
        - api.lucidtech.ai/transitions.executions.heartbeats:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /users:
    get:
      operationId: users_get
      security:
      - OAuth2:
        - api.lucidtech.ai/users:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: users_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      operationId: users_post
      security:
      - OAuth2:
        - api.lucidtech.ai/users:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /users/{userId}:
    delete:
      operationId: users_user_id_delete
      security:
      - OAuth2:
        - api.lucidtech.ai/users:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    get:
      operationId: users_user_id_get
      security:
      - OAuth2:
        - api.lucidtech.ai/users:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: users_user_id_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    patch:
      operationId: users_user_id_patch
      security:
      - OAuth2:
        - api.lucidtech.ai/users:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /workflows:
    get:
      operationId: workflows_get
      security:
      - OAuth2:
        - api.lucidtech.ai/workflows:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: workflows_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      operationId: workflows_post
      security:
      - OAuth2:
        - api.lucidtech.ai/workflows:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /workflows/{workflowId}:
    delete:
      operationId: workflows_workflow_id_delete
      security:
      - OAuth2:
        - api.lucidtech.ai/workflows:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    get:
      operationId: workflows_workflow_id_get
      security:
      - OAuth2:
        - api.lucidtech.ai/workflows:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: workflows_workflow_id_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    patch:
      operationId: workflows_workflow_id_patch
      security:
      - OAuth2:
        - api.lucidtech.ai/workflows:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /workflows/{workflowId}/executions:
    get:
      operationId: workflows_workflow_id_executions_get
      security:
      - OAuth2:
        - api.lucidtech.ai/workflows.executions:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: workflows_workflow_id_executions_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      operationId: workflows_workflow_id_executions_post
      security:
      - OAuth2:
        - api.lucidtech.ai/workflows.executions:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /workflows/{workflowId}/executions/{executionId}:
    delete:
      operationId: workflows_workflow_id_executions_execution_id_delete
      security:
      - OAuth2:
        - api.lucidtech.ai/workflows.executions:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    get:
      operationId: workflows_workflow_id_executions_execution_id_get
      security:
      - OAuth2:
        - api.lucidtech.ai/workflows.executions:read
      x-openapi-router-controller: openapi_server.controllers.default_controller
    options:
      operationId: workflows_workflow_id_executions_execution_id_options
      x-openapi-router-controller: openapi_server.controllers.default_controller
    patch:
      operationId: workflows_workflow_id_executions_execution_id_patch
      security:
      - OAuth2:
        - api.lucidtech.ai/workflows.executions:write
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  securitySchemes:
    OAuth2:
      flows:
        clientCredentials:
          scopes:
            api.lucidtech.ai/appclients:read: Read permissions
            api.lucidtech.ai/appclients:write: Write permissions
            api.lucidtech.ai/assets:read: Read permissions
            api.lucidtech.ai/assets:write: Write permissions
            api.lucidtech.ai/databundles:read: Read permissions
            api.lucidtech.ai/databundles:write: Write permissions
            api.lucidtech.ai/datasets:read: Read permissions
            api.lucidtech.ai/datasets:write: Write permissions
            api.lucidtech.ai/deploymentenvironments:read: Read permissions
            api.lucidtech.ai/documents:read: Read permissions
            api.lucidtech.ai/documents:write: Write permissions
            api.lucidtech.ai/logs:read: Read permissions
            api.lucidtech.ai/models:read: Read permissions
            api.lucidtech.ai/models:write: Write permissions
            api.lucidtech.ai/organizations:read: Read permissions
            api.lucidtech.ai/organizations:write: Write permissions
            api.lucidtech.ai/paymentmethods:read: Read permissions
            api.lucidtech.ai/paymentmethods:write: Write permissions
            api.lucidtech.ai/plans:read: Read permissions
            api.lucidtech.ai/predictions:read: Read permissions
            api.lucidtech.ai/predictions:write: Write permissions
            api.lucidtech.ai/profiles:read: Read permissions
            api.lucidtech.ai/profiles:write: Write permissions
            api.lucidtech.ai/secrets:read: Read permissions
            api.lucidtech.ai/secrets:write: Write permissions
            api.lucidtech.ai/trainings:read: Read permissions
            api.lucidtech.ai/trainings:write: Write permissions
            api.lucidtech.ai/transitions.executions.heartbeats:write: Write permissions
            api.lucidtech.ai/transitions.executions:read: Read permissions
            api.lucidtech.ai/transitions.executions:write: Write permissions
            api.lucidtech.ai/transitions:read: Read permissions
            api.lucidtech.ai/transitions:write: Write permissions
            api.lucidtech.ai/users:read: Read permissions
            api.lucidtech.ai/users:write: Write permissions
            api.lucidtech.ai/workflows.executions:read: Read permissions
            api.lucidtech.ai/workflows.executions:write: Write permissions
            api.lucidtech.ai/workflows:read: Read permissions
            api.lucidtech.ai/workflows:write: Write permissions
          tokenUrl: https://auth.lucidtech.ai/oauth2/token
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_OAuth2
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_OAuth2
