openapi: 3.0.0
info:
  contact:
    name: Slack developer relations
    url: https://api.slack.com/support
  description: "One way to interact with the Slack platform is its HTTP RPC-based\
    \ Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace\
    \ tokens blessed with related OAuth scopes."
  title: Slack Web API
  version: 1.7.0
  x-apisguru-categories:
  - collaboration
  - messaging
  x-logo:
    url: http://static.tumblr.com/wvuzcz9/LlKncfhmp/slack_logo_240.png
  x-origin:
  - format: openapi
    url: https://raw.githubusercontent.com/slackapi/slack-api-specs/master/web-api/slack_web_openapi_v2.json
    version: "3.0"
  x-providerName: slack.com
servers:
- url: https://slack.com/api
paths:
  /admin.apps.approve:
    post:
      description: Approve an app for installation on a workspace.
      operationId: admin_apps_approve
      security:
      - slackAuth:
        - admin.apps:write
      tags:
      - admin.apps
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.apps.approved.list:
    get:
      description: List approved apps for an org or workspace.
      operationId: admin_apps_approved_list
      security:
      - slackAuth:
        - admin.apps:read
      tags:
      - admin.apps.approved
      - admin
      x-accepts:
      - application/json
  /admin.apps.requests.list:
    get:
      description: List app requests for a team/workspace.
      operationId: admin_apps_requests_list
      security:
      - slackAuth:
        - admin.apps:read
      tags:
      - admin.apps.requests
      - admin
      x-accepts:
      - application/json
  /admin.apps.restrict:
    post:
      description: Restrict an app for installation on a workspace.
      operationId: admin_apps_restrict
      security:
      - slackAuth:
        - admin.apps:write
      tags:
      - admin.apps
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.apps.restricted.list:
    get:
      description: List restricted apps for an org or workspace.
      operationId: admin_apps_restricted_list
      security:
      - slackAuth:
        - admin.apps:read
      tags:
      - admin.apps.restricted
      - admin
      x-accepts:
      - application/json
  /admin.conversations.archive:
    post:
      description: Archive a public or private channel.
      operationId: admin_conversations_archive
      security:
      - slackAuth:
        - admin.conversations:write
      tags:
      - admin.conversations
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.conversations.convertToPrivate:
    post:
      description: Convert a public channel to a private channel.
      operationId: admin_conversations_convertToPrivate
      security:
      - slackAuth:
        - admin.conversations:write
      tags:
      - admin.conversations
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.conversations.create:
    post:
      description: Create a public or private channel-based conversation.
      operationId: admin_conversations_create
      security:
      - slackAuth:
        - admin.conversations:write
      tags:
      - admin.conversations
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.conversations.delete:
    post:
      description: Delete a public or private channel.
      operationId: admin_conversations_delete
      security:
      - slackAuth:
        - admin.conversations:write
      tags:
      - admin.conversations
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.conversations.disconnectShared:
    post:
      description: Disconnect a connected channel from one or more workspaces.
      operationId: admin_conversations_disconnectShared
      security:
      - slackAuth:
        - admin.conversations:write
      tags:
      - admin.conversations
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.conversations.ekm.listOriginalConnectedChannelInfo:
    get:
      description: "List all disconnected channels—i.e., channels that were once connected\
        \ to other workspaces and then disconnected—and the corresponding original\
        \ channel IDs for key revocation with EKM."
      operationId: admin_conversations_ekm_listOriginalConnectedChannelInfo
      security:
      - slackAuth:
        - admin.conversations:read
      tags:
      - admin.conversations.ekm
      - admin
      x-accepts:
      - application/json
  /admin.conversations.getConversationPrefs:
    get:
      description: Get conversation preferences for a public or private channel.
      operationId: admin_conversations_getConversationPrefs
      security:
      - slackAuth:
        - admin.conversations:read
      tags:
      - admin.conversations
      - admin
      x-accepts:
      - application/json
  /admin.conversations.getTeams:
    get:
      description: Get all the workspaces a given public or private channel is connected
        to within this Enterprise org.
      operationId: admin_conversations_getTeams
      security:
      - slackAuth:
        - admin.conversations:read
      tags:
      - admin.conversations
      - admin
      x-accepts:
      - application/json
  /admin.conversations.invite:
    post:
      description: Invite a user to a public or private channel.
      operationId: admin_conversations_invite
      security:
      - slackAuth:
        - admin.conversations:write
      tags:
      - admin.conversations
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.conversations.rename:
    post:
      description: Rename a public or private channel.
      operationId: admin_conversations_rename
      security:
      - slackAuth:
        - admin.conversations:write
      tags:
      - admin.conversations
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.conversations.restrictAccess.addGroup:
    post:
      description: Add an allowlist of IDP groups for accessing a channel
      operationId: admin_conversations_restrictAccess_addGroup
      security:
      - slackAuth:
        - admin.conversations:write
      tags:
      - admin.conversations.restrictAccess
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.conversations.restrictAccess.listGroups:
    get:
      description: List all IDP Groups linked to a channel
      operationId: admin_conversations_restrictAccess_listGroups
      security:
      - slackAuth:
        - admin.conversations:read
      tags:
      - admin.conversations.restrictAccess
      - admin
      x-accepts:
      - application/json
  /admin.conversations.restrictAccess.removeGroup:
    post:
      description: Remove a linked IDP group linked from a private channel
      operationId: admin_conversations_restrictAccess_removeGroup
      security:
      - slackAuth:
        - admin.conversations:write
      tags:
      - admin.conversations.restrictAccess
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.conversations.search:
    get:
      description: Search for public or private channels in an Enterprise organization.
      operationId: admin_conversations_search
      security:
      - slackAuth:
        - admin.conversations:read
      tags:
      - admin.conversations
      - admin
      x-accepts:
      - application/json
  /admin.conversations.setConversationPrefs:
    post:
      description: Set the posting permissions for a public or private channel.
      operationId: admin_conversations_setConversationPrefs
      security:
      - slackAuth:
        - admin.conversations:write
      tags:
      - admin.conversations
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.conversations.setTeams:
    post:
      description: Set the workspaces in an Enterprise grid org that connect to a
        public or private channel.
      operationId: admin_conversations_setTeams
      security:
      - slackAuth:
        - admin.conversations:write
      tags:
      - admin.conversations
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.conversations.unarchive:
    post:
      description: Unarchive a public or private channel.
      operationId: admin_conversations_unarchive
      security:
      - slackAuth:
        - admin.conversations:write
      tags:
      - admin.conversations
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.emoji.add:
    post:
      description: Add an emoji.
      operationId: admin_emoji_add
      security:
      - slackAuth:
        - admin.teams:write
      tags:
      - admin.emoji
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.emoji.addAlias:
    post:
      description: Add an emoji alias.
      operationId: admin_emoji_addAlias
      security:
      - slackAuth:
        - admin.teams:write
      tags:
      - admin.emoji
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.emoji.list:
    get:
      description: List emoji for an Enterprise Grid organization.
      operationId: admin_emoji_list
      security:
      - slackAuth:
        - admin.teams:read
      tags:
      - admin.emoji
      - admin
      x-accepts:
      - application/json
  /admin.emoji.remove:
    post:
      description: Remove an emoji across an Enterprise Grid organization
      operationId: admin_emoji_remove
      security:
      - slackAuth:
        - admin.teams:write
      tags:
      - admin.emoji
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.emoji.rename:
    post:
      description: Rename an emoji.
      operationId: admin_emoji_rename
      security:
      - slackAuth:
        - admin.teams:write
      tags:
      - admin.emoji
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.inviteRequests.approve:
    post:
      description: Approve a workspace invite request.
      operationId: admin_inviteRequests_approve
      security:
      - slackAuth:
        - admin.invites:write
      tags:
      - admin.inviteRequests
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.inviteRequests.approved.list:
    get:
      description: List all approved workspace invite requests.
      operationId: admin_inviteRequests_approved_list
      security:
      - slackAuth:
        - admin.invites:read
      tags:
      - admin.inviteRequests.approved
      - admin
      x-accepts:
      - application/json
  /admin.inviteRequests.denied.list:
    get:
      description: List all denied workspace invite requests.
      operationId: admin_inviteRequests_denied_list
      security:
      - slackAuth:
        - admin.invites:read
      tags:
      - admin.inviteRequests.denied
      - admin
      x-accepts:
      - application/json
  /admin.inviteRequests.deny:
    post:
      description: Deny a workspace invite request.
      operationId: admin_inviteRequests_deny
      security:
      - slackAuth:
        - admin.invites:write
      tags:
      - admin.inviteRequests
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.inviteRequests.list:
    get:
      description: List all pending workspace invite requests.
      operationId: admin_inviteRequests_list
      security:
      - slackAuth:
        - admin.invites:read
      tags:
      - admin.inviteRequests
      - admin
      x-accepts:
      - application/json
  /admin.teams.admins.list:
    get:
      description: List all of the admins on a given workspace.
      operationId: admin_teams_admins_list
      security:
      - slackAuth:
        - admin.teams:read
      tags:
      - admin.teams.admins
      - admin
      x-accepts:
      - application/json
  /admin.teams.create:
    post:
      description: Create an Enterprise team.
      operationId: admin_teams_create
      security:
      - slackAuth:
        - admin.teams:write
      tags:
      - admin.teams
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.teams.list:
    get:
      description: List all teams on an Enterprise organization
      operationId: admin_teams_list
      security:
      - slackAuth:
        - admin.teams:read
      tags:
      - admin.teams
      - admin
      x-accepts:
      - application/json
  /admin.teams.owners.list:
    get:
      description: List all of the owners on a given workspace.
      operationId: admin_teams_owners_list
      security:
      - slackAuth:
        - admin.teams:read
      tags:
      - admin.teams.owners
      - admin
      x-accepts:
      - application/json
  /admin.teams.settings.info:
    get:
      description: Fetch information about settings in a workspace
      operationId: admin_teams_settings_info
      security:
      - slackAuth:
        - admin.teams:read
      tags:
      - admin.teams.settings
      - admin
      x-accepts:
      - application/json
  /admin.teams.settings.setDefaultChannels:
    post:
      description: Set the default channels of a workspace.
      operationId: admin_teams_settings_setDefaultChannels
      security:
      - slackAuth:
        - admin.teams:write
      tags:
      - admin.teams.settings
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.teams.settings.setDescription:
    post:
      description: Set the description of a given workspace.
      operationId: admin_teams_settings_setDescription
      security:
      - slackAuth:
        - admin.teams:write
      tags:
      - admin.teams.settings
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.teams.settings.setDiscoverability:
    post:
      description: An API method that allows admins to set the discoverability of
        a given workspace
      operationId: admin_teams_settings_setDiscoverability
      security:
      - slackAuth:
        - admin.teams:write
      tags:
      - admin.teams.settings
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.teams.settings.setIcon:
    post:
      description: Sets the icon of a workspace.
      operationId: admin_teams_settings_setIcon
      security:
      - slackAuth:
        - admin.teams:write
      tags:
      - admin.teams.settings
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.teams.settings.setName:
    post:
      description: Set the name of a given workspace.
      operationId: admin_teams_settings_setName
      security:
      - slackAuth:
        - admin.teams:write
      tags:
      - admin.teams.settings
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.usergroups.addChannels:
    post:
      description: Add one or more default channels to an IDP group.
      operationId: admin_usergroups_addChannels
      security:
      - slackAuth:
        - admin.usergroups:write
      tags:
      - admin.usergroups
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.usergroups.addTeams:
    post:
      description: Associate one or more default workspaces with an organization-wide
        IDP group.
      operationId: admin_usergroups_addTeams
      security:
      - slackAuth:
        - admin.teams:write
      tags:
      - admin.usergroups
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.usergroups.listChannels:
    get:
      description: List the channels linked to an org-level IDP group (user group).
      operationId: admin_usergroups_listChannels
      security:
      - slackAuth:
        - admin.usergroups:read
      tags:
      - admin.usergroups
      - admin
      x-accepts:
      - application/json
  /admin.usergroups.removeChannels:
    post:
      description: Remove one or more default channels from an org-level IDP group
        (user group).
      operationId: admin_usergroups_removeChannels
      security:
      - slackAuth:
        - admin.usergroups:write
      tags:
      - admin.usergroups
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.users.assign:
    post:
      description: Add an Enterprise user to a workspace.
      operationId: admin_users_assign
      security:
      - slackAuth:
        - admin.users:write
      tags:
      - admin.users
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.users.invite:
    post:
      description: Invite a user to a workspace.
      operationId: admin_users_invite
      security:
      - slackAuth:
        - admin.users:write
      tags:
      - admin.users
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.users.list:
    get:
      description: List users on a workspace
      operationId: admin_users_list
      security:
      - slackAuth:
        - admin.users:read
      tags:
      - admin.users
      - admin
      x-accepts:
      - application/json
  /admin.users.remove:
    post:
      description: Remove a user from a workspace.
      operationId: admin_users_remove
      security:
      - slackAuth:
        - admin.users:write
      tags:
      - admin.users
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.users.session.invalidate:
    post:
      description: Invalidate a single session for a user by session_id
      operationId: admin_users_session_invalidate
      security:
      - slackAuth:
        - admin.users:write
      tags:
      - admin.users.session
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.users.session.reset:
    post:
      description: Wipes all valid sessions on all devices for a given user
      operationId: admin_users_session_reset
      security:
      - slackAuth:
        - admin.users:write
      tags:
      - admin.users.session
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.users.setAdmin:
    post:
      description: "Set an existing guest, regular user, or owner to be an admin user."
      operationId: admin_users_setAdmin
      security:
      - slackAuth:
        - admin.users:write
      tags:
      - admin.users
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.users.setExpiration:
    post:
      description: Set an expiration for a guest user
      operationId: admin_users_setExpiration
      security:
      - slackAuth:
        - admin.users:write
      tags:
      - admin.users
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.users.setOwner:
    post:
      description: "Set an existing guest, regular user, or admin user to be a workspace\
        \ owner."
      operationId: admin_users_setOwner
      security:
      - slackAuth:
        - admin.users:write
      tags:
      - admin.users
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /admin.users.setRegular:
    post:
      description: "Set an existing guest user, admin user, or owner to be a regular\
        \ user."
      operationId: admin_users_setRegular
      security:
      - slackAuth:
        - admin.users:write
      tags:
      - admin.users
      - admin
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /api.test:
    get:
      description: Checks API calling code.
      operationId: api_test
      security:
      - slackAuth:
        - none
      tags:
      - api
      x-accepts:
      - application/json
  /apps.event.authorizations.list:
    get:
      description: Get a list of authorizations for the given event context. Each
        authorization represents an app installation that the event is visible to.
      operationId: apps_event_authorizations_list
      security:
      - slackAuth:
        - authorizations:read
      tags:
      - apps.event.authorizations
      - apps
      x-accepts:
      - application/json
  /apps.permissions.info:
    get:
      description: Returns list of permissions this app has on a team.
      operationId: apps_permissions_info
      security:
      - slackAuth:
        - none
      tags:
      - apps.permissions
      - apps
      x-accepts:
      - application/json
  /apps.permissions.request:
    get:
      description: Allows an app to request additional scopes
      operationId: apps_permissions_request
      security:
      - slackAuth:
        - none
      tags:
      - apps.permissions
      - apps
      x-accepts:
      - application/json
  /apps.permissions.resources.list:
    get:
      description: Returns list of resource grants this app has on a team.
      operationId: apps_permissions_resources_list
      security:
      - slackAuth:
        - none
      tags:
      - apps.permissions.resources
      - apps
      x-accepts:
      - application/json
  /apps.permissions.scopes.list:
    get:
      description: Returns list of scopes this app has on a team.
      operationId: apps_permissions_scopes_list
      security:
      - slackAuth:
        - none
      tags:
      - apps.permissions.scopes
      - apps
      x-accepts:
      - application/json
  /apps.permissions.users.list:
    get:
      description: Returns list of user grants and corresponding scopes this app has
        on a team.
      operationId: apps_permissions_users_list
      security:
      - slackAuth:
        - none
      tags:
      - apps.permissions.users
      - apps
      x-accepts:
      - application/json
  /apps.permissions.users.request:
    get:
      description: Enables an app to trigger a permissions modal to grant an app access
        to a user access scope.
      operationId: apps_permissions_users_request
      security:
      - slackAuth:
        - none
      tags:
      - apps.permissions.users
      - apps
      x-accepts:
      - application/json
  /apps.uninstall:
    get:
      description: Uninstalls your app from a workspace.
      operationId: apps_uninstall
      security:
      - slackAuth:
        - none
      tags:
      - apps
      x-accepts:
      - application/json
  /auth.revoke:
    get:
      description: Revokes a token.
      operationId: auth_revoke
      security:
      - slackAuth:
        - none
      tags:
      - auth
      x-accepts:
      - application/json
  /auth.test:
    get:
      description: Checks authentication & identity.
      operationId: auth_test
      security:
      - slackAuth:
        - none
      tags:
      - auth
      x-accepts:
      - application/json
  /bots.info:
    get:
      description: Gets information about a bot user.
      operationId: bots_info
      security:
      - slackAuth:
        - users:read
      tags:
      - bots
      x-accepts:
      - application/json
  /calls.add:
    post:
      description: Registers a new Call.
      operationId: calls_add
      security:
      - slackAuth:
        - calls:write
      tags:
      - calls
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /calls.end:
    post:
      description: Ends a Call.
      operationId: calls_end
      security:
      - slackAuth:
        - calls:write
      tags:
      - calls
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /calls.info:
    get:
      description: Returns information about a Call.
      operationId: calls_info
      security:
      - slackAuth:
        - calls:read
      tags:
      - calls
      x-accepts:
      - application/json
  /calls.participants.add:
    post:
      description: Registers new participants added to a Call.
      operationId: calls_participants_add
      security:
      - slackAuth:
        - calls:write
      tags:
      - calls.participants
      - calls
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /calls.participants.remove:
    post:
      description: Registers participants removed from a Call.
      operationId: calls_participants_remove
      security:
      - slackAuth:
        - calls:write
      tags:
      - calls.participants
      - calls
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /calls.update:
    post:
      description: Updates information about a Call.
      operationId: calls_update
      security:
      - slackAuth:
        - calls:write
      tags:
      - calls
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /chat.delete:
    post:
      description: Deletes a message.
      operationId: chat_delete
      security:
      - slackAuth:
        - chat:write:user
        - chat:write:bot
      tags:
      - chat
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /chat.deleteScheduledMessage:
    post:
      description: Deletes a pending scheduled message from the queue.
      operationId: chat_deleteScheduledMessage
      security:
      - slackAuth:
        - chat:write:user
        - chat:write:bot
      tags:
      - chat
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /chat.getPermalink:
    get:
      description: Retrieve a permalink URL for a specific extant message
      operationId: chat_getPermalink
      security:
      - slackAuth:
        - none
      tags:
      - chat
      x-accepts:
      - application/json
  /chat.meMessage:
    post:
      description: Share a me message into a channel.
      operationId: chat_meMessage
      security:
      - slackAuth:
        - chat:write:user
        - chat:write:bot
      tags:
      - chat
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /chat.postEphemeral:
    post:
      description: Sends an ephemeral message to a user in a channel.
      operationId: chat_postEphemeral
      security:
      - slackAuth:
        - chat:write:user
        - chat:write:bot
      tags:
      - chat
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /chat.postMessage:
    post:
      description: Sends a message to a channel.
      operationId: chat_postMessage
      security:
      - slackAuth:
        - chat:write:user
        - chat:write:bot
      tags:
      - chat
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /chat.scheduleMessage:
    post:
      description: Schedules a message to be sent to a channel.
      operationId: chat_scheduleMessage
      security:
      - slackAuth:
        - chat:write:user
        - chat:write:bot
      tags:
      - chat
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /chat.scheduledMessages.list:
    get:
      description: Returns a list of scheduled messages.
      operationId: chat_scheduledMessages_list
      security:
      - slackAuth:
        - none
      tags:
      - chat.scheduledMessages
      - chat
      x-accepts:
      - application/json
  /chat.unfurl:
    post:
      description: Provide custom unfurl behavior for user-posted URLs
      operationId: chat_unfurl
      security:
      - slackAuth:
        - links:write
      tags:
      - chat
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /chat.update:
    post:
      description: Updates a message.
      operationId: chat_update
      security:
      - slackAuth:
        - chat:write:user
        - chat:write:bot
      tags:
      - chat
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /conversations.archive:
    post:
      description: Archives a conversation.
      operationId: conversations_archive
      security:
      - slackAuth:
        - channels:write
        - groups:write
        - im:write
        - mpim:write
      tags:
      - conversations
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /conversations.close:
    post:
      description: Closes a direct message or multi-person direct message.
      operationId: conversations_close
      security:
      - slackAuth:
        - channels:write
        - groups:write
        - im:write
        - mpim:write
      tags:
      - conversations
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /conversations.create:
    post:
      description: Initiates a public or private channel-based conversation
      operationId: conversations_create
      security:
      - slackAuth:
        - channels:write
        - groups:write
        - im:write
        - mpim:write
      tags:
      - conversations
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /conversations.history:
    get:
      description: Fetches a conversation's history of messages and events.
      operationId: conversations_history
      security:
      - slackAuth:
        - channels:history
        - groups:history
        - im:history
        - mpim:history
      tags:
      - conversations
      x-accepts:
      - application/json
  /conversations.info:
    get:
      description: Retrieve information about a conversation.
      operationId: conversations_info
      security:
      - slackAuth:
        - channels:read
        - groups:read
        - im:read
        - mpim:read
      tags:
      - conversations
      x-accepts:
      - application/json
  /conversations.invite:
    post:
      description: Invites users to a channel.
      operationId: conversations_invite
      security:
      - slackAuth:
        - channels:write
        - groups:write
        - im:write
        - mpim:write
      tags:
      - conversations
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /conversations.join:
    post:
      description: Joins an existing conversation.
      operationId: conversations_join
      security:
      - slackAuth:
        - channels:write
      tags:
      - conversations
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /conversations.kick:
    post:
      description: Removes a user from a conversation.
      operationId: conversations_kick
      security:
      - slackAuth:
        - channels:write
        - groups:write
        - im:write
        - mpim:write
      tags:
      - conversations
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /conversations.leave:
    post:
      description: Leaves a conversation.
      operationId: conversations_leave
      security:
      - slackAuth:
        - channels:write
        - groups:write
        - im:write
        - mpim:write
      tags:
      - conversations
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /conversations.list:
    get:
      description: Lists all channels in a Slack team.
      operationId: conversations_list
      security:
      - slackAuth:
        - channels:read
        - groups:read
        - im:read
        - mpim:read
      tags:
      - conversations
      x-accepts:
      - application/json
  /conversations.mark:
    post:
      description: Sets the read cursor in a channel.
      operationId: conversations_mark
      security:
      - slackAuth:
        - channels:write
        - groups:write
        - im:write
        - mpim:write
      tags:
      - conversations
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /conversations.members:
    get:
      description: Retrieve members of a conversation.
      operationId: conversations_members
      security:
      - slackAuth:
        - channels:read
        - groups:read
        - im:read
        - mpim:read
      tags:
      - conversations
      x-accepts:
      - application/json
  /conversations.open:
    post:
      description: Opens or resumes a direct message or multi-person direct message.
      operationId: conversations_open
      security:
      - slackAuth:
        - channels:write
        - groups:write
        - im:write
        - mpim:write
      tags:
      - conversations
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /conversations.rename:
    post:
      description: Renames a conversation.
      operationId: conversations_rename
      security:
      - slackAuth:
        - channels:write
        - groups:write
        - im:write
        - mpim:write
      tags:
      - conversations
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /conversations.replies:
    get:
      description: Retrieve a thread of messages posted to a conversation
      operationId: conversations_replies
      security:
      - slackAuth:
        - channels:history
        - groups:history
        - im:history
        - mpim:history
      tags:
      - conversations
      x-accepts:
      - application/json
  /conversations.setPurpose:
    post:
      description: Sets the purpose for a conversation.
      operationId: conversations_setPurpose
      security:
      - slackAuth:
        - channels:write
        - groups:write
        - im:write
        - mpim:write
      tags:
      - conversations
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /conversations.setTopic:
    post:
      description: Sets the topic for a conversation.
      operationId: conversations_setTopic
      security:
      - slackAuth:
        - channels:write
        - groups:write
        - im:write
        - mpim:write
      tags:
      - conversations
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /conversations.unarchive:
    post:
      description: Reverses conversation archival.
      operationId: conversations_unarchive
      security:
      - slackAuth:
        - channels:write
        - groups:write
        - im:write
        - mpim:write
      tags:
      - conversations
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /dialog.open:
    get:
      description: Open a dialog with a user
      operationId: dialog_open
      security:
      - slackAuth:
        - none
      tags:
      - dialog
      x-accepts:
      - application/json
  /dnd.endDnd:
    post:
      description: Ends the current user's Do Not Disturb session immediately.
      operationId: dnd_endDnd
      security:
      - slackAuth:
        - dnd:write
      tags:
      - dnd
      x-accepts:
      - application/json
  /dnd.endSnooze:
    post:
      description: Ends the current user's snooze mode immediately.
      operationId: dnd_endSnooze
      security:
      - slackAuth:
        - dnd:write
      tags:
      - dnd
      x-accepts:
      - application/json
  /dnd.info:
    get:
      description: Retrieves a user's current Do Not Disturb status.
      operationId: dnd_info
      security:
      - slackAuth:
        - dnd:read
      tags:
      - dnd
      x-accepts:
      - application/json
  /dnd.setSnooze:
    post:
      description: "Turns on Do Not Disturb mode for the current user, or changes\
        \ its duration."
      operationId: dnd_setSnooze
      security:
      - slackAuth:
        - dnd:write
      tags:
      - dnd
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /dnd.teamInfo:
    get:
      description: Retrieves the Do Not Disturb status for up to 50 users on a team.
      operationId: dnd_teamInfo
      security:
      - slackAuth:
        - dnd:read
      tags:
      - dnd
      x-accepts:
      - application/json
  /emoji.list:
    get:
      description: Lists custom emoji for a team.
      operationId: emoji_list
      security:
      - slackAuth:
        - emoji:read
      tags:
      - emoji
      x-accepts:
      - application/json
  /files.comments.delete:
    post:
      description: Deletes an existing comment on a file.
      operationId: files_comments_delete
      security:
      - slackAuth:
        - files:write:user
      tags:
      - files.comments
      - files
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /files.delete:
    post:
      description: Deletes a file.
      operationId: files_delete
      security:
      - slackAuth:
        - files:write:user
      tags:
      - files
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /files.info:
    get:
      description: Gets information about a file.
      operationId: files_info
      security:
      - slackAuth:
        - files:read
      tags:
      - files
      x-accepts:
      - application/json
  /files.list:
    get:
      description: "List for a team, in a channel, or from a user with applied filters."
      operationId: files_list
      security:
      - slackAuth:
        - files:read
      tags:
      - files
      x-accepts:
      - application/json
  /files.remote.add:
    post:
      description: Adds a file from a remote service
      operationId: files_remote_add
      security:
      - slackAuth:
        - remote_files:write
      tags:
      - files.remote
      - files
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /files.remote.info:
    get:
      description: Retrieve information about a remote file added to Slack
      operationId: files_remote_info
      security:
      - slackAuth:
        - remote_files:read
      tags:
      - files.remote
      - files
      x-accepts:
      - application/json
  /files.remote.list:
    get:
      description: Retrieve information about a remote file added to Slack
      operationId: files_remote_list
      security:
      - slackAuth:
        - remote_files:read
      tags:
      - files.remote
      - files
      x-accepts:
      - application/json
  /files.remote.remove:
    post:
      description: Remove a remote file.
      operationId: files_remote_remove
      security:
      - slackAuth:
        - remote_files:write
      tags:
      - files.remote
      - files
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /files.remote.share:
    get:
      description: Share a remote file into a channel.
      operationId: files_remote_share
      security:
      - slackAuth:
        - remote_files:share
      tags:
      - files.remote
      - files
      x-accepts:
      - application/json
  /files.remote.update:
    post:
      description: Updates an existing remote file.
      operationId: files_remote_update
      security:
      - slackAuth:
        - remote_files:write
      tags:
      - files.remote
      - files
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /files.revokePublicURL:
    post:
      description: Revokes public/external sharing access for a file
      operationId: files_revokePublicURL
      security:
      - slackAuth:
        - files:write:user
      tags:
      - files
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /files.sharedPublicURL:
    post:
      description: Enables a file for public/external sharing.
      operationId: files_sharedPublicURL
      security:
      - slackAuth:
        - files:write:user
      tags:
      - files
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /files.upload:
    post:
      description: Uploads or creates a file.
      operationId: files_upload
      security:
      - slackAuth:
        - files:write:user
      tags:
      - files
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /migration.exchange:
    get:
      description: "For Enterprise Grid workspaces, map local user IDs to global user\
        \ IDs"
      operationId: migration_exchange
      security:
      - slackAuth:
        - tokens.basic
      tags:
      - migration
      x-accepts:
      - application/json
  /oauth.access:
    get:
      description: Exchanges a temporary OAuth verifier code for an access token.
      operationId: oauth_access
      security:
      - slackAuth:
        - none
      tags:
      - oauth
      x-accepts:
      - application/json
  /oauth.token:
    get:
      description: Exchanges a temporary OAuth verifier code for a workspace token.
      operationId: oauth_token
      security:
      - slackAuth:
        - none
      tags:
      - oauth
      x-accepts:
      - application/json
  /oauth.v2.access:
    get:
      description: Exchanges a temporary OAuth verifier code for an access token.
      operationId: oauth_v2_access
      security:
      - slackAuth:
        - none
      tags:
      - oauth.v2
      - oauth
      x-accepts:
      - application/json
  /pins.add:
    post:
      description: Pins an item to a channel.
      operationId: pins_add
      security:
      - slackAuth:
        - pins:write
      tags:
      - pins
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /pins.list:
    get:
      description: Lists items pinned to a channel.
      operationId: pins_list
      security:
      - slackAuth:
        - pins:read
      tags:
      - pins
      x-accepts:
      - application/json
  /pins.remove:
    post:
      description: Un-pins an item from a channel.
      operationId: pins_remove
      security:
      - slackAuth:
        - pins:write
      tags:
      - pins
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /reactions.add:
    post:
      description: Adds a reaction to an item.
      operationId: reactions_add
      security:
      - slackAuth:
        - reactions:write
      tags:
      - reactions
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /reactions.get:
    get:
      description: Gets reactions for an item.
      operationId: reactions_get
      security:
      - slackAuth:
        - reactions:read
      tags:
      - reactions
      x-accepts:
      - application/json
  /reactions.list:
    get:
      description: Lists reactions made by a user.
      operationId: reactions_list
      security:
      - slackAuth:
        - reactions:read
      tags:
      - reactions
      x-accepts:
      - application/json
  /reactions.remove:
    post:
      description: Removes a reaction from an item.
      operationId: reactions_remove
      security:
      - slackAuth:
        - reactions:write
      tags:
      - reactions
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /reminders.add:
    post:
      description: Creates a reminder.
      operationId: reminders_add
      security:
      - slackAuth:
        - reminders:write
      tags:
      - reminders
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /reminders.complete:
    post:
      description: Marks a reminder as complete.
      operationId: reminders_complete
      security:
      - slackAuth:
        - reminders:write
      tags:
      - reminders
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /reminders.delete:
    post:
      description: Deletes a reminder.
      operationId: reminders_delete
      security:
      - slackAuth:
        - reminders:write
      tags:
      - reminders
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /reminders.info:
    get:
      description: Gets information about a reminder.
      operationId: reminders_info
      security:
      - slackAuth:
        - reminders:read
      tags:
      - reminders
      x-accepts:
      - application/json
  /reminders.list:
    get:
      description: Lists all reminders created by or for a given user.
      operationId: reminders_list
      security:
      - slackAuth:
        - reminders:read
      tags:
      - reminders
      x-accepts:
      - application/json
  /rtm.connect:
    get:
      description: Starts a Real Time Messaging session.
      operationId: rtm_connect
      security:
      - slackAuth:
        - rtm:stream
      tags:
      - rtm
      x-accepts:
      - application/json
  /search.messages:
    get:
      description: Searches for messages matching a query.
      operationId: search_messages
      security:
      - slackAuth:
        - search:read
      tags:
      - search
      x-accepts:
      - application/json
  /stars.add:
    post:
      description: Adds a star to an item.
      operationId: stars_add
      security:
      - slackAuth:
        - stars:write
      tags:
      - stars
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /stars.list:
    get:
      description: Lists stars for a user.
      operationId: stars_list
      security:
      - slackAuth:
        - stars:read
      tags:
      - stars
      x-accepts:
      - application/json
  /stars.remove:
    post:
      description: Removes a star from an item.
      operationId: stars_remove
      security:
      - slackAuth:
        - stars:write
      tags:
      - stars
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /team.accessLogs:
    get:
      description: Gets the access logs for the current team.
      operationId: team_accessLogs
      security:
      - slackAuth:
        - admin
      tags:
      - team
      x-accepts:
      - application/json
  /team.billableInfo:
    get:
      description: Gets billable users information for the current team.
      operationId: team_billableInfo
      security:
      - slackAuth:
        - admin
      tags:
      - team
      x-accepts:
      - application/json
  /team.info:
    get:
      description: Gets information about the current team.
      operationId: team_info
      security:
      - slackAuth:
        - team:read
      tags:
      - team
      x-accepts:
      - application/json
  /team.integrationLogs:
    get:
      description: Gets the integration logs for the current team.
      operationId: team_integrationLogs
      security:
      - slackAuth:
        - admin
      tags:
      - team
      x-accepts:
      - application/json
  /team.profile.get:
    get:
      description: Retrieve a team's profile.
      operationId: team_profile_get
      security:
      - slackAuth:
        - users.profile:read
      tags:
      - team.profile
      - team
      x-accepts:
      - application/json
  /usergroups.create:
    post:
      description: Create a User Group
      operationId: usergroups_create
      security:
      - slackAuth:
        - usergroups:write
      tags:
      - usergroups
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /usergroups.disable:
    post:
      description: Disable an existing User Group
      operationId: usergroups_disable
      security:
      - slackAuth:
        - usergroups:write
      tags:
      - usergroups
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /usergroups.enable:
    post:
      description: Enable a User Group
      operationId: usergroups_enable
      security:
      - slackAuth:
        - usergroups:write
      tags:
      - usergroups
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /usergroups.list:
    get:
      description: List all User Groups for a team
      operationId: usergroups_list
      security:
      - slackAuth:
        - usergroups:read
      tags:
      - usergroups
      x-accepts:
      - application/json
  /usergroups.update:
    post:
      description: Update an existing User Group
      operationId: usergroups_update
      security:
      - slackAuth:
        - usergroups:write
      tags:
      - usergroups
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /usergroups.users.list:
    get:
      description: List all users in a User Group
      operationId: usergroups_users_list
      security:
      - slackAuth:
        - usergroups:read
      tags:
      - usergroups.users
      - usergroups
      x-accepts:
      - application/json
  /usergroups.users.update:
    post:
      description: Update the list of users for a User Group
      operationId: usergroups_users_update
      security:
      - slackAuth:
        - usergroups:write
      tags:
      - usergroups.users
      - usergroups
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /users.conversations:
    get:
      description: List conversations the calling user may access.
      operationId: users_conversations
      security:
      - slackAuth:
        - channels:read
        - groups:read
        - im:read
        - mpim:read
      tags:
      - users
      x-accepts:
      - application/json
  /users.deletePhoto:
    post:
      description: Delete the user profile photo
      operationId: users_deletePhoto
      security:
      - slackAuth:
        - users.profile:write
      tags:
      - users
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /users.getPresence:
    get:
      description: Gets user presence information.
      operationId: users_getPresence
      security:
      - slackAuth:
        - users:read
      tags:
      - users
      x-accepts:
      - application/json
  /users.identity:
    get:
      description: Get a user's identity.
      operationId: users_identity
      security:
      - slackAuth:
        - identity.basic
      tags:
      - users
      x-accepts:
      - application/json
  /users.info:
    get:
      description: Gets information about a user.
      operationId: users_info
      security:
      - slackAuth:
        - users:read
      tags:
      - users
      x-accepts:
      - application/json
  /users.list:
    get:
      description: Lists all users in a Slack team.
      operationId: users_list
      security:
      - slackAuth:
        - users:read
      tags:
      - users
      x-accepts:
      - application/json
  /users.lookupByEmail:
    get:
      description: Find a user with an email address.
      operationId: users_lookupByEmail
      security:
      - slackAuth:
        - users:read.email
      tags:
      - users
      x-accepts:
      - application/json
  /users.profile.get:
    get:
      description: Retrieves a user's profile information.
      operationId: users_profile_get
      security:
      - slackAuth:
        - users.profile:read
      tags:
      - users.profile
      - users
      x-accepts:
      - application/json
  /users.profile.set:
    post:
      description: Set the profile information for a user.
      operationId: users_profile_set
      security:
      - slackAuth:
        - users.profile:write
      tags:
      - users.profile
      - users
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /users.setActive:
    post:
      description: Marked a user as active. Deprecated and non-functional.
      operationId: users_setActive
      security:
      - slackAuth:
        - users:write
      tags:
      - users
      x-accepts:
      - application/json
  /users.setPhoto:
    post:
      description: Set the user profile photo
      operationId: users_setPhoto
      security:
      - slackAuth:
        - users.profile:write
      tags:
      - users
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /users.setPresence:
    post:
      description: Manually sets user presence.
      operationId: users_setPresence
      security:
      - slackAuth:
        - users:write
      tags:
      - users
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /views.open:
    get:
      description: Open a view for a user.
      operationId: views_open
      security:
      - slackAuth:
        - none
      tags:
      - views
      x-accepts:
      - application/json
  /views.publish:
    get:
      description: Publish a static view for a User.
      operationId: views_publish
      security:
      - slackAuth:
        - none
      tags:
      - views
      x-accepts:
      - application/json
  /views.push:
    get:
      description: Push a view onto the stack of a root view.
      operationId: views_push
      security:
      - slackAuth:
        - none
      tags:
      - views
      x-accepts:
      - application/json
  /views.update:
    get:
      description: Update an existing view.
      operationId: views_update
      security:
      - slackAuth:
        - none
      tags:
      - views
      x-accepts:
      - application/json
  /workflows.stepCompleted:
    get:
      description: Indicate that an app's step in a workflow completed execution.
      operationId: workflows_stepCompleted
      security:
      - slackAuth:
        - workflow.steps:execute
      tags:
      - workflows
      x-accepts:
      - application/json
  /workflows.stepFailed:
    get:
      description: Indicate that an app's step in a workflow failed to execute.
      operationId: workflows_stepFailed
      security:
      - slackAuth:
        - workflow.steps:execute
      tags:
      - workflows
      x-accepts:
      - application/json
  /workflows.updateStep:
    get:
      description: Update the configuration for a workflow extension step.
      operationId: workflows_updateStep
      security:
      - slackAuth:
        - workflow.steps:execute
      tags:
      - workflows
      x-accepts:
      - application/json
components:
  securitySchemes:
    slackAuth:
      flows:
        authorizationCode:
          authorizationUrl: https://slack.com/oauth/authorize
          scopes:
            admin: admin
            admin.apps:read: admin.apps:read
            admin.apps:write: admin.apps:write
            admin.conversations:read: admin.conversations:read
            admin.conversations:write: admin.conversations:write
            admin.invites:read: admin.invites:read
            admin.invites:write: admin.invites:write
            admin.teams:read: admin.teams:read
            admin.teams:write: admin.teams:write
            admin.usergroups:read: admin.usergroups:read
            admin.usergroups:write: admin.usergroups:write
            admin.users:read: admin.users:read
            admin.users:write: admin.users:write
            authorizations:read: authorizations:read
            bot: Bot user scope
            calls:read: calls:read
            calls:write: calls:write
            channels:history: channels:history
            channels:manage: channels:manage
            channels:read: channels:read
            channels:write: channels:write
            chat:write: chat:write
            chat:write:bot: Author messages as a bot
            chat:write:user: Author messages as a user
            conversations:history: conversations:history
            conversations:read: conversations:read
            conversations:write: conversations:write
            dnd:read: dnd:read
            dnd:write: dnd:write
            emoji:read: emoji:read
            files:read: files:read
            files:write:user: files:write:user
            groups:history: groups:history
            groups:read: groups:read
            groups:write: groups:write
            identity.basic: identity.basic
            im:history: im:history
            im:read: im:read
            im:write: im:write
            links:write: links:write
            mpim:history: mpim:history
            mpim:read: mpim:read
            mpim:write: mpim:write
            none: No scope required
            pins:read: pins:read
            pins:write: pins:write
            reactions:read: reactions:read
            reactions:write: reactions:write
            reminders:read: reminders:read
            reminders:write: reminders:write
            remote_files:read: remote_files:read
            remote_files:share: remote_files:share
            remote_files:write: remote_files:write
            rtm:stream: rtm:stream
            search:read: search:read
            stars:read: stars:read
            stars:write: stars:write
            team:read: team:read
            tokens.basic: tokens.basic
            usergroups:read: usergroups:read
            usergroups:write: usergroups:write
            users.profile:read: users.profile:read
            users.profile:write: users.profile:write
            users:read: users:read
            users:read.email: users:read.email
            users:write: users:write
            workflow.steps:execute: workflow.steps:execute
          tokenUrl: https://slack.com/api/oauth.access
      type: oauth2

