QT += network

HEADERS += \
# Models
    $${PWD}/OAIAdMarkers.h \
    $${PWD}/OAIAdsOnDeliveryRestrictions.h \
    $${PWD}/OAIAuthorization.h \
    $${PWD}/OAIChannel.h \
    $${PWD}/OAICmafEncryption.h \
    $${PWD}/OAICmafEncryptionMethod.h \
    $${PWD}/OAICmafEncryption_SpekeKeyProvider.h \
    $${PWD}/OAICmafPackage.h \
    $${PWD}/OAICmafPackageCreateOrUpdateParameters.h \
    $${PWD}/OAIConfigureLogsRequest.h \
    $${PWD}/OAIConfigureLogsResponse.h \
    $${PWD}/OAIConfigureLogsResponse_EgressAccessLogs.h \
    $${PWD}/OAIConfigureLogsResponse_HlsIngest.h \
    $${PWD}/OAIConfigureLogsResponse_IngressAccessLogs.h \
    $${PWD}/OAIConfigureLogs_request.h \
    $${PWD}/OAIConfigureLogs_request_egressAccessLogs.h \
    $${PWD}/OAIConfigureLogs_request_ingressAccessLogs.h \
    $${PWD}/OAICreateChannelRequest.h \
    $${PWD}/OAICreateChannelResponse.h \
    $${PWD}/OAICreateChannel_request.h \
    $${PWD}/OAICreateHarvestJobRequest.h \
    $${PWD}/OAICreateHarvestJobResponse.h \
    $${PWD}/OAICreateHarvestJobResponse_S3Destination.h \
    $${PWD}/OAICreateHarvestJob_request.h \
    $${PWD}/OAICreateHarvestJob_request_s3Destination.h \
    $${PWD}/OAICreateOriginEndpointRequest.h \
    $${PWD}/OAICreateOriginEndpointRequest_CmafPackage.h \
    $${PWD}/OAICreateOriginEndpointResponse.h \
    $${PWD}/OAICreateOriginEndpointResponse_Authorization.h \
    $${PWD}/OAICreateOriginEndpointResponse_CmafPackage.h \
    $${PWD}/OAICreateOriginEndpointResponse_DashPackage.h \
    $${PWD}/OAICreateOriginEndpointResponse_HlsPackage.h \
    $${PWD}/OAICreateOriginEndpointResponse_MssPackage.h \
    $${PWD}/OAICreateOriginEndpoint_request.h \
    $${PWD}/OAICreateOriginEndpoint_request_authorization.h \
    $${PWD}/OAICreateOriginEndpoint_request_cmafPackage.h \
    $${PWD}/OAICreateOriginEndpoint_request_cmafPackage_Encryption.h \
    $${PWD}/OAICreateOriginEndpoint_request_cmafPackage_StreamSelection.h \
    $${PWD}/OAICreateOriginEndpoint_request_dashPackage.h \
    $${PWD}/OAICreateOriginEndpoint_request_dashPackage_Encryption.h \
    $${PWD}/OAICreateOriginEndpoint_request_hlsPackage.h \
    $${PWD}/OAICreateOriginEndpoint_request_hlsPackage_Encryption.h \
    $${PWD}/OAICreateOriginEndpoint_request_mssPackage.h \
    $${PWD}/OAICreateOriginEndpoint_request_mssPackage_Encryption.h \
    $${PWD}/OAIDashEncryption.h \
    $${PWD}/OAIDashPackage.h \
    $${PWD}/OAIDescribeChannelResponse.h \
    $${PWD}/OAIDescribeHarvestJobResponse.h \
    $${PWD}/OAIDescribeOriginEndpointResponse.h \
    $${PWD}/OAIEgressAccessLogs.h \
    $${PWD}/OAIEncryptionContractConfiguration.h \
    $${PWD}/OAIEncryptionMethod.h \
    $${PWD}/OAIHarvestJob.h \
    $${PWD}/OAIHlsEncryption.h \
    $${PWD}/OAIHlsIngest.h \
    $${PWD}/OAIHlsManifest.h \
    $${PWD}/OAIHlsManifestCreateOrUpdateParameters.h \
    $${PWD}/OAIHlsPackage.h \
    $${PWD}/OAIIngestEndpoint.h \
    $${PWD}/OAIIngressAccessLogs.h \
    $${PWD}/OAIListChannelsResponse.h \
    $${PWD}/OAIListHarvestJobsResponse.h \
    $${PWD}/OAIListOriginEndpointsResponse.h \
    $${PWD}/OAIListTagsForResourceResponse.h \
    $${PWD}/OAIManifestLayout.h \
    $${PWD}/OAIMssEncryption.h \
    $${PWD}/OAIMssPackage.h \
    $${PWD}/OAIOriginEndpoint.h \
    $${PWD}/OAIOrigination.h \
    $${PWD}/OAIPlaylistType.h \
    $${PWD}/OAIPresetSpeke20Audio.h \
    $${PWD}/OAIPresetSpeke20Video.h \
    $${PWD}/OAIProfile.h \
    $${PWD}/OAIRotateChannelCredentialsResponse.h \
    $${PWD}/OAIRotateIngestEndpointCredentialsResponse.h \
    $${PWD}/OAIS3Destination.h \
    $${PWD}/OAISegmentTemplateFormat.h \
    $${PWD}/OAISpekeKeyProvider.h \
    $${PWD}/OAISpekeKeyProvider_EncryptionContractConfiguration.h \
    $${PWD}/OAIStatus.h \
    $${PWD}/OAIStreamOrder.h \
    $${PWD}/OAIStreamSelection.h \
    $${PWD}/OAITagResourceRequest.h \
    $${PWD}/OAITagResource_request.h \
    $${PWD}/OAIUpdateChannelRequest.h \
    $${PWD}/OAIUpdateChannelResponse.h \
    $${PWD}/OAIUpdateChannel_request.h \
    $${PWD}/OAIUpdateOriginEndpointRequest.h \
    $${PWD}/OAIUpdateOriginEndpointResponse.h \
    $${PWD}/OAIUpdateOriginEndpoint_request.h \
    $${PWD}/OAIUtcTiming.h \
    $${PWD}/OAI__AdTriggersElement.h \
    $${PWD}/OAI__PeriodTriggersElement.h \
# APIs
    $${PWD}/OAIDefaultApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAdMarkers.cpp \
    $${PWD}/OAIAdsOnDeliveryRestrictions.cpp \
    $${PWD}/OAIAuthorization.cpp \
    $${PWD}/OAIChannel.cpp \
    $${PWD}/OAICmafEncryption.cpp \
    $${PWD}/OAICmafEncryptionMethod.cpp \
    $${PWD}/OAICmafEncryption_SpekeKeyProvider.cpp \
    $${PWD}/OAICmafPackage.cpp \
    $${PWD}/OAICmafPackageCreateOrUpdateParameters.cpp \
    $${PWD}/OAIConfigureLogsRequest.cpp \
    $${PWD}/OAIConfigureLogsResponse.cpp \
    $${PWD}/OAIConfigureLogsResponse_EgressAccessLogs.cpp \
    $${PWD}/OAIConfigureLogsResponse_HlsIngest.cpp \
    $${PWD}/OAIConfigureLogsResponse_IngressAccessLogs.cpp \
    $${PWD}/OAIConfigureLogs_request.cpp \
    $${PWD}/OAIConfigureLogs_request_egressAccessLogs.cpp \
    $${PWD}/OAIConfigureLogs_request_ingressAccessLogs.cpp \
    $${PWD}/OAICreateChannelRequest.cpp \
    $${PWD}/OAICreateChannelResponse.cpp \
    $${PWD}/OAICreateChannel_request.cpp \
    $${PWD}/OAICreateHarvestJobRequest.cpp \
    $${PWD}/OAICreateHarvestJobResponse.cpp \
    $${PWD}/OAICreateHarvestJobResponse_S3Destination.cpp \
    $${PWD}/OAICreateHarvestJob_request.cpp \
    $${PWD}/OAICreateHarvestJob_request_s3Destination.cpp \
    $${PWD}/OAICreateOriginEndpointRequest.cpp \
    $${PWD}/OAICreateOriginEndpointRequest_CmafPackage.cpp \
    $${PWD}/OAICreateOriginEndpointResponse.cpp \
    $${PWD}/OAICreateOriginEndpointResponse_Authorization.cpp \
    $${PWD}/OAICreateOriginEndpointResponse_CmafPackage.cpp \
    $${PWD}/OAICreateOriginEndpointResponse_DashPackage.cpp \
    $${PWD}/OAICreateOriginEndpointResponse_HlsPackage.cpp \
    $${PWD}/OAICreateOriginEndpointResponse_MssPackage.cpp \
    $${PWD}/OAICreateOriginEndpoint_request.cpp \
    $${PWD}/OAICreateOriginEndpoint_request_authorization.cpp \
    $${PWD}/OAICreateOriginEndpoint_request_cmafPackage.cpp \
    $${PWD}/OAICreateOriginEndpoint_request_cmafPackage_Encryption.cpp \
    $${PWD}/OAICreateOriginEndpoint_request_cmafPackage_StreamSelection.cpp \
    $${PWD}/OAICreateOriginEndpoint_request_dashPackage.cpp \
    $${PWD}/OAICreateOriginEndpoint_request_dashPackage_Encryption.cpp \
    $${PWD}/OAICreateOriginEndpoint_request_hlsPackage.cpp \
    $${PWD}/OAICreateOriginEndpoint_request_hlsPackage_Encryption.cpp \
    $${PWD}/OAICreateOriginEndpoint_request_mssPackage.cpp \
    $${PWD}/OAICreateOriginEndpoint_request_mssPackage_Encryption.cpp \
    $${PWD}/OAIDashEncryption.cpp \
    $${PWD}/OAIDashPackage.cpp \
    $${PWD}/OAIDescribeChannelResponse.cpp \
    $${PWD}/OAIDescribeHarvestJobResponse.cpp \
    $${PWD}/OAIDescribeOriginEndpointResponse.cpp \
    $${PWD}/OAIEgressAccessLogs.cpp \
    $${PWD}/OAIEncryptionContractConfiguration.cpp \
    $${PWD}/OAIEncryptionMethod.cpp \
    $${PWD}/OAIHarvestJob.cpp \
    $${PWD}/OAIHlsEncryption.cpp \
    $${PWD}/OAIHlsIngest.cpp \
    $${PWD}/OAIHlsManifest.cpp \
    $${PWD}/OAIHlsManifestCreateOrUpdateParameters.cpp \
    $${PWD}/OAIHlsPackage.cpp \
    $${PWD}/OAIIngestEndpoint.cpp \
    $${PWD}/OAIIngressAccessLogs.cpp \
    $${PWD}/OAIListChannelsResponse.cpp \
    $${PWD}/OAIListHarvestJobsResponse.cpp \
    $${PWD}/OAIListOriginEndpointsResponse.cpp \
    $${PWD}/OAIListTagsForResourceResponse.cpp \
    $${PWD}/OAIManifestLayout.cpp \
    $${PWD}/OAIMssEncryption.cpp \
    $${PWD}/OAIMssPackage.cpp \
    $${PWD}/OAIOriginEndpoint.cpp \
    $${PWD}/OAIOrigination.cpp \
    $${PWD}/OAIPlaylistType.cpp \
    $${PWD}/OAIPresetSpeke20Audio.cpp \
    $${PWD}/OAIPresetSpeke20Video.cpp \
    $${PWD}/OAIProfile.cpp \
    $${PWD}/OAIRotateChannelCredentialsResponse.cpp \
    $${PWD}/OAIRotateIngestEndpointCredentialsResponse.cpp \
    $${PWD}/OAIS3Destination.cpp \
    $${PWD}/OAISegmentTemplateFormat.cpp \
    $${PWD}/OAISpekeKeyProvider.cpp \
    $${PWD}/OAISpekeKeyProvider_EncryptionContractConfiguration.cpp \
    $${PWD}/OAIStatus.cpp \
    $${PWD}/OAIStreamOrder.cpp \
    $${PWD}/OAIStreamSelection.cpp \
    $${PWD}/OAITagResourceRequest.cpp \
    $${PWD}/OAITagResource_request.cpp \
    $${PWD}/OAIUpdateChannelRequest.cpp \
    $${PWD}/OAIUpdateChannelResponse.cpp \
    $${PWD}/OAIUpdateChannel_request.cpp \
    $${PWD}/OAIUpdateOriginEndpointRequest.cpp \
    $${PWD}/OAIUpdateOriginEndpointResponse.cpp \
    $${PWD}/OAIUpdateOriginEndpoint_request.cpp \
    $${PWD}/OAIUtcTiming.cpp \
    $${PWD}/OAI__AdTriggersElement.cpp \
    $${PWD}/OAI__PeriodTriggersElement.cpp \
# APIs
    $${PWD}/OAIDefaultApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
