QT += network

HEADERS += \
# Models
    $${PWD}/OAIApplication.h \
    $${PWD}/OAIApplicationState.h \
    $${PWD}/OAIApplicationSummary.h \
    $${PWD}/OAIApplication_autoStartConfiguration.h \
    $${PWD}/OAIApplication_autoStopConfiguration.h \
    $${PWD}/OAIApplication_imageConfiguration.h \
    $${PWD}/OAIApplication_maximumCapacity.h \
    $${PWD}/OAIApplication_networkConfiguration.h \
    $${PWD}/OAIArchitecture.h \
    $${PWD}/OAIAutoStartConfig.h \
    $${PWD}/OAIAutoStopConfig.h \
    $${PWD}/OAICancelJobRunResponse.h \
    $${PWD}/OAICloudWatchLoggingConfiguration.h \
    $${PWD}/OAIConfiguration.h \
    $${PWD}/OAIConfigurationOverrides.h \
    $${PWD}/OAICreateApplicationRequest.h \
    $${PWD}/OAICreateApplicationRequest_imageConfiguration.h \
    $${PWD}/OAICreateApplicationRequest_maximumCapacity.h \
    $${PWD}/OAICreateApplicationRequest_networkConfiguration.h \
    $${PWD}/OAICreateApplicationResponse.h \
    $${PWD}/OAICreateApplication_request.h \
    $${PWD}/OAICreateApplication_request_autoStartConfiguration.h \
    $${PWD}/OAICreateApplication_request_autoStopConfiguration.h \
    $${PWD}/OAICreateApplication_request_imageConfiguration.h \
    $${PWD}/OAICreateApplication_request_maximumCapacity.h \
    $${PWD}/OAICreateApplication_request_networkConfiguration.h \
    $${PWD}/OAIGetApplicationResponse.h \
    $${PWD}/OAIGetApplicationResponse_application.h \
    $${PWD}/OAIGetDashboardForJobRunResponse.h \
    $${PWD}/OAIGetJobRunResponse.h \
    $${PWD}/OAIGetJobRunResponse_jobRun.h \
    $${PWD}/OAIHive.h \
    $${PWD}/OAIImageConfiguration.h \
    $${PWD}/OAIImageConfigurationInput.h \
    $${PWD}/OAIInitialCapacityConfig.h \
    $${PWD}/OAIInitialCapacityConfig_workerConfiguration.h \
    $${PWD}/OAIJobDriver.h \
    $${PWD}/OAIJobRun.h \
    $${PWD}/OAIJobRunState.h \
    $${PWD}/OAIJobRunSummary.h \
    $${PWD}/OAIJobRun_billedResourceUtilization.h \
    $${PWD}/OAIJobRun_configurationOverrides.h \
    $${PWD}/OAIJobRun_jobDriver.h \
    $${PWD}/OAIJobRun_totalResourceUtilization.h \
    $${PWD}/OAIListApplicationsResponse.h \
    $${PWD}/OAIListJobRunsResponse.h \
    $${PWD}/OAIListTagsForResourceResponse.h \
    $${PWD}/OAIManagedPersistenceMonitoringConfiguration.h \
    $${PWD}/OAIMaximumAllowedResources.h \
    $${PWD}/OAIMonitoringConfiguration.h \
    $${PWD}/OAIMonitoringConfiguration_cloudWatchLoggingConfiguration.h \
    $${PWD}/OAIMonitoringConfiguration_managedPersistenceMonitoringConfiguration.h \
    $${PWD}/OAIMonitoringConfiguration_s3MonitoringConfiguration.h \
    $${PWD}/OAINetworkConfiguration.h \
    $${PWD}/OAIResourceUtilization.h \
    $${PWD}/OAIS3MonitoringConfiguration.h \
    $${PWD}/OAISparkSubmit.h \
    $${PWD}/OAIStartJobRunRequest.h \
    $${PWD}/OAIStartJobRunRequest_configurationOverrides.h \
    $${PWD}/OAIStartJobRunResponse.h \
    $${PWD}/OAIStartJobRun_request.h \
    $${PWD}/OAIStartJobRun_request_configurationOverrides.h \
    $${PWD}/OAIStartJobRun_request_configurationOverrides_monitoringConfiguration.h \
    $${PWD}/OAIStartJobRun_request_jobDriver.h \
    $${PWD}/OAIStartJobRun_request_jobDriver_hive.h \
    $${PWD}/OAIStartJobRun_request_jobDriver_sparkSubmit.h \
    $${PWD}/OAITagResourceRequest.h \
    $${PWD}/OAITagResource_request.h \
    $${PWD}/OAITotalResourceUtilization.h \
    $${PWD}/OAIUpdateApplicationRequest.h \
    $${PWD}/OAIUpdateApplicationRequest_imageConfiguration.h \
    $${PWD}/OAIUpdateApplicationRequest_maximumCapacity.h \
    $${PWD}/OAIUpdateApplicationResponse.h \
    $${PWD}/OAIUpdateApplicationResponse_application.h \
    $${PWD}/OAIUpdateApplication_request.h \
    $${PWD}/OAIWorkerResourceConfig.h \
    $${PWD}/OAIWorkerTypeSpecification.h \
    $${PWD}/OAIWorkerTypeSpecificationInput.h \
    $${PWD}/OAIWorkerTypeSpecificationInput_imageConfiguration.h \
    $${PWD}/OAIWorkerTypeSpecification_imageConfiguration.h \
# APIs
    $${PWD}/OAIDefaultApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIApplication.cpp \
    $${PWD}/OAIApplicationState.cpp \
    $${PWD}/OAIApplicationSummary.cpp \
    $${PWD}/OAIApplication_autoStartConfiguration.cpp \
    $${PWD}/OAIApplication_autoStopConfiguration.cpp \
    $${PWD}/OAIApplication_imageConfiguration.cpp \
    $${PWD}/OAIApplication_maximumCapacity.cpp \
    $${PWD}/OAIApplication_networkConfiguration.cpp \
    $${PWD}/OAIArchitecture.cpp \
    $${PWD}/OAIAutoStartConfig.cpp \
    $${PWD}/OAIAutoStopConfig.cpp \
    $${PWD}/OAICancelJobRunResponse.cpp \
    $${PWD}/OAICloudWatchLoggingConfiguration.cpp \
    $${PWD}/OAIConfiguration.cpp \
    $${PWD}/OAIConfigurationOverrides.cpp \
    $${PWD}/OAICreateApplicationRequest.cpp \
    $${PWD}/OAICreateApplicationRequest_imageConfiguration.cpp \
    $${PWD}/OAICreateApplicationRequest_maximumCapacity.cpp \
    $${PWD}/OAICreateApplicationRequest_networkConfiguration.cpp \
    $${PWD}/OAICreateApplicationResponse.cpp \
    $${PWD}/OAICreateApplication_request.cpp \
    $${PWD}/OAICreateApplication_request_autoStartConfiguration.cpp \
    $${PWD}/OAICreateApplication_request_autoStopConfiguration.cpp \
    $${PWD}/OAICreateApplication_request_imageConfiguration.cpp \
    $${PWD}/OAICreateApplication_request_maximumCapacity.cpp \
    $${PWD}/OAICreateApplication_request_networkConfiguration.cpp \
    $${PWD}/OAIGetApplicationResponse.cpp \
    $${PWD}/OAIGetApplicationResponse_application.cpp \
    $${PWD}/OAIGetDashboardForJobRunResponse.cpp \
    $${PWD}/OAIGetJobRunResponse.cpp \
    $${PWD}/OAIGetJobRunResponse_jobRun.cpp \
    $${PWD}/OAIHive.cpp \
    $${PWD}/OAIImageConfiguration.cpp \
    $${PWD}/OAIImageConfigurationInput.cpp \
    $${PWD}/OAIInitialCapacityConfig.cpp \
    $${PWD}/OAIInitialCapacityConfig_workerConfiguration.cpp \
    $${PWD}/OAIJobDriver.cpp \
    $${PWD}/OAIJobRun.cpp \
    $${PWD}/OAIJobRunState.cpp \
    $${PWD}/OAIJobRunSummary.cpp \
    $${PWD}/OAIJobRun_billedResourceUtilization.cpp \
    $${PWD}/OAIJobRun_configurationOverrides.cpp \
    $${PWD}/OAIJobRun_jobDriver.cpp \
    $${PWD}/OAIJobRun_totalResourceUtilization.cpp \
    $${PWD}/OAIListApplicationsResponse.cpp \
    $${PWD}/OAIListJobRunsResponse.cpp \
    $${PWD}/OAIListTagsForResourceResponse.cpp \
    $${PWD}/OAIManagedPersistenceMonitoringConfiguration.cpp \
    $${PWD}/OAIMaximumAllowedResources.cpp \
    $${PWD}/OAIMonitoringConfiguration.cpp \
    $${PWD}/OAIMonitoringConfiguration_cloudWatchLoggingConfiguration.cpp \
    $${PWD}/OAIMonitoringConfiguration_managedPersistenceMonitoringConfiguration.cpp \
    $${PWD}/OAIMonitoringConfiguration_s3MonitoringConfiguration.cpp \
    $${PWD}/OAINetworkConfiguration.cpp \
    $${PWD}/OAIResourceUtilization.cpp \
    $${PWD}/OAIS3MonitoringConfiguration.cpp \
    $${PWD}/OAISparkSubmit.cpp \
    $${PWD}/OAIStartJobRunRequest.cpp \
    $${PWD}/OAIStartJobRunRequest_configurationOverrides.cpp \
    $${PWD}/OAIStartJobRunResponse.cpp \
    $${PWD}/OAIStartJobRun_request.cpp \
    $${PWD}/OAIStartJobRun_request_configurationOverrides.cpp \
    $${PWD}/OAIStartJobRun_request_configurationOverrides_monitoringConfiguration.cpp \
    $${PWD}/OAIStartJobRun_request_jobDriver.cpp \
    $${PWD}/OAIStartJobRun_request_jobDriver_hive.cpp \
    $${PWD}/OAIStartJobRun_request_jobDriver_sparkSubmit.cpp \
    $${PWD}/OAITagResourceRequest.cpp \
    $${PWD}/OAITagResource_request.cpp \
    $${PWD}/OAITotalResourceUtilization.cpp \
    $${PWD}/OAIUpdateApplicationRequest.cpp \
    $${PWD}/OAIUpdateApplicationRequest_imageConfiguration.cpp \
    $${PWD}/OAIUpdateApplicationRequest_maximumCapacity.cpp \
    $${PWD}/OAIUpdateApplicationResponse.cpp \
    $${PWD}/OAIUpdateApplicationResponse_application.cpp \
    $${PWD}/OAIUpdateApplication_request.cpp \
    $${PWD}/OAIWorkerResourceConfig.cpp \
    $${PWD}/OAIWorkerTypeSpecification.cpp \
    $${PWD}/OAIWorkerTypeSpecificationInput.cpp \
    $${PWD}/OAIWorkerTypeSpecificationInput_imageConfiguration.cpp \
    $${PWD}/OAIWorkerTypeSpecification_imageConfiguration.cpp \
# APIs
    $${PWD}/OAIDefaultApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
