# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.create_api_response_cors_configuration import CreateApiResponseCorsConfiguration
from openapi_server.models.protocol_type import ProtocolType
from openapi_server import util


class CreateApiResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, api_endpoint: str=None, api_gateway_managed: bool=None, api_id: str=None, api_key_selection_expression: str=None, cors_configuration: CreateApiResponseCorsConfiguration=None, created_date: datetime=None, description: str=None, disable_schema_validation: bool=None, disable_execute_api_endpoint: bool=None, import_info: List=None, name: str=None, protocol_type: ProtocolType=None, route_selection_expression: str=None, tags: Dict=None, version: str=None, warnings: List=None):
        """CreateApiResponse - a model defined in OpenAPI

        :param api_endpoint: The api_endpoint of this CreateApiResponse.
        :param api_gateway_managed: The api_gateway_managed of this CreateApiResponse.
        :param api_id: The api_id of this CreateApiResponse.
        :param api_key_selection_expression: The api_key_selection_expression of this CreateApiResponse.
        :param cors_configuration: The cors_configuration of this CreateApiResponse.
        :param created_date: The created_date of this CreateApiResponse.
        :param description: The description of this CreateApiResponse.
        :param disable_schema_validation: The disable_schema_validation of this CreateApiResponse.
        :param disable_execute_api_endpoint: The disable_execute_api_endpoint of this CreateApiResponse.
        :param import_info: The import_info of this CreateApiResponse.
        :param name: The name of this CreateApiResponse.
        :param protocol_type: The protocol_type of this CreateApiResponse.
        :param route_selection_expression: The route_selection_expression of this CreateApiResponse.
        :param tags: The tags of this CreateApiResponse.
        :param version: The version of this CreateApiResponse.
        :param warnings: The warnings of this CreateApiResponse.
        """
        self.openapi_types = {
            'api_endpoint': str,
            'api_gateway_managed': bool,
            'api_id': str,
            'api_key_selection_expression': str,
            'cors_configuration': CreateApiResponseCorsConfiguration,
            'created_date': datetime,
            'description': str,
            'disable_schema_validation': bool,
            'disable_execute_api_endpoint': bool,
            'import_info': List,
            'name': str,
            'protocol_type': ProtocolType,
            'route_selection_expression': str,
            'tags': Dict,
            'version': str,
            'warnings': List
        }

        self.attribute_map = {
            'api_endpoint': 'ApiEndpoint',
            'api_gateway_managed': 'ApiGatewayManaged',
            'api_id': 'ApiId',
            'api_key_selection_expression': 'ApiKeySelectionExpression',
            'cors_configuration': 'CorsConfiguration',
            'created_date': 'CreatedDate',
            'description': 'Description',
            'disable_schema_validation': 'DisableSchemaValidation',
            'disable_execute_api_endpoint': 'DisableExecuteApiEndpoint',
            'import_info': 'ImportInfo',
            'name': 'Name',
            'protocol_type': 'ProtocolType',
            'route_selection_expression': 'RouteSelectionExpression',
            'tags': 'Tags',
            'version': 'Version',
            'warnings': 'Warnings'
        }

        self._api_endpoint = api_endpoint
        self._api_gateway_managed = api_gateway_managed
        self._api_id = api_id
        self._api_key_selection_expression = api_key_selection_expression
        self._cors_configuration = cors_configuration
        self._created_date = created_date
        self._description = description
        self._disable_schema_validation = disable_schema_validation
        self._disable_execute_api_endpoint = disable_execute_api_endpoint
        self._import_info = import_info
        self._name = name
        self._protocol_type = protocol_type
        self._route_selection_expression = route_selection_expression
        self._tags = tags
        self._version = version
        self._warnings = warnings

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CreateApiResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The CreateApiResponse of this CreateApiResponse.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def api_endpoint(self):
        """Gets the api_endpoint of this CreateApiResponse.


        :return: The api_endpoint of this CreateApiResponse.
        :rtype: str
        """
        return self._api_endpoint

    @api_endpoint.setter
    def api_endpoint(self, api_endpoint):
        """Sets the api_endpoint of this CreateApiResponse.


        :param api_endpoint: The api_endpoint of this CreateApiResponse.
        :type api_endpoint: str
        """

        self._api_endpoint = api_endpoint

    @property
    def api_gateway_managed(self):
        """Gets the api_gateway_managed of this CreateApiResponse.


        :return: The api_gateway_managed of this CreateApiResponse.
        :rtype: bool
        """
        return self._api_gateway_managed

    @api_gateway_managed.setter
    def api_gateway_managed(self, api_gateway_managed):
        """Sets the api_gateway_managed of this CreateApiResponse.


        :param api_gateway_managed: The api_gateway_managed of this CreateApiResponse.
        :type api_gateway_managed: bool
        """

        self._api_gateway_managed = api_gateway_managed

    @property
    def api_id(self):
        """Gets the api_id of this CreateApiResponse.


        :return: The api_id of this CreateApiResponse.
        :rtype: str
        """
        return self._api_id

    @api_id.setter
    def api_id(self, api_id):
        """Sets the api_id of this CreateApiResponse.


        :param api_id: The api_id of this CreateApiResponse.
        :type api_id: str
        """

        self._api_id = api_id

    @property
    def api_key_selection_expression(self):
        """Gets the api_key_selection_expression of this CreateApiResponse.


        :return: The api_key_selection_expression of this CreateApiResponse.
        :rtype: str
        """
        return self._api_key_selection_expression

    @api_key_selection_expression.setter
    def api_key_selection_expression(self, api_key_selection_expression):
        """Sets the api_key_selection_expression of this CreateApiResponse.


        :param api_key_selection_expression: The api_key_selection_expression of this CreateApiResponse.
        :type api_key_selection_expression: str
        """

        self._api_key_selection_expression = api_key_selection_expression

    @property
    def cors_configuration(self):
        """Gets the cors_configuration of this CreateApiResponse.


        :return: The cors_configuration of this CreateApiResponse.
        :rtype: CreateApiResponseCorsConfiguration
        """
        return self._cors_configuration

    @cors_configuration.setter
    def cors_configuration(self, cors_configuration):
        """Sets the cors_configuration of this CreateApiResponse.


        :param cors_configuration: The cors_configuration of this CreateApiResponse.
        :type cors_configuration: CreateApiResponseCorsConfiguration
        """

        self._cors_configuration = cors_configuration

    @property
    def created_date(self):
        """Gets the created_date of this CreateApiResponse.


        :return: The created_date of this CreateApiResponse.
        :rtype: datetime
        """
        return self._created_date

    @created_date.setter
    def created_date(self, created_date):
        """Sets the created_date of this CreateApiResponse.


        :param created_date: The created_date of this CreateApiResponse.
        :type created_date: datetime
        """

        self._created_date = created_date

    @property
    def description(self):
        """Gets the description of this CreateApiResponse.


        :return: The description of this CreateApiResponse.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CreateApiResponse.


        :param description: The description of this CreateApiResponse.
        :type description: str
        """

        self._description = description

    @property
    def disable_schema_validation(self):
        """Gets the disable_schema_validation of this CreateApiResponse.


        :return: The disable_schema_validation of this CreateApiResponse.
        :rtype: bool
        """
        return self._disable_schema_validation

    @disable_schema_validation.setter
    def disable_schema_validation(self, disable_schema_validation):
        """Sets the disable_schema_validation of this CreateApiResponse.


        :param disable_schema_validation: The disable_schema_validation of this CreateApiResponse.
        :type disable_schema_validation: bool
        """

        self._disable_schema_validation = disable_schema_validation

    @property
    def disable_execute_api_endpoint(self):
        """Gets the disable_execute_api_endpoint of this CreateApiResponse.


        :return: The disable_execute_api_endpoint of this CreateApiResponse.
        :rtype: bool
        """
        return self._disable_execute_api_endpoint

    @disable_execute_api_endpoint.setter
    def disable_execute_api_endpoint(self, disable_execute_api_endpoint):
        """Sets the disable_execute_api_endpoint of this CreateApiResponse.


        :param disable_execute_api_endpoint: The disable_execute_api_endpoint of this CreateApiResponse.
        :type disable_execute_api_endpoint: bool
        """

        self._disable_execute_api_endpoint = disable_execute_api_endpoint

    @property
    def import_info(self):
        """Gets the import_info of this CreateApiResponse.


        :return: The import_info of this CreateApiResponse.
        :rtype: List
        """
        return self._import_info

    @import_info.setter
    def import_info(self, import_info):
        """Sets the import_info of this CreateApiResponse.


        :param import_info: The import_info of this CreateApiResponse.
        :type import_info: List
        """

        self._import_info = import_info

    @property
    def name(self):
        """Gets the name of this CreateApiResponse.


        :return: The name of this CreateApiResponse.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateApiResponse.


        :param name: The name of this CreateApiResponse.
        :type name: str
        """

        self._name = name

    @property
    def protocol_type(self):
        """Gets the protocol_type of this CreateApiResponse.


        :return: The protocol_type of this CreateApiResponse.
        :rtype: ProtocolType
        """
        return self._protocol_type

    @protocol_type.setter
    def protocol_type(self, protocol_type):
        """Sets the protocol_type of this CreateApiResponse.


        :param protocol_type: The protocol_type of this CreateApiResponse.
        :type protocol_type: ProtocolType
        """

        self._protocol_type = protocol_type

    @property
    def route_selection_expression(self):
        """Gets the route_selection_expression of this CreateApiResponse.


        :return: The route_selection_expression of this CreateApiResponse.
        :rtype: str
        """
        return self._route_selection_expression

    @route_selection_expression.setter
    def route_selection_expression(self, route_selection_expression):
        """Sets the route_selection_expression of this CreateApiResponse.


        :param route_selection_expression: The route_selection_expression of this CreateApiResponse.
        :type route_selection_expression: str
        """

        self._route_selection_expression = route_selection_expression

    @property
    def tags(self):
        """Gets the tags of this CreateApiResponse.


        :return: The tags of this CreateApiResponse.
        :rtype: Dict
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this CreateApiResponse.


        :param tags: The tags of this CreateApiResponse.
        :type tags: Dict
        """

        self._tags = tags

    @property
    def version(self):
        """Gets the version of this CreateApiResponse.


        :return: The version of this CreateApiResponse.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this CreateApiResponse.


        :param version: The version of this CreateApiResponse.
        :type version: str
        """

        self._version = version

    @property
    def warnings(self):
        """Gets the warnings of this CreateApiResponse.


        :return: The warnings of this CreateApiResponse.
        :rtype: List
        """
        return self._warnings

    @warnings.setter
    def warnings(self, warnings):
        """Sets the warnings of this CreateApiResponse.


        :param warnings: The warnings of this CreateApiResponse.
        :type warnings: List
        """

        self._warnings = warnings
