# coding: utf-8

# import models into model package
from openapi_server.models.google_cloud_recommender_v1_cost_projection import GoogleCloudRecommenderV1CostProjection
from openapi_server.models.google_cloud_recommender_v1_impact import GoogleCloudRecommenderV1Impact
from openapi_server.models.google_cloud_recommender_v1_insight import GoogleCloudRecommenderV1Insight
from openapi_server.models.google_cloud_recommender_v1_insight_recommendation_reference import GoogleCloudRecommenderV1InsightRecommendationReference
from openapi_server.models.google_cloud_recommender_v1_insight_state_info import GoogleCloudRecommenderV1InsightStateInfo
from openapi_server.models.google_cloud_recommender_v1_insight_type_config import GoogleCloudRecommenderV1InsightTypeConfig
from openapi_server.models.google_cloud_recommender_v1_insight_type_generation_config import GoogleCloudRecommenderV1InsightTypeGenerationConfig
from openapi_server.models.google_cloud_recommender_v1_list_insights_response import GoogleCloudRecommenderV1ListInsightsResponse
from openapi_server.models.google_cloud_recommender_v1_list_recommendations_response import GoogleCloudRecommenderV1ListRecommendationsResponse
from openapi_server.models.google_cloud_recommender_v1_mark_insight_accepted_request import GoogleCloudRecommenderV1MarkInsightAcceptedRequest
from openapi_server.models.google_cloud_recommender_v1_mark_recommendation_claimed_request import GoogleCloudRecommenderV1MarkRecommendationClaimedRequest
from openapi_server.models.google_cloud_recommender_v1_mark_recommendation_dismissed_request import GoogleCloudRecommenderV1MarkRecommendationDismissedRequest
from openapi_server.models.google_cloud_recommender_v1_mark_recommendation_failed_request import GoogleCloudRecommenderV1MarkRecommendationFailedRequest
from openapi_server.models.google_cloud_recommender_v1_mark_recommendation_succeeded_request import GoogleCloudRecommenderV1MarkRecommendationSucceededRequest
from openapi_server.models.google_cloud_recommender_v1_operation import GoogleCloudRecommenderV1Operation
from openapi_server.models.google_cloud_recommender_v1_operation_group import GoogleCloudRecommenderV1OperationGroup
from openapi_server.models.google_cloud_recommender_v1_recommendation import GoogleCloudRecommenderV1Recommendation
from openapi_server.models.google_cloud_recommender_v1_recommendation_content import GoogleCloudRecommenderV1RecommendationContent
from openapi_server.models.google_cloud_recommender_v1_recommendation_insight_reference import GoogleCloudRecommenderV1RecommendationInsightReference
from openapi_server.models.google_cloud_recommender_v1_recommendation_state_info import GoogleCloudRecommenderV1RecommendationStateInfo
from openapi_server.models.google_cloud_recommender_v1_recommender_config import GoogleCloudRecommenderV1RecommenderConfig
from openapi_server.models.google_cloud_recommender_v1_recommender_generation_config import GoogleCloudRecommenderV1RecommenderGenerationConfig
from openapi_server.models.google_cloud_recommender_v1_reliability_projection import GoogleCloudRecommenderV1ReliabilityProjection
from openapi_server.models.google_cloud_recommender_v1_security_projection import GoogleCloudRecommenderV1SecurityProjection
from openapi_server.models.google_cloud_recommender_v1_sustainability_projection import GoogleCloudRecommenderV1SustainabilityProjection
from openapi_server.models.google_cloud_recommender_v1_value_matcher import GoogleCloudRecommenderV1ValueMatcher
from openapi_server.models.google_type_money import GoogleTypeMoney
