# coding: utf-8

# import models into model package
from openapi_server.models.advertised_id import AdvertisedId
from openapi_server.models.attachment_info import AttachmentInfo
from openapi_server.models.beacon import Beacon
from openapi_server.models.beacon_attachment import BeaconAttachment
from openapi_server.models.beacon_info import BeaconInfo
from openapi_server.models.delete_attachments_response import DeleteAttachmentsResponse
from openapi_server.models.diagnostics import Diagnostics
from openapi_server.models.ephemeral_id_registration import EphemeralIdRegistration
from openapi_server.models.ephemeral_id_registration_params import EphemeralIdRegistrationParams
from openapi_server.models.get_info_for_observed_beacons_request import GetInfoForObservedBeaconsRequest
from openapi_server.models.get_info_for_observed_beacons_response import GetInfoForObservedBeaconsResponse
from openapi_server.models.indoor_level import IndoorLevel
from openapi_server.models.lat_lng import LatLng
from openapi_server.models.list_beacon_attachments_response import ListBeaconAttachmentsResponse
from openapi_server.models.list_beacons_response import ListBeaconsResponse
from openapi_server.models.list_diagnostics_response import ListDiagnosticsResponse
from openapi_server.models.list_namespaces_response import ListNamespacesResponse
from openapi_server.models.model_date import ModelDate
from openapi_server.models.namespace import Namespace
from openapi_server.models.observation import Observation
