# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.notification_relationships_resource_data import NotificationRelationshipsResourceData
from openapi_server import util


class NotificationRelationshipsResource(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: NotificationRelationshipsResourceData=None):
        """NotificationRelationshipsResource - a model defined in OpenAPI

        :param data: The data of this NotificationRelationshipsResource.
        """
        self.openapi_types = {
            'data': NotificationRelationshipsResourceData
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'NotificationRelationshipsResource':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Notification_relationships_resource of this NotificationRelationshipsResource.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this NotificationRelationshipsResource.


        :return: The data of this NotificationRelationshipsResource.
        :rtype: NotificationRelationshipsResourceData
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this NotificationRelationshipsResource.


        :param data: The data of this NotificationRelationshipsResource.
        :type data: NotificationRelationshipsResourceData
        """

        self._data = data
