QT += network

HEADERS += \
# Models
    $${PWD}/OAIAccelerator.h \
    $${PWD}/OAIAcceleratorAttributes.h \
    $${PWD}/OAIAcceleratorEvent.h \
    $${PWD}/OAIAcceleratorStatus.h \
    $${PWD}/OAIAddCustomRoutingEndpointsRequest.h \
    $${PWD}/OAIAddCustomRoutingEndpointsResponse.h \
    $${PWD}/OAIAddEndpointsRequest.h \
    $${PWD}/OAIAddEndpointsResponse.h \
    $${PWD}/OAIAdvertiseByoipCidrRequest.h \
    $${PWD}/OAIAdvertiseByoipCidrResponse.h \
    $${PWD}/OAIAdvertiseByoipCidrResponse_ByoipCidr.h \
    $${PWD}/OAIAllowCustomRoutingTrafficRequest.h \
    $${PWD}/OAIByoipCidr.h \
    $${PWD}/OAIByoipCidrEvent.h \
    $${PWD}/OAIByoipCidrState.h \
    $${PWD}/OAICidrAuthorizationContext.h \
    $${PWD}/OAIClientAffinity.h \
    $${PWD}/OAICreateAcceleratorRequest.h \
    $${PWD}/OAICreateAcceleratorResponse.h \
    $${PWD}/OAICreateAcceleratorResponse_Accelerator.h \
    $${PWD}/OAICreateCustomRoutingAcceleratorRequest.h \
    $${PWD}/OAICreateCustomRoutingAcceleratorResponse.h \
    $${PWD}/OAICreateCustomRoutingAcceleratorResponse_Accelerator.h \
    $${PWD}/OAICreateCustomRoutingEndpointGroupRequest.h \
    $${PWD}/OAICreateCustomRoutingEndpointGroupResponse.h \
    $${PWD}/OAICreateCustomRoutingEndpointGroupResponse_EndpointGroup.h \
    $${PWD}/OAICreateCustomRoutingListenerRequest.h \
    $${PWD}/OAICreateCustomRoutingListenerResponse.h \
    $${PWD}/OAICreateCustomRoutingListenerResponse_Listener.h \
    $${PWD}/OAICreateEndpointGroupRequest.h \
    $${PWD}/OAICreateEndpointGroupResponse.h \
    $${PWD}/OAICreateEndpointGroupResponse_EndpointGroup.h \
    $${PWD}/OAICreateListenerRequest.h \
    $${PWD}/OAICreateListenerResponse.h \
    $${PWD}/OAICreateListenerResponse_Listener.h \
    $${PWD}/OAICustomRoutingAccelerator.h \
    $${PWD}/OAICustomRoutingAcceleratorAttributes.h \
    $${PWD}/OAICustomRoutingAcceleratorStatus.h \
    $${PWD}/OAICustomRoutingDestinationConfiguration.h \
    $${PWD}/OAICustomRoutingDestinationDescription.h \
    $${PWD}/OAICustomRoutingDestinationTrafficState.h \
    $${PWD}/OAICustomRoutingEndpointConfiguration.h \
    $${PWD}/OAICustomRoutingEndpointDescription.h \
    $${PWD}/OAICustomRoutingEndpointGroup.h \
    $${PWD}/OAICustomRoutingListener.h \
    $${PWD}/OAICustomRoutingProtocol.h \
    $${PWD}/OAIDeleteAcceleratorRequest.h \
    $${PWD}/OAIDeleteCustomRoutingAcceleratorRequest.h \
    $${PWD}/OAIDeleteCustomRoutingEndpointGroupRequest.h \
    $${PWD}/OAIDeleteCustomRoutingListenerRequest.h \
    $${PWD}/OAIDeleteEndpointGroupRequest.h \
    $${PWD}/OAIDeleteListenerRequest.h \
    $${PWD}/OAIDenyCustomRoutingTrafficRequest.h \
    $${PWD}/OAIDeprovisionByoipCidrRequest.h \
    $${PWD}/OAIDeprovisionByoipCidrResponse.h \
    $${PWD}/OAIDescribeAcceleratorAttributesRequest.h \
    $${PWD}/OAIDescribeAcceleratorAttributesResponse.h \
    $${PWD}/OAIDescribeAcceleratorAttributesResponse_AcceleratorAttributes.h \
    $${PWD}/OAIDescribeAcceleratorRequest.h \
    $${PWD}/OAIDescribeAcceleratorResponse.h \
    $${PWD}/OAIDescribeAcceleratorResponse_Accelerator.h \
    $${PWD}/OAIDescribeCustomRoutingAcceleratorAttributesRequest.h \
    $${PWD}/OAIDescribeCustomRoutingAcceleratorAttributesResponse.h \
    $${PWD}/OAIDescribeCustomRoutingAcceleratorAttributesResponse_AcceleratorAttributes.h \
    $${PWD}/OAIDescribeCustomRoutingAcceleratorRequest.h \
    $${PWD}/OAIDescribeCustomRoutingAcceleratorResponse.h \
    $${PWD}/OAIDescribeCustomRoutingAcceleratorResponse_Accelerator.h \
    $${PWD}/OAIDescribeCustomRoutingEndpointGroupRequest.h \
    $${PWD}/OAIDescribeCustomRoutingEndpointGroupResponse.h \
    $${PWD}/OAIDescribeCustomRoutingEndpointGroupResponse_EndpointGroup.h \
    $${PWD}/OAIDescribeCustomRoutingListenerRequest.h \
    $${PWD}/OAIDescribeCustomRoutingListenerResponse.h \
    $${PWD}/OAIDescribeCustomRoutingListenerResponse_Listener.h \
    $${PWD}/OAIDescribeEndpointGroupRequest.h \
    $${PWD}/OAIDescribeEndpointGroupResponse.h \
    $${PWD}/OAIDescribeEndpointGroupResponse_EndpointGroup.h \
    $${PWD}/OAIDescribeListenerRequest.h \
    $${PWD}/OAIDescribeListenerResponse.h \
    $${PWD}/OAIDescribeListenerResponse_Listener.h \
    $${PWD}/OAIDestinationPortMapping.h \
    $${PWD}/OAIDestinationPortMapping_DestinationSocketAddress.h \
    $${PWD}/OAIEndpointConfiguration.h \
    $${PWD}/OAIEndpointDescription.h \
    $${PWD}/OAIEndpointGroup.h \
    $${PWD}/OAIEndpointIdentifier.h \
    $${PWD}/OAIHealthCheckProtocol.h \
    $${PWD}/OAIHealthState.h \
    $${PWD}/OAIIpAddressFamily.h \
    $${PWD}/OAIIpAddressType.h \
    $${PWD}/OAIIpSet.h \
    $${PWD}/OAIListAcceleratorsRequest.h \
    $${PWD}/OAIListAcceleratorsResponse.h \
    $${PWD}/OAIListByoipCidrsRequest.h \
    $${PWD}/OAIListByoipCidrsResponse.h \
    $${PWD}/OAIListCustomRoutingAcceleratorsRequest.h \
    $${PWD}/OAIListCustomRoutingAcceleratorsResponse.h \
    $${PWD}/OAIListCustomRoutingEndpointGroupsRequest.h \
    $${PWD}/OAIListCustomRoutingEndpointGroupsResponse.h \
    $${PWD}/OAIListCustomRoutingListenersRequest.h \
    $${PWD}/OAIListCustomRoutingListenersResponse.h \
    $${PWD}/OAIListCustomRoutingPortMappingsByDestinationRequest.h \
    $${PWD}/OAIListCustomRoutingPortMappingsByDestinationResponse.h \
    $${PWD}/OAIListCustomRoutingPortMappingsRequest.h \
    $${PWD}/OAIListCustomRoutingPortMappingsResponse.h \
    $${PWD}/OAIListEndpointGroupsRequest.h \
    $${PWD}/OAIListEndpointGroupsResponse.h \
    $${PWD}/OAIListListenersRequest.h \
    $${PWD}/OAIListListenersResponse.h \
    $${PWD}/OAIListTagsForResourceRequest.h \
    $${PWD}/OAIListTagsForResourceResponse.h \
    $${PWD}/OAIListener.h \
    $${PWD}/OAIPortMapping.h \
    $${PWD}/OAIPortMapping_DestinationSocketAddress.h \
    $${PWD}/OAIPortOverride.h \
    $${PWD}/OAIPortRange.h \
    $${PWD}/OAIProtocol.h \
    $${PWD}/OAIProvisionByoipCidrRequest.h \
    $${PWD}/OAIProvisionByoipCidrRequest_CidrAuthorizationContext.h \
    $${PWD}/OAIProvisionByoipCidrResponse.h \
    $${PWD}/OAIRemoveCustomRoutingEndpointsRequest.h \
    $${PWD}/OAIRemoveEndpointsRequest.h \
    $${PWD}/OAISocketAddress.h \
    $${PWD}/OAITag.h \
    $${PWD}/OAITagResourceRequest.h \
    $${PWD}/OAIUntagResourceRequest.h \
    $${PWD}/OAIUpdateAcceleratorAttributesRequest.h \
    $${PWD}/OAIUpdateAcceleratorAttributesResponse.h \
    $${PWD}/OAIUpdateAcceleratorAttributesResponse_AcceleratorAttributes.h \
    $${PWD}/OAIUpdateAcceleratorRequest.h \
    $${PWD}/OAIUpdateAcceleratorResponse.h \
    $${PWD}/OAIUpdateAcceleratorResponse_Accelerator.h \
    $${PWD}/OAIUpdateCustomRoutingAcceleratorAttributesRequest.h \
    $${PWD}/OAIUpdateCustomRoutingAcceleratorAttributesResponse.h \
    $${PWD}/OAIUpdateCustomRoutingAcceleratorAttributesResponse_AcceleratorAttributes.h \
    $${PWD}/OAIUpdateCustomRoutingAcceleratorRequest.h \
    $${PWD}/OAIUpdateCustomRoutingAcceleratorResponse.h \
    $${PWD}/OAIUpdateCustomRoutingAcceleratorResponse_Accelerator.h \
    $${PWD}/OAIUpdateCustomRoutingListenerRequest.h \
    $${PWD}/OAIUpdateCustomRoutingListenerResponse.h \
    $${PWD}/OAIUpdateCustomRoutingListenerResponse_Listener.h \
    $${PWD}/OAIUpdateEndpointGroupRequest.h \
    $${PWD}/OAIUpdateEndpointGroupResponse.h \
    $${PWD}/OAIUpdateEndpointGroupResponse_EndpointGroup.h \
    $${PWD}/OAIUpdateListenerRequest.h \
    $${PWD}/OAIUpdateListenerResponse.h \
    $${PWD}/OAIUpdateListenerResponse_Listener.h \
    $${PWD}/OAIWithdrawByoipCidrRequest.h \
    $${PWD}/OAIWithdrawByoipCidrResponse.h \
    $${PWD}/OAIWithdrawByoipCidrResponse_ByoipCidr.h \
# APIs
    $${PWD}/OAIDefaultApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAccelerator.cpp \
    $${PWD}/OAIAcceleratorAttributes.cpp \
    $${PWD}/OAIAcceleratorEvent.cpp \
    $${PWD}/OAIAcceleratorStatus.cpp \
    $${PWD}/OAIAddCustomRoutingEndpointsRequest.cpp \
    $${PWD}/OAIAddCustomRoutingEndpointsResponse.cpp \
    $${PWD}/OAIAddEndpointsRequest.cpp \
    $${PWD}/OAIAddEndpointsResponse.cpp \
    $${PWD}/OAIAdvertiseByoipCidrRequest.cpp \
    $${PWD}/OAIAdvertiseByoipCidrResponse.cpp \
    $${PWD}/OAIAdvertiseByoipCidrResponse_ByoipCidr.cpp \
    $${PWD}/OAIAllowCustomRoutingTrafficRequest.cpp \
    $${PWD}/OAIByoipCidr.cpp \
    $${PWD}/OAIByoipCidrEvent.cpp \
    $${PWD}/OAIByoipCidrState.cpp \
    $${PWD}/OAICidrAuthorizationContext.cpp \
    $${PWD}/OAIClientAffinity.cpp \
    $${PWD}/OAICreateAcceleratorRequest.cpp \
    $${PWD}/OAICreateAcceleratorResponse.cpp \
    $${PWD}/OAICreateAcceleratorResponse_Accelerator.cpp \
    $${PWD}/OAICreateCustomRoutingAcceleratorRequest.cpp \
    $${PWD}/OAICreateCustomRoutingAcceleratorResponse.cpp \
    $${PWD}/OAICreateCustomRoutingAcceleratorResponse_Accelerator.cpp \
    $${PWD}/OAICreateCustomRoutingEndpointGroupRequest.cpp \
    $${PWD}/OAICreateCustomRoutingEndpointGroupResponse.cpp \
    $${PWD}/OAICreateCustomRoutingEndpointGroupResponse_EndpointGroup.cpp \
    $${PWD}/OAICreateCustomRoutingListenerRequest.cpp \
    $${PWD}/OAICreateCustomRoutingListenerResponse.cpp \
    $${PWD}/OAICreateCustomRoutingListenerResponse_Listener.cpp \
    $${PWD}/OAICreateEndpointGroupRequest.cpp \
    $${PWD}/OAICreateEndpointGroupResponse.cpp \
    $${PWD}/OAICreateEndpointGroupResponse_EndpointGroup.cpp \
    $${PWD}/OAICreateListenerRequest.cpp \
    $${PWD}/OAICreateListenerResponse.cpp \
    $${PWD}/OAICreateListenerResponse_Listener.cpp \
    $${PWD}/OAICustomRoutingAccelerator.cpp \
    $${PWD}/OAICustomRoutingAcceleratorAttributes.cpp \
    $${PWD}/OAICustomRoutingAcceleratorStatus.cpp \
    $${PWD}/OAICustomRoutingDestinationConfiguration.cpp \
    $${PWD}/OAICustomRoutingDestinationDescription.cpp \
    $${PWD}/OAICustomRoutingDestinationTrafficState.cpp \
    $${PWD}/OAICustomRoutingEndpointConfiguration.cpp \
    $${PWD}/OAICustomRoutingEndpointDescription.cpp \
    $${PWD}/OAICustomRoutingEndpointGroup.cpp \
    $${PWD}/OAICustomRoutingListener.cpp \
    $${PWD}/OAICustomRoutingProtocol.cpp \
    $${PWD}/OAIDeleteAcceleratorRequest.cpp \
    $${PWD}/OAIDeleteCustomRoutingAcceleratorRequest.cpp \
    $${PWD}/OAIDeleteCustomRoutingEndpointGroupRequest.cpp \
    $${PWD}/OAIDeleteCustomRoutingListenerRequest.cpp \
    $${PWD}/OAIDeleteEndpointGroupRequest.cpp \
    $${PWD}/OAIDeleteListenerRequest.cpp \
    $${PWD}/OAIDenyCustomRoutingTrafficRequest.cpp \
    $${PWD}/OAIDeprovisionByoipCidrRequest.cpp \
    $${PWD}/OAIDeprovisionByoipCidrResponse.cpp \
    $${PWD}/OAIDescribeAcceleratorAttributesRequest.cpp \
    $${PWD}/OAIDescribeAcceleratorAttributesResponse.cpp \
    $${PWD}/OAIDescribeAcceleratorAttributesResponse_AcceleratorAttributes.cpp \
    $${PWD}/OAIDescribeAcceleratorRequest.cpp \
    $${PWD}/OAIDescribeAcceleratorResponse.cpp \
    $${PWD}/OAIDescribeAcceleratorResponse_Accelerator.cpp \
    $${PWD}/OAIDescribeCustomRoutingAcceleratorAttributesRequest.cpp \
    $${PWD}/OAIDescribeCustomRoutingAcceleratorAttributesResponse.cpp \
    $${PWD}/OAIDescribeCustomRoutingAcceleratorAttributesResponse_AcceleratorAttributes.cpp \
    $${PWD}/OAIDescribeCustomRoutingAcceleratorRequest.cpp \
    $${PWD}/OAIDescribeCustomRoutingAcceleratorResponse.cpp \
    $${PWD}/OAIDescribeCustomRoutingAcceleratorResponse_Accelerator.cpp \
    $${PWD}/OAIDescribeCustomRoutingEndpointGroupRequest.cpp \
    $${PWD}/OAIDescribeCustomRoutingEndpointGroupResponse.cpp \
    $${PWD}/OAIDescribeCustomRoutingEndpointGroupResponse_EndpointGroup.cpp \
    $${PWD}/OAIDescribeCustomRoutingListenerRequest.cpp \
    $${PWD}/OAIDescribeCustomRoutingListenerResponse.cpp \
    $${PWD}/OAIDescribeCustomRoutingListenerResponse_Listener.cpp \
    $${PWD}/OAIDescribeEndpointGroupRequest.cpp \
    $${PWD}/OAIDescribeEndpointGroupResponse.cpp \
    $${PWD}/OAIDescribeEndpointGroupResponse_EndpointGroup.cpp \
    $${PWD}/OAIDescribeListenerRequest.cpp \
    $${PWD}/OAIDescribeListenerResponse.cpp \
    $${PWD}/OAIDescribeListenerResponse_Listener.cpp \
    $${PWD}/OAIDestinationPortMapping.cpp \
    $${PWD}/OAIDestinationPortMapping_DestinationSocketAddress.cpp \
    $${PWD}/OAIEndpointConfiguration.cpp \
    $${PWD}/OAIEndpointDescription.cpp \
    $${PWD}/OAIEndpointGroup.cpp \
    $${PWD}/OAIEndpointIdentifier.cpp \
    $${PWD}/OAIHealthCheckProtocol.cpp \
    $${PWD}/OAIHealthState.cpp \
    $${PWD}/OAIIpAddressFamily.cpp \
    $${PWD}/OAIIpAddressType.cpp \
    $${PWD}/OAIIpSet.cpp \
    $${PWD}/OAIListAcceleratorsRequest.cpp \
    $${PWD}/OAIListAcceleratorsResponse.cpp \
    $${PWD}/OAIListByoipCidrsRequest.cpp \
    $${PWD}/OAIListByoipCidrsResponse.cpp \
    $${PWD}/OAIListCustomRoutingAcceleratorsRequest.cpp \
    $${PWD}/OAIListCustomRoutingAcceleratorsResponse.cpp \
    $${PWD}/OAIListCustomRoutingEndpointGroupsRequest.cpp \
    $${PWD}/OAIListCustomRoutingEndpointGroupsResponse.cpp \
    $${PWD}/OAIListCustomRoutingListenersRequest.cpp \
    $${PWD}/OAIListCustomRoutingListenersResponse.cpp \
    $${PWD}/OAIListCustomRoutingPortMappingsByDestinationRequest.cpp \
    $${PWD}/OAIListCustomRoutingPortMappingsByDestinationResponse.cpp \
    $${PWD}/OAIListCustomRoutingPortMappingsRequest.cpp \
    $${PWD}/OAIListCustomRoutingPortMappingsResponse.cpp \
    $${PWD}/OAIListEndpointGroupsRequest.cpp \
    $${PWD}/OAIListEndpointGroupsResponse.cpp \
    $${PWD}/OAIListListenersRequest.cpp \
    $${PWD}/OAIListListenersResponse.cpp \
    $${PWD}/OAIListTagsForResourceRequest.cpp \
    $${PWD}/OAIListTagsForResourceResponse.cpp \
    $${PWD}/OAIListener.cpp \
    $${PWD}/OAIPortMapping.cpp \
    $${PWD}/OAIPortMapping_DestinationSocketAddress.cpp \
    $${PWD}/OAIPortOverride.cpp \
    $${PWD}/OAIPortRange.cpp \
    $${PWD}/OAIProtocol.cpp \
    $${PWD}/OAIProvisionByoipCidrRequest.cpp \
    $${PWD}/OAIProvisionByoipCidrRequest_CidrAuthorizationContext.cpp \
    $${PWD}/OAIProvisionByoipCidrResponse.cpp \
    $${PWD}/OAIRemoveCustomRoutingEndpointsRequest.cpp \
    $${PWD}/OAIRemoveEndpointsRequest.cpp \
    $${PWD}/OAISocketAddress.cpp \
    $${PWD}/OAITag.cpp \
    $${PWD}/OAITagResourceRequest.cpp \
    $${PWD}/OAIUntagResourceRequest.cpp \
    $${PWD}/OAIUpdateAcceleratorAttributesRequest.cpp \
    $${PWD}/OAIUpdateAcceleratorAttributesResponse.cpp \
    $${PWD}/OAIUpdateAcceleratorAttributesResponse_AcceleratorAttributes.cpp \
    $${PWD}/OAIUpdateAcceleratorRequest.cpp \
    $${PWD}/OAIUpdateAcceleratorResponse.cpp \
    $${PWD}/OAIUpdateAcceleratorResponse_Accelerator.cpp \
    $${PWD}/OAIUpdateCustomRoutingAcceleratorAttributesRequest.cpp \
    $${PWD}/OAIUpdateCustomRoutingAcceleratorAttributesResponse.cpp \
    $${PWD}/OAIUpdateCustomRoutingAcceleratorAttributesResponse_AcceleratorAttributes.cpp \
    $${PWD}/OAIUpdateCustomRoutingAcceleratorRequest.cpp \
    $${PWD}/OAIUpdateCustomRoutingAcceleratorResponse.cpp \
    $${PWD}/OAIUpdateCustomRoutingAcceleratorResponse_Accelerator.cpp \
    $${PWD}/OAIUpdateCustomRoutingListenerRequest.cpp \
    $${PWD}/OAIUpdateCustomRoutingListenerResponse.cpp \
    $${PWD}/OAIUpdateCustomRoutingListenerResponse_Listener.cpp \
    $${PWD}/OAIUpdateEndpointGroupRequest.cpp \
    $${PWD}/OAIUpdateEndpointGroupResponse.cpp \
    $${PWD}/OAIUpdateEndpointGroupResponse_EndpointGroup.cpp \
    $${PWD}/OAIUpdateListenerRequest.cpp \
    $${PWD}/OAIUpdateListenerResponse.cpp \
    $${PWD}/OAIUpdateListenerResponse_Listener.cpp \
    $${PWD}/OAIWithdrawByoipCidrRequest.cpp \
    $${PWD}/OAIWithdrawByoipCidrResponse.cpp \
    $${PWD}/OAIWithdrawByoipCidrResponse_ByoipCidr.cpp \
# APIs
    $${PWD}/OAIDefaultApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
