openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: "Display & Video 360 API allows users to automate complex Display &\
    \ Video 360 workflows, such as creating insertion orders and setting targeting\
    \ options for individual line items."
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Display & Video 360 API
  version: v4
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
  x-origin:
  - format: google
    url: https://displayvideo.googleapis.com/$discovery/rest?version=v4
    version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: displayvideo
servers:
- url: https://displayvideo.googleapis.com/
tags:
- name: media
- name: sdfdownloadtasks
paths:
  /download/{resourceName}:
    get:
      description: "Downloads media. Download is supported on the URI `/download/{resource_name=**}?alt=media.`\
        \ **Note**: Download requests will not be successful without including `alt=media`\
        \ query string."
      operationId: displayvideo.media.download
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      - Oauth2:
        - https://www.googleapis.com/auth/doubleclickbidmanager
        Oauth2c:
        - https://www.googleapis.com/auth/doubleclickbidmanager
      tags:
      - media
      x-accepts:
      - application/json
  /media/{resourceName}:
    post:
      description: "Uploads media. Upload is supported on the URI `/upload/media/{resource_name=**}?upload_type=media.`\
        \ **Note**: Upload requests will not be successful without including `upload_type=media`\
        \ query string."
      operationId: displayvideo.media.upload
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      - Oauth2:
        - https://www.googleapis.com/auth/doubleclickbidmanager
        Oauth2c:
        - https://www.googleapis.com/auth/doubleclickbidmanager
      tags:
      - media
      x-content-type: application/octet-stream
      x-accepts:
      - application/json
  /v4/{name}:
    get:
      description: Gets the latest state of an asynchronous SDF download task operation.
        Clients should poll this method at intervals of 30 seconds.
      operationId: displayvideo.sdfdownloadtasks.operations.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      - Oauth2:
        - https://www.googleapis.com/auth/doubleclickbidmanager
        Oauth2c:
        - https://www.googleapis.com/auth/doubleclickbidmanager
      tags:
      - sdfdownloadtasks
      x-accepts:
      - application/json
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/display-video: "Create, see, edit, and\
              \ permanently delete your Display & Video 360 entities and reports"
            https://www.googleapis.com/auth/doubleclickbidmanager: View and manage
              your reports in DoubleClick Bid Manager
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/display-video: "Create, see, edit, and\
              \ permanently delete your Display & Video 360 entities and reports"
            https://www.googleapis.com/auth/doubleclickbidmanager: View and manage
              your reports in DoubleClick Bid Manager
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2

