/**
 * Amazon SageMaker Service
 * <p>Provides APIs for creating and managing SageMaker resources. </p> <p>Other Resources:</p> <ul> <li> <p> <a href=\"https://docs.aws.amazon.com/sagemaker/latest/dg/whatis.html#first-time-user\">SageMaker Developer Guide</a> </p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/augmented-ai/2019-11-07/APIReference/Welcome.html\">Amazon Augmented AI Runtime API Reference</a> </p> </li> </ul>
 *
 * The version of the OpenAPI document: 2017-07-24
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAICreateMonitoringScheduleResponse.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAICreateMonitoringScheduleResponse::OAICreateMonitoringScheduleResponse(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAICreateMonitoringScheduleResponse::OAICreateMonitoringScheduleResponse() {
    this->initializeModel();
}

OAICreateMonitoringScheduleResponse::~OAICreateMonitoringScheduleResponse() {}

void OAICreateMonitoringScheduleResponse::initializeModel() {

    m_monitoring_schedule_arn_isSet = false;
    m_monitoring_schedule_arn_isValid = false;
}

void OAICreateMonitoringScheduleResponse::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAICreateMonitoringScheduleResponse::fromJsonObject(QJsonObject json) {

    m_monitoring_schedule_arn_isValid = ::OpenAPI::fromJsonValue(m_monitoring_schedule_arn, json[QString("MonitoringScheduleArn")]);
    m_monitoring_schedule_arn_isSet = !json[QString("MonitoringScheduleArn")].isNull() && m_monitoring_schedule_arn_isValid;
}

QString OAICreateMonitoringScheduleResponse::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAICreateMonitoringScheduleResponse::asJsonObject() const {
    QJsonObject obj;
    if (m_monitoring_schedule_arn_isSet) {
        obj.insert(QString("MonitoringScheduleArn"), ::OpenAPI::toJsonValue(m_monitoring_schedule_arn));
    }
    return obj;
}

QString OAICreateMonitoringScheduleResponse::getMonitoringScheduleArn() const {
    return m_monitoring_schedule_arn;
}
void OAICreateMonitoringScheduleResponse::setMonitoringScheduleArn(const QString &monitoring_schedule_arn) {
    m_monitoring_schedule_arn = monitoring_schedule_arn;
    m_monitoring_schedule_arn_isSet = true;
}

bool OAICreateMonitoringScheduleResponse::is_monitoring_schedule_arn_Set() const{
    return m_monitoring_schedule_arn_isSet;
}

bool OAICreateMonitoringScheduleResponse::is_monitoring_schedule_arn_Valid() const{
    return m_monitoring_schedule_arn_isValid;
}

bool OAICreateMonitoringScheduleResponse::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_monitoring_schedule_arn_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAICreateMonitoringScheduleResponse::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_monitoring_schedule_arn_isValid && true;
}

} // namespace OpenAPI
