QT += network

HEADERS += \
# Models
    $${PWD}/OAIAddApplicationCloudWatchLoggingOptionRequest.h \
    $${PWD}/OAIAddApplicationCloudWatchLoggingOptionRequest_CloudWatchLoggingOption.h \
    $${PWD}/OAIAddApplicationInputProcessingConfigurationRequest.h \
    $${PWD}/OAIAddApplicationInputProcessingConfigurationRequest_InputProcessingConfiguration.h \
    $${PWD}/OAIAddApplicationInputRequest.h \
    $${PWD}/OAIAddApplicationInputRequest_Input.h \
    $${PWD}/OAIAddApplicationOutputRequest.h \
    $${PWD}/OAIAddApplicationOutputRequest_Output.h \
    $${PWD}/OAIAddApplicationReferenceDataSourceRequest.h \
    $${PWD}/OAIAddApplicationReferenceDataSourceRequest_ReferenceDataSource.h \
    $${PWD}/OAIApplicationDetail.h \
    $${PWD}/OAIApplicationStatus.h \
    $${PWD}/OAIApplicationSummary.h \
    $${PWD}/OAIApplicationUpdate.h \
    $${PWD}/OAICSVMappingParameters.h \
    $${PWD}/OAICloudWatchLoggingOption.h \
    $${PWD}/OAICloudWatchLoggingOptionDescription.h \
    $${PWD}/OAICloudWatchLoggingOptionUpdate.h \
    $${PWD}/OAICreateApplicationRequest.h \
    $${PWD}/OAICreateApplicationResponse.h \
    $${PWD}/OAICreateApplicationResponse_ApplicationSummary.h \
    $${PWD}/OAIDeleteApplicationCloudWatchLoggingOptionRequest.h \
    $${PWD}/OAIDeleteApplicationInputProcessingConfigurationRequest.h \
    $${PWD}/OAIDeleteApplicationOutputRequest.h \
    $${PWD}/OAIDeleteApplicationReferenceDataSourceRequest.h \
    $${PWD}/OAIDeleteApplicationRequest.h \
    $${PWD}/OAIDescribeApplicationRequest.h \
    $${PWD}/OAIDescribeApplicationResponse.h \
    $${PWD}/OAIDescribeApplicationResponse_ApplicationDetail.h \
    $${PWD}/OAIDestinationSchema.h \
    $${PWD}/OAIDiscoverInputSchemaRequest.h \
    $${PWD}/OAIDiscoverInputSchemaRequest_InputProcessingConfiguration.h \
    $${PWD}/OAIDiscoverInputSchemaRequest_InputStartingPositionConfiguration.h \
    $${PWD}/OAIDiscoverInputSchemaRequest_S3Configuration.h \
    $${PWD}/OAIDiscoverInputSchemaResponse.h \
    $${PWD}/OAIDiscoverInputSchemaResponse_InputSchema.h \
    $${PWD}/OAIInput.h \
    $${PWD}/OAIInputConfiguration.h \
    $${PWD}/OAIInputConfiguration_InputStartingPositionConfiguration.h \
    $${PWD}/OAIInputDescription.h \
    $${PWD}/OAIInputDescription_InputParallelism.h \
    $${PWD}/OAIInputDescription_InputProcessingConfigurationDescription.h \
    $${PWD}/OAIInputDescription_InputSchema.h \
    $${PWD}/OAIInputDescription_InputStartingPositionConfiguration.h \
    $${PWD}/OAIInputDescription_KinesisFirehoseInputDescription.h \
    $${PWD}/OAIInputDescription_KinesisStreamsInputDescription.h \
    $${PWD}/OAIInputLambdaProcessor.h \
    $${PWD}/OAIInputLambdaProcessorDescription.h \
    $${PWD}/OAIInputLambdaProcessorUpdate.h \
    $${PWD}/OAIInputParallelism.h \
    $${PWD}/OAIInputParallelismUpdate.h \
    $${PWD}/OAIInputProcessingConfiguration.h \
    $${PWD}/OAIInputProcessingConfigurationDescription.h \
    $${PWD}/OAIInputProcessingConfigurationDescription_InputLambdaProcessorDescription.h \
    $${PWD}/OAIInputProcessingConfigurationUpdate.h \
    $${PWD}/OAIInputProcessingConfigurationUpdate_InputLambdaProcessorUpdate.h \
    $${PWD}/OAIInputProcessingConfiguration_InputLambdaProcessor.h \
    $${PWD}/OAIInputSchemaUpdate.h \
    $${PWD}/OAIInputStartingPosition.h \
    $${PWD}/OAIInputStartingPositionConfiguration.h \
    $${PWD}/OAIInputUpdate.h \
    $${PWD}/OAIInputUpdate_InputParallelismUpdate.h \
    $${PWD}/OAIInputUpdate_InputProcessingConfigurationUpdate.h \
    $${PWD}/OAIInputUpdate_InputSchemaUpdate.h \
    $${PWD}/OAIInputUpdate_KinesisFirehoseInputUpdate.h \
    $${PWD}/OAIInputUpdate_KinesisStreamsInputUpdate.h \
    $${PWD}/OAIInput_InputParallelism.h \
    $${PWD}/OAIInput_InputProcessingConfiguration.h \
    $${PWD}/OAIInput_InputSchema.h \
    $${PWD}/OAIInput_KinesisFirehoseInput.h \
    $${PWD}/OAIInput_KinesisStreamsInput.h \
    $${PWD}/OAIJSONMappingParameters.h \
    $${PWD}/OAIKinesisFirehoseInput.h \
    $${PWD}/OAIKinesisFirehoseInputDescription.h \
    $${PWD}/OAIKinesisFirehoseInputUpdate.h \
    $${PWD}/OAIKinesisFirehoseOutput.h \
    $${PWD}/OAIKinesisFirehoseOutputDescription.h \
    $${PWD}/OAIKinesisFirehoseOutputUpdate.h \
    $${PWD}/OAIKinesisStreamsInput.h \
    $${PWD}/OAIKinesisStreamsInputDescription.h \
    $${PWD}/OAIKinesisStreamsInputUpdate.h \
    $${PWD}/OAIKinesisStreamsOutput.h \
    $${PWD}/OAIKinesisStreamsOutputDescription.h \
    $${PWD}/OAIKinesisStreamsOutputUpdate.h \
    $${PWD}/OAILambdaOutput.h \
    $${PWD}/OAILambdaOutputDescription.h \
    $${PWD}/OAILambdaOutputUpdate.h \
    $${PWD}/OAIListApplicationsRequest.h \
    $${PWD}/OAIListApplicationsResponse.h \
    $${PWD}/OAIListTagsForResourceRequest.h \
    $${PWD}/OAIListTagsForResourceResponse.h \
    $${PWD}/OAIMappingParameters.h \
    $${PWD}/OAIMappingParameters_CSVMappingParameters.h \
    $${PWD}/OAIMappingParameters_JSONMappingParameters.h \
    $${PWD}/OAIOutput.h \
    $${PWD}/OAIOutputDescription.h \
    $${PWD}/OAIOutputDescription_DestinationSchema.h \
    $${PWD}/OAIOutputDescription_KinesisFirehoseOutputDescription.h \
    $${PWD}/OAIOutputDescription_KinesisStreamsOutputDescription.h \
    $${PWD}/OAIOutputDescription_LambdaOutputDescription.h \
    $${PWD}/OAIOutputUpdate.h \
    $${PWD}/OAIOutputUpdate_KinesisFirehoseOutputUpdate.h \
    $${PWD}/OAIOutputUpdate_KinesisStreamsOutputUpdate.h \
    $${PWD}/OAIOutputUpdate_LambdaOutputUpdate.h \
    $${PWD}/OAIOutput_DestinationSchema.h \
    $${PWD}/OAIOutput_KinesisFirehoseOutput.h \
    $${PWD}/OAIOutput_KinesisStreamsOutput.h \
    $${PWD}/OAIOutput_LambdaOutput.h \
    $${PWD}/OAIRecordColumn.h \
    $${PWD}/OAIRecordFormat.h \
    $${PWD}/OAIRecordFormatType.h \
    $${PWD}/OAIRecordFormat_MappingParameters.h \
    $${PWD}/OAIReferenceDataSource.h \
    $${PWD}/OAIReferenceDataSourceDescription.h \
    $${PWD}/OAIReferenceDataSourceDescription_S3ReferenceDataSourceDescription.h \
    $${PWD}/OAIReferenceDataSourceUpdate.h \
    $${PWD}/OAIReferenceDataSourceUpdate_ReferenceSchemaUpdate.h \
    $${PWD}/OAIReferenceDataSourceUpdate_S3ReferenceDataSourceUpdate.h \
    $${PWD}/OAIReferenceDataSource_ReferenceSchema.h \
    $${PWD}/OAIReferenceDataSource_S3ReferenceDataSource.h \
    $${PWD}/OAIS3Configuration.h \
    $${PWD}/OAIS3ReferenceDataSource.h \
    $${PWD}/OAIS3ReferenceDataSourceDescription.h \
    $${PWD}/OAIS3ReferenceDataSourceUpdate.h \
    $${PWD}/OAISourceSchema.h \
    $${PWD}/OAISourceSchema_RecordFormat.h \
    $${PWD}/OAIStartApplicationRequest.h \
    $${PWD}/OAIStopApplicationRequest.h \
    $${PWD}/OAITag.h \
    $${PWD}/OAITagResourceRequest.h \
    $${PWD}/OAIUntagResourceRequest.h \
    $${PWD}/OAIUpdateApplicationRequest.h \
    $${PWD}/OAIUpdateApplicationRequest_ApplicationUpdate.h \
# APIs
    $${PWD}/OAIDefaultApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAddApplicationCloudWatchLoggingOptionRequest.cpp \
    $${PWD}/OAIAddApplicationCloudWatchLoggingOptionRequest_CloudWatchLoggingOption.cpp \
    $${PWD}/OAIAddApplicationInputProcessingConfigurationRequest.cpp \
    $${PWD}/OAIAddApplicationInputProcessingConfigurationRequest_InputProcessingConfiguration.cpp \
    $${PWD}/OAIAddApplicationInputRequest.cpp \
    $${PWD}/OAIAddApplicationInputRequest_Input.cpp \
    $${PWD}/OAIAddApplicationOutputRequest.cpp \
    $${PWD}/OAIAddApplicationOutputRequest_Output.cpp \
    $${PWD}/OAIAddApplicationReferenceDataSourceRequest.cpp \
    $${PWD}/OAIAddApplicationReferenceDataSourceRequest_ReferenceDataSource.cpp \
    $${PWD}/OAIApplicationDetail.cpp \
    $${PWD}/OAIApplicationStatus.cpp \
    $${PWD}/OAIApplicationSummary.cpp \
    $${PWD}/OAIApplicationUpdate.cpp \
    $${PWD}/OAICSVMappingParameters.cpp \
    $${PWD}/OAICloudWatchLoggingOption.cpp \
    $${PWD}/OAICloudWatchLoggingOptionDescription.cpp \
    $${PWD}/OAICloudWatchLoggingOptionUpdate.cpp \
    $${PWD}/OAICreateApplicationRequest.cpp \
    $${PWD}/OAICreateApplicationResponse.cpp \
    $${PWD}/OAICreateApplicationResponse_ApplicationSummary.cpp \
    $${PWD}/OAIDeleteApplicationCloudWatchLoggingOptionRequest.cpp \
    $${PWD}/OAIDeleteApplicationInputProcessingConfigurationRequest.cpp \
    $${PWD}/OAIDeleteApplicationOutputRequest.cpp \
    $${PWD}/OAIDeleteApplicationReferenceDataSourceRequest.cpp \
    $${PWD}/OAIDeleteApplicationRequest.cpp \
    $${PWD}/OAIDescribeApplicationRequest.cpp \
    $${PWD}/OAIDescribeApplicationResponse.cpp \
    $${PWD}/OAIDescribeApplicationResponse_ApplicationDetail.cpp \
    $${PWD}/OAIDestinationSchema.cpp \
    $${PWD}/OAIDiscoverInputSchemaRequest.cpp \
    $${PWD}/OAIDiscoverInputSchemaRequest_InputProcessingConfiguration.cpp \
    $${PWD}/OAIDiscoverInputSchemaRequest_InputStartingPositionConfiguration.cpp \
    $${PWD}/OAIDiscoverInputSchemaRequest_S3Configuration.cpp \
    $${PWD}/OAIDiscoverInputSchemaResponse.cpp \
    $${PWD}/OAIDiscoverInputSchemaResponse_InputSchema.cpp \
    $${PWD}/OAIInput.cpp \
    $${PWD}/OAIInputConfiguration.cpp \
    $${PWD}/OAIInputConfiguration_InputStartingPositionConfiguration.cpp \
    $${PWD}/OAIInputDescription.cpp \
    $${PWD}/OAIInputDescription_InputParallelism.cpp \
    $${PWD}/OAIInputDescription_InputProcessingConfigurationDescription.cpp \
    $${PWD}/OAIInputDescription_InputSchema.cpp \
    $${PWD}/OAIInputDescription_InputStartingPositionConfiguration.cpp \
    $${PWD}/OAIInputDescription_KinesisFirehoseInputDescription.cpp \
    $${PWD}/OAIInputDescription_KinesisStreamsInputDescription.cpp \
    $${PWD}/OAIInputLambdaProcessor.cpp \
    $${PWD}/OAIInputLambdaProcessorDescription.cpp \
    $${PWD}/OAIInputLambdaProcessorUpdate.cpp \
    $${PWD}/OAIInputParallelism.cpp \
    $${PWD}/OAIInputParallelismUpdate.cpp \
    $${PWD}/OAIInputProcessingConfiguration.cpp \
    $${PWD}/OAIInputProcessingConfigurationDescription.cpp \
    $${PWD}/OAIInputProcessingConfigurationDescription_InputLambdaProcessorDescription.cpp \
    $${PWD}/OAIInputProcessingConfigurationUpdate.cpp \
    $${PWD}/OAIInputProcessingConfigurationUpdate_InputLambdaProcessorUpdate.cpp \
    $${PWD}/OAIInputProcessingConfiguration_InputLambdaProcessor.cpp \
    $${PWD}/OAIInputSchemaUpdate.cpp \
    $${PWD}/OAIInputStartingPosition.cpp \
    $${PWD}/OAIInputStartingPositionConfiguration.cpp \
    $${PWD}/OAIInputUpdate.cpp \
    $${PWD}/OAIInputUpdate_InputParallelismUpdate.cpp \
    $${PWD}/OAIInputUpdate_InputProcessingConfigurationUpdate.cpp \
    $${PWD}/OAIInputUpdate_InputSchemaUpdate.cpp \
    $${PWD}/OAIInputUpdate_KinesisFirehoseInputUpdate.cpp \
    $${PWD}/OAIInputUpdate_KinesisStreamsInputUpdate.cpp \
    $${PWD}/OAIInput_InputParallelism.cpp \
    $${PWD}/OAIInput_InputProcessingConfiguration.cpp \
    $${PWD}/OAIInput_InputSchema.cpp \
    $${PWD}/OAIInput_KinesisFirehoseInput.cpp \
    $${PWD}/OAIInput_KinesisStreamsInput.cpp \
    $${PWD}/OAIJSONMappingParameters.cpp \
    $${PWD}/OAIKinesisFirehoseInput.cpp \
    $${PWD}/OAIKinesisFirehoseInputDescription.cpp \
    $${PWD}/OAIKinesisFirehoseInputUpdate.cpp \
    $${PWD}/OAIKinesisFirehoseOutput.cpp \
    $${PWD}/OAIKinesisFirehoseOutputDescription.cpp \
    $${PWD}/OAIKinesisFirehoseOutputUpdate.cpp \
    $${PWD}/OAIKinesisStreamsInput.cpp \
    $${PWD}/OAIKinesisStreamsInputDescription.cpp \
    $${PWD}/OAIKinesisStreamsInputUpdate.cpp \
    $${PWD}/OAIKinesisStreamsOutput.cpp \
    $${PWD}/OAIKinesisStreamsOutputDescription.cpp \
    $${PWD}/OAIKinesisStreamsOutputUpdate.cpp \
    $${PWD}/OAILambdaOutput.cpp \
    $${PWD}/OAILambdaOutputDescription.cpp \
    $${PWD}/OAILambdaOutputUpdate.cpp \
    $${PWD}/OAIListApplicationsRequest.cpp \
    $${PWD}/OAIListApplicationsResponse.cpp \
    $${PWD}/OAIListTagsForResourceRequest.cpp \
    $${PWD}/OAIListTagsForResourceResponse.cpp \
    $${PWD}/OAIMappingParameters.cpp \
    $${PWD}/OAIMappingParameters_CSVMappingParameters.cpp \
    $${PWD}/OAIMappingParameters_JSONMappingParameters.cpp \
    $${PWD}/OAIOutput.cpp \
    $${PWD}/OAIOutputDescription.cpp \
    $${PWD}/OAIOutputDescription_DestinationSchema.cpp \
    $${PWD}/OAIOutputDescription_KinesisFirehoseOutputDescription.cpp \
    $${PWD}/OAIOutputDescription_KinesisStreamsOutputDescription.cpp \
    $${PWD}/OAIOutputDescription_LambdaOutputDescription.cpp \
    $${PWD}/OAIOutputUpdate.cpp \
    $${PWD}/OAIOutputUpdate_KinesisFirehoseOutputUpdate.cpp \
    $${PWD}/OAIOutputUpdate_KinesisStreamsOutputUpdate.cpp \
    $${PWD}/OAIOutputUpdate_LambdaOutputUpdate.cpp \
    $${PWD}/OAIOutput_DestinationSchema.cpp \
    $${PWD}/OAIOutput_KinesisFirehoseOutput.cpp \
    $${PWD}/OAIOutput_KinesisStreamsOutput.cpp \
    $${PWD}/OAIOutput_LambdaOutput.cpp \
    $${PWD}/OAIRecordColumn.cpp \
    $${PWD}/OAIRecordFormat.cpp \
    $${PWD}/OAIRecordFormatType.cpp \
    $${PWD}/OAIRecordFormat_MappingParameters.cpp \
    $${PWD}/OAIReferenceDataSource.cpp \
    $${PWD}/OAIReferenceDataSourceDescription.cpp \
    $${PWD}/OAIReferenceDataSourceDescription_S3ReferenceDataSourceDescription.cpp \
    $${PWD}/OAIReferenceDataSourceUpdate.cpp \
    $${PWD}/OAIReferenceDataSourceUpdate_ReferenceSchemaUpdate.cpp \
    $${PWD}/OAIReferenceDataSourceUpdate_S3ReferenceDataSourceUpdate.cpp \
    $${PWD}/OAIReferenceDataSource_ReferenceSchema.cpp \
    $${PWD}/OAIReferenceDataSource_S3ReferenceDataSource.cpp \
    $${PWD}/OAIS3Configuration.cpp \
    $${PWD}/OAIS3ReferenceDataSource.cpp \
    $${PWD}/OAIS3ReferenceDataSourceDescription.cpp \
    $${PWD}/OAIS3ReferenceDataSourceUpdate.cpp \
    $${PWD}/OAISourceSchema.cpp \
    $${PWD}/OAISourceSchema_RecordFormat.cpp \
    $${PWD}/OAIStartApplicationRequest.cpp \
    $${PWD}/OAIStopApplicationRequest.cpp \
    $${PWD}/OAITag.cpp \
    $${PWD}/OAITagResourceRequest.cpp \
    $${PWD}/OAIUntagResourceRequest.cpp \
    $${PWD}/OAIUpdateApplicationRequest.cpp \
    $${PWD}/OAIUpdateApplicationRequest_ApplicationUpdate.cpp \
# APIs
    $${PWD}/OAIDefaultApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
