openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: Schedules reporting jobs containing your YouTube Analytics data and
    downloads the resulting bulk data reports in the form of CSV files.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: YouTube Reporting API
  version: v1
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
  x-origin:
  - converter:
      url: https://github.com/mermade/oas-kit
      version: 7.0.4
    format: google
    url: https://youtubereporting.googleapis.com/$discovery/rest?version=v1
    version: v1
  x-providerName: googleapis.com
  x-serviceName: youtubereporting
servers:
- url: https://youtubereporting.googleapis.com/
tags:
- name: jobs
- name: media
- name: reportTypes
paths:
  /v1/jobs:
    get:
      description: Lists jobs.
      operationId: youtubereporting.jobs.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/yt-analytics.readonly
      tags:
      - jobs
      x-accepts:
      - application/json
    post:
      description: Creates a job and returns it.
      operationId: youtubereporting.jobs.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/yt-analytics.readonly
      tags:
      - jobs
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/jobs/{jobId}:
    delete:
      description: Deletes a job.
      operationId: youtubereporting.jobs.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/yt-analytics.readonly
      tags:
      - jobs
      x-accepts:
      - application/json
    get:
      description: Gets a job.
      operationId: youtubereporting.jobs.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/yt-analytics.readonly
      tags:
      - jobs
      x-accepts:
      - application/json
  /v1/jobs/{jobId}/reports:
    get:
      description: Lists reports created by a specific job. Returns NOT_FOUND if the
        job does not exist.
      operationId: youtubereporting.jobs.reports.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/yt-analytics.readonly
      tags:
      - jobs
      x-accepts:
      - application/json
  /v1/jobs/{jobId}/reports/{reportId}:
    get:
      description: Gets the metadata of a specific report.
      operationId: youtubereporting.jobs.reports.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/yt-analytics.readonly
      tags:
      - jobs
      x-accepts:
      - application/json
  /v1/media/{resourceName}:
    get:
      description: "Method for media download. Download is supported on the URI `/v1/media/{+name}?alt=media`."
      operationId: youtubereporting.media.download
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/yt-analytics.readonly
      tags:
      - media
      x-accepts:
      - application/json
  /v1/reportTypes:
    get:
      description: Lists report types.
      operationId: youtubereporting.reportTypes.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/yt-analytics.readonly
      tags:
      - reportTypes
      x-accepts:
      - application/json
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/yt-analytics-monetary.readonly: View monetary
              and non-monetary YouTube Analytics reports for your YouTube content
            https://www.googleapis.com/auth/yt-analytics.readonly: View YouTube Analytics
              reports for your YouTube content
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/yt-analytics-monetary.readonly: View monetary
              and non-monetary YouTube Analytics reports for your YouTube content
            https://www.googleapis.com/auth/yt-analytics.readonly: View YouTube Analytics
              reports for your YouTube content
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2

