QT += network

HEADERS += \
# Models
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_AdditionalFeeApiModel.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_ArticleApiCustomFieldDefinitionModel.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_ArticleApiCustomFieldValueModel.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_ArticleApiModel.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_ArticleCategoryApiModel.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_ArticleImageRelationApiModel.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_ArticleSourceApiModel.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_BomSubArticleApiModel.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_CloudStorageApiModel.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_CommentApiModel.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_CreateCustomerApiModel.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_CreateShipmentApiModel.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_CustomerAddressApiModel.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_CustomerApiModel.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_DeletedImagesModel.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_GetReservedAmountResponseData.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_InvoiceApiModel.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_InvoiceApiPositionApiModel.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_Order.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_OrderAddressApiModel.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_OrderItem.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_OrderItemAttribute.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_OrderUser.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_ProductImage.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_Shipment.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_ShipmentAddressApiModel.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_SoldProduct.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_StockArticleApiModel.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_StockResponseData.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_UpdateStockApiModel.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_UpdateStockCodeApiModel.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_UpdateStockResponseData.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Models_CustomerMetaDataApiModel.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Models_LayoutTemplate.h \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Models_OrderPayment.h \
    $${PWD}/OAIBillbee_Interfaces_Order_HistoryEntry.h \
    $${PWD}/OAIBillbee_Interfaces_Order_MultiLanguageString.h \
    $${PWD}/OAIBillbee_Interfaces_Order_VatDetailsRecognizedHistoryEntry_VatDetectionFlags.h \
    $${PWD}/OAIBillbee_Interfaces_Shipping_ProductService.h \
    $${PWD}/OAIBillbee_Interfaces_Shipping_ShipmentData_Dimensions.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiAddShipmentToOrderModel.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_PagingInformation_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_ArticleApiCustomFieldDefinitionModel_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_PagingInformation_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_ArticleApiModel_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_PagingInformation_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_CustomerAddressApiModel_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_PagingInformation_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_CustomerApiModel_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_PagingInformation_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_InvoiceApiModel_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_PagingInformation_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_Order_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_PagingInformation_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_Shipment_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_PagingInformation_System_Collections_Generic_List_Rechnungsdruck_WebApp_Controllers_Api_Order_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_ArticleApiCustomFieldDefinitionModel_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_ArticleApiModel_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_CustomerAddressApiModel_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_CustomerApiModel_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_InvoiceApiModel_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_Order_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_Shipment_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_System_Collections_Generic_List_Rechnungsdruck_WebApp_Controllers_Api_Order_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_Billbee_Interfaces_BillbeeAPI_Model_ArticleApiCustomFieldDefinitionModel_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_Billbee_Interfaces_BillbeeAPI_Model_ArticleApiModel_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_Billbee_Interfaces_BillbeeAPI_Model_ArticleImageRelationApiModel_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_Billbee_Interfaces_BillbeeAPI_Model_CustomerAddressApiModel_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_Billbee_Interfaces_BillbeeAPI_Model_CustomerApiModel_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_Billbee_Interfaces_BillbeeAPI_Model_DeletedImagesModel_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_Billbee_Interfaces_BillbeeAPI_Model_GetReservedAmountResponseData_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_Billbee_Interfaces_BillbeeAPI_Model_Order_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_Billbee_Interfaces_BillbeeAPI_Model_UpdateStockCodeResponseData_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_Billbee_Interfaces_BillbeeAPI_Model_UpdateStockResponseData_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_Rechnungsdruck_WebApp_Controllers_Api_Invoice_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_Rechnungsdruck_WebApp_Controllers_Api_SearchController_SearchResultsModel_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_Rechnungsdruck_WebApp_Controllers_Api_ShipmentWithLabelResult_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_ArticleImageRelationApiModel_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_CloudStorageApiModel_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_StockResponseData_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Models_LayoutTemplate_.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_AutomaticProvisioningController_CreateAccountContainer.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_AutomaticProvisioningController_CreateAccountContainer_UserAddress.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_Invoice.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_Order.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_OrderApiController_ParseTextContainer.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_OrderApiController_SendMessageModel.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_OrderApiController_TriggerEventContainer.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_OrderStateUpdate.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_OrderTagCreate.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_SearchController_CustomerResult.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_SearchController_OrderResult.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_SearchController_ProductResult.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_SearchController_SearchModel.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_SearchController_SearchResultsModel.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ShipmentWithLabel.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ShipmentWithLabelResult.h \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_WebHookApiModel.h \
    $${PWD}/OAISystem_Collections_Generic_KeyValuePair_System_Int32_System_String_.h \
    $${PWD}/OAISystem_Collections_Generic_KeyValuePair_System_String_System_Collections_Generic_List_System_Collections_Generic_KeyValuePair_System_Int32_System_String_.h \
# APIs
    $${PWD}/OAICloudStorageApi.h \
    $${PWD}/OAICustomerAddressesApi.h \
    $${PWD}/OAICustomersApi.h \
    $${PWD}/OAIDeliveryNoteApi.h \
    $${PWD}/OAIEnumApiApi.h \
    $${PWD}/OAIEventsApi.h \
    $${PWD}/OAIInvoiceApi.h \
    $${PWD}/OAIOrdersApi.h \
    $${PWD}/OAIProductsApi.h \
    $${PWD}/OAIProvisioningApi.h \
    $${PWD}/OAIShipmentsApi.h \
    $${PWD}/OAIWebhooksApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_AdditionalFeeApiModel.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_ArticleApiCustomFieldDefinitionModel.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_ArticleApiCustomFieldValueModel.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_ArticleApiModel.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_ArticleCategoryApiModel.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_ArticleImageRelationApiModel.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_ArticleSourceApiModel.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_BomSubArticleApiModel.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_CloudStorageApiModel.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_CommentApiModel.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_CreateCustomerApiModel.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_CreateShipmentApiModel.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_CustomerAddressApiModel.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_CustomerApiModel.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_DeletedImagesModel.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_GetReservedAmountResponseData.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_InvoiceApiModel.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_InvoiceApiPositionApiModel.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_Order.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_OrderAddressApiModel.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_OrderItem.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_OrderItemAttribute.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_OrderUser.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_ProductImage.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_Shipment.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_ShipmentAddressApiModel.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_SoldProduct.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_StockArticleApiModel.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_StockResponseData.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_UpdateStockApiModel.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_UpdateStockCodeApiModel.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Model_UpdateStockResponseData.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Models_CustomerMetaDataApiModel.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Models_LayoutTemplate.cpp \
    $${PWD}/OAIBillbee_Interfaces_BillbeeAPI_Models_OrderPayment.cpp \
    $${PWD}/OAIBillbee_Interfaces_Order_HistoryEntry.cpp \
    $${PWD}/OAIBillbee_Interfaces_Order_MultiLanguageString.cpp \
    $${PWD}/OAIBillbee_Interfaces_Order_VatDetailsRecognizedHistoryEntry_VatDetectionFlags.cpp \
    $${PWD}/OAIBillbee_Interfaces_Shipping_ProductService.cpp \
    $${PWD}/OAIBillbee_Interfaces_Shipping_ShipmentData_Dimensions.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiAddShipmentToOrderModel.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_PagingInformation_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_ArticleApiCustomFieldDefinitionModel_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_PagingInformation_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_ArticleApiModel_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_PagingInformation_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_CustomerAddressApiModel_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_PagingInformation_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_CustomerApiModel_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_PagingInformation_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_InvoiceApiModel_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_PagingInformation_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_Order_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_PagingInformation_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_Shipment_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_PagingInformation_System_Collections_Generic_List_Rechnungsdruck_WebApp_Controllers_Api_Order_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_ArticleApiCustomFieldDefinitionModel_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_ArticleApiModel_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_CustomerAddressApiModel_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_CustomerApiModel_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_InvoiceApiModel_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_Order_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_Shipment_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiPagedResult_System_Collections_Generic_List_Rechnungsdruck_WebApp_Controllers_Api_Order_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_Billbee_Interfaces_BillbeeAPI_Model_ArticleApiCustomFieldDefinitionModel_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_Billbee_Interfaces_BillbeeAPI_Model_ArticleApiModel_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_Billbee_Interfaces_BillbeeAPI_Model_ArticleImageRelationApiModel_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_Billbee_Interfaces_BillbeeAPI_Model_CustomerAddressApiModel_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_Billbee_Interfaces_BillbeeAPI_Model_CustomerApiModel_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_Billbee_Interfaces_BillbeeAPI_Model_DeletedImagesModel_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_Billbee_Interfaces_BillbeeAPI_Model_GetReservedAmountResponseData_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_Billbee_Interfaces_BillbeeAPI_Model_Order_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_Billbee_Interfaces_BillbeeAPI_Model_UpdateStockCodeResponseData_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_Billbee_Interfaces_BillbeeAPI_Model_UpdateStockResponseData_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_Rechnungsdruck_WebApp_Controllers_Api_Invoice_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_Rechnungsdruck_WebApp_Controllers_Api_SearchController_SearchResultsModel_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_Rechnungsdruck_WebApp_Controllers_Api_ShipmentWithLabelResult_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_ArticleImageRelationApiModel_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_CloudStorageApiModel_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Model_StockResponseData_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ApiResult_System_Collections_Generic_List_Billbee_Interfaces_BillbeeAPI_Models_LayoutTemplate_.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_AutomaticProvisioningController_CreateAccountContainer.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_AutomaticProvisioningController_CreateAccountContainer_UserAddress.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_Invoice.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_Order.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_OrderApiController_ParseTextContainer.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_OrderApiController_SendMessageModel.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_OrderApiController_TriggerEventContainer.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_OrderStateUpdate.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_OrderTagCreate.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_SearchController_CustomerResult.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_SearchController_OrderResult.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_SearchController_ProductResult.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_SearchController_SearchModel.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_SearchController_SearchResultsModel.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ShipmentWithLabel.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_ShipmentWithLabelResult.cpp \
    $${PWD}/OAIRechnungsdruck_WebApp_Controllers_Api_WebHookApiModel.cpp \
    $${PWD}/OAISystem_Collections_Generic_KeyValuePair_System_Int32_System_String_.cpp \
    $${PWD}/OAISystem_Collections_Generic_KeyValuePair_System_String_System_Collections_Generic_List_System_Collections_Generic_KeyValuePair_System_Int32_System_String_.cpp \
# APIs
    $${PWD}/OAICloudStorageApi.cpp \
    $${PWD}/OAICustomerAddressesApi.cpp \
    $${PWD}/OAICustomersApi.cpp \
    $${PWD}/OAIDeliveryNoteApi.cpp \
    $${PWD}/OAIEnumApiApi.cpp \
    $${PWD}/OAIEventsApi.cpp \
    $${PWD}/OAIInvoiceApi.cpp \
    $${PWD}/OAIOrdersApi.cpp \
    $${PWD}/OAIProductsApi.cpp \
    $${PWD}/OAIProvisioningApi.cpp \
    $${PWD}/OAIShipmentsApi.cpp \
    $${PWD}/OAIWebhooksApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
