openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: "Accesses report data in Google Analytics. Warning: Creating multiple\
    \ Customer Applications, Accounts, or Projects to simulate or act as a single\
    \ Customer Application, Account, or Project (respectively) or to circumvent Service-specific\
    \ usage limits or quotas is a direct violation of Google Cloud Platform Terms\
    \ of Service as well as Google APIs Terms of Service. These actions can result\
    \ in immediate termination of your GCP project(s) without any warning. "
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Google Analytics Data API
  version: v1beta
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://upload.wikimedia.org/wikipedia/commons/e/e1/YouTube_play_buttom_icon_%282013-2017%29.svg
  x-origin:
  - format: google
    url: https://analyticsdata.googleapis.com/$discovery/rest?version=v1beta
    version: v1
  x-providerName: googleapis.com
  x-serviceName: analyticsdata
servers:
- url: https://analyticsdata.googleapis.com/
tags:
- name: properties
paths:
  /v1beta/{name}:
    get:
      description: "Gets configuration metadata about a specific audience export.\
        \ This method can be used to understand an audience export after it has been\
        \ created. See [Creating an Audience Export](https://developers.google.com/analytics/devguides/reporting/data/v1/audience-list-basics)\
        \ for an introduction to Audience Exports with examples. Audience Export APIs\
        \ have some methods at alpha and other methods at beta stability. The intention\
        \ is to advance methods to beta stability after some feedback and adoption.\
        \ To give your feedback on this API, complete the [Google Analytics Audience\
        \ Export API Feedback](https://forms.gle/EeA5u5LW6PEggtCEA) form."
      operationId: analyticsdata.properties.audienceExports.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
        Oauth2c:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-accepts:
      - application/json
  /v1beta/{name}:query:
    post:
      description: "Retrieves an audience export of users. After creating an audience,\
        \ the users are not immediately available for exporting. First, a request\
        \ to `CreateAudienceExport` is necessary to create an audience export of users,\
        \ and then second, this method is used to retrieve the users in the audience\
        \ export. See [Creating an Audience Export](https://developers.google.com/analytics/devguides/reporting/data/v1/audience-list-basics)\
        \ for an introduction to Audience Exports with examples. Audiences in Google\
        \ Analytics 4 allow you to segment your users in the ways that are important\
        \ to your business. To learn more, see https://support.google.com/analytics/answer/9267572.\
        \ Audience Export APIs have some methods at alpha and other methods at beta\
        \ stability. The intention is to advance methods to beta stability after some\
        \ feedback and adoption. To give your feedback on this API, complete the [Google\
        \ Analytics Audience Export API Feedback](https://forms.gle/EeA5u5LW6PEggtCEA)\
        \ form."
      operationId: analyticsdata.properties.audienceExports.query
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
        Oauth2c:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1beta/{parent}/audienceExports:
    get:
      description: "Lists all audience exports for a property. This method can be\
        \ used for you to find and reuse existing audience exports rather than creating\
        \ unnecessary new audience exports. The same audience can have multiple audience\
        \ exports that represent the export of users that were in an audience on different\
        \ days. See [Creating an Audience Export](https://developers.google.com/analytics/devguides/reporting/data/v1/audience-list-basics)\
        \ for an introduction to Audience Exports with examples. Audience Export APIs\
        \ have some methods at alpha and other methods at beta stability. The intention\
        \ is to advance methods to beta stability after some feedback and adoption.\
        \ To give your feedback on this API, complete the [Google Analytics Audience\
        \ Export API Feedback](https://forms.gle/EeA5u5LW6PEggtCEA) form."
      operationId: analyticsdata.properties.audienceExports.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
        Oauth2c:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-accepts:
      - application/json
    post:
      description: "Creates an audience export for later retrieval. This method quickly\
        \ returns the audience export's resource name and initiates a long running\
        \ asynchronous request to form an audience export. To export the users in\
        \ an audience export, first create the audience export through this method\
        \ and then send the audience resource name to the `QueryAudienceExport` method.\
        \ See [Creating an Audience Export](https://developers.google.com/analytics/devguides/reporting/data/v1/audience-list-basics)\
        \ for an introduction to Audience Exports with examples. An audience export\
        \ is a snapshot of the users currently in the audience at the time of audience\
        \ export creation. Creating audience exports for one audience on different\
        \ days will return different results as users enter and exit the audience.\
        \ Audiences in Google Analytics 4 allow you to segment your users in the ways\
        \ that are important to your business. To learn more, see https://support.google.com/analytics/answer/9267572.\
        \ Audience exports contain the users in each audience. Audience Export APIs\
        \ have some methods at alpha and other methods at beta stability. The intention\
        \ is to advance methods to beta stability after some feedback and adoption.\
        \ To give your feedback on this API, complete the [Google Analytics Audience\
        \ Export API Feedback](https://forms.gle/EeA5u5LW6PEggtCEA) form."
      operationId: analyticsdata.properties.audienceExports.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
        Oauth2c:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1beta/{property}:batchRunPivotReports:
    post:
      description: Returns multiple pivot reports in a batch. All reports must be
        for the same GA4 Property.
      operationId: analyticsdata.properties.batchRunPivotReports
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
        Oauth2c:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1beta/{property}:batchRunReports:
    post:
      description: Returns multiple reports in a batch. All reports must be for the
        same GA4 Property.
      operationId: analyticsdata.properties.batchRunReports
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
        Oauth2c:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1beta/{property}:checkCompatibility:
    post:
      description: "This compatibility method lists dimensions and metrics that can\
        \ be added to a report request and maintain compatibility. This method fails\
        \ if the request's dimensions and metrics are incompatible. In Google Analytics,\
        \ reports fail if they request incompatible dimensions and/or metrics; in\
        \ that case, you will need to remove dimensions and/or metrics from the incompatible\
        \ report until the report is compatible. The Realtime and Core reports have\
        \ different compatibility rules. This method checks compatibility for Core\
        \ reports."
      operationId: analyticsdata.properties.checkCompatibility
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
        Oauth2c:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1beta/{property}:runPivotReport:
    post:
      description: "Returns a customized pivot report of your Google Analytics event\
        \ data. Pivot reports are more advanced and expressive formats than regular\
        \ reports. In a pivot report, dimensions are only visible if they are included\
        \ in a pivot. Multiple pivots can be specified to further dissect your data."
      operationId: analyticsdata.properties.runPivotReport
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
        Oauth2c:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1beta/{property}:runRealtimeReport:
    post:
      description: "Returns a customized report of realtime event data for your property.\
        \ Events appear in realtime reports seconds after they have been sent to the\
        \ Google Analytics. Realtime reports show events and usage data for the periods\
        \ of time ranging from the present moment to 30 minutes ago (up to 60 minutes\
        \ for Google Analytics 360 properties). For a guide to constructing realtime\
        \ requests & understanding responses, see [Creating a Realtime Report](https://developers.google.com/analytics/devguides/reporting/data/v1/realtime-basics)."
      operationId: analyticsdata.properties.runRealtimeReport
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
        Oauth2c:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1beta/{property}:runReport:
    post:
      description: "Returns a customized report of your Google Analytics event data.\
        \ Reports contain statistics derived from data collected by the Google Analytics\
        \ tracking code. The data returned from the API is as a table with columns\
        \ for the requested dimensions and metrics. Metrics are individual measurements\
        \ of user activity on your property, such as active users or event count.\
        \ Dimensions break down metrics across some common criteria, such as country\
        \ or event name. For a guide to constructing requests & understanding responses,\
        \ see [Creating a Report](https://developers.google.com/analytics/devguides/reporting/data/v1/basics)."
      operationId: analyticsdata.properties.runReport
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
        Oauth2c:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-content-type: application/json
      x-accepts:
      - application/json
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/analytics: View and manage your Google
              Analytics data
            https://www.googleapis.com/auth/analytics.readonly: See and download your
              Google Analytics data
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/analytics: View and manage your Google
              Analytics data
            https://www.googleapis.com/auth/analytics.readonly: See and download your
              Google Analytics data
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2

