# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class BoxScoreTeamsRushingInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, line_yards: float=None, line_yards_average: float=None, open_field_yards: int=None, open_field_yards_average: float=None, power_success: float=None, second_level_yards: int=None, second_level_yards_average: float=None, stuff_rate: float=None, team: str=None):
        """BoxScoreTeamsRushingInner - a model defined in OpenAPI

        :param line_yards: The line_yards of this BoxScoreTeamsRushingInner.
        :param line_yards_average: The line_yards_average of this BoxScoreTeamsRushingInner.
        :param open_field_yards: The open_field_yards of this BoxScoreTeamsRushingInner.
        :param open_field_yards_average: The open_field_yards_average of this BoxScoreTeamsRushingInner.
        :param power_success: The power_success of this BoxScoreTeamsRushingInner.
        :param second_level_yards: The second_level_yards of this BoxScoreTeamsRushingInner.
        :param second_level_yards_average: The second_level_yards_average of this BoxScoreTeamsRushingInner.
        :param stuff_rate: The stuff_rate of this BoxScoreTeamsRushingInner.
        :param team: The team of this BoxScoreTeamsRushingInner.
        """
        self.openapi_types = {
            'line_yards': float,
            'line_yards_average': float,
            'open_field_yards': int,
            'open_field_yards_average': float,
            'power_success': float,
            'second_level_yards': int,
            'second_level_yards_average': float,
            'stuff_rate': float,
            'team': str
        }

        self.attribute_map = {
            'line_yards': 'lineYards',
            'line_yards_average': 'lineYardsAverage',
            'open_field_yards': 'openFieldYards',
            'open_field_yards_average': 'openFieldYardsAverage',
            'power_success': 'powerSuccess',
            'second_level_yards': 'secondLevelYards',
            'second_level_yards_average': 'secondLevelYardsAverage',
            'stuff_rate': 'stuffRate',
            'team': 'team'
        }

        self._line_yards = line_yards
        self._line_yards_average = line_yards_average
        self._open_field_yards = open_field_yards
        self._open_field_yards_average = open_field_yards_average
        self._power_success = power_success
        self._second_level_yards = second_level_yards
        self._second_level_yards_average = second_level_yards_average
        self._stuff_rate = stuff_rate
        self._team = team

    @classmethod
    def from_dict(cls, dikt: dict) -> 'BoxScoreTeamsRushingInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The BoxScore_teams_rushing_inner of this BoxScoreTeamsRushingInner.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def line_yards(self):
        """Gets the line_yards of this BoxScoreTeamsRushingInner.


        :return: The line_yards of this BoxScoreTeamsRushingInner.
        :rtype: float
        """
        return self._line_yards

    @line_yards.setter
    def line_yards(self, line_yards):
        """Sets the line_yards of this BoxScoreTeamsRushingInner.


        :param line_yards: The line_yards of this BoxScoreTeamsRushingInner.
        :type line_yards: float
        """

        self._line_yards = line_yards

    @property
    def line_yards_average(self):
        """Gets the line_yards_average of this BoxScoreTeamsRushingInner.


        :return: The line_yards_average of this BoxScoreTeamsRushingInner.
        :rtype: float
        """
        return self._line_yards_average

    @line_yards_average.setter
    def line_yards_average(self, line_yards_average):
        """Sets the line_yards_average of this BoxScoreTeamsRushingInner.


        :param line_yards_average: The line_yards_average of this BoxScoreTeamsRushingInner.
        :type line_yards_average: float
        """

        self._line_yards_average = line_yards_average

    @property
    def open_field_yards(self):
        """Gets the open_field_yards of this BoxScoreTeamsRushingInner.


        :return: The open_field_yards of this BoxScoreTeamsRushingInner.
        :rtype: int
        """
        return self._open_field_yards

    @open_field_yards.setter
    def open_field_yards(self, open_field_yards):
        """Sets the open_field_yards of this BoxScoreTeamsRushingInner.


        :param open_field_yards: The open_field_yards of this BoxScoreTeamsRushingInner.
        :type open_field_yards: int
        """

        self._open_field_yards = open_field_yards

    @property
    def open_field_yards_average(self):
        """Gets the open_field_yards_average of this BoxScoreTeamsRushingInner.


        :return: The open_field_yards_average of this BoxScoreTeamsRushingInner.
        :rtype: float
        """
        return self._open_field_yards_average

    @open_field_yards_average.setter
    def open_field_yards_average(self, open_field_yards_average):
        """Sets the open_field_yards_average of this BoxScoreTeamsRushingInner.


        :param open_field_yards_average: The open_field_yards_average of this BoxScoreTeamsRushingInner.
        :type open_field_yards_average: float
        """

        self._open_field_yards_average = open_field_yards_average

    @property
    def power_success(self):
        """Gets the power_success of this BoxScoreTeamsRushingInner.


        :return: The power_success of this BoxScoreTeamsRushingInner.
        :rtype: float
        """
        return self._power_success

    @power_success.setter
    def power_success(self, power_success):
        """Sets the power_success of this BoxScoreTeamsRushingInner.


        :param power_success: The power_success of this BoxScoreTeamsRushingInner.
        :type power_success: float
        """

        self._power_success = power_success

    @property
    def second_level_yards(self):
        """Gets the second_level_yards of this BoxScoreTeamsRushingInner.


        :return: The second_level_yards of this BoxScoreTeamsRushingInner.
        :rtype: int
        """
        return self._second_level_yards

    @second_level_yards.setter
    def second_level_yards(self, second_level_yards):
        """Sets the second_level_yards of this BoxScoreTeamsRushingInner.


        :param second_level_yards: The second_level_yards of this BoxScoreTeamsRushingInner.
        :type second_level_yards: int
        """

        self._second_level_yards = second_level_yards

    @property
    def second_level_yards_average(self):
        """Gets the second_level_yards_average of this BoxScoreTeamsRushingInner.


        :return: The second_level_yards_average of this BoxScoreTeamsRushingInner.
        :rtype: float
        """
        return self._second_level_yards_average

    @second_level_yards_average.setter
    def second_level_yards_average(self, second_level_yards_average):
        """Sets the second_level_yards_average of this BoxScoreTeamsRushingInner.


        :param second_level_yards_average: The second_level_yards_average of this BoxScoreTeamsRushingInner.
        :type second_level_yards_average: float
        """

        self._second_level_yards_average = second_level_yards_average

    @property
    def stuff_rate(self):
        """Gets the stuff_rate of this BoxScoreTeamsRushingInner.


        :return: The stuff_rate of this BoxScoreTeamsRushingInner.
        :rtype: float
        """
        return self._stuff_rate

    @stuff_rate.setter
    def stuff_rate(self, stuff_rate):
        """Sets the stuff_rate of this BoxScoreTeamsRushingInner.


        :param stuff_rate: The stuff_rate of this BoxScoreTeamsRushingInner.
        :type stuff_rate: float
        """

        self._stuff_rate = stuff_rate

    @property
    def team(self):
        """Gets the team of this BoxScoreTeamsRushingInner.


        :return: The team of this BoxScoreTeamsRushingInner.
        :rtype: str
        """
        return self._team

    @team.setter
    def team(self, team):
        """Sets the team of this BoxScoreTeamsRushingInner.


        :param team: The team of this BoxScoreTeamsRushingInner.
        :type team: str
        """

        self._team = team
