QT += network

HEADERS += \
# Models
    $${PWD}/OAIGoogleApiHttpBody.h \
    $${PWD}/OAIGoogleCloudRetailLoggingErrorContext.h \
    $${PWD}/OAIGoogleCloudRetailLoggingErrorLog.h \
    $${PWD}/OAIGoogleCloudRetailLoggingHttpRequestContext.h \
    $${PWD}/OAIGoogleCloudRetailLoggingImportErrorContext.h \
    $${PWD}/OAIGoogleCloudRetailLoggingServiceContext.h \
    $${PWD}/OAIGoogleCloudRetailLoggingSourceLocation.h \
    $${PWD}/OAIGoogleCloudRetailV2BigQueryOutputResult.h \
    $${PWD}/OAIGoogleCloudRetailV2CreateModelMetadata.h \
    $${PWD}/OAIGoogleCloudRetailV2ExportAnalyticsMetricsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2ExportErrorsConfig.h \
    $${PWD}/OAIGoogleCloudRetailV2ExportMetadata.h \
    $${PWD}/OAIGoogleCloudRetailV2GcsOutputResult.h \
    $${PWD}/OAIGoogleCloudRetailV2ImportCompletionDataResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2ImportErrorsConfig.h \
    $${PWD}/OAIGoogleCloudRetailV2ImportMetadata.h \
    $${PWD}/OAIGoogleCloudRetailV2ImportProductsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2ImportUserEventsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2Model.h \
    $${PWD}/OAIGoogleCloudRetailV2ModelFrequentlyBoughtTogetherFeaturesConfig.h \
    $${PWD}/OAIGoogleCloudRetailV2ModelModelFeaturesConfig.h \
    $${PWD}/OAIGoogleCloudRetailV2ModelServingConfigList.h \
    $${PWD}/OAIGoogleCloudRetailV2OutputResult.h \
    $${PWD}/OAIGoogleCloudRetailV2PurgeProductsMetadata.h \
    $${PWD}/OAIGoogleCloudRetailV2PurgeProductsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2PurgeUserEventsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2RejoinUserEventsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2TuneModelMetadata.h \
    $${PWD}/OAIGoogleCloudRetailV2UserEventImportSummary.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaAddCatalogAttributeRequest.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaAddControlRequest.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaAddFulfillmentPlacesRequest.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaAddLocalInventoriesRequest.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaAttributesConfig.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaAudience.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaBatchRemoveCatalogAttributesRequest.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaBatchRemoveCatalogAttributesResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaBigQueryOutputResult.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaBigQuerySource.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaCatalog.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaCatalogAttribute.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaCatalogAttributeFacetConfig.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaCatalogAttributeFacetConfigIgnoredFacetValues.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaCatalogAttributeFacetConfigMergedFacet.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaCatalogAttributeFacetConfigMergedFacetValue.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaCatalogAttributeFacetConfigRerankConfig.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaColorInfo.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaCompleteQueryResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaCompleteQueryResponseAttributeResult.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaCompleteQueryResponseCompletionResult.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaCompleteQueryResponseRecentSearchResult.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaCompletionConfig.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaCompletionDataInputConfig.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaCompletionDetail.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaCondition.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaConditionQueryTerm.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaConditionTimeRange.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaControl.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaCreateMerchantCenterAccountLinkMetadata.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaCreateModelMetadata.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaCustomAttribute.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaEnrollSolutionRequest.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaEnrollSolutionResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaExperimentInfo.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaExperimentInfoServingConfigExperiment.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaExportAnalyticsMetricsRequest.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaExportAnalyticsMetricsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaExportErrorsConfig.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaExportMetadata.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaExportProductsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaExportUserEventsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaFulfillmentInfo.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaGcsOutputResult.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaGcsSource.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaGetDefaultBranchResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaImage.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaImportCompletionDataRequest.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaImportCompletionDataResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaImportErrorsConfig.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaImportMetadata.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaImportProductsRequest.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaImportProductsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaImportUserEventsRequest.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaImportUserEventsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaInterval.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaListCatalogsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaListControlsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaListEnrolledSolutionsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaListMerchantCenterAccountLinksResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaListModelsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaListProductsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaListServingConfigsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaLocalInventory.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaLoggingConfig.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaLoggingConfigLogGenerationRule.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaLoggingConfigServiceLogGenerationRule.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaMerchantCenterAccountLink.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaMerchantCenterAccountLinkMerchantCenterFeedFilter.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaMerchantCenterFeedFilter.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaMerchantCenterLink.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaMerchantCenterLinkingConfig.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaModel.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaModelFrequentlyBoughtTogetherFeaturesConfig.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaModelModelFeaturesConfig.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaModelPageOptimizationConfig.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaModelPageOptimizationConfigCandidate.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaModelPageOptimizationConfigPanel.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaModelServingConfigList.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaOutputConfig.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaOutputConfigBigQueryDestination.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaOutputConfigGcsDestination.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaOutputResult.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaPredictRequest.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaPredictResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaPredictResponsePredictionResult.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaPriceInfo.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaPriceInfoPriceRange.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaProduct.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaProductDetail.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaProductInlineSource.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaProductInputConfig.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaProductLevelConfig.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaProject.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaPromotion.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaPurchaseTransaction.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaPurgeProductsMetadata.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaPurgeProductsRequest.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaPurgeProductsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaPurgeUserEventsRequest.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaPurgeUserEventsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaRating.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaRejoinUserEventsRequest.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaRejoinUserEventsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaRemoveCatalogAttributeRequest.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaRemoveControlRequest.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaRemoveFulfillmentPlacesRequest.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaRemoveLocalInventoriesRequest.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaReplaceCatalogAttributeRequest.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaRule.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaRuleBoostAction.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaRuleDoNotAssociateAction.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaRuleFilterAction.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaRuleForceReturnFacetAction.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaRuleForceReturnFacetActionFacetPositionAdjustment.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaRuleIgnoreAction.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaRuleOnewaySynonymsAction.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaRuleRedirectAction.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaRuleRemoveFacetAction.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaRuleReplacementAction.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaRuleTwowaySynonymsAction.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchRequest.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchRequestBoostSpec.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchRequestBoostSpecConditionBoostSpec.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchRequestDynamicFacetSpec.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchRequestFacetSpec.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchRequestFacetSpecFacetKey.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchRequestPersonalizationSpec.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchRequestQueryExpansionSpec.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchRequestSpellCorrectionSpec.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchResponseFacet.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchResponseFacetFacetValue.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchResponseQueryExpansionInfo.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchResponseSearchResult.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaServingConfig.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaSetDefaultBranchRequest.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaSetInventoryRequest.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaTransformedUserEventsMetadata.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaTuneModelMetadata.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaUserEvent.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaUserEventImportSummary.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaUserEventInlineSource.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaUserEventInputConfig.h \
    $${PWD}/OAIGoogleCloudRetailV2alphaUserInfo.h \
    $${PWD}/OAIGoogleCloudRetailV2betaBigQueryOutputResult.h \
    $${PWD}/OAIGoogleCloudRetailV2betaCreateMerchantCenterAccountLinkMetadata.h \
    $${PWD}/OAIGoogleCloudRetailV2betaCreateModelMetadata.h \
    $${PWD}/OAIGoogleCloudRetailV2betaExportAnalyticsMetricsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2betaExportErrorsConfig.h \
    $${PWD}/OAIGoogleCloudRetailV2betaExportMetadata.h \
    $${PWD}/OAIGoogleCloudRetailV2betaExportProductsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2betaExportUserEventsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2betaGcsOutputResult.h \
    $${PWD}/OAIGoogleCloudRetailV2betaImportCompletionDataResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2betaImportErrorsConfig.h \
    $${PWD}/OAIGoogleCloudRetailV2betaImportMetadata.h \
    $${PWD}/OAIGoogleCloudRetailV2betaImportProductsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2betaImportUserEventsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2betaMerchantCenterAccountLink.h \
    $${PWD}/OAIGoogleCloudRetailV2betaMerchantCenterAccountLinkMerchantCenterFeedFilter.h \
    $${PWD}/OAIGoogleCloudRetailV2betaModel.h \
    $${PWD}/OAIGoogleCloudRetailV2betaModelFrequentlyBoughtTogetherFeaturesConfig.h \
    $${PWD}/OAIGoogleCloudRetailV2betaModelModelFeaturesConfig.h \
    $${PWD}/OAIGoogleCloudRetailV2betaModelServingConfigList.h \
    $${PWD}/OAIGoogleCloudRetailV2betaOutputResult.h \
    $${PWD}/OAIGoogleCloudRetailV2betaPurgeProductsMetadata.h \
    $${PWD}/OAIGoogleCloudRetailV2betaPurgeProductsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2betaPurgeUserEventsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2betaRejoinUserEventsResponse.h \
    $${PWD}/OAIGoogleCloudRetailV2betaTuneModelMetadata.h \
    $${PWD}/OAIGoogleCloudRetailV2betaUserEventImportSummary.h \
    $${PWD}/OAIGoogleLongrunningListOperationsResponse.h \
    $${PWD}/OAIGoogleLongrunningOperation.h \
    $${PWD}/OAIGoogleRpcStatus.h \
    $${PWD}/OAIGoogleTypeDate.h \
# APIs
    $${PWD}/OAIProjectsApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIGoogleApiHttpBody.cpp \
    $${PWD}/OAIGoogleCloudRetailLoggingErrorContext.cpp \
    $${PWD}/OAIGoogleCloudRetailLoggingErrorLog.cpp \
    $${PWD}/OAIGoogleCloudRetailLoggingHttpRequestContext.cpp \
    $${PWD}/OAIGoogleCloudRetailLoggingImportErrorContext.cpp \
    $${PWD}/OAIGoogleCloudRetailLoggingServiceContext.cpp \
    $${PWD}/OAIGoogleCloudRetailLoggingSourceLocation.cpp \
    $${PWD}/OAIGoogleCloudRetailV2BigQueryOutputResult.cpp \
    $${PWD}/OAIGoogleCloudRetailV2CreateModelMetadata.cpp \
    $${PWD}/OAIGoogleCloudRetailV2ExportAnalyticsMetricsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2ExportErrorsConfig.cpp \
    $${PWD}/OAIGoogleCloudRetailV2ExportMetadata.cpp \
    $${PWD}/OAIGoogleCloudRetailV2GcsOutputResult.cpp \
    $${PWD}/OAIGoogleCloudRetailV2ImportCompletionDataResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2ImportErrorsConfig.cpp \
    $${PWD}/OAIGoogleCloudRetailV2ImportMetadata.cpp \
    $${PWD}/OAIGoogleCloudRetailV2ImportProductsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2ImportUserEventsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2Model.cpp \
    $${PWD}/OAIGoogleCloudRetailV2ModelFrequentlyBoughtTogetherFeaturesConfig.cpp \
    $${PWD}/OAIGoogleCloudRetailV2ModelModelFeaturesConfig.cpp \
    $${PWD}/OAIGoogleCloudRetailV2ModelServingConfigList.cpp \
    $${PWD}/OAIGoogleCloudRetailV2OutputResult.cpp \
    $${PWD}/OAIGoogleCloudRetailV2PurgeProductsMetadata.cpp \
    $${PWD}/OAIGoogleCloudRetailV2PurgeProductsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2PurgeUserEventsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2RejoinUserEventsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2TuneModelMetadata.cpp \
    $${PWD}/OAIGoogleCloudRetailV2UserEventImportSummary.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaAddCatalogAttributeRequest.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaAddControlRequest.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaAddFulfillmentPlacesRequest.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaAddLocalInventoriesRequest.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaAttributesConfig.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaAudience.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaBatchRemoveCatalogAttributesRequest.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaBatchRemoveCatalogAttributesResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaBigQueryOutputResult.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaBigQuerySource.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaCatalog.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaCatalogAttribute.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaCatalogAttributeFacetConfig.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaCatalogAttributeFacetConfigIgnoredFacetValues.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaCatalogAttributeFacetConfigMergedFacet.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaCatalogAttributeFacetConfigMergedFacetValue.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaCatalogAttributeFacetConfigRerankConfig.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaColorInfo.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaCompleteQueryResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaCompleteQueryResponseAttributeResult.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaCompleteQueryResponseCompletionResult.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaCompleteQueryResponseRecentSearchResult.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaCompletionConfig.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaCompletionDataInputConfig.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaCompletionDetail.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaCondition.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaConditionQueryTerm.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaConditionTimeRange.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaControl.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaCreateMerchantCenterAccountLinkMetadata.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaCreateModelMetadata.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaCustomAttribute.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaEnrollSolutionRequest.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaEnrollSolutionResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaExperimentInfo.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaExperimentInfoServingConfigExperiment.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaExportAnalyticsMetricsRequest.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaExportAnalyticsMetricsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaExportErrorsConfig.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaExportMetadata.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaExportProductsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaExportUserEventsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaFulfillmentInfo.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaGcsOutputResult.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaGcsSource.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaGetDefaultBranchResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaImage.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaImportCompletionDataRequest.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaImportCompletionDataResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaImportErrorsConfig.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaImportMetadata.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaImportProductsRequest.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaImportProductsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaImportUserEventsRequest.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaImportUserEventsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaInterval.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaListCatalogsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaListControlsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaListEnrolledSolutionsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaListMerchantCenterAccountLinksResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaListModelsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaListProductsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaListServingConfigsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaLocalInventory.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaLoggingConfig.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaLoggingConfigLogGenerationRule.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaLoggingConfigServiceLogGenerationRule.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaMerchantCenterAccountLink.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaMerchantCenterAccountLinkMerchantCenterFeedFilter.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaMerchantCenterFeedFilter.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaMerchantCenterLink.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaMerchantCenterLinkingConfig.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaModel.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaModelFrequentlyBoughtTogetherFeaturesConfig.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaModelModelFeaturesConfig.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaModelPageOptimizationConfig.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaModelPageOptimizationConfigCandidate.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaModelPageOptimizationConfigPanel.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaModelServingConfigList.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaOutputConfig.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaOutputConfigBigQueryDestination.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaOutputConfigGcsDestination.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaOutputResult.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaPredictRequest.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaPredictResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaPredictResponsePredictionResult.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaPriceInfo.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaPriceInfoPriceRange.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaProduct.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaProductDetail.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaProductInlineSource.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaProductInputConfig.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaProductLevelConfig.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaProject.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaPromotion.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaPurchaseTransaction.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaPurgeProductsMetadata.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaPurgeProductsRequest.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaPurgeProductsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaPurgeUserEventsRequest.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaPurgeUserEventsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaRating.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaRejoinUserEventsRequest.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaRejoinUserEventsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaRemoveCatalogAttributeRequest.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaRemoveControlRequest.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaRemoveFulfillmentPlacesRequest.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaRemoveLocalInventoriesRequest.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaReplaceCatalogAttributeRequest.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaRule.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaRuleBoostAction.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaRuleDoNotAssociateAction.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaRuleFilterAction.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaRuleForceReturnFacetAction.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaRuleForceReturnFacetActionFacetPositionAdjustment.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaRuleIgnoreAction.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaRuleOnewaySynonymsAction.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaRuleRedirectAction.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaRuleRemoveFacetAction.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaRuleReplacementAction.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaRuleTwowaySynonymsAction.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchRequest.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchRequestBoostSpec.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchRequestBoostSpecConditionBoostSpec.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchRequestDynamicFacetSpec.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchRequestFacetSpec.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchRequestFacetSpecFacetKey.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchRequestPersonalizationSpec.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchRequestQueryExpansionSpec.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchRequestSpellCorrectionSpec.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchResponseFacet.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchResponseFacetFacetValue.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchResponseQueryExpansionInfo.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaSearchResponseSearchResult.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaServingConfig.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaSetDefaultBranchRequest.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaSetInventoryRequest.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaTransformedUserEventsMetadata.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaTuneModelMetadata.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaUserEvent.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaUserEventImportSummary.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaUserEventInlineSource.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaUserEventInputConfig.cpp \
    $${PWD}/OAIGoogleCloudRetailV2alphaUserInfo.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaBigQueryOutputResult.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaCreateMerchantCenterAccountLinkMetadata.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaCreateModelMetadata.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaExportAnalyticsMetricsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaExportErrorsConfig.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaExportMetadata.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaExportProductsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaExportUserEventsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaGcsOutputResult.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaImportCompletionDataResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaImportErrorsConfig.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaImportMetadata.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaImportProductsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaImportUserEventsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaMerchantCenterAccountLink.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaMerchantCenterAccountLinkMerchantCenterFeedFilter.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaModel.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaModelFrequentlyBoughtTogetherFeaturesConfig.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaModelModelFeaturesConfig.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaModelServingConfigList.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaOutputResult.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaPurgeProductsMetadata.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaPurgeProductsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaPurgeUserEventsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaRejoinUserEventsResponse.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaTuneModelMetadata.cpp \
    $${PWD}/OAIGoogleCloudRetailV2betaUserEventImportSummary.cpp \
    $${PWD}/OAIGoogleLongrunningListOperationsResponse.cpp \
    $${PWD}/OAIGoogleLongrunningOperation.cpp \
    $${PWD}/OAIGoogleRpcStatus.cpp \
    $${PWD}/OAIGoogleTypeDate.cpp \
# APIs
    $${PWD}/OAIProjectsApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
