/**
 * Amazon Connect Service
 * <p>Amazon Connect is a cloud-based contact center solution that you use to set up and manage a customer contact center and provide reliable customer engagement at any scale.</p> <p>Amazon Connect provides metrics and real-time reporting that enable you to optimize contact routing. You can also resolve customer issues more efficiently by getting customers in touch with the appropriate agents.</p> <p>There are limits to the number of Amazon Connect resources that you can create. There are also limits to the number of requests that you can make per second. For more information, see <a href=\"https://docs.aws.amazon.com/connect/latest/adminguide/amazon-connect-service-limits.html\">Amazon Connect Service Quotas</a> in the <i>Amazon Connect Administrator Guide</i>.</p> <p>You can connect programmatically to an Amazon Web Services service by using an endpoint. For a list of Amazon Connect endpoints, see <a href=\"https://docs.aws.amazon.com/general/latest/gr/connect_region.html\">Amazon Connect Endpoints</a>.</p>
 *
 * The version of the OpenAPI document: 2017-08-08
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIKinesisVideoStreamConfig.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIKinesisVideoStreamConfig::OAIKinesisVideoStreamConfig(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIKinesisVideoStreamConfig::OAIKinesisVideoStreamConfig() {
    this->initializeModel();
}

OAIKinesisVideoStreamConfig::~OAIKinesisVideoStreamConfig() {}

void OAIKinesisVideoStreamConfig::initializeModel() {

    m_prefix_isSet = false;
    m_prefix_isValid = false;

    m_retention_period_hours_isSet = false;
    m_retention_period_hours_isValid = false;

    m_encryption_config_isSet = false;
    m_encryption_config_isValid = false;
}

void OAIKinesisVideoStreamConfig::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIKinesisVideoStreamConfig::fromJsonObject(QJsonObject json) {

    m_prefix_isValid = ::OpenAPI::fromJsonValue(m_prefix, json[QString("Prefix")]);
    m_prefix_isSet = !json[QString("Prefix")].isNull() && m_prefix_isValid;

    m_retention_period_hours_isValid = ::OpenAPI::fromJsonValue(m_retention_period_hours, json[QString("RetentionPeriodHours")]);
    m_retention_period_hours_isSet = !json[QString("RetentionPeriodHours")].isNull() && m_retention_period_hours_isValid;

    m_encryption_config_isValid = ::OpenAPI::fromJsonValue(m_encryption_config, json[QString("EncryptionConfig")]);
    m_encryption_config_isSet = !json[QString("EncryptionConfig")].isNull() && m_encryption_config_isValid;
}

QString OAIKinesisVideoStreamConfig::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIKinesisVideoStreamConfig::asJsonObject() const {
    QJsonObject obj;
    if (m_prefix_isSet) {
        obj.insert(QString("Prefix"), ::OpenAPI::toJsonValue(m_prefix));
    }
    if (m_retention_period_hours_isSet) {
        obj.insert(QString("RetentionPeriodHours"), ::OpenAPI::toJsonValue(m_retention_period_hours));
    }
    if (m_encryption_config.isSet()) {
        obj.insert(QString("EncryptionConfig"), ::OpenAPI::toJsonValue(m_encryption_config));
    }
    return obj;
}

QString OAIKinesisVideoStreamConfig::getPrefix() const {
    return m_prefix;
}
void OAIKinesisVideoStreamConfig::setPrefix(const QString &prefix) {
    m_prefix = prefix;
    m_prefix_isSet = true;
}

bool OAIKinesisVideoStreamConfig::is_prefix_Set() const{
    return m_prefix_isSet;
}

bool OAIKinesisVideoStreamConfig::is_prefix_Valid() const{
    return m_prefix_isValid;
}

qint32 OAIKinesisVideoStreamConfig::getRetentionPeriodHours() const {
    return m_retention_period_hours;
}
void OAIKinesisVideoStreamConfig::setRetentionPeriodHours(const qint32 &retention_period_hours) {
    m_retention_period_hours = retention_period_hours;
    m_retention_period_hours_isSet = true;
}

bool OAIKinesisVideoStreamConfig::is_retention_period_hours_Set() const{
    return m_retention_period_hours_isSet;
}

bool OAIKinesisVideoStreamConfig::is_retention_period_hours_Valid() const{
    return m_retention_period_hours_isValid;
}

OAIKinesisVideoStreamConfig_EncryptionConfig OAIKinesisVideoStreamConfig::getEncryptionConfig() const {
    return m_encryption_config;
}
void OAIKinesisVideoStreamConfig::setEncryptionConfig(const OAIKinesisVideoStreamConfig_EncryptionConfig &encryption_config) {
    m_encryption_config = encryption_config;
    m_encryption_config_isSet = true;
}

bool OAIKinesisVideoStreamConfig::is_encryption_config_Set() const{
    return m_encryption_config_isSet;
}

bool OAIKinesisVideoStreamConfig::is_encryption_config_Valid() const{
    return m_encryption_config_isValid;
}

bool OAIKinesisVideoStreamConfig::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_prefix_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_retention_period_hours_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_encryption_config.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIKinesisVideoStreamConfig::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_prefix_isValid && m_retention_period_hours_isValid && m_encryption_config_isValid && true;
}

} // namespace OpenAPI
