/**
 * Amazon Connect Service
 * <p>Amazon Connect is a cloud-based contact center solution that you use to set up and manage a customer contact center and provide reliable customer engagement at any scale.</p> <p>Amazon Connect provides metrics and real-time reporting that enable you to optimize contact routing. You can also resolve customer issues more efficiently by getting customers in touch with the appropriate agents.</p> <p>There are limits to the number of Amazon Connect resources that you can create. There are also limits to the number of requests that you can make per second. For more information, see <a href=\"https://docs.aws.amazon.com/connect/latest/adminguide/amazon-connect-service-limits.html\">Amazon Connect Service Quotas</a> in the <i>Amazon Connect Administrator Guide</i>.</p> <p>You can connect programmatically to an Amazon Web Services service by using an endpoint. For a list of Amazon Connect endpoints, see <a href=\"https://docs.aws.amazon.com/general/latest/gr/connect_region.html\">Amazon Connect Endpoints</a>.</p>
 *
 * The version of the OpenAPI document: 2017-08-08
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIPhoneNumberWorkflowStatus.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIPhoneNumberWorkflowStatus::OAIPhoneNumberWorkflowStatus(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIPhoneNumberWorkflowStatus::OAIPhoneNumberWorkflowStatus() {
    this->initializeModel();
}

OAIPhoneNumberWorkflowStatus::~OAIPhoneNumberWorkflowStatus() {}

void OAIPhoneNumberWorkflowStatus::initializeModel() {

    m_value_isSet = false;
    m_value_isValid = false;
    m_value = eOAIPhoneNumberWorkflowStatus::INVALID_VALUE_OPENAPI_GENERATED;
}

void OAIPhoneNumberWorkflowStatus::fromJson(QString jsonString) {
    
    if ( jsonString.compare("CLAIMED", Qt::CaseInsensitive) == 0) {
        m_value = eOAIPhoneNumberWorkflowStatus::CLAIMED;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("IN_PROGRESS", Qt::CaseInsensitive) == 0) {
        m_value = eOAIPhoneNumberWorkflowStatus::IN_PROGRESS;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("FAILED", Qt::CaseInsensitive) == 0) {
        m_value = eOAIPhoneNumberWorkflowStatus::FAILED;
        m_value_isSet = m_value_isValid = true;
    }
}

void OAIPhoneNumberWorkflowStatus::fromJsonValue(QJsonValue json) {
fromJson(json.toString());
}

QString OAIPhoneNumberWorkflowStatus::asJson() const {
    
    QString val;
    switch (m_value){
        case eOAIPhoneNumberWorkflowStatus::CLAIMED:
            val = "CLAIMED";
            break;
        case eOAIPhoneNumberWorkflowStatus::IN_PROGRESS:
            val = "IN_PROGRESS";
            break;
        case eOAIPhoneNumberWorkflowStatus::FAILED:
            val = "FAILED";
            break;
        default:
            break;
    }
    return val;
}

QJsonValue OAIPhoneNumberWorkflowStatus::asJsonValue() const {
    
    return QJsonValue(asJson());
}


OAIPhoneNumberWorkflowStatus::eOAIPhoneNumberWorkflowStatus OAIPhoneNumberWorkflowStatus::getValue() const {
    return m_value;
}

void OAIPhoneNumberWorkflowStatus::setValue(const OAIPhoneNumberWorkflowStatus::eOAIPhoneNumberWorkflowStatus& value){
    m_value = value;
    m_value_isSet = true;
}
bool OAIPhoneNumberWorkflowStatus::isSet() const {
    
    return m_value_isSet;
}

bool OAIPhoneNumberWorkflowStatus::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_value_isValid;
}

} // namespace OpenAPI
