openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: This API allows clients to access and modify container and tag configuration.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Tag Manager API
  version: v2
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
  x-origin:
  - format: google
    url: https://tagmanager.googleapis.com/$discovery/rest?version=v2
    version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: tagmanager
servers:
- url: https://tagmanager.googleapis.com/
tags:
- name: accounts
paths:
  /tagmanager/v2/accounts:
    get:
      description: Lists all GTM Accounts that a user has access to.
      operationId: tagmanager_accounts_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.manage.accounts
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.manage.accounts
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/accounts/containers:lookup:
    get:
      description: Looks up a Container by destination ID.
      operationId: tagmanager_accounts_containers_lookup
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{parent}/built_in_variables:
    get:
      description: Lists all the enabled Built-In Variables of a GTM Container.
      operationId: tagmanager_accounts_containers_workspaces_built_in_variables_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    post:
      description: Creates one or more GTM Built-In Variables.
      operationId: tagmanager_accounts_containers_workspaces_built_in_variables_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{parent}/clients:
    get:
      description: Lists all GTM Clients of a GTM container workspace.
      operationId: tagmanager_accounts_containers_workspaces_clients_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    post:
      description: Creates a GTM Client.
      operationId: tagmanager_accounts_containers_workspaces_clients_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{parent}/containers:
    get:
      description: Lists all Containers that belongs to a GTM Account.
      operationId: tagmanager_accounts_containers_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    post:
      description: Creates a Container.
      operationId: tagmanager_accounts_containers_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{parent}/destinations:
    get:
      description: Lists all Destinations linked to a GTM Container.
      operationId: tagmanager_accounts_containers_destinations_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{parent}/destinations:link:
    post:
      description: Adds a Destination to this Container and removes it from the Container
        to which it is currently linked.
      operationId: tagmanager_accounts_containers_destinations_link
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{parent}/environments:
    get:
      description: Lists all GTM Environments of a GTM Container.
      operationId: tagmanager_accounts_containers_environments_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    post:
      description: Creates a GTM Environment.
      operationId: tagmanager_accounts_containers_environments_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{parent}/folders:
    get:
      description: Lists all GTM Folders of a Container.
      operationId: tagmanager_accounts_containers_workspaces_folders_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    post:
      description: Creates a GTM Folder.
      operationId: tagmanager_accounts_containers_workspaces_folders_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{parent}/gtag_config:
    get:
      description: Lists all Google tag configs in a Container.
      operationId: tagmanager_accounts_containers_workspaces_gtag_config_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    post:
      description: Creates a Google tag config.
      operationId: tagmanager_accounts_containers_workspaces_gtag_config_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{parent}/tags:
    get:
      description: Lists all GTM Tags of a Container.
      operationId: tagmanager_accounts_containers_workspaces_tags_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    post:
      description: Creates a GTM Tag.
      operationId: tagmanager_accounts_containers_workspaces_tags_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{parent}/templates:
    get:
      description: Lists all GTM Templates of a GTM container workspace.
      operationId: tagmanager_accounts_containers_workspaces_templates_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    post:
      description: Creates a GTM Custom Template.
      operationId: tagmanager_accounts_containers_workspaces_templates_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{parent}/transformations:
    get:
      description: Lists all GTM Transformations of a GTM container workspace.
      operationId: tagmanager_accounts_containers_workspaces_transformations_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    post:
      description: Creates a GTM Transformation.
      operationId: tagmanager_accounts_containers_workspaces_transformations_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{parent}/triggers:
    get:
      description: Lists all GTM Triggers of a Container.
      operationId: tagmanager_accounts_containers_workspaces_triggers_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    post:
      description: Creates a GTM Trigger.
      operationId: tagmanager_accounts_containers_workspaces_triggers_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{parent}/user_permissions:
    get:
      description: List all users that have access to the account along with Account
        and Container user access granted to each of them.
      operationId: tagmanager_accounts_user_permissions_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.manage.users
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.manage.users
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    post:
      description: Creates a user's Account & Container access.
      operationId: tagmanager_accounts_user_permissions_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.manage.users
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.manage.users
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{parent}/variables:
    get:
      description: Lists all GTM Variables of a Container.
      operationId: tagmanager_accounts_containers_workspaces_variables_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    post:
      description: Creates a GTM Variable.
      operationId: tagmanager_accounts_containers_workspaces_variables_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{parent}/version_headers:
    get:
      description: Lists all Container Versions of a GTM Container.
      operationId: tagmanager_accounts_containers_version_headers_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containerversions
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containerversions
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{parent}/version_headers:latest:
    get:
      description: Gets the latest container version header
      operationId: tagmanager_accounts_containers_version_headers_latest
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{parent}/versions:live:
    get:
      description: Gets the live (i.e. published) container version
      operationId: tagmanager_accounts_containers_versions_live
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{parent}/workspaces:
    get:
      description: Lists all Workspaces that belong to a GTM Container.
      operationId: tagmanager_accounts_containers_workspaces_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    post:
      description: Creates a Workspace.
      operationId: tagmanager_accounts_containers_workspaces_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{parent}/zones:
    get:
      description: Lists all GTM Zones of a GTM container workspace.
      operationId: tagmanager_accounts_containers_workspaces_zones_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    post:
      description: Creates a GTM Zone.
      operationId: tagmanager_accounts_containers_workspaces_zones_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{path}:
    delete:
      description: "Removes a user from the account, revoking access to it and all\
        \ of its containers."
      operationId: tagmanager_accounts_user_permissions_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.manage.users
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.manage.users
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    get:
      description: Gets a user's Account & Container access.
      operationId: tagmanager_accounts_user_permissions_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.manage.users
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.manage.users
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    put:
      description: Updates a user's Account & Container access.
      operationId: tagmanager_accounts_user_permissions_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.manage.users
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.manage.users
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{path}/built_in_variables:revert:
    post:
      description: Reverts changes to a GTM Built-In Variables in a GTM Workspace.
      operationId: tagmanager_accounts_containers_workspaces_built_in_variables_revert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{path}/status:
    get:
      description: Finds conflicting and modified entities in the workspace.
      operationId: tagmanager_accounts_containers_workspaces_get_status
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{path}:combine:
    post:
      description: Combines Containers.
      operationId: tagmanager_accounts_containers_combine
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{path}:create_version:
    post:
      description: "Creates a Container Version from the entities present in the workspace,\
        \ deletes the workspace, and sets the base container version to the newly\
        \ created version."
      operationId: tagmanager_accounts_containers_workspaces_create_version
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containerversions
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containerversions
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{path}:entities:
    post:
      description: List all entities in a GTM Folder.
      operationId: tagmanager_accounts_containers_workspaces_folders_entities
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{path}:move_entities_to_folder:
    post:
      description: "Moves entities to a GTM Folder. If {folder_id} in the request\
        \ path equals 0, this will instead move entities out of the folder they currently\
        \ belong to."
      operationId: tagmanager_accounts_containers_workspaces_folders_move_entities_to_folder
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{path}:move_tag_id:
    post:
      description: Move Tag ID out of a Container.
      operationId: tagmanager_accounts_containers_move_tag_id
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{path}:publish:
    post:
      description: Publishes a Container Version.
      operationId: tagmanager_accounts_containers_versions_publish
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.publish
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.publish
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{path}:quick_preview:
    post:
      description: Quick previews a workspace by creating a fake container version
        from all entities in the provided workspace.
      operationId: tagmanager_accounts_containers_workspaces_quick_preview
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containerversions
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containerversions
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{path}:reauthorize:
    post:
      description: Re-generates the authorization code for a GTM Environment.
      operationId: tagmanager_accounts_containers_environments_reauthorize
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.publish
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.publish
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{path}:resolve_conflict:
    post:
      description: Resolves a merge conflict for a workspace entity by updating it
        to the resolved entity passed in the request.
      operationId: tagmanager_accounts_containers_workspaces_resolve_conflict
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{path}:revert:
    post:
      description: Reverts changes to a GTM Zone in a GTM Workspace.
      operationId: tagmanager_accounts_containers_workspaces_zones_revert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{path}:set_latest:
    post:
      description: Sets the latest version used for synchronization of workspaces
        when detecting conflicts and errors.
      operationId: tagmanager_accounts_containers_versions_set_latest
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{path}:snippet:
    get:
      description: Gets the tagging snippet for a Container.
      operationId: tagmanager_accounts_containers_snippet
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{path}:sync:
    post:
      description: Syncs a workspace to the latest container version by updating all
        unmodified workspace entities and displaying conflicts for modified entities.
      operationId: tagmanager_accounts_containers_workspaces_sync
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v2/{path}:undelete:
    post:
      description: Undeletes a Container Version.
      operationId: tagmanager_accounts_containers_versions_undelete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containerversions
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containerversions
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/tagmanager.delete.containers: Delete your
              Google Tag Manager containers
            https://www.googleapis.com/auth/tagmanager.edit.containers: "Manage your\
              \ Google Tag Manager container and its subcomponents, excluding versioning\
              \ and publishing"
            https://www.googleapis.com/auth/tagmanager.edit.containerversions: Manage
              your Google Tag Manager container versions
            https://www.googleapis.com/auth/tagmanager.manage.accounts: View and manage
              your Google Tag Manager accounts
            https://www.googleapis.com/auth/tagmanager.manage.users: Manage user permissions
              of your Google Tag Manager account and container
            https://www.googleapis.com/auth/tagmanager.publish: Publish your Google
              Tag Manager container versions
            https://www.googleapis.com/auth/tagmanager.readonly: View your Google
              Tag Manager container and its subcomponents
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/tagmanager.delete.containers: Delete your
              Google Tag Manager containers
            https://www.googleapis.com/auth/tagmanager.edit.containers: "Manage your\
              \ Google Tag Manager container and its subcomponents, excluding versioning\
              \ and publishing"
            https://www.googleapis.com/auth/tagmanager.edit.containerversions: Manage
              your Google Tag Manager container versions
            https://www.googleapis.com/auth/tagmanager.manage.accounts: View and manage
              your Google Tag Manager accounts
            https://www.googleapis.com/auth/tagmanager.manage.users: Manage user permissions
              of your Google Tag Manager account and container
            https://www.googleapis.com/auth/tagmanager.publish: Publish your Google
              Tag Manager container versions
            https://www.googleapis.com/auth/tagmanager.readonly: View your Google
              Tag Manager container and its subcomponents
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2c
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2c
