QT += network

HEADERS += \
# Models
    $${PWD}/OAIAccept_contract_200_response.h \
    $${PWD}/OAIAccept_contract_200_response_data.h \
    $${PWD}/OAICreate_chart_201_response.h \
    $${PWD}/OAICreate_chart_201_response_data.h \
    $${PWD}/OAICreate_ship_ship_scan_201_response.h \
    $${PWD}/OAICreate_ship_ship_scan_201_response_data.h \
    $${PWD}/OAICreate_ship_ship_scan_201_response_data_ships_inner.h \
    $${PWD}/OAICreate_ship_ship_scan_201_response_data_ships_inner_engine.h \
    $${PWD}/OAICreate_ship_ship_scan_201_response_data_ships_inner_frame.h \
    $${PWD}/OAICreate_ship_ship_scan_201_response_data_ships_inner_mounts_inner.h \
    $${PWD}/OAICreate_ship_ship_scan_201_response_data_ships_inner_reactor.h \
    $${PWD}/OAICreate_ship_system_scan_201_response.h \
    $${PWD}/OAICreate_ship_system_scan_201_response_data.h \
    $${PWD}/OAICreate_ship_system_scan_201_response_data_systems_inner.h \
    $${PWD}/OAICreate_ship_waypoint_scan_201_response.h \
    $${PWD}/OAICreate_ship_waypoint_scan_201_response_data.h \
    $${PWD}/OAICreate_ship_waypoint_scan_201_response_data_waypoints_inner.h \
    $${PWD}/OAICreate_survey_201_response.h \
    $${PWD}/OAICreate_survey_201_response_data.h \
    $${PWD}/OAICreate_survey_201_response_data_surveys_inner.h \
    $${PWD}/OAICreate_survey_201_response_data_surveys_inner_deposits_inner.h \
    $${PWD}/OAIDeliver_contract_200_response.h \
    $${PWD}/OAIDeliver_contract_200_response_data.h \
    $${PWD}/OAIDeliver_contract_request.h \
    $${PWD}/OAIDock_Ship_200_Response.h \
    $${PWD}/OAIDock_Ship_200_Response_data.h \
    $${PWD}/OAIExtract_resources_201_response.h \
    $${PWD}/OAIExtract_resources_201_response_data.h \
    $${PWD}/OAIExtract_resources_201_response_data_extraction.h \
    $${PWD}/OAIExtract_resources_201_response_data_extraction_yield.h \
    $${PWD}/OAIExtract_resources_request.h \
    $${PWD}/OAIFulfill_contract_200_response.h \
    $${PWD}/OAIGet_contract_200_response.h \
    $${PWD}/OAIGet_contracts_200_response.h \
    $${PWD}/OAIGet_faction_200_response.h \
    $${PWD}/OAIGet_factions_200_response.h \
    $${PWD}/OAIGet_jump_gate_200_response.h \
    $${PWD}/OAIGet_jump_gate_200_response_data.h \
    $${PWD}/OAIGet_jump_gate_200_response_data_connectedSystems_inner.h \
    $${PWD}/OAIGet_market_200_response.h \
    $${PWD}/OAIGet_market_200_response_data.h \
    $${PWD}/OAIGet_market_200_response_data_exports_inner.h \
    $${PWD}/OAIGet_market_200_response_data_tradeGoods_inner.h \
    $${PWD}/OAIGet_market_200_response_data_transactions_inner.h \
    $${PWD}/OAIGet_my_agent_200_response.h \
    $${PWD}/OAIGet_my_ship_200_response.h \
    $${PWD}/OAIGet_my_ship_cargo_200_response.h \
    $${PWD}/OAIGet_my_ships_200_response.h \
    $${PWD}/OAIGet_ship_cooldown_200_response.h \
    $${PWD}/OAIGet_ship_nav_200_response.h \
    $${PWD}/OAIGet_shipyard_200_response.h \
    $${PWD}/OAIGet_shipyard_200_response_data.h \
    $${PWD}/OAIGet_shipyard_200_response_data_shipTypes_inner.h \
    $${PWD}/OAIGet_shipyard_200_response_data_ships_inner.h \
    $${PWD}/OAIGet_shipyard_200_response_data_transactions_inner.h \
    $${PWD}/OAIGet_system_200_response.h \
    $${PWD}/OAIGet_system_waypoints_200_response.h \
    $${PWD}/OAIGet_system_waypoints_200_response_data_inner.h \
    $${PWD}/OAIGet_system_waypoints_200_response_data_inner_chart.h \
    $${PWD}/OAIGet_system_waypoints_200_response_data_inner_orbitals_inner.h \
    $${PWD}/OAIGet_system_waypoints_200_response_data_inner_traits_inner.h \
    $${PWD}/OAIGet_systems_200_response.h \
    $${PWD}/OAIGet_systems_200_response_data_inner.h \
    $${PWD}/OAIGet_systems_200_response_data_inner_factions_inner.h \
    $${PWD}/OAIGet_systems_200_response_data_inner_waypoints_inner.h \
    $${PWD}/OAIGet_systems_200_response_meta.h \
    $${PWD}/OAIGet_waypoint_200_response.h \
    $${PWD}/OAIJettison_200_response.h \
    $${PWD}/OAIJettison_200_response_data.h \
    $${PWD}/OAIJettison_request.h \
    $${PWD}/OAIJump_ship_200_response.h \
    $${PWD}/OAIJump_ship_200_response_data.h \
    $${PWD}/OAIJump_ship_request.h \
    $${PWD}/OAINavigate_ship_200_response.h \
    $${PWD}/OAINavigate_ship_200_response_data.h \
    $${PWD}/OAINavigate_ship_request.h \
    $${PWD}/OAIOrbit_Ship_200_Response.h \
    $${PWD}/OAIPatch_ship_nav_request.h \
    $${PWD}/OAIPurchase_Cargo_201_Response.h \
    $${PWD}/OAIPurchase_Cargo_201_Response_data.h \
    $${PWD}/OAIPurchase_Cargo_Request.h \
    $${PWD}/OAIPurchase_ship_201_response.h \
    $${PWD}/OAIPurchase_ship_201_response_data.h \
    $${PWD}/OAIPurchase_ship_request.h \
    $${PWD}/OAIRefuel_ship_200_response.h \
    $${PWD}/OAIRefuel_ship_200_response_data.h \
    $${PWD}/OAIRegister_201_response.h \
    $${PWD}/OAIRegister_201_response_data.h \
    $${PWD}/OAIRegister_201_response_data_agent.h \
    $${PWD}/OAIRegister_201_response_data_contract.h \
    $${PWD}/OAIRegister_201_response_data_contract_terms.h \
    $${PWD}/OAIRegister_201_response_data_contract_terms_deliver_inner.h \
    $${PWD}/OAIRegister_201_response_data_contract_terms_payment.h \
    $${PWD}/OAIRegister_201_response_data_faction.h \
    $${PWD}/OAIRegister_201_response_data_faction_traits_inner.h \
    $${PWD}/OAIRegister_201_response_data_ship.h \
    $${PWD}/OAIRegister_201_response_data_ship_cargo.h \
    $${PWD}/OAIRegister_201_response_data_ship_cargo_inventory_inner.h \
    $${PWD}/OAIRegister_201_response_data_ship_crew.h \
    $${PWD}/OAIRegister_201_response_data_ship_engine.h \
    $${PWD}/OAIRegister_201_response_data_ship_frame.h \
    $${PWD}/OAIRegister_201_response_data_ship_frame_requirements.h \
    $${PWD}/OAIRegister_201_response_data_ship_fuel.h \
    $${PWD}/OAIRegister_201_response_data_ship_fuel_consumed.h \
    $${PWD}/OAIRegister_201_response_data_ship_modules_inner.h \
    $${PWD}/OAIRegister_201_response_data_ship_mounts_inner.h \
    $${PWD}/OAIRegister_201_response_data_ship_nav.h \
    $${PWD}/OAIRegister_201_response_data_ship_nav_route.h \
    $${PWD}/OAIRegister_201_response_data_ship_nav_route_destination.h \
    $${PWD}/OAIRegister_201_response_data_ship_reactor.h \
    $${PWD}/OAIRegister_201_response_data_ship_registration.h \
    $${PWD}/OAIRegister_request.h \
    $${PWD}/OAISellCargoRequest.h \
    $${PWD}/OAISell_Cargo_201_Response.h \
    $${PWD}/OAIShip_Refine_200_Response.h \
    $${PWD}/OAIShip_Refine_200_Response_data.h \
    $${PWD}/OAIShip_Refine_200_Response_data_consumed_inner.h \
    $${PWD}/OAIShip_Refine_200_Response_data_cooldown.h \
    $${PWD}/OAIShip_refine_request.h \
    $${PWD}/OAITransfer_Cargo_200_Response.h \
    $${PWD}/OAITransfer_Cargo_Request.h \
# APIs
    $${PWD}/OAIAgentsApi.h \
    $${PWD}/OAIContractsApi.h \
    $${PWD}/OAIDefaultApi.h \
    $${PWD}/OAIFactionsApi.h \
    $${PWD}/OAIFleetApi.h \
    $${PWD}/OAISystemsApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAccept_contract_200_response.cpp \
    $${PWD}/OAIAccept_contract_200_response_data.cpp \
    $${PWD}/OAICreate_chart_201_response.cpp \
    $${PWD}/OAICreate_chart_201_response_data.cpp \
    $${PWD}/OAICreate_ship_ship_scan_201_response.cpp \
    $${PWD}/OAICreate_ship_ship_scan_201_response_data.cpp \
    $${PWD}/OAICreate_ship_ship_scan_201_response_data_ships_inner.cpp \
    $${PWD}/OAICreate_ship_ship_scan_201_response_data_ships_inner_engine.cpp \
    $${PWD}/OAICreate_ship_ship_scan_201_response_data_ships_inner_frame.cpp \
    $${PWD}/OAICreate_ship_ship_scan_201_response_data_ships_inner_mounts_inner.cpp \
    $${PWD}/OAICreate_ship_ship_scan_201_response_data_ships_inner_reactor.cpp \
    $${PWD}/OAICreate_ship_system_scan_201_response.cpp \
    $${PWD}/OAICreate_ship_system_scan_201_response_data.cpp \
    $${PWD}/OAICreate_ship_system_scan_201_response_data_systems_inner.cpp \
    $${PWD}/OAICreate_ship_waypoint_scan_201_response.cpp \
    $${PWD}/OAICreate_ship_waypoint_scan_201_response_data.cpp \
    $${PWD}/OAICreate_ship_waypoint_scan_201_response_data_waypoints_inner.cpp \
    $${PWD}/OAICreate_survey_201_response.cpp \
    $${PWD}/OAICreate_survey_201_response_data.cpp \
    $${PWD}/OAICreate_survey_201_response_data_surveys_inner.cpp \
    $${PWD}/OAICreate_survey_201_response_data_surveys_inner_deposits_inner.cpp \
    $${PWD}/OAIDeliver_contract_200_response.cpp \
    $${PWD}/OAIDeliver_contract_200_response_data.cpp \
    $${PWD}/OAIDeliver_contract_request.cpp \
    $${PWD}/OAIDock_Ship_200_Response.cpp \
    $${PWD}/OAIDock_Ship_200_Response_data.cpp \
    $${PWD}/OAIExtract_resources_201_response.cpp \
    $${PWD}/OAIExtract_resources_201_response_data.cpp \
    $${PWD}/OAIExtract_resources_201_response_data_extraction.cpp \
    $${PWD}/OAIExtract_resources_201_response_data_extraction_yield.cpp \
    $${PWD}/OAIExtract_resources_request.cpp \
    $${PWD}/OAIFulfill_contract_200_response.cpp \
    $${PWD}/OAIGet_contract_200_response.cpp \
    $${PWD}/OAIGet_contracts_200_response.cpp \
    $${PWD}/OAIGet_faction_200_response.cpp \
    $${PWD}/OAIGet_factions_200_response.cpp \
    $${PWD}/OAIGet_jump_gate_200_response.cpp \
    $${PWD}/OAIGet_jump_gate_200_response_data.cpp \
    $${PWD}/OAIGet_jump_gate_200_response_data_connectedSystems_inner.cpp \
    $${PWD}/OAIGet_market_200_response.cpp \
    $${PWD}/OAIGet_market_200_response_data.cpp \
    $${PWD}/OAIGet_market_200_response_data_exports_inner.cpp \
    $${PWD}/OAIGet_market_200_response_data_tradeGoods_inner.cpp \
    $${PWD}/OAIGet_market_200_response_data_transactions_inner.cpp \
    $${PWD}/OAIGet_my_agent_200_response.cpp \
    $${PWD}/OAIGet_my_ship_200_response.cpp \
    $${PWD}/OAIGet_my_ship_cargo_200_response.cpp \
    $${PWD}/OAIGet_my_ships_200_response.cpp \
    $${PWD}/OAIGet_ship_cooldown_200_response.cpp \
    $${PWD}/OAIGet_ship_nav_200_response.cpp \
    $${PWD}/OAIGet_shipyard_200_response.cpp \
    $${PWD}/OAIGet_shipyard_200_response_data.cpp \
    $${PWD}/OAIGet_shipyard_200_response_data_shipTypes_inner.cpp \
    $${PWD}/OAIGet_shipyard_200_response_data_ships_inner.cpp \
    $${PWD}/OAIGet_shipyard_200_response_data_transactions_inner.cpp \
    $${PWD}/OAIGet_system_200_response.cpp \
    $${PWD}/OAIGet_system_waypoints_200_response.cpp \
    $${PWD}/OAIGet_system_waypoints_200_response_data_inner.cpp \
    $${PWD}/OAIGet_system_waypoints_200_response_data_inner_chart.cpp \
    $${PWD}/OAIGet_system_waypoints_200_response_data_inner_orbitals_inner.cpp \
    $${PWD}/OAIGet_system_waypoints_200_response_data_inner_traits_inner.cpp \
    $${PWD}/OAIGet_systems_200_response.cpp \
    $${PWD}/OAIGet_systems_200_response_data_inner.cpp \
    $${PWD}/OAIGet_systems_200_response_data_inner_factions_inner.cpp \
    $${PWD}/OAIGet_systems_200_response_data_inner_waypoints_inner.cpp \
    $${PWD}/OAIGet_systems_200_response_meta.cpp \
    $${PWD}/OAIGet_waypoint_200_response.cpp \
    $${PWD}/OAIJettison_200_response.cpp \
    $${PWD}/OAIJettison_200_response_data.cpp \
    $${PWD}/OAIJettison_request.cpp \
    $${PWD}/OAIJump_ship_200_response.cpp \
    $${PWD}/OAIJump_ship_200_response_data.cpp \
    $${PWD}/OAIJump_ship_request.cpp \
    $${PWD}/OAINavigate_ship_200_response.cpp \
    $${PWD}/OAINavigate_ship_200_response_data.cpp \
    $${PWD}/OAINavigate_ship_request.cpp \
    $${PWD}/OAIOrbit_Ship_200_Response.cpp \
    $${PWD}/OAIPatch_ship_nav_request.cpp \
    $${PWD}/OAIPurchase_Cargo_201_Response.cpp \
    $${PWD}/OAIPurchase_Cargo_201_Response_data.cpp \
    $${PWD}/OAIPurchase_Cargo_Request.cpp \
    $${PWD}/OAIPurchase_ship_201_response.cpp \
    $${PWD}/OAIPurchase_ship_201_response_data.cpp \
    $${PWD}/OAIPurchase_ship_request.cpp \
    $${PWD}/OAIRefuel_ship_200_response.cpp \
    $${PWD}/OAIRefuel_ship_200_response_data.cpp \
    $${PWD}/OAIRegister_201_response.cpp \
    $${PWD}/OAIRegister_201_response_data.cpp \
    $${PWD}/OAIRegister_201_response_data_agent.cpp \
    $${PWD}/OAIRegister_201_response_data_contract.cpp \
    $${PWD}/OAIRegister_201_response_data_contract_terms.cpp \
    $${PWD}/OAIRegister_201_response_data_contract_terms_deliver_inner.cpp \
    $${PWD}/OAIRegister_201_response_data_contract_terms_payment.cpp \
    $${PWD}/OAIRegister_201_response_data_faction.cpp \
    $${PWD}/OAIRegister_201_response_data_faction_traits_inner.cpp \
    $${PWD}/OAIRegister_201_response_data_ship.cpp \
    $${PWD}/OAIRegister_201_response_data_ship_cargo.cpp \
    $${PWD}/OAIRegister_201_response_data_ship_cargo_inventory_inner.cpp \
    $${PWD}/OAIRegister_201_response_data_ship_crew.cpp \
    $${PWD}/OAIRegister_201_response_data_ship_engine.cpp \
    $${PWD}/OAIRegister_201_response_data_ship_frame.cpp \
    $${PWD}/OAIRegister_201_response_data_ship_frame_requirements.cpp \
    $${PWD}/OAIRegister_201_response_data_ship_fuel.cpp \
    $${PWD}/OAIRegister_201_response_data_ship_fuel_consumed.cpp \
    $${PWD}/OAIRegister_201_response_data_ship_modules_inner.cpp \
    $${PWD}/OAIRegister_201_response_data_ship_mounts_inner.cpp \
    $${PWD}/OAIRegister_201_response_data_ship_nav.cpp \
    $${PWD}/OAIRegister_201_response_data_ship_nav_route.cpp \
    $${PWD}/OAIRegister_201_response_data_ship_nav_route_destination.cpp \
    $${PWD}/OAIRegister_201_response_data_ship_reactor.cpp \
    $${PWD}/OAIRegister_201_response_data_ship_registration.cpp \
    $${PWD}/OAIRegister_request.cpp \
    $${PWD}/OAISellCargoRequest.cpp \
    $${PWD}/OAISell_Cargo_201_Response.cpp \
    $${PWD}/OAIShip_Refine_200_Response.cpp \
    $${PWD}/OAIShip_Refine_200_Response_data.cpp \
    $${PWD}/OAIShip_Refine_200_Response_data_consumed_inner.cpp \
    $${PWD}/OAIShip_Refine_200_Response_data_cooldown.cpp \
    $${PWD}/OAIShip_refine_request.cpp \
    $${PWD}/OAITransfer_Cargo_200_Response.cpp \
    $${PWD}/OAITransfer_Cargo_Request.cpp \
# APIs
    $${PWD}/OAIAgentsApi.cpp \
    $${PWD}/OAIContractsApi.cpp \
    $${PWD}/OAIDefaultApi.cpp \
    $${PWD}/OAIFactionsApi.cpp \
    $${PWD}/OAIFleetApi.cpp \
    $${PWD}/OAISystemsApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
