openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: ""
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Area120 Tables API
  version: v1alpha1
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://upload.wikimedia.org/wikipedia/commons/e/e1/YouTube_play_buttom_icon_%282013-2017%29.svg
  x-origin:
  - format: google
    url: https://area120tables.googleapis.com/$discovery/rest?version=v1alpha1
    version: v1
  x-providerName: googleapis.com
  x-serviceName: area120tables
servers:
- url: https://area120tables.googleapis.com/
tags:
- name: tables
- name: workspaces
paths:
  /v1alpha1/tables:
    get:
      description: Lists tables for the user.
      operationId: area120tables_tables_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/spreadsheets
        Oauth2c:
        - https://www.googleapis.com/auth/spreadsheets
      - Oauth2:
        - https://www.googleapis.com/auth/spreadsheets.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/spreadsheets.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/tables
        Oauth2c:
        - https://www.googleapis.com/auth/tables
      tags:
      - tables
      x-openapi-router-controller: openapi_server.controllers.tables_controller
  /v1alpha1/workspaces:
    get:
      description: Lists workspaces for the user.
      operationId: area120tables_workspaces_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/spreadsheets
        Oauth2c:
        - https://www.googleapis.com/auth/spreadsheets
      - Oauth2:
        - https://www.googleapis.com/auth/spreadsheets.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/spreadsheets.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/tables
        Oauth2c:
        - https://www.googleapis.com/auth/tables
      tags:
      - workspaces
      x-openapi-router-controller: openapi_server.controllers.workspaces_controller
  /v1alpha1/{name}:
    delete:
      description: Deletes a row.
      operationId: area120tables_tables_rows_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/spreadsheets
        Oauth2c:
        - https://www.googleapis.com/auth/spreadsheets
      - Oauth2:
        - https://www.googleapis.com/auth/tables
        Oauth2c:
        - https://www.googleapis.com/auth/tables
      tags:
      - tables
      x-openapi-router-controller: openapi_server.controllers.tables_controller
    get:
      description: Gets a workspace. Returns NOT_FOUND if the workspace does not exist.
      operationId: area120tables_workspaces_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/spreadsheets
        Oauth2c:
        - https://www.googleapis.com/auth/spreadsheets
      - Oauth2:
        - https://www.googleapis.com/auth/spreadsheets.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/spreadsheets.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/tables
        Oauth2c:
        - https://www.googleapis.com/auth/tables
      tags:
      - workspaces
      x-openapi-router-controller: openapi_server.controllers.workspaces_controller
    patch:
      description: Updates a row.
      operationId: area120tables_tables_rows_patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/spreadsheets
        Oauth2c:
        - https://www.googleapis.com/auth/spreadsheets
      - Oauth2:
        - https://www.googleapis.com/auth/tables
        Oauth2c:
        - https://www.googleapis.com/auth/tables
      tags:
      - tables
      x-openapi-router-controller: openapi_server.controllers.tables_controller
  /v1alpha1/{parent}/rows:
    get:
      description: Lists rows in a table. Returns NOT_FOUND if the table does not
        exist.
      operationId: area120tables_tables_rows_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/spreadsheets
        Oauth2c:
        - https://www.googleapis.com/auth/spreadsheets
      - Oauth2:
        - https://www.googleapis.com/auth/spreadsheets.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/spreadsheets.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/tables
        Oauth2c:
        - https://www.googleapis.com/auth/tables
      tags:
      - tables
      x-openapi-router-controller: openapi_server.controllers.tables_controller
    post:
      description: Creates a row.
      operationId: area120tables_tables_rows_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/spreadsheets
        Oauth2c:
        - https://www.googleapis.com/auth/spreadsheets
      - Oauth2:
        - https://www.googleapis.com/auth/tables
        Oauth2c:
        - https://www.googleapis.com/auth/tables
      tags:
      - tables
      x-openapi-router-controller: openapi_server.controllers.tables_controller
  /v1alpha1/{parent}/rows:batchCreate:
    post:
      description: Creates multiple rows.
      operationId: area120tables_tables_rows_batch_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/spreadsheets
        Oauth2c:
        - https://www.googleapis.com/auth/spreadsheets
      - Oauth2:
        - https://www.googleapis.com/auth/tables
        Oauth2c:
        - https://www.googleapis.com/auth/tables
      tags:
      - tables
      x-openapi-router-controller: openapi_server.controllers.tables_controller
  /v1alpha1/{parent}/rows:batchDelete:
    post:
      description: Deletes multiple rows.
      operationId: area120tables_tables_rows_batch_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/spreadsheets
        Oauth2c:
        - https://www.googleapis.com/auth/spreadsheets
      - Oauth2:
        - https://www.googleapis.com/auth/tables
        Oauth2c:
        - https://www.googleapis.com/auth/tables
      tags:
      - tables
      x-openapi-router-controller: openapi_server.controllers.tables_controller
  /v1alpha1/{parent}/rows:batchUpdate:
    post:
      description: Updates multiple rows.
      operationId: area120tables_tables_rows_batch_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/spreadsheets
        Oauth2c:
        - https://www.googleapis.com/auth/spreadsheets
      - Oauth2:
        - https://www.googleapis.com/auth/tables
        Oauth2c:
        - https://www.googleapis.com/auth/tables
      tags:
      - tables
      x-openapi-router-controller: openapi_server.controllers.tables_controller
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/drive: "See, edit, create, and delete\
              \ all of your Google Drive files"
            https://www.googleapis.com/auth/drive.file: "See, edit, create, and delete\
              \ only the specific Google Drive files you use with this app"
            https://www.googleapis.com/auth/drive.readonly: See and download all your
              Google Drive files
            https://www.googleapis.com/auth/spreadsheets: "See, edit, create, and\
              \ delete all your Google Sheets spreadsheets"
            https://www.googleapis.com/auth/spreadsheets.readonly: See all your Google
              Sheets spreadsheets
            https://www.googleapis.com/auth/tables: "See, edit, create, and delete\
              \ your tables in Tables by Area 120"
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/drive: "See, edit, create, and delete\
              \ all of your Google Drive files"
            https://www.googleapis.com/auth/drive.file: "See, edit, create, and delete\
              \ only the specific Google Drive files you use with this app"
            https://www.googleapis.com/auth/drive.readonly: See and download all your
              Google Drive files
            https://www.googleapis.com/auth/spreadsheets: "See, edit, create, and\
              \ delete all your Google Sheets spreadsheets"
            https://www.googleapis.com/auth/spreadsheets.readonly: See all your Google
              Sheets spreadsheets
            https://www.googleapis.com/auth/tables: "See, edit, create, and delete\
              \ your tables in Tables by Area 120"
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2c
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2c
