openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: "Display & Video 360 API allows users to automate complex Display &\
    \ Video 360 workflows, such as creating insertion orders and setting targeting\
    \ options for individual line items."
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Display & Video 360 API
  version: v3
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
  x-origin:
  - format: google
    url: https://displayvideo.googleapis.com/$discovery/rest?version=v3
    version: v1
  x-preferred: false
  x-providerName: googleapis.com
  x-serviceName: displayvideo
servers:
- url: https://displayvideo.googleapis.com/
tags:
- name: advertisers
- name: combinedAudiences
- name: customBiddingAlgorithms
- name: customLists
- name: firstAndThirdPartyAudiences
- name: floodlightGroups
- name: googleAudiences
- name: guaranteedOrders
- name: inventorySourceGroups
- name: inventorySources
- name: media
- name: partners
- name: sdfdownloadtasks
- name: targetingTypes
- name: users
paths:
  /download/{resourceName}:
    get:
      description: "Downloads media. Download is supported on the URI `/download/{resource_name=**}?alt=media.`\
        \ **Note**: Download requests will not be successful without including `alt=media`\
        \ query string."
      operationId: displayvideo.media.download
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      - Oauth2:
        - https://www.googleapis.com/auth/doubleclickbidmanager
        Oauth2c:
        - https://www.googleapis.com/auth/doubleclickbidmanager
      tags:
      - media
      x-accepts:
      - application/json
  /media/{resourceName}:
    post:
      description: "Uploads media. Upload is supported on the URI `/upload/media/{resource_name=**}?upload_type=media.`\
        \ **Note**: Upload requests will not be successful without including `upload_type=media`\
        \ query string."
      operationId: displayvideo.media.upload
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      - Oauth2:
        - https://www.googleapis.com/auth/doubleclickbidmanager
        Oauth2c:
        - https://www.googleapis.com/auth/doubleclickbidmanager
      tags:
      - media
      x-content-type: application/octet-stream
      x-accepts:
      - application/json
  /v3/advertisers:
    get:
      description: Lists advertisers that are accessible to the current user. The
        order is defined by the order_by parameter. A single partner_id is required.
        Cross-partner listing is not supported.
      operationId: displayvideo.advertisers.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
    post:
      description: "Creates a new advertiser. Returns the newly created advertiser\
        \ if successful. **This method regularly experiences high latency.** We recommend\
        \ [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout)\
        \ to avoid errors."
      operationId: displayvideo.advertisers.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}:
    delete:
      description: "Deletes an advertiser. Deleting an advertiser will delete all\
        \ of its child resources, for example, campaigns, insertion orders and line\
        \ items. A deleted advertiser cannot be recovered."
      operationId: displayvideo.advertisers.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
    get:
      description: Gets an advertiser.
      operationId: displayvideo.advertisers.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
    patch:
      description: Updates an existing advertiser. Returns the updated advertiser
        if successful.
      operationId: displayvideo.advertisers.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/adGroupAds:
    get:
      description: Lists ad group ads.
      operationId: displayvideo.advertisers.adGroupAds.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/adGroupAds/{adGroupAdId}:
    get:
      description: Gets an ad group ad.
      operationId: displayvideo.advertisers.adGroupAds.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/adGroups:
    get:
      description: Lists ad groups.
      operationId: displayvideo.advertisers.adGroups.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/adGroups/{adGroupId}:
    get:
      description: Gets an ad group.
      operationId: displayvideo.advertisers.adGroups.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/adGroups/{adGroupId}/targetingTypes/{targetingType}/assignedTargetingOptions:
    get:
      description: Lists the targeting options assigned to an ad group. Inherited
        assigned targeting options are not included.
      operationId: displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
  ? /v3/advertisers/{advertiserId}/adGroups/{adGroupId}/targetingTypes/{targetingType}/assignedTargetingOptions/{assignedTargetingOptionId}
  : get:
      description: Gets a single targeting option assigned to an ad group. Inherited
        assigned targeting options are not included.
      operationId: displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/adGroups:bulkListAdGroupAssignedTargetingOptions:
    get:
      description: Lists assigned targeting options for multiple ad groups across
        targeting types. Inherited assigned targeting options are not included.
      operationId: displayvideo.advertisers.adGroups.bulkListAdGroupAssignedTargetingOptions
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/assets:
    post:
      description: "Uploads an asset. Returns the ID of the newly uploaded asset if\
        \ successful. The asset file size should be no more than 10 MB for images,\
        \ 200 MB for ZIP files, and 1 GB for videos. Must be used within the [multipart\
        \ media upload process](/display-video/api/guides/how-tos/upload#multipart).\
        \ Examples using provided client libraries can be found in our [Creating Creatives\
        \ guide](/display-video/api/guides/creating-creatives/overview#upload_an_asset)."
      operationId: displayvideo.advertisers.assets.upload
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/octet-stream
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/campaigns:
    get:
      description: "Lists campaigns in an advertiser. The order is defined by the\
        \ order_by parameter. If a filter by entity_status is not specified, campaigns\
        \ with `ENTITY_STATUS_ARCHIVED` will not be included in the results."
      operationId: displayvideo.advertisers.campaigns.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      - Oauth2:
        - https://www.googleapis.com/auth/display-video-mediaplanning
        Oauth2c:
        - https://www.googleapis.com/auth/display-video-mediaplanning
      tags:
      - advertisers
      x-accepts:
      - application/json
    post:
      description: Creates a new campaign. Returns the newly created campaign if successful.
      operationId: displayvideo.advertisers.campaigns.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      - Oauth2:
        - https://www.googleapis.com/auth/display-video-mediaplanning
        Oauth2c:
        - https://www.googleapis.com/auth/display-video-mediaplanning
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/campaigns/{campaignId}:
    delete:
      description: "Permanently deletes a campaign. A deleted campaign cannot be recovered.\
        \ The campaign should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`,\
        \ to be able to delete it. **This method regularly experiences high latency.**\
        \ We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout)\
        \ to avoid errors."
      operationId: displayvideo.advertisers.campaigns.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      - Oauth2:
        - https://www.googleapis.com/auth/display-video-mediaplanning
        Oauth2c:
        - https://www.googleapis.com/auth/display-video-mediaplanning
      tags:
      - advertisers
      x-accepts:
      - application/json
    get:
      description: Gets a campaign.
      operationId: displayvideo.advertisers.campaigns.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      - Oauth2:
        - https://www.googleapis.com/auth/display-video-mediaplanning
        Oauth2c:
        - https://www.googleapis.com/auth/display-video-mediaplanning
      tags:
      - advertisers
      x-accepts:
      - application/json
    patch:
      description: Updates an existing campaign. Returns the updated campaign if successful.
      operationId: displayvideo.advertisers.campaigns.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      - Oauth2:
        - https://www.googleapis.com/auth/display-video-mediaplanning
        Oauth2c:
        - https://www.googleapis.com/auth/display-video-mediaplanning
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/campaigns/{campaignId}/targetingTypes/{targetingType}/assignedTargetingOptions:
    get:
      description: Lists the targeting options assigned to a campaign for a specified
        targeting type.
      operationId: displayvideo.advertisers.campaigns.targetingTypes.assignedTargetingOptions.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
  ? /v3/advertisers/{advertiserId}/campaigns/{campaignId}/targetingTypes/{targetingType}/assignedTargetingOptions/{assignedTargetingOptionId}
  : get:
      description: Gets a single targeting option assigned to a campaign.
      operationId: displayvideo.advertisers.campaigns.targetingTypes.assignedTargetingOptions.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/campaigns/{campaignId}:listAssignedTargetingOptions:
    get:
      description: Lists assigned targeting options of a campaign across targeting
        types.
      operationId: displayvideo.advertisers.campaigns.listAssignedTargetingOptions
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/channels:
    get:
      description: Lists channels for a partner or advertiser.
      operationId: displayvideo.advertisers.channels.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
    post:
      description: Creates a new channel. Returns the newly created channel if successful.
      operationId: displayvideo.advertisers.channels.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/channels/{channelId}:
    patch:
      description: Updates a channel. Returns the updated channel if successful.
      operationId: displayvideo.advertisers.channels.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/channels/{channelId}/sites:
    get:
      description: Lists sites in a channel.
      operationId: displayvideo.advertisers.channels.sites.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/channels/{channelId}/sites/{urlOrAppId}:
    delete:
      description: Deletes a site from a channel.
      operationId: displayvideo.advertisers.channels.sites.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/channels/{channelId}/sites:bulkEdit:
    post:
      description: Bulk edits sites under a single channel. The operation will delete
        the sites provided in BulkEditSitesRequest.deleted_sites and then create the
        sites provided in BulkEditSitesRequest.created_sites.
      operationId: displayvideo.advertisers.channels.sites.bulkEdit
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/channels/{channelId}/sites:replace:
    post:
      description: "Replaces all of the sites under a single channel. The operation\
        \ will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites.\
        \ **This method regularly experiences high latency.** We recommend [increasing\
        \ your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout)\
        \ to avoid errors."
      operationId: displayvideo.advertisers.channels.sites.replace
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/creatives:
    get:
      description: "Lists creatives in an advertiser. The order is defined by the\
        \ order_by parameter. If a filter by entity_status is not specified, creatives\
        \ with `ENTITY_STATUS_ARCHIVED` will not be included in the results."
      operationId: displayvideo.advertisers.creatives.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
    post:
      description: "Creates a new creative. Returns the newly created creative if\
        \ successful. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011)\
        \ or greater for the parent advertiser or partner is required to make this\
        \ request."
      operationId: displayvideo.advertisers.creatives.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/creatives/{creativeId}:
    delete:
      description: "Deletes a creative. Returns error code `NOT_FOUND` if the creative\
        \ does not exist. The creative should be archived first, i.e. set entity_status\
        \ to `ENTITY_STATUS_ARCHIVED`, before it can be deleted. A [\"Standard\" user\
        \ role](//support.google.com/displayvideo/answer/2723011) or greater for the\
        \ parent advertiser or partner is required to make this request."
      operationId: displayvideo.advertisers.creatives.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
    get:
      description: Gets a creative.
      operationId: displayvideo.advertisers.creatives.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
    patch:
      description: "Updates an existing creative. Returns the updated creative if\
        \ successful. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011)\
        \ or greater for the parent advertiser or partner is required to make this\
        \ request."
      operationId: displayvideo.advertisers.creatives.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/insertionOrders:
    get:
      description: "Lists insertion orders in an advertiser. The order is defined\
        \ by the order_by parameter. If a filter by entity_status is not specified,\
        \ insertion orders with `ENTITY_STATUS_ARCHIVED` will not be included in the\
        \ results."
      operationId: displayvideo.advertisers.insertionOrders.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
    post:
      description: Creates a new insertion order. Returns the newly created insertion
        order if successful.
      operationId: displayvideo.advertisers.insertionOrders.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/insertionOrders/{insertionOrderId}:
    delete:
      description: "Deletes an insertion order. Returns error code `NOT_FOUND` if\
        \ the insertion order does not exist. The insertion order should be archived\
        \ first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to\
        \ delete it."
      operationId: displayvideo.advertisers.insertionOrders.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
    get:
      description: Gets an insertion order. Returns error code `NOT_FOUND` if the
        insertion order does not exist.
      operationId: displayvideo.advertisers.insertionOrders.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
    patch:
      description: Updates an existing insertion order. Returns the updated insertion
        order if successful.
      operationId: displayvideo.advertisers.insertionOrders.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/insertionOrders/{insertionOrderId}/targetingTypes/{targetingType}/assignedTargetingOptions:
    get:
      description: Lists the targeting options assigned to an insertion order.
      operationId: displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
    post:
      description: "Assigns a targeting option to an insertion order. Returns the\
        \ assigned targeting option if successful. Supported targeting types: * `TARGETING_TYPE_AGE_RANGE`\
        \ * `TARGETING_TYPE_BROWSER` * `TARGETING_TYPE_CATEGORY` * `TARGETING_TYPE_CHANNEL`\
        \ * `TARGETING_TYPE_DEVICE_MAKE_MODEL` * `TARGETING_TYPE_DIGITAL_CONTENT_LABEL_EXCLUSION`\
        \ * `TARGETING_TYPE_ENVIRONMENT` * `TARGETING_TYPE_GENDER` * `TARGETING_TYPE_KEYWORD`\
        \ * `TARGETING_TYPE_LANGUAGE` * `TARGETING_TYPE_NEGATIVE_KEYWORD_LIST` * `TARGETING_TYPE_OPERATING_SYSTEM`\
        \ * `TARGETING_TYPE_PARENTAL_STATUS` * `TARGETING_TYPE_SENSITIVE_CATEGORY_EXCLUSION`\
        \ * `TARGETING_TYPE_VIEWABILITY`"
      operationId: displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  ? /v3/advertisers/{advertiserId}/insertionOrders/{insertionOrderId}/targetingTypes/{targetingType}/assignedTargetingOptions/{assignedTargetingOptionId}
  : delete:
      description: "Deletes an assigned targeting option from an insertion order.\
        \ Supported targeting types: * `TARGETING_TYPE_AGE_RANGE` * `TARGETING_TYPE_BROWSER`\
        \ * `TARGETING_TYPE_CATEGORY` * `TARGETING_TYPE_CHANNEL` * `TARGETING_TYPE_DEVICE_MAKE_MODEL`\
        \ * `TARGETING_TYPE_DIGITAL_CONTENT_LABEL_EXCLUSION` * `TARGETING_TYPE_ENVIRONMENT`\
        \ * `TARGETING_TYPE_GENDER` * `TARGETING_TYPE_KEYWORD` * `TARGETING_TYPE_LANGUAGE`\
        \ * `TARGETING_TYPE_NEGATIVE_KEYWORD_LIST` * `TARGETING_TYPE_OPERATING_SYSTEM`\
        \ * `TARGETING_TYPE_PARENTAL_STATUS` * `TARGETING_TYPE_SENSITIVE_CATEGORY_EXCLUSION`\
        \ * `TARGETING_TYPE_VIEWABILITY`"
      operationId: displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
    get:
      description: Gets a single targeting option assigned to an insertion order.
      operationId: displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/insertionOrders/{insertionOrderId}:listAssignedTargetingOptions:
    get:
      description: Lists assigned targeting options of an insertion order across targeting
        types.
      operationId: displayvideo.advertisers.insertionOrders.listAssignedTargetingOptions
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/invoices:
    get:
      description: Lists invoices posted for an advertiser in a given month. Invoices
        generated by billing profiles with a "Partner" invoice level are not retrievable
        through this method.
      operationId: displayvideo.advertisers.invoices.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      - Oauth2:
        - https://www.googleapis.com/auth/display-video-mediaplanning
        Oauth2c:
        - https://www.googleapis.com/auth/display-video-mediaplanning
      tags:
      - advertisers
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/invoices:lookupInvoiceCurrency:
    get:
      description: Retrieves the invoice currency used by an advertiser in a given
        month.
      operationId: displayvideo.advertisers.invoices.lookupInvoiceCurrency
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      - Oauth2:
        - https://www.googleapis.com/auth/display-video-mediaplanning
        Oauth2c:
        - https://www.googleapis.com/auth/display-video-mediaplanning
      tags:
      - advertisers
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/lineItems:
    get:
      description: "Lists line items in an advertiser. The order is defined by the\
        \ order_by parameter. If a filter by entity_status is not specified, line\
        \ items with `ENTITY_STATUS_ARCHIVED` will not be included in the results."
      operationId: displayvideo.advertisers.lineItems.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
    post:
      description: Creates a new line item. Returns the newly created line item if
        successful. YouTube & Partners line items cannot be created or updated using
        the API.
      operationId: displayvideo.advertisers.lineItems.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/lineItems/{lineItemId}:
    delete:
      description: "Deletes a line item. Returns error code `NOT_FOUND` if the line\
        \ item does not exist. The line item should be archived first, i.e. set entity_status\
        \ to `ENTITY_STATUS_ARCHIVED`, to be able to delete it. YouTube & Partners\
        \ line items cannot be created or updated using the API."
      operationId: displayvideo.advertisers.lineItems.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
    get:
      description: Gets a line item.
      operationId: displayvideo.advertisers.lineItems.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
    patch:
      description: "Updates an existing line item. Returns the updated line item if\
        \ successful. Requests to this endpoint cannot be made concurrently with the\
        \ following requests updating the same line item: * BulkEditAssignedTargetingOptions\
        \ * BulkUpdateLineItems * assignedTargetingOptions.create * assignedTargetingOptions.delete\
        \ YouTube & Partners line items cannot be created or updated using the API.\
        \ **This method regularly experiences high latency.** We recommend [increasing\
        \ your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout)\
        \ to avoid errors."
      operationId: displayvideo.advertisers.lineItems.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/lineItems/{lineItemId}/targetingTypes/{targetingType}/assignedTargetingOptions:
    get:
      description: Lists the targeting options assigned to a line item.
      operationId: displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
    post:
      description: "Assigns a targeting option to a line item. Returns the assigned\
        \ targeting option if successful. Requests to this endpoint cannot be made\
        \ concurrently with the following requests updating the same line item: *\
        \ lineItems.bulkEditAssignedTargetingOptions * lineItems.bulkUpdate * lineItems.patch\
        \ * DeleteLineItemAssignedTargetingOption YouTube & Partners line items cannot\
        \ be created or updated using the API."
      operationId: displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  ? /v3/advertisers/{advertiserId}/lineItems/{lineItemId}/targetingTypes/{targetingType}/assignedTargetingOptions/{assignedTargetingOptionId}
  : delete:
      description: "Deletes an assigned targeting option from a line item. Requests\
        \ to this endpoint cannot be made concurrently with the following requests\
        \ updating the same line item: * lineItems.bulkEditAssignedTargetingOptions\
        \ * lineItems.bulkUpdate * lineItems.patch * CreateLineItemAssignedTargetingOption\
        \ YouTube & Partners line items cannot be created or updated using the API."
      operationId: displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
    get:
      description: Gets a single targeting option assigned to a line item.
      operationId: displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/lineItems/{lineItemId}:duplicate:
    post:
      description: "Duplicates a line item. Returns the ID of the created line item\
        \ if successful. YouTube & Partners line items cannot be created or updated\
        \ using the API. **This method regularly experiences high latency.** We recommend\
        \ [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout)\
        \ to avoid errors."
      operationId: displayvideo.advertisers.lineItems.duplicate
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/lineItems:bulkEditAssignedTargetingOptions:
    post:
      description: "Bulk edits targeting options under multiple line items. The operation\
        \ will delete the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.delete_requests\
        \ and then create the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.create_requests.\
        \ Requests to this endpoint cannot be made concurrently with the following\
        \ requests updating the same line item: * lineItems.bulkUpdate * lineItems.patch\
        \ * assignedTargetingOptions.create * assignedTargetingOptions.delete YouTube\
        \ & Partners line items cannot be created or updated using the API."
      operationId: displayvideo.advertisers.lineItems.bulkEditAssignedTargetingOptions
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/lineItems:bulkListAssignedTargetingOptions:
    get:
      description: Lists assigned targeting options for multiple line items across
        targeting types.
      operationId: displayvideo.advertisers.lineItems.bulkListAssignedTargetingOptions
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/lineItems:bulkUpdate:
    post:
      description: "Updates multiple line items. Requests to this endpoint cannot\
        \ be made concurrently with the following requests updating the same line\
        \ item: * BulkEditAssignedTargetingOptions * UpdateLineItem * assignedTargetingOptions.create\
        \ * assignedTargetingOptions.delete YouTube & Partners line items cannot be\
        \ created or updated using the API."
      operationId: displayvideo.advertisers.lineItems.bulkUpdate
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/lineItems:generateDefault:
    post:
      description: "Creates a new line item with settings (including targeting) inherited\
        \ from the insertion order and an `ENTITY_STATUS_DRAFT` entity_status. Returns\
        \ the newly created line item if successful. There are default values based\
        \ on the three fields: * The insertion order's insertion_order_type * The\
        \ insertion order's automation_type * The given line_item_type YouTube & Partners\
        \ line items cannot be created or updated using the API."
      operationId: displayvideo.advertisers.lineItems.generateDefault
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/locationLists:
    get:
      description: Lists location lists based on a given advertiser id.
      operationId: displayvideo.advertisers.locationLists.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
    post:
      description: Creates a new location list. Returns the newly created location
        list if successful.
      operationId: displayvideo.advertisers.locationLists.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/locationLists/{locationListId}:
    patch:
      description: Updates a location list. Returns the updated location list if successful.
      operationId: displayvideo.advertisers.locationLists.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations:
    get:
      description: Lists locations assigned to a location list.
      operationId: displayvideo.advertisers.locationLists.assignedLocations.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
    post:
      description: Creates an assignment between a location and a location list.
      operationId: displayvideo.advertisers.locationLists.assignedLocations.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{assignedLocationId}:
    delete:
      description: Deletes the assignment between a location and a location list.
      operationId: displayvideo.advertisers.locationLists.assignedLocations.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations:bulkEdit:
    post:
      description: Bulk edits multiple assignments between locations and a single
        location list. The operation will delete the assigned locations provided in
        deletedAssignedLocations and then create the assigned locations provided in
        createdAssignedLocations.
      operationId: displayvideo.advertisers.locationLists.assignedLocations.bulkEdit
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/negativeKeywordLists:
    get:
      description: Lists negative keyword lists based on a given advertiser id.
      operationId: displayvideo.advertisers.negativeKeywordLists.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
    post:
      description: Creates a new negative keyword list. Returns the newly created
        negative keyword list if successful.
      operationId: displayvideo.advertisers.negativeKeywordLists.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListId}:
    patch:
      description: Updates a negative keyword list. Returns the updated negative keyword
        list if successful.
      operationId: displayvideo.advertisers.negativeKeywordLists.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListId}/negativeKeywords:
    get:
      description: Lists negative keywords in a negative keyword list.
      operationId: displayvideo.advertisers.negativeKeywordLists.negativeKeywords.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListId}/negativeKeywords/{keywordValue}:
    delete:
      description: Deletes a negative keyword from a negative keyword list.
      operationId: displayvideo.advertisers.negativeKeywordLists.negativeKeywords.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListId}/negativeKeywords:bulkEdit:
    post:
      description: Bulk edits negative keywords in a single negative keyword list.
        The operation will delete the negative keywords provided in BulkEditNegativeKeywordsRequest.deleted_negative_keywords
        and then create the negative keywords provided in BulkEditNegativeKeywordsRequest.created_negative_keywords.
        This operation is guaranteed to be atomic and will never result in a partial
        success or partial failure.
      operationId: displayvideo.advertisers.negativeKeywordLists.negativeKeywords.bulkEdit
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListId}/negativeKeywords:replace:
    post:
      description: Replaces all negative keywords in a single negative keyword list.
        The operation will replace the keywords in a negative keyword list with keywords
        provided in ReplaceNegativeKeywordsRequest.new_negative_keywords.
      operationId: displayvideo.advertisers.negativeKeywordLists.negativeKeywords.replace
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/targetingTypes/{targetingType}/assignedTargetingOptions:
    get:
      description: Lists the targeting options assigned to an advertiser.
      operationId: displayvideo.advertisers.targetingTypes.assignedTargetingOptions.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
    post:
      description: Assigns a targeting option to an advertiser. Returns the assigned
        targeting option if successful.
      operationId: displayvideo.advertisers.targetingTypes.assignedTargetingOptions.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}/targetingTypes/{targetingType}/assignedTargetingOptions/{assignedTargetingOptionId}:
    delete:
      description: Deletes an assigned targeting option from an advertiser.
      operationId: displayvideo.advertisers.targetingTypes.assignedTargetingOptions.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
    get:
      description: Gets a single targeting option assigned to an advertiser.
      operationId: displayvideo.advertisers.targetingTypes.assignedTargetingOptions.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}:audit:
    get:
      description: Audits an advertiser. Returns the counts of used entities per resource
        type under the advertiser provided. Used entities count towards their respective
        resource limit. See https://support.google.com/displayvideo/answer/6071450.
      operationId: displayvideo.advertisers.audit
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}:editAssignedTargetingOptions:
    post:
      description: Edits targeting options under a single advertiser. The operation
        will delete the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.delete_requests
        and then create the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.create_requests
        .
      operationId: displayvideo.advertisers.editAssignedTargetingOptions
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/advertisers/{advertiserId}:listAssignedTargetingOptions:
    get:
      description: Lists assigned targeting options of an advertiser across targeting
        types.
      operationId: displayvideo.advertisers.listAssignedTargetingOptions
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - advertisers
      x-accepts:
      - application/json
  /v3/combinedAudiences:
    get:
      description: Lists combined audiences. The order is defined by the order_by
        parameter.
      operationId: displayvideo.combinedAudiences.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - combinedAudiences
      x-accepts:
      - application/json
  /v3/combinedAudiences/{combinedAudienceId}:
    get:
      description: Gets a combined audience.
      operationId: displayvideo.combinedAudiences.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - combinedAudiences
      x-accepts:
      - application/json
  /v3/customBiddingAlgorithms:
    get:
      description: Lists custom bidding algorithms that are accessible to the current
        user and can be used in bidding stratgies. The order is defined by the order_by
        parameter.
      operationId: displayvideo.customBiddingAlgorithms.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - customBiddingAlgorithms
      x-accepts:
      - application/json
    post:
      description: Creates a new custom bidding algorithm. Returns the newly created
        custom bidding algorithm if successful.
      operationId: displayvideo.customBiddingAlgorithms.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - customBiddingAlgorithms
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/customBiddingAlgorithms/{customBiddingAlgorithmId}:
    get:
      description: Gets a custom bidding algorithm.
      operationId: displayvideo.customBiddingAlgorithms.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - customBiddingAlgorithms
      x-accepts:
      - application/json
    patch:
      description: Updates an existing custom bidding algorithm. Returns the updated
        custom bidding algorithm if successful.
      operationId: displayvideo.customBiddingAlgorithms.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - customBiddingAlgorithms
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/customBiddingAlgorithms/{customBiddingAlgorithmId}/rules:
    get:
      description: Lists rules resources that belong to the given algorithm. The order
        is defined by the order_by parameter.
      operationId: displayvideo.customBiddingAlgorithms.rules.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - customBiddingAlgorithms
      x-accepts:
      - application/json
    post:
      description: Creates a new rules resource. Returns the newly created rules resource
        if successful.
      operationId: displayvideo.customBiddingAlgorithms.rules.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - customBiddingAlgorithms
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/customBiddingAlgorithms/{customBiddingAlgorithmId}/rules/{customBiddingAlgorithmRulesId}:
    get:
      description: Retrieves a rules resource.
      operationId: displayvideo.customBiddingAlgorithms.rules.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - customBiddingAlgorithms
      x-accepts:
      - application/json
  /v3/customBiddingAlgorithms/{customBiddingAlgorithmId}/scripts:
    get:
      description: Lists custom bidding scripts that belong to the given algorithm.
        The order is defined by the order_by parameter.
      operationId: displayvideo.customBiddingAlgorithms.scripts.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - customBiddingAlgorithms
      x-accepts:
      - application/json
    post:
      description: Creates a new custom bidding script. Returns the newly created
        script if successful.
      operationId: displayvideo.customBiddingAlgorithms.scripts.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - customBiddingAlgorithms
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/customBiddingAlgorithms/{customBiddingAlgorithmId}/scripts/{customBiddingScriptId}:
    get:
      description: Gets a custom bidding script.
      operationId: displayvideo.customBiddingAlgorithms.scripts.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - customBiddingAlgorithms
      x-accepts:
      - application/json
  /v3/customBiddingAlgorithms/{customBiddingAlgorithmId}:uploadRules:
    get:
      description: Creates a rules reference object for an AlgorithmRules file. The
        resulting reference object provides a resource path where the AlgorithmRules
        file should be uploaded. This reference object should be included when creating
        a new CustomBiddingAlgorithmRules resource.
      operationId: displayvideo.customBiddingAlgorithms.uploadRules
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - customBiddingAlgorithms
      x-accepts:
      - application/json
  /v3/customBiddingAlgorithms/{customBiddingAlgorithmId}:uploadScript:
    get:
      description: Creates a custom bidding script reference object for a script file.
        The resulting reference object provides a resource path to which the script
        file should be uploaded. This reference object should be included in when
        creating a new custom bidding script object.
      operationId: displayvideo.customBiddingAlgorithms.uploadScript
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - customBiddingAlgorithms
      x-accepts:
      - application/json
  /v3/customLists:
    get:
      description: Lists custom lists. The order is defined by the order_by parameter.
      operationId: displayvideo.customLists.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - customLists
      x-accepts:
      - application/json
  /v3/customLists/{customListId}:
    get:
      description: Gets a custom list.
      operationId: displayvideo.customLists.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - customLists
      x-accepts:
      - application/json
  /v3/firstAndThirdPartyAudiences:
    get:
      description: Lists first and third party audiences. The order is defined by
        the order_by parameter.
      operationId: displayvideo.firstAndThirdPartyAudiences.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - firstAndThirdPartyAudiences
      x-accepts:
      - application/json
    post:
      description: "Creates a FirstAndThirdPartyAudience. Only supported for the following\
        \ audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`"
      operationId: displayvideo.firstAndThirdPartyAudiences.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - firstAndThirdPartyAudiences
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/firstAndThirdPartyAudiences/{firstAndThirdPartyAudienceId}:
    get:
      description: Gets a first and third party audience.
      operationId: displayvideo.firstAndThirdPartyAudiences.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - firstAndThirdPartyAudiences
      x-accepts:
      - application/json
    patch:
      description: "Updates an existing FirstAndThirdPartyAudience. Only supported\
        \ for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`"
      operationId: displayvideo.firstAndThirdPartyAudiences.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - firstAndThirdPartyAudiences
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/firstAndThirdPartyAudiences/{firstAndThirdPartyAudienceId}:editCustomerMatchMembers:
    post:
      description: "Updates the member list of a Customer Match audience. Only supported\
        \ for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`"
      operationId: displayvideo.firstAndThirdPartyAudiences.editCustomerMatchMembers
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - firstAndThirdPartyAudiences
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/floodlightGroups/{floodlightGroupId}:
    get:
      description: Gets a Floodlight group.
      operationId: displayvideo.floodlightGroups.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - floodlightGroups
      x-accepts:
      - application/json
  /v3/floodlightGroups/{floodlightGroupId}/floodlightActivities:
    get:
      description: Lists Floodlight activities in a Floodlight group.
      operationId: displayvideo.floodlightGroups.floodlightActivities.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - floodlightGroups
      x-accepts:
      - application/json
  /v3/floodlightGroups/{floodlightGroupId}/floodlightActivities/{floodlightActivityId}:
    get:
      description: Gets a Floodlight activity.
      operationId: displayvideo.floodlightGroups.floodlightActivities.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - floodlightGroups
      x-accepts:
      - application/json
  /v3/googleAudiences:
    get:
      description: Lists Google audiences. The order is defined by the order_by parameter.
      operationId: displayvideo.googleAudiences.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - googleAudiences
      x-accepts:
      - application/json
  /v3/googleAudiences/{googleAudienceId}:
    get:
      description: Gets a Google audience.
      operationId: displayvideo.googleAudiences.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - googleAudiences
      x-accepts:
      - application/json
  /v3/guaranteedOrders:
    get:
      description: "Lists guaranteed orders that are accessible to the current user.\
        \ The order is defined by the order_by parameter. If a filter by entity_status\
        \ is not specified, guaranteed orders with entity status `ENTITY_STATUS_ARCHIVED`\
        \ will not be included in the results."
      operationId: displayvideo.guaranteedOrders.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - guaranteedOrders
      x-accepts:
      - application/json
    post:
      description: Creates a new guaranteed order. Returns the newly created guaranteed
        order if successful.
      operationId: displayvideo.guaranteedOrders.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - guaranteedOrders
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/guaranteedOrders/{guaranteedOrderId}:
    get:
      description: Gets a guaranteed order.
      operationId: displayvideo.guaranteedOrders.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - guaranteedOrders
      x-accepts:
      - application/json
    patch:
      description: Updates an existing guaranteed order. Returns the updated guaranteed
        order if successful.
      operationId: displayvideo.guaranteedOrders.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - guaranteedOrders
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/guaranteedOrders/{guaranteedOrderId}:editGuaranteedOrderReadAccessors:
    post:
      description: Edits read advertisers of a guaranteed order.
      operationId: displayvideo.guaranteedOrders.editGuaranteedOrderReadAccessors
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - guaranteedOrders
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/inventorySourceGroups:
    get:
      description: Lists inventory source groups that are accessible to the current
        user. The order is defined by the order_by parameter.
      operationId: displayvideo.inventorySourceGroups.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - inventorySourceGroups
      x-accepts:
      - application/json
    post:
      description: Creates a new inventory source group. Returns the newly created
        inventory source group if successful.
      operationId: displayvideo.inventorySourceGroups.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - inventorySourceGroups
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/inventorySourceGroups/{inventorySourceGroupId}:
    delete:
      description: Deletes an inventory source group.
      operationId: displayvideo.inventorySourceGroups.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - inventorySourceGroups
      x-accepts:
      - application/json
    get:
      description: Gets an inventory source group.
      operationId: displayvideo.inventorySourceGroups.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - inventorySourceGroups
      x-accepts:
      - application/json
  /v3/inventorySourceGroups/{inventorySourceGroupId}/assignedInventorySources:
    get:
      description: Lists inventory sources assigned to an inventory source group.
      operationId: displayvideo.inventorySourceGroups.assignedInventorySources.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - inventorySourceGroups
      x-accepts:
      - application/json
    post:
      description: Creates an assignment between an inventory source and an inventory
        source group.
      operationId: displayvideo.inventorySourceGroups.assignedInventorySources.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - inventorySourceGroups
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/inventorySourceGroups/{inventorySourceGroupId}/assignedInventorySources/{assignedInventorySourceId}:
    delete:
      description: Deletes the assignment between an inventory source and an inventory
        source group.
      operationId: displayvideo.inventorySourceGroups.assignedInventorySources.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - inventorySourceGroups
      x-accepts:
      - application/json
  /v3/inventorySourceGroups/{inventorySourceGroupId}/assignedInventorySources:bulkEdit:
    post:
      description: Bulk edits multiple assignments between inventory sources and a
        single inventory source group. The operation will delete the assigned inventory
        sources provided in BulkEditAssignedInventorySourcesRequest.deleted_assigned_inventory_sources
        and then create the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.created_assigned_inventory_sources.
      operationId: displayvideo.inventorySourceGroups.assignedInventorySources.bulkEdit
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - inventorySourceGroups
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/inventorySources:
    get:
      description: "Lists inventory sources that are accessible to the current user.\
        \ The order is defined by the order_by parameter. If a filter by entity_status\
        \ is not specified, inventory sources with entity status `ENTITY_STATUS_ARCHIVED`\
        \ will not be included in the results."
      operationId: displayvideo.inventorySources.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - inventorySources
      x-accepts:
      - application/json
    post:
      description: Creates a new inventory source. Returns the newly created inventory
        source if successful.
      operationId: displayvideo.inventorySources.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - inventorySources
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/inventorySources/{inventorySourceId}:
    get:
      description: Gets an inventory source.
      operationId: displayvideo.inventorySources.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - inventorySources
      x-accepts:
      - application/json
    patch:
      description: Updates an existing inventory source. Returns the updated inventory
        source if successful.
      operationId: displayvideo.inventorySources.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - inventorySources
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/inventorySources/{inventorySourceId}:editInventorySourceReadWriteAccessors:
    post:
      description: Edits read/write accessors of an inventory source. Returns the
        updated read_write_accessors for the inventory source.
      operationId: displayvideo.inventorySources.editInventorySourceReadWriteAccessors
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - inventorySources
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/partners:
    get:
      description: Lists partners that are accessible to the current user. The order
        is defined by the order_by parameter.
      operationId: displayvideo.partners.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - partners
      x-accepts:
      - application/json
  /v3/partners/{partnerId}:
    get:
      description: Gets a partner.
      operationId: displayvideo.partners.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - partners
      x-accepts:
      - application/json
  /v3/partners/{partnerId}/channels:
    get:
      description: Lists channels for a partner or advertiser.
      operationId: displayvideo.partners.channels.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - partners
      x-accepts:
      - application/json
    post:
      description: Creates a new channel. Returns the newly created channel if successful.
      operationId: displayvideo.partners.channels.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - partners
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/partners/{partnerId}/channels/{channelId}:
    patch:
      description: Updates a channel. Returns the updated channel if successful.
      operationId: displayvideo.partners.channels.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - partners
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/partners/{partnerId}/channels/{channelId}/sites:
    get:
      description: Lists sites in a channel.
      operationId: displayvideo.partners.channels.sites.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - partners
      x-accepts:
      - application/json
  /v3/partners/{partnerId}/channels/{channelId}/sites/{urlOrAppId}:
    delete:
      description: Deletes a site from a channel.
      operationId: displayvideo.partners.channels.sites.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - partners
      x-accepts:
      - application/json
  /v3/partners/{partnerId}/channels/{channelId}/sites:bulkEdit:
    post:
      description: Bulk edits sites under a single channel. The operation will delete
        the sites provided in BulkEditSitesRequest.deleted_sites and then create the
        sites provided in BulkEditSitesRequest.created_sites.
      operationId: displayvideo.partners.channels.sites.bulkEdit
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - partners
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/partners/{partnerId}/channels/{channelId}/sites:replace:
    post:
      description: "Replaces all of the sites under a single channel. The operation\
        \ will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites.\
        \ **This method regularly experiences high latency.** We recommend [increasing\
        \ your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout)\
        \ to avoid errors."
      operationId: displayvideo.partners.channels.sites.replace
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - partners
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/partners/{partnerId}/targetingTypes/{targetingType}/assignedTargetingOptions:
    get:
      description: Lists the targeting options assigned to a partner.
      operationId: displayvideo.partners.targetingTypes.assignedTargetingOptions.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - partners
      x-accepts:
      - application/json
    post:
      description: Assigns a targeting option to a partner. Returns the assigned targeting
        option if successful.
      operationId: displayvideo.partners.targetingTypes.assignedTargetingOptions.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - partners
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/partners/{partnerId}/targetingTypes/{targetingType}/assignedTargetingOptions/{assignedTargetingOptionId}:
    delete:
      description: Deletes an assigned targeting option from a partner.
      operationId: displayvideo.partners.targetingTypes.assignedTargetingOptions.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - partners
      x-accepts:
      - application/json
    get:
      description: Gets a single targeting option assigned to a partner.
      operationId: displayvideo.partners.targetingTypes.assignedTargetingOptions.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - partners
      x-accepts:
      - application/json
  /v3/partners/{partnerId}:editAssignedTargetingOptions:
    post:
      description: Edits targeting options under a single partner. The operation will
        delete the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.deleteRequests
        and then create the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.createRequests
        .
      operationId: displayvideo.partners.editAssignedTargetingOptions
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - partners
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/sdfdownloadtasks:
    post:
      description: "Creates an SDF Download Task. Returns an Operation. An SDF Download\
        \ Task is a long-running, asynchronous operation. The metadata type of this\
        \ operation is SdfDownloadTaskMetadata. If the request is successful, the\
        \ response type of the operation is SdfDownloadTask. The response will not\
        \ include the download files, which must be retrieved with media.download.\
        \ The state of operation can be retrieved with sdfdownloadtask.operations.get.\
        \ Any errors can be found in the error.message. Note that error.details is\
        \ expected to be empty."
      operationId: displayvideo.sdfdownloadtasks.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - sdfdownloadtasks
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/targetingTypes/{targetingType}/targetingOptions:
    get:
      description: Lists targeting options of a given type.
      operationId: displayvideo.targetingTypes.targetingOptions.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - targetingTypes
      x-accepts:
      - application/json
  /v3/targetingTypes/{targetingType}/targetingOptions/{targetingOptionId}:
    get:
      description: Gets a single targeting option.
      operationId: displayvideo.targetingTypes.targetingOptions.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - targetingTypes
      x-accepts:
      - application/json
  /v3/targetingTypes/{targetingType}/targetingOptions:search:
    post:
      description: Searches for targeting options of a given type based on the given
        search terms.
      operationId: displayvideo.targetingTypes.targetingOptions.search
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      tags:
      - targetingTypes
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/users:
    get:
      description: "Lists users that are accessible to the current user. If two users\
        \ have user roles on the same partner or advertiser, they can access each\
        \ other. This method has unique authentication requirements. Read the prerequisites\
        \ in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites)\
        \ before using this method. The \"Try this method\" feature does not work\
        \ for this method."
      operationId: displayvideo.users.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video-user-management
        Oauth2c:
        - https://www.googleapis.com/auth/display-video-user-management
      tags:
      - users
      x-accepts:
      - application/json
    post:
      description: "Creates a new user. Returns the newly created user if successful.\
        \ This method has unique authentication requirements. Read the prerequisites\
        \ in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites)\
        \ before using this method. The \"Try this method\" feature does not work\
        \ for this method."
      operationId: displayvideo.users.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video-user-management
        Oauth2c:
        - https://www.googleapis.com/auth/display-video-user-management
      tags:
      - users
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/users/{userId}:
    delete:
      description: "Deletes a user. This method has unique authentication requirements.\
        \ Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites)\
        \ before using this method. The \"Try this method\" feature does not work\
        \ for this method."
      operationId: displayvideo.users.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video-user-management
        Oauth2c:
        - https://www.googleapis.com/auth/display-video-user-management
      tags:
      - users
      x-accepts:
      - application/json
    get:
      description: "Gets a user. This method has unique authentication requirements.\
        \ Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites)\
        \ before using this method. The \"Try this method\" feature does not work\
        \ for this method."
      operationId: displayvideo.users.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video-user-management
        Oauth2c:
        - https://www.googleapis.com/auth/display-video-user-management
      tags:
      - users
      x-accepts:
      - application/json
    patch:
      description: "Updates an existing user. Returns the updated user if successful.\
        \ This method has unique authentication requirements. Read the prerequisites\
        \ in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites)\
        \ before using this method. The \"Try this method\" feature does not work\
        \ for this method."
      operationId: displayvideo.users.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video-user-management
        Oauth2c:
        - https://www.googleapis.com/auth/display-video-user-management
      tags:
      - users
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/users/{userId}:bulkEditAssignedUserRoles:
    post:
      description: "Bulk edits user roles for a user. The operation will delete the\
        \ assigned user roles provided in BulkEditAssignedUserRolesRequest.deletedAssignedUserRoles\
        \ and then assign the user roles provided in BulkEditAssignedUserRolesRequest.createdAssignedUserRoles.\
        \ This method has unique authentication requirements. Read the prerequisites\
        \ in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites)\
        \ before using this method. The \"Try this method\" feature does not work\
        \ for this method."
      operationId: displayvideo.users.bulkEditAssignedUserRoles
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video-user-management
        Oauth2c:
        - https://www.googleapis.com/auth/display-video-user-management
      tags:
      - users
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/{name}:
    get:
      description: Gets the latest state of an asynchronous SDF download task operation.
        Clients should poll this method at intervals of 30 seconds.
      operationId: displayvideo.sdfdownloadtasks.operations.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/display-video
        Oauth2c:
        - https://www.googleapis.com/auth/display-video
      - Oauth2:
        - https://www.googleapis.com/auth/doubleclickbidmanager
        Oauth2c:
        - https://www.googleapis.com/auth/doubleclickbidmanager
      tags:
      - sdfdownloadtasks
      x-accepts:
      - application/json
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/display-video: "Create, see, edit, and\
              \ permanently delete your Display & Video 360 entities and reports"
            https://www.googleapis.com/auth/display-video-mediaplanning: "Create,\
              \ see, and edit Display & Video 360 Campaign entities and see billing\
              \ invoices"
            https://www.googleapis.com/auth/display-video-user-management: "Private\
              \ Service: https://www.googleapis.com/auth/display-video-user-management"
            https://www.googleapis.com/auth/doubleclickbidmanager: View and manage
              your reports in DoubleClick Bid Manager
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/display-video: "Create, see, edit, and\
              \ permanently delete your Display & Video 360 entities and reports"
            https://www.googleapis.com/auth/display-video-mediaplanning: "Create,\
              \ see, and edit Display & Video 360 Campaign entities and see billing\
              \ invoices"
            https://www.googleapis.com/auth/display-video-user-management: "Private\
              \ Service: https://www.googleapis.com/auth/display-video-user-management"
            https://www.googleapis.com/auth/doubleclickbidmanager: View and manage
              your reports in DoubleClick Bid Manager
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2

