QT += network

HEADERS += \
# Models
    $${PWD}/OAIAccount_settings.h \
    $${PWD}/OAIAccount_settings_images.h \
    $${PWD}/OAIAdd_funds_to_carrier_request_body.h \
    $${PWD}/OAIAdd_funds_to_carrier_response_body.h \
    $${PWD}/OAIAdd_funds_to_insurance_request_body.h \
    $${PWD}/OAIAdd_funds_to_insurance_response_body.h \
    $${PWD}/OAIAdd_to_batch_request_body.h \
    $${PWD}/OAIAddress.h \
    $${PWD}/OAIAddress_residential_indicator.h \
    $${PWD}/OAIAddress_to_validate.h \
    $${PWD}/OAIAddress_validating_shipment.h \
    $${PWD}/OAIAddress_validation_code.h \
    $${PWD}/OAIAddress_validation_detail_code.h \
    $${PWD}/OAIAddress_validation_message_type.h \
    $${PWD}/OAIAddress_validation_result.h \
    $${PWD}/OAIAddress_validation_status.h \
    $${PWD}/OAIAdvanced_shipment_options.h \
    $${PWD}/OAIAdvanced_shipment_options_fedex_freight.h \
    $${PWD}/OAIAlternative_identifier.h \
    $${PWD}/OAIAncillary_service_endorsement.h \
    $${PWD}/OAIBatch.h \
    $${PWD}/OAIBatch_response_error.h \
    $${PWD}/OAIBatch_status.h \
    $${PWD}/OAIBatches_sort_by.h \
    $${PWD}/OAIBill_to_party.h \
    $${PWD}/OAIBulk_rate.h \
    $${PWD}/OAICalculate_rates_request_body.h \
    $${PWD}/OAICalculate_rates_response_body.h \
    $${PWD}/OAICarrier.h \
    $${PWD}/OAICarrier_advanced_option.h \
    $${PWD}/OAICarrier_name.h \
    $${PWD}/OAICarrier_name_with_settings.h \
    $${PWD}/OAICollect_on_delivery.h \
    $${PWD}/OAICollect_on_delivery_payment_type.h \
    $${PWD}/OAICompare_bulk_rates_request_body.h \
    $${PWD}/OAIConnect_access_worldwide_request_body.h \
    $${PWD}/OAIConnect_amazon_buy_shipping_request_body.h \
    $${PWD}/OAIConnect_amazon_shipping_uk.h \
    $${PWD}/OAIConnect_apc_request_body.h \
    $${PWD}/OAIConnect_asendia_request_body.h \
    $${PWD}/OAIConnect_australia_post_request_body.h \
    $${PWD}/OAIConnect_canada_post_request_body.h \
    $${PWD}/OAIConnect_carrier_request_body.h \
    $${PWD}/OAIConnect_carrier_response_body.h \
    $${PWD}/OAIConnect_dhl_ecommerce_request_body.h \
    $${PWD}/OAIConnect_dhl_express_au_request_body.h \
    $${PWD}/OAIConnect_dhl_express_ca_request_body.h \
    $${PWD}/OAIConnect_dhl_express_request_body.h \
    $${PWD}/OAIConnect_dhl_express_uk_request_body.h \
    $${PWD}/OAIConnect_dpd_request_body.h \
    $${PWD}/OAIConnect_endicia_request_body.h \
    $${PWD}/OAIConnect_fedex_request_body.h \
    $${PWD}/OAIConnect_fedex_uk_request_body.h \
    $${PWD}/OAIConnect_firstmile_request_body.h \
    $${PWD}/OAIConnect_imex_request_body.h \
    $${PWD}/OAIConnect_insurer_request_body.h \
    $${PWD}/OAIConnect_newgistics_request_body.h \
    $${PWD}/OAIConnect_ontrac_request_body.h \
    $${PWD}/OAIConnect_purolator_request_body.h \
    $${PWD}/OAIConnect_royal_mail_request_body.h \
    $${PWD}/OAIConnect_rr_donnelley_request_body.h \
    $${PWD}/OAIConnect_seko_request_body.h \
    $${PWD}/OAIConnect_sendle_request_body.h \
    $${PWD}/OAIConnect_stamps_request_body.h \
    $${PWD}/OAIConnect_ups_request_body.h \
    $${PWD}/OAIContact_details.h \
    $${PWD}/OAICreate_account_settings_image_request_body.h \
    $${PWD}/OAICreate_and_validate_shipment.h \
    $${PWD}/OAICreate_batch_request_body.h \
    $${PWD}/OAICreate_batch_response_body.h \
    $${PWD}/OAICreate_label_from_rate_request_body.h \
    $${PWD}/OAICreate_label_from_rate_response_body.h \
    $${PWD}/OAICreate_label_from_shipment_request_body.h \
    $${PWD}/OAICreate_label_from_shipment_response_body.h \
    $${PWD}/OAICreate_label_request_body.h \
    $${PWD}/OAICreate_label_response_body.h \
    $${PWD}/OAICreate_manifest_by_object_request_body.h \
    $${PWD}/OAICreate_manifest_label_ids_request_body.h \
    $${PWD}/OAICreate_manifest_request_body.h \
    $${PWD}/OAICreate_manifest_response_body.h \
    $${PWD}/OAICreate_package_type_request_body.h \
    $${PWD}/OAICreate_package_type_response_body.h \
    $${PWD}/OAICreate_return_label_request_body.h \
    $${PWD}/OAICreate_return_label_response_body.h \
    $${PWD}/OAICreate_shipment_response_body_fields.h \
    $${PWD}/OAICreate_shipments_request_body.h \
    $${PWD}/OAICreate_shipments_response_body.h \
    $${PWD}/OAICreate_tag_response_body.h \
    $${PWD}/OAICreate_warehouse_request_body.h \
    $${PWD}/OAICreate_warehouse_response_body.h \
    $${PWD}/OAICreate_webhook_request_body.h \
    $${PWD}/OAICreate_webhook_response_body.h \
    $${PWD}/OAICustoms_item.h \
    $${PWD}/OAIDefault_label_layout.h \
    $${PWD}/OAIDelete_pickup_by_id_response_body.h \
    $${PWD}/OAIDelete_scheduled_pickup_response_body.h \
    $${PWD}/OAIDelivery_confirmation.h \
    $${PWD}/OAIDeprecated_manifest.h \
    $${PWD}/OAIDhl_express_account_settings.h \
    $${PWD}/OAIDhl_express_settings_response_body.h \
    $${PWD}/OAIDimension_unit.h \
    $${PWD}/OAIDimensions.h \
    $${PWD}/OAIDisplay_scheme.h \
    $${PWD}/OAIError.h \
    $${PWD}/OAIError_code.h \
    $${PWD}/OAIError_response_body.h \
    $${PWD}/OAIError_source.h \
    $${PWD}/OAIError_type.h \
    $${PWD}/OAIError_with_label_id_response_body.h \
    $${PWD}/OAIEstimate_rates_request_body.h \
    $${PWD}/OAIFedex_account_settings.h \
    $${PWD}/OAIFedex_account_settings_request_body.h \
    $${PWD}/OAIFedex_pickup_type.h \
    $${PWD}/OAIFedex_settings_response_body.h \
    $${PWD}/OAIGet_account_settings_images_response_body.h \
    $${PWD}/OAIGet_account_settings_response_body.h \
    $${PWD}/OAIGet_batch_by_external_id_response_body.h \
    $${PWD}/OAIGet_batch_by_id_response_body.h \
    $${PWD}/OAIGet_carrier_by_id_response_body.h \
    $${PWD}/OAIGet_carrier_options_response_body.h \
    $${PWD}/OAIGet_carrier_settings_response_body.h \
    $${PWD}/OAIGet_carriers_response_body.h \
    $${PWD}/OAIGet_insurance_balance_response_body.h \
    $${PWD}/OAIGet_label_by_external_shipment_id_response_body.h \
    $${PWD}/OAIGet_label_by_id_response_body.h \
    $${PWD}/OAIGet_manifest_by_id_response_body.h \
    $${PWD}/OAIGet_package_type_by_id_response_body.h \
    $${PWD}/OAIGet_pickup_by_id_response_body.h \
    $${PWD}/OAIGet_pickups_response_body.h \
    $${PWD}/OAIGet_rate_by_id_response_body.h \
    $${PWD}/OAIGet_service_point_by_id_response_body.h \
    $${PWD}/OAIGet_service_point_by_id_response_body_service_point.h \
    $${PWD}/OAIGet_service_point_by_id_response_body_service_point_hours_of_operation.h \
    $${PWD}/OAIGet_service_point_by_id_response_body_service_point_hours_of_operation_friday_inner.h \
    $${PWD}/OAIGet_service_points_request.h \
    $${PWD}/OAIGet_service_points_request_body.h \
    $${PWD}/OAIGet_service_points_request_body_address.h \
    $${PWD}/OAIGet_service_points_request_body_providers_inner.h \
    $${PWD}/OAIGet_shipment_by_external_id_response_body.h \
    $${PWD}/OAIGet_shipment_by_id_response_body.h \
    $${PWD}/OAIGet_tracking_log_from_label_response_body.h \
    $${PWD}/OAIGet_tracking_log_response_body.h \
    $${PWD}/OAIGet_warehouse_by_id_response_body.h \
    $${PWD}/OAIGet_webhook_by_id_response_body.h \
    $${PWD}/OAIIdentifier_type.h \
    $${PWD}/OAIInsurance_provider.h \
    $${PWD}/OAIInternational_shipment_options.h \
    $${PWD}/OAILabel.h \
    $${PWD}/OAILabel_charge_event.h \
    $${PWD}/OAILabel_download.h \
    $${PWD}/OAILabel_download_type.h \
    $${PWD}/OAILabel_format.h \
    $${PWD}/OAILabel_layout.h \
    $${PWD}/OAILabel_messages.h \
    $${PWD}/OAILabel_status.h \
    $${PWD}/OAILink.h \
    $${PWD}/OAIList_account_images_response_body.h \
    $${PWD}/OAIList_account_settings_body.h \
    $${PWD}/OAIList_account_settings_images_response_body.h \
    $${PWD}/OAIList_batch_errors_response_body.h \
    $${PWD}/OAIList_batches_response_body.h \
    $${PWD}/OAIList_carrier_package_types_response_body.h \
    $${PWD}/OAIList_carrier_services_response_body.h \
    $${PWD}/OAIList_carriers_response_body.h \
    $${PWD}/OAIList_labels_response_body.h \
    $${PWD}/OAIList_manifests_response_body.h \
    $${PWD}/OAIList_package_types_response_body.h \
    $${PWD}/OAIList_pickup_response_body.h \
    $${PWD}/OAIList_service_points_response_body.h \
    $${PWD}/OAIList_service_points_response_body_service_points_inner.h \
    $${PWD}/OAIList_shipment_rates_response_body.h \
    $${PWD}/OAIList_shipments_response_body.h \
    $${PWD}/OAIList_tags_response_body.h \
    $${PWD}/OAIList_warehouses_response_body.h \
    $${PWD}/OAIManifest.h \
    $${PWD}/OAIManifest_download.h \
    $${PWD}/OAIManifest_request.h \
    $${PWD}/OAIManifest_request_status.h \
    $${PWD}/OAIManifests.h \
    $${PWD}/OAIManifests_requests.h \
    $${PWD}/OAIModify_batch.h \
    $${PWD}/OAIMonetary_value.h \
    $${PWD}/OAINon_delivery.h \
    $${PWD}/OAIOptional_link.h \
    $${PWD}/OAIOrder_source_name.h \
    $${PWD}/OAIOrigin_type.h \
    $${PWD}/OAIPackage.h \
    $${PWD}/OAIPackage_contents.h \
    $${PWD}/OAIPackage_type.h \
    $${PWD}/OAIPaged_list_response_body.h \
    $${PWD}/OAIPagination_link.h \
    $${PWD}/OAIParse_address_request_body.h \
    $${PWD}/OAIParse_address_response_body.h \
    $${PWD}/OAIParse_shipment_request_body.h \
    $${PWD}/OAIParse_shipment_response_body.h \
    $${PWD}/OAIPartial_address.h \
    $${PWD}/OAIPartial_shipment.h \
    $${PWD}/OAIPartial_shipping_address.h \
    $${PWD}/OAIPayment_amount.h \
    $${PWD}/OAIPickup.h \
    $${PWD}/OAIPickup_response_body.h \
    $${PWD}/OAIPickup_window.h \
    $${PWD}/OAIPickup_windows.h \
    $${PWD}/OAIProcess_batch_request_body.h \
    $${PWD}/OAIPurchase_label_without_shipment.h \
    $${PWD}/OAIRate.h \
    $${PWD}/OAIRate_estimate.h \
    $${PWD}/OAIRate_estimate_by_carrier_id.h \
    $${PWD}/OAIRate_estimate_by_carrier_ids.h \
    $${PWD}/OAIRate_estimate_options.h \
    $${PWD}/OAIRate_request_body.h \
    $${PWD}/OAIRate_request_by_shipment_ids.h \
    $${PWD}/OAIRate_request_by_shipments.h \
    $${PWD}/OAIRate_request_options.h \
    $${PWD}/OAIRate_request_rate_options.h \
    $${PWD}/OAIRate_response.h \
    $${PWD}/OAIRate_response_status.h \
    $${PWD}/OAIRate_type.h \
    $${PWD}/OAIRates_information.h \
    $${PWD}/OAIRecognized_entity.h \
    $${PWD}/OAIRedirect.h \
    $${PWD}/OAIRemove_from_batch_request_body.h \
    $${PWD}/OAIResponse_message.h \
    $${PWD}/OAISchedule_pickup_request_body.h \
    $${PWD}/OAISchedule_pickup_response_body.h \
    $${PWD}/OAIService.h \
    $${PWD}/OAIShipment.h \
    $${PWD}/OAIShipment_id_request.h \
    $${PWD}/OAIShipment_item.h \
    $${PWD}/OAIShipment_request.h \
    $${PWD}/OAIShipment_status.h \
    $${PWD}/OAIShipments_sort_by.h \
    $${PWD}/OAIShipping_address.h \
    $${PWD}/OAISmart_post_hub.h \
    $${PWD}/OAISort_dir.h \
    $${PWD}/OAIStatus_code.h \
    $${PWD}/OAITag.h \
    $${PWD}/OAITag_shipment_response_body.h \
    $${PWD}/OAITax_identifier.h \
    $${PWD}/OAITaxable_entity_type.h \
    $${PWD}/OAITokens_get_ephemeral_token_response_body_yaml.h \
    $${PWD}/OAITrack_event.h \
    $${PWD}/OAITracking_information.h \
    $${PWD}/OAITracking_status.h \
    $${PWD}/OAIUpdate_account_settings_image_request_body.h \
    $${PWD}/OAIUpdate_amazon_buy_shipping_request_body.h \
    $${PWD}/OAIUpdate_carrier_settings_request_body.h \
    $${PWD}/OAIUpdate_dhl_express_settings_request_body.h \
    $${PWD}/OAIUpdate_fedex_settings_request_body.h \
    $${PWD}/OAIUpdate_newgistics_settings_request_body.h \
    $${PWD}/OAIUpdate_package_type_request_body.h \
    $${PWD}/OAIUpdate_shipment_fields.h \
    $${PWD}/OAIUpdate_shipment_request_body.h \
    $${PWD}/OAIUpdate_shipment_response_body.h \
    $${PWD}/OAIUpdate_ups_settings_request_body.h \
    $${PWD}/OAIUpdate_warehouse_request_body.h \
    $${PWD}/OAIUpdate_warehouse_settings_request_body.h \
    $${PWD}/OAIUpdate_webhook_request_body.h \
    $${PWD}/OAIUps_account_settings.h \
    $${PWD}/OAIUps_invoice.h \
    $${PWD}/OAIUps_pickup_type.h \
    $${PWD}/OAIUps_settings_response_body.h \
    $${PWD}/OAIValidate_address.h \
    $${PWD}/OAIValidate_shipment_fields.h \
    $${PWD}/OAIValidation_status.h \
    $${PWD}/OAIVoid_label_response_body.h \
    $${PWD}/OAIWarehouse.h \
    $${PWD}/OAIWebhook.h \
    $${PWD}/OAIWebhook_event.h \
    $${PWD}/OAIWeight.h \
    $${PWD}/OAIWeight_unit.h \
# APIs
    $${PWD}/OAIAccountApi.h \
    $${PWD}/OAIAddressesApi.h \
    $${PWD}/OAIBatchesApi.h \
    $${PWD}/OAICarrierAccountsApi.h \
    $${PWD}/OAICarriersApi.h \
    $${PWD}/OAIDownloadsApi.h \
    $${PWD}/OAIInsuranceApi.h \
    $${PWD}/OAILabelsApi.h \
    $${PWD}/OAIManifestsApi.h \
    $${PWD}/OAIPackagePickupsApi.h \
    $${PWD}/OAIPackageTypesApi.h \
    $${PWD}/OAIRatesApi.h \
    $${PWD}/OAIServicePointsApi.h \
    $${PWD}/OAIShipmentsApi.h \
    $${PWD}/OAITagsApi.h \
    $${PWD}/OAITokensApi.h \
    $${PWD}/OAITrackingApi.h \
    $${PWD}/OAIWarehousesApi.h \
    $${PWD}/OAIWebhooksApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAccount_settings.cpp \
    $${PWD}/OAIAccount_settings_images.cpp \
    $${PWD}/OAIAdd_funds_to_carrier_request_body.cpp \
    $${PWD}/OAIAdd_funds_to_carrier_response_body.cpp \
    $${PWD}/OAIAdd_funds_to_insurance_request_body.cpp \
    $${PWD}/OAIAdd_funds_to_insurance_response_body.cpp \
    $${PWD}/OAIAdd_to_batch_request_body.cpp \
    $${PWD}/OAIAddress.cpp \
    $${PWD}/OAIAddress_residential_indicator.cpp \
    $${PWD}/OAIAddress_to_validate.cpp \
    $${PWD}/OAIAddress_validating_shipment.cpp \
    $${PWD}/OAIAddress_validation_code.cpp \
    $${PWD}/OAIAddress_validation_detail_code.cpp \
    $${PWD}/OAIAddress_validation_message_type.cpp \
    $${PWD}/OAIAddress_validation_result.cpp \
    $${PWD}/OAIAddress_validation_status.cpp \
    $${PWD}/OAIAdvanced_shipment_options.cpp \
    $${PWD}/OAIAdvanced_shipment_options_fedex_freight.cpp \
    $${PWD}/OAIAlternative_identifier.cpp \
    $${PWD}/OAIAncillary_service_endorsement.cpp \
    $${PWD}/OAIBatch.cpp \
    $${PWD}/OAIBatch_response_error.cpp \
    $${PWD}/OAIBatch_status.cpp \
    $${PWD}/OAIBatches_sort_by.cpp \
    $${PWD}/OAIBill_to_party.cpp \
    $${PWD}/OAIBulk_rate.cpp \
    $${PWD}/OAICalculate_rates_request_body.cpp \
    $${PWD}/OAICalculate_rates_response_body.cpp \
    $${PWD}/OAICarrier.cpp \
    $${PWD}/OAICarrier_advanced_option.cpp \
    $${PWD}/OAICarrier_name.cpp \
    $${PWD}/OAICarrier_name_with_settings.cpp \
    $${PWD}/OAICollect_on_delivery.cpp \
    $${PWD}/OAICollect_on_delivery_payment_type.cpp \
    $${PWD}/OAICompare_bulk_rates_request_body.cpp \
    $${PWD}/OAIConnect_access_worldwide_request_body.cpp \
    $${PWD}/OAIConnect_amazon_buy_shipping_request_body.cpp \
    $${PWD}/OAIConnect_amazon_shipping_uk.cpp \
    $${PWD}/OAIConnect_apc_request_body.cpp \
    $${PWD}/OAIConnect_asendia_request_body.cpp \
    $${PWD}/OAIConnect_australia_post_request_body.cpp \
    $${PWD}/OAIConnect_canada_post_request_body.cpp \
    $${PWD}/OAIConnect_carrier_request_body.cpp \
    $${PWD}/OAIConnect_carrier_response_body.cpp \
    $${PWD}/OAIConnect_dhl_ecommerce_request_body.cpp \
    $${PWD}/OAIConnect_dhl_express_au_request_body.cpp \
    $${PWD}/OAIConnect_dhl_express_ca_request_body.cpp \
    $${PWD}/OAIConnect_dhl_express_request_body.cpp \
    $${PWD}/OAIConnect_dhl_express_uk_request_body.cpp \
    $${PWD}/OAIConnect_dpd_request_body.cpp \
    $${PWD}/OAIConnect_endicia_request_body.cpp \
    $${PWD}/OAIConnect_fedex_request_body.cpp \
    $${PWD}/OAIConnect_fedex_uk_request_body.cpp \
    $${PWD}/OAIConnect_firstmile_request_body.cpp \
    $${PWD}/OAIConnect_imex_request_body.cpp \
    $${PWD}/OAIConnect_insurer_request_body.cpp \
    $${PWD}/OAIConnect_newgistics_request_body.cpp \
    $${PWD}/OAIConnect_ontrac_request_body.cpp \
    $${PWD}/OAIConnect_purolator_request_body.cpp \
    $${PWD}/OAIConnect_royal_mail_request_body.cpp \
    $${PWD}/OAIConnect_rr_donnelley_request_body.cpp \
    $${PWD}/OAIConnect_seko_request_body.cpp \
    $${PWD}/OAIConnect_sendle_request_body.cpp \
    $${PWD}/OAIConnect_stamps_request_body.cpp \
    $${PWD}/OAIConnect_ups_request_body.cpp \
    $${PWD}/OAIContact_details.cpp \
    $${PWD}/OAICreate_account_settings_image_request_body.cpp \
    $${PWD}/OAICreate_and_validate_shipment.cpp \
    $${PWD}/OAICreate_batch_request_body.cpp \
    $${PWD}/OAICreate_batch_response_body.cpp \
    $${PWD}/OAICreate_label_from_rate_request_body.cpp \
    $${PWD}/OAICreate_label_from_rate_response_body.cpp \
    $${PWD}/OAICreate_label_from_shipment_request_body.cpp \
    $${PWD}/OAICreate_label_from_shipment_response_body.cpp \
    $${PWD}/OAICreate_label_request_body.cpp \
    $${PWD}/OAICreate_label_response_body.cpp \
    $${PWD}/OAICreate_manifest_by_object_request_body.cpp \
    $${PWD}/OAICreate_manifest_label_ids_request_body.cpp \
    $${PWD}/OAICreate_manifest_request_body.cpp \
    $${PWD}/OAICreate_manifest_response_body.cpp \
    $${PWD}/OAICreate_package_type_request_body.cpp \
    $${PWD}/OAICreate_package_type_response_body.cpp \
    $${PWD}/OAICreate_return_label_request_body.cpp \
    $${PWD}/OAICreate_return_label_response_body.cpp \
    $${PWD}/OAICreate_shipment_response_body_fields.cpp \
    $${PWD}/OAICreate_shipments_request_body.cpp \
    $${PWD}/OAICreate_shipments_response_body.cpp \
    $${PWD}/OAICreate_tag_response_body.cpp \
    $${PWD}/OAICreate_warehouse_request_body.cpp \
    $${PWD}/OAICreate_warehouse_response_body.cpp \
    $${PWD}/OAICreate_webhook_request_body.cpp \
    $${PWD}/OAICreate_webhook_response_body.cpp \
    $${PWD}/OAICustoms_item.cpp \
    $${PWD}/OAIDefault_label_layout.cpp \
    $${PWD}/OAIDelete_pickup_by_id_response_body.cpp \
    $${PWD}/OAIDelete_scheduled_pickup_response_body.cpp \
    $${PWD}/OAIDelivery_confirmation.cpp \
    $${PWD}/OAIDeprecated_manifest.cpp \
    $${PWD}/OAIDhl_express_account_settings.cpp \
    $${PWD}/OAIDhl_express_settings_response_body.cpp \
    $${PWD}/OAIDimension_unit.cpp \
    $${PWD}/OAIDimensions.cpp \
    $${PWD}/OAIDisplay_scheme.cpp \
    $${PWD}/OAIError.cpp \
    $${PWD}/OAIError_code.cpp \
    $${PWD}/OAIError_response_body.cpp \
    $${PWD}/OAIError_source.cpp \
    $${PWD}/OAIError_type.cpp \
    $${PWD}/OAIError_with_label_id_response_body.cpp \
    $${PWD}/OAIEstimate_rates_request_body.cpp \
    $${PWD}/OAIFedex_account_settings.cpp \
    $${PWD}/OAIFedex_account_settings_request_body.cpp \
    $${PWD}/OAIFedex_pickup_type.cpp \
    $${PWD}/OAIFedex_settings_response_body.cpp \
    $${PWD}/OAIGet_account_settings_images_response_body.cpp \
    $${PWD}/OAIGet_account_settings_response_body.cpp \
    $${PWD}/OAIGet_batch_by_external_id_response_body.cpp \
    $${PWD}/OAIGet_batch_by_id_response_body.cpp \
    $${PWD}/OAIGet_carrier_by_id_response_body.cpp \
    $${PWD}/OAIGet_carrier_options_response_body.cpp \
    $${PWD}/OAIGet_carrier_settings_response_body.cpp \
    $${PWD}/OAIGet_carriers_response_body.cpp \
    $${PWD}/OAIGet_insurance_balance_response_body.cpp \
    $${PWD}/OAIGet_label_by_external_shipment_id_response_body.cpp \
    $${PWD}/OAIGet_label_by_id_response_body.cpp \
    $${PWD}/OAIGet_manifest_by_id_response_body.cpp \
    $${PWD}/OAIGet_package_type_by_id_response_body.cpp \
    $${PWD}/OAIGet_pickup_by_id_response_body.cpp \
    $${PWD}/OAIGet_pickups_response_body.cpp \
    $${PWD}/OAIGet_rate_by_id_response_body.cpp \
    $${PWD}/OAIGet_service_point_by_id_response_body.cpp \
    $${PWD}/OAIGet_service_point_by_id_response_body_service_point.cpp \
    $${PWD}/OAIGet_service_point_by_id_response_body_service_point_hours_of_operation.cpp \
    $${PWD}/OAIGet_service_point_by_id_response_body_service_point_hours_of_operation_friday_inner.cpp \
    $${PWD}/OAIGet_service_points_request.cpp \
    $${PWD}/OAIGet_service_points_request_body.cpp \
    $${PWD}/OAIGet_service_points_request_body_address.cpp \
    $${PWD}/OAIGet_service_points_request_body_providers_inner.cpp \
    $${PWD}/OAIGet_shipment_by_external_id_response_body.cpp \
    $${PWD}/OAIGet_shipment_by_id_response_body.cpp \
    $${PWD}/OAIGet_tracking_log_from_label_response_body.cpp \
    $${PWD}/OAIGet_tracking_log_response_body.cpp \
    $${PWD}/OAIGet_warehouse_by_id_response_body.cpp \
    $${PWD}/OAIGet_webhook_by_id_response_body.cpp \
    $${PWD}/OAIIdentifier_type.cpp \
    $${PWD}/OAIInsurance_provider.cpp \
    $${PWD}/OAIInternational_shipment_options.cpp \
    $${PWD}/OAILabel.cpp \
    $${PWD}/OAILabel_charge_event.cpp \
    $${PWD}/OAILabel_download.cpp \
    $${PWD}/OAILabel_download_type.cpp \
    $${PWD}/OAILabel_format.cpp \
    $${PWD}/OAILabel_layout.cpp \
    $${PWD}/OAILabel_messages.cpp \
    $${PWD}/OAILabel_status.cpp \
    $${PWD}/OAILink.cpp \
    $${PWD}/OAIList_account_images_response_body.cpp \
    $${PWD}/OAIList_account_settings_body.cpp \
    $${PWD}/OAIList_account_settings_images_response_body.cpp \
    $${PWD}/OAIList_batch_errors_response_body.cpp \
    $${PWD}/OAIList_batches_response_body.cpp \
    $${PWD}/OAIList_carrier_package_types_response_body.cpp \
    $${PWD}/OAIList_carrier_services_response_body.cpp \
    $${PWD}/OAIList_carriers_response_body.cpp \
    $${PWD}/OAIList_labels_response_body.cpp \
    $${PWD}/OAIList_manifests_response_body.cpp \
    $${PWD}/OAIList_package_types_response_body.cpp \
    $${PWD}/OAIList_pickup_response_body.cpp \
    $${PWD}/OAIList_service_points_response_body.cpp \
    $${PWD}/OAIList_service_points_response_body_service_points_inner.cpp \
    $${PWD}/OAIList_shipment_rates_response_body.cpp \
    $${PWD}/OAIList_shipments_response_body.cpp \
    $${PWD}/OAIList_tags_response_body.cpp \
    $${PWD}/OAIList_warehouses_response_body.cpp \
    $${PWD}/OAIManifest.cpp \
    $${PWD}/OAIManifest_download.cpp \
    $${PWD}/OAIManifest_request.cpp \
    $${PWD}/OAIManifest_request_status.cpp \
    $${PWD}/OAIManifests.cpp \
    $${PWD}/OAIManifests_requests.cpp \
    $${PWD}/OAIModify_batch.cpp \
    $${PWD}/OAIMonetary_value.cpp \
    $${PWD}/OAINon_delivery.cpp \
    $${PWD}/OAIOptional_link.cpp \
    $${PWD}/OAIOrder_source_name.cpp \
    $${PWD}/OAIOrigin_type.cpp \
    $${PWD}/OAIPackage.cpp \
    $${PWD}/OAIPackage_contents.cpp \
    $${PWD}/OAIPackage_type.cpp \
    $${PWD}/OAIPaged_list_response_body.cpp \
    $${PWD}/OAIPagination_link.cpp \
    $${PWD}/OAIParse_address_request_body.cpp \
    $${PWD}/OAIParse_address_response_body.cpp \
    $${PWD}/OAIParse_shipment_request_body.cpp \
    $${PWD}/OAIParse_shipment_response_body.cpp \
    $${PWD}/OAIPartial_address.cpp \
    $${PWD}/OAIPartial_shipment.cpp \
    $${PWD}/OAIPartial_shipping_address.cpp \
    $${PWD}/OAIPayment_amount.cpp \
    $${PWD}/OAIPickup.cpp \
    $${PWD}/OAIPickup_response_body.cpp \
    $${PWD}/OAIPickup_window.cpp \
    $${PWD}/OAIPickup_windows.cpp \
    $${PWD}/OAIProcess_batch_request_body.cpp \
    $${PWD}/OAIPurchase_label_without_shipment.cpp \
    $${PWD}/OAIRate.cpp \
    $${PWD}/OAIRate_estimate.cpp \
    $${PWD}/OAIRate_estimate_by_carrier_id.cpp \
    $${PWD}/OAIRate_estimate_by_carrier_ids.cpp \
    $${PWD}/OAIRate_estimate_options.cpp \
    $${PWD}/OAIRate_request_body.cpp \
    $${PWD}/OAIRate_request_by_shipment_ids.cpp \
    $${PWD}/OAIRate_request_by_shipments.cpp \
    $${PWD}/OAIRate_request_options.cpp \
    $${PWD}/OAIRate_request_rate_options.cpp \
    $${PWD}/OAIRate_response.cpp \
    $${PWD}/OAIRate_response_status.cpp \
    $${PWD}/OAIRate_type.cpp \
    $${PWD}/OAIRates_information.cpp \
    $${PWD}/OAIRecognized_entity.cpp \
    $${PWD}/OAIRedirect.cpp \
    $${PWD}/OAIRemove_from_batch_request_body.cpp \
    $${PWD}/OAIResponse_message.cpp \
    $${PWD}/OAISchedule_pickup_request_body.cpp \
    $${PWD}/OAISchedule_pickup_response_body.cpp \
    $${PWD}/OAIService.cpp \
    $${PWD}/OAIShipment.cpp \
    $${PWD}/OAIShipment_id_request.cpp \
    $${PWD}/OAIShipment_item.cpp \
    $${PWD}/OAIShipment_request.cpp \
    $${PWD}/OAIShipment_status.cpp \
    $${PWD}/OAIShipments_sort_by.cpp \
    $${PWD}/OAIShipping_address.cpp \
    $${PWD}/OAISmart_post_hub.cpp \
    $${PWD}/OAISort_dir.cpp \
    $${PWD}/OAIStatus_code.cpp \
    $${PWD}/OAITag.cpp \
    $${PWD}/OAITag_shipment_response_body.cpp \
    $${PWD}/OAITax_identifier.cpp \
    $${PWD}/OAITaxable_entity_type.cpp \
    $${PWD}/OAITokens_get_ephemeral_token_response_body_yaml.cpp \
    $${PWD}/OAITrack_event.cpp \
    $${PWD}/OAITracking_information.cpp \
    $${PWD}/OAITracking_status.cpp \
    $${PWD}/OAIUpdate_account_settings_image_request_body.cpp \
    $${PWD}/OAIUpdate_amazon_buy_shipping_request_body.cpp \
    $${PWD}/OAIUpdate_carrier_settings_request_body.cpp \
    $${PWD}/OAIUpdate_dhl_express_settings_request_body.cpp \
    $${PWD}/OAIUpdate_fedex_settings_request_body.cpp \
    $${PWD}/OAIUpdate_newgistics_settings_request_body.cpp \
    $${PWD}/OAIUpdate_package_type_request_body.cpp \
    $${PWD}/OAIUpdate_shipment_fields.cpp \
    $${PWD}/OAIUpdate_shipment_request_body.cpp \
    $${PWD}/OAIUpdate_shipment_response_body.cpp \
    $${PWD}/OAIUpdate_ups_settings_request_body.cpp \
    $${PWD}/OAIUpdate_warehouse_request_body.cpp \
    $${PWD}/OAIUpdate_warehouse_settings_request_body.cpp \
    $${PWD}/OAIUpdate_webhook_request_body.cpp \
    $${PWD}/OAIUps_account_settings.cpp \
    $${PWD}/OAIUps_invoice.cpp \
    $${PWD}/OAIUps_pickup_type.cpp \
    $${PWD}/OAIUps_settings_response_body.cpp \
    $${PWD}/OAIValidate_address.cpp \
    $${PWD}/OAIValidate_shipment_fields.cpp \
    $${PWD}/OAIValidation_status.cpp \
    $${PWD}/OAIVoid_label_response_body.cpp \
    $${PWD}/OAIWarehouse.cpp \
    $${PWD}/OAIWebhook.cpp \
    $${PWD}/OAIWebhook_event.cpp \
    $${PWD}/OAIWeight.cpp \
    $${PWD}/OAIWeight_unit.cpp \
# APIs
    $${PWD}/OAIAccountApi.cpp \
    $${PWD}/OAIAddressesApi.cpp \
    $${PWD}/OAIBatchesApi.cpp \
    $${PWD}/OAICarrierAccountsApi.cpp \
    $${PWD}/OAICarriersApi.cpp \
    $${PWD}/OAIDownloadsApi.cpp \
    $${PWD}/OAIInsuranceApi.cpp \
    $${PWD}/OAILabelsApi.cpp \
    $${PWD}/OAIManifestsApi.cpp \
    $${PWD}/OAIPackagePickupsApi.cpp \
    $${PWD}/OAIPackageTypesApi.cpp \
    $${PWD}/OAIRatesApi.cpp \
    $${PWD}/OAIServicePointsApi.cpp \
    $${PWD}/OAIShipmentsApi.cpp \
    $${PWD}/OAITagsApi.cpp \
    $${PWD}/OAITokensApi.cpp \
    $${PWD}/OAITrackingApi.cpp \
    $${PWD}/OAIWarehousesApi.cpp \
    $${PWD}/OAIWebhooksApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
