QT += network

HEADERS += \
# Models
    $${PWD}/OAIAWSDomainInformation.h \
    $${PWD}/OAIAcceptInboundConnectionResponse.h \
    $${PWD}/OAIAcceptInboundConnectionResponse_Connection.h \
    $${PWD}/OAIAccessPoliciesStatus.h \
    $${PWD}/OAIAccessPoliciesStatus_Status.h \
    $${PWD}/OAIActionSeverity.h \
    $${PWD}/OAIActionStatus.h \
    $${PWD}/OAIActionType.h \
    $${PWD}/OAIAddTagsRequest.h \
    $${PWD}/OAIAddTags_request.h \
    $${PWD}/OAIAdditionalLimit.h \
    $${PWD}/OAIAdvancedOptionsStatus.h \
    $${PWD}/OAIAdvancedOptionsStatus_Status.h \
    $${PWD}/OAIAdvancedSecurityOptions.h \
    $${PWD}/OAIAdvancedSecurityOptionsInput.h \
    $${PWD}/OAIAdvancedSecurityOptionsStatus.h \
    $${PWD}/OAIAdvancedSecurityOptionsStatus_Options.h \
    $${PWD}/OAIAdvancedSecurityOptionsStatus_Status.h \
    $${PWD}/OAIAdvancedSecurityOptions_SAMLOptions.h \
    $${PWD}/OAIAssociatePackageResponse.h \
    $${PWD}/OAIAssociatePackageResponse_DomainPackageDetails.h \
    $${PWD}/OAIAuthorizeVpcEndpointAccessRequest.h \
    $${PWD}/OAIAuthorizeVpcEndpointAccessResponse.h \
    $${PWD}/OAIAuthorizeVpcEndpointAccessResponse_AuthorizedPrincipal.h \
    $${PWD}/OAIAuthorizeVpcEndpointAccess_request.h \
    $${PWD}/OAIAuthorizedPrincipal.h \
    $${PWD}/OAIAutoTune.h \
    $${PWD}/OAIAutoTuneDesiredState.h \
    $${PWD}/OAIAutoTuneDetails.h \
    $${PWD}/OAIAutoTuneDetails_ScheduledAutoTuneDetails.h \
    $${PWD}/OAIAutoTuneMaintenanceSchedule.h \
    $${PWD}/OAIAutoTuneMaintenanceSchedule_Duration.h \
    $${PWD}/OAIAutoTuneOptions.h \
    $${PWD}/OAIAutoTuneOptionsInput.h \
    $${PWD}/OAIAutoTuneOptionsOutput.h \
    $${PWD}/OAIAutoTuneOptionsStatus.h \
    $${PWD}/OAIAutoTuneOptionsStatus_Options.h \
    $${PWD}/OAIAutoTuneOptionsStatus_Status.h \
    $${PWD}/OAIAutoTuneState.h \
    $${PWD}/OAIAutoTuneStatus.h \
    $${PWD}/OAIAutoTuneType.h \
    $${PWD}/OAIAutoTune_AutoTuneDetails.h \
    $${PWD}/OAIAvailabilityZoneInfo.h \
    $${PWD}/OAICancelServiceSoftwareUpdateRequest.h \
    $${PWD}/OAICancelServiceSoftwareUpdateResponse.h \
    $${PWD}/OAICancelServiceSoftwareUpdateResponse_ServiceSoftwareOptions.h \
    $${PWD}/OAICancelServiceSoftwareUpdate_request.h \
    $${PWD}/OAIChangeProgressDetails.h \
    $${PWD}/OAIChangeProgressStage.h \
    $${PWD}/OAIChangeProgressStatusDetails.h \
    $${PWD}/OAIClusterConfig.h \
    $${PWD}/OAIClusterConfigStatus.h \
    $${PWD}/OAIClusterConfigStatus_Options.h \
    $${PWD}/OAIClusterConfigStatus_Status.h \
    $${PWD}/OAICognitoOptions.h \
    $${PWD}/OAICognitoOptionsStatus.h \
    $${PWD}/OAICognitoOptionsStatus_Options.h \
    $${PWD}/OAICognitoOptionsStatus_Status.h \
    $${PWD}/OAIColdStorageOptions.h \
    $${PWD}/OAICompatibleVersionsMap.h \
    $${PWD}/OAIConnectionMode.h \
    $${PWD}/OAIConnectionProperties.h \
    $${PWD}/OAICreateDomainRequest.h \
    $${PWD}/OAICreateDomainRequest_AdvancedSecurityOptions.h \
    $${PWD}/OAICreateDomainRequest_AutoTuneOptions.h \
    $${PWD}/OAICreateDomainRequest_ClusterConfig.h \
    $${PWD}/OAICreateDomainRequest_CognitoOptions.h \
    $${PWD}/OAICreateDomainRequest_DomainEndpointOptions.h \
    $${PWD}/OAICreateDomainRequest_EBSOptions.h \
    $${PWD}/OAICreateDomainRequest_EncryptionAtRestOptions.h \
    $${PWD}/OAICreateDomainRequest_NodeToNodeEncryptionOptions.h \
    $${PWD}/OAICreateDomainRequest_OffPeakWindowOptions.h \
    $${PWD}/OAICreateDomainRequest_SnapshotOptions.h \
    $${PWD}/OAICreateDomainRequest_SoftwareUpdateOptions.h \
    $${PWD}/OAICreateDomainRequest_VPCOptions.h \
    $${PWD}/OAICreateDomainResponse.h \
    $${PWD}/OAICreateDomainResponse_DomainStatus.h \
    $${PWD}/OAICreateDomain_request.h \
    $${PWD}/OAICreateDomain_request_AdvancedSecurityOptions.h \
    $${PWD}/OAICreateDomain_request_AdvancedSecurityOptions_MasterUserOptions.h \
    $${PWD}/OAICreateDomain_request_AdvancedSecurityOptions_SAMLOptions.h \
    $${PWD}/OAICreateDomain_request_AutoTuneOptions.h \
    $${PWD}/OAICreateDomain_request_ClusterConfig.h \
    $${PWD}/OAICreateDomain_request_ClusterConfig_ColdStorageOptions.h \
    $${PWD}/OAICreateDomain_request_ClusterConfig_ZoneAwarenessConfig.h \
    $${PWD}/OAICreateDomain_request_CognitoOptions.h \
    $${PWD}/OAICreateDomain_request_DomainEndpointOptions.h \
    $${PWD}/OAICreateDomain_request_EBSOptions.h \
    $${PWD}/OAICreateDomain_request_EncryptionAtRestOptions.h \
    $${PWD}/OAICreateDomain_request_NodeToNodeEncryptionOptions.h \
    $${PWD}/OAICreateDomain_request_OffPeakWindowOptions.h \
    $${PWD}/OAICreateDomain_request_OffPeakWindowOptions_OffPeakWindow.h \
    $${PWD}/OAICreateDomain_request_SnapshotOptions.h \
    $${PWD}/OAICreateDomain_request_SoftwareUpdateOptions.h \
    $${PWD}/OAICreateDomain_request_VPCOptions.h \
    $${PWD}/OAICreateOutboundConnectionRequest.h \
    $${PWD}/OAICreateOutboundConnectionRequest_ConnectionProperties.h \
    $${PWD}/OAICreateOutboundConnectionRequest_LocalDomainInfo.h \
    $${PWD}/OAICreateOutboundConnectionRequest_RemoteDomainInfo.h \
    $${PWD}/OAICreateOutboundConnectionResponse.h \
    $${PWD}/OAICreateOutboundConnectionResponse_ConnectionProperties.h \
    $${PWD}/OAICreateOutboundConnectionResponse_ConnectionStatus.h \
    $${PWD}/OAICreateOutboundConnectionResponse_LocalDomainInfo.h \
    $${PWD}/OAICreateOutboundConnectionResponse_RemoteDomainInfo.h \
    $${PWD}/OAICreateOutboundConnection_request.h \
    $${PWD}/OAICreateOutboundConnection_request_ConnectionProperties.h \
    $${PWD}/OAICreateOutboundConnection_request_ConnectionProperties_CrossClusterSearch.h \
    $${PWD}/OAICreateOutboundConnection_request_LocalDomainInfo.h \
    $${PWD}/OAICreateOutboundConnection_request_LocalDomainInfo_AWSDomainInformation.h \
    $${PWD}/OAICreatePackageRequest.h \
    $${PWD}/OAICreatePackageRequest_PackageSource.h \
    $${PWD}/OAICreatePackageResponse.h \
    $${PWD}/OAICreatePackageResponse_PackageDetails.h \
    $${PWD}/OAICreatePackage_request.h \
    $${PWD}/OAICreatePackage_request_PackageSource.h \
    $${PWD}/OAICreateVpcEndpointRequest.h \
    $${PWD}/OAICreateVpcEndpointRequest_VpcOptions.h \
    $${PWD}/OAICreateVpcEndpointResponse.h \
    $${PWD}/OAICreateVpcEndpointResponse_VpcEndpoint.h \
    $${PWD}/OAICreateVpcEndpoint_request.h \
    $${PWD}/OAICrossClusterSearchConnectionProperties.h \
    $${PWD}/OAIDeleteDomainResponse.h \
    $${PWD}/OAIDeleteDomainResponse_DomainStatus.h \
    $${PWD}/OAIDeleteInboundConnectionResponse.h \
    $${PWD}/OAIDeleteInboundConnectionResponse_Connection.h \
    $${PWD}/OAIDeleteOutboundConnectionResponse.h \
    $${PWD}/OAIDeleteOutboundConnectionResponse_Connection.h \
    $${PWD}/OAIDeletePackageResponse.h \
    $${PWD}/OAIDeletePackageResponse_PackageDetails.h \
    $${PWD}/OAIDeleteVpcEndpointResponse.h \
    $${PWD}/OAIDeleteVpcEndpointResponse_VpcEndpointSummary.h \
    $${PWD}/OAIDeploymentStatus.h \
    $${PWD}/OAIDescribeDomainAutoTunesRequest.h \
    $${PWD}/OAIDescribeDomainAutoTunesResponse.h \
    $${PWD}/OAIDescribeDomainAutoTunes_request.h \
    $${PWD}/OAIDescribeDomainChangeProgressResponse.h \
    $${PWD}/OAIDescribeDomainChangeProgressResponse_ChangeProgressStatus.h \
    $${PWD}/OAIDescribeDomainConfigResponse.h \
    $${PWD}/OAIDescribeDomainConfigResponse_DomainConfig.h \
    $${PWD}/OAIDescribeDomainHealthResponse.h \
    $${PWD}/OAIDescribeDomainNodesResponse.h \
    $${PWD}/OAIDescribeDomainResponse.h \
    $${PWD}/OAIDescribeDomainResponse_DomainStatus.h \
    $${PWD}/OAIDescribeDomainsRequest.h \
    $${PWD}/OAIDescribeDomainsResponse.h \
    $${PWD}/OAIDescribeDomains_request.h \
    $${PWD}/OAIDescribeDryRunProgressResponse.h \
    $${PWD}/OAIDescribeDryRunProgressResponse_DryRunConfig.h \
    $${PWD}/OAIDescribeDryRunProgressResponse_DryRunProgressStatus.h \
    $${PWD}/OAIDescribeDryRunProgressResponse_DryRunResults.h \
    $${PWD}/OAIDescribeInboundConnectionsRequest.h \
    $${PWD}/OAIDescribeInboundConnectionsResponse.h \
    $${PWD}/OAIDescribeInboundConnections_request.h \
    $${PWD}/OAIDescribeInstanceTypeLimitsResponse.h \
    $${PWD}/OAIDescribeOutboundConnectionsRequest.h \
    $${PWD}/OAIDescribeOutboundConnectionsResponse.h \
    $${PWD}/OAIDescribeOutboundConnections_request.h \
    $${PWD}/OAIDescribePackagesFilter.h \
    $${PWD}/OAIDescribePackagesFilterName.h \
    $${PWD}/OAIDescribePackagesRequest.h \
    $${PWD}/OAIDescribePackagesResponse.h \
    $${PWD}/OAIDescribePackages_request.h \
    $${PWD}/OAIDescribeReservedInstanceOfferingsResponse.h \
    $${PWD}/OAIDescribeReservedInstancesResponse.h \
    $${PWD}/OAIDescribeVpcEndpointsRequest.h \
    $${PWD}/OAIDescribeVpcEndpointsResponse.h \
    $${PWD}/OAIDescribeVpcEndpoints_request.h \
    $${PWD}/OAIDissociatePackageResponse.h \
    $${PWD}/OAIDissociatePackageResponse_DomainPackageDetails.h \
    $${PWD}/OAIDomainConfig.h \
    $${PWD}/OAIDomainConfig_AccessPolicies.h \
    $${PWD}/OAIDomainConfig_AdvancedOptions.h \
    $${PWD}/OAIDomainConfig_AdvancedSecurityOptions.h \
    $${PWD}/OAIDomainConfig_AutoTuneOptions.h \
    $${PWD}/OAIDomainConfig_ChangeProgressDetails.h \
    $${PWD}/OAIDomainConfig_ClusterConfig.h \
    $${PWD}/OAIDomainConfig_CognitoOptions.h \
    $${PWD}/OAIDomainConfig_DomainEndpointOptions.h \
    $${PWD}/OAIDomainConfig_EBSOptions.h \
    $${PWD}/OAIDomainConfig_EncryptionAtRestOptions.h \
    $${PWD}/OAIDomainConfig_EngineVersion.h \
    $${PWD}/OAIDomainConfig_LogPublishingOptions.h \
    $${PWD}/OAIDomainConfig_NodeToNodeEncryptionOptions.h \
    $${PWD}/OAIDomainConfig_OffPeakWindowOptions.h \
    $${PWD}/OAIDomainConfig_SnapshotOptions.h \
    $${PWD}/OAIDomainConfig_SoftwareUpdateOptions.h \
    $${PWD}/OAIDomainConfig_VPCOptions.h \
    $${PWD}/OAIDomainEndpointOptions.h \
    $${PWD}/OAIDomainEndpointOptionsStatus.h \
    $${PWD}/OAIDomainEndpointOptionsStatus_Options.h \
    $${PWD}/OAIDomainEndpointOptionsStatus_Status.h \
    $${PWD}/OAIDomainHealth.h \
    $${PWD}/OAIDomainInfo.h \
    $${PWD}/OAIDomainInformationContainer.h \
    $${PWD}/OAIDomainNodesStatus.h \
    $${PWD}/OAIDomainPackageDetails.h \
    $${PWD}/OAIDomainPackageDetails_ErrorDetails.h \
    $${PWD}/OAIDomainPackageStatus.h \
    $${PWD}/OAIDomainState.h \
    $${PWD}/OAIDomainStatus.h \
    $${PWD}/OAIDomainStatus_AdvancedSecurityOptions.h \
    $${PWD}/OAIDomainStatus_AutoTuneOptions.h \
    $${PWD}/OAIDomainStatus_ChangeProgressDetails.h \
    $${PWD}/OAIDomainStatus_ClusterConfig.h \
    $${PWD}/OAIDomainStatus_CognitoOptions.h \
    $${PWD}/OAIDomainStatus_EBSOptions.h \
    $${PWD}/OAIDomainStatus_EncryptionAtRestOptions.h \
    $${PWD}/OAIDomainStatus_NodeToNodeEncryptionOptions.h \
    $${PWD}/OAIDomainStatus_OffPeakWindowOptions.h \
    $${PWD}/OAIDomainStatus_ServiceSoftwareOptions.h \
    $${PWD}/OAIDomainStatus_SnapshotOptions.h \
    $${PWD}/OAIDomainStatus_SoftwareUpdateOptions.h \
    $${PWD}/OAIDomainStatus_VPCOptions.h \
    $${PWD}/OAIDryRunMode.h \
    $${PWD}/OAIDryRunProgressStatus.h \
    $${PWD}/OAIDryRunResults.h \
    $${PWD}/OAIDuration.h \
    $${PWD}/OAIEBSOptions.h \
    $${PWD}/OAIEBSOptionsStatus.h \
    $${PWD}/OAIEBSOptionsStatus_Options.h \
    $${PWD}/OAIEBSOptionsStatus_Status.h \
    $${PWD}/OAIEncryptionAtRestOptions.h \
    $${PWD}/OAIEncryptionAtRestOptionsStatus.h \
    $${PWD}/OAIEncryptionAtRestOptionsStatus_Options.h \
    $${PWD}/OAIEncryptionAtRestOptionsStatus_Status.h \
    $${PWD}/OAIEngineType.h \
    $${PWD}/OAIEnvironmentInfo.h \
    $${PWD}/OAIErrorDetails.h \
    $${PWD}/OAIFilter.h \
    $${PWD}/OAIGetCompatibleVersionsResponse.h \
    $${PWD}/OAIGetPackageVersionHistoryResponse.h \
    $${PWD}/OAIGetUpgradeHistoryResponse.h \
    $${PWD}/OAIGetUpgradeStatusResponse.h \
    $${PWD}/OAIInboundConnection.h \
    $${PWD}/OAIInboundConnectionStatus.h \
    $${PWD}/OAIInboundConnectionStatusCode.h \
    $${PWD}/OAIInboundConnection_ConnectionStatus.h \
    $${PWD}/OAIInstanceCountLimits.h \
    $${PWD}/OAIInstanceLimits.h \
    $${PWD}/OAIInstanceLimits_InstanceCountLimits.h \
    $${PWD}/OAIInstanceTypeDetails.h \
    $${PWD}/OAILimits.h \
    $${PWD}/OAILimits_InstanceLimits.h \
    $${PWD}/OAIListDomainNamesResponse.h \
    $${PWD}/OAIListDomainsForPackageResponse.h \
    $${PWD}/OAIListInstanceTypeDetailsResponse.h \
    $${PWD}/OAIListPackagesForDomainResponse.h \
    $${PWD}/OAIListScheduledActionsResponse.h \
    $${PWD}/OAIListTagsResponse.h \
    $${PWD}/OAIListVersionsResponse.h \
    $${PWD}/OAIListVpcEndpointAccessResponse.h \
    $${PWD}/OAIListVpcEndpointsForDomainResponse.h \
    $${PWD}/OAIListVpcEndpointsResponse.h \
    $${PWD}/OAILogPublishingOption.h \
    $${PWD}/OAILogPublishingOptionsStatus.h \
    $${PWD}/OAILogPublishingOptionsStatus_Status.h \
    $${PWD}/OAILogType.h \
    $${PWD}/OAIMasterNodeStatus.h \
    $${PWD}/OAIMasterUserOptions.h \
    $${PWD}/OAINodeStatus.h \
    $${PWD}/OAINodeToNodeEncryptionOptions.h \
    $${PWD}/OAINodeToNodeEncryptionOptionsStatus.h \
    $${PWD}/OAINodeToNodeEncryptionOptionsStatus_Options.h \
    $${PWD}/OAINodeToNodeEncryptionOptionsStatus_Status.h \
    $${PWD}/OAINodeType.h \
    $${PWD}/OAIOffPeakWindow.h \
    $${PWD}/OAIOffPeakWindowOptions.h \
    $${PWD}/OAIOffPeakWindowOptionsStatus.h \
    $${PWD}/OAIOffPeakWindowOptionsStatus_Options.h \
    $${PWD}/OAIOffPeakWindowOptionsStatus_Status.h \
    $${PWD}/OAIOffPeakWindow_WindowStartTime.h \
    $${PWD}/OAIOpenSearchPartitionInstanceType.h \
    $${PWD}/OAIOpenSearchWarmPartitionInstanceType.h \
    $${PWD}/OAIOptionState.h \
    $${PWD}/OAIOptionStatus.h \
    $${PWD}/OAIOutboundConnection.h \
    $${PWD}/OAIOutboundConnectionStatus.h \
    $${PWD}/OAIOutboundConnectionStatusCode.h \
    $${PWD}/OAIOutboundConnection_ConnectionProperties.h \
    $${PWD}/OAIOutboundConnection_ConnectionStatus.h \
    $${PWD}/OAIOverallChangeStatus.h \
    $${PWD}/OAIPackageDetails.h \
    $${PWD}/OAIPackageSource.h \
    $${PWD}/OAIPackageStatus.h \
    $${PWD}/OAIPackageType.h \
    $${PWD}/OAIPackageVersionHistory.h \
    $${PWD}/OAIPrincipalType.h \
    $${PWD}/OAIPurchaseReservedInstanceOfferingRequest.h \
    $${PWD}/OAIPurchaseReservedInstanceOfferingResponse.h \
    $${PWD}/OAIPurchaseReservedInstanceOffering_request.h \
    $${PWD}/OAIRecurringCharge.h \
    $${PWD}/OAIRejectInboundConnectionResponse.h \
    $${PWD}/OAIRejectInboundConnectionResponse_Connection.h \
    $${PWD}/OAIRemoveTagsRequest.h \
    $${PWD}/OAIRemoveTags_request.h \
    $${PWD}/OAIReservedInstance.h \
    $${PWD}/OAIReservedInstanceOffering.h \
    $${PWD}/OAIReservedInstancePaymentOption.h \
    $${PWD}/OAIRevokeVpcEndpointAccessRequest.h \
    $${PWD}/OAIRevokeVpcEndpointAccess_request.h \
    $${PWD}/OAIRollbackOnDisable.h \
    $${PWD}/OAISAMLIdp.h \
    $${PWD}/OAISAMLOptionsInput.h \
    $${PWD}/OAISAMLOptionsInput_Idp.h \
    $${PWD}/OAISAMLOptionsOutput.h \
    $${PWD}/OAISAMLOptionsOutput_Idp.h \
    $${PWD}/OAIScheduleAt.h \
    $${PWD}/OAIScheduledAction.h \
    $${PWD}/OAIScheduledAutoTuneActionType.h \
    $${PWD}/OAIScheduledAutoTuneDetails.h \
    $${PWD}/OAIScheduledAutoTuneSeverityType.h \
    $${PWD}/OAIScheduledBy.h \
    $${PWD}/OAIServiceSoftwareOptions.h \
    $${PWD}/OAISkipUnavailableStatus.h \
    $${PWD}/OAISnapshotOptions.h \
    $${PWD}/OAISnapshotOptionsStatus.h \
    $${PWD}/OAISnapshotOptionsStatus_Options.h \
    $${PWD}/OAISnapshotOptionsStatus_Status.h \
    $${PWD}/OAISoftwareUpdateOptions.h \
    $${PWD}/OAISoftwareUpdateOptionsStatus.h \
    $${PWD}/OAISoftwareUpdateOptionsStatus_Options.h \
    $${PWD}/OAISoftwareUpdateOptionsStatus_Status.h \
    $${PWD}/OAIStartServiceSoftwareUpdateRequest.h \
    $${PWD}/OAIStartServiceSoftwareUpdateResponse.h \
    $${PWD}/OAIStartServiceSoftwareUpdateResponse_ServiceSoftwareOptions.h \
    $${PWD}/OAIStartServiceSoftwareUpdate_request.h \
    $${PWD}/OAIStorageType.h \
    $${PWD}/OAIStorageTypeLimit.h \
    $${PWD}/OAITLSSecurityPolicy.h \
    $${PWD}/OAITag.h \
    $${PWD}/OAITimeUnit.h \
    $${PWD}/OAIUpdateDomainConfigRequest.h \
    $${PWD}/OAIUpdateDomainConfigRequest_AutoTuneOptions.h \
    $${PWD}/OAIUpdateDomainConfigRequest_ClusterConfig.h \
    $${PWD}/OAIUpdateDomainConfigRequest_EBSOptions.h \
    $${PWD}/OAIUpdateDomainConfigRequest_EncryptionAtRestOptions.h \
    $${PWD}/OAIUpdateDomainConfigRequest_NodeToNodeEncryptionOptions.h \
    $${PWD}/OAIUpdateDomainConfigRequest_OffPeakWindowOptions.h \
    $${PWD}/OAIUpdateDomainConfigRequest_SnapshotOptions.h \
    $${PWD}/OAIUpdateDomainConfigRequest_VPCOptions.h \
    $${PWD}/OAIUpdateDomainConfigResponse.h \
    $${PWD}/OAIUpdateDomainConfigResponse_DomainConfig.h \
    $${PWD}/OAIUpdateDomainConfigResponse_DryRunProgressStatus.h \
    $${PWD}/OAIUpdateDomainConfigResponse_DryRunResults.h \
    $${PWD}/OAIUpdateDomainConfig_request.h \
    $${PWD}/OAIUpdateDomainConfig_request_AutoTuneOptions.h \
    $${PWD}/OAIUpdatePackageRequest.h \
    $${PWD}/OAIUpdatePackageRequest_PackageSource.h \
    $${PWD}/OAIUpdatePackageResponse.h \
    $${PWD}/OAIUpdatePackageResponse_PackageDetails.h \
    $${PWD}/OAIUpdatePackage_request.h \
    $${PWD}/OAIUpdateScheduledActionRequest.h \
    $${PWD}/OAIUpdateScheduledActionResponse.h \
    $${PWD}/OAIUpdateScheduledActionResponse_ScheduledAction.h \
    $${PWD}/OAIUpdateScheduledAction_request.h \
    $${PWD}/OAIUpdateVpcEndpointRequest.h \
    $${PWD}/OAIUpdateVpcEndpointRequest_VpcOptions.h \
    $${PWD}/OAIUpdateVpcEndpointResponse.h \
    $${PWD}/OAIUpdateVpcEndpointResponse_VpcEndpoint.h \
    $${PWD}/OAIUpdateVpcEndpoint_request.h \
    $${PWD}/OAIUpgradeDomainRequest.h \
    $${PWD}/OAIUpgradeDomainResponse.h \
    $${PWD}/OAIUpgradeDomainResponse_ChangeProgressDetails.h \
    $${PWD}/OAIUpgradeDomain_request.h \
    $${PWD}/OAIUpgradeHistory.h \
    $${PWD}/OAIUpgradeStatus.h \
    $${PWD}/OAIUpgradeStep.h \
    $${PWD}/OAIUpgradeStepItem.h \
    $${PWD}/OAIVPCDerivedInfo.h \
    $${PWD}/OAIVPCDerivedInfoStatus.h \
    $${PWD}/OAIVPCDerivedInfoStatus_Options.h \
    $${PWD}/OAIVPCDerivedInfoStatus_Status.h \
    $${PWD}/OAIVPCOptions.h \
    $${PWD}/OAIValidationFailure.h \
    $${PWD}/OAIVersionStatus.h \
    $${PWD}/OAIVersionStatus_Status.h \
    $${PWD}/OAIVolumeType.h \
    $${PWD}/OAIVpcEndpoint.h \
    $${PWD}/OAIVpcEndpointError.h \
    $${PWD}/OAIVpcEndpointErrorCode.h \
    $${PWD}/OAIVpcEndpointStatus.h \
    $${PWD}/OAIVpcEndpointSummary.h \
    $${PWD}/OAIVpcEndpoint_VpcOptions.h \
    $${PWD}/OAIWindowStartTime.h \
    $${PWD}/OAIZoneAwarenessConfig.h \
    $${PWD}/OAIZoneStatus.h \
# APIs
    $${PWD}/OAIDefaultApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAWSDomainInformation.cpp \
    $${PWD}/OAIAcceptInboundConnectionResponse.cpp \
    $${PWD}/OAIAcceptInboundConnectionResponse_Connection.cpp \
    $${PWD}/OAIAccessPoliciesStatus.cpp \
    $${PWD}/OAIAccessPoliciesStatus_Status.cpp \
    $${PWD}/OAIActionSeverity.cpp \
    $${PWD}/OAIActionStatus.cpp \
    $${PWD}/OAIActionType.cpp \
    $${PWD}/OAIAddTagsRequest.cpp \
    $${PWD}/OAIAddTags_request.cpp \
    $${PWD}/OAIAdditionalLimit.cpp \
    $${PWD}/OAIAdvancedOptionsStatus.cpp \
    $${PWD}/OAIAdvancedOptionsStatus_Status.cpp \
    $${PWD}/OAIAdvancedSecurityOptions.cpp \
    $${PWD}/OAIAdvancedSecurityOptionsInput.cpp \
    $${PWD}/OAIAdvancedSecurityOptionsStatus.cpp \
    $${PWD}/OAIAdvancedSecurityOptionsStatus_Options.cpp \
    $${PWD}/OAIAdvancedSecurityOptionsStatus_Status.cpp \
    $${PWD}/OAIAdvancedSecurityOptions_SAMLOptions.cpp \
    $${PWD}/OAIAssociatePackageResponse.cpp \
    $${PWD}/OAIAssociatePackageResponse_DomainPackageDetails.cpp \
    $${PWD}/OAIAuthorizeVpcEndpointAccessRequest.cpp \
    $${PWD}/OAIAuthorizeVpcEndpointAccessResponse.cpp \
    $${PWD}/OAIAuthorizeVpcEndpointAccessResponse_AuthorizedPrincipal.cpp \
    $${PWD}/OAIAuthorizeVpcEndpointAccess_request.cpp \
    $${PWD}/OAIAuthorizedPrincipal.cpp \
    $${PWD}/OAIAutoTune.cpp \
    $${PWD}/OAIAutoTuneDesiredState.cpp \
    $${PWD}/OAIAutoTuneDetails.cpp \
    $${PWD}/OAIAutoTuneDetails_ScheduledAutoTuneDetails.cpp \
    $${PWD}/OAIAutoTuneMaintenanceSchedule.cpp \
    $${PWD}/OAIAutoTuneMaintenanceSchedule_Duration.cpp \
    $${PWD}/OAIAutoTuneOptions.cpp \
    $${PWD}/OAIAutoTuneOptionsInput.cpp \
    $${PWD}/OAIAutoTuneOptionsOutput.cpp \
    $${PWD}/OAIAutoTuneOptionsStatus.cpp \
    $${PWD}/OAIAutoTuneOptionsStatus_Options.cpp \
    $${PWD}/OAIAutoTuneOptionsStatus_Status.cpp \
    $${PWD}/OAIAutoTuneState.cpp \
    $${PWD}/OAIAutoTuneStatus.cpp \
    $${PWD}/OAIAutoTuneType.cpp \
    $${PWD}/OAIAutoTune_AutoTuneDetails.cpp \
    $${PWD}/OAIAvailabilityZoneInfo.cpp \
    $${PWD}/OAICancelServiceSoftwareUpdateRequest.cpp \
    $${PWD}/OAICancelServiceSoftwareUpdateResponse.cpp \
    $${PWD}/OAICancelServiceSoftwareUpdateResponse_ServiceSoftwareOptions.cpp \
    $${PWD}/OAICancelServiceSoftwareUpdate_request.cpp \
    $${PWD}/OAIChangeProgressDetails.cpp \
    $${PWD}/OAIChangeProgressStage.cpp \
    $${PWD}/OAIChangeProgressStatusDetails.cpp \
    $${PWD}/OAIClusterConfig.cpp \
    $${PWD}/OAIClusterConfigStatus.cpp \
    $${PWD}/OAIClusterConfigStatus_Options.cpp \
    $${PWD}/OAIClusterConfigStatus_Status.cpp \
    $${PWD}/OAICognitoOptions.cpp \
    $${PWD}/OAICognitoOptionsStatus.cpp \
    $${PWD}/OAICognitoOptionsStatus_Options.cpp \
    $${PWD}/OAICognitoOptionsStatus_Status.cpp \
    $${PWD}/OAIColdStorageOptions.cpp \
    $${PWD}/OAICompatibleVersionsMap.cpp \
    $${PWD}/OAIConnectionMode.cpp \
    $${PWD}/OAIConnectionProperties.cpp \
    $${PWD}/OAICreateDomainRequest.cpp \
    $${PWD}/OAICreateDomainRequest_AdvancedSecurityOptions.cpp \
    $${PWD}/OAICreateDomainRequest_AutoTuneOptions.cpp \
    $${PWD}/OAICreateDomainRequest_ClusterConfig.cpp \
    $${PWD}/OAICreateDomainRequest_CognitoOptions.cpp \
    $${PWD}/OAICreateDomainRequest_DomainEndpointOptions.cpp \
    $${PWD}/OAICreateDomainRequest_EBSOptions.cpp \
    $${PWD}/OAICreateDomainRequest_EncryptionAtRestOptions.cpp \
    $${PWD}/OAICreateDomainRequest_NodeToNodeEncryptionOptions.cpp \
    $${PWD}/OAICreateDomainRequest_OffPeakWindowOptions.cpp \
    $${PWD}/OAICreateDomainRequest_SnapshotOptions.cpp \
    $${PWD}/OAICreateDomainRequest_SoftwareUpdateOptions.cpp \
    $${PWD}/OAICreateDomainRequest_VPCOptions.cpp \
    $${PWD}/OAICreateDomainResponse.cpp \
    $${PWD}/OAICreateDomainResponse_DomainStatus.cpp \
    $${PWD}/OAICreateDomain_request.cpp \
    $${PWD}/OAICreateDomain_request_AdvancedSecurityOptions.cpp \
    $${PWD}/OAICreateDomain_request_AdvancedSecurityOptions_MasterUserOptions.cpp \
    $${PWD}/OAICreateDomain_request_AdvancedSecurityOptions_SAMLOptions.cpp \
    $${PWD}/OAICreateDomain_request_AutoTuneOptions.cpp \
    $${PWD}/OAICreateDomain_request_ClusterConfig.cpp \
    $${PWD}/OAICreateDomain_request_ClusterConfig_ColdStorageOptions.cpp \
    $${PWD}/OAICreateDomain_request_ClusterConfig_ZoneAwarenessConfig.cpp \
    $${PWD}/OAICreateDomain_request_CognitoOptions.cpp \
    $${PWD}/OAICreateDomain_request_DomainEndpointOptions.cpp \
    $${PWD}/OAICreateDomain_request_EBSOptions.cpp \
    $${PWD}/OAICreateDomain_request_EncryptionAtRestOptions.cpp \
    $${PWD}/OAICreateDomain_request_NodeToNodeEncryptionOptions.cpp \
    $${PWD}/OAICreateDomain_request_OffPeakWindowOptions.cpp \
    $${PWD}/OAICreateDomain_request_OffPeakWindowOptions_OffPeakWindow.cpp \
    $${PWD}/OAICreateDomain_request_SnapshotOptions.cpp \
    $${PWD}/OAICreateDomain_request_SoftwareUpdateOptions.cpp \
    $${PWD}/OAICreateDomain_request_VPCOptions.cpp \
    $${PWD}/OAICreateOutboundConnectionRequest.cpp \
    $${PWD}/OAICreateOutboundConnectionRequest_ConnectionProperties.cpp \
    $${PWD}/OAICreateOutboundConnectionRequest_LocalDomainInfo.cpp \
    $${PWD}/OAICreateOutboundConnectionRequest_RemoteDomainInfo.cpp \
    $${PWD}/OAICreateOutboundConnectionResponse.cpp \
    $${PWD}/OAICreateOutboundConnectionResponse_ConnectionProperties.cpp \
    $${PWD}/OAICreateOutboundConnectionResponse_ConnectionStatus.cpp \
    $${PWD}/OAICreateOutboundConnectionResponse_LocalDomainInfo.cpp \
    $${PWD}/OAICreateOutboundConnectionResponse_RemoteDomainInfo.cpp \
    $${PWD}/OAICreateOutboundConnection_request.cpp \
    $${PWD}/OAICreateOutboundConnection_request_ConnectionProperties.cpp \
    $${PWD}/OAICreateOutboundConnection_request_ConnectionProperties_CrossClusterSearch.cpp \
    $${PWD}/OAICreateOutboundConnection_request_LocalDomainInfo.cpp \
    $${PWD}/OAICreateOutboundConnection_request_LocalDomainInfo_AWSDomainInformation.cpp \
    $${PWD}/OAICreatePackageRequest.cpp \
    $${PWD}/OAICreatePackageRequest_PackageSource.cpp \
    $${PWD}/OAICreatePackageResponse.cpp \
    $${PWD}/OAICreatePackageResponse_PackageDetails.cpp \
    $${PWD}/OAICreatePackage_request.cpp \
    $${PWD}/OAICreatePackage_request_PackageSource.cpp \
    $${PWD}/OAICreateVpcEndpointRequest.cpp \
    $${PWD}/OAICreateVpcEndpointRequest_VpcOptions.cpp \
    $${PWD}/OAICreateVpcEndpointResponse.cpp \
    $${PWD}/OAICreateVpcEndpointResponse_VpcEndpoint.cpp \
    $${PWD}/OAICreateVpcEndpoint_request.cpp \
    $${PWD}/OAICrossClusterSearchConnectionProperties.cpp \
    $${PWD}/OAIDeleteDomainResponse.cpp \
    $${PWD}/OAIDeleteDomainResponse_DomainStatus.cpp \
    $${PWD}/OAIDeleteInboundConnectionResponse.cpp \
    $${PWD}/OAIDeleteInboundConnectionResponse_Connection.cpp \
    $${PWD}/OAIDeleteOutboundConnectionResponse.cpp \
    $${PWD}/OAIDeleteOutboundConnectionResponse_Connection.cpp \
    $${PWD}/OAIDeletePackageResponse.cpp \
    $${PWD}/OAIDeletePackageResponse_PackageDetails.cpp \
    $${PWD}/OAIDeleteVpcEndpointResponse.cpp \
    $${PWD}/OAIDeleteVpcEndpointResponse_VpcEndpointSummary.cpp \
    $${PWD}/OAIDeploymentStatus.cpp \
    $${PWD}/OAIDescribeDomainAutoTunesRequest.cpp \
    $${PWD}/OAIDescribeDomainAutoTunesResponse.cpp \
    $${PWD}/OAIDescribeDomainAutoTunes_request.cpp \
    $${PWD}/OAIDescribeDomainChangeProgressResponse.cpp \
    $${PWD}/OAIDescribeDomainChangeProgressResponse_ChangeProgressStatus.cpp \
    $${PWD}/OAIDescribeDomainConfigResponse.cpp \
    $${PWD}/OAIDescribeDomainConfigResponse_DomainConfig.cpp \
    $${PWD}/OAIDescribeDomainHealthResponse.cpp \
    $${PWD}/OAIDescribeDomainNodesResponse.cpp \
    $${PWD}/OAIDescribeDomainResponse.cpp \
    $${PWD}/OAIDescribeDomainResponse_DomainStatus.cpp \
    $${PWD}/OAIDescribeDomainsRequest.cpp \
    $${PWD}/OAIDescribeDomainsResponse.cpp \
    $${PWD}/OAIDescribeDomains_request.cpp \
    $${PWD}/OAIDescribeDryRunProgressResponse.cpp \
    $${PWD}/OAIDescribeDryRunProgressResponse_DryRunConfig.cpp \
    $${PWD}/OAIDescribeDryRunProgressResponse_DryRunProgressStatus.cpp \
    $${PWD}/OAIDescribeDryRunProgressResponse_DryRunResults.cpp \
    $${PWD}/OAIDescribeInboundConnectionsRequest.cpp \
    $${PWD}/OAIDescribeInboundConnectionsResponse.cpp \
    $${PWD}/OAIDescribeInboundConnections_request.cpp \
    $${PWD}/OAIDescribeInstanceTypeLimitsResponse.cpp \
    $${PWD}/OAIDescribeOutboundConnectionsRequest.cpp \
    $${PWD}/OAIDescribeOutboundConnectionsResponse.cpp \
    $${PWD}/OAIDescribeOutboundConnections_request.cpp \
    $${PWD}/OAIDescribePackagesFilter.cpp \
    $${PWD}/OAIDescribePackagesFilterName.cpp \
    $${PWD}/OAIDescribePackagesRequest.cpp \
    $${PWD}/OAIDescribePackagesResponse.cpp \
    $${PWD}/OAIDescribePackages_request.cpp \
    $${PWD}/OAIDescribeReservedInstanceOfferingsResponse.cpp \
    $${PWD}/OAIDescribeReservedInstancesResponse.cpp \
    $${PWD}/OAIDescribeVpcEndpointsRequest.cpp \
    $${PWD}/OAIDescribeVpcEndpointsResponse.cpp \
    $${PWD}/OAIDescribeVpcEndpoints_request.cpp \
    $${PWD}/OAIDissociatePackageResponse.cpp \
    $${PWD}/OAIDissociatePackageResponse_DomainPackageDetails.cpp \
    $${PWD}/OAIDomainConfig.cpp \
    $${PWD}/OAIDomainConfig_AccessPolicies.cpp \
    $${PWD}/OAIDomainConfig_AdvancedOptions.cpp \
    $${PWD}/OAIDomainConfig_AdvancedSecurityOptions.cpp \
    $${PWD}/OAIDomainConfig_AutoTuneOptions.cpp \
    $${PWD}/OAIDomainConfig_ChangeProgressDetails.cpp \
    $${PWD}/OAIDomainConfig_ClusterConfig.cpp \
    $${PWD}/OAIDomainConfig_CognitoOptions.cpp \
    $${PWD}/OAIDomainConfig_DomainEndpointOptions.cpp \
    $${PWD}/OAIDomainConfig_EBSOptions.cpp \
    $${PWD}/OAIDomainConfig_EncryptionAtRestOptions.cpp \
    $${PWD}/OAIDomainConfig_EngineVersion.cpp \
    $${PWD}/OAIDomainConfig_LogPublishingOptions.cpp \
    $${PWD}/OAIDomainConfig_NodeToNodeEncryptionOptions.cpp \
    $${PWD}/OAIDomainConfig_OffPeakWindowOptions.cpp \
    $${PWD}/OAIDomainConfig_SnapshotOptions.cpp \
    $${PWD}/OAIDomainConfig_SoftwareUpdateOptions.cpp \
    $${PWD}/OAIDomainConfig_VPCOptions.cpp \
    $${PWD}/OAIDomainEndpointOptions.cpp \
    $${PWD}/OAIDomainEndpointOptionsStatus.cpp \
    $${PWD}/OAIDomainEndpointOptionsStatus_Options.cpp \
    $${PWD}/OAIDomainEndpointOptionsStatus_Status.cpp \
    $${PWD}/OAIDomainHealth.cpp \
    $${PWD}/OAIDomainInfo.cpp \
    $${PWD}/OAIDomainInformationContainer.cpp \
    $${PWD}/OAIDomainNodesStatus.cpp \
    $${PWD}/OAIDomainPackageDetails.cpp \
    $${PWD}/OAIDomainPackageDetails_ErrorDetails.cpp \
    $${PWD}/OAIDomainPackageStatus.cpp \
    $${PWD}/OAIDomainState.cpp \
    $${PWD}/OAIDomainStatus.cpp \
    $${PWD}/OAIDomainStatus_AdvancedSecurityOptions.cpp \
    $${PWD}/OAIDomainStatus_AutoTuneOptions.cpp \
    $${PWD}/OAIDomainStatus_ChangeProgressDetails.cpp \
    $${PWD}/OAIDomainStatus_ClusterConfig.cpp \
    $${PWD}/OAIDomainStatus_CognitoOptions.cpp \
    $${PWD}/OAIDomainStatus_EBSOptions.cpp \
    $${PWD}/OAIDomainStatus_EncryptionAtRestOptions.cpp \
    $${PWD}/OAIDomainStatus_NodeToNodeEncryptionOptions.cpp \
    $${PWD}/OAIDomainStatus_OffPeakWindowOptions.cpp \
    $${PWD}/OAIDomainStatus_ServiceSoftwareOptions.cpp \
    $${PWD}/OAIDomainStatus_SnapshotOptions.cpp \
    $${PWD}/OAIDomainStatus_SoftwareUpdateOptions.cpp \
    $${PWD}/OAIDomainStatus_VPCOptions.cpp \
    $${PWD}/OAIDryRunMode.cpp \
    $${PWD}/OAIDryRunProgressStatus.cpp \
    $${PWD}/OAIDryRunResults.cpp \
    $${PWD}/OAIDuration.cpp \
    $${PWD}/OAIEBSOptions.cpp \
    $${PWD}/OAIEBSOptionsStatus.cpp \
    $${PWD}/OAIEBSOptionsStatus_Options.cpp \
    $${PWD}/OAIEBSOptionsStatus_Status.cpp \
    $${PWD}/OAIEncryptionAtRestOptions.cpp \
    $${PWD}/OAIEncryptionAtRestOptionsStatus.cpp \
    $${PWD}/OAIEncryptionAtRestOptionsStatus_Options.cpp \
    $${PWD}/OAIEncryptionAtRestOptionsStatus_Status.cpp \
    $${PWD}/OAIEngineType.cpp \
    $${PWD}/OAIEnvironmentInfo.cpp \
    $${PWD}/OAIErrorDetails.cpp \
    $${PWD}/OAIFilter.cpp \
    $${PWD}/OAIGetCompatibleVersionsResponse.cpp \
    $${PWD}/OAIGetPackageVersionHistoryResponse.cpp \
    $${PWD}/OAIGetUpgradeHistoryResponse.cpp \
    $${PWD}/OAIGetUpgradeStatusResponse.cpp \
    $${PWD}/OAIInboundConnection.cpp \
    $${PWD}/OAIInboundConnectionStatus.cpp \
    $${PWD}/OAIInboundConnectionStatusCode.cpp \
    $${PWD}/OAIInboundConnection_ConnectionStatus.cpp \
    $${PWD}/OAIInstanceCountLimits.cpp \
    $${PWD}/OAIInstanceLimits.cpp \
    $${PWD}/OAIInstanceLimits_InstanceCountLimits.cpp \
    $${PWD}/OAIInstanceTypeDetails.cpp \
    $${PWD}/OAILimits.cpp \
    $${PWD}/OAILimits_InstanceLimits.cpp \
    $${PWD}/OAIListDomainNamesResponse.cpp \
    $${PWD}/OAIListDomainsForPackageResponse.cpp \
    $${PWD}/OAIListInstanceTypeDetailsResponse.cpp \
    $${PWD}/OAIListPackagesForDomainResponse.cpp \
    $${PWD}/OAIListScheduledActionsResponse.cpp \
    $${PWD}/OAIListTagsResponse.cpp \
    $${PWD}/OAIListVersionsResponse.cpp \
    $${PWD}/OAIListVpcEndpointAccessResponse.cpp \
    $${PWD}/OAIListVpcEndpointsForDomainResponse.cpp \
    $${PWD}/OAIListVpcEndpointsResponse.cpp \
    $${PWD}/OAILogPublishingOption.cpp \
    $${PWD}/OAILogPublishingOptionsStatus.cpp \
    $${PWD}/OAILogPublishingOptionsStatus_Status.cpp \
    $${PWD}/OAILogType.cpp \
    $${PWD}/OAIMasterNodeStatus.cpp \
    $${PWD}/OAIMasterUserOptions.cpp \
    $${PWD}/OAINodeStatus.cpp \
    $${PWD}/OAINodeToNodeEncryptionOptions.cpp \
    $${PWD}/OAINodeToNodeEncryptionOptionsStatus.cpp \
    $${PWD}/OAINodeToNodeEncryptionOptionsStatus_Options.cpp \
    $${PWD}/OAINodeToNodeEncryptionOptionsStatus_Status.cpp \
    $${PWD}/OAINodeType.cpp \
    $${PWD}/OAIOffPeakWindow.cpp \
    $${PWD}/OAIOffPeakWindowOptions.cpp \
    $${PWD}/OAIOffPeakWindowOptionsStatus.cpp \
    $${PWD}/OAIOffPeakWindowOptionsStatus_Options.cpp \
    $${PWD}/OAIOffPeakWindowOptionsStatus_Status.cpp \
    $${PWD}/OAIOffPeakWindow_WindowStartTime.cpp \
    $${PWD}/OAIOpenSearchPartitionInstanceType.cpp \
    $${PWD}/OAIOpenSearchWarmPartitionInstanceType.cpp \
    $${PWD}/OAIOptionState.cpp \
    $${PWD}/OAIOptionStatus.cpp \
    $${PWD}/OAIOutboundConnection.cpp \
    $${PWD}/OAIOutboundConnectionStatus.cpp \
    $${PWD}/OAIOutboundConnectionStatusCode.cpp \
    $${PWD}/OAIOutboundConnection_ConnectionProperties.cpp \
    $${PWD}/OAIOutboundConnection_ConnectionStatus.cpp \
    $${PWD}/OAIOverallChangeStatus.cpp \
    $${PWD}/OAIPackageDetails.cpp \
    $${PWD}/OAIPackageSource.cpp \
    $${PWD}/OAIPackageStatus.cpp \
    $${PWD}/OAIPackageType.cpp \
    $${PWD}/OAIPackageVersionHistory.cpp \
    $${PWD}/OAIPrincipalType.cpp \
    $${PWD}/OAIPurchaseReservedInstanceOfferingRequest.cpp \
    $${PWD}/OAIPurchaseReservedInstanceOfferingResponse.cpp \
    $${PWD}/OAIPurchaseReservedInstanceOffering_request.cpp \
    $${PWD}/OAIRecurringCharge.cpp \
    $${PWD}/OAIRejectInboundConnectionResponse.cpp \
    $${PWD}/OAIRejectInboundConnectionResponse_Connection.cpp \
    $${PWD}/OAIRemoveTagsRequest.cpp \
    $${PWD}/OAIRemoveTags_request.cpp \
    $${PWD}/OAIReservedInstance.cpp \
    $${PWD}/OAIReservedInstanceOffering.cpp \
    $${PWD}/OAIReservedInstancePaymentOption.cpp \
    $${PWD}/OAIRevokeVpcEndpointAccessRequest.cpp \
    $${PWD}/OAIRevokeVpcEndpointAccess_request.cpp \
    $${PWD}/OAIRollbackOnDisable.cpp \
    $${PWD}/OAISAMLIdp.cpp \
    $${PWD}/OAISAMLOptionsInput.cpp \
    $${PWD}/OAISAMLOptionsInput_Idp.cpp \
    $${PWD}/OAISAMLOptionsOutput.cpp \
    $${PWD}/OAISAMLOptionsOutput_Idp.cpp \
    $${PWD}/OAIScheduleAt.cpp \
    $${PWD}/OAIScheduledAction.cpp \
    $${PWD}/OAIScheduledAutoTuneActionType.cpp \
    $${PWD}/OAIScheduledAutoTuneDetails.cpp \
    $${PWD}/OAIScheduledAutoTuneSeverityType.cpp \
    $${PWD}/OAIScheduledBy.cpp \
    $${PWD}/OAIServiceSoftwareOptions.cpp \
    $${PWD}/OAISkipUnavailableStatus.cpp \
    $${PWD}/OAISnapshotOptions.cpp \
    $${PWD}/OAISnapshotOptionsStatus.cpp \
    $${PWD}/OAISnapshotOptionsStatus_Options.cpp \
    $${PWD}/OAISnapshotOptionsStatus_Status.cpp \
    $${PWD}/OAISoftwareUpdateOptions.cpp \
    $${PWD}/OAISoftwareUpdateOptionsStatus.cpp \
    $${PWD}/OAISoftwareUpdateOptionsStatus_Options.cpp \
    $${PWD}/OAISoftwareUpdateOptionsStatus_Status.cpp \
    $${PWD}/OAIStartServiceSoftwareUpdateRequest.cpp \
    $${PWD}/OAIStartServiceSoftwareUpdateResponse.cpp \
    $${PWD}/OAIStartServiceSoftwareUpdateResponse_ServiceSoftwareOptions.cpp \
    $${PWD}/OAIStartServiceSoftwareUpdate_request.cpp \
    $${PWD}/OAIStorageType.cpp \
    $${PWD}/OAIStorageTypeLimit.cpp \
    $${PWD}/OAITLSSecurityPolicy.cpp \
    $${PWD}/OAITag.cpp \
    $${PWD}/OAITimeUnit.cpp \
    $${PWD}/OAIUpdateDomainConfigRequest.cpp \
    $${PWD}/OAIUpdateDomainConfigRequest_AutoTuneOptions.cpp \
    $${PWD}/OAIUpdateDomainConfigRequest_ClusterConfig.cpp \
    $${PWD}/OAIUpdateDomainConfigRequest_EBSOptions.cpp \
    $${PWD}/OAIUpdateDomainConfigRequest_EncryptionAtRestOptions.cpp \
    $${PWD}/OAIUpdateDomainConfigRequest_NodeToNodeEncryptionOptions.cpp \
    $${PWD}/OAIUpdateDomainConfigRequest_OffPeakWindowOptions.cpp \
    $${PWD}/OAIUpdateDomainConfigRequest_SnapshotOptions.cpp \
    $${PWD}/OAIUpdateDomainConfigRequest_VPCOptions.cpp \
    $${PWD}/OAIUpdateDomainConfigResponse.cpp \
    $${PWD}/OAIUpdateDomainConfigResponse_DomainConfig.cpp \
    $${PWD}/OAIUpdateDomainConfigResponse_DryRunProgressStatus.cpp \
    $${PWD}/OAIUpdateDomainConfigResponse_DryRunResults.cpp \
    $${PWD}/OAIUpdateDomainConfig_request.cpp \
    $${PWD}/OAIUpdateDomainConfig_request_AutoTuneOptions.cpp \
    $${PWD}/OAIUpdatePackageRequest.cpp \
    $${PWD}/OAIUpdatePackageRequest_PackageSource.cpp \
    $${PWD}/OAIUpdatePackageResponse.cpp \
    $${PWD}/OAIUpdatePackageResponse_PackageDetails.cpp \
    $${PWD}/OAIUpdatePackage_request.cpp \
    $${PWD}/OAIUpdateScheduledActionRequest.cpp \
    $${PWD}/OAIUpdateScheduledActionResponse.cpp \
    $${PWD}/OAIUpdateScheduledActionResponse_ScheduledAction.cpp \
    $${PWD}/OAIUpdateScheduledAction_request.cpp \
    $${PWD}/OAIUpdateVpcEndpointRequest.cpp \
    $${PWD}/OAIUpdateVpcEndpointRequest_VpcOptions.cpp \
    $${PWD}/OAIUpdateVpcEndpointResponse.cpp \
    $${PWD}/OAIUpdateVpcEndpointResponse_VpcEndpoint.cpp \
    $${PWD}/OAIUpdateVpcEndpoint_request.cpp \
    $${PWD}/OAIUpgradeDomainRequest.cpp \
    $${PWD}/OAIUpgradeDomainResponse.cpp \
    $${PWD}/OAIUpgradeDomainResponse_ChangeProgressDetails.cpp \
    $${PWD}/OAIUpgradeDomain_request.cpp \
    $${PWD}/OAIUpgradeHistory.cpp \
    $${PWD}/OAIUpgradeStatus.cpp \
    $${PWD}/OAIUpgradeStep.cpp \
    $${PWD}/OAIUpgradeStepItem.cpp \
    $${PWD}/OAIVPCDerivedInfo.cpp \
    $${PWD}/OAIVPCDerivedInfoStatus.cpp \
    $${PWD}/OAIVPCDerivedInfoStatus_Options.cpp \
    $${PWD}/OAIVPCDerivedInfoStatus_Status.cpp \
    $${PWD}/OAIVPCOptions.cpp \
    $${PWD}/OAIValidationFailure.cpp \
    $${PWD}/OAIVersionStatus.cpp \
    $${PWD}/OAIVersionStatus_Status.cpp \
    $${PWD}/OAIVolumeType.cpp \
    $${PWD}/OAIVpcEndpoint.cpp \
    $${PWD}/OAIVpcEndpointError.cpp \
    $${PWD}/OAIVpcEndpointErrorCode.cpp \
    $${PWD}/OAIVpcEndpointStatus.cpp \
    $${PWD}/OAIVpcEndpointSummary.cpp \
    $${PWD}/OAIVpcEndpoint_VpcOptions.cpp \
    $${PWD}/OAIWindowStartTime.cpp \
    $${PWD}/OAIZoneAwarenessConfig.cpp \
    $${PWD}/OAIZoneStatus.cpp \
# APIs
    $${PWD}/OAIDefaultApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
