openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: Reads and writes Google Slides presentations.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Google Slides API
  version: v1
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
  x-origin:
  - converter:
      url: https://github.com/mermade/oas-kit
      version: 7.0.4
    format: google
    url: https://slides.googleapis.com/$discovery/rest?version=v1
    version: v1
  x-providerName: googleapis.com
  x-serviceName: slides
servers:
- url: https://slides.googleapis.com/
tags:
- name: presentations
paths:
  /v1/presentations:
    post:
      description: "Creates a blank presentation using the title given in the request.\
        \ If a `presentationId` is provided, it is used as the ID of the new presentation.\
        \ Otherwise, a new ID is generated. Other fields in the request, including\
        \ any provided content, are ignored. Returns the created presentation."
      operationId: slides_presentations_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/presentations
        Oauth2c:
        - https://www.googleapis.com/auth/presentations
      tags:
      - presentations
      x-openapi-router-controller: openapi_server.controllers.presentations_controller
  /v1/presentations/{presentationId}:
    get:
      description: Gets the latest version of the specified presentation.
      operationId: slides_presentations_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/presentations
        Oauth2c:
        - https://www.googleapis.com/auth/presentations
      - Oauth2:
        - https://www.googleapis.com/auth/presentations.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/presentations.readonly
      tags:
      - presentations
      x-openapi-router-controller: openapi_server.controllers.presentations_controller
  /v1/presentations/{presentationId}/pages/{pageObjectId}:
    get:
      description: Gets the latest version of the specified page in the presentation.
      operationId: slides_presentations_pages_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/presentations
        Oauth2c:
        - https://www.googleapis.com/auth/presentations
      - Oauth2:
        - https://www.googleapis.com/auth/presentations.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/presentations.readonly
      tags:
      - presentations
      x-openapi-router-controller: openapi_server.controllers.presentations_controller
  /v1/presentations/{presentationId}/pages/{pageObjectId}/thumbnail:
    get:
      description: "Generates a thumbnail of the latest version of the specified page\
        \ in the presentation and returns a URL to the thumbnail image. This request\
        \ counts as an [expensive read request](/slides/limits) for quota purposes."
      operationId: slides_presentations_pages_get_thumbnail
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/presentations
        Oauth2c:
        - https://www.googleapis.com/auth/presentations
      - Oauth2:
        - https://www.googleapis.com/auth/presentations.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/presentations.readonly
      tags:
      - presentations
      x-openapi-router-controller: openapi_server.controllers.presentations_controller
  /v1/presentations/{presentationId}:batchUpdate:
    post:
      description: "Applies one or more updates to the presentation. Each request\
        \ is validated before being applied. If any request is not valid, then the\
        \ entire request will fail and nothing will be applied. Some requests have\
        \ replies to give you some information about how they are applied. Other requests\
        \ do not need to return information; these each return an empty reply. The\
        \ order of replies matches that of the requests. For example, suppose you\
        \ call batchUpdate with four updates, and only the third one returns information.\
        \ The response would have two empty replies: the reply to the third request,\
        \ and another empty reply, in that order. Because other users may be editing\
        \ the presentation, the presentation might not exactly reflect your changes:\
        \ your changes may be altered with respect to collaborator changes. If there\
        \ are no collaborators, the presentation should reflect your changes. In any\
        \ case, the updates in your request are guaranteed to be applied together\
        \ atomically."
      operationId: slides_presentations_batch_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/presentations
        Oauth2c:
        - https://www.googleapis.com/auth/presentations
      - Oauth2:
        - https://www.googleapis.com/auth/spreadsheets
        Oauth2c:
        - https://www.googleapis.com/auth/spreadsheets
      - Oauth2:
        - https://www.googleapis.com/auth/spreadsheets.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/spreadsheets.readonly
      tags:
      - presentations
      x-openapi-router-controller: openapi_server.controllers.presentations_controller
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/drive: "See, edit, create, and delete\
              \ all of your Google Drive files"
            https://www.googleapis.com/auth/drive.file: "See, edit, create, and delete\
              \ only the specific Google Drive files you use with this app"
            https://www.googleapis.com/auth/drive.readonly: See and download all your
              Google Drive files
            https://www.googleapis.com/auth/presentations: "See, edit, create, and\
              \ delete all your Google Slides presentations"
            https://www.googleapis.com/auth/presentations.readonly: See all your Google
              Slides presentations
            https://www.googleapis.com/auth/spreadsheets: "See, edit, create, and\
              \ delete all your Google Sheets spreadsheets"
            https://www.googleapis.com/auth/spreadsheets.readonly: See all your Google
              Sheets spreadsheets
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/drive: "See, edit, create, and delete\
              \ all of your Google Drive files"
            https://www.googleapis.com/auth/drive.file: "See, edit, create, and delete\
              \ only the specific Google Drive files you use with this app"
            https://www.googleapis.com/auth/drive.readonly: See and download all your
              Google Drive files
            https://www.googleapis.com/auth/presentations: "See, edit, create, and\
              \ delete all your Google Slides presentations"
            https://www.googleapis.com/auth/presentations.readonly: See all your Google
              Slides presentations
            https://www.googleapis.com/auth/spreadsheets: "See, edit, create, and\
              \ delete all your Google Sheets spreadsheets"
            https://www.googleapis.com/auth/spreadsheets.readonly: See all your Google
              Sheets spreadsheets
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2c
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2c
