QT += network

HEADERS += \
# Models
    $${PWD}/OAICacheExpirationActionParameters.h \
    $${PWD}/OAICacheKeyQueryStringActionParameters.h \
    $${PWD}/OAICdnCertificateSourceParameters.h \
    $${PWD}/OAICdnManagedHttpsParameters.h \
    $${PWD}/OAICheckNameAvailabilityInput.h \
    $${PWD}/OAICheckNameAvailabilityOutput.h \
    $${PWD}/OAICidrIpAddress.h \
    $${PWD}/OAICookiesMatchConditionParameters.h \
    $${PWD}/OAICustomDomain.h \
    $${PWD}/OAICustomDomainHttpsParameters.h \
    $${PWD}/OAICustomDomainListResult.h \
    $${PWD}/OAICustomDomainParameters.h \
    $${PWD}/OAICustomDomainProperties.h \
    $${PWD}/OAICustomDomainPropertiesParameters.h \
    $${PWD}/OAIDeepCreatedOrigin.h \
    $${PWD}/OAIDeepCreatedOriginProperties.h \
    $${PWD}/OAIDeliveryRule.h \
    $${PWD}/OAIDeliveryRuleAction.h \
    $${PWD}/OAIDeliveryRuleCacheExpirationAction.h \
    $${PWD}/OAIDeliveryRuleCacheKeyQueryStringAction.h \
    $${PWD}/OAIDeliveryRuleCondition.h \
    $${PWD}/OAIDeliveryRuleCookiesCondition.h \
    $${PWD}/OAIDeliveryRuleHttpVersionCondition.h \
    $${PWD}/OAIDeliveryRuleIsDeviceCondition.h \
    $${PWD}/OAIDeliveryRulePostArgsCondition.h \
    $${PWD}/OAIDeliveryRuleQueryStringCondition.h \
    $${PWD}/OAIDeliveryRuleRemoteAddressCondition.h \
    $${PWD}/OAIDeliveryRuleRequestBodyCondition.h \
    $${PWD}/OAIDeliveryRuleRequestHeaderAction.h \
    $${PWD}/OAIDeliveryRuleRequestHeaderCondition.h \
    $${PWD}/OAIDeliveryRuleRequestMethodCondition.h \
    $${PWD}/OAIDeliveryRuleRequestSchemeCondition.h \
    $${PWD}/OAIDeliveryRuleRequestUriCondition.h \
    $${PWD}/OAIDeliveryRuleResponseHeaderAction.h \
    $${PWD}/OAIDeliveryRuleUrlFileExtensionCondition.h \
    $${PWD}/OAIDeliveryRuleUrlFileNameCondition.h \
    $${PWD}/OAIDeliveryRuleUrlPathCondition.h \
    $${PWD}/OAIEdgeNode.h \
    $${PWD}/OAIEdgeNodeProperties.h \
    $${PWD}/OAIEdgenodeResult.h \
    $${PWD}/OAIEndpoint.h \
    $${PWD}/OAIEndpointListResult.h \
    $${PWD}/OAIEndpointProperties.h \
    $${PWD}/OAIEndpointPropertiesUpdateParameters.h \
    $${PWD}/OAIEndpointPropertiesUpdateParameters_deliveryPolicy.h \
    $${PWD}/OAIEndpointPropertiesUpdateParameters_webApplicationFirewallPolicyLink.h \
    $${PWD}/OAIEndpointUpdateParameters.h \
    $${PWD}/OAIErrorResponse.h \
    $${PWD}/OAIGeoFilter.h \
    $${PWD}/OAIHeaderActionParameters.h \
    $${PWD}/OAIHttpVersionMatchConditionParameters.h \
    $${PWD}/OAIIpAddressGroup.h \
    $${PWD}/OAIIsDeviceMatchConditionParameters.h \
    $${PWD}/OAIKeyVaultCertificateSourceParameters.h \
    $${PWD}/OAILoadParameters.h \
    $${PWD}/OAIOperation.h \
    $${PWD}/OAIOperation_display.h \
    $${PWD}/OAIOperationsListResult.h \
    $${PWD}/OAIOptimizationType.h \
    $${PWD}/OAIOrigin.h \
    $${PWD}/OAIOriginListResult.h \
    $${PWD}/OAIOriginProperties.h \
    $${PWD}/OAIOriginPropertiesParameters.h \
    $${PWD}/OAIOriginUpdateParameters.h \
    $${PWD}/OAIPostArgsMatchConditionParameters.h \
    $${PWD}/OAIProfile.h \
    $${PWD}/OAIProfileListResult.h \
    $${PWD}/OAIProfileProperties.h \
    $${PWD}/OAIProfileUpdateParameters.h \
    $${PWD}/OAIProxyResource.h \
    $${PWD}/OAIPurgeParameters.h \
    $${PWD}/OAIQueryStringCachingBehavior.h \
    $${PWD}/OAIQueryStringMatchConditionParameters.h \
    $${PWD}/OAIRemoteAddressMatchConditionParameters.h \
    $${PWD}/OAIRequestBodyMatchConditionParameters.h \
    $${PWD}/OAIRequestHeaderMatchConditionParameters.h \
    $${PWD}/OAIRequestMethodMatchConditionParameters.h \
    $${PWD}/OAIRequestSchemeMatchConditionParameters.h \
    $${PWD}/OAIRequestUriMatchConditionParameters.h \
    $${PWD}/OAIResource.h \
    $${PWD}/OAIResourceType.h \
    $${PWD}/OAIResourceUsage.h \
    $${PWD}/OAIResourceUsageListResult.h \
    $${PWD}/OAISku.h \
    $${PWD}/OAISsoUri.h \
    $${PWD}/OAISupportedOptimizationTypesListResult.h \
    $${PWD}/OAITrackedResource.h \
    $${PWD}/OAITransform.h \
    $${PWD}/OAIUrlFileExtensionMatchConditionParameters.h \
    $${PWD}/OAIUrlFileNameMatchConditionParameters.h \
    $${PWD}/OAIUrlPathMatchConditionParameters.h \
    $${PWD}/OAIUrlRedirectAction.h \
    $${PWD}/OAIUrlRedirectActionParameters.h \
    $${PWD}/OAIUrlRewriteAction.h \
    $${PWD}/OAIUrlRewriteActionParameters.h \
    $${PWD}/OAIUserManagedHttpsParameters.h \
    $${PWD}/OAIValidateCustomDomainInput.h \
    $${PWD}/OAIValidateCustomDomainOutput.h \
    $${PWD}/OAIValidateProbeInput.h \
    $${PWD}/OAIValidateProbeOutput.h \
# APIs
    $${PWD}/OAICheckNameAvailabilityApi.h \
    $${PWD}/OAICheckNameAvailabilityWithSubscriptionApi.h \
    $${PWD}/OAICheckResourceUsageApi.h \
    $${PWD}/OAICustomDomainsApi.h \
    $${PWD}/OAIEdgenodesApi.h \
    $${PWD}/OAIEndpointsApi.h \
    $${PWD}/OAIOperationsApi.h \
    $${PWD}/OAIOriginsApi.h \
    $${PWD}/OAIProfilesApi.h \
    $${PWD}/OAIValidateProbeApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAICacheExpirationActionParameters.cpp \
    $${PWD}/OAICacheKeyQueryStringActionParameters.cpp \
    $${PWD}/OAICdnCertificateSourceParameters.cpp \
    $${PWD}/OAICdnManagedHttpsParameters.cpp \
    $${PWD}/OAICheckNameAvailabilityInput.cpp \
    $${PWD}/OAICheckNameAvailabilityOutput.cpp \
    $${PWD}/OAICidrIpAddress.cpp \
    $${PWD}/OAICookiesMatchConditionParameters.cpp \
    $${PWD}/OAICustomDomain.cpp \
    $${PWD}/OAICustomDomainHttpsParameters.cpp \
    $${PWD}/OAICustomDomainListResult.cpp \
    $${PWD}/OAICustomDomainParameters.cpp \
    $${PWD}/OAICustomDomainProperties.cpp \
    $${PWD}/OAICustomDomainPropertiesParameters.cpp \
    $${PWD}/OAIDeepCreatedOrigin.cpp \
    $${PWD}/OAIDeepCreatedOriginProperties.cpp \
    $${PWD}/OAIDeliveryRule.cpp \
    $${PWD}/OAIDeliveryRuleAction.cpp \
    $${PWD}/OAIDeliveryRuleCacheExpirationAction.cpp \
    $${PWD}/OAIDeliveryRuleCacheKeyQueryStringAction.cpp \
    $${PWD}/OAIDeliveryRuleCondition.cpp \
    $${PWD}/OAIDeliveryRuleCookiesCondition.cpp \
    $${PWD}/OAIDeliveryRuleHttpVersionCondition.cpp \
    $${PWD}/OAIDeliveryRuleIsDeviceCondition.cpp \
    $${PWD}/OAIDeliveryRulePostArgsCondition.cpp \
    $${PWD}/OAIDeliveryRuleQueryStringCondition.cpp \
    $${PWD}/OAIDeliveryRuleRemoteAddressCondition.cpp \
    $${PWD}/OAIDeliveryRuleRequestBodyCondition.cpp \
    $${PWD}/OAIDeliveryRuleRequestHeaderAction.cpp \
    $${PWD}/OAIDeliveryRuleRequestHeaderCondition.cpp \
    $${PWD}/OAIDeliveryRuleRequestMethodCondition.cpp \
    $${PWD}/OAIDeliveryRuleRequestSchemeCondition.cpp \
    $${PWD}/OAIDeliveryRuleRequestUriCondition.cpp \
    $${PWD}/OAIDeliveryRuleResponseHeaderAction.cpp \
    $${PWD}/OAIDeliveryRuleUrlFileExtensionCondition.cpp \
    $${PWD}/OAIDeliveryRuleUrlFileNameCondition.cpp \
    $${PWD}/OAIDeliveryRuleUrlPathCondition.cpp \
    $${PWD}/OAIEdgeNode.cpp \
    $${PWD}/OAIEdgeNodeProperties.cpp \
    $${PWD}/OAIEdgenodeResult.cpp \
    $${PWD}/OAIEndpoint.cpp \
    $${PWD}/OAIEndpointListResult.cpp \
    $${PWD}/OAIEndpointProperties.cpp \
    $${PWD}/OAIEndpointPropertiesUpdateParameters.cpp \
    $${PWD}/OAIEndpointPropertiesUpdateParameters_deliveryPolicy.cpp \
    $${PWD}/OAIEndpointPropertiesUpdateParameters_webApplicationFirewallPolicyLink.cpp \
    $${PWD}/OAIEndpointUpdateParameters.cpp \
    $${PWD}/OAIErrorResponse.cpp \
    $${PWD}/OAIGeoFilter.cpp \
    $${PWD}/OAIHeaderActionParameters.cpp \
    $${PWD}/OAIHttpVersionMatchConditionParameters.cpp \
    $${PWD}/OAIIpAddressGroup.cpp \
    $${PWD}/OAIIsDeviceMatchConditionParameters.cpp \
    $${PWD}/OAIKeyVaultCertificateSourceParameters.cpp \
    $${PWD}/OAILoadParameters.cpp \
    $${PWD}/OAIOperation.cpp \
    $${PWD}/OAIOperation_display.cpp \
    $${PWD}/OAIOperationsListResult.cpp \
    $${PWD}/OAIOptimizationType.cpp \
    $${PWD}/OAIOrigin.cpp \
    $${PWD}/OAIOriginListResult.cpp \
    $${PWD}/OAIOriginProperties.cpp \
    $${PWD}/OAIOriginPropertiesParameters.cpp \
    $${PWD}/OAIOriginUpdateParameters.cpp \
    $${PWD}/OAIPostArgsMatchConditionParameters.cpp \
    $${PWD}/OAIProfile.cpp \
    $${PWD}/OAIProfileListResult.cpp \
    $${PWD}/OAIProfileProperties.cpp \
    $${PWD}/OAIProfileUpdateParameters.cpp \
    $${PWD}/OAIProxyResource.cpp \
    $${PWD}/OAIPurgeParameters.cpp \
    $${PWD}/OAIQueryStringCachingBehavior.cpp \
    $${PWD}/OAIQueryStringMatchConditionParameters.cpp \
    $${PWD}/OAIRemoteAddressMatchConditionParameters.cpp \
    $${PWD}/OAIRequestBodyMatchConditionParameters.cpp \
    $${PWD}/OAIRequestHeaderMatchConditionParameters.cpp \
    $${PWD}/OAIRequestMethodMatchConditionParameters.cpp \
    $${PWD}/OAIRequestSchemeMatchConditionParameters.cpp \
    $${PWD}/OAIRequestUriMatchConditionParameters.cpp \
    $${PWD}/OAIResource.cpp \
    $${PWD}/OAIResourceType.cpp \
    $${PWD}/OAIResourceUsage.cpp \
    $${PWD}/OAIResourceUsageListResult.cpp \
    $${PWD}/OAISku.cpp \
    $${PWD}/OAISsoUri.cpp \
    $${PWD}/OAISupportedOptimizationTypesListResult.cpp \
    $${PWD}/OAITrackedResource.cpp \
    $${PWD}/OAITransform.cpp \
    $${PWD}/OAIUrlFileExtensionMatchConditionParameters.cpp \
    $${PWD}/OAIUrlFileNameMatchConditionParameters.cpp \
    $${PWD}/OAIUrlPathMatchConditionParameters.cpp \
    $${PWD}/OAIUrlRedirectAction.cpp \
    $${PWD}/OAIUrlRedirectActionParameters.cpp \
    $${PWD}/OAIUrlRewriteAction.cpp \
    $${PWD}/OAIUrlRewriteActionParameters.cpp \
    $${PWD}/OAIUserManagedHttpsParameters.cpp \
    $${PWD}/OAIValidateCustomDomainInput.cpp \
    $${PWD}/OAIValidateCustomDomainOutput.cpp \
    $${PWD}/OAIValidateProbeInput.cpp \
    $${PWD}/OAIValidateProbeOutput.cpp \
# APIs
    $${PWD}/OAICheckNameAvailabilityApi.cpp \
    $${PWD}/OAICheckNameAvailabilityWithSubscriptionApi.cpp \
    $${PWD}/OAICheckResourceUsageApi.cpp \
    $${PWD}/OAICustomDomainsApi.cpp \
    $${PWD}/OAIEdgenodesApi.cpp \
    $${PWD}/OAIEndpointsApi.cpp \
    $${PWD}/OAIOperationsApi.cpp \
    $${PWD}/OAIOriginsApi.cpp \
    $${PWD}/OAIProfilesApi.cpp \
    $${PWD}/OAIValidateProbeApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
