QT += network

HEADERS += \
# Models
    $${PWD}/OAIAggregation.h \
    $${PWD}/OAIAggregationQuery.h \
    $${PWD}/OAIAggregationResult.h \
    $${PWD}/OAIAggregationResultBatch.h \
    $${PWD}/OAIAllocateIdsRequest.h \
    $${PWD}/OAIAllocateIdsResponse.h \
    $${PWD}/OAIArrayValue.h \
    $${PWD}/OAIAvg.h \
    $${PWD}/OAIBeginTransactionRequest.h \
    $${PWD}/OAIBeginTransactionResponse.h \
    $${PWD}/OAICommitRequest.h \
    $${PWD}/OAICommitResponse.h \
    $${PWD}/OAICompositeFilter.h \
    $${PWD}/OAICount.h \
    $${PWD}/OAIEntity.h \
    $${PWD}/OAIEntityResult.h \
    $${PWD}/OAIFilter.h \
    $${PWD}/OAIGoogleDatastoreAdminV1CommonMetadata.h \
    $${PWD}/OAIGoogleDatastoreAdminV1DatastoreFirestoreMigrationMetadata.h \
    $${PWD}/OAIGoogleDatastoreAdminV1EntityFilter.h \
    $${PWD}/OAIGoogleDatastoreAdminV1ExportEntitiesMetadata.h \
    $${PWD}/OAIGoogleDatastoreAdminV1ExportEntitiesRequest.h \
    $${PWD}/OAIGoogleDatastoreAdminV1ExportEntitiesResponse.h \
    $${PWD}/OAIGoogleDatastoreAdminV1ImportEntitiesMetadata.h \
    $${PWD}/OAIGoogleDatastoreAdminV1ImportEntitiesRequest.h \
    $${PWD}/OAIGoogleDatastoreAdminV1Index.h \
    $${PWD}/OAIGoogleDatastoreAdminV1IndexOperationMetadata.h \
    $${PWD}/OAIGoogleDatastoreAdminV1IndexedProperty.h \
    $${PWD}/OAIGoogleDatastoreAdminV1ListIndexesResponse.h \
    $${PWD}/OAIGoogleDatastoreAdminV1MigrationProgressEvent.h \
    $${PWD}/OAIGoogleDatastoreAdminV1MigrationStateEvent.h \
    $${PWD}/OAIGoogleDatastoreAdminV1PrepareStepDetails.h \
    $${PWD}/OAIGoogleDatastoreAdminV1Progress.h \
    $${PWD}/OAIGoogleDatastoreAdminV1RedirectWritesStepDetails.h \
    $${PWD}/OAIGoogleDatastoreAdminV1beta1CommonMetadata.h \
    $${PWD}/OAIGoogleDatastoreAdminV1beta1EntityFilter.h \
    $${PWD}/OAIGoogleDatastoreAdminV1beta1ExportEntitiesMetadata.h \
    $${PWD}/OAIGoogleDatastoreAdminV1beta1ExportEntitiesResponse.h \
    $${PWD}/OAIGoogleDatastoreAdminV1beta1ImportEntitiesMetadata.h \
    $${PWD}/OAIGoogleDatastoreAdminV1beta1Progress.h \
    $${PWD}/OAIGoogleLongrunningListOperationsResponse.h \
    $${PWD}/OAIGoogleLongrunningOperation.h \
    $${PWD}/OAIGqlQuery.h \
    $${PWD}/OAIGqlQueryParameter.h \
    $${PWD}/OAIKey.h \
    $${PWD}/OAIKindExpression.h \
    $${PWD}/OAILatLng.h \
    $${PWD}/OAILookupRequest.h \
    $${PWD}/OAILookupResponse.h \
    $${PWD}/OAIMutation.h \
    $${PWD}/OAIMutationResult.h \
    $${PWD}/OAIPartitionId.h \
    $${PWD}/OAIPathElement.h \
    $${PWD}/OAIProjection.h \
    $${PWD}/OAIPropertyFilter.h \
    $${PWD}/OAIPropertyOrder.h \
    $${PWD}/OAIPropertyReference.h \
    $${PWD}/OAIQuery.h \
    $${PWD}/OAIQueryResultBatch.h \
    $${PWD}/OAIReadOnly.h \
    $${PWD}/OAIReadOptions.h \
    $${PWD}/OAIReadWrite.h \
    $${PWD}/OAIReserveIdsRequest.h \
    $${PWD}/OAIRollbackRequest.h \
    $${PWD}/OAIRunAggregationQueryRequest.h \
    $${PWD}/OAIRunAggregationQueryResponse.h \
    $${PWD}/OAIRunQueryRequest.h \
    $${PWD}/OAIRunQueryResponse.h \
    $${PWD}/OAIStatus.h \
    $${PWD}/OAISum.h \
    $${PWD}/OAITransactionOptions.h \
    $${PWD}/OAIValue.h \
# APIs
    $${PWD}/OAIProjectsApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAggregation.cpp \
    $${PWD}/OAIAggregationQuery.cpp \
    $${PWD}/OAIAggregationResult.cpp \
    $${PWD}/OAIAggregationResultBatch.cpp \
    $${PWD}/OAIAllocateIdsRequest.cpp \
    $${PWD}/OAIAllocateIdsResponse.cpp \
    $${PWD}/OAIArrayValue.cpp \
    $${PWD}/OAIAvg.cpp \
    $${PWD}/OAIBeginTransactionRequest.cpp \
    $${PWD}/OAIBeginTransactionResponse.cpp \
    $${PWD}/OAICommitRequest.cpp \
    $${PWD}/OAICommitResponse.cpp \
    $${PWD}/OAICompositeFilter.cpp \
    $${PWD}/OAICount.cpp \
    $${PWD}/OAIEntity.cpp \
    $${PWD}/OAIEntityResult.cpp \
    $${PWD}/OAIFilter.cpp \
    $${PWD}/OAIGoogleDatastoreAdminV1CommonMetadata.cpp \
    $${PWD}/OAIGoogleDatastoreAdminV1DatastoreFirestoreMigrationMetadata.cpp \
    $${PWD}/OAIGoogleDatastoreAdminV1EntityFilter.cpp \
    $${PWD}/OAIGoogleDatastoreAdminV1ExportEntitiesMetadata.cpp \
    $${PWD}/OAIGoogleDatastoreAdminV1ExportEntitiesRequest.cpp \
    $${PWD}/OAIGoogleDatastoreAdminV1ExportEntitiesResponse.cpp \
    $${PWD}/OAIGoogleDatastoreAdminV1ImportEntitiesMetadata.cpp \
    $${PWD}/OAIGoogleDatastoreAdminV1ImportEntitiesRequest.cpp \
    $${PWD}/OAIGoogleDatastoreAdminV1Index.cpp \
    $${PWD}/OAIGoogleDatastoreAdminV1IndexOperationMetadata.cpp \
    $${PWD}/OAIGoogleDatastoreAdminV1IndexedProperty.cpp \
    $${PWD}/OAIGoogleDatastoreAdminV1ListIndexesResponse.cpp \
    $${PWD}/OAIGoogleDatastoreAdminV1MigrationProgressEvent.cpp \
    $${PWD}/OAIGoogleDatastoreAdminV1MigrationStateEvent.cpp \
    $${PWD}/OAIGoogleDatastoreAdminV1PrepareStepDetails.cpp \
    $${PWD}/OAIGoogleDatastoreAdminV1Progress.cpp \
    $${PWD}/OAIGoogleDatastoreAdminV1RedirectWritesStepDetails.cpp \
    $${PWD}/OAIGoogleDatastoreAdminV1beta1CommonMetadata.cpp \
    $${PWD}/OAIGoogleDatastoreAdminV1beta1EntityFilter.cpp \
    $${PWD}/OAIGoogleDatastoreAdminV1beta1ExportEntitiesMetadata.cpp \
    $${PWD}/OAIGoogleDatastoreAdminV1beta1ExportEntitiesResponse.cpp \
    $${PWD}/OAIGoogleDatastoreAdminV1beta1ImportEntitiesMetadata.cpp \
    $${PWD}/OAIGoogleDatastoreAdminV1beta1Progress.cpp \
    $${PWD}/OAIGoogleLongrunningListOperationsResponse.cpp \
    $${PWD}/OAIGoogleLongrunningOperation.cpp \
    $${PWD}/OAIGqlQuery.cpp \
    $${PWD}/OAIGqlQueryParameter.cpp \
    $${PWD}/OAIKey.cpp \
    $${PWD}/OAIKindExpression.cpp \
    $${PWD}/OAILatLng.cpp \
    $${PWD}/OAILookupRequest.cpp \
    $${PWD}/OAILookupResponse.cpp \
    $${PWD}/OAIMutation.cpp \
    $${PWD}/OAIMutationResult.cpp \
    $${PWD}/OAIPartitionId.cpp \
    $${PWD}/OAIPathElement.cpp \
    $${PWD}/OAIProjection.cpp \
    $${PWD}/OAIPropertyFilter.cpp \
    $${PWD}/OAIPropertyOrder.cpp \
    $${PWD}/OAIPropertyReference.cpp \
    $${PWD}/OAIQuery.cpp \
    $${PWD}/OAIQueryResultBatch.cpp \
    $${PWD}/OAIReadOnly.cpp \
    $${PWD}/OAIReadOptions.cpp \
    $${PWD}/OAIReadWrite.cpp \
    $${PWD}/OAIReserveIdsRequest.cpp \
    $${PWD}/OAIRollbackRequest.cpp \
    $${PWD}/OAIRunAggregationQueryRequest.cpp \
    $${PWD}/OAIRunAggregationQueryResponse.cpp \
    $${PWD}/OAIRunQueryRequest.cpp \
    $${PWD}/OAIRunQueryResponse.cpp \
    $${PWD}/OAIStatus.cpp \
    $${PWD}/OAISum.cpp \
    $${PWD}/OAITransactionOptions.cpp \
    $${PWD}/OAIValue.cpp \
# APIs
    $${PWD}/OAIProjectsApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
