openapi: 3.0.0
info:
  contact:
    email: api@xero.com
    name: Xero Platform Team
    url: https://developer.xero.com
    x-twitter: XeroAPI
  description: These endpoints are specific to Xero Files API
  termsOfService: https://developer.xero.com/xero-developer-platform-terms-conditions/
  title: Xero Files API
  version: 2.9.4
  x-apisguru-categories:
  - financial
  x-origin:
  - format: openapi
    url: https://raw.githubusercontent.com/XeroAPI/Xero-OpenAPI/master/xero_files.yaml
    version: "3.0"
  x-providerName: xero.com
  x-serviceName: xero_files
servers:
- description: Xero Files API
  url: https://api.xero.com/files.xro/1.0/
tags:
- description: Operations available to regular developers
  name: Files
paths:
  /Associations/{ObjectId}:
    get:
      description: "By passing in the appropriate options,"
      operationId: get_associations_by_object
      security:
      - OAuth2:
        - files.read
      summary: Retrieves an association object using a unique object ID
      tags:
      - Files
      x-openapi-router-controller: openapi_server.controllers.files_controller
  /Files:
    get:
      operationId: get_files
      security:
      - OAuth2:
        - files.read
      summary: Retrieves files
      tags:
      - Files
      x-openapi-router-controller: openapi_server.controllers.files_controller
    post:
      operationId: upload_file
      security:
      - OAuth2:
        - files
      summary: Uploads a File
      tags:
      - Files
      x-openapi-router-controller: openapi_server.controllers.files_controller
  /Files/{FileId}:
    delete:
      description: Delete a specific file
      operationId: delete_file
      security:
      - OAuth2:
        - files
      summary: Deletes a specific file
      tags:
      - Files
      x-openapi-router-controller: openapi_server.controllers.files_controller
    get:
      operationId: get_file
      security:
      - OAuth2:
        - files.read
      summary: Retrieves a file by a unique file ID
      tags:
      - Files
      x-openapi-router-controller: openapi_server.controllers.files_controller
    put:
      description: Updates file properties of a single file
      operationId: update_file
      security:
      - OAuth2:
        - files
      summary: Update a file
      tags:
      - Files
      x-openapi-router-controller: openapi_server.controllers.files_controller
  /Files/{FileId}/Associations:
    get:
      description: "By passing in the appropriate options, \n"
      operationId: get_file_associations
      security:
      - OAuth2:
        - files.read
      summary: Retrieves a specific file associations
      tags:
      - Files
      x-openapi-router-controller: openapi_server.controllers.files_controller
    post:
      description: "By passing in the appropriate options, you can create a new folder"
      operationId: create_file_association
      security:
      - OAuth2:
        - files
      summary: Creates a new file association
      tags:
      - Files
      x-openapi-router-controller: openapi_server.controllers.files_controller
  /Files/{FileId}/Associations/{ObjectId}:
    delete:
      description: "By passing in the appropriate options, you can create a new folder"
      operationId: delete_file_association
      security:
      - OAuth2:
        - files
      summary: Deletes an existing file association
      tags:
      - Files
      x-openapi-router-controller: openapi_server.controllers.files_controller
  /Files/{FileId}/Content:
    get:
      description: "By passing in the appropriate options, retrieve data for specific\
        \ file"
      operationId: get_file_content
      security:
      - OAuth2:
        - files.read
      summary: Retrieves the content of a specific file
      tags:
      - Files
      x-openapi-router-controller: openapi_server.controllers.files_controller
  /Folders:
    get:
      description: "By passing in the appropriate options, you can search for available\
        \ folders"
      operationId: get_folders
      security:
      - OAuth2:
        - files.read
      summary: Retrieves folders
      tags:
      - Files
      x-openapi-router-controller: openapi_server.controllers.files_controller
    post:
      description: "By passing in the appropriate properties, you can create a new\
        \ folder"
      operationId: create_folder
      security:
      - OAuth2:
        - files
      summary: Creates a new folder
      tags:
      - Files
      x-openapi-router-controller: openapi_server.controllers.files_controller
  /Folders/{FolderId}:
    delete:
      description: "By passing in the appropriate ID, you can delete a folder"
      operationId: delete_folder
      security:
      - OAuth2:
        - files
      summary: Deletes a folder
      tags:
      - Files
      x-openapi-router-controller: openapi_server.controllers.files_controller
    get:
      description: "By passing in the appropriate ID, you can search for specific\
        \ folder"
      operationId: get_folder
      security:
      - OAuth2:
        - files.read
      summary: Retrieves specific folder by using a unique folder ID
      tags:
      - Files
      x-openapi-router-controller: openapi_server.controllers.files_controller
    put:
      description: "By passing in the appropriate ID and properties, you can update\
        \ a folder"
      operationId: update_folder
      security:
      - OAuth2:
        - files
      summary: Updates an existing folder
      tags:
      - Files
      x-openapi-router-controller: openapi_server.controllers.files_controller
  /Inbox:
    get:
      description: Search for the user inbox
      operationId: get_inbox
      security:
      - OAuth2:
        - files.read
      summary: Retrieves inbox folder
      tags:
      - Files
      x-openapi-router-controller: openapi_server.controllers.files_controller
components:
  securitySchemes:
    OAuth2:
      description: For more information
      flows:
        authorizationCode:
          authorizationUrl: https://login.xero.com/identity/connect/authorize
          scopes:
            email: Grant read-only access to your email
            files: Grant read-write access to files and folders
            files.read: Grant read-only access to files and folders
            openid: Grant read-only access to your open id
            profile: your profile information
          tokenUrl: https://identity.xero.com/connect/token
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_OAuth2
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_OAuth2
