# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.create_volume_response_volume import CreateVolumeResponseVolume
from openapi_server import util


class CreateVolumeResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, volume: CreateVolumeResponseVolume=None):
        """CreateVolumeResponse - a model defined in OpenAPI

        :param volume: The volume of this CreateVolumeResponse.
        """
        self.openapi_types = {
            'volume': CreateVolumeResponseVolume
        }

        self.attribute_map = {
            'volume': 'Volume'
        }

        self._volume = volume

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CreateVolumeResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The CreateVolumeResponse of this CreateVolumeResponse.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def volume(self):
        """Gets the volume of this CreateVolumeResponse.


        :return: The volume of this CreateVolumeResponse.
        :rtype: CreateVolumeResponseVolume
        """
        return self._volume

    @volume.setter
    def volume(self, volume):
        """Sets the volume of this CreateVolumeResponse.


        :param volume: The volume of this CreateVolumeResponse.
        :type volume: CreateVolumeResponseVolume
        """

        self._volume = volume
