openapi: 3.0.0
info:
  contact:
    email: integrations@reverb.com
    name: Reverb API
    url: https://www.reverb-api.com
  description: reverb
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://reverb.com/page/terms
  title: reverb
  version: "3.0"
  x-apisguru-categories:
  - ecommerce
  x-logo:
    url: https://d1g5417jjjo7sf.cloudfront.net/assets/top-level/reverb-logo-d2c75af0b020521f0bc5e90c883a13b5.svg
  x-origin:
  - format: openapi
    url: https://s3.amazonaws.com/swagger.reverb.com/swagger.json
    version: "3.0"
  x-providerName: reverb.com
servers:
- url: https://api.reverb.com/api
paths:
  /articles:
    get:
      operationId: articles_get
      tags:
      - articles
      x-openapi-router-controller: openapi_server.controllers.articles_controller
  /articles/categories:
    get:
      description: List of all article categories
      operationId: articles_categories_get
      summary: List of all article categories
      tags:
      - articles
      x-openapi-router-controller: openapi_server.controllers.articles_controller
  /categories:
    get:
      description: List of supported product categories
      operationId: categories_get
      summary: List of supported product categories
      tags:
      - categories
      x-openapi-router-controller: openapi_server.controllers.categories_controller
  /categories/flat:
    get:
      operationId: categories_flat_get
      tags:
      - categories
      x-openapi-router-controller: openapi_server.controllers.categories_controller
  /categories/taxonomy:
    get:
      description: Full taxonomy tree of categories including middle categories
      operationId: categories_taxonomy_get
      summary: Full taxonomy tree of categories including middle categories
      tags:
      - categories
      x-openapi-router-controller: openapi_server.controllers.categories_controller
  /categories/{product_type}/{category}:
    get:
      description: Get subcategory details
      operationId: categories_product_type_category_get
      summary: Get subcategory details
      tags:
      - categories
      x-openapi-router-controller: openapi_server.controllers.categories_controller
  /categories/{uuid}:
    get:
      description: Get category details
      operationId: categories_uuid_get
      summary: Get category details
      tags:
      - categories
      x-openapi-router-controller: openapi_server.controllers.categories_controller
  /comparison_shopping_pages:
    get:
      description: Returns a set of comparison shopping pages based on the current
        params
      operationId: comparison_shopping_pages_get
      summary: Returns a set of comparison shopping pages based on the current params
      tags:
      - comparison_shopping_pages
      x-openapi-router-controller: openapi_server.controllers.comparison_shopping_pages_controller
  /comparison_shopping_pages/find:
    get:
      description: Show comparison shopping page
      operationId: comparison_shopping_pages_find_get
      summary: Show comparison shopping page
      tags:
      - comparison_shopping_pages
      x-openapi-router-controller: openapi_server.controllers.comparison_shopping_pages_controller
  /comparison_shopping_pages/{id}:
    get:
      operationId: comparison_shopping_pages_id_get
      tags:
      - comparison_shopping_pages
      x-openapi-router-controller: openapi_server.controllers.comparison_shopping_pages_controller
  /comparison_shopping_pages/{id}/listings:
    get:
      description: Return new or used listings for a comparison shopping page
      operationId: comparison_shopping_pages_id_listings_get
      summary: Return new or used listings for a comparison shopping page
      tags:
      - comparison_shopping_pages
      x-openapi-router-controller: openapi_server.controllers.comparison_shopping_pages_controller
  /comparison_shopping_pages/{id}/reviews:
    get:
      description: View reviews of a comparison shopping page
      operationId: comparison_shopping_pages_id_reviews_get
      summary: View reviews of a comparison shopping page
      tags:
      - comparison_shopping_pages
      x-openapi-router-controller: openapi_server.controllers.comparison_shopping_pages_controller
  /conversations/{conversation_id}/offer:
    post:
      description: Make an offer to the other participant in the conversation
      operationId: conversations_conversation_id_offer_post
      security:
      - oauth2:
        - write_offers
      summary: Make an offer to the other participant in the conversation
      tags:
      - conversations
      x-openapi-router-controller: openapi_server.controllers.conversations_controller
  /conversations/{id}/offer:
    post:
      description: Make an offer to the other participant in the conversation
      operationId: conversations_id_offer_post
      security:
      - oauth2:
        - write_offers
      summary: Make an offer to the other participant in the conversation
      tags:
      - conversations
      x-openapi-router-controller: openapi_server.controllers.conversations_controller
  /countries:
    get:
      description: Retrieve a list of country codes with corresponding subregions
      operationId: countries_get
      summary: Retrieve a list of country codes with corresponding subregions
      tags:
      - countries
      x-openapi-router-controller: openapi_server.controllers.countries_controller
  /csps:
    get:
      description: Returns a set of comparison shopping pages based on the current
        params
      operationId: csps_get
      summary: Returns a set of comparison shopping pages based on the current params
      tags:
      - csps
      x-openapi-router-controller: openapi_server.controllers.csps_controller
  /csps/categories:
    get:
      operationId: csps_categories_get
      tags:
      - csps
      x-openapi-router-controller: openapi_server.controllers.csps_controller
  /csps/find:
    get:
      description: Show comparison shopping page
      operationId: csps_find_get
      summary: Show comparison shopping page
      tags:
      - csps
      x-openapi-router-controller: openapi_server.controllers.csps_controller
  /csps/{id}:
    get:
      operationId: csps_id_get
      tags:
      - csps
      x-openapi-router-controller: openapi_server.controllers.csps_controller
  /curated_sets/{slug}:
    get:
      operationId: curated_sets_slug_get
      tags:
      - curated_sets
      x-openapi-router-controller: openapi_server.controllers.curated_sets_controller
  /currencies/display:
    get:
      description: List of supported display currencies for browsing listings
      operationId: currencies_display_get
      summary: List of supported display currencies for browsing listings
      tags:
      - currencies
      x-openapi-router-controller: openapi_server.controllers.currencies_controller
  /currencies/listing:
    get:
      description: List of supported listing currencies for shops
      operationId: currencies_listing_get
      summary: List of supported listing currencies for shops
      tags:
      - currencies
      x-openapi-router-controller: openapi_server.controllers.currencies_controller
  /feedback/{feedback_id}:
    get:
      description: Feedback details
      operationId: feedback_feedback_id_get
      summary: Feedback details
      tags:
      - feedback
      x-openapi-router-controller: openapi_server.controllers.feedback_controller
  /handpicked/{slug}:
    get:
      description: Get results from a handpicked collection
      operationId: handpicked_slug_get
      summary: Get results from a handpicked collection
      tags:
      - handpicked
      x-openapi-router-controller: openapi_server.controllers.handpicked_controller
  /listing_conditions:
    get:
      description: List of supported product conditions
      operationId: listing_conditions_get
      summary: List of supported product conditions
      tags:
      - listing_conditions
      x-openapi-router-controller: openapi_server.controllers.listing_conditions_controller
  /listings:
    get:
      description: Default search of listings includes only used & handmade. Add a
        filter to view all listings or use the /listings/all endpoint.
      operationId: listings_get
      summary: Default search of listings includes only used & handmade. Add a filter
        to view all listings or use the /listings/all endpoint.
      tags:
      - listings
      x-openapi-router-controller: openapi_server.controllers.listings_controller
    post:
      description: Create a listing
      operationId: listings_post
      security:
      - oauth2:
        - write_listings
        - write_listings_for_others
      summary: Create a listing
      tags:
      - listings
      x-openapi-router-controller: openapi_server.controllers.listings_controller
  /listings/all:
    get:
      description: "All listings including used, handmade, and brand new"
      operationId: listings_all_get
      summary: "All listings including used, handmade, and brand new"
      tags:
      - listings
      x-openapi-router-controller: openapi_server.controllers.listings_controller
  /listings/facets/seller_location:
    get:
      description: Individual facets
      operationId: listings_facets_seller_location_get
      summary: Individual facets
      tags:
      - listings
      x-openapi-router-controller: openapi_server.controllers.listings_controller
  /listings/{id}/negotiation:
    get:
      description: Returns the latest negotiation for the requesting user given a
        listing id
      operationId: listings_id_negotiation_get
      security:
      - oauth2:
        - read_offers
      summary: Returns the latest negotiation for the requesting user given a listing
        id
      tags:
      - listings
      x-openapi-router-controller: openapi_server.controllers.listings_controller
  /listings/{id}/offer:
    post:
      description: Make an offer to the seller of a listing
      operationId: listings_id_offer_post
      security:
      - oauth2:
        - write_offers
      summary: Make an offer to the seller of a listing
      tags:
      - listings
      x-openapi-router-controller: openapi_server.controllers.listings_controller
  /listings/{listing_id}/bump:
    get:
      description: View available bump tiers and stats for a listing
      operationId: listings_listing_id_bump_get
      security:
      - oauth2:
        - read_listings
      summary: View available bump tiers and stats for a listing
      tags:
      - listings
      x-openapi-router-controller: openapi_server.controllers.listings_controller
  /listings/{listing_id}/bump/{budget_type}:
    post:
      description: Bump a listing
      operationId: listings_listing_id_bump_budget_type_post
      security:
      - oauth2:
        - write_listings
      summary: Bump a listing
      tags:
      - listings
      x-openapi-router-controller: openapi_server.controllers.listings_controller
  /listings/{listing_id}/conversations:
    post:
      description: Start a conversation with a seller
      operationId: listings_listing_id_conversations_post
      security:
      - oauth2:
        - write_messages
      summary: Start a conversation with a seller
      tags:
      - listings
      x-openapi-router-controller: openapi_server.controllers.listings_controller
  /listings/{listing_id}/images:
    get:
      description: View the images associated with a particular listing
      operationId: listings_listing_id_images_get
      security:
      - oauth2:
        - read_listings
      summary: View the images associated with a particular listing
      tags:
      - listings
      x-openapi-router-controller: openapi_server.controllers.listings_controller
  /listings/{listing_id}/images/{image_id}:
    delete:
      description: Delete an image from a listing
      operationId: listings_listing_id_images_image_id_delete
      security:
      - oauth2:
        - write_listings
      summary: Delete an image from a listing
      tags:
      - listings
      x-openapi-router-controller: openapi_server.controllers.listings_controller
  /listings/{listing_id}/sales:
    get:
      description: See all sales that include a listing.
      operationId: listings_listing_id_sales_get
      summary: See all sales that include a listing.
      tags:
      - listings
      x-openapi-router-controller: openapi_server.controllers.listings_controller
  /listings/{slug}:
    delete:
      description: Delete a draft listing. Cannot be used on non-drafts.
      operationId: listings_slug_delete
      security:
      - oauth2:
        - write_listings
      summary: Delete a draft listing. Cannot be used on non-drafts.
      tags:
      - listings
      x-openapi-router-controller: openapi_server.controllers.listings_controller
    get:
      description: Listing details
      operationId: listings_slug_get
      summary: Listing details
      tags:
      - listings
      x-openapi-router-controller: openapi_server.controllers.listings_controller
    put:
      description: Update a listing
      operationId: listings_slug_put
      security:
      - oauth2:
        - write_listings
      summary: Update a listing
      tags:
      - listings
      x-openapi-router-controller: openapi_server.controllers.listings_controller
  /listings/{slug}/edit:
    get:
      description: Edit listing.
      operationId: listings_slug_edit_get
      security:
      - oauth2:
        - write_listings
      summary: Edit listing.
      tags:
      - listings
      x-openapi-router-controller: openapi_server.controllers.listings_controller
  /listings/{slug}/flag:
    post:
      description: Flag a listing for inappropriate content or fraud
      operationId: listings_slug_flag_post
      summary: Flag a listing for inappropriate content or fraud
      tags:
      - listings
      x-openapi-router-controller: openapi_server.controllers.listings_controller
  /listings/{slug}/reviews:
    get:
      description: View reviews of a listing
      operationId: listings_slug_reviews_get
      summary: View reviews of a listing
      tags:
      - listings
      x-openapi-router-controller: openapi_server.controllers.listings_controller
    post:
      description: Create a review for a listing
      operationId: listings_slug_reviews_post
      security:
      - oauth2:
        - write_reviews
      summary: Create a review for a listing
      tags:
      - listings
      x-openapi-router-controller: openapi_server.controllers.listings_controller
  /listings/{slug}/similar_listings:
    get:
      description: Listing details
      operationId: listings_slug_similar_listings_get
      summary: Listing details
      tags:
      - listings
      x-openapi-router-controller: openapi_server.controllers.listings_controller
  /my/account:
    get:
      description: Get account details
      operationId: my_account_get
      security:
      - oauth2:
        - read_profile
      summary: Get account details
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
    put:
      description: Update account details
      operationId: my_account_put
      security:
      - oauth2:
        - write_profile
      summary: Update account details
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/addresses:
    get:
      description: See all addresses in your address book
      operationId: my_addresses_get
      security:
      - oauth2:
        - read_profile
      summary: See all addresses in your address book
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
    post:
      description: Create a new address in your address book
      operationId: my_addresses_post
      security:
      - oauth2:
        - write_profile
      summary: Create a new address in your address book
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/addresses/{address_id}:
    delete:
      description: Delete an existing address in your address book
      operationId: my_addresses_address_id_delete
      security:
      - oauth2:
        - write_profile
      summary: Delete an existing address in your address book
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
    put:
      description: Update an existing address in your address book
      operationId: my_addresses_address_id_put
      security:
      - oauth2:
        - write_profile
      summary: Update an existing address in your address book
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/conversations:
    get:
      description: Get a list of your conversations
      operationId: my_conversations_get
      security:
      - oauth2:
        - read_messages
      summary: Get a list of your conversations
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
    post:
      description: Start a conversation
      operationId: my_conversations_post
      security:
      - oauth2:
        - write_messages
      summary: Start a conversation
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/conversations/{conversation_id}/messages:
    post:
      description: Send a message
      operationId: my_conversations_conversation_id_messages_post
      security:
      - oauth2:
        - write_messages
      summary: Send a message
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/conversations/{id}:
    get:
      description: Display conversation details with messages in natural time order
        (oldest to newest)
      operationId: my_conversations_id_get
      security:
      - oauth2:
        - read_messages
      summary: Display conversation details with messages in natural time order (oldest
        to newest)
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
    put:
      description: Mark a conversation read/unread
      operationId: my_conversations_id_put
      security:
      - oauth2:
        - write_messages
      summary: Mark a conversation read/unread
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/counts:
    get:
      description: Get your actionable status counts
      operationId: my_counts_get
      security:
      - oauth2:
        - read_profile
      summary: Get your actionable status counts
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/curated_set/product/{product_id}:
    delete:
      operationId: my_curated_set_product_product_id_delete
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
    post:
      operationId: my_curated_set_product_product_id_post
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/feed:
    get:
      description: Get listings from your feed
      operationId: my_feed_get
      security:
      - oauth2:
        - read_lists
      summary: Get listings from your feed
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/feed/customize:
    get:
      description: get your feed customization options
      operationId: my_feed_customize_get
      security:
      - oauth2:
        - read_lists
      summary: get your feed customization options
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/feed/grid:
    get:
      description: get your feed
      operationId: my_feed_grid_get
      security:
      - oauth2:
        - read_lists
      summary: get your feed
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/feedback/received:
    get:
      description: List of received feedback
      operationId: my_feedback_received_get
      security:
      - oauth2:
        - read_feedback
      summary: List of received feedback
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/feedback/sent:
    get:
      description: List of sent feedback
      operationId: my_feedback_sent_get
      security:
      - oauth2:
        - read_feedback
      summary: List of sent feedback
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/follows:
    get:
      description: See what the user is following
      operationId: my_follows_get
      security:
      - oauth2:
        - read_lists
      summary: See what the user is following
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/follows/articles:
    get:
      description: Returns a user's ArticleCategoryFollows
      operationId: my_follows_articles_get
      security:
      - oauth2:
        - read_lists
      summary: Returns a user's ArticleCategoryFollows
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
    post:
      description: Set a user's ArticleCategoryFollows
      operationId: my_follows_articles_post
      security:
      - oauth2:
        - write_lists
      summary: Set a user's ArticleCategoryFollows
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/follows/brands/{slug}:
    delete:
      description: Unfollow a brand
      operationId: my_follows_brands_slug_delete
      security:
      - oauth2:
        - write_lists
      summary: Unfollow a brand
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
    get:
      description: Follow status for a brand
      operationId: my_follows_brands_slug_get
      security:
      - oauth2:
        - read_lists
      summary: Follow status for a brand
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
    post:
      description: Follow a brand
      operationId: my_follows_brands_slug_post
      security:
      - oauth2:
        - write_lists
      summary: Follow a brand
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/follows/categories/{category}/{subcategory}:
    delete:
      description: Unfollow a subcategory
      operationId: my_follows_categories_category_subcategory_delete
      security:
      - oauth2:
        - write_lists
      summary: Unfollow a subcategory
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
    get:
      description: Follow status for a subcategory
      operationId: my_follows_categories_category_subcategory_get
      security:
      - oauth2:
        - read_lists
      summary: Follow status for a subcategory
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
    post:
      description: Follow a subcategory
      operationId: my_follows_categories_category_subcategory_post
      security:
      - oauth2:
        - write_lists
      summary: Follow a subcategory
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/follows/categories/{identifier}:
    delete:
      description: Unfollow a category
      operationId: my_follows_categories_identifier_delete
      security:
      - oauth2:
        - write_lists
      summary: Unfollow a category
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
    get:
      description: Follow status for a category
      operationId: my_follows_categories_identifier_get
      security:
      - oauth2:
        - read_lists
      summary: Follow status for a category
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
    post:
      description: Follow a category
      operationId: my_follows_categories_identifier_post
      security:
      - oauth2:
        - write_lists
      summary: Follow a category
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/follows/categories/{uuid}:
    post:
      description: Follow a category
      operationId: my_follows_categories_uuid_post
      security:
      - oauth2:
        - write_lists
      summary: Follow a category
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/follows/collections/{slug}:
    delete:
      description: Unfollow a collection
      operationId: my_follows_collections_slug_delete
      security:
      - oauth2:
        - write_lists
      summary: Unfollow a collection
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
    get:
      description: Follow status for a collection
      operationId: my_follows_collections_slug_get
      security:
      - oauth2:
        - read_lists
      summary: Follow status for a collection
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
    post:
      description: Follow a collection
      operationId: my_follows_collections_slug_post
      security:
      - oauth2:
        - write_lists
      summary: Follow a collection
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/follows/handpicked/{slug}:
    delete:
      description: Unfollow a handpicked collection
      operationId: my_follows_handpicked_slug_delete
      security:
      - oauth2:
        - write_lists
      summary: Unfollow a handpicked collection
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
    get:
      description: Follow status for a handpicked collection
      operationId: my_follows_handpicked_slug_get
      security:
      - oauth2:
        - read_lists
      summary: Follow status for a handpicked collection
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
    post:
      description: Follow a handpicked collection
      operationId: my_follows_handpicked_slug_post
      security:
      - oauth2:
        - write_lists
      summary: Follow a handpicked collection
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/follows/search:
    get:
      description: Follow status for a search
      operationId: my_follows_search_get
      security:
      - oauth2:
        - read_lists
      summary: Follow status for a search
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
    post:
      description: Follow a search
      operationId: my_follows_search_post
      security:
      - oauth2:
        - write_lists
      summary: Follow a search
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/follows/shops/{slug}:
    delete:
      description: Unfollow a shop
      operationId: my_follows_shops_slug_delete
      security:
      - oauth2:
        - write_lists
      summary: Unfollow a shop
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
    get:
      description: Follow status for a shop
      operationId: my_follows_shops_slug_get
      security:
      - oauth2:
        - read_lists
      summary: Follow status for a shop
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
    post:
      description: Follow a shop
      operationId: my_follows_shops_slug_post
      security:
      - oauth2:
        - write_lists
      summary: Follow a shop
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/follows/{follow_id}:
    delete:
      description: Delete a follow
      operationId: my_follows_follow_id_delete
      security:
      - oauth2:
        - write_lists
      summary: Delete a follow
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/follows/{follow_id}/alert:
    delete:
      operationId: my_follows_follow_id_alert_delete
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
    post:
      operationId: my_follows_follow_id_alert_post
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/listings:
    get:
      description: Retrieve a list of live listings for the seller. To search all
        listings specify state=all
      operationId: my_listings_get
      security:
      - oauth2:
        - read_listings
      summary: Retrieve a list of live listings for the seller. To search all listings
        specify state=all
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/listings/drafts:
    get:
      description: Retrieve a list your draft listings
      operationId: my_listings_drafts_get
      security:
      - oauth2:
        - read_listings
      summary: Retrieve a list your draft listings
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/listings/negotiations:
    get:
      description: Get a list of active negotiations as a seller
      operationId: my_listings_negotiations_get
      security:
      - oauth2:
        - read_offers
      summary: Get a list of active negotiations as a seller
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/listings/{slug}/state/end:
    put:
      description: End a listing
      operationId: my_listings_slug_state_end_put
      security:
      - oauth2:
        - write_listings
      summary: End a listing
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/lists:
    get:
      description: "Get a list of your lists (wishlist, watch list, etc)"
      operationId: my_lists_get
      security:
      - oauth2:
        - read_lists
      summary: "Get a list of your lists (wishlist, watch list, etc)"
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/negotiations/buying:
    get:
      description: Get a list of active negotiations as a buyer
      operationId: my_negotiations_buying_get
      security:
      - oauth2:
        - read_offers
      summary: Get a list of active negotiations as a buyer
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/negotiations/{id}:
    get:
      description: Get offer details
      operationId: my_negotiations_id_get
      security:
      - oauth2:
        - read_offers
      summary: Get offer details
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/negotiations/{id}/accept:
    post:
      description: Accept an offer
      operationId: my_negotiations_id_accept_post
      security:
      - oauth2:
        - write_offers
      summary: Accept an offer
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/negotiations/{id}/counter:
    post:
      description: Counter an offer
      operationId: my_negotiations_id_counter_post
      security:
      - oauth2:
        - write_offers
      summary: Counter an offer
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/negotiations/{id}/decline:
    post:
      description: Decline an offer
      operationId: my_negotiations_id_decline_post
      security:
      - oauth2:
        - write_offers
      summary: Decline an offer
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/orders/awaiting_feedback:
    get:
      description: List of orders that need feedback
      operationId: my_orders_awaiting_feedback_get
      security:
      - oauth2:
        - read_feedback
      summary: List of orders that need feedback
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/orders/buying/all:
    get:
      description: "Returns all orders, newest first."
      operationId: my_orders_buying_all_get
      security:
      - oauth2:
        - read_orders
      summary: "Returns all orders, newest first."
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/orders/buying/by_uuid/{uuid}:
    get:
      operationId: my_orders_buying_by_uuid_uuid_get
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/orders/buying/unpaid:
    get:
      description: "Returns unpaid orders, newest first."
      operationId: my_orders_buying_unpaid_get
      security:
      - oauth2:
        - read_orders
      summary: "Returns unpaid orders, newest first."
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/orders/buying/{id}:
    get:
      description: Returns order details for a buyer
      operationId: my_orders_buying_id_get
      security:
      - oauth2:
        - read_orders
      summary: Returns order details for a buyer
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/orders/buying/{id}/mark_received:
    post:
      description: Marks an order as received by the buyer
      operationId: my_orders_buying_id_mark_received_post
      security:
      - oauth2:
        - write_orders
      summary: Marks an order as received by the buyer
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/orders/selling/all:
    get:
      description: "Get all seller orders, newest first."
      operationId: my_orders_selling_all_get
      security:
      - oauth2:
        - read_orders
      summary: "Get all seller orders, newest first."
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/orders/selling/awaiting_shipment:
    get:
      description: "Get unpaid seller orders, newest first."
      operationId: my_orders_selling_awaiting_shipment_get
      security:
      - oauth2:
        - read_orders
      summary: "Get unpaid seller orders, newest first."
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/orders/selling/buyer_history/{buyer_id}:
    get:
      description: See previous orders from buyer
      operationId: my_orders_selling_buyer_history_buyer_id_get
      security:
      - oauth2:
        - read_orders
      summary: See previous orders from buyer
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/orders/selling/by_uuid/{uuid}:
    get:
      operationId: my_orders_selling_by_uuid_uuid_get
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/orders/selling/unpaid:
    get:
      description: "Get unpaid seller orders, newest first."
      operationId: my_orders_selling_unpaid_get
      security:
      - oauth2:
        - read_orders
      summary: "Get unpaid seller orders, newest first."
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/orders/selling/{id}:
    get:
      description: Returns order details for a seller
      operationId: my_orders_selling_id_get
      security:
      - oauth2:
        - read_orders
      summary: Returns order details for a seller
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/orders/selling/{id}/mark_picked_up:
    post:
      description: Marks an order as picked up
      operationId: my_orders_selling_id_mark_picked_up_post
      security:
      - oauth2:
        - write_orders
      summary: Marks an order as picked up
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/orders/selling/{id}/ship:
    post:
      description: Marks an order as shipped
      operationId: my_orders_selling_id_ship_post
      security:
      - oauth2:
        - write_orders
      summary: Marks an order as shipped
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/orders/selling/{order_id}/refund_requests:
    post:
      description: Initiate a refund for a sold order
      operationId: my_orders_selling_order_id_refund_requests_post
      security:
      - oauth2:
        - write_orders
      summary: Initiate a refund for a sold order
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/payments/selling:
    get:
      description: Get payments
      operationId: my_payments_selling_get
      security:
      - oauth2:
        - read_orders
      summary: Get payments
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/payments/selling/{id}:
    get:
      description: Get payment
      operationId: my_payments_selling_id_get
      security:
      - oauth2:
        - read_orders
      summary: Get payment
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/payouts:
    get:
      description: Get a list of payouts
      operationId: my_payouts_get
      security:
      - oauth2:
        - read_payouts
      summary: Get a list of payouts
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/payouts/{id}/line_items:
    get:
      description: Read the line items of a payout
      operationId: my_payouts_id_line_items_get
      security:
      - oauth2:
        - read_payouts
      summary: Read the line items of a payout
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/refund_requests/selling:
    get:
      description: Get a list of refund requests as a seller
      operationId: my_refund_requests_selling_get
      security:
      - oauth2:
        - read_orders
      summary: Get a list of refund requests as a seller
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/refund_requests/selling/{id}:
    put:
      description: Update a refund request for a sold order
      operationId: my_refund_requests_selling_id_put
      security:
      - oauth2:
        - write_orders
      summary: Update a refund request for a sold order
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/viewed_listings:
    get:
      description: Get a list of your recently viewed listings.
      operationId: my_viewed_listings_get
      security:
      - oauth2:
        - read_lists
      summary: Get a list of your recently viewed listings.
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/wishlist:
    get:
      description: Get a list of wishlisted items
      operationId: my_wishlist_get
      security:
      - oauth2:
        - read_lists
      summary: Get a list of wishlisted items
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /my/wishlist/{id}:
    delete:
      description: Remove a listing from your wishlist
      operationId: my_wishlist_id_delete
      security:
      - oauth2:
        - write_lists
      summary: Remove a listing from your wishlist
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
    put:
      description: Add a listing to your wishlist
      operationId: my_wishlist_id_put
      security:
      - oauth2:
        - write_lists
      summary: Add a listing to your wishlist
      tags:
      - my
      x-openapi-router-controller: openapi_server.controllers.my_controller
  /orders/{order_id}/feedback/buyer:
    get:
      description: Feedback details for an order's buyer
      operationId: orders_order_id_feedback_buyer_get
      summary: Feedback details for an order's buyer
      tags:
      - orders
      x-openapi-router-controller: openapi_server.controllers.orders_controller
    post:
      description: Add feedback about an order's buyer
      operationId: orders_order_id_feedback_buyer_post
      security:
      - oauth2:
        - write_feedback
      summary: Add feedback about an order's buyer
      tags:
      - orders
      x-openapi-router-controller: openapi_server.controllers.orders_controller
  /orders/{order_id}/feedback/seller:
    get:
      description: Feedback details for an order's seller
      operationId: orders_order_id_feedback_seller_get
      summary: Feedback details for an order's seller
      tags:
      - orders
      x-openapi-router-controller: openapi_server.controllers.orders_controller
    post:
      description: Add feedback about an order's seller
      operationId: orders_order_id_feedback_seller_post
      security:
      - oauth2:
        - write_feedback
      summary: Add feedback about an order's seller
      tags:
      - orders
      x-openapi-router-controller: openapi_server.controllers.orders_controller
  /payment_methods:
    get:
      description: Get list of payment methods
      operationId: payment_methods_get
      summary: Get list of payment methods
      tags:
      - payment_methods
      x-openapi-router-controller: openapi_server.controllers.payment_methods_controller
  /priceguide/{id}/transactions/summary:
    get:
      description: Get a summary of transactions for a given price guide
      operationId: priceguide_id_transactions_summary_get
      summary: Get a summary of transactions for a given price guide
      tags:
      - priceguide
      x-openapi-router-controller: openapi_server.controllers.priceguide_controller
  /products/reviews/{id}:
    get:
      description: View a review
      operationId: products_reviews_id_get
      summary: View a review
      tags:
      - products
      x-openapi-router-controller: openapi_server.controllers.products_controller
    put:
      description: Update a review
      operationId: products_reviews_id_put
      security:
      - oauth2:
        - write_reviews
      summary: Update a review
      tags:
      - products
      x-openapi-router-controller: openapi_server.controllers.products_controller
  /products/{slug}/reviews:
    get:
      description: View reviews of a comparison shopping page
      operationId: products_slug_reviews_get
      summary: View reviews of a comparison shopping page
      tags:
      - products
      x-openapi-router-controller: openapi_server.controllers.products_controller
    post:
      description: Create a review for a product
      operationId: products_slug_reviews_post
      security:
      - oauth2:
        - write_reviews
      summary: Create a review for a product
      tags:
      - products
      x-openapi-router-controller: openapi_server.controllers.products_controller
  /sales/reverb:
    get:
      description: View upcoming and live Reverb official sales.
      operationId: sales_reverb_get
      security:
      - oauth2:
        - read_listings
      summary: View upcoming and live Reverb official sales.
      tags:
      - sales
      x-openapi-router-controller: openapi_server.controllers.sales_controller
  /sales/seller:
    get:
      description: View your created sales.
      operationId: sales_seller_get
      security:
      - oauth2:
        - read_listings
      summary: View your created sales.
      tags:
      - sales
      x-openapi-router-controller: openapi_server.controllers.sales_controller
  /sales/{sale_id}/listings:
    delete:
      description: Remove a listing from a sale
      operationId: sales_sale_id_listings_delete
      security:
      - oauth2:
        - write_listings
      summary: Remove a listing from a sale
      tags:
      - sales
      x-openapi-router-controller: openapi_server.controllers.sales_controller
    post:
      description: Add listings to a sale
      operationId: sales_sale_id_listings_post
      security:
      - oauth2:
        - write_listings
      summary: Add listings to a sale
      tags:
      - sales
      x-openapi-router-controller: openapi_server.controllers.sales_controller
  /sales/{slug}:
    get:
      operationId: sales_slug_get
      tags:
      - sales
      x-openapi-router-controller: openapi_server.controllers.sales_controller
  /shipping/providers:
    get:
      description: List of supported shipping providers
      operationId: shipping_providers_get
      summary: List of supported shipping providers
      tags:
      - shipping
      x-openapi-router-controller: openapi_server.controllers.shipping_controller
  /shipping/regions:
    get:
      operationId: shipping_regions_get
      tags:
      - shipping
      x-openapi-router-controller: openapi_server.controllers.shipping_controller
  /shop:
    get:
      description: Get your own shop details
      operationId: shop_get
      security:
      - oauth2:
        - read_profile
      summary: Get your own shop details
      tags:
      - shop
      x-openapi-router-controller: openapi_server.controllers.shop_controller
    put:
      description: Update your shop profile
      operationId: shop_put
      security:
      - oauth2:
        - write_profile
      summary: Update your shop profile
      tags:
      - shop
      x-openapi-router-controller: openapi_server.controllers.shop_controller
  /shop/listing_conditions:
    get:
      description: List of supported product conditions
      operationId: shop_listing_conditions_get
      security:
      - oauth2:
        - read_profile
      summary: List of supported product conditions
      tags:
      - shop
      x-openapi-router-controller: openapi_server.controllers.shop_controller
  /shop/payment_methods:
    get:
      description: Get accepted payment methods
      operationId: shop_payment_methods_get
      security:
      - oauth2:
        - read_profile
      summary: Get accepted payment methods
      tags:
      - shop
      x-openapi-router-controller: openapi_server.controllers.shop_controller
  /shop/vacation:
    delete:
      description: Disable vacation mode. All listings will be re-enabled.
      operationId: shop_vacation_delete
      security:
      - oauth2:
        - write_profile
      summary: Disable vacation mode. All listings will be re-enabled.
      tags:
      - shop
      x-openapi-router-controller: openapi_server.controllers.shop_controller
    get:
      description: Returns shop vacation status
      operationId: shop_vacation_get
      security:
      - oauth2:
        - read_profile
      summary: Returns shop vacation status
      tags:
      - shop
      x-openapi-router-controller: openapi_server.controllers.shop_controller
    post:
      description: Enable vacation mode. All listings will be unavailable until vacation
        mode is turned off.
      operationId: shop_vacation_post
      security:
      - oauth2:
        - write_profile
      summary: Enable vacation mode. All listings will be unavailable until vacation
        mode is turned off.
      tags:
      - shop
      x-openapi-router-controller: openapi_server.controllers.shop_controller
  /shops/{id}/storefronts:
    get:
      description: Get storefront details on a shop.
      operationId: shops_id_storefronts_get
      summary: Get storefront details on a shop.
      tags:
      - shops
      x-openapi-router-controller: openapi_server.controllers.shops_controller
  /shops/{shop_id}/shipping_profiles:
    get:
      description: List of shipping profiles for your shop
      operationId: shops_shop_id_shipping_profiles_get
      security:
      - oauth2:
        - read_profile
      summary: List of shipping profiles for your shop
      tags:
      - shops
      x-openapi-router-controller: openapi_server.controllers.shops_controller
  /shops/{slug}:
    get:
      description: Get details on a shop.
      operationId: shops_slug_get
      summary: Get details on a shop.
      tags:
      - shops
      x-openapi-router-controller: openapi_server.controllers.shops_controller
  /shops/{slug}/feedback:
    get:
      description: Get seller's feedback
      operationId: shops_slug_feedback_get
      summary: Get seller's feedback
      tags:
      - shops
      x-openapi-router-controller: openapi_server.controllers.shops_controller
  /shops/{slug}/feedback/buyer:
    get:
      description: Get seller's feedback as a buyer
      operationId: shops_slug_feedback_buyer_get
      summary: Get seller's feedback as a buyer
      tags:
      - shops
      x-openapi-router-controller: openapi_server.controllers.shops_controller
  /shops/{slug}/feedback/seller:
    get:
      description: Get seller's feedback as a seller
      operationId: shops_slug_feedback_seller_get
      summary: Get seller's feedback as a seller
      tags:
      - shops
      x-openapi-router-controller: openapi_server.controllers.shops_controller
  /wants:
    get:
      description: A list of wanted items by the user
      operationId: wants_get
      security:
      - oauth2:
        - read_lists
      summary: A list of wanted items by the user
      tags:
      - wants
      x-openapi-router-controller: openapi_server.controllers.wants_controller
  /wants/{id}:
    delete:
      description: Unmark an item wanted.
      operationId: wants_id_delete
      security:
      - oauth2:
        - write_lists
      summary: Unmark an item wanted.
      tags:
      - wants
      x-openapi-router-controller: openapi_server.controllers.wants_controller
    put:
      description: Mark an item wanted. Returns 200 on success or 422 on failure.
      operationId: wants_id_put
      security:
      - oauth2:
        - write_lists
      summary: Mark an item wanted. Returns 200 on success or 422 on failure.
      tags:
      - wants
      x-openapi-router-controller: openapi_server.controllers.wants_controller
  /webhooks/registrations:
    get:
      description: Get webhook registrations
      operationId: webhooks_registrations_get
      summary: Get webhook registrations
      tags:
      - webhooks
      x-openapi-router-controller: openapi_server.controllers.webhooks_controller
    post:
      description: Register a webhook
      operationId: webhooks_registrations_post
      summary: Register a webhook
      tags:
      - webhooks
      x-openapi-router-controller: openapi_server.controllers.webhooks_controller
  /webhooks/registrations/{id}:
    delete:
      description: Remove a webhook
      operationId: webhooks_registrations_id_delete
      summary: Remove a webhook
      tags:
      - webhooks
      x-openapi-router-controller: openapi_server.controllers.webhooks_controller
    get:
      description: Get details of a webhook registration
      operationId: webhooks_registrations_id_get
      summary: Get details of a webhook registration
      tags:
      - webhooks
      x-openapi-router-controller: openapi_server.controllers.webhooks_controller
components:
  securitySchemes:
    oauth2:
      flows:
        clientCredentials:
          scopes:
            public: ""
            read_feedback: '*Originally missing*'
            read_listings: '*Originally missing*'
            read_lists: '*Originally missing*'
            read_messages: '*Originally missing*'
            read_offers: '*Originally missing*'
            read_orders: '*Originally missing*'
            read_payouts: '*Originally missing*'
            read_profile: '*Originally missing*'
            write_feedback: '*Originally missing*'
            write_listings: '*Originally missing*'
            write_listings_for_others: '*Originally missing*'
            write_lists: '*Originally missing*'
            write_messages: '*Originally missing*'
            write_offers: '*Originally missing*'
            write_orders: '*Originally missing*'
            write_profile: '*Originally missing*'
            write_reviews: '*Originally missing*'
          tokenUrl: https://reverb.com/oauth/token
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_oauth2
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_oauth2
x-hasEquivalentPaths: true
