QT += network

HEADERS += \
# Models
    $${PWD}/OAIAccessProfile.h \
    $${PWD}/OAIAgentPool.h \
    $${PWD}/OAIAgentPoolAvailableVersions.h \
    $${PWD}/OAIAgentPoolAvailableVersionsProperties.h \
    $${PWD}/OAIAgentPoolAvailableVersionsProperties_agentPoolVersions_inner.h \
    $${PWD}/OAIAgentPoolListResult.h \
    $${PWD}/OAIAgentPoolType.h \
    $${PWD}/OAIAgentPoolUpgradeProfile.h \
    $${PWD}/OAIAgentPoolUpgradeProfileProperties.h \
    $${PWD}/OAIAgentPoolUpgradeProfileProperties_upgrades_inner.h \
    $${PWD}/OAICloudError.h \
    $${PWD}/OAICloudErrorBody.h \
    $${PWD}/OAIContainerServiceDiagnosticsProfile.h \
    $${PWD}/OAIContainerServiceLinuxProfile.h \
    $${PWD}/OAIContainerServiceMasterProfile.h \
    $${PWD}/OAIContainerServiceNetworkProfile.h \
    $${PWD}/OAIContainerServiceSshConfiguration.h \
    $${PWD}/OAIContainerServiceSshPublicKey.h \
    $${PWD}/OAIContainerServiceStorageProfile.h \
    $${PWD}/OAIContainerServiceVMDiagnostics.h \
    $${PWD}/OAIContainerServiceVMSize.h \
    $${PWD}/OAICredentialResult.h \
    $${PWD}/OAICredentialResults.h \
    $${PWD}/OAIManagedCluster.h \
    $${PWD}/OAIManagedClusterAADProfile.h \
    $${PWD}/OAIManagedClusterAPIServerAccessProfile.h \
    $${PWD}/OAIManagedClusterAccessProfile.h \
    $${PWD}/OAIManagedClusterAddonProfile.h \
    $${PWD}/OAIManagedClusterAgentPoolProfile.h \
    $${PWD}/OAIManagedClusterAgentPoolProfileProperties.h \
    $${PWD}/OAIManagedClusterIdentity.h \
    $${PWD}/OAIManagedClusterListResult.h \
    $${PWD}/OAIManagedClusterLoadBalancerProfile.h \
    $${PWD}/OAIManagedClusterLoadBalancerProfile_managedOutboundIPs.h \
    $${PWD}/OAIManagedClusterLoadBalancerProfile_outboundIPPrefixes.h \
    $${PWD}/OAIManagedClusterLoadBalancerProfile_outboundIPs.h \
    $${PWD}/OAIManagedClusterPoolUpgradeProfile.h \
    $${PWD}/OAIManagedClusterProperties.h \
    $${PWD}/OAIManagedClusterServicePrincipalProfile.h \
    $${PWD}/OAIManagedClusterUpgradeProfile.h \
    $${PWD}/OAIManagedClusterUpgradeProfileProperties.h \
    $${PWD}/OAIManagedClusterWindowsProfile.h \
    $${PWD}/OAIOSType.h \
    $${PWD}/OAIOperationListResult.h \
    $${PWD}/OAIOperationValue.h \
    $${PWD}/OAIOperationValueDisplay.h \
    $${PWD}/OAIResource.h \
    $${PWD}/OAIResourceReference.h \
    $${PWD}/OAIScaleSetEvictionPolicy.h \
    $${PWD}/OAIScaleSetPriority.h \
    $${PWD}/OAISubResource.h \
    $${PWD}/OAITagsObject.h \
# APIs
    $${PWD}/OAIAgentPoolsApi.h \
    $${PWD}/OAIManagedClustersApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAccessProfile.cpp \
    $${PWD}/OAIAgentPool.cpp \
    $${PWD}/OAIAgentPoolAvailableVersions.cpp \
    $${PWD}/OAIAgentPoolAvailableVersionsProperties.cpp \
    $${PWD}/OAIAgentPoolAvailableVersionsProperties_agentPoolVersions_inner.cpp \
    $${PWD}/OAIAgentPoolListResult.cpp \
    $${PWD}/OAIAgentPoolType.cpp \
    $${PWD}/OAIAgentPoolUpgradeProfile.cpp \
    $${PWD}/OAIAgentPoolUpgradeProfileProperties.cpp \
    $${PWD}/OAIAgentPoolUpgradeProfileProperties_upgrades_inner.cpp \
    $${PWD}/OAICloudError.cpp \
    $${PWD}/OAICloudErrorBody.cpp \
    $${PWD}/OAIContainerServiceDiagnosticsProfile.cpp \
    $${PWD}/OAIContainerServiceLinuxProfile.cpp \
    $${PWD}/OAIContainerServiceMasterProfile.cpp \
    $${PWD}/OAIContainerServiceNetworkProfile.cpp \
    $${PWD}/OAIContainerServiceSshConfiguration.cpp \
    $${PWD}/OAIContainerServiceSshPublicKey.cpp \
    $${PWD}/OAIContainerServiceStorageProfile.cpp \
    $${PWD}/OAIContainerServiceVMDiagnostics.cpp \
    $${PWD}/OAIContainerServiceVMSize.cpp \
    $${PWD}/OAICredentialResult.cpp \
    $${PWD}/OAICredentialResults.cpp \
    $${PWD}/OAIManagedCluster.cpp \
    $${PWD}/OAIManagedClusterAADProfile.cpp \
    $${PWD}/OAIManagedClusterAPIServerAccessProfile.cpp \
    $${PWD}/OAIManagedClusterAccessProfile.cpp \
    $${PWD}/OAIManagedClusterAddonProfile.cpp \
    $${PWD}/OAIManagedClusterAgentPoolProfile.cpp \
    $${PWD}/OAIManagedClusterAgentPoolProfileProperties.cpp \
    $${PWD}/OAIManagedClusterIdentity.cpp \
    $${PWD}/OAIManagedClusterListResult.cpp \
    $${PWD}/OAIManagedClusterLoadBalancerProfile.cpp \
    $${PWD}/OAIManagedClusterLoadBalancerProfile_managedOutboundIPs.cpp \
    $${PWD}/OAIManagedClusterLoadBalancerProfile_outboundIPPrefixes.cpp \
    $${PWD}/OAIManagedClusterLoadBalancerProfile_outboundIPs.cpp \
    $${PWD}/OAIManagedClusterPoolUpgradeProfile.cpp \
    $${PWD}/OAIManagedClusterProperties.cpp \
    $${PWD}/OAIManagedClusterServicePrincipalProfile.cpp \
    $${PWD}/OAIManagedClusterUpgradeProfile.cpp \
    $${PWD}/OAIManagedClusterUpgradeProfileProperties.cpp \
    $${PWD}/OAIManagedClusterWindowsProfile.cpp \
    $${PWD}/OAIOSType.cpp \
    $${PWD}/OAIOperationListResult.cpp \
    $${PWD}/OAIOperationValue.cpp \
    $${PWD}/OAIOperationValueDisplay.cpp \
    $${PWD}/OAIResource.cpp \
    $${PWD}/OAIResourceReference.cpp \
    $${PWD}/OAIScaleSetEvictionPolicy.cpp \
    $${PWD}/OAIScaleSetPriority.cpp \
    $${PWD}/OAISubResource.cpp \
    $${PWD}/OAITagsObject.cpp \
# APIs
    $${PWD}/OAIAgentPoolsApi.cpp \
    $${PWD}/OAIManagedClustersApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
