QT += network

HEADERS += \
# Models
    $${PWD}/OAIBroadcastTxRequest.h \
    $${PWD}/OAIBroadcastTxResponse.h \
    $${PWD}/OAIBurnTokenRequest.h \
    $${PWD}/OAIBurnTokenRequest_burn_inner.h \
    $${PWD}/OAIBurnTokenRequest_transfer_inner.h \
    $${PWD}/OAIBurnTokenResponse.h \
    $${PWD}/OAIError.h \
    $${PWD}/OAIGetAddressInfoResponse.h \
    $${PWD}/OAIGetAddressInfoResponse_utxos_inner.h \
    $${PWD}/OAIGetAddressInfoResponse_utxos_inner_tokens_inner.h \
    $${PWD}/OAIGetAddressResponse.h \
    $${PWD}/OAIGetAddressUtxosResponse_inner.h \
    $${PWD}/OAIGetBlockIndexResponse.h \
    $${PWD}/OAIGetBlockResponse.h \
    $${PWD}/OAIGetFaucetResponse.h \
    $${PWD}/OAIGetFaucetResponse_data.h \
    $${PWD}/OAIGetRawTxResponse.h \
    $${PWD}/OAIGetSyncResponse.h \
    $${PWD}/OAIGetTokenHoldersResponse.h \
    $${PWD}/OAIGetTokenHoldersResponse_holders_inner.h \
    $${PWD}/OAIGetTokenIdResponse.h \
    $${PWD}/OAIGetTokenMetadataResponse.h \
    $${PWD}/OAIGetTokenMetadataResponse_metadataOfIssuance.h \
    $${PWD}/OAIGetTokenMetadataResponse_metadataOfIssuance_data.h \
    $${PWD}/OAIGetTokenMetadataResponse_metadataOfIssuance_data_userData.h \
    $${PWD}/OAIGetTokenMetadataResponse_metadataOfIssuance_data_userData_meta_inner.h \
    $${PWD}/OAIGetTokenMetadataResponse_metadataOfUtxo.h \
    $${PWD}/OAIGetTokenMetadataResponse_metadataOfUtxo_userData.h \
    $${PWD}/OAIGetTransactionInfoResponse.h \
    $${PWD}/OAIGetTransactionInfoResponse_vin_inner.h \
    $${PWD}/OAIGetTransactionInfoResponse_vin_inner_previousOutput.h \
    $${PWD}/OAIGetTransactionInfoResponse_vin_inner_scriptSig.h \
    $${PWD}/OAIGetTransactionInfoResponse_vin_inner_tokens_inner.h \
    $${PWD}/OAIGetTransactionInfoResponse_vout_inner.h \
    $${PWD}/OAIGetTxResponse.h \
    $${PWD}/OAIGetTxResponse_vin_inner.h \
    $${PWD}/OAIGetTxResponse_vout_inner.h \
    $${PWD}/OAIGetTxsResponse.h \
    $${PWD}/OAIIssueTokenRequest.h \
    $${PWD}/OAIIssueTokenRequest_flags.h \
    $${PWD}/OAIIssueTokenRequest_metadata.h \
    $${PWD}/OAIIssueTokenRequest_metadata_encryptions_inner.h \
    $${PWD}/OAIIssueTokenRequest_metadata_rules.h \
    $${PWD}/OAIIssueTokenRequest_metadata_rules_expiration.h \
    $${PWD}/OAIIssueTokenRequest_metadata_rules_fees.h \
    $${PWD}/OAIIssueTokenRequest_metadata_rules_fees_items_inner.h \
    $${PWD}/OAIIssueTokenRequest_metadata_rules_holders_inner.h \
    $${PWD}/OAIIssueTokenRequest_metadata_urls_inner.h \
    $${PWD}/OAIIssueTokenRequest_transfer_inner.h \
    $${PWD}/OAIIssueTokenResponse.h \
    $${PWD}/OAIRpcRequest.h \
    $${PWD}/OAIRpcResponse.h \
    $${PWD}/OAISendTokenRequest.h \
    $${PWD}/OAISendTokenResponse.h \
    $${PWD}/OAISendTxRequest.h \
# APIs
    $${PWD}/OAIInsightApi.h \
    $${PWD}/OAIJSONRPCApi.h \
    $${PWD}/OAINTP1Api.h \
    $${PWD}/OAITestnetFaucetApi.h \
    $${PWD}/OAITestnetInsightApi.h \
    $${PWD}/OAITestnetNTP1Api.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIBroadcastTxRequest.cpp \
    $${PWD}/OAIBroadcastTxResponse.cpp \
    $${PWD}/OAIBurnTokenRequest.cpp \
    $${PWD}/OAIBurnTokenRequest_burn_inner.cpp \
    $${PWD}/OAIBurnTokenRequest_transfer_inner.cpp \
    $${PWD}/OAIBurnTokenResponse.cpp \
    $${PWD}/OAIError.cpp \
    $${PWD}/OAIGetAddressInfoResponse.cpp \
    $${PWD}/OAIGetAddressInfoResponse_utxos_inner.cpp \
    $${PWD}/OAIGetAddressInfoResponse_utxos_inner_tokens_inner.cpp \
    $${PWD}/OAIGetAddressResponse.cpp \
    $${PWD}/OAIGetAddressUtxosResponse_inner.cpp \
    $${PWD}/OAIGetBlockIndexResponse.cpp \
    $${PWD}/OAIGetBlockResponse.cpp \
    $${PWD}/OAIGetFaucetResponse.cpp \
    $${PWD}/OAIGetFaucetResponse_data.cpp \
    $${PWD}/OAIGetRawTxResponse.cpp \
    $${PWD}/OAIGetSyncResponse.cpp \
    $${PWD}/OAIGetTokenHoldersResponse.cpp \
    $${PWD}/OAIGetTokenHoldersResponse_holders_inner.cpp \
    $${PWD}/OAIGetTokenIdResponse.cpp \
    $${PWD}/OAIGetTokenMetadataResponse.cpp \
    $${PWD}/OAIGetTokenMetadataResponse_metadataOfIssuance.cpp \
    $${PWD}/OAIGetTokenMetadataResponse_metadataOfIssuance_data.cpp \
    $${PWD}/OAIGetTokenMetadataResponse_metadataOfIssuance_data_userData.cpp \
    $${PWD}/OAIGetTokenMetadataResponse_metadataOfIssuance_data_userData_meta_inner.cpp \
    $${PWD}/OAIGetTokenMetadataResponse_metadataOfUtxo.cpp \
    $${PWD}/OAIGetTokenMetadataResponse_metadataOfUtxo_userData.cpp \
    $${PWD}/OAIGetTransactionInfoResponse.cpp \
    $${PWD}/OAIGetTransactionInfoResponse_vin_inner.cpp \
    $${PWD}/OAIGetTransactionInfoResponse_vin_inner_previousOutput.cpp \
    $${PWD}/OAIGetTransactionInfoResponse_vin_inner_scriptSig.cpp \
    $${PWD}/OAIGetTransactionInfoResponse_vin_inner_tokens_inner.cpp \
    $${PWD}/OAIGetTransactionInfoResponse_vout_inner.cpp \
    $${PWD}/OAIGetTxResponse.cpp \
    $${PWD}/OAIGetTxResponse_vin_inner.cpp \
    $${PWD}/OAIGetTxResponse_vout_inner.cpp \
    $${PWD}/OAIGetTxsResponse.cpp \
    $${PWD}/OAIIssueTokenRequest.cpp \
    $${PWD}/OAIIssueTokenRequest_flags.cpp \
    $${PWD}/OAIIssueTokenRequest_metadata.cpp \
    $${PWD}/OAIIssueTokenRequest_metadata_encryptions_inner.cpp \
    $${PWD}/OAIIssueTokenRequest_metadata_rules.cpp \
    $${PWD}/OAIIssueTokenRequest_metadata_rules_expiration.cpp \
    $${PWD}/OAIIssueTokenRequest_metadata_rules_fees.cpp \
    $${PWD}/OAIIssueTokenRequest_metadata_rules_fees_items_inner.cpp \
    $${PWD}/OAIIssueTokenRequest_metadata_rules_holders_inner.cpp \
    $${PWD}/OAIIssueTokenRequest_metadata_urls_inner.cpp \
    $${PWD}/OAIIssueTokenRequest_transfer_inner.cpp \
    $${PWD}/OAIIssueTokenResponse.cpp \
    $${PWD}/OAIRpcRequest.cpp \
    $${PWD}/OAIRpcResponse.cpp \
    $${PWD}/OAISendTokenRequest.cpp \
    $${PWD}/OAISendTokenResponse.cpp \
    $${PWD}/OAISendTxRequest.cpp \
# APIs
    $${PWD}/OAIInsightApi.cpp \
    $${PWD}/OAIJSONRPCApi.cpp \
    $${PWD}/OAINTP1Api.cpp \
    $${PWD}/OAITestnetFaucetApi.cpp \
    $${PWD}/OAITestnetInsightApi.cpp \
    $${PWD}/OAITestnetNTP1Api.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
