/**
 * AWS MediaConnect
 * API for AWS Elemental MediaConnect
 *
 * The version of the OpenAPI document: 2018-11-14
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIAddFlowOutputs_request.h
 *
 * 
 */

#ifndef OAIAddFlowOutputs_request_H
#define OAIAddFlowOutputs_request_H

#include <QJsonObject>

#include "OAIAddOutputRequest.h"
#include <QList>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIAddOutputRequest;

class OAIAddFlowOutputs_request : public OAIObject {
public:
    OAIAddFlowOutputs_request();
    OAIAddFlowOutputs_request(QString json);
    ~OAIAddFlowOutputs_request() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<OAIAddOutputRequest> getOutputs() const;
    void setOutputs(const QList<OAIAddOutputRequest> &outputs);
    bool is_outputs_Set() const;
    bool is_outputs_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QList<OAIAddOutputRequest> m_outputs;
    bool m_outputs_isSet;
    bool m_outputs_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIAddFlowOutputs_request)

#endif // OAIAddFlowOutputs_request_H
