/*
 * Tradeworks
 * Authentication is required to access all methods of the API. Enter username and password.                 Credentials are automatically set as you type.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PasswordDTO
 */
public class PasswordDTOTest {
    private final PasswordDTO model = new PasswordDTO();

    /**
     * Model tests for PasswordDTO
     */
    @Test
    public void testPasswordDTO() {
        // TODO: test PasswordDTO
    }

    /**
     * Test the property 'newPassword'
     */
    @Test
    public void newPasswordTest() {
        // TODO: test newPassword
    }

    /**
     * Test the property 'oldPassword'
     */
    @Test
    public void oldPasswordTest() {
        // TODO: test oldPassword
    }

}
