openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: "The Blogger API provides access to posts, comments and pages of a\
    \ Blogger blog."
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Blogger API
  version: v3
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
  x-origin:
  - format: google
    url: https://blogger.googleapis.com/$discovery/rest?version=v3
    version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: blogger
servers:
- url: https://blogger.googleapis.com/
tags:
- name: blogs
- name: blogUserInfos
- name: comments
- name: pages
- name: pageViews
- name: posts
- name: postUserInfos
- name: users
paths:
  /v3/blogs/byurl:
    get:
      description: Gets a blog by url.
      operationId: blogger_blogs_get_by_url
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      - Oauth2:
        - https://www.googleapis.com/auth/blogger.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/blogger.readonly
      tags:
      - blogs
      x-openapi-router-controller: openapi_server.controllers.blogs_controller
  /v3/blogs/{blogId}:
    get:
      description: Gets a blog by id.
      operationId: blogger_blogs_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      - Oauth2:
        - https://www.googleapis.com/auth/blogger.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/blogger.readonly
      tags:
      - blogs
      x-openapi-router-controller: openapi_server.controllers.blogs_controller
  /v3/blogs/{blogId}/comments:
    get:
      description: Lists comments by blog.
      operationId: blogger_comments_list_by_blog
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      - Oauth2:
        - https://www.googleapis.com/auth/blogger.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/blogger.readonly
      tags:
      - comments
      x-openapi-router-controller: openapi_server.controllers.comments_controller
  /v3/blogs/{blogId}/pages:
    get:
      description: Lists pages.
      operationId: blogger_pages_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      - Oauth2:
        - https://www.googleapis.com/auth/blogger.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/blogger.readonly
      tags:
      - pages
      x-openapi-router-controller: openapi_server.controllers.pages_controller
    post:
      description: Inserts a page.
      operationId: blogger_pages_insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      tags:
      - pages
      x-openapi-router-controller: openapi_server.controllers.pages_controller
  /v3/blogs/{blogId}/pages/{pageId}:
    delete:
      description: Deletes a page by blog id and page id.
      operationId: blogger_pages_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      tags:
      - pages
      x-openapi-router-controller: openapi_server.controllers.pages_controller
    get:
      description: Gets a page by blog id and page id.
      operationId: blogger_pages_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      - Oauth2:
        - https://www.googleapis.com/auth/blogger.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/blogger.readonly
      tags:
      - pages
      x-openapi-router-controller: openapi_server.controllers.pages_controller
    patch:
      description: Patches a page.
      operationId: blogger_pages_patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      tags:
      - pages
      x-openapi-router-controller: openapi_server.controllers.pages_controller
    put:
      description: Updates a page by blog id and page id.
      operationId: blogger_pages_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      tags:
      - pages
      x-openapi-router-controller: openapi_server.controllers.pages_controller
  /v3/blogs/{blogId}/pages/{pageId}/publish:
    post:
      description: Publishes a page.
      operationId: blogger_pages_publish
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      tags:
      - pages
      x-openapi-router-controller: openapi_server.controllers.pages_controller
  /v3/blogs/{blogId}/pages/{pageId}/revert:
    post:
      description: Reverts a published or scheduled page to draft state.
      operationId: blogger_pages_revert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      tags:
      - pages
      x-openapi-router-controller: openapi_server.controllers.pages_controller
  /v3/blogs/{blogId}/pageviews:
    get:
      description: Gets page views by blog id.
      operationId: blogger_page_views_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      tags:
      - pageViews
      x-openapi-router-controller: openapi_server.controllers.page_views_controller
  /v3/blogs/{blogId}/posts:
    get:
      description: Lists posts.
      operationId: blogger_posts_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      - Oauth2:
        - https://www.googleapis.com/auth/blogger.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/blogger.readonly
      tags:
      - posts
      x-openapi-router-controller: openapi_server.controllers.posts_controller
    post:
      description: Inserts a post.
      operationId: blogger_posts_insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      tags:
      - posts
      x-openapi-router-controller: openapi_server.controllers.posts_controller
  /v3/blogs/{blogId}/posts/bypath:
    get:
      description: Gets a post by path.
      operationId: blogger_posts_get_by_path
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      - Oauth2:
        - https://www.googleapis.com/auth/blogger.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/blogger.readonly
      tags:
      - posts
      x-openapi-router-controller: openapi_server.controllers.posts_controller
  /v3/blogs/{blogId}/posts/search:
    get:
      description: Searches for posts matching given query terms in the specified
        blog.
      operationId: blogger_posts_search
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      - Oauth2:
        - https://www.googleapis.com/auth/blogger.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/blogger.readonly
      tags:
      - posts
      x-openapi-router-controller: openapi_server.controllers.posts_controller
  /v3/blogs/{blogId}/posts/{postId}:
    delete:
      description: Deletes a post by blog id and post id.
      operationId: blogger_posts_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      tags:
      - posts
      x-openapi-router-controller: openapi_server.controllers.posts_controller
    get:
      description: Gets a post by blog id and post id
      operationId: blogger_posts_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      - Oauth2:
        - https://www.googleapis.com/auth/blogger.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/blogger.readonly
      tags:
      - posts
      x-openapi-router-controller: openapi_server.controllers.posts_controller
    patch:
      description: Patches a post.
      operationId: blogger_posts_patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      tags:
      - posts
      x-openapi-router-controller: openapi_server.controllers.posts_controller
    put:
      description: Updates a post by blog id and post id.
      operationId: blogger_posts_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      tags:
      - posts
      x-openapi-router-controller: openapi_server.controllers.posts_controller
  /v3/blogs/{blogId}/posts/{postId}/comments:
    get:
      description: Lists comments.
      operationId: blogger_comments_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      - Oauth2:
        - https://www.googleapis.com/auth/blogger.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/blogger.readonly
      tags:
      - comments
      x-openapi-router-controller: openapi_server.controllers.comments_controller
  /v3/blogs/{blogId}/posts/{postId}/comments/{commentId}:
    delete:
      description: "Deletes a comment by blog id, post id and comment id."
      operationId: blogger_comments_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      tags:
      - comments
      x-openapi-router-controller: openapi_server.controllers.comments_controller
    get:
      description: Gets a comment by id.
      operationId: blogger_comments_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      - Oauth2:
        - https://www.googleapis.com/auth/blogger.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/blogger.readonly
      tags:
      - comments
      x-openapi-router-controller: openapi_server.controllers.comments_controller
  /v3/blogs/{blogId}/posts/{postId}/comments/{commentId}/approve:
    post:
      description: "Marks a comment as not spam by blog id, post id and comment id."
      operationId: blogger_comments_approve
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      tags:
      - comments
      x-openapi-router-controller: openapi_server.controllers.comments_controller
  /v3/blogs/{blogId}/posts/{postId}/comments/{commentId}/removecontent:
    post:
      description: "Removes the content of a comment by blog id, post id and comment\
        \ id."
      operationId: blogger_comments_remove_content
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      tags:
      - comments
      x-openapi-router-controller: openapi_server.controllers.comments_controller
  /v3/blogs/{blogId}/posts/{postId}/comments/{commentId}/spam:
    post:
      description: "Marks a comment as spam by blog id, post id and comment id."
      operationId: blogger_comments_mark_as_spam
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      tags:
      - comments
      x-openapi-router-controller: openapi_server.controllers.comments_controller
  /v3/blogs/{blogId}/posts/{postId}/publish:
    post:
      description: Publishes a post.
      operationId: blogger_posts_publish
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      tags:
      - posts
      x-openapi-router-controller: openapi_server.controllers.posts_controller
  /v3/blogs/{blogId}/posts/{postId}/revert:
    post:
      description: Reverts a published or scheduled post to draft state.
      operationId: blogger_posts_revert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      tags:
      - posts
      x-openapi-router-controller: openapi_server.controllers.posts_controller
  /v3/users/{userId}:
    get:
      description: Gets one user by user_id.
      operationId: blogger_users_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      - Oauth2:
        - https://www.googleapis.com/auth/blogger.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/blogger.readonly
      tags:
      - users
      x-openapi-router-controller: openapi_server.controllers.users_controller
  /v3/users/{userId}/blogs:
    get:
      description: Lists blogs by user.
      operationId: blogger_blogs_list_by_user
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      - Oauth2:
        - https://www.googleapis.com/auth/blogger.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/blogger.readonly
      tags:
      - blogs
      x-openapi-router-controller: openapi_server.controllers.blogs_controller
  /v3/users/{userId}/blogs/{blogId}:
    get:
      description: Gets one blog and user info pair by blog id and user id.
      operationId: blogger_blog_user_infos_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      - Oauth2:
        - https://www.googleapis.com/auth/blogger.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/blogger.readonly
      tags:
      - blogUserInfos
      x-openapi-router-controller: openapi_server.controllers.blog_user_infos_controller
  /v3/users/{userId}/blogs/{blogId}/posts:
    get:
      description: Lists post and user info pairs.
      operationId: blogger_post_user_infos_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      - Oauth2:
        - https://www.googleapis.com/auth/blogger.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/blogger.readonly
      tags:
      - postUserInfos
      x-openapi-router-controller: openapi_server.controllers.post_user_infos_controller
  /v3/users/{userId}/blogs/{blogId}/posts/{postId}:
    get:
      description: "Gets one post and user info pair, by post_id and user_id."
      operationId: blogger_post_user_infos_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/blogger
        Oauth2c:
        - https://www.googleapis.com/auth/blogger
      - Oauth2:
        - https://www.googleapis.com/auth/blogger.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/blogger.readonly
      tags:
      - postUserInfos
      x-openapi-router-controller: openapi_server.controllers.post_user_infos_controller
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/blogger: Manage your Blogger account
            https://www.googleapis.com/auth/blogger.readonly: View your Blogger account
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/blogger: Manage your Blogger account
            https://www.googleapis.com/auth/blogger.readonly: View your Blogger account
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2c
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2c
