openapi: 3.0.0
info:
  contact:
    name: Twitter Developers
    url: https://developer.twitter.com/
    x-twitter: twitter
  description: Twitter API v2 available endpoints
  license:
    name: Twitter Developer Agreement and Policy
    url: https://developer.twitter.com/en/developer-terms/agreement-and-policy.html
  termsOfService: https://developer.twitter.com/en/developer-terms/agreement-and-policy.html
  title: Twitter API v2
  version: "2.62"
  x-apisguru-categories:
  - social
  x-logo:
    url: https://twitter.com/twitter/profile_image?size=original
  x-origin:
  - format: openapi
    url: https://api.twitter.com/2/openapi.json
    version: "3.0"
  x-providerName: twitter.com
  x-serviceName: current
  x-tags:
  - pii
servers:
- description: Twitter API
  url: https://api.twitter.com
tags:
- description: "Endpoints related to retrieving, managing bookmarks of a user"
  name: Bookmarks
- description: Endpoints related to keeping Twitter data in your systems compliant
  name: Compliance
- description: "Endpoints related to retrieving, managing Direct Messages"
  name: Direct Messages
- description: Miscellaneous endpoints for general API functionality
  name: General
- description: "Endpoints related to retrieving, managing Lists"
  name: Lists
- description: "Endpoints related to retrieving, managing Spaces"
  name: Spaces
- description: "Endpoints related to retrieving, searching, and modifying Tweets"
  name: Tweets
- description: "Endpoints related to retrieving, managing relationships of Users"
  name: Users
paths:
  /2/compliance/jobs:
    get:
      description: Returns recent Compliance Jobs for a given job type and optional
        job status
      operationId: list_batch_compliance_jobs
      security:
      - BearerToken: []
      summary: List Compliance Jobs
      tags:
      - Compliance
      x-openapi-router-controller: openapi_server.controllers.compliance_controller
    post:
      description: Creates a compliance for the given job type
      operationId: create_batch_compliance_job
      security:
      - BearerToken: []
      summary: Create compliance job
      tags:
      - Compliance
      x-openapi-router-controller: openapi_server.controllers.compliance_controller
  /2/compliance/jobs/{id}:
    get:
      description: Returns a single Compliance Job by ID
      operationId: get_batch_compliance_job
      security:
      - BearerToken: []
      summary: Get Compliance Job
      tags:
      - Compliance
      x-openapi-router-controller: openapi_server.controllers.compliance_controller
  /2/dm_conversations:
    post:
      description: Creates a new DM Conversation.
      operationId: dm_conversation_id_create
      security:
      - OAuth2UserToken:
        - dm.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Create a new DM Conversation
      tags:
      - Direct Messages
      x-openapi-router-controller: openapi_server.controllers.direct_messages_controller
  /2/dm_conversations/with/{participant_id}/dm_events:
    get:
      description: Returns DM Events for a DM Conversation
      operationId: get_dm_conversations_with_participant_id_dm_events
      security:
      - OAuth2UserToken:
        - dm.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Get DM Events for a DM Conversation
      tags:
      - Direct Messages
      x-openapi-router-controller: openapi_server.controllers.direct_messages_controller
  /2/dm_conversations/with/{participant_id}/messages:
    post:
      description: Creates a new message for a DM Conversation with a participant
        user by ID
      operationId: dm_conversation_with_user_event_id_create
      security:
      - OAuth2UserToken:
        - dm.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Send a new message to a user
      tags:
      - Direct Messages
      x-openapi-router-controller: openapi_server.controllers.direct_messages_controller
  /2/dm_conversations/{dm_conversation_id}/messages:
    post:
      description: Creates a new message for a DM Conversation specified by DM Conversation
        ID
      operationId: dm_conversation_by_id_event_id_create
      security:
      - OAuth2UserToken:
        - dm.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Send a new message to a DM Conversation
      tags:
      - Direct Messages
      x-openapi-router-controller: openapi_server.controllers.direct_messages_controller
  /2/dm_conversations/{id}/dm_events:
    get:
      description: Returns DM Events for a DM Conversation
      operationId: get_dm_conversations_id_dm_events
      security:
      - OAuth2UserToken:
        - dm.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Get DM Events for a DM Conversation
      tags:
      - Direct Messages
      x-openapi-router-controller: openapi_server.controllers.direct_messages_controller
  /2/dm_events:
    get:
      description: Returns recent DM Events across DM conversations
      operationId: get_dm_events
      security:
      - OAuth2UserToken:
        - dm.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Get recent DM Events
      tags:
      - Direct Messages
      x-openapi-router-controller: openapi_server.controllers.direct_messages_controller
  /2/lists:
    post:
      description: Creates a new List.
      operationId: list_id_create
      security:
      - OAuth2UserToken:
        - list.read
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Create List
      tags:
      - Lists
      x-openapi-router-controller: openapi_server.controllers.lists_controller
  /2/lists/{id}:
    delete:
      description: Delete a List that you own.
      operationId: list_id_delete
      security:
      - OAuth2UserToken:
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Delete List
      tags:
      - Lists
      x-openapi-router-controller: openapi_server.controllers.lists_controller
    get:
      description: Returns a List.
      operationId: list_id_get
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - list.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: List lookup by List ID.
      tags:
      - Lists
      x-openapi-router-controller: openapi_server.controllers.lists_controller
    put:
      description: Update a List that you own.
      operationId: list_id_update
      security:
      - OAuth2UserToken:
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Update List.
      tags:
      - Lists
      x-openapi-router-controller: openapi_server.controllers.lists_controller
  /2/lists/{id}/followers:
    get:
      description: Returns a list of Users that follow a List by the provided List
        ID
      operationId: list_get_followers
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - list.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Returns User objects that follow a List by the provided List ID
      tags:
      - Users
      x-openapi-router-controller: openapi_server.controllers.users_controller
  /2/lists/{id}/members:
    get:
      description: Returns a list of Users that are members of a List by the provided
        List ID.
      operationId: list_get_members
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - list.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Returns User objects that are members of a List by the provided List
        ID.
      tags:
      - Users
      x-openapi-router-controller: openapi_server.controllers.users_controller
    post:
      description: Causes a User to become a member of a List.
      operationId: list_add_member
      security:
      - OAuth2UserToken:
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Add a List member
      tags:
      - Lists
      x-openapi-router-controller: openapi_server.controllers.lists_controller
  /2/lists/{id}/members/{user_id}:
    delete:
      description: Causes a User to be removed from the members of a List.
      operationId: list_remove_member
      security:
      - OAuth2UserToken:
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Remove a List member
      tags:
      - Lists
      x-openapi-router-controller: openapi_server.controllers.lists_controller
  /2/lists/{id}/tweets:
    get:
      description: Returns a list of Tweets associated with the provided List ID.
      operationId: lists_id_tweets
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - list.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: List Tweets timeline by List ID.
      tags:
      - Tweets
      x-openapi-router-controller: openapi_server.controllers.tweets_controller
  /2/openapi.json:
    get:
      description: Full OpenAPI Specification in JSON format. (See https://github.com/OAI/OpenAPI-Specification/blob/master/README.md)
      operationId: get_open_api_spec
      summary: Returns the OpenAPI Specification document.
      tags:
      - General
      x-openapi-router-controller: openapi_server.controllers.general_controller
  /2/spaces:
    get:
      description: Returns a variety of information about the Spaces specified by
        the requested IDs
      operationId: find_spaces_by_ids
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - space.read
        - tweet.read
        - users.read
      summary: Space lookup up Space IDs
      tags:
      - Spaces
      x-openapi-router-controller: openapi_server.controllers.spaces_controller
  /2/spaces/by/creator_ids:
    get:
      description: Returns a variety of information about the Spaces created by the
        provided User IDs
      operationId: find_spaces_by_creator_ids
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - space.read
        - tweet.read
        - users.read
      summary: Space lookup by their creators
      tags:
      - Spaces
      x-openapi-router-controller: openapi_server.controllers.spaces_controller
  /2/spaces/search:
    get:
      description: Returns Spaces that match the provided query.
      operationId: search_spaces
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - space.read
        - tweet.read
        - users.read
      summary: Search for Spaces
      tags:
      - Spaces
      x-openapi-router-controller: openapi_server.controllers.spaces_controller
  /2/spaces/{id}:
    get:
      description: Returns a variety of information about the Space specified by the
        requested ID
      operationId: find_space_by_id
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - space.read
        - tweet.read
        - users.read
      summary: Space lookup by Space ID
      tags:
      - Spaces
      x-openapi-router-controller: openapi_server.controllers.spaces_controller
  /2/spaces/{id}/buyers:
    get:
      description: Retrieves the list of Users who purchased a ticket to the given
        space
      operationId: space_buyers
      security:
      - OAuth2UserToken:
        - space.read
        - tweet.read
        - users.read
      summary: Retrieve the list of Users who purchased a ticket to the given space
      tags:
      - Spaces
      - Tweets
      x-openapi-router-controller: openapi_server.controllers.spaces_controller
  /2/spaces/{id}/tweets:
    get:
      description: Retrieves Tweets shared in the specified Space.
      operationId: space_tweets
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - space.read
        - tweet.read
        - users.read
      summary: Retrieve Tweets from a Space.
      tags:
      - Spaces
      - Tweets
      x-openapi-router-controller: openapi_server.controllers.spaces_controller
  /2/tweets:
    get:
      description: Returns a variety of information about the Tweet specified by the
        requested ID.
      operationId: find_tweets_by_id
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: Tweet lookup by Tweet IDs
      tags:
      - Tweets
      x-openapi-router-controller: openapi_server.controllers.tweets_controller
    post:
      description: Causes the User to create a Tweet under the authorized account.
      operationId: create_tweet
      security:
      - OAuth2UserToken:
        - tweet.read
        - tweet.write
        - users.read
      - UserToken: []
      summary: Creation of a Tweet
      tags:
      - Tweets
      x-openapi-router-controller: openapi_server.controllers.tweets_controller
  /2/tweets/compliance/stream:
    get:
      description: Streams 100% of compliance data for Tweets
      operationId: get_tweets_compliance_stream
      security:
      - BearerToken: []
      summary: Tweets Compliance stream
      tags:
      - Compliance
      x-twitter-streaming: true
      x-openapi-router-controller: openapi_server.controllers.compliance_controller
  /2/tweets/counts/all:
    get:
      description: Returns Tweet Counts that match a search query.
      operationId: tweet_counts_full_archive_search
      security:
      - BearerToken: []
      summary: Full archive search counts
      tags:
      - Tweets
      x-openapi-router-controller: openapi_server.controllers.tweets_controller
  /2/tweets/counts/recent:
    get:
      description: Returns Tweet Counts from the last 7 days that match a search query.
      operationId: tweet_counts_recent_search
      security:
      - BearerToken: []
      summary: Recent search counts
      tags:
      - Tweets
      x-openapi-router-controller: openapi_server.controllers.tweets_controller
  /2/tweets/firehose/stream:
    get:
      description: Streams 100% of public Tweets.
      operationId: get_tweets_firehose_stream
      security:
      - BearerToken: []
      summary: Firehose stream
      tags:
      - Tweets
      x-twitter-streaming: true
      x-openapi-router-controller: openapi_server.controllers.tweets_controller
  /2/tweets/label/stream:
    get:
      description: Streams 100% of labeling events applied to Tweets
      operationId: get_tweets_label_stream
      security:
      - BearerToken: []
      summary: Tweets Label stream
      tags:
      - Compliance
      x-twitter-streaming: true
      x-openapi-router-controller: openapi_server.controllers.compliance_controller
  /2/tweets/sample/stream:
    get:
      description: Streams a deterministic 1% of public Tweets.
      operationId: sample_stream
      security:
      - BearerToken: []
      summary: Sample stream
      tags:
      - Tweets
      x-twitter-streaming: true
      x-openapi-router-controller: openapi_server.controllers.tweets_controller
  /2/tweets/sample10/stream:
    get:
      description: Streams a deterministic 10% of public Tweets.
      operationId: get_tweets_sample10_stream
      security:
      - BearerToken: []
      summary: Sample 10% stream
      tags:
      - Tweets
      x-twitter-streaming: true
      x-openapi-router-controller: openapi_server.controllers.tweets_controller
  /2/tweets/search/all:
    get:
      description: Returns Tweets that match a search query.
      operationId: tweets_fullarchive_search
      security:
      - BearerToken: []
      summary: Full-archive search
      tags:
      - Tweets
      x-openapi-router-controller: openapi_server.controllers.tweets_controller
  /2/tweets/search/recent:
    get:
      description: Returns Tweets from the last 7 days that match a search query.
      operationId: tweets_recent_search
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: Recent search
      tags:
      - Tweets
      x-openapi-router-controller: openapi_server.controllers.tweets_controller
  /2/tweets/search/stream:
    get:
      description: Streams Tweets matching the stream's active rule set.
      operationId: search_stream
      security:
      - BearerToken: []
      summary: Filtered stream
      tags:
      - Tweets
      x-twitter-streaming: true
      x-openapi-router-controller: openapi_server.controllers.tweets_controller
  /2/tweets/search/stream/rules:
    get:
      description: "Returns rules from a User's active rule set. Users can fetch all\
        \ of their rules or a subset, specified by the provided rule ids."
      operationId: get_rules
      security:
      - BearerToken: []
      summary: Rules lookup
      tags:
      - Tweets
      x-openapi-router-controller: openapi_server.controllers.tweets_controller
    post:
      description: "Add or delete rules from a User's active rule set. Users can provide\
        \ unique, optionally tagged rules to add. Users can delete their entire rule\
        \ set or a subset specified by rule ids or values."
      operationId: add_or_delete_rules
      security:
      - BearerToken: []
      summary: Add/Delete rules
      tags:
      - Tweets
      x-openapi-router-controller: openapi_server.controllers.tweets_controller
  /2/tweets/{id}:
    delete:
      description: Delete specified Tweet (in the path) by ID.
      operationId: delete_tweet_by_id
      security:
      - OAuth2UserToken:
        - tweet.read
        - tweet.write
        - users.read
      - UserToken: []
      summary: Tweet delete by Tweet ID
      tags:
      - Tweets
      x-openapi-router-controller: openapi_server.controllers.tweets_controller
    get:
      description: Returns a variety of information about the Tweet specified by the
        requested ID.
      operationId: find_tweet_by_id
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: Tweet lookup by Tweet ID
      tags:
      - Tweets
      x-openapi-router-controller: openapi_server.controllers.tweets_controller
  /2/tweets/{id}/liking_users:
    get:
      description: Returns a list of Users that have liked the provided Tweet ID
      operationId: tweets_id_liking_users
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - like.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Returns User objects that have liked the provided Tweet ID
      tags:
      - Users
      x-openapi-router-controller: openapi_server.controllers.users_controller
  /2/tweets/{id}/quote_tweets:
    get:
      description: Returns a variety of information about each Tweet that quotes the
        Tweet specified by the requested ID.
      operationId: find_tweets_that_quote_a_tweet
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: Retrieve Tweets that quote a Tweet.
      tags:
      - Tweets
      x-openapi-router-controller: openapi_server.controllers.tweets_controller
  /2/tweets/{id}/retweeted_by:
    get:
      description: Returns a list of Users that have retweeted the provided Tweet
        ID
      operationId: tweets_id_retweeting_users
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: Returns User objects that have retweeted the provided Tweet ID
      tags:
      - Users
      x-openapi-router-controller: openapi_server.controllers.users_controller
  /2/tweets/{tweet_id}/hidden:
    put:
      description: Hides or unhides a reply to an owned conversation.
      operationId: hide_reply_by_id
      security:
      - OAuth2UserToken:
        - tweet.moderate.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Hide replies
      tags:
      - Tweets
      x-openapi-router-controller: openapi_server.controllers.tweets_controller
  /2/users:
    get:
      description: This endpoint returns information about Users. Specify Users by
        their ID.
      operationId: find_users_by_id
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: User lookup by IDs
      tags:
      - Users
      x-openapi-router-controller: openapi_server.controllers.users_controller
  /2/users/by:
    get:
      description: This endpoint returns information about Users. Specify Users by
        their username.
      operationId: find_users_by_username
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: User lookup by usernames
      tags:
      - Users
      x-openapi-router-controller: openapi_server.controllers.users_controller
  /2/users/by/username/{username}:
    get:
      description: This endpoint returns information about a User. Specify User by
        username.
      operationId: find_user_by_username
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: User lookup by username
      tags:
      - Users
      x-openapi-router-controller: openapi_server.controllers.users_controller
  /2/users/compliance/stream:
    get:
      description: Streams 100% of compliance data for Users
      operationId: get_users_compliance_stream
      security:
      - BearerToken: []
      summary: Users Compliance stream
      tags:
      - Compliance
      x-twitter-streaming: true
      x-openapi-router-controller: openapi_server.controllers.compliance_controller
  /2/users/me:
    get:
      description: This endpoint returns information about the requesting User.
      operationId: find_my_user
      security:
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: User lookup me
      tags:
      - Users
      x-openapi-router-controller: openapi_server.controllers.users_controller
  /2/users/{id}:
    get:
      description: This endpoint returns information about a User. Specify User by
        ID.
      operationId: find_user_by_id
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: User lookup by ID
      tags:
      - Users
      x-openapi-router-controller: openapi_server.controllers.users_controller
  /2/users/{id}/blocking:
    get:
      description: Returns a list of Users that are blocked by the provided User ID
      operationId: users_id_blocking
      security:
      - OAuth2UserToken:
        - block.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Returns User objects that are blocked by provided User ID
      tags:
      - Users
      x-openapi-router-controller: openapi_server.controllers.users_controller
    post:
      description: Causes the User (in the path) to block the target User. The User
        (in the path) must match the User context authorizing the request
      operationId: users_id_block
      security:
      - OAuth2UserToken:
        - block.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Block User by User ID
      tags:
      - Users
      x-openapi-router-controller: openapi_server.controllers.users_controller
  /2/users/{id}/bookmarks:
    get:
      description: Returns Tweet objects that have been bookmarked by the requesting
        User
      operationId: get_users_id_bookmarks
      security:
      - OAuth2UserToken:
        - bookmark.read
        - tweet.read
        - users.read
      summary: Bookmarks by User
      tags:
      - Bookmarks
      x-openapi-router-controller: openapi_server.controllers.bookmarks_controller
    post:
      description: Adds a Tweet (ID in the body) to the requesting User's (in the
        path) bookmarks
      operationId: post_users_id_bookmarks
      security:
      - OAuth2UserToken:
        - bookmark.write
        - tweet.read
        - users.read
      summary: Add Tweet to Bookmarks
      tags:
      - Bookmarks
      x-openapi-router-controller: openapi_server.controllers.bookmarks_controller
  /2/users/{id}/bookmarks/{tweet_id}:
    delete:
      description: Removes a Tweet from the requesting User's bookmarked Tweets.
      operationId: users_id_bookmarks_delete
      security:
      - OAuth2UserToken:
        - bookmark.write
        - tweet.read
        - users.read
      summary: Remove a bookmarked Tweet
      tags:
      - Bookmarks
      x-openapi-router-controller: openapi_server.controllers.bookmarks_controller
  /2/users/{id}/followed_lists:
    get:
      description: Returns a User's followed Lists.
      operationId: user_followed_lists
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - list.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Get User's Followed Lists
      tags:
      - Lists
      x-openapi-router-controller: openapi_server.controllers.lists_controller
    post:
      description: Causes a User to follow a List.
      operationId: list_user_follow
      security:
      - OAuth2UserToken:
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Follow a List
      tags:
      - Lists
      x-openapi-router-controller: openapi_server.controllers.lists_controller
  /2/users/{id}/followed_lists/{list_id}:
    delete:
      description: Causes a User to unfollow a List.
      operationId: list_user_unfollow
      security:
      - OAuth2UserToken:
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Unfollow a List
      tags:
      - Lists
      x-openapi-router-controller: openapi_server.controllers.lists_controller
  /2/users/{id}/followers:
    get:
      description: Returns a list of Users who are followers of the specified User
        ID.
      operationId: users_id_followers
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - follows.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Followers by User ID
      tags:
      - Users
      x-openapi-router-controller: openapi_server.controllers.users_controller
  /2/users/{id}/following:
    get:
      description: Returns a list of Users that are being followed by the provided
        User ID
      operationId: users_id_following
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - follows.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Following by User ID
      tags:
      - Users
      x-openapi-router-controller: openapi_server.controllers.users_controller
    post:
      description: "Causes the User(in the path) to follow, or “request to follow”\
        \ for protected Users, the target User. The User(in the path) must match the\
        \ User context authorizing the request"
      operationId: users_id_follow
      security:
      - OAuth2UserToken:
        - follows.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Follow User
      tags:
      - Users
      x-openapi-router-controller: openapi_server.controllers.users_controller
  /2/users/{id}/liked_tweets:
    get:
      description: Returns a list of Tweets liked by the provided User ID
      operationId: users_id_liked_tweets
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - like.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Returns Tweet objects liked by the provided User ID
      tags:
      - Tweets
      x-openapi-router-controller: openapi_server.controllers.tweets_controller
  /2/users/{id}/likes:
    post:
      description: Causes the User (in the path) to like the specified Tweet. The
        User in the path must match the User context authorizing the request.
      operationId: users_id_like
      security:
      - OAuth2UserToken:
        - like.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Causes the User (in the path) to like the specified Tweet
      tags:
      - Tweets
      x-openapi-router-controller: openapi_server.controllers.tweets_controller
  /2/users/{id}/likes/{tweet_id}:
    delete:
      description: Causes the User (in the path) to unlike the specified Tweet. The
        User must match the User context authorizing the request
      operationId: users_id_unlike
      security:
      - OAuth2UserToken:
        - like.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Causes the User (in the path) to unlike the specified Tweet
      tags:
      - Tweets
      x-openapi-router-controller: openapi_server.controllers.tweets_controller
  /2/users/{id}/list_memberships:
    get:
      description: Get a User's List Memberships.
      operationId: get_user_list_memberships
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - list.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Get a User's List Memberships
      tags:
      - Lists
      x-openapi-router-controller: openapi_server.controllers.lists_controller
  /2/users/{id}/mentions:
    get:
      description: Returns Tweet objects that mention username associated to the provided
        User ID
      operationId: users_id_mentions
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: User mention timeline by User ID
      tags:
      - Tweets
      x-openapi-router-controller: openapi_server.controllers.tweets_controller
  /2/users/{id}/muting:
    get:
      description: Returns a list of Users that are muted by the provided User ID
      operationId: users_id_muting
      security:
      - OAuth2UserToken:
        - mute.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Returns User objects that are muted by the provided User ID
      tags:
      - Users
      x-openapi-router-controller: openapi_server.controllers.users_controller
    post:
      description: Causes the User (in the path) to mute the target User. The User
        (in the path) must match the User context authorizing the request.
      operationId: users_id_mute
      security:
      - OAuth2UserToken:
        - mute.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Mute User by User ID.
      tags:
      - Users
      x-openapi-router-controller: openapi_server.controllers.users_controller
  /2/users/{id}/owned_lists:
    get:
      description: Get a User's Owned Lists.
      operationId: list_user_owned_lists
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - list.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Get a User's Owned Lists.
      tags:
      - Lists
      x-openapi-router-controller: openapi_server.controllers.lists_controller
  /2/users/{id}/pinned_lists:
    get:
      description: Get a User's Pinned Lists.
      operationId: list_user_pinned_lists
      security:
      - OAuth2UserToken:
        - list.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Get a User's Pinned Lists
      tags:
      - Lists
      x-openapi-router-controller: openapi_server.controllers.lists_controller
    post:
      description: Causes a User to pin a List.
      operationId: list_user_pin
      security:
      - OAuth2UserToken:
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Pin a List
      tags:
      - Lists
      x-openapi-router-controller: openapi_server.controllers.lists_controller
  /2/users/{id}/pinned_lists/{list_id}:
    delete:
      description: Causes a User to remove a pinned List.
      operationId: list_user_unpin
      security:
      - OAuth2UserToken:
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Unpin a List
      tags:
      - Lists
      x-openapi-router-controller: openapi_server.controllers.lists_controller
  /2/users/{id}/retweets:
    post:
      description: Causes the User (in the path) to retweet the specified Tweet. The
        User in the path must match the User context authorizing the request.
      operationId: users_id_retweets
      security:
      - OAuth2UserToken:
        - tweet.read
        - tweet.write
        - users.read
      - UserToken: []
      summary: Causes the User (in the path) to retweet the specified Tweet.
      tags:
      - Tweets
      x-openapi-router-controller: openapi_server.controllers.tweets_controller
  /2/users/{id}/retweets/{source_tweet_id}:
    delete:
      description: Causes the User (in the path) to unretweet the specified Tweet.
        The User must match the User context authorizing the request
      operationId: users_id_unretweets
      security:
      - OAuth2UserToken:
        - tweet.read
        - tweet.write
        - users.read
      - UserToken: []
      summary: Causes the User (in the path) to unretweet the specified Tweet
      tags:
      - Tweets
      x-openapi-router-controller: openapi_server.controllers.tweets_controller
  /2/users/{id}/timelines/reverse_chronological:
    get:
      description: Returns Tweet objects that appears in the provided User ID's home
        timeline
      operationId: users_id_timeline
      security:
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: User home timeline by User ID
      tags:
      - Tweets
      x-openapi-router-controller: openapi_server.controllers.tweets_controller
  /2/users/{id}/tweets:
    get:
      description: Returns a list of Tweets authored by the provided User ID
      operationId: users_id_tweets
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: User Tweets timeline by User ID
      tags:
      - Tweets
      x-openapi-router-controller: openapi_server.controllers.tweets_controller
  /2/users/{source_user_id}/blocking/{target_user_id}:
    delete:
      description: Causes the source User to unblock the target User. The source User
        must match the User context authorizing the request
      operationId: users_id_unblock
      security:
      - OAuth2UserToken:
        - block.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Unblock User by User ID
      tags:
      - Users
      x-openapi-router-controller: openapi_server.controllers.users_controller
  /2/users/{source_user_id}/following/{target_user_id}:
    delete:
      description: Causes the source User to unfollow the target User. The source
        User must match the User context authorizing the request
      operationId: users_id_unfollow
      security:
      - OAuth2UserToken:
        - follows.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Unfollow User
      tags:
      - Users
      x-openapi-router-controller: openapi_server.controllers.users_controller
  /2/users/{source_user_id}/muting/{target_user_id}:
    delete:
      description: Causes the source User to unmute the target User. The source User
        must match the User context authorizing the request
      operationId: users_id_unmute
      security:
      - OAuth2UserToken:
        - mute.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Unmute User by User ID
      tags:
      - Users
      x-openapi-router-controller: openapi_server.controllers.users_controller
components:
  securitySchemes:
    BearerToken:
      scheme: bearer
      type: http
      x-bearerInfoFunc: openapi_server.controllers.security_controller.info_from_BearerToken
    OAuth2UserToken:
      flows:
        authorizationCode:
          authorizationUrl: https://api.twitter.com/2/oauth2/authorize
          scopes:
            block.read: Accounts you’ve blocked.
            block.write: Block and unblock accounts for you.
            bookmark.read: Allows an app to read bookmarked Tweets
            bookmark.write: Allows an app to create and delete bookmarks
            dm.read: All your Direct Messages
            dm.write: Send and manage Direct Messages for you
            follows.read: People who follow you and people who you follow.
            follows.write: Follow and unfollow people for you.
            like.read: Tweets you’ve liked and likes you can view.
            like.write: Like and un-like Tweets for you.
            list.read: "Lists, list members, and list followers of lists you’ve created\
              \ or are a member of, including private lists."
            list.write: Create and manage Lists for you.
            mute.read: Accounts you’ve muted.
            mute.write: Mute and unmute accounts for you.
            offline.access: App can request refresh token.
            space.read: Access all of the Spaces you can see.
            tweet.moderate.write: Hide and unhide replies to your Tweets.
            tweet.read: "All the Tweets you can see, including Tweets from protected\
              \ accounts."
            tweet.write: Tweet and retweet for you.
            users.read: "Any account you can see, including protected accounts. Any\
              \ account you can see, including protected accounts."
          tokenUrl: https://api.twitter.com/2/oauth2/token
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_OAuth2UserToken
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_OAuth2UserToken
    UserToken:
      scheme: OAuth
      type: http
