QT += network

HEADERS += \
# Models
    $${PWD}/OAIBrand_registrations_enum_brand_feedback.h \
    $${PWD}/OAIBrand_registrations_enum_identity_status.h \
    $${PWD}/OAIBrand_registrations_enum_status.h \
    $${PWD}/OAIBrand_vetting_enum_vetting_provider.h \
    $${PWD}/OAIListAlphaSenderResponse.h \
    $${PWD}/OAIListBrandRegistrationsResponse.h \
    $${PWD}/OAIListBrandVettingResponse.h \
    $${PWD}/OAIListChannelSenderResponse.h \
    $${PWD}/OAIListPhoneNumberResponse.h \
    $${PWD}/OAIListServiceResponse.h \
    $${PWD}/OAIListServiceResponse_meta.h \
    $${PWD}/OAIListShortCodeResponse.h \
    $${PWD}/OAIListTollfreeVerificationResponse.h \
    $${PWD}/OAIListUsAppToPersonResponse.h \
    $${PWD}/OAIMessaging_v1_brand_registrations.h \
    $${PWD}/OAIMessaging_v1_brand_registrations_brand_registration_otp.h \
    $${PWD}/OAIMessaging_v1_brand_registrations_brand_vetting.h \
    $${PWD}/OAIMessaging_v1_deactivation.h \
    $${PWD}/OAIMessaging_v1_domain_cert_v4.h \
    $${PWD}/OAIMessaging_v1_domain_config.h \
    $${PWD}/OAIMessaging_v1_domain_config_messaging_service.h \
    $${PWD}/OAIMessaging_v1_external_campaign.h \
    $${PWD}/OAIMessaging_v1_linkshortening_messaging_service.h \
    $${PWD}/OAIMessaging_v1_linkshortening_messaging_service_domain_association.h \
    $${PWD}/OAIMessaging_v1_service.h \
    $${PWD}/OAIMessaging_v1_service_alpha_sender.h \
    $${PWD}/OAIMessaging_v1_service_channel_sender.h \
    $${PWD}/OAIMessaging_v1_service_phone_number.h \
    $${PWD}/OAIMessaging_v1_service_short_code.h \
    $${PWD}/OAIMessaging_v1_service_us_app_to_person.h \
    $${PWD}/OAIMessaging_v1_service_us_app_to_person_usecase.h \
    $${PWD}/OAIMessaging_v1_tollfree_verification.h \
    $${PWD}/OAIMessaging_v1_usecase.h \
    $${PWD}/OAIService_enum_scan_message_content.h \
    $${PWD}/OAITollfree_verification_enum_opt_in_type.h \
    $${PWD}/OAITollfree_verification_enum_status.h \
# APIs
    $${PWD}/OAIMessagingV1AlphaSenderApi.h \
    $${PWD}/OAIMessagingV1BrandRegistrationApi.h \
    $${PWD}/OAIMessagingV1BrandRegistrationOtpApi.h \
    $${PWD}/OAIMessagingV1BrandVettingApi.h \
    $${PWD}/OAIMessagingV1ChannelSenderApi.h \
    $${PWD}/OAIMessagingV1DeactivationsApi.h \
    $${PWD}/OAIMessagingV1DomainCertsApi.h \
    $${PWD}/OAIMessagingV1DomainConfigApi.h \
    $${PWD}/OAIMessagingV1DomainConfigMessagingServiceApi.h \
    $${PWD}/OAIMessagingV1ExternalCampaignApi.h \
    $${PWD}/OAIMessagingV1LinkshorteningMessagingServiceApi.h \
    $${PWD}/OAIMessagingV1LinkshorteningMessagingServiceDomainAssociationApi.h \
    $${PWD}/OAIMessagingV1PhoneNumberApi.h \
    $${PWD}/OAIMessagingV1ServiceApi.h \
    $${PWD}/OAIMessagingV1ShortCodeApi.h \
    $${PWD}/OAIMessagingV1TollfreeVerificationApi.h \
    $${PWD}/OAIMessagingV1UsAppToPersonApi.h \
    $${PWD}/OAIMessagingV1UsAppToPersonUsecaseApi.h \
    $${PWD}/OAIMessagingV1UsecaseApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIBrand_registrations_enum_brand_feedback.cpp \
    $${PWD}/OAIBrand_registrations_enum_identity_status.cpp \
    $${PWD}/OAIBrand_registrations_enum_status.cpp \
    $${PWD}/OAIBrand_vetting_enum_vetting_provider.cpp \
    $${PWD}/OAIListAlphaSenderResponse.cpp \
    $${PWD}/OAIListBrandRegistrationsResponse.cpp \
    $${PWD}/OAIListBrandVettingResponse.cpp \
    $${PWD}/OAIListChannelSenderResponse.cpp \
    $${PWD}/OAIListPhoneNumberResponse.cpp \
    $${PWD}/OAIListServiceResponse.cpp \
    $${PWD}/OAIListServiceResponse_meta.cpp \
    $${PWD}/OAIListShortCodeResponse.cpp \
    $${PWD}/OAIListTollfreeVerificationResponse.cpp \
    $${PWD}/OAIListUsAppToPersonResponse.cpp \
    $${PWD}/OAIMessaging_v1_brand_registrations.cpp \
    $${PWD}/OAIMessaging_v1_brand_registrations_brand_registration_otp.cpp \
    $${PWD}/OAIMessaging_v1_brand_registrations_brand_vetting.cpp \
    $${PWD}/OAIMessaging_v1_deactivation.cpp \
    $${PWD}/OAIMessaging_v1_domain_cert_v4.cpp \
    $${PWD}/OAIMessaging_v1_domain_config.cpp \
    $${PWD}/OAIMessaging_v1_domain_config_messaging_service.cpp \
    $${PWD}/OAIMessaging_v1_external_campaign.cpp \
    $${PWD}/OAIMessaging_v1_linkshortening_messaging_service.cpp \
    $${PWD}/OAIMessaging_v1_linkshortening_messaging_service_domain_association.cpp \
    $${PWD}/OAIMessaging_v1_service.cpp \
    $${PWD}/OAIMessaging_v1_service_alpha_sender.cpp \
    $${PWD}/OAIMessaging_v1_service_channel_sender.cpp \
    $${PWD}/OAIMessaging_v1_service_phone_number.cpp \
    $${PWD}/OAIMessaging_v1_service_short_code.cpp \
    $${PWD}/OAIMessaging_v1_service_us_app_to_person.cpp \
    $${PWD}/OAIMessaging_v1_service_us_app_to_person_usecase.cpp \
    $${PWD}/OAIMessaging_v1_tollfree_verification.cpp \
    $${PWD}/OAIMessaging_v1_usecase.cpp \
    $${PWD}/OAIService_enum_scan_message_content.cpp \
    $${PWD}/OAITollfree_verification_enum_opt_in_type.cpp \
    $${PWD}/OAITollfree_verification_enum_status.cpp \
# APIs
    $${PWD}/OAIMessagingV1AlphaSenderApi.cpp \
    $${PWD}/OAIMessagingV1BrandRegistrationApi.cpp \
    $${PWD}/OAIMessagingV1BrandRegistrationOtpApi.cpp \
    $${PWD}/OAIMessagingV1BrandVettingApi.cpp \
    $${PWD}/OAIMessagingV1ChannelSenderApi.cpp \
    $${PWD}/OAIMessagingV1DeactivationsApi.cpp \
    $${PWD}/OAIMessagingV1DomainCertsApi.cpp \
    $${PWD}/OAIMessagingV1DomainConfigApi.cpp \
    $${PWD}/OAIMessagingV1DomainConfigMessagingServiceApi.cpp \
    $${PWD}/OAIMessagingV1ExternalCampaignApi.cpp \
    $${PWD}/OAIMessagingV1LinkshorteningMessagingServiceApi.cpp \
    $${PWD}/OAIMessagingV1LinkshorteningMessagingServiceDomainAssociationApi.cpp \
    $${PWD}/OAIMessagingV1PhoneNumberApi.cpp \
    $${PWD}/OAIMessagingV1ServiceApi.cpp \
    $${PWD}/OAIMessagingV1ShortCodeApi.cpp \
    $${PWD}/OAIMessagingV1TollfreeVerificationApi.cpp \
    $${PWD}/OAIMessagingV1UsAppToPersonApi.cpp \
    $${PWD}/OAIMessagingV1UsAppToPersonUsecaseApi.cpp \
    $${PWD}/OAIMessagingV1UsecaseApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
