# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class PolicyScopeEnum(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    POLICY_SCOPE_UNKNOWN = 'POLICY_SCOPE_UNKNOWN'
    NODE = 'NODE'
    CLUSTER = 'CLUSTER'
    CHASSIS = 'CHASSIS'

    def __init__(self):
        """PolicyScopeEnum - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt: dict) -> 'PolicyScopeEnum':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The PolicyScopeEnum of this PolicyScopeEnum.
        """
        return util.deserialize_model(dikt, cls)
