/**
 * AWS Elemental MediaLive
 * API for AWS Elemental MediaLive
 *
 * The version of the OpenAPI document: 2017-10-14
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class OfferingType.
* @enum {}
* @readonly
*/
export default class OfferingType {
    
        /**
         * value: "NO_UPFRONT"
         * @const
         */
        "NO_UPFRONT" = "NO_UPFRONT";

    

    /**
    * Returns a <code>OfferingType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/OfferingType} The enum <code>OfferingType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

