QT += network

HEADERS += \
# Models
    $${PWD}/OAI401_UNAUTHORIZED.h \
    $${PWD}/OAI406_NOT_ACCEPTABLE.h \
    $${PWD}/OAI500_INTERNAL_SERVER_ERROR.h \
    $${PWD}/OAI503_SERVICE_UNAVAILABLE.h \
    $${PWD}/OAIAvailableProducts_200_response.h \
    $${PWD}/OAIAvailableProducts_200_response_allOf_data_inner.h \
    $${PWD}/OAIAvailableProducts_200_response_allOf_data_inner_pas.h \
    $${PWD}/OAIAvailableProducts_200_response_allOf_data_inner_pas_tourGrades_value.h \
    $${PWD}/OAIAvailableProducts_200_response_allOf_data_inner_pas_tourGrades_value_availDates_inner.h \
    $${PWD}/OAIAvailableProducts_200_response_allOf_data_inner_pas_tourGrades_value_availDates_inner_priceQuote.h \
    $${PWD}/OAIAvailableProducts_request.h \
    $${PWD}/OAIBasicErrorModel.h \
    $${PWD}/OAIBookingAvailabilityDates_200_response.h \
    $${PWD}/OAIBookingAvailabilityTourgradesPricingmatrix_200_response.h \
    $${PWD}/OAIBookingAvailabilityTourgradesPricingmatrix_200_response_allOf_data.h \
    $${PWD}/OAIBookingAvailabilityTourgradesPricingmatrix_200_response_allOf_data_dates_inner.h \
    $${PWD}/OAIBookingAvailabilityTourgradesPricingmatrix_200_response_allOf_data_dates_inner_tourGrades_inner.h \
    $${PWD}/OAIBookingAvailabilityTourgradesPricingmatrix_200_response_allOf_data_dates_inner_tourGrades_inner_pricingMatrix_inner.h \
    $${PWD}/OAIBookingAvailabilityTourgradesPricingmatrix_200_response_allOf_data_dates_inner_tourGrades_inner_pricingMatrix_inner_ageBandPrices_inner.h \
    $${PWD}/OAIBookingAvailabilityTourgradesPricingmatrix_200_response_allOf_data_dates_inner_tourGrades_inner_pricingMatrix_inner_ageBandPrices_inner_prices_inner.h \
    $${PWD}/OAIBookingAvailabilityTourgradesPricingmatrix_request.h \
    $${PWD}/OAIBookingAvailabilityTourgrades_200_response.h \
    $${PWD}/OAIBookingAvailabilityTourgrades_200_response_allOf_data_inner.h \
    $${PWD}/OAIBookingAvailabilityTourgrades_200_response_allOf_data_inner_ageBandsRequired_inner_inner.h \
    $${PWD}/OAIBookingAvailabilityTourgrades_request.h \
    $${PWD}/OAIBookingAvailabilityTourgrades_request_ageBands_inner.h \
    $${PWD}/OAIBookingAvailability_200_response.h \
    $${PWD}/OAIBookingAvailability_200_response_allOf_data.h \
    $${PWD}/OAIBookingAvailability_200_response_allOf_data_availability_inner.h \
    $${PWD}/OAIBookingAvailability_request.h \
    $${PWD}/OAIBookingAvailability_request_ageBands_inner.h \
    $${PWD}/OAIBookingBook_200_response.h \
    $${PWD}/OAIBookingBook_200_response_allOf_data.h \
    $${PWD}/OAIBookingBook_200_response_allOf_data_itemSummaries_inner.h \
    $${PWD}/OAIBookingBook_200_response_allOf_data_itemSummaries_inner_merchantTermsAndConditions.h \
    $${PWD}/OAIBookingBook_200_response_allOf_data_itemSummaries_inner_merchantTermsAndConditions_cancellationFromTourDate_inner.h \
    $${PWD}/OAIBookingBook_200_response_allOf_data_itemSummaries_inner_travellerAgeBands_inner.h \
    $${PWD}/OAIBookingBook_request.h \
    $${PWD}/OAIBookingBook_request_booker.h \
    $${PWD}/OAIBookingBook_request_items_inner.h \
    $${PWD}/OAIBookingBook_request_items_inner_bookingQuestionAnswers_inner.h \
    $${PWD}/OAIBookingBook_request_items_inner_partnerItemDetail.h \
    $${PWD}/OAIBookingBook_request_items_inner_travellers_inner.h \
    $${PWD}/OAIBookingBook_request_partnerDetail.h \
    $${PWD}/OAIBookingCalculateprice_200_response.h \
    $${PWD}/OAIBookingCalculateprice_200_response_allOf_data.h \
    $${PWD}/OAIBookingCalculateprice_200_response_allOf_data_itinerary.h \
    $${PWD}/OAIBookingCalculateprice_200_response_allOf_data_itinerary_itemSummaries_inner.h \
    $${PWD}/OAIBookingCalculateprice_200_response_allOf_data_itinerary_itemSummaries_inner_travellerAgeBands_inner.h \
    $${PWD}/OAIBookingCalculateprice_request.h \
    $${PWD}/OAIBookingCalculateprice_request_items_inner.h \
    $${PWD}/OAIBookingCalculateprice_request_items_inner_travellers_inner.h \
    $${PWD}/OAIBookingEngineId.h \
    $${PWD}/OAIBookingEngineId_response.h \
    $${PWD}/OAIBookingHotels_200_response.h \
    $${PWD}/OAIBookingHotels_200_response_allOf_data_inner.h \
    $${PWD}/OAIBookingMybookings_200_response.h \
    $${PWD}/OAIBookingMybookings_200_response_allOf_data.h \
    $${PWD}/OAIBookingMybookings_200_response_allOf_data_itemSummaries_inner.h \
    $${PWD}/OAIBookingMybookings_200_response_allOf_data_itemSummaries_inner_travellerAgeBands_inner.h \
    $${PWD}/OAIBookingPastbooking_200_response.h \
    $${PWD}/OAIBookingPastbooking_200_response_allOf_data.h \
    $${PWD}/OAIBookingPastbooking_200_response_allOf_data_itemSummaries_inner.h \
    $${PWD}/OAIBookingPricingmatrix_200_response.h \
    $${PWD}/OAIBookingPricingmatrix_200_response_allOf_data_inner.h \
    $${PWD}/OAIBookingPricingmatrix_200_response_allOf_data_inner_ageBandPrices_inner.h \
    $${PWD}/OAIBookingPricingmatrix_200_response_allOf_data_inner_ageBandPrices_inner_prices_inner.h \
    $${PWD}/OAIBookingPricingmatrix_request.h \
    $${PWD}/OAIBookingStatusItems_200_response.h \
    $${PWD}/OAIBookingStatusItems_200_response_allOf_data_inner.h \
    $${PWD}/OAIBookingStatusItems_request.h \
    $${PWD}/OAIBookingStatus_200_response.h \
    $${PWD}/OAIBookingStatus_200_response_allOf_data.h \
    $${PWD}/OAIBookingStatus_200_response_allOf_data_itemSummaries_inner.h \
    $${PWD}/OAIBookingStatus_item.h \
    $${PWD}/OAIBookingStatus_itinerary.h \
    $${PWD}/OAIBookingStatus_request.h \
    $${PWD}/OAIBookingVoucher_200_response.h \
    $${PWD}/OAICancelBookingQuoteResponse.h \
    $${PWD}/OAICancelBookingResponse.h \
    $${PWD}/OAICancelBooking_400_response.h \
    $${PWD}/OAICancelBooking_404_response.h \
    $${PWD}/OAICancellationReason.h \
    $${PWD}/OAICancellationReasonsResponse.h \
    $${PWD}/OAICancellationRequest.h \
    $${PWD}/OAIDestinationType.h \
    $${PWD}/OAIHealthCheck_200_response.h \
    $${PWD}/OAIMerchantCancellation_200_response.h \
    $${PWD}/OAIMerchantCancellation_200_response_allOf_data.h \
    $${PWD}/OAIMerchantCancellation_200_response_allOf_data_cancelItems_inner.h \
    $${PWD}/OAIMerchantCancellation_400_response.h \
    $${PWD}/OAIMerchantCancellation_400_response_allOf_data.h \
    $${PWD}/OAIMerchantCancellation_request.h \
    $${PWD}/OAIMerchantCancellation_request_cancelItems_inner.h \
    $${PWD}/OAIPhotoObject.h \
    $${PWD}/OAIProductPhotos_200_response.h \
    $${PWD}/OAIProductReviews_200_response.h \
    $${PWD}/OAIProduct_200_response.h \
    $${PWD}/OAIProduct_200_response_allOf_data.h \
    $${PWD}/OAIProduct_200_response_allOf_data_ageBands_inner.h \
    $${PWD}/OAIProduct_200_response_allOf_data_bookingQuestions_inner.h \
    $${PWD}/OAIProduct_200_response_allOf_data_merchantTermsAndConditions.h \
    $${PWD}/OAIProduct_200_response_allOf_data_merchantTermsAndConditions_cancellationFromTourDate_inner.h \
    $${PWD}/OAIProduct_200_response_allOf_data_passengerAttributes_inner.h \
    $${PWD}/OAIProduct_200_response_allOf_data_productPhotos_inner.h \
    $${PWD}/OAIProduct_200_response_allOf_data_tourGrades_inner.h \
    $${PWD}/OAIRatingCounts.h \
    $${PWD}/OAIRefundDetails.h \
    $${PWD}/OAIReviewObject.h \
    $${PWD}/OAISearchFreetextResponse.h \
    $${PWD}/OAISearchFreetextResponseAttraction.h \
    $${PWD}/OAISearchFreetextResponseAttraction_allOf_data.h \
    $${PWD}/OAISearchFreetextResponseDestination.h \
    $${PWD}/OAISearchFreetextResponseDestination_allOf_data.h \
    $${PWD}/OAISearchFreetextResponseProduct.h \
    $${PWD}/OAISearchFreetextResponseProduct_allOf_data.h \
    $${PWD}/OAISearchFreetextResponseRecommendation.h \
    $${PWD}/OAISearchFreetextResponseRecommendation_allOf_data.h \
    $${PWD}/OAISearchFreetext_200_response.h \
    $${PWD}/OAISearchFreetext_request.h \
    $${PWD}/OAISearchProductsCodes_200_response.h \
    $${PWD}/OAISearchProductsCodes_200_response_allOf_data_inner.h \
    $${PWD}/OAISearchProductsCodes_request.h \
    $${PWD}/OAISearchProducts_200_response.h \
    $${PWD}/OAISearchProducts_200_response_allOf_data_inner.h \
    $${PWD}/OAISearchProducts_request.h \
    $${PWD}/OAISortOrder.h \
    $${PWD}/OAITaxonomyAttractions_200_response.h \
    $${PWD}/OAITaxonomyAttractions_200_response_allOf_data_inner.h \
    $${PWD}/OAITaxonomyAttractions_request.h \
    $${PWD}/OAITaxonomyCategories_200_response.h \
    $${PWD}/OAITaxonomyCategories_200_response_allOf_data_inner.h \
    $${PWD}/OAITaxonomyCategories_200_response_allOf_data_inner_subcategories_inner.h \
    $${PWD}/OAITaxonomyDestinations_200_response.h \
    $${PWD}/OAITaxonomyDestinations_200_response_allOf_data_inner.h \
    $${PWD}/OAITranslationLevel.h \
# APIs
    $${PWD}/OAIBookingServicesApi.h \
    $${PWD}/OAIDeprecatedServicesApi.h \
    $${PWD}/OAIGeneralServicesApi.h \
    $${PWD}/OAIProductServicesApi.h \
    $${PWD}/OAITaxonomyServicesApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAI401_UNAUTHORIZED.cpp \
    $${PWD}/OAI406_NOT_ACCEPTABLE.cpp \
    $${PWD}/OAI500_INTERNAL_SERVER_ERROR.cpp \
    $${PWD}/OAI503_SERVICE_UNAVAILABLE.cpp \
    $${PWD}/OAIAvailableProducts_200_response.cpp \
    $${PWD}/OAIAvailableProducts_200_response_allOf_data_inner.cpp \
    $${PWD}/OAIAvailableProducts_200_response_allOf_data_inner_pas.cpp \
    $${PWD}/OAIAvailableProducts_200_response_allOf_data_inner_pas_tourGrades_value.cpp \
    $${PWD}/OAIAvailableProducts_200_response_allOf_data_inner_pas_tourGrades_value_availDates_inner.cpp \
    $${PWD}/OAIAvailableProducts_200_response_allOf_data_inner_pas_tourGrades_value_availDates_inner_priceQuote.cpp \
    $${PWD}/OAIAvailableProducts_request.cpp \
    $${PWD}/OAIBasicErrorModel.cpp \
    $${PWD}/OAIBookingAvailabilityDates_200_response.cpp \
    $${PWD}/OAIBookingAvailabilityTourgradesPricingmatrix_200_response.cpp \
    $${PWD}/OAIBookingAvailabilityTourgradesPricingmatrix_200_response_allOf_data.cpp \
    $${PWD}/OAIBookingAvailabilityTourgradesPricingmatrix_200_response_allOf_data_dates_inner.cpp \
    $${PWD}/OAIBookingAvailabilityTourgradesPricingmatrix_200_response_allOf_data_dates_inner_tourGrades_inner.cpp \
    $${PWD}/OAIBookingAvailabilityTourgradesPricingmatrix_200_response_allOf_data_dates_inner_tourGrades_inner_pricingMatrix_inner.cpp \
    $${PWD}/OAIBookingAvailabilityTourgradesPricingmatrix_200_response_allOf_data_dates_inner_tourGrades_inner_pricingMatrix_inner_ageBandPrices_inner.cpp \
    $${PWD}/OAIBookingAvailabilityTourgradesPricingmatrix_200_response_allOf_data_dates_inner_tourGrades_inner_pricingMatrix_inner_ageBandPrices_inner_prices_inner.cpp \
    $${PWD}/OAIBookingAvailabilityTourgradesPricingmatrix_request.cpp \
    $${PWD}/OAIBookingAvailabilityTourgrades_200_response.cpp \
    $${PWD}/OAIBookingAvailabilityTourgrades_200_response_allOf_data_inner.cpp \
    $${PWD}/OAIBookingAvailabilityTourgrades_200_response_allOf_data_inner_ageBandsRequired_inner_inner.cpp \
    $${PWD}/OAIBookingAvailabilityTourgrades_request.cpp \
    $${PWD}/OAIBookingAvailabilityTourgrades_request_ageBands_inner.cpp \
    $${PWD}/OAIBookingAvailability_200_response.cpp \
    $${PWD}/OAIBookingAvailability_200_response_allOf_data.cpp \
    $${PWD}/OAIBookingAvailability_200_response_allOf_data_availability_inner.cpp \
    $${PWD}/OAIBookingAvailability_request.cpp \
    $${PWD}/OAIBookingAvailability_request_ageBands_inner.cpp \
    $${PWD}/OAIBookingBook_200_response.cpp \
    $${PWD}/OAIBookingBook_200_response_allOf_data.cpp \
    $${PWD}/OAIBookingBook_200_response_allOf_data_itemSummaries_inner.cpp \
    $${PWD}/OAIBookingBook_200_response_allOf_data_itemSummaries_inner_merchantTermsAndConditions.cpp \
    $${PWD}/OAIBookingBook_200_response_allOf_data_itemSummaries_inner_merchantTermsAndConditions_cancellationFromTourDate_inner.cpp \
    $${PWD}/OAIBookingBook_200_response_allOf_data_itemSummaries_inner_travellerAgeBands_inner.cpp \
    $${PWD}/OAIBookingBook_request.cpp \
    $${PWD}/OAIBookingBook_request_booker.cpp \
    $${PWD}/OAIBookingBook_request_items_inner.cpp \
    $${PWD}/OAIBookingBook_request_items_inner_bookingQuestionAnswers_inner.cpp \
    $${PWD}/OAIBookingBook_request_items_inner_partnerItemDetail.cpp \
    $${PWD}/OAIBookingBook_request_items_inner_travellers_inner.cpp \
    $${PWD}/OAIBookingBook_request_partnerDetail.cpp \
    $${PWD}/OAIBookingCalculateprice_200_response.cpp \
    $${PWD}/OAIBookingCalculateprice_200_response_allOf_data.cpp \
    $${PWD}/OAIBookingCalculateprice_200_response_allOf_data_itinerary.cpp \
    $${PWD}/OAIBookingCalculateprice_200_response_allOf_data_itinerary_itemSummaries_inner.cpp \
    $${PWD}/OAIBookingCalculateprice_200_response_allOf_data_itinerary_itemSummaries_inner_travellerAgeBands_inner.cpp \
    $${PWD}/OAIBookingCalculateprice_request.cpp \
    $${PWD}/OAIBookingCalculateprice_request_items_inner.cpp \
    $${PWD}/OAIBookingCalculateprice_request_items_inner_travellers_inner.cpp \
    $${PWD}/OAIBookingEngineId.cpp \
    $${PWD}/OAIBookingEngineId_response.cpp \
    $${PWD}/OAIBookingHotels_200_response.cpp \
    $${PWD}/OAIBookingHotels_200_response_allOf_data_inner.cpp \
    $${PWD}/OAIBookingMybookings_200_response.cpp \
    $${PWD}/OAIBookingMybookings_200_response_allOf_data.cpp \
    $${PWD}/OAIBookingMybookings_200_response_allOf_data_itemSummaries_inner.cpp \
    $${PWD}/OAIBookingMybookings_200_response_allOf_data_itemSummaries_inner_travellerAgeBands_inner.cpp \
    $${PWD}/OAIBookingPastbooking_200_response.cpp \
    $${PWD}/OAIBookingPastbooking_200_response_allOf_data.cpp \
    $${PWD}/OAIBookingPastbooking_200_response_allOf_data_itemSummaries_inner.cpp \
    $${PWD}/OAIBookingPricingmatrix_200_response.cpp \
    $${PWD}/OAIBookingPricingmatrix_200_response_allOf_data_inner.cpp \
    $${PWD}/OAIBookingPricingmatrix_200_response_allOf_data_inner_ageBandPrices_inner.cpp \
    $${PWD}/OAIBookingPricingmatrix_200_response_allOf_data_inner_ageBandPrices_inner_prices_inner.cpp \
    $${PWD}/OAIBookingPricingmatrix_request.cpp \
    $${PWD}/OAIBookingStatusItems_200_response.cpp \
    $${PWD}/OAIBookingStatusItems_200_response_allOf_data_inner.cpp \
    $${PWD}/OAIBookingStatusItems_request.cpp \
    $${PWD}/OAIBookingStatus_200_response.cpp \
    $${PWD}/OAIBookingStatus_200_response_allOf_data.cpp \
    $${PWD}/OAIBookingStatus_200_response_allOf_data_itemSummaries_inner.cpp \
    $${PWD}/OAIBookingStatus_item.cpp \
    $${PWD}/OAIBookingStatus_itinerary.cpp \
    $${PWD}/OAIBookingStatus_request.cpp \
    $${PWD}/OAIBookingVoucher_200_response.cpp \
    $${PWD}/OAICancelBookingQuoteResponse.cpp \
    $${PWD}/OAICancelBookingResponse.cpp \
    $${PWD}/OAICancelBooking_400_response.cpp \
    $${PWD}/OAICancelBooking_404_response.cpp \
    $${PWD}/OAICancellationReason.cpp \
    $${PWD}/OAICancellationReasonsResponse.cpp \
    $${PWD}/OAICancellationRequest.cpp \
    $${PWD}/OAIDestinationType.cpp \
    $${PWD}/OAIHealthCheck_200_response.cpp \
    $${PWD}/OAIMerchantCancellation_200_response.cpp \
    $${PWD}/OAIMerchantCancellation_200_response_allOf_data.cpp \
    $${PWD}/OAIMerchantCancellation_200_response_allOf_data_cancelItems_inner.cpp \
    $${PWD}/OAIMerchantCancellation_400_response.cpp \
    $${PWD}/OAIMerchantCancellation_400_response_allOf_data.cpp \
    $${PWD}/OAIMerchantCancellation_request.cpp \
    $${PWD}/OAIMerchantCancellation_request_cancelItems_inner.cpp \
    $${PWD}/OAIPhotoObject.cpp \
    $${PWD}/OAIProductPhotos_200_response.cpp \
    $${PWD}/OAIProductReviews_200_response.cpp \
    $${PWD}/OAIProduct_200_response.cpp \
    $${PWD}/OAIProduct_200_response_allOf_data.cpp \
    $${PWD}/OAIProduct_200_response_allOf_data_ageBands_inner.cpp \
    $${PWD}/OAIProduct_200_response_allOf_data_bookingQuestions_inner.cpp \
    $${PWD}/OAIProduct_200_response_allOf_data_merchantTermsAndConditions.cpp \
    $${PWD}/OAIProduct_200_response_allOf_data_merchantTermsAndConditions_cancellationFromTourDate_inner.cpp \
    $${PWD}/OAIProduct_200_response_allOf_data_passengerAttributes_inner.cpp \
    $${PWD}/OAIProduct_200_response_allOf_data_productPhotos_inner.cpp \
    $${PWD}/OAIProduct_200_response_allOf_data_tourGrades_inner.cpp \
    $${PWD}/OAIRatingCounts.cpp \
    $${PWD}/OAIRefundDetails.cpp \
    $${PWD}/OAIReviewObject.cpp \
    $${PWD}/OAISearchFreetextResponse.cpp \
    $${PWD}/OAISearchFreetextResponseAttraction.cpp \
    $${PWD}/OAISearchFreetextResponseAttraction_allOf_data.cpp \
    $${PWD}/OAISearchFreetextResponseDestination.cpp \
    $${PWD}/OAISearchFreetextResponseDestination_allOf_data.cpp \
    $${PWD}/OAISearchFreetextResponseProduct.cpp \
    $${PWD}/OAISearchFreetextResponseProduct_allOf_data.cpp \
    $${PWD}/OAISearchFreetextResponseRecommendation.cpp \
    $${PWD}/OAISearchFreetextResponseRecommendation_allOf_data.cpp \
    $${PWD}/OAISearchFreetext_200_response.cpp \
    $${PWD}/OAISearchFreetext_request.cpp \
    $${PWD}/OAISearchProductsCodes_200_response.cpp \
    $${PWD}/OAISearchProductsCodes_200_response_allOf_data_inner.cpp \
    $${PWD}/OAISearchProductsCodes_request.cpp \
    $${PWD}/OAISearchProducts_200_response.cpp \
    $${PWD}/OAISearchProducts_200_response_allOf_data_inner.cpp \
    $${PWD}/OAISearchProducts_request.cpp \
    $${PWD}/OAISortOrder.cpp \
    $${PWD}/OAITaxonomyAttractions_200_response.cpp \
    $${PWD}/OAITaxonomyAttractions_200_response_allOf_data_inner.cpp \
    $${PWD}/OAITaxonomyAttractions_request.cpp \
    $${PWD}/OAITaxonomyCategories_200_response.cpp \
    $${PWD}/OAITaxonomyCategories_200_response_allOf_data_inner.cpp \
    $${PWD}/OAITaxonomyCategories_200_response_allOf_data_inner_subcategories_inner.cpp \
    $${PWD}/OAITaxonomyDestinations_200_response.cpp \
    $${PWD}/OAITaxonomyDestinations_200_response_allOf_data_inner.cpp \
    $${PWD}/OAITranslationLevel.cpp \
# APIs
    $${PWD}/OAIBookingServicesApi.cpp \
    $${PWD}/OAIDeprecatedServicesApi.cpp \
    $${PWD}/OAIGeneralServicesApi.cpp \
    $${PWD}/OAIProductServicesApi.cpp \
    $${PWD}/OAITaxonomyServicesApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
