/*
 * Accounts API
 * The Accounts API is a collection of methods used to query a customer account. It allows the developer to retrieve account-related data such as the user account balance. It should be noted that regional variations may exist - so some fields may not be returned for certain territories.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: platform@williamhill.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.AccountBalance;
import org.openapitools.client.model.AccountErrors;
import org.openapitools.client.model.Accounts;
import java.math.BigDecimal;
import org.openapitools.client.model.GetPayments;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountsApi
 */
@Disabled
public class AccountsApiTest {

    private final AccountsApi api = new AccountsApi();

    /**
     * Get a customers account balance
     *
     * This method can be used to retrieve the customer’s account balance in UK Sterling.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBalanceTest() throws ApiException {
        String apiKey = null;
        String apiSecret = null;
        String apiTicket = null;
        List<String> fields = null;
        List<String> include = null;
        List<String> exclude = null;
        String territory = null;
        String languageAsPerTerritory = null;
        AccountBalance response = api.getBalance(apiKey, apiSecret, apiTicket, fields, include, exclude, territory, languageAsPerTerritory);
        // TODO: test validations
    }

    /**
     * Retrieves details of a customers account
     *
     * Retrieves a limited set of customer account details. For security purposes, only a subset is supplied, which does not include fields such as security questions and answers. argFileDR1.properties argFileDR2.properties argFileGIB1.properties argFileGIB2.properties argFileGIB3.properties argFileGIB4.properties argFilePP1.properties argFilePP2.properties argFilePP3.properties argFile.properties argFilePT1.properties argFilePTE.properties argFileSCC1.properties argFileSCC2.properties argFileSCC3.properties argFileSTG.properties argFileSYS.properties CWP GatewayMigrationUtility-1.4.00-85 GatewayMigrationUtility.jar GatewayMigrationUtility.sh gmu.log inputFile.xml lib logs migratePolicy.sh migratev2CWP.sh migratev2Policy.sh retrieveCWP.sh retrievePolicy.sh updateCWP.sh updatePolicyById.sh updatePolicy.sh returned by default, others need to be selected. argFileDR1.properties argFileDR2.properties argFileGIB1.properties argFileGIB2.properties argFileGIB3.properties argFileGIB4.properties argFilePP1.properties argFilePP2.properties argFilePP3.properties argFile.properties argFilePT1.properties argFilePTE.properties argFileSCC1.properties argFileSCC2.properties argFileSCC3.properties argFileSTG.properties argFileSYS.properties CWP GatewayMigrationUtility-1.4.00-85 GatewayMigrationUtility.jar GatewayMigrationUtility.sh gmu.log inputFile.xml lib logs migratePolicy.sh migratev2CWP.sh migratev2Policy.sh retrieveCWP.sh retrievePolicy.sh updateCWP.sh updatePolicyById.sh updatePolicy.sh returned by default only in italian region.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDetailsTest() throws ApiException {
        String apiKey = null;
        String apiSecret = null;
        String apiTicket = null;
        List<String> fields = null;
        List<String> include = null;
        List<String> exclude = null;
        String territory = null;
        String languageAsPerTerritory = null;
        Accounts response = api.getDetails(apiKey, apiSecret, apiTicket, fields, include, exclude, territory, languageAsPerTerritory);
        // TODO: test validations
    }

    /**
     * Gets a customer&#39;s account payments
     *
     * Retrieves the customer’s account payments in UK Sterling.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPaymentsTest() throws ApiException {
        String apiKey = null;
        String apiSecret = null;
        String apiTicket = null;
        BigDecimal page = null;
        BigDecimal pageSize = null;
        String dateFrom = null;
        String dateTo = null;
        String sort = null;
        String transactionType = null;
        List<String> fields = null;
        List<String> include = null;
        List<String> exclude = null;
        String territory = null;
        String languageAsPerTerritory = null;
        GetPayments response = api.getPayments(apiKey, apiSecret, apiTicket, page, pageSize, dateFrom, dateTo, sort, transactionType, fields, include, exclude, territory, languageAsPerTerritory);
        // TODO: test validations
    }

}
