openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: The Google Drive API allows clients to access resources from Google
    Drive.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Google Drive API
  version: v3
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
  x-origin:
  - converter:
      url: https://github.com/mermade/oas-kit
      version: 7.0.4
    format: google
    url: https://www.googleapis.com/discovery/v1/apis/drive/v3/rest
    version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: drive
servers:
- url: https://www.googleapis.com/drive/v3
tags:
- name: about
- name: apps
- name: changes
- name: channels
- name: comments
- name: drives
- name: files
- name: permissions
- name: replies
- name: revisions
- name: teamdrives
paths:
  /about:
    get:
      description: "Gets information about the user, the user's Drive, and system\
        \ capabilities."
      operationId: drive_about_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.appdata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.appdata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.photos.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.photos.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      tags:
      - about
      x-openapi-router-controller: openapi_server.controllers.about_controller
  /apps:
    get:
      description: Lists a user's installed apps.
      operationId: drive_apps_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive.apps.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.apps.readonly
      tags:
      - apps
      x-openapi-router-controller: openapi_server.controllers.apps_controller
  /apps/{appId}:
    get:
      description: Gets a specific app.
      operationId: drive_apps_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.appdata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.appdata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.apps.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.apps.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      tags:
      - apps
      x-openapi-router-controller: openapi_server.controllers.apps_controller
  /changes:
    get:
      description: Lists the changes for a user or shared drive.
      operationId: drive_changes_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.appdata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.appdata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.photos.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.photos.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      tags:
      - changes
      x-openapi-router-controller: openapi_server.controllers.changes_controller
  /changes/startPageToken:
    get:
      description: Gets the starting pageToken for listing future changes.
      operationId: drive_changes_get_start_page_token
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.appdata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.appdata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.photos.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.photos.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      tags:
      - changes
      x-openapi-router-controller: openapi_server.controllers.changes_controller
  /changes/watch:
    post:
      description: Subscribes to changes for a user.
      operationId: drive_changes_watch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.appdata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.appdata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.photos.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.photos.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      tags:
      - changes
      x-openapi-router-controller: openapi_server.controllers.changes_controller
  /channels/stop:
    post:
      description: Stops watching resources through this channel.
      operationId: drive_channels_stop
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.appdata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.appdata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.photos.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.photos.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      tags:
      - channels
      x-openapi-router-controller: openapi_server.controllers.channels_controller
  /drives:
    get:
      description: " Lists the user's shared drives. This method accepts the `q` parameter,\
        \ which is a search query combining one or more search terms. For more information,\
        \ see the [Search for shared drives](/drive/api/guides/search-shareddrives)\
        \ guide."
      operationId: drive_drives_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      tags:
      - drives
      x-openapi-router-controller: openapi_server.controllers.drives_controller
    post:
      description: Creates a shared drive.
      operationId: drive_drives_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      tags:
      - drives
      x-openapi-router-controller: openapi_server.controllers.drives_controller
  /drives/{driveId}:
    delete:
      description: Permanently deletes a shared drive for which the user is an `organizer`.
        The shared drive cannot contain any untrashed items.
      operationId: drive_drives_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      tags:
      - drives
      x-openapi-router-controller: openapi_server.controllers.drives_controller
    get:
      description: Gets a shared drive's metadata by ID.
      operationId: drive_drives_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      tags:
      - drives
      x-openapi-router-controller: openapi_server.controllers.drives_controller
    patch:
      description: Updates the metadate for a shared drive.
      operationId: drive_drives_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      tags:
      - drives
      x-openapi-router-controller: openapi_server.controllers.drives_controller
  /drives/{driveId}/hide:
    post:
      description: Hides a shared drive from the default view.
      operationId: drive_drives_hide
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      tags:
      - drives
      x-openapi-router-controller: openapi_server.controllers.drives_controller
  /drives/{driveId}/unhide:
    post:
      description: Restores a shared drive to the default view.
      operationId: drive_drives_unhide
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      tags:
      - drives
      x-openapi-router-controller: openapi_server.controllers.drives_controller
  /files:
    get:
      description: " Lists the user's files. This method accepts the `q` parameter,\
        \ which is a search query combining one or more search terms. For more information,\
        \ see the [Search for files & folders](/drive/api/guides/search-files) guide.\
        \ *Note:* This method returns *all* files by default, including trashed files.\
        \ If you don't want trashed files to appear in the list, use the `trashed=false`\
        \ query parameter to remove trashed files from the results."
      operationId: drive_files_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.appdata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.appdata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.photos.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.photos.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      tags:
      - files
      x-openapi-router-controller: openapi_server.controllers.files_controller
    post:
      description: " Creates a new file. This method supports an */upload* URI and\
        \ accepts uploaded media with the following characteristics: - *Maximum file\
        \ size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid\
        \ MIME type, rather than the literal `*/*` value. The literal `*/*` is only\
        \ used to indicate that any valid MIME type can be uploaded. For more information\
        \ on uploading files, see [Upload file data](/drive/api/guides/manage-uploads).\
        \ Apps creating shortcuts with `files.create` must specify the MIME type `application/vnd.google-apps.shortcut`.\
        \ Apps should specify a file extension in the `name` property when inserting\
        \ files with the API. For example, an operation to insert a JPEG file should\
        \ specify something like `\"name\": \"cat.jpg\"` in the metadata. Subsequent\
        \ `GET` requests include the read-only `fileExtension` property populated\
        \ with the extension originally specified in the `title` property. When a\
        \ Google Drive user requests to download a file, or when the file is downloaded\
        \ through the sync client, Drive builds a full filename (with extension) based\
        \ on the title. In cases where the extension is missing, Drive attempts to\
        \ determine the extension based on the file's MIME type."
      operationId: drive_files_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.appdata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.appdata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      tags:
      - files
      x-openapi-router-controller: openapi_server.controllers.files_controller
  /files/generateIds:
    get:
      description: Generates a set of file IDs which can be provided in create or
        copy requests.
      operationId: drive_files_generate_ids
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.appdata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.appdata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      tags:
      - files
      x-openapi-router-controller: openapi_server.controllers.files_controller
  /files/trash:
    delete:
      description: Permanently deletes all of the user's trashed files.
      operationId: drive_files_empty_trash
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      tags:
      - files
      x-openapi-router-controller: openapi_server.controllers.files_controller
  /files/{fileId}:
    delete:
      description: "Permanently deletes a file owned by the user without moving it\
        \ to the trash. If the file belongs to a shared drive, the user must be an\
        \ `organizer` on the parent folder. If the target is a folder, all descendants\
        \ owned by the user are also deleted."
      operationId: drive_files_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.appdata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.appdata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      tags:
      - files
      x-openapi-router-controller: openapi_server.controllers.files_controller
    get:
      description: " Gets a file's metadata or content by ID. If you provide the URL\
        \ parameter `alt=media`, then the response includes the file contents in the\
        \ response body. Downloading content with `alt=media` only works if the file\
        \ is stored in Drive. To download Google Docs, Sheets, and Slides use [`files.export`](/drive/api/reference/rest/v3/files/export)\
        \ instead. For more information, see [Download & export files](/drive/api/guides/manage-downloads)."
      operationId: drive_files_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.appdata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.appdata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.photos.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.photos.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      tags:
      - files
      x-openapi-router-controller: openapi_server.controllers.files_controller
    patch:
      description: " Updates a file's metadata and/or content. When calling this method,\
        \ only populate fields in the request that you want to modify. When updating\
        \ fields, some fields might be changed automatically, such as `modifiedDate`.\
        \ This method supports patch semantics. This method supports an */upload*\
        \ URI and accepts uploaded media with the following characteristics: - *Maximum\
        \ file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a\
        \ valid MIME type, rather than the literal `*/*` value. The literal `*/*`\
        \ is only used to indicate that any valid MIME type can be uploaded. For more\
        \ information on uploading files, see [Upload file data](/drive/api/guides/manage-uploads)."
      operationId: drive_files_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.appdata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.appdata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.scripts
        Oauth2c:
        - https://www.googleapis.com/auth/drive.scripts
      tags:
      - files
      x-openapi-router-controller: openapi_server.controllers.files_controller
  /files/{fileId}/comments:
    get:
      description: Lists a file's comments.
      operationId: drive_comments_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      tags:
      - comments
      x-openapi-router-controller: openapi_server.controllers.comments_controller
    post:
      description: Creates a comment on a file.
      operationId: drive_comments_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      tags:
      - comments
      x-openapi-router-controller: openapi_server.controllers.comments_controller
  /files/{fileId}/comments/{commentId}:
    delete:
      description: Deletes a comment.
      operationId: drive_comments_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      tags:
      - comments
      x-openapi-router-controller: openapi_server.controllers.comments_controller
    get:
      description: Gets a comment by ID.
      operationId: drive_comments_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      tags:
      - comments
      x-openapi-router-controller: openapi_server.controllers.comments_controller
    patch:
      description: Updates a comment with patch semantics.
      operationId: drive_comments_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      tags:
      - comments
      x-openapi-router-controller: openapi_server.controllers.comments_controller
  /files/{fileId}/comments/{commentId}/replies:
    get:
      description: Lists a comment's replies.
      operationId: drive_replies_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      tags:
      - replies
      x-openapi-router-controller: openapi_server.controllers.replies_controller
    post:
      description: Creates a reply to a comment.
      operationId: drive_replies_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      tags:
      - replies
      x-openapi-router-controller: openapi_server.controllers.replies_controller
  /files/{fileId}/comments/{commentId}/replies/{replyId}:
    delete:
      description: Deletes a reply.
      operationId: drive_replies_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      tags:
      - replies
      x-openapi-router-controller: openapi_server.controllers.replies_controller
    get:
      description: Gets a reply by ID.
      operationId: drive_replies_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      tags:
      - replies
      x-openapi-router-controller: openapi_server.controllers.replies_controller
    patch:
      description: Updates a reply with patch semantics.
      operationId: drive_replies_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      tags:
      - replies
      x-openapi-router-controller: openapi_server.controllers.replies_controller
  /files/{fileId}/copy:
    post:
      description: Creates a copy of a file and applies any requested updates with
        patch semantics.
      operationId: drive_files_copy
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.appdata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.appdata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.photos.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.photos.readonly
      tags:
      - files
      x-openapi-router-controller: openapi_server.controllers.files_controller
  /files/{fileId}/export:
    get:
      description: Exports a Google Workspace document to the requested MIME type
        and returns exported byte content. Note that the exported content is limited
        to 10MB.
      operationId: drive_files_export
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      tags:
      - files
      x-openapi-router-controller: openapi_server.controllers.files_controller
  /files/{fileId}/listLabels:
    get:
      description: Lists the labels on a file.
      operationId: drive_files_list_labels
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      tags:
      - files
      x-openapi-router-controller: openapi_server.controllers.files_controller
  /files/{fileId}/modifyLabels:
    post:
      description: Modifies the set of labels applied to a file. Returns a list of
        the labels that were added or modified.
      operationId: drive_files_modify_labels
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata
      tags:
      - files
      x-openapi-router-controller: openapi_server.controllers.files_controller
  /files/{fileId}/permissions:
    get:
      description: Lists a file's or shared drive's permissions.
      operationId: drive_permissions_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.photos.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.photos.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      tags:
      - permissions
      x-openapi-router-controller: openapi_server.controllers.permissions_controller
    post:
      description: Creates a permission for a file or shared drive. **Warning:** Concurrent
        permissions operations on the same file are not supported; only the last update
        is applied.
      operationId: drive_permissions_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      tags:
      - permissions
      x-openapi-router-controller: openapi_server.controllers.permissions_controller
  /files/{fileId}/permissions/{permissionId}:
    delete:
      description: Deletes a permission. **Warning:** Concurrent permissions operations
        on the same file are not supported; only the last update is applied.
      operationId: drive_permissions_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      tags:
      - permissions
      x-openapi-router-controller: openapi_server.controllers.permissions_controller
    get:
      description: Gets a permission by ID.
      operationId: drive_permissions_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.photos.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.photos.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      tags:
      - permissions
      x-openapi-router-controller: openapi_server.controllers.permissions_controller
    patch:
      description: Updates a permission with patch semantics. **Warning:** Concurrent
        permissions operations on the same file are not supported; only the last update
        is applied.
      operationId: drive_permissions_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      tags:
      - permissions
      x-openapi-router-controller: openapi_server.controllers.permissions_controller
  /files/{fileId}/revisions:
    get:
      description: Lists a file's revisions.
      operationId: drive_revisions_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.appdata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.appdata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.photos.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.photos.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      tags:
      - revisions
      x-openapi-router-controller: openapi_server.controllers.revisions_controller
  /files/{fileId}/revisions/{revisionId}:
    delete:
      description: "Permanently deletes a file version. You can only delete revisions\
        \ for files with binary content in Google Drive, like images or videos. Revisions\
        \ for other files, like Google Docs or Sheets, and the last remaining file\
        \ version can't be deleted."
      operationId: drive_revisions_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.appdata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.appdata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      tags:
      - revisions
      x-openapi-router-controller: openapi_server.controllers.revisions_controller
    get:
      description: Gets a revision's metadata or content by ID.
      operationId: drive_revisions_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.appdata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.appdata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.photos.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.photos.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      tags:
      - revisions
      x-openapi-router-controller: openapi_server.controllers.revisions_controller
    patch:
      description: Updates a revision with patch semantics.
      operationId: drive_revisions_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.appdata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.appdata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      tags:
      - revisions
      x-openapi-router-controller: openapi_server.controllers.revisions_controller
  /files/{fileId}/watch:
    post:
      description: Subscribes to changes to a file.
      operationId: drive_files_watch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.appdata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.appdata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/drive.metadata.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.metadata.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.photos.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.photos.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      tags:
      - files
      x-openapi-router-controller: openapi_server.controllers.files_controller
  /teamdrives:
    get:
      description: "Deprecated: Use `drives.list` instead."
      operationId: drive_teamdrives_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      tags:
      - teamdrives
      x-openapi-router-controller: openapi_server.controllers.teamdrives_controller
    post:
      description: "Deprecated: Use `drives.create` instead."
      operationId: drive_teamdrives_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      tags:
      - teamdrives
      x-openapi-router-controller: openapi_server.controllers.teamdrives_controller
  /teamdrives/{teamDriveId}:
    delete:
      description: "Deprecated: Use `drives.delete` instead."
      operationId: drive_teamdrives_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      tags:
      - teamdrives
      x-openapi-router-controller: openapi_server.controllers.teamdrives_controller
    get:
      description: "Deprecated: Use `drives.get` instead."
      operationId: drive_teamdrives_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      tags:
      - teamdrives
      x-openapi-router-controller: openapi_server.controllers.teamdrives_controller
    patch:
      description: "Deprecated: Use `drives.update` instead."
      operationId: drive_teamdrives_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      tags:
      - teamdrives
      x-openapi-router-controller: openapi_server.controllers.teamdrives_controller
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/drive: "See, edit, create, and delete\
              \ all of your Google Drive files"
            https://www.googleapis.com/auth/drive.appdata: "See, create, and delete\
              \ its own configuration data in your Google Drive"
            https://www.googleapis.com/auth/drive.apps.readonly: View your Google
              Drive apps
            https://www.googleapis.com/auth/drive.file: "See, edit, create, and delete\
              \ only the specific Google Drive files you use with this app"
            https://www.googleapis.com/auth/drive.metadata: View and manage metadata
              of files in your Google Drive
            https://www.googleapis.com/auth/drive.metadata.readonly: See information
              about your Google Drive files
            https://www.googleapis.com/auth/drive.photos.readonly: "View the photos,\
              \ videos and albums in your Google Photos"
            https://www.googleapis.com/auth/drive.readonly: See and download all your
              Google Drive files
            https://www.googleapis.com/auth/drive.scripts: Modify your Google Apps
              Script scripts' behavior
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/drive: "See, edit, create, and delete\
              \ all of your Google Drive files"
            https://www.googleapis.com/auth/drive.appdata: "See, create, and delete\
              \ its own configuration data in your Google Drive"
            https://www.googleapis.com/auth/drive.apps.readonly: View your Google
              Drive apps
            https://www.googleapis.com/auth/drive.file: "See, edit, create, and delete\
              \ only the specific Google Drive files you use with this app"
            https://www.googleapis.com/auth/drive.metadata: View and manage metadata
              of files in your Google Drive
            https://www.googleapis.com/auth/drive.metadata.readonly: See information
              about your Google Drive files
            https://www.googleapis.com/auth/drive.photos.readonly: "View the photos,\
              \ videos and albums in your Google Photos"
            https://www.googleapis.com/auth/drive.readonly: See and download all your
              Google Drive files
            https://www.googleapis.com/auth/drive.scripts: Modify your Google Apps
              Script scripts' behavior
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2c
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2c
