# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class ClusterResizeInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, resize_type: str=None, allow_cancel_resize: bool=None):
        """ClusterResizeInfo - a model defined in OpenAPI

        :param resize_type: The resize_type of this ClusterResizeInfo.
        :param allow_cancel_resize: The allow_cancel_resize of this ClusterResizeInfo.
        """
        self.openapi_types = {
            'resize_type': str,
            'allow_cancel_resize': bool
        }

        self.attribute_map = {
            'resize_type': 'ResizeType',
            'allow_cancel_resize': 'AllowCancelResize'
        }

        self._resize_type = resize_type
        self._allow_cancel_resize = allow_cancel_resize

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ClusterResizeInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Cluster_ResizeInfo of this ClusterResizeInfo.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def resize_type(self):
        """Gets the resize_type of this ClusterResizeInfo.


        :return: The resize_type of this ClusterResizeInfo.
        :rtype: str
        """
        return self._resize_type

    @resize_type.setter
    def resize_type(self, resize_type):
        """Sets the resize_type of this ClusterResizeInfo.


        :param resize_type: The resize_type of this ClusterResizeInfo.
        :type resize_type: str
        """

        self._resize_type = resize_type

    @property
    def allow_cancel_resize(self):
        """Gets the allow_cancel_resize of this ClusterResizeInfo.


        :return: The allow_cancel_resize of this ClusterResizeInfo.
        :rtype: bool
        """
        return self._allow_cancel_resize

    @allow_cancel_resize.setter
    def allow_cancel_resize(self, allow_cancel_resize):
        """Sets the allow_cancel_resize of this ClusterResizeInfo.


        :param allow_cancel_resize: The allow_cancel_resize of this ClusterResizeInfo.
        :type allow_cancel_resize: bool
        """

        self._allow_cancel_resize = allow_cancel_resize
