# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class FloatValueObject(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, value: float=None):
        """FloatValueObject - a model defined in OpenAPI

        :param value: The value of this FloatValueObject.
        """
        self.openapi_types = {
            'value': float
        }

        self.attribute_map = {
            'value': 'value'
        }

        self._value = value

    @classmethod
    def from_dict(cls, dikt: dict) -> 'FloatValueObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The FloatValueObject of this FloatValueObject.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self):
        """Gets the value of this FloatValueObject.

        Value of the float variable

        :return: The value of this FloatValueObject.
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this FloatValueObject.

        Value of the float variable

        :param value: The value of this FloatValueObject.
        :type value: float
        """

        self._value = value
