QT += network

HEADERS += \
# Models
    $${PWD}/OAIAcceptMatchInput.h \
    $${PWD}/OAIAcceptanceType.h \
    $${PWD}/OAIAlias.h \
    $${PWD}/OAIAnywhereConfiguration.h \
    $${PWD}/OAIAttributeValue.h \
    $${PWD}/OAIAwsCredentials.h \
    $${PWD}/OAIBackfillMode.h \
    $${PWD}/OAIBalancingStrategy.h \
    $${PWD}/OAIBuild.h \
    $${PWD}/OAIBuildStatus.h \
    $${PWD}/OAICertificateConfiguration.h \
    $${PWD}/OAICertificateType.h \
    $${PWD}/OAIClaimFilterOption.h \
    $${PWD}/OAIClaimGameServerInput.h \
    $${PWD}/OAIClaimGameServerInput_FilterOption.h \
    $${PWD}/OAIClaimGameServerOutput.h \
    $${PWD}/OAIClaimGameServerOutput_GameServer.h \
    $${PWD}/OAIComparisonOperatorType.h \
    $${PWD}/OAICompute.h \
    $${PWD}/OAIComputeStatus.h \
    $${PWD}/OAIComputeType.h \
    $${PWD}/OAICreateAliasInput.h \
    $${PWD}/OAICreateAliasInput_RoutingStrategy.h \
    $${PWD}/OAICreateAliasOutput.h \
    $${PWD}/OAICreateAliasOutput_Alias.h \
    $${PWD}/OAICreateBuildInput.h \
    $${PWD}/OAICreateBuildInput_StorageLocation.h \
    $${PWD}/OAICreateBuildOutput.h \
    $${PWD}/OAICreateBuildOutput_Build.h \
    $${PWD}/OAICreateBuildOutput_StorageLocation.h \
    $${PWD}/OAICreateBuildOutput_UploadCredentials.h \
    $${PWD}/OAICreateFleetInput.h \
    $${PWD}/OAICreateFleetInput_AnywhereConfiguration.h \
    $${PWD}/OAICreateFleetInput_CertificateConfiguration.h \
    $${PWD}/OAICreateFleetInput_ResourceCreationLimitPolicy.h \
    $${PWD}/OAICreateFleetInput_RuntimeConfiguration.h \
    $${PWD}/OAICreateFleetLocationsInput.h \
    $${PWD}/OAICreateFleetLocationsOutput.h \
    $${PWD}/OAICreateFleetOutput.h \
    $${PWD}/OAICreateFleetOutput_FleetAttributes.h \
    $${PWD}/OAICreateGameServerGroupInput.h \
    $${PWD}/OAICreateGameServerGroupInput_AutoScalingPolicy.h \
    $${PWD}/OAICreateGameServerGroupInput_LaunchTemplate.h \
    $${PWD}/OAICreateGameServerGroupOutput.h \
    $${PWD}/OAICreateGameServerGroupOutput_GameServerGroup.h \
    $${PWD}/OAICreateGameSessionInput.h \
    $${PWD}/OAICreateGameSessionOutput.h \
    $${PWD}/OAICreateGameSessionOutput_GameSession.h \
    $${PWD}/OAICreateGameSessionQueueInput.h \
    $${PWD}/OAICreateGameSessionQueueInput_FilterConfiguration.h \
    $${PWD}/OAICreateGameSessionQueueInput_PriorityConfiguration.h \
    $${PWD}/OAICreateGameSessionQueueOutput.h \
    $${PWD}/OAICreateGameSessionQueueOutput_GameSessionQueue.h \
    $${PWD}/OAICreateLocationInput.h \
    $${PWD}/OAICreateLocationOutput.h \
    $${PWD}/OAICreateLocationOutput_Location.h \
    $${PWD}/OAICreateMatchmakingConfigurationInput.h \
    $${PWD}/OAICreateMatchmakingConfigurationOutput.h \
    $${PWD}/OAICreateMatchmakingConfigurationOutput_Configuration.h \
    $${PWD}/OAICreateMatchmakingRuleSetInput.h \
    $${PWD}/OAICreateMatchmakingRuleSetOutput.h \
    $${PWD}/OAICreateMatchmakingRuleSetOutput_RuleSet.h \
    $${PWD}/OAICreatePlayerSessionInput.h \
    $${PWD}/OAICreatePlayerSessionOutput.h \
    $${PWD}/OAICreatePlayerSessionOutput_PlayerSession.h \
    $${PWD}/OAICreatePlayerSessionsInput.h \
    $${PWD}/OAICreatePlayerSessionsOutput.h \
    $${PWD}/OAICreateScriptInput.h \
    $${PWD}/OAICreateScriptInput_StorageLocation.h \
    $${PWD}/OAICreateScriptOutput.h \
    $${PWD}/OAICreateScriptOutput_Script.h \
    $${PWD}/OAICreateVpcPeeringAuthorizationInput.h \
    $${PWD}/OAICreateVpcPeeringAuthorizationOutput.h \
    $${PWD}/OAICreateVpcPeeringAuthorizationOutput_VpcPeeringAuthorization.h \
    $${PWD}/OAICreateVpcPeeringConnectionInput.h \
    $${PWD}/OAIDeleteAliasInput.h \
    $${PWD}/OAIDeleteBuildInput.h \
    $${PWD}/OAIDeleteFleetInput.h \
    $${PWD}/OAIDeleteFleetLocationsInput.h \
    $${PWD}/OAIDeleteFleetLocationsOutput.h \
    $${PWD}/OAIDeleteGameServerGroupInput.h \
    $${PWD}/OAIDeleteGameServerGroupOutput.h \
    $${PWD}/OAIDeleteGameServerGroupOutput_GameServerGroup.h \
    $${PWD}/OAIDeleteGameSessionQueueInput.h \
    $${PWD}/OAIDeleteLocationInput.h \
    $${PWD}/OAIDeleteMatchmakingConfigurationInput.h \
    $${PWD}/OAIDeleteMatchmakingRuleSetInput.h \
    $${PWD}/OAIDeleteScalingPolicyInput.h \
    $${PWD}/OAIDeleteScriptInput.h \
    $${PWD}/OAIDeleteVpcPeeringAuthorizationInput.h \
    $${PWD}/OAIDeleteVpcPeeringConnectionInput.h \
    $${PWD}/OAIDeregisterComputeInput.h \
    $${PWD}/OAIDeregisterGameServerInput.h \
    $${PWD}/OAIDescribeAliasInput.h \
    $${PWD}/OAIDescribeAliasOutput.h \
    $${PWD}/OAIDescribeAliasOutput_Alias.h \
    $${PWD}/OAIDescribeBuildInput.h \
    $${PWD}/OAIDescribeBuildOutput.h \
    $${PWD}/OAIDescribeBuildOutput_Build.h \
    $${PWD}/OAIDescribeComputeInput.h \
    $${PWD}/OAIDescribeComputeOutput.h \
    $${PWD}/OAIDescribeComputeOutput_Compute.h \
    $${PWD}/OAIDescribeEC2InstanceLimitsInput.h \
    $${PWD}/OAIDescribeEC2InstanceLimitsOutput.h \
    $${PWD}/OAIDescribeFleetAttributesInput.h \
    $${PWD}/OAIDescribeFleetAttributesOutput.h \
    $${PWD}/OAIDescribeFleetCapacityInput.h \
    $${PWD}/OAIDescribeFleetCapacityOutput.h \
    $${PWD}/OAIDescribeFleetEventsInput.h \
    $${PWD}/OAIDescribeFleetEventsOutput.h \
    $${PWD}/OAIDescribeFleetLocationAttributesInput.h \
    $${PWD}/OAIDescribeFleetLocationAttributesOutput.h \
    $${PWD}/OAIDescribeFleetLocationCapacityInput.h \
    $${PWD}/OAIDescribeFleetLocationCapacityOutput.h \
    $${PWD}/OAIDescribeFleetLocationCapacityOutput_FleetCapacity.h \
    $${PWD}/OAIDescribeFleetLocationUtilizationInput.h \
    $${PWD}/OAIDescribeFleetLocationUtilizationOutput.h \
    $${PWD}/OAIDescribeFleetLocationUtilizationOutput_FleetUtilization.h \
    $${PWD}/OAIDescribeFleetPortSettingsInput.h \
    $${PWD}/OAIDescribeFleetPortSettingsOutput.h \
    $${PWD}/OAIDescribeFleetUtilizationInput.h \
    $${PWD}/OAIDescribeFleetUtilizationOutput.h \
    $${PWD}/OAIDescribeGameServerGroupInput.h \
    $${PWD}/OAIDescribeGameServerGroupOutput.h \
    $${PWD}/OAIDescribeGameServerGroupOutput_GameServerGroup.h \
    $${PWD}/OAIDescribeGameServerInput.h \
    $${PWD}/OAIDescribeGameServerInstancesInput.h \
    $${PWD}/OAIDescribeGameServerInstancesOutput.h \
    $${PWD}/OAIDescribeGameServerOutput.h \
    $${PWD}/OAIDescribeGameServerOutput_GameServer.h \
    $${PWD}/OAIDescribeGameSessionDetailsInput.h \
    $${PWD}/OAIDescribeGameSessionDetailsOutput.h \
    $${PWD}/OAIDescribeGameSessionPlacementInput.h \
    $${PWD}/OAIDescribeGameSessionPlacementOutput.h \
    $${PWD}/OAIDescribeGameSessionPlacementOutput_GameSessionPlacement.h \
    $${PWD}/OAIDescribeGameSessionQueuesInput.h \
    $${PWD}/OAIDescribeGameSessionQueuesOutput.h \
    $${PWD}/OAIDescribeGameSessionsInput.h \
    $${PWD}/OAIDescribeGameSessionsOutput.h \
    $${PWD}/OAIDescribeInstancesInput.h \
    $${PWD}/OAIDescribeInstancesOutput.h \
    $${PWD}/OAIDescribeMatchmakingConfigurationsInput.h \
    $${PWD}/OAIDescribeMatchmakingConfigurationsOutput.h \
    $${PWD}/OAIDescribeMatchmakingInput.h \
    $${PWD}/OAIDescribeMatchmakingOutput.h \
    $${PWD}/OAIDescribeMatchmakingRuleSetsInput.h \
    $${PWD}/OAIDescribeMatchmakingRuleSetsOutput.h \
    $${PWD}/OAIDescribePlayerSessionsInput.h \
    $${PWD}/OAIDescribePlayerSessionsOutput.h \
    $${PWD}/OAIDescribeRuntimeConfigurationInput.h \
    $${PWD}/OAIDescribeRuntimeConfigurationOutput.h \
    $${PWD}/OAIDescribeRuntimeConfigurationOutput_RuntimeConfiguration.h \
    $${PWD}/OAIDescribeScalingPoliciesInput.h \
    $${PWD}/OAIDescribeScalingPoliciesOutput.h \
    $${PWD}/OAIDescribeScriptInput.h \
    $${PWD}/OAIDescribeScriptOutput.h \
    $${PWD}/OAIDescribeScriptOutput_Script.h \
    $${PWD}/OAIDescribeVpcPeeringAuthorizationsOutput.h \
    $${PWD}/OAIDescribeVpcPeeringConnectionsInput.h \
    $${PWD}/OAIDescribeVpcPeeringConnectionsOutput.h \
    $${PWD}/OAIDesiredPlayerSession.h \
    $${PWD}/OAIEC2InstanceCounts.h \
    $${PWD}/OAIEC2InstanceLimit.h \
    $${PWD}/OAIEC2InstanceType.h \
    $${PWD}/OAIEvent.h \
    $${PWD}/OAIEventCode.h \
    $${PWD}/OAIFilterConfiguration.h \
    $${PWD}/OAIFilterInstanceStatus.h \
    $${PWD}/OAIFleetAction.h \
    $${PWD}/OAIFleetAttributes.h \
    $${PWD}/OAIFleetCapacity.h \
    $${PWD}/OAIFleetStatus.h \
    $${PWD}/OAIFleetType.h \
    $${PWD}/OAIFleetUtilization.h \
    $${PWD}/OAIFlexMatchMode.h \
    $${PWD}/OAIGameProperty.h \
    $${PWD}/OAIGameServer.h \
    $${PWD}/OAIGameServerClaimStatus.h \
    $${PWD}/OAIGameServerGroup.h \
    $${PWD}/OAIGameServerGroupAction.h \
    $${PWD}/OAIGameServerGroupAutoScalingPolicy.h \
    $${PWD}/OAIGameServerGroupAutoScalingPolicy_TargetTrackingConfiguration.h \
    $${PWD}/OAIGameServerGroupDeleteOption.h \
    $${PWD}/OAIGameServerGroupInstanceType.h \
    $${PWD}/OAIGameServerGroupStatus.h \
    $${PWD}/OAIGameServerHealthCheck.h \
    $${PWD}/OAIGameServerInstance.h \
    $${PWD}/OAIGameServerInstanceStatus.h \
    $${PWD}/OAIGameServerProtectionPolicy.h \
    $${PWD}/OAIGameServerUtilizationStatus.h \
    $${PWD}/OAIGameSession.h \
    $${PWD}/OAIGameSessionConnectionInfo.h \
    $${PWD}/OAIGameSessionDetail.h \
    $${PWD}/OAIGameSessionDetail_GameSession.h \
    $${PWD}/OAIGameSessionPlacement.h \
    $${PWD}/OAIGameSessionPlacementState.h \
    $${PWD}/OAIGameSessionQueue.h \
    $${PWD}/OAIGameSessionQueueDestination.h \
    $${PWD}/OAIGameSessionStatus.h \
    $${PWD}/OAIGameSessionStatusReason.h \
    $${PWD}/OAIGetComputeAccessInput.h \
    $${PWD}/OAIGetComputeAccessOutput.h \
    $${PWD}/OAIGetComputeAccessOutput_Credentials.h \
    $${PWD}/OAIGetComputeAuthTokenInput.h \
    $${PWD}/OAIGetComputeAuthTokenOutput.h \
    $${PWD}/OAIGetGameSessionLogUrlInput.h \
    $${PWD}/OAIGetGameSessionLogUrlOutput.h \
    $${PWD}/OAIGetInstanceAccessInput.h \
    $${PWD}/OAIGetInstanceAccessOutput.h \
    $${PWD}/OAIGetInstanceAccessOutput_InstanceAccess.h \
    $${PWD}/OAIInstance.h \
    $${PWD}/OAIInstanceAccess.h \
    $${PWD}/OAIInstanceAccess_Credentials.h \
    $${PWD}/OAIInstanceCredentials.h \
    $${PWD}/OAIInstanceDefinition.h \
    $${PWD}/OAIInstanceStatus.h \
    $${PWD}/OAIIpPermission.h \
    $${PWD}/OAIIpProtocol.h \
    $${PWD}/OAILaunchTemplateSpecification.h \
    $${PWD}/OAIListAliasesInput.h \
    $${PWD}/OAIListAliasesOutput.h \
    $${PWD}/OAIListBuildsInput.h \
    $${PWD}/OAIListBuildsOutput.h \
    $${PWD}/OAIListComputeInput.h \
    $${PWD}/OAIListComputeOutput.h \
    $${PWD}/OAIListFleetsInput.h \
    $${PWD}/OAIListFleetsOutput.h \
    $${PWD}/OAIListGameServerGroupsInput.h \
    $${PWD}/OAIListGameServerGroupsOutput.h \
    $${PWD}/OAIListGameServersInput.h \
    $${PWD}/OAIListGameServersOutput.h \
    $${PWD}/OAIListLocationsInput.h \
    $${PWD}/OAIListLocationsOutput.h \
    $${PWD}/OAIListScriptsInput.h \
    $${PWD}/OAIListScriptsOutput.h \
    $${PWD}/OAIListTagsForResourceRequest.h \
    $${PWD}/OAIListTagsForResourceResponse.h \
    $${PWD}/OAILocationAttributes.h \
    $${PWD}/OAILocationAttributes_LocationState.h \
    $${PWD}/OAILocationConfiguration.h \
    $${PWD}/OAILocationFilter.h \
    $${PWD}/OAILocationModel.h \
    $${PWD}/OAILocationState.h \
    $${PWD}/OAILocationUpdateStatus.h \
    $${PWD}/OAIMatchedPlayerSession.h \
    $${PWD}/OAIMatchmakingConfiguration.h \
    $${PWD}/OAIMatchmakingConfigurationStatus.h \
    $${PWD}/OAIMatchmakingRuleSet.h \
    $${PWD}/OAIMatchmakingTicket.h \
    $${PWD}/OAIMatchmakingTicket_GameSessionConnectionInfo.h \
    $${PWD}/OAIMetricName.h \
    $${PWD}/OAIOperatingSystem.h \
    $${PWD}/OAIPlacedPlayerSession.h \
    $${PWD}/OAIPlayer.h \
    $${PWD}/OAIPlayerLatency.h \
    $${PWD}/OAIPlayerLatencyPolicy.h \
    $${PWD}/OAIPlayerSession.h \
    $${PWD}/OAIPlayerSessionCreationPolicy.h \
    $${PWD}/OAIPlayerSessionStatus.h \
    $${PWD}/OAIPolicyType.h \
    $${PWD}/OAIPriorityConfiguration.h \
    $${PWD}/OAIPriorityType.h \
    $${PWD}/OAIProtectionPolicy.h \
    $${PWD}/OAIPutScalingPolicyInput.h \
    $${PWD}/OAIPutScalingPolicyInput_TargetConfiguration.h \
    $${PWD}/OAIPutScalingPolicyOutput.h \
    $${PWD}/OAIRegisterComputeInput.h \
    $${PWD}/OAIRegisterComputeOutput.h \
    $${PWD}/OAIRegisterGameServerInput.h \
    $${PWD}/OAIRegisterGameServerOutput.h \
    $${PWD}/OAIRegisterGameServerOutput_GameServer.h \
    $${PWD}/OAIRequestUploadCredentialsInput.h \
    $${PWD}/OAIRequestUploadCredentialsOutput.h \
    $${PWD}/OAIRequestUploadCredentialsOutput_StorageLocation.h \
    $${PWD}/OAIRequestUploadCredentialsOutput_UploadCredentials.h \
    $${PWD}/OAIResolveAliasInput.h \
    $${PWD}/OAIResolveAliasOutput.h \
    $${PWD}/OAIResourceCreationLimitPolicy.h \
    $${PWD}/OAIResumeGameServerGroupInput.h \
    $${PWD}/OAIResumeGameServerGroupOutput.h \
    $${PWD}/OAIResumeGameServerGroupOutput_GameServerGroup.h \
    $${PWD}/OAIRoutingStrategy.h \
    $${PWD}/OAIRoutingStrategyType.h \
    $${PWD}/OAIRuntimeConfiguration.h \
    $${PWD}/OAIS3Location.h \
    $${PWD}/OAIScalingAdjustmentType.h \
    $${PWD}/OAIScalingPolicy.h \
    $${PWD}/OAIScalingStatusType.h \
    $${PWD}/OAIScript.h \
    $${PWD}/OAISearchGameSessionsInput.h \
    $${PWD}/OAISearchGameSessionsOutput.h \
    $${PWD}/OAIServerProcess.h \
    $${PWD}/OAISortOrder.h \
    $${PWD}/OAIStartFleetActionsInput.h \
    $${PWD}/OAIStartFleetActionsOutput.h \
    $${PWD}/OAIStartGameSessionPlacementInput.h \
    $${PWD}/OAIStartGameSessionPlacementOutput.h \
    $${PWD}/OAIStartGameSessionPlacementOutput_GameSessionPlacement.h \
    $${PWD}/OAIStartMatchBackfillInput.h \
    $${PWD}/OAIStartMatchBackfillOutput.h \
    $${PWD}/OAIStartMatchBackfillOutput_MatchmakingTicket.h \
    $${PWD}/OAIStartMatchmakingInput.h \
    $${PWD}/OAIStartMatchmakingOutput.h \
    $${PWD}/OAIStartMatchmakingOutput_MatchmakingTicket.h \
    $${PWD}/OAIStopFleetActionsInput.h \
    $${PWD}/OAIStopFleetActionsOutput.h \
    $${PWD}/OAIStopGameSessionPlacementInput.h \
    $${PWD}/OAIStopGameSessionPlacementOutput.h \
    $${PWD}/OAIStopGameSessionPlacementOutput_GameSessionPlacement.h \
    $${PWD}/OAIStopMatchmakingInput.h \
    $${PWD}/OAISuspendGameServerGroupInput.h \
    $${PWD}/OAISuspendGameServerGroupOutput.h \
    $${PWD}/OAISuspendGameServerGroupOutput_GameServerGroup.h \
    $${PWD}/OAITag.h \
    $${PWD}/OAITagResourceRequest.h \
    $${PWD}/OAITargetConfiguration.h \
    $${PWD}/OAITargetTrackingConfiguration.h \
    $${PWD}/OAIUntagResourceRequest.h \
    $${PWD}/OAIUpdateAliasInput.h \
    $${PWD}/OAIUpdateAliasInput_RoutingStrategy.h \
    $${PWD}/OAIUpdateAliasOutput.h \
    $${PWD}/OAIUpdateAliasOutput_Alias.h \
    $${PWD}/OAIUpdateBuildInput.h \
    $${PWD}/OAIUpdateBuildOutput.h \
    $${PWD}/OAIUpdateBuildOutput_Build.h \
    $${PWD}/OAIUpdateFleetAttributesInput.h \
    $${PWD}/OAIUpdateFleetAttributesInput_ResourceCreationLimitPolicy.h \
    $${PWD}/OAIUpdateFleetAttributesOutput.h \
    $${PWD}/OAIUpdateFleetCapacityInput.h \
    $${PWD}/OAIUpdateFleetCapacityOutput.h \
    $${PWD}/OAIUpdateFleetPortSettingsInput.h \
    $${PWD}/OAIUpdateFleetPortSettingsOutput.h \
    $${PWD}/OAIUpdateGameServerGroupInput.h \
    $${PWD}/OAIUpdateGameServerGroupOutput.h \
    $${PWD}/OAIUpdateGameServerGroupOutput_GameServerGroup.h \
    $${PWD}/OAIUpdateGameServerInput.h \
    $${PWD}/OAIUpdateGameServerOutput.h \
    $${PWD}/OAIUpdateGameServerOutput_GameServer.h \
    $${PWD}/OAIUpdateGameSessionInput.h \
    $${PWD}/OAIUpdateGameSessionOutput.h \
    $${PWD}/OAIUpdateGameSessionOutput_GameSession.h \
    $${PWD}/OAIUpdateGameSessionQueueInput.h \
    $${PWD}/OAIUpdateGameSessionQueueInput_FilterConfiguration.h \
    $${PWD}/OAIUpdateGameSessionQueueInput_PriorityConfiguration.h \
    $${PWD}/OAIUpdateGameSessionQueueOutput.h \
    $${PWD}/OAIUpdateGameSessionQueueOutput_GameSessionQueue.h \
    $${PWD}/OAIUpdateMatchmakingConfigurationInput.h \
    $${PWD}/OAIUpdateMatchmakingConfigurationOutput.h \
    $${PWD}/OAIUpdateMatchmakingConfigurationOutput_Configuration.h \
    $${PWD}/OAIUpdateRuntimeConfigurationInput.h \
    $${PWD}/OAIUpdateRuntimeConfigurationInput_RuntimeConfiguration.h \
    $${PWD}/OAIUpdateRuntimeConfigurationOutput.h \
    $${PWD}/OAIUpdateRuntimeConfigurationOutput_RuntimeConfiguration.h \
    $${PWD}/OAIUpdateScriptInput.h \
    $${PWD}/OAIUpdateScriptOutput.h \
    $${PWD}/OAIUpdateScriptOutput_Script.h \
    $${PWD}/OAIValidateMatchmakingRuleSetInput.h \
    $${PWD}/OAIValidateMatchmakingRuleSetOutput.h \
    $${PWD}/OAIVpcPeeringAuthorization.h \
    $${PWD}/OAIVpcPeeringConnection.h \
    $${PWD}/OAIVpcPeeringConnectionStatus.h \
    $${PWD}/OAIVpcPeeringConnection_Status.h \
# APIs
    $${PWD}/OAIDefaultApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAcceptMatchInput.cpp \
    $${PWD}/OAIAcceptanceType.cpp \
    $${PWD}/OAIAlias.cpp \
    $${PWD}/OAIAnywhereConfiguration.cpp \
    $${PWD}/OAIAttributeValue.cpp \
    $${PWD}/OAIAwsCredentials.cpp \
    $${PWD}/OAIBackfillMode.cpp \
    $${PWD}/OAIBalancingStrategy.cpp \
    $${PWD}/OAIBuild.cpp \
    $${PWD}/OAIBuildStatus.cpp \
    $${PWD}/OAICertificateConfiguration.cpp \
    $${PWD}/OAICertificateType.cpp \
    $${PWD}/OAIClaimFilterOption.cpp \
    $${PWD}/OAIClaimGameServerInput.cpp \
    $${PWD}/OAIClaimGameServerInput_FilterOption.cpp \
    $${PWD}/OAIClaimGameServerOutput.cpp \
    $${PWD}/OAIClaimGameServerOutput_GameServer.cpp \
    $${PWD}/OAIComparisonOperatorType.cpp \
    $${PWD}/OAICompute.cpp \
    $${PWD}/OAIComputeStatus.cpp \
    $${PWD}/OAIComputeType.cpp \
    $${PWD}/OAICreateAliasInput.cpp \
    $${PWD}/OAICreateAliasInput_RoutingStrategy.cpp \
    $${PWD}/OAICreateAliasOutput.cpp \
    $${PWD}/OAICreateAliasOutput_Alias.cpp \
    $${PWD}/OAICreateBuildInput.cpp \
    $${PWD}/OAICreateBuildInput_StorageLocation.cpp \
    $${PWD}/OAICreateBuildOutput.cpp \
    $${PWD}/OAICreateBuildOutput_Build.cpp \
    $${PWD}/OAICreateBuildOutput_StorageLocation.cpp \
    $${PWD}/OAICreateBuildOutput_UploadCredentials.cpp \
    $${PWD}/OAICreateFleetInput.cpp \
    $${PWD}/OAICreateFleetInput_AnywhereConfiguration.cpp \
    $${PWD}/OAICreateFleetInput_CertificateConfiguration.cpp \
    $${PWD}/OAICreateFleetInput_ResourceCreationLimitPolicy.cpp \
    $${PWD}/OAICreateFleetInput_RuntimeConfiguration.cpp \
    $${PWD}/OAICreateFleetLocationsInput.cpp \
    $${PWD}/OAICreateFleetLocationsOutput.cpp \
    $${PWD}/OAICreateFleetOutput.cpp \
    $${PWD}/OAICreateFleetOutput_FleetAttributes.cpp \
    $${PWD}/OAICreateGameServerGroupInput.cpp \
    $${PWD}/OAICreateGameServerGroupInput_AutoScalingPolicy.cpp \
    $${PWD}/OAICreateGameServerGroupInput_LaunchTemplate.cpp \
    $${PWD}/OAICreateGameServerGroupOutput.cpp \
    $${PWD}/OAICreateGameServerGroupOutput_GameServerGroup.cpp \
    $${PWD}/OAICreateGameSessionInput.cpp \
    $${PWD}/OAICreateGameSessionOutput.cpp \
    $${PWD}/OAICreateGameSessionOutput_GameSession.cpp \
    $${PWD}/OAICreateGameSessionQueueInput.cpp \
    $${PWD}/OAICreateGameSessionQueueInput_FilterConfiguration.cpp \
    $${PWD}/OAICreateGameSessionQueueInput_PriorityConfiguration.cpp \
    $${PWD}/OAICreateGameSessionQueueOutput.cpp \
    $${PWD}/OAICreateGameSessionQueueOutput_GameSessionQueue.cpp \
    $${PWD}/OAICreateLocationInput.cpp \
    $${PWD}/OAICreateLocationOutput.cpp \
    $${PWD}/OAICreateLocationOutput_Location.cpp \
    $${PWD}/OAICreateMatchmakingConfigurationInput.cpp \
    $${PWD}/OAICreateMatchmakingConfigurationOutput.cpp \
    $${PWD}/OAICreateMatchmakingConfigurationOutput_Configuration.cpp \
    $${PWD}/OAICreateMatchmakingRuleSetInput.cpp \
    $${PWD}/OAICreateMatchmakingRuleSetOutput.cpp \
    $${PWD}/OAICreateMatchmakingRuleSetOutput_RuleSet.cpp \
    $${PWD}/OAICreatePlayerSessionInput.cpp \
    $${PWD}/OAICreatePlayerSessionOutput.cpp \
    $${PWD}/OAICreatePlayerSessionOutput_PlayerSession.cpp \
    $${PWD}/OAICreatePlayerSessionsInput.cpp \
    $${PWD}/OAICreatePlayerSessionsOutput.cpp \
    $${PWD}/OAICreateScriptInput.cpp \
    $${PWD}/OAICreateScriptInput_StorageLocation.cpp \
    $${PWD}/OAICreateScriptOutput.cpp \
    $${PWD}/OAICreateScriptOutput_Script.cpp \
    $${PWD}/OAICreateVpcPeeringAuthorizationInput.cpp \
    $${PWD}/OAICreateVpcPeeringAuthorizationOutput.cpp \
    $${PWD}/OAICreateVpcPeeringAuthorizationOutput_VpcPeeringAuthorization.cpp \
    $${PWD}/OAICreateVpcPeeringConnectionInput.cpp \
    $${PWD}/OAIDeleteAliasInput.cpp \
    $${PWD}/OAIDeleteBuildInput.cpp \
    $${PWD}/OAIDeleteFleetInput.cpp \
    $${PWD}/OAIDeleteFleetLocationsInput.cpp \
    $${PWD}/OAIDeleteFleetLocationsOutput.cpp \
    $${PWD}/OAIDeleteGameServerGroupInput.cpp \
    $${PWD}/OAIDeleteGameServerGroupOutput.cpp \
    $${PWD}/OAIDeleteGameServerGroupOutput_GameServerGroup.cpp \
    $${PWD}/OAIDeleteGameSessionQueueInput.cpp \
    $${PWD}/OAIDeleteLocationInput.cpp \
    $${PWD}/OAIDeleteMatchmakingConfigurationInput.cpp \
    $${PWD}/OAIDeleteMatchmakingRuleSetInput.cpp \
    $${PWD}/OAIDeleteScalingPolicyInput.cpp \
    $${PWD}/OAIDeleteScriptInput.cpp \
    $${PWD}/OAIDeleteVpcPeeringAuthorizationInput.cpp \
    $${PWD}/OAIDeleteVpcPeeringConnectionInput.cpp \
    $${PWD}/OAIDeregisterComputeInput.cpp \
    $${PWD}/OAIDeregisterGameServerInput.cpp \
    $${PWD}/OAIDescribeAliasInput.cpp \
    $${PWD}/OAIDescribeAliasOutput.cpp \
    $${PWD}/OAIDescribeAliasOutput_Alias.cpp \
    $${PWD}/OAIDescribeBuildInput.cpp \
    $${PWD}/OAIDescribeBuildOutput.cpp \
    $${PWD}/OAIDescribeBuildOutput_Build.cpp \
    $${PWD}/OAIDescribeComputeInput.cpp \
    $${PWD}/OAIDescribeComputeOutput.cpp \
    $${PWD}/OAIDescribeComputeOutput_Compute.cpp \
    $${PWD}/OAIDescribeEC2InstanceLimitsInput.cpp \
    $${PWD}/OAIDescribeEC2InstanceLimitsOutput.cpp \
    $${PWD}/OAIDescribeFleetAttributesInput.cpp \
    $${PWD}/OAIDescribeFleetAttributesOutput.cpp \
    $${PWD}/OAIDescribeFleetCapacityInput.cpp \
    $${PWD}/OAIDescribeFleetCapacityOutput.cpp \
    $${PWD}/OAIDescribeFleetEventsInput.cpp \
    $${PWD}/OAIDescribeFleetEventsOutput.cpp \
    $${PWD}/OAIDescribeFleetLocationAttributesInput.cpp \
    $${PWD}/OAIDescribeFleetLocationAttributesOutput.cpp \
    $${PWD}/OAIDescribeFleetLocationCapacityInput.cpp \
    $${PWD}/OAIDescribeFleetLocationCapacityOutput.cpp \
    $${PWD}/OAIDescribeFleetLocationCapacityOutput_FleetCapacity.cpp \
    $${PWD}/OAIDescribeFleetLocationUtilizationInput.cpp \
    $${PWD}/OAIDescribeFleetLocationUtilizationOutput.cpp \
    $${PWD}/OAIDescribeFleetLocationUtilizationOutput_FleetUtilization.cpp \
    $${PWD}/OAIDescribeFleetPortSettingsInput.cpp \
    $${PWD}/OAIDescribeFleetPortSettingsOutput.cpp \
    $${PWD}/OAIDescribeFleetUtilizationInput.cpp \
    $${PWD}/OAIDescribeFleetUtilizationOutput.cpp \
    $${PWD}/OAIDescribeGameServerGroupInput.cpp \
    $${PWD}/OAIDescribeGameServerGroupOutput.cpp \
    $${PWD}/OAIDescribeGameServerGroupOutput_GameServerGroup.cpp \
    $${PWD}/OAIDescribeGameServerInput.cpp \
    $${PWD}/OAIDescribeGameServerInstancesInput.cpp \
    $${PWD}/OAIDescribeGameServerInstancesOutput.cpp \
    $${PWD}/OAIDescribeGameServerOutput.cpp \
    $${PWD}/OAIDescribeGameServerOutput_GameServer.cpp \
    $${PWD}/OAIDescribeGameSessionDetailsInput.cpp \
    $${PWD}/OAIDescribeGameSessionDetailsOutput.cpp \
    $${PWD}/OAIDescribeGameSessionPlacementInput.cpp \
    $${PWD}/OAIDescribeGameSessionPlacementOutput.cpp \
    $${PWD}/OAIDescribeGameSessionPlacementOutput_GameSessionPlacement.cpp \
    $${PWD}/OAIDescribeGameSessionQueuesInput.cpp \
    $${PWD}/OAIDescribeGameSessionQueuesOutput.cpp \
    $${PWD}/OAIDescribeGameSessionsInput.cpp \
    $${PWD}/OAIDescribeGameSessionsOutput.cpp \
    $${PWD}/OAIDescribeInstancesInput.cpp \
    $${PWD}/OAIDescribeInstancesOutput.cpp \
    $${PWD}/OAIDescribeMatchmakingConfigurationsInput.cpp \
    $${PWD}/OAIDescribeMatchmakingConfigurationsOutput.cpp \
    $${PWD}/OAIDescribeMatchmakingInput.cpp \
    $${PWD}/OAIDescribeMatchmakingOutput.cpp \
    $${PWD}/OAIDescribeMatchmakingRuleSetsInput.cpp \
    $${PWD}/OAIDescribeMatchmakingRuleSetsOutput.cpp \
    $${PWD}/OAIDescribePlayerSessionsInput.cpp \
    $${PWD}/OAIDescribePlayerSessionsOutput.cpp \
    $${PWD}/OAIDescribeRuntimeConfigurationInput.cpp \
    $${PWD}/OAIDescribeRuntimeConfigurationOutput.cpp \
    $${PWD}/OAIDescribeRuntimeConfigurationOutput_RuntimeConfiguration.cpp \
    $${PWD}/OAIDescribeScalingPoliciesInput.cpp \
    $${PWD}/OAIDescribeScalingPoliciesOutput.cpp \
    $${PWD}/OAIDescribeScriptInput.cpp \
    $${PWD}/OAIDescribeScriptOutput.cpp \
    $${PWD}/OAIDescribeScriptOutput_Script.cpp \
    $${PWD}/OAIDescribeVpcPeeringAuthorizationsOutput.cpp \
    $${PWD}/OAIDescribeVpcPeeringConnectionsInput.cpp \
    $${PWD}/OAIDescribeVpcPeeringConnectionsOutput.cpp \
    $${PWD}/OAIDesiredPlayerSession.cpp \
    $${PWD}/OAIEC2InstanceCounts.cpp \
    $${PWD}/OAIEC2InstanceLimit.cpp \
    $${PWD}/OAIEC2InstanceType.cpp \
    $${PWD}/OAIEvent.cpp \
    $${PWD}/OAIEventCode.cpp \
    $${PWD}/OAIFilterConfiguration.cpp \
    $${PWD}/OAIFilterInstanceStatus.cpp \
    $${PWD}/OAIFleetAction.cpp \
    $${PWD}/OAIFleetAttributes.cpp \
    $${PWD}/OAIFleetCapacity.cpp \
    $${PWD}/OAIFleetStatus.cpp \
    $${PWD}/OAIFleetType.cpp \
    $${PWD}/OAIFleetUtilization.cpp \
    $${PWD}/OAIFlexMatchMode.cpp \
    $${PWD}/OAIGameProperty.cpp \
    $${PWD}/OAIGameServer.cpp \
    $${PWD}/OAIGameServerClaimStatus.cpp \
    $${PWD}/OAIGameServerGroup.cpp \
    $${PWD}/OAIGameServerGroupAction.cpp \
    $${PWD}/OAIGameServerGroupAutoScalingPolicy.cpp \
    $${PWD}/OAIGameServerGroupAutoScalingPolicy_TargetTrackingConfiguration.cpp \
    $${PWD}/OAIGameServerGroupDeleteOption.cpp \
    $${PWD}/OAIGameServerGroupInstanceType.cpp \
    $${PWD}/OAIGameServerGroupStatus.cpp \
    $${PWD}/OAIGameServerHealthCheck.cpp \
    $${PWD}/OAIGameServerInstance.cpp \
    $${PWD}/OAIGameServerInstanceStatus.cpp \
    $${PWD}/OAIGameServerProtectionPolicy.cpp \
    $${PWD}/OAIGameServerUtilizationStatus.cpp \
    $${PWD}/OAIGameSession.cpp \
    $${PWD}/OAIGameSessionConnectionInfo.cpp \
    $${PWD}/OAIGameSessionDetail.cpp \
    $${PWD}/OAIGameSessionDetail_GameSession.cpp \
    $${PWD}/OAIGameSessionPlacement.cpp \
    $${PWD}/OAIGameSessionPlacementState.cpp \
    $${PWD}/OAIGameSessionQueue.cpp \
    $${PWD}/OAIGameSessionQueueDestination.cpp \
    $${PWD}/OAIGameSessionStatus.cpp \
    $${PWD}/OAIGameSessionStatusReason.cpp \
    $${PWD}/OAIGetComputeAccessInput.cpp \
    $${PWD}/OAIGetComputeAccessOutput.cpp \
    $${PWD}/OAIGetComputeAccessOutput_Credentials.cpp \
    $${PWD}/OAIGetComputeAuthTokenInput.cpp \
    $${PWD}/OAIGetComputeAuthTokenOutput.cpp \
    $${PWD}/OAIGetGameSessionLogUrlInput.cpp \
    $${PWD}/OAIGetGameSessionLogUrlOutput.cpp \
    $${PWD}/OAIGetInstanceAccessInput.cpp \
    $${PWD}/OAIGetInstanceAccessOutput.cpp \
    $${PWD}/OAIGetInstanceAccessOutput_InstanceAccess.cpp \
    $${PWD}/OAIInstance.cpp \
    $${PWD}/OAIInstanceAccess.cpp \
    $${PWD}/OAIInstanceAccess_Credentials.cpp \
    $${PWD}/OAIInstanceCredentials.cpp \
    $${PWD}/OAIInstanceDefinition.cpp \
    $${PWD}/OAIInstanceStatus.cpp \
    $${PWD}/OAIIpPermission.cpp \
    $${PWD}/OAIIpProtocol.cpp \
    $${PWD}/OAILaunchTemplateSpecification.cpp \
    $${PWD}/OAIListAliasesInput.cpp \
    $${PWD}/OAIListAliasesOutput.cpp \
    $${PWD}/OAIListBuildsInput.cpp \
    $${PWD}/OAIListBuildsOutput.cpp \
    $${PWD}/OAIListComputeInput.cpp \
    $${PWD}/OAIListComputeOutput.cpp \
    $${PWD}/OAIListFleetsInput.cpp \
    $${PWD}/OAIListFleetsOutput.cpp \
    $${PWD}/OAIListGameServerGroupsInput.cpp \
    $${PWD}/OAIListGameServerGroupsOutput.cpp \
    $${PWD}/OAIListGameServersInput.cpp \
    $${PWD}/OAIListGameServersOutput.cpp \
    $${PWD}/OAIListLocationsInput.cpp \
    $${PWD}/OAIListLocationsOutput.cpp \
    $${PWD}/OAIListScriptsInput.cpp \
    $${PWD}/OAIListScriptsOutput.cpp \
    $${PWD}/OAIListTagsForResourceRequest.cpp \
    $${PWD}/OAIListTagsForResourceResponse.cpp \
    $${PWD}/OAILocationAttributes.cpp \
    $${PWD}/OAILocationAttributes_LocationState.cpp \
    $${PWD}/OAILocationConfiguration.cpp \
    $${PWD}/OAILocationFilter.cpp \
    $${PWD}/OAILocationModel.cpp \
    $${PWD}/OAILocationState.cpp \
    $${PWD}/OAILocationUpdateStatus.cpp \
    $${PWD}/OAIMatchedPlayerSession.cpp \
    $${PWD}/OAIMatchmakingConfiguration.cpp \
    $${PWD}/OAIMatchmakingConfigurationStatus.cpp \
    $${PWD}/OAIMatchmakingRuleSet.cpp \
    $${PWD}/OAIMatchmakingTicket.cpp \
    $${PWD}/OAIMatchmakingTicket_GameSessionConnectionInfo.cpp \
    $${PWD}/OAIMetricName.cpp \
    $${PWD}/OAIOperatingSystem.cpp \
    $${PWD}/OAIPlacedPlayerSession.cpp \
    $${PWD}/OAIPlayer.cpp \
    $${PWD}/OAIPlayerLatency.cpp \
    $${PWD}/OAIPlayerLatencyPolicy.cpp \
    $${PWD}/OAIPlayerSession.cpp \
    $${PWD}/OAIPlayerSessionCreationPolicy.cpp \
    $${PWD}/OAIPlayerSessionStatus.cpp \
    $${PWD}/OAIPolicyType.cpp \
    $${PWD}/OAIPriorityConfiguration.cpp \
    $${PWD}/OAIPriorityType.cpp \
    $${PWD}/OAIProtectionPolicy.cpp \
    $${PWD}/OAIPutScalingPolicyInput.cpp \
    $${PWD}/OAIPutScalingPolicyInput_TargetConfiguration.cpp \
    $${PWD}/OAIPutScalingPolicyOutput.cpp \
    $${PWD}/OAIRegisterComputeInput.cpp \
    $${PWD}/OAIRegisterComputeOutput.cpp \
    $${PWD}/OAIRegisterGameServerInput.cpp \
    $${PWD}/OAIRegisterGameServerOutput.cpp \
    $${PWD}/OAIRegisterGameServerOutput_GameServer.cpp \
    $${PWD}/OAIRequestUploadCredentialsInput.cpp \
    $${PWD}/OAIRequestUploadCredentialsOutput.cpp \
    $${PWD}/OAIRequestUploadCredentialsOutput_StorageLocation.cpp \
    $${PWD}/OAIRequestUploadCredentialsOutput_UploadCredentials.cpp \
    $${PWD}/OAIResolveAliasInput.cpp \
    $${PWD}/OAIResolveAliasOutput.cpp \
    $${PWD}/OAIResourceCreationLimitPolicy.cpp \
    $${PWD}/OAIResumeGameServerGroupInput.cpp \
    $${PWD}/OAIResumeGameServerGroupOutput.cpp \
    $${PWD}/OAIResumeGameServerGroupOutput_GameServerGroup.cpp \
    $${PWD}/OAIRoutingStrategy.cpp \
    $${PWD}/OAIRoutingStrategyType.cpp \
    $${PWD}/OAIRuntimeConfiguration.cpp \
    $${PWD}/OAIS3Location.cpp \
    $${PWD}/OAIScalingAdjustmentType.cpp \
    $${PWD}/OAIScalingPolicy.cpp \
    $${PWD}/OAIScalingStatusType.cpp \
    $${PWD}/OAIScript.cpp \
    $${PWD}/OAISearchGameSessionsInput.cpp \
    $${PWD}/OAISearchGameSessionsOutput.cpp \
    $${PWD}/OAIServerProcess.cpp \
    $${PWD}/OAISortOrder.cpp \
    $${PWD}/OAIStartFleetActionsInput.cpp \
    $${PWD}/OAIStartFleetActionsOutput.cpp \
    $${PWD}/OAIStartGameSessionPlacementInput.cpp \
    $${PWD}/OAIStartGameSessionPlacementOutput.cpp \
    $${PWD}/OAIStartGameSessionPlacementOutput_GameSessionPlacement.cpp \
    $${PWD}/OAIStartMatchBackfillInput.cpp \
    $${PWD}/OAIStartMatchBackfillOutput.cpp \
    $${PWD}/OAIStartMatchBackfillOutput_MatchmakingTicket.cpp \
    $${PWD}/OAIStartMatchmakingInput.cpp \
    $${PWD}/OAIStartMatchmakingOutput.cpp \
    $${PWD}/OAIStartMatchmakingOutput_MatchmakingTicket.cpp \
    $${PWD}/OAIStopFleetActionsInput.cpp \
    $${PWD}/OAIStopFleetActionsOutput.cpp \
    $${PWD}/OAIStopGameSessionPlacementInput.cpp \
    $${PWD}/OAIStopGameSessionPlacementOutput.cpp \
    $${PWD}/OAIStopGameSessionPlacementOutput_GameSessionPlacement.cpp \
    $${PWD}/OAIStopMatchmakingInput.cpp \
    $${PWD}/OAISuspendGameServerGroupInput.cpp \
    $${PWD}/OAISuspendGameServerGroupOutput.cpp \
    $${PWD}/OAISuspendGameServerGroupOutput_GameServerGroup.cpp \
    $${PWD}/OAITag.cpp \
    $${PWD}/OAITagResourceRequest.cpp \
    $${PWD}/OAITargetConfiguration.cpp \
    $${PWD}/OAITargetTrackingConfiguration.cpp \
    $${PWD}/OAIUntagResourceRequest.cpp \
    $${PWD}/OAIUpdateAliasInput.cpp \
    $${PWD}/OAIUpdateAliasInput_RoutingStrategy.cpp \
    $${PWD}/OAIUpdateAliasOutput.cpp \
    $${PWD}/OAIUpdateAliasOutput_Alias.cpp \
    $${PWD}/OAIUpdateBuildInput.cpp \
    $${PWD}/OAIUpdateBuildOutput.cpp \
    $${PWD}/OAIUpdateBuildOutput_Build.cpp \
    $${PWD}/OAIUpdateFleetAttributesInput.cpp \
    $${PWD}/OAIUpdateFleetAttributesInput_ResourceCreationLimitPolicy.cpp \
    $${PWD}/OAIUpdateFleetAttributesOutput.cpp \
    $${PWD}/OAIUpdateFleetCapacityInput.cpp \
    $${PWD}/OAIUpdateFleetCapacityOutput.cpp \
    $${PWD}/OAIUpdateFleetPortSettingsInput.cpp \
    $${PWD}/OAIUpdateFleetPortSettingsOutput.cpp \
    $${PWD}/OAIUpdateGameServerGroupInput.cpp \
    $${PWD}/OAIUpdateGameServerGroupOutput.cpp \
    $${PWD}/OAIUpdateGameServerGroupOutput_GameServerGroup.cpp \
    $${PWD}/OAIUpdateGameServerInput.cpp \
    $${PWD}/OAIUpdateGameServerOutput.cpp \
    $${PWD}/OAIUpdateGameServerOutput_GameServer.cpp \
    $${PWD}/OAIUpdateGameSessionInput.cpp \
    $${PWD}/OAIUpdateGameSessionOutput.cpp \
    $${PWD}/OAIUpdateGameSessionOutput_GameSession.cpp \
    $${PWD}/OAIUpdateGameSessionQueueInput.cpp \
    $${PWD}/OAIUpdateGameSessionQueueInput_FilterConfiguration.cpp \
    $${PWD}/OAIUpdateGameSessionQueueInput_PriorityConfiguration.cpp \
    $${PWD}/OAIUpdateGameSessionQueueOutput.cpp \
    $${PWD}/OAIUpdateGameSessionQueueOutput_GameSessionQueue.cpp \
    $${PWD}/OAIUpdateMatchmakingConfigurationInput.cpp \
    $${PWD}/OAIUpdateMatchmakingConfigurationOutput.cpp \
    $${PWD}/OAIUpdateMatchmakingConfigurationOutput_Configuration.cpp \
    $${PWD}/OAIUpdateRuntimeConfigurationInput.cpp \
    $${PWD}/OAIUpdateRuntimeConfigurationInput_RuntimeConfiguration.cpp \
    $${PWD}/OAIUpdateRuntimeConfigurationOutput.cpp \
    $${PWD}/OAIUpdateRuntimeConfigurationOutput_RuntimeConfiguration.cpp \
    $${PWD}/OAIUpdateScriptInput.cpp \
    $${PWD}/OAIUpdateScriptOutput.cpp \
    $${PWD}/OAIUpdateScriptOutput_Script.cpp \
    $${PWD}/OAIValidateMatchmakingRuleSetInput.cpp \
    $${PWD}/OAIValidateMatchmakingRuleSetOutput.cpp \
    $${PWD}/OAIVpcPeeringAuthorization.cpp \
    $${PWD}/OAIVpcPeeringConnection.cpp \
    $${PWD}/OAIVpcPeeringConnectionStatus.cpp \
    $${PWD}/OAIVpcPeeringConnection_Status.cpp \
# APIs
    $${PWD}/OAIDefaultApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
