QT += network

HEADERS += \
# Models
    $${PWD}/OAIAvailableProvidersList.h \
    $${PWD}/OAIAvailableProvidersListCity.h \
    $${PWD}/OAIAvailableProvidersListCountry.h \
    $${PWD}/OAIAvailableProvidersListParameters.h \
    $${PWD}/OAIAvailableProvidersListState.h \
    $${PWD}/OAIAzureReachabilityReport.h \
    $${PWD}/OAIAzureReachabilityReportItem.h \
    $${PWD}/OAIAzureReachabilityReportLatencyInfo.h \
    $${PWD}/OAIAzureReachabilityReportLocation.h \
    $${PWD}/OAIAzureReachabilityReportParameters.h \
    $${PWD}/OAIConnectionMonitor.h \
    $${PWD}/OAIConnectionMonitorDestination.h \
    $${PWD}/OAIConnectionMonitorEndpoint.h \
    $${PWD}/OAIConnectionMonitorEndpointFilter.h \
    $${PWD}/OAIConnectionMonitorEndpointFilterItem.h \
    $${PWD}/OAIConnectionMonitorHttpConfiguration.h \
    $${PWD}/OAIConnectionMonitorIcmpConfiguration.h \
    $${PWD}/OAIConnectionMonitorListResult.h \
    $${PWD}/OAIConnectionMonitorOutput.h \
    $${PWD}/OAIConnectionMonitorParameters.h \
    $${PWD}/OAIConnectionMonitorQueryResult.h \
    $${PWD}/OAIConnectionMonitorResult.h \
    $${PWD}/OAIConnectionMonitorResultProperties.h \
    $${PWD}/OAIConnectionMonitorSource.h \
    $${PWD}/OAIConnectionMonitorSuccessThreshold.h \
    $${PWD}/OAIConnectionMonitorTcpConfiguration.h \
    $${PWD}/OAIConnectionMonitorTestConfiguration.h \
    $${PWD}/OAIConnectionMonitorTestGroup.h \
    $${PWD}/OAIConnectionMonitorWorkspaceSettings.h \
    $${PWD}/OAIConnectionMonitors_List_default_response.h \
    $${PWD}/OAIConnectionMonitors_List_default_response_error.h \
    $${PWD}/OAIConnectionStateSnapshot.h \
    $${PWD}/OAIConnectionStateSnapshot_hops_inner.h \
    $${PWD}/OAIConnectionStateSnapshot_hops_inner_issues_inner.h \
    $${PWD}/OAIConnectivityDestination.h \
    $${PWD}/OAIConnectivityHop.h \
    $${PWD}/OAIConnectivityInformation.h \
    $${PWD}/OAIConnectivityIssue.h \
    $${PWD}/OAIConnectivityParameters.h \
    $${PWD}/OAIConnectivitySource.h \
    $${PWD}/OAIDirection.h \
    $${PWD}/OAIErrorResponse.h \
    $${PWD}/OAIEvaluatedNetworkSecurityGroup.h \
    $${PWD}/OAIFlowLog.h \
    $${PWD}/OAIFlowLogFormatParameters.h \
    $${PWD}/OAIFlowLogInformation.h \
    $${PWD}/OAIFlowLogListResult.h \
    $${PWD}/OAIFlowLogProperties.h \
    $${PWD}/OAIFlowLogPropertiesFormat.h \
    $${PWD}/OAIFlowLogStatusParameters.h \
    $${PWD}/OAIHTTPConfiguration.h \
    $${PWD}/OAIHTTPHeader.h \
    $${PWD}/OAIMatchedRule.h \
    $${PWD}/OAINetworkConfigurationDiagnosticParameters.h \
    $${PWD}/OAINetworkConfigurationDiagnosticProfile.h \
    $${PWD}/OAINetworkConfigurationDiagnosticResponse.h \
    $${PWD}/OAINetworkConfigurationDiagnosticResult.h \
    $${PWD}/OAINetworkInterfaceAssociation.h \
    $${PWD}/OAINetworkInterfaceAssociation_securityRules_inner.h \
    $${PWD}/OAINetworkInterfaceAssociation_securityRules_inner_properties.h \
    $${PWD}/OAINetworkInterfaceAssociation_securityRules_inner_properties_destinationApplicationSecurityGroups_inner.h \
    $${PWD}/OAINetworkInterfaceAssociation_securityRules_inner_properties_destinationApplicationSecurityGroups_inner_properties.h \
    $${PWD}/OAINetworkSecurityGroupResult.h \
    $${PWD}/OAINetworkSecurityRulesEvaluationResult.h \
    $${PWD}/OAINetworkWatcher.h \
    $${PWD}/OAINetworkWatcherListResult.h \
    $${PWD}/OAINetworkWatcherPropertiesFormat.h \
    $${PWD}/OAINetworkWatchers_UpdateTags_request.h \
    $${PWD}/OAINextHopParameters.h \
    $${PWD}/OAINextHopResult.h \
    $${PWD}/OAIPacketCapture.h \
    $${PWD}/OAIPacketCaptureFilter.h \
    $${PWD}/OAIPacketCaptureListResult.h \
    $${PWD}/OAIPacketCaptureParameters.h \
    $${PWD}/OAIPacketCaptureQueryStatusResult.h \
    $${PWD}/OAIPacketCaptureResult.h \
    $${PWD}/OAIPacketCaptureResultProperties.h \
    $${PWD}/OAIPacketCaptureStorageLocation.h \
    $${PWD}/OAIProtocolConfiguration.h \
    $${PWD}/OAIQueryTroubleshootingParameters.h \
    $${PWD}/OAIRetentionPolicyParameters.h \
    $${PWD}/OAISecurityGroupNetworkInterface.h \
    $${PWD}/OAISecurityGroupViewParameters.h \
    $${PWD}/OAISecurityGroupViewResult.h \
    $${PWD}/OAISecurityRuleAssociations.h \
    $${PWD}/OAISecurityRuleAssociations_effectiveSecurityRules_inner.h \
    $${PWD}/OAISubnetAssociation.h \
    $${PWD}/OAITopology.h \
    $${PWD}/OAITopologyAssociation.h \
    $${PWD}/OAITopologyParameters.h \
    $${PWD}/OAITopologyParameters_targetSubnet.h \
    $${PWD}/OAITopologyResource.h \
    $${PWD}/OAITrafficAnalyticsConfigurationProperties.h \
    $${PWD}/OAITrafficAnalyticsProperties.h \
    $${PWD}/OAITroubleshootingDetails.h \
    $${PWD}/OAITroubleshootingParameters.h \
    $${PWD}/OAITroubleshootingProperties.h \
    $${PWD}/OAITroubleshootingRecommendedActions.h \
    $${PWD}/OAITroubleshootingResult.h \
    $${PWD}/OAIVerificationIPFlowParameters.h \
    $${PWD}/OAIVerificationIPFlowResult.h \
# APIs
    $${PWD}/OAIConnectionMonitorsApi.h \
    $${PWD}/OAIFlowLogsApi.h \
    $${PWD}/OAINetworkWatchersApi.h \
    $${PWD}/OAIPacketCapturesApi.h \
    $${PWD}/OAITrafficAnalyticsApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAvailableProvidersList.cpp \
    $${PWD}/OAIAvailableProvidersListCity.cpp \
    $${PWD}/OAIAvailableProvidersListCountry.cpp \
    $${PWD}/OAIAvailableProvidersListParameters.cpp \
    $${PWD}/OAIAvailableProvidersListState.cpp \
    $${PWD}/OAIAzureReachabilityReport.cpp \
    $${PWD}/OAIAzureReachabilityReportItem.cpp \
    $${PWD}/OAIAzureReachabilityReportLatencyInfo.cpp \
    $${PWD}/OAIAzureReachabilityReportLocation.cpp \
    $${PWD}/OAIAzureReachabilityReportParameters.cpp \
    $${PWD}/OAIConnectionMonitor.cpp \
    $${PWD}/OAIConnectionMonitorDestination.cpp \
    $${PWD}/OAIConnectionMonitorEndpoint.cpp \
    $${PWD}/OAIConnectionMonitorEndpointFilter.cpp \
    $${PWD}/OAIConnectionMonitorEndpointFilterItem.cpp \
    $${PWD}/OAIConnectionMonitorHttpConfiguration.cpp \
    $${PWD}/OAIConnectionMonitorIcmpConfiguration.cpp \
    $${PWD}/OAIConnectionMonitorListResult.cpp \
    $${PWD}/OAIConnectionMonitorOutput.cpp \
    $${PWD}/OAIConnectionMonitorParameters.cpp \
    $${PWD}/OAIConnectionMonitorQueryResult.cpp \
    $${PWD}/OAIConnectionMonitorResult.cpp \
    $${PWD}/OAIConnectionMonitorResultProperties.cpp \
    $${PWD}/OAIConnectionMonitorSource.cpp \
    $${PWD}/OAIConnectionMonitorSuccessThreshold.cpp \
    $${PWD}/OAIConnectionMonitorTcpConfiguration.cpp \
    $${PWD}/OAIConnectionMonitorTestConfiguration.cpp \
    $${PWD}/OAIConnectionMonitorTestGroup.cpp \
    $${PWD}/OAIConnectionMonitorWorkspaceSettings.cpp \
    $${PWD}/OAIConnectionMonitors_List_default_response.cpp \
    $${PWD}/OAIConnectionMonitors_List_default_response_error.cpp \
    $${PWD}/OAIConnectionStateSnapshot.cpp \
    $${PWD}/OAIConnectionStateSnapshot_hops_inner.cpp \
    $${PWD}/OAIConnectionStateSnapshot_hops_inner_issues_inner.cpp \
    $${PWD}/OAIConnectivityDestination.cpp \
    $${PWD}/OAIConnectivityHop.cpp \
    $${PWD}/OAIConnectivityInformation.cpp \
    $${PWD}/OAIConnectivityIssue.cpp \
    $${PWD}/OAIConnectivityParameters.cpp \
    $${PWD}/OAIConnectivitySource.cpp \
    $${PWD}/OAIDirection.cpp \
    $${PWD}/OAIErrorResponse.cpp \
    $${PWD}/OAIEvaluatedNetworkSecurityGroup.cpp \
    $${PWD}/OAIFlowLog.cpp \
    $${PWD}/OAIFlowLogFormatParameters.cpp \
    $${PWD}/OAIFlowLogInformation.cpp \
    $${PWD}/OAIFlowLogListResult.cpp \
    $${PWD}/OAIFlowLogProperties.cpp \
    $${PWD}/OAIFlowLogPropertiesFormat.cpp \
    $${PWD}/OAIFlowLogStatusParameters.cpp \
    $${PWD}/OAIHTTPConfiguration.cpp \
    $${PWD}/OAIHTTPHeader.cpp \
    $${PWD}/OAIMatchedRule.cpp \
    $${PWD}/OAINetworkConfigurationDiagnosticParameters.cpp \
    $${PWD}/OAINetworkConfigurationDiagnosticProfile.cpp \
    $${PWD}/OAINetworkConfigurationDiagnosticResponse.cpp \
    $${PWD}/OAINetworkConfigurationDiagnosticResult.cpp \
    $${PWD}/OAINetworkInterfaceAssociation.cpp \
    $${PWD}/OAINetworkInterfaceAssociation_securityRules_inner.cpp \
    $${PWD}/OAINetworkInterfaceAssociation_securityRules_inner_properties.cpp \
    $${PWD}/OAINetworkInterfaceAssociation_securityRules_inner_properties_destinationApplicationSecurityGroups_inner.cpp \
    $${PWD}/OAINetworkInterfaceAssociation_securityRules_inner_properties_destinationApplicationSecurityGroups_inner_properties.cpp \
    $${PWD}/OAINetworkSecurityGroupResult.cpp \
    $${PWD}/OAINetworkSecurityRulesEvaluationResult.cpp \
    $${PWD}/OAINetworkWatcher.cpp \
    $${PWD}/OAINetworkWatcherListResult.cpp \
    $${PWD}/OAINetworkWatcherPropertiesFormat.cpp \
    $${PWD}/OAINetworkWatchers_UpdateTags_request.cpp \
    $${PWD}/OAINextHopParameters.cpp \
    $${PWD}/OAINextHopResult.cpp \
    $${PWD}/OAIPacketCapture.cpp \
    $${PWD}/OAIPacketCaptureFilter.cpp \
    $${PWD}/OAIPacketCaptureListResult.cpp \
    $${PWD}/OAIPacketCaptureParameters.cpp \
    $${PWD}/OAIPacketCaptureQueryStatusResult.cpp \
    $${PWD}/OAIPacketCaptureResult.cpp \
    $${PWD}/OAIPacketCaptureResultProperties.cpp \
    $${PWD}/OAIPacketCaptureStorageLocation.cpp \
    $${PWD}/OAIProtocolConfiguration.cpp \
    $${PWD}/OAIQueryTroubleshootingParameters.cpp \
    $${PWD}/OAIRetentionPolicyParameters.cpp \
    $${PWD}/OAISecurityGroupNetworkInterface.cpp \
    $${PWD}/OAISecurityGroupViewParameters.cpp \
    $${PWD}/OAISecurityGroupViewResult.cpp \
    $${PWD}/OAISecurityRuleAssociations.cpp \
    $${PWD}/OAISecurityRuleAssociations_effectiveSecurityRules_inner.cpp \
    $${PWD}/OAISubnetAssociation.cpp \
    $${PWD}/OAITopology.cpp \
    $${PWD}/OAITopologyAssociation.cpp \
    $${PWD}/OAITopologyParameters.cpp \
    $${PWD}/OAITopologyParameters_targetSubnet.cpp \
    $${PWD}/OAITopologyResource.cpp \
    $${PWD}/OAITrafficAnalyticsConfigurationProperties.cpp \
    $${PWD}/OAITrafficAnalyticsProperties.cpp \
    $${PWD}/OAITroubleshootingDetails.cpp \
    $${PWD}/OAITroubleshootingParameters.cpp \
    $${PWD}/OAITroubleshootingProperties.cpp \
    $${PWD}/OAITroubleshootingRecommendedActions.cpp \
    $${PWD}/OAITroubleshootingResult.cpp \
    $${PWD}/OAIVerificationIPFlowParameters.cpp \
    $${PWD}/OAIVerificationIPFlowResult.cpp \
# APIs
    $${PWD}/OAIConnectionMonitorsApi.cpp \
    $${PWD}/OAIFlowLogsApi.cpp \
    $${PWD}/OAINetworkWatchersApi.cpp \
    $${PWD}/OAIPacketCapturesApi.cpp \
    $${PWD}/OAITrafficAnalyticsApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
