# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class DeleteScalingPolicyInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, fleet_id: str=None):
        """DeleteScalingPolicyInput - a model defined in OpenAPI

        :param name: The name of this DeleteScalingPolicyInput.
        :param fleet_id: The fleet_id of this DeleteScalingPolicyInput.
        """
        self.openapi_types = {
            'name': str,
            'fleet_id': str
        }

        self.attribute_map = {
            'name': 'Name',
            'fleet_id': 'FleetId'
        }

        self._name = name
        self._fleet_id = fleet_id

    @classmethod
    def from_dict(cls, dikt: dict) -> 'DeleteScalingPolicyInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The DeleteScalingPolicyInput of this DeleteScalingPolicyInput.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this DeleteScalingPolicyInput.


        :return: The name of this DeleteScalingPolicyInput.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DeleteScalingPolicyInput.


        :param name: The name of this DeleteScalingPolicyInput.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def fleet_id(self):
        """Gets the fleet_id of this DeleteScalingPolicyInput.


        :return: The fleet_id of this DeleteScalingPolicyInput.
        :rtype: str
        """
        return self._fleet_id

    @fleet_id.setter
    def fleet_id(self, fleet_id):
        """Sets the fleet_id of this DeleteScalingPolicyInput.


        :param fleet_id: The fleet_id of this DeleteScalingPolicyInput.
        :type fleet_id: str
        """
        if fleet_id is None:
            raise ValueError("Invalid value for `fleet_id`, must not be `None`")

        self._fleet_id = fleet_id
