QT += network

HEADERS += \
# Models
    $${PWD}/OAIApiCollection.h \
    $${PWD}/OAIApiContract.h \
    $${PWD}/OAIApiContractProperties.h \
    $${PWD}/OAIApiContractProperties_allOf_authenticationSettings.h \
    $${PWD}/OAIApiContractProperties_allOf_authenticationSettings_oAuth2.h \
    $${PWD}/OAIApiContractProperties_allOf_subscriptionKeyParameterNames.h \
    $${PWD}/OAIApiContractUpdateProperties.h \
    $${PWD}/OAIApiCreateOrUpdateParameter.h \
    $${PWD}/OAIApiCreateOrUpdateProperties.h \
    $${PWD}/OAIApiDiagnosticLogger_CreateOrUpdate_200_response.h \
    $${PWD}/OAIApiDiagnosticLogger_ListByService_200_response.h \
    $${PWD}/OAIApiDiagnosticLogger_ListByService_200_response_value_inner.h \
    $${PWD}/OAIApiDiagnosticLogger_ListByService_200_response_value_inner_properties.h \
    $${PWD}/OAIApiDiagnosticLogger_ListByService_200_response_value_inner_properties_sampling.h \
    $${PWD}/OAIApiDiagnosticLogger_ListByService_200_response_value_inner_properties_sampling_properties.h \
    $${PWD}/OAIApiDiagnostic_Get_200_response.h \
    $${PWD}/OAIApiDiagnostic_ListByService_200_response.h \
    $${PWD}/OAIApiDiagnostic_ListByService_200_response_value_inner.h \
    $${PWD}/OAIApiDiagnostic_ListByService_200_response_value_inner_properties.h \
    $${PWD}/OAIApiEntityBaseContract.h \
    $${PWD}/OAIApiEntityBaseContract_subscriptionKeyParameterNames.h \
    $${PWD}/OAIApiExportResult.h \
    $${PWD}/OAIApiOperationPolicy_Get_200_response.h \
    $${PWD}/OAIApiOperationPolicy_ListByOperation_200_response.h \
    $${PWD}/OAIApiOperationPolicy_ListByOperation_200_response_value_inner.h \
    $${PWD}/OAIApiOperationPolicy_ListByOperation_200_response_value_inner_properties.h \
    $${PWD}/OAIApiProduct_ListByApis_200_response.h \
    $${PWD}/OAIApiProduct_ListByApis_200_response_value_inner.h \
    $${PWD}/OAIApiProduct_ListByApis_200_response_value_inner_properties.h \
    $${PWD}/OAIApiReleaseCollection.h \
    $${PWD}/OAIApiReleaseContract.h \
    $${PWD}/OAIApiReleaseContractProperties.h \
    $${PWD}/OAIApiRevisionCollection.h \
    $${PWD}/OAIApiRevisionContract.h \
    $${PWD}/OAIApiRevisionContractProperties.h \
    $${PWD}/OAIApiRevisionInfoContract.h \
    $${PWD}/OAIApiUpdateContract.h \
    $${PWD}/OAIApi_ListByService_default_response.h \
    $${PWD}/OAIApi_ListByService_default_response_details_inner.h \
    $${PWD}/OAIApi_ListByTags_200_response.h \
    $${PWD}/OAIApi_ListByTags_200_response_value_inner.h \
    $${PWD}/OAIApi_ListByTags_200_response_value_inner_properties.h \
    $${PWD}/OAIApi_ListByTags_200_response_value_inner_properties_api.h \
    $${PWD}/OAIApi_ListByTags_200_response_value_inner_properties_api_properties.h \
    $${PWD}/OAIApi_ListByTags_200_response_value_inner_properties_api_properties_apiVersionSet.h \
    $${PWD}/OAIApi_ListByTags_200_response_value_inner_properties_api_properties_apiVersionSet_properties.h \
    $${PWD}/OAIApi_ListByTags_200_response_value_inner_properties_operation.h \
    $${PWD}/OAIApi_ListByTags_200_response_value_inner_properties_operation_properties.h \
    $${PWD}/OAIApi_ListByTags_200_response_value_inner_properties_tag.h \
    $${PWD}/OAIApi_ListByTags_200_response_value_inner_properties_tag_properties.h \
    $${PWD}/OAIAuthenticationSettingsContract.h \
    $${PWD}/OAIIssueAttachmentCollection.h \
    $${PWD}/OAIIssueAttachmentContract.h \
    $${PWD}/OAIIssueAttachmentContractProperties.h \
    $${PWD}/OAIIssueCollection.h \
    $${PWD}/OAIIssueCommentCollection.h \
    $${PWD}/OAIIssueCommentContract.h \
    $${PWD}/OAIIssueCommentContractProperties.h \
    $${PWD}/OAIIssueContract.h \
    $${PWD}/OAIIssueContractProperties.h \
    $${PWD}/OAIOAuth2AuthenticationSettingsContract.h \
    $${PWD}/OAIOperationCollection.h \
    $${PWD}/OAIOperationContract.h \
    $${PWD}/OAIOperationContractProperties.h \
    $${PWD}/OAIOperationEntityBaseContract.h \
    $${PWD}/OAIOperationUpdateContract.h \
    $${PWD}/OAIOperationUpdateContractProperties.h \
    $${PWD}/OAIParameterContract.h \
    $${PWD}/OAIRepresentationContract.h \
    $${PWD}/OAIRequestContract.h \
    $${PWD}/OAIResponseContract.h \
    $${PWD}/OAISchemaCollection.h \
    $${PWD}/OAISchemaContract.h \
    $${PWD}/OAISchemaContractProperties.h \
    $${PWD}/OAISchemaDocumentProperties.h \
    $${PWD}/OAISubscriptionKeyParameterNamesContract.h \
# APIs
    $${PWD}/OAIApiDiagnosticLoggersApi.h \
    $${PWD}/OAIApiDiagnosticsApi.h \
    $${PWD}/OAIApiIssueAttachmentsApi.h \
    $${PWD}/OAIApiIssueAttachmentssApi.h \
    $${PWD}/OAIApiIssueCommentsApi.h \
    $${PWD}/OAIApiIssueCommentssApi.h \
    $${PWD}/OAIApiIssuesApi.h \
    $${PWD}/OAIApiOperationPoliciesApi.h \
    $${PWD}/OAIApiPolicyApi.h \
    $${PWD}/OAIApiProductApi.h \
    $${PWD}/OAIApiSchemaApi.h \
    $${PWD}/OAIApisApi.h \
    $${PWD}/OAIApisByTagsApi.h \
    $${PWD}/OAIOperationsApi.h \
    $${PWD}/OAIReleasesApi.h \
    $${PWD}/OAIRevisionsApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIApiCollection.cpp \
    $${PWD}/OAIApiContract.cpp \
    $${PWD}/OAIApiContractProperties.cpp \
    $${PWD}/OAIApiContractProperties_allOf_authenticationSettings.cpp \
    $${PWD}/OAIApiContractProperties_allOf_authenticationSettings_oAuth2.cpp \
    $${PWD}/OAIApiContractProperties_allOf_subscriptionKeyParameterNames.cpp \
    $${PWD}/OAIApiContractUpdateProperties.cpp \
    $${PWD}/OAIApiCreateOrUpdateParameter.cpp \
    $${PWD}/OAIApiCreateOrUpdateProperties.cpp \
    $${PWD}/OAIApiDiagnosticLogger_CreateOrUpdate_200_response.cpp \
    $${PWD}/OAIApiDiagnosticLogger_ListByService_200_response.cpp \
    $${PWD}/OAIApiDiagnosticLogger_ListByService_200_response_value_inner.cpp \
    $${PWD}/OAIApiDiagnosticLogger_ListByService_200_response_value_inner_properties.cpp \
    $${PWD}/OAIApiDiagnosticLogger_ListByService_200_response_value_inner_properties_sampling.cpp \
    $${PWD}/OAIApiDiagnosticLogger_ListByService_200_response_value_inner_properties_sampling_properties.cpp \
    $${PWD}/OAIApiDiagnostic_Get_200_response.cpp \
    $${PWD}/OAIApiDiagnostic_ListByService_200_response.cpp \
    $${PWD}/OAIApiDiagnostic_ListByService_200_response_value_inner.cpp \
    $${PWD}/OAIApiDiagnostic_ListByService_200_response_value_inner_properties.cpp \
    $${PWD}/OAIApiEntityBaseContract.cpp \
    $${PWD}/OAIApiEntityBaseContract_subscriptionKeyParameterNames.cpp \
    $${PWD}/OAIApiExportResult.cpp \
    $${PWD}/OAIApiOperationPolicy_Get_200_response.cpp \
    $${PWD}/OAIApiOperationPolicy_ListByOperation_200_response.cpp \
    $${PWD}/OAIApiOperationPolicy_ListByOperation_200_response_value_inner.cpp \
    $${PWD}/OAIApiOperationPolicy_ListByOperation_200_response_value_inner_properties.cpp \
    $${PWD}/OAIApiProduct_ListByApis_200_response.cpp \
    $${PWD}/OAIApiProduct_ListByApis_200_response_value_inner.cpp \
    $${PWD}/OAIApiProduct_ListByApis_200_response_value_inner_properties.cpp \
    $${PWD}/OAIApiReleaseCollection.cpp \
    $${PWD}/OAIApiReleaseContract.cpp \
    $${PWD}/OAIApiReleaseContractProperties.cpp \
    $${PWD}/OAIApiRevisionCollection.cpp \
    $${PWD}/OAIApiRevisionContract.cpp \
    $${PWD}/OAIApiRevisionContractProperties.cpp \
    $${PWD}/OAIApiRevisionInfoContract.cpp \
    $${PWD}/OAIApiUpdateContract.cpp \
    $${PWD}/OAIApi_ListByService_default_response.cpp \
    $${PWD}/OAIApi_ListByService_default_response_details_inner.cpp \
    $${PWD}/OAIApi_ListByTags_200_response.cpp \
    $${PWD}/OAIApi_ListByTags_200_response_value_inner.cpp \
    $${PWD}/OAIApi_ListByTags_200_response_value_inner_properties.cpp \
    $${PWD}/OAIApi_ListByTags_200_response_value_inner_properties_api.cpp \
    $${PWD}/OAIApi_ListByTags_200_response_value_inner_properties_api_properties.cpp \
    $${PWD}/OAIApi_ListByTags_200_response_value_inner_properties_api_properties_apiVersionSet.cpp \
    $${PWD}/OAIApi_ListByTags_200_response_value_inner_properties_api_properties_apiVersionSet_properties.cpp \
    $${PWD}/OAIApi_ListByTags_200_response_value_inner_properties_operation.cpp \
    $${PWD}/OAIApi_ListByTags_200_response_value_inner_properties_operation_properties.cpp \
    $${PWD}/OAIApi_ListByTags_200_response_value_inner_properties_tag.cpp \
    $${PWD}/OAIApi_ListByTags_200_response_value_inner_properties_tag_properties.cpp \
    $${PWD}/OAIAuthenticationSettingsContract.cpp \
    $${PWD}/OAIIssueAttachmentCollection.cpp \
    $${PWD}/OAIIssueAttachmentContract.cpp \
    $${PWD}/OAIIssueAttachmentContractProperties.cpp \
    $${PWD}/OAIIssueCollection.cpp \
    $${PWD}/OAIIssueCommentCollection.cpp \
    $${PWD}/OAIIssueCommentContract.cpp \
    $${PWD}/OAIIssueCommentContractProperties.cpp \
    $${PWD}/OAIIssueContract.cpp \
    $${PWD}/OAIIssueContractProperties.cpp \
    $${PWD}/OAIOAuth2AuthenticationSettingsContract.cpp \
    $${PWD}/OAIOperationCollection.cpp \
    $${PWD}/OAIOperationContract.cpp \
    $${PWD}/OAIOperationContractProperties.cpp \
    $${PWD}/OAIOperationEntityBaseContract.cpp \
    $${PWD}/OAIOperationUpdateContract.cpp \
    $${PWD}/OAIOperationUpdateContractProperties.cpp \
    $${PWD}/OAIParameterContract.cpp \
    $${PWD}/OAIRepresentationContract.cpp \
    $${PWD}/OAIRequestContract.cpp \
    $${PWD}/OAIResponseContract.cpp \
    $${PWD}/OAISchemaCollection.cpp \
    $${PWD}/OAISchemaContract.cpp \
    $${PWD}/OAISchemaContractProperties.cpp \
    $${PWD}/OAISchemaDocumentProperties.cpp \
    $${PWD}/OAISubscriptionKeyParameterNamesContract.cpp \
# APIs
    $${PWD}/OAIApiDiagnosticLoggersApi.cpp \
    $${PWD}/OAIApiDiagnosticsApi.cpp \
    $${PWD}/OAIApiIssueAttachmentsApi.cpp \
    $${PWD}/OAIApiIssueAttachmentssApi.cpp \
    $${PWD}/OAIApiIssueCommentsApi.cpp \
    $${PWD}/OAIApiIssueCommentssApi.cpp \
    $${PWD}/OAIApiIssuesApi.cpp \
    $${PWD}/OAIApiOperationPoliciesApi.cpp \
    $${PWD}/OAIApiPolicyApi.cpp \
    $${PWD}/OAIApiProductApi.cpp \
    $${PWD}/OAIApiSchemaApi.cpp \
    $${PWD}/OAIApisApi.cpp \
    $${PWD}/OAIApisByTagsApi.cpp \
    $${PWD}/OAIOperationsApi.cpp \
    $${PWD}/OAIReleasesApi.cpp \
    $${PWD}/OAIRevisionsApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
