openapi: 3.0.1
info:
  title: Lucidtech API
  version: 2023-03-23T15:40:40Z
  x-logo:
    url: https://assets-global.website-files.com/5d3e265ac89f6a3e64292efc/5d5595354de4fbdd8c554dba_default_webclip.png
  x-origin:
  - format: openapi
    url: https://raw.githubusercontent.com/LucidtechAI/cradl-docs/master/static/oas.yaml
    version: "3.0"
  x-providerName: webflow.com
servers:
- url: "https://api.lucidtech.ai/{basePath}"
  variables:
    basePath:
      default: v1
paths:
  /appClients:
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/appclients:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    post:
      security:
      - OAuth2:
        - api.lucidtech.ai/appclients:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /appClients/{appClientId}:
    delete:
      security: []
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    patch:
      security:
      - OAuth2:
        - api.lucidtech.ai/appclients:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /assets:
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/assets:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    post:
      security:
      - OAuth2:
        - api.lucidtech.ai/assets:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /assets/{assetId}:
    delete:
      security:
      - OAuth2:
        - api.lucidtech.ai/assets:read
      x-accepts:
      - application/json
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/assets:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    patch:
      security:
      - OAuth2:
        - api.lucidtech.ai/assets:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /datasets:
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/datasets:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    post:
      security:
      - OAuth2:
        - api.lucidtech.ai/datasets:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /datasets/{datasetId}:
    delete:
      security:
      - OAuth2:
        - api.lucidtech.ai/datasets:read
      x-accepts:
      - application/json
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/datasets:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    patch:
      security:
      - OAuth2:
        - api.lucidtech.ai/datasets:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /deploymentEnvironments:
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/secrets:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
  /deploymentEnvironments/{deploymentEnvironmentId}:
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/organizations:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
  /documents:
    delete:
      security:
      - OAuth2:
        - api.lucidtech.ai/documents:write
      x-accepts:
      - application/json
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/documents:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    post:
      security:
      - OAuth2:
        - api.lucidtech.ai/documents:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /documents/{documentId}:
    delete:
      security:
      - OAuth2:
        - api.lucidtech.ai/documents:read
      x-accepts:
      - application/json
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/documents:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    patch:
      security:
      - OAuth2:
        - api.lucidtech.ai/documents:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /logs:
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/logs:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
  /logs/{logId}:
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/logs:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
  /models:
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/models:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    post:
      security:
      - OAuth2:
        - api.lucidtech.ai/models:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /models/{modelId}:
    delete:
      security:
      - OAuth2:
        - api.lucidtech.ai/models:read
      x-accepts:
      - application/json
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/models:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    patch:
      security:
      - OAuth2:
        - api.lucidtech.ai/models:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /models/{modelId}/dataBundles:
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/databundles:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    post:
      security:
      - OAuth2:
        - api.lucidtech.ai/databundles:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /models/{modelId}/dataBundles/{dataBundleId}:
    delete:
      security: []
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    patch:
      security:
      - OAuth2:
        - api.lucidtech.ai/databundles:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /models/{modelId}/trainings:
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/workflows.executions:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    post:
      security:
      - OAuth2:
        - api.lucidtech.ai/workflows.executions:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /models/{modelId}/trainings/{trainingId}:
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    patch:
      security:
      - OAuth2:
        - api.lucidtech.ai/predictions:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /organizations:
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/organizations:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    post:
      security:
      - OAuth2:
        - api.lucidtech.ai/organizations:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /organizations/{organizationId}:
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/organizations:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    patch:
      security:
      - OAuth2:
        - api.lucidtech.ai/organizations:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /paymentMethods:
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/paymentmethods:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    post:
      security:
      - OAuth2:
        - api.lucidtech.ai/paymentmethods:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /paymentMethods/{paymentMethodId}:
    delete:
      security:
      - OAuth2:
        - api.lucidtech.ai/paymentmethods:read
      x-accepts:
      - application/json
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/paymentmethods:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    patch:
      security:
      - OAuth2:
        - api.lucidtech.ai/paymentmethods:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /plans:
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/plans:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
  /plans/{planId}:
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/plans:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
  /predictions:
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/predictions:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    post:
      security:
      - OAuth2:
        - api.lucidtech.ai/predictions:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /profiles/{profileId}:
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/assets:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    patch:
      security:
      - OAuth2:
        - api.lucidtech.ai/assets:write
      x-accepts:
      - application/json
  /secrets:
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/secrets:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    post:
      security:
      - OAuth2:
        - api.lucidtech.ai/secrets:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /secrets/{secretId}:
    delete:
      security: []
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    patch:
      security:
      - OAuth2:
        - api.lucidtech.ai/secrets:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /transitions:
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/transitions:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    post:
      security:
      - OAuth2:
        - api.lucidtech.ai/transitions:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /transitions/{transitionId}:
    delete:
      security:
      - OAuth2:
        - api.lucidtech.ai/transitions:read
      x-accepts:
      - application/json
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/transitions:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    patch:
      security:
      - OAuth2:
        - api.lucidtech.ai/transitions:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /transitions/{transitionId}/executions:
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/transitions.executions:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    post:
      security:
      - OAuth2:
        - api.lucidtech.ai/transitions.executions:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /transitions/{transitionId}/executions/{executionId}:
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/transitions.executions:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    patch:
      security:
      - OAuth2:
        - api.lucidtech.ai/transitions.executions:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /transitions/{transitionId}/executions/{executionId}/heartbeats:
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    post:
      security:
      - OAuth2:
        - api.lucidtech.ai/transitions.executions.heartbeats:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /users:
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/users:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    post:
      security:
      - OAuth2:
        - api.lucidtech.ai/users:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /users/{userId}:
    delete:
      security:
      - OAuth2:
        - api.lucidtech.ai/users:read
      x-accepts:
      - application/json
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/users:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    patch:
      security:
      - OAuth2:
        - api.lucidtech.ai/users:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /workflows:
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/workflows:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    post:
      security:
      - OAuth2:
        - api.lucidtech.ai/workflows:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /workflows/{workflowId}:
    delete:
      security:
      - OAuth2:
        - api.lucidtech.ai/workflows:read
      x-accepts:
      - application/json
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/workflows:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    patch:
      security:
      - OAuth2:
        - api.lucidtech.ai/workflows:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /workflows/{workflowId}/executions:
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/workflows.executions:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    post:
      security:
      - OAuth2:
        - api.lucidtech.ai/workflows.executions:write
      x-content-type: application/json
      x-accepts:
      - application/json
  /workflows/{workflowId}/executions/{executionId}:
    delete:
      security:
      - OAuth2:
        - api.lucidtech.ai/workflows.executions:read
      x-accepts:
      - application/json
    get:
      security:
      - OAuth2:
        - api.lucidtech.ai/workflows.executions:read
      x-accepts:
      - application/json
    options:
      x-content-type: application/json
      x-accepts:
      - application/json
    patch:
      security:
      - OAuth2:
        - api.lucidtech.ai/workflows.executions:write
      x-content-type: application/json
      x-accepts:
      - application/json
components:
  securitySchemes:
    OAuth2:
      flows:
        clientCredentials:
          scopes:
            api.lucidtech.ai/appclients:read: Read permissions
            api.lucidtech.ai/appclients:write: Write permissions
            api.lucidtech.ai/assets:read: Read permissions
            api.lucidtech.ai/assets:write: Write permissions
            api.lucidtech.ai/databundles:read: Read permissions
            api.lucidtech.ai/databundles:write: Write permissions
            api.lucidtech.ai/datasets:read: Read permissions
            api.lucidtech.ai/datasets:write: Write permissions
            api.lucidtech.ai/deploymentenvironments:read: Read permissions
            api.lucidtech.ai/documents:read: Read permissions
            api.lucidtech.ai/documents:write: Write permissions
            api.lucidtech.ai/logs:read: Read permissions
            api.lucidtech.ai/models:read: Read permissions
            api.lucidtech.ai/models:write: Write permissions
            api.lucidtech.ai/organizations:read: Read permissions
            api.lucidtech.ai/organizations:write: Write permissions
            api.lucidtech.ai/paymentmethods:read: Read permissions
            api.lucidtech.ai/paymentmethods:write: Write permissions
            api.lucidtech.ai/plans:read: Read permissions
            api.lucidtech.ai/predictions:read: Read permissions
            api.lucidtech.ai/predictions:write: Write permissions
            api.lucidtech.ai/profiles:read: Read permissions
            api.lucidtech.ai/profiles:write: Write permissions
            api.lucidtech.ai/secrets:read: Read permissions
            api.lucidtech.ai/secrets:write: Write permissions
            api.lucidtech.ai/trainings:read: Read permissions
            api.lucidtech.ai/trainings:write: Write permissions
            api.lucidtech.ai/transitions.executions.heartbeats:write: Write permissions
            api.lucidtech.ai/transitions.executions:read: Read permissions
            api.lucidtech.ai/transitions.executions:write: Write permissions
            api.lucidtech.ai/transitions:read: Read permissions
            api.lucidtech.ai/transitions:write: Write permissions
            api.lucidtech.ai/users:read: Read permissions
            api.lucidtech.ai/users:write: Write permissions
            api.lucidtech.ai/workflows.executions:read: Read permissions
            api.lucidtech.ai/workflows.executions:write: Write permissions
            api.lucidtech.ai/workflows:read: Read permissions
            api.lucidtech.ai/workflows:write: Write permissions
          tokenUrl: https://auth.lucidtech.ai/oauth2/token
      type: oauth2

