# coding: utf-8

# import models into model package
from openapi_server.models.academic_certificate_schema import AcademicCertificateSchema
from openapi_server.models.academic_certificate_schema_certificate_data import AcademicCertificateSchemaCertificateData
from openapi_server.models.academic_certificate_schema_certificate_data_examination import AcademicCertificateSchemaCertificateDataExamination
from openapi_server.models.academic_certificate_schema_certificate_data_performance import AcademicCertificateSchemaCertificateDataPerformance
from openapi_server.models.academic_certificate_schema_certificate_data_performance_subjects_inner import AcademicCertificateSchemaCertificateDataPerformanceSubjectsInner
from openapi_server.models.academic_certificate_schema_certificate_data_school import AcademicCertificateSchemaCertificateDataSchool
from openapi_server.models.academic_certificate_schema_issued_by import AcademicCertificateSchemaIssuedBy
from openapi_server.models.academic_certificate_schema_issued_by_organization import AcademicCertificateSchemaIssuedByOrganization
from openapi_server.models.academic_certificate_schema_issued_by_organization_address import AcademicCertificateSchemaIssuedByOrganizationAddress
from openapi_server.models.academic_certificate_schema_issued_to import AcademicCertificateSchemaIssuedTo
from openapi_server.models.academic_certificate_schema_issued_to_person import AcademicCertificateSchemaIssuedToPerson
from openapi_server.models.academic_certificate_schema_issued_to_person_address import AcademicCertificateSchemaIssuedToPersonAddress
from openapi_server.models.academic_certificate_schema_issued_to_person_photo import AcademicCertificateSchemaIssuedToPersonPhoto
from openapi_server.models.consent_artifact_schema import ConsentArtifactSchema
from openapi_server.models.consent_artifact_schema_consent import ConsentArtifactSchemaConsent
from openapi_server.models.consent_artifact_schema_consent_data import ConsentArtifactSchemaConsentData
from openapi_server.models.consent_artifact_schema_consent_permission import ConsentArtifactSchemaConsentPermission
from openapi_server.models.consent_artifact_schema_consent_permission_date_range import ConsentArtifactSchemaConsentPermissionDateRange
from openapi_server.models.consent_artifact_schema_consent_permission_frequency import ConsentArtifactSchemaConsentPermissionFrequency
from openapi_server.models.consent_artifact_schema_consent_purpose import ConsentArtifactSchemaConsentPurpose
from openapi_server.models.consent_artifact_schema_consent_user import ConsentArtifactSchemaConsentUser
from openapi_server.models.consent_artifact_schema_signature import ConsentArtifactSchemaSignature
from openapi_server.models.cripc400_response import Cripc400Response
from openapi_server.models.cripc401_response import Cripc401Response
from openapi_server.models.cripc404_response import Cripc404Response
from openapi_server.models.cripc500_response import Cripc500Response
from openapi_server.models.cripc502_response import Cripc502Response
from openapi_server.models.cripc503_response import Cripc503Response
from openapi_server.models.cripc504_response import Cripc504Response
from openapi_server.models.cripc_request import CripcRequest
from openapi_server.models.cripc_request_certificate_parameters import CripcRequestCertificateParameters
