/**
 * Legal Entity Management API
 * The Legal Entity Management API enables you to manage legal entities that contain information required for verification.  ## Authentication Your Adyen contact will provide your API credential and an API key. To connect to the API, add an `X-API-Key` header with the API key as the value. For example:  ``` curl -H \"X-API-Key: YOUR_API_KEY\" \\ -H \"Content-Type: application/json\" \\ ... ``` Alternatively, you can use the username and password of your API credential to connect to the API using basic authentication. For example:  ``` curl -U \"ws_123456@Scope.Company_YOUR_COMPANY_ACCOUNT\":\"YourWsPassword\" \\ -H \"Content-Type: application/json\" \\ ... ``` ## Versioning The Legal Entity Management API supports [versioning](https://docs.adyen.com/development-resources/versioning) using a version suffix in the endpoint URL. This suffix has the following format: \"vXX\", where XX is the version number.  For example: ``` https://kyc-test.adyen.com/lem/v2/legalEntities ``` >If you are using hosted onboarding and just beginning your integration, use v3 for your API requests. Otherwise, use v2.  ## Going live When going live, your Adyen contact will provide your API credential for the live environment. You can then use the API key or the username and password to send requests to `https://kyc-live.adyen.com/lem/v2`.  
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BankAccountInfo model module.
 * @module model/BankAccountInfo
 * @version 2
 */
class BankAccountInfo {
    /**
     * Constructs a new <code>BankAccountInfo</code>.
     * @alias module:model/BankAccountInfo
     * @param currencyCode {String} The account's three-character [ISO currency code](https://docs.adyen.com/development-resources/currency-codes). For example, **EUR**.
     */
    constructor(currencyCode) { 
        
        BankAccountInfo.initialize(this, currencyCode);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, currencyCode) { 
        obj['currencyCode'] = currencyCode;
    }

    /**
     * Constructs a <code>BankAccountInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BankAccountInfo} obj Optional instance to populate.
     * @return {module:model/BankAccountInfo} The populated <code>BankAccountInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BankAccountInfo();

            if (data.hasOwnProperty('accountNumber')) {
                obj['accountNumber'] = ApiClient.convertToType(data['accountNumber'], 'String');
            }
            if (data.hasOwnProperty('accountType')) {
                obj['accountType'] = ApiClient.convertToType(data['accountType'], 'String');
            }
            if (data.hasOwnProperty('bankBicSwift')) {
                obj['bankBicSwift'] = ApiClient.convertToType(data['bankBicSwift'], 'String');
            }
            if (data.hasOwnProperty('bankCity')) {
                obj['bankCity'] = ApiClient.convertToType(data['bankCity'], 'String');
            }
            if (data.hasOwnProperty('bankCode')) {
                obj['bankCode'] = ApiClient.convertToType(data['bankCode'], 'String');
            }
            if (data.hasOwnProperty('bankName')) {
                obj['bankName'] = ApiClient.convertToType(data['bankName'], 'String');
            }
            if (data.hasOwnProperty('branchCode')) {
                obj['branchCode'] = ApiClient.convertToType(data['branchCode'], 'String');
            }
            if (data.hasOwnProperty('checkCode')) {
                obj['checkCode'] = ApiClient.convertToType(data['checkCode'], 'String');
            }
            if (data.hasOwnProperty('countryCode')) {
                obj['countryCode'] = ApiClient.convertToType(data['countryCode'], 'String');
            }
            if (data.hasOwnProperty('currencyCode')) {
                obj['currencyCode'] = ApiClient.convertToType(data['currencyCode'], 'String');
            }
            if (data.hasOwnProperty('iban')) {
                obj['iban'] = ApiClient.convertToType(data['iban'], 'String');
            }
            if (data.hasOwnProperty('trustedSource')) {
                obj['trustedSource'] = ApiClient.convertToType(data['trustedSource'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BankAccountInfo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BankAccountInfo</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BankAccountInfo.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['accountNumber'] && !(typeof data['accountNumber'] === 'string' || data['accountNumber'] instanceof String)) {
            throw new Error("Expected the field `accountNumber` to be a primitive type in the JSON string but got " + data['accountNumber']);
        }
        // ensure the json data is a string
        if (data['accountType'] && !(typeof data['accountType'] === 'string' || data['accountType'] instanceof String)) {
            throw new Error("Expected the field `accountType` to be a primitive type in the JSON string but got " + data['accountType']);
        }
        // ensure the json data is a string
        if (data['bankBicSwift'] && !(typeof data['bankBicSwift'] === 'string' || data['bankBicSwift'] instanceof String)) {
            throw new Error("Expected the field `bankBicSwift` to be a primitive type in the JSON string but got " + data['bankBicSwift']);
        }
        // ensure the json data is a string
        if (data['bankCity'] && !(typeof data['bankCity'] === 'string' || data['bankCity'] instanceof String)) {
            throw new Error("Expected the field `bankCity` to be a primitive type in the JSON string but got " + data['bankCity']);
        }
        // ensure the json data is a string
        if (data['bankCode'] && !(typeof data['bankCode'] === 'string' || data['bankCode'] instanceof String)) {
            throw new Error("Expected the field `bankCode` to be a primitive type in the JSON string but got " + data['bankCode']);
        }
        // ensure the json data is a string
        if (data['bankName'] && !(typeof data['bankName'] === 'string' || data['bankName'] instanceof String)) {
            throw new Error("Expected the field `bankName` to be a primitive type in the JSON string but got " + data['bankName']);
        }
        // ensure the json data is a string
        if (data['branchCode'] && !(typeof data['branchCode'] === 'string' || data['branchCode'] instanceof String)) {
            throw new Error("Expected the field `branchCode` to be a primitive type in the JSON string but got " + data['branchCode']);
        }
        // ensure the json data is a string
        if (data['checkCode'] && !(typeof data['checkCode'] === 'string' || data['checkCode'] instanceof String)) {
            throw new Error("Expected the field `checkCode` to be a primitive type in the JSON string but got " + data['checkCode']);
        }
        // ensure the json data is a string
        if (data['countryCode'] && !(typeof data['countryCode'] === 'string' || data['countryCode'] instanceof String)) {
            throw new Error("Expected the field `countryCode` to be a primitive type in the JSON string but got " + data['countryCode']);
        }
        // ensure the json data is a string
        if (data['currencyCode'] && !(typeof data['currencyCode'] === 'string' || data['currencyCode'] instanceof String)) {
            throw new Error("Expected the field `currencyCode` to be a primitive type in the JSON string but got " + data['currencyCode']);
        }
        // ensure the json data is a string
        if (data['iban'] && !(typeof data['iban'] === 'string' || data['iban'] instanceof String)) {
            throw new Error("Expected the field `iban` to be a primitive type in the JSON string but got " + data['iban']);
        }

        return true;
    }


}

BankAccountInfo.RequiredProperties = ["currencyCode"];

/**
 * The bank account number (without separators).   When this is provided, the `branchCode` is also required.
 * @member {String} accountNumber
 */
BankAccountInfo.prototype['accountNumber'] = undefined;

/**
 * The type of bank account.
 * @member {String} accountType
 */
BankAccountInfo.prototype['accountType'] = undefined;

/**
 * The bank's BIC or SWIFT code.
 * @member {String} bankBicSwift
 */
BankAccountInfo.prototype['bankBicSwift'] = undefined;

/**
 * The city where the bank is located.
 * @member {String} bankCity
 */
BankAccountInfo.prototype['bankCity'] = undefined;

/**
 * The bank code of the banking institution with which the bank account is registered.
 * @member {String} bankCode
 */
BankAccountInfo.prototype['bankCode'] = undefined;

/**
 * The name of the banking institution where the bank account is held.
 * @member {String} bankName
 */
BankAccountInfo.prototype['bankName'] = undefined;

/**
 * The branch code of the branch under which the bank account is registered.  Required when you provide an `accountNumber`.   In the following countries, this value corresponds to:   * United States: routing number * United Kingdom: sort code * Germany: Bankleitzahl
 * @member {String} branchCode
 */
BankAccountInfo.prototype['branchCode'] = undefined;

/**
 * The check code of the bank account.
 * @member {String} checkCode
 */
BankAccountInfo.prototype['checkCode'] = undefined;

/**
 * The two-character [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country code where the bank account is registered. For example, **NL**.
 * @member {String} countryCode
 */
BankAccountInfo.prototype['countryCode'] = undefined;

/**
 * The account's three-character [ISO currency code](https://docs.adyen.com/development-resources/currency-codes). For example, **EUR**.
 * @member {String} currencyCode
 */
BankAccountInfo.prototype['currencyCode'] = undefined;

/**
 * The international bank account number as defined in the [ISO-13616](https://www.iso.org/standard/81090.html) standard.
 * @member {String} iban
 */
BankAccountInfo.prototype['iban'] = undefined;

/**
 * Identifies if the bank account was created through [instant bank verification](https://docs.adyen.com/release-notes/platforms-and-financial-products#releaseNote=2023-05-08-hosted-onboarding).
 * @member {Boolean} trustedSource
 */
BankAccountInfo.prototype['trustedSource'] = undefined;






export default BankAccountInfo;

