openapi: 3.0.0
info:
  contact:
    email: integrations@reverb.com
    name: Reverb API
    url: https://www.reverb-api.com
  description: reverb
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://reverb.com/page/terms
  title: reverb
  version: "3.0"
  x-apisguru-categories:
  - ecommerce
  x-logo:
    url: https://d1g5417jjjo7sf.cloudfront.net/assets/top-level/reverb-logo-d2c75af0b020521f0bc5e90c883a13b5.svg
  x-origin:
  - format: openapi
    url: https://s3.amazonaws.com/swagger.reverb.com/swagger.json
    version: "3.0"
  x-providerName: reverb.com
servers:
- url: https://api.reverb.com/api
paths:
  /articles:
    get:
      tags:
      - articles
      x-accepts:
      - application/json
  /articles/categories:
    get:
      description: List of all article categories
      summary: List of all article categories
      tags:
      - articles
      x-accepts:
      - application/json
  /categories:
    get:
      description: List of supported product categories
      summary: List of supported product categories
      tags:
      - categories
      x-accepts:
      - application/json
  /categories/flat:
    get:
      tags:
      - categories
      x-accepts:
      - application/json
  /categories/taxonomy:
    get:
      description: Full taxonomy tree of categories including middle categories
      summary: Full taxonomy tree of categories including middle categories
      tags:
      - categories
      x-accepts:
      - application/json
  /categories/{product_type}/{category}:
    get:
      description: Get subcategory details
      summary: Get subcategory details
      tags:
      - categories
      x-accepts:
      - application/json
  /categories/{uuid}:
    get:
      description: Get category details
      summary: Get category details
      tags:
      - categories
      x-accepts:
      - application/json
  /comparison_shopping_pages:
    get:
      description: Returns a set of comparison shopping pages based on the current
        params
      summary: Returns a set of comparison shopping pages based on the current params
      tags:
      - comparison_shopping_pages
      x-accepts:
      - application/json
  /comparison_shopping_pages/find:
    get:
      description: Show comparison shopping page
      summary: Show comparison shopping page
      tags:
      - comparison_shopping_pages
      x-accepts:
      - application/json
  /comparison_shopping_pages/{id}:
    get:
      tags:
      - comparison_shopping_pages
      x-accepts:
      - application/json
  /comparison_shopping_pages/{id}/listings:
    get:
      description: Return new or used listings for a comparison shopping page
      summary: Return new or used listings for a comparison shopping page
      tags:
      - comparison_shopping_pages
      x-accepts:
      - application/json
  /comparison_shopping_pages/{id}/reviews:
    get:
      description: View reviews of a comparison shopping page
      summary: View reviews of a comparison shopping page
      tags:
      - comparison_shopping_pages
      x-accepts:
      - application/json
  /conversations/{conversation_id}/offer:
    post:
      description: Make an offer to the other participant in the conversation
      security:
      - oauth2:
        - write_offers
      summary: Make an offer to the other participant in the conversation
      tags:
      - conversations
      x-content-type: application/json
      x-accepts:
      - application/json
  /conversations/{id}/offer:
    post:
      description: Make an offer to the other participant in the conversation
      security:
      - oauth2:
        - write_offers
      summary: Make an offer to the other participant in the conversation
      tags:
      - conversations
      x-content-type: application/json
      x-accepts:
      - application/json
  /countries:
    get:
      description: Retrieve a list of country codes with corresponding subregions
      summary: Retrieve a list of country codes with corresponding subregions
      tags:
      - countries
      x-accepts:
      - application/json
  /csps:
    get:
      description: Returns a set of comparison shopping pages based on the current
        params
      summary: Returns a set of comparison shopping pages based on the current params
      tags:
      - csps
      x-accepts:
      - application/json
  /csps/categories:
    get:
      tags:
      - csps
      x-accepts:
      - application/json
  /csps/find:
    get:
      description: Show comparison shopping page
      summary: Show comparison shopping page
      tags:
      - csps
      x-accepts:
      - application/json
  /csps/{id}:
    get:
      tags:
      - csps
      x-accepts:
      - application/json
  /curated_sets/{slug}:
    get:
      tags:
      - curated_sets
      x-accepts:
      - application/json
  /currencies/display:
    get:
      description: List of supported display currencies for browsing listings
      summary: List of supported display currencies for browsing listings
      tags:
      - currencies
      x-accepts:
      - application/json
  /currencies/listing:
    get:
      description: List of supported listing currencies for shops
      summary: List of supported listing currencies for shops
      tags:
      - currencies
      x-accepts:
      - application/json
  /feedback/{feedback_id}:
    get:
      description: Feedback details
      summary: Feedback details
      tags:
      - feedback
      x-accepts:
      - application/json
  /handpicked/{slug}:
    get:
      description: Get results from a handpicked collection
      summary: Get results from a handpicked collection
      tags:
      - handpicked
      x-accepts:
      - application/json
  /listing_conditions:
    get:
      description: List of supported product conditions
      summary: List of supported product conditions
      tags:
      - listing_conditions
      x-accepts:
      - application/json
  /listings:
    get:
      description: Default search of listings includes only used & handmade. Add a
        filter to view all listings or use the /listings/all endpoint.
      summary: Default search of listings includes only used & handmade. Add a filter
        to view all listings or use the /listings/all endpoint.
      tags:
      - listings
      x-accepts:
      - application/json
    post:
      description: Create a listing
      security:
      - oauth2:
        - write_listings
        - write_listings_for_others
      summary: Create a listing
      tags:
      - listings
      x-content-type: application/json
      x-accepts:
      - application/json
  /listings/all:
    get:
      description: "All listings including used, handmade, and brand new"
      summary: "All listings including used, handmade, and brand new"
      tags:
      - listings
      x-accepts:
      - application/json
  /listings/facets/seller_location:
    get:
      description: Individual facets
      summary: Individual facets
      tags:
      - listings
      x-accepts:
      - application/json
  /listings/{id}/negotiation:
    get:
      description: Returns the latest negotiation for the requesting user given a
        listing id
      security:
      - oauth2:
        - read_offers
      summary: Returns the latest negotiation for the requesting user given a listing
        id
      tags:
      - listings
      x-accepts:
      - application/json
  /listings/{id}/offer:
    post:
      description: Make an offer to the seller of a listing
      security:
      - oauth2:
        - write_offers
      summary: Make an offer to the seller of a listing
      tags:
      - listings
      x-content-type: application/json
      x-accepts:
      - application/json
  /listings/{listing_id}/bump:
    get:
      description: View available bump tiers and stats for a listing
      security:
      - oauth2:
        - read_listings
      summary: View available bump tiers and stats for a listing
      tags:
      - listings
      x-accepts:
      - application/json
  /listings/{listing_id}/bump/{budget_type}:
    post:
      description: Bump a listing
      security:
      - oauth2:
        - write_listings
      summary: Bump a listing
      tags:
      - listings
      x-accepts:
      - application/json
  /listings/{listing_id}/conversations:
    post:
      description: Start a conversation with a seller
      security:
      - oauth2:
        - write_messages
      summary: Start a conversation with a seller
      tags:
      - listings
      x-content-type: application/json
      x-accepts:
      - application/json
  /listings/{listing_id}/images:
    get:
      description: View the images associated with a particular listing
      security:
      - oauth2:
        - read_listings
      summary: View the images associated with a particular listing
      tags:
      - listings
      x-accepts:
      - application/json
  /listings/{listing_id}/images/{image_id}:
    delete:
      description: Delete an image from a listing
      security:
      - oauth2:
        - write_listings
      summary: Delete an image from a listing
      tags:
      - listings
      x-accepts:
      - application/json
  /listings/{listing_id}/sales:
    get:
      description: See all sales that include a listing.
      summary: See all sales that include a listing.
      tags:
      - listings
      x-accepts:
      - application/json
  /listings/{slug}:
    delete:
      description: Delete a draft listing. Cannot be used on non-drafts.
      security:
      - oauth2:
        - write_listings
      summary: Delete a draft listing. Cannot be used on non-drafts.
      tags:
      - listings
      x-accepts:
      - application/json
    get:
      description: Listing details
      summary: Listing details
      tags:
      - listings
      x-accepts:
      - application/json
    put:
      description: Update a listing
      security:
      - oauth2:
        - write_listings
      summary: Update a listing
      tags:
      - listings
      x-content-type: application/json
      x-accepts:
      - application/json
  /listings/{slug}/edit:
    get:
      description: Edit listing.
      security:
      - oauth2:
        - write_listings
      summary: Edit listing.
      tags:
      - listings
      x-accepts:
      - application/json
  /listings/{slug}/flag:
    post:
      description: Flag a listing for inappropriate content or fraud
      summary: Flag a listing for inappropriate content or fraud
      tags:
      - listings
      x-content-type: application/json
      x-accepts:
      - application/json
  /listings/{slug}/reviews:
    get:
      description: View reviews of a listing
      summary: View reviews of a listing
      tags:
      - listings
      x-accepts:
      - application/json
    post:
      description: Create a review for a listing
      security:
      - oauth2:
        - write_reviews
      summary: Create a review for a listing
      tags:
      - listings
      x-accepts:
      - application/json
  /listings/{slug}/similar_listings:
    get:
      description: Listing details
      summary: Listing details
      tags:
      - listings
      x-accepts:
      - application/json
  /my/account:
    get:
      description: Get account details
      security:
      - oauth2:
        - read_profile
      summary: Get account details
      tags:
      - my
      x-accepts:
      - application/json
    put:
      description: Update account details
      security:
      - oauth2:
        - write_profile
      summary: Update account details
      tags:
      - my
      x-content-type: application/json
      x-accepts:
      - application/json
  /my/addresses:
    get:
      description: See all addresses in your address book
      security:
      - oauth2:
        - read_profile
      summary: See all addresses in your address book
      tags:
      - my
      x-accepts:
      - application/json
    post:
      description: Create a new address in your address book
      security:
      - oauth2:
        - write_profile
      summary: Create a new address in your address book
      tags:
      - my
      x-accepts:
      - application/json
  /my/addresses/{address_id}:
    delete:
      description: Delete an existing address in your address book
      security:
      - oauth2:
        - write_profile
      summary: Delete an existing address in your address book
      tags:
      - my
      x-accepts:
      - application/json
    put:
      description: Update an existing address in your address book
      security:
      - oauth2:
        - write_profile
      summary: Update an existing address in your address book
      tags:
      - my
      x-accepts:
      - application/json
  /my/conversations:
    get:
      description: Get a list of your conversations
      security:
      - oauth2:
        - read_messages
      summary: Get a list of your conversations
      tags:
      - my
      x-accepts:
      - application/json
    post:
      description: Start a conversation
      security:
      - oauth2:
        - write_messages
      summary: Start a conversation
      tags:
      - my
      x-content-type: application/json
      x-accepts:
      - application/json
  /my/conversations/{conversation_id}/messages:
    post:
      description: Send a message
      security:
      - oauth2:
        - write_messages
      summary: Send a message
      tags:
      - my
      x-content-type: application/json
      x-accepts:
      - application/json
  /my/conversations/{id}:
    get:
      description: Display conversation details with messages in natural time order
        (oldest to newest)
      security:
      - oauth2:
        - read_messages
      summary: Display conversation details with messages in natural time order (oldest
        to newest)
      tags:
      - my
      x-accepts:
      - application/json
    put:
      description: Mark a conversation read/unread
      security:
      - oauth2:
        - write_messages
      summary: Mark a conversation read/unread
      tags:
      - my
      x-content-type: application/json
      x-accepts:
      - application/json
  /my/counts:
    get:
      description: Get your actionable status counts
      security:
      - oauth2:
        - read_profile
      summary: Get your actionable status counts
      tags:
      - my
      x-accepts:
      - application/json
  /my/curated_set/product/{product_id}:
    delete:
      tags:
      - my
      x-accepts:
      - application/json
    post:
      tags:
      - my
      x-accepts:
      - application/json
  /my/feed:
    get:
      description: Get listings from your feed
      security:
      - oauth2:
        - read_lists
      summary: Get listings from your feed
      tags:
      - my
      x-accepts:
      - application/json
  /my/feed/customize:
    get:
      description: get your feed customization options
      security:
      - oauth2:
        - read_lists
      summary: get your feed customization options
      tags:
      - my
      x-accepts:
      - application/json
  /my/feed/grid:
    get:
      description: get your feed
      security:
      - oauth2:
        - read_lists
      summary: get your feed
      tags:
      - my
      x-accepts:
      - application/json
  /my/feedback/received:
    get:
      description: List of received feedback
      security:
      - oauth2:
        - read_feedback
      summary: List of received feedback
      tags:
      - my
      x-accepts:
      - application/json
  /my/feedback/sent:
    get:
      description: List of sent feedback
      security:
      - oauth2:
        - read_feedback
      summary: List of sent feedback
      tags:
      - my
      x-accepts:
      - application/json
  /my/follows:
    get:
      description: See what the user is following
      security:
      - oauth2:
        - read_lists
      summary: See what the user is following
      tags:
      - my
      x-accepts:
      - application/json
  /my/follows/articles:
    get:
      description: Returns a user's ArticleCategoryFollows
      security:
      - oauth2:
        - read_lists
      summary: Returns a user's ArticleCategoryFollows
      tags:
      - my
      x-accepts:
      - application/json
    post:
      description: Set a user's ArticleCategoryFollows
      security:
      - oauth2:
        - write_lists
      summary: Set a user's ArticleCategoryFollows
      tags:
      - my
      x-content-type: application/json
      x-accepts:
      - application/json
  /my/follows/brands/{slug}:
    delete:
      description: Unfollow a brand
      security:
      - oauth2:
        - write_lists
      summary: Unfollow a brand
      tags:
      - my
      x-accepts:
      - application/json
    get:
      description: Follow status for a brand
      security:
      - oauth2:
        - read_lists
      summary: Follow status for a brand
      tags:
      - my
      x-accepts:
      - application/json
    post:
      description: Follow a brand
      security:
      - oauth2:
        - write_lists
      summary: Follow a brand
      tags:
      - my
      x-accepts:
      - application/json
  /my/follows/categories/{category}/{subcategory}:
    delete:
      description: Unfollow a subcategory
      security:
      - oauth2:
        - write_lists
      summary: Unfollow a subcategory
      tags:
      - my
      x-accepts:
      - application/json
    get:
      description: Follow status for a subcategory
      security:
      - oauth2:
        - read_lists
      summary: Follow status for a subcategory
      tags:
      - my
      x-accepts:
      - application/json
    post:
      description: Follow a subcategory
      security:
      - oauth2:
        - write_lists
      summary: Follow a subcategory
      tags:
      - my
      x-accepts:
      - application/json
  /my/follows/categories/{identifier}:
    delete:
      description: Unfollow a category
      security:
      - oauth2:
        - write_lists
      summary: Unfollow a category
      tags:
      - my
      x-accepts:
      - application/json
    get:
      description: Follow status for a category
      security:
      - oauth2:
        - read_lists
      summary: Follow status for a category
      tags:
      - my
      x-accepts:
      - application/json
    post:
      description: Follow a category
      security:
      - oauth2:
        - write_lists
      summary: Follow a category
      tags:
      - my
      x-accepts:
      - application/json
  /my/follows/categories/{uuid}:
    post:
      description: Follow a category
      security:
      - oauth2:
        - write_lists
      summary: Follow a category
      tags:
      - my
      x-accepts:
      - application/json
  /my/follows/collections/{slug}:
    delete:
      description: Unfollow a collection
      security:
      - oauth2:
        - write_lists
      summary: Unfollow a collection
      tags:
      - my
      x-accepts:
      - application/json
    get:
      description: Follow status for a collection
      security:
      - oauth2:
        - read_lists
      summary: Follow status for a collection
      tags:
      - my
      x-accepts:
      - application/json
    post:
      description: Follow a collection
      security:
      - oauth2:
        - write_lists
      summary: Follow a collection
      tags:
      - my
      x-accepts:
      - application/json
  /my/follows/handpicked/{slug}:
    delete:
      description: Unfollow a handpicked collection
      security:
      - oauth2:
        - write_lists
      summary: Unfollow a handpicked collection
      tags:
      - my
      x-accepts:
      - application/json
    get:
      description: Follow status for a handpicked collection
      security:
      - oauth2:
        - read_lists
      summary: Follow status for a handpicked collection
      tags:
      - my
      x-accepts:
      - application/json
    post:
      description: Follow a handpicked collection
      security:
      - oauth2:
        - write_lists
      summary: Follow a handpicked collection
      tags:
      - my
      x-accepts:
      - application/json
  /my/follows/search:
    get:
      description: Follow status for a search
      security:
      - oauth2:
        - read_lists
      summary: Follow status for a search
      tags:
      - my
      x-accepts:
      - application/json
    post:
      description: Follow a search
      security:
      - oauth2:
        - write_lists
      summary: Follow a search
      tags:
      - my
      x-content-type: application/json
      x-accepts:
      - application/json
  /my/follows/shops/{slug}:
    delete:
      description: Unfollow a shop
      security:
      - oauth2:
        - write_lists
      summary: Unfollow a shop
      tags:
      - my
      x-accepts:
      - application/json
    get:
      description: Follow status for a shop
      security:
      - oauth2:
        - read_lists
      summary: Follow status for a shop
      tags:
      - my
      x-accepts:
      - application/json
    post:
      description: Follow a shop
      security:
      - oauth2:
        - write_lists
      summary: Follow a shop
      tags:
      - my
      x-accepts:
      - application/json
  /my/follows/{follow_id}:
    delete:
      description: Delete a follow
      security:
      - oauth2:
        - write_lists
      summary: Delete a follow
      tags:
      - my
      x-accepts:
      - application/json
  /my/follows/{follow_id}/alert:
    delete:
      tags:
      - my
      x-accepts:
      - application/json
    post:
      tags:
      - my
      x-accepts:
      - application/json
  /my/listings:
    get:
      description: Retrieve a list of live listings for the seller. To search all
        listings specify state=all
      security:
      - oauth2:
        - read_listings
      summary: Retrieve a list of live listings for the seller. To search all listings
        specify state=all
      tags:
      - my
      x-accepts:
      - application/json
  /my/listings/drafts:
    get:
      description: Retrieve a list your draft listings
      security:
      - oauth2:
        - read_listings
      summary: Retrieve a list your draft listings
      tags:
      - my
      x-accepts:
      - application/json
  /my/listings/negotiations:
    get:
      description: Get a list of active negotiations as a seller
      security:
      - oauth2:
        - read_offers
      summary: Get a list of active negotiations as a seller
      tags:
      - my
      x-accepts:
      - application/json
  /my/listings/{slug}/state/end:
    put:
      description: End a listing
      security:
      - oauth2:
        - write_listings
      summary: End a listing
      tags:
      - my
      x-content-type: application/json
      x-accepts:
      - application/json
  /my/lists:
    get:
      description: "Get a list of your lists (wishlist, watch list, etc)"
      security:
      - oauth2:
        - read_lists
      summary: "Get a list of your lists (wishlist, watch list, etc)"
      tags:
      - my
      x-accepts:
      - application/json
  /my/negotiations/buying:
    get:
      description: Get a list of active negotiations as a buyer
      security:
      - oauth2:
        - read_offers
      summary: Get a list of active negotiations as a buyer
      tags:
      - my
      x-accepts:
      - application/json
  /my/negotiations/{id}:
    get:
      description: Get offer details
      security:
      - oauth2:
        - read_offers
      summary: Get offer details
      tags:
      - my
      x-accepts:
      - application/json
  /my/negotiations/{id}/accept:
    post:
      description: Accept an offer
      security:
      - oauth2:
        - write_offers
      summary: Accept an offer
      tags:
      - my
      x-content-type: application/json
      x-accepts:
      - application/json
  /my/negotiations/{id}/counter:
    post:
      description: Counter an offer
      security:
      - oauth2:
        - write_offers
      summary: Counter an offer
      tags:
      - my
      x-content-type: application/json
      x-accepts:
      - application/json
  /my/negotiations/{id}/decline:
    post:
      description: Decline an offer
      security:
      - oauth2:
        - write_offers
      summary: Decline an offer
      tags:
      - my
      x-accepts:
      - application/json
  /my/orders/awaiting_feedback:
    get:
      description: List of orders that need feedback
      security:
      - oauth2:
        - read_feedback
      summary: List of orders that need feedback
      tags:
      - my
      x-accepts:
      - application/json
  /my/orders/buying/all:
    get:
      description: "Returns all orders, newest first."
      security:
      - oauth2:
        - read_orders
      summary: "Returns all orders, newest first."
      tags:
      - my
      x-accepts:
      - application/json
  /my/orders/buying/by_uuid/{uuid}:
    get:
      tags:
      - my
      x-accepts:
      - application/json
  /my/orders/buying/unpaid:
    get:
      description: "Returns unpaid orders, newest first."
      security:
      - oauth2:
        - read_orders
      summary: "Returns unpaid orders, newest first."
      tags:
      - my
      x-accepts:
      - application/json
  /my/orders/buying/{id}:
    get:
      description: Returns order details for a buyer
      security:
      - oauth2:
        - read_orders
      summary: Returns order details for a buyer
      tags:
      - my
      x-accepts:
      - application/json
  /my/orders/buying/{id}/mark_received:
    post:
      description: Marks an order as received by the buyer
      security:
      - oauth2:
        - write_orders
      summary: Marks an order as received by the buyer
      tags:
      - my
      x-accepts:
      - application/json
  /my/orders/selling/all:
    get:
      description: "Get all seller orders, newest first."
      security:
      - oauth2:
        - read_orders
      summary: "Get all seller orders, newest first."
      tags:
      - my
      x-accepts:
      - application/json
  /my/orders/selling/awaiting_shipment:
    get:
      description: "Get unpaid seller orders, newest first."
      security:
      - oauth2:
        - read_orders
      summary: "Get unpaid seller orders, newest first."
      tags:
      - my
      x-accepts:
      - application/json
  /my/orders/selling/buyer_history/{buyer_id}:
    get:
      description: See previous orders from buyer
      security:
      - oauth2:
        - read_orders
      summary: See previous orders from buyer
      tags:
      - my
      x-accepts:
      - application/json
  /my/orders/selling/by_uuid/{uuid}:
    get:
      tags:
      - my
      x-accepts:
      - application/json
  /my/orders/selling/unpaid:
    get:
      description: "Get unpaid seller orders, newest first."
      security:
      - oauth2:
        - read_orders
      summary: "Get unpaid seller orders, newest first."
      tags:
      - my
      x-accepts:
      - application/json
  /my/orders/selling/{id}:
    get:
      description: Returns order details for a seller
      security:
      - oauth2:
        - read_orders
      summary: Returns order details for a seller
      tags:
      - my
      x-accepts:
      - application/json
  /my/orders/selling/{id}/mark_picked_up:
    post:
      description: Marks an order as picked up
      security:
      - oauth2:
        - write_orders
      summary: Marks an order as picked up
      tags:
      - my
      x-content-type: application/json
      x-accepts:
      - application/json
  /my/orders/selling/{id}/ship:
    post:
      description: Marks an order as shipped
      security:
      - oauth2:
        - write_orders
      summary: Marks an order as shipped
      tags:
      - my
      x-content-type: application/json
      x-accepts:
      - application/json
  /my/orders/selling/{order_id}/refund_requests:
    post:
      description: Initiate a refund for a sold order
      security:
      - oauth2:
        - write_orders
      summary: Initiate a refund for a sold order
      tags:
      - my
      x-accepts:
      - application/json
  /my/payments/selling:
    get:
      description: Get payments
      security:
      - oauth2:
        - read_orders
      summary: Get payments
      tags:
      - my
      x-accepts:
      - application/json
  /my/payments/selling/{id}:
    get:
      description: Get payment
      security:
      - oauth2:
        - read_orders
      summary: Get payment
      tags:
      - my
      x-accepts:
      - application/json
  /my/payouts:
    get:
      description: Get a list of payouts
      security:
      - oauth2:
        - read_payouts
      summary: Get a list of payouts
      tags:
      - my
      x-accepts:
      - application/json
  /my/payouts/{id}/line_items:
    get:
      description: Read the line items of a payout
      security:
      - oauth2:
        - read_payouts
      summary: Read the line items of a payout
      tags:
      - my
      x-accepts:
      - application/json
  /my/refund_requests/selling:
    get:
      description: Get a list of refund requests as a seller
      security:
      - oauth2:
        - read_orders
      summary: Get a list of refund requests as a seller
      tags:
      - my
      x-accepts:
      - application/json
  /my/refund_requests/selling/{id}:
    put:
      description: Update a refund request for a sold order
      security:
      - oauth2:
        - write_orders
      summary: Update a refund request for a sold order
      tags:
      - my
      x-accepts:
      - application/json
  /my/viewed_listings:
    get:
      description: Get a list of your recently viewed listings.
      security:
      - oauth2:
        - read_lists
      summary: Get a list of your recently viewed listings.
      tags:
      - my
      x-accepts:
      - application/json
  /my/wishlist:
    get:
      description: Get a list of wishlisted items
      security:
      - oauth2:
        - read_lists
      summary: Get a list of wishlisted items
      tags:
      - my
      x-accepts:
      - application/json
  /my/wishlist/{id}:
    delete:
      description: Remove a listing from your wishlist
      security:
      - oauth2:
        - write_lists
      summary: Remove a listing from your wishlist
      tags:
      - my
      x-accepts:
      - application/json
    put:
      description: Add a listing to your wishlist
      security:
      - oauth2:
        - write_lists
      summary: Add a listing to your wishlist
      tags:
      - my
      x-accepts:
      - application/json
  /orders/{order_id}/feedback/buyer:
    get:
      description: Feedback details for an order's buyer
      summary: Feedback details for an order's buyer
      tags:
      - orders
      x-accepts:
      - application/json
    post:
      description: Add feedback about an order's buyer
      security:
      - oauth2:
        - write_feedback
      summary: Add feedback about an order's buyer
      tags:
      - orders
      x-accepts:
      - application/json
  /orders/{order_id}/feedback/seller:
    get:
      description: Feedback details for an order's seller
      summary: Feedback details for an order's seller
      tags:
      - orders
      x-accepts:
      - application/json
    post:
      description: Add feedback about an order's seller
      security:
      - oauth2:
        - write_feedback
      summary: Add feedback about an order's seller
      tags:
      - orders
      x-accepts:
      - application/json
  /payment_methods:
    get:
      description: Get list of payment methods
      summary: Get list of payment methods
      tags:
      - payment_methods
      x-accepts:
      - application/json
  /priceguide/{id}/transactions/summary:
    get:
      description: Get a summary of transactions for a given price guide
      summary: Get a summary of transactions for a given price guide
      tags:
      - priceguide
      x-accepts:
      - application/json
  /products/reviews/{id}:
    get:
      description: View a review
      summary: View a review
      tags:
      - products
      x-accepts:
      - application/json
    put:
      description: Update a review
      security:
      - oauth2:
        - write_reviews
      summary: Update a review
      tags:
      - products
      x-content-type: application/json
      x-accepts:
      - application/json
  /products/{slug}/reviews:
    get:
      description: View reviews of a comparison shopping page
      summary: View reviews of a comparison shopping page
      tags:
      - products
      x-accepts:
      - application/json
    post:
      description: Create a review for a product
      security:
      - oauth2:
        - write_reviews
      summary: Create a review for a product
      tags:
      - products
      x-accepts:
      - application/json
  /sales/reverb:
    get:
      description: View upcoming and live Reverb official sales.
      security:
      - oauth2:
        - read_listings
      summary: View upcoming and live Reverb official sales.
      tags:
      - sales
      x-accepts:
      - application/json
  /sales/seller:
    get:
      description: View your created sales.
      security:
      - oauth2:
        - read_listings
      summary: View your created sales.
      tags:
      - sales
      x-accepts:
      - application/json
  /sales/{sale_id}/listings:
    delete:
      description: Remove a listing from a sale
      security:
      - oauth2:
        - write_listings
      summary: Remove a listing from a sale
      tags:
      - sales
      x-accepts:
      - application/json
    post:
      description: Add listings to a sale
      security:
      - oauth2:
        - write_listings
      summary: Add listings to a sale
      tags:
      - sales
      x-accepts:
      - application/json
  /sales/{slug}:
    get:
      tags:
      - sales
      x-accepts:
      - application/json
  /shipping/providers:
    get:
      description: List of supported shipping providers
      summary: List of supported shipping providers
      tags:
      - shipping
      x-accepts:
      - application/json
  /shipping/regions:
    get:
      tags:
      - shipping
      x-accepts:
      - application/json
  /shop:
    get:
      description: Get your own shop details
      security:
      - oauth2:
        - read_profile
      summary: Get your own shop details
      tags:
      - shop
      x-accepts:
      - application/json
    put:
      description: Update your shop profile
      security:
      - oauth2:
        - write_profile
      summary: Update your shop profile
      tags:
      - shop
      x-content-type: application/json
      x-accepts:
      - application/json
  /shop/listing_conditions:
    get:
      description: List of supported product conditions
      security:
      - oauth2:
        - read_profile
      summary: List of supported product conditions
      tags:
      - shop
      x-accepts:
      - application/json
  /shop/payment_methods:
    get:
      description: Get accepted payment methods
      security:
      - oauth2:
        - read_profile
      summary: Get accepted payment methods
      tags:
      - shop
      x-accepts:
      - application/json
  /shop/vacation:
    delete:
      description: Disable vacation mode. All listings will be re-enabled.
      security:
      - oauth2:
        - write_profile
      summary: Disable vacation mode. All listings will be re-enabled.
      tags:
      - shop
      x-accepts:
      - application/json
    get:
      description: Returns shop vacation status
      security:
      - oauth2:
        - read_profile
      summary: Returns shop vacation status
      tags:
      - shop
      x-accepts:
      - application/json
    post:
      description: Enable vacation mode. All listings will be unavailable until vacation
        mode is turned off.
      security:
      - oauth2:
        - write_profile
      summary: Enable vacation mode. All listings will be unavailable until vacation
        mode is turned off.
      tags:
      - shop
      x-accepts:
      - application/json
  /shops/{id}/storefronts:
    get:
      description: Get storefront details on a shop.
      summary: Get storefront details on a shop.
      tags:
      - shops
      x-accepts:
      - application/json
  /shops/{shop_id}/shipping_profiles:
    get:
      description: List of shipping profiles for your shop
      security:
      - oauth2:
        - read_profile
      summary: List of shipping profiles for your shop
      tags:
      - shops
      x-accepts:
      - application/json
  /shops/{slug}:
    get:
      description: Get details on a shop.
      summary: Get details on a shop.
      tags:
      - shops
      x-accepts:
      - application/json
  /shops/{slug}/feedback:
    get:
      description: Get seller's feedback
      summary: Get seller's feedback
      tags:
      - shops
      x-accepts:
      - application/json
  /shops/{slug}/feedback/buyer:
    get:
      description: Get seller's feedback as a buyer
      summary: Get seller's feedback as a buyer
      tags:
      - shops
      x-accepts:
      - application/json
  /shops/{slug}/feedback/seller:
    get:
      description: Get seller's feedback as a seller
      summary: Get seller's feedback as a seller
      tags:
      - shops
      x-accepts:
      - application/json
  /wants:
    get:
      description: A list of wanted items by the user
      security:
      - oauth2:
        - read_lists
      summary: A list of wanted items by the user
      tags:
      - wants
      x-accepts:
      - application/json
  /wants/{id}:
    delete:
      description: Unmark an item wanted.
      security:
      - oauth2:
        - write_lists
      summary: Unmark an item wanted.
      tags:
      - wants
      x-accepts:
      - application/json
    put:
      description: Mark an item wanted. Returns 200 on success or 422 on failure.
      security:
      - oauth2:
        - write_lists
      summary: Mark an item wanted. Returns 200 on success or 422 on failure.
      tags:
      - wants
      x-accepts:
      - application/json
  /webhooks/registrations:
    get:
      description: Get webhook registrations
      summary: Get webhook registrations
      tags:
      - webhooks
      x-accepts:
      - application/json
    post:
      description: Register a webhook
      summary: Register a webhook
      tags:
      - webhooks
      x-content-type: application/json
      x-accepts:
      - application/json
  /webhooks/registrations/{id}:
    delete:
      description: Remove a webhook
      summary: Remove a webhook
      tags:
      - webhooks
      x-accepts:
      - application/json
    get:
      description: Get details of a webhook registration
      summary: Get details of a webhook registration
      tags:
      - webhooks
      x-accepts:
      - application/json
components:
  securitySchemes:
    oauth2:
      flows:
        clientCredentials:
          scopes:
            public: ""
            read_feedback: '*Originally missing*'
            read_listings: '*Originally missing*'
            read_lists: '*Originally missing*'
            read_messages: '*Originally missing*'
            read_offers: '*Originally missing*'
            read_orders: '*Originally missing*'
            read_payouts: '*Originally missing*'
            read_profile: '*Originally missing*'
            write_feedback: '*Originally missing*'
            write_listings: '*Originally missing*'
            write_listings_for_others: '*Originally missing*'
            write_lists: '*Originally missing*'
            write_messages: '*Originally missing*'
            write_offers: '*Originally missing*'
            write_orders: '*Originally missing*'
            write_profile: '*Originally missing*'
            write_reviews: '*Originally missing*'
          tokenUrl: https://reverb.com/oauth/token
      type: oauth2
x-hasEquivalentPaths: true

