QT += network

HEADERS += \
# Models
    $${PWD}/OAIAccountHoldingModel.h \
    $${PWD}/OAIAccountHoldingWithIdModel.h \
    $${PWD}/OAIAccountHoldingsModel.h \
    $${PWD}/OAIAccountHoldingsWithoutIdModel.h \
    $${PWD}/OAIAccountModel.h \
    $${PWD}/OAIAccountTypeModel.h \
    $${PWD}/OAIAccountTypesModel.h \
    $${PWD}/OAIAccountWithIdModel.h \
    $${PWD}/OAIAccountWithSubEntitiesModel.h \
    $${PWD}/OAIAccountsModel.h \
    $${PWD}/OAIAccountsWithSubEntitiesModel.h \
    $${PWD}/OAIClientModel.h \
    $${PWD}/OAIClientsModel.h \
    $${PWD}/OAICriticalIllnessInsurancePoliciesModel.h \
    $${PWD}/OAICriticalIllnessInsurancePolicyModel.h \
    $${PWD}/OAICriticalIllnessInsurancePolicyTypeModel.h \
    $${PWD}/OAICriticalIllnessInsurancePolicyTypesModel.h \
    $${PWD}/OAICriticalIllnessInsurancePolicyWithIdModel.h \
    $${PWD}/OAIDefinedBenefitPensionModel.h \
    $${PWD}/OAIDefinedBenefitPensionWithIdModel.h \
    $${PWD}/OAIDefinedBenefitPensionsModel.h \
    $${PWD}/OAIDemographicsDependentModel.h \
    $${PWD}/OAIDemographicsDependentWithIdModel.h \
    $${PWD}/OAIDemographicsDependentsModel.h \
    $${PWD}/OAIDemographicsModel.h \
    $${PWD}/OAIDemographicsWithIdModel.h \
    $${PWD}/OAIDisabilityInsurancePoliciesModel.h \
    $${PWD}/OAIDisabilityInsurancePolicyModel.h \
    $${PWD}/OAIDisabilityInsurancePolicyTypeModel.h \
    $${PWD}/OAIDisabilityInsurancePolicyTypesModel.h \
    $${PWD}/OAIDisabilityInsurancePolicyWithIdModel.h \
    $${PWD}/OAIEducationExpenseModel.h \
    $${PWD}/OAIEducationExpenseWithIdModel.h \
    $${PWD}/OAIEducationExpensesModel.h \
    $${PWD}/OAIEducationGoalModel.h \
    $${PWD}/OAIEducationGoalWithIdModel.h \
    $${PWD}/OAIEducationGoalsModel.h \
    $${PWD}/OAIExpenseModel.h \
    $${PWD}/OAIExpenseTypeModel.h \
    $${PWD}/OAIExpenseTypesModel.h \
    $${PWD}/OAIExpenseWithIdModel.h \
    $${PWD}/OAIExpensesModel.h \
    $${PWD}/OAIFactFinderEntityModel.h \
    $${PWD}/OAIFactFinderModel.h \
    $${PWD}/OAIFactFinderModuleModel.h \
    $${PWD}/OAIFactFinderModuleWithIdModel.h \
    $${PWD}/OAIFactFinderModulesModel.h \
    $${PWD}/OAIFactFinderPopulatableEntityModel.h \
    $${PWD}/OAIFactFinderPopulationModel.h \
    $${PWD}/OAIFactFinderSnapshotWithIdModel.h \
    $${PWD}/OAIFactFinderSnapshotsModel.h \
    $${PWD}/OAIFactFinderWithIdModel.h \
    $${PWD}/OAIFamilyHeadModel.h \
    $${PWD}/OAIFilingStatusTypeModel.h \
    $${PWD}/OAIFilingStatusTypesModel.h \
    $${PWD}/OAIFrequencyTypeModel.h \
    $${PWD}/OAIFrequencyTypesModel.h \
    $${PWD}/OAIIAccountHoldingDomainObject.h \
    $${PWD}/OAIIAccountSavingsStrategyDomainObject.h \
    $${PWD}/OAIIAccountWithSubEntitiesDomainObject.h \
    $${PWD}/OAIICriticalIllnessInsurancePolicyDomainObject.h \
    $${PWD}/OAIIDemographicsDependentDomainObject.h \
    $${PWD}/OAIIDemographicsWithDependentsDomainObject.h \
    $${PWD}/OAIIDisabilityInsurancePolicyDomainObject.h \
    $${PWD}/OAIIEducationExpenseDomainObject.h \
    $${PWD}/OAIIEducationGoalWithExpensesDomainObject.h \
    $${PWD}/OAIIExpenseDomainObject.h \
    $${PWD}/OAIIFactFinderDefinedBenefitPensionDomainObject.h \
    $${PWD}/OAIIFactFinderLiabilityDomainObject.h \
    $${PWD}/OAIIFactFinderLifestyleAssetDomainObject.h \
    $${PWD}/OAIIFactFinderSnapshotDomainObject.h \
    $${PWD}/OAIIFamilyHeadDomainObject.h \
    $${PWD}/OAIIIncomeDomainObject.h \
    $${PWD}/OAIILifeInsurancePolicyDomainObject.h \
    $${PWD}/OAIILongTermCareInsurancePolicyDomainObject.h \
    $${PWD}/OAIIMajorPurchaseGoalDomainObject.h \
    $${PWD}/OAIIRealEstateAssetDomainObject.h \
    $${PWD}/OAIIRetirementExpenseDomainObject.h \
    $${PWD}/OAIIRetirementGoalWithExpensesDomainObject.h \
    $${PWD}/OAIIncomeModel.h \
    $${PWD}/OAIIncomeTypeModel.h \
    $${PWD}/OAIIncomeTypesModel.h \
    $${PWD}/OAIIncomeWithIdModel.h \
    $${PWD}/OAIIncomesModel.h \
    $${PWD}/OAILiabilitiesModel.h \
    $${PWD}/OAILiabilityModel.h \
    $${PWD}/OAILiabilityTypeModel.h \
    $${PWD}/OAILiabilityTypesModel.h \
    $${PWD}/OAILiabilityWithIdModel.h \
    $${PWD}/OAILifeInsurancePoliciesModel.h \
    $${PWD}/OAILifeInsurancePoliciesWithSubEntitiesModel.h \
    $${PWD}/OAILifeInsurancePolicyModel.h \
    $${PWD}/OAILifeInsurancePolicySubaccountDomainObject.h \
    $${PWD}/OAILifeInsurancePolicySubaccountModel.h \
    $${PWD}/OAILifeInsurancePolicySubaccountWithIdModel.h \
    $${PWD}/OAILifeInsurancePolicySubaccountsModel.h \
    $${PWD}/OAILifeInsurancePolicyTypeModel.h \
    $${PWD}/OAILifeInsurancePolicyTypesModel.h \
    $${PWD}/OAILifeInsurancePolicyWithIdModel.h \
    $${PWD}/OAILifeInsurancePolicyWithSubEntitiesModel.h \
    $${PWD}/OAILifestyleAssetModel.h \
    $${PWD}/OAILifestyleAssetTypeModel.h \
    $${PWD}/OAILifestyleAssetTypesModel.h \
    $${PWD}/OAILifestyleAssetWithIdModel.h \
    $${PWD}/OAILifestyleAssetsModel.h \
    $${PWD}/OAILongTermCareInsurancePoliciesModel.h \
    $${PWD}/OAILongTermCareInsurancePolicyModel.h \
    $${PWD}/OAILongTermCareInsurancePolicyWithIdModel.h \
    $${PWD}/OAIMajorPurchaseGoalModel.h \
    $${PWD}/OAIMajorPurchaseGoalTypeModel.h \
    $${PWD}/OAIMajorPurchaseGoalTypesModel.h \
    $${PWD}/OAIMajorPurchaseGoalWithIdModel.h \
    $${PWD}/OAIMajorPurchaseGoalsModel.h \
    $${PWD}/OAIObjectLink.h \
    $${PWD}/OAIOwnerModel.h \
    $${PWD}/OAIOwnersModel.h \
    $${PWD}/OAIRealEstateAssetModel.h \
    $${PWD}/OAIRealEstateAssetWithIdModel.h \
    $${PWD}/OAIRealEstateAssetsModel.h \
    $${PWD}/OAIRelationshipTypeModel.h \
    $${PWD}/OAIRelationshipTypesModel.h \
    $${PWD}/OAIRetirementExpenseModel.h \
    $${PWD}/OAIRetirementExpenseWithIdModel.h \
    $${PWD}/OAIRetirementExpensesModel.h \
    $${PWD}/OAIRetirementGoalModel.h \
    $${PWD}/OAIRetirementGoalWithIdModel.h \
    $${PWD}/OAIRetirementGoalsModel.h \
    $${PWD}/OAISavingsStrategiesModel.h \
    $${PWD}/OAISavingsStrategyModel.h \
    $${PWD}/OAISavingsStrategyWithIdModel.h \
    $${PWD}/OAISavingsTypeDomainObject.h \
    $${PWD}/OAIServiceInformationModel.h \
    $${PWD}/OAIStateProvinceModel.h \
    $${PWD}/OAIStatesProvincesModel.h \
# APIs
    $${PWD}/OAIAccountTypesApi.h \
    $${PWD}/OAIAccountsApi.h \
    $${PWD}/OAIClientsApi.h \
    $${PWD}/OAICriticalIllnessInsurancePoliciesApi.h \
    $${PWD}/OAICriticalIllnessInsurancePolicyTypesApi.h \
    $${PWD}/OAIDefinedBenefitPensionsApi.h \
    $${PWD}/OAIDemographicsApi.h \
    $${PWD}/OAIDisabilityInsurancePoliciesApi.h \
    $${PWD}/OAIDisabilityInsurancePolicyTypesApi.h \
    $${PWD}/OAIEducationGoalsApi.h \
    $${PWD}/OAIExpenseTypesApi.h \
    $${PWD}/OAIExpensesApi.h \
    $${PWD}/OAIFactFinderModulesApi.h \
    $${PWD}/OAIFactFinderServiceInformationApi.h \
    $${PWD}/OAIFactFindersApi.h \
    $${PWD}/OAIFilingStatusTypesApi.h \
    $${PWD}/OAIFrequencyTypesApi.h \
    $${PWD}/OAIIncomeTypesApi.h \
    $${PWD}/OAIIncomesApi.h \
    $${PWD}/OAILiabilitiesApi.h \
    $${PWD}/OAILiabilityTypesApi.h \
    $${PWD}/OAILifeInsurancePoliciesApi.h \
    $${PWD}/OAILifeInsurancePolicyTypesApi.h \
    $${PWD}/OAILifestyleAssetTypesApi.h \
    $${PWD}/OAILifestyleAssetsApi.h \
    $${PWD}/OAILongTermCareInsurancePoliciesApi.h \
    $${PWD}/OAIMajorPurchaseGoalTypesApi.h \
    $${PWD}/OAIMajorPurchaseGoalsApi.h \
    $${PWD}/OAIPresentationApi.h \
    $${PWD}/OAIRealEstateAssetsApi.h \
    $${PWD}/OAIRetirementGoalsApi.h \
    $${PWD}/OAIStatesProvincesApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAccountHoldingModel.cpp \
    $${PWD}/OAIAccountHoldingWithIdModel.cpp \
    $${PWD}/OAIAccountHoldingsModel.cpp \
    $${PWD}/OAIAccountHoldingsWithoutIdModel.cpp \
    $${PWD}/OAIAccountModel.cpp \
    $${PWD}/OAIAccountTypeModel.cpp \
    $${PWD}/OAIAccountTypesModel.cpp \
    $${PWD}/OAIAccountWithIdModel.cpp \
    $${PWD}/OAIAccountWithSubEntitiesModel.cpp \
    $${PWD}/OAIAccountsModel.cpp \
    $${PWD}/OAIAccountsWithSubEntitiesModel.cpp \
    $${PWD}/OAIClientModel.cpp \
    $${PWD}/OAIClientsModel.cpp \
    $${PWD}/OAICriticalIllnessInsurancePoliciesModel.cpp \
    $${PWD}/OAICriticalIllnessInsurancePolicyModel.cpp \
    $${PWD}/OAICriticalIllnessInsurancePolicyTypeModel.cpp \
    $${PWD}/OAICriticalIllnessInsurancePolicyTypesModel.cpp \
    $${PWD}/OAICriticalIllnessInsurancePolicyWithIdModel.cpp \
    $${PWD}/OAIDefinedBenefitPensionModel.cpp \
    $${PWD}/OAIDefinedBenefitPensionWithIdModel.cpp \
    $${PWD}/OAIDefinedBenefitPensionsModel.cpp \
    $${PWD}/OAIDemographicsDependentModel.cpp \
    $${PWD}/OAIDemographicsDependentWithIdModel.cpp \
    $${PWD}/OAIDemographicsDependentsModel.cpp \
    $${PWD}/OAIDemographicsModel.cpp \
    $${PWD}/OAIDemographicsWithIdModel.cpp \
    $${PWD}/OAIDisabilityInsurancePoliciesModel.cpp \
    $${PWD}/OAIDisabilityInsurancePolicyModel.cpp \
    $${PWD}/OAIDisabilityInsurancePolicyTypeModel.cpp \
    $${PWD}/OAIDisabilityInsurancePolicyTypesModel.cpp \
    $${PWD}/OAIDisabilityInsurancePolicyWithIdModel.cpp \
    $${PWD}/OAIEducationExpenseModel.cpp \
    $${PWD}/OAIEducationExpenseWithIdModel.cpp \
    $${PWD}/OAIEducationExpensesModel.cpp \
    $${PWD}/OAIEducationGoalModel.cpp \
    $${PWD}/OAIEducationGoalWithIdModel.cpp \
    $${PWD}/OAIEducationGoalsModel.cpp \
    $${PWD}/OAIExpenseModel.cpp \
    $${PWD}/OAIExpenseTypeModel.cpp \
    $${PWD}/OAIExpenseTypesModel.cpp \
    $${PWD}/OAIExpenseWithIdModel.cpp \
    $${PWD}/OAIExpensesModel.cpp \
    $${PWD}/OAIFactFinderEntityModel.cpp \
    $${PWD}/OAIFactFinderModel.cpp \
    $${PWD}/OAIFactFinderModuleModel.cpp \
    $${PWD}/OAIFactFinderModuleWithIdModel.cpp \
    $${PWD}/OAIFactFinderModulesModel.cpp \
    $${PWD}/OAIFactFinderPopulatableEntityModel.cpp \
    $${PWD}/OAIFactFinderPopulationModel.cpp \
    $${PWD}/OAIFactFinderSnapshotWithIdModel.cpp \
    $${PWD}/OAIFactFinderSnapshotsModel.cpp \
    $${PWD}/OAIFactFinderWithIdModel.cpp \
    $${PWD}/OAIFamilyHeadModel.cpp \
    $${PWD}/OAIFilingStatusTypeModel.cpp \
    $${PWD}/OAIFilingStatusTypesModel.cpp \
    $${PWD}/OAIFrequencyTypeModel.cpp \
    $${PWD}/OAIFrequencyTypesModel.cpp \
    $${PWD}/OAIIAccountHoldingDomainObject.cpp \
    $${PWD}/OAIIAccountSavingsStrategyDomainObject.cpp \
    $${PWD}/OAIIAccountWithSubEntitiesDomainObject.cpp \
    $${PWD}/OAIICriticalIllnessInsurancePolicyDomainObject.cpp \
    $${PWD}/OAIIDemographicsDependentDomainObject.cpp \
    $${PWD}/OAIIDemographicsWithDependentsDomainObject.cpp \
    $${PWD}/OAIIDisabilityInsurancePolicyDomainObject.cpp \
    $${PWD}/OAIIEducationExpenseDomainObject.cpp \
    $${PWD}/OAIIEducationGoalWithExpensesDomainObject.cpp \
    $${PWD}/OAIIExpenseDomainObject.cpp \
    $${PWD}/OAIIFactFinderDefinedBenefitPensionDomainObject.cpp \
    $${PWD}/OAIIFactFinderLiabilityDomainObject.cpp \
    $${PWD}/OAIIFactFinderLifestyleAssetDomainObject.cpp \
    $${PWD}/OAIIFactFinderSnapshotDomainObject.cpp \
    $${PWD}/OAIIFamilyHeadDomainObject.cpp \
    $${PWD}/OAIIIncomeDomainObject.cpp \
    $${PWD}/OAIILifeInsurancePolicyDomainObject.cpp \
    $${PWD}/OAIILongTermCareInsurancePolicyDomainObject.cpp \
    $${PWD}/OAIIMajorPurchaseGoalDomainObject.cpp \
    $${PWD}/OAIIRealEstateAssetDomainObject.cpp \
    $${PWD}/OAIIRetirementExpenseDomainObject.cpp \
    $${PWD}/OAIIRetirementGoalWithExpensesDomainObject.cpp \
    $${PWD}/OAIIncomeModel.cpp \
    $${PWD}/OAIIncomeTypeModel.cpp \
    $${PWD}/OAIIncomeTypesModel.cpp \
    $${PWD}/OAIIncomeWithIdModel.cpp \
    $${PWD}/OAIIncomesModel.cpp \
    $${PWD}/OAILiabilitiesModel.cpp \
    $${PWD}/OAILiabilityModel.cpp \
    $${PWD}/OAILiabilityTypeModel.cpp \
    $${PWD}/OAILiabilityTypesModel.cpp \
    $${PWD}/OAILiabilityWithIdModel.cpp \
    $${PWD}/OAILifeInsurancePoliciesModel.cpp \
    $${PWD}/OAILifeInsurancePoliciesWithSubEntitiesModel.cpp \
    $${PWD}/OAILifeInsurancePolicyModel.cpp \
    $${PWD}/OAILifeInsurancePolicySubaccountDomainObject.cpp \
    $${PWD}/OAILifeInsurancePolicySubaccountModel.cpp \
    $${PWD}/OAILifeInsurancePolicySubaccountWithIdModel.cpp \
    $${PWD}/OAILifeInsurancePolicySubaccountsModel.cpp \
    $${PWD}/OAILifeInsurancePolicyTypeModel.cpp \
    $${PWD}/OAILifeInsurancePolicyTypesModel.cpp \
    $${PWD}/OAILifeInsurancePolicyWithIdModel.cpp \
    $${PWD}/OAILifeInsurancePolicyWithSubEntitiesModel.cpp \
    $${PWD}/OAILifestyleAssetModel.cpp \
    $${PWD}/OAILifestyleAssetTypeModel.cpp \
    $${PWD}/OAILifestyleAssetTypesModel.cpp \
    $${PWD}/OAILifestyleAssetWithIdModel.cpp \
    $${PWD}/OAILifestyleAssetsModel.cpp \
    $${PWD}/OAILongTermCareInsurancePoliciesModel.cpp \
    $${PWD}/OAILongTermCareInsurancePolicyModel.cpp \
    $${PWD}/OAILongTermCareInsurancePolicyWithIdModel.cpp \
    $${PWD}/OAIMajorPurchaseGoalModel.cpp \
    $${PWD}/OAIMajorPurchaseGoalTypeModel.cpp \
    $${PWD}/OAIMajorPurchaseGoalTypesModel.cpp \
    $${PWD}/OAIMajorPurchaseGoalWithIdModel.cpp \
    $${PWD}/OAIMajorPurchaseGoalsModel.cpp \
    $${PWD}/OAIObjectLink.cpp \
    $${PWD}/OAIOwnerModel.cpp \
    $${PWD}/OAIOwnersModel.cpp \
    $${PWD}/OAIRealEstateAssetModel.cpp \
    $${PWD}/OAIRealEstateAssetWithIdModel.cpp \
    $${PWD}/OAIRealEstateAssetsModel.cpp \
    $${PWD}/OAIRelationshipTypeModel.cpp \
    $${PWD}/OAIRelationshipTypesModel.cpp \
    $${PWD}/OAIRetirementExpenseModel.cpp \
    $${PWD}/OAIRetirementExpenseWithIdModel.cpp \
    $${PWD}/OAIRetirementExpensesModel.cpp \
    $${PWD}/OAIRetirementGoalModel.cpp \
    $${PWD}/OAIRetirementGoalWithIdModel.cpp \
    $${PWD}/OAIRetirementGoalsModel.cpp \
    $${PWD}/OAISavingsStrategiesModel.cpp \
    $${PWD}/OAISavingsStrategyModel.cpp \
    $${PWD}/OAISavingsStrategyWithIdModel.cpp \
    $${PWD}/OAISavingsTypeDomainObject.cpp \
    $${PWD}/OAIServiceInformationModel.cpp \
    $${PWD}/OAIStateProvinceModel.cpp \
    $${PWD}/OAIStatesProvincesModel.cpp \
# APIs
    $${PWD}/OAIAccountTypesApi.cpp \
    $${PWD}/OAIAccountsApi.cpp \
    $${PWD}/OAIClientsApi.cpp \
    $${PWD}/OAICriticalIllnessInsurancePoliciesApi.cpp \
    $${PWD}/OAICriticalIllnessInsurancePolicyTypesApi.cpp \
    $${PWD}/OAIDefinedBenefitPensionsApi.cpp \
    $${PWD}/OAIDemographicsApi.cpp \
    $${PWD}/OAIDisabilityInsurancePoliciesApi.cpp \
    $${PWD}/OAIDisabilityInsurancePolicyTypesApi.cpp \
    $${PWD}/OAIEducationGoalsApi.cpp \
    $${PWD}/OAIExpenseTypesApi.cpp \
    $${PWD}/OAIExpensesApi.cpp \
    $${PWD}/OAIFactFinderModulesApi.cpp \
    $${PWD}/OAIFactFinderServiceInformationApi.cpp \
    $${PWD}/OAIFactFindersApi.cpp \
    $${PWD}/OAIFilingStatusTypesApi.cpp \
    $${PWD}/OAIFrequencyTypesApi.cpp \
    $${PWD}/OAIIncomeTypesApi.cpp \
    $${PWD}/OAIIncomesApi.cpp \
    $${PWD}/OAILiabilitiesApi.cpp \
    $${PWD}/OAILiabilityTypesApi.cpp \
    $${PWD}/OAILifeInsurancePoliciesApi.cpp \
    $${PWD}/OAILifeInsurancePolicyTypesApi.cpp \
    $${PWD}/OAILifestyleAssetTypesApi.cpp \
    $${PWD}/OAILifestyleAssetsApi.cpp \
    $${PWD}/OAILongTermCareInsurancePoliciesApi.cpp \
    $${PWD}/OAIMajorPurchaseGoalTypesApi.cpp \
    $${PWD}/OAIMajorPurchaseGoalsApi.cpp \
    $${PWD}/OAIPresentationApi.cpp \
    $${PWD}/OAIRealEstateAssetsApi.cpp \
    $${PWD}/OAIRetirementGoalsApi.cpp \
    $${PWD}/OAIStatesProvincesApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
