QT += network

HEADERS += \
# Models
    $${PWD}/OAIGoogleCloudDialogflowCxV3AdvancedSettings.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3AdvancedSettingsDtmfSettings.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3AdvancedSettingsLoggingSettings.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3AudioInput.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3BargeInConfig.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3BatchRunTestCasesMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3BatchRunTestCasesResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ContinuousTestResult.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ConversationSignals.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ConversationTurn.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ConversationTurnUserInput.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ConversationTurnVirtualAgentOutput.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3CreateDocumentOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3CreateVersionOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3DataStoreConnection.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3DeleteDocumentOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3DeployFlowMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3DeployFlowResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3DtmfInput.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3Environment.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3EnvironmentTestCasesConfig.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3EnvironmentVersionConfig.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3EnvironmentWebhookConfig.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3EventHandler.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3EventInput.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ExportAgentResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ExportEntityTypesResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ExportFlowResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ExportIntentsResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ExportTestCasesResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3Form.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3FormParameter.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3FormParameterFillBehavior.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3Fulfillment.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3FulfillmentConditionalCases.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3FulfillmentConditionalCasesCase.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3FulfillmentConditionalCasesCaseCaseContent.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3FulfillmentSetParameterAction.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3GcsDestination.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3GenericKnowledgeOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ImportDocumentsOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ImportDocumentsResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ImportEntityTypesResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ImportEntityTypesResponseConflictingResources.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ImportFlowResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ImportIntentsResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ImportIntentsResponseConflictingResources.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ImportTestCasesMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ImportTestCasesResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3InlineDestination.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3InputAudioConfig.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3Intent.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3IntentInput.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3IntentParameter.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3IntentTrainingPhrase.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3IntentTrainingPhrasePart.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3KnowledgeConnectorSettings.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3Page.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3PageInfo.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3PageInfoFormInfo.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3PageInfoFormInfoParameterInfo.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3QueryInput.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ReloadDocumentOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ResponseMessage.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ResponseMessageConversationSuccess.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ResponseMessageLiveAgentHandoff.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ResponseMessageMixedAudio.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ResponseMessageMixedAudioSegment.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ResponseMessageOutputAudioText.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ResponseMessagePlayAudio.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ResponseMessageTelephonyTransferCall.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ResponseMessageText.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3RunContinuousTestMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3RunContinuousTestResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3RunTestCaseResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3SessionInfo.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3TestCase.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3TestCaseError.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3TestCaseResult.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3TestConfig.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3TestError.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3TestRunDifference.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3TextInput.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3TransitionRoute.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3TurnSignals.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3UpdateDocumentOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3Webhook.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3WebhookGenericWebService.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3WebhookRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3WebhookRequestFulfillmentInfo.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3WebhookRequestIntentInfo.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3WebhookRequestIntentInfoIntentParameterValue.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3WebhookRequestSentimentAnalysisResult.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3WebhookResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3WebhookResponseFulfillmentResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3WebhookServiceDirectoryConfig.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1AdvancedSettings.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1AdvancedSettingsDtmfSettings.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1AdvancedSettingsLoggingSettings.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Agent.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1AgentAnswerFeedbackSettings.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1AgentGenAppBuilderSettings.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1AgentGitIntegrationSettings.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1AgentGitIntegrationSettingsGithubSettings.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1AgentValidationResult.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1AnswerFeedback.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1AnswerFeedbackRatingReason.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1AudioInput.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1BargeInConfig.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1BatchDeleteTestCasesRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1BatchRunTestCasesMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1BatchRunTestCasesRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1BatchRunTestCasesResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1BoostSpec.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1BoostSpecConditionBoostSpec.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1BoostSpecs.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1CalculateCoverageResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Changelog.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1CompareVersionsRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1CompareVersionsResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ContinuousTestResult.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ConversationSignals.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ConversationTurn.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ConversationTurnUserInput.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ConversationTurnVirtualAgentOutput.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1CreateDocumentOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1CreateVersionOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1DataStoreConnection.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1DeleteDocumentOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1DeployFlowMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1DeployFlowRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1DeployFlowResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Deployment.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1DeploymentResult.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1DetectIntentRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1DetectIntentResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1DtmfInput.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1EntityType.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1EntityTypeEntity.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1EntityTypeExcludedPhrase.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Environment.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1EnvironmentTestCasesConfig.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1EnvironmentVersionConfig.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1EnvironmentWebhookConfig.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1EventHandler.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1EventInput.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Experiment.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExperimentDefinition.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExperimentResult.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExperimentResultConfidenceInterval.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExperimentResultMetric.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExperimentResultVersionMetrics.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExportAgentRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExportAgentRequestGitDestination.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExportAgentResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExportEntityTypesRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExportEntityTypesResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExportFlowRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExportFlowResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExportIntentsRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExportIntentsResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExportTestCasesRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExportTestCasesResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1FilterSpecs.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Flow.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1FlowImportStrategy.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1FlowValidationResult.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Form.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1FormParameter.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1FormParameterFillBehavior.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1FulfillIntentRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1FulfillIntentResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Fulfillment.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1FulfillmentConditionalCases.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1FulfillmentConditionalCasesCase.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1FulfillmentConditionalCasesCaseCaseContent.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1FulfillmentSetParameterAction.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1GcsDestination.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1GenerativeSettings.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1GenerativeSettingsFallbackSettings.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1GenerativeSettingsFallbackSettingsPromptTemplate.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1GenerativeSettingsKnowledgeConnectorSettings.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Generator.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1GeneratorPlaceholder.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1GenericKnowledgeOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ImportDocumentsOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ImportDocumentsResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ImportEntityTypesRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ImportEntityTypesResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ImportEntityTypesResponseConflictingResources.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ImportFlowRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ImportFlowResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ImportIntentsRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ImportIntentsResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ImportIntentsResponseConflictingResources.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ImportTestCasesMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ImportTestCasesRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ImportTestCasesResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1InlineDestination.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1InlineSource.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1InputAudioConfig.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Intent.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1IntentCoverage.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1IntentCoverageIntent.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1IntentInput.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1IntentParameter.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1IntentTrainingPhrase.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1IntentTrainingPhrasePart.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1KnowledgeConnectorSettings.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListAgentsResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListChangelogsResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListContinuousTestResultsResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListDeploymentsResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListEntityTypesResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListEnvironmentsResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListExperimentsResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListFlowsResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListGeneratorsResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListIntentsResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListPagesResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListSecuritySettingsResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListSessionEntityTypesResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListTestCaseResultsResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListTestCasesResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListTransitionRouteGroupsResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListVersionsResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListWebhooksResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1LoadVersionRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1LookupEnvironmentHistoryResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Match.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1MatchIntentRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1MatchIntentResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1NluSettings.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1OutputAudioConfig.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Page.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1PageInfo.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1PageInfoFormInfo.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1PageInfoFormInfoParameterInfo.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Phrase.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1QueryInput.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1QueryParameters.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1QueryResult.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ReloadDocumentOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ResourceName.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ResponseMessage.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ResponseMessageConversationSuccess.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ResponseMessageLiveAgentHandoff.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ResponseMessageMixedAudio.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ResponseMessageMixedAudioSegment.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ResponseMessageOutputAudioText.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ResponseMessagePlayAudio.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ResponseMessageTelephonyTransferCall.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ResponseMessageText.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1RestoreAgentRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1RestoreAgentRequestGitSource.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1RolloutConfig.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1RolloutConfigRolloutStep.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1RolloutState.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1RunContinuousTestMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1RunContinuousTestResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1RunTestCaseRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1RunTestCaseResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1SafetySettings.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1SafetySettingsPhrase.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1SearchConfig.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1SecuritySettings.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1SecuritySettingsAudioExportSettings.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1SecuritySettingsInsightsExportSettings.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1SentimentAnalysisResult.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1SessionEntityType.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1SessionInfo.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1SpeechToTextSettings.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1SubmitAnswerFeedbackRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1SynthesizeSpeechConfig.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TestCase.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TestCaseError.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TestCaseResult.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TestConfig.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TestError.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TestRunDifference.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TextInput.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TextToSpeechSettings.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TransitionCoverage.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TransitionCoverageTransition.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TransitionCoverageTransitionNode.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TransitionRoute.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TransitionRouteGroup.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TransitionRouteGroupCoverage.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TransitionRouteGroupCoverageCoverage.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TransitionRouteGroupCoverageCoverageTransition.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TurnSignals.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1UpdateDocumentOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ValidateAgentRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ValidateFlowRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ValidationMessage.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1VariantsHistory.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Version.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1VersionVariants.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1VersionVariantsVariant.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1VoiceSelectionParams.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Webhook.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1WebhookGenericWebService.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1WebhookRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1WebhookRequestFulfillmentInfo.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1WebhookRequestIntentInfo.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1WebhookRequestIntentInfoIntentParameterValue.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1WebhookRequestSentimentAnalysisResult.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1WebhookResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1WebhookResponseFulfillmentResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1WebhookServiceDirectoryConfig.h \
    $${PWD}/OAIGoogleCloudDialogflowV2AnnotatedMessagePart.h \
    $${PWD}/OAIGoogleCloudDialogflowV2ArticleAnswer.h \
    $${PWD}/OAIGoogleCloudDialogflowV2ArticleSuggestionModelMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowV2BatchUpdateEntityTypesResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowV2BatchUpdateIntentsResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowV2ClearSuggestionFeatureConfigOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowV2Context.h \
    $${PWD}/OAIGoogleCloudDialogflowV2ConversationEvent.h \
    $${PWD}/OAIGoogleCloudDialogflowV2ConversationModel.h \
    $${PWD}/OAIGoogleCloudDialogflowV2CreateConversationDatasetOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowV2CreateConversationModelEvaluationOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowV2CreateConversationModelOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowV2DeleteConversationModelOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowV2DeployConversationModelOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowV2EntityType.h \
    $${PWD}/OAIGoogleCloudDialogflowV2EntityTypeEntity.h \
    $${PWD}/OAIGoogleCloudDialogflowV2EventInput.h \
    $${PWD}/OAIGoogleCloudDialogflowV2ExportAgentResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowV2ExportOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowV2FaqAnswer.h \
    $${PWD}/OAIGoogleCloudDialogflowV2GcsDestination.h \
    $${PWD}/OAIGoogleCloudDialogflowV2HumanAgentAssistantEvent.h \
    $${PWD}/OAIGoogleCloudDialogflowV2ImportConversationDataOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowV2ImportConversationDataOperationResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowV2ImportDocumentsResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowV2InputDataset.h \
    $${PWD}/OAIGoogleCloudDialogflowV2Intent.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentFollowupIntentInfo.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessage.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageBasicCard.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageBasicCardButton.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageBasicCardButtonOpenUriAction.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageBrowseCarouselCard.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageBrowseCarouselCardBrowseCarouselCardItem.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageBrowseCarouselCardBrowseCarouselCardItemOpenUrlAction.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageCard.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageCardButton.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageCarouselSelect.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageCarouselSelectItem.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageColumnProperties.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageImage.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageLinkOutSuggestion.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageListSelect.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageListSelectItem.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageMediaContent.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageMediaContentResponseMediaObject.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageQuickReplies.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageSelectItemInfo.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageSimpleResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageSimpleResponses.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageSuggestion.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageSuggestions.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageTableCard.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageTableCardCell.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageTableCardRow.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageText.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentParameter.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentTrainingPhrase.h \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentTrainingPhrasePart.h \
    $${PWD}/OAIGoogleCloudDialogflowV2KnowledgeOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowV2Message.h \
    $${PWD}/OAIGoogleCloudDialogflowV2MessageAnnotation.h \
    $${PWD}/OAIGoogleCloudDialogflowV2OriginalDetectIntentRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowV2QueryResult.h \
    $${PWD}/OAIGoogleCloudDialogflowV2Sentiment.h \
    $${PWD}/OAIGoogleCloudDialogflowV2SentimentAnalysisResult.h \
    $${PWD}/OAIGoogleCloudDialogflowV2SessionEntityType.h \
    $${PWD}/OAIGoogleCloudDialogflowV2SetSuggestionFeatureConfigOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowV2SmartReplyAnswer.h \
    $${PWD}/OAIGoogleCloudDialogflowV2SmartReplyModelMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowV2SuggestArticlesResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowV2SuggestFaqAnswersResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowV2SuggestSmartRepliesResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowV2SuggestionResult.h \
    $${PWD}/OAIGoogleCloudDialogflowV2UndeployConversationModelOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowV2WebhookRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowV2WebhookResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1AnnotatedMessagePart.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1ArticleAnswer.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1BatchUpdateEntityTypesResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1BatchUpdateIntentsResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1ClearSuggestionFeatureConfigOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1Context.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1ConversationEvent.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1DialogflowAssistAnswer.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1EntityType.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1EntityTypeEntity.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1EventInput.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1ExportAgentResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1ExportOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1FaqAnswer.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1GcsDestination.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1HumanAgentAssistantEvent.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1ImportDocumentsResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1Intent.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentFollowupIntentInfo.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessage.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageBasicCard.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageBasicCardButton.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageBasicCardButtonOpenUriAction.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageBrowseCarouselCard.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageBrowseCarouselCardBrowseCarouselCardItem.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageBrowseCarouselCardBrowseCarouselCardItemOpenUrlAction.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageCard.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageCardButton.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageCarouselSelect.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageCarouselSelectItem.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageColumnProperties.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageImage.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageLinkOutSuggestion.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageListSelect.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageListSelectItem.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageMediaContent.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageMediaContentResponseMediaObject.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageQuickReplies.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageRbmCardContent.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageRbmCardContentRbmMedia.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageRbmCarouselCard.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageRbmStandaloneCard.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageRbmSuggestedAction.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageRbmSuggestedActionRbmSuggestedActionDial.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageRbmSuggestedActionRbmSuggestedActionOpenUri.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageRbmSuggestedReply.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageRbmSuggestion.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageRbmText.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageSelectItemInfo.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageSimpleResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageSimpleResponses.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageSuggestion.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageSuggestions.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageTableCard.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageTableCardCell.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageTableCardRow.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageTelephonyPlayAudio.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageTelephonySynthesizeSpeech.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageTelephonyTransferCall.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageText.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentParameter.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentSuggestion.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentTrainingPhrase.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentTrainingPhrasePart.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1KnowledgeAnswers.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1KnowledgeAnswersAnswer.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1KnowledgeOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1Message.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1MessageAnnotation.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1OriginalDetectIntentRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1QueryResult.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1Sentiment.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1SentimentAnalysisResult.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1SessionEntityType.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1SetSuggestionFeatureConfigOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1SmartReplyAnswer.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1SuggestArticlesResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1SuggestDialogflowAssistsResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1SuggestFaqAnswersResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1SuggestSmartRepliesResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1SuggestionResult.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1WebhookRequest.h \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1WebhookResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowV3alpha1ConversationSignals.h \
    $${PWD}/OAIGoogleCloudDialogflowV3alpha1CreateDocumentOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowV3alpha1DeleteDocumentOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowV3alpha1GenericKnowledgeOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowV3alpha1ImportDocumentsOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowV3alpha1ImportDocumentsResponse.h \
    $${PWD}/OAIGoogleCloudDialogflowV3alpha1ReloadDocumentOperationMetadata.h \
    $${PWD}/OAIGoogleCloudDialogflowV3alpha1TurnSignals.h \
    $${PWD}/OAIGoogleCloudDialogflowV3alpha1UpdateDocumentOperationMetadata.h \
    $${PWD}/OAIGoogleCloudLocationListLocationsResponse.h \
    $${PWD}/OAIGoogleCloudLocationLocation.h \
    $${PWD}/OAIGoogleLongrunningListOperationsResponse.h \
    $${PWD}/OAIGoogleLongrunningOperation.h \
    $${PWD}/OAIGoogleRpcStatus.h \
    $${PWD}/OAIGoogleTypeLatLng.h \
# APIs
    $${PWD}/OAIProjectsApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIGoogleCloudDialogflowCxV3AdvancedSettings.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3AdvancedSettingsDtmfSettings.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3AdvancedSettingsLoggingSettings.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3AudioInput.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3BargeInConfig.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3BatchRunTestCasesMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3BatchRunTestCasesResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ContinuousTestResult.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ConversationSignals.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ConversationTurn.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ConversationTurnUserInput.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ConversationTurnVirtualAgentOutput.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3CreateDocumentOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3CreateVersionOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3DataStoreConnection.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3DeleteDocumentOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3DeployFlowMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3DeployFlowResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3DtmfInput.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3Environment.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3EnvironmentTestCasesConfig.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3EnvironmentVersionConfig.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3EnvironmentWebhookConfig.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3EventHandler.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3EventInput.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ExportAgentResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ExportEntityTypesResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ExportFlowResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ExportIntentsResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ExportTestCasesResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3Form.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3FormParameter.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3FormParameterFillBehavior.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3Fulfillment.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3FulfillmentConditionalCases.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3FulfillmentConditionalCasesCase.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3FulfillmentConditionalCasesCaseCaseContent.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3FulfillmentSetParameterAction.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3GcsDestination.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3GenericKnowledgeOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ImportDocumentsOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ImportDocumentsResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ImportEntityTypesResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ImportEntityTypesResponseConflictingResources.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ImportFlowResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ImportIntentsResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ImportIntentsResponseConflictingResources.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ImportTestCasesMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ImportTestCasesResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3InlineDestination.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3InputAudioConfig.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3Intent.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3IntentInput.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3IntentParameter.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3IntentTrainingPhrase.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3IntentTrainingPhrasePart.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3KnowledgeConnectorSettings.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3Page.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3PageInfo.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3PageInfoFormInfo.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3PageInfoFormInfoParameterInfo.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3QueryInput.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ReloadDocumentOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ResponseMessage.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ResponseMessageConversationSuccess.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ResponseMessageLiveAgentHandoff.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ResponseMessageMixedAudio.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ResponseMessageMixedAudioSegment.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ResponseMessageOutputAudioText.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ResponseMessagePlayAudio.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ResponseMessageTelephonyTransferCall.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3ResponseMessageText.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3RunContinuousTestMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3RunContinuousTestResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3RunTestCaseResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3SessionInfo.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3TestCase.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3TestCaseError.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3TestCaseResult.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3TestConfig.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3TestError.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3TestRunDifference.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3TextInput.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3TransitionRoute.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3TurnSignals.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3UpdateDocumentOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3Webhook.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3WebhookGenericWebService.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3WebhookRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3WebhookRequestFulfillmentInfo.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3WebhookRequestIntentInfo.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3WebhookRequestIntentInfoIntentParameterValue.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3WebhookRequestSentimentAnalysisResult.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3WebhookResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3WebhookResponseFulfillmentResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3WebhookServiceDirectoryConfig.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1AdvancedSettings.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1AdvancedSettingsDtmfSettings.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1AdvancedSettingsLoggingSettings.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Agent.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1AgentAnswerFeedbackSettings.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1AgentGenAppBuilderSettings.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1AgentGitIntegrationSettings.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1AgentGitIntegrationSettingsGithubSettings.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1AgentValidationResult.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1AnswerFeedback.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1AnswerFeedbackRatingReason.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1AudioInput.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1BargeInConfig.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1BatchDeleteTestCasesRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1BatchRunTestCasesMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1BatchRunTestCasesRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1BatchRunTestCasesResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1BoostSpec.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1BoostSpecConditionBoostSpec.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1BoostSpecs.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1CalculateCoverageResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Changelog.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1CompareVersionsRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1CompareVersionsResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ContinuousTestResult.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ConversationSignals.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ConversationTurn.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ConversationTurnUserInput.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ConversationTurnVirtualAgentOutput.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1CreateDocumentOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1CreateVersionOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1DataStoreConnection.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1DeleteDocumentOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1DeployFlowMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1DeployFlowRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1DeployFlowResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Deployment.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1DeploymentResult.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1DetectIntentRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1DetectIntentResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1DtmfInput.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1EntityType.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1EntityTypeEntity.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1EntityTypeExcludedPhrase.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Environment.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1EnvironmentTestCasesConfig.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1EnvironmentVersionConfig.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1EnvironmentWebhookConfig.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1EventHandler.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1EventInput.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Experiment.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExperimentDefinition.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExperimentResult.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExperimentResultConfidenceInterval.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExperimentResultMetric.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExperimentResultVersionMetrics.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExportAgentRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExportAgentRequestGitDestination.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExportAgentResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExportEntityTypesRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExportEntityTypesResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExportFlowRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExportFlowResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExportIntentsRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExportIntentsResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExportTestCasesRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ExportTestCasesResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1FilterSpecs.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Flow.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1FlowImportStrategy.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1FlowValidationResult.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Form.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1FormParameter.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1FormParameterFillBehavior.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1FulfillIntentRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1FulfillIntentResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Fulfillment.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1FulfillmentConditionalCases.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1FulfillmentConditionalCasesCase.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1FulfillmentConditionalCasesCaseCaseContent.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1FulfillmentSetParameterAction.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1GcsDestination.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1GenerativeSettings.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1GenerativeSettingsFallbackSettings.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1GenerativeSettingsFallbackSettingsPromptTemplate.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1GenerativeSettingsKnowledgeConnectorSettings.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Generator.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1GeneratorPlaceholder.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1GenericKnowledgeOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ImportDocumentsOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ImportDocumentsResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ImportEntityTypesRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ImportEntityTypesResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ImportEntityTypesResponseConflictingResources.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ImportFlowRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ImportFlowResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ImportIntentsRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ImportIntentsResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ImportIntentsResponseConflictingResources.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ImportTestCasesMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ImportTestCasesRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ImportTestCasesResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1InlineDestination.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1InlineSource.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1InputAudioConfig.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Intent.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1IntentCoverage.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1IntentCoverageIntent.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1IntentInput.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1IntentParameter.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1IntentTrainingPhrase.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1IntentTrainingPhrasePart.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1KnowledgeConnectorSettings.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListAgentsResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListChangelogsResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListContinuousTestResultsResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListDeploymentsResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListEntityTypesResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListEnvironmentsResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListExperimentsResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListFlowsResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListGeneratorsResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListIntentsResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListPagesResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListSecuritySettingsResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListSessionEntityTypesResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListTestCaseResultsResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListTestCasesResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListTransitionRouteGroupsResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListVersionsResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ListWebhooksResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1LoadVersionRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1LookupEnvironmentHistoryResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Match.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1MatchIntentRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1MatchIntentResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1NluSettings.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1OutputAudioConfig.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Page.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1PageInfo.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1PageInfoFormInfo.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1PageInfoFormInfoParameterInfo.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Phrase.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1QueryInput.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1QueryParameters.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1QueryResult.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ReloadDocumentOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ResourceName.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ResponseMessage.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ResponseMessageConversationSuccess.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ResponseMessageLiveAgentHandoff.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ResponseMessageMixedAudio.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ResponseMessageMixedAudioSegment.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ResponseMessageOutputAudioText.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ResponseMessagePlayAudio.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ResponseMessageTelephonyTransferCall.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ResponseMessageText.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1RestoreAgentRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1RestoreAgentRequestGitSource.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1RolloutConfig.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1RolloutConfigRolloutStep.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1RolloutState.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1RunContinuousTestMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1RunContinuousTestResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1RunTestCaseRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1RunTestCaseResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1SafetySettings.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1SafetySettingsPhrase.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1SearchConfig.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1SecuritySettings.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1SecuritySettingsAudioExportSettings.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1SecuritySettingsInsightsExportSettings.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1SentimentAnalysisResult.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1SessionEntityType.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1SessionInfo.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1SpeechToTextSettings.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1SubmitAnswerFeedbackRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1SynthesizeSpeechConfig.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TestCase.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TestCaseError.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TestCaseResult.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TestConfig.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TestError.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TestRunDifference.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TextInput.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TextToSpeechSettings.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TransitionCoverage.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TransitionCoverageTransition.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TransitionCoverageTransitionNode.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TransitionRoute.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TransitionRouteGroup.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TransitionRouteGroupCoverage.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TransitionRouteGroupCoverageCoverage.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TransitionRouteGroupCoverageCoverageTransition.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1TurnSignals.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1UpdateDocumentOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ValidateAgentRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ValidateFlowRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1ValidationMessage.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1VariantsHistory.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Version.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1VersionVariants.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1VersionVariantsVariant.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1VoiceSelectionParams.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1Webhook.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1WebhookGenericWebService.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1WebhookRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1WebhookRequestFulfillmentInfo.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1WebhookRequestIntentInfo.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1WebhookRequestIntentInfoIntentParameterValue.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1WebhookRequestSentimentAnalysisResult.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1WebhookResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1WebhookResponseFulfillmentResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowCxV3beta1WebhookServiceDirectoryConfig.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2AnnotatedMessagePart.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2ArticleAnswer.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2ArticleSuggestionModelMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2BatchUpdateEntityTypesResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2BatchUpdateIntentsResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2ClearSuggestionFeatureConfigOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2Context.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2ConversationEvent.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2ConversationModel.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2CreateConversationDatasetOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2CreateConversationModelEvaluationOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2CreateConversationModelOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2DeleteConversationModelOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2DeployConversationModelOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2EntityType.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2EntityTypeEntity.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2EventInput.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2ExportAgentResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2ExportOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2FaqAnswer.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2GcsDestination.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2HumanAgentAssistantEvent.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2ImportConversationDataOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2ImportConversationDataOperationResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2ImportDocumentsResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2InputDataset.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2Intent.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentFollowupIntentInfo.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessage.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageBasicCard.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageBasicCardButton.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageBasicCardButtonOpenUriAction.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageBrowseCarouselCard.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageBrowseCarouselCardBrowseCarouselCardItem.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageBrowseCarouselCardBrowseCarouselCardItemOpenUrlAction.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageCard.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageCardButton.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageCarouselSelect.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageCarouselSelectItem.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageColumnProperties.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageImage.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageLinkOutSuggestion.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageListSelect.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageListSelectItem.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageMediaContent.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageMediaContentResponseMediaObject.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageQuickReplies.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageSelectItemInfo.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageSimpleResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageSimpleResponses.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageSuggestion.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageSuggestions.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageTableCard.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageTableCardCell.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageTableCardRow.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentMessageText.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentParameter.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentTrainingPhrase.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2IntentTrainingPhrasePart.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2KnowledgeOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2Message.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2MessageAnnotation.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2OriginalDetectIntentRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2QueryResult.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2Sentiment.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2SentimentAnalysisResult.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2SessionEntityType.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2SetSuggestionFeatureConfigOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2SmartReplyAnswer.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2SmartReplyModelMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2SuggestArticlesResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2SuggestFaqAnswersResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2SuggestSmartRepliesResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2SuggestionResult.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2UndeployConversationModelOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2WebhookRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2WebhookResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1AnnotatedMessagePart.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1ArticleAnswer.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1BatchUpdateEntityTypesResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1BatchUpdateIntentsResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1ClearSuggestionFeatureConfigOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1Context.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1ConversationEvent.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1DialogflowAssistAnswer.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1EntityType.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1EntityTypeEntity.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1EventInput.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1ExportAgentResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1ExportOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1FaqAnswer.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1GcsDestination.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1HumanAgentAssistantEvent.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1ImportDocumentsResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1Intent.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentFollowupIntentInfo.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessage.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageBasicCard.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageBasicCardButton.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageBasicCardButtonOpenUriAction.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageBrowseCarouselCard.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageBrowseCarouselCardBrowseCarouselCardItem.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageBrowseCarouselCardBrowseCarouselCardItemOpenUrlAction.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageCard.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageCardButton.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageCarouselSelect.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageCarouselSelectItem.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageColumnProperties.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageImage.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageLinkOutSuggestion.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageListSelect.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageListSelectItem.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageMediaContent.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageMediaContentResponseMediaObject.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageQuickReplies.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageRbmCardContent.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageRbmCardContentRbmMedia.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageRbmCarouselCard.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageRbmStandaloneCard.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageRbmSuggestedAction.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageRbmSuggestedActionRbmSuggestedActionDial.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageRbmSuggestedActionRbmSuggestedActionOpenUri.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageRbmSuggestedReply.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageRbmSuggestion.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageRbmText.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageSelectItemInfo.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageSimpleResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageSimpleResponses.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageSuggestion.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageSuggestions.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageTableCard.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageTableCardCell.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageTableCardRow.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageTelephonyPlayAudio.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageTelephonySynthesizeSpeech.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageTelephonyTransferCall.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentMessageText.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentParameter.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentSuggestion.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentTrainingPhrase.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1IntentTrainingPhrasePart.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1KnowledgeAnswers.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1KnowledgeAnswersAnswer.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1KnowledgeOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1Message.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1MessageAnnotation.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1OriginalDetectIntentRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1QueryResult.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1Sentiment.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1SentimentAnalysisResult.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1SessionEntityType.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1SetSuggestionFeatureConfigOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1SmartReplyAnswer.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1SuggestArticlesResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1SuggestDialogflowAssistsResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1SuggestFaqAnswersResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1SuggestSmartRepliesResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1SuggestionResult.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1WebhookRequest.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV2beta1WebhookResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV3alpha1ConversationSignals.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV3alpha1CreateDocumentOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV3alpha1DeleteDocumentOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV3alpha1GenericKnowledgeOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV3alpha1ImportDocumentsOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV3alpha1ImportDocumentsResponse.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV3alpha1ReloadDocumentOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV3alpha1TurnSignals.cpp \
    $${PWD}/OAIGoogleCloudDialogflowV3alpha1UpdateDocumentOperationMetadata.cpp \
    $${PWD}/OAIGoogleCloudLocationListLocationsResponse.cpp \
    $${PWD}/OAIGoogleCloudLocationLocation.cpp \
    $${PWD}/OAIGoogleLongrunningListOperationsResponse.cpp \
    $${PWD}/OAIGoogleLongrunningOperation.cpp \
    $${PWD}/OAIGoogleRpcStatus.cpp \
    $${PWD}/OAIGoogleTypeLatLng.cpp \
# APIs
    $${PWD}/OAIProjectsApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
