openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: Reads and writes Google Forms and responses.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Google Forms API
  version: v1
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://upload.wikimedia.org/wikipedia/commons/e/e1/YouTube_play_buttom_icon_%282013-2017%29.svg
  x-origin:
  - format: google
    url: https://forms.googleapis.com/$discovery/rest?version=v1
    version: v1
  x-providerName: googleapis.com
  x-serviceName: forms
servers:
- url: https://forms.googleapis.com/
tags:
- name: forms
paths:
  /v1/forms:
    post:
      description: "Create a new form using the title given in the provided form message\
        \ in the request. *Important:* Only the form.info.title and form.info.document_title\
        \ fields are copied to the new form. All other fields including the form description,\
        \ items and settings are disallowed. To create a new form and add items, you\
        \ must first call forms.create to create an empty form with a title and (optional)\
        \ document title, and then call forms.update to add the items."
      operationId: forms_forms_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/forms.body
        Oauth2c:
        - https://www.googleapis.com/auth/forms.body
      tags:
      - forms
      x-openapi-router-controller: openapi_server.controllers.forms_controller
  /v1/forms/{formId}:
    get:
      description: Get a form.
      operationId: forms_forms_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/forms.body
        Oauth2c:
        - https://www.googleapis.com/auth/forms.body
      - Oauth2:
        - https://www.googleapis.com/auth/forms.body.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/forms.body.readonly
      tags:
      - forms
      x-openapi-router-controller: openapi_server.controllers.forms_controller
  /v1/forms/{formId}/responses:
    get:
      description: List a form's responses.
      operationId: forms_forms_responses_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/forms.responses.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/forms.responses.readonly
      tags:
      - forms
      x-openapi-router-controller: openapi_server.controllers.forms_controller
  /v1/forms/{formId}/responses/{responseId}:
    get:
      description: Get one response from the form.
      operationId: forms_forms_responses_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/forms.responses.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/forms.responses.readonly
      tags:
      - forms
      x-openapi-router-controller: openapi_server.controllers.forms_controller
  /v1/forms/{formId}/watches:
    get:
      description: "Return a list of the watches owned by the invoking project. The\
        \ maximum number of watches is two: For each invoker, the limit is one for\
        \ each event type per form."
      operationId: forms_forms_watches_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/forms.body
        Oauth2c:
        - https://www.googleapis.com/auth/forms.body
      - Oauth2:
        - https://www.googleapis.com/auth/forms.body.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/forms.body.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/forms.responses.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/forms.responses.readonly
      tags:
      - forms
      x-openapi-router-controller: openapi_server.controllers.forms_controller
    post:
      description: "Create a new watch. If a watch ID is provided, it must be unused.\
        \ For each invoking project, the per form limit is one watch per Watch.EventType.\
        \ A watch expires seven days after it is created (see Watch.expire_time)."
      operationId: forms_forms_watches_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/forms.body
        Oauth2c:
        - https://www.googleapis.com/auth/forms.body
      - Oauth2:
        - https://www.googleapis.com/auth/forms.body.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/forms.body.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/forms.responses.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/forms.responses.readonly
      tags:
      - forms
      x-openapi-router-controller: openapi_server.controllers.forms_controller
  /v1/forms/{formId}/watches/{watchId}:
    delete:
      description: Delete a watch.
      operationId: forms_forms_watches_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/forms.body
        Oauth2c:
        - https://www.googleapis.com/auth/forms.body
      - Oauth2:
        - https://www.googleapis.com/auth/forms.body.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/forms.body.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/forms.responses.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/forms.responses.readonly
      tags:
      - forms
      x-openapi-router-controller: openapi_server.controllers.forms_controller
  /v1/forms/{formId}/watches/{watchId}:renew:
    post:
      description: "Renew an existing watch for seven days. The state of the watch\
        \ after renewal is `ACTIVE`, and the `expire_time` is seven days from the\
        \ renewal. Renewing a watch in an error state (e.g. `SUSPENDED`) succeeds\
        \ if the error is no longer present, but fail otherwise. After a watch has\
        \ expired, RenewWatch returns `NOT_FOUND`."
      operationId: forms_forms_watches_renew
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/forms.body
        Oauth2c:
        - https://www.googleapis.com/auth/forms.body
      - Oauth2:
        - https://www.googleapis.com/auth/forms.body.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/forms.body.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/forms.responses.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/forms.responses.readonly
      tags:
      - forms
      x-openapi-router-controller: openapi_server.controllers.forms_controller
  /v1/forms/{formId}:batchUpdate:
    post:
      description: Change the form with a batch of updates.
      operationId: forms_forms_batch_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
        Oauth2c:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
        Oauth2c:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/forms.body
        Oauth2c:
        - https://www.googleapis.com/auth/forms.body
      tags:
      - forms
      x-openapi-router-controller: openapi_server.controllers.forms_controller
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/drive: "See, edit, create, and delete\
              \ all of your Google Drive files"
            https://www.googleapis.com/auth/drive.file: "See, edit, create, and delete\
              \ only the specific Google Drive files you use with this app"
            https://www.googleapis.com/auth/drive.readonly: See and download all your
              Google Drive files
            https://www.googleapis.com/auth/forms.body: "See, edit, create, and delete\
              \ all your Google Forms forms"
            https://www.googleapis.com/auth/forms.body.readonly: See all your Google
              Forms forms
            https://www.googleapis.com/auth/forms.responses.readonly: See all responses
              to your Google Forms forms
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/drive: "See, edit, create, and delete\
              \ all of your Google Drive files"
            https://www.googleapis.com/auth/drive.file: "See, edit, create, and delete\
              \ only the specific Google Drive files you use with this app"
            https://www.googleapis.com/auth/drive.readonly: See and download all your
              Google Drive files
            https://www.googleapis.com/auth/forms.body: "See, edit, create, and delete\
              \ all your Google Forms forms"
            https://www.googleapis.com/auth/forms.body.readonly: See all your Google
              Forms forms
            https://www.googleapis.com/auth/forms.responses.readonly: See all responses
              to your Google Forms forms
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2c
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2c
