QT += network

HEADERS += \
# Models
    $${PWD}/OAIAccountInfo.h \
    $${PWD}/OAIAccountInfoLinks.h \
    $${PWD}/OAIAccountPublications.h \
    $${PWD}/OAIAccountPublicationsLinks.h \
    $${PWD}/OAIAccountStatus.h \
    $${PWD}/OAIAccountSynchronization.h \
    $${PWD}/OAIAccountSynchronizationList.h \
    $${PWD}/OAIActivateSubscriptionRequest.h \
    $${PWD}/OAIAddChannelCatalogRequest.h \
    $${PWD}/OAIAnalyticsIndex.h \
    $${PWD}/OAIAnalyticsIndexLinks.h \
    $${PWD}/OAIAnalyticsIndexLovLinks.h \
    $${PWD}/OAIAnalyticsProductColumnFilter.h \
    $${PWD}/OAIAnalyticsProductColumnFilters.h \
    $${PWD}/OAIAnalyticsStoreIndex.h \
    $${PWD}/OAIAnalyticsStoreIndexLinks.h \
    $${PWD}/OAIApiCredential.h \
    $${PWD}/OAIApiCredentials.h \
    $${PWD}/OAIAutoImportConfiguration.h \
    $${PWD}/OAIAutoImportConfigurationLinks.h \
    $${PWD}/OAIAutomaticTransition.h \
    $${PWD}/OAIAutomaticTransitionInfo.h \
    $${PWD}/OAIAutomaticTransitionInfoLinks.h \
    $${PWD}/OAIAutomaticTransitionInfoList.h \
    $${PWD}/OAIAutomaticTransitionInfoListLinks.h \
    $${PWD}/OAIBatchOrderOperationResponse.h \
    $${PWD}/OAIBeezUPColumnConfiguration.h \
    $${PWD}/OAIBeezUP_Common_AdditionalProductFiltersValue.h \
    $${PWD}/OAIBeezUP_Common_ApiSettingsStatus.h \
    $${PWD}/OAIBeezUP_Common_CatalogCategoryFilter.h \
    $${PWD}/OAIBeezUP_Common_ChannelBasicInfo.h \
    $${PWD}/OAIBeezUP_Common_ChannelCategoryFilter.h \
    $${PWD}/OAIBeezUP_Common_ColumnDataType.h \
    $${PWD}/OAIBeezUP_Common_ColumnImportance.h \
    $${PWD}/OAIBeezUP_Common_ErrorResponseMessage.h \
    $${PWD}/OAIBeezUP_Common_ErrorSummary.h \
    $${PWD}/OAIBeezUP_Common_ExceptionDetail.h \
    $${PWD}/OAIBeezUP_Common_HttpMethod.h \
    $${PWD}/OAIBeezUP_Common_InfoSummaries.h \
    $${PWD}/OAIBeezUP_Common_InfoSummary.h \
    $${PWD}/OAIBeezUP_Common_LOVLink3.h \
    $${PWD}/OAIBeezUP_Common_Link3.h \
    $${PWD}/OAIBeezUP_Common_LinkParameter3.h \
    $${PWD}/OAIBeezUP_Common_LinkParameterProperty3.h \
    $${PWD}/OAIBeezUP_Common_ListOfValueItem.h \
    $${PWD}/OAIBeezUP_Common_PaginationResult.h \
    $${PWD}/OAIBeezUP_Common_PaginationResultLinks.h \
    $${PWD}/OAIBeezUP_Common_ParameterIn.h \
    $${PWD}/OAIBeezUP_Common_ParameterType.h \
    $${PWD}/OAIBeezUP_Common_ProductBasicInfo.h \
    $${PWD}/OAIBeezUP_Common_SuccessSummary.h \
    $${PWD}/OAIBeezUP_Common_UserErrorMessage.h \
    $${PWD}/OAIBeezUP_Common_UserErrorMessage_arguments_inner.h \
    $${PWD}/OAIBeezUP_Common_WarningSummary.h \
    $${PWD}/OAIBillingPeriod.h \
    $${PWD}/OAIBillingPeriodList.h \
    $${PWD}/OAIBillingPeriodListLinks.h \
    $${PWD}/OAIBonusInfo.h \
    $${PWD}/OAIBonusType.h \
    $${PWD}/OAICatalogColumn.h \
    $${PWD}/OAICatalogColumnLinks.h \
    $${PWD}/OAICatalogColumnList.h \
    $${PWD}/OAICatalogIndex.h \
    $${PWD}/OAICatalogIndexLOVLinks.h \
    $${PWD}/OAICatalogIndexLinks.h \
    $${PWD}/OAICatalogStoreIndex.h \
    $${PWD}/OAICatalogStoreIndexLinks.h \
    $${PWD}/OAICatalogStoreIndexList.h \
    $${PWD}/OAICatalogStoreStatus.h \
    $${PWD}/OAICategory.h \
    $${PWD}/OAICategoryList.h \
    $${PWD}/OAICategoryMappingState.h \
    $${PWD}/OAICategoryMappingStatus.h \
    $${PWD}/OAIChangeCustomColumnExpressionRequest.h \
    $${PWD}/OAIChangeCustomColumnRequest.h \
    $${PWD}/OAIChangeEmailRequest.h \
    $${PWD}/OAIChangeOrderListRequest.h \
    $${PWD}/OAIChangeOrderListRequestItem.h \
    $${PWD}/OAIChangeOrderListRequestItemV2.h \
    $${PWD}/OAIChangeOrderListRequestV2.h \
    $${PWD}/OAIChangeOrderReporting.h \
    $${PWD}/OAIChangePasswordRequest.h \
    $${PWD}/OAIChangeUserColumnNameRequest.h \
    $${PWD}/OAIChannelCatalog.h \
    $${PWD}/OAIChannelCatalogCategoryConfiguration.h \
    $${PWD}/OAIChannelCatalogCategoryConfigurationInfo.h \
    $${PWD}/OAIChannelCatalogCategoryConfigurationList.h \
    $${PWD}/OAIChannelCatalogCategoryMappingInfoLinks.h \
    $${PWD}/OAIChannelCatalogCategoryMappingSettings.h \
    $${PWD}/OAIChannelCatalogCategoryMappingsLinks.h \
    $${PWD}/OAIChannelCatalogColumnMapping.h \
    $${PWD}/OAIChannelCatalogColumnMappingWithName.h \
    $${PWD}/OAIChannelCatalogExportCacheInfo.h \
    $${PWD}/OAIChannelCatalogExportCacheInfoResponse.h \
    $${PWD}/OAIChannelCatalogExportCacheInfoResponseLinks.h \
    $${PWD}/OAIChannelCatalogExportationHistory.h \
    $${PWD}/OAIChannelCatalogExportationHistoryLinks.h \
    $${PWD}/OAIChannelCatalogExportationReporting.h \
    $${PWD}/OAIChannelCatalogLinks.h \
    $${PWD}/OAIChannelCatalogList.h \
    $${PWD}/OAIChannelCatalogListLinks.h \
    $${PWD}/OAIChannelCatalogListLovLinks.h \
    $${PWD}/OAIChannelCatalogMarketplaceBooleanProperty.h \
    $${PWD}/OAIChannelCatalogMarketplaceBooleanSetting.h \
    $${PWD}/OAIChannelCatalogMarketplaceIntegerProperty.h \
    $${PWD}/OAIChannelCatalogMarketplaceIntegerSetting.h \
    $${PWD}/OAIChannelCatalogMarketplaceNumberProperty.h \
    $${PWD}/OAIChannelCatalogMarketplaceNumberSetting.h \
    $${PWD}/OAIChannelCatalogMarketplaceProperties.h \
    $${PWD}/OAIChannelCatalogMarketplacePropertiesLinks.h \
    $${PWD}/OAIChannelCatalogMarketplaceProperty.h \
    $${PWD}/OAIChannelCatalogMarketplacePropertyDiscriminatorType.h \
    $${PWD}/OAIChannelCatalogMarketplacePropertyGroup.h \
    $${PWD}/OAIChannelCatalogMarketplaceSetting.h \
    $${PWD}/OAIChannelCatalogMarketplaceSettingDiscriminatorType.h \
    $${PWD}/OAIChannelCatalogMarketplaceSettings.h \
    $${PWD}/OAIChannelCatalogMarketplaceSettingsLinks.h \
    $${PWD}/OAIChannelCatalogMarketplaceStringProperty.h \
    $${PWD}/OAIChannelCatalogMarketplaceStringSetting.h \
    $${PWD}/OAIChannelCatalogProductByChannelCatalogRequest.h \
    $${PWD}/OAIChannelCatalogProductByChannelCatalogResponse.h \
    $${PWD}/OAIChannelCatalogProductFilters.h \
    $${PWD}/OAIChannelCatalogProductInfo.h \
    $${PWD}/OAIChannelCatalogProductInfoLinks.h \
    $${PWD}/OAIChannelCatalogProductInfoList.h \
    $${PWD}/OAIChannelCatalogProductInfoListLinks.h \
    $${PWD}/OAIChannelCatalogProductsCounters.h \
    $${PWD}/OAIChannelCatalogState.h \
    $${PWD}/OAIChannelCategory.h \
    $${PWD}/OAIChannelCategoryColumnOverride.h \
    $${PWD}/OAIChannelCategorySettings.h \
    $${PWD}/OAIChannelColumn.h \
    $${PWD}/OAIChannelColumnConfiguration.h \
    $${PWD}/OAIChannelCostSettings.h \
    $${PWD}/OAIChannelFirstLevelCategory.h \
    $${PWD}/OAIChannelHeader.h \
    $${PWD}/OAIChannelHeaderLinks.h \
    $${PWD}/OAIChannelInfo.h \
    $${PWD}/OAIChannelInfo_details.h \
    $${PWD}/OAIChannelInfo_keyNumbers.h \
    $${PWD}/OAIChannelInfo_salesContact.h \
    $${PWD}/OAIChannelInfo_technicalContact.h \
    $${PWD}/OAIChannelRootCategory.h \
    $${PWD}/OAIClearMerchantOrderInfoListRequest.h \
    $${PWD}/OAIClickIncludedAndAdditionalClickPrice.h \
    $${PWD}/OAIClickIncludedAndVariablePrice.h \
    $${PWD}/OAIColumnConfiguration.h \
    $${PWD}/OAIColumnMappingStatus.h \
    $${PWD}/OAICompanyInfo.h \
    $${PWD}/OAICompareOptions.h \
    $${PWD}/OAICompressionFormatStrategy.h \
    $${PWD}/OAIComputeExpressionRequest.h \
    $${PWD}/OAIConfigureAutoImportIntervalRequest.h \
    $${PWD}/OAIConfigureAutomaticTransitionRequest.h \
    $${PWD}/OAIConfigureCatalogColumnCatalogRequest.h \
    $${PWD}/OAIConfigureCategoryRequest.h \
    $${PWD}/OAIConsumptionAvailabilityStatus.h \
    $${PWD}/OAIContractBillingPeriodInfo.h \
    $${PWD}/OAIContractBonusInfo.h \
    $${PWD}/OAIContractClickInfo.h \
    $${PWD}/OAIContractCommitmentInfo.h \
    $${PWD}/OAIContractDiscountInfo.h \
    $${PWD}/OAIContractInfo.h \
    $${PWD}/OAIContractMoneyInfo.h \
    $${PWD}/OAIContractStoreInfo.h \
    $${PWD}/OAIContracts.h \
    $${PWD}/OAIContractsLinks.h \
    $${PWD}/OAICopyOptimisationRequest.h \
    $${PWD}/OAICopyOptimisationResponse.h \
    $${PWD}/OAICostSettings.h \
    $${PWD}/OAICostStatus.h \
    $${PWD}/OAICostType.h \
    $${PWD}/OAICreateContract.h \
    $${PWD}/OAICreateContractResponse.h \
    $${PWD}/OAICreateContractResponseLinks.h \
    $${PWD}/OAICreateCustomColumnRequest.h \
    $${PWD}/OAICreateRuleRequest.h \
    $${PWD}/OAICreateStoreRequest.h \
    $${PWD}/OAICreateSubscriptionRequest.h \
    $${PWD}/OAICredential.h \
    $${PWD}/OAICreditCardInfo.h \
    $${PWD}/OAICreditCardInfoResponse.h \
    $${PWD}/OAICreditCardInfoResponseLinks.h \
    $${PWD}/OAICreditCardInfoWithCardType.h \
    $${PWD}/OAICurrentContractInfo.h \
    $${PWD}/OAICurrentContractInfoLinks.h \
    $${PWD}/OAICustomColumn.h \
    $${PWD}/OAICustomColumnLinks.h \
    $${PWD}/OAICustomColumnList.h \
    $${PWD}/OAICustomColumnListLinks.h \
    $${PWD}/OAICustomerIndex.h \
    $${PWD}/OAICustomerIndexLinks.h \
    $${PWD}/OAICustomerIndexLovLinks.h \
    $${PWD}/OAIDateSearchType.h \
    $${PWD}/OAIDetectedCatalogColumn.h \
    $${PWD}/OAIDetectedCatalogColumnLinks.h \
    $${PWD}/OAIDetectedCatalogColumnList.h \
    $${PWD}/OAIDetectedCatalogColumnListLinks.h \
    $${PWD}/OAIDownloadCatalogStrategy.h \
    $${PWD}/OAIDuplicateProductValueConfiguration.h \
    $${PWD}/OAIDuplicateProductValueStrategy.h \
    $${PWD}/OAIErrorResponseMessage.h \
    $${PWD}/OAIErrorResponseMessagePaymentRequired.h \
    $${PWD}/OAIErrorResponseMessagePaymentRequiredLinks.h \
    $${PWD}/OAIErrorSummary.h \
    $${PWD}/OAIExceptionDetail.h \
    $${PWD}/OAIExchangedMessagesItem.h \
    $${PWD}/OAIExclusionFilter.h \
    $${PWD}/OAIExclusionFiltersResponse.h \
    $${PWD}/OAIExclusionFiltersResponseLinks.h \
    $${PWD}/OAIExportOrderListFormat.h \
    $${PWD}/OAIExportOrderListRequest.h \
    $${PWD}/OAIExternalLinks_Catalog_GetBeezUPColumnsLink.h \
    $${PWD}/OAIExternalLinks_GetChannelCatalogMarketplaceSettingsLink.h \
    $${PWD}/OAIExternalLinks_GetChannelInfoLink.h \
    $${PWD}/OAIExternalLinks_GetExternalConfigurationPageLink.h \
    $${PWD}/OAIFeedType.h \
    $${PWD}/OAIFileFormatStrategy.h \
    $${PWD}/OAIFilterOperator.h \
    $${PWD}/OAIFilterOperatorDataType.h \
    $${PWD}/OAIFixedAndVariableClickModelInfo.h \
    $${PWD}/OAIFunctionality.h \
    $${PWD}/OAIFunctionalityRightInfo.h \
    $${PWD}/OAIGeneralSettings.h \
    $${PWD}/OAIGenerateBatchOrderInvoiceErrorResponseItem.h \
    $${PWD}/OAIGenerateBatchOrderInvoiceErrorResponseItemDetail.h \
    $${PWD}/OAIGenerateBatchOrderInvoiceRequestItem.h \
    $${PWD}/OAIGenerateOrderInvoiceRequest.h \
    $${PWD}/OAIGenerateOrderInvoiceResponse.h \
    $${PWD}/OAIGetChannelCatalogProductInfoListRequest.h \
    $${PWD}/OAIGetImportationProductsReportRequest.h \
    $${PWD}/OAIGetImportationProductsReportRequestErrorCode.h \
    $${PWD}/OAIGetImportationProductsReportResponse.h \
    $${PWD}/OAIGetImportationReportResponse.h \
    $${PWD}/OAIGetImportationReportResponseDiff.h \
    $${PWD}/OAIGetImportationReportResponseError.h \
    $${PWD}/OAIGetImportationReportResponseImportationInfo.h \
    $${PWD}/OAIGetImportationReportResponseProductMetrics.h \
    $${PWD}/OAIGetOrderInvoiceDesignPreviewResponse.h \
    $${PWD}/OAIGetOrderInvoiceGeneralSettingsResponse.h \
    $${PWD}/OAIGetOrderInvoicePdfFromHtmlInvoiceUrlRequest.h \
    $${PWD}/OAIGetProductsRequest.h \
    $${PWD}/OAIHarvestOrderReporting.h \
    $${PWD}/OAIHttpMethod.h \
    $${PWD}/OAIImportAlreadyInProgressResponse.h \
    $${PWD}/OAIImportAlreadyInProgressResponseLinks.h \
    $${PWD}/OAIImportationCustomColumn.h \
    $${PWD}/OAIImportationCustomColumnLinks.h \
    $${PWD}/OAIImportationCustomColumnList.h \
    $${PWD}/OAIImportationCustomColumnListLinks.h \
    $${PWD}/OAIImportationMonitoring.h \
    $${PWD}/OAIImportationMonitoringLinks.h \
    $${PWD}/OAIImportationReporting.h \
    $${PWD}/OAIImportationReportingLinks.h \
    $${PWD}/OAIImportationTechnicalProgression.h \
    $${PWD}/OAIImportationsResponse.h \
    $${PWD}/OAIImportationsResponseLinks.h \
    $${PWD}/OAIInfoSummaries.h \
    $${PWD}/OAIInfoSummary.h \
    $${PWD}/OAIInputConfiguration.h \
    $${PWD}/OAIInputFileConfiguration.h \
    $${PWD}/OAIInputFileFetchConfiguration.h \
    $${PWD}/OAIInputFileReadConfiguration.h \
    $${PWD}/OAIInputFileReadCsvConfiguration.h \
    $${PWD}/OAIInputFileReadXmlConfiguration.h \
    $${PWD}/OAIInvoice.h \
    $${PWD}/OAIInvoiceList.h \
    $${PWD}/OAIInvoiceListLinks.h \
    $${PWD}/OAIInvoicePaymentStatus.h \
    $${PWD}/OAILOVLink3.h \
    $${PWD}/OAILastManualImportInputConfiguration.h \
    $${PWD}/OAILegacyTrackingChannelCatalog.h \
    $${PWD}/OAILegacyTrackingChannelCatalogLinks.h \
    $${PWD}/OAILegacyTrackingChannelCatalogList.h \
    $${PWD}/OAILegacyTrackingChannelCatalogListLinks.h \
    $${PWD}/OAILink3.h \
    $${PWD}/OAILinkClickToOrderType.h \
    $${PWD}/OAILinkParameter3.h \
    $${PWD}/OAILinkParameterProperty3.h \
    $${PWD}/OAILinks_AddChannelCatalogLink.h \
    $${PWD}/OAILinks_AnalyticsIndexLink.h \
    $${PWD}/OAILinks_Auto_ConfigureAutoImportIntervalLink.h \
    $${PWD}/OAILinks_Auto_GetAutoImportConfigurationLink.h \
    $${PWD}/OAILinks_Auto_PauseAutoImportLink.h \
    $${PWD}/OAILinks_Auto_ResumeAutoImportLink.h \
    $${PWD}/OAILinks_Auto_ScheduleAutoImportLink.h \
    $${PWD}/OAILinks_Auto_StartAutoImportLink.h \
    $${PWD}/OAILinks_CatalogIndexLink.h \
    $${PWD}/OAILinks_CatalogStoreIndexLink.h \
    $${PWD}/OAILinks_Catalog_ChangeCatalogColumnUserNameLink.h \
    $${PWD}/OAILinks_Catalog_ChangeCustomColumnExpressionLink.h \
    $${PWD}/OAILinks_Catalog_ChangeCustomColumnUserNameLink.h \
    $${PWD}/OAILinks_Catalog_ComputeExpressionLink.h \
    $${PWD}/OAILinks_Catalog_DeleteCustomColumnLink.h \
    $${PWD}/OAILinks_Catalog_GetBeezUPColumnsLink.h \
    $${PWD}/OAILinks_Catalog_GetCatalogColumnsLink.h \
    $${PWD}/OAILinks_Catalog_GetCategoriesLink.h \
    $${PWD}/OAILinks_Catalog_GetCustomColumnExpressionLink.h \
    $${PWD}/OAILinks_Catalog_GetCustomColumnsLink.h \
    $${PWD}/OAILinks_Catalog_GetProductsLink.h \
    $${PWD}/OAILinks_Catalog_GetRandomProductsLink.h \
    $${PWD}/OAILinks_Catalog_SaveCustomColumnLink.h \
    $${PWD}/OAILinks_ChangeOrderLink.h \
    $${PWD}/OAILinks_ChangeOrderV3Link.h \
    $${PWD}/OAILinks_ClearChannelCatalogExportationCacheLink.h \
    $${PWD}/OAILinks_ClearMerchantOrderInfoLink.h \
    $${PWD}/OAILinks_ClearMerchantOrderInfoListLink.h \
    $${PWD}/OAILinks_ClearMerchantOrderInfoListV3Link.h \
    $${PWD}/OAILinks_ClearMerchantOrderInfoV3Link.h \
    $${PWD}/OAILinks_ConfigureAutomaticTransitionsLink.h \
    $${PWD}/OAILinks_ConfigureChannelCatalogCategoryLink.h \
    $${PWD}/OAILinks_ConfigureChannelCatalogColumnMappingsLink.h \
    $${PWD}/OAILinks_ConfigureChannelCatalogCostSettingsLink.h \
    $${PWD}/OAILinks_ConfigureChannelCatalogExclusionFiltersCopyLink.h \
    $${PWD}/OAILinks_ConfigureChannelCatalogExclusionFiltersLink.h \
    $${PWD}/OAILinks_ConfigureChannelCatalogGeneralSettingsLink.h \
    $${PWD}/OAILinks_ConfigureChannelCatalogProductValueOverrideCopyLink.h \
    $${PWD}/OAILinks_CreateRuleLink.h \
    $${PWD}/OAILinks_DeleteChannelCatalogLink.h \
    $${PWD}/OAILinks_DeleteReportFilterLink.h \
    $${PWD}/OAILinks_DeleteRuleLink.h \
    $${PWD}/OAILinks_DisableChannelCatalogCategoryMappingLink.h \
    $${PWD}/OAILinks_DisableChannelCatalogLink.h \
    $${PWD}/OAILinks_DisableChannelCatalogProductLink.h \
    $${PWD}/OAILinks_DisableRuleLink.h \
    $${PWD}/OAILinks_EnableChannelCatalogLink.h \
    $${PWD}/OAILinks_EnableRuleLink.h \
    $${PWD}/OAILinks_ExportChannelCatalogProductInfoListLink.h \
    $${PWD}/OAILinks_ExportOrdersLink.h \
    $${PWD}/OAILinks_GetAutomaticTransitionsLink.h \
    $${PWD}/OAILinks_GetChannelCatalogCategoriesLink.h \
    $${PWD}/OAILinks_GetChannelCatalogExclusionFiltersCopyLink.h \
    $${PWD}/OAILinks_GetChannelCatalogExclusionFiltersLink.h \
    $${PWD}/OAILinks_GetChannelCatalogExportationCacheInfoLink.h \
    $${PWD}/OAILinks_GetChannelCatalogExportationHistoryLink.h \
    $${PWD}/OAILinks_GetChannelCatalogFilterOperatorsLink.h \
    $${PWD}/OAILinks_GetChannelCatalogLink.h \
    $${PWD}/OAILinks_GetChannelCatalogMarketplacePropertiesLink.h \
    $${PWD}/OAILinks_GetChannelCatalogMarketplaceSettingsLink.h \
    $${PWD}/OAILinks_GetChannelCatalogProductInfoLink.h \
    $${PWD}/OAILinks_GetChannelCatalogProductInfoListLink.h \
    $${PWD}/OAILinks_GetChannelCatalogProductValueOverrideCopyLink.h \
    $${PWD}/OAILinks_GetChannelCatalogsLink.h \
    $${PWD}/OAILinks_GetChannelInfoLink.h \
    $${PWD}/OAILinks_GetChannelsIndexLink.h \
    $${PWD}/OAILinks_GetChannelsLink.h \
    $${PWD}/OAILinks_GetCustomerIndexLink.h \
    $${PWD}/OAILinks_GetLegacyTrackingChannelCatalogLink.h \
    $${PWD}/OAILinks_GetLegacyTrackingChannelCatalogsLink.h \
    $${PWD}/OAILinks_GetMarketplaceAccountsSynchronizationLink.h \
    $${PWD}/OAILinks_GetMarketplaceAccountsSynchronizationV3Link.h \
    $${PWD}/OAILinks_GetMarketplaceChannelCatalogsLink.h \
    $${PWD}/OAILinks_GetOrderExportationsLink.h \
    $${PWD}/OAILinks_GetOrderHistoryLink.h \
    $${PWD}/OAILinks_GetOrderHistoryV3Link.h \
    $${PWD}/OAILinks_GetOrderIndexLink.h \
    $${PWD}/OAILinks_GetOrderLink.h \
    $${PWD}/OAILinks_GetOrderListFullLink.h \
    $${PWD}/OAILinks_GetOrderListFullV3Link.h \
    $${PWD}/OAILinks_GetOrderListLightLink.h \
    $${PWD}/OAILinks_GetOrderListLightV3Link.h \
    $${PWD}/OAILinks_GetOrderV3Link.h \
    $${PWD}/OAILinks_GetPublicListOfValuesLink.h \
    $${PWD}/OAILinks_GetPublicLovIndexLink.h \
    $${PWD}/OAILinks_GetPublicationsLink.h \
    $${PWD}/OAILinks_GetReportFilterLink.h \
    $${PWD}/OAILinks_GetReportFiltersLink.h \
    $${PWD}/OAILinks_GetRuleLink.h \
    $${PWD}/OAILinks_GetRulesExecutionsLink.h \
    $${PWD}/OAILinks_GetRulesLink.h \
    $${PWD}/OAILinks_GetStoreReportByCategoryLink.h \
    $${PWD}/OAILinks_GetStoreReportByChannelLink.h \
    $${PWD}/OAILinks_GetStoreReportByDayLink.h \
    $${PWD}/OAILinks_GetStoreReportByProductLink.h \
    $${PWD}/OAILinks_GetStoreTrackedClicksLink.h \
    $${PWD}/OAILinks_GetStoreTrackedExternalOrdersLink.h \
    $${PWD}/OAILinks_GetStoreTrackedOrdersLink.h \
    $${PWD}/OAILinks_GetStoreTrackingStatusLink.h \
    $${PWD}/OAILinks_GetTrackingStatusLink.h \
    $${PWD}/OAILinks_GetUserListOfValuesLink.h \
    $${PWD}/OAILinks_GetUserLovIndexLink.h \
    $${PWD}/OAILinks_HarvestAllLink.h \
    $${PWD}/OAILinks_HarvestAllV3Link.h \
    $${PWD}/OAILinks_HarvestOrderLink.h \
    $${PWD}/OAILinks_HarvestOrderV3Link.h \
    $${PWD}/OAILinks_Importation_ActivateAutoImportLink.h \
    $${PWD}/OAILinks_Importation_CancelLink.h \
    $${PWD}/OAILinks_Importation_CommitColumnsLink.h \
    $${PWD}/OAILinks_Importation_CommitLink.h \
    $${PWD}/OAILinks_Importation_ConfigureCatalogColumnLink.h \
    $${PWD}/OAILinks_Importation_ConfigureRemainingCatalogColumnsLink.h \
    $${PWD}/OAILinks_Importation_DeleteCustomColumnLink.h \
    $${PWD}/OAILinks_Importation_GetCustomColumnExpressionLink.h \
    $${PWD}/OAILinks_Importation_GetCustomColumnsLink.h \
    $${PWD}/OAILinks_Importation_GetDetectedCatalogColumnsLink.h \
    $${PWD}/OAILinks_Importation_GetImportationMonitoringLink.h \
    $${PWD}/OAILinks_Importation_GetManualUpdateLastInputConfigLink.h \
    $${PWD}/OAILinks_Importation_GetProductSampleCustomColumnValueLink.h \
    $${PWD}/OAILinks_Importation_GetProductSampleLink.h \
    $${PWD}/OAILinks_Importation_GetReportLink.h \
    $${PWD}/OAILinks_Importation_GetReportingsLink.h \
    $${PWD}/OAILinks_Importation_IgnoreColumnLink.h \
    $${PWD}/OAILinks_Importation_MapCatalogColumnLink.h \
    $${PWD}/OAILinks_Importation_MapCustomColumnLink.h \
    $${PWD}/OAILinks_Importation_ReattendColumnLink.h \
    $${PWD}/OAILinks_Importation_SaveCustomColumnLink.h \
    $${PWD}/OAILinks_Importation_StartManualUpdateLink.h \
    $${PWD}/OAILinks_Importation_TechnicalProgressionLink.h \
    $${PWD}/OAILinks_Importation_UnmapCatalogColumnLink.h \
    $${PWD}/OAILinks_Importation_UnmapCustomColumnLink.h \
    $${PWD}/OAILinks_MigrateLegacyTrackingChannelCatalogLink.h \
    $${PWD}/OAILinks_MoveDownRuleLink.h \
    $${PWD}/OAILinks_MoveUpRuleLink.h \
    $${PWD}/OAILinks_OptimiseAllLink.h \
    $${PWD}/OAILinks_OptimiseByCategoryLink.h \
    $${PWD}/OAILinks_OptimiseByChannelLink.h \
    $${PWD}/OAILinks_OptimiseByProductLink.h \
    $${PWD}/OAILinks_OptimiseLink.h \
    $${PWD}/OAILinks_OverrideChannelCatalogProductValuesLink.h \
    $${PWD}/OAILinks_PublishCatalogToMarketplaceLink.h \
    $${PWD}/OAILinks_ReenableChannelCatalogCategoryMappingLink.h \
    $${PWD}/OAILinks_ReenableChannelCatalogProductLink.h \
    $${PWD}/OAILinks_RunRuleLink.h \
    $${PWD}/OAILinks_RunRulesLink.h \
    $${PWD}/OAILinks_SaveReportFilterLink.h \
    $${PWD}/OAILinks_SetChannelCatalogMarketplaceSettingsLink.h \
    $${PWD}/OAILinks_SetMerchantOrderInfoLink.h \
    $${PWD}/OAILinks_SetMerchantOrderInfoListLink.h \
    $${PWD}/OAILinks_SetMerchantOrderInfoListV3Link.h \
    $${PWD}/OAILinks_SetMerchantOrderInfoV3Link.h \
    $${PWD}/OAILinks_UpdateRuleLink.h \
    $${PWD}/OAILinks_activateUserAccountLink.h \
    $${PWD}/OAILinks_changeEmailLink.h \
    $${PWD}/OAILinks_changePasswordLink.h \
    $${PWD}/OAILinks_createContractLink.h \
    $${PWD}/OAILinks_createStoreLink.h \
    $${PWD}/OAILinks_deleteNextContractLink.h \
    $${PWD}/OAILinks_deleteStoreLink.h \
    $${PWD}/OAILinks_deleteStoreShareLink.h \
    $${PWD}/OAILinks_getBillingPeriodsLink.h \
    $${PWD}/OAILinks_getContractsLink.h \
    $${PWD}/OAILinks_getCreditCardInfoLink.h \
    $${PWD}/OAILinks_getFriendInfoLink.h \
    $${PWD}/OAILinks_getInvoicesLink.h \
    $${PWD}/OAILinks_getOfferLink.h \
    $${PWD}/OAILinks_getProfilePictureInfoLink.h \
    $${PWD}/OAILinks_getStandardOffersLink.h \
    $${PWD}/OAILinks_getStoreLink.h \
    $${PWD}/OAILinks_getStoreSharesLink.h \
    $${PWD}/OAILinks_getStoresLink.h \
    $${PWD}/OAILinks_getUserAccountInfoLink.h \
    $${PWD}/OAILinks_logoutLink.h \
    $${PWD}/OAILinks_reactivateCurrentContractLink.h \
    $${PWD}/OAILinks_saveCompanyInfoLink.h \
    $${PWD}/OAILinks_saveCreditCardInfoLink.h \
    $${PWD}/OAILinks_savePersonalInfoLink.h \
    $${PWD}/OAILinks_saveProfilePictureInfoLink.h \
    $${PWD}/OAILinks_saveStoreAlertsLink.h \
    $${PWD}/OAILinks_shareStoreLink.h \
    $${PWD}/OAILinks_terminateCurrentContractLink.h \
    $${PWD}/OAILinks_updateStoreLink.h \
    $${PWD}/OAIListOfValueItem.h \
    $${PWD}/OAILoginRequest.h \
    $${PWD}/OAIMapBeezUPColumnRequest.h \
    $${PWD}/OAIMappingStatus.h \
    $${PWD}/OAIMarginType.h \
    $${PWD}/OAIMarketplaceChannelCatalog.h \
    $${PWD}/OAIMarketplaceChannelCatalogLinks.h \
    $${PWD}/OAIMarketplaceChannelCatalogList.h \
    $${PWD}/OAIMarketplaceChannelCatalogListLinks.h \
    $${PWD}/OAIMarketplaceChannelCatalogLovLinks.h \
    $${PWD}/OAIMarketplaceChannelCatalogPublicationOption.h \
    $${PWD}/OAINextContractInfo.h \
    $${PWD}/OAINextContractInfoLinks.h \
    $${PWD}/OAIOffer.h \
    $${PWD}/OAIOfferContent.h \
    $${PWD}/OAIOfferFunctionality.h \
    $${PWD}/OAIOfferLinks.h \
    $${PWD}/OAIOfferRequest.h \
    $${PWD}/OAIOptimisationActionName.h \
    $${PWD}/OAIOptimiseAllRequest.h \
    $${PWD}/OAIOptimiseRequest.h \
    $${PWD}/OAIOrder.h \
    $${PWD}/OAIOrderByDirection.h \
    $${PWD}/OAIOrderExportationReporting.h \
    $${PWD}/OAIOrderExportationReportingProcessingStatus.h \
    $${PWD}/OAIOrderExportations.h \
    $${PWD}/OAIOrderExportationsLinks.h \
    $${PWD}/OAIOrderHarvestErrorValue.h \
    $${PWD}/OAIOrderHeader.h \
    $${PWD}/OAIOrderHeaderLinks.h \
    $${PWD}/OAIOrderHeaderWithLinks.h \
    $${PWD}/OAIOrderHistory.h \
    $${PWD}/OAIOrderIdentifier.h \
    $${PWD}/OAIOrderIdentifierWithETag.h \
    $${PWD}/OAIOrderIndex.h \
    $${PWD}/OAIOrderIndexLinks.h \
    $${PWD}/OAIOrderIndexLovLinks.h \
    $${PWD}/OAIOrderInvoiceDesignSettings.h \
    $${PWD}/OAIOrderInvoiceGeneralSettings.h \
    $${PWD}/OAIOrderItem.h \
    $${PWD}/OAIOrderLinks.h \
    $${PWD}/OAIOrderListDateSearchType.h \
    $${PWD}/OAIOrderListFull.h \
    $${PWD}/OAIOrderListFullLinks.h \
    $${PWD}/OAIOrderListFullWithLinks.h \
    $${PWD}/OAIOrderListLight.h \
    $${PWD}/OAIOrderListLightLinks.h \
    $${PWD}/OAIOrderListLightWithLinks.h \
    $${PWD}/OAIOrderListLinks.h \
    $${PWD}/OAIOrderListRequest.h \
    $${PWD}/OAIOrderListRequestWithoutPagination.h \
    $${PWD}/OAIOrderOperationResponse.h \
    $${PWD}/OAIOrderWithLinks.h \
    $${PWD}/OAIOrderedReportFilterCommonParameters.h \
    $${PWD}/OAIPaginationRequestParameters.h \
    $${PWD}/OAIPaginationResult.h \
    $${PWD}/OAIPaginationResultLinks.h \
    $${PWD}/OAIParameterIn.h \
    $${PWD}/OAIParameterType.h \
    $${PWD}/OAIPaymentMethod.h \
    $${PWD}/OAIPerformanceIndicatorFilter.h \
    $${PWD}/OAIPerformanceIndicatorFormula.h \
    $${PWD}/OAIPerformanceIndicatorFormulaOperatorName.h \
    $${PWD}/OAIPerformanceIndicatorFormulaParameterType.h \
    $${PWD}/OAIPerformanceIndicatorType.h \
    $${PWD}/OAIPersonalInfo.h \
    $${PWD}/OAIPreviewOrderInvoiceRequest.h \
    $${PWD}/OAIPreviewOrderInvoiceResponse.h \
    $${PWD}/OAIPreviousFixPeriodInvoiceProrataInfo.h \
    $${PWD}/OAIProduct.h \
    $${PWD}/OAIProductError.h \
    $${PWD}/OAIProductErrorCode.h \
    $${PWD}/OAIProductList.h \
    $${PWD}/OAIProductOverrideWithCatalogValue.h \
    $${PWD}/OAIProductSample.h \
    $${PWD}/OAIProductSetVisibilityCriteria.h \
    $${PWD}/OAIProductSetVisibilityCriteriaLogicType.h \
    $${PWD}/OAIProductStateFilter.h \
    $${PWD}/OAIProfilePictureInfo.h \
    $${PWD}/OAIProfilePictureInfoResponse.h \
    $${PWD}/OAIProfilePictureInfoResponseLinks.h \
    $${PWD}/OAIProfilePictureInfoWithDefault.h \
    $${PWD}/OAIProfilePictureSelected.h \
    $${PWD}/OAIPromotionalCodeValidity.h \
    $${PWD}/OAIPublicChannelIndex.h \
    $${PWD}/OAIPublicChannelIndex_links.h \
    $${PWD}/OAIPublicChannelInfo.h \
    $${PWD}/OAIPublicChannelInfoList.h \
    $${PWD}/OAIPublicChannelInfoList_links.h \
    $${PWD}/OAIPublicListOfValuesResponse.h \
    $${PWD}/OAIPublicListOfValuesResponseLinks.h \
    $${PWD}/OAIPublicLovIndex.h \
    $${PWD}/OAIPublicLovIndexLinks.h \
    $${PWD}/OAIPublicationFeedReporting.h \
    $${PWD}/OAIPublicationReporting.h \
    $${PWD}/OAIPublicationStrategyKind.h \
    $${PWD}/OAIPublicationType.h \
    $${PWD}/OAIPublishCatalogToMarketplaceRequest.h \
    $${PWD}/OAIRandomProductList.h \
    $${PWD}/OAIRegisterRequest.h \
    $${PWD}/OAIReportAdvancedFilters.h \
    $${PWD}/OAIReportByCategory.h \
    $${PWD}/OAIReportByCategoryLinks.h \
    $${PWD}/OAIReportByCategoryRequest.h \
    $${PWD}/OAIReportByCategoryResponse.h \
    $${PWD}/OAIReportByCategoryResponseLinks.h \
    $${PWD}/OAIReportByChannel.h \
    $${PWD}/OAIReportByChannelLinks.h \
    $${PWD}/OAIReportByChannelRequest.h \
    $${PWD}/OAIReportByChannelResponse.h \
    $${PWD}/OAIReportByChannelResponseLinks.h \
    $${PWD}/OAIReportByCommonResponseLinks.h \
    $${PWD}/OAIReportByDay.h \
    $${PWD}/OAIReportByDayAllChannels.h \
    $${PWD}/OAIReportByDayByChannel.h \
    $${PWD}/OAIReportByDayGlobal.h \
    $${PWD}/OAIReportByDayGlobalAllChannels.h \
    $${PWD}/OAIReportByDayGlobalByChannel.h \
    $${PWD}/OAIReportByDayRequest.h \
    $${PWD}/OAIReportByDayResponse.h \
    $${PWD}/OAIReportByProduct.h \
    $${PWD}/OAIReportByProductAllChannelsLinks.h \
    $${PWD}/OAIReportByProductLinks.h \
    $${PWD}/OAIReportByProductOneChannelLinks.h \
    $${PWD}/OAIReportByProductRequest.h \
    $${PWD}/OAIReportByProductResponse.h \
    $${PWD}/OAIReportByProductResponseLinks.h \
    $${PWD}/OAIReportFilter.h \
    $${PWD}/OAIReportFilterCommonParameters.h \
    $${PWD}/OAIReportFilterHeader.h \
    $${PWD}/OAIReportFilterHeaderLinks.h \
    $${PWD}/OAIReportFilterLinks.h \
    $${PWD}/OAIReportFilterList.h \
    $${PWD}/OAIReportFilterParameters.h \
    $${PWD}/OAIReportFilterPeriodType.h \
    $${PWD}/OAIReportFiltersLinks.h \
    $${PWD}/OAIReportType.h \
    $${PWD}/OAIRule.h \
    $${PWD}/OAIRuleExecutionReporting.h \
    $${PWD}/OAIRuleExecutionReportingErrorType.h \
    $${PWD}/OAIRuleExecutionReportingExecutionSource.h \
    $${PWD}/OAIRuleExecutionReportingLinks.h \
    $${PWD}/OAIRuleExecutionReportingStatus.h \
    $${PWD}/OAIRuleExecutionReportings.h \
    $${PWD}/OAIRuleLastExecutionStatus.h \
    $${PWD}/OAIRuleLinks.h \
    $${PWD}/OAIRuleList.h \
    $${PWD}/OAIRuleListLinks.h \
    $${PWD}/OAISaveReportFilterRequest.h \
    $${PWD}/OAISaveStoreAlertRequest.h \
    $${PWD}/OAIScheduleAutoImportRequest.h \
    $${PWD}/OAISchedulingType.h \
    $${PWD}/OAISetChannelCatalogMarketplaceSettingsRequest.h \
    $${PWD}/OAISetMerchantOrderInfoListRequest.h \
    $${PWD}/OAISetMerchantOrderInfoListRequestItem.h \
    $${PWD}/OAISetMerchantOrderInfoRequest.h \
    $${PWD}/OAISourceType.h \
    $${PWD}/OAIStandardOffer.h \
    $${PWD}/OAIStandardOfferLinks.h \
    $${PWD}/OAIStandardOffers.h \
    $${PWD}/OAIStandardOffersLinks.h \
    $${PWD}/OAIStartManualImportRequest.h \
    $${PWD}/OAIStore.h \
    $${PWD}/OAIStoreAlert.h \
    $${PWD}/OAIStoreAlertLinks.h \
    $${PWD}/OAIStoreAlertProperty.h \
    $${PWD}/OAIStoreAlertPropertyInfo.h \
    $${PWD}/OAIStoreAlerts.h \
    $${PWD}/OAIStoreLinks.h \
    $${PWD}/OAIStoreList.h \
    $${PWD}/OAIStoreListLinks.h \
    $${PWD}/OAIStoreShare.h \
    $${PWD}/OAIStoreShareLinks.h \
    $${PWD}/OAIStoreShares.h \
    $${PWD}/OAIStoreSharesLinks.h \
    $${PWD}/OAIStoreStatus.h \
    $${PWD}/OAIStoreTrackingStatus.h \
    $${PWD}/OAIStoreUserRole.h \
    $${PWD}/OAISubscription.h \
    $${PWD}/OAISubscriptionIndex.h \
    $${PWD}/OAISubscriptionLinks.h \
    $${PWD}/OAISubscriptionPushReporting.h \
    $${PWD}/OAISubscriptionStatus.h \
    $${PWD}/OAISuccessSummary.h \
    $${PWD}/OAITerminateContract.h \
    $${PWD}/OAITrackedClick.h \
    $${PWD}/OAITrackedClicks.h \
    $${PWD}/OAITrackedExternalOrder.h \
    $${PWD}/OAITrackedExternalOrderProduct.h \
    $${PWD}/OAITrackedExternalOrders.h \
    $${PWD}/OAITrackedOrder.h \
    $${PWD}/OAITrackedOrderProduct.h \
    $${PWD}/OAITrackedOrders.h \
    $${PWD}/OAITrackingStatus.h \
    $${PWD}/OAIType.h \
    $${PWD}/OAIUnmapCategoryRequest.h \
    $${PWD}/OAIUpdateRuleRequest.h \
    $${PWD}/OAIUpdateStoreRequest.h \
    $${PWD}/OAIUpgradeOfferRequired.h \
    $${PWD}/OAIUserErrorMessage.h \
    $${PWD}/OAIUserFriendInfo.h \
    $${PWD}/OAIUserListOfValuesResponse.h \
    $${PWD}/OAIUserListOfValuesResponseLinks.h \
    $${PWD}/OAIUserLovIndex.h \
    $${PWD}/OAIUserLovIndexLinks.h \
    $${PWD}/OAIVariableModelInfo.h \
    $${PWD}/OAIWarningSummary.h \
    $${PWD}/OAIZendeskToken.h \
# APIs
    $${PWD}/OAIAnalyticsGlobalApi.h \
    $${PWD}/OAIAnalyticsOptimisationsApi.h \
    $${PWD}/OAIAnalyticsReportsApi.h \
    $${PWD}/OAIAnalyticsRulesApi.h \
    $${PWD}/OAIAnalyticsStatisticsApi.h \
    $${PWD}/OAIAnalyticsTrackingApi.h \
    $${PWD}/OAICatalogsAutoApi.h \
    $${PWD}/OAICatalogsCatalogApi.h \
    $${PWD}/OAICatalogsGlobalApi.h \
    $${PWD}/OAICatalogsImportationCatalogInfoApi.h \
    $${PWD}/OAICatalogsImportationProcessApi.h \
    $${PWD}/OAIChannelCatalogsCategoriesApi.h \
    $${PWD}/OAIChannelCatalogsColumnMappingsApi.h \
    $${PWD}/OAIChannelCatalogsExclusionFiltersApi.h \
    $${PWD}/OAIChannelCatalogsExportationsApi.h \
    $${PWD}/OAIChannelCatalogsGlobalApi.h \
    $${PWD}/OAIChannelCatalogsLegacyTrackingGlobalApi.h \
    $${PWD}/OAIChannelCatalogsProductsApi.h \
    $${PWD}/OAIChannelCatalogsProductsOptimisationApi.h \
    $${PWD}/OAIChannelCatalogsProductsOverridesApi.h \
    $${PWD}/OAIChannelCatalogsSettingsApi.h \
    $${PWD}/OAIChannelsChannelsGlobalApi.h \
    $${PWD}/OAICustomerAccountApi.h \
    $${PWD}/OAICustomerAlertsApi.h \
    $${PWD}/OAICustomerContractsApi.h \
    $${PWD}/OAICustomerFriendsApi.h \
    $${PWD}/OAICustomerGlobalApi.h \
    $${PWD}/OAICustomerInvoicesApi.h \
    $${PWD}/OAICustomerRightsApi.h \
    $${PWD}/OAICustomerSecurityApi.h \
    $${PWD}/OAICustomerSharesApi.h \
    $${PWD}/OAICustomerStoresApi.h \
    $${PWD}/OAIMarketplacesChannelCatalogsGlobalApi.h \
    $${PWD}/OAIMarketplacesChannelCatalogsPublicationsApi.h \
    $${PWD}/OAIMarketplacesChannelCatalogsSettingsApi.h \
    $${PWD}/OAIMarketplacesOrdersAutoTransitionsApi.h \
    $${PWD}/OAIMarketplacesOrdersBatchesApi.h \
    $${PWD}/OAIMarketplacesOrdersExportsApi.h \
    $${PWD}/OAIMarketplacesOrdersGlobalApi.h \
    $${PWD}/OAIMarketplacesOrdersListApi.h \
    $${PWD}/OAIMarketplacesOrdersOrderApi.h \
    $${PWD}/OAIMarketplacesOrdersSubscriptionsSubscriptionsApi.h \
    $${PWD}/OAIMarketplacesOrdersV3BatchesApi.h \
    $${PWD}/OAIMarketplacesOrdersV3GlobalApi.h \
    $${PWD}/OAIMarketplacesOrdersV3ListApi.h \
    $${PWD}/OAIMarketplacesOrdersV3OrderApi.h \
    $${PWD}/OAIOMInvoiceAPIGenerationApi.h \
    $${PWD}/OAIOMInvoiceAPISettingsApi.h \
    $${PWD}/OAIPublicChannelsPublicChannelsApi.h \
    $${PWD}/OAIPublicListOfValuesLOVApi.h \
    $${PWD}/OAIPublicSecuritySecurityApi.h \
    $${PWD}/OAIUserListOfValuesLOVApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAccountInfo.cpp \
    $${PWD}/OAIAccountInfoLinks.cpp \
    $${PWD}/OAIAccountPublications.cpp \
    $${PWD}/OAIAccountPublicationsLinks.cpp \
    $${PWD}/OAIAccountStatus.cpp \
    $${PWD}/OAIAccountSynchronization.cpp \
    $${PWD}/OAIAccountSynchronizationList.cpp \
    $${PWD}/OAIActivateSubscriptionRequest.cpp \
    $${PWD}/OAIAddChannelCatalogRequest.cpp \
    $${PWD}/OAIAnalyticsIndex.cpp \
    $${PWD}/OAIAnalyticsIndexLinks.cpp \
    $${PWD}/OAIAnalyticsIndexLovLinks.cpp \
    $${PWD}/OAIAnalyticsProductColumnFilter.cpp \
    $${PWD}/OAIAnalyticsProductColumnFilters.cpp \
    $${PWD}/OAIAnalyticsStoreIndex.cpp \
    $${PWD}/OAIAnalyticsStoreIndexLinks.cpp \
    $${PWD}/OAIApiCredential.cpp \
    $${PWD}/OAIApiCredentials.cpp \
    $${PWD}/OAIAutoImportConfiguration.cpp \
    $${PWD}/OAIAutoImportConfigurationLinks.cpp \
    $${PWD}/OAIAutomaticTransition.cpp \
    $${PWD}/OAIAutomaticTransitionInfo.cpp \
    $${PWD}/OAIAutomaticTransitionInfoLinks.cpp \
    $${PWD}/OAIAutomaticTransitionInfoList.cpp \
    $${PWD}/OAIAutomaticTransitionInfoListLinks.cpp \
    $${PWD}/OAIBatchOrderOperationResponse.cpp \
    $${PWD}/OAIBeezUPColumnConfiguration.cpp \
    $${PWD}/OAIBeezUP_Common_AdditionalProductFiltersValue.cpp \
    $${PWD}/OAIBeezUP_Common_ApiSettingsStatus.cpp \
    $${PWD}/OAIBeezUP_Common_CatalogCategoryFilter.cpp \
    $${PWD}/OAIBeezUP_Common_ChannelBasicInfo.cpp \
    $${PWD}/OAIBeezUP_Common_ChannelCategoryFilter.cpp \
    $${PWD}/OAIBeezUP_Common_ColumnDataType.cpp \
    $${PWD}/OAIBeezUP_Common_ColumnImportance.cpp \
    $${PWD}/OAIBeezUP_Common_ErrorResponseMessage.cpp \
    $${PWD}/OAIBeezUP_Common_ErrorSummary.cpp \
    $${PWD}/OAIBeezUP_Common_ExceptionDetail.cpp \
    $${PWD}/OAIBeezUP_Common_HttpMethod.cpp \
    $${PWD}/OAIBeezUP_Common_InfoSummaries.cpp \
    $${PWD}/OAIBeezUP_Common_InfoSummary.cpp \
    $${PWD}/OAIBeezUP_Common_LOVLink3.cpp \
    $${PWD}/OAIBeezUP_Common_Link3.cpp \
    $${PWD}/OAIBeezUP_Common_LinkParameter3.cpp \
    $${PWD}/OAIBeezUP_Common_LinkParameterProperty3.cpp \
    $${PWD}/OAIBeezUP_Common_ListOfValueItem.cpp \
    $${PWD}/OAIBeezUP_Common_PaginationResult.cpp \
    $${PWD}/OAIBeezUP_Common_PaginationResultLinks.cpp \
    $${PWD}/OAIBeezUP_Common_ParameterIn.cpp \
    $${PWD}/OAIBeezUP_Common_ParameterType.cpp \
    $${PWD}/OAIBeezUP_Common_ProductBasicInfo.cpp \
    $${PWD}/OAIBeezUP_Common_SuccessSummary.cpp \
    $${PWD}/OAIBeezUP_Common_UserErrorMessage.cpp \
    $${PWD}/OAIBeezUP_Common_UserErrorMessage_arguments_inner.cpp \
    $${PWD}/OAIBeezUP_Common_WarningSummary.cpp \
    $${PWD}/OAIBillingPeriod.cpp \
    $${PWD}/OAIBillingPeriodList.cpp \
    $${PWD}/OAIBillingPeriodListLinks.cpp \
    $${PWD}/OAIBonusInfo.cpp \
    $${PWD}/OAIBonusType.cpp \
    $${PWD}/OAICatalogColumn.cpp \
    $${PWD}/OAICatalogColumnLinks.cpp \
    $${PWD}/OAICatalogColumnList.cpp \
    $${PWD}/OAICatalogIndex.cpp \
    $${PWD}/OAICatalogIndexLOVLinks.cpp \
    $${PWD}/OAICatalogIndexLinks.cpp \
    $${PWD}/OAICatalogStoreIndex.cpp \
    $${PWD}/OAICatalogStoreIndexLinks.cpp \
    $${PWD}/OAICatalogStoreIndexList.cpp \
    $${PWD}/OAICatalogStoreStatus.cpp \
    $${PWD}/OAICategory.cpp \
    $${PWD}/OAICategoryList.cpp \
    $${PWD}/OAICategoryMappingState.cpp \
    $${PWD}/OAICategoryMappingStatus.cpp \
    $${PWD}/OAIChangeCustomColumnExpressionRequest.cpp \
    $${PWD}/OAIChangeCustomColumnRequest.cpp \
    $${PWD}/OAIChangeEmailRequest.cpp \
    $${PWD}/OAIChangeOrderListRequest.cpp \
    $${PWD}/OAIChangeOrderListRequestItem.cpp \
    $${PWD}/OAIChangeOrderListRequestItemV2.cpp \
    $${PWD}/OAIChangeOrderListRequestV2.cpp \
    $${PWD}/OAIChangeOrderReporting.cpp \
    $${PWD}/OAIChangePasswordRequest.cpp \
    $${PWD}/OAIChangeUserColumnNameRequest.cpp \
    $${PWD}/OAIChannelCatalog.cpp \
    $${PWD}/OAIChannelCatalogCategoryConfiguration.cpp \
    $${PWD}/OAIChannelCatalogCategoryConfigurationInfo.cpp \
    $${PWD}/OAIChannelCatalogCategoryConfigurationList.cpp \
    $${PWD}/OAIChannelCatalogCategoryMappingInfoLinks.cpp \
    $${PWD}/OAIChannelCatalogCategoryMappingSettings.cpp \
    $${PWD}/OAIChannelCatalogCategoryMappingsLinks.cpp \
    $${PWD}/OAIChannelCatalogColumnMapping.cpp \
    $${PWD}/OAIChannelCatalogColumnMappingWithName.cpp \
    $${PWD}/OAIChannelCatalogExportCacheInfo.cpp \
    $${PWD}/OAIChannelCatalogExportCacheInfoResponse.cpp \
    $${PWD}/OAIChannelCatalogExportCacheInfoResponseLinks.cpp \
    $${PWD}/OAIChannelCatalogExportationHistory.cpp \
    $${PWD}/OAIChannelCatalogExportationHistoryLinks.cpp \
    $${PWD}/OAIChannelCatalogExportationReporting.cpp \
    $${PWD}/OAIChannelCatalogLinks.cpp \
    $${PWD}/OAIChannelCatalogList.cpp \
    $${PWD}/OAIChannelCatalogListLinks.cpp \
    $${PWD}/OAIChannelCatalogListLovLinks.cpp \
    $${PWD}/OAIChannelCatalogMarketplaceBooleanProperty.cpp \
    $${PWD}/OAIChannelCatalogMarketplaceBooleanSetting.cpp \
    $${PWD}/OAIChannelCatalogMarketplaceIntegerProperty.cpp \
    $${PWD}/OAIChannelCatalogMarketplaceIntegerSetting.cpp \
    $${PWD}/OAIChannelCatalogMarketplaceNumberProperty.cpp \
    $${PWD}/OAIChannelCatalogMarketplaceNumberSetting.cpp \
    $${PWD}/OAIChannelCatalogMarketplaceProperties.cpp \
    $${PWD}/OAIChannelCatalogMarketplacePropertiesLinks.cpp \
    $${PWD}/OAIChannelCatalogMarketplaceProperty.cpp \
    $${PWD}/OAIChannelCatalogMarketplacePropertyDiscriminatorType.cpp \
    $${PWD}/OAIChannelCatalogMarketplacePropertyGroup.cpp \
    $${PWD}/OAIChannelCatalogMarketplaceSetting.cpp \
    $${PWD}/OAIChannelCatalogMarketplaceSettingDiscriminatorType.cpp \
    $${PWD}/OAIChannelCatalogMarketplaceSettings.cpp \
    $${PWD}/OAIChannelCatalogMarketplaceSettingsLinks.cpp \
    $${PWD}/OAIChannelCatalogMarketplaceStringProperty.cpp \
    $${PWD}/OAIChannelCatalogMarketplaceStringSetting.cpp \
    $${PWD}/OAIChannelCatalogProductByChannelCatalogRequest.cpp \
    $${PWD}/OAIChannelCatalogProductByChannelCatalogResponse.cpp \
    $${PWD}/OAIChannelCatalogProductFilters.cpp \
    $${PWD}/OAIChannelCatalogProductInfo.cpp \
    $${PWD}/OAIChannelCatalogProductInfoLinks.cpp \
    $${PWD}/OAIChannelCatalogProductInfoList.cpp \
    $${PWD}/OAIChannelCatalogProductInfoListLinks.cpp \
    $${PWD}/OAIChannelCatalogProductsCounters.cpp \
    $${PWD}/OAIChannelCatalogState.cpp \
    $${PWD}/OAIChannelCategory.cpp \
    $${PWD}/OAIChannelCategoryColumnOverride.cpp \
    $${PWD}/OAIChannelCategorySettings.cpp \
    $${PWD}/OAIChannelColumn.cpp \
    $${PWD}/OAIChannelColumnConfiguration.cpp \
    $${PWD}/OAIChannelCostSettings.cpp \
    $${PWD}/OAIChannelFirstLevelCategory.cpp \
    $${PWD}/OAIChannelHeader.cpp \
    $${PWD}/OAIChannelHeaderLinks.cpp \
    $${PWD}/OAIChannelInfo.cpp \
    $${PWD}/OAIChannelInfo_details.cpp \
    $${PWD}/OAIChannelInfo_keyNumbers.cpp \
    $${PWD}/OAIChannelInfo_salesContact.cpp \
    $${PWD}/OAIChannelInfo_technicalContact.cpp \
    $${PWD}/OAIChannelRootCategory.cpp \
    $${PWD}/OAIClearMerchantOrderInfoListRequest.cpp \
    $${PWD}/OAIClickIncludedAndAdditionalClickPrice.cpp \
    $${PWD}/OAIClickIncludedAndVariablePrice.cpp \
    $${PWD}/OAIColumnConfiguration.cpp \
    $${PWD}/OAIColumnMappingStatus.cpp \
    $${PWD}/OAICompanyInfo.cpp \
    $${PWD}/OAICompareOptions.cpp \
    $${PWD}/OAICompressionFormatStrategy.cpp \
    $${PWD}/OAIComputeExpressionRequest.cpp \
    $${PWD}/OAIConfigureAutoImportIntervalRequest.cpp \
    $${PWD}/OAIConfigureAutomaticTransitionRequest.cpp \
    $${PWD}/OAIConfigureCatalogColumnCatalogRequest.cpp \
    $${PWD}/OAIConfigureCategoryRequest.cpp \
    $${PWD}/OAIConsumptionAvailabilityStatus.cpp \
    $${PWD}/OAIContractBillingPeriodInfo.cpp \
    $${PWD}/OAIContractBonusInfo.cpp \
    $${PWD}/OAIContractClickInfo.cpp \
    $${PWD}/OAIContractCommitmentInfo.cpp \
    $${PWD}/OAIContractDiscountInfo.cpp \
    $${PWD}/OAIContractInfo.cpp \
    $${PWD}/OAIContractMoneyInfo.cpp \
    $${PWD}/OAIContractStoreInfo.cpp \
    $${PWD}/OAIContracts.cpp \
    $${PWD}/OAIContractsLinks.cpp \
    $${PWD}/OAICopyOptimisationRequest.cpp \
    $${PWD}/OAICopyOptimisationResponse.cpp \
    $${PWD}/OAICostSettings.cpp \
    $${PWD}/OAICostStatus.cpp \
    $${PWD}/OAICostType.cpp \
    $${PWD}/OAICreateContract.cpp \
    $${PWD}/OAICreateContractResponse.cpp \
    $${PWD}/OAICreateContractResponseLinks.cpp \
    $${PWD}/OAICreateCustomColumnRequest.cpp \
    $${PWD}/OAICreateRuleRequest.cpp \
    $${PWD}/OAICreateStoreRequest.cpp \
    $${PWD}/OAICreateSubscriptionRequest.cpp \
    $${PWD}/OAICredential.cpp \
    $${PWD}/OAICreditCardInfo.cpp \
    $${PWD}/OAICreditCardInfoResponse.cpp \
    $${PWD}/OAICreditCardInfoResponseLinks.cpp \
    $${PWD}/OAICreditCardInfoWithCardType.cpp \
    $${PWD}/OAICurrentContractInfo.cpp \
    $${PWD}/OAICurrentContractInfoLinks.cpp \
    $${PWD}/OAICustomColumn.cpp \
    $${PWD}/OAICustomColumnLinks.cpp \
    $${PWD}/OAICustomColumnList.cpp \
    $${PWD}/OAICustomColumnListLinks.cpp \
    $${PWD}/OAICustomerIndex.cpp \
    $${PWD}/OAICustomerIndexLinks.cpp \
    $${PWD}/OAICustomerIndexLovLinks.cpp \
    $${PWD}/OAIDateSearchType.cpp \
    $${PWD}/OAIDetectedCatalogColumn.cpp \
    $${PWD}/OAIDetectedCatalogColumnLinks.cpp \
    $${PWD}/OAIDetectedCatalogColumnList.cpp \
    $${PWD}/OAIDetectedCatalogColumnListLinks.cpp \
    $${PWD}/OAIDownloadCatalogStrategy.cpp \
    $${PWD}/OAIDuplicateProductValueConfiguration.cpp \
    $${PWD}/OAIDuplicateProductValueStrategy.cpp \
    $${PWD}/OAIErrorResponseMessage.cpp \
    $${PWD}/OAIErrorResponseMessagePaymentRequired.cpp \
    $${PWD}/OAIErrorResponseMessagePaymentRequiredLinks.cpp \
    $${PWD}/OAIErrorSummary.cpp \
    $${PWD}/OAIExceptionDetail.cpp \
    $${PWD}/OAIExchangedMessagesItem.cpp \
    $${PWD}/OAIExclusionFilter.cpp \
    $${PWD}/OAIExclusionFiltersResponse.cpp \
    $${PWD}/OAIExclusionFiltersResponseLinks.cpp \
    $${PWD}/OAIExportOrderListFormat.cpp \
    $${PWD}/OAIExportOrderListRequest.cpp \
    $${PWD}/OAIExternalLinks_Catalog_GetBeezUPColumnsLink.cpp \
    $${PWD}/OAIExternalLinks_GetChannelCatalogMarketplaceSettingsLink.cpp \
    $${PWD}/OAIExternalLinks_GetChannelInfoLink.cpp \
    $${PWD}/OAIExternalLinks_GetExternalConfigurationPageLink.cpp \
    $${PWD}/OAIFeedType.cpp \
    $${PWD}/OAIFileFormatStrategy.cpp \
    $${PWD}/OAIFilterOperator.cpp \
    $${PWD}/OAIFilterOperatorDataType.cpp \
    $${PWD}/OAIFixedAndVariableClickModelInfo.cpp \
    $${PWD}/OAIFunctionality.cpp \
    $${PWD}/OAIFunctionalityRightInfo.cpp \
    $${PWD}/OAIGeneralSettings.cpp \
    $${PWD}/OAIGenerateBatchOrderInvoiceErrorResponseItem.cpp \
    $${PWD}/OAIGenerateBatchOrderInvoiceErrorResponseItemDetail.cpp \
    $${PWD}/OAIGenerateBatchOrderInvoiceRequestItem.cpp \
    $${PWD}/OAIGenerateOrderInvoiceRequest.cpp \
    $${PWD}/OAIGenerateOrderInvoiceResponse.cpp \
    $${PWD}/OAIGetChannelCatalogProductInfoListRequest.cpp \
    $${PWD}/OAIGetImportationProductsReportRequest.cpp \
    $${PWD}/OAIGetImportationProductsReportRequestErrorCode.cpp \
    $${PWD}/OAIGetImportationProductsReportResponse.cpp \
    $${PWD}/OAIGetImportationReportResponse.cpp \
    $${PWD}/OAIGetImportationReportResponseDiff.cpp \
    $${PWD}/OAIGetImportationReportResponseError.cpp \
    $${PWD}/OAIGetImportationReportResponseImportationInfo.cpp \
    $${PWD}/OAIGetImportationReportResponseProductMetrics.cpp \
    $${PWD}/OAIGetOrderInvoiceDesignPreviewResponse.cpp \
    $${PWD}/OAIGetOrderInvoiceGeneralSettingsResponse.cpp \
    $${PWD}/OAIGetOrderInvoicePdfFromHtmlInvoiceUrlRequest.cpp \
    $${PWD}/OAIGetProductsRequest.cpp \
    $${PWD}/OAIHarvestOrderReporting.cpp \
    $${PWD}/OAIHttpMethod.cpp \
    $${PWD}/OAIImportAlreadyInProgressResponse.cpp \
    $${PWD}/OAIImportAlreadyInProgressResponseLinks.cpp \
    $${PWD}/OAIImportationCustomColumn.cpp \
    $${PWD}/OAIImportationCustomColumnLinks.cpp \
    $${PWD}/OAIImportationCustomColumnList.cpp \
    $${PWD}/OAIImportationCustomColumnListLinks.cpp \
    $${PWD}/OAIImportationMonitoring.cpp \
    $${PWD}/OAIImportationMonitoringLinks.cpp \
    $${PWD}/OAIImportationReporting.cpp \
    $${PWD}/OAIImportationReportingLinks.cpp \
    $${PWD}/OAIImportationTechnicalProgression.cpp \
    $${PWD}/OAIImportationsResponse.cpp \
    $${PWD}/OAIImportationsResponseLinks.cpp \
    $${PWD}/OAIInfoSummaries.cpp \
    $${PWD}/OAIInfoSummary.cpp \
    $${PWD}/OAIInputConfiguration.cpp \
    $${PWD}/OAIInputFileConfiguration.cpp \
    $${PWD}/OAIInputFileFetchConfiguration.cpp \
    $${PWD}/OAIInputFileReadConfiguration.cpp \
    $${PWD}/OAIInputFileReadCsvConfiguration.cpp \
    $${PWD}/OAIInputFileReadXmlConfiguration.cpp \
    $${PWD}/OAIInvoice.cpp \
    $${PWD}/OAIInvoiceList.cpp \
    $${PWD}/OAIInvoiceListLinks.cpp \
    $${PWD}/OAIInvoicePaymentStatus.cpp \
    $${PWD}/OAILOVLink3.cpp \
    $${PWD}/OAILastManualImportInputConfiguration.cpp \
    $${PWD}/OAILegacyTrackingChannelCatalog.cpp \
    $${PWD}/OAILegacyTrackingChannelCatalogLinks.cpp \
    $${PWD}/OAILegacyTrackingChannelCatalogList.cpp \
    $${PWD}/OAILegacyTrackingChannelCatalogListLinks.cpp \
    $${PWD}/OAILink3.cpp \
    $${PWD}/OAILinkClickToOrderType.cpp \
    $${PWD}/OAILinkParameter3.cpp \
    $${PWD}/OAILinkParameterProperty3.cpp \
    $${PWD}/OAILinks_AddChannelCatalogLink.cpp \
    $${PWD}/OAILinks_AnalyticsIndexLink.cpp \
    $${PWD}/OAILinks_Auto_ConfigureAutoImportIntervalLink.cpp \
    $${PWD}/OAILinks_Auto_GetAutoImportConfigurationLink.cpp \
    $${PWD}/OAILinks_Auto_PauseAutoImportLink.cpp \
    $${PWD}/OAILinks_Auto_ResumeAutoImportLink.cpp \
    $${PWD}/OAILinks_Auto_ScheduleAutoImportLink.cpp \
    $${PWD}/OAILinks_Auto_StartAutoImportLink.cpp \
    $${PWD}/OAILinks_CatalogIndexLink.cpp \
    $${PWD}/OAILinks_CatalogStoreIndexLink.cpp \
    $${PWD}/OAILinks_Catalog_ChangeCatalogColumnUserNameLink.cpp \
    $${PWD}/OAILinks_Catalog_ChangeCustomColumnExpressionLink.cpp \
    $${PWD}/OAILinks_Catalog_ChangeCustomColumnUserNameLink.cpp \
    $${PWD}/OAILinks_Catalog_ComputeExpressionLink.cpp \
    $${PWD}/OAILinks_Catalog_DeleteCustomColumnLink.cpp \
    $${PWD}/OAILinks_Catalog_GetBeezUPColumnsLink.cpp \
    $${PWD}/OAILinks_Catalog_GetCatalogColumnsLink.cpp \
    $${PWD}/OAILinks_Catalog_GetCategoriesLink.cpp \
    $${PWD}/OAILinks_Catalog_GetCustomColumnExpressionLink.cpp \
    $${PWD}/OAILinks_Catalog_GetCustomColumnsLink.cpp \
    $${PWD}/OAILinks_Catalog_GetProductsLink.cpp \
    $${PWD}/OAILinks_Catalog_GetRandomProductsLink.cpp \
    $${PWD}/OAILinks_Catalog_SaveCustomColumnLink.cpp \
    $${PWD}/OAILinks_ChangeOrderLink.cpp \
    $${PWD}/OAILinks_ChangeOrderV3Link.cpp \
    $${PWD}/OAILinks_ClearChannelCatalogExportationCacheLink.cpp \
    $${PWD}/OAILinks_ClearMerchantOrderInfoLink.cpp \
    $${PWD}/OAILinks_ClearMerchantOrderInfoListLink.cpp \
    $${PWD}/OAILinks_ClearMerchantOrderInfoListV3Link.cpp \
    $${PWD}/OAILinks_ClearMerchantOrderInfoV3Link.cpp \
    $${PWD}/OAILinks_ConfigureAutomaticTransitionsLink.cpp \
    $${PWD}/OAILinks_ConfigureChannelCatalogCategoryLink.cpp \
    $${PWD}/OAILinks_ConfigureChannelCatalogColumnMappingsLink.cpp \
    $${PWD}/OAILinks_ConfigureChannelCatalogCostSettingsLink.cpp \
    $${PWD}/OAILinks_ConfigureChannelCatalogExclusionFiltersCopyLink.cpp \
    $${PWD}/OAILinks_ConfigureChannelCatalogExclusionFiltersLink.cpp \
    $${PWD}/OAILinks_ConfigureChannelCatalogGeneralSettingsLink.cpp \
    $${PWD}/OAILinks_ConfigureChannelCatalogProductValueOverrideCopyLink.cpp \
    $${PWD}/OAILinks_CreateRuleLink.cpp \
    $${PWD}/OAILinks_DeleteChannelCatalogLink.cpp \
    $${PWD}/OAILinks_DeleteReportFilterLink.cpp \
    $${PWD}/OAILinks_DeleteRuleLink.cpp \
    $${PWD}/OAILinks_DisableChannelCatalogCategoryMappingLink.cpp \
    $${PWD}/OAILinks_DisableChannelCatalogLink.cpp \
    $${PWD}/OAILinks_DisableChannelCatalogProductLink.cpp \
    $${PWD}/OAILinks_DisableRuleLink.cpp \
    $${PWD}/OAILinks_EnableChannelCatalogLink.cpp \
    $${PWD}/OAILinks_EnableRuleLink.cpp \
    $${PWD}/OAILinks_ExportChannelCatalogProductInfoListLink.cpp \
    $${PWD}/OAILinks_ExportOrdersLink.cpp \
    $${PWD}/OAILinks_GetAutomaticTransitionsLink.cpp \
    $${PWD}/OAILinks_GetChannelCatalogCategoriesLink.cpp \
    $${PWD}/OAILinks_GetChannelCatalogExclusionFiltersCopyLink.cpp \
    $${PWD}/OAILinks_GetChannelCatalogExclusionFiltersLink.cpp \
    $${PWD}/OAILinks_GetChannelCatalogExportationCacheInfoLink.cpp \
    $${PWD}/OAILinks_GetChannelCatalogExportationHistoryLink.cpp \
    $${PWD}/OAILinks_GetChannelCatalogFilterOperatorsLink.cpp \
    $${PWD}/OAILinks_GetChannelCatalogLink.cpp \
    $${PWD}/OAILinks_GetChannelCatalogMarketplacePropertiesLink.cpp \
    $${PWD}/OAILinks_GetChannelCatalogMarketplaceSettingsLink.cpp \
    $${PWD}/OAILinks_GetChannelCatalogProductInfoLink.cpp \
    $${PWD}/OAILinks_GetChannelCatalogProductInfoListLink.cpp \
    $${PWD}/OAILinks_GetChannelCatalogProductValueOverrideCopyLink.cpp \
    $${PWD}/OAILinks_GetChannelCatalogsLink.cpp \
    $${PWD}/OAILinks_GetChannelInfoLink.cpp \
    $${PWD}/OAILinks_GetChannelsIndexLink.cpp \
    $${PWD}/OAILinks_GetChannelsLink.cpp \
    $${PWD}/OAILinks_GetCustomerIndexLink.cpp \
    $${PWD}/OAILinks_GetLegacyTrackingChannelCatalogLink.cpp \
    $${PWD}/OAILinks_GetLegacyTrackingChannelCatalogsLink.cpp \
    $${PWD}/OAILinks_GetMarketplaceAccountsSynchronizationLink.cpp \
    $${PWD}/OAILinks_GetMarketplaceAccountsSynchronizationV3Link.cpp \
    $${PWD}/OAILinks_GetMarketplaceChannelCatalogsLink.cpp \
    $${PWD}/OAILinks_GetOrderExportationsLink.cpp \
    $${PWD}/OAILinks_GetOrderHistoryLink.cpp \
    $${PWD}/OAILinks_GetOrderHistoryV3Link.cpp \
    $${PWD}/OAILinks_GetOrderIndexLink.cpp \
    $${PWD}/OAILinks_GetOrderLink.cpp \
    $${PWD}/OAILinks_GetOrderListFullLink.cpp \
    $${PWD}/OAILinks_GetOrderListFullV3Link.cpp \
    $${PWD}/OAILinks_GetOrderListLightLink.cpp \
    $${PWD}/OAILinks_GetOrderListLightV3Link.cpp \
    $${PWD}/OAILinks_GetOrderV3Link.cpp \
    $${PWD}/OAILinks_GetPublicListOfValuesLink.cpp \
    $${PWD}/OAILinks_GetPublicLovIndexLink.cpp \
    $${PWD}/OAILinks_GetPublicationsLink.cpp \
    $${PWD}/OAILinks_GetReportFilterLink.cpp \
    $${PWD}/OAILinks_GetReportFiltersLink.cpp \
    $${PWD}/OAILinks_GetRuleLink.cpp \
    $${PWD}/OAILinks_GetRulesExecutionsLink.cpp \
    $${PWD}/OAILinks_GetRulesLink.cpp \
    $${PWD}/OAILinks_GetStoreReportByCategoryLink.cpp \
    $${PWD}/OAILinks_GetStoreReportByChannelLink.cpp \
    $${PWD}/OAILinks_GetStoreReportByDayLink.cpp \
    $${PWD}/OAILinks_GetStoreReportByProductLink.cpp \
    $${PWD}/OAILinks_GetStoreTrackedClicksLink.cpp \
    $${PWD}/OAILinks_GetStoreTrackedExternalOrdersLink.cpp \
    $${PWD}/OAILinks_GetStoreTrackedOrdersLink.cpp \
    $${PWD}/OAILinks_GetStoreTrackingStatusLink.cpp \
    $${PWD}/OAILinks_GetTrackingStatusLink.cpp \
    $${PWD}/OAILinks_GetUserListOfValuesLink.cpp \
    $${PWD}/OAILinks_GetUserLovIndexLink.cpp \
    $${PWD}/OAILinks_HarvestAllLink.cpp \
    $${PWD}/OAILinks_HarvestAllV3Link.cpp \
    $${PWD}/OAILinks_HarvestOrderLink.cpp \
    $${PWD}/OAILinks_HarvestOrderV3Link.cpp \
    $${PWD}/OAILinks_Importation_ActivateAutoImportLink.cpp \
    $${PWD}/OAILinks_Importation_CancelLink.cpp \
    $${PWD}/OAILinks_Importation_CommitColumnsLink.cpp \
    $${PWD}/OAILinks_Importation_CommitLink.cpp \
    $${PWD}/OAILinks_Importation_ConfigureCatalogColumnLink.cpp \
    $${PWD}/OAILinks_Importation_ConfigureRemainingCatalogColumnsLink.cpp \
    $${PWD}/OAILinks_Importation_DeleteCustomColumnLink.cpp \
    $${PWD}/OAILinks_Importation_GetCustomColumnExpressionLink.cpp \
    $${PWD}/OAILinks_Importation_GetCustomColumnsLink.cpp \
    $${PWD}/OAILinks_Importation_GetDetectedCatalogColumnsLink.cpp \
    $${PWD}/OAILinks_Importation_GetImportationMonitoringLink.cpp \
    $${PWD}/OAILinks_Importation_GetManualUpdateLastInputConfigLink.cpp \
    $${PWD}/OAILinks_Importation_GetProductSampleCustomColumnValueLink.cpp \
    $${PWD}/OAILinks_Importation_GetProductSampleLink.cpp \
    $${PWD}/OAILinks_Importation_GetReportLink.cpp \
    $${PWD}/OAILinks_Importation_GetReportingsLink.cpp \
    $${PWD}/OAILinks_Importation_IgnoreColumnLink.cpp \
    $${PWD}/OAILinks_Importation_MapCatalogColumnLink.cpp \
    $${PWD}/OAILinks_Importation_MapCustomColumnLink.cpp \
    $${PWD}/OAILinks_Importation_ReattendColumnLink.cpp \
    $${PWD}/OAILinks_Importation_SaveCustomColumnLink.cpp \
    $${PWD}/OAILinks_Importation_StartManualUpdateLink.cpp \
    $${PWD}/OAILinks_Importation_TechnicalProgressionLink.cpp \
    $${PWD}/OAILinks_Importation_UnmapCatalogColumnLink.cpp \
    $${PWD}/OAILinks_Importation_UnmapCustomColumnLink.cpp \
    $${PWD}/OAILinks_MigrateLegacyTrackingChannelCatalogLink.cpp \
    $${PWD}/OAILinks_MoveDownRuleLink.cpp \
    $${PWD}/OAILinks_MoveUpRuleLink.cpp \
    $${PWD}/OAILinks_OptimiseAllLink.cpp \
    $${PWD}/OAILinks_OptimiseByCategoryLink.cpp \
    $${PWD}/OAILinks_OptimiseByChannelLink.cpp \
    $${PWD}/OAILinks_OptimiseByProductLink.cpp \
    $${PWD}/OAILinks_OptimiseLink.cpp \
    $${PWD}/OAILinks_OverrideChannelCatalogProductValuesLink.cpp \
    $${PWD}/OAILinks_PublishCatalogToMarketplaceLink.cpp \
    $${PWD}/OAILinks_ReenableChannelCatalogCategoryMappingLink.cpp \
    $${PWD}/OAILinks_ReenableChannelCatalogProductLink.cpp \
    $${PWD}/OAILinks_RunRuleLink.cpp \
    $${PWD}/OAILinks_RunRulesLink.cpp \
    $${PWD}/OAILinks_SaveReportFilterLink.cpp \
    $${PWD}/OAILinks_SetChannelCatalogMarketplaceSettingsLink.cpp \
    $${PWD}/OAILinks_SetMerchantOrderInfoLink.cpp \
    $${PWD}/OAILinks_SetMerchantOrderInfoListLink.cpp \
    $${PWD}/OAILinks_SetMerchantOrderInfoListV3Link.cpp \
    $${PWD}/OAILinks_SetMerchantOrderInfoV3Link.cpp \
    $${PWD}/OAILinks_UpdateRuleLink.cpp \
    $${PWD}/OAILinks_activateUserAccountLink.cpp \
    $${PWD}/OAILinks_changeEmailLink.cpp \
    $${PWD}/OAILinks_changePasswordLink.cpp \
    $${PWD}/OAILinks_createContractLink.cpp \
    $${PWD}/OAILinks_createStoreLink.cpp \
    $${PWD}/OAILinks_deleteNextContractLink.cpp \
    $${PWD}/OAILinks_deleteStoreLink.cpp \
    $${PWD}/OAILinks_deleteStoreShareLink.cpp \
    $${PWD}/OAILinks_getBillingPeriodsLink.cpp \
    $${PWD}/OAILinks_getContractsLink.cpp \
    $${PWD}/OAILinks_getCreditCardInfoLink.cpp \
    $${PWD}/OAILinks_getFriendInfoLink.cpp \
    $${PWD}/OAILinks_getInvoicesLink.cpp \
    $${PWD}/OAILinks_getOfferLink.cpp \
    $${PWD}/OAILinks_getProfilePictureInfoLink.cpp \
    $${PWD}/OAILinks_getStandardOffersLink.cpp \
    $${PWD}/OAILinks_getStoreLink.cpp \
    $${PWD}/OAILinks_getStoreSharesLink.cpp \
    $${PWD}/OAILinks_getStoresLink.cpp \
    $${PWD}/OAILinks_getUserAccountInfoLink.cpp \
    $${PWD}/OAILinks_logoutLink.cpp \
    $${PWD}/OAILinks_reactivateCurrentContractLink.cpp \
    $${PWD}/OAILinks_saveCompanyInfoLink.cpp \
    $${PWD}/OAILinks_saveCreditCardInfoLink.cpp \
    $${PWD}/OAILinks_savePersonalInfoLink.cpp \
    $${PWD}/OAILinks_saveProfilePictureInfoLink.cpp \
    $${PWD}/OAILinks_saveStoreAlertsLink.cpp \
    $${PWD}/OAILinks_shareStoreLink.cpp \
    $${PWD}/OAILinks_terminateCurrentContractLink.cpp \
    $${PWD}/OAILinks_updateStoreLink.cpp \
    $${PWD}/OAIListOfValueItem.cpp \
    $${PWD}/OAILoginRequest.cpp \
    $${PWD}/OAIMapBeezUPColumnRequest.cpp \
    $${PWD}/OAIMappingStatus.cpp \
    $${PWD}/OAIMarginType.cpp \
    $${PWD}/OAIMarketplaceChannelCatalog.cpp \
    $${PWD}/OAIMarketplaceChannelCatalogLinks.cpp \
    $${PWD}/OAIMarketplaceChannelCatalogList.cpp \
    $${PWD}/OAIMarketplaceChannelCatalogListLinks.cpp \
    $${PWD}/OAIMarketplaceChannelCatalogLovLinks.cpp \
    $${PWD}/OAIMarketplaceChannelCatalogPublicationOption.cpp \
    $${PWD}/OAINextContractInfo.cpp \
    $${PWD}/OAINextContractInfoLinks.cpp \
    $${PWD}/OAIOffer.cpp \
    $${PWD}/OAIOfferContent.cpp \
    $${PWD}/OAIOfferFunctionality.cpp \
    $${PWD}/OAIOfferLinks.cpp \
    $${PWD}/OAIOfferRequest.cpp \
    $${PWD}/OAIOptimisationActionName.cpp \
    $${PWD}/OAIOptimiseAllRequest.cpp \
    $${PWD}/OAIOptimiseRequest.cpp \
    $${PWD}/OAIOrder.cpp \
    $${PWD}/OAIOrderByDirection.cpp \
    $${PWD}/OAIOrderExportationReporting.cpp \
    $${PWD}/OAIOrderExportationReportingProcessingStatus.cpp \
    $${PWD}/OAIOrderExportations.cpp \
    $${PWD}/OAIOrderExportationsLinks.cpp \
    $${PWD}/OAIOrderHarvestErrorValue.cpp \
    $${PWD}/OAIOrderHeader.cpp \
    $${PWD}/OAIOrderHeaderLinks.cpp \
    $${PWD}/OAIOrderHeaderWithLinks.cpp \
    $${PWD}/OAIOrderHistory.cpp \
    $${PWD}/OAIOrderIdentifier.cpp \
    $${PWD}/OAIOrderIdentifierWithETag.cpp \
    $${PWD}/OAIOrderIndex.cpp \
    $${PWD}/OAIOrderIndexLinks.cpp \
    $${PWD}/OAIOrderIndexLovLinks.cpp \
    $${PWD}/OAIOrderInvoiceDesignSettings.cpp \
    $${PWD}/OAIOrderInvoiceGeneralSettings.cpp \
    $${PWD}/OAIOrderItem.cpp \
    $${PWD}/OAIOrderLinks.cpp \
    $${PWD}/OAIOrderListDateSearchType.cpp \
    $${PWD}/OAIOrderListFull.cpp \
    $${PWD}/OAIOrderListFullLinks.cpp \
    $${PWD}/OAIOrderListFullWithLinks.cpp \
    $${PWD}/OAIOrderListLight.cpp \
    $${PWD}/OAIOrderListLightLinks.cpp \
    $${PWD}/OAIOrderListLightWithLinks.cpp \
    $${PWD}/OAIOrderListLinks.cpp \
    $${PWD}/OAIOrderListRequest.cpp \
    $${PWD}/OAIOrderListRequestWithoutPagination.cpp \
    $${PWD}/OAIOrderOperationResponse.cpp \
    $${PWD}/OAIOrderWithLinks.cpp \
    $${PWD}/OAIOrderedReportFilterCommonParameters.cpp \
    $${PWD}/OAIPaginationRequestParameters.cpp \
    $${PWD}/OAIPaginationResult.cpp \
    $${PWD}/OAIPaginationResultLinks.cpp \
    $${PWD}/OAIParameterIn.cpp \
    $${PWD}/OAIParameterType.cpp \
    $${PWD}/OAIPaymentMethod.cpp \
    $${PWD}/OAIPerformanceIndicatorFilter.cpp \
    $${PWD}/OAIPerformanceIndicatorFormula.cpp \
    $${PWD}/OAIPerformanceIndicatorFormulaOperatorName.cpp \
    $${PWD}/OAIPerformanceIndicatorFormulaParameterType.cpp \
    $${PWD}/OAIPerformanceIndicatorType.cpp \
    $${PWD}/OAIPersonalInfo.cpp \
    $${PWD}/OAIPreviewOrderInvoiceRequest.cpp \
    $${PWD}/OAIPreviewOrderInvoiceResponse.cpp \
    $${PWD}/OAIPreviousFixPeriodInvoiceProrataInfo.cpp \
    $${PWD}/OAIProduct.cpp \
    $${PWD}/OAIProductError.cpp \
    $${PWD}/OAIProductErrorCode.cpp \
    $${PWD}/OAIProductList.cpp \
    $${PWD}/OAIProductOverrideWithCatalogValue.cpp \
    $${PWD}/OAIProductSample.cpp \
    $${PWD}/OAIProductSetVisibilityCriteria.cpp \
    $${PWD}/OAIProductSetVisibilityCriteriaLogicType.cpp \
    $${PWD}/OAIProductStateFilter.cpp \
    $${PWD}/OAIProfilePictureInfo.cpp \
    $${PWD}/OAIProfilePictureInfoResponse.cpp \
    $${PWD}/OAIProfilePictureInfoResponseLinks.cpp \
    $${PWD}/OAIProfilePictureInfoWithDefault.cpp \
    $${PWD}/OAIProfilePictureSelected.cpp \
    $${PWD}/OAIPromotionalCodeValidity.cpp \
    $${PWD}/OAIPublicChannelIndex.cpp \
    $${PWD}/OAIPublicChannelIndex_links.cpp \
    $${PWD}/OAIPublicChannelInfo.cpp \
    $${PWD}/OAIPublicChannelInfoList.cpp \
    $${PWD}/OAIPublicChannelInfoList_links.cpp \
    $${PWD}/OAIPublicListOfValuesResponse.cpp \
    $${PWD}/OAIPublicListOfValuesResponseLinks.cpp \
    $${PWD}/OAIPublicLovIndex.cpp \
    $${PWD}/OAIPublicLovIndexLinks.cpp \
    $${PWD}/OAIPublicationFeedReporting.cpp \
    $${PWD}/OAIPublicationReporting.cpp \
    $${PWD}/OAIPublicationStrategyKind.cpp \
    $${PWD}/OAIPublicationType.cpp \
    $${PWD}/OAIPublishCatalogToMarketplaceRequest.cpp \
    $${PWD}/OAIRandomProductList.cpp \
    $${PWD}/OAIRegisterRequest.cpp \
    $${PWD}/OAIReportAdvancedFilters.cpp \
    $${PWD}/OAIReportByCategory.cpp \
    $${PWD}/OAIReportByCategoryLinks.cpp \
    $${PWD}/OAIReportByCategoryRequest.cpp \
    $${PWD}/OAIReportByCategoryResponse.cpp \
    $${PWD}/OAIReportByCategoryResponseLinks.cpp \
    $${PWD}/OAIReportByChannel.cpp \
    $${PWD}/OAIReportByChannelLinks.cpp \
    $${PWD}/OAIReportByChannelRequest.cpp \
    $${PWD}/OAIReportByChannelResponse.cpp \
    $${PWD}/OAIReportByChannelResponseLinks.cpp \
    $${PWD}/OAIReportByCommonResponseLinks.cpp \
    $${PWD}/OAIReportByDay.cpp \
    $${PWD}/OAIReportByDayAllChannels.cpp \
    $${PWD}/OAIReportByDayByChannel.cpp \
    $${PWD}/OAIReportByDayGlobal.cpp \
    $${PWD}/OAIReportByDayGlobalAllChannels.cpp \
    $${PWD}/OAIReportByDayGlobalByChannel.cpp \
    $${PWD}/OAIReportByDayRequest.cpp \
    $${PWD}/OAIReportByDayResponse.cpp \
    $${PWD}/OAIReportByProduct.cpp \
    $${PWD}/OAIReportByProductAllChannelsLinks.cpp \
    $${PWD}/OAIReportByProductLinks.cpp \
    $${PWD}/OAIReportByProductOneChannelLinks.cpp \
    $${PWD}/OAIReportByProductRequest.cpp \
    $${PWD}/OAIReportByProductResponse.cpp \
    $${PWD}/OAIReportByProductResponseLinks.cpp \
    $${PWD}/OAIReportFilter.cpp \
    $${PWD}/OAIReportFilterCommonParameters.cpp \
    $${PWD}/OAIReportFilterHeader.cpp \
    $${PWD}/OAIReportFilterHeaderLinks.cpp \
    $${PWD}/OAIReportFilterLinks.cpp \
    $${PWD}/OAIReportFilterList.cpp \
    $${PWD}/OAIReportFilterParameters.cpp \
    $${PWD}/OAIReportFilterPeriodType.cpp \
    $${PWD}/OAIReportFiltersLinks.cpp \
    $${PWD}/OAIReportType.cpp \
    $${PWD}/OAIRule.cpp \
    $${PWD}/OAIRuleExecutionReporting.cpp \
    $${PWD}/OAIRuleExecutionReportingErrorType.cpp \
    $${PWD}/OAIRuleExecutionReportingExecutionSource.cpp \
    $${PWD}/OAIRuleExecutionReportingLinks.cpp \
    $${PWD}/OAIRuleExecutionReportingStatus.cpp \
    $${PWD}/OAIRuleExecutionReportings.cpp \
    $${PWD}/OAIRuleLastExecutionStatus.cpp \
    $${PWD}/OAIRuleLinks.cpp \
    $${PWD}/OAIRuleList.cpp \
    $${PWD}/OAIRuleListLinks.cpp \
    $${PWD}/OAISaveReportFilterRequest.cpp \
    $${PWD}/OAISaveStoreAlertRequest.cpp \
    $${PWD}/OAIScheduleAutoImportRequest.cpp \
    $${PWD}/OAISchedulingType.cpp \
    $${PWD}/OAISetChannelCatalogMarketplaceSettingsRequest.cpp \
    $${PWD}/OAISetMerchantOrderInfoListRequest.cpp \
    $${PWD}/OAISetMerchantOrderInfoListRequestItem.cpp \
    $${PWD}/OAISetMerchantOrderInfoRequest.cpp \
    $${PWD}/OAISourceType.cpp \
    $${PWD}/OAIStandardOffer.cpp \
    $${PWD}/OAIStandardOfferLinks.cpp \
    $${PWD}/OAIStandardOffers.cpp \
    $${PWD}/OAIStandardOffersLinks.cpp \
    $${PWD}/OAIStartManualImportRequest.cpp \
    $${PWD}/OAIStore.cpp \
    $${PWD}/OAIStoreAlert.cpp \
    $${PWD}/OAIStoreAlertLinks.cpp \
    $${PWD}/OAIStoreAlertProperty.cpp \
    $${PWD}/OAIStoreAlertPropertyInfo.cpp \
    $${PWD}/OAIStoreAlerts.cpp \
    $${PWD}/OAIStoreLinks.cpp \
    $${PWD}/OAIStoreList.cpp \
    $${PWD}/OAIStoreListLinks.cpp \
    $${PWD}/OAIStoreShare.cpp \
    $${PWD}/OAIStoreShareLinks.cpp \
    $${PWD}/OAIStoreShares.cpp \
    $${PWD}/OAIStoreSharesLinks.cpp \
    $${PWD}/OAIStoreStatus.cpp \
    $${PWD}/OAIStoreTrackingStatus.cpp \
    $${PWD}/OAIStoreUserRole.cpp \
    $${PWD}/OAISubscription.cpp \
    $${PWD}/OAISubscriptionIndex.cpp \
    $${PWD}/OAISubscriptionLinks.cpp \
    $${PWD}/OAISubscriptionPushReporting.cpp \
    $${PWD}/OAISubscriptionStatus.cpp \
    $${PWD}/OAISuccessSummary.cpp \
    $${PWD}/OAITerminateContract.cpp \
    $${PWD}/OAITrackedClick.cpp \
    $${PWD}/OAITrackedClicks.cpp \
    $${PWD}/OAITrackedExternalOrder.cpp \
    $${PWD}/OAITrackedExternalOrderProduct.cpp \
    $${PWD}/OAITrackedExternalOrders.cpp \
    $${PWD}/OAITrackedOrder.cpp \
    $${PWD}/OAITrackedOrderProduct.cpp \
    $${PWD}/OAITrackedOrders.cpp \
    $${PWD}/OAITrackingStatus.cpp \
    $${PWD}/OAIType.cpp \
    $${PWD}/OAIUnmapCategoryRequest.cpp \
    $${PWD}/OAIUpdateRuleRequest.cpp \
    $${PWD}/OAIUpdateStoreRequest.cpp \
    $${PWD}/OAIUpgradeOfferRequired.cpp \
    $${PWD}/OAIUserErrorMessage.cpp \
    $${PWD}/OAIUserFriendInfo.cpp \
    $${PWD}/OAIUserListOfValuesResponse.cpp \
    $${PWD}/OAIUserListOfValuesResponseLinks.cpp \
    $${PWD}/OAIUserLovIndex.cpp \
    $${PWD}/OAIUserLovIndexLinks.cpp \
    $${PWD}/OAIVariableModelInfo.cpp \
    $${PWD}/OAIWarningSummary.cpp \
    $${PWD}/OAIZendeskToken.cpp \
# APIs
    $${PWD}/OAIAnalyticsGlobalApi.cpp \
    $${PWD}/OAIAnalyticsOptimisationsApi.cpp \
    $${PWD}/OAIAnalyticsReportsApi.cpp \
    $${PWD}/OAIAnalyticsRulesApi.cpp \
    $${PWD}/OAIAnalyticsStatisticsApi.cpp \
    $${PWD}/OAIAnalyticsTrackingApi.cpp \
    $${PWD}/OAICatalogsAutoApi.cpp \
    $${PWD}/OAICatalogsCatalogApi.cpp \
    $${PWD}/OAICatalogsGlobalApi.cpp \
    $${PWD}/OAICatalogsImportationCatalogInfoApi.cpp \
    $${PWD}/OAICatalogsImportationProcessApi.cpp \
    $${PWD}/OAIChannelCatalogsCategoriesApi.cpp \
    $${PWD}/OAIChannelCatalogsColumnMappingsApi.cpp \
    $${PWD}/OAIChannelCatalogsExclusionFiltersApi.cpp \
    $${PWD}/OAIChannelCatalogsExportationsApi.cpp \
    $${PWD}/OAIChannelCatalogsGlobalApi.cpp \
    $${PWD}/OAIChannelCatalogsLegacyTrackingGlobalApi.cpp \
    $${PWD}/OAIChannelCatalogsProductsApi.cpp \
    $${PWD}/OAIChannelCatalogsProductsOptimisationApi.cpp \
    $${PWD}/OAIChannelCatalogsProductsOverridesApi.cpp \
    $${PWD}/OAIChannelCatalogsSettingsApi.cpp \
    $${PWD}/OAIChannelsChannelsGlobalApi.cpp \
    $${PWD}/OAICustomerAccountApi.cpp \
    $${PWD}/OAICustomerAlertsApi.cpp \
    $${PWD}/OAICustomerContractsApi.cpp \
    $${PWD}/OAICustomerFriendsApi.cpp \
    $${PWD}/OAICustomerGlobalApi.cpp \
    $${PWD}/OAICustomerInvoicesApi.cpp \
    $${PWD}/OAICustomerRightsApi.cpp \
    $${PWD}/OAICustomerSecurityApi.cpp \
    $${PWD}/OAICustomerSharesApi.cpp \
    $${PWD}/OAICustomerStoresApi.cpp \
    $${PWD}/OAIMarketplacesChannelCatalogsGlobalApi.cpp \
    $${PWD}/OAIMarketplacesChannelCatalogsPublicationsApi.cpp \
    $${PWD}/OAIMarketplacesChannelCatalogsSettingsApi.cpp \
    $${PWD}/OAIMarketplacesOrdersAutoTransitionsApi.cpp \
    $${PWD}/OAIMarketplacesOrdersBatchesApi.cpp \
    $${PWD}/OAIMarketplacesOrdersExportsApi.cpp \
    $${PWD}/OAIMarketplacesOrdersGlobalApi.cpp \
    $${PWD}/OAIMarketplacesOrdersListApi.cpp \
    $${PWD}/OAIMarketplacesOrdersOrderApi.cpp \
    $${PWD}/OAIMarketplacesOrdersSubscriptionsSubscriptionsApi.cpp \
    $${PWD}/OAIMarketplacesOrdersV3BatchesApi.cpp \
    $${PWD}/OAIMarketplacesOrdersV3GlobalApi.cpp \
    $${PWD}/OAIMarketplacesOrdersV3ListApi.cpp \
    $${PWD}/OAIMarketplacesOrdersV3OrderApi.cpp \
    $${PWD}/OAIOMInvoiceAPIGenerationApi.cpp \
    $${PWD}/OAIOMInvoiceAPISettingsApi.cpp \
    $${PWD}/OAIPublicChannelsPublicChannelsApi.cpp \
    $${PWD}/OAIPublicListOfValuesLOVApi.cpp \
    $${PWD}/OAIPublicSecuritySecurityApi.cpp \
    $${PWD}/OAIUserListOfValuesLOVApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
