QT += network

HEADERS += \
# Models
    $${PWD}/OAIAGCOPowerServices_Models_ECU.h \
    $${PWD}/OAIAGCOPowerServices_Models_ProductionData.h \
    $${PWD}/OAIAGCOPowerServices_Models_UserStatus.h \
    $${PWD}/OAIAPI_IPagedResponse_AuthorizationCodes_Shared_Models_AuthorizationCodeDefinition_.h \
    $${PWD}/OAIAPI_IPagedResponse_AuthorizationCodes_Shared_Models_AuthorizationCode_.h \
    $${PWD}/OAIAPI_IPagedResponse_AuthorizationCodes_Shared_Models_AuthorizationContactInformation_.h \
    $${PWD}/OAIAPI_IPagedResponse_AuthorizationCodes_Shared_Models_CategoryUserReport_.h \
    $${PWD}/OAIAPI_IPagedResponse_AuthorizationCodes_Shared_Models_Category_.h \
    $${PWD}/OAIAPI_IPagedResponse_GlobalResources_Shared_Models_FileDownload_.h \
    $${PWD}/OAIAPI_IPagedResponse_GlobalResources_Shared_Models_GlobalImageCategory_.h \
    $${PWD}/OAIAPI_IPagedResponse_GlobalResources_Shared_Models_GlobalImage_.h \
    $${PWD}/OAIAPI_IPagedResponse_GlobalResources_Shared_Models_Language_.h \
    $${PWD}/OAIAPI_IPagedResponse_GlobalResources_Shared_Models_StringDefinition_.h \
    $${PWD}/OAIAPI_IPagedResponse_GlobalResources_Shared_Models_StringTranslation_.h \
    $${PWD}/OAIAPI_IPagedResponse_GlobalResources_Shared_Models_TranslationRequest_.h \
    $${PWD}/OAIAPI_IPagedResponse_GlobalResources_Shared_Models_TranslationSetAttribute_.h \
    $${PWD}/OAIAPI_IPagedResponse_GlobalResources_Shared_Models_TranslationSetSourceString_.h \
    $${PWD}/OAIAPI_IPagedResponse_GlobalResources_Shared_Models_TranslationSetString_.h \
    $${PWD}/OAIAPI_IPagedResponse_GlobalResources_Shared_Models_TranslationSet_.h \
    $${PWD}/OAIAPI_IPagedResponse_OASSupport_Shared_Models_TranslationKey_.h \
    $${PWD}/OAIAPI_Models_ApiError.h \
    $${PWD}/OAIAPI_Models_AuthenticatedUser.h \
    $${PWD}/OAIAPI_Models_Credentials.h \
    $${PWD}/OAIAPI_Models_Log.h \
    $${PWD}/OAIAPI_Models_Notification.h \
    $${PWD}/OAIAPI_Models_PasswordReset.h \
    $${PWD}/OAIAPI_Models_PasswordResetRequest.h \
    $${PWD}/OAIAPI_Models_Permission.h \
    $${PWD}/OAIAPI_Models_Role.h \
    $${PWD}/OAIAPI_Models_RolePermissionChange.h \
    $${PWD}/OAIAPI_Models_RoleUserChange.h \
    $${PWD}/OAIAPI_Models_TokenOptions.h \
    $${PWD}/OAIAPI_Models_User.h \
    $${PWD}/OAIAPI_Models_UserEffectivePermission.h \
    $${PWD}/OAIAPI_Models_UserRoleChange.h \
    $${PWD}/OAIAPI_PagedResponseMetadata.h \
    $${PWD}/OAIAPI_PagedResponse_API_Models_Log_.h \
    $${PWD}/OAIAPI_PagedResponse_API_Models_Permission_.h \
    $${PWD}/OAIAPI_PagedResponse_API_Models_Role_.h \
    $${PWD}/OAIAPI_PagedResponse_API_Models_UserEffectivePermission_.h \
    $${PWD}/OAIAPI_PagedResponse_API_Models_User_.h \
    $${PWD}/OAIAPI_PagedResponse_BuildSystem_Shared_DTO_ActivityRun_.h \
    $${PWD}/OAIAPI_PagedResponse_BuildSystem_Shared_DTO_Activity_.h \
    $${PWD}/OAIAPI_PagedResponse_BuildSystem_Shared_DTO_Agent_.h \
    $${PWD}/OAIAPI_PagedResponse_BuildSystem_Shared_DTO_JobRun_.h \
    $${PWD}/OAIAPI_PagedResponse_BuildSystem_Shared_DTO_Job_.h \
    $${PWD}/OAIAPI_PagedResponse_BuildSystem_Shared_DTO_Step_.h \
    $${PWD}/OAIAPI_PagedResponse_ContentSubmission_Shared_BusinessEntities_ContentDefinitionAttribute_.h \
    $${PWD}/OAIAPI_PagedResponse_ContentSubmission_Shared_BusinessEntities_ContentDefinition_.h \
    $${PWD}/OAIAPI_PagedResponse_ContentSubmission_Shared_BusinessEntities_ContentReleaseVersion_.h \
    $${PWD}/OAIAPI_PagedResponse_ContentSubmission_Shared_BusinessEntities_ContentSubmissionAttribute_.h \
    $${PWD}/OAIAPI_PagedResponse_ContentSubmission_Shared_BusinessEntities_ContentSubmission_.h \
    $${PWD}/OAIAPI_PagedResponse_ContentSubmission_Shared_BusinessEntities_Release_.h \
    $${PWD}/OAIAPI_PagedResponse_ContentSubmission_Shared_BusinessEntities_UserContentDefinition_.h \
    $${PWD}/OAIAPI_PagedResponse_DealerDB_Models_Dealer_.h \
    $${PWD}/OAIAPI_PagedResponse_DealerDB_Models_DealersPerCountry_.h \
    $${PWD}/OAIAPI_PagedResponse_DealerDB_Models_License_.h \
    $${PWD}/OAIAPI_PagedResponse_DealerDB_Models_VoucherHistory_.h \
    $${PWD}/OAIAPI_PagedResponse_DealerDB_Models_Voucher_.h \
    $${PWD}/OAIAPI_PagedResponse_UpdateSystem_Models_AvailableUpdateGroupSubscription_.h \
    $${PWD}/OAIAPI_PagedResponse_UpdateSystem_Models_Bundle_.h \
    $${PWD}/OAIAPI_PagedResponse_UpdateSystem_Models_ClientStatus_UpdateSystem_Models_PagedClientStatusMetadata_.h \
    $${PWD}/OAIAPI_PagedResponse_UpdateSystem_Models_Client_.h \
    $${PWD}/OAIAPI_PagedResponse_UpdateSystem_Models_PackageStatusSummary_.h \
    $${PWD}/OAIAPI_PagedResponse_UpdateSystem_Models_PackageTypeIDtoBundle_.h \
    $${PWD}/OAIAPI_PagedResponse_UpdateSystem_Models_PackageType_.h \
    $${PWD}/OAIAPI_PagedResponse_UpdateSystem_Models_Package_.h \
    $${PWD}/OAIAPI_PagedResponse_UpdateSystem_Models_PriorityPackage_.h \
    $${PWD}/OAIAPI_PagedResponse_UpdateSystem_Models_UpdateGroupClientRelationship_.h \
    $${PWD}/OAIAPI_PagedResponse_UpdateSystem_Models_UpdateGroupSubscription_.h \
    $${PWD}/OAIAPI_PagedResponse_UpdateSystem_Models_UpdateGroup_.h \
    $${PWD}/OAIAuthorizationCodes_Shared_Models_AuthorizationCode.h \
    $${PWD}/OAIAuthorizationCodes_Shared_Models_AuthorizationCodeDefinition.h \
    $${PWD}/OAIAuthorizationCodes_Shared_Models_AuthorizationCodeUser.h \
    $${PWD}/OAIAuthorizationCodes_Shared_Models_AuthorizationContactInformation.h \
    $${PWD}/OAIAuthorizationCodes_Shared_Models_Category.h \
    $${PWD}/OAIAuthorizationCodes_Shared_Models_CategoryUserReport.h \
    $${PWD}/OAIAuthorizationCodes_Shared_Models_CodeValidationModel.h \
    $${PWD}/OAIAuthorizationCodes_Shared_Models_DataField.h \
    $${PWD}/OAIAuthorizationCodes_Shared_Models_Parameter.h \
    $${PWD}/OAIAuthorizationCodes_Shared_Models_ValidationField.h \
    $${PWD}/OAIBuildSystem_Shared_DTO_Activity.h \
    $${PWD}/OAIBuildSystem_Shared_DTO_ActivityRun.h \
    $${PWD}/OAIBuildSystem_Shared_DTO_ActivityRunStatus.h \
    $${PWD}/OAIBuildSystem_Shared_DTO_ActivityStep.h \
    $${PWD}/OAIBuildSystem_Shared_DTO_Agent.h \
    $${PWD}/OAIBuildSystem_Shared_DTO_AgentStatus.h \
    $${PWD}/OAIBuildSystem_Shared_DTO_Job.h \
    $${PWD}/OAIBuildSystem_Shared_DTO_JobActivity.h \
    $${PWD}/OAIBuildSystem_Shared_DTO_JobRun.h \
    $${PWD}/OAIBuildSystem_Shared_DTO_Parameter.h \
    $${PWD}/OAIBuildSystem_Shared_DTO_ParameterMapping.h \
    $${PWD}/OAIBuildSystem_Shared_DTO_ParameterValue.h \
    $${PWD}/OAIBuildSystem_Shared_DTO_Step.h \
    $${PWD}/OAIBuildSystem_Shared_DTO_StepConfiguration.h \
    $${PWD}/OAIBuildSystem_Shared_Interfaces_IActivityRun.h \
    $${PWD}/OAIBuildSystem_Shared_Interfaces_IActivityRunStatus.h \
    $${PWD}/OAIBuildSystem_Shared_Interfaces_IActivityStep.h \
    $${PWD}/OAIBuildSystem_Shared_Interfaces_IJobRun.h \
    $${PWD}/OAIBuildSystem_Shared_Interfaces_IParameterMapping.h \
    $${PWD}/OAIBuildSystem_Shared_Interfaces_IParameterValue.h \
    $${PWD}/OAIContentSubmission_Shared_BusinessEntities_ContentDefinition.h \
    $${PWD}/OAIContentSubmission_Shared_BusinessEntities_ContentDefinitionAttribute.h \
    $${PWD}/OAIContentSubmission_Shared_BusinessEntities_ContentReleaseVersion.h \
    $${PWD}/OAIContentSubmission_Shared_BusinessEntities_ContentSubmission.h \
    $${PWD}/OAIContentSubmission_Shared_BusinessEntities_ContentSubmissionAttribute.h \
    $${PWD}/OAIContentSubmission_Shared_BusinessEntities_ContentSubmissionType.h \
    $${PWD}/OAIContentSubmission_Shared_BusinessEntities_Release.h \
    $${PWD}/OAIContentSubmission_Shared_BusinessEntities_UserContentDefinition.h \
    $${PWD}/OAIDealerDB_Models_Dealer.h \
    $${PWD}/OAIDealerDB_Models_DealersPerCountry.h \
    $${PWD}/OAIDealerDB_Models_EDTLiteRegistration.h \
    $${PWD}/OAIDealerDB_Models_License.h \
    $${PWD}/OAIDealerDB_Models_LicenseActivation.h \
    $${PWD}/OAIDealerDB_Models_LicenseActivationConfirm.h \
    $${PWD}/OAIDealerDB_Models_LicenseActivationCreate.h \
    $${PWD}/OAIDealerDB_Models_LicenseActivationUpdate.h \
    $${PWD}/OAIDealerDB_Models_Voucher.h \
    $${PWD}/OAIDealerDB_Models_VoucherHistory.h \
    $${PWD}/OAIGlobalResources_Shared_Models_FileDownload.h \
    $${PWD}/OAIGlobalResources_Shared_Models_GlobalImage.h \
    $${PWD}/OAIGlobalResources_Shared_Models_GlobalImageCategory.h \
    $${PWD}/OAIGlobalResources_Shared_Models_Language.h \
    $${PWD}/OAIGlobalResources_Shared_Models_StringDefinition.h \
    $${PWD}/OAIGlobalResources_Shared_Models_StringTranslation.h \
    $${PWD}/OAIGlobalResources_Shared_Models_TranslationRequest.h \
    $${PWD}/OAIGlobalResources_Shared_Models_TranslationSet.h \
    $${PWD}/OAIGlobalResources_Shared_Models_TranslationSetAttribute.h \
    $${PWD}/OAIGlobalResources_Shared_Models_TranslationSetSourceString.h \
    $${PWD}/OAIGlobalResources_Shared_Models_TranslationSetStatistics.h \
    $${PWD}/OAIGlobalResources_Shared_Models_TranslationSetString.h \
    $${PWD}/OAIOASSupport_Shared_Models_TranslationKey.h \
    $${PWD}/OAIUpdateSystem_Models_AttributeValue.h \
    $${PWD}/OAIUpdateSystem_Models_AvailableSubscription.h \
    $${PWD}/OAIUpdateSystem_Models_AvailableUpdateGroupSubscription.h \
    $${PWD}/OAIUpdateSystem_Models_Bundle.h \
    $${PWD}/OAIUpdateSystem_Models_Category.h \
    $${PWD}/OAIUpdateSystem_Models_CheckinResult.h \
    $${PWD}/OAIUpdateSystem_Models_Client.h \
    $${PWD}/OAIUpdateSystem_Models_ClientInfo.h \
    $${PWD}/OAIUpdateSystem_Models_ClientStatus.h \
    $${PWD}/OAIUpdateSystem_Models_Package.h \
    $${PWD}/OAIUpdateSystem_Models_PackageReport.h \
    $${PWD}/OAIUpdateSystem_Models_PackageStatus.h \
    $${PWD}/OAIUpdateSystem_Models_PackageStatusSummary.h \
    $${PWD}/OAIUpdateSystem_Models_PackageType.h \
    $${PWD}/OAIUpdateSystem_Models_PackageTypeIDtoBundle.h \
    $${PWD}/OAIUpdateSystem_Models_PagedClientStatusMetadata.h \
    $${PWD}/OAIUpdateSystem_Models_PriorityPackage.h \
    $${PWD}/OAIUpdateSystem_Models_UpdateGroup.h \
    $${PWD}/OAIUpdateSystem_Models_UpdateGroupClientRelationship.h \
    $${PWD}/OAIUpdateSystem_Models_UpdateGroupSubscription.h \
    $${PWD}/OAIUpdateSystem_Models_UpdateMetricsData.h \
    $${PWD}/OAIUpdateSystem_Models_UpdateMetricsData_ActiveVersionByClientRecord.h \
    $${PWD}/OAIUpdateSystem_Models_UpdateMetricsData_CurrentStateByClientRecord.h \
    $${PWD}/OAIUpdateSystem_Models_UpdateMetricsData_PackageErrorsRecord.h \
# APIs
    $${PWD}/OAIActivitiesApi.h \
    $${PWD}/OAIActivityRunsApi.h \
    $${PWD}/OAIAftermarketServicesApi.h \
    $${PWD}/OAIAgentsApi.h \
    $${PWD}/OAIAuthenticationApi.h \
    $${PWD}/OAIAuthorizationCategoriesApi.h \
    $${PWD}/OAIAuthorizationCodeDefinitionsApi.h \
    $${PWD}/OAIAuthorizationCodesApi.h \
    $${PWD}/OAIAuthorizationContactInformationApi.h \
    $${PWD}/OAIBrandsApi.h \
    $${PWD}/OAIBundlesApi.h \
    $${PWD}/OAIClientsApi.h \
    $${PWD}/OAIContentDefinitionsApi.h \
    $${PWD}/OAIContentReleaseApi.h \
    $${PWD}/OAIContentSubmissionTypesApi.h \
    $${PWD}/OAIContentSubmissionsApi.h \
    $${PWD}/OAIDealerByCountryApi.h \
    $${PWD}/OAIDealersApi.h \
    $${PWD}/OAIFilesApi.h \
    $${PWD}/OAIGlobalImageCategoriesApi.h \
    $${PWD}/OAIGlobalImagesApi.h \
    $${PWD}/OAIJobRunsApi.h \
    $${PWD}/OAIJobsApi.h \
    $${PWD}/OAILanguagesApi.h \
    $${PWD}/OAILicenseActivationsApi.h \
    $${PWD}/OAILicensesApi.h \
    $${PWD}/OAILogsApi.h \
    $${PWD}/OAINotificationsApi.h \
    $${PWD}/OAIPackageReportsApi.h \
    $${PWD}/OAIPackageTypesApi.h \
    $${PWD}/OAIPackageTypetoBundlesApi.h \
    $${PWD}/OAIPackagesApi.h \
    $${PWD}/OAIPermissionsApi.h \
    $${PWD}/OAIPriorityPackagesApi.h \
    $${PWD}/OAIReleaseApi.h \
    $${PWD}/OAIReportingApi.h \
    $${PWD}/OAIRolesApi.h \
    $${PWD}/OAIStepsApi.h \
    $${PWD}/OAIStringDefinitionsApi.h \
    $${PWD}/OAIStringTranslationsApi.h \
    $${PWD}/OAITranslationKeysApi.h \
    $${PWD}/OAITranslationRequestsApi.h \
    $${PWD}/OAITranslationSetsApi.h \
    $${PWD}/OAIUpdateGroupClientRelationshipsApi.h \
    $${PWD}/OAIUpdateGroupSubscriptionsApi.h \
    $${PWD}/OAIUpdateGroupsApi.h \
    $${PWD}/OAIUpdateSystemApi.h \
    $${PWD}/OAIUserContentDefinitionsApi.h \
    $${PWD}/OAIUserPermissionsApi.h \
    $${PWD}/OAIUsersApi.h \
    $${PWD}/OAIVoucherHistoryApi.h \
    $${PWD}/OAIVouchersApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAGCOPowerServices_Models_ECU.cpp \
    $${PWD}/OAIAGCOPowerServices_Models_ProductionData.cpp \
    $${PWD}/OAIAGCOPowerServices_Models_UserStatus.cpp \
    $${PWD}/OAIAPI_IPagedResponse_AuthorizationCodes_Shared_Models_AuthorizationCodeDefinition_.cpp \
    $${PWD}/OAIAPI_IPagedResponse_AuthorizationCodes_Shared_Models_AuthorizationCode_.cpp \
    $${PWD}/OAIAPI_IPagedResponse_AuthorizationCodes_Shared_Models_AuthorizationContactInformation_.cpp \
    $${PWD}/OAIAPI_IPagedResponse_AuthorizationCodes_Shared_Models_CategoryUserReport_.cpp \
    $${PWD}/OAIAPI_IPagedResponse_AuthorizationCodes_Shared_Models_Category_.cpp \
    $${PWD}/OAIAPI_IPagedResponse_GlobalResources_Shared_Models_FileDownload_.cpp \
    $${PWD}/OAIAPI_IPagedResponse_GlobalResources_Shared_Models_GlobalImageCategory_.cpp \
    $${PWD}/OAIAPI_IPagedResponse_GlobalResources_Shared_Models_GlobalImage_.cpp \
    $${PWD}/OAIAPI_IPagedResponse_GlobalResources_Shared_Models_Language_.cpp \
    $${PWD}/OAIAPI_IPagedResponse_GlobalResources_Shared_Models_StringDefinition_.cpp \
    $${PWD}/OAIAPI_IPagedResponse_GlobalResources_Shared_Models_StringTranslation_.cpp \
    $${PWD}/OAIAPI_IPagedResponse_GlobalResources_Shared_Models_TranslationRequest_.cpp \
    $${PWD}/OAIAPI_IPagedResponse_GlobalResources_Shared_Models_TranslationSetAttribute_.cpp \
    $${PWD}/OAIAPI_IPagedResponse_GlobalResources_Shared_Models_TranslationSetSourceString_.cpp \
    $${PWD}/OAIAPI_IPagedResponse_GlobalResources_Shared_Models_TranslationSetString_.cpp \
    $${PWD}/OAIAPI_IPagedResponse_GlobalResources_Shared_Models_TranslationSet_.cpp \
    $${PWD}/OAIAPI_IPagedResponse_OASSupport_Shared_Models_TranslationKey_.cpp \
    $${PWD}/OAIAPI_Models_ApiError.cpp \
    $${PWD}/OAIAPI_Models_AuthenticatedUser.cpp \
    $${PWD}/OAIAPI_Models_Credentials.cpp \
    $${PWD}/OAIAPI_Models_Log.cpp \
    $${PWD}/OAIAPI_Models_Notification.cpp \
    $${PWD}/OAIAPI_Models_PasswordReset.cpp \
    $${PWD}/OAIAPI_Models_PasswordResetRequest.cpp \
    $${PWD}/OAIAPI_Models_Permission.cpp \
    $${PWD}/OAIAPI_Models_Role.cpp \
    $${PWD}/OAIAPI_Models_RolePermissionChange.cpp \
    $${PWD}/OAIAPI_Models_RoleUserChange.cpp \
    $${PWD}/OAIAPI_Models_TokenOptions.cpp \
    $${PWD}/OAIAPI_Models_User.cpp \
    $${PWD}/OAIAPI_Models_UserEffectivePermission.cpp \
    $${PWD}/OAIAPI_Models_UserRoleChange.cpp \
    $${PWD}/OAIAPI_PagedResponseMetadata.cpp \
    $${PWD}/OAIAPI_PagedResponse_API_Models_Log_.cpp \
    $${PWD}/OAIAPI_PagedResponse_API_Models_Permission_.cpp \
    $${PWD}/OAIAPI_PagedResponse_API_Models_Role_.cpp \
    $${PWD}/OAIAPI_PagedResponse_API_Models_UserEffectivePermission_.cpp \
    $${PWD}/OAIAPI_PagedResponse_API_Models_User_.cpp \
    $${PWD}/OAIAPI_PagedResponse_BuildSystem_Shared_DTO_ActivityRun_.cpp \
    $${PWD}/OAIAPI_PagedResponse_BuildSystem_Shared_DTO_Activity_.cpp \
    $${PWD}/OAIAPI_PagedResponse_BuildSystem_Shared_DTO_Agent_.cpp \
    $${PWD}/OAIAPI_PagedResponse_BuildSystem_Shared_DTO_JobRun_.cpp \
    $${PWD}/OAIAPI_PagedResponse_BuildSystem_Shared_DTO_Job_.cpp \
    $${PWD}/OAIAPI_PagedResponse_BuildSystem_Shared_DTO_Step_.cpp \
    $${PWD}/OAIAPI_PagedResponse_ContentSubmission_Shared_BusinessEntities_ContentDefinitionAttribute_.cpp \
    $${PWD}/OAIAPI_PagedResponse_ContentSubmission_Shared_BusinessEntities_ContentDefinition_.cpp \
    $${PWD}/OAIAPI_PagedResponse_ContentSubmission_Shared_BusinessEntities_ContentReleaseVersion_.cpp \
    $${PWD}/OAIAPI_PagedResponse_ContentSubmission_Shared_BusinessEntities_ContentSubmissionAttribute_.cpp \
    $${PWD}/OAIAPI_PagedResponse_ContentSubmission_Shared_BusinessEntities_ContentSubmission_.cpp \
    $${PWD}/OAIAPI_PagedResponse_ContentSubmission_Shared_BusinessEntities_Release_.cpp \
    $${PWD}/OAIAPI_PagedResponse_ContentSubmission_Shared_BusinessEntities_UserContentDefinition_.cpp \
    $${PWD}/OAIAPI_PagedResponse_DealerDB_Models_Dealer_.cpp \
    $${PWD}/OAIAPI_PagedResponse_DealerDB_Models_DealersPerCountry_.cpp \
    $${PWD}/OAIAPI_PagedResponse_DealerDB_Models_License_.cpp \
    $${PWD}/OAIAPI_PagedResponse_DealerDB_Models_VoucherHistory_.cpp \
    $${PWD}/OAIAPI_PagedResponse_DealerDB_Models_Voucher_.cpp \
    $${PWD}/OAIAPI_PagedResponse_UpdateSystem_Models_AvailableUpdateGroupSubscription_.cpp \
    $${PWD}/OAIAPI_PagedResponse_UpdateSystem_Models_Bundle_.cpp \
    $${PWD}/OAIAPI_PagedResponse_UpdateSystem_Models_ClientStatus_UpdateSystem_Models_PagedClientStatusMetadata_.cpp \
    $${PWD}/OAIAPI_PagedResponse_UpdateSystem_Models_Client_.cpp \
    $${PWD}/OAIAPI_PagedResponse_UpdateSystem_Models_PackageStatusSummary_.cpp \
    $${PWD}/OAIAPI_PagedResponse_UpdateSystem_Models_PackageTypeIDtoBundle_.cpp \
    $${PWD}/OAIAPI_PagedResponse_UpdateSystem_Models_PackageType_.cpp \
    $${PWD}/OAIAPI_PagedResponse_UpdateSystem_Models_Package_.cpp \
    $${PWD}/OAIAPI_PagedResponse_UpdateSystem_Models_PriorityPackage_.cpp \
    $${PWD}/OAIAPI_PagedResponse_UpdateSystem_Models_UpdateGroupClientRelationship_.cpp \
    $${PWD}/OAIAPI_PagedResponse_UpdateSystem_Models_UpdateGroupSubscription_.cpp \
    $${PWD}/OAIAPI_PagedResponse_UpdateSystem_Models_UpdateGroup_.cpp \
    $${PWD}/OAIAuthorizationCodes_Shared_Models_AuthorizationCode.cpp \
    $${PWD}/OAIAuthorizationCodes_Shared_Models_AuthorizationCodeDefinition.cpp \
    $${PWD}/OAIAuthorizationCodes_Shared_Models_AuthorizationCodeUser.cpp \
    $${PWD}/OAIAuthorizationCodes_Shared_Models_AuthorizationContactInformation.cpp \
    $${PWD}/OAIAuthorizationCodes_Shared_Models_Category.cpp \
    $${PWD}/OAIAuthorizationCodes_Shared_Models_CategoryUserReport.cpp \
    $${PWD}/OAIAuthorizationCodes_Shared_Models_CodeValidationModel.cpp \
    $${PWD}/OAIAuthorizationCodes_Shared_Models_DataField.cpp \
    $${PWD}/OAIAuthorizationCodes_Shared_Models_Parameter.cpp \
    $${PWD}/OAIAuthorizationCodes_Shared_Models_ValidationField.cpp \
    $${PWD}/OAIBuildSystem_Shared_DTO_Activity.cpp \
    $${PWD}/OAIBuildSystem_Shared_DTO_ActivityRun.cpp \
    $${PWD}/OAIBuildSystem_Shared_DTO_ActivityRunStatus.cpp \
    $${PWD}/OAIBuildSystem_Shared_DTO_ActivityStep.cpp \
    $${PWD}/OAIBuildSystem_Shared_DTO_Agent.cpp \
    $${PWD}/OAIBuildSystem_Shared_DTO_AgentStatus.cpp \
    $${PWD}/OAIBuildSystem_Shared_DTO_Job.cpp \
    $${PWD}/OAIBuildSystem_Shared_DTO_JobActivity.cpp \
    $${PWD}/OAIBuildSystem_Shared_DTO_JobRun.cpp \
    $${PWD}/OAIBuildSystem_Shared_DTO_Parameter.cpp \
    $${PWD}/OAIBuildSystem_Shared_DTO_ParameterMapping.cpp \
    $${PWD}/OAIBuildSystem_Shared_DTO_ParameterValue.cpp \
    $${PWD}/OAIBuildSystem_Shared_DTO_Step.cpp \
    $${PWD}/OAIBuildSystem_Shared_DTO_StepConfiguration.cpp \
    $${PWD}/OAIBuildSystem_Shared_Interfaces_IActivityRun.cpp \
    $${PWD}/OAIBuildSystem_Shared_Interfaces_IActivityRunStatus.cpp \
    $${PWD}/OAIBuildSystem_Shared_Interfaces_IActivityStep.cpp \
    $${PWD}/OAIBuildSystem_Shared_Interfaces_IJobRun.cpp \
    $${PWD}/OAIBuildSystem_Shared_Interfaces_IParameterMapping.cpp \
    $${PWD}/OAIBuildSystem_Shared_Interfaces_IParameterValue.cpp \
    $${PWD}/OAIContentSubmission_Shared_BusinessEntities_ContentDefinition.cpp \
    $${PWD}/OAIContentSubmission_Shared_BusinessEntities_ContentDefinitionAttribute.cpp \
    $${PWD}/OAIContentSubmission_Shared_BusinessEntities_ContentReleaseVersion.cpp \
    $${PWD}/OAIContentSubmission_Shared_BusinessEntities_ContentSubmission.cpp \
    $${PWD}/OAIContentSubmission_Shared_BusinessEntities_ContentSubmissionAttribute.cpp \
    $${PWD}/OAIContentSubmission_Shared_BusinessEntities_ContentSubmissionType.cpp \
    $${PWD}/OAIContentSubmission_Shared_BusinessEntities_Release.cpp \
    $${PWD}/OAIContentSubmission_Shared_BusinessEntities_UserContentDefinition.cpp \
    $${PWD}/OAIDealerDB_Models_Dealer.cpp \
    $${PWD}/OAIDealerDB_Models_DealersPerCountry.cpp \
    $${PWD}/OAIDealerDB_Models_EDTLiteRegistration.cpp \
    $${PWD}/OAIDealerDB_Models_License.cpp \
    $${PWD}/OAIDealerDB_Models_LicenseActivation.cpp \
    $${PWD}/OAIDealerDB_Models_LicenseActivationConfirm.cpp \
    $${PWD}/OAIDealerDB_Models_LicenseActivationCreate.cpp \
    $${PWD}/OAIDealerDB_Models_LicenseActivationUpdate.cpp \
    $${PWD}/OAIDealerDB_Models_Voucher.cpp \
    $${PWD}/OAIDealerDB_Models_VoucherHistory.cpp \
    $${PWD}/OAIGlobalResources_Shared_Models_FileDownload.cpp \
    $${PWD}/OAIGlobalResources_Shared_Models_GlobalImage.cpp \
    $${PWD}/OAIGlobalResources_Shared_Models_GlobalImageCategory.cpp \
    $${PWD}/OAIGlobalResources_Shared_Models_Language.cpp \
    $${PWD}/OAIGlobalResources_Shared_Models_StringDefinition.cpp \
    $${PWD}/OAIGlobalResources_Shared_Models_StringTranslation.cpp \
    $${PWD}/OAIGlobalResources_Shared_Models_TranslationRequest.cpp \
    $${PWD}/OAIGlobalResources_Shared_Models_TranslationSet.cpp \
    $${PWD}/OAIGlobalResources_Shared_Models_TranslationSetAttribute.cpp \
    $${PWD}/OAIGlobalResources_Shared_Models_TranslationSetSourceString.cpp \
    $${PWD}/OAIGlobalResources_Shared_Models_TranslationSetStatistics.cpp \
    $${PWD}/OAIGlobalResources_Shared_Models_TranslationSetString.cpp \
    $${PWD}/OAIOASSupport_Shared_Models_TranslationKey.cpp \
    $${PWD}/OAIUpdateSystem_Models_AttributeValue.cpp \
    $${PWD}/OAIUpdateSystem_Models_AvailableSubscription.cpp \
    $${PWD}/OAIUpdateSystem_Models_AvailableUpdateGroupSubscription.cpp \
    $${PWD}/OAIUpdateSystem_Models_Bundle.cpp \
    $${PWD}/OAIUpdateSystem_Models_Category.cpp \
    $${PWD}/OAIUpdateSystem_Models_CheckinResult.cpp \
    $${PWD}/OAIUpdateSystem_Models_Client.cpp \
    $${PWD}/OAIUpdateSystem_Models_ClientInfo.cpp \
    $${PWD}/OAIUpdateSystem_Models_ClientStatus.cpp \
    $${PWD}/OAIUpdateSystem_Models_Package.cpp \
    $${PWD}/OAIUpdateSystem_Models_PackageReport.cpp \
    $${PWD}/OAIUpdateSystem_Models_PackageStatus.cpp \
    $${PWD}/OAIUpdateSystem_Models_PackageStatusSummary.cpp \
    $${PWD}/OAIUpdateSystem_Models_PackageType.cpp \
    $${PWD}/OAIUpdateSystem_Models_PackageTypeIDtoBundle.cpp \
    $${PWD}/OAIUpdateSystem_Models_PagedClientStatusMetadata.cpp \
    $${PWD}/OAIUpdateSystem_Models_PriorityPackage.cpp \
    $${PWD}/OAIUpdateSystem_Models_UpdateGroup.cpp \
    $${PWD}/OAIUpdateSystem_Models_UpdateGroupClientRelationship.cpp \
    $${PWD}/OAIUpdateSystem_Models_UpdateGroupSubscription.cpp \
    $${PWD}/OAIUpdateSystem_Models_UpdateMetricsData.cpp \
    $${PWD}/OAIUpdateSystem_Models_UpdateMetricsData_ActiveVersionByClientRecord.cpp \
    $${PWD}/OAIUpdateSystem_Models_UpdateMetricsData_CurrentStateByClientRecord.cpp \
    $${PWD}/OAIUpdateSystem_Models_UpdateMetricsData_PackageErrorsRecord.cpp \
# APIs
    $${PWD}/OAIActivitiesApi.cpp \
    $${PWD}/OAIActivityRunsApi.cpp \
    $${PWD}/OAIAftermarketServicesApi.cpp \
    $${PWD}/OAIAgentsApi.cpp \
    $${PWD}/OAIAuthenticationApi.cpp \
    $${PWD}/OAIAuthorizationCategoriesApi.cpp \
    $${PWD}/OAIAuthorizationCodeDefinitionsApi.cpp \
    $${PWD}/OAIAuthorizationCodesApi.cpp \
    $${PWD}/OAIAuthorizationContactInformationApi.cpp \
    $${PWD}/OAIBrandsApi.cpp \
    $${PWD}/OAIBundlesApi.cpp \
    $${PWD}/OAIClientsApi.cpp \
    $${PWD}/OAIContentDefinitionsApi.cpp \
    $${PWD}/OAIContentReleaseApi.cpp \
    $${PWD}/OAIContentSubmissionTypesApi.cpp \
    $${PWD}/OAIContentSubmissionsApi.cpp \
    $${PWD}/OAIDealerByCountryApi.cpp \
    $${PWD}/OAIDealersApi.cpp \
    $${PWD}/OAIFilesApi.cpp \
    $${PWD}/OAIGlobalImageCategoriesApi.cpp \
    $${PWD}/OAIGlobalImagesApi.cpp \
    $${PWD}/OAIJobRunsApi.cpp \
    $${PWD}/OAIJobsApi.cpp \
    $${PWD}/OAILanguagesApi.cpp \
    $${PWD}/OAILicenseActivationsApi.cpp \
    $${PWD}/OAILicensesApi.cpp \
    $${PWD}/OAILogsApi.cpp \
    $${PWD}/OAINotificationsApi.cpp \
    $${PWD}/OAIPackageReportsApi.cpp \
    $${PWD}/OAIPackageTypesApi.cpp \
    $${PWD}/OAIPackageTypetoBundlesApi.cpp \
    $${PWD}/OAIPackagesApi.cpp \
    $${PWD}/OAIPermissionsApi.cpp \
    $${PWD}/OAIPriorityPackagesApi.cpp \
    $${PWD}/OAIReleaseApi.cpp \
    $${PWD}/OAIReportingApi.cpp \
    $${PWD}/OAIRolesApi.cpp \
    $${PWD}/OAIStepsApi.cpp \
    $${PWD}/OAIStringDefinitionsApi.cpp \
    $${PWD}/OAIStringTranslationsApi.cpp \
    $${PWD}/OAITranslationKeysApi.cpp \
    $${PWD}/OAITranslationRequestsApi.cpp \
    $${PWD}/OAITranslationSetsApi.cpp \
    $${PWD}/OAIUpdateGroupClientRelationshipsApi.cpp \
    $${PWD}/OAIUpdateGroupSubscriptionsApi.cpp \
    $${PWD}/OAIUpdateGroupsApi.cpp \
    $${PWD}/OAIUpdateSystemApi.cpp \
    $${PWD}/OAIUserContentDefinitionsApi.cpp \
    $${PWD}/OAIUserPermissionsApi.cpp \
    $${PWD}/OAIUsersApi.cpp \
    $${PWD}/OAIVoucherHistoryApi.cpp \
    $${PWD}/OAIVouchersApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
