QT += network

HEADERS += \
# Models
    $${PWD}/OAIAccessResponse.h \
    $${PWD}/OAIAccessToken.h \
    $${PWD}/OAIAuthTokenResponse.h \
    $${PWD}/OAIDemoAuthResponse.h \
    $${PWD}/OAIDemoAuthResponse_details.h \
    $${PWD}/OAIDemoAuthVerifyResponse.h \
    $${PWD}/OAIDemoAuthVerifyResponse_details.h \
    $${PWD}/OAIDeviceAccessToken.h \
    $${PWD}/OAIDeviceAuthorizationCode.h \
    $${PWD}/OAIDeviceAuthorizationCodeResponse.h \
    $${PWD}/OAIDocTypeResponse.h \
    $${PWD}/OAIDocTypeResponse_documents_inner.h \
    $${PWD}/OAIEaadharXamlSchema.h \
    $${PWD}/OAIEaadharXamlSchema_KycRes.h \
    $${PWD}/OAIEaadharXamlSchema_KycRes_Signature.h \
    $${PWD}/OAIEaadharXamlSchema_KycRes_Signature_KeyInfo.h \
    $${PWD}/OAIEaadharXamlSchema_KycRes_Signature_KeyInfo_X509Data.h \
    $${PWD}/OAIEaadharXamlSchema_KycRes_Signature_SignedInfo.h \
    $${PWD}/OAIEaadharXamlSchema_KycRes_Signature_SignedInfo_CanonicalizationMethod.h \
    $${PWD}/OAIEaadharXamlSchema_KycRes_Signature_SignedInfo_Reference.h \
    $${PWD}/OAIEaadharXamlSchema_KycRes_Signature_SignedInfo_Reference_Transforms.h \
    $${PWD}/OAIEaadharXamlSchema_KycRes_UidData.h \
    $${PWD}/OAIEaadharXamlSchema_KycRes_UidData_LData.h \
    $${PWD}/OAIEaadharXamlSchema_KycRes_UidData_Poa.h \
    $${PWD}/OAIEaadharXamlSchema_KycRes_UidData_Poi.h \
    $${PWD}/OAIEaadharXamlSchema_KycRes_UidData_Prn.h \
    $${PWD}/OAIFileUpload.h \
    $${PWD}/OAIFileUploadResponse.h \
    $${PWD}/OAIFileUploadResponse_details.h \
    $${PWD}/OAIGetStatisticsResponse.h \
    $${PWD}/OAIGetStatisticsResponse_monthwise_registations.h \
    $${PWD}/OAIGetStatisticsResponse_monthwise_registations_details2.h \
    $${PWD}/OAIGetStatisticsResponse_yearwise_authentic_documents.h \
    $${PWD}/OAIGetStatisticsResponse_yearwise_authentic_documents_details.h \
    $${PWD}/OAIGetStatisticsResponse_yearwise_authentic_documents_details1.h \
    $${PWD}/OAIGetStatisticsResponse_yearwise_authentic_documents_details2.h \
    $${PWD}/OAIGet_Device_Code_id_400_response.h \
    $${PWD}/OAIGet_Device_Code_id_401_response.h \
    $${PWD}/OAIGet_Device_Code_id_500_response.h \
    $${PWD}/OAIGet_File_from_URI_id_400_response.h \
    $${PWD}/OAIGet_File_from_URI_id_404_response.h \
    $${PWD}/OAIGet_File_from_URI_id_500_response.h \
    $${PWD}/OAIGet_File_from_URI_id_503_response.h \
    $${PWD}/OAIGet_List_of_Documents_Provided_by_an_Issuer_id_400_response.h \
    $${PWD}/OAIGet_List_of_Issuers_id_400_response.h \
    $${PWD}/OAIGet_List_of_Self_Uploaded_Documents_404_response.h \
    $${PWD}/OAIGet_List_of_Self_Uploaded_Documents_500_response.h \
    $${PWD}/OAIGet_List_of_issued_Documents_Version1_id_500_response.h \
    $${PWD}/OAIGet_List_of_issued_Documents_id_200_response.h \
    $${PWD}/OAIGet_List_of_issued_Documents_id_200_response_items_inner.h \
    $${PWD}/OAIGet_Search_Parameters_for_a_Document_id_400_response.h \
    $${PWD}/OAIGet_Statistics_id_400_response.h \
    $${PWD}/OAIGet_e_Aadhaar_Data_in_XML_Format_id_401_response.h \
    $${PWD}/OAIGet_e_Aadhaar_Data_in_XML_Format_id_404_response.h \
    $${PWD}/OAIGet_token_revocation_id_request.h \
    $${PWD}/OAIGetaccesstoken_id_request.h \
    $${PWD}/OAIIssuerResponse.h \
    $${PWD}/OAIIssuerResponse_issuers_inner.h \
    $${PWD}/OAIPull_Document_id_400_response.h \
    $${PWD}/OAIPull_Document_id_404_response.h \
    $${PWD}/OAIPull_Document_id_500_response.h \
    $${PWD}/OAIPush_URI_to_Account_id_400_response.h \
    $${PWD}/OAIPush_URI_to_Account_id_401_response.h \
    $${PWD}/OAIPush_URI_to_Account_id_404_response.h \
    $${PWD}/OAIPush_URI_to_Account_id_500_response.h \
    $${PWD}/OAIRefreshAccessToken.h \
    $${PWD}/OAIRefreshToken.h \
    $${PWD}/OAIResponse1.h \
    $${PWD}/OAIResponse10.h \
    $${PWD}/OAIResponse11.h \
    $${PWD}/OAIResponse12.h \
    $${PWD}/OAIResponse13.h \
    $${PWD}/OAIResponse14.h \
    $${PWD}/OAIResponse15.h \
    $${PWD}/OAIResponse16.h \
    $${PWD}/OAIResponse17.h \
    $${PWD}/OAIResponse18.h \
    $${PWD}/OAIResponse2.h \
    $${PWD}/OAIResponse3.h \
    $${PWD}/OAIResponse4.h \
    $${PWD}/OAIResponse5.h \
    $${PWD}/OAIResponse6.h \
    $${PWD}/OAIResponse7.h \
    $${PWD}/OAIResponse8.h \
    $${PWD}/OAIResponse9.h \
    $${PWD}/OAIResponseFive.h \
    $${PWD}/OAIResponseFour.h \
    $${PWD}/OAIResponseOne.h \
    $${PWD}/OAIResponseSeven.h \
    $${PWD}/OAIResponseSix.h \
    $${PWD}/OAIResponseThree.h \
    $${PWD}/OAIResponseTwo.h \
    $${PWD}/OAISIGN_UP_id_400_response.h \
    $${PWD}/OAISample.h \
    $${PWD}/OAISample_1.h \
    $${PWD}/OAISample_1_items_inner.h \
    $${PWD}/OAISample_2.h \
    $${PWD}/OAISample_2_details.h \
    $${PWD}/OAISample_3.h \
    $${PWD}/OAISample_3_details.h \
    $${PWD}/OAISample_4.h \
    $${PWD}/OAISample_4_details.h \
    $${PWD}/OAISample_5.h \
    $${PWD}/OAISample_5_details.h \
    $${PWD}/OAISample_details.h \
    $${PWD}/OAISearchParametersResponse_inner.h \
    $${PWD}/OAIUpload_File_to_Locker_id_400_response.h \
    $${PWD}/OAIUpload_File_to_Locker_id_401_response.h \
    $${PWD}/OAIVerifyAccountResponse.h \
    $${PWD}/OAIVerify_Account_id_400_response.h \
    $${PWD}/OAIVerify_Account_id_500_response.h \
    $${PWD}/OAIVerify_OTP_id_400_response.h \
    $${PWD}/OAIXMLFormatSchema.h \
    $${PWD}/OAIXMLFormatSchema_Signature.h \
    $${PWD}/OAIXMLFormatSchema_Signature_KeyInfo.h \
# APIs
    $${PWD}/OAIAccountDetailAPIApi.h \
    $${PWD}/OAIAuthorizationApi.h \
    $${PWD}/OAIAuthorizationAPIApi.h \
    $${PWD}/OAIDigiLockerMetaAPIsApi.h \
    $${PWD}/OAIDigiLockerSignUpAPIsApi.h \
    $${PWD}/OAIFileAPIsApi.h \
    $${PWD}/OAITokenRevocationAPIApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAccessResponse.cpp \
    $${PWD}/OAIAccessToken.cpp \
    $${PWD}/OAIAuthTokenResponse.cpp \
    $${PWD}/OAIDemoAuthResponse.cpp \
    $${PWD}/OAIDemoAuthResponse_details.cpp \
    $${PWD}/OAIDemoAuthVerifyResponse.cpp \
    $${PWD}/OAIDemoAuthVerifyResponse_details.cpp \
    $${PWD}/OAIDeviceAccessToken.cpp \
    $${PWD}/OAIDeviceAuthorizationCode.cpp \
    $${PWD}/OAIDeviceAuthorizationCodeResponse.cpp \
    $${PWD}/OAIDocTypeResponse.cpp \
    $${PWD}/OAIDocTypeResponse_documents_inner.cpp \
    $${PWD}/OAIEaadharXamlSchema.cpp \
    $${PWD}/OAIEaadharXamlSchema_KycRes.cpp \
    $${PWD}/OAIEaadharXamlSchema_KycRes_Signature.cpp \
    $${PWD}/OAIEaadharXamlSchema_KycRes_Signature_KeyInfo.cpp \
    $${PWD}/OAIEaadharXamlSchema_KycRes_Signature_KeyInfo_X509Data.cpp \
    $${PWD}/OAIEaadharXamlSchema_KycRes_Signature_SignedInfo.cpp \
    $${PWD}/OAIEaadharXamlSchema_KycRes_Signature_SignedInfo_CanonicalizationMethod.cpp \
    $${PWD}/OAIEaadharXamlSchema_KycRes_Signature_SignedInfo_Reference.cpp \
    $${PWD}/OAIEaadharXamlSchema_KycRes_Signature_SignedInfo_Reference_Transforms.cpp \
    $${PWD}/OAIEaadharXamlSchema_KycRes_UidData.cpp \
    $${PWD}/OAIEaadharXamlSchema_KycRes_UidData_LData.cpp \
    $${PWD}/OAIEaadharXamlSchema_KycRes_UidData_Poa.cpp \
    $${PWD}/OAIEaadharXamlSchema_KycRes_UidData_Poi.cpp \
    $${PWD}/OAIEaadharXamlSchema_KycRes_UidData_Prn.cpp \
    $${PWD}/OAIFileUpload.cpp \
    $${PWD}/OAIFileUploadResponse.cpp \
    $${PWD}/OAIFileUploadResponse_details.cpp \
    $${PWD}/OAIGetStatisticsResponse.cpp \
    $${PWD}/OAIGetStatisticsResponse_monthwise_registations.cpp \
    $${PWD}/OAIGetStatisticsResponse_monthwise_registations_details2.cpp \
    $${PWD}/OAIGetStatisticsResponse_yearwise_authentic_documents.cpp \
    $${PWD}/OAIGetStatisticsResponse_yearwise_authentic_documents_details.cpp \
    $${PWD}/OAIGetStatisticsResponse_yearwise_authentic_documents_details1.cpp \
    $${PWD}/OAIGetStatisticsResponse_yearwise_authentic_documents_details2.cpp \
    $${PWD}/OAIGet_Device_Code_id_400_response.cpp \
    $${PWD}/OAIGet_Device_Code_id_401_response.cpp \
    $${PWD}/OAIGet_Device_Code_id_500_response.cpp \
    $${PWD}/OAIGet_File_from_URI_id_400_response.cpp \
    $${PWD}/OAIGet_File_from_URI_id_404_response.cpp \
    $${PWD}/OAIGet_File_from_URI_id_500_response.cpp \
    $${PWD}/OAIGet_File_from_URI_id_503_response.cpp \
    $${PWD}/OAIGet_List_of_Documents_Provided_by_an_Issuer_id_400_response.cpp \
    $${PWD}/OAIGet_List_of_Issuers_id_400_response.cpp \
    $${PWD}/OAIGet_List_of_Self_Uploaded_Documents_404_response.cpp \
    $${PWD}/OAIGet_List_of_Self_Uploaded_Documents_500_response.cpp \
    $${PWD}/OAIGet_List_of_issued_Documents_Version1_id_500_response.cpp \
    $${PWD}/OAIGet_List_of_issued_Documents_id_200_response.cpp \
    $${PWD}/OAIGet_List_of_issued_Documents_id_200_response_items_inner.cpp \
    $${PWD}/OAIGet_Search_Parameters_for_a_Document_id_400_response.cpp \
    $${PWD}/OAIGet_Statistics_id_400_response.cpp \
    $${PWD}/OAIGet_e_Aadhaar_Data_in_XML_Format_id_401_response.cpp \
    $${PWD}/OAIGet_e_Aadhaar_Data_in_XML_Format_id_404_response.cpp \
    $${PWD}/OAIGet_token_revocation_id_request.cpp \
    $${PWD}/OAIGetaccesstoken_id_request.cpp \
    $${PWD}/OAIIssuerResponse.cpp \
    $${PWD}/OAIIssuerResponse_issuers_inner.cpp \
    $${PWD}/OAIPull_Document_id_400_response.cpp \
    $${PWD}/OAIPull_Document_id_404_response.cpp \
    $${PWD}/OAIPull_Document_id_500_response.cpp \
    $${PWD}/OAIPush_URI_to_Account_id_400_response.cpp \
    $${PWD}/OAIPush_URI_to_Account_id_401_response.cpp \
    $${PWD}/OAIPush_URI_to_Account_id_404_response.cpp \
    $${PWD}/OAIPush_URI_to_Account_id_500_response.cpp \
    $${PWD}/OAIRefreshAccessToken.cpp \
    $${PWD}/OAIRefreshToken.cpp \
    $${PWD}/OAIResponse1.cpp \
    $${PWD}/OAIResponse10.cpp \
    $${PWD}/OAIResponse11.cpp \
    $${PWD}/OAIResponse12.cpp \
    $${PWD}/OAIResponse13.cpp \
    $${PWD}/OAIResponse14.cpp \
    $${PWD}/OAIResponse15.cpp \
    $${PWD}/OAIResponse16.cpp \
    $${PWD}/OAIResponse17.cpp \
    $${PWD}/OAIResponse18.cpp \
    $${PWD}/OAIResponse2.cpp \
    $${PWD}/OAIResponse3.cpp \
    $${PWD}/OAIResponse4.cpp \
    $${PWD}/OAIResponse5.cpp \
    $${PWD}/OAIResponse6.cpp \
    $${PWD}/OAIResponse7.cpp \
    $${PWD}/OAIResponse8.cpp \
    $${PWD}/OAIResponse9.cpp \
    $${PWD}/OAIResponseFive.cpp \
    $${PWD}/OAIResponseFour.cpp \
    $${PWD}/OAIResponseOne.cpp \
    $${PWD}/OAIResponseSeven.cpp \
    $${PWD}/OAIResponseSix.cpp \
    $${PWD}/OAIResponseThree.cpp \
    $${PWD}/OAIResponseTwo.cpp \
    $${PWD}/OAISIGN_UP_id_400_response.cpp \
    $${PWD}/OAISample.cpp \
    $${PWD}/OAISample_1.cpp \
    $${PWD}/OAISample_1_items_inner.cpp \
    $${PWD}/OAISample_2.cpp \
    $${PWD}/OAISample_2_details.cpp \
    $${PWD}/OAISample_3.cpp \
    $${PWD}/OAISample_3_details.cpp \
    $${PWD}/OAISample_4.cpp \
    $${PWD}/OAISample_4_details.cpp \
    $${PWD}/OAISample_5.cpp \
    $${PWD}/OAISample_5_details.cpp \
    $${PWD}/OAISample_details.cpp \
    $${PWD}/OAISearchParametersResponse_inner.cpp \
    $${PWD}/OAIUpload_File_to_Locker_id_400_response.cpp \
    $${PWD}/OAIUpload_File_to_Locker_id_401_response.cpp \
    $${PWD}/OAIVerifyAccountResponse.cpp \
    $${PWD}/OAIVerify_Account_id_400_response.cpp \
    $${PWD}/OAIVerify_Account_id_500_response.cpp \
    $${PWD}/OAIVerify_OTP_id_400_response.cpp \
    $${PWD}/OAIXMLFormatSchema.cpp \
    $${PWD}/OAIXMLFormatSchema_Signature.cpp \
    $${PWD}/OAIXMLFormatSchema_Signature_KeyInfo.cpp \
# APIs
    $${PWD}/OAIAccountDetailAPIApi.cpp \
    $${PWD}/OAIAuthorizationApi.cpp \
    $${PWD}/OAIAuthorizationAPIApi.cpp \
    $${PWD}/OAIDigiLockerMetaAPIsApi.cpp \
    $${PWD}/OAIDigiLockerSignUpAPIsApi.cpp \
    $${PWD}/OAIFileAPIsApi.cpp \
    $${PWD}/OAITokenRevocationAPIApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
