QT += network

HEADERS += \
# Models
    $${PWD}/OAIAggregateColumn.h \
    $${PWD}/OAIAggregateFunctionName.h \
    $${PWD}/OAIAggregationConstraint.h \
    $${PWD}/OAIAggregationType.h \
    $${PWD}/OAIAnalysisFormat.h \
    $${PWD}/OAIAnalysisMethod.h \
    $${PWD}/OAIAnalysisParameter.h \
    $${PWD}/OAIAnalysisRule.h \
    $${PWD}/OAIAnalysisRuleAggregation.h \
    $${PWD}/OAIAnalysisRuleCustom.h \
    $${PWD}/OAIAnalysisRuleList.h \
    $${PWD}/OAIAnalysisRulePolicy.h \
    $${PWD}/OAIAnalysisRulePolicyV1.h \
    $${PWD}/OAIAnalysisRulePolicyV1_custom.h \
    $${PWD}/OAIAnalysisRulePolicy_v1.h \
    $${PWD}/OAIAnalysisRuleType.h \
    $${PWD}/OAIAnalysisRule_policy.h \
    $${PWD}/OAIAnalysisSchema.h \
    $${PWD}/OAIAnalysisSource.h \
    $${PWD}/OAIAnalysisTemplate.h \
    $${PWD}/OAIAnalysisTemplateSummary.h \
    $${PWD}/OAIAnalysisTemplate_schema.h \
    $${PWD}/OAIAnalysisTemplate_source.h \
    $${PWD}/OAIBatchGetCollaborationAnalysisTemplateError.h \
    $${PWD}/OAIBatchGetCollaborationAnalysisTemplateInput.h \
    $${PWD}/OAIBatchGetCollaborationAnalysisTemplateOutput.h \
    $${PWD}/OAIBatchGetCollaborationAnalysisTemplate_request.h \
    $${PWD}/OAIBatchGetSchemaError.h \
    $${PWD}/OAIBatchGetSchemaInput.h \
    $${PWD}/OAIBatchGetSchemaOutput.h \
    $${PWD}/OAIBatchGetSchema_request.h \
    $${PWD}/OAICollaboration.h \
    $${PWD}/OAICollaborationAnalysisTemplate.h \
    $${PWD}/OAICollaborationAnalysisTemplateSummary.h \
    $${PWD}/OAICollaborationAnalysisTemplate_source.h \
    $${PWD}/OAICollaborationQueryLogStatus.h \
    $${PWD}/OAICollaborationSummary.h \
    $${PWD}/OAICollaboration_dataEncryptionMetadata.h \
    $${PWD}/OAIColumn.h \
    $${PWD}/OAIConfiguredTable.h \
    $${PWD}/OAIConfiguredTableAnalysisRule.h \
    $${PWD}/OAIConfiguredTableAnalysisRulePolicy.h \
    $${PWD}/OAIConfiguredTableAnalysisRulePolicyV1.h \
    $${PWD}/OAIConfiguredTableAnalysisRulePolicyV1_aggregation.h \
    $${PWD}/OAIConfiguredTableAnalysisRulePolicyV1_list.h \
    $${PWD}/OAIConfiguredTableAnalysisRuleType.h \
    $${PWD}/OAIConfiguredTableAnalysisRule_policy.h \
    $${PWD}/OAIConfiguredTableAssociation.h \
    $${PWD}/OAIConfiguredTableAssociationSummary.h \
    $${PWD}/OAIConfiguredTableSummary.h \
    $${PWD}/OAIConfiguredTableSummaryList_inner.h \
    $${PWD}/OAIConfiguredTable_tableReference.h \
    $${PWD}/OAICreateAnalysisTemplateInput.h \
    $${PWD}/OAICreateAnalysisTemplateInput_source.h \
    $${PWD}/OAICreateAnalysisTemplateOutput.h \
    $${PWD}/OAICreateAnalysisTemplateOutput_analysisTemplate.h \
    $${PWD}/OAICreateAnalysisTemplate_request.h \
    $${PWD}/OAICreateAnalysisTemplate_request_source.h \
    $${PWD}/OAICreateCollaborationInput.h \
    $${PWD}/OAICreateCollaborationInput_dataEncryptionMetadata.h \
    $${PWD}/OAICreateCollaborationOutput.h \
    $${PWD}/OAICreateCollaborationOutput_collaboration.h \
    $${PWD}/OAICreateCollaboration_request.h \
    $${PWD}/OAICreateCollaboration_request_dataEncryptionMetadata.h \
    $${PWD}/OAICreateConfiguredTableAnalysisRuleInput.h \
    $${PWD}/OAICreateConfiguredTableAnalysisRuleInput_analysisRulePolicy.h \
    $${PWD}/OAICreateConfiguredTableAnalysisRuleOutput.h \
    $${PWD}/OAICreateConfiguredTableAnalysisRuleOutput_analysisRule.h \
    $${PWD}/OAICreateConfiguredTableAnalysisRule_request.h \
    $${PWD}/OAICreateConfiguredTableAnalysisRule_request_analysisRulePolicy.h \
    $${PWD}/OAICreateConfiguredTableAnalysisRule_request_analysisRulePolicy_v1.h \
    $${PWD}/OAICreateConfiguredTableAssociationInput.h \
    $${PWD}/OAICreateConfiguredTableAssociationOutput.h \
    $${PWD}/OAICreateConfiguredTableAssociationOutput_configuredTableAssociation.h \
    $${PWD}/OAICreateConfiguredTableAssociation_request.h \
    $${PWD}/OAICreateConfiguredTableInput.h \
    $${PWD}/OAICreateConfiguredTableInput_tableReference.h \
    $${PWD}/OAICreateConfiguredTableOutput.h \
    $${PWD}/OAICreateConfiguredTableOutput_configuredTable.h \
    $${PWD}/OAICreateConfiguredTable_request.h \
    $${PWD}/OAICreateConfiguredTable_request_tableReference.h \
    $${PWD}/OAICreateConfiguredTable_request_tableReference_glue.h \
    $${PWD}/OAICreateMembershipInput.h \
    $${PWD}/OAICreateMembershipOutput.h \
    $${PWD}/OAICreateMembershipOutput_membership.h \
    $${PWD}/OAICreateMembership_request.h \
    $${PWD}/OAIDataEncryptionMetadata.h \
    $${PWD}/OAIFilterableMemberStatus.h \
    $${PWD}/OAIGetAnalysisTemplateOutput.h \
    $${PWD}/OAIGetCollaborationAnalysisTemplateOutput.h \
    $${PWD}/OAIGetCollaborationAnalysisTemplateOutput_collaborationAnalysisTemplate.h \
    $${PWD}/OAIGetCollaborationOutput.h \
    $${PWD}/OAIGetCollaborationOutput_collaboration.h \
    $${PWD}/OAIGetConfiguredTableAnalysisRuleOutput.h \
    $${PWD}/OAIGetConfiguredTableAnalysisRuleOutput_analysisRule.h \
    $${PWD}/OAIGetConfiguredTableAssociationOutput.h \
    $${PWD}/OAIGetConfiguredTableOutput.h \
    $${PWD}/OAIGetConfiguredTableOutput_configuredTable.h \
    $${PWD}/OAIGetMembershipOutput.h \
    $${PWD}/OAIGetMembershipOutput_membership.h \
    $${PWD}/OAIGetProtectedQueryOutput.h \
    $${PWD}/OAIGetProtectedQueryOutput_protectedQuery.h \
    $${PWD}/OAIGetSchemaAnalysisRuleOutput.h \
    $${PWD}/OAIGetSchemaAnalysisRuleOutput_analysisRule.h \
    $${PWD}/OAIGetSchemaOutput.h \
    $${PWD}/OAIGetSchemaOutput_schema.h \
    $${PWD}/OAIGlueTableReference.h \
    $${PWD}/OAIJoinOperator.h \
    $${PWD}/OAIJoinRequiredOption.h \
    $${PWD}/OAIListAnalysisTemplatesOutput.h \
    $${PWD}/OAIListCollaborationAnalysisTemplatesOutput.h \
    $${PWD}/OAIListCollaborationsOutput.h \
    $${PWD}/OAIListConfiguredTableAssociationsOutput.h \
    $${PWD}/OAIListConfiguredTablesOutput.h \
    $${PWD}/OAIListMembersOutput.h \
    $${PWD}/OAIListMembershipsOutput.h \
    $${PWD}/OAIListProtectedQueriesOutput.h \
    $${PWD}/OAIListSchemasOutput.h \
    $${PWD}/OAIListTagsForResourceOutput.h \
    $${PWD}/OAIMemberAbility.h \
    $${PWD}/OAIMemberSpecification.h \
    $${PWD}/OAIMemberStatus.h \
    $${PWD}/OAIMemberSummary.h \
    $${PWD}/OAIMembership.h \
    $${PWD}/OAIMembershipQueryLogStatus.h \
    $${PWD}/OAIMembershipStatus.h \
    $${PWD}/OAIMembershipSummary.h \
    $${PWD}/OAIParameterType.h \
    $${PWD}/OAIProtectedQuery.h \
    $${PWD}/OAIProtectedQueryError.h \
    $${PWD}/OAIProtectedQueryOutput.h \
    $${PWD}/OAIProtectedQueryOutputConfiguration.h \
    $${PWD}/OAIProtectedQueryOutputConfiguration_s3.h \
    $${PWD}/OAIProtectedQueryOutput_s3.h \
    $${PWD}/OAIProtectedQueryResult.h \
    $${PWD}/OAIProtectedQueryResultConfiguration.h \
    $${PWD}/OAIProtectedQueryResult_output.h \
    $${PWD}/OAIProtectedQueryS3Output.h \
    $${PWD}/OAIProtectedQueryS3OutputConfiguration.h \
    $${PWD}/OAIProtectedQuerySQLParameters.h \
    $${PWD}/OAIProtectedQueryStatistics.h \
    $${PWD}/OAIProtectedQueryStatus.h \
    $${PWD}/OAIProtectedQuerySummary.h \
    $${PWD}/OAIProtectedQueryType.h \
    $${PWD}/OAIProtectedQuery_error.h \
    $${PWD}/OAIProtectedQuery_result.h \
    $${PWD}/OAIProtectedQuery_resultConfiguration.h \
    $${PWD}/OAIProtectedQuery_sqlParameters.h \
    $${PWD}/OAIProtectedQuery_statistics.h \
    $${PWD}/OAIResultFormat.h \
    $${PWD}/OAIScalarFunctions.h \
    $${PWD}/OAISchema.h \
    $${PWD}/OAISchemaSummary.h \
    $${PWD}/OAISchemaType.h \
    $${PWD}/OAIStartProtectedQueryInput.h \
    $${PWD}/OAIStartProtectedQueryInput_resultConfiguration.h \
    $${PWD}/OAIStartProtectedQueryInput_sqlParameters.h \
    $${PWD}/OAIStartProtectedQueryOutput.h \
    $${PWD}/OAIStartProtectedQueryOutput_protectedQuery.h \
    $${PWD}/OAIStartProtectedQuery_request.h \
    $${PWD}/OAIStartProtectedQuery_request_resultConfiguration.h \
    $${PWD}/OAIStartProtectedQuery_request_resultConfiguration_outputConfiguration.h \
    $${PWD}/OAIStartProtectedQuery_request_sqlParameters.h \
    $${PWD}/OAITableReference.h \
    $${PWD}/OAITagResourceInput.h \
    $${PWD}/OAITagResource_request.h \
    $${PWD}/OAITargetProtectedQueryStatus.h \
    $${PWD}/OAIUpdateAnalysisTemplateInput.h \
    $${PWD}/OAIUpdateAnalysisTemplateOutput.h \
    $${PWD}/OAIUpdateAnalysisTemplate_request.h \
    $${PWD}/OAIUpdateCollaborationInput.h \
    $${PWD}/OAIUpdateCollaborationOutput.h \
    $${PWD}/OAIUpdateCollaborationOutput_collaboration.h \
    $${PWD}/OAIUpdateCollaboration_request.h \
    $${PWD}/OAIUpdateConfiguredTableAnalysisRuleInput.h \
    $${PWD}/OAIUpdateConfiguredTableAnalysisRuleInput_analysisRulePolicy.h \
    $${PWD}/OAIUpdateConfiguredTableAnalysisRuleOutput.h \
    $${PWD}/OAIUpdateConfiguredTableAnalysisRuleOutput_analysisRule.h \
    $${PWD}/OAIUpdateConfiguredTableAnalysisRule_request.h \
    $${PWD}/OAIUpdateConfiguredTableAssociationInput.h \
    $${PWD}/OAIUpdateConfiguredTableAssociationOutput.h \
    $${PWD}/OAIUpdateConfiguredTableAssociationOutput_configuredTableAssociation.h \
    $${PWD}/OAIUpdateConfiguredTableAssociation_request.h \
    $${PWD}/OAIUpdateConfiguredTableInput.h \
    $${PWD}/OAIUpdateConfiguredTableOutput.h \
    $${PWD}/OAIUpdateConfiguredTableOutput_configuredTable.h \
    $${PWD}/OAIUpdateConfiguredTable_request.h \
    $${PWD}/OAIUpdateMembershipInput.h \
    $${PWD}/OAIUpdateMembershipOutput.h \
    $${PWD}/OAIUpdateMembership_request.h \
    $${PWD}/OAIUpdateProtectedQueryInput.h \
    $${PWD}/OAIUpdateProtectedQueryOutput.h \
    $${PWD}/OAIUpdateProtectedQueryOutput_protectedQuery.h \
    $${PWD}/OAIUpdateProtectedQuery_request.h \
# APIs
    $${PWD}/OAIDefaultApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAggregateColumn.cpp \
    $${PWD}/OAIAggregateFunctionName.cpp \
    $${PWD}/OAIAggregationConstraint.cpp \
    $${PWD}/OAIAggregationType.cpp \
    $${PWD}/OAIAnalysisFormat.cpp \
    $${PWD}/OAIAnalysisMethod.cpp \
    $${PWD}/OAIAnalysisParameter.cpp \
    $${PWD}/OAIAnalysisRule.cpp \
    $${PWD}/OAIAnalysisRuleAggregation.cpp \
    $${PWD}/OAIAnalysisRuleCustom.cpp \
    $${PWD}/OAIAnalysisRuleList.cpp \
    $${PWD}/OAIAnalysisRulePolicy.cpp \
    $${PWD}/OAIAnalysisRulePolicyV1.cpp \
    $${PWD}/OAIAnalysisRulePolicyV1_custom.cpp \
    $${PWD}/OAIAnalysisRulePolicy_v1.cpp \
    $${PWD}/OAIAnalysisRuleType.cpp \
    $${PWD}/OAIAnalysisRule_policy.cpp \
    $${PWD}/OAIAnalysisSchema.cpp \
    $${PWD}/OAIAnalysisSource.cpp \
    $${PWD}/OAIAnalysisTemplate.cpp \
    $${PWD}/OAIAnalysisTemplateSummary.cpp \
    $${PWD}/OAIAnalysisTemplate_schema.cpp \
    $${PWD}/OAIAnalysisTemplate_source.cpp \
    $${PWD}/OAIBatchGetCollaborationAnalysisTemplateError.cpp \
    $${PWD}/OAIBatchGetCollaborationAnalysisTemplateInput.cpp \
    $${PWD}/OAIBatchGetCollaborationAnalysisTemplateOutput.cpp \
    $${PWD}/OAIBatchGetCollaborationAnalysisTemplate_request.cpp \
    $${PWD}/OAIBatchGetSchemaError.cpp \
    $${PWD}/OAIBatchGetSchemaInput.cpp \
    $${PWD}/OAIBatchGetSchemaOutput.cpp \
    $${PWD}/OAIBatchGetSchema_request.cpp \
    $${PWD}/OAICollaboration.cpp \
    $${PWD}/OAICollaborationAnalysisTemplate.cpp \
    $${PWD}/OAICollaborationAnalysisTemplateSummary.cpp \
    $${PWD}/OAICollaborationAnalysisTemplate_source.cpp \
    $${PWD}/OAICollaborationQueryLogStatus.cpp \
    $${PWD}/OAICollaborationSummary.cpp \
    $${PWD}/OAICollaboration_dataEncryptionMetadata.cpp \
    $${PWD}/OAIColumn.cpp \
    $${PWD}/OAIConfiguredTable.cpp \
    $${PWD}/OAIConfiguredTableAnalysisRule.cpp \
    $${PWD}/OAIConfiguredTableAnalysisRulePolicy.cpp \
    $${PWD}/OAIConfiguredTableAnalysisRulePolicyV1.cpp \
    $${PWD}/OAIConfiguredTableAnalysisRulePolicyV1_aggregation.cpp \
    $${PWD}/OAIConfiguredTableAnalysisRulePolicyV1_list.cpp \
    $${PWD}/OAIConfiguredTableAnalysisRuleType.cpp \
    $${PWD}/OAIConfiguredTableAnalysisRule_policy.cpp \
    $${PWD}/OAIConfiguredTableAssociation.cpp \
    $${PWD}/OAIConfiguredTableAssociationSummary.cpp \
    $${PWD}/OAIConfiguredTableSummary.cpp \
    $${PWD}/OAIConfiguredTableSummaryList_inner.cpp \
    $${PWD}/OAIConfiguredTable_tableReference.cpp \
    $${PWD}/OAICreateAnalysisTemplateInput.cpp \
    $${PWD}/OAICreateAnalysisTemplateInput_source.cpp \
    $${PWD}/OAICreateAnalysisTemplateOutput.cpp \
    $${PWD}/OAICreateAnalysisTemplateOutput_analysisTemplate.cpp \
    $${PWD}/OAICreateAnalysisTemplate_request.cpp \
    $${PWD}/OAICreateAnalysisTemplate_request_source.cpp \
    $${PWD}/OAICreateCollaborationInput.cpp \
    $${PWD}/OAICreateCollaborationInput_dataEncryptionMetadata.cpp \
    $${PWD}/OAICreateCollaborationOutput.cpp \
    $${PWD}/OAICreateCollaborationOutput_collaboration.cpp \
    $${PWD}/OAICreateCollaboration_request.cpp \
    $${PWD}/OAICreateCollaboration_request_dataEncryptionMetadata.cpp \
    $${PWD}/OAICreateConfiguredTableAnalysisRuleInput.cpp \
    $${PWD}/OAICreateConfiguredTableAnalysisRuleInput_analysisRulePolicy.cpp \
    $${PWD}/OAICreateConfiguredTableAnalysisRuleOutput.cpp \
    $${PWD}/OAICreateConfiguredTableAnalysisRuleOutput_analysisRule.cpp \
    $${PWD}/OAICreateConfiguredTableAnalysisRule_request.cpp \
    $${PWD}/OAICreateConfiguredTableAnalysisRule_request_analysisRulePolicy.cpp \
    $${PWD}/OAICreateConfiguredTableAnalysisRule_request_analysisRulePolicy_v1.cpp \
    $${PWD}/OAICreateConfiguredTableAssociationInput.cpp \
    $${PWD}/OAICreateConfiguredTableAssociationOutput.cpp \
    $${PWD}/OAICreateConfiguredTableAssociationOutput_configuredTableAssociation.cpp \
    $${PWD}/OAICreateConfiguredTableAssociation_request.cpp \
    $${PWD}/OAICreateConfiguredTableInput.cpp \
    $${PWD}/OAICreateConfiguredTableInput_tableReference.cpp \
    $${PWD}/OAICreateConfiguredTableOutput.cpp \
    $${PWD}/OAICreateConfiguredTableOutput_configuredTable.cpp \
    $${PWD}/OAICreateConfiguredTable_request.cpp \
    $${PWD}/OAICreateConfiguredTable_request_tableReference.cpp \
    $${PWD}/OAICreateConfiguredTable_request_tableReference_glue.cpp \
    $${PWD}/OAICreateMembershipInput.cpp \
    $${PWD}/OAICreateMembershipOutput.cpp \
    $${PWD}/OAICreateMembershipOutput_membership.cpp \
    $${PWD}/OAICreateMembership_request.cpp \
    $${PWD}/OAIDataEncryptionMetadata.cpp \
    $${PWD}/OAIFilterableMemberStatus.cpp \
    $${PWD}/OAIGetAnalysisTemplateOutput.cpp \
    $${PWD}/OAIGetCollaborationAnalysisTemplateOutput.cpp \
    $${PWD}/OAIGetCollaborationAnalysisTemplateOutput_collaborationAnalysisTemplate.cpp \
    $${PWD}/OAIGetCollaborationOutput.cpp \
    $${PWD}/OAIGetCollaborationOutput_collaboration.cpp \
    $${PWD}/OAIGetConfiguredTableAnalysisRuleOutput.cpp \
    $${PWD}/OAIGetConfiguredTableAnalysisRuleOutput_analysisRule.cpp \
    $${PWD}/OAIGetConfiguredTableAssociationOutput.cpp \
    $${PWD}/OAIGetConfiguredTableOutput.cpp \
    $${PWD}/OAIGetConfiguredTableOutput_configuredTable.cpp \
    $${PWD}/OAIGetMembershipOutput.cpp \
    $${PWD}/OAIGetMembershipOutput_membership.cpp \
    $${PWD}/OAIGetProtectedQueryOutput.cpp \
    $${PWD}/OAIGetProtectedQueryOutput_protectedQuery.cpp \
    $${PWD}/OAIGetSchemaAnalysisRuleOutput.cpp \
    $${PWD}/OAIGetSchemaAnalysisRuleOutput_analysisRule.cpp \
    $${PWD}/OAIGetSchemaOutput.cpp \
    $${PWD}/OAIGetSchemaOutput_schema.cpp \
    $${PWD}/OAIGlueTableReference.cpp \
    $${PWD}/OAIJoinOperator.cpp \
    $${PWD}/OAIJoinRequiredOption.cpp \
    $${PWD}/OAIListAnalysisTemplatesOutput.cpp \
    $${PWD}/OAIListCollaborationAnalysisTemplatesOutput.cpp \
    $${PWD}/OAIListCollaborationsOutput.cpp \
    $${PWD}/OAIListConfiguredTableAssociationsOutput.cpp \
    $${PWD}/OAIListConfiguredTablesOutput.cpp \
    $${PWD}/OAIListMembersOutput.cpp \
    $${PWD}/OAIListMembershipsOutput.cpp \
    $${PWD}/OAIListProtectedQueriesOutput.cpp \
    $${PWD}/OAIListSchemasOutput.cpp \
    $${PWD}/OAIListTagsForResourceOutput.cpp \
    $${PWD}/OAIMemberAbility.cpp \
    $${PWD}/OAIMemberSpecification.cpp \
    $${PWD}/OAIMemberStatus.cpp \
    $${PWD}/OAIMemberSummary.cpp \
    $${PWD}/OAIMembership.cpp \
    $${PWD}/OAIMembershipQueryLogStatus.cpp \
    $${PWD}/OAIMembershipStatus.cpp \
    $${PWD}/OAIMembershipSummary.cpp \
    $${PWD}/OAIParameterType.cpp \
    $${PWD}/OAIProtectedQuery.cpp \
    $${PWD}/OAIProtectedQueryError.cpp \
    $${PWD}/OAIProtectedQueryOutput.cpp \
    $${PWD}/OAIProtectedQueryOutputConfiguration.cpp \
    $${PWD}/OAIProtectedQueryOutputConfiguration_s3.cpp \
    $${PWD}/OAIProtectedQueryOutput_s3.cpp \
    $${PWD}/OAIProtectedQueryResult.cpp \
    $${PWD}/OAIProtectedQueryResultConfiguration.cpp \
    $${PWD}/OAIProtectedQueryResult_output.cpp \
    $${PWD}/OAIProtectedQueryS3Output.cpp \
    $${PWD}/OAIProtectedQueryS3OutputConfiguration.cpp \
    $${PWD}/OAIProtectedQuerySQLParameters.cpp \
    $${PWD}/OAIProtectedQueryStatistics.cpp \
    $${PWD}/OAIProtectedQueryStatus.cpp \
    $${PWD}/OAIProtectedQuerySummary.cpp \
    $${PWD}/OAIProtectedQueryType.cpp \
    $${PWD}/OAIProtectedQuery_error.cpp \
    $${PWD}/OAIProtectedQuery_result.cpp \
    $${PWD}/OAIProtectedQuery_resultConfiguration.cpp \
    $${PWD}/OAIProtectedQuery_sqlParameters.cpp \
    $${PWD}/OAIProtectedQuery_statistics.cpp \
    $${PWD}/OAIResultFormat.cpp \
    $${PWD}/OAIScalarFunctions.cpp \
    $${PWD}/OAISchema.cpp \
    $${PWD}/OAISchemaSummary.cpp \
    $${PWD}/OAISchemaType.cpp \
    $${PWD}/OAIStartProtectedQueryInput.cpp \
    $${PWD}/OAIStartProtectedQueryInput_resultConfiguration.cpp \
    $${PWD}/OAIStartProtectedQueryInput_sqlParameters.cpp \
    $${PWD}/OAIStartProtectedQueryOutput.cpp \
    $${PWD}/OAIStartProtectedQueryOutput_protectedQuery.cpp \
    $${PWD}/OAIStartProtectedQuery_request.cpp \
    $${PWD}/OAIStartProtectedQuery_request_resultConfiguration.cpp \
    $${PWD}/OAIStartProtectedQuery_request_resultConfiguration_outputConfiguration.cpp \
    $${PWD}/OAIStartProtectedQuery_request_sqlParameters.cpp \
    $${PWD}/OAITableReference.cpp \
    $${PWD}/OAITagResourceInput.cpp \
    $${PWD}/OAITagResource_request.cpp \
    $${PWD}/OAITargetProtectedQueryStatus.cpp \
    $${PWD}/OAIUpdateAnalysisTemplateInput.cpp \
    $${PWD}/OAIUpdateAnalysisTemplateOutput.cpp \
    $${PWD}/OAIUpdateAnalysisTemplate_request.cpp \
    $${PWD}/OAIUpdateCollaborationInput.cpp \
    $${PWD}/OAIUpdateCollaborationOutput.cpp \
    $${PWD}/OAIUpdateCollaborationOutput_collaboration.cpp \
    $${PWD}/OAIUpdateCollaboration_request.cpp \
    $${PWD}/OAIUpdateConfiguredTableAnalysisRuleInput.cpp \
    $${PWD}/OAIUpdateConfiguredTableAnalysisRuleInput_analysisRulePolicy.cpp \
    $${PWD}/OAIUpdateConfiguredTableAnalysisRuleOutput.cpp \
    $${PWD}/OAIUpdateConfiguredTableAnalysisRuleOutput_analysisRule.cpp \
    $${PWD}/OAIUpdateConfiguredTableAnalysisRule_request.cpp \
    $${PWD}/OAIUpdateConfiguredTableAssociationInput.cpp \
    $${PWD}/OAIUpdateConfiguredTableAssociationOutput.cpp \
    $${PWD}/OAIUpdateConfiguredTableAssociationOutput_configuredTableAssociation.cpp \
    $${PWD}/OAIUpdateConfiguredTableAssociation_request.cpp \
    $${PWD}/OAIUpdateConfiguredTableInput.cpp \
    $${PWD}/OAIUpdateConfiguredTableOutput.cpp \
    $${PWD}/OAIUpdateConfiguredTableOutput_configuredTable.cpp \
    $${PWD}/OAIUpdateConfiguredTable_request.cpp \
    $${PWD}/OAIUpdateMembershipInput.cpp \
    $${PWD}/OAIUpdateMembershipOutput.cpp \
    $${PWD}/OAIUpdateMembership_request.cpp \
    $${PWD}/OAIUpdateProtectedQueryInput.cpp \
    $${PWD}/OAIUpdateProtectedQueryOutput.cpp \
    $${PWD}/OAIUpdateProtectedQueryOutput_protectedQuery.cpp \
    $${PWD}/OAIUpdateProtectedQuery_request.cpp \
# APIs
    $${PWD}/OAIDefaultApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
