openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: 'The AdMob API allows publishers to programmatically get information
    about their AdMob account. '
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: AdMob API
  version: v1
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
  x-origin:
  - format: openapi
    url: https://admob.googleapis.com/$discovery/rest?version=v1
    version: "3.0"
  x-preferred: false
  x-providerName: googleapis.com
  x-serviceName: admob
servers:
- url: https://admob.googleapis.com/
tags:
- name: accounts
paths:
  /v1/accounts:
    get:
      description: "Lists the AdMob publisher account that was most recently signed\
        \ in to from the AdMob UI. For more information, see https://support.google.com/admob/answer/10243672."
      operationId: admob.accounts.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/admob.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/admob.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/admob.report
        Oauth2c:
        - https://www.googleapis.com/auth/admob.report
      tags:
      - accounts
      x-accepts:
      - application/json
  /v1/{name}:
    get:
      description: Gets information about the specified AdMob publisher account.
      operationId: admob.accounts.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/admob.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/admob.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/admob.report
        Oauth2c:
        - https://www.googleapis.com/auth/admob.report
      tags:
      - accounts
      x-accepts:
      - application/json
  /v1/{parent}/adUnits:
    get:
      description: List the ad units under the specified AdMob account.
      operationId: admob.accounts.adUnits.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/admob.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/admob.readonly
      tags:
      - accounts
      x-accepts:
      - application/json
  /v1/{parent}/apps:
    get:
      description: List the apps under the specified AdMob account.
      operationId: admob.accounts.apps.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/admob.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/admob.readonly
      tags:
      - accounts
      x-accepts:
      - application/json
  /v1/{parent}/mediationReport:generate:
    post:
      description: Generates an AdMob mediation report based on the provided report
        specification. Returns result of a server-side streaming RPC. The result is
        returned in a sequence of responses.
      operationId: admob.accounts.mediationReport.generate
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/admob.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/admob.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/admob.report
        Oauth2c:
        - https://www.googleapis.com/auth/admob.report
      tags:
      - accounts
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/{parent}/networkReport:generate:
    post:
      description: Generates an AdMob Network report based on the provided report
        specification. Returns result of a server-side streaming RPC. The result is
        returned in a sequence of responses.
      operationId: admob.accounts.networkReport.generate
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/admob.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/admob.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/admob.report
        Oauth2c:
        - https://www.googleapis.com/auth/admob.report
      tags:
      - accounts
      x-content-type: application/json
      x-accepts:
      - application/json
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/admob.readonly: See your AdMob data
            https://www.googleapis.com/auth/admob.report: See your AdMob data
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/admob.readonly: See your AdMob data
            https://www.googleapis.com/auth/admob.report: See your AdMob data
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2

