/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import PayeeLocationResponse from '../model/PayeeLocationResponse';
import PayeeLocationsResponse from '../model/PayeeLocationsResponse';

/**
* PayeeLocations service.
* @module api/PayeeLocationsApi
* @version 1.0.0
*/
export default class PayeeLocationsApi {

    /**
    * Constructs a new PayeeLocationsApi. 
    * @alias module:api/PayeeLocationsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getPayeeLocationById operation.
     * @callback module:api/PayeeLocationsApi~getPayeeLocationByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PayeeLocationResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Single payee location
     * Returns a single payee location
     * @param {String} budgetId The id of the budget. \"last-used\" can be used to specify the last used budget and \"default\" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
     * @param {String} payeeLocationId id of payee location
     * @param {module:api/PayeeLocationsApi~getPayeeLocationByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PayeeLocationResponse}
     */
    getPayeeLocationById(budgetId, payeeLocationId, callback) {
      let postBody = null;
      // verify the required parameter 'budgetId' is set
      if (budgetId === undefined || budgetId === null) {
        throw new Error("Missing the required parameter 'budgetId' when calling getPayeeLocationById");
      }
      // verify the required parameter 'payeeLocationId' is set
      if (payeeLocationId === undefined || payeeLocationId === null) {
        throw new Error("Missing the required parameter 'payeeLocationId' when calling getPayeeLocationById");
      }

      let pathParams = {
        'budget_id': budgetId,
        'payee_location_id': payeeLocationId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PayeeLocationResponse;
      return this.apiClient.callApi(
        '/budgets/{budget_id}/payee_locations/{payee_location_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPayeeLocations operation.
     * @callback module:api/PayeeLocationsApi~getPayeeLocationsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PayeeLocationsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List payee locations
     * Returns all payee locations
     * @param {String} budgetId The id of the budget. \"last-used\" can be used to specify the last used budget and \"default\" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
     * @param {module:api/PayeeLocationsApi~getPayeeLocationsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PayeeLocationsResponse}
     */
    getPayeeLocations(budgetId, callback) {
      let postBody = null;
      // verify the required parameter 'budgetId' is set
      if (budgetId === undefined || budgetId === null) {
        throw new Error("Missing the required parameter 'budgetId' when calling getPayeeLocations");
      }

      let pathParams = {
        'budget_id': budgetId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PayeeLocationsResponse;
      return this.apiClient.callApi(
        '/budgets/{budget_id}/payee_locations', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPayeeLocationsByPayee operation.
     * @callback module:api/PayeeLocationsApi~getPayeeLocationsByPayeeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PayeeLocationsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List locations for a payee
     * Returns all payee locations for a specified payee
     * @param {String} budgetId The id of the budget. \"last-used\" can be used to specify the last used budget and \"default\" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
     * @param {String} payeeId id of payee
     * @param {module:api/PayeeLocationsApi~getPayeeLocationsByPayeeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PayeeLocationsResponse}
     */
    getPayeeLocationsByPayee(budgetId, payeeId, callback) {
      let postBody = null;
      // verify the required parameter 'budgetId' is set
      if (budgetId === undefined || budgetId === null) {
        throw new Error("Missing the required parameter 'budgetId' when calling getPayeeLocationsByPayee");
      }
      // verify the required parameter 'payeeId' is set
      if (payeeId === undefined || payeeId === null) {
        throw new Error("Missing the required parameter 'payeeId' when calling getPayeeLocationsByPayee");
      }

      let pathParams = {
        'budget_id': budgetId,
        'payee_id': payeeId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PayeeLocationsResponse;
      return this.apiClient.callApi(
        '/budgets/{budget_id}/payees/{payee_id}/payee_locations', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
