QT += network

HEADERS += \
# Models
    $${PWD}/OAIAccessPolicySummary.h \
    $${PWD}/OAIAccessPolicySummary_identity.h \
    $${PWD}/OAIAccessPolicySummary_resource.h \
    $${PWD}/OAIAggregateType.h \
    $${PWD}/OAIAggregatedValue.h \
    $${PWD}/OAIAggregatedValue_value.h \
    $${PWD}/OAIAggregates.h \
    $${PWD}/OAIAlarms.h \
    $${PWD}/OAIAssetCompositeModel.h \
    $${PWD}/OAIAssetErrorCode.h \
    $${PWD}/OAIAssetErrorDetails.h \
    $${PWD}/OAIAssetHierarchy.h \
    $${PWD}/OAIAssetHierarchyInfo.h \
    $${PWD}/OAIAssetModelCompositeModel.h \
    $${PWD}/OAIAssetModelCompositeModelDefinition.h \
    $${PWD}/OAIAssetModelHierarchy.h \
    $${PWD}/OAIAssetModelHierarchyDefinition.h \
    $${PWD}/OAIAssetModelProperty.h \
    $${PWD}/OAIAssetModelPropertyDefinition.h \
    $${PWD}/OAIAssetModelPropertyDefinition_type.h \
    $${PWD}/OAIAssetModelPropertySummary.h \
    $${PWD}/OAIAssetModelProperty_type.h \
    $${PWD}/OAIAssetModelState.h \
    $${PWD}/OAIAssetModelStatus.h \
    $${PWD}/OAIAssetModelStatus_error.h \
    $${PWD}/OAIAssetModelSummary.h \
    $${PWD}/OAIAssetModelSummary_status.h \
    $${PWD}/OAIAssetProperty.h \
    $${PWD}/OAIAssetPropertySummary.h \
    $${PWD}/OAIAssetPropertyValue.h \
    $${PWD}/OAIAssetPropertyValue_timestamp.h \
    $${PWD}/OAIAssetPropertyValue_value.h \
    $${PWD}/OAIAssetProperty_notification.h \
    $${PWD}/OAIAssetRelationshipSummary.h \
    $${PWD}/OAIAssetRelationshipSummary_hierarchyInfo.h \
    $${PWD}/OAIAssetRelationshipType.h \
    $${PWD}/OAIAssetState.h \
    $${PWD}/OAIAssetStatus.h \
    $${PWD}/OAIAssetSummary.h \
    $${PWD}/OAIAssetSummary_status.h \
    $${PWD}/OAIAssociateAssetsRequest.h \
    $${PWD}/OAIAssociateAssets_request.h \
    $${PWD}/OAIAssociateTimeSeriesToAssetPropertyRequest.h \
    $${PWD}/OAIAssociateTimeSeriesToAssetProperty_request.h \
    $${PWD}/OAIAssociatedAssetsSummary.h \
    $${PWD}/OAIAttribute.h \
    $${PWD}/OAIAuthMode.h \
    $${PWD}/OAIBatchAssociateProjectAssetsRequest.h \
    $${PWD}/OAIBatchAssociateProjectAssetsResponse.h \
    $${PWD}/OAIBatchAssociateProjectAssets_request.h \
    $${PWD}/OAIBatchDisassociateProjectAssetsRequest.h \
    $${PWD}/OAIBatchDisassociateProjectAssetsResponse.h \
    $${PWD}/OAIBatchDisassociateProjectAssets_request.h \
    $${PWD}/OAIBatchEntryCompletionStatus.h \
    $${PWD}/OAIBatchGetAssetPropertyAggregatesEntry.h \
    $${PWD}/OAIBatchGetAssetPropertyAggregatesErrorCode.h \
    $${PWD}/OAIBatchGetAssetPropertyAggregatesErrorEntry.h \
    $${PWD}/OAIBatchGetAssetPropertyAggregatesErrorInfo.h \
    $${PWD}/OAIBatchGetAssetPropertyAggregatesRequest.h \
    $${PWD}/OAIBatchGetAssetPropertyAggregatesResponse.h \
    $${PWD}/OAIBatchGetAssetPropertyAggregatesSkippedEntry.h \
    $${PWD}/OAIBatchGetAssetPropertyAggregatesSkippedEntry_errorInfo.h \
    $${PWD}/OAIBatchGetAssetPropertyAggregatesSuccessEntry.h \
    $${PWD}/OAIBatchGetAssetPropertyAggregates_request.h \
    $${PWD}/OAIBatchGetAssetPropertyValueEntry.h \
    $${PWD}/OAIBatchGetAssetPropertyValueErrorCode.h \
    $${PWD}/OAIBatchGetAssetPropertyValueErrorEntry.h \
    $${PWD}/OAIBatchGetAssetPropertyValueErrorInfo.h \
    $${PWD}/OAIBatchGetAssetPropertyValueHistoryEntry.h \
    $${PWD}/OAIBatchGetAssetPropertyValueHistoryErrorCode.h \
    $${PWD}/OAIBatchGetAssetPropertyValueHistoryErrorEntry.h \
    $${PWD}/OAIBatchGetAssetPropertyValueHistoryErrorInfo.h \
    $${PWD}/OAIBatchGetAssetPropertyValueHistoryRequest.h \
    $${PWD}/OAIBatchGetAssetPropertyValueHistoryResponse.h \
    $${PWD}/OAIBatchGetAssetPropertyValueHistorySkippedEntry.h \
    $${PWD}/OAIBatchGetAssetPropertyValueHistorySkippedEntry_errorInfo.h \
    $${PWD}/OAIBatchGetAssetPropertyValueHistorySuccessEntry.h \
    $${PWD}/OAIBatchGetAssetPropertyValueHistory_request.h \
    $${PWD}/OAIBatchGetAssetPropertyValueRequest.h \
    $${PWD}/OAIBatchGetAssetPropertyValueResponse.h \
    $${PWD}/OAIBatchGetAssetPropertyValueSkippedEntry.h \
    $${PWD}/OAIBatchGetAssetPropertyValueSkippedEntry_errorInfo.h \
    $${PWD}/OAIBatchGetAssetPropertyValueSuccessEntry.h \
    $${PWD}/OAIBatchGetAssetPropertyValue_request.h \
    $${PWD}/OAIBatchPutAssetPropertyError.h \
    $${PWD}/OAIBatchPutAssetPropertyErrorEntry.h \
    $${PWD}/OAIBatchPutAssetPropertyValueErrorCode.h \
    $${PWD}/OAIBatchPutAssetPropertyValueRequest.h \
    $${PWD}/OAIBatchPutAssetPropertyValueResponse.h \
    $${PWD}/OAIBatchPutAssetPropertyValue_request.h \
    $${PWD}/OAICapabilitySyncStatus.h \
    $${PWD}/OAIColumnName.h \
    $${PWD}/OAICompositeModelProperty.h \
    $${PWD}/OAIComputeLocation.h \
    $${PWD}/OAIConfigurationErrorDetails.h \
    $${PWD}/OAIConfigurationState.h \
    $${PWD}/OAIConfigurationStatus.h \
    $${PWD}/OAIConfigurationStatus_error.h \
    $${PWD}/OAICreateAccessPolicyRequest.h \
    $${PWD}/OAICreateAccessPolicyRequest_accessPolicyIdentity.h \
    $${PWD}/OAICreateAccessPolicyRequest_accessPolicyResource.h \
    $${PWD}/OAICreateAccessPolicyResponse.h \
    $${PWD}/OAICreateAccessPolicy_request.h \
    $${PWD}/OAICreateAccessPolicy_request_accessPolicyIdentity.h \
    $${PWD}/OAICreateAccessPolicy_request_accessPolicyIdentity_group.h \
    $${PWD}/OAICreateAccessPolicy_request_accessPolicyIdentity_iamRole.h \
    $${PWD}/OAICreateAccessPolicy_request_accessPolicyIdentity_iamUser.h \
    $${PWD}/OAICreateAccessPolicy_request_accessPolicyIdentity_user.h \
    $${PWD}/OAICreateAccessPolicy_request_accessPolicyResource.h \
    $${PWD}/OAICreateAccessPolicy_request_accessPolicyResource_portal.h \
    $${PWD}/OAICreateAccessPolicy_request_accessPolicyResource_project.h \
    $${PWD}/OAICreateAssetModelRequest.h \
    $${PWD}/OAICreateAssetModelResponse.h \
    $${PWD}/OAICreateAssetModelResponse_assetModelStatus.h \
    $${PWD}/OAICreateAssetModel_request.h \
    $${PWD}/OAICreateAssetRequest.h \
    $${PWD}/OAICreateAssetResponse.h \
    $${PWD}/OAICreateAssetResponse_assetStatus.h \
    $${PWD}/OAICreateAsset_request.h \
    $${PWD}/OAICreateBulkImportJobRequest.h \
    $${PWD}/OAICreateBulkImportJobResponse.h \
    $${PWD}/OAICreateBulkImportJob_request.h \
    $${PWD}/OAICreateBulkImportJob_request_errorReportLocation.h \
    $${PWD}/OAICreateBulkImportJob_request_jobConfiguration.h \
    $${PWD}/OAICreateBulkImportJob_request_jobConfiguration_fileFormat.h \
    $${PWD}/OAICreateDashboardRequest.h \
    $${PWD}/OAICreateDashboardResponse.h \
    $${PWD}/OAICreateDashboard_request.h \
    $${PWD}/OAICreateGatewayRequest.h \
    $${PWD}/OAICreateGatewayRequest_gatewayPlatform.h \
    $${PWD}/OAICreateGatewayResponse.h \
    $${PWD}/OAICreateGateway_request.h \
    $${PWD}/OAICreateGateway_request_gatewayPlatform.h \
    $${PWD}/OAICreateGateway_request_gatewayPlatform_greengrass.h \
    $${PWD}/OAICreateGateway_request_gatewayPlatform_greengrassV2.h \
    $${PWD}/OAICreatePortalRequest.h \
    $${PWD}/OAICreatePortalRequest_alarms.h \
    $${PWD}/OAICreatePortalRequest_portalLogoImageFile.h \
    $${PWD}/OAICreatePortalResponse.h \
    $${PWD}/OAICreatePortalResponse_portalStatus.h \
    $${PWD}/OAICreatePortal_request.h \
    $${PWD}/OAICreatePortal_request_alarms.h \
    $${PWD}/OAICreatePortal_request_portalLogoImageFile.h \
    $${PWD}/OAICreateProjectRequest.h \
    $${PWD}/OAICreateProjectResponse.h \
    $${PWD}/OAICreateProject_request.h \
    $${PWD}/OAICsv.h \
    $${PWD}/OAICustomerManagedS3Storage.h \
    $${PWD}/OAIDashboardSummary.h \
    $${PWD}/OAIDeleteAssetModelResponse.h \
    $${PWD}/OAIDeleteAssetModelResponse_assetModelStatus.h \
    $${PWD}/OAIDeleteAssetResponse.h \
    $${PWD}/OAIDeleteAssetResponse_assetStatus.h \
    $${PWD}/OAIDeletePortalResponse.h \
    $${PWD}/OAIDeletePortalResponse_portalStatus.h \
    $${PWD}/OAIDeleteTimeSeriesRequest.h \
    $${PWD}/OAIDescribeAccessPolicyResponse.h \
    $${PWD}/OAIDescribeAccessPolicyResponse_accessPolicyIdentity.h \
    $${PWD}/OAIDescribeAccessPolicyResponse_accessPolicyResource.h \
    $${PWD}/OAIDescribeAssetModelResponse.h \
    $${PWD}/OAIDescribeAssetModelResponse_assetModelStatus.h \
    $${PWD}/OAIDescribeAssetPropertyResponse.h \
    $${PWD}/OAIDescribeAssetPropertyResponse_assetProperty.h \
    $${PWD}/OAIDescribeAssetPropertyResponse_compositeModel.h \
    $${PWD}/OAIDescribeAssetResponse.h \
    $${PWD}/OAIDescribeAssetResponse_assetStatus.h \
    $${PWD}/OAIDescribeBulkImportJobResponse.h \
    $${PWD}/OAIDescribeBulkImportJobResponse_errorReportLocation.h \
    $${PWD}/OAIDescribeBulkImportJobResponse_jobConfiguration.h \
    $${PWD}/OAIDescribeDashboardResponse.h \
    $${PWD}/OAIDescribeDefaultEncryptionConfigurationResponse.h \
    $${PWD}/OAIDescribeDefaultEncryptionConfigurationResponse_configurationStatus.h \
    $${PWD}/OAIDescribeGatewayCapabilityConfigurationResponse.h \
    $${PWD}/OAIDescribeGatewayResponse.h \
    $${PWD}/OAIDescribeGatewayResponse_gatewayPlatform.h \
    $${PWD}/OAIDescribeLoggingOptionsResponse.h \
    $${PWD}/OAIDescribeLoggingOptionsResponse_loggingOptions.h \
    $${PWD}/OAIDescribePortalResponse.h \
    $${PWD}/OAIDescribePortalResponse_alarms.h \
    $${PWD}/OAIDescribePortalResponse_portalLogoImageLocation.h \
    $${PWD}/OAIDescribePortalResponse_portalStatus.h \
    $${PWD}/OAIDescribeProjectResponse.h \
    $${PWD}/OAIDescribeStorageConfigurationResponse.h \
    $${PWD}/OAIDescribeStorageConfigurationResponse_multiLayerStorage.h \
    $${PWD}/OAIDescribeStorageConfigurationResponse_retentionPeriod.h \
    $${PWD}/OAIDescribeTimeSeriesResponse.h \
    $${PWD}/OAIDetailedError.h \
    $${PWD}/OAIDetailedErrorCode.h \
    $${PWD}/OAIDisassociateAssetsRequest.h \
    $${PWD}/OAIDisassociateAssets_request.h \
    $${PWD}/OAIDisassociateTimeSeriesFromAssetPropertyRequest.h \
    $${PWD}/OAIDisassociatedDataStorageState.h \
    $${PWD}/OAIEncryptionType.h \
    $${PWD}/OAIErrorCode.h \
    $${PWD}/OAIErrorDetails.h \
    $${PWD}/OAIErrorReportLocation.h \
    $${PWD}/OAIExpressionVariable.h \
    $${PWD}/OAIExpressionVariable_value.h \
    $${PWD}/OAIFile.h \
    $${PWD}/OAIFileFormat.h \
    $${PWD}/OAIFileFormat_csv.h \
    $${PWD}/OAIForwardingConfig.h \
    $${PWD}/OAIForwardingConfigState.h \
    $${PWD}/OAIGatewayCapabilitySummary.h \
    $${PWD}/OAIGatewayPlatform.h \
    $${PWD}/OAIGatewaySummary.h \
    $${PWD}/OAIGetAssetPropertyAggregatesResponse.h \
    $${PWD}/OAIGetAssetPropertyValueHistoryResponse.h \
    $${PWD}/OAIGetAssetPropertyValueResponse.h \
    $${PWD}/OAIGetAssetPropertyValueResponse_propertyValue.h \
    $${PWD}/OAIGetInterpolatedAssetPropertyValuesResponse.h \
    $${PWD}/OAIGreengrass.h \
    $${PWD}/OAIGreengrassV2.h \
    $${PWD}/OAIGroupIdentity.h \
    $${PWD}/OAIIAMRoleIdentity.h \
    $${PWD}/OAIIAMUserIdentity.h \
    $${PWD}/OAIIdentity.h \
    $${PWD}/OAIIdentityType.h \
    $${PWD}/OAIImage.h \
    $${PWD}/OAIImageFile.h \
    $${PWD}/OAIImageFileType.h \
    $${PWD}/OAIImageLocation.h \
    $${PWD}/OAIInterpolatedAssetPropertyValue.h \
    $${PWD}/OAIJobConfiguration.h \
    $${PWD}/OAIJobStatus.h \
    $${PWD}/OAIJobSummary.h \
    $${PWD}/OAIListAccessPoliciesResponse.h \
    $${PWD}/OAIListAssetModelPropertiesFilter.h \
    $${PWD}/OAIListAssetModelPropertiesResponse.h \
    $${PWD}/OAIListAssetModelsResponse.h \
    $${PWD}/OAIListAssetPropertiesFilter.h \
    $${PWD}/OAIListAssetPropertiesResponse.h \
    $${PWD}/OAIListAssetRelationshipsResponse.h \
    $${PWD}/OAIListAssetsFilter.h \
    $${PWD}/OAIListAssetsResponse.h \
    $${PWD}/OAIListAssociatedAssetsResponse.h \
    $${PWD}/OAIListBulkImportJobsFilter.h \
    $${PWD}/OAIListBulkImportJobsResponse.h \
    $${PWD}/OAIListDashboardsResponse.h \
    $${PWD}/OAIListGatewaysResponse.h \
    $${PWD}/OAIListPortalsResponse.h \
    $${PWD}/OAIListProjectAssetsResponse.h \
    $${PWD}/OAIListProjectsResponse.h \
    $${PWD}/OAIListTagsForResourceResponse.h \
    $${PWD}/OAIListTimeSeriesResponse.h \
    $${PWD}/OAIListTimeSeriesType.h \
    $${PWD}/OAILoggingLevel.h \
    $${PWD}/OAILoggingOptions.h \
    $${PWD}/OAIMeasurement.h \
    $${PWD}/OAIMeasurementProcessingConfig.h \
    $${PWD}/OAIMeasurementProcessingConfig_forwardingConfig.h \
    $${PWD}/OAIMeasurement_processingConfig.h \
    $${PWD}/OAIMetric.h \
    $${PWD}/OAIMetricProcessingConfig.h \
    $${PWD}/OAIMetricWindow.h \
    $${PWD}/OAIMetricWindow_tumbling.h \
    $${PWD}/OAIMetric_processingConfig.h \
    $${PWD}/OAIMetric_window.h \
    $${PWD}/OAIMonitorErrorCode.h \
    $${PWD}/OAIMonitorErrorDetails.h \
    $${PWD}/OAIMultiLayerStorage.h \
    $${PWD}/OAIPermission.h \
    $${PWD}/OAIPortalResource.h \
    $${PWD}/OAIPortalState.h \
    $${PWD}/OAIPortalStatus.h \
    $${PWD}/OAIPortalStatus_error.h \
    $${PWD}/OAIPortalSummary.h \
    $${PWD}/OAIProjectResource.h \
    $${PWD}/OAIProjectSummary.h \
    $${PWD}/OAIProperty.h \
    $${PWD}/OAIPropertyDataType.h \
    $${PWD}/OAIPropertyNotification.h \
    $${PWD}/OAIPropertyNotificationState.h \
    $${PWD}/OAIPropertyType.h \
    $${PWD}/OAIPropertyType_attribute.h \
    $${PWD}/OAIPropertyType_measurement.h \
    $${PWD}/OAIPropertyType_metric.h \
    $${PWD}/OAIPropertyType_transform.h \
    $${PWD}/OAIProperty_type.h \
    $${PWD}/OAIPutAssetPropertyValueEntry.h \
    $${PWD}/OAIPutDefaultEncryptionConfigurationRequest.h \
    $${PWD}/OAIPutDefaultEncryptionConfigurationResponse.h \
    $${PWD}/OAIPutDefaultEncryptionConfigurationResponse_configurationStatus.h \
    $${PWD}/OAIPutDefaultEncryptionConfiguration_request.h \
    $${PWD}/OAIPutLoggingOptionsRequest.h \
    $${PWD}/OAIPutLoggingOptionsRequest_loggingOptions.h \
    $${PWD}/OAIPutLoggingOptions_request.h \
    $${PWD}/OAIPutLoggingOptions_request_loggingOptions.h \
    $${PWD}/OAIPutStorageConfigurationRequest.h \
    $${PWD}/OAIPutStorageConfigurationRequest_multiLayerStorage.h \
    $${PWD}/OAIPutStorageConfigurationResponse.h \
    $${PWD}/OAIPutStorageConfiguration_request.h \
    $${PWD}/OAIPutStorageConfiguration_request_multiLayerStorage.h \
    $${PWD}/OAIPutStorageConfiguration_request_multiLayerStorage_customerManagedS3Storage.h \
    $${PWD}/OAIPutStorageConfiguration_request_retentionPeriod.h \
    $${PWD}/OAIQuality.h \
    $${PWD}/OAIResource.h \
    $${PWD}/OAIResourceType.h \
    $${PWD}/OAIRetentionPeriod.h \
    $${PWD}/OAIStorageType.h \
    $${PWD}/OAITagResourceRequest.h \
    $${PWD}/OAITagResource_request.h \
    $${PWD}/OAITimeInNanos.h \
    $${PWD}/OAITimeOrdering.h \
    $${PWD}/OAITimeSeriesSummary.h \
    $${PWD}/OAITransform.h \
    $${PWD}/OAITransformProcessingConfig.h \
    $${PWD}/OAITransform_processingConfig.h \
    $${PWD}/OAITraversalDirection.h \
    $${PWD}/OAITraversalType.h \
    $${PWD}/OAITumblingWindow.h \
    $${PWD}/OAIUpdateAccessPolicyRequest.h \
    $${PWD}/OAIUpdateAccessPolicy_request.h \
    $${PWD}/OAIUpdateAssetModelRequest.h \
    $${PWD}/OAIUpdateAssetModelResponse.h \
    $${PWD}/OAIUpdateAssetModelResponse_assetModelStatus.h \
    $${PWD}/OAIUpdateAssetModel_request.h \
    $${PWD}/OAIUpdateAssetPropertyRequest.h \
    $${PWD}/OAIUpdateAssetProperty_request.h \
    $${PWD}/OAIUpdateAssetRequest.h \
    $${PWD}/OAIUpdateAssetResponse.h \
    $${PWD}/OAIUpdateAssetResponse_assetStatus.h \
    $${PWD}/OAIUpdateAsset_request.h \
    $${PWD}/OAIUpdateDashboardRequest.h \
    $${PWD}/OAIUpdateDashboard_request.h \
    $${PWD}/OAIUpdateGatewayCapabilityConfigurationRequest.h \
    $${PWD}/OAIUpdateGatewayCapabilityConfigurationResponse.h \
    $${PWD}/OAIUpdateGatewayCapabilityConfiguration_request.h \
    $${PWD}/OAIUpdateGatewayRequest.h \
    $${PWD}/OAIUpdateGateway_request.h \
    $${PWD}/OAIUpdatePortalRequest.h \
    $${PWD}/OAIUpdatePortalResponse.h \
    $${PWD}/OAIUpdatePortalResponse_portalStatus.h \
    $${PWD}/OAIUpdatePortal_request.h \
    $${PWD}/OAIUpdatePortal_request_portalLogoImage.h \
    $${PWD}/OAIUpdateProjectRequest.h \
    $${PWD}/OAIUpdateProject_request.h \
    $${PWD}/OAIUserIdentity.h \
    $${PWD}/OAIVariableValue.h \
    $${PWD}/OAIVariant.h \
# APIs
    $${PWD}/OAIDefaultApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAccessPolicySummary.cpp \
    $${PWD}/OAIAccessPolicySummary_identity.cpp \
    $${PWD}/OAIAccessPolicySummary_resource.cpp \
    $${PWD}/OAIAggregateType.cpp \
    $${PWD}/OAIAggregatedValue.cpp \
    $${PWD}/OAIAggregatedValue_value.cpp \
    $${PWD}/OAIAggregates.cpp \
    $${PWD}/OAIAlarms.cpp \
    $${PWD}/OAIAssetCompositeModel.cpp \
    $${PWD}/OAIAssetErrorCode.cpp \
    $${PWD}/OAIAssetErrorDetails.cpp \
    $${PWD}/OAIAssetHierarchy.cpp \
    $${PWD}/OAIAssetHierarchyInfo.cpp \
    $${PWD}/OAIAssetModelCompositeModel.cpp \
    $${PWD}/OAIAssetModelCompositeModelDefinition.cpp \
    $${PWD}/OAIAssetModelHierarchy.cpp \
    $${PWD}/OAIAssetModelHierarchyDefinition.cpp \
    $${PWD}/OAIAssetModelProperty.cpp \
    $${PWD}/OAIAssetModelPropertyDefinition.cpp \
    $${PWD}/OAIAssetModelPropertyDefinition_type.cpp \
    $${PWD}/OAIAssetModelPropertySummary.cpp \
    $${PWD}/OAIAssetModelProperty_type.cpp \
    $${PWD}/OAIAssetModelState.cpp \
    $${PWD}/OAIAssetModelStatus.cpp \
    $${PWD}/OAIAssetModelStatus_error.cpp \
    $${PWD}/OAIAssetModelSummary.cpp \
    $${PWD}/OAIAssetModelSummary_status.cpp \
    $${PWD}/OAIAssetProperty.cpp \
    $${PWD}/OAIAssetPropertySummary.cpp \
    $${PWD}/OAIAssetPropertyValue.cpp \
    $${PWD}/OAIAssetPropertyValue_timestamp.cpp \
    $${PWD}/OAIAssetPropertyValue_value.cpp \
    $${PWD}/OAIAssetProperty_notification.cpp \
    $${PWD}/OAIAssetRelationshipSummary.cpp \
    $${PWD}/OAIAssetRelationshipSummary_hierarchyInfo.cpp \
    $${PWD}/OAIAssetRelationshipType.cpp \
    $${PWD}/OAIAssetState.cpp \
    $${PWD}/OAIAssetStatus.cpp \
    $${PWD}/OAIAssetSummary.cpp \
    $${PWD}/OAIAssetSummary_status.cpp \
    $${PWD}/OAIAssociateAssetsRequest.cpp \
    $${PWD}/OAIAssociateAssets_request.cpp \
    $${PWD}/OAIAssociateTimeSeriesToAssetPropertyRequest.cpp \
    $${PWD}/OAIAssociateTimeSeriesToAssetProperty_request.cpp \
    $${PWD}/OAIAssociatedAssetsSummary.cpp \
    $${PWD}/OAIAttribute.cpp \
    $${PWD}/OAIAuthMode.cpp \
    $${PWD}/OAIBatchAssociateProjectAssetsRequest.cpp \
    $${PWD}/OAIBatchAssociateProjectAssetsResponse.cpp \
    $${PWD}/OAIBatchAssociateProjectAssets_request.cpp \
    $${PWD}/OAIBatchDisassociateProjectAssetsRequest.cpp \
    $${PWD}/OAIBatchDisassociateProjectAssetsResponse.cpp \
    $${PWD}/OAIBatchDisassociateProjectAssets_request.cpp \
    $${PWD}/OAIBatchEntryCompletionStatus.cpp \
    $${PWD}/OAIBatchGetAssetPropertyAggregatesEntry.cpp \
    $${PWD}/OAIBatchGetAssetPropertyAggregatesErrorCode.cpp \
    $${PWD}/OAIBatchGetAssetPropertyAggregatesErrorEntry.cpp \
    $${PWD}/OAIBatchGetAssetPropertyAggregatesErrorInfo.cpp \
    $${PWD}/OAIBatchGetAssetPropertyAggregatesRequest.cpp \
    $${PWD}/OAIBatchGetAssetPropertyAggregatesResponse.cpp \
    $${PWD}/OAIBatchGetAssetPropertyAggregatesSkippedEntry.cpp \
    $${PWD}/OAIBatchGetAssetPropertyAggregatesSkippedEntry_errorInfo.cpp \
    $${PWD}/OAIBatchGetAssetPropertyAggregatesSuccessEntry.cpp \
    $${PWD}/OAIBatchGetAssetPropertyAggregates_request.cpp \
    $${PWD}/OAIBatchGetAssetPropertyValueEntry.cpp \
    $${PWD}/OAIBatchGetAssetPropertyValueErrorCode.cpp \
    $${PWD}/OAIBatchGetAssetPropertyValueErrorEntry.cpp \
    $${PWD}/OAIBatchGetAssetPropertyValueErrorInfo.cpp \
    $${PWD}/OAIBatchGetAssetPropertyValueHistoryEntry.cpp \
    $${PWD}/OAIBatchGetAssetPropertyValueHistoryErrorCode.cpp \
    $${PWD}/OAIBatchGetAssetPropertyValueHistoryErrorEntry.cpp \
    $${PWD}/OAIBatchGetAssetPropertyValueHistoryErrorInfo.cpp \
    $${PWD}/OAIBatchGetAssetPropertyValueHistoryRequest.cpp \
    $${PWD}/OAIBatchGetAssetPropertyValueHistoryResponse.cpp \
    $${PWD}/OAIBatchGetAssetPropertyValueHistorySkippedEntry.cpp \
    $${PWD}/OAIBatchGetAssetPropertyValueHistorySkippedEntry_errorInfo.cpp \
    $${PWD}/OAIBatchGetAssetPropertyValueHistorySuccessEntry.cpp \
    $${PWD}/OAIBatchGetAssetPropertyValueHistory_request.cpp \
    $${PWD}/OAIBatchGetAssetPropertyValueRequest.cpp \
    $${PWD}/OAIBatchGetAssetPropertyValueResponse.cpp \
    $${PWD}/OAIBatchGetAssetPropertyValueSkippedEntry.cpp \
    $${PWD}/OAIBatchGetAssetPropertyValueSkippedEntry_errorInfo.cpp \
    $${PWD}/OAIBatchGetAssetPropertyValueSuccessEntry.cpp \
    $${PWD}/OAIBatchGetAssetPropertyValue_request.cpp \
    $${PWD}/OAIBatchPutAssetPropertyError.cpp \
    $${PWD}/OAIBatchPutAssetPropertyErrorEntry.cpp \
    $${PWD}/OAIBatchPutAssetPropertyValueErrorCode.cpp \
    $${PWD}/OAIBatchPutAssetPropertyValueRequest.cpp \
    $${PWD}/OAIBatchPutAssetPropertyValueResponse.cpp \
    $${PWD}/OAIBatchPutAssetPropertyValue_request.cpp \
    $${PWD}/OAICapabilitySyncStatus.cpp \
    $${PWD}/OAIColumnName.cpp \
    $${PWD}/OAICompositeModelProperty.cpp \
    $${PWD}/OAIComputeLocation.cpp \
    $${PWD}/OAIConfigurationErrorDetails.cpp \
    $${PWD}/OAIConfigurationState.cpp \
    $${PWD}/OAIConfigurationStatus.cpp \
    $${PWD}/OAIConfigurationStatus_error.cpp \
    $${PWD}/OAICreateAccessPolicyRequest.cpp \
    $${PWD}/OAICreateAccessPolicyRequest_accessPolicyIdentity.cpp \
    $${PWD}/OAICreateAccessPolicyRequest_accessPolicyResource.cpp \
    $${PWD}/OAICreateAccessPolicyResponse.cpp \
    $${PWD}/OAICreateAccessPolicy_request.cpp \
    $${PWD}/OAICreateAccessPolicy_request_accessPolicyIdentity.cpp \
    $${PWD}/OAICreateAccessPolicy_request_accessPolicyIdentity_group.cpp \
    $${PWD}/OAICreateAccessPolicy_request_accessPolicyIdentity_iamRole.cpp \
    $${PWD}/OAICreateAccessPolicy_request_accessPolicyIdentity_iamUser.cpp \
    $${PWD}/OAICreateAccessPolicy_request_accessPolicyIdentity_user.cpp \
    $${PWD}/OAICreateAccessPolicy_request_accessPolicyResource.cpp \
    $${PWD}/OAICreateAccessPolicy_request_accessPolicyResource_portal.cpp \
    $${PWD}/OAICreateAccessPolicy_request_accessPolicyResource_project.cpp \
    $${PWD}/OAICreateAssetModelRequest.cpp \
    $${PWD}/OAICreateAssetModelResponse.cpp \
    $${PWD}/OAICreateAssetModelResponse_assetModelStatus.cpp \
    $${PWD}/OAICreateAssetModel_request.cpp \
    $${PWD}/OAICreateAssetRequest.cpp \
    $${PWD}/OAICreateAssetResponse.cpp \
    $${PWD}/OAICreateAssetResponse_assetStatus.cpp \
    $${PWD}/OAICreateAsset_request.cpp \
    $${PWD}/OAICreateBulkImportJobRequest.cpp \
    $${PWD}/OAICreateBulkImportJobResponse.cpp \
    $${PWD}/OAICreateBulkImportJob_request.cpp \
    $${PWD}/OAICreateBulkImportJob_request_errorReportLocation.cpp \
    $${PWD}/OAICreateBulkImportJob_request_jobConfiguration.cpp \
    $${PWD}/OAICreateBulkImportJob_request_jobConfiguration_fileFormat.cpp \
    $${PWD}/OAICreateDashboardRequest.cpp \
    $${PWD}/OAICreateDashboardResponse.cpp \
    $${PWD}/OAICreateDashboard_request.cpp \
    $${PWD}/OAICreateGatewayRequest.cpp \
    $${PWD}/OAICreateGatewayRequest_gatewayPlatform.cpp \
    $${PWD}/OAICreateGatewayResponse.cpp \
    $${PWD}/OAICreateGateway_request.cpp \
    $${PWD}/OAICreateGateway_request_gatewayPlatform.cpp \
    $${PWD}/OAICreateGateway_request_gatewayPlatform_greengrass.cpp \
    $${PWD}/OAICreateGateway_request_gatewayPlatform_greengrassV2.cpp \
    $${PWD}/OAICreatePortalRequest.cpp \
    $${PWD}/OAICreatePortalRequest_alarms.cpp \
    $${PWD}/OAICreatePortalRequest_portalLogoImageFile.cpp \
    $${PWD}/OAICreatePortalResponse.cpp \
    $${PWD}/OAICreatePortalResponse_portalStatus.cpp \
    $${PWD}/OAICreatePortal_request.cpp \
    $${PWD}/OAICreatePortal_request_alarms.cpp \
    $${PWD}/OAICreatePortal_request_portalLogoImageFile.cpp \
    $${PWD}/OAICreateProjectRequest.cpp \
    $${PWD}/OAICreateProjectResponse.cpp \
    $${PWD}/OAICreateProject_request.cpp \
    $${PWD}/OAICsv.cpp \
    $${PWD}/OAICustomerManagedS3Storage.cpp \
    $${PWD}/OAIDashboardSummary.cpp \
    $${PWD}/OAIDeleteAssetModelResponse.cpp \
    $${PWD}/OAIDeleteAssetModelResponse_assetModelStatus.cpp \
    $${PWD}/OAIDeleteAssetResponse.cpp \
    $${PWD}/OAIDeleteAssetResponse_assetStatus.cpp \
    $${PWD}/OAIDeletePortalResponse.cpp \
    $${PWD}/OAIDeletePortalResponse_portalStatus.cpp \
    $${PWD}/OAIDeleteTimeSeriesRequest.cpp \
    $${PWD}/OAIDescribeAccessPolicyResponse.cpp \
    $${PWD}/OAIDescribeAccessPolicyResponse_accessPolicyIdentity.cpp \
    $${PWD}/OAIDescribeAccessPolicyResponse_accessPolicyResource.cpp \
    $${PWD}/OAIDescribeAssetModelResponse.cpp \
    $${PWD}/OAIDescribeAssetModelResponse_assetModelStatus.cpp \
    $${PWD}/OAIDescribeAssetPropertyResponse.cpp \
    $${PWD}/OAIDescribeAssetPropertyResponse_assetProperty.cpp \
    $${PWD}/OAIDescribeAssetPropertyResponse_compositeModel.cpp \
    $${PWD}/OAIDescribeAssetResponse.cpp \
    $${PWD}/OAIDescribeAssetResponse_assetStatus.cpp \
    $${PWD}/OAIDescribeBulkImportJobResponse.cpp \
    $${PWD}/OAIDescribeBulkImportJobResponse_errorReportLocation.cpp \
    $${PWD}/OAIDescribeBulkImportJobResponse_jobConfiguration.cpp \
    $${PWD}/OAIDescribeDashboardResponse.cpp \
    $${PWD}/OAIDescribeDefaultEncryptionConfigurationResponse.cpp \
    $${PWD}/OAIDescribeDefaultEncryptionConfigurationResponse_configurationStatus.cpp \
    $${PWD}/OAIDescribeGatewayCapabilityConfigurationResponse.cpp \
    $${PWD}/OAIDescribeGatewayResponse.cpp \
    $${PWD}/OAIDescribeGatewayResponse_gatewayPlatform.cpp \
    $${PWD}/OAIDescribeLoggingOptionsResponse.cpp \
    $${PWD}/OAIDescribeLoggingOptionsResponse_loggingOptions.cpp \
    $${PWD}/OAIDescribePortalResponse.cpp \
    $${PWD}/OAIDescribePortalResponse_alarms.cpp \
    $${PWD}/OAIDescribePortalResponse_portalLogoImageLocation.cpp \
    $${PWD}/OAIDescribePortalResponse_portalStatus.cpp \
    $${PWD}/OAIDescribeProjectResponse.cpp \
    $${PWD}/OAIDescribeStorageConfigurationResponse.cpp \
    $${PWD}/OAIDescribeStorageConfigurationResponse_multiLayerStorage.cpp \
    $${PWD}/OAIDescribeStorageConfigurationResponse_retentionPeriod.cpp \
    $${PWD}/OAIDescribeTimeSeriesResponse.cpp \
    $${PWD}/OAIDetailedError.cpp \
    $${PWD}/OAIDetailedErrorCode.cpp \
    $${PWD}/OAIDisassociateAssetsRequest.cpp \
    $${PWD}/OAIDisassociateAssets_request.cpp \
    $${PWD}/OAIDisassociateTimeSeriesFromAssetPropertyRequest.cpp \
    $${PWD}/OAIDisassociatedDataStorageState.cpp \
    $${PWD}/OAIEncryptionType.cpp \
    $${PWD}/OAIErrorCode.cpp \
    $${PWD}/OAIErrorDetails.cpp \
    $${PWD}/OAIErrorReportLocation.cpp \
    $${PWD}/OAIExpressionVariable.cpp \
    $${PWD}/OAIExpressionVariable_value.cpp \
    $${PWD}/OAIFile.cpp \
    $${PWD}/OAIFileFormat.cpp \
    $${PWD}/OAIFileFormat_csv.cpp \
    $${PWD}/OAIForwardingConfig.cpp \
    $${PWD}/OAIForwardingConfigState.cpp \
    $${PWD}/OAIGatewayCapabilitySummary.cpp \
    $${PWD}/OAIGatewayPlatform.cpp \
    $${PWD}/OAIGatewaySummary.cpp \
    $${PWD}/OAIGetAssetPropertyAggregatesResponse.cpp \
    $${PWD}/OAIGetAssetPropertyValueHistoryResponse.cpp \
    $${PWD}/OAIGetAssetPropertyValueResponse.cpp \
    $${PWD}/OAIGetAssetPropertyValueResponse_propertyValue.cpp \
    $${PWD}/OAIGetInterpolatedAssetPropertyValuesResponse.cpp \
    $${PWD}/OAIGreengrass.cpp \
    $${PWD}/OAIGreengrassV2.cpp \
    $${PWD}/OAIGroupIdentity.cpp \
    $${PWD}/OAIIAMRoleIdentity.cpp \
    $${PWD}/OAIIAMUserIdentity.cpp \
    $${PWD}/OAIIdentity.cpp \
    $${PWD}/OAIIdentityType.cpp \
    $${PWD}/OAIImage.cpp \
    $${PWD}/OAIImageFile.cpp \
    $${PWD}/OAIImageFileType.cpp \
    $${PWD}/OAIImageLocation.cpp \
    $${PWD}/OAIInterpolatedAssetPropertyValue.cpp \
    $${PWD}/OAIJobConfiguration.cpp \
    $${PWD}/OAIJobStatus.cpp \
    $${PWD}/OAIJobSummary.cpp \
    $${PWD}/OAIListAccessPoliciesResponse.cpp \
    $${PWD}/OAIListAssetModelPropertiesFilter.cpp \
    $${PWD}/OAIListAssetModelPropertiesResponse.cpp \
    $${PWD}/OAIListAssetModelsResponse.cpp \
    $${PWD}/OAIListAssetPropertiesFilter.cpp \
    $${PWD}/OAIListAssetPropertiesResponse.cpp \
    $${PWD}/OAIListAssetRelationshipsResponse.cpp \
    $${PWD}/OAIListAssetsFilter.cpp \
    $${PWD}/OAIListAssetsResponse.cpp \
    $${PWD}/OAIListAssociatedAssetsResponse.cpp \
    $${PWD}/OAIListBulkImportJobsFilter.cpp \
    $${PWD}/OAIListBulkImportJobsResponse.cpp \
    $${PWD}/OAIListDashboardsResponse.cpp \
    $${PWD}/OAIListGatewaysResponse.cpp \
    $${PWD}/OAIListPortalsResponse.cpp \
    $${PWD}/OAIListProjectAssetsResponse.cpp \
    $${PWD}/OAIListProjectsResponse.cpp \
    $${PWD}/OAIListTagsForResourceResponse.cpp \
    $${PWD}/OAIListTimeSeriesResponse.cpp \
    $${PWD}/OAIListTimeSeriesType.cpp \
    $${PWD}/OAILoggingLevel.cpp \
    $${PWD}/OAILoggingOptions.cpp \
    $${PWD}/OAIMeasurement.cpp \
    $${PWD}/OAIMeasurementProcessingConfig.cpp \
    $${PWD}/OAIMeasurementProcessingConfig_forwardingConfig.cpp \
    $${PWD}/OAIMeasurement_processingConfig.cpp \
    $${PWD}/OAIMetric.cpp \
    $${PWD}/OAIMetricProcessingConfig.cpp \
    $${PWD}/OAIMetricWindow.cpp \
    $${PWD}/OAIMetricWindow_tumbling.cpp \
    $${PWD}/OAIMetric_processingConfig.cpp \
    $${PWD}/OAIMetric_window.cpp \
    $${PWD}/OAIMonitorErrorCode.cpp \
    $${PWD}/OAIMonitorErrorDetails.cpp \
    $${PWD}/OAIMultiLayerStorage.cpp \
    $${PWD}/OAIPermission.cpp \
    $${PWD}/OAIPortalResource.cpp \
    $${PWD}/OAIPortalState.cpp \
    $${PWD}/OAIPortalStatus.cpp \
    $${PWD}/OAIPortalStatus_error.cpp \
    $${PWD}/OAIPortalSummary.cpp \
    $${PWD}/OAIProjectResource.cpp \
    $${PWD}/OAIProjectSummary.cpp \
    $${PWD}/OAIProperty.cpp \
    $${PWD}/OAIPropertyDataType.cpp \
    $${PWD}/OAIPropertyNotification.cpp \
    $${PWD}/OAIPropertyNotificationState.cpp \
    $${PWD}/OAIPropertyType.cpp \
    $${PWD}/OAIPropertyType_attribute.cpp \
    $${PWD}/OAIPropertyType_measurement.cpp \
    $${PWD}/OAIPropertyType_metric.cpp \
    $${PWD}/OAIPropertyType_transform.cpp \
    $${PWD}/OAIProperty_type.cpp \
    $${PWD}/OAIPutAssetPropertyValueEntry.cpp \
    $${PWD}/OAIPutDefaultEncryptionConfigurationRequest.cpp \
    $${PWD}/OAIPutDefaultEncryptionConfigurationResponse.cpp \
    $${PWD}/OAIPutDefaultEncryptionConfigurationResponse_configurationStatus.cpp \
    $${PWD}/OAIPutDefaultEncryptionConfiguration_request.cpp \
    $${PWD}/OAIPutLoggingOptionsRequest.cpp \
    $${PWD}/OAIPutLoggingOptionsRequest_loggingOptions.cpp \
    $${PWD}/OAIPutLoggingOptions_request.cpp \
    $${PWD}/OAIPutLoggingOptions_request_loggingOptions.cpp \
    $${PWD}/OAIPutStorageConfigurationRequest.cpp \
    $${PWD}/OAIPutStorageConfigurationRequest_multiLayerStorage.cpp \
    $${PWD}/OAIPutStorageConfigurationResponse.cpp \
    $${PWD}/OAIPutStorageConfiguration_request.cpp \
    $${PWD}/OAIPutStorageConfiguration_request_multiLayerStorage.cpp \
    $${PWD}/OAIPutStorageConfiguration_request_multiLayerStorage_customerManagedS3Storage.cpp \
    $${PWD}/OAIPutStorageConfiguration_request_retentionPeriod.cpp \
    $${PWD}/OAIQuality.cpp \
    $${PWD}/OAIResource.cpp \
    $${PWD}/OAIResourceType.cpp \
    $${PWD}/OAIRetentionPeriod.cpp \
    $${PWD}/OAIStorageType.cpp \
    $${PWD}/OAITagResourceRequest.cpp \
    $${PWD}/OAITagResource_request.cpp \
    $${PWD}/OAITimeInNanos.cpp \
    $${PWD}/OAITimeOrdering.cpp \
    $${PWD}/OAITimeSeriesSummary.cpp \
    $${PWD}/OAITransform.cpp \
    $${PWD}/OAITransformProcessingConfig.cpp \
    $${PWD}/OAITransform_processingConfig.cpp \
    $${PWD}/OAITraversalDirection.cpp \
    $${PWD}/OAITraversalType.cpp \
    $${PWD}/OAITumblingWindow.cpp \
    $${PWD}/OAIUpdateAccessPolicyRequest.cpp \
    $${PWD}/OAIUpdateAccessPolicy_request.cpp \
    $${PWD}/OAIUpdateAssetModelRequest.cpp \
    $${PWD}/OAIUpdateAssetModelResponse.cpp \
    $${PWD}/OAIUpdateAssetModelResponse_assetModelStatus.cpp \
    $${PWD}/OAIUpdateAssetModel_request.cpp \
    $${PWD}/OAIUpdateAssetPropertyRequest.cpp \
    $${PWD}/OAIUpdateAssetProperty_request.cpp \
    $${PWD}/OAIUpdateAssetRequest.cpp \
    $${PWD}/OAIUpdateAssetResponse.cpp \
    $${PWD}/OAIUpdateAssetResponse_assetStatus.cpp \
    $${PWD}/OAIUpdateAsset_request.cpp \
    $${PWD}/OAIUpdateDashboardRequest.cpp \
    $${PWD}/OAIUpdateDashboard_request.cpp \
    $${PWD}/OAIUpdateGatewayCapabilityConfigurationRequest.cpp \
    $${PWD}/OAIUpdateGatewayCapabilityConfigurationResponse.cpp \
    $${PWD}/OAIUpdateGatewayCapabilityConfiguration_request.cpp \
    $${PWD}/OAIUpdateGatewayRequest.cpp \
    $${PWD}/OAIUpdateGateway_request.cpp \
    $${PWD}/OAIUpdatePortalRequest.cpp \
    $${PWD}/OAIUpdatePortalResponse.cpp \
    $${PWD}/OAIUpdatePortalResponse_portalStatus.cpp \
    $${PWD}/OAIUpdatePortal_request.cpp \
    $${PWD}/OAIUpdatePortal_request_portalLogoImage.cpp \
    $${PWD}/OAIUpdateProjectRequest.cpp \
    $${PWD}/OAIUpdateProject_request.cpp \
    $${PWD}/OAIUserIdentity.cpp \
    $${PWD}/OAIVariableValue.cpp \
    $${PWD}/OAIVariant.cpp \
# APIs
    $${PWD}/OAIDefaultApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
