openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: ""
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Places API (New)
  version: v1
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://upload.wikimedia.org/wikipedia/commons/e/e1/YouTube_play_buttom_icon_%282013-2017%29.svg
  x-origin:
  - format: google
    url: https://places.googleapis.com/$discovery/rest?version=v1
    version: v1
  x-providerName: googleapis.com
  x-serviceName: places
servers:
- url: https://places.googleapis.com/
tags:
- name: places
paths:
  /v1/places:autocomplete:
    post:
      description: Returns predictions for the given input.
      operationId: places.places.autocomplete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      - Oauth2:
        - https://www.googleapis.com/auth/maps-platform.places
        Oauth2c:
        - https://www.googleapis.com/auth/maps-platform.places
      - Oauth2:
        - https://www.googleapis.com/auth/maps-platform.places.autocomplete
        Oauth2c:
        - https://www.googleapis.com/auth/maps-platform.places.autocomplete
      tags:
      - places
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/places:searchNearby:
    post:
      description: Search for places near locations.
      operationId: places.places.searchNearby
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      - Oauth2:
        - https://www.googleapis.com/auth/maps-platform.places
        Oauth2c:
        - https://www.googleapis.com/auth/maps-platform.places
      - Oauth2:
        - https://www.googleapis.com/auth/maps-platform.places.nearbysearch
        Oauth2c:
        - https://www.googleapis.com/auth/maps-platform.places.nearbysearch
      tags:
      - places
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/places:searchText:
    post:
      description: Text query based place search.
      operationId: places.places.searchText
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      - Oauth2:
        - https://www.googleapis.com/auth/maps-platform.places
        Oauth2c:
        - https://www.googleapis.com/auth/maps-platform.places
      - Oauth2:
        - https://www.googleapis.com/auth/maps-platform.places.textsearch
        Oauth2c:
        - https://www.googleapis.com/auth/maps-platform.places.textsearch
      tags:
      - places
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/{name}:
    get:
      description: Get a photo media with a photo reference string.
      operationId: places.places.photos.getMedia
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      - Oauth2:
        - https://www.googleapis.com/auth/maps-platform.places
        Oauth2c:
        - https://www.googleapis.com/auth/maps-platform.places
      - Oauth2:
        - https://www.googleapis.com/auth/maps-platform.places.details
        Oauth2c:
        - https://www.googleapis.com/auth/maps-platform.places.details
      tags:
      - places
      x-accepts:
      - application/json
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/cloud-platform: "See, edit, configure,\
              \ and delete your Google Cloud data and see the email address for your\
              \ Google Account."
            https://www.googleapis.com/auth/maps-platform.places: "Private Service:\
              \ https://www.googleapis.com/auth/maps-platform.places"
            https://www.googleapis.com/auth/maps-platform.places.autocomplete: "Private\
              \ Service: https://www.googleapis.com/auth/maps-platform.places.autocomplete"
            https://www.googleapis.com/auth/maps-platform.places.details: "Private\
              \ Service: https://www.googleapis.com/auth/maps-platform.places.details"
            https://www.googleapis.com/auth/maps-platform.places.nearbysearch: "Private\
              \ Service: https://www.googleapis.com/auth/maps-platform.places.nearbysearch"
            https://www.googleapis.com/auth/maps-platform.places.textsearch: "Private\
              \ Service: https://www.googleapis.com/auth/maps-platform.places.textsearch"
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/cloud-platform: "See, edit, configure,\
              \ and delete your Google Cloud data and see the email address for your\
              \ Google Account."
            https://www.googleapis.com/auth/maps-platform.places: "Private Service:\
              \ https://www.googleapis.com/auth/maps-platform.places"
            https://www.googleapis.com/auth/maps-platform.places.autocomplete: "Private\
              \ Service: https://www.googleapis.com/auth/maps-platform.places.autocomplete"
            https://www.googleapis.com/auth/maps-platform.places.details: "Private\
              \ Service: https://www.googleapis.com/auth/maps-platform.places.details"
            https://www.googleapis.com/auth/maps-platform.places.nearbysearch: "Private\
              \ Service: https://www.googleapis.com/auth/maps-platform.places.nearbysearch"
            https://www.googleapis.com/auth/maps-platform.places.textsearch: "Private\
              \ Service: https://www.googleapis.com/auth/maps-platform.places.textsearch"
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2

