/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BulkOperationErrorResult from './BulkOperationErrorResult';
import CreatedIssue from './CreatedIssue';

/**
 * The CreatedIssues model module.
 * @module model/CreatedIssues
 * @version 1001.0.0-SNAPSHOT
 */
class CreatedIssues {
    /**
     * Constructs a new <code>CreatedIssues</code>.
     * Details about the issues created and the errors for requests that failed.
     * @alias module:model/CreatedIssues
     */
    constructor() { 
        
        CreatedIssues.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreatedIssues</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreatedIssues} obj Optional instance to populate.
     * @return {module:model/CreatedIssues} The populated <code>CreatedIssues</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreatedIssues();

            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], [BulkOperationErrorResult]);
            }
            if (data.hasOwnProperty('issues')) {
                obj['issues'] = ApiClient.convertToType(data['issues'], [CreatedIssue]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreatedIssues</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreatedIssues</code>.
     */
    static validateJSON(data) {
        if (data['errors']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['errors'])) {
                throw new Error("Expected the field `errors` to be an array in the JSON data but got " + data['errors']);
            }
            // validate the optional field `errors` (array)
            for (const item of data['errors']) {
                BulkOperationErrorResult.validateJSON(item);
            };
        }
        if (data['issues']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['issues'])) {
                throw new Error("Expected the field `issues` to be an array in the JSON data but got " + data['issues']);
            }
            // validate the optional field `issues` (array)
            for (const item of data['issues']) {
                CreatedIssue.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Error details for failed issue creation requests.
 * @member {Array.<module:model/BulkOperationErrorResult>} errors
 */
CreatedIssues.prototype['errors'] = undefined;

/**
 * Details of the issues created.
 * @member {Array.<module:model/CreatedIssue>} issues
 */
CreatedIssues.prototype['issues'] = undefined;






export default CreatedIssues;

