openapi: 3.0.2
info:
  contact:
    url: https://developer.vimeo.com/help
    x-twitter: vimeo
  title: Vimeo
  version: "3.4"
  x-apisguru-categories:
  - entertainment
  x-logo:
    url: https://twitter.com/vimeo/profile_image?size=original
  x-origin:
  - converter:
      url: https://github.com/lucybot/api-spec-converter
      version: 2.7.31
    format: openapi
    url: https://raw.githubusercontent.com/vimeo/openapi/master/api.yaml
    version: "3.0"
  x-providerName: vimeo.com
servers:
- description: Vimeo.com
  url: https://api.vimeo.com
security:
- oauth2:
  - create
  - delete
  - edit
  - email
  - interact
  - private
  - promo_codes
  - public
  - purchase
  - purchased
  - stats
  - upload
  - video_files
tags:
- name: API Information
- name: Albums\Album videos
- name: Albums\Custom album logos
- name: Albums\Custom album thumbnails
- name: Albums\Essentials
- name: Authentication Extras\Essentials
- name: Categories\Channels
- name: Categories\Essentials
- name: Categories\Groups
- name: Categories\Subscriptions
- name: Categories\Videos
- name: Channels\Categories
- name: Channels\Essentials
- name: Channels\Moderators
- name: Channels\Private channel members
- name: Channels\Subscriptions and subscribers
- name: Channels\Tags
- name: Channels\Videos
- name: Embed Presets\Custom Logos
- name: Embed Presets\Essentials
- name: Embed Presets\Videos
- name: Groups\Essentials
- name: Groups\Subscription
- name: Groups\Users
- name: Groups\Videos
- name: Likes\Essentials
- name: On Demand\Backgrounds
- name: On Demand\Essentials
- name: On Demand\Genres
- name: On Demand\Posters
- name: On Demand\Promotions
- name: On Demand\Purchases and Rentals
- name: On Demand\Regions
- name: On Demand\Seasons
- name: On Demand\Videos
- name: Portfolios\Essentials
- name: Portfolios\Videos
- name: Projects\Essentials
- name: Projects\Videos
- name: Tags\Essentials
- name: Users\Essentials
- name: Users\Feed
- name: Users\Follows
- name: Users\Internal
- name: Users\Pictures
- name: Users\Watch History
- name: Videos\Comments
- name: Videos\Content Ratings
- name: Videos\Creative Commons
- name: Videos\Credits
- name: Videos\Embed Privacy
- name: Videos\Essentials
- name: Videos\Languages
- name: Videos\Recommendations
- name: Videos\Tags
- name: Videos\Text Tracks
- name: Videos\Thumbnails
- name: Videos\Upload
- name: Videos\Versions
- name: Videos\Viewing Privacy
- name: Watch Later Queue\Essentials
paths:
  /:
    get:
      operationId: get_endpoints
      summary: Get an API specification
      tags:
      - API Information
      x-accepts:
      - application/vnd.vimeo.endpoint+json
  /categories:
    get:
      description: This method gets all existing categories.
      operationId: get_categories
      summary: Get all categories
      tags:
      - Categories\Essentials
      x-accepts:
      - application/vnd.vimeo.category+json
  /categories/{category}:
    get:
      operationId: get_category
      summary: Get a specific category
      tags:
      - Categories\Essentials
      x-accepts:
      - application/vnd.vimeo.category+json
  /categories/{category}/channels:
    get:
      operationId: get_category_channels
      summary: Get all the channels in a category
      tags:
      - Categories\Channels
      x-accepts:
      - application/vnd.vimeo.channel+json
  /categories/{category}/groups:
    get:
      operationId: get_category_groups
      summary: Get all the groups in a category
      tags:
      - Categories\Groups
      x-accepts:
      - application/vnd.vimeo.group+json
  /categories/{category}/videos:
    get:
      operationId: get_category_videos
      summary: Get all the videos in a category
      tags:
      - Categories\Videos
      x-accepts:
      - application/vnd.vimeo.video+json
  /categories/{category}/videos/{video_id}:
    get:
      operationId: check_category_for_video
      summary: Check for a video in a category
      tags:
      - Categories\Videos
      x-accepts:
      - application/vnd.vimeo.video+json
  /channels:
    get:
      operationId: get_channels
      summary: Get all channels
      tags:
      - Channels\Essentials
      x-accepts:
      - application/vnd.vimeo.channel+json
    post:
      description: This method creates a new channel.
      operationId: create_channel
      security:
      - oauth2:
        - create
      summary: Create a channel
      tags:
      - Channels\Essentials
      x-content-type: application/vnd.vimeo.channel+json
      x-accepts:
      - application/vnd.vimeo.channel+json
  /channels/{channel_id}:
    delete:
      operationId: delete_channel
      security:
      - oauth2:
        - delete
      summary: Delete a channel
      tags:
      - Channels\Essentials
      x-accepts:
      - application/json
    get:
      operationId: get_channel
      summary: Get a specific channel
      tags:
      - Channels\Essentials
      x-accepts:
      - application/vnd.vimeo.channel+json
    patch:
      description: This method edits the specified channel.
      operationId: edit_channel
      security:
      - oauth2:
        - edit
      summary: Edit a channel
      tags:
      - Channels\Essentials
      x-content-type: application/vnd.vimeo.channel+json
      x-accepts:
      - application/vnd.vimeo.channel+json
  /channels/{channel_id}/categories:
    get:
      description: This method gets all the categories in the specified channel.
      operationId: get_channel_categories
      summary: Get all the categories in a channel
      tags:
      - Channels\Categories
      x-accepts:
      - application/vnd.vimeo.category+json
    put:
      description: This method adds multiple categories to the specified channel.
      operationId: add_channel_categories
      summary: Add a list of categories to a channel
      tags:
      - Channels\Categories
      x-content-type: application/json
      x-accepts:
      - application/json
  /channels/{channel_id}/categories/{category}:
    delete:
      description: This method removes a single category from the specified channel.
      operationId: delete_channel_category
      security:
      - oauth2:
        - edit
      summary: Remove a category from a channel
      tags:
      - Channels\Categories
      x-accepts:
      - application/vnd.vimeo.category+json
    put:
      description: This method adds a channel to a category.
      operationId: categorize_channel
      security:
      - oauth2:
        - edit
      summary: Categorize a channel
      tags:
      - Channels\Categories
      x-accepts:
      - application/vnd.vimeo.category+json
  /channels/{channel_id}/moderators:
    delete:
      operationId: remove_channel_moderators
      security:
      - oauth2:
        - edit
      summary: Remove a list of channel moderators
      tags:
      - Channels\Moderators
      x-content-type: application/vnd.vimeo.user+json
      x-accepts:
      - application/vnd.vimeo.user+json
    get:
      operationId: get_channel_moderators
      summary: Get all the moderators in a channel
      tags:
      - Channels\Moderators
      x-accepts:
      - application/vnd.vimeo.user+json
    patch:
      operationId: replace_channel_moderators
      security:
      - oauth2:
        - edit
      summary: Replace the moderators of a channel
      tags:
      - Channels\Moderators
      x-content-type: application/json
      x-accepts:
      - application/json
    put:
      operationId: add_channel_moderators
      security:
      - oauth2:
        - edit
      summary: Add a list of channel moderators
      tags:
      - Channels\Moderators
      x-content-type: application/json
      x-accepts:
      - application/json
  /channels/{channel_id}/moderators/{user_id}:
    delete:
      operationId: remove_channel_moderator
      security:
      - oauth2:
        - edit
      summary: Remove a specific channel moderator
      tags:
      - Channels\Moderators
      x-accepts:
      - application/vnd.vimeo.user+json
    get:
      operationId: get_channel_moderator
      summary: Get a specific channel moderator
      tags:
      - Channels\Moderators
      x-accepts:
      - application/vnd.vimeo.user+json
    put:
      operationId: add_channel_moderator
      security:
      - oauth2:
        - edit
      summary: Add a specific channel moderator
      tags:
      - Channels\Moderators
      x-accepts:
      - application/vnd.vimeo.user+json
  /channels/{channel_id}/privacy/users:
    get:
      description: This method gets all the users who have access to the specified
        private channel.
      operationId: get_channel_privacy_users
      summary: Get all the users who can view a private channel
      tags:
      - Channels\Private channel members
      x-accepts:
      - application/vnd.vimeo.user+json
    put:
      description: This method gives multiple users access to the specified private
        channel.
      operationId: set_channel_privacy_users
      security:
      - oauth2:
        - edit
      summary: Permit a list of users to view a private channel
      tags:
      - Channels\Private channel members
      x-content-type: application/vnd.vimeo.user+json
      x-accepts:
      - application/vnd.vimeo.user+json
  /channels/{channel_id}/privacy/users/{user_id}:
    delete:
      description: This method prevents a single user from being able to access the
        specified private channel.
      operationId: delete_channel_privacy_user
      security:
      - oauth2:
        - edit
      summary: Restrict a user from viewing a private channel
      tags:
      - Channels\Private channel members
      x-accepts:
      - application/json
    put:
      description: This method gives a single user access to the specified private
        channel.
      operationId: set_channel_privacy_user
      security:
      - oauth2:
        - edit
      summary: Permit a specific user to view a private channel
      tags:
      - Channels\Private channel members
      x-accepts:
      - application/json
  /channels/{channel_id}/tags:
    get:
      description: This method gets all the tags that have been added to the specified
        channel.
      operationId: get_channel_tags
      summary: Get all the tags that have been added to a channel
      tags:
      - Channels\Tags
      x-accepts:
      - application/vnd.vimeo.tag+json
    put:
      description: This method adds multiple tags to the specified channel.
      operationId: add_tags_to_channel
      security:
      - oauth2:
        - edit
      summary: Add a list of tags to a channel
      tags:
      - Channels\Tags
      x-content-type: application/vnd.vimeo.tag+json
      x-accepts:
      - application/vnd.vimeo.tag+json
  /channels/{channel_id}/tags/{word}:
    delete:
      description: This method removes a single tag from the specified channel.
      operationId: delete_tag_from_channel
      security:
      - oauth2:
        - edit
      summary: Remove a tag from a channel
      tags:
      - Channels\Tags
      x-accepts:
      - application/vnd.vimeo.tag+json
    get:
      description: This method determines whether a specific tag has been added to
        the channel in question.
      operationId: check_if_channel_has_tag
      summary: Check if a tag has been added to a channel
      tags:
      - Channels\Tags
      x-accepts:
      - application/vnd.vimeo.tag+json
    put:
      description: This method adds a single tag to the specified channel.
      operationId: add_channel_tag
      security:
      - oauth2:
        - edit
      summary: Add a specific tag to a channel
      tags:
      - Channels\Tags
      x-accepts:
      - application/vnd.vimeo.tag+json
  /channels/{channel_id}/users:
    get:
      operationId: get_channel_subscribers
      summary: Get all the followers of a channel
      tags:
      - Channels\Subscriptions and subscribers
      x-accepts:
      - application/vnd.vimeo.user+json
  /channels/{channel_id}/videos:
    delete:
      operationId: remove_videos_from_channel
      security:
      - oauth2:
        - edit
      summary: Remove a list of videos from a channel
      tags:
      - Channels\Videos
      x-content-type: application/json
      x-accepts:
      - application/json
    get:
      operationId: get_channel_videos
      summary: Get all the videos in a channel
      tags:
      - Channels\Videos
      x-accepts:
      - application/vnd.vimeo.video+json
    put:
      operationId: add_videos_to_channel
      security:
      - oauth2:
        - edit
      summary: Add a list of videos to a channel
      tags:
      - Channels\Videos
      x-content-type: application/json
      x-accepts:
      - application/json
  /channels/{channel_id}/videos/{video_id}:
    delete:
      operationId: delete_video_from_channel
      security:
      - oauth2:
        - edit
      summary: Remove a specific video from a channel
      tags:
      - Channels\Videos
      x-accepts:
      - application/json
    get:
      description: This method returns a specific video in a channel. You can use
        it to determine whether the video is in the channel.
      operationId: get_channel_video
      summary: Get a specific video in a channel
      tags:
      - Channels\Videos
      x-accepts:
      - application/vnd.vimeo.video+json
    put:
      operationId: add_video_to_channel
      security:
      - oauth2:
        - edit
      summary: Add a specific video to a channel
      tags:
      - Channels\Videos
      x-accepts:
      - application/json
  /channels/{channel_id}/videos/{video_id}/comments:
    get:
      operationId: get_comments_alt1
      summary: Get all the comments on a video
      tags:
      - Videos\Comments
      x-accepts:
      - application/vnd.vimeo.comment+json
    post:
      operationId: create_comment_alt1
      security:
      - oauth2:
        - interact
      summary: Add a comment to a video
      tags:
      - Videos\Comments
      x-content-type: application/vnd.vimeo.comment+json
      x-accepts:
      - application/vnd.vimeo.comment+json
  /channels/{channel_id}/videos/{video_id}/credits:
    get:
      operationId: get_video_credits_alt1
      summary: Get all the credited users in a video
      tags:
      - Videos\Credits
      x-accepts:
      - application/vnd.vimeo.credit+json
    post:
      operationId: add_video_credit_alt1
      summary: Credit a user in a video
      tags:
      - Videos\Credits
      x-content-type: application/vnd.vimeo.credit+json
      x-accepts:
      - application/vnd.vimeo.credit+json
  /channels/{channel_id}/videos/{video_id}/likes:
    get:
      operationId: get_video_likes_alt1
      summary: Get all the users who have liked a video
      tags:
      - Likes\Essentials
      x-accepts:
      - application/vnd.vimeo.user+json
  /channels/{channel_id}/videos/{video_id}/pictures:
    get:
      operationId: get_video_thumbnails_alt1
      summary: Get all the thumbnails of a video
      tags:
      - Videos\Thumbnails
      x-accepts:
      - application/vnd.vimeo.picture+json
    post:
      operationId: create_video_thumbnail_alt1
      security:
      - oauth2:
        - upload
      summary: Add a video thumbnail
      tags:
      - Videos\Thumbnails
      x-content-type: application/vnd.vimeo.picture+json
      x-accepts:
      - application/vnd.vimeo.picture+json
  /channels/{channel_id}/videos/{video_id}/privacy/users:
    get:
      operationId: get_video_privacy_users_alt1
      summary: Get all the users who can view a user's private videos by default
      tags:
      - Videos\Viewing Privacy
      x-accepts:
      - application/vnd.vimeo.user+json
    put:
      description: |-
        The body of this request should follow our
        [batch request format](https://developer.vimeo.com/api/common-formats#batch-requests). Each object must contain
        a single `URI` field, and the value of this field must be the URI of the user who can view this video.
      operationId: add_video_privacy_users_alt1
      security:
      - oauth2:
        - edit
      summary: Permit a list of users to view a private video
      tags:
      - Videos\Viewing Privacy
      x-accepts:
      - application/vnd.vimeo.user+json
  /channels/{channel_id}/videos/{video_id}/texttracks:
    get:
      operationId: get_text_tracks_alt1
      summary: Get all the text tracks of a video
      tags:
      - Videos\Text Tracks
      x-accepts:
      - application/vnd.vimeo.video.texttrack+json
    post:
      description: "For additional information, see our [text track upload guide](https://developer.vimeo.com/api/upload/texttracks)."
      operationId: create_text_track_alt1
      security:
      - oauth2:
        - upload
      summary: Add a text track to a video
      tags:
      - Videos\Text Tracks
      x-content-type: application/vnd.vimeo.video.texttrack+json
      x-accepts:
      - application/vnd.vimeo.video.texttrack+json
  /contentratings:
    get:
      operationId: get_content_ratings
      summary: Get all content ratings
      tags:
      - Videos\Content Ratings
      x-accepts:
      - application/vnd.vimeo.contentrating+json
  /creativecommons:
    get:
      operationId: get_cc_licenses
      summary: Get all Creative Commons licenses
      tags:
      - Videos\Creative Commons
      x-accepts:
      - application/vnd.vimeo.creativecommons+json
  /groups:
    get:
      operationId: get_groups
      summary: Get all groups
      tags:
      - Groups\Essentials
      x-accepts:
      - application/vnd.vimeo.group+json
    post:
      operationId: create_group
      security:
      - oauth2:
        - create
      summary: Create a group
      tags:
      - Groups\Essentials
      x-content-type: application/vnd.vimeo.group+json
      x-accepts:
      - application/vnd.vimeo.group+json
  /groups/{group_id}:
    delete:
      operationId: delete_group
      security:
      - oauth2:
        - delete
      summary: Delete a group
      tags:
      - Groups\Essentials
      x-accepts:
      - application/json
    get:
      operationId: get_group
      summary: Get a specific group
      tags:
      - Groups\Essentials
      x-accepts:
      - application/vnd.vimeo.group+json
  /groups/{group_id}/users:
    get:
      operationId: get_group_members
      summary: Get all the members of a group
      tags:
      - Groups\Users
      x-accepts:
      - application/vnd.vimeo.user+json
  /groups/{group_id}/videos:
    get:
      operationId: get_group_videos
      summary: Get all the videos in a group
      tags:
      - Groups\Videos
      x-accepts:
      - application/vnd.vimeo.video+json
  /groups/{group_id}/videos/{video_id}:
    delete:
      operationId: delete_video_from_group
      security:
      - oauth2:
        - edit
      summary: Remove a video from a group
      tags:
      - Groups\Videos
      x-accepts:
      - application/json
    get:
      description: Check if a group has a video.
      operationId: get_group_video
      summary: Get a specific video in a group
      tags:
      - Groups\Videos
      x-accepts:
      - application/vnd.vimeo.video+json
    put:
      operationId: add_video_to_group
      security:
      - oauth2:
        - edit
      summary: Add a video to a group
      tags:
      - Groups\Videos
      x-accepts:
      - application/vnd.vimeo.video+json
  /languages:
    get:
      operationId: get_languages
      summary: Get all languages
      tags:
      - Videos\Languages
      x-accepts:
      - application/vnd.vimeo.language+json
  /me:
    get:
      operationId: get_user_alt1
      summary: Get a user
      tags:
      - Users\Essentials
      x-accepts:
      - application/vnd.vimeo.user+json
    patch:
      operationId: edit_user_alt1
      summary: Edit a user
      tags:
      - Users\Essentials
      x-content-type: application/vnd.vimeo.user+json
      x-accepts:
      - application/vnd.vimeo.user+json
  /me/albums:
    get:
      operationId: get_albums_alt1
      summary: Get all the albums that belong to a user
      tags:
      - Albums\Essentials
      x-accepts:
      - application/json
    post:
      operationId: create_album_alt1
      security:
      - oauth2:
        - create
      summary: Create an album
      tags:
      - Albums\Essentials
      x-content-type: application/vnd.vimeo.album+json
      x-accepts:
      - application/vnd.vimeo.album+json
  /me/albums/{album_id}:
    delete:
      operationId: delete_album_alt1
      security:
      - oauth2:
        - delete
      summary: Delete an album
      tags:
      - Albums\Essentials
      x-accepts:
      - application/json
    get:
      operationId: get_album_alt1
      summary: Get a specific album
      tags:
      - Albums\Essentials
      x-accepts:
      - application/vnd.vimeo.album+json
    patch:
      operationId: edit_album_alt1
      security:
      - oauth2:
        - edit
      summary: Edit an album
      tags:
      - Albums\Essentials
      x-content-type: application/vnd.vimeo.album+json
      x-accepts:
      - application/vnd.vimeo.album+json
  /me/albums/{album_id}/videos:
    get:
      operationId: get_album_videos_alt1
      summary: Get all the videos in an album
      tags:
      - Albums\Album videos
      x-accepts:
      - application/vnd.vimeo.video+json
    put:
      description: This method replaces all the existing videos in an album with one
        or more videos.
      operationId: replace_videos_in_album_alt1
      security:
      - oauth2:
        - edit
      summary: Replace all the videos in an album
      tags:
      - Albums\Album videos
      x-content-type: application/json
      x-accepts:
      - application/json
  /me/albums/{album_id}/videos/{video_id}:
    delete:
      operationId: remove_video_from_album_alt1
      security:
      - oauth2:
        - edit
      summary: Remove a video from an album
      tags:
      - Albums\Album videos
      x-accepts:
      - application/json
    get:
      description: This method gets a single video from an album. You can use this
        method to determine whether the album contains the specified video.
      operationId: get_album_video_alt1
      summary: Get a specific video in an album
      tags:
      - Albums\Album videos
      x-accepts:
      - application/vnd.vimeo.video+json
    put:
      operationId: add_video_to_album_alt1
      security:
      - oauth2:
        - edit
      summary: Add a specific video to an album
      tags:
      - Albums\Album videos
      x-accepts:
      - application/json
  /me/albums/{album_id}/videos/{video_id}/set_album_thumbnail:
    post:
      operationId: set_video_as_album_thumbnail_alt1
      security:
      - oauth2:
        - edit
      summary: Set a video as the album thumbnail
      tags:
      - Albums\Album videos
      x-content-type: application/json
      x-accepts:
      - application/json
  /me/appearances:
    get:
      operationId: get_appearances_alt1
      summary: Get all the videos in which a user appears
      tags:
      - Videos\Essentials
      x-accepts:
      - application/vnd.vimeo.video+json
  /me/categories:
    get:
      operationId: get_category_subscriptions_alt1
      security:
      - oauth2:
        - private
      summary: Get all the categories that a user follows
      tags:
      - Categories\Subscriptions
      x-accepts:
      - application/vnd.vimeo.category+json
  /me/categories/{category}:
    delete:
      operationId: unsubscribe_from_category_alt1
      security:
      - oauth2:
        - interact
      summary: Unsubscribe a user from a category
      tags:
      - Categories\Subscriptions
      x-accepts:
      - application/json
    get:
      operationId: check_if_user_subscribed_to_category_alt1
      security:
      - oauth2:
        - private
      summary: Check if a user follows a category
      tags:
      - Categories\Subscriptions
      x-accepts:
      - application/json
    put:
      operationId: subscribe_to_category_alt1
      security:
      - oauth2:
        - interact
      summary: Subscribe a user to a single category
      tags:
      - Categories\Subscriptions
      x-accepts:
      - application/json
  /me/channels:
    get:
      operationId: get_channel_subscriptions_alt1
      summary: Get all the channels to which a user subscribes
      tags:
      - Channels\Essentials
      x-accepts:
      - application/vnd.vimeo.channel+json
  /me/channels/{channel_id}:
    delete:
      operationId: unsubscribe_from_channel_alt1
      security:
      - oauth2:
        - interact
      summary: Unsubscribe a user from a specific channel
      tags:
      - Channels\Subscriptions and subscribers
      x-accepts:
      - application/json
    get:
      operationId: check_if_user_subscribed_to_channel_alt1
      summary: Check if a user follows a channel
      tags:
      - Channels\Subscriptions and subscribers
      x-accepts:
      - application/json
    put:
      operationId: subscribe_to_channel_alt1
      security:
      - oauth2:
        - interact
      summary: Subscribe a user to a specific channel
      tags:
      - Channels\Subscriptions and subscribers
      x-accepts:
      - application/json
  /me/customlogos:
    get:
      operationId: get_custom_logos_alt1
      summary: Get all the custom logos that belong to a user
      tags:
      - Embed Presets\Custom Logos
      x-accepts:
      - application/vnd.vimeo.picture+json
    post:
      operationId: create_custom_logo_alt1
      security:
      - oauth2:
        - upload
      summary: Add a custom logo
      tags:
      - Embed Presets\Custom Logos
      x-accepts:
      - application/vnd.vimeo.picture+json
  /me/customlogos/{logo_id}:
    get:
      operationId: get_custom_logo_alt1
      summary: Get a specific custom logo
      tags:
      - Embed Presets\Custom Logos
      x-accepts:
      - application/vnd.vimeo.picture+json
  /me/feed:
    get:
      operationId: get_feed_alt1
      security:
      - oauth2:
        - private
      summary: Get all videos in a user's feed
      tags:
      - Users\Feed
      x-accepts:
      - application/vnd.vimeo.activity+json
  /me/followers:
    get:
      operationId: get_followers_alt1
      summary: Get all the followers of a user
      tags:
      - Users\Follows
      x-accepts:
      - application/vnd.vimeo.user+json
  /me/following:
    get:
      operationId: get_user_following_alt1
      summary: Get all the users that a user is following
      tags:
      - Users\Follows
      x-accepts:
      - application/vnd.vimeo.user+json
    post:
      operationId: follow_users_alt1
      security:
      - oauth2:
        - interact
      summary: Follow a list of users
      tags:
      - Users\Follows
      x-content-type: application/json
      x-accepts:
      - application/json
  /me/following/{follow_user_id}:
    delete:
      operationId: unfollow_user_alt1
      security:
      - oauth2:
        - interact
      summary: Unfollow a user
      tags:
      - Users\Follows
      x-accepts:
      - application/json
    get:
      operationId: check_if_user_is_following_alt1
      summary: Check if a user is following another user
      tags:
      - Users\Follows
      x-accepts:
      - application/json
    put:
      operationId: follow_user_alt1
      security:
      - oauth2:
        - interact
      summary: Follow a specific user
      tags:
      - Users\Follows
      x-accepts:
      - application/json
  /me/groups:
    get:
      operationId: get_user_groups_alt1
      summary: Get all the groups that a user has joined
      tags:
      - Groups\Users
      x-accepts:
      - application/vnd.vimeo.group+json
  /me/groups/{group_id}:
    delete:
      operationId: leave_group_alt1
      security:
      - oauth2:
        - interact
      summary: Remove a user from a group
      tags:
      - Groups\Subscription
      x-accepts:
      - application/json
    get:
      operationId: check_if_user_joined_group_alt1
      summary: Check if a user has joined a group
      tags:
      - Groups\Users
      x-accepts:
      - application/json
    put:
      operationId: join_group_alt1
      security:
      - oauth2:
        - interact
      summary: Add a user to a group
      tags:
      - Groups\Subscription
      x-accepts:
      - application/json
  /me/likes:
    get:
      operationId: get_likes_alt1
      summary: Get all the videos that a user has liked
      tags:
      - Likes\Essentials
      x-accepts:
      - application/vnd.vimeo.video+json
  /me/likes/{video_id}:
    delete:
      operationId: unlike_video_alt1
      security:
      - oauth2:
        - interact
      summary: Cause a user to unlike a video
      tags:
      - Likes\Essentials
      x-accepts:
      - application/json
    get:
      operationId: check_if_user_liked_video_alt1
      summary: Check if a user has liked a video
      tags:
      - Likes\Essentials
      x-accepts:
      - application/json
    put:
      operationId: like_video_alt1
      security:
      - oauth2:
        - interact
      summary: Cause a user to like a video
      tags:
      - Likes\Essentials
      x-accepts:
      - application/json
  /me/ondemand/pages:
    get:
      operationId: get_user_vods_alt1
      summary: Get all the On Demand pages of a user
      tags:
      - On Demand\Essentials
      x-accepts:
      - application/vnd.vimeo.ondemand.page+json
    post:
      operationId: create_vod_alt1
      summary: Create an On Demand page
      tags:
      - On Demand\Essentials
      x-content-type: application/json
      x-accepts:
      - application/json
  /me/ondemand/purchases:
    get:
      operationId: get_vod_purchases
      security:
      - oauth2:
        - purchased
      summary: Get all the On Demand purchases and rentals that a user has made
      tags:
      - On Demand\Purchases and Rentals
      x-accepts:
      - application/vnd.vimeo.ondemand.page+json
  /me/ondemand/purchases/{ondemand_id}:
    get:
      operationId: check_if_vod_was_purchased_alt1
      security:
      - oauth2:
        - purchased
      summary: Check if a user has made a purchase or rental from an On Demand page
      tags:
      - On Demand\Purchases and Rentals
      x-accepts:
      - application/vnd.vimeo.ondemand.page+json
  /me/pictures:
    get:
      operationId: get_pictures_alt1
      summary: Get all the pictures that belong to a user
      tags:
      - Users\Pictures
      x-accepts:
      - application/vnd.vimeo.picture+json
    post:
      operationId: create_picture_alt1
      security:
      - oauth2:
        - upload
      summary: Add a user picture
      tags:
      - Users\Pictures
      x-accepts:
      - application/vnd.vimeo.picture+json
  /me/pictures/{portraitset_id}:
    delete:
      operationId: delete_picture_alt1
      security:
      - oauth2:
        - delete
      summary: Delete a user picture
      tags:
      - Users\Pictures
      x-accepts:
      - application/json
    get:
      operationId: get_picture_alt1
      summary: Get a specific user picture
      tags:
      - Users\Pictures
      x-accepts:
      - application/vnd.vimeo.picture+json
    patch:
      operationId: edit_picture_alt1
      security:
      - oauth2:
        - edit
      summary: Edit a user picture
      tags:
      - Users\Pictures
      x-content-type: application/vnd.vimeo.picture+json
      x-accepts:
      - application/vnd.vimeo.picture+json
  /me/portfolios:
    get:
      operationId: get_portfolios_alt1
      summary: Get all the portfolios that belong to a user
      tags:
      - Portfolios\Essentials
      x-accepts:
      - application/vnd.vimeo.portfolio+json
  /me/portfolios/{portfolio_id}:
    get:
      operationId: get_portfolio_alt1
      summary: Get a specific portfolio
      tags:
      - Portfolios\Essentials
      x-accepts:
      - application/vnd.vimeo.portfolio+json
  /me/portfolios/{portfolio_id}/videos:
    get:
      operationId: get_portfolio_videos_alt1
      summary: Get all the videos in a portfolio
      tags:
      - Portfolios\Videos
      x-accepts:
      - application/vnd.vimeo.video+json
  /me/portfolios/{portfolio_id}/videos/{video_id}:
    delete:
      operationId: delete_video_from_portfolio_alt1
      security:
      - oauth2:
        - edit
      summary: Remove a video from a portfolio
      tags:
      - Portfolios\Videos
      x-accepts:
      - application/json
    get:
      operationId: get_portfolio_video_alt1
      summary: Get a specific video in a portfolio
      tags:
      - Portfolios\Videos
      x-accepts:
      - application/vnd.vimeo.video+json
    put:
      operationId: add_video_to_portfolio_alt1
      security:
      - oauth2:
        - edit
      summary: Add a video to a portfolio
      tags:
      - Portfolios\Videos
      x-accepts:
      - application/json
  /me/presets:
    get:
      operationId: get_embed_presets_alt1
      summary: Get all the embed presets that a user has created
      tags:
      - Embed Presets\Essentials
      x-accepts:
      - application/vnd.vimeo.preset+json
  /me/presets/{preset_id}:
    get:
      operationId: get_embed_preset_alt1
      summary: Get a specific embed preset
      tags:
      - Embed Presets\Essentials
      x-accepts:
      - application/vnd.vimeo.preset+json
    patch:
      operationId: edit_embed_preset_alt1
      summary: Edit an embed preset
      tags:
      - Embed Presets\Essentials
      x-content-type: application/vnd.vimeo.preset+json
      x-accepts:
      - application/vnd.vimeo.preset+json
  /me/presets/{preset_id}/videos:
    get:
      operationId: get_embed_preset_videos_alt1
      summary: Get all the videos that have been added to an embed preset
      tags:
      - Embed Presets\Videos
      x-accepts:
      - application/vnd.vimeo.video+json
  /me/projects:
    get:
      description: This method gets all the projects that belong to the specified
        user.
      operationId: get_projects_alt1
      security:
      - oauth2:
        - private
      summary: Get all the projects that belong to a user
      tags:
      - Projects\Essentials
      x-accepts:
      - application/json
    post:
      description: This method creates a new project for the specified user.
      operationId: create_project_alt1
      security:
      - oauth2:
        - create
      summary: Create a project
      tags:
      - Projects\Essentials
      x-content-type: application/json
      x-accepts:
      - application/json
  /me/projects/{project_id}:
    delete:
      description: This method deletes a project and optionally also the videos that
        it contains.
      operationId: delete_project_alt1
      security:
      - oauth2:
        - delete
      summary: Delete a project
      tags:
      - Projects\Essentials
      x-accepts:
      - application/json
    get:
      description: This method gets a single project that belongs to the specified
        user.
      operationId: get_project_alt1
      security:
      - oauth2:
        - private
      summary: Get a specific project
      tags:
      - Projects\Essentials
      x-accepts:
      - application/json
    patch:
      description: This method edits an existing project.
      operationId: edit_project_alt1
      security:
      - oauth2:
        - edit
      summary: Edit a project
      tags:
      - Projects\Essentials
      x-content-type: application/json
      x-accepts:
      - application/json
  /me/projects/{project_id}/videos:
    delete:
      description: This method removed multiple videos from the specified project.
      operationId: remove_videos_from_project_alt1
      security:
      - oauth2:
        - interact
      summary: Remove a list of videos from a project
      tags:
      - Projects\Videos
      x-accepts:
      - application/json
    get:
      description: This method gets all the videos that belong to the specified project.
      operationId: get_project_videos_alt1
      security:
      - oauth2:
        - private
      summary: Get all the videos in a project
      tags:
      - Projects\Videos
      x-accepts:
      - application/json
    put:
      description: This method adds multiple videos to the specified project.
      operationId: add_videos_to_project_alt1
      security:
      - oauth2:
        - interact
      summary: Add a list of videos to a project
      tags:
      - Projects\Videos
      x-accepts:
      - application/json
  /me/projects/{project_id}/videos/{video_id}:
    delete:
      description: This method removes a single video from the specified project.
      operationId: remove_video_from_project_alt1
      security:
      - oauth2:
        - delete
      summary: Remove a specific video from a project
      tags:
      - Projects\Videos
      x-accepts:
      - application/json
    put:
      description: This method adds a single video to the specified project.
      operationId: add_video_to_project_alt1
      security:
      - oauth2:
        - interact
      summary: Add a specific video to a project
      tags:
      - Projects\Videos
      x-accepts:
      - application/json
  /me/videos:
    get:
      operationId: get_videos_alt1
      summary: Get all the videos that a user has uploaded
      tags:
      - Videos\Essentials
      x-accepts:
      - application/vnd.vimeo.video+json
    post:
      description: "Begin the video upload process. For more information, see our\
        \ [upload documentation](https://developer.vimeo.com/api/upload/videos)."
      operationId: upload_video_alt1
      summary: Upload a video
      tags:
      - Videos\Upload
      x-content-type: application/vnd.vimeo.video+json
      x-accepts:
      - application/vnd.vimeo.video+json
  /me/videos/{video_id}:
    get:
      operationId: check_if_user_owns_video_alt1
      summary: Check if a user owns a video
      tags:
      - Videos\Essentials
      x-accepts:
      - application/vnd.vimeo.video+json
  /me/watched/videos:
    delete:
      operationId: delete_watch_history
      security:
      - oauth2:
        - delete
      summary: Delete a user's watch history
      tags:
      - Users\Watch History
      x-accepts:
      - application/json
    get:
      operationId: get_watch_history
      security:
      - oauth2:
        - private
      summary: Get all the videos that a user has watched
      tags:
      - Users\Watch History
      x-accepts:
      - application/vnd.vimeo.video+json
  /me/watched/videos/{video_id}:
    delete:
      operationId: delete_from_watch_history
      security:
      - oauth2:
        - delete
      summary: Delete a specific video from a user's watch history
      tags:
      - Users\Watch History
      x-accepts:
      - application/json
  /me/watchlater:
    get:
      operationId: get_watch_later_queue_alt1
      security:
      - oauth2:
        - private
      summary: Get all the videos in a user's Watch Later queue
      tags:
      - Watch Later Queue\Essentials
      x-accepts:
      - application/vnd.vimeo.video+json
  /me/watchlater/{video_id}:
    delete:
      operationId: delete_video_from_watch_later_alt1
      security:
      - oauth2:
        - interact
      summary: Remove a video from a user's Watch Later queue
      tags:
      - Watch Later Queue\Essentials
      x-accepts:
      - application/json
    get:
      operationId: check_watch_later_queue_alt1
      security:
      - oauth2:
        - private
      summary: Check if a user has added a specific video to their Watch Later queue
      tags:
      - Watch Later Queue\Essentials
      x-accepts:
      - application/vnd.vimeo.video+json
    put:
      operationId: add_video_to_watch_later_alt1
      security:
      - oauth2:
        - interact
      summary: Add a video to a user's Watch Later queue
      tags:
      - Watch Later Queue\Essentials
      x-accepts:
      - application/json
  /oauth/access_token:
    post:
      operationId: exchange_auth_code
      summary: Exchange an authorization code for an access token
      tags:
      - Authentication Extras\Essentials
      x-content-type: application/vnd.vimeo.auth+json
      x-accepts:
      - application/vnd.vimeo.auth+json
  /oauth/authorize/client:
    post:
      description: |-
        For information on utilizing OAuth client authorization, see our
        [authentication](/api/authentication#generate-unauthenticated-tokens) documentation or the
        [Client Credentials Grant](https://tools.ietf.org/html/draft-ietf-oauth-v2-31#section-4.4) section of the
        [OAuth spec](https://tools.ietf.org/html/draft-ietf-oauth-v2-31.
      operationId: client_auth
      summary: Authorize a client with OAuth
      tags:
      - Authentication Extras\Essentials
      x-content-type: application/vnd.vimeo.auth+json
      x-accepts:
      - application/vnd.vimeo.auth+json
  /oauth/authorize/vimeo_oauth1:
    post:
      operationId: convert_access_token
      summary: Convert OAuth 1 access tokens to OAuth 2 access tokens
      tags:
      - Authentication Extras\Essentials
      x-content-type: application/vnd.vimeo.auth+json
      x-accepts:
      - application/vnd.vimeo.auth+json
  /oauth/verify:
    get:
      operationId: verify_token
      summary: Verify an OAuth 2 token
      tags:
      - Authentication Extras\Essentials
      x-accepts:
      - application/vnd.vimeo.auth+json
  /ondemand/genres:
    get:
      operationId: get_vod_genres
      summary: Get all On Demand genres
      tags:
      - On Demand\Genres
      x-accepts:
      - application/vnd.vimeo.ondemand.genre+json
  /ondemand/genres/{genre_id}:
    get:
      operationId: get_vod_genre
      summary: Get a specific On Demand genre
      tags:
      - On Demand\Genres
      x-accepts:
      - application/vnd.vimeo.ondemand.genre+json
  /ondemand/genres/{genre_id}/pages:
    get:
      operationId: get_genre_vods
      summary: Get all the On Demand pages in a genre
      tags:
      - On Demand\Genres
      x-accepts:
      - application/vnd.vimeo.ondemand.page+json
  /ondemand/genres/{genre_id}/pages/{ondemand_id}:
    get:
      description: Check whether a genre contains an On Demand page.
      operationId: get_genre_vod
      summary: Get a specific On Demand page in a genre
      tags:
      - On Demand\Genres
      x-accepts:
      - application/vnd.vimeo.ondemand.page+json
  /ondemand/pages/{ondemand_id}:
    delete:
      operationId: delete_vod_draft
      security:
      - oauth2:
        - delete
      summary: Delete a draft of an On Demand page
      tags:
      - On Demand\Essentials
      x-accepts:
      - application/vnd.vimeo.ondemand.page+json
    get:
      operationId: get_vod
      summary: Get a specific On Demand page
      tags:
      - On Demand\Essentials
      x-accepts:
      - application/vnd.vimeo.ondemand.page+json
    patch:
      description: Enable preorders or publish the page.
      operationId: edit_vod
      security:
      - oauth2:
        - edit
      summary: Edit an On Demand page
      tags:
      - On Demand\Essentials
      x-content-type: application/vnd.vimeo.ondemand.page+json
      x-accepts:
      - application/vnd.vimeo.ondemand.page+json
  /ondemand/pages/{ondemand_id}/backgrounds:
    get:
      operationId: get_vod_backgrounds
      summary: Get all the backgrounds of an On Demand page
      tags:
      - On Demand\Backgrounds
      x-accepts:
      - application/vnd.vimeo.picture+json
    post:
      operationId: create_vod_background
      security:
      - oauth2:
        - upload
      summary: Add a background to an On Demand page
      tags:
      - On Demand\Backgrounds
      x-accepts:
      - application/vnd.vimeo.picture+json
  /ondemand/pages/{ondemand_id}/backgrounds/{background_id}:
    delete:
      operationId: delete_vod_background
      security:
      - oauth2:
        - edit
      summary: Remove a background from an On Demand page
      tags:
      - On Demand\Backgrounds
      x-accepts:
      - application/vnd.vimeo.picture+json
    get:
      operationId: get_vod_background
      summary: Get a specific background of an On Demand page
      tags:
      - On Demand\Backgrounds
      x-accepts:
      - application/vnd.vimeo.picture+json
    patch:
      operationId: edit_vod_background
      security:
      - oauth2:
        - edit
      summary: Edit a background of an On Demand page
      tags:
      - On Demand\Backgrounds
      x-content-type: application/vnd.vimeo.picture+json
      x-accepts:
      - application/vnd.vimeo.picture+json
  /ondemand/pages/{ondemand_id}/genres:
    get:
      operationId: get_vod_genres_by_ondemand_id
      summary: Get all the genres of an On Demand page
      tags:
      - On Demand\Genres
      x-accepts:
      - application/vnd.vimeo.ondemand.genre+json
  /ondemand/pages/{ondemand_id}/genres/{genre_id}:
    delete:
      operationId: delete_vod_genre
      security:
      - oauth2:
        - edit
      summary: Remove a genre from an On Demand page
      tags:
      - On Demand\Genres
      x-accepts:
      - application/vnd.vimeo.ondemand.genre+json
    get:
      operationId: get_vod_genre_by_ondemand_id
      summary: Check whether an On Demand page belongs to a genre
      tags:
      - On Demand\Genres
      x-accepts:
      - application/vnd.vimeo.ondemand.genre+json
    put:
      operationId: add_vod_genre
      security:
      - oauth2:
        - edit
      summary: Add a genre to an On Demand page
      tags:
      - On Demand\Genres
      x-accepts:
      - application/vnd.vimeo.ondemand.genre+json
  /ondemand/pages/{ondemand_id}/likes:
    get:
      description: This method gets all the users who have liked a particular video
        on an On Demand page.
      operationId: get_vod_likes
      summary: Get all the users who have liked a video on an On Demand page
      tags:
      - Likes\Essentials
      x-accepts:
      - application/vnd.vimeo.user+json
  /ondemand/pages/{ondemand_id}/pictures:
    get:
      operationId: get_vod_posters
      summary: Get all the posters of an On Demand page
      tags:
      - On Demand\Posters
      x-accepts:
      - application/vnd.vimeo.picture+json
    post:
      operationId: add_vod_poster
      security:
      - oauth2:
        - upload
      summary: Add a poster to an On Demand page
      tags:
      - On Demand\Posters
      x-accepts:
      - application/vnd.vimeo.picture+json
  /ondemand/pages/{ondemand_id}/pictures/{poster_id}:
    get:
      operationId: get_vod_poster
      summary: Get a specific poster of an On Demand page
      tags:
      - On Demand\Posters
      x-accepts:
      - application/vnd.vimeo.picture+json
    patch:
      operationId: edit_vod_poster
      security:
      - oauth2:
        - edit
      summary: Edit a poster of an On Demand page
      tags:
      - On Demand\Posters
      x-content-type: application/vnd.vimeo.picture+json
      x-accepts:
      - application/vnd.vimeo.picture+json
  /ondemand/pages/{ondemand_id}/promotions:
    get:
      operationId: get_vod_promotions
      security:
      - oauth2:
        - promo_codes
      summary: Get all the promotions on an On Demand page
      tags:
      - On Demand\Promotions
      x-accepts:
      - application/vnd.vimeo.ondemand.promotion+json
    post:
      operationId: create_vod_promotion
      security:
      - oauth2:
        - promo_codes
        - create
      summary: Add a promotion to an On Demand page
      tags:
      - On Demand\Promotions
      x-content-type: application/vnd.vimeo.ondemand.promotion+json
      x-accepts:
      - application/vnd.vimeo.ondemand.promotion+json
  /ondemand/pages/{ondemand_id}/promotions/{promotion_id}:
    delete:
      operationId: delete_vod_promotion
      security:
      - oauth2:
        - promo_codes
        - delete
      summary: Remove a promotion from an On Demand page
      tags:
      - On Demand\Promotions
      x-accepts:
      - application/json
    get:
      operationId: get_vod_promotion
      security:
      - oauth2:
        - promo_codes
      summary: Get a specific promotion on an On Demand page
      tags:
      - On Demand\Promotions
      x-accepts:
      - application/vnd.vimeo.ondemand.promotion+json
  /ondemand/pages/{ondemand_id}/promotions/{promotion_id}/codes:
    get:
      operationId: get_vod_promotion_codes
      security:
      - oauth2:
        - promo_codes
      summary: Get all the codes of a promotion on an On Demand page
      tags:
      - On Demand\Promotions
      x-accepts:
      - application/vnd.vimeo.ondemand.promocode+json
  /ondemand/pages/{ondemand_id}/regions:
    delete:
      operationId: delete_vod_regions
      security:
      - oauth2:
        - edit
      summary: Remove a list of regions from an On Demand page
      tags:
      - On Demand\Regions
      x-content-type: application/vnd.vimeo.ondemand.region+json
      x-accepts:
      - application/vnd.vimeo.ondemand.region+json
    get:
      operationId: get_vod_regions
      summary: Get all the regions of an On Demand page
      tags:
      - On Demand\Regions
      x-accepts:
      - application/vnd.vimeo.ondemand.region+json
    put:
      operationId: set_vod_regions
      security:
      - oauth2:
        - edit
      summary: Add a list of regions to an On Demand page
      tags:
      - On Demand\Regions
      x-content-type: application/vnd.vimeo.ondemand.region+json
      x-accepts:
      - application/vnd.vimeo.ondemand.region+json
  /ondemand/pages/{ondemand_id}/regions/{country}:
    delete:
      operationId: delete_vod_region
      security:
      - oauth2:
        - edit
      summary: Remove a specific region from an On Demand page
      tags:
      - On Demand\Regions
      x-accepts:
      - application/vnd.vimeo.ondemand.region+json
    get:
      description: Checks whether an On Demand page belongs to a region.
      operationId: get_vod_region
      summary: Get a specific region of an On Demand page
      tags:
      - On Demand\Regions
      x-accepts:
      - application/vnd.vimeo.ondemand.region+json
    put:
      operationId: add_vod_region
      security:
      - oauth2:
        - edit
      summary: Add a specific region to an On Demand page
      tags:
      - On Demand\Regions
      x-accepts:
      - application/vnd.vimeo.ondemand.region+json
  /ondemand/pages/{ondemand_id}/seasons:
    get:
      operationId: get_vod_seasons
      summary: Get all the seasons on an On Demand page
      tags:
      - On Demand\Seasons
      x-accepts:
      - application/vnd.vimeo.ondemand.season+json
  /ondemand/pages/{ondemand_id}/seasons/{season_id}:
    get:
      operationId: get_vod_season
      summary: Get a specific season on an On Demand page
      tags:
      - On Demand\Seasons
      x-accepts:
      - application/vnd.vimeo.ondemand.season+json
  /ondemand/pages/{ondemand_id}/seasons/{season_id}/videos:
    get:
      operationId: get_vod_season_videos
      summary: Get all the videos in a season on an On Demand page
      tags:
      - On Demand\Seasons
      x-accepts:
      - application/vnd.vimeo.video+json
  /ondemand/pages/{ondemand_id}/videos:
    get:
      operationId: get_vod_videos
      summary: Get all the videos on an On Demand page
      tags:
      - On Demand\Videos
      x-accepts:
      - application/vnd.vimeo.ondemand.video+json
  /ondemand/pages/{ondemand_id}/videos/{video_id}:
    delete:
      operationId: delete_video_from_vod
      security:
      - oauth2:
        - edit
      summary: Remove a video from an On Demand page
      tags:
      - On Demand\Videos
      x-accepts:
      - application/vnd.vimeo.ondemand.video+json
    get:
      operationId: get_vod_video
      summary: Get a specific video on an On Demand page
      tags:
      - On Demand\Videos
      x-accepts:
      - application/vnd.vimeo.ondemand.video+json
    put:
      operationId: add_video_to_vod
      security:
      - oauth2:
        - edit
      summary: Add a video to an On Demand page
      tags:
      - On Demand\Videos
      x-content-type: application/vnd.vimeo.ondemand.video+json
      x-accepts:
      - application/vnd.vimeo.ondemand.video+json
  /ondemand/regions:
    get:
      operationId: get_regions
      summary: Get all the On Demand regions
      tags:
      - On Demand\Regions
      x-accepts:
      - application/vnd.vimeo.ondemand.region+json
  /ondemand/regions/{country}:
    get:
      operationId: get_region
      summary: Get a specific On Demand region
      tags:
      - On Demand\Regions
      x-accepts:
      - application/vnd.vimeo.ondemand.region+json
  /tags/{word}:
    get:
      operationId: get_tag
      summary: Get a specific tag
      tags:
      - Tags\Essentials
      x-accepts:
      - application/vnd.vimeo.tag+json
  /tags/{word}/videos:
    get:
      operationId: get_videos_with_tag
      summary: Get all the videos with a specific tag
      tags:
      - Videos\Tags
      x-accepts:
      - application/vnd.vimeo.video+json
  /tokens:
    delete:
      description: This method enables an app to notify the API that it is done with
        a token and that the token can be discarded.
      operationId: delete_token
      summary: Revoke the current access token
      tags:
      - Authentication Extras\Essentials
      x-accepts:
      - application/vnd.vimeo.auth+json
  /users:
    get:
      operationId: search_users
      summary: Search for users
      tags:
      - Users\Internal
      x-accepts:
      - application/vnd.vimeo.user+json
  /users/{user_id}:
    get:
      operationId: get_user
      summary: Get a user
      tags:
      - Users\Essentials
      x-accepts:
      - application/vnd.vimeo.user+json
    patch:
      operationId: edit_user
      summary: Edit a user
      tags:
      - Users\Essentials
      x-content-type: application/vnd.vimeo.user+json
      x-accepts:
      - application/vnd.vimeo.user+json
  /users/{user_id}/albums:
    get:
      operationId: get_albums
      summary: Get all the albums that belong to a user
      tags:
      - Albums\Essentials
      x-accepts:
      - application/json
    post:
      operationId: create_album
      security:
      - oauth2:
        - create
      summary: Create an album
      tags:
      - Albums\Essentials
      x-content-type: application/vnd.vimeo.album+json
      x-accepts:
      - application/vnd.vimeo.album+json
  /users/{user_id}/albums/{album_id}:
    delete:
      operationId: delete_album
      security:
      - oauth2:
        - delete
      summary: Delete an album
      tags:
      - Albums\Essentials
      x-accepts:
      - application/json
    get:
      operationId: get_album
      summary: Get a specific album
      tags:
      - Albums\Essentials
      x-accepts:
      - application/vnd.vimeo.album+json
    patch:
      operationId: edit_album
      security:
      - oauth2:
        - edit
      summary: Edit an album
      tags:
      - Albums\Essentials
      x-content-type: application/vnd.vimeo.album+json
      x-accepts:
      - application/vnd.vimeo.album+json
  /users/{user_id}/albums/{album_id}/custom_thumbnails:
    get:
      operationId: get_album_custom_thumbs
      summary: Get all the custom upload thumbnails of an album
      tags:
      - Albums\Custom album thumbnails
      x-accepts:
      - application/vnd.vimeo.picture+json
    post:
      operationId: create_album_custom_thumb
      security:
      - oauth2:
        - upload
      summary: Add a custom uploaded thumbnail
      tags:
      - Albums\Custom album thumbnails
      x-accepts:
      - application/vnd.vimeo.picture+json
  /users/{user_id}/albums/{album_id}/custom_thumbnails/{thumbnail_id}:
    delete:
      description: This method removes a custom uploaded thumbnail from the specified
        album.
      operationId: delete_album_custom_thumbnail
      security:
      - oauth2:
        - edit
      summary: Remove a custom uploaded album thumbnail
      tags:
      - Albums\Custom album thumbnails
      x-accepts:
      - application/vnd.vimeo.picture+json
    get:
      operationId: get_album_custom_thumbnail
      summary: Get a specific custom uploaded album thumbnail
      tags:
      - Albums\Custom album thumbnails
      x-accepts:
      - application/vnd.vimeo.picture+json
    patch:
      operationId: replace_album_custom_thumb
      security:
      - oauth2:
        - edit
      summary: Replace a custom uploaded album thumbnail
      tags:
      - Albums\Custom album thumbnails
      x-content-type: application/vnd.vimeo.picture+json
      x-accepts:
      - application/vnd.vimeo.picture+json
  /users/{user_id}/albums/{album_id}/logos:
    get:
      operationId: get_album_logos
      summary: Get all the custom logos of an album
      tags:
      - Albums\Custom album logos
      x-accepts:
      - application/vnd.vimeo.picture+json
    post:
      operationId: create_album_logo
      security:
      - oauth2:
        - upload
      summary: Add a custom album logo
      tags:
      - Albums\Custom album logos
      x-accepts:
      - application/vnd.vimeo.picture+json
  /users/{user_id}/albums/{album_id}/logos/{logo_id}:
    delete:
      description: This method removes a custom logo from the specified album.
      operationId: delete_album_logo
      security:
      - oauth2:
        - edit
      summary: Remove a custom album logo
      tags:
      - Albums\Custom album logos
      x-accepts:
      - application/vnd.vimeo.picture+json
    get:
      operationId: get_album_logo
      summary: Get a specific custom album logo
      tags:
      - Albums\Custom album logos
      x-accepts:
      - application/vnd.vimeo.picture+json
    patch:
      operationId: replace_album_logo
      security:
      - oauth2:
        - edit
      summary: Replace a custom album logo
      tags:
      - Albums\Custom album logos
      x-content-type: application/vnd.vimeo.picture+json
      x-accepts:
      - application/vnd.vimeo.picture+json
  /users/{user_id}/albums/{album_id}/videos:
    get:
      operationId: get_album_videos
      summary: Get all the videos in an album
      tags:
      - Albums\Album videos
      x-accepts:
      - application/vnd.vimeo.video+json
    put:
      description: This method replaces all the existing videos in an album with one
        or more videos.
      operationId: replace_videos_in_album
      security:
      - oauth2:
        - edit
      summary: Replace all the videos in an album
      tags:
      - Albums\Album videos
      x-content-type: application/json
      x-accepts:
      - application/json
  /users/{user_id}/albums/{album_id}/videos/{video_id}:
    delete:
      operationId: remove_video_from_album
      security:
      - oauth2:
        - edit
      summary: Remove a video from an album
      tags:
      - Albums\Album videos
      x-accepts:
      - application/json
    get:
      description: This method gets a single video from an album. You can use this
        method to determine whether the album contains the specified video.
      operationId: get_album_video
      summary: Get a specific video in an album
      tags:
      - Albums\Album videos
      x-accepts:
      - application/vnd.vimeo.video+json
    put:
      operationId: add_video_to_album
      security:
      - oauth2:
        - edit
      summary: Add a specific video to an album
      tags:
      - Albums\Album videos
      x-accepts:
      - application/json
  /users/{user_id}/albums/{album_id}/videos/{video_id}/set_album_thumbnail:
    post:
      operationId: set_video_as_album_thumbnail
      security:
      - oauth2:
        - edit
      summary: Set a video as the album thumbnail
      tags:
      - Albums\Album videos
      x-content-type: application/json
      x-accepts:
      - application/json
  /users/{user_id}/appearances:
    get:
      operationId: get_appearances
      summary: Get all the videos in which a user appears
      tags:
      - Videos\Essentials
      x-accepts:
      - application/vnd.vimeo.video+json
  /users/{user_id}/categories:
    get:
      operationId: get_category_subscriptions
      security:
      - oauth2:
        - private
      summary: Get all the categories that a user follows
      tags:
      - Categories\Subscriptions
      x-accepts:
      - application/vnd.vimeo.category+json
  /users/{user_id}/categories/{category}:
    delete:
      operationId: unsubscribe_from_category
      security:
      - oauth2:
        - interact
      summary: Unsubscribe a user from a category
      tags:
      - Categories\Subscriptions
      x-accepts:
      - application/json
    get:
      operationId: check_if_user_subscribed_to_category
      security:
      - oauth2:
        - private
      summary: Check if a user follows a category
      tags:
      - Categories\Subscriptions
      x-accepts:
      - application/json
    put:
      operationId: subscribe_to_category
      security:
      - oauth2:
        - interact
      summary: Subscribe a user to a single category
      tags:
      - Categories\Subscriptions
      x-accepts:
      - application/json
  /users/{user_id}/channels:
    get:
      operationId: get_channel_subscriptions
      summary: Get all the channels to which a user subscribes
      tags:
      - Channels\Essentials
      x-accepts:
      - application/vnd.vimeo.channel+json
  /users/{user_id}/channels/{channel_id}:
    delete:
      operationId: unsubscribe_from_channel
      security:
      - oauth2:
        - interact
      summary: Unsubscribe a user from a specific channel
      tags:
      - Channels\Subscriptions and subscribers
      x-accepts:
      - application/json
    get:
      operationId: check_if_user_subscribed_to_channel
      summary: Check if a user follows a channel
      tags:
      - Channels\Subscriptions and subscribers
      x-accepts:
      - application/json
    put:
      operationId: subscribe_to_channel
      security:
      - oauth2:
        - interact
      summary: Subscribe a user to a specific channel
      tags:
      - Channels\Subscriptions and subscribers
      x-accepts:
      - application/json
  /users/{user_id}/customlogos:
    get:
      operationId: get_custom_logos
      summary: Get all the custom logos that belong to a user
      tags:
      - Embed Presets\Custom Logos
      x-accepts:
      - application/vnd.vimeo.picture+json
    post:
      operationId: create_custom_logo
      security:
      - oauth2:
        - upload
      summary: Add a custom logo
      tags:
      - Embed Presets\Custom Logos
      x-accepts:
      - application/vnd.vimeo.picture+json
  /users/{user_id}/customlogos/{logo_id}:
    get:
      operationId: get_custom_logo
      summary: Get a specific custom logo
      tags:
      - Embed Presets\Custom Logos
      x-accepts:
      - application/vnd.vimeo.picture+json
  /users/{user_id}/feed:
    get:
      operationId: get_feed
      security:
      - oauth2:
        - private
      summary: Get all videos in a user's feed
      tags:
      - Users\Feed
      x-accepts:
      - application/vnd.vimeo.activity+json
  /users/{user_id}/followers:
    get:
      operationId: get_followers
      summary: Get all the followers of a user
      tags:
      - Users\Follows
      x-accepts:
      - application/vnd.vimeo.user+json
  /users/{user_id}/following:
    get:
      operationId: get_user_following
      summary: Get all the users that a user is following
      tags:
      - Users\Follows
      x-accepts:
      - application/vnd.vimeo.user+json
    post:
      operationId: follow_users
      security:
      - oauth2:
        - interact
      summary: Follow a list of users
      tags:
      - Users\Follows
      x-content-type: application/json
      x-accepts:
      - application/json
  /users/{user_id}/following/{follow_user_id}:
    delete:
      operationId: unfollow_user
      security:
      - oauth2:
        - interact
      summary: Unfollow a user
      tags:
      - Users\Follows
      x-accepts:
      - application/json
    get:
      operationId: check_if_user_is_following
      summary: Check if a user is following another user
      tags:
      - Users\Follows
      x-accepts:
      - application/json
    put:
      operationId: follow_user
      security:
      - oauth2:
        - interact
      summary: Follow a specific user
      tags:
      - Users\Follows
      x-accepts:
      - application/json
  /users/{user_id}/groups:
    get:
      operationId: get_user_groups
      summary: Get all the groups that a user has joined
      tags:
      - Groups\Users
      x-accepts:
      - application/vnd.vimeo.group+json
  /users/{user_id}/groups/{group_id}:
    delete:
      operationId: leave_group
      security:
      - oauth2:
        - interact
      summary: Remove a user from a group
      tags:
      - Groups\Subscription
      x-accepts:
      - application/json
    get:
      operationId: check_if_user_joined_group
      summary: Check if a user has joined a group
      tags:
      - Groups\Users
      x-accepts:
      - application/json
    put:
      operationId: join_group
      security:
      - oauth2:
        - interact
      summary: Add a user to a group
      tags:
      - Groups\Subscription
      x-accepts:
      - application/json
  /users/{user_id}/likes:
    get:
      operationId: get_likes
      summary: Get all the videos that a user has liked
      tags:
      - Likes\Essentials
      x-accepts:
      - application/vnd.vimeo.video+json
  /users/{user_id}/likes/{video_id}:
    delete:
      operationId: unlike_video
      security:
      - oauth2:
        - interact
      summary: Cause a user to unlike a video
      tags:
      - Likes\Essentials
      x-accepts:
      - application/json
    get:
      operationId: check_if_user_liked_video
      summary: Check if a user has liked a video
      tags:
      - Likes\Essentials
      x-accepts:
      - application/json
    put:
      operationId: like_video
      security:
      - oauth2:
        - interact
      summary: Cause a user to like a video
      tags:
      - Likes\Essentials
      x-accepts:
      - application/json
  /users/{user_id}/ondemand/pages:
    get:
      operationId: get_user_vods
      summary: Get all the On Demand pages of a user
      tags:
      - On Demand\Essentials
      x-accepts:
      - application/vnd.vimeo.ondemand.page+json
    post:
      operationId: create_vod
      summary: Create an On Demand page
      tags:
      - On Demand\Essentials
      x-content-type: application/json
      x-accepts:
      - application/json
  /users/{user_id}/ondemand/purchases:
    get:
      operationId: check_if_vod_was_purchased
      security:
      - oauth2:
        - purchased
      summary: Check if a user has made a purchase or rental from an On Demand page
      tags:
      - On Demand\Purchases and Rentals
      x-accepts:
      - application/vnd.vimeo.ondemand.page+json
  /users/{user_id}/pictures:
    get:
      operationId: get_pictures
      summary: Get all the pictures that belong to a user
      tags:
      - Users\Pictures
      x-accepts:
      - application/vnd.vimeo.picture+json
    post:
      operationId: create_picture
      security:
      - oauth2:
        - upload
      summary: Add a user picture
      tags:
      - Users\Pictures
      x-accepts:
      - application/vnd.vimeo.picture+json
  /users/{user_id}/pictures/{portraitset_id}:
    delete:
      operationId: delete_picture
      security:
      - oauth2:
        - delete
      summary: Delete a user picture
      tags:
      - Users\Pictures
      x-accepts:
      - application/json
    get:
      operationId: get_picture
      summary: Get a specific user picture
      tags:
      - Users\Pictures
      x-accepts:
      - application/vnd.vimeo.picture+json
    patch:
      operationId: edit_picture
      security:
      - oauth2:
        - edit
      summary: Edit a user picture
      tags:
      - Users\Pictures
      x-content-type: application/vnd.vimeo.picture+json
      x-accepts:
      - application/vnd.vimeo.picture+json
  /users/{user_id}/portfolios:
    get:
      operationId: get_portfolios
      summary: Get all the portfolios that belong to a user
      tags:
      - Portfolios\Essentials
      x-accepts:
      - application/vnd.vimeo.portfolio+json
  /users/{user_id}/portfolios/{portfolio_id}:
    get:
      operationId: get_portfolio
      summary: Get a specific portfolio
      tags:
      - Portfolios\Essentials
      x-accepts:
      - application/vnd.vimeo.portfolio+json
  /users/{user_id}/portfolios/{portfolio_id}/videos:
    get:
      operationId: get_portfolio_videos
      summary: Get all the videos in a portfolio
      tags:
      - Portfolios\Videos
      x-accepts:
      - application/vnd.vimeo.video+json
  /users/{user_id}/portfolios/{portfolio_id}/videos/{video_id}:
    delete:
      operationId: delete_video_from_portfolio
      security:
      - oauth2:
        - edit
      summary: Remove a video from a portfolio
      tags:
      - Portfolios\Videos
      x-accepts:
      - application/json
    get:
      operationId: get_portfolio_video
      summary: Get a specific video in a portfolio
      tags:
      - Portfolios\Videos
      x-accepts:
      - application/vnd.vimeo.video+json
    put:
      operationId: add_video_to_portfolio
      security:
      - oauth2:
        - edit
      summary: Add a video to a portfolio
      tags:
      - Portfolios\Videos
      x-accepts:
      - application/json
  /users/{user_id}/presets:
    get:
      operationId: get_embed_presets
      summary: Get all the embed presets that a user has created
      tags:
      - Embed Presets\Essentials
      x-accepts:
      - application/vnd.vimeo.preset+json
  /users/{user_id}/presets/{preset_id}:
    get:
      operationId: get_embed_preset
      summary: Get a specific embed preset
      tags:
      - Embed Presets\Essentials
      x-accepts:
      - application/vnd.vimeo.preset+json
    patch:
      operationId: edit_embed_preset
      summary: Edit an embed preset
      tags:
      - Embed Presets\Essentials
      x-content-type: application/vnd.vimeo.preset+json
      x-accepts:
      - application/vnd.vimeo.preset+json
  /users/{user_id}/presets/{preset_id}/videos:
    get:
      operationId: get_embed_preset_videos
      summary: Get all the videos that have been added to an embed preset
      tags:
      - Embed Presets\Videos
      x-accepts:
      - application/vnd.vimeo.video+json
  /users/{user_id}/projects:
    get:
      description: This method gets all the projects that belong to the specified
        user.
      operationId: get_projects
      security:
      - oauth2:
        - private
      summary: Get all the projects that belong to a user
      tags:
      - Projects\Essentials
      x-accepts:
      - application/json
    post:
      description: This method creates a new project for the specified user.
      operationId: create_project
      security:
      - oauth2:
        - create
      summary: Create a project
      tags:
      - Projects\Essentials
      x-content-type: application/json
      x-accepts:
      - application/json
  /users/{user_id}/projects/{project_id}:
    delete:
      description: This method deletes a project and optionally also the videos that
        it contains.
      operationId: delete_project
      security:
      - oauth2:
        - delete
      summary: Delete a project
      tags:
      - Projects\Essentials
      x-accepts:
      - application/json
    get:
      description: This method gets a single project that belongs to the specified
        user.
      operationId: get_project
      security:
      - oauth2:
        - private
      summary: Get a specific project
      tags:
      - Projects\Essentials
      x-accepts:
      - application/json
    patch:
      description: This method edits an existing project.
      operationId: edit_project
      security:
      - oauth2:
        - edit
      summary: Edit a project
      tags:
      - Projects\Essentials
      x-content-type: application/json
      x-accepts:
      - application/json
  /users/{user_id}/projects/{project_id}/videos:
    delete:
      description: This method removed multiple videos from the specified project.
      operationId: remove_videos_from_project
      security:
      - oauth2:
        - interact
      summary: Remove a list of videos from a project
      tags:
      - Projects\Videos
      x-accepts:
      - application/json
    get:
      description: This method gets all the videos that belong to the specified project.
      operationId: get_project_videos
      security:
      - oauth2:
        - private
      summary: Get all the videos in a project
      tags:
      - Projects\Videos
      x-accepts:
      - application/json
    put:
      description: This method adds multiple videos to the specified project.
      operationId: add_videos_to_project
      security:
      - oauth2:
        - interact
      summary: Add a list of videos to a project
      tags:
      - Projects\Videos
      x-accepts:
      - application/json
  /users/{user_id}/projects/{project_id}/videos/{video_id}:
    delete:
      description: This method removes a single video from the specified project.
      operationId: remove_video_from_project
      security:
      - oauth2:
        - delete
      summary: Remove a specific video from a project
      tags:
      - Projects\Videos
      x-accepts:
      - application/json
    put:
      description: This method adds a single video to the specified project.
      operationId: add_video_to_project
      security:
      - oauth2:
        - interact
      summary: Add a specific video to a project
      tags:
      - Projects\Videos
      x-accepts:
      - application/json
  /users/{user_id}/uploads/{upload}:
    delete:
      operationId: complete_streaming_upload
      security:
      - oauth2:
        - upload
      summary: Complete a user's streaming upload
      tags:
      - Videos\Upload
      x-accepts:
      - application/json
    get:
      operationId: get_upload_attempt
      security:
      - oauth2:
        - upload
      summary: Get a user's upload attempt
      tags:
      - Videos\Upload
      x-accepts:
      - application/vnd.vimeo.uploadattempt+json
  /users/{user_id}/videos:
    get:
      operationId: get_videos
      summary: Get all the videos that a user has uploaded
      tags:
      - Videos\Essentials
      x-accepts:
      - application/vnd.vimeo.video+json
    post:
      description: "Begin the video upload process. For more information, see our\
        \ [upload documentation](https://developer.vimeo.com/api/upload/videos)."
      operationId: upload_video
      summary: Upload a video
      tags:
      - Videos\Upload
      x-content-type: application/vnd.vimeo.video+json
      x-accepts:
      - application/vnd.vimeo.video+json
  /users/{user_id}/videos/{video_id}:
    get:
      operationId: check_if_user_owns_video
      summary: Check if a user owns a video
      tags:
      - Videos\Essentials
      x-accepts:
      - application/vnd.vimeo.video+json
  /users/{user_id}/watchlater:
    get:
      operationId: get_watch_later_queue
      security:
      - oauth2:
        - private
      summary: Get all the videos in a user's Watch Later queue
      tags:
      - Watch Later Queue\Essentials
      x-accepts:
      - application/vnd.vimeo.video+json
  /users/{user_id}/watchlater/{video_id}:
    delete:
      operationId: delete_video_from_watch_later
      security:
      - oauth2:
        - interact
      summary: Remove a video from a user's Watch Later queue
      tags:
      - Watch Later Queue\Essentials
      x-accepts:
      - application/json
    get:
      operationId: check_watch_later_queue
      security:
      - oauth2:
        - private
      summary: Check if a user has added a specific video to their Watch Later queue
      tags:
      - Watch Later Queue\Essentials
      x-accepts:
      - application/vnd.vimeo.video+json
    put:
      operationId: add_video_to_watch_later
      security:
      - oauth2:
        - interact
      summary: Add a video to a user's Watch Later queue
      tags:
      - Watch Later Queue\Essentials
      x-accepts:
      - application/json
  /videos:
    get:
      operationId: search_videos
      summary: Search for videos
      tags:
      - Videos\Essentials
      x-accepts:
      - application/vnd.vimeo.video+json
  /videos/{video_id}:
    delete:
      operationId: delete_video
      security:
      - oauth2:
        - delete
      summary: Delete a video
      tags:
      - Videos\Essentials
      x-accepts:
      - application/json
    get:
      operationId: get_video
      summary: Get a specific video
      tags:
      - Videos\Essentials
      x-accepts:
      - application/vnd.vimeo.video+json
    patch:
      operationId: edit_video
      security:
      - oauth2:
        - edit
      summary: Edit a video
      tags:
      - Videos\Essentials
      x-content-type: application/vnd.vimeo.video+json
      x-accepts:
      - application/vnd.vimeo.video+json
  /videos/{video_id}/available_channels:
    get:
      operationId: get_available_video_channels
      summary: Get all the channels to which a user can add or remove a specific video
      tags:
      - Channels\Videos
      x-accepts:
      - application/vnd.vimeo.channel+json
  /videos/{video_id}/categories:
    get:
      operationId: get_video_categories
      summary: Get all the categories to which a video belongs
      tags:
      - Categories\Videos
      x-accepts:
      - application/vnd.vimeo.category+json
    put:
      description: |-
        With this method, you can suggest up to two categories and one subcategory for a video. Vimeo makes the final determination about whether the video
        belongs in these categories.
      operationId: suggest_video_category
      security:
      - oauth2:
        - edit
      summary: Suggest categories for a video
      tags:
      - Categories\Videos
      x-content-type: application/vnd.vimeo.category+json
      x-accepts:
      - application/vnd.vimeo.category+json
  /videos/{video_id}/comments:
    get:
      operationId: get_comments
      summary: Get all the comments on a video
      tags:
      - Videos\Comments
      x-accepts:
      - application/vnd.vimeo.comment+json
    post:
      operationId: create_comment
      security:
      - oauth2:
        - interact
      summary: Add a comment to a video
      tags:
      - Videos\Comments
      x-content-type: application/vnd.vimeo.comment+json
      x-accepts:
      - application/vnd.vimeo.comment+json
  /videos/{video_id}/comments/{comment_id}:
    delete:
      operationId: delete_comment
      security:
      - oauth2:
        - delete
      summary: Delete a video comment
      tags:
      - Videos\Comments
      x-accepts:
      - application/json
    get:
      operationId: get_comment
      summary: Get a specific video comment
      tags:
      - Videos\Comments
      x-accepts:
      - application/vnd.vimeo.comment+json
    patch:
      operationId: edit_comment
      security:
      - oauth2:
        - edit
      summary: Edit a video comment
      tags:
      - Videos\Comments
      x-content-type: application/vnd.vimeo.comment+json
      x-accepts:
      - application/vnd.vimeo.comment+json
  /videos/{video_id}/comments/{comment_id}/replies:
    get:
      operationId: get_comment_replies
      summary: Get all the replies to a video comment
      tags:
      - Videos\Comments
      x-accepts:
      - application/vnd.vimeo.comment+json
    post:
      operationId: create_comment_reply
      security:
      - oauth2:
        - interact
      summary: Add a reply to a video comment
      tags:
      - Videos\Comments
      x-content-type: application/vnd.vimeo.comment+json
      x-accepts:
      - application/vnd.vimeo.comment+json
  /videos/{video_id}/credits:
    get:
      operationId: get_video_credits
      summary: Get all the credited users in a video
      tags:
      - Videos\Credits
      x-accepts:
      - application/vnd.vimeo.credit+json
    post:
      operationId: add_video_credit
      summary: Credit a user in a video
      tags:
      - Videos\Credits
      x-content-type: application/vnd.vimeo.credit+json
      x-accepts:
      - application/vnd.vimeo.credit+json
  /videos/{video_id}/credits/{credit_id}:
    delete:
      operationId: delete_video_credit
      security:
      - oauth2:
        - edit
      summary: Delete a credit for a user in a video
      tags:
      - Videos\Credits
      x-accepts:
      - application/json
    get:
      operationId: get_video_credit
      summary: Get a specific credited user in a video
      tags:
      - Videos\Credits
      x-accepts:
      - application/vnd.vimeo.credit+json
    patch:
      operationId: edit_video_credit
      security:
      - oauth2:
        - edit
      summary: Edit a credit for a user in a video
      tags:
      - Videos\Credits
      x-content-type: application/vnd.vimeo.credit+json
      x-accepts:
      - application/vnd.vimeo.credit+json
  /videos/{video_id}/likes:
    get:
      operationId: get_video_likes
      summary: Get all the users who have liked a video
      tags:
      - Likes\Essentials
      x-accepts:
      - application/vnd.vimeo.user+json
  /videos/{video_id}/pictures:
    get:
      operationId: get_video_thumbnails
      summary: Get all the thumbnails of a video
      tags:
      - Videos\Thumbnails
      x-accepts:
      - application/vnd.vimeo.picture+json
    post:
      operationId: create_video_thumbnail
      security:
      - oauth2:
        - upload
      summary: Add a video thumbnail
      tags:
      - Videos\Thumbnails
      x-content-type: application/vnd.vimeo.picture+json
      x-accepts:
      - application/vnd.vimeo.picture+json
  /videos/{video_id}/pictures/{picture_id}:
    delete:
      operationId: delete_video_thumbnail
      security:
      - oauth2:
        - edit
      summary: Delete a video thumbnail
      tags:
      - Videos\Thumbnails
      x-accepts:
      - application/json
    get:
      operationId: get_video_thumbnail
      summary: Get a video thumbnail
      tags:
      - Videos\Thumbnails
      x-accepts:
      - application/vnd.vimeo.picture+json
    patch:
      operationId: edit_video_thumbnail
      security:
      - oauth2:
        - edit
      summary: Edit a video thumbnail
      tags:
      - Videos\Thumbnails
      x-content-type: application/vnd.vimeo.picture+json
      x-accepts:
      - application/vnd.vimeo.picture+json
  /videos/{video_id}/presets/{preset_id}:
    delete:
      operationId: delete_video_embed_preset
      security:
      - oauth2:
        - edit
      summary: Remove an embed preset from a video
      tags:
      - Embed Presets\Videos
      x-accepts:
      - application/json
    get:
      operationId: get_video_embed_preset
      summary: Check if an embed preset has been added to a video
      tags:
      - Embed Presets\Videos
      x-accepts:
      - application/json
    put:
      operationId: add_video_embed_preset
      security:
      - oauth2:
        - edit
      summary: Add an embed preset to a video
      tags:
      - Embed Presets\Videos
      x-accepts:
      - application/json
  /videos/{video_id}/privacy/domains:
    get:
      operationId: get_video_privacy_domains
      summary: Get all the domains on which a video can be embedded
      tags:
      - Videos\Embed Privacy
      x-accepts:
      - application/vnd.vimeo.domain+json
  /videos/{video_id}/privacy/domains/{domain}:
    delete:
      operationId: delete_video_privacy_domain
      security:
      - oauth2:
        - edit
      summary: Restrict a video from being embedded on a domain
      tags:
      - Videos\Embed Privacy
      x-accepts:
      - application/json
    put:
      description: "If domain privacy is enabled for this video, this method permits\
        \ the video to be embedded on the specified domain."
      operationId: add_video_privacy_domain
      security:
      - oauth2:
        - edit
      summary: Permit a video to be embedded on a domain
      tags:
      - Videos\Embed Privacy
      x-accepts:
      - application/json
  /videos/{video_id}/privacy/users:
    get:
      operationId: get_video_privacy_users
      summary: Get all the users who can view a user's private videos by default
      tags:
      - Videos\Viewing Privacy
      x-accepts:
      - application/vnd.vimeo.user+json
    put:
      description: |-
        The body of this request should follow our
        [batch request format](https://developer.vimeo.com/api/common-formats#batch-requests). Each object must contain
        a single `URI` field, and the value of this field must be the URI of the user who can view this video.
      operationId: add_video_privacy_users
      security:
      - oauth2:
        - edit
      summary: Permit a list of users to view a private video
      tags:
      - Videos\Viewing Privacy
      x-accepts:
      - application/vnd.vimeo.user+json
  /videos/{video_id}/privacy/users/{user_id}:
    delete:
      operationId: delete_video_privacy_user
      security:
      - oauth2:
        - edit
      summary: Restrict a user from viewing a private video
      tags:
      - Videos\Viewing Privacy
      x-accepts:
      - application/json
    put:
      operationId: add_video_privacy_user
      security:
      - oauth2:
        - edit
      summary: Permit a specific user to view a private video
      tags:
      - Videos\Viewing Privacy
      x-accepts:
      - application/vnd.vimeo.user+json
  /videos/{video_id}/tags:
    get:
      operationId: get_video_tags
      summary: Get all the tags of a video
      tags:
      - Videos\Tags
      x-accepts:
      - application/vnd.vimeo.tag+json
    put:
      operationId: add_video_tags
      security:
      - oauth2:
        - edit
      summary: Add a list of tags to a video
      tags:
      - Videos\Tags
      x-content-type: application/vnd.vimeo.tag+json
      x-accepts:
      - application/vnd.vimeo.tag+json
  /videos/{video_id}/tags/{word}:
    delete:
      operationId: delete_video_tag
      security:
      - oauth2:
        - edit
      summary: Remove a tag from a video
      tags:
      - Videos\Tags
      x-accepts:
      - application/vnd.vimeo.tag+json
    get:
      operationId: check_video_for_tag
      summary: Check if a tag has been added to a video
      tags:
      - Videos\Tags
      x-accepts:
      - application/vnd.vimeo.tag+json
    put:
      operationId: add_video_tag
      security:
      - oauth2:
        - edit
      summary: Add a specific tag to a video
      tags:
      - Videos\Tags
      x-accepts:
      - application/vnd.vimeo.tag+json
  /videos/{video_id}/texttracks:
    get:
      operationId: get_text_tracks
      summary: Get all the text tracks of a video
      tags:
      - Videos\Text Tracks
      x-accepts:
      - application/vnd.vimeo.video.texttrack+json
    post:
      description: "For additional information, see our [text track upload guide](https://developer.vimeo.com/api/upload/texttracks)."
      operationId: create_text_track
      security:
      - oauth2:
        - upload
      summary: Add a text track to a video
      tags:
      - Videos\Text Tracks
      x-content-type: application/vnd.vimeo.video.texttrack+json
      x-accepts:
      - application/vnd.vimeo.video.texttrack+json
  /videos/{video_id}/texttracks/{texttrack_id}:
    delete:
      operationId: delete_text_track
      security:
      - oauth2:
        - delete
      summary: Delete a text track
      tags:
      - Videos\Text Tracks
      x-accepts:
      - application/vnd.vimeo.video.texttrack+json
    get:
      operationId: get_text_track
      summary: Get a specific text track
      tags:
      - Videos\Text Tracks
      x-accepts:
      - application/vnd.vimeo.video.texttrack+json
    patch:
      operationId: edit_text_track
      security:
      - oauth2:
        - edit
      summary: Edit a text track
      tags:
      - Videos\Text Tracks
      x-content-type: application/vnd.vimeo.video.texttrack+json
      x-accepts:
      - application/vnd.vimeo.video.texttrack+json
  /videos/{video_id}/timelinethumbnails:
    post:
      operationId: create_video_custom_logo
      security:
      - oauth2:
        - upload
      summary: Add a new custom logo to a video
      tags:
      - Embed Presets\Videos
      x-accepts:
      - application/vnd.vimeo.picture+json
  /videos/{video_id}/timelinethumbnails/{thumbnail_id}:
    get:
      operationId: get_video_custom_logo
      summary: Get a custom video logo
      tags:
      - Embed Presets\Videos
      x-accepts:
      - application/vnd.vimeo.picture+json
  /videos/{video_id}/versions:
    post:
      operationId: create_video_version
      summary: Add a version to a video
      tags:
      - Videos\Versions
      x-content-type: application/vnd.vimeo.video.version+json
      x-accepts:
      - application/vnd.vimeo.video.version+json
  /videos/{video_id}/videos:
    get:
      operationId: get_related_videos
      summary: Get all the related videos of a video
      tags:
      - Videos\Recommendations
      x-accepts:
      - application/vnd.vimeo.video+json
components:
  securitySchemes:
    bearer:
      bearerFormat: bearer
      scheme: bearer
      type: http
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: /oauth/authorize
          scopes:
            create: "Create new albums, channels, and so on"
            delete: "Delete videos, albums, channels, and so on"
            edit: "Edit existing videos, albums, channels, and so on"
            email: Access to email addresses
            interact: "Interact with Vimeo resources on a member's behalf, such as\
              \ liking a video or following another member"
            private: Access private member data
            promo_codes: "Add, remove, and review Vimeo On Demand promotions"
            public: Access public member data
            purchase: Purchase content
            purchased: Access a member's Vimeo On Demand purchase history
            stats: Access video stats
            upload: Upload videos
            video_files: Access video files belonging to members with a PRO subscription
              or higher
          tokenUrl: /oauth/access_token
        clientCredentials:
          scopes:
            create: "Create new albums, channels, and so on"
            delete: "Delete videos, albums, channels, and so on"
            edit: "Edit existing videos, albums, channels, and so on"
            email: Access to email addresses
            interact: "Interact with Vimeo resources on a member's behalf, such as\
              \ liking a video or following another member"
            private: Access private member data
            promo_codes: "Add, remove, and review Vimeo On Demand promotions"
            public: Access public member data
            purchase: Purchase content
            purchased: Access a member's Vimeo On Demand purchase history
            stats: Access video stats
            upload: Upload videos
            video_files: Access video files belonging to members with a PRO subscription
              or higher
          tokenUrl: /oauth/authorize/client
      type: oauth2

