# coding: utf-8

# import models into model package
from openapi_server.models.academic_certificate_schema import AcademicCertificateSchema
from openapi_server.models.academic_certificate_schema_certificate_data import AcademicCertificateSchemaCertificateData
from openapi_server.models.academic_certificate_schema_certificate_data_examination import AcademicCertificateSchemaCertificateDataExamination
from openapi_server.models.academic_certificate_schema_certificate_data_performance import AcademicCertificateSchemaCertificateDataPerformance
from openapi_server.models.academic_certificate_schema_certificate_data_performance_subjects_inner import AcademicCertificateSchemaCertificateDataPerformanceSubjectsInner
from openapi_server.models.academic_certificate_schema_certificate_data_school import AcademicCertificateSchemaCertificateDataSchool
from openapi_server.models.academic_certificate_schema_issued_by import AcademicCertificateSchemaIssuedBy
from openapi_server.models.academic_certificate_schema_issued_by_organization import AcademicCertificateSchemaIssuedByOrganization
from openapi_server.models.academic_certificate_schema_issued_by_organization_address import AcademicCertificateSchemaIssuedByOrganizationAddress
from openapi_server.models.academic_certificate_schema_issued_to import AcademicCertificateSchemaIssuedTo
from openapi_server.models.academic_certificate_schema_issued_to_person import AcademicCertificateSchemaIssuedToPerson
from openapi_server.models.academic_certificate_schema_issued_to_person_address import AcademicCertificateSchemaIssuedToPersonAddress
from openapi_server.models.academic_certificate_schema_issued_to_person_photo import AcademicCertificateSchemaIssuedToPersonPhoto
from openapi_server.models.consent_artifact_schema import ConsentArtifactSchema
from openapi_server.models.consent_artifact_schema_consent import ConsentArtifactSchemaConsent
from openapi_server.models.consent_artifact_schema_consent_data import ConsentArtifactSchemaConsentData
from openapi_server.models.consent_artifact_schema_consent_permission import ConsentArtifactSchemaConsentPermission
from openapi_server.models.consent_artifact_schema_consent_permission_date_range import ConsentArtifactSchemaConsentPermissionDateRange
from openapi_server.models.consent_artifact_schema_consent_permission_frequency import ConsentArtifactSchemaConsentPermissionFrequency
from openapi_server.models.consent_artifact_schema_consent_purpose import ConsentArtifactSchemaConsentPurpose
from openapi_server.models.consent_artifact_schema_consent_user import ConsentArtifactSchemaConsentUser
from openapi_server.models.consent_artifact_schema_signature import ConsentArtifactSchemaSignature
from openapi_server.models.sscer400_response import Sscer400Response
from openapi_server.models.sscer401_response import Sscer401Response
from openapi_server.models.sscer404_response import Sscer404Response
from openapi_server.models.sscer500_response import Sscer500Response
from openapi_server.models.sscer502_response import Sscer502Response
from openapi_server.models.sscer503_response import Sscer503Response
from openapi_server.models.sscer504_response import Sscer504Response
from openapi_server.models.sscer_request import SscerRequest
from openapi_server.models.sscer_request_certificate_parameters import SscerRequestCertificateParameters
