/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.345.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAICreditPayrollIncomeRiskSignalsGetResponse.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAICreditPayrollIncomeRiskSignalsGetResponse::OAICreditPayrollIncomeRiskSignalsGetResponse(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAICreditPayrollIncomeRiskSignalsGetResponse::OAICreditPayrollIncomeRiskSignalsGetResponse() {
    this->initializeModel();
}

OAICreditPayrollIncomeRiskSignalsGetResponse::~OAICreditPayrollIncomeRiskSignalsGetResponse() {}

void OAICreditPayrollIncomeRiskSignalsGetResponse::initializeModel() {

    m_error_isSet = false;
    m_error_isValid = false;

    m_items_isSet = false;
    m_items_isValid = false;

    m_request_id_isSet = false;
    m_request_id_isValid = false;
}

void OAICreditPayrollIncomeRiskSignalsGetResponse::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAICreditPayrollIncomeRiskSignalsGetResponse::fromJsonObject(QJsonObject json) {

    m_error_isValid = ::OpenAPI::fromJsonValue(m_error, json[QString("error")]);
    m_error_isSet = !json[QString("error")].isNull() && m_error_isValid;

    m_items_isValid = ::OpenAPI::fromJsonValue(m_items, json[QString("items")]);
    m_items_isSet = !json[QString("items")].isNull() && m_items_isValid;

    m_request_id_isValid = ::OpenAPI::fromJsonValue(m_request_id, json[QString("request_id")]);
    m_request_id_isSet = !json[QString("request_id")].isNull() && m_request_id_isValid;
}

QString OAICreditPayrollIncomeRiskSignalsGetResponse::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAICreditPayrollIncomeRiskSignalsGetResponse::asJsonObject() const {
    QJsonObject obj;
    if (m_error.isSet()) {
        obj.insert(QString("error"), ::OpenAPI::toJsonValue(m_error));
    }
    if (m_items.size() > 0) {
        obj.insert(QString("items"), ::OpenAPI::toJsonValue(m_items));
    }
    if (m_request_id_isSet) {
        obj.insert(QString("request_id"), ::OpenAPI::toJsonValue(m_request_id));
    }
    return obj;
}

OAIPlaidError OAICreditPayrollIncomeRiskSignalsGetResponse::getError() const {
    return m_error;
}
void OAICreditPayrollIncomeRiskSignalsGetResponse::setError(const OAIPlaidError &error) {
    m_error = error;
    m_error_isSet = true;
}

bool OAICreditPayrollIncomeRiskSignalsGetResponse::is_error_Set() const{
    return m_error_isSet;
}

bool OAICreditPayrollIncomeRiskSignalsGetResponse::is_error_Valid() const{
    return m_error_isValid;
}

QList<OAIPayrollRiskSignalsItem> OAICreditPayrollIncomeRiskSignalsGetResponse::getItems() const {
    return m_items;
}
void OAICreditPayrollIncomeRiskSignalsGetResponse::setItems(const QList<OAIPayrollRiskSignalsItem> &items) {
    m_items = items;
    m_items_isSet = true;
}

bool OAICreditPayrollIncomeRiskSignalsGetResponse::is_items_Set() const{
    return m_items_isSet;
}

bool OAICreditPayrollIncomeRiskSignalsGetResponse::is_items_Valid() const{
    return m_items_isValid;
}

QString OAICreditPayrollIncomeRiskSignalsGetResponse::getRequestId() const {
    return m_request_id;
}
void OAICreditPayrollIncomeRiskSignalsGetResponse::setRequestId(const QString &request_id) {
    m_request_id = request_id;
    m_request_id_isSet = true;
}

bool OAICreditPayrollIncomeRiskSignalsGetResponse::is_request_id_Set() const{
    return m_request_id_isSet;
}

bool OAICreditPayrollIncomeRiskSignalsGetResponse::is_request_id_Valid() const{
    return m_request_id_isValid;
}

bool OAICreditPayrollIncomeRiskSignalsGetResponse::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_error.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_items.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_request_id_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAICreditPayrollIncomeRiskSignalsGetResponse::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_items_isValid && m_request_id_isValid && true;
}

} // namespace OpenAPI
