QT += network

HEADERS += \
# Models
    $${PWD}/OAIBgpPeerStatus.h \
    $${PWD}/OAIBgpPeerStatusListResult.h \
    $${PWD}/OAIBgpSettings.h \
    $${PWD}/OAIConnectionProtocol.h \
    $${PWD}/OAIConnectionResetSharedKey.h \
    $${PWD}/OAIConnectionSharedKey.h \
    $${PWD}/OAIDhGroup.h \
    $${PWD}/OAIGatewayRoute.h \
    $${PWD}/OAIGatewayRouteListResult.h \
    $${PWD}/OAIIkeEncryption.h \
    $${PWD}/OAIIkeIntegrity.h \
    $${PWD}/OAIIpsecEncryption.h \
    $${PWD}/OAIIpsecIntegrity.h \
    $${PWD}/OAIIpsecPolicy.h \
    $${PWD}/OAILocalNetworkGateway.h \
    $${PWD}/OAILocalNetworkGatewayListResult.h \
    $${PWD}/OAILocalNetworkGatewayPropertiesFormat.h \
    $${PWD}/OAILocalNetworkGatewayPropertiesFormat_localNetworkAddressSpace.h \
    $${PWD}/OAIPfsGroup.h \
    $${PWD}/OAITrafficSelectorPolicy.h \
    $${PWD}/OAITunnelConnectionHealth.h \
    $${PWD}/OAIVirtualNetworkConnectionGatewayReference.h \
    $${PWD}/OAIVirtualNetworkGateway.h \
    $${PWD}/OAIVirtualNetworkGatewayConnection.h \
    $${PWD}/OAIVirtualNetworkGatewayConnectionListEntity.h \
    $${PWD}/OAIVirtualNetworkGatewayConnectionListEntityPropertiesFormat.h \
    $${PWD}/OAIVirtualNetworkGatewayConnectionListEntityPropertiesFormat_peer.h \
    $${PWD}/OAIVirtualNetworkGatewayConnectionListResult.h \
    $${PWD}/OAIVirtualNetworkGatewayConnectionPropertiesFormat.h \
    $${PWD}/OAIVirtualNetworkGatewayConnectionStatus.h \
    $${PWD}/OAIVirtualNetworkGatewayConnectionType.h \
    $${PWD}/OAIVirtualNetworkGatewayConnections_StartPacketCapture_default_response.h \
    $${PWD}/OAIVirtualNetworkGatewayConnections_StartPacketCapture_default_response_details_inner.h \
    $${PWD}/OAIVirtualNetworkGatewayConnections_UpdateTags_request.h \
    $${PWD}/OAIVirtualNetworkGatewayIPConfiguration.h \
    $${PWD}/OAIVirtualNetworkGatewayIPConfigurationPropertiesFormat.h \
    $${PWD}/OAIVirtualNetworkGatewayListConnectionsResult.h \
    $${PWD}/OAIVirtualNetworkGatewayListResult.h \
    $${PWD}/OAIVirtualNetworkGatewayPropertiesFormat.h \
    $${PWD}/OAIVirtualNetworkGatewaySku.h \
    $${PWD}/OAIVpnClientConfiguration.h \
    $${PWD}/OAIVpnClientConnectionHealthDetail.h \
    $${PWD}/OAIVpnClientConnectionHealthDetailListResult.h \
    $${PWD}/OAIVpnClientIPsecParameters.h \
    $${PWD}/OAIVpnClientParameters.h \
    $${PWD}/OAIVpnClientRevokedCertificate.h \
    $${PWD}/OAIVpnClientRevokedCertificatePropertiesFormat.h \
    $${PWD}/OAIVpnClientRootCertificate.h \
    $${PWD}/OAIVpnClientRootCertificatePropertiesFormat.h \
    $${PWD}/OAIVpnDeviceScriptParameters.h \
    $${PWD}/OAIVpnPacketCaptureStartParameters.h \
    $${PWD}/OAIVpnPacketCaptureStopParameters.h \
# APIs
    $${PWD}/OAILocalNetworkGatewaysApi.h \
    $${PWD}/OAIVirtualNetworkGatewayConnectionsApi.h \
    $${PWD}/OAIVirtualNetworkGatewaysApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIBgpPeerStatus.cpp \
    $${PWD}/OAIBgpPeerStatusListResult.cpp \
    $${PWD}/OAIBgpSettings.cpp \
    $${PWD}/OAIConnectionProtocol.cpp \
    $${PWD}/OAIConnectionResetSharedKey.cpp \
    $${PWD}/OAIConnectionSharedKey.cpp \
    $${PWD}/OAIDhGroup.cpp \
    $${PWD}/OAIGatewayRoute.cpp \
    $${PWD}/OAIGatewayRouteListResult.cpp \
    $${PWD}/OAIIkeEncryption.cpp \
    $${PWD}/OAIIkeIntegrity.cpp \
    $${PWD}/OAIIpsecEncryption.cpp \
    $${PWD}/OAIIpsecIntegrity.cpp \
    $${PWD}/OAIIpsecPolicy.cpp \
    $${PWD}/OAILocalNetworkGateway.cpp \
    $${PWD}/OAILocalNetworkGatewayListResult.cpp \
    $${PWD}/OAILocalNetworkGatewayPropertiesFormat.cpp \
    $${PWD}/OAILocalNetworkGatewayPropertiesFormat_localNetworkAddressSpace.cpp \
    $${PWD}/OAIPfsGroup.cpp \
    $${PWD}/OAITrafficSelectorPolicy.cpp \
    $${PWD}/OAITunnelConnectionHealth.cpp \
    $${PWD}/OAIVirtualNetworkConnectionGatewayReference.cpp \
    $${PWD}/OAIVirtualNetworkGateway.cpp \
    $${PWD}/OAIVirtualNetworkGatewayConnection.cpp \
    $${PWD}/OAIVirtualNetworkGatewayConnectionListEntity.cpp \
    $${PWD}/OAIVirtualNetworkGatewayConnectionListEntityPropertiesFormat.cpp \
    $${PWD}/OAIVirtualNetworkGatewayConnectionListEntityPropertiesFormat_peer.cpp \
    $${PWD}/OAIVirtualNetworkGatewayConnectionListResult.cpp \
    $${PWD}/OAIVirtualNetworkGatewayConnectionPropertiesFormat.cpp \
    $${PWD}/OAIVirtualNetworkGatewayConnectionStatus.cpp \
    $${PWD}/OAIVirtualNetworkGatewayConnectionType.cpp \
    $${PWD}/OAIVirtualNetworkGatewayConnections_StartPacketCapture_default_response.cpp \
    $${PWD}/OAIVirtualNetworkGatewayConnections_StartPacketCapture_default_response_details_inner.cpp \
    $${PWD}/OAIVirtualNetworkGatewayConnections_UpdateTags_request.cpp \
    $${PWD}/OAIVirtualNetworkGatewayIPConfiguration.cpp \
    $${PWD}/OAIVirtualNetworkGatewayIPConfigurationPropertiesFormat.cpp \
    $${PWD}/OAIVirtualNetworkGatewayListConnectionsResult.cpp \
    $${PWD}/OAIVirtualNetworkGatewayListResult.cpp \
    $${PWD}/OAIVirtualNetworkGatewayPropertiesFormat.cpp \
    $${PWD}/OAIVirtualNetworkGatewaySku.cpp \
    $${PWD}/OAIVpnClientConfiguration.cpp \
    $${PWD}/OAIVpnClientConnectionHealthDetail.cpp \
    $${PWD}/OAIVpnClientConnectionHealthDetailListResult.cpp \
    $${PWD}/OAIVpnClientIPsecParameters.cpp \
    $${PWD}/OAIVpnClientParameters.cpp \
    $${PWD}/OAIVpnClientRevokedCertificate.cpp \
    $${PWD}/OAIVpnClientRevokedCertificatePropertiesFormat.cpp \
    $${PWD}/OAIVpnClientRootCertificate.cpp \
    $${PWD}/OAIVpnClientRootCertificatePropertiesFormat.cpp \
    $${PWD}/OAIVpnDeviceScriptParameters.cpp \
    $${PWD}/OAIVpnPacketCaptureStartParameters.cpp \
    $${PWD}/OAIVpnPacketCaptureStopParameters.cpp \
# APIs
    $${PWD}/OAILocalNetworkGatewaysApi.cpp \
    $${PWD}/OAIVirtualNetworkGatewayConnectionsApi.cpp \
    $${PWD}/OAIVirtualNetworkGatewaysApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
