QT += network

HEADERS += \
# Models
    $${PWD}/OAIAction.h \
    $${PWD}/OAIAggregate.h \
    $${PWD}/OAICircuit.h \
    $${PWD}/OAICircuitTermination.h \
    $${PWD}/OAICircuitType.h \
    $${PWD}/OAICircuits_circuit_terminations_list_200_response.h \
    $${PWD}/OAICircuits_circuit_types_list_200_response.h \
    $${PWD}/OAICircuits_circuits_list_200_response.h \
    $${PWD}/OAICircuits_providers_list_200_response.h \
    $${PWD}/OAICluster.h \
    $${PWD}/OAIClusterGroup.h \
    $${PWD}/OAIClusterType.h \
    $${PWD}/OAIConfigContext.h \
    $${PWD}/OAIConnection_status.h \
    $${PWD}/OAIConsolePort.h \
    $${PWD}/OAIConsolePortTemplate.h \
    $${PWD}/OAIConsoleServerPort.h \
    $${PWD}/OAIConsoleServerPortTemplate.h \
    $${PWD}/OAIDcim_console_connections_list_200_response.h \
    $${PWD}/OAIDcim_console_port_templates_list_200_response.h \
    $${PWD}/OAIDcim_console_server_port_templates_list_200_response.h \
    $${PWD}/OAIDcim_console_server_ports_list_200_response.h \
    $${PWD}/OAIDcim_device_bay_templates_list_200_response.h \
    $${PWD}/OAIDcim_device_bays_list_200_response.h \
    $${PWD}/OAIDcim_device_roles_list_200_response.h \
    $${PWD}/OAIDcim_device_types_list_200_response.h \
    $${PWD}/OAIDcim_devices_list_200_response.h \
    $${PWD}/OAIDcim_interface_connections_list_200_response.h \
    $${PWD}/OAIDcim_interface_templates_list_200_response.h \
    $${PWD}/OAIDcim_interfaces_list_200_response.h \
    $${PWD}/OAIDcim_inventory_items_list_200_response.h \
    $${PWD}/OAIDcim_manufacturers_list_200_response.h \
    $${PWD}/OAIDcim_platforms_list_200_response.h \
    $${PWD}/OAIDcim_power_connections_list_200_response.h \
    $${PWD}/OAIDcim_power_outlet_templates_list_200_response.h \
    $${PWD}/OAIDcim_power_outlets_list_200_response.h \
    $${PWD}/OAIDcim_power_port_templates_list_200_response.h \
    $${PWD}/OAIDcim_rack_groups_list_200_response.h \
    $${PWD}/OAIDcim_rack_reservations_list_200_response.h \
    $${PWD}/OAIDcim_rack_roles_list_200_response.h \
    $${PWD}/OAIDcim_racks_list_200_response.h \
    $${PWD}/OAIDcim_regions_list_200_response.h \
    $${PWD}/OAIDcim_sites_list_200_response.h \
    $${PWD}/OAIDcim_virtual_chassis_list_200_response.h \
    $${PWD}/OAIDevice.h \
    $${PWD}/OAIDeviceBay.h \
    $${PWD}/OAIDeviceBayTemplate.h \
    $${PWD}/OAIDeviceIPAddress.h \
    $${PWD}/OAIDeviceRole.h \
    $${PWD}/OAIDeviceType.h \
    $${PWD}/OAIDeviceVirtualChassis.h \
    $${PWD}/OAIDeviceWithConfigContext.h \
    $${PWD}/OAIExportTemplate.h \
    $${PWD}/OAIExtras_config_contexts_list_200_response.h \
    $${PWD}/OAIExtras_export_templates_list_200_response.h \
    $${PWD}/OAIExtras_graphs_list_200_response.h \
    $${PWD}/OAIExtras_image_attachments_list_200_response.h \
    $${PWD}/OAIExtras_object_changes_list_200_response.h \
    $${PWD}/OAIExtras_recent_activity_list_200_response.h \
    $${PWD}/OAIExtras_tags_list_200_response.h \
    $${PWD}/OAIExtras_topology_maps_list_200_response.h \
    $${PWD}/OAIFace.h \
    $${PWD}/OAIForm_factor.h \
    $${PWD}/OAIGraph.h \
    $${PWD}/OAIIPAddress.h \
    $${PWD}/OAIIPAddressInterface.h \
    $${PWD}/OAIImageAttachment.h \
    $${PWD}/OAIInterface.h \
    $${PWD}/OAIInterfaceCircuitTermination.h \
    $${PWD}/OAIInterfaceConnection.h \
    $${PWD}/OAIInterfaceNestedCircuit.h \
    $${PWD}/OAIInterfaceTemplate.h \
    $${PWD}/OAIInterfaceVLAN.h \
    $${PWD}/OAIInterface_ordering.h \
    $${PWD}/OAIInventoryItem.h \
    $${PWD}/OAIIpam_aggregates_list_200_response.h \
    $${PWD}/OAIIpam_ip_addresses_list_200_response.h \
    $${PWD}/OAIIpam_prefixes_list_200_response.h \
    $${PWD}/OAIIpam_rirs_list_200_response.h \
    $${PWD}/OAIIpam_roles_list_200_response.h \
    $${PWD}/OAIIpam_services_list_200_response.h \
    $${PWD}/OAIIpam_vlan_groups_list_200_response.h \
    $${PWD}/OAIIpam_vlans_list_200_response.h \
    $${PWD}/OAIIpam_vrfs_list_200_response.h \
    $${PWD}/OAIManufacturer.h \
    $${PWD}/OAIMode.h \
    $${PWD}/OAINestedCircuit.h \
    $${PWD}/OAINestedCircuitType.h \
    $${PWD}/OAINestedCluster.h \
    $${PWD}/OAINestedClusterGroup.h \
    $${PWD}/OAINestedClusterType.h \
    $${PWD}/OAINestedConsoleServerPort.h \
    $${PWD}/OAINestedDevice.h \
    $${PWD}/OAINestedDeviceRole.h \
    $${PWD}/OAINestedDeviceType.h \
    $${PWD}/OAINestedIPAddress.h \
    $${PWD}/OAINestedInterface.h \
    $${PWD}/OAINestedManufacturer.h \
    $${PWD}/OAINestedPlatform.h \
    $${PWD}/OAINestedPowerOutlet.h \
    $${PWD}/OAINestedProvider.h \
    $${PWD}/OAINestedRIR.h \
    $${PWD}/OAINestedRack.h \
    $${PWD}/OAINestedRackGroup.h \
    $${PWD}/OAINestedRackRole.h \
    $${PWD}/OAINestedRegion.h \
    $${PWD}/OAINestedRole.h \
    $${PWD}/OAINestedSecretRole.h \
    $${PWD}/OAINestedSite.h \
    $${PWD}/OAINestedTenant.h \
    $${PWD}/OAINestedTenantGroup.h \
    $${PWD}/OAINestedUser.h \
    $${PWD}/OAINestedVLAN.h \
    $${PWD}/OAINestedVLANGroup.h \
    $${PWD}/OAINestedVRF.h \
    $${PWD}/OAINestedVirtualMachine.h \
    $${PWD}/OAIObjectChange.h \
    $${PWD}/OAIPlatform.h \
    $${PWD}/OAIPowerOutlet.h \
    $${PWD}/OAIPowerOutletTemplate.h \
    $${PWD}/OAIPowerPort.h \
    $${PWD}/OAIPowerPortTemplate.h \
    $${PWD}/OAIPrefix.h \
    $${PWD}/OAIProtocol.h \
    $${PWD}/OAIProvider.h \
    $${PWD}/OAIRIR.h \
    $${PWD}/OAIRack.h \
    $${PWD}/OAIRackGroup.h \
    $${PWD}/OAIRackReservation.h \
    $${PWD}/OAIRackRole.h \
    $${PWD}/OAIRegion.h \
    $${PWD}/OAIRole.h \
    $${PWD}/OAIRole_1.h \
    $${PWD}/OAISecret.h \
    $${PWD}/OAISecretRole.h \
    $${PWD}/OAISecrets_secret_roles_list_200_response.h \
    $${PWD}/OAISecrets_secrets_list_200_response.h \
    $${PWD}/OAIService.h \
    $${PWD}/OAISite.h \
    $${PWD}/OAIStatus.h \
    $${PWD}/OAISubdevice_role.h \
    $${PWD}/OAITag.h \
    $${PWD}/OAITenancy_tenant_groups_list_200_response.h \
    $${PWD}/OAITenancy_tenants_list_200_response.h \
    $${PWD}/OAITenant.h \
    $${PWD}/OAITenantGroup.h \
    $${PWD}/OAITopologyMap.h \
    $${PWD}/OAIType.h \
    $${PWD}/OAIUserAction.h \
    $${PWD}/OAIVLAN.h \
    $${PWD}/OAIVLANGroup.h \
    $${PWD}/OAIVRF.h \
    $${PWD}/OAIVirtualChassis.h \
    $${PWD}/OAIVirtualMachine.h \
    $${PWD}/OAIVirtualMachineIPAddress.h \
    $${PWD}/OAIVirtualMachineWithConfigContext.h \
    $${PWD}/OAIVirtualization_cluster_groups_list_200_response.h \
    $${PWD}/OAIVirtualization_cluster_types_list_200_response.h \
    $${PWD}/OAIVirtualization_clusters_list_200_response.h \
    $${PWD}/OAIVirtualization_virtual_machines_list_200_response.h \
    $${PWD}/OAIWidth.h \
    $${PWD}/OAIWritableAggregate.h \
    $${PWD}/OAIWritableCircuit.h \
    $${PWD}/OAIWritableCircuitTermination.h \
    $${PWD}/OAIWritableCluster.h \
    $${PWD}/OAIWritableConfigContext.h \
    $${PWD}/OAIWritableConsolePort.h \
    $${PWD}/OAIWritableConsolePortTemplate.h \
    $${PWD}/OAIWritableConsoleServerPort.h \
    $${PWD}/OAIWritableConsoleServerPortTemplate.h \
    $${PWD}/OAIWritableDevice.h \
    $${PWD}/OAIWritableDeviceBay.h \
    $${PWD}/OAIWritableDeviceBayTemplate.h \
    $${PWD}/OAIWritableDeviceType.h \
    $${PWD}/OAIWritableGraph.h \
    $${PWD}/OAIWritableIPAddress.h \
    $${PWD}/OAIWritableInterface.h \
    $${PWD}/OAIWritableInterfaceConnection.h \
    $${PWD}/OAIWritableInterfaceTemplate.h \
    $${PWD}/OAIWritableInventoryItem.h \
    $${PWD}/OAIWritablePlatform.h \
    $${PWD}/OAIWritablePowerOutlet.h \
    $${PWD}/OAIWritablePowerOutletTemplate.h \
    $${PWD}/OAIWritablePowerPort.h \
    $${PWD}/OAIWritablePowerPortTemplate.h \
    $${PWD}/OAIWritablePrefix.h \
    $${PWD}/OAIWritableRack.h \
    $${PWD}/OAIWritableRackGroup.h \
    $${PWD}/OAIWritableRackReservation.h \
    $${PWD}/OAIWritableRegion.h \
    $${PWD}/OAIWritableSecret.h \
    $${PWD}/OAIWritableService.h \
    $${PWD}/OAIWritableSite.h \
    $${PWD}/OAIWritableTenant.h \
    $${PWD}/OAIWritableTopologyMap.h \
    $${PWD}/OAIWritableVLAN.h \
    $${PWD}/OAIWritableVLANGroup.h \
    $${PWD}/OAIWritableVRF.h \
    $${PWD}/OAIWritableVirtualChassis.h \
    $${PWD}/OAIWritableVirtualMachine.h \
# APIs
    $${PWD}/OAICircuitsApi.h \
    $${PWD}/OAIDcimApi.h \
    $${PWD}/OAIExtrasApi.h \
    $${PWD}/OAIIpamApi.h \
    $${PWD}/OAISecretsApi.h \
    $${PWD}/OAITenancyApi.h \
    $${PWD}/OAIVirtualizationApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAction.cpp \
    $${PWD}/OAIAggregate.cpp \
    $${PWD}/OAICircuit.cpp \
    $${PWD}/OAICircuitTermination.cpp \
    $${PWD}/OAICircuitType.cpp \
    $${PWD}/OAICircuits_circuit_terminations_list_200_response.cpp \
    $${PWD}/OAICircuits_circuit_types_list_200_response.cpp \
    $${PWD}/OAICircuits_circuits_list_200_response.cpp \
    $${PWD}/OAICircuits_providers_list_200_response.cpp \
    $${PWD}/OAICluster.cpp \
    $${PWD}/OAIClusterGroup.cpp \
    $${PWD}/OAIClusterType.cpp \
    $${PWD}/OAIConfigContext.cpp \
    $${PWD}/OAIConnection_status.cpp \
    $${PWD}/OAIConsolePort.cpp \
    $${PWD}/OAIConsolePortTemplate.cpp \
    $${PWD}/OAIConsoleServerPort.cpp \
    $${PWD}/OAIConsoleServerPortTemplate.cpp \
    $${PWD}/OAIDcim_console_connections_list_200_response.cpp \
    $${PWD}/OAIDcim_console_port_templates_list_200_response.cpp \
    $${PWD}/OAIDcim_console_server_port_templates_list_200_response.cpp \
    $${PWD}/OAIDcim_console_server_ports_list_200_response.cpp \
    $${PWD}/OAIDcim_device_bay_templates_list_200_response.cpp \
    $${PWD}/OAIDcim_device_bays_list_200_response.cpp \
    $${PWD}/OAIDcim_device_roles_list_200_response.cpp \
    $${PWD}/OAIDcim_device_types_list_200_response.cpp \
    $${PWD}/OAIDcim_devices_list_200_response.cpp \
    $${PWD}/OAIDcim_interface_connections_list_200_response.cpp \
    $${PWD}/OAIDcim_interface_templates_list_200_response.cpp \
    $${PWD}/OAIDcim_interfaces_list_200_response.cpp \
    $${PWD}/OAIDcim_inventory_items_list_200_response.cpp \
    $${PWD}/OAIDcim_manufacturers_list_200_response.cpp \
    $${PWD}/OAIDcim_platforms_list_200_response.cpp \
    $${PWD}/OAIDcim_power_connections_list_200_response.cpp \
    $${PWD}/OAIDcim_power_outlet_templates_list_200_response.cpp \
    $${PWD}/OAIDcim_power_outlets_list_200_response.cpp \
    $${PWD}/OAIDcim_power_port_templates_list_200_response.cpp \
    $${PWD}/OAIDcim_rack_groups_list_200_response.cpp \
    $${PWD}/OAIDcim_rack_reservations_list_200_response.cpp \
    $${PWD}/OAIDcim_rack_roles_list_200_response.cpp \
    $${PWD}/OAIDcim_racks_list_200_response.cpp \
    $${PWD}/OAIDcim_regions_list_200_response.cpp \
    $${PWD}/OAIDcim_sites_list_200_response.cpp \
    $${PWD}/OAIDcim_virtual_chassis_list_200_response.cpp \
    $${PWD}/OAIDevice.cpp \
    $${PWD}/OAIDeviceBay.cpp \
    $${PWD}/OAIDeviceBayTemplate.cpp \
    $${PWD}/OAIDeviceIPAddress.cpp \
    $${PWD}/OAIDeviceRole.cpp \
    $${PWD}/OAIDeviceType.cpp \
    $${PWD}/OAIDeviceVirtualChassis.cpp \
    $${PWD}/OAIDeviceWithConfigContext.cpp \
    $${PWD}/OAIExportTemplate.cpp \
    $${PWD}/OAIExtras_config_contexts_list_200_response.cpp \
    $${PWD}/OAIExtras_export_templates_list_200_response.cpp \
    $${PWD}/OAIExtras_graphs_list_200_response.cpp \
    $${PWD}/OAIExtras_image_attachments_list_200_response.cpp \
    $${PWD}/OAIExtras_object_changes_list_200_response.cpp \
    $${PWD}/OAIExtras_recent_activity_list_200_response.cpp \
    $${PWD}/OAIExtras_tags_list_200_response.cpp \
    $${PWD}/OAIExtras_topology_maps_list_200_response.cpp \
    $${PWD}/OAIFace.cpp \
    $${PWD}/OAIForm_factor.cpp \
    $${PWD}/OAIGraph.cpp \
    $${PWD}/OAIIPAddress.cpp \
    $${PWD}/OAIIPAddressInterface.cpp \
    $${PWD}/OAIImageAttachment.cpp \
    $${PWD}/OAIInterface.cpp \
    $${PWD}/OAIInterfaceCircuitTermination.cpp \
    $${PWD}/OAIInterfaceConnection.cpp \
    $${PWD}/OAIInterfaceNestedCircuit.cpp \
    $${PWD}/OAIInterfaceTemplate.cpp \
    $${PWD}/OAIInterfaceVLAN.cpp \
    $${PWD}/OAIInterface_ordering.cpp \
    $${PWD}/OAIInventoryItem.cpp \
    $${PWD}/OAIIpam_aggregates_list_200_response.cpp \
    $${PWD}/OAIIpam_ip_addresses_list_200_response.cpp \
    $${PWD}/OAIIpam_prefixes_list_200_response.cpp \
    $${PWD}/OAIIpam_rirs_list_200_response.cpp \
    $${PWD}/OAIIpam_roles_list_200_response.cpp \
    $${PWD}/OAIIpam_services_list_200_response.cpp \
    $${PWD}/OAIIpam_vlan_groups_list_200_response.cpp \
    $${PWD}/OAIIpam_vlans_list_200_response.cpp \
    $${PWD}/OAIIpam_vrfs_list_200_response.cpp \
    $${PWD}/OAIManufacturer.cpp \
    $${PWD}/OAIMode.cpp \
    $${PWD}/OAINestedCircuit.cpp \
    $${PWD}/OAINestedCircuitType.cpp \
    $${PWD}/OAINestedCluster.cpp \
    $${PWD}/OAINestedClusterGroup.cpp \
    $${PWD}/OAINestedClusterType.cpp \
    $${PWD}/OAINestedConsoleServerPort.cpp \
    $${PWD}/OAINestedDevice.cpp \
    $${PWD}/OAINestedDeviceRole.cpp \
    $${PWD}/OAINestedDeviceType.cpp \
    $${PWD}/OAINestedIPAddress.cpp \
    $${PWD}/OAINestedInterface.cpp \
    $${PWD}/OAINestedManufacturer.cpp \
    $${PWD}/OAINestedPlatform.cpp \
    $${PWD}/OAINestedPowerOutlet.cpp \
    $${PWD}/OAINestedProvider.cpp \
    $${PWD}/OAINestedRIR.cpp \
    $${PWD}/OAINestedRack.cpp \
    $${PWD}/OAINestedRackGroup.cpp \
    $${PWD}/OAINestedRackRole.cpp \
    $${PWD}/OAINestedRegion.cpp \
    $${PWD}/OAINestedRole.cpp \
    $${PWD}/OAINestedSecretRole.cpp \
    $${PWD}/OAINestedSite.cpp \
    $${PWD}/OAINestedTenant.cpp \
    $${PWD}/OAINestedTenantGroup.cpp \
    $${PWD}/OAINestedUser.cpp \
    $${PWD}/OAINestedVLAN.cpp \
    $${PWD}/OAINestedVLANGroup.cpp \
    $${PWD}/OAINestedVRF.cpp \
    $${PWD}/OAINestedVirtualMachine.cpp \
    $${PWD}/OAIObjectChange.cpp \
    $${PWD}/OAIPlatform.cpp \
    $${PWD}/OAIPowerOutlet.cpp \
    $${PWD}/OAIPowerOutletTemplate.cpp \
    $${PWD}/OAIPowerPort.cpp \
    $${PWD}/OAIPowerPortTemplate.cpp \
    $${PWD}/OAIPrefix.cpp \
    $${PWD}/OAIProtocol.cpp \
    $${PWD}/OAIProvider.cpp \
    $${PWD}/OAIRIR.cpp \
    $${PWD}/OAIRack.cpp \
    $${PWD}/OAIRackGroup.cpp \
    $${PWD}/OAIRackReservation.cpp \
    $${PWD}/OAIRackRole.cpp \
    $${PWD}/OAIRegion.cpp \
    $${PWD}/OAIRole.cpp \
    $${PWD}/OAIRole_1.cpp \
    $${PWD}/OAISecret.cpp \
    $${PWD}/OAISecretRole.cpp \
    $${PWD}/OAISecrets_secret_roles_list_200_response.cpp \
    $${PWD}/OAISecrets_secrets_list_200_response.cpp \
    $${PWD}/OAIService.cpp \
    $${PWD}/OAISite.cpp \
    $${PWD}/OAIStatus.cpp \
    $${PWD}/OAISubdevice_role.cpp \
    $${PWD}/OAITag.cpp \
    $${PWD}/OAITenancy_tenant_groups_list_200_response.cpp \
    $${PWD}/OAITenancy_tenants_list_200_response.cpp \
    $${PWD}/OAITenant.cpp \
    $${PWD}/OAITenantGroup.cpp \
    $${PWD}/OAITopologyMap.cpp \
    $${PWD}/OAIType.cpp \
    $${PWD}/OAIUserAction.cpp \
    $${PWD}/OAIVLAN.cpp \
    $${PWD}/OAIVLANGroup.cpp \
    $${PWD}/OAIVRF.cpp \
    $${PWD}/OAIVirtualChassis.cpp \
    $${PWD}/OAIVirtualMachine.cpp \
    $${PWD}/OAIVirtualMachineIPAddress.cpp \
    $${PWD}/OAIVirtualMachineWithConfigContext.cpp \
    $${PWD}/OAIVirtualization_cluster_groups_list_200_response.cpp \
    $${PWD}/OAIVirtualization_cluster_types_list_200_response.cpp \
    $${PWD}/OAIVirtualization_clusters_list_200_response.cpp \
    $${PWD}/OAIVirtualization_virtual_machines_list_200_response.cpp \
    $${PWD}/OAIWidth.cpp \
    $${PWD}/OAIWritableAggregate.cpp \
    $${PWD}/OAIWritableCircuit.cpp \
    $${PWD}/OAIWritableCircuitTermination.cpp \
    $${PWD}/OAIWritableCluster.cpp \
    $${PWD}/OAIWritableConfigContext.cpp \
    $${PWD}/OAIWritableConsolePort.cpp \
    $${PWD}/OAIWritableConsolePortTemplate.cpp \
    $${PWD}/OAIWritableConsoleServerPort.cpp \
    $${PWD}/OAIWritableConsoleServerPortTemplate.cpp \
    $${PWD}/OAIWritableDevice.cpp \
    $${PWD}/OAIWritableDeviceBay.cpp \
    $${PWD}/OAIWritableDeviceBayTemplate.cpp \
    $${PWD}/OAIWritableDeviceType.cpp \
    $${PWD}/OAIWritableGraph.cpp \
    $${PWD}/OAIWritableIPAddress.cpp \
    $${PWD}/OAIWritableInterface.cpp \
    $${PWD}/OAIWritableInterfaceConnection.cpp \
    $${PWD}/OAIWritableInterfaceTemplate.cpp \
    $${PWD}/OAIWritableInventoryItem.cpp \
    $${PWD}/OAIWritablePlatform.cpp \
    $${PWD}/OAIWritablePowerOutlet.cpp \
    $${PWD}/OAIWritablePowerOutletTemplate.cpp \
    $${PWD}/OAIWritablePowerPort.cpp \
    $${PWD}/OAIWritablePowerPortTemplate.cpp \
    $${PWD}/OAIWritablePrefix.cpp \
    $${PWD}/OAIWritableRack.cpp \
    $${PWD}/OAIWritableRackGroup.cpp \
    $${PWD}/OAIWritableRackReservation.cpp \
    $${PWD}/OAIWritableRegion.cpp \
    $${PWD}/OAIWritableSecret.cpp \
    $${PWD}/OAIWritableService.cpp \
    $${PWD}/OAIWritableSite.cpp \
    $${PWD}/OAIWritableTenant.cpp \
    $${PWD}/OAIWritableTopologyMap.cpp \
    $${PWD}/OAIWritableVLAN.cpp \
    $${PWD}/OAIWritableVLANGroup.cpp \
    $${PWD}/OAIWritableVRF.cpp \
    $${PWD}/OAIWritableVirtualChassis.cpp \
    $${PWD}/OAIWritableVirtualMachine.cpp \
# APIs
    $${PWD}/OAICircuitsApi.cpp \
    $${PWD}/OAIDcimApi.cpp \
    $${PWD}/OAIExtrasApi.cpp \
    $${PWD}/OAIIpamApi.cpp \
    $${PWD}/OAISecretsApi.cpp \
    $${PWD}/OAITenancyApi.cpp \
    $${PWD}/OAIVirtualizationApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
