/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.8.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * APIStatusAppVersion
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-12T09:56:47.661723-04:00[America/New_York]", comments = "Generator version: 7.9.0")
public class APIStatusAppVersion {
  public static final String SERIALIZED_NAME_LATEST_APP_VERSION = "latest_app_version";
  @SerializedName(SERIALIZED_NAME_LATEST_APP_VERSION)
  private Integer latestAppVersion;

  public static final String SERIALIZED_NAME_MIN_APP_VERSION = "min_app_version";
  @SerializedName(SERIALIZED_NAME_MIN_APP_VERSION)
  private Integer minAppVersion;

  public APIStatusAppVersion() {
  }

  public APIStatusAppVersion latestAppVersion(Integer latestAppVersion) {
    this.latestAppVersion = latestAppVersion;
    return this;
  }

  /**
   * Internal use - Latest application version available.
   * @return latestAppVersion
   */
  @javax.annotation.Nonnull
  public Integer getLatestAppVersion() {
    return latestAppVersion;
  }

  public void setLatestAppVersion(Integer latestAppVersion) {
    this.latestAppVersion = latestAppVersion;
  }


  public APIStatusAppVersion minAppVersion(Integer minAppVersion) {
    this.minAppVersion = minAppVersion;
    return this;
  }

  /**
   * Internal use - Minimum application version required to correctly connect and process data.
   * @return minAppVersion
   */
  @javax.annotation.Nonnull
  public Integer getMinAppVersion() {
    return minAppVersion;
  }

  public void setMinAppVersion(Integer minAppVersion) {
    this.minAppVersion = minAppVersion;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIStatusAppVersion apIStatusAppVersion = (APIStatusAppVersion) o;
    return Objects.equals(this.latestAppVersion, apIStatusAppVersion.latestAppVersion) &&
        Objects.equals(this.minAppVersion, apIStatusAppVersion.minAppVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(latestAppVersion, minAppVersion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIStatusAppVersion {\n");
    sb.append("    latestAppVersion: ").append(toIndentedString(latestAppVersion)).append("\n");
    sb.append("    minAppVersion: ").append(toIndentedString(minAppVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("latest_app_version");
    openapiFields.add("min_app_version");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("latest_app_version");
    openapiRequiredFields.add("min_app_version");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to APIStatusAppVersion
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!APIStatusAppVersion.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in APIStatusAppVersion is not found in the empty JSON string", APIStatusAppVersion.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!APIStatusAppVersion.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `APIStatusAppVersion` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : APIStatusAppVersion.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!APIStatusAppVersion.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'APIStatusAppVersion' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<APIStatusAppVersion> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(APIStatusAppVersion.class));

       return (TypeAdapter<T>) new TypeAdapter<APIStatusAppVersion>() {
           @Override
           public void write(JsonWriter out, APIStatusAppVersion value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public APIStatusAppVersion read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of APIStatusAppVersion given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of APIStatusAppVersion
   * @throws IOException if the JSON string is invalid with respect to APIStatusAppVersion
   */
  public static APIStatusAppVersion fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, APIStatusAppVersion.class);
  }

  /**
   * Convert an instance of APIStatusAppVersion to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

