QT += network

HEADERS += \
# Models
    $${PWD}/OAIAccountAttribute.h \
    $${PWD}/OAIAccountAttributeName.h \
    $${PWD}/OAIAccountLimit.h \
    $${PWD}/OAIAccountLimitName.h \
    $${PWD}/OAIAssociateOriginationIdentityRequest.h \
    $${PWD}/OAIAssociateOriginationIdentityResult.h \
    $${PWD}/OAICloudWatchLogsDestination.h \
    $${PWD}/OAIConfigurationSetFilter.h \
    $${PWD}/OAIConfigurationSetFilterName.h \
    $${PWD}/OAIConfigurationSetInformation.h \
    $${PWD}/OAICreateConfigurationSetRequest.h \
    $${PWD}/OAICreateConfigurationSetResult.h \
    $${PWD}/OAICreateEventDestinationRequest.h \
    $${PWD}/OAICreateEventDestinationRequest_CloudWatchLogsDestination.h \
    $${PWD}/OAICreateEventDestinationRequest_KinesisFirehoseDestination.h \
    $${PWD}/OAICreateEventDestinationRequest_SnsDestination.h \
    $${PWD}/OAICreateEventDestinationResult.h \
    $${PWD}/OAICreateEventDestinationResult_EventDestination.h \
    $${PWD}/OAICreateOptOutListRequest.h \
    $${PWD}/OAICreateOptOutListResult.h \
    $${PWD}/OAICreatePoolRequest.h \
    $${PWD}/OAICreatePoolResult.h \
    $${PWD}/OAIDeleteConfigurationSetRequest.h \
    $${PWD}/OAIDeleteConfigurationSetResult.h \
    $${PWD}/OAIDeleteDefaultMessageTypeRequest.h \
    $${PWD}/OAIDeleteDefaultMessageTypeResult.h \
    $${PWD}/OAIDeleteDefaultSenderIdRequest.h \
    $${PWD}/OAIDeleteDefaultSenderIdResult.h \
    $${PWD}/OAIDeleteEventDestinationRequest.h \
    $${PWD}/OAIDeleteEventDestinationResult.h \
    $${PWD}/OAIDeleteEventDestinationResult_EventDestination.h \
    $${PWD}/OAIDeleteKeywordRequest.h \
    $${PWD}/OAIDeleteKeywordResult.h \
    $${PWD}/OAIDeleteOptOutListRequest.h \
    $${PWD}/OAIDeleteOptOutListResult.h \
    $${PWD}/OAIDeleteOptedOutNumberRequest.h \
    $${PWD}/OAIDeleteOptedOutNumberResult.h \
    $${PWD}/OAIDeletePoolRequest.h \
    $${PWD}/OAIDeletePoolResult.h \
    $${PWD}/OAIDeleteTextMessageSpendLimitOverrideResult.h \
    $${PWD}/OAIDeleteVoiceMessageSpendLimitOverrideResult.h \
    $${PWD}/OAIDescribeAccountAttributesRequest.h \
    $${PWD}/OAIDescribeAccountAttributesResult.h \
    $${PWD}/OAIDescribeAccountLimitsRequest.h \
    $${PWD}/OAIDescribeAccountLimitsResult.h \
    $${PWD}/OAIDescribeConfigurationSetsRequest.h \
    $${PWD}/OAIDescribeConfigurationSetsResult.h \
    $${PWD}/OAIDescribeKeywordsRequest.h \
    $${PWD}/OAIDescribeKeywordsResult.h \
    $${PWD}/OAIDescribeOptOutListsRequest.h \
    $${PWD}/OAIDescribeOptOutListsResult.h \
    $${PWD}/OAIDescribeOptedOutNumbersRequest.h \
    $${PWD}/OAIDescribeOptedOutNumbersResult.h \
    $${PWD}/OAIDescribePhoneNumbersRequest.h \
    $${PWD}/OAIDescribePhoneNumbersResult.h \
    $${PWD}/OAIDescribePoolsRequest.h \
    $${PWD}/OAIDescribePoolsResult.h \
    $${PWD}/OAIDescribeSenderIdsRequest.h \
    $${PWD}/OAIDescribeSenderIdsResult.h \
    $${PWD}/OAIDescribeSpendLimitsRequest.h \
    $${PWD}/OAIDescribeSpendLimitsResult.h \
    $${PWD}/OAIDestinationCountryParameterKey.h \
    $${PWD}/OAIDisassociateOriginationIdentityRequest.h \
    $${PWD}/OAIDisassociateOriginationIdentityResult.h \
    $${PWD}/OAIEventDestination.h \
    $${PWD}/OAIEventDestination_CloudWatchLogsDestination.h \
    $${PWD}/OAIEventDestination_SnsDestination.h \
    $${PWD}/OAIEventType.h \
    $${PWD}/OAIKeywordAction.h \
    $${PWD}/OAIKeywordFilter.h \
    $${PWD}/OAIKeywordFilterName.h \
    $${PWD}/OAIKeywordInformation.h \
    $${PWD}/OAIKinesisFirehoseDestination.h \
    $${PWD}/OAIListPoolOriginationIdentitiesRequest.h \
    $${PWD}/OAIListPoolOriginationIdentitiesResult.h \
    $${PWD}/OAIListTagsForResourceRequest.h \
    $${PWD}/OAIListTagsForResourceResult.h \
    $${PWD}/OAIMessageType.h \
    $${PWD}/OAINumberCapability.h \
    $${PWD}/OAINumberStatus.h \
    $${PWD}/OAINumberType.h \
    $${PWD}/OAIOptOutListInformation.h \
    $${PWD}/OAIOptedOutFilter.h \
    $${PWD}/OAIOptedOutFilterName.h \
    $${PWD}/OAIOptedOutNumberInformation.h \
    $${PWD}/OAIOriginationIdentityMetadata.h \
    $${PWD}/OAIPhoneNumberFilter.h \
    $${PWD}/OAIPhoneNumberFilterName.h \
    $${PWD}/OAIPhoneNumberInformation.h \
    $${PWD}/OAIPoolFilter.h \
    $${PWD}/OAIPoolFilterName.h \
    $${PWD}/OAIPoolInformation.h \
    $${PWD}/OAIPoolOriginationIdentitiesFilter.h \
    $${PWD}/OAIPoolOriginationIdentitiesFilterName.h \
    $${PWD}/OAIPoolStatus.h \
    $${PWD}/OAIPutKeywordRequest.h \
    $${PWD}/OAIPutKeywordResult.h \
    $${PWD}/OAIPutOptedOutNumberRequest.h \
    $${PWD}/OAIPutOptedOutNumberResult.h \
    $${PWD}/OAIReleasePhoneNumberRequest.h \
    $${PWD}/OAIReleasePhoneNumberResult.h \
    $${PWD}/OAIRequestPhoneNumberRequest.h \
    $${PWD}/OAIRequestPhoneNumberResult.h \
    $${PWD}/OAIRequestableNumberType.h \
    $${PWD}/OAISendTextMessageRequest.h \
    $${PWD}/OAISendTextMessageResult.h \
    $${PWD}/OAISendVoiceMessageRequest.h \
    $${PWD}/OAISendVoiceMessageResult.h \
    $${PWD}/OAISenderIdAndCountry.h \
    $${PWD}/OAISenderIdFilter.h \
    $${PWD}/OAISenderIdFilterName.h \
    $${PWD}/OAISenderIdInformation.h \
    $${PWD}/OAISetDefaultMessageTypeRequest.h \
    $${PWD}/OAISetDefaultMessageTypeResult.h \
    $${PWD}/OAISetDefaultSenderIdRequest.h \
    $${PWD}/OAISetDefaultSenderIdResult.h \
    $${PWD}/OAISetTextMessageSpendLimitOverrideRequest.h \
    $${PWD}/OAISetTextMessageSpendLimitOverrideResult.h \
    $${PWD}/OAISetVoiceMessageSpendLimitOverrideRequest.h \
    $${PWD}/OAISetVoiceMessageSpendLimitOverrideResult.h \
    $${PWD}/OAISnsDestination.h \
    $${PWD}/OAISpendLimit.h \
    $${PWD}/OAISpendLimitName.h \
    $${PWD}/OAITag.h \
    $${PWD}/OAITagResourceRequest.h \
    $${PWD}/OAIUntagResourceRequest.h \
    $${PWD}/OAIUpdateEventDestinationRequest.h \
    $${PWD}/OAIUpdateEventDestinationRequest_CloudWatchLogsDestination.h \
    $${PWD}/OAIUpdateEventDestinationRequest_KinesisFirehoseDestination.h \
    $${PWD}/OAIUpdateEventDestinationRequest_SnsDestination.h \
    $${PWD}/OAIUpdateEventDestinationResult.h \
    $${PWD}/OAIUpdateEventDestinationResult_EventDestination.h \
    $${PWD}/OAIUpdatePhoneNumberRequest.h \
    $${PWD}/OAIUpdatePhoneNumberResult.h \
    $${PWD}/OAIUpdatePoolRequest.h \
    $${PWD}/OAIUpdatePoolResult.h \
    $${PWD}/OAIVoiceId.h \
    $${PWD}/OAIVoiceMessageBodyTextType.h \
# APIs
    $${PWD}/OAIDefaultApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAccountAttribute.cpp \
    $${PWD}/OAIAccountAttributeName.cpp \
    $${PWD}/OAIAccountLimit.cpp \
    $${PWD}/OAIAccountLimitName.cpp \
    $${PWD}/OAIAssociateOriginationIdentityRequest.cpp \
    $${PWD}/OAIAssociateOriginationIdentityResult.cpp \
    $${PWD}/OAICloudWatchLogsDestination.cpp \
    $${PWD}/OAIConfigurationSetFilter.cpp \
    $${PWD}/OAIConfigurationSetFilterName.cpp \
    $${PWD}/OAIConfigurationSetInformation.cpp \
    $${PWD}/OAICreateConfigurationSetRequest.cpp \
    $${PWD}/OAICreateConfigurationSetResult.cpp \
    $${PWD}/OAICreateEventDestinationRequest.cpp \
    $${PWD}/OAICreateEventDestinationRequest_CloudWatchLogsDestination.cpp \
    $${PWD}/OAICreateEventDestinationRequest_KinesisFirehoseDestination.cpp \
    $${PWD}/OAICreateEventDestinationRequest_SnsDestination.cpp \
    $${PWD}/OAICreateEventDestinationResult.cpp \
    $${PWD}/OAICreateEventDestinationResult_EventDestination.cpp \
    $${PWD}/OAICreateOptOutListRequest.cpp \
    $${PWD}/OAICreateOptOutListResult.cpp \
    $${PWD}/OAICreatePoolRequest.cpp \
    $${PWD}/OAICreatePoolResult.cpp \
    $${PWD}/OAIDeleteConfigurationSetRequest.cpp \
    $${PWD}/OAIDeleteConfigurationSetResult.cpp \
    $${PWD}/OAIDeleteDefaultMessageTypeRequest.cpp \
    $${PWD}/OAIDeleteDefaultMessageTypeResult.cpp \
    $${PWD}/OAIDeleteDefaultSenderIdRequest.cpp \
    $${PWD}/OAIDeleteDefaultSenderIdResult.cpp \
    $${PWD}/OAIDeleteEventDestinationRequest.cpp \
    $${PWD}/OAIDeleteEventDestinationResult.cpp \
    $${PWD}/OAIDeleteEventDestinationResult_EventDestination.cpp \
    $${PWD}/OAIDeleteKeywordRequest.cpp \
    $${PWD}/OAIDeleteKeywordResult.cpp \
    $${PWD}/OAIDeleteOptOutListRequest.cpp \
    $${PWD}/OAIDeleteOptOutListResult.cpp \
    $${PWD}/OAIDeleteOptedOutNumberRequest.cpp \
    $${PWD}/OAIDeleteOptedOutNumberResult.cpp \
    $${PWD}/OAIDeletePoolRequest.cpp \
    $${PWD}/OAIDeletePoolResult.cpp \
    $${PWD}/OAIDeleteTextMessageSpendLimitOverrideResult.cpp \
    $${PWD}/OAIDeleteVoiceMessageSpendLimitOverrideResult.cpp \
    $${PWD}/OAIDescribeAccountAttributesRequest.cpp \
    $${PWD}/OAIDescribeAccountAttributesResult.cpp \
    $${PWD}/OAIDescribeAccountLimitsRequest.cpp \
    $${PWD}/OAIDescribeAccountLimitsResult.cpp \
    $${PWD}/OAIDescribeConfigurationSetsRequest.cpp \
    $${PWD}/OAIDescribeConfigurationSetsResult.cpp \
    $${PWD}/OAIDescribeKeywordsRequest.cpp \
    $${PWD}/OAIDescribeKeywordsResult.cpp \
    $${PWD}/OAIDescribeOptOutListsRequest.cpp \
    $${PWD}/OAIDescribeOptOutListsResult.cpp \
    $${PWD}/OAIDescribeOptedOutNumbersRequest.cpp \
    $${PWD}/OAIDescribeOptedOutNumbersResult.cpp \
    $${PWD}/OAIDescribePhoneNumbersRequest.cpp \
    $${PWD}/OAIDescribePhoneNumbersResult.cpp \
    $${PWD}/OAIDescribePoolsRequest.cpp \
    $${PWD}/OAIDescribePoolsResult.cpp \
    $${PWD}/OAIDescribeSenderIdsRequest.cpp \
    $${PWD}/OAIDescribeSenderIdsResult.cpp \
    $${PWD}/OAIDescribeSpendLimitsRequest.cpp \
    $${PWD}/OAIDescribeSpendLimitsResult.cpp \
    $${PWD}/OAIDestinationCountryParameterKey.cpp \
    $${PWD}/OAIDisassociateOriginationIdentityRequest.cpp \
    $${PWD}/OAIDisassociateOriginationIdentityResult.cpp \
    $${PWD}/OAIEventDestination.cpp \
    $${PWD}/OAIEventDestination_CloudWatchLogsDestination.cpp \
    $${PWD}/OAIEventDestination_SnsDestination.cpp \
    $${PWD}/OAIEventType.cpp \
    $${PWD}/OAIKeywordAction.cpp \
    $${PWD}/OAIKeywordFilter.cpp \
    $${PWD}/OAIKeywordFilterName.cpp \
    $${PWD}/OAIKeywordInformation.cpp \
    $${PWD}/OAIKinesisFirehoseDestination.cpp \
    $${PWD}/OAIListPoolOriginationIdentitiesRequest.cpp \
    $${PWD}/OAIListPoolOriginationIdentitiesResult.cpp \
    $${PWD}/OAIListTagsForResourceRequest.cpp \
    $${PWD}/OAIListTagsForResourceResult.cpp \
    $${PWD}/OAIMessageType.cpp \
    $${PWD}/OAINumberCapability.cpp \
    $${PWD}/OAINumberStatus.cpp \
    $${PWD}/OAINumberType.cpp \
    $${PWD}/OAIOptOutListInformation.cpp \
    $${PWD}/OAIOptedOutFilter.cpp \
    $${PWD}/OAIOptedOutFilterName.cpp \
    $${PWD}/OAIOptedOutNumberInformation.cpp \
    $${PWD}/OAIOriginationIdentityMetadata.cpp \
    $${PWD}/OAIPhoneNumberFilter.cpp \
    $${PWD}/OAIPhoneNumberFilterName.cpp \
    $${PWD}/OAIPhoneNumberInformation.cpp \
    $${PWD}/OAIPoolFilter.cpp \
    $${PWD}/OAIPoolFilterName.cpp \
    $${PWD}/OAIPoolInformation.cpp \
    $${PWD}/OAIPoolOriginationIdentitiesFilter.cpp \
    $${PWD}/OAIPoolOriginationIdentitiesFilterName.cpp \
    $${PWD}/OAIPoolStatus.cpp \
    $${PWD}/OAIPutKeywordRequest.cpp \
    $${PWD}/OAIPutKeywordResult.cpp \
    $${PWD}/OAIPutOptedOutNumberRequest.cpp \
    $${PWD}/OAIPutOptedOutNumberResult.cpp \
    $${PWD}/OAIReleasePhoneNumberRequest.cpp \
    $${PWD}/OAIReleasePhoneNumberResult.cpp \
    $${PWD}/OAIRequestPhoneNumberRequest.cpp \
    $${PWD}/OAIRequestPhoneNumberResult.cpp \
    $${PWD}/OAIRequestableNumberType.cpp \
    $${PWD}/OAISendTextMessageRequest.cpp \
    $${PWD}/OAISendTextMessageResult.cpp \
    $${PWD}/OAISendVoiceMessageRequest.cpp \
    $${PWD}/OAISendVoiceMessageResult.cpp \
    $${PWD}/OAISenderIdAndCountry.cpp \
    $${PWD}/OAISenderIdFilter.cpp \
    $${PWD}/OAISenderIdFilterName.cpp \
    $${PWD}/OAISenderIdInformation.cpp \
    $${PWD}/OAISetDefaultMessageTypeRequest.cpp \
    $${PWD}/OAISetDefaultMessageTypeResult.cpp \
    $${PWD}/OAISetDefaultSenderIdRequest.cpp \
    $${PWD}/OAISetDefaultSenderIdResult.cpp \
    $${PWD}/OAISetTextMessageSpendLimitOverrideRequest.cpp \
    $${PWD}/OAISetTextMessageSpendLimitOverrideResult.cpp \
    $${PWD}/OAISetVoiceMessageSpendLimitOverrideRequest.cpp \
    $${PWD}/OAISetVoiceMessageSpendLimitOverrideResult.cpp \
    $${PWD}/OAISnsDestination.cpp \
    $${PWD}/OAISpendLimit.cpp \
    $${PWD}/OAISpendLimitName.cpp \
    $${PWD}/OAITag.cpp \
    $${PWD}/OAITagResourceRequest.cpp \
    $${PWD}/OAIUntagResourceRequest.cpp \
    $${PWD}/OAIUpdateEventDestinationRequest.cpp \
    $${PWD}/OAIUpdateEventDestinationRequest_CloudWatchLogsDestination.cpp \
    $${PWD}/OAIUpdateEventDestinationRequest_KinesisFirehoseDestination.cpp \
    $${PWD}/OAIUpdateEventDestinationRequest_SnsDestination.cpp \
    $${PWD}/OAIUpdateEventDestinationResult.cpp \
    $${PWD}/OAIUpdateEventDestinationResult_EventDestination.cpp \
    $${PWD}/OAIUpdatePhoneNumberRequest.cpp \
    $${PWD}/OAIUpdatePhoneNumberResult.cpp \
    $${PWD}/OAIUpdatePoolRequest.cpp \
    $${PWD}/OAIUpdatePoolResult.cpp \
    $${PWD}/OAIVoiceId.cpp \
    $${PWD}/OAIVoiceMessageBodyTextType.cpp \
# APIs
    $${PWD}/OAIDefaultApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
