openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: This API allows clients to access and modify container and tag configuration.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Tag Manager API
  version: v1
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
  x-origin:
  - format: google
    url: https://tagmanager.googleapis.com/$discovery/rest?version=v1
    version: v1
  x-preferred: false
  x-providerName: googleapis.com
  x-serviceName: tagmanager
servers:
- url: https://tagmanager.googleapis.com/
tags:
- name: accounts
paths:
  /tagmanager/v1/accounts:
    get:
      description: Lists all GTM Accounts that a user has access to.
      operationId: tagmanager_accounts_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.manage.accounts
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.manage.accounts
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v1/accounts/{accountId}:
    get:
      description: Gets a GTM Account.
      operationId: tagmanager_accounts_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.manage.accounts
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.manage.accounts
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    put:
      description: Updates a GTM Account.
      operationId: tagmanager_accounts_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.manage.accounts
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.manage.accounts
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v1/accounts/{accountId}/containers:
    get:
      description: Lists all Containers that belongs to a GTM Account.
      operationId: tagmanager_accounts_containers_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    post:
      description: Creates a Container.
      operationId: tagmanager_accounts_containers_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}:
    delete:
      description: Deletes a Container.
      operationId: tagmanager_accounts_containers_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.delete.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.delete.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    get:
      description: Gets a Container.
      operationId: tagmanager_accounts_containers_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    put:
      description: Updates a Container.
      operationId: tagmanager_accounts_containers_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/environments:
    get:
      description: Lists all GTM Environments of a GTM Container.
      operationId: tagmanager_accounts_containers_environments_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    post:
      description: Creates a GTM Environment.
      operationId: tagmanager_accounts_containers_environments_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/environments/{environmentId}:
    delete:
      description: Deletes a GTM Environment.
      operationId: tagmanager_accounts_containers_environments_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    get:
      description: Gets a GTM Environment.
      operationId: tagmanager_accounts_containers_environments_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    put:
      description: Updates a GTM Environment.
      operationId: tagmanager_accounts_containers_environments_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/folders:
    get:
      description: Lists all GTM Folders of a Container.
      operationId: tagmanager_accounts_containers_folders_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    post:
      description: Creates a GTM Folder.
      operationId: tagmanager_accounts_containers_folders_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/folders/{folderId}:
    delete:
      description: Deletes a GTM Folder.
      operationId: tagmanager_accounts_containers_folders_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    get:
      description: Gets a GTM Folder.
      operationId: tagmanager_accounts_containers_folders_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    put:
      description: Updates a GTM Folder.
      operationId: tagmanager_accounts_containers_folders_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/folders/{folderId}/entities:
    get:
      description: List all entities in a GTM Folder.
      operationId: tagmanager_accounts_containers_folders_entities_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/move_folders/{folderId}:
    put:
      description: Moves entities to a GTM Folder.
      operationId: tagmanager_accounts_containers_move_folders_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/reauthorize_environments/{environmentId}:
    put:
      description: Re-generates the authorization code for a GTM Environment.
      operationId: tagmanager_accounts_containers_reauthorize_environments_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.publish
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.publish
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/tags:
    get:
      description: Lists all GTM Tags of a Container.
      operationId: tagmanager_accounts_containers_tags_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    post:
      description: Creates a GTM Tag.
      operationId: tagmanager_accounts_containers_tags_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/tags/{tagId}:
    delete:
      description: Deletes a GTM Tag.
      operationId: tagmanager_accounts_containers_tags_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    get:
      description: Gets a GTM Tag.
      operationId: tagmanager_accounts_containers_tags_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    put:
      description: Updates a GTM Tag.
      operationId: tagmanager_accounts_containers_tags_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/triggers:
    get:
      description: Lists all GTM Triggers of a Container.
      operationId: tagmanager_accounts_containers_triggers_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    post:
      description: Creates a GTM Trigger.
      operationId: tagmanager_accounts_containers_triggers_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/triggers/{triggerId}:
    delete:
      description: Deletes a GTM Trigger.
      operationId: tagmanager_accounts_containers_triggers_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    get:
      description: Gets a GTM Trigger.
      operationId: tagmanager_accounts_containers_triggers_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    put:
      description: Updates a GTM Trigger.
      operationId: tagmanager_accounts_containers_triggers_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/variables:
    get:
      description: Lists all GTM Variables of a Container.
      operationId: tagmanager_accounts_containers_variables_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    post:
      description: Creates a GTM Variable.
      operationId: tagmanager_accounts_containers_variables_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/variables/{variableId}:
    delete:
      description: Deletes a GTM Variable.
      operationId: tagmanager_accounts_containers_variables_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    get:
      description: Gets a GTM Variable.
      operationId: tagmanager_accounts_containers_variables_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    put:
      description: Updates a GTM Variable.
      operationId: tagmanager_accounts_containers_variables_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/versions:
    get:
      description: Lists all Container Versions of a GTM Container.
      operationId: tagmanager_accounts_containers_versions_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containerversions
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containerversions
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    post:
      description: Creates a Container Version.
      operationId: tagmanager_accounts_containers_versions_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containerversions
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containerversions
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}:
    delete:
      description: Deletes a Container Version.
      operationId: tagmanager_accounts_containers_versions_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containerversions
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containerversions
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    get:
      description: Gets a Container Version.
      operationId: tagmanager_accounts_containers_versions_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containerversions
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containerversions
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    put:
      description: Updates a Container Version.
      operationId: tagmanager_accounts_containers_versions_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containerversions
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containerversions
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/publish:
    post:
      description: Publishes a Container Version.
      operationId: tagmanager_accounts_containers_versions_publish
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.publish
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.publish
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/restore:
    post:
      description: "Restores a Container Version. This will overwrite the container's\
        \ current configuration (including its variables, triggers and tags). The\
        \ operation will not have any effect on the version that is being served (i.e.\
        \ the published version)."
      operationId: tagmanager_accounts_containers_versions_restore
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v1/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/undelete:
    post:
      description: Undeletes a Container Version.
      operationId: tagmanager_accounts_containers_versions_undelete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containerversions
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.edit.containerversions
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v1/accounts/{accountId}/permissions:
    get:
      description: List all users that have access to the account along with Account
        and Container Permissions granted to each of them.
      operationId: tagmanager_accounts_permissions_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.manage.users
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.manage.users
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    post:
      description: Creates a user's Account & Container Permissions.
      operationId: tagmanager_accounts_permissions_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.manage.users
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.manage.users
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /tagmanager/v1/accounts/{accountId}/permissions/{permissionId}:
    delete:
      description: "Removes a user from the account, revoking access to it and all\
        \ of its containers."
      operationId: tagmanager_accounts_permissions_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.manage.users
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.manage.users
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    get:
      description: Gets a user's Account & Container Permissions.
      operationId: tagmanager_accounts_permissions_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.manage.users
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.manage.users
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
    put:
      description: Updates a user's Account & Container Permissions.
      operationId: tagmanager_accounts_permissions_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.manage.users
        Oauth2c:
        - https://www.googleapis.com/auth/tagmanager.manage.users
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/tagmanager.delete.containers: Delete your
              Google Tag Manager containers
            https://www.googleapis.com/auth/tagmanager.edit.containers: "Manage your\
              \ Google Tag Manager container and its subcomponents, excluding versioning\
              \ and publishing"
            https://www.googleapis.com/auth/tagmanager.edit.containerversions: Manage
              your Google Tag Manager container versions
            https://www.googleapis.com/auth/tagmanager.manage.accounts: View and manage
              your Google Tag Manager accounts
            https://www.googleapis.com/auth/tagmanager.manage.users: Manage user permissions
              of your Google Tag Manager account and container
            https://www.googleapis.com/auth/tagmanager.publish: Publish your Google
              Tag Manager container versions
            https://www.googleapis.com/auth/tagmanager.readonly: View your Google
              Tag Manager container and its subcomponents
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/tagmanager.delete.containers: Delete your
              Google Tag Manager containers
            https://www.googleapis.com/auth/tagmanager.edit.containers: "Manage your\
              \ Google Tag Manager container and its subcomponents, excluding versioning\
              \ and publishing"
            https://www.googleapis.com/auth/tagmanager.edit.containerversions: Manage
              your Google Tag Manager container versions
            https://www.googleapis.com/auth/tagmanager.manage.accounts: View and manage
              your Google Tag Manager accounts
            https://www.googleapis.com/auth/tagmanager.manage.users: Manage user permissions
              of your Google Tag Manager account and container
            https://www.googleapis.com/auth/tagmanager.publish: Publish your Google
              Tag Manager container versions
            https://www.googleapis.com/auth/tagmanager.readonly: View your Google
              Tag Manager container and its subcomponents
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2c
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2c
