QT += network

HEADERS += \
# Models
    $${PWD}/OAIAllowPublish.h \
    $${PWD}/OAIAllowUpstream.h \
    $${PWD}/OAIAssetSummary.h \
    $${PWD}/OAIAssociateExternalConnectionResult.h \
    $${PWD}/OAIAssociateExternalConnectionResult_repository.h \
    $${PWD}/OAICopyPackageVersionsRequest.h \
    $${PWD}/OAICopyPackageVersionsResult.h \
    $${PWD}/OAICopyPackageVersions_request.h \
    $${PWD}/OAICreateDomainRequest.h \
    $${PWD}/OAICreateDomainResult.h \
    $${PWD}/OAICreateDomainResult_domain.h \
    $${PWD}/OAICreateDomain_request.h \
    $${PWD}/OAICreateRepositoryRequest.h \
    $${PWD}/OAICreateRepositoryResult.h \
    $${PWD}/OAICreateRepositoryResult_repository.h \
    $${PWD}/OAICreateRepository_request.h \
    $${PWD}/OAIDeleteDomainPermissionsPolicyResult.h \
    $${PWD}/OAIDeleteDomainPermissionsPolicyResult_policy.h \
    $${PWD}/OAIDeleteDomainResult.h \
    $${PWD}/OAIDeleteDomainResult_domain.h \
    $${PWD}/OAIDeletePackageResult.h \
    $${PWD}/OAIDeletePackageVersionsRequest.h \
    $${PWD}/OAIDeletePackageVersionsResult.h \
    $${PWD}/OAIDeletePackageVersions_request.h \
    $${PWD}/OAIDeleteRepositoryPermissionsPolicyResult.h \
    $${PWD}/OAIDeleteRepositoryPermissionsPolicyResult_policy.h \
    $${PWD}/OAIDeleteRepositoryResult.h \
    $${PWD}/OAIDeleteRepositoryResult_repository.h \
    $${PWD}/OAIDescribeDomainResult.h \
    $${PWD}/OAIDescribePackageResult.h \
    $${PWD}/OAIDescribePackageResult_package.h \
    $${PWD}/OAIDescribePackageVersionResult.h \
    $${PWD}/OAIDescribePackageVersionResult_packageVersion.h \
    $${PWD}/OAIDescribeRepositoryResult.h \
    $${PWD}/OAIDescribeRepositoryResult_repository.h \
    $${PWD}/OAIDisassociateExternalConnectionResult.h \
    $${PWD}/OAIDisassociateExternalConnectionResult_repository.h \
    $${PWD}/OAIDisposePackageVersionsRequest.h \
    $${PWD}/OAIDisposePackageVersionsResult.h \
    $${PWD}/OAIDisposePackageVersions_request.h \
    $${PWD}/OAIDomainDescription.h \
    $${PWD}/OAIDomainEntryPoint.h \
    $${PWD}/OAIDomainStatus.h \
    $${PWD}/OAIDomainSummary.h \
    $${PWD}/OAIExternalConnectionStatus.h \
    $${PWD}/OAIGetAuthorizationTokenResult.h \
    $${PWD}/OAIGetDomainPermissionsPolicyResult.h \
    $${PWD}/OAIGetDomainPermissionsPolicyResult_policy.h \
    $${PWD}/OAIGetPackageVersionAssetResult.h \
    $${PWD}/OAIGetPackageVersionReadmeResult.h \
    $${PWD}/OAIGetRepositoryEndpointResult.h \
    $${PWD}/OAIGetRepositoryPermissionsPolicyResult.h \
    $${PWD}/OAIHashAlgorithm.h \
    $${PWD}/OAILicenseInfo.h \
    $${PWD}/OAIListDomainsRequest.h \
    $${PWD}/OAIListDomainsResult.h \
    $${PWD}/OAIListDomains_request.h \
    $${PWD}/OAIListPackageVersionAssetsResult.h \
    $${PWD}/OAIListPackageVersionDependenciesResult.h \
    $${PWD}/OAIListPackageVersionsResult.h \
    $${PWD}/OAIListPackagesResult.h \
    $${PWD}/OAIListRepositoriesInDomainResult.h \
    $${PWD}/OAIListRepositoriesResult.h \
    $${PWD}/OAIListTagsForResourceResult.h \
    $${PWD}/OAIPackageDependency.h \
    $${PWD}/OAIPackageDescription.h \
    $${PWD}/OAIPackageDescription_originConfiguration.h \
    $${PWD}/OAIPackageFormat.h \
    $${PWD}/OAIPackageOriginConfiguration.h \
    $${PWD}/OAIPackageOriginConfiguration_restrictions.h \
    $${PWD}/OAIPackageOriginRestrictions.h \
    $${PWD}/OAIPackageSummary.h \
    $${PWD}/OAIPackageSummary_originConfiguration.h \
    $${PWD}/OAIPackageVersionDescription.h \
    $${PWD}/OAIPackageVersionDescription_origin.h \
    $${PWD}/OAIPackageVersionError.h \
    $${PWD}/OAIPackageVersionErrorCode.h \
    $${PWD}/OAIPackageVersionOrigin.h \
    $${PWD}/OAIPackageVersionOriginType.h \
    $${PWD}/OAIPackageVersionOrigin_domainEntryPoint.h \
    $${PWD}/OAIPackageVersionSortType.h \
    $${PWD}/OAIPackageVersionStatus.h \
    $${PWD}/OAIPackageVersionSummary.h \
    $${PWD}/OAIPublishPackageVersionRequest.h \
    $${PWD}/OAIPublishPackageVersionResult.h \
    $${PWD}/OAIPublishPackageVersionResult_asset.h \
    $${PWD}/OAIPublishPackageVersion_request.h \
    $${PWD}/OAIPutDomainPermissionsPolicyRequest.h \
    $${PWD}/OAIPutDomainPermissionsPolicyResult.h \
    $${PWD}/OAIPutDomainPermissionsPolicyResult_policy.h \
    $${PWD}/OAIPutDomainPermissionsPolicy_request.h \
    $${PWD}/OAIPutPackageOriginConfigurationRequest.h \
    $${PWD}/OAIPutPackageOriginConfigurationRequest_restrictions.h \
    $${PWD}/OAIPutPackageOriginConfigurationResult.h \
    $${PWD}/OAIPutPackageOriginConfigurationResult_originConfiguration.h \
    $${PWD}/OAIPutPackageOriginConfiguration_request.h \
    $${PWD}/OAIPutPackageOriginConfiguration_request_restrictions.h \
    $${PWD}/OAIPutRepositoryPermissionsPolicyRequest.h \
    $${PWD}/OAIPutRepositoryPermissionsPolicyResult.h \
    $${PWD}/OAIPutRepositoryPermissionsPolicy_request.h \
    $${PWD}/OAIRepositoryDescription.h \
    $${PWD}/OAIRepositoryExternalConnectionInfo.h \
    $${PWD}/OAIRepositorySummary.h \
    $${PWD}/OAIResourcePolicy.h \
    $${PWD}/OAISuccessfulPackageVersionInfo.h \
    $${PWD}/OAITag.h \
    $${PWD}/OAITagResourceRequest.h \
    $${PWD}/OAITagResource_request.h \
    $${PWD}/OAIUntagResourceRequest.h \
    $${PWD}/OAIUntagResource_request.h \
    $${PWD}/OAIUpdatePackageVersionsStatusRequest.h \
    $${PWD}/OAIUpdatePackageVersionsStatusResult.h \
    $${PWD}/OAIUpdatePackageVersionsStatus_request.h \
    $${PWD}/OAIUpdateRepositoryRequest.h \
    $${PWD}/OAIUpdateRepositoryResult.h \
    $${PWD}/OAIUpdateRepositoryResult_repository.h \
    $${PWD}/OAIUpdateRepository_request.h \
    $${PWD}/OAIUpstreamRepository.h \
    $${PWD}/OAIUpstreamRepositoryInfo.h \
# APIs
    $${PWD}/OAIDefaultApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAllowPublish.cpp \
    $${PWD}/OAIAllowUpstream.cpp \
    $${PWD}/OAIAssetSummary.cpp \
    $${PWD}/OAIAssociateExternalConnectionResult.cpp \
    $${PWD}/OAIAssociateExternalConnectionResult_repository.cpp \
    $${PWD}/OAICopyPackageVersionsRequest.cpp \
    $${PWD}/OAICopyPackageVersionsResult.cpp \
    $${PWD}/OAICopyPackageVersions_request.cpp \
    $${PWD}/OAICreateDomainRequest.cpp \
    $${PWD}/OAICreateDomainResult.cpp \
    $${PWD}/OAICreateDomainResult_domain.cpp \
    $${PWD}/OAICreateDomain_request.cpp \
    $${PWD}/OAICreateRepositoryRequest.cpp \
    $${PWD}/OAICreateRepositoryResult.cpp \
    $${PWD}/OAICreateRepositoryResult_repository.cpp \
    $${PWD}/OAICreateRepository_request.cpp \
    $${PWD}/OAIDeleteDomainPermissionsPolicyResult.cpp \
    $${PWD}/OAIDeleteDomainPermissionsPolicyResult_policy.cpp \
    $${PWD}/OAIDeleteDomainResult.cpp \
    $${PWD}/OAIDeleteDomainResult_domain.cpp \
    $${PWD}/OAIDeletePackageResult.cpp \
    $${PWD}/OAIDeletePackageVersionsRequest.cpp \
    $${PWD}/OAIDeletePackageVersionsResult.cpp \
    $${PWD}/OAIDeletePackageVersions_request.cpp \
    $${PWD}/OAIDeleteRepositoryPermissionsPolicyResult.cpp \
    $${PWD}/OAIDeleteRepositoryPermissionsPolicyResult_policy.cpp \
    $${PWD}/OAIDeleteRepositoryResult.cpp \
    $${PWD}/OAIDeleteRepositoryResult_repository.cpp \
    $${PWD}/OAIDescribeDomainResult.cpp \
    $${PWD}/OAIDescribePackageResult.cpp \
    $${PWD}/OAIDescribePackageResult_package.cpp \
    $${PWD}/OAIDescribePackageVersionResult.cpp \
    $${PWD}/OAIDescribePackageVersionResult_packageVersion.cpp \
    $${PWD}/OAIDescribeRepositoryResult.cpp \
    $${PWD}/OAIDescribeRepositoryResult_repository.cpp \
    $${PWD}/OAIDisassociateExternalConnectionResult.cpp \
    $${PWD}/OAIDisassociateExternalConnectionResult_repository.cpp \
    $${PWD}/OAIDisposePackageVersionsRequest.cpp \
    $${PWD}/OAIDisposePackageVersionsResult.cpp \
    $${PWD}/OAIDisposePackageVersions_request.cpp \
    $${PWD}/OAIDomainDescription.cpp \
    $${PWD}/OAIDomainEntryPoint.cpp \
    $${PWD}/OAIDomainStatus.cpp \
    $${PWD}/OAIDomainSummary.cpp \
    $${PWD}/OAIExternalConnectionStatus.cpp \
    $${PWD}/OAIGetAuthorizationTokenResult.cpp \
    $${PWD}/OAIGetDomainPermissionsPolicyResult.cpp \
    $${PWD}/OAIGetDomainPermissionsPolicyResult_policy.cpp \
    $${PWD}/OAIGetPackageVersionAssetResult.cpp \
    $${PWD}/OAIGetPackageVersionReadmeResult.cpp \
    $${PWD}/OAIGetRepositoryEndpointResult.cpp \
    $${PWD}/OAIGetRepositoryPermissionsPolicyResult.cpp \
    $${PWD}/OAIHashAlgorithm.cpp \
    $${PWD}/OAILicenseInfo.cpp \
    $${PWD}/OAIListDomainsRequest.cpp \
    $${PWD}/OAIListDomainsResult.cpp \
    $${PWD}/OAIListDomains_request.cpp \
    $${PWD}/OAIListPackageVersionAssetsResult.cpp \
    $${PWD}/OAIListPackageVersionDependenciesResult.cpp \
    $${PWD}/OAIListPackageVersionsResult.cpp \
    $${PWD}/OAIListPackagesResult.cpp \
    $${PWD}/OAIListRepositoriesInDomainResult.cpp \
    $${PWD}/OAIListRepositoriesResult.cpp \
    $${PWD}/OAIListTagsForResourceResult.cpp \
    $${PWD}/OAIPackageDependency.cpp \
    $${PWD}/OAIPackageDescription.cpp \
    $${PWD}/OAIPackageDescription_originConfiguration.cpp \
    $${PWD}/OAIPackageFormat.cpp \
    $${PWD}/OAIPackageOriginConfiguration.cpp \
    $${PWD}/OAIPackageOriginConfiguration_restrictions.cpp \
    $${PWD}/OAIPackageOriginRestrictions.cpp \
    $${PWD}/OAIPackageSummary.cpp \
    $${PWD}/OAIPackageSummary_originConfiguration.cpp \
    $${PWD}/OAIPackageVersionDescription.cpp \
    $${PWD}/OAIPackageVersionDescription_origin.cpp \
    $${PWD}/OAIPackageVersionError.cpp \
    $${PWD}/OAIPackageVersionErrorCode.cpp \
    $${PWD}/OAIPackageVersionOrigin.cpp \
    $${PWD}/OAIPackageVersionOriginType.cpp \
    $${PWD}/OAIPackageVersionOrigin_domainEntryPoint.cpp \
    $${PWD}/OAIPackageVersionSortType.cpp \
    $${PWD}/OAIPackageVersionStatus.cpp \
    $${PWD}/OAIPackageVersionSummary.cpp \
    $${PWD}/OAIPublishPackageVersionRequest.cpp \
    $${PWD}/OAIPublishPackageVersionResult.cpp \
    $${PWD}/OAIPublishPackageVersionResult_asset.cpp \
    $${PWD}/OAIPublishPackageVersion_request.cpp \
    $${PWD}/OAIPutDomainPermissionsPolicyRequest.cpp \
    $${PWD}/OAIPutDomainPermissionsPolicyResult.cpp \
    $${PWD}/OAIPutDomainPermissionsPolicyResult_policy.cpp \
    $${PWD}/OAIPutDomainPermissionsPolicy_request.cpp \
    $${PWD}/OAIPutPackageOriginConfigurationRequest.cpp \
    $${PWD}/OAIPutPackageOriginConfigurationRequest_restrictions.cpp \
    $${PWD}/OAIPutPackageOriginConfigurationResult.cpp \
    $${PWD}/OAIPutPackageOriginConfigurationResult_originConfiguration.cpp \
    $${PWD}/OAIPutPackageOriginConfiguration_request.cpp \
    $${PWD}/OAIPutPackageOriginConfiguration_request_restrictions.cpp \
    $${PWD}/OAIPutRepositoryPermissionsPolicyRequest.cpp \
    $${PWD}/OAIPutRepositoryPermissionsPolicyResult.cpp \
    $${PWD}/OAIPutRepositoryPermissionsPolicy_request.cpp \
    $${PWD}/OAIRepositoryDescription.cpp \
    $${PWD}/OAIRepositoryExternalConnectionInfo.cpp \
    $${PWD}/OAIRepositorySummary.cpp \
    $${PWD}/OAIResourcePolicy.cpp \
    $${PWD}/OAISuccessfulPackageVersionInfo.cpp \
    $${PWD}/OAITag.cpp \
    $${PWD}/OAITagResourceRequest.cpp \
    $${PWD}/OAITagResource_request.cpp \
    $${PWD}/OAIUntagResourceRequest.cpp \
    $${PWD}/OAIUntagResource_request.cpp \
    $${PWD}/OAIUpdatePackageVersionsStatusRequest.cpp \
    $${PWD}/OAIUpdatePackageVersionsStatusResult.cpp \
    $${PWD}/OAIUpdatePackageVersionsStatus_request.cpp \
    $${PWD}/OAIUpdateRepositoryRequest.cpp \
    $${PWD}/OAIUpdateRepositoryResult.cpp \
    $${PWD}/OAIUpdateRepositoryResult_repository.cpp \
    $${PWD}/OAIUpdateRepository_request.cpp \
    $${PWD}/OAIUpstreamRepository.cpp \
    $${PWD}/OAIUpstreamRepositoryInfo.cpp \
# APIs
    $${PWD}/OAIDefaultApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
