openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: API for provisioning and managing identity resources.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Cloud Identity API
  version: v1
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
  x-origin:
  - format: openapi
    url: https://cloudidentity.googleapis.com/$discovery/rest?version=v1
    version: "3.0"
  x-preferred: false
  x-providerName: googleapis.com
  x-serviceName: cloudidentity
servers:
- url: https://cloudidentity.googleapis.com/
tags:
- name: customers
- name: devices
- name: groups
- name: inboundSamlSsoProfiles
- name: inboundSsoAssignments
paths:
  /v1/devices:
    get:
      description: Lists/Searches devices.
      operationId: cloudidentity.devices.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.devices
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.devices
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.devices.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.devices.readonly
      tags:
      - devices
      x-accepts:
      - application/json
    post:
      description: "Creates a device. Only company-owned device may be created. **Note**:\
        \ This method is available only to customers who have one of the following\
        \ SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and\
        \ Cloud Identity Premium"
      operationId: cloudidentity.devices.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.devices
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.devices
      tags:
      - devices
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/groups:
    get:
      description: Lists the `Group` resources under a customer or namespace.
      operationId: cloudidentity.groups.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.groups
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.groups
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.groups.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.groups.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - groups
      x-accepts:
      - application/json
    post:
      description: Creates a Group.
      operationId: cloudidentity.groups.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.groups
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.groups
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - groups
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/groups:lookup:
    get:
      description: "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names)\
        \ of a `Group` by its `EntityKey`."
      operationId: cloudidentity.groups.lookup
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.groups
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.groups
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.groups.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.groups.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - groups
      x-accepts:
      - application/json
  /v1/groups:search:
    get:
      description: Searches for `Group` resources matching a specified query.
      operationId: cloudidentity.groups.search
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.groups
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.groups
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.groups.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.groups.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - groups
      x-accepts:
      - application/json
  /v1/inboundSamlSsoProfiles:
    get:
      description: Lists InboundSamlSsoProfiles for a customer.
      operationId: cloudidentity.inboundSamlSsoProfiles.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - inboundSamlSsoProfiles
      x-accepts:
      - application/json
    post:
      description: Creates an InboundSamlSsoProfile for a customer.
      operationId: cloudidentity.inboundSamlSsoProfiles.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - inboundSamlSsoProfiles
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/inboundSsoAssignments:
    get:
      description: Lists the InboundSsoAssignments for a `Customer`.
      operationId: cloudidentity.inboundSsoAssignments.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - inboundSsoAssignments
      x-accepts:
      - application/json
    post:
      description: Creates an InboundSsoAssignment for users and devices in a `Customer`
        under a given `Group` or `OrgUnit`.
      operationId: cloudidentity.inboundSsoAssignments.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - inboundSsoAssignments
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/{name}:
    delete:
      description: "Deletes an InboundSsoAssignment. To disable SSO, Create (or Update)\
        \ an assignment that has `sso_mode` == `SSO_OFF`."
      operationId: cloudidentity.inboundSsoAssignments.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - inboundSsoAssignments
      x-accepts:
      - application/json
    get:
      description: Gets an InboundSsoAssignment.
      operationId: cloudidentity.inboundSsoAssignments.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.groups.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.groups.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - inboundSsoAssignments
      x-accepts:
      - application/json
    patch:
      description: "Updates an InboundSsoAssignment. The body of this request is the\
        \ `inbound_sso_assignment` field and the `update_mask` is relative to that.\
        \ For example: a PATCH to `/v1/inboundSsoAssignments/0abcdefg1234567&update_mask=rank`\
        \ with a body of `{ \"rank\": 1 }` moves that (presumably group-targeted)\
        \ SSO assignment to the highest priority and shifts any other group-targeted\
        \ assignments down in priority."
      operationId: cloudidentity.inboundSsoAssignments.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - inboundSsoAssignments
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/{name}:approve:
    post:
      description: Approves device to access user data.
      operationId: cloudidentity.devices.deviceUsers.approve
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.devices
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.devices
      tags:
      - devices
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/{name}:block:
    post:
      description: Blocks device from accessing user data
      operationId: cloudidentity.devices.deviceUsers.block
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.devices
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.devices
      tags:
      - devices
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/{name}:cancel:
    post:
      description: Cancels a UserInvitation that was already sent.
      operationId: cloudidentity.customers.userinvitations.cancel
      tags:
      - customers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/{name}:cancelWipe:
    post:
      description: Cancels an unfinished user account wipe. This operation can be
        used to cancel device wipe in the gap between the wipe operation returning
        success and the device being wiped.
      operationId: cloudidentity.devices.deviceUsers.cancelWipe
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.devices
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.devices
      tags:
      - devices
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/{name}:isInvitableUser:
    get:
      description: "Verifies whether a user account is eligible to receive a UserInvitation\
        \ (is an unmanaged account). Eligibility is based on the following criteria:\
        \ * the email address is a consumer account and it's the primary email address\
        \ of the account, and * the domain of the email address matches an existing\
        \ verified Google Workspace or Cloud Identity domain If both conditions are\
        \ met, the user is eligible. **Note:** This method is not supported for Workspace\
        \ Essentials customers."
      operationId: cloudidentity.customers.userinvitations.isInvitableUser
      tags:
      - customers
      x-accepts:
      - application/json
  /v1/{name}:modifyMembershipRoles:
    post:
      description: Modifies the `MembershipRole`s of a `Membership`.
      operationId: cloudidentity.groups.memberships.modifyMembershipRoles
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.groups
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.groups
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - groups
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/{name}:send:
    post:
      description: "Sends a UserInvitation to email. If the `UserInvitation` does\
        \ not exist for this request and it is a valid request, the request creates\
        \ a `UserInvitation`. **Note:** The `get` and `list` methods have a 48-hour\
        \ delay where newly-created consumer accounts will not appear in the results.\
        \ You can still send a `UserInvitation` to those accounts if you know the\
        \ unmanaged email address and IsInvitableUser==True."
      operationId: cloudidentity.customers.userinvitations.send
      tags:
      - customers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/{name}:wipe:
    post:
      description: "Wipes the user's account on a device. Other data on the device\
        \ that is not associated with the user's work account is not affected. For\
        \ example, if a Gmail app is installed on a device that is used for personal\
        \ and work purposes, and the user is logged in to the Gmail app with their\
        \ personal account as well as their work account, wiping the \"deviceUser\"\
        \ by their work administrator will not affect their personal account within\
        \ Gmail or other apps such as Photos."
      operationId: cloudidentity.devices.deviceUsers.wipe
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.devices
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.devices
      tags:
      - devices
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/{parent}/clientStates:
    get:
      description: Lists the client states for the given search query.
      operationId: cloudidentity.devices.deviceUsers.clientStates.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.devices
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.devices
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.devices.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.devices.readonly
      tags:
      - devices
      x-accepts:
      - application/json
  /v1/{parent}/deviceUsers:
    get:
      description: Lists/Searches DeviceUsers.
      operationId: cloudidentity.devices.deviceUsers.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.devices
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.devices
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.devices.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.devices.readonly
      tags:
      - devices
      x-accepts:
      - application/json
  /v1/{parent}/idpCredentials:
    get:
      description: Returns a list of IdpCredentials in an InboundSamlSsoProfile.
      operationId: cloudidentity.inboundSamlSsoProfiles.idpCredentials.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - inboundSamlSsoProfiles
      x-accepts:
      - application/json
  /v1/{parent}/idpCredentials:add:
    post:
      description: Adds an IdpCredential. Up to 2 credentials are allowed.
      operationId: cloudidentity.inboundSamlSsoProfiles.idpCredentials.add
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - inboundSamlSsoProfiles
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/{parent}/memberships:
    get:
      description: Lists the `Membership`s within a `Group`.
      operationId: cloudidentity.groups.memberships.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.groups
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.groups
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.groups.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.groups.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - groups
      x-accepts:
      - application/json
    post:
      description: Creates a `Membership`.
      operationId: cloudidentity.groups.memberships.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.groups
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.groups
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - groups
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/{parent}/memberships:checkTransitiveMembership:
    get:
      description: "Check a potential member for membership in a group. **Note:**\
        \ This feature is only available to Google Workspace Enterprise Standard,\
        \ Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium\
        \ accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED)\
        \ HTTP status code will be returned. A member has membership to a group as\
        \ long as there is a single viewable transitive membership between the group\
        \ and the member. The actor must have view permissions to at least one transitive\
        \ membership between the member and group."
      operationId: cloudidentity.groups.memberships.checkTransitiveMembership
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.groups
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.groups
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.groups.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.groups.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - groups
      x-accepts:
      - application/json
  /v1/{parent}/memberships:getMembershipGraph:
    get:
      description: "Get a membership graph of just a member or both a member and a\
        \ group. **Note:** This feature is only available to Google Workspace Enterprise\
        \ Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity\
        \ Premium accounts. If the account of the member is not one of these, a 403\
        \ (PERMISSION_DENIED) HTTP status code will be returned. Given a member, the\
        \ response will contain all membership paths from the member. Given both a\
        \ group and a member, the response will contain all membership paths between\
        \ the group and the member."
      operationId: cloudidentity.groups.memberships.getMembershipGraph
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.groups
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.groups
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.groups.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.groups.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - groups
      x-accepts:
      - application/json
  /v1/{parent}/memberships:lookup:
    get:
      description: "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names)\
        \ of a `Membership` by its `EntityKey`."
      operationId: cloudidentity.groups.memberships.lookup
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.groups
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.groups
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.groups.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.groups.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - groups
      x-accepts:
      - application/json
  /v1/{parent}/memberships:searchDirectGroups:
    get:
      description: Searches direct groups of a member.
      operationId: cloudidentity.groups.memberships.searchDirectGroups
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.groups
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.groups
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.groups.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.groups.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - groups
      x-accepts:
      - application/json
  /v1/{parent}/memberships:searchTransitiveGroups:
    get:
      description: "Search transitive groups of a member. **Note:** This feature is\
        \ only available to Google Workspace Enterprise Standard, Enterprise Plus,\
        \ and Enterprise for Education; and Cloud Identity Premium accounts. If the\
        \ account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP\
        \ status code will be returned. A transitive group is any group that has a\
        \ direct or indirect membership to the member. Actor must have view permissions\
        \ all transitive groups."
      operationId: cloudidentity.groups.memberships.searchTransitiveGroups
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.groups
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.groups
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.groups.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.groups.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - groups
      x-accepts:
      - application/json
  /v1/{parent}/memberships:searchTransitiveMemberships:
    get:
      description: "Search transitive memberships of a group. **Note:** This feature\
        \ is only available to Google Workspace Enterprise Standard, Enterprise Plus,\
        \ and Enterprise for Education; and Cloud Identity Premium accounts. If the\
        \ account of the group is not one of these, a 403 (PERMISSION_DENIED) HTTP\
        \ status code will be returned. A transitive membership is any direct or indirect\
        \ membership of a group. Actor must have view permissions to all transitive\
        \ memberships."
      operationId: cloudidentity.groups.memberships.searchTransitiveMemberships
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.groups
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.groups
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.groups.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.groups.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-platform
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-platform
      tags:
      - groups
      x-accepts:
      - application/json
  /v1/{parent}/userinvitations:
    get:
      description: Retrieves a list of UserInvitation resources. **Note:** New consumer
        accounts with the customer's verified domain created within the previous 48
        hours will not appear in the result. This delay also applies to newly-verified
        domains.
      operationId: cloudidentity.customers.userinvitations.list
      tags:
      - customers
      x-accepts:
      - application/json
  /v1/{parent}:lookup:
    get:
      description: "Looks up resource names of the DeviceUsers associated with the\
        \ caller's credentials, as well as the properties provided in the request.\
        \ This method must be called with end-user credentials with the scope: https://www.googleapis.com/auth/cloud-identity.devices.lookup\
        \ If multiple properties are provided, only DeviceUsers having all of these\
        \ properties are considered as matches - i.e. the query behaves like an AND.\
        \ Different platforms require different amounts of information from the caller\
        \ to ensure that the DeviceUser is uniquely identified. - iOS: No properties\
        \ need to be passed, the caller's credentials are sufficient to identify the\
        \ corresponding DeviceUser. - Android: Specifying the 'android_id' field is\
        \ required. - Desktop: Specifying the 'raw_resource_id' field is required."
      operationId: cloudidentity.devices.deviceUsers.lookup
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/cloud-identity.devices.lookup
        Oauth2c:
        - https://www.googleapis.com/auth/cloud-identity.devices.lookup
      tags:
      - devices
      x-accepts:
      - application/json
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/cloud-identity.devices: "Private Service:\
              \ https://www.googleapis.com/auth/cloud-identity.devices"
            https://www.googleapis.com/auth/cloud-identity.devices.lookup: See your
              device details
            https://www.googleapis.com/auth/cloud-identity.devices.readonly: "Private\
              \ Service: https://www.googleapis.com/auth/cloud-identity.devices.readonly"
            https://www.googleapis.com/auth/cloud-identity.groups: "See, change, create,\
              \ and delete any of the Cloud Identity Groups that you can access, including\
              \ the members of each group"
            https://www.googleapis.com/auth/cloud-identity.groups.readonly: "See any\
              \ Cloud Identity Groups that you can access, including group members\
              \ and their emails"
            https://www.googleapis.com/auth/cloud-platform: "See, edit, configure,\
              \ and delete your Google Cloud data and see the email address for your\
              \ Google Account."
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/cloud-identity.devices: "Private Service:\
              \ https://www.googleapis.com/auth/cloud-identity.devices"
            https://www.googleapis.com/auth/cloud-identity.devices.lookup: See your
              device details
            https://www.googleapis.com/auth/cloud-identity.devices.readonly: "Private\
              \ Service: https://www.googleapis.com/auth/cloud-identity.devices.readonly"
            https://www.googleapis.com/auth/cloud-identity.groups: "See, change, create,\
              \ and delete any of the Cloud Identity Groups that you can access, including\
              \ the members of each group"
            https://www.googleapis.com/auth/cloud-identity.groups.readonly: "See any\
              \ Cloud Identity Groups that you can access, including group members\
              \ and their emails"
            https://www.googleapis.com/auth/cloud-platform: "See, edit, configure,\
              \ and delete your Google Cloud data and see the email address for your\
              \ Google Account."
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2

