openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: An API for managing Drive Labels
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Drive Labels API
  version: v2beta
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://upload.wikimedia.org/wikipedia/commons/e/e1/YouTube_play_buttom_icon_%282013-2017%29.svg
  x-origin:
  - format: google
    url: https://drivelabels.googleapis.com/$discovery/rest?version=v2beta
    version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: drivelabels
servers:
- url: https://drivelabels.googleapis.com/
tags:
- name: labels
- name: limits
- name: users
paths:
  /v2beta/labels:
    get:
      description: List labels.
      operationId: drivelabels_labels_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive.admin.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.admin.labels
      - Oauth2:
        - https://www.googleapis.com/auth/drive.admin.labels.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.admin.labels.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.labels
      - Oauth2:
        - https://www.googleapis.com/auth/drive.labels.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.labels.readonly
      tags:
      - labels
      x-openapi-router-controller: openapi_server.controllers.labels_controller
    post:
      description: Creates a new Label.
      operationId: drivelabels_labels_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive.admin.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.admin.labels
      - Oauth2:
        - https://www.googleapis.com/auth/drive.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.labels
      tags:
      - labels
      x-openapi-router-controller: openapi_server.controllers.labels_controller
  /v2beta/limits/label:
    get:
      description: "Get the constraints on the structure of a Label; such as, the\
        \ maximum number of Fields allowed and maximum length of the label title."
      operationId: drivelabels_limits_get_label
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive.admin.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.admin.labels
      - Oauth2:
        - https://www.googleapis.com/auth/drive.admin.labels.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.admin.labels.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.labels
      - Oauth2:
        - https://www.googleapis.com/auth/drive.labels.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.labels.readonly
      tags:
      - limits
      x-openapi-router-controller: openapi_server.controllers.limits_controller
  /v2beta/{name}:
    delete:
      description: "Deletes a Label's permission. Permissions affect the Label resource\
        \ as a whole, are not revisioned, and do not require publishing."
      operationId: drivelabels_labels_revisions_permissions_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive.admin.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.admin.labels
      - Oauth2:
        - https://www.googleapis.com/auth/drive.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.labels
      tags:
      - labels
      x-openapi-router-controller: openapi_server.controllers.labels_controller
    get:
      description: Gets the user capabilities.
      operationId: drivelabels_users_get_capabilities
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive.admin.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.admin.labels
      - Oauth2:
        - https://www.googleapis.com/auth/drive.admin.labels.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.admin.labels.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.labels
      - Oauth2:
        - https://www.googleapis.com/auth/drive.labels.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.labels.readonly
      tags:
      - users
      x-openapi-router-controller: openapi_server.controllers.users_controller
  /v2beta/{name}:delta:
    post:
      description: "Updates a single Label by applying a set of update requests resulting\
        \ in a new draft revision. The batch update is all-or-nothing: If any of the\
        \ update requests are invalid, no changes are applied. The resulting draft\
        \ revision must be published before the changes may be used with Drive Items."
      operationId: drivelabels_labels_delta
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive.admin.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.admin.labels
      - Oauth2:
        - https://www.googleapis.com/auth/drive.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.labels
      tags:
      - labels
      x-openapi-router-controller: openapi_server.controllers.labels_controller
  /v2beta/{name}:disable:
    post:
      description: "Disable a published Label. Disabling a Label will result in a\
        \ new disabled published revision based on the current published revision.\
        \ If there is a draft revision, a new disabled draft revision will be created\
        \ based on the latest draft revision. Older draft revisions will be deleted.\
        \ Once disabled, a label may be deleted with `DeleteLabel`."
      operationId: drivelabels_labels_disable
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive.admin.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.admin.labels
      - Oauth2:
        - https://www.googleapis.com/auth/drive.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.labels
      tags:
      - labels
      x-openapi-router-controller: openapi_server.controllers.labels_controller
  /v2beta/{name}:enable:
    post:
      description: "Enable a disabled Label and restore it to its published state.\
        \ This will result in a new published revision based on the current disabled\
        \ published revision. If there is an existing disabled draft revision, a new\
        \ revision will be created based on that draft and will be enabled."
      operationId: drivelabels_labels_enable
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive.admin.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.admin.labels
      - Oauth2:
        - https://www.googleapis.com/auth/drive.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.labels
      tags:
      - labels
      x-openapi-router-controller: openapi_server.controllers.labels_controller
  /v2beta/{name}:publish:
    post:
      description: "Publish all draft changes to the Label. Once published, the Label\
        \ may not return to its draft state. See `google.apps.drive.labels.v2.Lifecycle`\
        \ for more information. Publishing a Label will result in a new published\
        \ revision. All previous draft revisions will be deleted. Previous published\
        \ revisions will be kept but are subject to automated deletion as needed.\
        \ Once published, some changes are no longer permitted. Generally, any change\
        \ that would invalidate or cause new restrictions on existing metadata related\
        \ to the Label will be rejected. For example, the following changes to a Label\
        \ will be rejected after the Label is published: * The label cannot be directly\
        \ deleted. It must be disabled first, then deleted. * Field.FieldType cannot\
        \ be changed. * Changes to Field validation options cannot reject something\
        \ that was previously accepted. * Reducing the max entries."
      operationId: drivelabels_labels_publish
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive.admin.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.admin.labels
      - Oauth2:
        - https://www.googleapis.com/auth/drive.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.labels
      tags:
      - labels
      x-openapi-router-controller: openapi_server.controllers.labels_controller
  /v2beta/{name}:updateLabelCopyMode:
    post:
      description: "Updates a Label's `CopyMode`. Changes to this policy are not revisioned,\
        \ do not require publishing, and take effect immediately."
      operationId: drivelabels_labels_update_label_copy_mode
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive.admin.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.admin.labels
      - Oauth2:
        - https://www.googleapis.com/auth/drive.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.labels
      tags:
      - labels
      x-openapi-router-controller: openapi_server.controllers.labels_controller
  /v2beta/{parent}/locks:
    get:
      description: Lists the LabelLocks on a Label.
      operationId: drivelabels_labels_revisions_locks_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive.admin.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.admin.labels
      - Oauth2:
        - https://www.googleapis.com/auth/drive.admin.labels.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.admin.labels.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.labels
      - Oauth2:
        - https://www.googleapis.com/auth/drive.labels.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.labels.readonly
      tags:
      - labels
      x-openapi-router-controller: openapi_server.controllers.labels_controller
  /v2beta/{parent}/permissions:
    get:
      description: Lists a Label's permissions.
      operationId: drivelabels_labels_revisions_permissions_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive.admin.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.admin.labels
      - Oauth2:
        - https://www.googleapis.com/auth/drive.admin.labels.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.admin.labels.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/drive.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.labels
      - Oauth2:
        - https://www.googleapis.com/auth/drive.labels.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/drive.labels.readonly
      tags:
      - labels
      x-openapi-router-controller: openapi_server.controllers.labels_controller
    patch:
      description: "Updates a Label's permissions. If a permission for the indicated\
        \ principal doesn't exist, a new Label Permission is created, otherwise the\
        \ existing permission is updated. Permissions affect the Label resource as\
        \ a whole, are not revisioned, and do not require publishing."
      operationId: drivelabels_labels_revisions_update_permissions
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive.admin.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.admin.labels
      - Oauth2:
        - https://www.googleapis.com/auth/drive.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.labels
      tags:
      - labels
      x-openapi-router-controller: openapi_server.controllers.labels_controller
    post:
      description: "Updates a Label's permissions. If a permission for the indicated\
        \ principal doesn't exist, a new Label Permission is created, otherwise the\
        \ existing permission is updated. Permissions affect the Label resource as\
        \ a whole, are not revisioned, and do not require publishing."
      operationId: drivelabels_labels_revisions_permissions_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive.admin.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.admin.labels
      - Oauth2:
        - https://www.googleapis.com/auth/drive.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.labels
      tags:
      - labels
      x-openapi-router-controller: openapi_server.controllers.labels_controller
  /v2beta/{parent}/permissions:batchDelete:
    post:
      description: "Deletes Label permissions. Permissions affect the Label resource\
        \ as a whole, are not revisioned, and do not require publishing."
      operationId: drivelabels_labels_revisions_permissions_batch_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive.admin.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.admin.labels
      - Oauth2:
        - https://www.googleapis.com/auth/drive.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.labels
      tags:
      - labels
      x-openapi-router-controller: openapi_server.controllers.labels_controller
  /v2beta/{parent}/permissions:batchUpdate:
    post:
      description: "Updates Label permissions. If a permission for the indicated principal\
        \ doesn't exist, a new Label Permission is created, otherwise the existing\
        \ permission is updated. Permissions affect the Label resource as a whole,\
        \ are not revisioned, and do not require publishing."
      operationId: drivelabels_labels_revisions_permissions_batch_update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive.admin.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.admin.labels
      - Oauth2:
        - https://www.googleapis.com/auth/drive.labels
        Oauth2c:
        - https://www.googleapis.com/auth/drive.labels
      tags:
      - labels
      x-openapi-router-controller: openapi_server.controllers.labels_controller
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/drive.admin.labels: "See, edit, create,\
              \ and delete all Google Drive labels in your organization, and see your\
              \ organization's label-related admin policies"
            https://www.googleapis.com/auth/drive.admin.labels.readonly: See all Google
              Drive labels and label-related admin policies in your organization
            https://www.googleapis.com/auth/drive.labels: "See, edit, create, and\
              \ delete your Google Drive labels"
            https://www.googleapis.com/auth/drive.labels.readonly: See your Google
              Drive labels
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/drive.admin.labels: "See, edit, create,\
              \ and delete all Google Drive labels in your organization, and see your\
              \ organization's label-related admin policies"
            https://www.googleapis.com/auth/drive.admin.labels.readonly: See all Google
              Drive labels and label-related admin policies in your organization
            https://www.googleapis.com/auth/drive.labels: "See, edit, create, and\
              \ delete your Google Drive labels"
            https://www.googleapis.com/auth/drive.labels.readonly: See your Google
              Drive labels
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2c
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2c
