QT += network

HEADERS += \
# Models
    $${PWD}/OAIAddProfileKeyRequest.h \
    $${PWD}/OAIAddProfileKeyResponse.h \
    $${PWD}/OAIAddProfileKey_request.h \
    $${PWD}/OAIAdditionalSearchKey.h \
    $${PWD}/OAIAddress.h \
    $${PWD}/OAIAppflowIntegration.h \
    $${PWD}/OAIAppflowIntegrationWorkflowAttributes.h \
    $${PWD}/OAIAppflowIntegrationWorkflowMetrics.h \
    $${PWD}/OAIAppflowIntegrationWorkflowStep.h \
    $${PWD}/OAIAttributeDetails.h \
    $${PWD}/OAIAttributeItem.h \
    $${PWD}/OAIAttributeMatchingModel.h \
    $${PWD}/OAIAttributeTypesSelector.h \
    $${PWD}/OAIAutoMerging.h \
    $${PWD}/OAIAutoMerging_ConflictResolution.h \
    $${PWD}/OAIAutoMerging_Consolidation.h \
    $${PWD}/OAIBatch.h \
    $${PWD}/OAIConditions.h \
    $${PWD}/OAIConflictResolution.h \
    $${PWD}/OAIConflictResolvingModel.h \
    $${PWD}/OAIConnectorOperator.h \
    $${PWD}/OAIConsolidation.h \
    $${PWD}/OAICreateCalculatedAttributeDefinitionRequest.h \
    $${PWD}/OAICreateCalculatedAttributeDefinitionResponse.h \
    $${PWD}/OAICreateCalculatedAttributeDefinitionResponse_AttributeDetails.h \
    $${PWD}/OAICreateCalculatedAttributeDefinitionResponse_Conditions.h \
    $${PWD}/OAICreateCalculatedAttributeDefinition_request.h \
    $${PWD}/OAICreateCalculatedAttributeDefinition_request_AttributeDetails.h \
    $${PWD}/OAICreateDomainRequest.h \
    $${PWD}/OAICreateDomainRequest_Matching.h \
    $${PWD}/OAICreateDomainRequest_RuleBasedMatching.h \
    $${PWD}/OAICreateDomainResponse.h \
    $${PWD}/OAICreateDomainResponse_Matching.h \
    $${PWD}/OAICreateDomainResponse_RuleBasedMatching.h \
    $${PWD}/OAICreateDomain_request.h \
    $${PWD}/OAICreateEventStreamRequest.h \
    $${PWD}/OAICreateEventStreamResponse.h \
    $${PWD}/OAICreateEventStream_request.h \
    $${PWD}/OAICreateIntegrationWorkflowRequest.h \
    $${PWD}/OAICreateIntegrationWorkflowRequest_IntegrationConfig.h \
    $${PWD}/OAICreateIntegrationWorkflowResponse.h \
    $${PWD}/OAICreateIntegrationWorkflow_request.h \
    $${PWD}/OAICreateIntegrationWorkflow_request_IntegrationConfig.h \
    $${PWD}/OAICreateIntegrationWorkflow_request_IntegrationConfig_AppflowIntegration.h \
    $${PWD}/OAICreateProfileRequest.h \
    $${PWD}/OAICreateProfileRequest_Address.h \
    $${PWD}/OAICreateProfileRequest_BillingAddress.h \
    $${PWD}/OAICreateProfileRequest_MailingAddress.h \
    $${PWD}/OAICreateProfileRequest_ShippingAddress.h \
    $${PWD}/OAICreateProfileResponse.h \
    $${PWD}/OAICreateProfile_request.h \
    $${PWD}/OAICreateProfile_request_Address.h \
    $${PWD}/OAIDataPullMode.h \
    $${PWD}/OAIDeleteDomainResponse.h \
    $${PWD}/OAIDeleteIntegrationRequest.h \
    $${PWD}/OAIDeleteIntegrationResponse.h \
    $${PWD}/OAIDeleteIntegration_request.h \
    $${PWD}/OAIDeleteProfileKeyRequest.h \
    $${PWD}/OAIDeleteProfileKeyResponse.h \
    $${PWD}/OAIDeleteProfileKey_request.h \
    $${PWD}/OAIDeleteProfileObjectRequest.h \
    $${PWD}/OAIDeleteProfileObjectResponse.h \
    $${PWD}/OAIDeleteProfileObjectTypeResponse.h \
    $${PWD}/OAIDeleteProfileObject_request.h \
    $${PWD}/OAIDeleteProfileRequest.h \
    $${PWD}/OAIDeleteProfileResponse.h \
    $${PWD}/OAIDeleteProfile_request.h \
    $${PWD}/OAIDestinationSummary.h \
    $${PWD}/OAIDomainStats.h \
    $${PWD}/OAIEventStreamDestinationDetails.h \
    $${PWD}/OAIEventStreamDestinationStatus.h \
    $${PWD}/OAIEventStreamState.h \
    $${PWD}/OAIEventStreamSummary.h \
    $${PWD}/OAIEventStreamSummary_DestinationSummary.h \
    $${PWD}/OAIExportingConfig.h \
    $${PWD}/OAIExportingConfig_S3Exporting.h \
    $${PWD}/OAIExportingLocation.h \
    $${PWD}/OAIExportingLocation_S3Exporting.h \
    $${PWD}/OAIFieldContentType.h \
    $${PWD}/OAIFieldSourceProfileIds.h \
    $${PWD}/OAIFlowDefinition.h \
    $${PWD}/OAIFoundByKeyValue.h \
    $${PWD}/OAIGender.h \
    $${PWD}/OAIGetAutoMergingPreviewRequest.h \
    $${PWD}/OAIGetAutoMergingPreviewRequest_ConflictResolution.h \
    $${PWD}/OAIGetAutoMergingPreviewRequest_Consolidation.h \
    $${PWD}/OAIGetAutoMergingPreviewResponse.h \
    $${PWD}/OAIGetAutoMergingPreview_request.h \
    $${PWD}/OAIGetAutoMergingPreview_request_ConflictResolution.h \
    $${PWD}/OAIGetAutoMergingPreview_request_Consolidation.h \
    $${PWD}/OAIGetCalculatedAttributeDefinitionResponse.h \
    $${PWD}/OAIGetCalculatedAttributeForProfileResponse.h \
    $${PWD}/OAIGetDomainResponse.h \
    $${PWD}/OAIGetDomainResponse_Stats.h \
    $${PWD}/OAIGetEventStreamResponse.h \
    $${PWD}/OAIGetEventStreamResponse_DestinationDetails.h \
    $${PWD}/OAIGetIdentityResolutionJobResponse.h \
    $${PWD}/OAIGetIdentityResolutionJobResponse_AutoMerging.h \
    $${PWD}/OAIGetIdentityResolutionJobResponse_ExportingLocation.h \
    $${PWD}/OAIGetIdentityResolutionJobResponse_JobStats.h \
    $${PWD}/OAIGetIntegrationRequest.h \
    $${PWD}/OAIGetIntegrationResponse.h \
    $${PWD}/OAIGetMatchesResponse.h \
    $${PWD}/OAIGetProfileObjectTypeResponse.h \
    $${PWD}/OAIGetProfileObjectTypeTemplateResponse.h \
    $${PWD}/OAIGetSimilarProfilesRequest.h \
    $${PWD}/OAIGetSimilarProfilesResponse.h \
    $${PWD}/OAIGetSimilarProfiles_request.h \
    $${PWD}/OAIGetWorkflowResponse.h \
    $${PWD}/OAIGetWorkflowResponse_Attributes.h \
    $${PWD}/OAIGetWorkflowResponse_Metrics.h \
    $${PWD}/OAIGetWorkflowStepsResponse.h \
    $${PWD}/OAIIdentityResolutionJob.h \
    $${PWD}/OAIIdentityResolutionJobStatus.h \
    $${PWD}/OAIIdentityResolutionJob_JobStats.h \
    $${PWD}/OAIIncrementalPullConfig.h \
    $${PWD}/OAIIntegrationConfig.h \
    $${PWD}/OAIJobSchedule.h \
    $${PWD}/OAIJobScheduleDayOfTheWeek.h \
    $${PWD}/OAIJobStats.h \
    $${PWD}/OAIListAccountIntegrationsRequest.h \
    $${PWD}/OAIListAccountIntegrationsResponse.h \
    $${PWD}/OAIListCalculatedAttributeDefinitionItem.h \
    $${PWD}/OAIListCalculatedAttributeDefinitionsResponse.h \
    $${PWD}/OAIListCalculatedAttributeForProfileItem.h \
    $${PWD}/OAIListCalculatedAttributesForProfileResponse.h \
    $${PWD}/OAIListDomainItem.h \
    $${PWD}/OAIListDomainsResponse.h \
    $${PWD}/OAIListEventStreamsResponse.h \
    $${PWD}/OAIListIdentityResolutionJobsResponse.h \
    $${PWD}/OAIListIntegrationItem.h \
    $${PWD}/OAIListIntegrationsResponse.h \
    $${PWD}/OAIListProfileObjectTypeItem.h \
    $${PWD}/OAIListProfileObjectTypeTemplateItem.h \
    $${PWD}/OAIListProfileObjectTypeTemplatesResponse.h \
    $${PWD}/OAIListProfileObjectTypesResponse.h \
    $${PWD}/OAIListProfileObjectsItem.h \
    $${PWD}/OAIListProfileObjectsRequest.h \
    $${PWD}/OAIListProfileObjectsRequest_ObjectFilter.h \
    $${PWD}/OAIListProfileObjectsResponse.h \
    $${PWD}/OAIListProfileObjects_request.h \
    $${PWD}/OAIListProfileObjects_request_ObjectFilter.h \
    $${PWD}/OAIListRuleBasedMatchesResponse.h \
    $${PWD}/OAIListTagsForResourceResponse.h \
    $${PWD}/OAIListWorkflowsItem.h \
    $${PWD}/OAIListWorkflowsRequest.h \
    $${PWD}/OAIListWorkflowsResponse.h \
    $${PWD}/OAIListWorkflows_request.h \
    $${PWD}/OAILogicalOperator.h \
    $${PWD}/OAIMarketoConnectorOperator.h \
    $${PWD}/OAIMarketoSourceProperties.h \
    $${PWD}/OAIMatchItem.h \
    $${PWD}/OAIMatchType.h \
    $${PWD}/OAIMatchingRequest.h \
    $${PWD}/OAIMatchingResponse.h \
    $${PWD}/OAIMatchingRule.h \
    $${PWD}/OAIMergeProfilesRequest.h \
    $${PWD}/OAIMergeProfilesRequest_FieldSourceProfileIds.h \
    $${PWD}/OAIMergeProfilesResponse.h \
    $${PWD}/OAIMergeProfiles_request.h \
    $${PWD}/OAIMergeProfiles_request_FieldSourceProfileIds.h \
    $${PWD}/OAIObjectFilter.h \
    $${PWD}/OAIObjectTypeField.h \
    $${PWD}/OAIObjectTypeKey.h \
    $${PWD}/OAIOperator.h \
    $${PWD}/OAIOperatorPropertiesKeys.h \
    $${PWD}/OAIPartyType.h \
    $${PWD}/OAIProfile.h \
    $${PWD}/OAIPutIntegrationRequest.h \
    $${PWD}/OAIPutIntegrationRequest_FlowDefinition.h \
    $${PWD}/OAIPutIntegrationResponse.h \
    $${PWD}/OAIPutIntegration_request.h \
    $${PWD}/OAIPutIntegration_request_FlowDefinition.h \
    $${PWD}/OAIPutIntegration_request_FlowDefinition_SourceFlowConfig.h \
    $${PWD}/OAIPutIntegration_request_FlowDefinition_TriggerConfig.h \
    $${PWD}/OAIPutProfileObjectRequest.h \
    $${PWD}/OAIPutProfileObjectResponse.h \
    $${PWD}/OAIPutProfileObjectTypeRequest.h \
    $${PWD}/OAIPutProfileObjectTypeResponse.h \
    $${PWD}/OAIPutProfileObjectType_request.h \
    $${PWD}/OAIPutProfileObject_request.h \
    $${PWD}/OAIRange.h \
    $${PWD}/OAIRuleBasedMatchingRequest.h \
    $${PWD}/OAIRuleBasedMatchingResponse.h \
    $${PWD}/OAIRuleBasedMatchingStatus.h \
    $${PWD}/OAIS3ConnectorOperator.h \
    $${PWD}/OAIS3ExportingConfig.h \
    $${PWD}/OAIS3ExportingLocation.h \
    $${PWD}/OAIS3SourceProperties.h \
    $${PWD}/OAISalesforceConnectorOperator.h \
    $${PWD}/OAISalesforceSourceProperties.h \
    $${PWD}/OAIScheduledTriggerProperties.h \
    $${PWD}/OAISearchProfilesRequest.h \
    $${PWD}/OAISearchProfilesResponse.h \
    $${PWD}/OAISearchProfiles_request.h \
    $${PWD}/OAIServiceNowConnectorOperator.h \
    $${PWD}/OAIServiceNowSourceProperties.h \
    $${PWD}/OAISourceConnectorProperties.h \
    $${PWD}/OAISourceConnectorProperties_Marketo.h \
    $${PWD}/OAISourceConnectorProperties_S3.h \
    $${PWD}/OAISourceConnectorProperties_Salesforce.h \
    $${PWD}/OAISourceConnectorProperties_ServiceNow.h \
    $${PWD}/OAISourceConnectorProperties_Zendesk.h \
    $${PWD}/OAISourceConnectorType.h \
    $${PWD}/OAISourceFlowConfig.h \
    $${PWD}/OAISourceFlowConfig_IncrementalPullConfig.h \
    $${PWD}/OAISourceFlowConfig_SourceConnectorProperties.h \
    $${PWD}/OAIStandardIdentifier.h \
    $${PWD}/OAIStatistic.h \
    $${PWD}/OAIStatus.h \
    $${PWD}/OAITagResourceRequest.h \
    $${PWD}/OAITagResource_request.h \
    $${PWD}/OAITask.h \
    $${PWD}/OAITaskType.h \
    $${PWD}/OAITask_ConnectorOperator.h \
    $${PWD}/OAIThreshold.h \
    $${PWD}/OAITriggerConfig.h \
    $${PWD}/OAITriggerConfig_TriggerProperties.h \
    $${PWD}/OAITriggerProperties.h \
    $${PWD}/OAITriggerProperties_Scheduled.h \
    $${PWD}/OAITriggerType.h \
    $${PWD}/OAIUnit.h \
    $${PWD}/OAIUpdateAddress.h \
    $${PWD}/OAIUpdateCalculatedAttributeDefinitionRequest.h \
    $${PWD}/OAIUpdateCalculatedAttributeDefinitionResponse.h \
    $${PWD}/OAIUpdateCalculatedAttributeDefinitionResponse_AttributeDetails.h \
    $${PWD}/OAIUpdateCalculatedAttributeDefinition_request.h \
    $${PWD}/OAIUpdateCalculatedAttributeDefinition_request_Conditions.h \
    $${PWD}/OAIUpdateCalculatedAttributeDefinition_request_Conditions_Range.h \
    $${PWD}/OAIUpdateCalculatedAttributeDefinition_request_Conditions_Threshold.h \
    $${PWD}/OAIUpdateDomainRequest.h \
    $${PWD}/OAIUpdateDomainRequest_RuleBasedMatching.h \
    $${PWD}/OAIUpdateDomainResponse.h \
    $${PWD}/OAIUpdateDomainResponse_RuleBasedMatching.h \
    $${PWD}/OAIUpdateDomain_request.h \
    $${PWD}/OAIUpdateDomain_request_Matching.h \
    $${PWD}/OAIUpdateDomain_request_Matching_AutoMerging.h \
    $${PWD}/OAIUpdateDomain_request_Matching_ExportingConfig.h \
    $${PWD}/OAIUpdateDomain_request_Matching_JobSchedule.h \
    $${PWD}/OAIUpdateDomain_request_RuleBasedMatching.h \
    $${PWD}/OAIUpdateDomain_request_RuleBasedMatching_AttributeTypesSelector.h \
    $${PWD}/OAIUpdateProfileRequest.h \
    $${PWD}/OAIUpdateProfileRequest_Address.h \
    $${PWD}/OAIUpdateProfileRequest_BillingAddress.h \
    $${PWD}/OAIUpdateProfileRequest_MailingAddress.h \
    $${PWD}/OAIUpdateProfileRequest_ShippingAddress.h \
    $${PWD}/OAIUpdateProfileResponse.h \
    $${PWD}/OAIUpdateProfile_request.h \
    $${PWD}/OAIUpdateProfile_request_Address.h \
    $${PWD}/OAIWorkflowAttributes.h \
    $${PWD}/OAIWorkflowAttributes_AppflowIntegration.h \
    $${PWD}/OAIWorkflowMetrics.h \
    $${PWD}/OAIWorkflowMetrics_AppflowIntegration.h \
    $${PWD}/OAIWorkflowStepItem.h \
    $${PWD}/OAIWorkflowStepItem_AppflowIntegration.h \
    $${PWD}/OAIWorkflowType.h \
    $${PWD}/OAIZendeskConnectorOperator.h \
    $${PWD}/OAIZendeskSourceProperties.h \
# APIs
    $${PWD}/OAIDefaultApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAddProfileKeyRequest.cpp \
    $${PWD}/OAIAddProfileKeyResponse.cpp \
    $${PWD}/OAIAddProfileKey_request.cpp \
    $${PWD}/OAIAdditionalSearchKey.cpp \
    $${PWD}/OAIAddress.cpp \
    $${PWD}/OAIAppflowIntegration.cpp \
    $${PWD}/OAIAppflowIntegrationWorkflowAttributes.cpp \
    $${PWD}/OAIAppflowIntegrationWorkflowMetrics.cpp \
    $${PWD}/OAIAppflowIntegrationWorkflowStep.cpp \
    $${PWD}/OAIAttributeDetails.cpp \
    $${PWD}/OAIAttributeItem.cpp \
    $${PWD}/OAIAttributeMatchingModel.cpp \
    $${PWD}/OAIAttributeTypesSelector.cpp \
    $${PWD}/OAIAutoMerging.cpp \
    $${PWD}/OAIAutoMerging_ConflictResolution.cpp \
    $${PWD}/OAIAutoMerging_Consolidation.cpp \
    $${PWD}/OAIBatch.cpp \
    $${PWD}/OAIConditions.cpp \
    $${PWD}/OAIConflictResolution.cpp \
    $${PWD}/OAIConflictResolvingModel.cpp \
    $${PWD}/OAIConnectorOperator.cpp \
    $${PWD}/OAIConsolidation.cpp \
    $${PWD}/OAICreateCalculatedAttributeDefinitionRequest.cpp \
    $${PWD}/OAICreateCalculatedAttributeDefinitionResponse.cpp \
    $${PWD}/OAICreateCalculatedAttributeDefinitionResponse_AttributeDetails.cpp \
    $${PWD}/OAICreateCalculatedAttributeDefinitionResponse_Conditions.cpp \
    $${PWD}/OAICreateCalculatedAttributeDefinition_request.cpp \
    $${PWD}/OAICreateCalculatedAttributeDefinition_request_AttributeDetails.cpp \
    $${PWD}/OAICreateDomainRequest.cpp \
    $${PWD}/OAICreateDomainRequest_Matching.cpp \
    $${PWD}/OAICreateDomainRequest_RuleBasedMatching.cpp \
    $${PWD}/OAICreateDomainResponse.cpp \
    $${PWD}/OAICreateDomainResponse_Matching.cpp \
    $${PWD}/OAICreateDomainResponse_RuleBasedMatching.cpp \
    $${PWD}/OAICreateDomain_request.cpp \
    $${PWD}/OAICreateEventStreamRequest.cpp \
    $${PWD}/OAICreateEventStreamResponse.cpp \
    $${PWD}/OAICreateEventStream_request.cpp \
    $${PWD}/OAICreateIntegrationWorkflowRequest.cpp \
    $${PWD}/OAICreateIntegrationWorkflowRequest_IntegrationConfig.cpp \
    $${PWD}/OAICreateIntegrationWorkflowResponse.cpp \
    $${PWD}/OAICreateIntegrationWorkflow_request.cpp \
    $${PWD}/OAICreateIntegrationWorkflow_request_IntegrationConfig.cpp \
    $${PWD}/OAICreateIntegrationWorkflow_request_IntegrationConfig_AppflowIntegration.cpp \
    $${PWD}/OAICreateProfileRequest.cpp \
    $${PWD}/OAICreateProfileRequest_Address.cpp \
    $${PWD}/OAICreateProfileRequest_BillingAddress.cpp \
    $${PWD}/OAICreateProfileRequest_MailingAddress.cpp \
    $${PWD}/OAICreateProfileRequest_ShippingAddress.cpp \
    $${PWD}/OAICreateProfileResponse.cpp \
    $${PWD}/OAICreateProfile_request.cpp \
    $${PWD}/OAICreateProfile_request_Address.cpp \
    $${PWD}/OAIDataPullMode.cpp \
    $${PWD}/OAIDeleteDomainResponse.cpp \
    $${PWD}/OAIDeleteIntegrationRequest.cpp \
    $${PWD}/OAIDeleteIntegrationResponse.cpp \
    $${PWD}/OAIDeleteIntegration_request.cpp \
    $${PWD}/OAIDeleteProfileKeyRequest.cpp \
    $${PWD}/OAIDeleteProfileKeyResponse.cpp \
    $${PWD}/OAIDeleteProfileKey_request.cpp \
    $${PWD}/OAIDeleteProfileObjectRequest.cpp \
    $${PWD}/OAIDeleteProfileObjectResponse.cpp \
    $${PWD}/OAIDeleteProfileObjectTypeResponse.cpp \
    $${PWD}/OAIDeleteProfileObject_request.cpp \
    $${PWD}/OAIDeleteProfileRequest.cpp \
    $${PWD}/OAIDeleteProfileResponse.cpp \
    $${PWD}/OAIDeleteProfile_request.cpp \
    $${PWD}/OAIDestinationSummary.cpp \
    $${PWD}/OAIDomainStats.cpp \
    $${PWD}/OAIEventStreamDestinationDetails.cpp \
    $${PWD}/OAIEventStreamDestinationStatus.cpp \
    $${PWD}/OAIEventStreamState.cpp \
    $${PWD}/OAIEventStreamSummary.cpp \
    $${PWD}/OAIEventStreamSummary_DestinationSummary.cpp \
    $${PWD}/OAIExportingConfig.cpp \
    $${PWD}/OAIExportingConfig_S3Exporting.cpp \
    $${PWD}/OAIExportingLocation.cpp \
    $${PWD}/OAIExportingLocation_S3Exporting.cpp \
    $${PWD}/OAIFieldContentType.cpp \
    $${PWD}/OAIFieldSourceProfileIds.cpp \
    $${PWD}/OAIFlowDefinition.cpp \
    $${PWD}/OAIFoundByKeyValue.cpp \
    $${PWD}/OAIGender.cpp \
    $${PWD}/OAIGetAutoMergingPreviewRequest.cpp \
    $${PWD}/OAIGetAutoMergingPreviewRequest_ConflictResolution.cpp \
    $${PWD}/OAIGetAutoMergingPreviewRequest_Consolidation.cpp \
    $${PWD}/OAIGetAutoMergingPreviewResponse.cpp \
    $${PWD}/OAIGetAutoMergingPreview_request.cpp \
    $${PWD}/OAIGetAutoMergingPreview_request_ConflictResolution.cpp \
    $${PWD}/OAIGetAutoMergingPreview_request_Consolidation.cpp \
    $${PWD}/OAIGetCalculatedAttributeDefinitionResponse.cpp \
    $${PWD}/OAIGetCalculatedAttributeForProfileResponse.cpp \
    $${PWD}/OAIGetDomainResponse.cpp \
    $${PWD}/OAIGetDomainResponse_Stats.cpp \
    $${PWD}/OAIGetEventStreamResponse.cpp \
    $${PWD}/OAIGetEventStreamResponse_DestinationDetails.cpp \
    $${PWD}/OAIGetIdentityResolutionJobResponse.cpp \
    $${PWD}/OAIGetIdentityResolutionJobResponse_AutoMerging.cpp \
    $${PWD}/OAIGetIdentityResolutionJobResponse_ExportingLocation.cpp \
    $${PWD}/OAIGetIdentityResolutionJobResponse_JobStats.cpp \
    $${PWD}/OAIGetIntegrationRequest.cpp \
    $${PWD}/OAIGetIntegrationResponse.cpp \
    $${PWD}/OAIGetMatchesResponse.cpp \
    $${PWD}/OAIGetProfileObjectTypeResponse.cpp \
    $${PWD}/OAIGetProfileObjectTypeTemplateResponse.cpp \
    $${PWD}/OAIGetSimilarProfilesRequest.cpp \
    $${PWD}/OAIGetSimilarProfilesResponse.cpp \
    $${PWD}/OAIGetSimilarProfiles_request.cpp \
    $${PWD}/OAIGetWorkflowResponse.cpp \
    $${PWD}/OAIGetWorkflowResponse_Attributes.cpp \
    $${PWD}/OAIGetWorkflowResponse_Metrics.cpp \
    $${PWD}/OAIGetWorkflowStepsResponse.cpp \
    $${PWD}/OAIIdentityResolutionJob.cpp \
    $${PWD}/OAIIdentityResolutionJobStatus.cpp \
    $${PWD}/OAIIdentityResolutionJob_JobStats.cpp \
    $${PWD}/OAIIncrementalPullConfig.cpp \
    $${PWD}/OAIIntegrationConfig.cpp \
    $${PWD}/OAIJobSchedule.cpp \
    $${PWD}/OAIJobScheduleDayOfTheWeek.cpp \
    $${PWD}/OAIJobStats.cpp \
    $${PWD}/OAIListAccountIntegrationsRequest.cpp \
    $${PWD}/OAIListAccountIntegrationsResponse.cpp \
    $${PWD}/OAIListCalculatedAttributeDefinitionItem.cpp \
    $${PWD}/OAIListCalculatedAttributeDefinitionsResponse.cpp \
    $${PWD}/OAIListCalculatedAttributeForProfileItem.cpp \
    $${PWD}/OAIListCalculatedAttributesForProfileResponse.cpp \
    $${PWD}/OAIListDomainItem.cpp \
    $${PWD}/OAIListDomainsResponse.cpp \
    $${PWD}/OAIListEventStreamsResponse.cpp \
    $${PWD}/OAIListIdentityResolutionJobsResponse.cpp \
    $${PWD}/OAIListIntegrationItem.cpp \
    $${PWD}/OAIListIntegrationsResponse.cpp \
    $${PWD}/OAIListProfileObjectTypeItem.cpp \
    $${PWD}/OAIListProfileObjectTypeTemplateItem.cpp \
    $${PWD}/OAIListProfileObjectTypeTemplatesResponse.cpp \
    $${PWD}/OAIListProfileObjectTypesResponse.cpp \
    $${PWD}/OAIListProfileObjectsItem.cpp \
    $${PWD}/OAIListProfileObjectsRequest.cpp \
    $${PWD}/OAIListProfileObjectsRequest_ObjectFilter.cpp \
    $${PWD}/OAIListProfileObjectsResponse.cpp \
    $${PWD}/OAIListProfileObjects_request.cpp \
    $${PWD}/OAIListProfileObjects_request_ObjectFilter.cpp \
    $${PWD}/OAIListRuleBasedMatchesResponse.cpp \
    $${PWD}/OAIListTagsForResourceResponse.cpp \
    $${PWD}/OAIListWorkflowsItem.cpp \
    $${PWD}/OAIListWorkflowsRequest.cpp \
    $${PWD}/OAIListWorkflowsResponse.cpp \
    $${PWD}/OAIListWorkflows_request.cpp \
    $${PWD}/OAILogicalOperator.cpp \
    $${PWD}/OAIMarketoConnectorOperator.cpp \
    $${PWD}/OAIMarketoSourceProperties.cpp \
    $${PWD}/OAIMatchItem.cpp \
    $${PWD}/OAIMatchType.cpp \
    $${PWD}/OAIMatchingRequest.cpp \
    $${PWD}/OAIMatchingResponse.cpp \
    $${PWD}/OAIMatchingRule.cpp \
    $${PWD}/OAIMergeProfilesRequest.cpp \
    $${PWD}/OAIMergeProfilesRequest_FieldSourceProfileIds.cpp \
    $${PWD}/OAIMergeProfilesResponse.cpp \
    $${PWD}/OAIMergeProfiles_request.cpp \
    $${PWD}/OAIMergeProfiles_request_FieldSourceProfileIds.cpp \
    $${PWD}/OAIObjectFilter.cpp \
    $${PWD}/OAIObjectTypeField.cpp \
    $${PWD}/OAIObjectTypeKey.cpp \
    $${PWD}/OAIOperator.cpp \
    $${PWD}/OAIOperatorPropertiesKeys.cpp \
    $${PWD}/OAIPartyType.cpp \
    $${PWD}/OAIProfile.cpp \
    $${PWD}/OAIPutIntegrationRequest.cpp \
    $${PWD}/OAIPutIntegrationRequest_FlowDefinition.cpp \
    $${PWD}/OAIPutIntegrationResponse.cpp \
    $${PWD}/OAIPutIntegration_request.cpp \
    $${PWD}/OAIPutIntegration_request_FlowDefinition.cpp \
    $${PWD}/OAIPutIntegration_request_FlowDefinition_SourceFlowConfig.cpp \
    $${PWD}/OAIPutIntegration_request_FlowDefinition_TriggerConfig.cpp \
    $${PWD}/OAIPutProfileObjectRequest.cpp \
    $${PWD}/OAIPutProfileObjectResponse.cpp \
    $${PWD}/OAIPutProfileObjectTypeRequest.cpp \
    $${PWD}/OAIPutProfileObjectTypeResponse.cpp \
    $${PWD}/OAIPutProfileObjectType_request.cpp \
    $${PWD}/OAIPutProfileObject_request.cpp \
    $${PWD}/OAIRange.cpp \
    $${PWD}/OAIRuleBasedMatchingRequest.cpp \
    $${PWD}/OAIRuleBasedMatchingResponse.cpp \
    $${PWD}/OAIRuleBasedMatchingStatus.cpp \
    $${PWD}/OAIS3ConnectorOperator.cpp \
    $${PWD}/OAIS3ExportingConfig.cpp \
    $${PWD}/OAIS3ExportingLocation.cpp \
    $${PWD}/OAIS3SourceProperties.cpp \
    $${PWD}/OAISalesforceConnectorOperator.cpp \
    $${PWD}/OAISalesforceSourceProperties.cpp \
    $${PWD}/OAIScheduledTriggerProperties.cpp \
    $${PWD}/OAISearchProfilesRequest.cpp \
    $${PWD}/OAISearchProfilesResponse.cpp \
    $${PWD}/OAISearchProfiles_request.cpp \
    $${PWD}/OAIServiceNowConnectorOperator.cpp \
    $${PWD}/OAIServiceNowSourceProperties.cpp \
    $${PWD}/OAISourceConnectorProperties.cpp \
    $${PWD}/OAISourceConnectorProperties_Marketo.cpp \
    $${PWD}/OAISourceConnectorProperties_S3.cpp \
    $${PWD}/OAISourceConnectorProperties_Salesforce.cpp \
    $${PWD}/OAISourceConnectorProperties_ServiceNow.cpp \
    $${PWD}/OAISourceConnectorProperties_Zendesk.cpp \
    $${PWD}/OAISourceConnectorType.cpp \
    $${PWD}/OAISourceFlowConfig.cpp \
    $${PWD}/OAISourceFlowConfig_IncrementalPullConfig.cpp \
    $${PWD}/OAISourceFlowConfig_SourceConnectorProperties.cpp \
    $${PWD}/OAIStandardIdentifier.cpp \
    $${PWD}/OAIStatistic.cpp \
    $${PWD}/OAIStatus.cpp \
    $${PWD}/OAITagResourceRequest.cpp \
    $${PWD}/OAITagResource_request.cpp \
    $${PWD}/OAITask.cpp \
    $${PWD}/OAITaskType.cpp \
    $${PWD}/OAITask_ConnectorOperator.cpp \
    $${PWD}/OAIThreshold.cpp \
    $${PWD}/OAITriggerConfig.cpp \
    $${PWD}/OAITriggerConfig_TriggerProperties.cpp \
    $${PWD}/OAITriggerProperties.cpp \
    $${PWD}/OAITriggerProperties_Scheduled.cpp \
    $${PWD}/OAITriggerType.cpp \
    $${PWD}/OAIUnit.cpp \
    $${PWD}/OAIUpdateAddress.cpp \
    $${PWD}/OAIUpdateCalculatedAttributeDefinitionRequest.cpp \
    $${PWD}/OAIUpdateCalculatedAttributeDefinitionResponse.cpp \
    $${PWD}/OAIUpdateCalculatedAttributeDefinitionResponse_AttributeDetails.cpp \
    $${PWD}/OAIUpdateCalculatedAttributeDefinition_request.cpp \
    $${PWD}/OAIUpdateCalculatedAttributeDefinition_request_Conditions.cpp \
    $${PWD}/OAIUpdateCalculatedAttributeDefinition_request_Conditions_Range.cpp \
    $${PWD}/OAIUpdateCalculatedAttributeDefinition_request_Conditions_Threshold.cpp \
    $${PWD}/OAIUpdateDomainRequest.cpp \
    $${PWD}/OAIUpdateDomainRequest_RuleBasedMatching.cpp \
    $${PWD}/OAIUpdateDomainResponse.cpp \
    $${PWD}/OAIUpdateDomainResponse_RuleBasedMatching.cpp \
    $${PWD}/OAIUpdateDomain_request.cpp \
    $${PWD}/OAIUpdateDomain_request_Matching.cpp \
    $${PWD}/OAIUpdateDomain_request_Matching_AutoMerging.cpp \
    $${PWD}/OAIUpdateDomain_request_Matching_ExportingConfig.cpp \
    $${PWD}/OAIUpdateDomain_request_Matching_JobSchedule.cpp \
    $${PWD}/OAIUpdateDomain_request_RuleBasedMatching.cpp \
    $${PWD}/OAIUpdateDomain_request_RuleBasedMatching_AttributeTypesSelector.cpp \
    $${PWD}/OAIUpdateProfileRequest.cpp \
    $${PWD}/OAIUpdateProfileRequest_Address.cpp \
    $${PWD}/OAIUpdateProfileRequest_BillingAddress.cpp \
    $${PWD}/OAIUpdateProfileRequest_MailingAddress.cpp \
    $${PWD}/OAIUpdateProfileRequest_ShippingAddress.cpp \
    $${PWD}/OAIUpdateProfileResponse.cpp \
    $${PWD}/OAIUpdateProfile_request.cpp \
    $${PWD}/OAIUpdateProfile_request_Address.cpp \
    $${PWD}/OAIWorkflowAttributes.cpp \
    $${PWD}/OAIWorkflowAttributes_AppflowIntegration.cpp \
    $${PWD}/OAIWorkflowMetrics.cpp \
    $${PWD}/OAIWorkflowMetrics_AppflowIntegration.cpp \
    $${PWD}/OAIWorkflowStepItem.cpp \
    $${PWD}/OAIWorkflowStepItem_AppflowIntegration.cpp \
    $${PWD}/OAIWorkflowType.cpp \
    $${PWD}/OAIZendeskConnectorOperator.cpp \
    $${PWD}/OAIZendeskSourceProperties.cpp \
# APIs
    $${PWD}/OAIDefaultApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
