openapi: 3.0.1
info:
  description: |
    These APIs allow you to interact with HubSpot's Marketing Events Extension. It allows you to:
    * Create, Read or update Marketing Event information in HubSpot
    * Specify whether a HubSpot contact has registered, attended or cancelled a registration to a Marketing Event.
    * Specify a URL that can be called to get the details of a Marketing Event.
  title: Marketing Events
  version: v3
  x-hubspot-api-use-case: You have an external system that handles registration for
    your webinars and you want to ensure that attendee data and behavior is synced
    with your HubSpot CRM.
  x-hubspot-documentation-banner: NONE
  x-hubspot-introduction: The marketing events API allows you to build a custom integration
    that will sync event and registration data with your HubSpot account.The marketing
    events API allows you to build a custom integration that will sync event and registration
    data with your HubSpot account.
  x-hubspot-product-tier-requirements:
    cms: STARTER
    marketing: FREE
  x-hubspot-related-documentation:
  - name: Marketing Events Guide
    url: https://hubspot.dev/guides/api/marketing/marketing-events
  x-logo:
    url: https://developers.hubspot.com/hubfs/assets/hubspot.com/buzz/HubSpotOpenGraph.png
  x-origin:
  - format: openapi
    url: https://api.hubspot.com/api-catalog-public/v1/apis/marketing/v3/marketing-events-beta
    version: "3.0"
  x-providerName: hubapi.com
  x-serviceName: marketing
servers:
- url: https://api.hubapi.com
tags:
- description: ""
  name: Batch
  x-hubspot-tag-name-english-source: Batch
- description: ""
  name: Attendance Subscriber State Changes
  x-hubspot-tag-name-english-source: Attendance Subscriber State Changes
- description: ""
  name: Subscriber State Changes
  x-hubspot-tag-name-english-source: Subscriber State Changes
- description: ""
  name: Marketing_Events_External
  x-hubspot-tag-name-english-source: Marketing_Events_External
- description: ""
  name: Basic
  x-hubspot-tag-name-english-source: Basic
- description: ""
  name: Settings
  x-hubspot-tag-name-english-source: Settings
- description: ""
  name: Search
  x-hubspot-tag-name-english-source: Search
paths:
  /marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/create:
    post:
      description: "Record a subscription state between multiple HubSpot contacts\
        \ and a marketing event, using HubSpot contact ids."
      operationId: post_marketing_v3_marketing_events_attendance_external_event_id_subscriber_state_create_create
      security:
      - private_apps_legacy: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Record
      tags:
      - Attendance Subscriber State Changes
      x-openapi-router-controller: openapi_server.controllers.attendance_subscriber_state_changes_controller
  /marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/email-create:
    post:
      description: "Record a subscription state between multiple HubSpot contacts\
        \ and a marketing event, using contact email addresses. If contact is not\
        \ present it will be automatically created."
      operationId: post_marketing_v3_marketing_events_attendance_external_event_id_subscriber_state_email_create_create_by_email
      security:
      - private_apps_legacy: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Record
      tags:
      - Attendance Subscriber State Changes
      x-openapi-router-controller: openapi_server.controllers.attendance_subscriber_state_changes_controller
  /marketing/v3/marketing-events/events:
    post:
      description: Creates a new marketing event in HubSpot
      operationId: post_marketing_v3_marketing_events_events_create
      security:
      - private_apps_legacy: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Create a marketing event
      tags:
      - Basic
      x-openapi-router-controller: openapi_server.controllers.basic_controller
  /marketing/v3/marketing-events/events/delete:
    post:
      description: Bulk delete a number of marketing events in HubSpot
      operationId: post_marketing_v3_marketing_events_events_delete_archive
      security:
      - private_apps_legacy: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Delete multiple marketing events
      tags:
      - Batch
      x-openapi-router-controller: openapi_server.controllers.batch_controller
  /marketing/v3/marketing-events/events/search:
    get:
      description: Search for marketing events that have an event id that starts with
        the query string
      operationId: get_marketing_v3_marketing_events_events_search_do_search
      security:
      - oauth2_legacy:
        - crm.objects.marketing_events.read
      - private_apps_legacy: []
      summary: Search for marketing events
      tags:
      - Search
      x-openapi-router-controller: openapi_server.controllers.search_controller
  /marketing/v3/marketing-events/events/upsert:
    post:
      description: "Upset multiple Marketing Event. If there is an existing Marketing\
        \ event with the specified id, it will be updated; otherwise a new event will\
        \ be created."
      operationId: post_marketing_v3_marketing_events_events_upsert_do_upsert
      security:
      - private_apps_legacy: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Create or update multiple marketing events
      tags:
      - Batch
      x-openapi-router-controller: openapi_server.controllers.batch_controller
  /marketing/v3/marketing-events/events/{externalEventId}:
    delete:
      description: "Deletes an existing Marketing Event with the specified id, if\
        \ one exists."
      operationId: delete_marketing_v3_marketing_events_events_external_event_id_archive
      security:
      - private_apps_legacy: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Delete a marketing event
      tags:
      - Basic
      x-openapi-router-controller: openapi_server.controllers.basic_controller
    get:
      description: "Returns the details of the Marketing Event with the specified\
        \ id, if one exists."
      operationId: get_marketing_v3_marketing_events_events_external_event_id_get_by_id
      security:
      - oauth2_legacy:
        - crm.objects.marketing_events.read
      - private_apps_legacy: []
      summary: Get a marketing event
      tags:
      - Basic
      x-openapi-router-controller: openapi_server.controllers.basic_controller
    patch:
      description: "Updates an existing Marketing Event with the specified id, if\
        \ one exists."
      operationId: patch_marketing_v3_marketing_events_events_external_event_id_update
      security:
      - private_apps_legacy: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Update a marketing event
      tags:
      - Basic
      x-openapi-router-controller: openapi_server.controllers.basic_controller
    put:
      description: "Upsets a Marketing Event. If there is an existing Marketing event\
        \ with the specified id, it will be updated; otherwise a new event will be\
        \ created."
      operationId: put_marketing_v3_marketing_events_events_external_event_id_replace
      security:
      - private_apps_legacy: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Create or update a marketing event
      tags:
      - Basic
      x-openapi-router-controller: openapi_server.controllers.basic_controller
  /marketing/v3/marketing-events/events/{externalEventId}/cancel:
    post:
      description: Mark a marketing event as cancelled.
      operationId: post_marketing_v3_marketing_events_events_external_event_id_cancel_do_cancel
      security:
      - private_apps_legacy: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Mark a marketing event as cancelled
      tags:
      - Basic
      x-openapi-router-controller: openapi_server.controllers.basic_controller
  /marketing/v3/marketing-events/events/{externalEventId}/complete:
    post:
      operationId: post_marketing_v3_marketing_events_events_external_event_id_complete_complete
      security:
      - private_apps_legacy: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      tags:
      - Marketing_Events_External
      x-openapi-router-controller: openapi_server.controllers.marketing_events_external_controller
  /marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert:
    post:
      description: "Record a subscription state between multiple HubSpot contacts\
        \ and a marketing event, using contact email addresses. Note that the contact\
        \ must already exist in HubSpot; a contact will not be created."
      operationId: post_marketing_v3_marketing_events_events_external_event_id_subscriber_state_email_upsert_do_email_upsert_by_id
      security:
      - private_apps_legacy: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Record
      tags:
      - Subscriber State Changes
      x-openapi-router-controller: openapi_server.controllers.subscriber_state_changes_controller
  /marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert:
    post:
      description: "Record a subscription state between multiple HubSpot contacts\
        \ and a marketing event, using HubSpot contact ids. Note that the contact\
        \ must already exist in HubSpot; a contact will not be create."
      operationId: post_marketing_v3_marketing_events_events_external_event_id_subscriber_state_upsert_do_upsert_by_id
      security:
      - private_apps_legacy: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Record
      tags:
      - Subscriber State Changes
      x-openapi-router-controller: openapi_server.controllers.subscriber_state_changes_controller
  /marketing/v3/marketing-events/{appId}/settings:
    get:
      description: Retrieve the current settings for the application.
      operationId: get_marketing_v3_marketing_events_app_id_settings_get_all
      security:
      - developer_hapikey: []
      summary: Retrieve the application settings
      tags:
      - Settings
      x-openapi-router-controller: openapi_server.controllers.settings_controller
    post:
      description: Create or update the current settings for the application.
      operationId: post_marketing_v3_marketing_events_app_id_settings_create
      security:
      - developer_hapikey: []
      summary: Update the application settings
      tags:
      - Settings
      x-openapi-router-controller: openapi_server.controllers.settings_controller
components:
  securitySchemes:
    developer_hapikey:
      in: query
      name: hapikey
      type: apiKey
      x-apikeyInfoFunc: openapi_server.controllers.security_controller.info_from_developer_hapikey
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.marketing_events.read: Read marketing events
            crm.objects.marketing_events.write: Write marketing events
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_oauth2_legacy
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_oauth2_legacy
    private_apps_legacy:
      in: header
      name: private-app-legacy
      type: apiKey
      x-apikeyInfoFunc: openapi_server.controllers.security_controller.info_from_private_apps_legacy
x-hubspot-available-client-libraries:
- PHP
- Node
- Ruby
- Python
x-hubspot-documentation-banner: NONE
x-hubspot-product-tier-requirements:
  cms: STARTER
  marketing: FREE
