/**
 * Amazon Chime SDK Identity
 * The Amazon Chime SDK Identity APIs in this section allow software developers to create and manage unique instances of their messaging applications. These APIs provide the overarching framework for creating and sending messages. For more information about the identity APIs, refer to <a href=\"https://docs.aws.amazon.com/chime/latest/APIReference/API_Operations_Amazon_Chime_SDK_Identity.html\">Amazon Chime SDK identity</a>.
 *
 * The version of the OpenAPI document: 2021-04-20
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EndpointAttributes model module.
 * @module model/EndpointAttributes
 * @version 2021-04-20
 */
class EndpointAttributes {
    /**
     * Constructs a new <code>EndpointAttributes</code>.
     * The attributes of an &lt;code&gt;Endpoint&lt;/code&gt;.
     * @alias module:model/EndpointAttributes
     * @param deviceToken {String} 
     */
    constructor(deviceToken) { 
        
        EndpointAttributes.initialize(this, deviceToken);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, deviceToken) { 
        obj['DeviceToken'] = deviceToken;
    }

    /**
     * Constructs a <code>EndpointAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EndpointAttributes} obj Optional instance to populate.
     * @return {module:model/EndpointAttributes} The populated <code>EndpointAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EndpointAttributes();

            if (data.hasOwnProperty('DeviceToken')) {
                obj['DeviceToken'] = ApiClient.convertToType(data['DeviceToken'], 'String');
            }
            if (data.hasOwnProperty('VoipDeviceToken')) {
                obj['VoipDeviceToken'] = ApiClient.convertToType(data['VoipDeviceToken'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EndpointAttributes</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EndpointAttributes</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EndpointAttributes.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `DeviceToken`
        if (data['DeviceToken']) { // data not null
          String.validateJSON(data['DeviceToken']);
        }
        // validate the optional field `VoipDeviceToken`
        if (data['VoipDeviceToken']) { // data not null
          String.validateJSON(data['VoipDeviceToken']);
        }

        return true;
    }


}

EndpointAttributes.RequiredProperties = ["DeviceToken"];

/**
 * @member {String} DeviceToken
 */
EndpointAttributes.prototype['DeviceToken'] = undefined;

/**
 * @member {String} VoipDeviceToken
 */
EndpointAttributes.prototype['VoipDeviceToken'] = undefined;






export default EndpointAttributes;

