/**
 * Google Play Android Developer API
 * Lets Android application developers access their Google Play accounts. At a high level, the expected workflow is to \"insert\" an Edit, make changes as necessary, and then \"commit\" it. 
 *
 * The version of the OpenAPI document: v3
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIBatchUpdateBasePlanStatesRequest.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIBatchUpdateBasePlanStatesRequest::OAIBatchUpdateBasePlanStatesRequest(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIBatchUpdateBasePlanStatesRequest::OAIBatchUpdateBasePlanStatesRequest() {
    this->initializeModel();
}

OAIBatchUpdateBasePlanStatesRequest::~OAIBatchUpdateBasePlanStatesRequest() {}

void OAIBatchUpdateBasePlanStatesRequest::initializeModel() {

    m_requests_isSet = false;
    m_requests_isValid = false;
}

void OAIBatchUpdateBasePlanStatesRequest::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIBatchUpdateBasePlanStatesRequest::fromJsonObject(QJsonObject json) {

    m_requests_isValid = ::OpenAPI::fromJsonValue(m_requests, json[QString("requests")]);
    m_requests_isSet = !json[QString("requests")].isNull() && m_requests_isValid;
}

QString OAIBatchUpdateBasePlanStatesRequest::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIBatchUpdateBasePlanStatesRequest::asJsonObject() const {
    QJsonObject obj;
    if (m_requests.size() > 0) {
        obj.insert(QString("requests"), ::OpenAPI::toJsonValue(m_requests));
    }
    return obj;
}

QList<OAIUpdateBasePlanStateRequest> OAIBatchUpdateBasePlanStatesRequest::getRequests() const {
    return m_requests;
}
void OAIBatchUpdateBasePlanStatesRequest::setRequests(const QList<OAIUpdateBasePlanStateRequest> &requests) {
    m_requests = requests;
    m_requests_isSet = true;
}

bool OAIBatchUpdateBasePlanStatesRequest::is_requests_Set() const{
    return m_requests_isSet;
}

bool OAIBatchUpdateBasePlanStatesRequest::is_requests_Valid() const{
    return m_requests_isValid;
}

bool OAIBatchUpdateBasePlanStatesRequest::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_requests.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIBatchUpdateBasePlanStatesRequest::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
