QT += network

HEADERS += \
# Models
    $${PWD}/OAIAddAttachmentsToSetRequest.h \
    $${PWD}/OAIAddAttachmentsToSetResponse.h \
    $${PWD}/OAIAddCommunicationToCaseRequest.h \
    $${PWD}/OAIAddCommunicationToCaseResponse.h \
    $${PWD}/OAIAttachment.h \
    $${PWD}/OAIAttachmentDetails.h \
    $${PWD}/OAICaseDetails.h \
    $${PWD}/OAICaseDetails_recentCommunications.h \
    $${PWD}/OAICategory.h \
    $${PWD}/OAICommunication.h \
    $${PWD}/OAICommunicationTypeOptions.h \
    $${PWD}/OAICreateCaseRequest.h \
    $${PWD}/OAICreateCaseResponse.h \
    $${PWD}/OAIDateInterval.h \
    $${PWD}/OAIDescribeAttachmentRequest.h \
    $${PWD}/OAIDescribeAttachmentResponse.h \
    $${PWD}/OAIDescribeAttachmentResponse_attachment.h \
    $${PWD}/OAIDescribeCasesRequest.h \
    $${PWD}/OAIDescribeCasesResponse.h \
    $${PWD}/OAIDescribeCommunicationsRequest.h \
    $${PWD}/OAIDescribeCommunicationsResponse.h \
    $${PWD}/OAIDescribeCreateCaseOptionsRequest.h \
    $${PWD}/OAIDescribeCreateCaseOptionsResponse.h \
    $${PWD}/OAIDescribeServicesRequest.h \
    $${PWD}/OAIDescribeServicesResponse.h \
    $${PWD}/OAIDescribeSeverityLevelsRequest.h \
    $${PWD}/OAIDescribeSeverityLevelsResponse.h \
    $${PWD}/OAIDescribeSupportedLanguagesRequest.h \
    $${PWD}/OAIDescribeSupportedLanguagesResponse.h \
    $${PWD}/OAIDescribeTrustedAdvisorCheckRefreshStatusesRequest.h \
    $${PWD}/OAIDescribeTrustedAdvisorCheckRefreshStatusesResponse.h \
    $${PWD}/OAIDescribeTrustedAdvisorCheckResultRequest.h \
    $${PWD}/OAIDescribeTrustedAdvisorCheckResultResponse.h \
    $${PWD}/OAIDescribeTrustedAdvisorCheckResultResponse_result.h \
    $${PWD}/OAIDescribeTrustedAdvisorCheckSummariesRequest.h \
    $${PWD}/OAIDescribeTrustedAdvisorCheckSummariesResponse.h \
    $${PWD}/OAIDescribeTrustedAdvisorChecksRequest.h \
    $${PWD}/OAIDescribeTrustedAdvisorChecksResponse.h \
    $${PWD}/OAIRecentCaseCommunications.h \
    $${PWD}/OAIRefreshTrustedAdvisorCheckRequest.h \
    $${PWD}/OAIRefreshTrustedAdvisorCheckResponse.h \
    $${PWD}/OAIRefreshTrustedAdvisorCheckResponse_status.h \
    $${PWD}/OAIResolveCaseRequest.h \
    $${PWD}/OAIResolveCaseResponse.h \
    $${PWD}/OAIService.h \
    $${PWD}/OAISeverityLevel.h \
    $${PWD}/OAISupportedHour.h \
    $${PWD}/OAISupportedLanguage.h \
    $${PWD}/OAITrustedAdvisorCategorySpecificSummary.h \
    $${PWD}/OAITrustedAdvisorCategorySpecificSummary_costOptimizing.h \
    $${PWD}/OAITrustedAdvisorCheckDescription.h \
    $${PWD}/OAITrustedAdvisorCheckRefreshStatus.h \
    $${PWD}/OAITrustedAdvisorCheckResult.h \
    $${PWD}/OAITrustedAdvisorCheckResult_categorySpecificSummary.h \
    $${PWD}/OAITrustedAdvisorCheckSummary.h \
    $${PWD}/OAITrustedAdvisorCostOptimizingSummary.h \
    $${PWD}/OAITrustedAdvisorResourceDetail.h \
    $${PWD}/OAITrustedAdvisorResourcesSummary.h \
# APIs
    $${PWD}/OAIDefaultApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAddAttachmentsToSetRequest.cpp \
    $${PWD}/OAIAddAttachmentsToSetResponse.cpp \
    $${PWD}/OAIAddCommunicationToCaseRequest.cpp \
    $${PWD}/OAIAddCommunicationToCaseResponse.cpp \
    $${PWD}/OAIAttachment.cpp \
    $${PWD}/OAIAttachmentDetails.cpp \
    $${PWD}/OAICaseDetails.cpp \
    $${PWD}/OAICaseDetails_recentCommunications.cpp \
    $${PWD}/OAICategory.cpp \
    $${PWD}/OAICommunication.cpp \
    $${PWD}/OAICommunicationTypeOptions.cpp \
    $${PWD}/OAICreateCaseRequest.cpp \
    $${PWD}/OAICreateCaseResponse.cpp \
    $${PWD}/OAIDateInterval.cpp \
    $${PWD}/OAIDescribeAttachmentRequest.cpp \
    $${PWD}/OAIDescribeAttachmentResponse.cpp \
    $${PWD}/OAIDescribeAttachmentResponse_attachment.cpp \
    $${PWD}/OAIDescribeCasesRequest.cpp \
    $${PWD}/OAIDescribeCasesResponse.cpp \
    $${PWD}/OAIDescribeCommunicationsRequest.cpp \
    $${PWD}/OAIDescribeCommunicationsResponse.cpp \
    $${PWD}/OAIDescribeCreateCaseOptionsRequest.cpp \
    $${PWD}/OAIDescribeCreateCaseOptionsResponse.cpp \
    $${PWD}/OAIDescribeServicesRequest.cpp \
    $${PWD}/OAIDescribeServicesResponse.cpp \
    $${PWD}/OAIDescribeSeverityLevelsRequest.cpp \
    $${PWD}/OAIDescribeSeverityLevelsResponse.cpp \
    $${PWD}/OAIDescribeSupportedLanguagesRequest.cpp \
    $${PWD}/OAIDescribeSupportedLanguagesResponse.cpp \
    $${PWD}/OAIDescribeTrustedAdvisorCheckRefreshStatusesRequest.cpp \
    $${PWD}/OAIDescribeTrustedAdvisorCheckRefreshStatusesResponse.cpp \
    $${PWD}/OAIDescribeTrustedAdvisorCheckResultRequest.cpp \
    $${PWD}/OAIDescribeTrustedAdvisorCheckResultResponse.cpp \
    $${PWD}/OAIDescribeTrustedAdvisorCheckResultResponse_result.cpp \
    $${PWD}/OAIDescribeTrustedAdvisorCheckSummariesRequest.cpp \
    $${PWD}/OAIDescribeTrustedAdvisorCheckSummariesResponse.cpp \
    $${PWD}/OAIDescribeTrustedAdvisorChecksRequest.cpp \
    $${PWD}/OAIDescribeTrustedAdvisorChecksResponse.cpp \
    $${PWD}/OAIRecentCaseCommunications.cpp \
    $${PWD}/OAIRefreshTrustedAdvisorCheckRequest.cpp \
    $${PWD}/OAIRefreshTrustedAdvisorCheckResponse.cpp \
    $${PWD}/OAIRefreshTrustedAdvisorCheckResponse_status.cpp \
    $${PWD}/OAIResolveCaseRequest.cpp \
    $${PWD}/OAIResolveCaseResponse.cpp \
    $${PWD}/OAIService.cpp \
    $${PWD}/OAISeverityLevel.cpp \
    $${PWD}/OAISupportedHour.cpp \
    $${PWD}/OAISupportedLanguage.cpp \
    $${PWD}/OAITrustedAdvisorCategorySpecificSummary.cpp \
    $${PWD}/OAITrustedAdvisorCategorySpecificSummary_costOptimizing.cpp \
    $${PWD}/OAITrustedAdvisorCheckDescription.cpp \
    $${PWD}/OAITrustedAdvisorCheckRefreshStatus.cpp \
    $${PWD}/OAITrustedAdvisorCheckResult.cpp \
    $${PWD}/OAITrustedAdvisorCheckResult_categorySpecificSummary.cpp \
    $${PWD}/OAITrustedAdvisorCheckSummary.cpp \
    $${PWD}/OAITrustedAdvisorCostOptimizingSummary.cpp \
    $${PWD}/OAITrustedAdvisorResourceDetail.cpp \
    $${PWD}/OAITrustedAdvisorResourcesSummary.cpp \
# APIs
    $${PWD}/OAIDefaultApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
