# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.google_chrome_management_v1_device_aue_count_report import GoogleChromeManagementV1DeviceAueCountReport
from openapi_server import util


class GoogleChromeManagementV1CountChromeDevicesReachingAutoExpirationDateResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, device_aue_count_reports: List[GoogleChromeManagementV1DeviceAueCountReport]=None):
        """GoogleChromeManagementV1CountChromeDevicesReachingAutoExpirationDateResponse - a model defined in OpenAPI

        :param device_aue_count_reports: The device_aue_count_reports of this GoogleChromeManagementV1CountChromeDevicesReachingAutoExpirationDateResponse.
        """
        self.openapi_types = {
            'device_aue_count_reports': List[GoogleChromeManagementV1DeviceAueCountReport]
        }

        self.attribute_map = {
            'device_aue_count_reports': 'deviceAueCountReports'
        }

        self._device_aue_count_reports = device_aue_count_reports

    @classmethod
    def from_dict(cls, dikt: dict) -> 'GoogleChromeManagementV1CountChromeDevicesReachingAutoExpirationDateResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The GoogleChromeManagementV1CountChromeDevicesReachingAutoExpirationDateResponse of this GoogleChromeManagementV1CountChromeDevicesReachingAutoExpirationDateResponse.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def device_aue_count_reports(self):
        """Gets the device_aue_count_reports of this GoogleChromeManagementV1CountChromeDevicesReachingAutoExpirationDateResponse.

        The list of reports sorted by auto update expiration date in ascending order.

        :return: The device_aue_count_reports of this GoogleChromeManagementV1CountChromeDevicesReachingAutoExpirationDateResponse.
        :rtype: List[GoogleChromeManagementV1DeviceAueCountReport]
        """
        return self._device_aue_count_reports

    @device_aue_count_reports.setter
    def device_aue_count_reports(self, device_aue_count_reports):
        """Sets the device_aue_count_reports of this GoogleChromeManagementV1CountChromeDevicesReachingAutoExpirationDateResponse.

        The list of reports sorted by auto update expiration date in ascending order.

        :param device_aue_count_reports: The device_aue_count_reports of this GoogleChromeManagementV1CountChromeDevicesReachingAutoExpirationDateResponse.
        :type device_aue_count_reports: List[GoogleChromeManagementV1DeviceAueCountReport]
        """

        self._device_aue_count_reports = device_aue_count_reports
