openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: "Manage properties in Google Analytics. Warning: Creating multiple\
    \ Customer Applications, Accounts, or Projects to simulate or act as a single\
    \ Customer Application, Account, or Project (respectively) or to circumvent Service-specific\
    \ usage limits or quotas is a direct violation of Google Cloud Platform Terms\
    \ of Service as well as Google APIs Terms of Service. These actions can result\
    \ in immediate termination of your GCP project(s) without any warning."
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Google Analytics Admin API
  version: v1beta
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://upload.wikimedia.org/wikipedia/commons/e/e1/YouTube_play_buttom_icon_%282013-2017%29.svg
  x-origin:
  - format: google
    url: https://analyticsadmin.googleapis.com/$discovery/rest?version=v1beta
    version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: analyticsadmin
servers:
- url: https://analyticsadmin.googleapis.com/
tags:
- name: accounts
- name: accountSummaries
- name: properties
paths:
  /v1beta/accountSummaries:
    get:
      description: Returns summaries of all accounts accessible by the caller.
      operationId: analyticsadmin_account_summaries_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - accountSummaries
      x-openapi-router-controller: openapi_server.controllers.account_summaries_controller
  /v1beta/accounts:
    get:
      description: "Returns all accounts accessible by the caller. Note that these\
        \ accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\"\
        ) accounts are excluded by default. Returns an empty list if no relevant accounts\
        \ are found."
      operationId: analyticsadmin_accounts_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /v1beta/accounts:provisionAccountTicket:
    post:
      description: Requests a ticket for creating an account.
      operationId: analyticsadmin_accounts_provision_account_ticket
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /v1beta/properties:
    get:
      description: "Returns child Properties under the specified parent Account. Only\
        \ \"GA4\" properties will be returned. Properties will be excluded if the\
        \ caller does not have access. Soft-deleted (ie: \"trashed\") properties are\
        \ excluded by default. Returns an empty list if no relevant properties are\
        \ found."
      operationId: analyticsadmin_properties_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates an "GA4" property with the specified location and attributes.
      operationId: analyticsadmin_properties_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1beta/{account}:searchChangeHistoryEvents:
    post:
      description: Searches through all changes to an account or its children given
        the specified set of filters.
      operationId: analyticsadmin_accounts_search_change_history_events
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - accounts
      x-openapi-router-controller: openapi_server.controllers.accounts_controller
  /v1beta/{entity}:runAccessReport:
    post:
      description: "Returns a customized report of data access records. The report\
        \ provides records of each time a user reads Google Analytics reporting data.\
        \ Access records are retained for up to 2 years. Data Access Reports can be\
        \ requested for a property. Reports may be requested for any property, but\
        \ dimensions that aren't related to quota can only be requested on Google\
        \ Analytics 360 properties. This method is only available to Administrators.\
        \ These data access records include GA4 UI Reporting, GA4 UI Explorations,\
        \ GA4 Data API, and other products like Firebase & Admob that can retrieve\
        \ data from Google Analytics through a linkage. These records don't include\
        \ property configuration changes like adding a stream or changing a property's\
        \ time zone. For configuration change history, see [searchChangeHistoryEvents](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/accounts/searchChangeHistoryEvents)."
      operationId: analyticsadmin_properties_run_access_report
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1beta/{name}:
    delete:
      description: Deletes a GoogleAdsLink on a property
      operationId: analyticsadmin_properties_google_ads_links_delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    get:
      description: Lookup for a single "GA4" MeasurementProtocolSecret.
      operationId: analyticsadmin_properties_data_streams_measurement_protocol_secrets_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    patch:
      description: Updates a GoogleAdsLink on a property
      operationId: analyticsadmin_properties_google_ads_links_patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1beta/{name}:archive:
    post:
      description: Archives a CustomMetric on a property.
      operationId: analyticsadmin_properties_custom_metrics_archive
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1beta/{parent}/conversionEvents:
    get:
      description: Returns a list of conversion events in the specified parent property.
        Returns an empty list if no conversion events are found.
      operationId: analyticsadmin_properties_conversion_events_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates a conversion event with the specified attributes.
      operationId: analyticsadmin_properties_conversion_events_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1beta/{parent}/customDimensions:
    get:
      description: Lists CustomDimensions on a property.
      operationId: analyticsadmin_properties_custom_dimensions_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates a CustomDimension.
      operationId: analyticsadmin_properties_custom_dimensions_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1beta/{parent}/customMetrics:
    get:
      description: Lists CustomMetrics on a property.
      operationId: analyticsadmin_properties_custom_metrics_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates a CustomMetric.
      operationId: analyticsadmin_properties_custom_metrics_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1beta/{parent}/dataStreams:
    get:
      description: Lists DataStreams on a property.
      operationId: analyticsadmin_properties_data_streams_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates a DataStream.
      operationId: analyticsadmin_properties_data_streams_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1beta/{parent}/firebaseLinks:
    get:
      description: Lists FirebaseLinks on a property. Properties can have at most
        one FirebaseLink.
      operationId: analyticsadmin_properties_firebase_links_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates a FirebaseLink. Properties can have at most one FirebaseLink.
      operationId: analyticsadmin_properties_firebase_links_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1beta/{parent}/googleAdsLinks:
    get:
      description: Lists GoogleAdsLinks on a property.
      operationId: analyticsadmin_properties_google_ads_links_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates a GoogleAdsLink.
      operationId: analyticsadmin_properties_google_ads_links_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1beta/{parent}/measurementProtocolSecrets:
    get:
      description: Returns child MeasurementProtocolSecrets under the specified parent
        Property.
      operationId: analyticsadmin_properties_data_streams_measurement_protocol_secrets_list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
    post:
      description: Creates a measurement protocol secret.
      operationId: analyticsadmin_properties_data_streams_measurement_protocol_secrets_create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
  /v1beta/{property}:acknowledgeUserDataCollection:
    post:
      description: Acknowledges the terms of user data collection for the specified
        property. This acknowledgement must be completed (either in the Google Analytics
        UI or through this API) before MeasurementProtocolSecret resources may be
        created.
      operationId: analyticsadmin_properties_acknowledge_user_data_collection
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - properties
      x-openapi-router-controller: openapi_server.controllers.properties_controller
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/analytics.edit: Edit Google Analytics
              management entities
            https://www.googleapis.com/auth/analytics.readonly: See and download your
              Google Analytics data
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/analytics.edit: Edit Google Analytics
              management entities
            https://www.googleapis.com/auth/analytics.readonly: See and download your
              Google Analytics data
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2c
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2c
