QT += network

HEADERS += \
# Models
    $${PWD}/OAIAction.h \
    $${PWD}/OAIAssociateFirewallRuleGroupRequest.h \
    $${PWD}/OAIAssociateFirewallRuleGroupResponse.h \
    $${PWD}/OAIAssociateFirewallRuleGroupResponse_FirewallRuleGroupAssociation.h \
    $${PWD}/OAIAssociateResolverEndpointIpAddressRequest.h \
    $${PWD}/OAIAssociateResolverEndpointIpAddressRequest_IpAddress.h \
    $${PWD}/OAIAssociateResolverEndpointIpAddressResponse.h \
    $${PWD}/OAIAssociateResolverEndpointIpAddressResponse_ResolverEndpoint.h \
    $${PWD}/OAIAssociateResolverQueryLogConfigRequest.h \
    $${PWD}/OAIAssociateResolverQueryLogConfigResponse.h \
    $${PWD}/OAIAssociateResolverQueryLogConfigResponse_ResolverQueryLogConfigAssociation.h \
    $${PWD}/OAIAssociateResolverRuleRequest.h \
    $${PWD}/OAIAssociateResolverRuleResponse.h \
    $${PWD}/OAIAssociateResolverRuleResponse_ResolverRuleAssociation.h \
    $${PWD}/OAIAutodefinedReverseFlag.h \
    $${PWD}/OAIBlockOverrideDnsType.h \
    $${PWD}/OAIBlockResponse.h \
    $${PWD}/OAICreateFirewallDomainListRequest.h \
    $${PWD}/OAICreateFirewallDomainListResponse.h \
    $${PWD}/OAICreateFirewallDomainListResponse_FirewallDomainList.h \
    $${PWD}/OAICreateFirewallRuleGroupRequest.h \
    $${PWD}/OAICreateFirewallRuleGroupResponse.h \
    $${PWD}/OAICreateFirewallRuleGroupResponse_FirewallRuleGroup.h \
    $${PWD}/OAICreateFirewallRuleRequest.h \
    $${PWD}/OAICreateFirewallRuleResponse.h \
    $${PWD}/OAICreateFirewallRuleResponse_FirewallRule.h \
    $${PWD}/OAICreateOutpostResolverRequest.h \
    $${PWD}/OAICreateOutpostResolverResponse.h \
    $${PWD}/OAICreateOutpostResolverResponse_OutpostResolver.h \
    $${PWD}/OAICreateResolverEndpointRequest.h \
    $${PWD}/OAICreateResolverEndpointResponse.h \
    $${PWD}/OAICreateResolverEndpointResponse_ResolverEndpoint.h \
    $${PWD}/OAICreateResolverQueryLogConfigRequest.h \
    $${PWD}/OAICreateResolverQueryLogConfigResponse.h \
    $${PWD}/OAICreateResolverQueryLogConfigResponse_ResolverQueryLogConfig.h \
    $${PWD}/OAICreateResolverRuleRequest.h \
    $${PWD}/OAICreateResolverRuleResponse.h \
    $${PWD}/OAICreateResolverRuleResponse_ResolverRule.h \
    $${PWD}/OAIDeleteFirewallDomainListRequest.h \
    $${PWD}/OAIDeleteFirewallDomainListResponse.h \
    $${PWD}/OAIDeleteFirewallDomainListResponse_FirewallDomainList.h \
    $${PWD}/OAIDeleteFirewallRuleGroupRequest.h \
    $${PWD}/OAIDeleteFirewallRuleGroupResponse.h \
    $${PWD}/OAIDeleteFirewallRuleRequest.h \
    $${PWD}/OAIDeleteFirewallRuleResponse.h \
    $${PWD}/OAIDeleteFirewallRuleResponse_FirewallRule.h \
    $${PWD}/OAIDeleteOutpostResolverRequest.h \
    $${PWD}/OAIDeleteOutpostResolverResponse.h \
    $${PWD}/OAIDeleteOutpostResolverResponse_OutpostResolver.h \
    $${PWD}/OAIDeleteResolverEndpointRequest.h \
    $${PWD}/OAIDeleteResolverEndpointResponse.h \
    $${PWD}/OAIDeleteResolverEndpointResponse_ResolverEndpoint.h \
    $${PWD}/OAIDeleteResolverQueryLogConfigRequest.h \
    $${PWD}/OAIDeleteResolverQueryLogConfigResponse.h \
    $${PWD}/OAIDeleteResolverQueryLogConfigResponse_ResolverQueryLogConfig.h \
    $${PWD}/OAIDeleteResolverRuleRequest.h \
    $${PWD}/OAIDeleteResolverRuleResponse.h \
    $${PWD}/OAIDeleteResolverRuleResponse_ResolverRule.h \
    $${PWD}/OAIDisassociateFirewallRuleGroupRequest.h \
    $${PWD}/OAIDisassociateFirewallRuleGroupResponse.h \
    $${PWD}/OAIDisassociateFirewallRuleGroupResponse_FirewallRuleGroupAssociation.h \
    $${PWD}/OAIDisassociateResolverEndpointIpAddressRequest.h \
    $${PWD}/OAIDisassociateResolverEndpointIpAddressRequest_IpAddress.h \
    $${PWD}/OAIDisassociateResolverEndpointIpAddressResponse.h \
    $${PWD}/OAIDisassociateResolverEndpointIpAddressResponse_ResolverEndpoint.h \
    $${PWD}/OAIDisassociateResolverQueryLogConfigRequest.h \
    $${PWD}/OAIDisassociateResolverQueryLogConfigResponse.h \
    $${PWD}/OAIDisassociateResolverQueryLogConfigResponse_ResolverQueryLogConfigAssociation.h \
    $${PWD}/OAIDisassociateResolverRuleRequest.h \
    $${PWD}/OAIDisassociateResolverRuleResponse.h \
    $${PWD}/OAIDisassociateResolverRuleResponse_ResolverRuleAssociation.h \
    $${PWD}/OAIFilter.h \
    $${PWD}/OAIFirewallConfig.h \
    $${PWD}/OAIFirewallDomainImportOperation.h \
    $${PWD}/OAIFirewallDomainList.h \
    $${PWD}/OAIFirewallDomainListMetadata.h \
    $${PWD}/OAIFirewallDomainListStatus.h \
    $${PWD}/OAIFirewallDomainUpdateOperation.h \
    $${PWD}/OAIFirewallFailOpenStatus.h \
    $${PWD}/OAIFirewallRule.h \
    $${PWD}/OAIFirewallRuleGroup.h \
    $${PWD}/OAIFirewallRuleGroupAssociation.h \
    $${PWD}/OAIFirewallRuleGroupAssociationStatus.h \
    $${PWD}/OAIFirewallRuleGroupMetadata.h \
    $${PWD}/OAIFirewallRuleGroupStatus.h \
    $${PWD}/OAIGetFirewallConfigRequest.h \
    $${PWD}/OAIGetFirewallConfigResponse.h \
    $${PWD}/OAIGetFirewallConfigResponse_FirewallConfig.h \
    $${PWD}/OAIGetFirewallDomainListRequest.h \
    $${PWD}/OAIGetFirewallDomainListResponse.h \
    $${PWD}/OAIGetFirewallDomainListResponse_FirewallDomainList.h \
    $${PWD}/OAIGetFirewallRuleGroupAssociationRequest.h \
    $${PWD}/OAIGetFirewallRuleGroupAssociationResponse.h \
    $${PWD}/OAIGetFirewallRuleGroupAssociationResponse_FirewallRuleGroupAssociation.h \
    $${PWD}/OAIGetFirewallRuleGroupPolicyRequest.h \
    $${PWD}/OAIGetFirewallRuleGroupPolicyResponse.h \
    $${PWD}/OAIGetFirewallRuleGroupRequest.h \
    $${PWD}/OAIGetFirewallRuleGroupResponse.h \
    $${PWD}/OAIGetOutpostResolverRequest.h \
    $${PWD}/OAIGetOutpostResolverResponse.h \
    $${PWD}/OAIGetOutpostResolverResponse_OutpostResolver.h \
    $${PWD}/OAIGetResolverConfigRequest.h \
    $${PWD}/OAIGetResolverConfigResponse.h \
    $${PWD}/OAIGetResolverConfigResponse_ResolverConfig.h \
    $${PWD}/OAIGetResolverDnssecConfigRequest.h \
    $${PWD}/OAIGetResolverDnssecConfigResponse.h \
    $${PWD}/OAIGetResolverDnssecConfigResponse_ResolverDNSSECConfig.h \
    $${PWD}/OAIGetResolverEndpointRequest.h \
    $${PWD}/OAIGetResolverEndpointResponse.h \
    $${PWD}/OAIGetResolverEndpointResponse_ResolverEndpoint.h \
    $${PWD}/OAIGetResolverQueryLogConfigAssociationRequest.h \
    $${PWD}/OAIGetResolverQueryLogConfigAssociationResponse.h \
    $${PWD}/OAIGetResolverQueryLogConfigAssociationResponse_ResolverQueryLogConfigAssociation.h \
    $${PWD}/OAIGetResolverQueryLogConfigPolicyRequest.h \
    $${PWD}/OAIGetResolverQueryLogConfigPolicyResponse.h \
    $${PWD}/OAIGetResolverQueryLogConfigRequest.h \
    $${PWD}/OAIGetResolverQueryLogConfigResponse.h \
    $${PWD}/OAIGetResolverQueryLogConfigResponse_ResolverQueryLogConfig.h \
    $${PWD}/OAIGetResolverRuleAssociationRequest.h \
    $${PWD}/OAIGetResolverRuleAssociationResponse.h \
    $${PWD}/OAIGetResolverRuleAssociationResponse_ResolverRuleAssociation.h \
    $${PWD}/OAIGetResolverRulePolicyRequest.h \
    $${PWD}/OAIGetResolverRulePolicyResponse.h \
    $${PWD}/OAIGetResolverRuleRequest.h \
    $${PWD}/OAIGetResolverRuleResponse.h \
    $${PWD}/OAIGetResolverRuleResponse_ResolverRule.h \
    $${PWD}/OAIImportFirewallDomainsRequest.h \
    $${PWD}/OAIImportFirewallDomainsResponse.h \
    $${PWD}/OAIIpAddressRequest.h \
    $${PWD}/OAIIpAddressResponse.h \
    $${PWD}/OAIIpAddressStatus.h \
    $${PWD}/OAIIpAddressUpdate.h \
    $${PWD}/OAIListFirewallConfigsRequest.h \
    $${PWD}/OAIListFirewallConfigsResponse.h \
    $${PWD}/OAIListFirewallDomainListsRequest.h \
    $${PWD}/OAIListFirewallDomainListsResponse.h \
    $${PWD}/OAIListFirewallDomainsRequest.h \
    $${PWD}/OAIListFirewallDomainsResponse.h \
    $${PWD}/OAIListFirewallRuleGroupAssociationsRequest.h \
    $${PWD}/OAIListFirewallRuleGroupAssociationsResponse.h \
    $${PWD}/OAIListFirewallRuleGroupsRequest.h \
    $${PWD}/OAIListFirewallRuleGroupsResponse.h \
    $${PWD}/OAIListFirewallRulesRequest.h \
    $${PWD}/OAIListFirewallRulesResponse.h \
    $${PWD}/OAIListOutpostResolversRequest.h \
    $${PWD}/OAIListOutpostResolversResponse.h \
    $${PWD}/OAIListResolverConfigsRequest.h \
    $${PWD}/OAIListResolverConfigsResponse.h \
    $${PWD}/OAIListResolverDnssecConfigsRequest.h \
    $${PWD}/OAIListResolverDnssecConfigsResponse.h \
    $${PWD}/OAIListResolverEndpointIpAddressesRequest.h \
    $${PWD}/OAIListResolverEndpointIpAddressesResponse.h \
    $${PWD}/OAIListResolverEndpointsRequest.h \
    $${PWD}/OAIListResolverEndpointsResponse.h \
    $${PWD}/OAIListResolverQueryLogConfigAssociationsRequest.h \
    $${PWD}/OAIListResolverQueryLogConfigAssociationsResponse.h \
    $${PWD}/OAIListResolverQueryLogConfigsRequest.h \
    $${PWD}/OAIListResolverQueryLogConfigsResponse.h \
    $${PWD}/OAIListResolverRuleAssociationsRequest.h \
    $${PWD}/OAIListResolverRuleAssociationsResponse.h \
    $${PWD}/OAIListResolverRulesRequest.h \
    $${PWD}/OAIListResolverRulesResponse.h \
    $${PWD}/OAIListTagsForResourceRequest.h \
    $${PWD}/OAIListTagsForResourceResponse.h \
    $${PWD}/OAIMutationProtectionStatus.h \
    $${PWD}/OAIOutpostResolver.h \
    $${PWD}/OAIOutpostResolverStatus.h \
    $${PWD}/OAIPutFirewallRuleGroupPolicyRequest.h \
    $${PWD}/OAIPutFirewallRuleGroupPolicyResponse.h \
    $${PWD}/OAIPutResolverQueryLogConfigPolicyRequest.h \
    $${PWD}/OAIPutResolverQueryLogConfigPolicyResponse.h \
    $${PWD}/OAIPutResolverRulePolicyRequest.h \
    $${PWD}/OAIPutResolverRulePolicyResponse.h \
    $${PWD}/OAIResolverAutodefinedReverseStatus.h \
    $${PWD}/OAIResolverConfig.h \
    $${PWD}/OAIResolverDNSSECValidationStatus.h \
    $${PWD}/OAIResolverDnssecConfig.h \
    $${PWD}/OAIResolverEndpoint.h \
    $${PWD}/OAIResolverEndpointDirection.h \
    $${PWD}/OAIResolverEndpointStatus.h \
    $${PWD}/OAIResolverEndpointType.h \
    $${PWD}/OAIResolverQueryLogConfig.h \
    $${PWD}/OAIResolverQueryLogConfigAssociation.h \
    $${PWD}/OAIResolverQueryLogConfigAssociationError.h \
    $${PWD}/OAIResolverQueryLogConfigAssociationStatus.h \
    $${PWD}/OAIResolverQueryLogConfigStatus.h \
    $${PWD}/OAIResolverRule.h \
    $${PWD}/OAIResolverRuleAssociation.h \
    $${PWD}/OAIResolverRuleAssociationStatus.h \
    $${PWD}/OAIResolverRuleConfig.h \
    $${PWD}/OAIResolverRuleStatus.h \
    $${PWD}/OAIRuleTypeOption.h \
    $${PWD}/OAIShareStatus.h \
    $${PWD}/OAISortOrder.h \
    $${PWD}/OAITag.h \
    $${PWD}/OAITagResourceRequest.h \
    $${PWD}/OAITargetAddress.h \
    $${PWD}/OAIUntagResourceRequest.h \
    $${PWD}/OAIUpdateFirewallConfigRequest.h \
    $${PWD}/OAIUpdateFirewallConfigResponse.h \
    $${PWD}/OAIUpdateFirewallConfigResponse_FirewallConfig.h \
    $${PWD}/OAIUpdateFirewallDomainsRequest.h \
    $${PWD}/OAIUpdateFirewallDomainsResponse.h \
    $${PWD}/OAIUpdateFirewallRuleGroupAssociationRequest.h \
    $${PWD}/OAIUpdateFirewallRuleGroupAssociationResponse.h \
    $${PWD}/OAIUpdateFirewallRuleGroupAssociationResponse_FirewallRuleGroupAssociation.h \
    $${PWD}/OAIUpdateFirewallRuleRequest.h \
    $${PWD}/OAIUpdateFirewallRuleResponse.h \
    $${PWD}/OAIUpdateFirewallRuleResponse_FirewallRule.h \
    $${PWD}/OAIUpdateIpAddress.h \
    $${PWD}/OAIUpdateOutpostResolverRequest.h \
    $${PWD}/OAIUpdateOutpostResolverResponse.h \
    $${PWD}/OAIUpdateOutpostResolverResponse_OutpostResolver.h \
    $${PWD}/OAIUpdateResolverConfigRequest.h \
    $${PWD}/OAIUpdateResolverConfigResponse.h \
    $${PWD}/OAIUpdateResolverConfigResponse_ResolverConfig.h \
    $${PWD}/OAIUpdateResolverDnssecConfigRequest.h \
    $${PWD}/OAIUpdateResolverDnssecConfigResponse.h \
    $${PWD}/OAIUpdateResolverDnssecConfigResponse_ResolverDNSSECConfig.h \
    $${PWD}/OAIUpdateResolverEndpointRequest.h \
    $${PWD}/OAIUpdateResolverEndpointResponse.h \
    $${PWD}/OAIUpdateResolverEndpointResponse_ResolverEndpoint.h \
    $${PWD}/OAIUpdateResolverRuleRequest.h \
    $${PWD}/OAIUpdateResolverRuleRequest_Config.h \
    $${PWD}/OAIUpdateResolverRuleResponse.h \
    $${PWD}/OAIUpdateResolverRuleResponse_ResolverRule.h \
    $${PWD}/OAIValidation.h \
# APIs
    $${PWD}/OAIDefaultApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAction.cpp \
    $${PWD}/OAIAssociateFirewallRuleGroupRequest.cpp \
    $${PWD}/OAIAssociateFirewallRuleGroupResponse.cpp \
    $${PWD}/OAIAssociateFirewallRuleGroupResponse_FirewallRuleGroupAssociation.cpp \
    $${PWD}/OAIAssociateResolverEndpointIpAddressRequest.cpp \
    $${PWD}/OAIAssociateResolverEndpointIpAddressRequest_IpAddress.cpp \
    $${PWD}/OAIAssociateResolverEndpointIpAddressResponse.cpp \
    $${PWD}/OAIAssociateResolverEndpointIpAddressResponse_ResolverEndpoint.cpp \
    $${PWD}/OAIAssociateResolverQueryLogConfigRequest.cpp \
    $${PWD}/OAIAssociateResolverQueryLogConfigResponse.cpp \
    $${PWD}/OAIAssociateResolverQueryLogConfigResponse_ResolverQueryLogConfigAssociation.cpp \
    $${PWD}/OAIAssociateResolverRuleRequest.cpp \
    $${PWD}/OAIAssociateResolverRuleResponse.cpp \
    $${PWD}/OAIAssociateResolverRuleResponse_ResolverRuleAssociation.cpp \
    $${PWD}/OAIAutodefinedReverseFlag.cpp \
    $${PWD}/OAIBlockOverrideDnsType.cpp \
    $${PWD}/OAIBlockResponse.cpp \
    $${PWD}/OAICreateFirewallDomainListRequest.cpp \
    $${PWD}/OAICreateFirewallDomainListResponse.cpp \
    $${PWD}/OAICreateFirewallDomainListResponse_FirewallDomainList.cpp \
    $${PWD}/OAICreateFirewallRuleGroupRequest.cpp \
    $${PWD}/OAICreateFirewallRuleGroupResponse.cpp \
    $${PWD}/OAICreateFirewallRuleGroupResponse_FirewallRuleGroup.cpp \
    $${PWD}/OAICreateFirewallRuleRequest.cpp \
    $${PWD}/OAICreateFirewallRuleResponse.cpp \
    $${PWD}/OAICreateFirewallRuleResponse_FirewallRule.cpp \
    $${PWD}/OAICreateOutpostResolverRequest.cpp \
    $${PWD}/OAICreateOutpostResolverResponse.cpp \
    $${PWD}/OAICreateOutpostResolverResponse_OutpostResolver.cpp \
    $${PWD}/OAICreateResolverEndpointRequest.cpp \
    $${PWD}/OAICreateResolverEndpointResponse.cpp \
    $${PWD}/OAICreateResolverEndpointResponse_ResolverEndpoint.cpp \
    $${PWD}/OAICreateResolverQueryLogConfigRequest.cpp \
    $${PWD}/OAICreateResolverQueryLogConfigResponse.cpp \
    $${PWD}/OAICreateResolverQueryLogConfigResponse_ResolverQueryLogConfig.cpp \
    $${PWD}/OAICreateResolverRuleRequest.cpp \
    $${PWD}/OAICreateResolverRuleResponse.cpp \
    $${PWD}/OAICreateResolverRuleResponse_ResolverRule.cpp \
    $${PWD}/OAIDeleteFirewallDomainListRequest.cpp \
    $${PWD}/OAIDeleteFirewallDomainListResponse.cpp \
    $${PWD}/OAIDeleteFirewallDomainListResponse_FirewallDomainList.cpp \
    $${PWD}/OAIDeleteFirewallRuleGroupRequest.cpp \
    $${PWD}/OAIDeleteFirewallRuleGroupResponse.cpp \
    $${PWD}/OAIDeleteFirewallRuleRequest.cpp \
    $${PWD}/OAIDeleteFirewallRuleResponse.cpp \
    $${PWD}/OAIDeleteFirewallRuleResponse_FirewallRule.cpp \
    $${PWD}/OAIDeleteOutpostResolverRequest.cpp \
    $${PWD}/OAIDeleteOutpostResolverResponse.cpp \
    $${PWD}/OAIDeleteOutpostResolverResponse_OutpostResolver.cpp \
    $${PWD}/OAIDeleteResolverEndpointRequest.cpp \
    $${PWD}/OAIDeleteResolverEndpointResponse.cpp \
    $${PWD}/OAIDeleteResolverEndpointResponse_ResolverEndpoint.cpp \
    $${PWD}/OAIDeleteResolverQueryLogConfigRequest.cpp \
    $${PWD}/OAIDeleteResolverQueryLogConfigResponse.cpp \
    $${PWD}/OAIDeleteResolverQueryLogConfigResponse_ResolverQueryLogConfig.cpp \
    $${PWD}/OAIDeleteResolverRuleRequest.cpp \
    $${PWD}/OAIDeleteResolverRuleResponse.cpp \
    $${PWD}/OAIDeleteResolverRuleResponse_ResolverRule.cpp \
    $${PWD}/OAIDisassociateFirewallRuleGroupRequest.cpp \
    $${PWD}/OAIDisassociateFirewallRuleGroupResponse.cpp \
    $${PWD}/OAIDisassociateFirewallRuleGroupResponse_FirewallRuleGroupAssociation.cpp \
    $${PWD}/OAIDisassociateResolverEndpointIpAddressRequest.cpp \
    $${PWD}/OAIDisassociateResolverEndpointIpAddressRequest_IpAddress.cpp \
    $${PWD}/OAIDisassociateResolverEndpointIpAddressResponse.cpp \
    $${PWD}/OAIDisassociateResolverEndpointIpAddressResponse_ResolverEndpoint.cpp \
    $${PWD}/OAIDisassociateResolverQueryLogConfigRequest.cpp \
    $${PWD}/OAIDisassociateResolverQueryLogConfigResponse.cpp \
    $${PWD}/OAIDisassociateResolverQueryLogConfigResponse_ResolverQueryLogConfigAssociation.cpp \
    $${PWD}/OAIDisassociateResolverRuleRequest.cpp \
    $${PWD}/OAIDisassociateResolverRuleResponse.cpp \
    $${PWD}/OAIDisassociateResolverRuleResponse_ResolverRuleAssociation.cpp \
    $${PWD}/OAIFilter.cpp \
    $${PWD}/OAIFirewallConfig.cpp \
    $${PWD}/OAIFirewallDomainImportOperation.cpp \
    $${PWD}/OAIFirewallDomainList.cpp \
    $${PWD}/OAIFirewallDomainListMetadata.cpp \
    $${PWD}/OAIFirewallDomainListStatus.cpp \
    $${PWD}/OAIFirewallDomainUpdateOperation.cpp \
    $${PWD}/OAIFirewallFailOpenStatus.cpp \
    $${PWD}/OAIFirewallRule.cpp \
    $${PWD}/OAIFirewallRuleGroup.cpp \
    $${PWD}/OAIFirewallRuleGroupAssociation.cpp \
    $${PWD}/OAIFirewallRuleGroupAssociationStatus.cpp \
    $${PWD}/OAIFirewallRuleGroupMetadata.cpp \
    $${PWD}/OAIFirewallRuleGroupStatus.cpp \
    $${PWD}/OAIGetFirewallConfigRequest.cpp \
    $${PWD}/OAIGetFirewallConfigResponse.cpp \
    $${PWD}/OAIGetFirewallConfigResponse_FirewallConfig.cpp \
    $${PWD}/OAIGetFirewallDomainListRequest.cpp \
    $${PWD}/OAIGetFirewallDomainListResponse.cpp \
    $${PWD}/OAIGetFirewallDomainListResponse_FirewallDomainList.cpp \
    $${PWD}/OAIGetFirewallRuleGroupAssociationRequest.cpp \
    $${PWD}/OAIGetFirewallRuleGroupAssociationResponse.cpp \
    $${PWD}/OAIGetFirewallRuleGroupAssociationResponse_FirewallRuleGroupAssociation.cpp \
    $${PWD}/OAIGetFirewallRuleGroupPolicyRequest.cpp \
    $${PWD}/OAIGetFirewallRuleGroupPolicyResponse.cpp \
    $${PWD}/OAIGetFirewallRuleGroupRequest.cpp \
    $${PWD}/OAIGetFirewallRuleGroupResponse.cpp \
    $${PWD}/OAIGetOutpostResolverRequest.cpp \
    $${PWD}/OAIGetOutpostResolverResponse.cpp \
    $${PWD}/OAIGetOutpostResolverResponse_OutpostResolver.cpp \
    $${PWD}/OAIGetResolverConfigRequest.cpp \
    $${PWD}/OAIGetResolverConfigResponse.cpp \
    $${PWD}/OAIGetResolverConfigResponse_ResolverConfig.cpp \
    $${PWD}/OAIGetResolverDnssecConfigRequest.cpp \
    $${PWD}/OAIGetResolverDnssecConfigResponse.cpp \
    $${PWD}/OAIGetResolverDnssecConfigResponse_ResolverDNSSECConfig.cpp \
    $${PWD}/OAIGetResolverEndpointRequest.cpp \
    $${PWD}/OAIGetResolverEndpointResponse.cpp \
    $${PWD}/OAIGetResolverEndpointResponse_ResolverEndpoint.cpp \
    $${PWD}/OAIGetResolverQueryLogConfigAssociationRequest.cpp \
    $${PWD}/OAIGetResolverQueryLogConfigAssociationResponse.cpp \
    $${PWD}/OAIGetResolverQueryLogConfigAssociationResponse_ResolverQueryLogConfigAssociation.cpp \
    $${PWD}/OAIGetResolverQueryLogConfigPolicyRequest.cpp \
    $${PWD}/OAIGetResolverQueryLogConfigPolicyResponse.cpp \
    $${PWD}/OAIGetResolverQueryLogConfigRequest.cpp \
    $${PWD}/OAIGetResolverQueryLogConfigResponse.cpp \
    $${PWD}/OAIGetResolverQueryLogConfigResponse_ResolverQueryLogConfig.cpp \
    $${PWD}/OAIGetResolverRuleAssociationRequest.cpp \
    $${PWD}/OAIGetResolverRuleAssociationResponse.cpp \
    $${PWD}/OAIGetResolverRuleAssociationResponse_ResolverRuleAssociation.cpp \
    $${PWD}/OAIGetResolverRulePolicyRequest.cpp \
    $${PWD}/OAIGetResolverRulePolicyResponse.cpp \
    $${PWD}/OAIGetResolverRuleRequest.cpp \
    $${PWD}/OAIGetResolverRuleResponse.cpp \
    $${PWD}/OAIGetResolverRuleResponse_ResolverRule.cpp \
    $${PWD}/OAIImportFirewallDomainsRequest.cpp \
    $${PWD}/OAIImportFirewallDomainsResponse.cpp \
    $${PWD}/OAIIpAddressRequest.cpp \
    $${PWD}/OAIIpAddressResponse.cpp \
    $${PWD}/OAIIpAddressStatus.cpp \
    $${PWD}/OAIIpAddressUpdate.cpp \
    $${PWD}/OAIListFirewallConfigsRequest.cpp \
    $${PWD}/OAIListFirewallConfigsResponse.cpp \
    $${PWD}/OAIListFirewallDomainListsRequest.cpp \
    $${PWD}/OAIListFirewallDomainListsResponse.cpp \
    $${PWD}/OAIListFirewallDomainsRequest.cpp \
    $${PWD}/OAIListFirewallDomainsResponse.cpp \
    $${PWD}/OAIListFirewallRuleGroupAssociationsRequest.cpp \
    $${PWD}/OAIListFirewallRuleGroupAssociationsResponse.cpp \
    $${PWD}/OAIListFirewallRuleGroupsRequest.cpp \
    $${PWD}/OAIListFirewallRuleGroupsResponse.cpp \
    $${PWD}/OAIListFirewallRulesRequest.cpp \
    $${PWD}/OAIListFirewallRulesResponse.cpp \
    $${PWD}/OAIListOutpostResolversRequest.cpp \
    $${PWD}/OAIListOutpostResolversResponse.cpp \
    $${PWD}/OAIListResolverConfigsRequest.cpp \
    $${PWD}/OAIListResolverConfigsResponse.cpp \
    $${PWD}/OAIListResolverDnssecConfigsRequest.cpp \
    $${PWD}/OAIListResolverDnssecConfigsResponse.cpp \
    $${PWD}/OAIListResolverEndpointIpAddressesRequest.cpp \
    $${PWD}/OAIListResolverEndpointIpAddressesResponse.cpp \
    $${PWD}/OAIListResolverEndpointsRequest.cpp \
    $${PWD}/OAIListResolverEndpointsResponse.cpp \
    $${PWD}/OAIListResolverQueryLogConfigAssociationsRequest.cpp \
    $${PWD}/OAIListResolverQueryLogConfigAssociationsResponse.cpp \
    $${PWD}/OAIListResolverQueryLogConfigsRequest.cpp \
    $${PWD}/OAIListResolverQueryLogConfigsResponse.cpp \
    $${PWD}/OAIListResolverRuleAssociationsRequest.cpp \
    $${PWD}/OAIListResolverRuleAssociationsResponse.cpp \
    $${PWD}/OAIListResolverRulesRequest.cpp \
    $${PWD}/OAIListResolverRulesResponse.cpp \
    $${PWD}/OAIListTagsForResourceRequest.cpp \
    $${PWD}/OAIListTagsForResourceResponse.cpp \
    $${PWD}/OAIMutationProtectionStatus.cpp \
    $${PWD}/OAIOutpostResolver.cpp \
    $${PWD}/OAIOutpostResolverStatus.cpp \
    $${PWD}/OAIPutFirewallRuleGroupPolicyRequest.cpp \
    $${PWD}/OAIPutFirewallRuleGroupPolicyResponse.cpp \
    $${PWD}/OAIPutResolverQueryLogConfigPolicyRequest.cpp \
    $${PWD}/OAIPutResolverQueryLogConfigPolicyResponse.cpp \
    $${PWD}/OAIPutResolverRulePolicyRequest.cpp \
    $${PWD}/OAIPutResolverRulePolicyResponse.cpp \
    $${PWD}/OAIResolverAutodefinedReverseStatus.cpp \
    $${PWD}/OAIResolverConfig.cpp \
    $${PWD}/OAIResolverDNSSECValidationStatus.cpp \
    $${PWD}/OAIResolverDnssecConfig.cpp \
    $${PWD}/OAIResolverEndpoint.cpp \
    $${PWD}/OAIResolverEndpointDirection.cpp \
    $${PWD}/OAIResolverEndpointStatus.cpp \
    $${PWD}/OAIResolverEndpointType.cpp \
    $${PWD}/OAIResolverQueryLogConfig.cpp \
    $${PWD}/OAIResolverQueryLogConfigAssociation.cpp \
    $${PWD}/OAIResolverQueryLogConfigAssociationError.cpp \
    $${PWD}/OAIResolverQueryLogConfigAssociationStatus.cpp \
    $${PWD}/OAIResolverQueryLogConfigStatus.cpp \
    $${PWD}/OAIResolverRule.cpp \
    $${PWD}/OAIResolverRuleAssociation.cpp \
    $${PWD}/OAIResolverRuleAssociationStatus.cpp \
    $${PWD}/OAIResolverRuleConfig.cpp \
    $${PWD}/OAIResolverRuleStatus.cpp \
    $${PWD}/OAIRuleTypeOption.cpp \
    $${PWD}/OAIShareStatus.cpp \
    $${PWD}/OAISortOrder.cpp \
    $${PWD}/OAITag.cpp \
    $${PWD}/OAITagResourceRequest.cpp \
    $${PWD}/OAITargetAddress.cpp \
    $${PWD}/OAIUntagResourceRequest.cpp \
    $${PWD}/OAIUpdateFirewallConfigRequest.cpp \
    $${PWD}/OAIUpdateFirewallConfigResponse.cpp \
    $${PWD}/OAIUpdateFirewallConfigResponse_FirewallConfig.cpp \
    $${PWD}/OAIUpdateFirewallDomainsRequest.cpp \
    $${PWD}/OAIUpdateFirewallDomainsResponse.cpp \
    $${PWD}/OAIUpdateFirewallRuleGroupAssociationRequest.cpp \
    $${PWD}/OAIUpdateFirewallRuleGroupAssociationResponse.cpp \
    $${PWD}/OAIUpdateFirewallRuleGroupAssociationResponse_FirewallRuleGroupAssociation.cpp \
    $${PWD}/OAIUpdateFirewallRuleRequest.cpp \
    $${PWD}/OAIUpdateFirewallRuleResponse.cpp \
    $${PWD}/OAIUpdateFirewallRuleResponse_FirewallRule.cpp \
    $${PWD}/OAIUpdateIpAddress.cpp \
    $${PWD}/OAIUpdateOutpostResolverRequest.cpp \
    $${PWD}/OAIUpdateOutpostResolverResponse.cpp \
    $${PWD}/OAIUpdateOutpostResolverResponse_OutpostResolver.cpp \
    $${PWD}/OAIUpdateResolverConfigRequest.cpp \
    $${PWD}/OAIUpdateResolverConfigResponse.cpp \
    $${PWD}/OAIUpdateResolverConfigResponse_ResolverConfig.cpp \
    $${PWD}/OAIUpdateResolverDnssecConfigRequest.cpp \
    $${PWD}/OAIUpdateResolverDnssecConfigResponse.cpp \
    $${PWD}/OAIUpdateResolverDnssecConfigResponse_ResolverDNSSECConfig.cpp \
    $${PWD}/OAIUpdateResolverEndpointRequest.cpp \
    $${PWD}/OAIUpdateResolverEndpointResponse.cpp \
    $${PWD}/OAIUpdateResolverEndpointResponse_ResolverEndpoint.cpp \
    $${PWD}/OAIUpdateResolverRuleRequest.cpp \
    $${PWD}/OAIUpdateResolverRuleRequest_Config.cpp \
    $${PWD}/OAIUpdateResolverRuleResponse.cpp \
    $${PWD}/OAIUpdateResolverRuleResponse_ResolverRule.cpp \
    $${PWD}/OAIValidation.cpp \
# APIs
    $${PWD}/OAIDefaultApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
