QT += network

HEADERS += \
# Models
    $${PWD}/OAIAddClientPreferences_request.h \
    $${PWD}/OAIAddClientProfile_request.h \
    $${PWD}/OAIAddCoupons_200_response.h \
    $${PWD}/OAIAddCoupons_200_response_availableAddresses_inner.h \
    $${PWD}/OAIAddCoupons_200_response_clientPreferencesData.h \
    $${PWD}/OAIAddCoupons_200_response_clientProfileData.h \
    $${PWD}/OAIAddCoupons_200_response_itemMetadata.h \
    $${PWD}/OAIAddCoupons_200_response_itemMetadata_items_inner.h \
    $${PWD}/OAIAddCoupons_200_response_itemsOrdination.h \
    $${PWD}/OAIAddCoupons_200_response_items_inner.h \
    $${PWD}/OAIAddCoupons_200_response_items_inner_additionalInfo.h \
    $${PWD}/OAIAddCoupons_200_response_items_inner_bundleItems_inner.h \
    $${PWD}/OAIAddCoupons_200_response_items_inner_priceDefinition.h \
    $${PWD}/OAIAddCoupons_200_response_items_inner_priceDefinition_sellingPrices_inner.h \
    $${PWD}/OAIAddCoupons_200_response_items_inner_priceTags_inner.h \
    $${PWD}/OAIAddCoupons_200_response_items_inner_productCategories.h \
    $${PWD}/OAIAddCoupons_200_response_marketingData.h \
    $${PWD}/OAIAddCoupons_200_response_paymentData.h \
    $${PWD}/OAIAddCoupons_200_response_paymentData_giftCards_inner.h \
    $${PWD}/OAIAddCoupons_200_response_paymentData_transactions_inner.h \
    $${PWD}/OAIAddCoupons_200_response_paymentData_transactions_inner_payments_inner.h \
    $${PWD}/OAIAddCoupons_200_response_ratesAndBenefitsData.h \
    $${PWD}/OAIAddCoupons_200_response_sellers_inner.h \
    $${PWD}/OAIAddCoupons_200_response_shippingData.h \
    $${PWD}/OAIAddCoupons_200_response_shippingData_address.h \
    $${PWD}/OAIAddCoupons_200_response_shippingData_availableAddresses_inner.h \
    $${PWD}/OAIAddCoupons_200_response_shippingData_logisticsInfo_inner.h \
    $${PWD}/OAIAddCoupons_200_response_shippingData_logisticsInfo_inner_deliveryChannels_inner.h \
    $${PWD}/OAIAddCoupons_200_response_shippingData_logisticsInfo_inner_slas_inner.h \
    $${PWD}/OAIAddCoupons_200_response_shippingData_logisticsInfo_inner_slas_inner_deliveryIds_inner.h \
    $${PWD}/OAIAddCoupons_200_response_shippingData_logisticsInfo_inner_slas_inner_pickupStoreInfo.h \
    $${PWD}/OAIAddCoupons_200_response_shippingData_logisticsInfo_inner_slas_inner_pickupStoreInfo_address.h \
    $${PWD}/OAIAddCoupons_request.h \
    $${PWD}/OAIAddMarketingData_request.h \
    $${PWD}/OAIAddMerchantContextData_200_response.h \
    $${PWD}/OAIAddMerchantContextData_request.h \
    $${PWD}/OAIAddMerchantContextData_request_salesAssociateData.h \
    $${PWD}/OAIAddPaymentData_request.h \
    $${PWD}/OAIAddPaymentData_request_payments_inner.h \
    $${PWD}/OAIAddShippingAddress_request.h \
    $${PWD}/OAIAddShippingAddress_request_logisticsInfo_inner.h \
    $${PWD}/OAIAddShippingAddress_request_selectedAddresses_inner.h \
    $${PWD}/OAICartSimulation_200_response.h \
    $${PWD}/OAICartSimulation_200_response_items_inner.h \
    $${PWD}/OAICartSimulation_200_response_items_inner_priceTags_inner.h \
    $${PWD}/OAICartSimulation_200_response_logisticsInfo_inner.h \
    $${PWD}/OAICartSimulation_200_response_logisticsInfo_inner_itemMetadata.h \
    $${PWD}/OAICartSimulation_200_response_logisticsInfo_inner_itemMetadata_items_inner.h \
    $${PWD}/OAICartSimulation_200_response_logisticsInfo_inner_purchaseConditions.h \
    $${PWD}/OAICartSimulation_200_response_logisticsInfo_inner_purchaseConditions_itemPurchaseConditions_inner.h \
    $${PWD}/OAICartSimulation_200_response_logisticsInfo_inner_purchaseConditions_itemPurchaseConditions_inner_slas_inner.h \
    $${PWD}/OAICartSimulation_200_response_logisticsInfo_inner_purchaseConditions_itemPurchaseConditions_inner_slas_inner_availableDeliveryWindows.h \
    $${PWD}/OAICartSimulation_200_response_logisticsInfo_inner_purchaseConditions_itemPurchaseConditions_inner_slas_inner_deliveryWindow.h \
    $${PWD}/OAICartSimulation_200_response_logisticsInfo_inner_purchaseConditions_itemPurchaseConditions_inner_slas_inner_pickupStoreInfo.h \
    $${PWD}/OAICartSimulation_200_response_logisticsInfo_inner_totals_inner.h \
    $${PWD}/OAICartSimulation_200_response_paymentData.h \
    $${PWD}/OAICartSimulation_200_response_paymentData_paymentSystems_inner.h \
    $${PWD}/OAICartSimulation_200_response_ratesAndBenefitsData.h \
    $${PWD}/OAICartSimulation_request.h \
    $${PWD}/OAICartSimulation_request_items_inner.h \
    $${PWD}/OAIClearorderFormMessages_200_response.h \
    $${PWD}/OAIClearorderFormMessages_200_response_marketingData.h \
    $${PWD}/OAIGetClientProfileByEmail_200_response.h \
    $${PWD}/OAIGetClientProfileByEmail_200_response_userProfile.h \
    $${PWD}/OAIGetSellersByRegion_200_response.h \
    $${PWD}/OAIIgnoreProfileData_request.h \
    $${PWD}/OAIItem.h \
    $${PWD}/OAIItemsUpdate_200_response.h \
    $${PWD}/OAIItemsUpdate_200_response_availableAddresses_inner.h \
    $${PWD}/OAIItemsUpdate_200_response_itemsOrdination.h \
    $${PWD}/OAIItemsUpdate_200_response_shippingData.h \
    $${PWD}/OAIItemsUpdate_200_response_shippingData_address.h \
    $${PWD}/OAIItemsUpdate_200_response_shippingData_availableAddresses_inner.h \
    $${PWD}/OAIItemsUpdate_200_response_shippingData_logisticsInfo_inner.h \
    $${PWD}/OAIItemsUpdate_200_response_shippingData_logisticsInfo_inner_slas_inner.h \
    $${PWD}/OAIItemsUpdate_200_response_shippingData_logisticsInfo_inner_slas_inner_pickupStoreInfo.h \
    $${PWD}/OAIItemsUpdate_200_response_shippingData_logisticsInfo_inner_slas_inner_pickupStoreInfo_address.h \
    $${PWD}/OAIItemsUpdate_request.h \
    $${PWD}/OAIItemsUpdate_request_orderItems_inner.h \
    $${PWD}/OAIItems_200_response.h \
    $${PWD}/OAIItems_200_response_clientPreferencesData.h \
    $${PWD}/OAIItems_200_response_items_inner.h \
    $${PWD}/OAIItems_200_response_marketingData.h \
    $${PWD}/OAIItems_request.h \
    $${PWD}/OAIItems_request_orderItems_inner.h \
    $${PWD}/OAIOrderFormSimulationRequest.h \
    $${PWD}/OAIPaymentConfiguration.h \
    $${PWD}/OAIPlaceOrderFromExistingOrderForm_request.h \
    $${PWD}/OAIPlaceOrder_200_response.h \
    $${PWD}/OAIPlaceOrder_200_response_orders_inner.h \
    $${PWD}/OAIPlaceOrder_200_response_orders_inner_items_inner.h \
    $${PWD}/OAIPlaceOrder_200_response_transactionData.h \
    $${PWD}/OAIPlaceOrder_200_response_transactionData_merchantTransactions_inner.h \
    $${PWD}/OAIPlaceOrder_200_response_transactionData_merchantTransactions_inner_payments_inner.h \
    $${PWD}/OAIPlaceOrder_request.h \
    $${PWD}/OAIPlaceOrder_request_clientProfileData.h \
    $${PWD}/OAIPlaceOrder_request_items_inner.h \
    $${PWD}/OAIPlaceOrder_request_items_inner_bundleItems_inner.h \
    $${PWD}/OAIPlaceOrder_request_items_inner_itemAttachment.h \
    $${PWD}/OAIPlaceOrder_request_items_inner_priceTags_inner.h \
    $${PWD}/OAIPlaceOrder_request_marketingData.h \
    $${PWD}/OAIPlaceOrder_request_paymentData.h \
    $${PWD}/OAIPlaceOrder_request_paymentData_giftCards_inner.h \
    $${PWD}/OAIPlaceOrder_request_paymentData_paymentSystems_inner.h \
    $${PWD}/OAIPlaceOrder_request_paymentData_paymentSystems_inner_validator.h \
    $${PWD}/OAIPlaceOrder_request_paymentData_payments_inner.h \
    $${PWD}/OAIPlaceOrder_request_shippingData.h \
    $${PWD}/OAIPlaceOrder_request_shippingData_address.h \
    $${PWD}/OAIPlaceOrder_request_shippingData_logisticsInfo_inner.h \
    $${PWD}/OAIPlaceOrder_request_shippingData_logisticsInfo_inner_deliveryWindow.h \
    $${PWD}/OAIPriceChangeRequest.h \
    $${PWD}/OAIProcessOrder_500_response.h \
    $${PWD}/OAIProcessOrder_500_response_error.h \
    $${PWD}/OAISetsinglecustomfieldvalueRequest.h \
    $${PWD}/OAIUpdateorderFormconfigurationRequest.h \
    $${PWD}/OAIUpdateorderFormconfigurationRequest_apps_inner.h \
    $${PWD}/OAIUpdateorderFormconfigurationRequest_taxConfiguration.h \
    $${PWD}/OAIWaitingTime.h \
# APIs
    $${PWD}/OAICartAttachmentsApi.h \
    $${PWD}/OAIConfigurationApi.h \
    $${PWD}/OAICustomDataApi.h \
    $${PWD}/OAIFulfillmentApi.h \
    $${PWD}/OAIOrderPlacementApi.h \
    $${PWD}/OAIRegionApi.h \
    $${PWD}/OAIShoppingCartApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAddClientPreferences_request.cpp \
    $${PWD}/OAIAddClientProfile_request.cpp \
    $${PWD}/OAIAddCoupons_200_response.cpp \
    $${PWD}/OAIAddCoupons_200_response_availableAddresses_inner.cpp \
    $${PWD}/OAIAddCoupons_200_response_clientPreferencesData.cpp \
    $${PWD}/OAIAddCoupons_200_response_clientProfileData.cpp \
    $${PWD}/OAIAddCoupons_200_response_itemMetadata.cpp \
    $${PWD}/OAIAddCoupons_200_response_itemMetadata_items_inner.cpp \
    $${PWD}/OAIAddCoupons_200_response_itemsOrdination.cpp \
    $${PWD}/OAIAddCoupons_200_response_items_inner.cpp \
    $${PWD}/OAIAddCoupons_200_response_items_inner_additionalInfo.cpp \
    $${PWD}/OAIAddCoupons_200_response_items_inner_bundleItems_inner.cpp \
    $${PWD}/OAIAddCoupons_200_response_items_inner_priceDefinition.cpp \
    $${PWD}/OAIAddCoupons_200_response_items_inner_priceDefinition_sellingPrices_inner.cpp \
    $${PWD}/OAIAddCoupons_200_response_items_inner_priceTags_inner.cpp \
    $${PWD}/OAIAddCoupons_200_response_items_inner_productCategories.cpp \
    $${PWD}/OAIAddCoupons_200_response_marketingData.cpp \
    $${PWD}/OAIAddCoupons_200_response_paymentData.cpp \
    $${PWD}/OAIAddCoupons_200_response_paymentData_giftCards_inner.cpp \
    $${PWD}/OAIAddCoupons_200_response_paymentData_transactions_inner.cpp \
    $${PWD}/OAIAddCoupons_200_response_paymentData_transactions_inner_payments_inner.cpp \
    $${PWD}/OAIAddCoupons_200_response_ratesAndBenefitsData.cpp \
    $${PWD}/OAIAddCoupons_200_response_sellers_inner.cpp \
    $${PWD}/OAIAddCoupons_200_response_shippingData.cpp \
    $${PWD}/OAIAddCoupons_200_response_shippingData_address.cpp \
    $${PWD}/OAIAddCoupons_200_response_shippingData_availableAddresses_inner.cpp \
    $${PWD}/OAIAddCoupons_200_response_shippingData_logisticsInfo_inner.cpp \
    $${PWD}/OAIAddCoupons_200_response_shippingData_logisticsInfo_inner_deliveryChannels_inner.cpp \
    $${PWD}/OAIAddCoupons_200_response_shippingData_logisticsInfo_inner_slas_inner.cpp \
    $${PWD}/OAIAddCoupons_200_response_shippingData_logisticsInfo_inner_slas_inner_deliveryIds_inner.cpp \
    $${PWD}/OAIAddCoupons_200_response_shippingData_logisticsInfo_inner_slas_inner_pickupStoreInfo.cpp \
    $${PWD}/OAIAddCoupons_200_response_shippingData_logisticsInfo_inner_slas_inner_pickupStoreInfo_address.cpp \
    $${PWD}/OAIAddCoupons_request.cpp \
    $${PWD}/OAIAddMarketingData_request.cpp \
    $${PWD}/OAIAddMerchantContextData_200_response.cpp \
    $${PWD}/OAIAddMerchantContextData_request.cpp \
    $${PWD}/OAIAddMerchantContextData_request_salesAssociateData.cpp \
    $${PWD}/OAIAddPaymentData_request.cpp \
    $${PWD}/OAIAddPaymentData_request_payments_inner.cpp \
    $${PWD}/OAIAddShippingAddress_request.cpp \
    $${PWD}/OAIAddShippingAddress_request_logisticsInfo_inner.cpp \
    $${PWD}/OAIAddShippingAddress_request_selectedAddresses_inner.cpp \
    $${PWD}/OAICartSimulation_200_response.cpp \
    $${PWD}/OAICartSimulation_200_response_items_inner.cpp \
    $${PWD}/OAICartSimulation_200_response_items_inner_priceTags_inner.cpp \
    $${PWD}/OAICartSimulation_200_response_logisticsInfo_inner.cpp \
    $${PWD}/OAICartSimulation_200_response_logisticsInfo_inner_itemMetadata.cpp \
    $${PWD}/OAICartSimulation_200_response_logisticsInfo_inner_itemMetadata_items_inner.cpp \
    $${PWD}/OAICartSimulation_200_response_logisticsInfo_inner_purchaseConditions.cpp \
    $${PWD}/OAICartSimulation_200_response_logisticsInfo_inner_purchaseConditions_itemPurchaseConditions_inner.cpp \
    $${PWD}/OAICartSimulation_200_response_logisticsInfo_inner_purchaseConditions_itemPurchaseConditions_inner_slas_inner.cpp \
    $${PWD}/OAICartSimulation_200_response_logisticsInfo_inner_purchaseConditions_itemPurchaseConditions_inner_slas_inner_availableDeliveryWindows.cpp \
    $${PWD}/OAICartSimulation_200_response_logisticsInfo_inner_purchaseConditions_itemPurchaseConditions_inner_slas_inner_deliveryWindow.cpp \
    $${PWD}/OAICartSimulation_200_response_logisticsInfo_inner_purchaseConditions_itemPurchaseConditions_inner_slas_inner_pickupStoreInfo.cpp \
    $${PWD}/OAICartSimulation_200_response_logisticsInfo_inner_totals_inner.cpp \
    $${PWD}/OAICartSimulation_200_response_paymentData.cpp \
    $${PWD}/OAICartSimulation_200_response_paymentData_paymentSystems_inner.cpp \
    $${PWD}/OAICartSimulation_200_response_ratesAndBenefitsData.cpp \
    $${PWD}/OAICartSimulation_request.cpp \
    $${PWD}/OAICartSimulation_request_items_inner.cpp \
    $${PWD}/OAIClearorderFormMessages_200_response.cpp \
    $${PWD}/OAIClearorderFormMessages_200_response_marketingData.cpp \
    $${PWD}/OAIGetClientProfileByEmail_200_response.cpp \
    $${PWD}/OAIGetClientProfileByEmail_200_response_userProfile.cpp \
    $${PWD}/OAIGetSellersByRegion_200_response.cpp \
    $${PWD}/OAIIgnoreProfileData_request.cpp \
    $${PWD}/OAIItem.cpp \
    $${PWD}/OAIItemsUpdate_200_response.cpp \
    $${PWD}/OAIItemsUpdate_200_response_availableAddresses_inner.cpp \
    $${PWD}/OAIItemsUpdate_200_response_itemsOrdination.cpp \
    $${PWD}/OAIItemsUpdate_200_response_shippingData.cpp \
    $${PWD}/OAIItemsUpdate_200_response_shippingData_address.cpp \
    $${PWD}/OAIItemsUpdate_200_response_shippingData_availableAddresses_inner.cpp \
    $${PWD}/OAIItemsUpdate_200_response_shippingData_logisticsInfo_inner.cpp \
    $${PWD}/OAIItemsUpdate_200_response_shippingData_logisticsInfo_inner_slas_inner.cpp \
    $${PWD}/OAIItemsUpdate_200_response_shippingData_logisticsInfo_inner_slas_inner_pickupStoreInfo.cpp \
    $${PWD}/OAIItemsUpdate_200_response_shippingData_logisticsInfo_inner_slas_inner_pickupStoreInfo_address.cpp \
    $${PWD}/OAIItemsUpdate_request.cpp \
    $${PWD}/OAIItemsUpdate_request_orderItems_inner.cpp \
    $${PWD}/OAIItems_200_response.cpp \
    $${PWD}/OAIItems_200_response_clientPreferencesData.cpp \
    $${PWD}/OAIItems_200_response_items_inner.cpp \
    $${PWD}/OAIItems_200_response_marketingData.cpp \
    $${PWD}/OAIItems_request.cpp \
    $${PWD}/OAIItems_request_orderItems_inner.cpp \
    $${PWD}/OAIOrderFormSimulationRequest.cpp \
    $${PWD}/OAIPaymentConfiguration.cpp \
    $${PWD}/OAIPlaceOrderFromExistingOrderForm_request.cpp \
    $${PWD}/OAIPlaceOrder_200_response.cpp \
    $${PWD}/OAIPlaceOrder_200_response_orders_inner.cpp \
    $${PWD}/OAIPlaceOrder_200_response_orders_inner_items_inner.cpp \
    $${PWD}/OAIPlaceOrder_200_response_transactionData.cpp \
    $${PWD}/OAIPlaceOrder_200_response_transactionData_merchantTransactions_inner.cpp \
    $${PWD}/OAIPlaceOrder_200_response_transactionData_merchantTransactions_inner_payments_inner.cpp \
    $${PWD}/OAIPlaceOrder_request.cpp \
    $${PWD}/OAIPlaceOrder_request_clientProfileData.cpp \
    $${PWD}/OAIPlaceOrder_request_items_inner.cpp \
    $${PWD}/OAIPlaceOrder_request_items_inner_bundleItems_inner.cpp \
    $${PWD}/OAIPlaceOrder_request_items_inner_itemAttachment.cpp \
    $${PWD}/OAIPlaceOrder_request_items_inner_priceTags_inner.cpp \
    $${PWD}/OAIPlaceOrder_request_marketingData.cpp \
    $${PWD}/OAIPlaceOrder_request_paymentData.cpp \
    $${PWD}/OAIPlaceOrder_request_paymentData_giftCards_inner.cpp \
    $${PWD}/OAIPlaceOrder_request_paymentData_paymentSystems_inner.cpp \
    $${PWD}/OAIPlaceOrder_request_paymentData_paymentSystems_inner_validator.cpp \
    $${PWD}/OAIPlaceOrder_request_paymentData_payments_inner.cpp \
    $${PWD}/OAIPlaceOrder_request_shippingData.cpp \
    $${PWD}/OAIPlaceOrder_request_shippingData_address.cpp \
    $${PWD}/OAIPlaceOrder_request_shippingData_logisticsInfo_inner.cpp \
    $${PWD}/OAIPlaceOrder_request_shippingData_logisticsInfo_inner_deliveryWindow.cpp \
    $${PWD}/OAIPriceChangeRequest.cpp \
    $${PWD}/OAIProcessOrder_500_response.cpp \
    $${PWD}/OAIProcessOrder_500_response_error.cpp \
    $${PWD}/OAISetsinglecustomfieldvalueRequest.cpp \
    $${PWD}/OAIUpdateorderFormconfigurationRequest.cpp \
    $${PWD}/OAIUpdateorderFormconfigurationRequest_apps_inner.cpp \
    $${PWD}/OAIUpdateorderFormconfigurationRequest_taxConfiguration.cpp \
    $${PWD}/OAIWaitingTime.cpp \
# APIs
    $${PWD}/OAICartAttachmentsApi.cpp \
    $${PWD}/OAIConfigurationApi.cpp \
    $${PWD}/OAICustomDataApi.cpp \
    $${PWD}/OAIFulfillmentApi.cpp \
    $${PWD}/OAIOrderPlacementApi.cpp \
    $${PWD}/OAIRegionApi.cpp \
    $${PWD}/OAIShoppingCartApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
