QT += network

HEADERS += \
# Models
    $${PWD}/OAIDeviceProperties.h \
    $${PWD}/OAIGetVpnSitesConfigurationRequest.h \
    $${PWD}/OAIHubVirtualNetworkConnection.h \
    $${PWD}/OAIHubVirtualNetworkConnectionProperties.h \
    $${PWD}/OAIHubVirtualNetworkConnectionProperties_remoteVirtualNetwork.h \
    $${PWD}/OAIHubVirtualNetworkConnectionStatus.h \
    $${PWD}/OAIListHubVirtualNetworkConnectionsResult.h \
    $${PWD}/OAIListP2SVpnGatewaysResult.h \
    $${PWD}/OAIListP2SVpnServerConfigurationsResult.h \
    $${PWD}/OAIListVirtualHubsResult.h \
    $${PWD}/OAIListVirtualWANsResult.h \
    $${PWD}/OAIListVpnConnectionsResult.h \
    $${PWD}/OAIListVpnGatewaysResult.h \
    $${PWD}/OAIListVpnSiteLinkConnectionsResult.h \
    $${PWD}/OAIListVpnSiteLinksResult.h \
    $${PWD}/OAIListVpnSitesResult.h \
    $${PWD}/OAIOfficeTrafficCategory.h \
    $${PWD}/OAIP2SVpnGateway.h \
    $${PWD}/OAIP2SVpnGatewayProperties.h \
    $${PWD}/OAIP2SVpnGatewayProperties_customRoutes.h \
    $${PWD}/OAIP2SVpnProfileParameters.h \
    $${PWD}/OAIP2SVpnServerConfigRadiusClientRootCertificate.h \
    $${PWD}/OAIP2SVpnServerConfigRadiusClientRootCertificatePropertiesFormat.h \
    $${PWD}/OAIP2SVpnServerConfigRadiusServerRootCertificate.h \
    $${PWD}/OAIP2SVpnServerConfigRadiusServerRootCertificatePropertiesFormat.h \
    $${PWD}/OAIP2SVpnServerConfigVpnClientRevokedCertificate.h \
    $${PWD}/OAIP2SVpnServerConfigVpnClientRevokedCertificatePropertiesFormat.h \
    $${PWD}/OAIP2SVpnServerConfigVpnClientRootCertificate.h \
    $${PWD}/OAIP2SVpnServerConfigVpnClientRootCertificatePropertiesFormat.h \
    $${PWD}/OAIP2SVpnServerConfiguration.h \
    $${PWD}/OAIP2SVpnServerConfigurationProperties.h \
    $${PWD}/OAIP2SVpnServerConfigurationProperties_vpnClientIpsecPolicies_inner.h \
    $${PWD}/OAIP2sVpnGateways_List_default_response.h \
    $${PWD}/OAIP2sVpnGateways_List_default_response_details_inner.h \
    $${PWD}/OAIP2sVpnGateways_UpdateTags_request.h \
    $${PWD}/OAITunnelConnectionStatus.h \
    $${PWD}/OAIVirtualHub.h \
    $${PWD}/OAIVirtualHubProperties.h \
    $${PWD}/OAIVirtualHubRoute.h \
    $${PWD}/OAIVirtualHubRouteTable.h \
    $${PWD}/OAIVirtualWAN.h \
    $${PWD}/OAIVirtualWanProperties.h \
    $${PWD}/OAIVirtualWanSecurityProvider.h \
    $${PWD}/OAIVirtualWanSecurityProviderType.h \
    $${PWD}/OAIVirtualWanSecurityProviders.h \
    $${PWD}/OAIVpnClientConnectionHealth.h \
    $${PWD}/OAIVpnConnection.h \
    $${PWD}/OAIVpnConnectionProperties.h \
    $${PWD}/OAIVpnConnectionStatus.h \
    $${PWD}/OAIVpnGateway.h \
    $${PWD}/OAIVpnGatewayProperties.h \
    $${PWD}/OAIVpnGatewayProperties_bgpSettings.h \
    $${PWD}/OAIVpnLinkBgpSettings.h \
    $${PWD}/OAIVpnLinkProviderProperties.h \
    $${PWD}/OAIVpnProfileResponse.h \
    $${PWD}/OAIVpnSite.h \
    $${PWD}/OAIVpnSiteId.h \
    $${PWD}/OAIVpnSiteLink.h \
    $${PWD}/OAIVpnSiteLinkConnection.h \
    $${PWD}/OAIVpnSiteLinkConnectionProperties.h \
    $${PWD}/OAIVpnSiteLinkProperties.h \
    $${PWD}/OAIVpnSiteProperties.h \
# APIs
    $${PWD}/OAIDefaultApi.h \
    $${PWD}/OAIP2SVpnGatewaysApi.h \
    $${PWD}/OAIVirtualWANsApi.h \
    $${PWD}/OAIVpnGatewaysApi.h \
    $${PWD}/OAIVpnSitesApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIDeviceProperties.cpp \
    $${PWD}/OAIGetVpnSitesConfigurationRequest.cpp \
    $${PWD}/OAIHubVirtualNetworkConnection.cpp \
    $${PWD}/OAIHubVirtualNetworkConnectionProperties.cpp \
    $${PWD}/OAIHubVirtualNetworkConnectionProperties_remoteVirtualNetwork.cpp \
    $${PWD}/OAIHubVirtualNetworkConnectionStatus.cpp \
    $${PWD}/OAIListHubVirtualNetworkConnectionsResult.cpp \
    $${PWD}/OAIListP2SVpnGatewaysResult.cpp \
    $${PWD}/OAIListP2SVpnServerConfigurationsResult.cpp \
    $${PWD}/OAIListVirtualHubsResult.cpp \
    $${PWD}/OAIListVirtualWANsResult.cpp \
    $${PWD}/OAIListVpnConnectionsResult.cpp \
    $${PWD}/OAIListVpnGatewaysResult.cpp \
    $${PWD}/OAIListVpnSiteLinkConnectionsResult.cpp \
    $${PWD}/OAIListVpnSiteLinksResult.cpp \
    $${PWD}/OAIListVpnSitesResult.cpp \
    $${PWD}/OAIOfficeTrafficCategory.cpp \
    $${PWD}/OAIP2SVpnGateway.cpp \
    $${PWD}/OAIP2SVpnGatewayProperties.cpp \
    $${PWD}/OAIP2SVpnGatewayProperties_customRoutes.cpp \
    $${PWD}/OAIP2SVpnProfileParameters.cpp \
    $${PWD}/OAIP2SVpnServerConfigRadiusClientRootCertificate.cpp \
    $${PWD}/OAIP2SVpnServerConfigRadiusClientRootCertificatePropertiesFormat.cpp \
    $${PWD}/OAIP2SVpnServerConfigRadiusServerRootCertificate.cpp \
    $${PWD}/OAIP2SVpnServerConfigRadiusServerRootCertificatePropertiesFormat.cpp \
    $${PWD}/OAIP2SVpnServerConfigVpnClientRevokedCertificate.cpp \
    $${PWD}/OAIP2SVpnServerConfigVpnClientRevokedCertificatePropertiesFormat.cpp \
    $${PWD}/OAIP2SVpnServerConfigVpnClientRootCertificate.cpp \
    $${PWD}/OAIP2SVpnServerConfigVpnClientRootCertificatePropertiesFormat.cpp \
    $${PWD}/OAIP2SVpnServerConfiguration.cpp \
    $${PWD}/OAIP2SVpnServerConfigurationProperties.cpp \
    $${PWD}/OAIP2SVpnServerConfigurationProperties_vpnClientIpsecPolicies_inner.cpp \
    $${PWD}/OAIP2sVpnGateways_List_default_response.cpp \
    $${PWD}/OAIP2sVpnGateways_List_default_response_details_inner.cpp \
    $${PWD}/OAIP2sVpnGateways_UpdateTags_request.cpp \
    $${PWD}/OAITunnelConnectionStatus.cpp \
    $${PWD}/OAIVirtualHub.cpp \
    $${PWD}/OAIVirtualHubProperties.cpp \
    $${PWD}/OAIVirtualHubRoute.cpp \
    $${PWD}/OAIVirtualHubRouteTable.cpp \
    $${PWD}/OAIVirtualWAN.cpp \
    $${PWD}/OAIVirtualWanProperties.cpp \
    $${PWD}/OAIVirtualWanSecurityProvider.cpp \
    $${PWD}/OAIVirtualWanSecurityProviderType.cpp \
    $${PWD}/OAIVirtualWanSecurityProviders.cpp \
    $${PWD}/OAIVpnClientConnectionHealth.cpp \
    $${PWD}/OAIVpnConnection.cpp \
    $${PWD}/OAIVpnConnectionProperties.cpp \
    $${PWD}/OAIVpnConnectionStatus.cpp \
    $${PWD}/OAIVpnGateway.cpp \
    $${PWD}/OAIVpnGatewayProperties.cpp \
    $${PWD}/OAIVpnGatewayProperties_bgpSettings.cpp \
    $${PWD}/OAIVpnLinkBgpSettings.cpp \
    $${PWD}/OAIVpnLinkProviderProperties.cpp \
    $${PWD}/OAIVpnProfileResponse.cpp \
    $${PWD}/OAIVpnSite.cpp \
    $${PWD}/OAIVpnSiteId.cpp \
    $${PWD}/OAIVpnSiteLink.cpp \
    $${PWD}/OAIVpnSiteLinkConnection.cpp \
    $${PWD}/OAIVpnSiteLinkConnectionProperties.cpp \
    $${PWD}/OAIVpnSiteLinkProperties.cpp \
    $${PWD}/OAIVpnSiteProperties.cpp \
# APIs
    $${PWD}/OAIDefaultApi.cpp \
    $${PWD}/OAIP2SVpnGatewaysApi.cpp \
    $${PWD}/OAIVirtualWANsApi.cpp \
    $${PWD}/OAIVpnGatewaysApi.cpp \
    $${PWD}/OAIVpnSitesApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
