QT += network

HEADERS += \
# Models
    $${PWD}/OAIAgentUpdateStatus.h \
    $${PWD}/OAIApplicationProtocol.h \
    $${PWD}/OAIAssignPublicIp.h \
    $${PWD}/OAIAttachment.h \
    $${PWD}/OAIAttachmentStateChange.h \
    $${PWD}/OAIAttribute.h \
    $${PWD}/OAIAutoScalingGroupProvider.h \
    $${PWD}/OAIAutoScalingGroupProviderUpdate.h \
    $${PWD}/OAIAutoScalingGroupProviderUpdate_managedScaling.h \
    $${PWD}/OAIAutoScalingGroupProvider_managedScaling.h \
    $${PWD}/OAIAwsVpcConfiguration.h \
    $${PWD}/OAICPUArchitecture.h \
    $${PWD}/OAICapacityProvider.h \
    $${PWD}/OAICapacityProviderField.h \
    $${PWD}/OAICapacityProviderStatus.h \
    $${PWD}/OAICapacityProviderStrategyItem.h \
    $${PWD}/OAICapacityProviderUpdateStatus.h \
    $${PWD}/OAICapacityProvider_autoScalingGroupProvider.h \
    $${PWD}/OAICluster.h \
    $${PWD}/OAIClusterConfiguration.h \
    $${PWD}/OAIClusterConfiguration_executeCommandConfiguration.h \
    $${PWD}/OAIClusterField.h \
    $${PWD}/OAIClusterServiceConnectDefaults.h \
    $${PWD}/OAIClusterServiceConnectDefaultsRequest.h \
    $${PWD}/OAIClusterSetting.h \
    $${PWD}/OAIClusterSettingName.h \
    $${PWD}/OAICluster_serviceConnectDefaults.h \
    $${PWD}/OAICompatibility.h \
    $${PWD}/OAIConnectivity.h \
    $${PWD}/OAIContainer.h \
    $${PWD}/OAIContainerCondition.h \
    $${PWD}/OAIContainerDefinition.h \
    $${PWD}/OAIContainerDefinition_firelensConfiguration.h \
    $${PWD}/OAIContainerDefinition_healthCheck.h \
    $${PWD}/OAIContainerDefinition_linuxParameters.h \
    $${PWD}/OAIContainerDefinition_logConfiguration.h \
    $${PWD}/OAIContainerDefinition_repositoryCredentials.h \
    $${PWD}/OAIContainerDependency.h \
    $${PWD}/OAIContainerInstance.h \
    $${PWD}/OAIContainerInstanceField.h \
    $${PWD}/OAIContainerInstanceHealthStatus.h \
    $${PWD}/OAIContainerInstanceStatus.h \
    $${PWD}/OAIContainerInstance_healthStatus.h \
    $${PWD}/OAIContainerInstance_versionInfo.h \
    $${PWD}/OAIContainerOverride.h \
    $${PWD}/OAIContainerStateChange.h \
    $${PWD}/OAICreateCapacityProviderRequest.h \
    $${PWD}/OAICreateCapacityProviderRequest_autoScalingGroupProvider.h \
    $${PWD}/OAICreateCapacityProviderResponse.h \
    $${PWD}/OAICreateCapacityProviderResponse_capacityProvider.h \
    $${PWD}/OAICreateClusterRequest.h \
    $${PWD}/OAICreateClusterRequest_configuration.h \
    $${PWD}/OAICreateClusterRequest_serviceConnectDefaults.h \
    $${PWD}/OAICreateClusterResponse.h \
    $${PWD}/OAICreateClusterResponse_cluster.h \
    $${PWD}/OAICreateServiceRequest.h \
    $${PWD}/OAICreateServiceRequest_deploymentConfiguration.h \
    $${PWD}/OAICreateServiceRequest_deploymentController.h \
    $${PWD}/OAICreateServiceRequest_networkConfiguration.h \
    $${PWD}/OAICreateServiceRequest_serviceConnectConfiguration.h \
    $${PWD}/OAICreateServiceResponse.h \
    $${PWD}/OAICreateServiceResponse_service.h \
    $${PWD}/OAICreateTaskSetRequest.h \
    $${PWD}/OAICreateTaskSetRequest_networkConfiguration.h \
    $${PWD}/OAICreateTaskSetRequest_scale.h \
    $${PWD}/OAICreateTaskSetResponse.h \
    $${PWD}/OAICreateTaskSetResponse_taskSet.h \
    $${PWD}/OAIDeleteAccountSettingRequest.h \
    $${PWD}/OAIDeleteAccountSettingResponse.h \
    $${PWD}/OAIDeleteAccountSettingResponse_setting.h \
    $${PWD}/OAIDeleteAttributesRequest.h \
    $${PWD}/OAIDeleteAttributesResponse.h \
    $${PWD}/OAIDeleteCapacityProviderRequest.h \
    $${PWD}/OAIDeleteCapacityProviderResponse.h \
    $${PWD}/OAIDeleteCapacityProviderResponse_capacityProvider.h \
    $${PWD}/OAIDeleteClusterRequest.h \
    $${PWD}/OAIDeleteClusterResponse.h \
    $${PWD}/OAIDeleteClusterResponse_cluster.h \
    $${PWD}/OAIDeleteServiceRequest.h \
    $${PWD}/OAIDeleteServiceResponse.h \
    $${PWD}/OAIDeleteServiceResponse_service.h \
    $${PWD}/OAIDeleteTaskDefinitionsRequest.h \
    $${PWD}/OAIDeleteTaskDefinitionsResponse.h \
    $${PWD}/OAIDeleteTaskSetRequest.h \
    $${PWD}/OAIDeleteTaskSetResponse.h \
    $${PWD}/OAIDeleteTaskSetResponse_taskSet.h \
    $${PWD}/OAIDeployment.h \
    $${PWD}/OAIDeploymentAlarms.h \
    $${PWD}/OAIDeploymentCircuitBreaker.h \
    $${PWD}/OAIDeploymentConfiguration.h \
    $${PWD}/OAIDeploymentConfiguration_alarms.h \
    $${PWD}/OAIDeploymentConfiguration_deploymentCircuitBreaker.h \
    $${PWD}/OAIDeploymentController.h \
    $${PWD}/OAIDeploymentControllerType.h \
    $${PWD}/OAIDeploymentRolloutState.h \
    $${PWD}/OAIDeployment_serviceConnectConfiguration.h \
    $${PWD}/OAIDeregisterContainerInstanceRequest.h \
    $${PWD}/OAIDeregisterContainerInstanceResponse.h \
    $${PWD}/OAIDeregisterContainerInstanceResponse_containerInstance.h \
    $${PWD}/OAIDeregisterTaskDefinitionRequest.h \
    $${PWD}/OAIDeregisterTaskDefinitionResponse.h \
    $${PWD}/OAIDeregisterTaskDefinitionResponse_taskDefinition.h \
    $${PWD}/OAIDescribeCapacityProvidersRequest.h \
    $${PWD}/OAIDescribeCapacityProvidersResponse.h \
    $${PWD}/OAIDescribeClustersRequest.h \
    $${PWD}/OAIDescribeClustersResponse.h \
    $${PWD}/OAIDescribeContainerInstancesRequest.h \
    $${PWD}/OAIDescribeContainerInstancesResponse.h \
    $${PWD}/OAIDescribeServicesRequest.h \
    $${PWD}/OAIDescribeServicesResponse.h \
    $${PWD}/OAIDescribeTaskDefinitionRequest.h \
    $${PWD}/OAIDescribeTaskDefinitionResponse.h \
    $${PWD}/OAIDescribeTaskDefinitionResponse_taskDefinition.h \
    $${PWD}/OAIDescribeTaskSetsRequest.h \
    $${PWD}/OAIDescribeTaskSetsResponse.h \
    $${PWD}/OAIDescribeTasksRequest.h \
    $${PWD}/OAIDescribeTasksResponse.h \
    $${PWD}/OAIDesiredStatus.h \
    $${PWD}/OAIDevice.h \
    $${PWD}/OAIDeviceCgroupPermission.h \
    $${PWD}/OAIDiscoverPollEndpointRequest.h \
    $${PWD}/OAIDiscoverPollEndpointResponse.h \
    $${PWD}/OAIDockerVolumeConfiguration.h \
    $${PWD}/OAIEFSAuthorizationConfig.h \
    $${PWD}/OAIEFSAuthorizationConfigIAM.h \
    $${PWD}/OAIEFSTransitEncryption.h \
    $${PWD}/OAIEFSVolumeConfiguration.h \
    $${PWD}/OAIEFSVolumeConfiguration_authorizationConfig.h \
    $${PWD}/OAIEnvironmentFile.h \
    $${PWD}/OAIEnvironmentFileType.h \
    $${PWD}/OAIEphemeralStorage.h \
    $${PWD}/OAIExecuteCommandConfiguration.h \
    $${PWD}/OAIExecuteCommandConfiguration_logConfiguration.h \
    $${PWD}/OAIExecuteCommandLogConfiguration.h \
    $${PWD}/OAIExecuteCommandLogging.h \
    $${PWD}/OAIExecuteCommandRequest.h \
    $${PWD}/OAIExecuteCommandResponse.h \
    $${PWD}/OAIExecuteCommandResponse_session.h \
    $${PWD}/OAIFSxWindowsFileServerAuthorizationConfig.h \
    $${PWD}/OAIFSxWindowsFileServerVolumeConfiguration.h \
    $${PWD}/OAIFSxWindowsFileServerVolumeConfiguration_authorizationConfig.h \
    $${PWD}/OAIFailure.h \
    $${PWD}/OAIFirelensConfiguration.h \
    $${PWD}/OAIFirelensConfigurationType.h \
    $${PWD}/OAIGetTaskProtectionRequest.h \
    $${PWD}/OAIGetTaskProtectionResponse.h \
    $${PWD}/OAIHealthCheck.h \
    $${PWD}/OAIHealthStatus.h \
    $${PWD}/OAIHostEntry.h \
    $${PWD}/OAIHostVolumeProperties.h \
    $${PWD}/OAIInferenceAccelerator.h \
    $${PWD}/OAIInferenceAcceleratorOverride.h \
    $${PWD}/OAIInstanceHealthCheckResult.h \
    $${PWD}/OAIInstanceHealthCheckState.h \
    $${PWD}/OAIInstanceHealthCheckType.h \
    $${PWD}/OAIIpcMode.h \
    $${PWD}/OAIKernelCapabilities.h \
    $${PWD}/OAIKeyValuePair.h \
    $${PWD}/OAILaunchType.h \
    $${PWD}/OAILinuxParameters.h \
    $${PWD}/OAILinuxParameters_capabilities.h \
    $${PWD}/OAIListAccountSettingsRequest.h \
    $${PWD}/OAIListAccountSettingsResponse.h \
    $${PWD}/OAIListAttributesRequest.h \
    $${PWD}/OAIListAttributesResponse.h \
    $${PWD}/OAIListClustersRequest.h \
    $${PWD}/OAIListClustersResponse.h \
    $${PWD}/OAIListContainerInstancesRequest.h \
    $${PWD}/OAIListContainerInstancesResponse.h \
    $${PWD}/OAIListServicesByNamespaceRequest.h \
    $${PWD}/OAIListServicesByNamespaceResponse.h \
    $${PWD}/OAIListServicesRequest.h \
    $${PWD}/OAIListServicesResponse.h \
    $${PWD}/OAIListTagsForResourceRequest.h \
    $${PWD}/OAIListTagsForResourceResponse.h \
    $${PWD}/OAIListTaskDefinitionFamiliesRequest.h \
    $${PWD}/OAIListTaskDefinitionFamiliesResponse.h \
    $${PWD}/OAIListTaskDefinitionsRequest.h \
    $${PWD}/OAIListTaskDefinitionsResponse.h \
    $${PWD}/OAIListTasksRequest.h \
    $${PWD}/OAIListTasksResponse.h \
    $${PWD}/OAILoadBalancer.h \
    $${PWD}/OAILogConfiguration.h \
    $${PWD}/OAILogDriver.h \
    $${PWD}/OAIManagedAgent.h \
    $${PWD}/OAIManagedAgentName.h \
    $${PWD}/OAIManagedAgentStateChange.h \
    $${PWD}/OAIManagedScaling.h \
    $${PWD}/OAIManagedScalingStatus.h \
    $${PWD}/OAIManagedTerminationProtection.h \
    $${PWD}/OAIMountPoint.h \
    $${PWD}/OAINetworkBinding.h \
    $${PWD}/OAINetworkConfiguration.h \
    $${PWD}/OAINetworkConfiguration_awsvpcConfiguration.h \
    $${PWD}/OAINetworkInterface.h \
    $${PWD}/OAINetworkMode.h \
    $${PWD}/OAIOSFamily.h \
    $${PWD}/OAIPidMode.h \
    $${PWD}/OAIPlacementConstraint.h \
    $${PWD}/OAIPlacementConstraintType.h \
    $${PWD}/OAIPlacementStrategy.h \
    $${PWD}/OAIPlacementStrategyType.h \
    $${PWD}/OAIPlatformDevice.h \
    $${PWD}/OAIPlatformDeviceType.h \
    $${PWD}/OAIPortMapping.h \
    $${PWD}/OAIPropagateTags.h \
    $${PWD}/OAIProtectedTask.h \
    $${PWD}/OAIProxyConfiguration.h \
    $${PWD}/OAIProxyConfigurationType.h \
    $${PWD}/OAIPutAccountSettingDefaultRequest.h \
    $${PWD}/OAIPutAccountSettingDefaultResponse.h \
    $${PWD}/OAIPutAccountSettingDefaultResponse_setting.h \
    $${PWD}/OAIPutAccountSettingRequest.h \
    $${PWD}/OAIPutAccountSettingResponse.h \
    $${PWD}/OAIPutAccountSettingResponse_setting.h \
    $${PWD}/OAIPutAttributesRequest.h \
    $${PWD}/OAIPutAttributesResponse.h \
    $${PWD}/OAIPutClusterCapacityProvidersRequest.h \
    $${PWD}/OAIPutClusterCapacityProvidersResponse.h \
    $${PWD}/OAIPutClusterCapacityProvidersResponse_cluster.h \
    $${PWD}/OAIRegisterContainerInstanceRequest.h \
    $${PWD}/OAIRegisterContainerInstanceRequest_versionInfo.h \
    $${PWD}/OAIRegisterContainerInstanceResponse.h \
    $${PWD}/OAIRegisterContainerInstanceResponse_containerInstance.h \
    $${PWD}/OAIRegisterTaskDefinitionRequest.h \
    $${PWD}/OAIRegisterTaskDefinitionRequest_ephemeralStorage.h \
    $${PWD}/OAIRegisterTaskDefinitionRequest_proxyConfiguration.h \
    $${PWD}/OAIRegisterTaskDefinitionRequest_runtimePlatform.h \
    $${PWD}/OAIRegisterTaskDefinitionResponse.h \
    $${PWD}/OAIRegisterTaskDefinitionResponse_taskDefinition.h \
    $${PWD}/OAIRepositoryCredentials.h \
    $${PWD}/OAIResource.h \
    $${PWD}/OAIResourceRequirement.h \
    $${PWD}/OAIResourceType.h \
    $${PWD}/OAIRunTaskRequest.h \
    $${PWD}/OAIRunTaskRequest_networkConfiguration.h \
    $${PWD}/OAIRunTaskRequest_overrides.h \
    $${PWD}/OAIRunTaskResponse.h \
    $${PWD}/OAIRuntimePlatform.h \
    $${PWD}/OAIScale.h \
    $${PWD}/OAIScaleUnit.h \
    $${PWD}/OAISchedulingStrategy.h \
    $${PWD}/OAIScope.h \
    $${PWD}/OAISecret.h \
    $${PWD}/OAIService.h \
    $${PWD}/OAIServiceConnectClientAlias.h \
    $${PWD}/OAIServiceConnectConfiguration.h \
    $${PWD}/OAIServiceConnectService.h \
    $${PWD}/OAIServiceConnectServiceResource.h \
    $${PWD}/OAIServiceEvent.h \
    $${PWD}/OAIServiceField.h \
    $${PWD}/OAIServiceRegistry.h \
    $${PWD}/OAIService_deploymentController.h \
    $${PWD}/OAISession.h \
    $${PWD}/OAISetting.h \
    $${PWD}/OAISettingName.h \
    $${PWD}/OAISortOrder.h \
    $${PWD}/OAIStabilityStatus.h \
    $${PWD}/OAIStartTaskRequest.h \
    $${PWD}/OAIStartTaskRequest_networkConfiguration.h \
    $${PWD}/OAIStartTaskRequest_overrides.h \
    $${PWD}/OAIStartTaskResponse.h \
    $${PWD}/OAIStopTaskRequest.h \
    $${PWD}/OAIStopTaskResponse.h \
    $${PWD}/OAIStopTaskResponse_task.h \
    $${PWD}/OAISubmitAttachmentStateChangesRequest.h \
    $${PWD}/OAISubmitAttachmentStateChangesResponse.h \
    $${PWD}/OAISubmitContainerStateChangeRequest.h \
    $${PWD}/OAISubmitContainerStateChangeResponse.h \
    $${PWD}/OAISubmitTaskStateChangeRequest.h \
    $${PWD}/OAISubmitTaskStateChangeResponse.h \
    $${PWD}/OAISystemControl.h \
    $${PWD}/OAITag.h \
    $${PWD}/OAITagResourceRequest.h \
    $${PWD}/OAITargetType.h \
    $${PWD}/OAITask.h \
    $${PWD}/OAITaskDefinition.h \
    $${PWD}/OAITaskDefinitionFamilyStatus.h \
    $${PWD}/OAITaskDefinitionField.h \
    $${PWD}/OAITaskDefinitionPlacementConstraint.h \
    $${PWD}/OAITaskDefinitionPlacementConstraintType.h \
    $${PWD}/OAITaskDefinitionStatus.h \
    $${PWD}/OAITaskDefinition_ephemeralStorage.h \
    $${PWD}/OAITaskDefinition_proxyConfiguration.h \
    $${PWD}/OAITaskDefinition_runtimePlatform.h \
    $${PWD}/OAITaskField.h \
    $${PWD}/OAITaskOverride.h \
    $${PWD}/OAITaskOverride_ephemeralStorage.h \
    $${PWD}/OAITaskSet.h \
    $${PWD}/OAITaskSetField.h \
    $${PWD}/OAITaskSet_networkConfiguration.h \
    $${PWD}/OAITaskSet_scale.h \
    $${PWD}/OAITaskStopCode.h \
    $${PWD}/OAITask_ephemeralStorage.h \
    $${PWD}/OAITask_overrides.h \
    $${PWD}/OAITmpfs.h \
    $${PWD}/OAITransportProtocol.h \
    $${PWD}/OAIUlimit.h \
    $${PWD}/OAIUlimitName.h \
    $${PWD}/OAIUntagResourceRequest.h \
    $${PWD}/OAIUpdateCapacityProviderRequest.h \
    $${PWD}/OAIUpdateCapacityProviderRequest_autoScalingGroupProvider.h \
    $${PWD}/OAIUpdateCapacityProviderResponse.h \
    $${PWD}/OAIUpdateCapacityProviderResponse_capacityProvider.h \
    $${PWD}/OAIUpdateClusterRequest.h \
    $${PWD}/OAIUpdateClusterRequest_configuration.h \
    $${PWD}/OAIUpdateClusterResponse.h \
    $${PWD}/OAIUpdateClusterSettingsRequest.h \
    $${PWD}/OAIUpdateClusterSettingsResponse.h \
    $${PWD}/OAIUpdateClusterSettingsResponse_cluster.h \
    $${PWD}/OAIUpdateContainerAgentRequest.h \
    $${PWD}/OAIUpdateContainerAgentResponse.h \
    $${PWD}/OAIUpdateContainerAgentResponse_containerInstance.h \
    $${PWD}/OAIUpdateContainerInstancesStateRequest.h \
    $${PWD}/OAIUpdateContainerInstancesStateResponse.h \
    $${PWD}/OAIUpdateServicePrimaryTaskSetRequest.h \
    $${PWD}/OAIUpdateServicePrimaryTaskSetResponse.h \
    $${PWD}/OAIUpdateServicePrimaryTaskSetResponse_taskSet.h \
    $${PWD}/OAIUpdateServiceRequest.h \
    $${PWD}/OAIUpdateServiceRequest_networkConfiguration.h \
    $${PWD}/OAIUpdateServiceResponse.h \
    $${PWD}/OAIUpdateServiceResponse_service.h \
    $${PWD}/OAIUpdateTaskProtectionRequest.h \
    $${PWD}/OAIUpdateTaskProtectionResponse.h \
    $${PWD}/OAIUpdateTaskSetRequest.h \
    $${PWD}/OAIUpdateTaskSetResponse.h \
    $${PWD}/OAIVersionInfo.h \
    $${PWD}/OAIVolume.h \
    $${PWD}/OAIVolumeFrom.h \
    $${PWD}/OAIVolume_dockerVolumeConfiguration.h \
    $${PWD}/OAIVolume_efsVolumeConfiguration.h \
    $${PWD}/OAIVolume_fsxWindowsFileServerVolumeConfiguration.h \
    $${PWD}/OAIVolume_host.h \
# APIs
    $${PWD}/OAIDefaultApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAgentUpdateStatus.cpp \
    $${PWD}/OAIApplicationProtocol.cpp \
    $${PWD}/OAIAssignPublicIp.cpp \
    $${PWD}/OAIAttachment.cpp \
    $${PWD}/OAIAttachmentStateChange.cpp \
    $${PWD}/OAIAttribute.cpp \
    $${PWD}/OAIAutoScalingGroupProvider.cpp \
    $${PWD}/OAIAutoScalingGroupProviderUpdate.cpp \
    $${PWD}/OAIAutoScalingGroupProviderUpdate_managedScaling.cpp \
    $${PWD}/OAIAutoScalingGroupProvider_managedScaling.cpp \
    $${PWD}/OAIAwsVpcConfiguration.cpp \
    $${PWD}/OAICPUArchitecture.cpp \
    $${PWD}/OAICapacityProvider.cpp \
    $${PWD}/OAICapacityProviderField.cpp \
    $${PWD}/OAICapacityProviderStatus.cpp \
    $${PWD}/OAICapacityProviderStrategyItem.cpp \
    $${PWD}/OAICapacityProviderUpdateStatus.cpp \
    $${PWD}/OAICapacityProvider_autoScalingGroupProvider.cpp \
    $${PWD}/OAICluster.cpp \
    $${PWD}/OAIClusterConfiguration.cpp \
    $${PWD}/OAIClusterConfiguration_executeCommandConfiguration.cpp \
    $${PWD}/OAIClusterField.cpp \
    $${PWD}/OAIClusterServiceConnectDefaults.cpp \
    $${PWD}/OAIClusterServiceConnectDefaultsRequest.cpp \
    $${PWD}/OAIClusterSetting.cpp \
    $${PWD}/OAIClusterSettingName.cpp \
    $${PWD}/OAICluster_serviceConnectDefaults.cpp \
    $${PWD}/OAICompatibility.cpp \
    $${PWD}/OAIConnectivity.cpp \
    $${PWD}/OAIContainer.cpp \
    $${PWD}/OAIContainerCondition.cpp \
    $${PWD}/OAIContainerDefinition.cpp \
    $${PWD}/OAIContainerDefinition_firelensConfiguration.cpp \
    $${PWD}/OAIContainerDefinition_healthCheck.cpp \
    $${PWD}/OAIContainerDefinition_linuxParameters.cpp \
    $${PWD}/OAIContainerDefinition_logConfiguration.cpp \
    $${PWD}/OAIContainerDefinition_repositoryCredentials.cpp \
    $${PWD}/OAIContainerDependency.cpp \
    $${PWD}/OAIContainerInstance.cpp \
    $${PWD}/OAIContainerInstanceField.cpp \
    $${PWD}/OAIContainerInstanceHealthStatus.cpp \
    $${PWD}/OAIContainerInstanceStatus.cpp \
    $${PWD}/OAIContainerInstance_healthStatus.cpp \
    $${PWD}/OAIContainerInstance_versionInfo.cpp \
    $${PWD}/OAIContainerOverride.cpp \
    $${PWD}/OAIContainerStateChange.cpp \
    $${PWD}/OAICreateCapacityProviderRequest.cpp \
    $${PWD}/OAICreateCapacityProviderRequest_autoScalingGroupProvider.cpp \
    $${PWD}/OAICreateCapacityProviderResponse.cpp \
    $${PWD}/OAICreateCapacityProviderResponse_capacityProvider.cpp \
    $${PWD}/OAICreateClusterRequest.cpp \
    $${PWD}/OAICreateClusterRequest_configuration.cpp \
    $${PWD}/OAICreateClusterRequest_serviceConnectDefaults.cpp \
    $${PWD}/OAICreateClusterResponse.cpp \
    $${PWD}/OAICreateClusterResponse_cluster.cpp \
    $${PWD}/OAICreateServiceRequest.cpp \
    $${PWD}/OAICreateServiceRequest_deploymentConfiguration.cpp \
    $${PWD}/OAICreateServiceRequest_deploymentController.cpp \
    $${PWD}/OAICreateServiceRequest_networkConfiguration.cpp \
    $${PWD}/OAICreateServiceRequest_serviceConnectConfiguration.cpp \
    $${PWD}/OAICreateServiceResponse.cpp \
    $${PWD}/OAICreateServiceResponse_service.cpp \
    $${PWD}/OAICreateTaskSetRequest.cpp \
    $${PWD}/OAICreateTaskSetRequest_networkConfiguration.cpp \
    $${PWD}/OAICreateTaskSetRequest_scale.cpp \
    $${PWD}/OAICreateTaskSetResponse.cpp \
    $${PWD}/OAICreateTaskSetResponse_taskSet.cpp \
    $${PWD}/OAIDeleteAccountSettingRequest.cpp \
    $${PWD}/OAIDeleteAccountSettingResponse.cpp \
    $${PWD}/OAIDeleteAccountSettingResponse_setting.cpp \
    $${PWD}/OAIDeleteAttributesRequest.cpp \
    $${PWD}/OAIDeleteAttributesResponse.cpp \
    $${PWD}/OAIDeleteCapacityProviderRequest.cpp \
    $${PWD}/OAIDeleteCapacityProviderResponse.cpp \
    $${PWD}/OAIDeleteCapacityProviderResponse_capacityProvider.cpp \
    $${PWD}/OAIDeleteClusterRequest.cpp \
    $${PWD}/OAIDeleteClusterResponse.cpp \
    $${PWD}/OAIDeleteClusterResponse_cluster.cpp \
    $${PWD}/OAIDeleteServiceRequest.cpp \
    $${PWD}/OAIDeleteServiceResponse.cpp \
    $${PWD}/OAIDeleteServiceResponse_service.cpp \
    $${PWD}/OAIDeleteTaskDefinitionsRequest.cpp \
    $${PWD}/OAIDeleteTaskDefinitionsResponse.cpp \
    $${PWD}/OAIDeleteTaskSetRequest.cpp \
    $${PWD}/OAIDeleteTaskSetResponse.cpp \
    $${PWD}/OAIDeleteTaskSetResponse_taskSet.cpp \
    $${PWD}/OAIDeployment.cpp \
    $${PWD}/OAIDeploymentAlarms.cpp \
    $${PWD}/OAIDeploymentCircuitBreaker.cpp \
    $${PWD}/OAIDeploymentConfiguration.cpp \
    $${PWD}/OAIDeploymentConfiguration_alarms.cpp \
    $${PWD}/OAIDeploymentConfiguration_deploymentCircuitBreaker.cpp \
    $${PWD}/OAIDeploymentController.cpp \
    $${PWD}/OAIDeploymentControllerType.cpp \
    $${PWD}/OAIDeploymentRolloutState.cpp \
    $${PWD}/OAIDeployment_serviceConnectConfiguration.cpp \
    $${PWD}/OAIDeregisterContainerInstanceRequest.cpp \
    $${PWD}/OAIDeregisterContainerInstanceResponse.cpp \
    $${PWD}/OAIDeregisterContainerInstanceResponse_containerInstance.cpp \
    $${PWD}/OAIDeregisterTaskDefinitionRequest.cpp \
    $${PWD}/OAIDeregisterTaskDefinitionResponse.cpp \
    $${PWD}/OAIDeregisterTaskDefinitionResponse_taskDefinition.cpp \
    $${PWD}/OAIDescribeCapacityProvidersRequest.cpp \
    $${PWD}/OAIDescribeCapacityProvidersResponse.cpp \
    $${PWD}/OAIDescribeClustersRequest.cpp \
    $${PWD}/OAIDescribeClustersResponse.cpp \
    $${PWD}/OAIDescribeContainerInstancesRequest.cpp \
    $${PWD}/OAIDescribeContainerInstancesResponse.cpp \
    $${PWD}/OAIDescribeServicesRequest.cpp \
    $${PWD}/OAIDescribeServicesResponse.cpp \
    $${PWD}/OAIDescribeTaskDefinitionRequest.cpp \
    $${PWD}/OAIDescribeTaskDefinitionResponse.cpp \
    $${PWD}/OAIDescribeTaskDefinitionResponse_taskDefinition.cpp \
    $${PWD}/OAIDescribeTaskSetsRequest.cpp \
    $${PWD}/OAIDescribeTaskSetsResponse.cpp \
    $${PWD}/OAIDescribeTasksRequest.cpp \
    $${PWD}/OAIDescribeTasksResponse.cpp \
    $${PWD}/OAIDesiredStatus.cpp \
    $${PWD}/OAIDevice.cpp \
    $${PWD}/OAIDeviceCgroupPermission.cpp \
    $${PWD}/OAIDiscoverPollEndpointRequest.cpp \
    $${PWD}/OAIDiscoverPollEndpointResponse.cpp \
    $${PWD}/OAIDockerVolumeConfiguration.cpp \
    $${PWD}/OAIEFSAuthorizationConfig.cpp \
    $${PWD}/OAIEFSAuthorizationConfigIAM.cpp \
    $${PWD}/OAIEFSTransitEncryption.cpp \
    $${PWD}/OAIEFSVolumeConfiguration.cpp \
    $${PWD}/OAIEFSVolumeConfiguration_authorizationConfig.cpp \
    $${PWD}/OAIEnvironmentFile.cpp \
    $${PWD}/OAIEnvironmentFileType.cpp \
    $${PWD}/OAIEphemeralStorage.cpp \
    $${PWD}/OAIExecuteCommandConfiguration.cpp \
    $${PWD}/OAIExecuteCommandConfiguration_logConfiguration.cpp \
    $${PWD}/OAIExecuteCommandLogConfiguration.cpp \
    $${PWD}/OAIExecuteCommandLogging.cpp \
    $${PWD}/OAIExecuteCommandRequest.cpp \
    $${PWD}/OAIExecuteCommandResponse.cpp \
    $${PWD}/OAIExecuteCommandResponse_session.cpp \
    $${PWD}/OAIFSxWindowsFileServerAuthorizationConfig.cpp \
    $${PWD}/OAIFSxWindowsFileServerVolumeConfiguration.cpp \
    $${PWD}/OAIFSxWindowsFileServerVolumeConfiguration_authorizationConfig.cpp \
    $${PWD}/OAIFailure.cpp \
    $${PWD}/OAIFirelensConfiguration.cpp \
    $${PWD}/OAIFirelensConfigurationType.cpp \
    $${PWD}/OAIGetTaskProtectionRequest.cpp \
    $${PWD}/OAIGetTaskProtectionResponse.cpp \
    $${PWD}/OAIHealthCheck.cpp \
    $${PWD}/OAIHealthStatus.cpp \
    $${PWD}/OAIHostEntry.cpp \
    $${PWD}/OAIHostVolumeProperties.cpp \
    $${PWD}/OAIInferenceAccelerator.cpp \
    $${PWD}/OAIInferenceAcceleratorOverride.cpp \
    $${PWD}/OAIInstanceHealthCheckResult.cpp \
    $${PWD}/OAIInstanceHealthCheckState.cpp \
    $${PWD}/OAIInstanceHealthCheckType.cpp \
    $${PWD}/OAIIpcMode.cpp \
    $${PWD}/OAIKernelCapabilities.cpp \
    $${PWD}/OAIKeyValuePair.cpp \
    $${PWD}/OAILaunchType.cpp \
    $${PWD}/OAILinuxParameters.cpp \
    $${PWD}/OAILinuxParameters_capabilities.cpp \
    $${PWD}/OAIListAccountSettingsRequest.cpp \
    $${PWD}/OAIListAccountSettingsResponse.cpp \
    $${PWD}/OAIListAttributesRequest.cpp \
    $${PWD}/OAIListAttributesResponse.cpp \
    $${PWD}/OAIListClustersRequest.cpp \
    $${PWD}/OAIListClustersResponse.cpp \
    $${PWD}/OAIListContainerInstancesRequest.cpp \
    $${PWD}/OAIListContainerInstancesResponse.cpp \
    $${PWD}/OAIListServicesByNamespaceRequest.cpp \
    $${PWD}/OAIListServicesByNamespaceResponse.cpp \
    $${PWD}/OAIListServicesRequest.cpp \
    $${PWD}/OAIListServicesResponse.cpp \
    $${PWD}/OAIListTagsForResourceRequest.cpp \
    $${PWD}/OAIListTagsForResourceResponse.cpp \
    $${PWD}/OAIListTaskDefinitionFamiliesRequest.cpp \
    $${PWD}/OAIListTaskDefinitionFamiliesResponse.cpp \
    $${PWD}/OAIListTaskDefinitionsRequest.cpp \
    $${PWD}/OAIListTaskDefinitionsResponse.cpp \
    $${PWD}/OAIListTasksRequest.cpp \
    $${PWD}/OAIListTasksResponse.cpp \
    $${PWD}/OAILoadBalancer.cpp \
    $${PWD}/OAILogConfiguration.cpp \
    $${PWD}/OAILogDriver.cpp \
    $${PWD}/OAIManagedAgent.cpp \
    $${PWD}/OAIManagedAgentName.cpp \
    $${PWD}/OAIManagedAgentStateChange.cpp \
    $${PWD}/OAIManagedScaling.cpp \
    $${PWD}/OAIManagedScalingStatus.cpp \
    $${PWD}/OAIManagedTerminationProtection.cpp \
    $${PWD}/OAIMountPoint.cpp \
    $${PWD}/OAINetworkBinding.cpp \
    $${PWD}/OAINetworkConfiguration.cpp \
    $${PWD}/OAINetworkConfiguration_awsvpcConfiguration.cpp \
    $${PWD}/OAINetworkInterface.cpp \
    $${PWD}/OAINetworkMode.cpp \
    $${PWD}/OAIOSFamily.cpp \
    $${PWD}/OAIPidMode.cpp \
    $${PWD}/OAIPlacementConstraint.cpp \
    $${PWD}/OAIPlacementConstraintType.cpp \
    $${PWD}/OAIPlacementStrategy.cpp \
    $${PWD}/OAIPlacementStrategyType.cpp \
    $${PWD}/OAIPlatformDevice.cpp \
    $${PWD}/OAIPlatformDeviceType.cpp \
    $${PWD}/OAIPortMapping.cpp \
    $${PWD}/OAIPropagateTags.cpp \
    $${PWD}/OAIProtectedTask.cpp \
    $${PWD}/OAIProxyConfiguration.cpp \
    $${PWD}/OAIProxyConfigurationType.cpp \
    $${PWD}/OAIPutAccountSettingDefaultRequest.cpp \
    $${PWD}/OAIPutAccountSettingDefaultResponse.cpp \
    $${PWD}/OAIPutAccountSettingDefaultResponse_setting.cpp \
    $${PWD}/OAIPutAccountSettingRequest.cpp \
    $${PWD}/OAIPutAccountSettingResponse.cpp \
    $${PWD}/OAIPutAccountSettingResponse_setting.cpp \
    $${PWD}/OAIPutAttributesRequest.cpp \
    $${PWD}/OAIPutAttributesResponse.cpp \
    $${PWD}/OAIPutClusterCapacityProvidersRequest.cpp \
    $${PWD}/OAIPutClusterCapacityProvidersResponse.cpp \
    $${PWD}/OAIPutClusterCapacityProvidersResponse_cluster.cpp \
    $${PWD}/OAIRegisterContainerInstanceRequest.cpp \
    $${PWD}/OAIRegisterContainerInstanceRequest_versionInfo.cpp \
    $${PWD}/OAIRegisterContainerInstanceResponse.cpp \
    $${PWD}/OAIRegisterContainerInstanceResponse_containerInstance.cpp \
    $${PWD}/OAIRegisterTaskDefinitionRequest.cpp \
    $${PWD}/OAIRegisterTaskDefinitionRequest_ephemeralStorage.cpp \
    $${PWD}/OAIRegisterTaskDefinitionRequest_proxyConfiguration.cpp \
    $${PWD}/OAIRegisterTaskDefinitionRequest_runtimePlatform.cpp \
    $${PWD}/OAIRegisterTaskDefinitionResponse.cpp \
    $${PWD}/OAIRegisterTaskDefinitionResponse_taskDefinition.cpp \
    $${PWD}/OAIRepositoryCredentials.cpp \
    $${PWD}/OAIResource.cpp \
    $${PWD}/OAIResourceRequirement.cpp \
    $${PWD}/OAIResourceType.cpp \
    $${PWD}/OAIRunTaskRequest.cpp \
    $${PWD}/OAIRunTaskRequest_networkConfiguration.cpp \
    $${PWD}/OAIRunTaskRequest_overrides.cpp \
    $${PWD}/OAIRunTaskResponse.cpp \
    $${PWD}/OAIRuntimePlatform.cpp \
    $${PWD}/OAIScale.cpp \
    $${PWD}/OAIScaleUnit.cpp \
    $${PWD}/OAISchedulingStrategy.cpp \
    $${PWD}/OAIScope.cpp \
    $${PWD}/OAISecret.cpp \
    $${PWD}/OAIService.cpp \
    $${PWD}/OAIServiceConnectClientAlias.cpp \
    $${PWD}/OAIServiceConnectConfiguration.cpp \
    $${PWD}/OAIServiceConnectService.cpp \
    $${PWD}/OAIServiceConnectServiceResource.cpp \
    $${PWD}/OAIServiceEvent.cpp \
    $${PWD}/OAIServiceField.cpp \
    $${PWD}/OAIServiceRegistry.cpp \
    $${PWD}/OAIService_deploymentController.cpp \
    $${PWD}/OAISession.cpp \
    $${PWD}/OAISetting.cpp \
    $${PWD}/OAISettingName.cpp \
    $${PWD}/OAISortOrder.cpp \
    $${PWD}/OAIStabilityStatus.cpp \
    $${PWD}/OAIStartTaskRequest.cpp \
    $${PWD}/OAIStartTaskRequest_networkConfiguration.cpp \
    $${PWD}/OAIStartTaskRequest_overrides.cpp \
    $${PWD}/OAIStartTaskResponse.cpp \
    $${PWD}/OAIStopTaskRequest.cpp \
    $${PWD}/OAIStopTaskResponse.cpp \
    $${PWD}/OAIStopTaskResponse_task.cpp \
    $${PWD}/OAISubmitAttachmentStateChangesRequest.cpp \
    $${PWD}/OAISubmitAttachmentStateChangesResponse.cpp \
    $${PWD}/OAISubmitContainerStateChangeRequest.cpp \
    $${PWD}/OAISubmitContainerStateChangeResponse.cpp \
    $${PWD}/OAISubmitTaskStateChangeRequest.cpp \
    $${PWD}/OAISubmitTaskStateChangeResponse.cpp \
    $${PWD}/OAISystemControl.cpp \
    $${PWD}/OAITag.cpp \
    $${PWD}/OAITagResourceRequest.cpp \
    $${PWD}/OAITargetType.cpp \
    $${PWD}/OAITask.cpp \
    $${PWD}/OAITaskDefinition.cpp \
    $${PWD}/OAITaskDefinitionFamilyStatus.cpp \
    $${PWD}/OAITaskDefinitionField.cpp \
    $${PWD}/OAITaskDefinitionPlacementConstraint.cpp \
    $${PWD}/OAITaskDefinitionPlacementConstraintType.cpp \
    $${PWD}/OAITaskDefinitionStatus.cpp \
    $${PWD}/OAITaskDefinition_ephemeralStorage.cpp \
    $${PWD}/OAITaskDefinition_proxyConfiguration.cpp \
    $${PWD}/OAITaskDefinition_runtimePlatform.cpp \
    $${PWD}/OAITaskField.cpp \
    $${PWD}/OAITaskOverride.cpp \
    $${PWD}/OAITaskOverride_ephemeralStorage.cpp \
    $${PWD}/OAITaskSet.cpp \
    $${PWD}/OAITaskSetField.cpp \
    $${PWD}/OAITaskSet_networkConfiguration.cpp \
    $${PWD}/OAITaskSet_scale.cpp \
    $${PWD}/OAITaskStopCode.cpp \
    $${PWD}/OAITask_ephemeralStorage.cpp \
    $${PWD}/OAITask_overrides.cpp \
    $${PWD}/OAITmpfs.cpp \
    $${PWD}/OAITransportProtocol.cpp \
    $${PWD}/OAIUlimit.cpp \
    $${PWD}/OAIUlimitName.cpp \
    $${PWD}/OAIUntagResourceRequest.cpp \
    $${PWD}/OAIUpdateCapacityProviderRequest.cpp \
    $${PWD}/OAIUpdateCapacityProviderRequest_autoScalingGroupProvider.cpp \
    $${PWD}/OAIUpdateCapacityProviderResponse.cpp \
    $${PWD}/OAIUpdateCapacityProviderResponse_capacityProvider.cpp \
    $${PWD}/OAIUpdateClusterRequest.cpp \
    $${PWD}/OAIUpdateClusterRequest_configuration.cpp \
    $${PWD}/OAIUpdateClusterResponse.cpp \
    $${PWD}/OAIUpdateClusterSettingsRequest.cpp \
    $${PWD}/OAIUpdateClusterSettingsResponse.cpp \
    $${PWD}/OAIUpdateClusterSettingsResponse_cluster.cpp \
    $${PWD}/OAIUpdateContainerAgentRequest.cpp \
    $${PWD}/OAIUpdateContainerAgentResponse.cpp \
    $${PWD}/OAIUpdateContainerAgentResponse_containerInstance.cpp \
    $${PWD}/OAIUpdateContainerInstancesStateRequest.cpp \
    $${PWD}/OAIUpdateContainerInstancesStateResponse.cpp \
    $${PWD}/OAIUpdateServicePrimaryTaskSetRequest.cpp \
    $${PWD}/OAIUpdateServicePrimaryTaskSetResponse.cpp \
    $${PWD}/OAIUpdateServicePrimaryTaskSetResponse_taskSet.cpp \
    $${PWD}/OAIUpdateServiceRequest.cpp \
    $${PWD}/OAIUpdateServiceRequest_networkConfiguration.cpp \
    $${PWD}/OAIUpdateServiceResponse.cpp \
    $${PWD}/OAIUpdateServiceResponse_service.cpp \
    $${PWD}/OAIUpdateTaskProtectionRequest.cpp \
    $${PWD}/OAIUpdateTaskProtectionResponse.cpp \
    $${PWD}/OAIUpdateTaskSetRequest.cpp \
    $${PWD}/OAIUpdateTaskSetResponse.cpp \
    $${PWD}/OAIVersionInfo.cpp \
    $${PWD}/OAIVolume.cpp \
    $${PWD}/OAIVolumeFrom.cpp \
    $${PWD}/OAIVolume_dockerVolumeConfiguration.cpp \
    $${PWD}/OAIVolume_efsVolumeConfiguration.cpp \
    $${PWD}/OAIVolume_fsxWindowsFileServerVolumeConfiguration.cpp \
    $${PWD}/OAIVolume_host.cpp \
# APIs
    $${PWD}/OAIDefaultApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
