QT += network

HEADERS += \
# Models
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1Anomaly.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1AnrRateMetricSet.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1App.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1AppVersion.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1CrashRateMetricSet.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1DecimalConfidenceInterval.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1DeviceId.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1DeviceModelSummary.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1DimensionValue.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1ErrorCountMetricSet.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1ErrorIssue.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1ErrorReport.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1ExcessiveWakeupRateMetricSet.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1FreshnessInfo.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1FreshnessInfoFreshness.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1ListAnomaliesResponse.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1MetricValue.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1MetricsRow.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1OsVersion.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QueryAnrRateMetricSetRequest.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QueryAnrRateMetricSetResponse.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QueryCrashRateMetricSetRequest.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QueryCrashRateMetricSetResponse.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QueryErrorCountMetricSetRequest.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QueryErrorCountMetricSetResponse.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QueryExcessiveWakeupRateMetricSetRequest.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QueryExcessiveWakeupRateMetricSetResponse.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QuerySlowRenderingRateMetricSetRequest.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QuerySlowRenderingRateMetricSetResponse.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QuerySlowStartRateMetricSetRequest.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QuerySlowStartRateMetricSetResponse.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QueryStuckBackgroundWakelockRateMetricSetRequest.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QueryStuckBackgroundWakelockRateMetricSetResponse.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1Release.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1ReleaseFilterOptions.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1SearchAccessibleAppsResponse.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1SearchErrorIssuesResponse.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1SearchErrorReportsResponse.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1SlowRenderingRateMetricSet.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1SlowStartRateMetricSet.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1StuckBackgroundWakelockRateMetricSet.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1TimelineSpec.h \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1Track.h \
    $${PWD}/OAIGoogleTypeDateTime.h \
    $${PWD}/OAIGoogleTypeDecimal.h \
    $${PWD}/OAIGoogleTypeTimeZone.h \
# APIs
    $${PWD}/OAIAnomaliesApi.h \
    $${PWD}/OAIAppsApi.h \
    $${PWD}/OAIVitalsApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1Anomaly.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1AnrRateMetricSet.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1App.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1AppVersion.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1CrashRateMetricSet.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1DecimalConfidenceInterval.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1DeviceId.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1DeviceModelSummary.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1DimensionValue.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1ErrorCountMetricSet.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1ErrorIssue.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1ErrorReport.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1ExcessiveWakeupRateMetricSet.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1FreshnessInfo.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1FreshnessInfoFreshness.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1ListAnomaliesResponse.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1MetricValue.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1MetricsRow.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1OsVersion.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QueryAnrRateMetricSetRequest.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QueryAnrRateMetricSetResponse.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QueryCrashRateMetricSetRequest.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QueryCrashRateMetricSetResponse.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QueryErrorCountMetricSetRequest.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QueryErrorCountMetricSetResponse.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QueryExcessiveWakeupRateMetricSetRequest.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QueryExcessiveWakeupRateMetricSetResponse.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QuerySlowRenderingRateMetricSetRequest.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QuerySlowRenderingRateMetricSetResponse.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QuerySlowStartRateMetricSetRequest.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QuerySlowStartRateMetricSetResponse.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QueryStuckBackgroundWakelockRateMetricSetRequest.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1QueryStuckBackgroundWakelockRateMetricSetResponse.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1Release.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1ReleaseFilterOptions.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1SearchAccessibleAppsResponse.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1SearchErrorIssuesResponse.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1SearchErrorReportsResponse.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1SlowRenderingRateMetricSet.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1SlowStartRateMetricSet.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1StuckBackgroundWakelockRateMetricSet.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1TimelineSpec.cpp \
    $${PWD}/OAIGooglePlayDeveloperReportingV1alpha1Track.cpp \
    $${PWD}/OAIGoogleTypeDateTime.cpp \
    $${PWD}/OAIGoogleTypeDecimal.cpp \
    $${PWD}/OAIGoogleTypeTimeZone.cpp \
# APIs
    $${PWD}/OAIAnomaliesApi.cpp \
    $${PWD}/OAIAppsApi.cpp \
    $${PWD}/OAIVitalsApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
