/**
 * Amazon AppStream
 * <fullname>Amazon AppStream 2.0</fullname> <p>This is the <i>Amazon AppStream 2.0 API Reference</i>. This documentation provides descriptions and syntax for each of the actions and data types in AppStream 2.0. AppStream 2.0 is a fully managed, secure application streaming service that lets you stream desktop applications to users without rewriting applications. AppStream 2.0 manages the AWS resources that are required to host and run your applications, scales automatically, and provides access to your users on demand. </p> <note> <p>You can call the AppStream 2.0 API operations by using an interface VPC endpoint (interface endpoint). For more information, see <a href=\"https://docs.aws.amazon.com/appstream2/latest/developerguide/access-api-cli-through-interface-vpc-endpoint.html\">Access AppStream 2.0 API Operations and CLI Commands Through an Interface VPC Endpoint</a> in the <i>Amazon AppStream 2.0 Administration Guide</i>.</p> </note> <p>To learn more about AppStream 2.0, see the following resources:</p> <ul> <li> <p> <a href=\"http://aws.amazon.com/appstream2\">Amazon AppStream 2.0 product page</a> </p> </li> <li> <p> <a href=\"http://aws.amazon.com/documentation/appstream2\">Amazon AppStream 2.0 documentation</a> </p> </li> </ul>
 *
 * The version of the OpenAPI document: 2016-12-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AuthenticationType from './AuthenticationType';
import MessageAction from './MessageAction';

/**
 * The CreateUserRequest model module.
 * @module model/CreateUserRequest
 * @version 2016-12-01
 */
class CreateUserRequest {
    /**
     * Constructs a new <code>CreateUserRequest</code>.
     * @alias module:model/CreateUserRequest
     * @param userName {String} 
     * @param authenticationType {module:model/AuthenticationType} 
     */
    constructor(userName, authenticationType) { 
        
        CreateUserRequest.initialize(this, userName, authenticationType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userName, authenticationType) { 
        obj['UserName'] = userName;
        obj['AuthenticationType'] = authenticationType;
    }

    /**
     * Constructs a <code>CreateUserRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateUserRequest} obj Optional instance to populate.
     * @return {module:model/CreateUserRequest} The populated <code>CreateUserRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateUserRequest();

            if (data.hasOwnProperty('UserName')) {
                obj['UserName'] = ApiClient.convertToType(data['UserName'], 'String');
            }
            if (data.hasOwnProperty('MessageAction')) {
                obj['MessageAction'] = ApiClient.convertToType(data['MessageAction'], MessageAction);
            }
            if (data.hasOwnProperty('FirstName')) {
                obj['FirstName'] = ApiClient.convertToType(data['FirstName'], 'String');
            }
            if (data.hasOwnProperty('LastName')) {
                obj['LastName'] = ApiClient.convertToType(data['LastName'], 'String');
            }
            if (data.hasOwnProperty('AuthenticationType')) {
                obj['AuthenticationType'] = ApiClient.convertToType(data['AuthenticationType'], AuthenticationType);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateUserRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateUserRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateUserRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `UserName`
        if (data['UserName']) { // data not null
          String.validateJSON(data['UserName']);
        }
        // validate the optional field `MessageAction`
        if (data['MessageAction']) { // data not null
          MessageAction.validateJSON(data['MessageAction']);
        }
        // validate the optional field `FirstName`
        if (data['FirstName']) { // data not null
          String.validateJSON(data['FirstName']);
        }
        // validate the optional field `LastName`
        if (data['LastName']) { // data not null
          String.validateJSON(data['LastName']);
        }
        // validate the optional field `AuthenticationType`
        if (data['AuthenticationType']) { // data not null
          AuthenticationType.validateJSON(data['AuthenticationType']);
        }

        return true;
    }


}

CreateUserRequest.RequiredProperties = ["UserName", "AuthenticationType"];

/**
 * @member {String} UserName
 */
CreateUserRequest.prototype['UserName'] = undefined;

/**
 * @member {module:model/MessageAction} MessageAction
 */
CreateUserRequest.prototype['MessageAction'] = undefined;

/**
 * @member {String} FirstName
 */
CreateUserRequest.prototype['FirstName'] = undefined;

/**
 * @member {String} LastName
 */
CreateUserRequest.prototype['LastName'] = undefined;

/**
 * @member {module:model/AuthenticationType} AuthenticationType
 */
CreateUserRequest.prototype['AuthenticationType'] = undefined;






export default CreateUserRequest;

