openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: Accesses Analytics report data.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Analytics Reporting API
  version: v4
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
  x-origin:
  - converter:
      url: https://github.com/mermade/oas-kit
      version: 7.0.4
    format: google
    url: https://analyticsreporting.googleapis.com/$discovery/rest?version=v4
    version: v1
  x-providerName: googleapis.com
  x-serviceName: analyticsreporting
servers:
- url: https://analyticsreporting.googleapis.com/
tags:
- name: reports
- name: userActivity
paths:
  /v4/reports:batchGet:
    post:
      description: Returns the Analytics data.
      operationId: analyticsreporting_reports_batch_get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
        Oauth2c:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - reports
      x-openapi-router-controller: openapi_server.controllers.reports_controller
  /v4/userActivity:search:
    post:
      description: Returns User Activity data.
      operationId: analyticsreporting_user_activity_search
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
        Oauth2c:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - userActivity
      x-openapi-router-controller: openapi_server.controllers.user_activity_controller
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/analytics: View and manage your Google
              Analytics data
            https://www.googleapis.com/auth/analytics.readonly: See and download your
              Google Analytics data
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/analytics: View and manage your Google
              Analytics data
            https://www.googleapis.com/auth/analytics.readonly: See and download your
              Google Analytics data
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller.info_from_Oauth2c
      x-scopeValidateFunc: openapi_server.controllers.security_controller.validate_scope_Oauth2c
