QT += network

HEADERS += \
# Models
    $${PWD}/OAIAccessRequester.h \
    $${PWD}/OAIApplicationSetting.h \
    $${PWD}/OAIAwardEmoji.h \
    $${PWD}/OAIBasicProjectDetails.h \
    $${PWD}/OAIBoard.h \
    $${PWD}/OAIBuild.h \
    $${PWD}/OAIBuildArtifactFile.h \
    $${PWD}/OAICommitNote.h \
    $${PWD}/OAICommitStatus.h \
    $${PWD}/OAICompare.h \
    $${PWD}/OAIContributor.h \
    $${PWD}/OAIDeployment.h \
    $${PWD}/OAIEmail.h \
    $${PWD}/OAIEnvironment.h \
    $${PWD}/OAIEnvironmentBasic.h \
    $${PWD}/OAIEvent.h \
    $${PWD}/OAIGlobalNotificationSetting.h \
    $${PWD}/OAIGroup.h \
    $${PWD}/OAIGroupDetail.h \
    $${PWD}/OAIHook.h \
    $${PWD}/OAIIdentity.h \
    $${PWD}/OAIIssue.h \
    $${PWD}/OAILabel.h \
    $${PWD}/OAILabelBasic.h \
    $${PWD}/OAIList.h \
    $${PWD}/OAIMRNote.h \
    $${PWD}/OAIMember.h \
    $${PWD}/OAIMergeRequest.h \
    $${PWD}/OAIMergeRequestChanges.h \
    $${PWD}/OAIMergeRequestDiff.h \
    $${PWD}/OAIMergeRequestDiffFull.h \
    $${PWD}/OAIMilestone.h \
    $${PWD}/OAINamespace.h \
    $${PWD}/OAINote.h \
    $${PWD}/OAINotificationSetting.h \
    $${PWD}/OAIPersonalSnippet.h \
    $${PWD}/OAIPipeline.h \
    $${PWD}/OAIPipelineBasic.h \
    $${PWD}/OAIPostV3CiLint_request.h \
    $${PWD}/OAIPostV3GroupsIdMembers_request.h \
    $${PWD}/OAIPostV3Groups_request.h \
    $${PWD}/OAIPostV3Hooks_request.h \
    $${PWD}/OAIPostV3ProjectsForkId_request.h \
    $${PWD}/OAIPostV3ProjectsIdBoardsBoardIdLists_request.h \
    $${PWD}/OAIPostV3ProjectsIdDeployKeys_request.h \
    $${PWD}/OAIPostV3ProjectsIdEnvironments_request.h \
    $${PWD}/OAIPostV3ProjectsIdHooks_request.h \
    $${PWD}/OAIPostV3ProjectsIdIssuesIssueIdAddSpentTime_request.h \
    $${PWD}/OAIPostV3ProjectsIdIssuesIssueIdAwardEmoji_request.h \
    $${PWD}/OAIPostV3ProjectsIdIssuesIssueIdMove_request.h \
    $${PWD}/OAIPostV3ProjectsIdIssuesNoteableIdNotes_request.h \
    $${PWD}/OAIPostV3ProjectsIdIssues_request.h \
    $${PWD}/OAIPostV3ProjectsIdLabels_request.h \
    $${PWD}/OAIPostV3ProjectsIdMergeRequestMergeRequestIdComments_request.h \
    $${PWD}/OAIPostV3ProjectsIdMergeRequests_request.h \
    $${PWD}/OAIPostV3ProjectsIdMilestones_request.h \
    $${PWD}/OAIPostV3ProjectsIdPipeline_request.h \
    $${PWD}/OAIPostV3ProjectsIdRepositoryBranches_request.h \
    $${PWD}/OAIPostV3ProjectsIdRepositoryCommitsShaCherryPick_request.h \
    $${PWD}/OAIPostV3ProjectsIdRepositoryCommitsShaComments_request.h \
    $${PWD}/OAIPostV3ProjectsIdRepositoryCommits_request.h \
    $${PWD}/OAIPostV3ProjectsIdRepositoryTags_request.h \
    $${PWD}/OAIPostV3ProjectsIdRunners_request.h \
    $${PWD}/OAIPostV3ProjectsIdShare_request.h \
    $${PWD}/OAIPostV3ProjectsIdSnippets_request.h \
    $${PWD}/OAIPostV3ProjectsIdStatusesSha_request.h \
    $${PWD}/OAIPostV3ProjectsIdUploads_request.h \
    $${PWD}/OAIPostV3ProjectsIdVariables_request.h \
    $${PWD}/OAIPostV3ProjectsId_refRef_triggerBuilds_request.h \
    $${PWD}/OAIPostV3ProjectsUserUserId_request.h \
    $${PWD}/OAIPostV3Projects_request.h \
    $${PWD}/OAIPostV3Session_request.h \
    $${PWD}/OAIPostV3Snippets_request.h \
    $${PWD}/OAIPostV3UserEmails_request.h \
    $${PWD}/OAIPostV3UserKeys_request.h \
    $${PWD}/OAIPostV3UsersIdEmails_request.h \
    $${PWD}/OAIPostV3Users_request.h \
    $${PWD}/OAIProject.h \
    $${PWD}/OAIProjectGroupLink.h \
    $${PWD}/OAIProjectHook.h \
    $${PWD}/OAIProjectService.h \
    $${PWD}/OAIProjectSnippet.h \
    $${PWD}/OAIProjectStatistics.h \
    $${PWD}/OAIProjectWithAccess.h \
    $${PWD}/OAIPutV3ApplicationSettings_request.h \
    $${PWD}/OAIPutV3GroupsIdAccessRequestsUserIdApprove_request.h \
    $${PWD}/OAIPutV3GroupsIdMembersUserId_request.h \
    $${PWD}/OAIPutV3GroupsIdNotificationSettings_request.h \
    $${PWD}/OAIPutV3GroupsId_request.h \
    $${PWD}/OAIPutV3NotificationSettings_request.h \
    $${PWD}/OAIPutV3ProjectsIdBoardsBoardIdListsListId_request.h \
    $${PWD}/OAIPutV3ProjectsIdEnvironmentsEnvironmentId_request.h \
    $${PWD}/OAIPutV3ProjectsIdIssuesIssueId_request.h \
    $${PWD}/OAIPutV3ProjectsIdIssuesNoteableIdNotesNoteId_request.h \
    $${PWD}/OAIPutV3ProjectsIdLabels_request.h \
    $${PWD}/OAIPutV3ProjectsIdMergeRequestMergeRequestIdMerge_request.h \
    $${PWD}/OAIPutV3ProjectsIdMergeRequestMergeRequestId_request.h \
    $${PWD}/OAIPutV3ProjectsIdMilestonesMilestoneId_request.h \
    $${PWD}/OAIPutV3ProjectsIdNotificationSettings_request.h \
    $${PWD}/OAIPutV3ProjectsIdRepositoryBranchesBranchProtect_request.h \
    $${PWD}/OAIPutV3ProjectsIdRepositoryFiles_request.h \
    $${PWD}/OAIPutV3ProjectsIdRepositoryTagsTagNameRelease_request.h \
    $${PWD}/OAIPutV3ProjectsIdServicesAsana_request.h \
    $${PWD}/OAIPutV3ProjectsIdServicesAssembla_request.h \
    $${PWD}/OAIPutV3ProjectsIdServicesBamboo_request.h \
    $${PWD}/OAIPutV3ProjectsIdServicesBugzilla_request.h \
    $${PWD}/OAIPutV3ProjectsIdServicesBuildkite_request.h \
    $${PWD}/OAIPutV3ProjectsIdServicesBuildsEmail_request.h \
    $${PWD}/OAIPutV3ProjectsIdServicesCampfire_request.h \
    $${PWD}/OAIPutV3ProjectsIdServicesDroneCi_request.h \
    $${PWD}/OAIPutV3ProjectsIdServicesEmailsOnPush_request.h \
    $${PWD}/OAIPutV3ProjectsIdServicesExternalWiki_request.h \
    $${PWD}/OAIPutV3ProjectsIdServicesFlowdock_request.h \
    $${PWD}/OAIPutV3ProjectsIdServicesGemnasium_request.h \
    $${PWD}/OAIPutV3ProjectsIdServicesHipchat_request.h \
    $${PWD}/OAIPutV3ProjectsIdServicesIrker_request.h \
    $${PWD}/OAIPutV3ProjectsIdServicesJira_request.h \
    $${PWD}/OAIPutV3ProjectsIdServicesKubernetes_request.h \
    $${PWD}/OAIPutV3ProjectsIdServicesMattermostSlashCommands_request.h \
    $${PWD}/OAIPutV3ProjectsIdServicesMattermost_request.h \
    $${PWD}/OAIPutV3ProjectsIdServicesPipelinesEmail_request.h \
    $${PWD}/OAIPutV3ProjectsIdServicesPivotaltracker_request.h \
    $${PWD}/OAIPutV3ProjectsIdServicesPushover_request.h \
    $${PWD}/OAIPutV3ProjectsIdServicesRedmine_request.h \
    $${PWD}/OAIPutV3ProjectsIdServicesSlackSlashCommands_request.h \
    $${PWD}/OAIPutV3ProjectsIdServicesSlack_request.h \
    $${PWD}/OAIPutV3ProjectsIdServicesTeamcity_request.h \
    $${PWD}/OAIPutV3ProjectsIdSnippetsSnippetId_request.h \
    $${PWD}/OAIPutV3ProjectsIdVariablesKey_request.h \
    $${PWD}/OAIPutV3ProjectsId_request.h \
    $${PWD}/OAIPutV3RunnersId_request.h \
    $${PWD}/OAIPutV3SnippetsId_request.h \
    $${PWD}/OAIPutV3UsersId_request.h \
    $${PWD}/OAIRelease.h \
    $${PWD}/OAIRepoBranch.h \
    $${PWD}/OAIRepoCommit.h \
    $${PWD}/OAIRepoCommitDetail.h \
    $${PWD}/OAIRepoCommitStats.h \
    $${PWD}/OAIRepoDiff.h \
    $${PWD}/OAIRepoLicense.h \
    $${PWD}/OAIRepoTag.h \
    $${PWD}/OAIRepoTreeObject.h \
    $${PWD}/OAIRunner.h \
    $${PWD}/OAIRunnerDetails.h \
    $${PWD}/OAISSHKey.h \
    $${PWD}/OAISSHKeyWithUser.h \
    $${PWD}/OAITemplate.h \
    $${PWD}/OAITemplatesList.h \
    $${PWD}/OAITodo.h \
    $${PWD}/OAITrigger.h \
    $${PWD}/OAITriggerRequest.h \
    $${PWD}/OAIUser.h \
    $${PWD}/OAIUserBasic.h \
    $${PWD}/OAIUserPublic.h \
    $${PWD}/OAIUserWithPrivateToken.h \
    $${PWD}/OAIVariable.h \
# APIs
    $${PWD}/OAIApplicationApi.h \
    $${PWD}/OAICiApi.h \
    $${PWD}/OAIDeployKeysApi.h \
    $${PWD}/OAIDockerfilesApi.h \
    $${PWD}/OAIGitignoresApi.h \
    $${PWD}/OAIGitlabCiYmlsApi.h \
    $${PWD}/OAIGroupsApi.h \
    $${PWD}/OAIHooksApi.h \
    $${PWD}/OAIInternalApi.h \
    $${PWD}/OAIIssuesApi.h \
    $${PWD}/OAIKeysApi.h \
    $${PWD}/OAILicensesApi.h \
    $${PWD}/OAINamespacesApi.h \
    $${PWD}/OAINotificationSettingsApi.h \
    $${PWD}/OAIProjectsApi.h \
    $${PWD}/OAIRunnersApi.h \
    $${PWD}/OAISessionApi.h \
    $${PWD}/OAISidekiqApi.h \
    $${PWD}/OAISnippetsApi.h \
    $${PWD}/OAITemplatesApi.h \
    $${PWD}/OAITodosApi.h \
    $${PWD}/OAIUserApi.h \
    $${PWD}/OAIUsersApi.h \
    $${PWD}/OAIVersionApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAccessRequester.cpp \
    $${PWD}/OAIApplicationSetting.cpp \
    $${PWD}/OAIAwardEmoji.cpp \
    $${PWD}/OAIBasicProjectDetails.cpp \
    $${PWD}/OAIBoard.cpp \
    $${PWD}/OAIBuild.cpp \
    $${PWD}/OAIBuildArtifactFile.cpp \
    $${PWD}/OAICommitNote.cpp \
    $${PWD}/OAICommitStatus.cpp \
    $${PWD}/OAICompare.cpp \
    $${PWD}/OAIContributor.cpp \
    $${PWD}/OAIDeployment.cpp \
    $${PWD}/OAIEmail.cpp \
    $${PWD}/OAIEnvironment.cpp \
    $${PWD}/OAIEnvironmentBasic.cpp \
    $${PWD}/OAIEvent.cpp \
    $${PWD}/OAIGlobalNotificationSetting.cpp \
    $${PWD}/OAIGroup.cpp \
    $${PWD}/OAIGroupDetail.cpp \
    $${PWD}/OAIHook.cpp \
    $${PWD}/OAIIdentity.cpp \
    $${PWD}/OAIIssue.cpp \
    $${PWD}/OAILabel.cpp \
    $${PWD}/OAILabelBasic.cpp \
    $${PWD}/OAIList.cpp \
    $${PWD}/OAIMRNote.cpp \
    $${PWD}/OAIMember.cpp \
    $${PWD}/OAIMergeRequest.cpp \
    $${PWD}/OAIMergeRequestChanges.cpp \
    $${PWD}/OAIMergeRequestDiff.cpp \
    $${PWD}/OAIMergeRequestDiffFull.cpp \
    $${PWD}/OAIMilestone.cpp \
    $${PWD}/OAINamespace.cpp \
    $${PWD}/OAINote.cpp \
    $${PWD}/OAINotificationSetting.cpp \
    $${PWD}/OAIPersonalSnippet.cpp \
    $${PWD}/OAIPipeline.cpp \
    $${PWD}/OAIPipelineBasic.cpp \
    $${PWD}/OAIPostV3CiLint_request.cpp \
    $${PWD}/OAIPostV3GroupsIdMembers_request.cpp \
    $${PWD}/OAIPostV3Groups_request.cpp \
    $${PWD}/OAIPostV3Hooks_request.cpp \
    $${PWD}/OAIPostV3ProjectsForkId_request.cpp \
    $${PWD}/OAIPostV3ProjectsIdBoardsBoardIdLists_request.cpp \
    $${PWD}/OAIPostV3ProjectsIdDeployKeys_request.cpp \
    $${PWD}/OAIPostV3ProjectsIdEnvironments_request.cpp \
    $${PWD}/OAIPostV3ProjectsIdHooks_request.cpp \
    $${PWD}/OAIPostV3ProjectsIdIssuesIssueIdAddSpentTime_request.cpp \
    $${PWD}/OAIPostV3ProjectsIdIssuesIssueIdAwardEmoji_request.cpp \
    $${PWD}/OAIPostV3ProjectsIdIssuesIssueIdMove_request.cpp \
    $${PWD}/OAIPostV3ProjectsIdIssuesNoteableIdNotes_request.cpp \
    $${PWD}/OAIPostV3ProjectsIdIssues_request.cpp \
    $${PWD}/OAIPostV3ProjectsIdLabels_request.cpp \
    $${PWD}/OAIPostV3ProjectsIdMergeRequestMergeRequestIdComments_request.cpp \
    $${PWD}/OAIPostV3ProjectsIdMergeRequests_request.cpp \
    $${PWD}/OAIPostV3ProjectsIdMilestones_request.cpp \
    $${PWD}/OAIPostV3ProjectsIdPipeline_request.cpp \
    $${PWD}/OAIPostV3ProjectsIdRepositoryBranches_request.cpp \
    $${PWD}/OAIPostV3ProjectsIdRepositoryCommitsShaCherryPick_request.cpp \
    $${PWD}/OAIPostV3ProjectsIdRepositoryCommitsShaComments_request.cpp \
    $${PWD}/OAIPostV3ProjectsIdRepositoryCommits_request.cpp \
    $${PWD}/OAIPostV3ProjectsIdRepositoryTags_request.cpp \
    $${PWD}/OAIPostV3ProjectsIdRunners_request.cpp \
    $${PWD}/OAIPostV3ProjectsIdShare_request.cpp \
    $${PWD}/OAIPostV3ProjectsIdSnippets_request.cpp \
    $${PWD}/OAIPostV3ProjectsIdStatusesSha_request.cpp \
    $${PWD}/OAIPostV3ProjectsIdUploads_request.cpp \
    $${PWD}/OAIPostV3ProjectsIdVariables_request.cpp \
    $${PWD}/OAIPostV3ProjectsId_refRef_triggerBuilds_request.cpp \
    $${PWD}/OAIPostV3ProjectsUserUserId_request.cpp \
    $${PWD}/OAIPostV3Projects_request.cpp \
    $${PWD}/OAIPostV3Session_request.cpp \
    $${PWD}/OAIPostV3Snippets_request.cpp \
    $${PWD}/OAIPostV3UserEmails_request.cpp \
    $${PWD}/OAIPostV3UserKeys_request.cpp \
    $${PWD}/OAIPostV3UsersIdEmails_request.cpp \
    $${PWD}/OAIPostV3Users_request.cpp \
    $${PWD}/OAIProject.cpp \
    $${PWD}/OAIProjectGroupLink.cpp \
    $${PWD}/OAIProjectHook.cpp \
    $${PWD}/OAIProjectService.cpp \
    $${PWD}/OAIProjectSnippet.cpp \
    $${PWD}/OAIProjectStatistics.cpp \
    $${PWD}/OAIProjectWithAccess.cpp \
    $${PWD}/OAIPutV3ApplicationSettings_request.cpp \
    $${PWD}/OAIPutV3GroupsIdAccessRequestsUserIdApprove_request.cpp \
    $${PWD}/OAIPutV3GroupsIdMembersUserId_request.cpp \
    $${PWD}/OAIPutV3GroupsIdNotificationSettings_request.cpp \
    $${PWD}/OAIPutV3GroupsId_request.cpp \
    $${PWD}/OAIPutV3NotificationSettings_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdBoardsBoardIdListsListId_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdEnvironmentsEnvironmentId_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdIssuesIssueId_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdIssuesNoteableIdNotesNoteId_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdLabels_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdMergeRequestMergeRequestIdMerge_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdMergeRequestMergeRequestId_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdMilestonesMilestoneId_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdNotificationSettings_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdRepositoryBranchesBranchProtect_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdRepositoryFiles_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdRepositoryTagsTagNameRelease_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdServicesAsana_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdServicesAssembla_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdServicesBamboo_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdServicesBugzilla_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdServicesBuildkite_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdServicesBuildsEmail_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdServicesCampfire_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdServicesDroneCi_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdServicesEmailsOnPush_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdServicesExternalWiki_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdServicesFlowdock_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdServicesGemnasium_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdServicesHipchat_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdServicesIrker_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdServicesJira_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdServicesKubernetes_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdServicesMattermostSlashCommands_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdServicesMattermost_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdServicesPipelinesEmail_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdServicesPivotaltracker_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdServicesPushover_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdServicesRedmine_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdServicesSlackSlashCommands_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdServicesSlack_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdServicesTeamcity_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdSnippetsSnippetId_request.cpp \
    $${PWD}/OAIPutV3ProjectsIdVariablesKey_request.cpp \
    $${PWD}/OAIPutV3ProjectsId_request.cpp \
    $${PWD}/OAIPutV3RunnersId_request.cpp \
    $${PWD}/OAIPutV3SnippetsId_request.cpp \
    $${PWD}/OAIPutV3UsersId_request.cpp \
    $${PWD}/OAIRelease.cpp \
    $${PWD}/OAIRepoBranch.cpp \
    $${PWD}/OAIRepoCommit.cpp \
    $${PWD}/OAIRepoCommitDetail.cpp \
    $${PWD}/OAIRepoCommitStats.cpp \
    $${PWD}/OAIRepoDiff.cpp \
    $${PWD}/OAIRepoLicense.cpp \
    $${PWD}/OAIRepoTag.cpp \
    $${PWD}/OAIRepoTreeObject.cpp \
    $${PWD}/OAIRunner.cpp \
    $${PWD}/OAIRunnerDetails.cpp \
    $${PWD}/OAISSHKey.cpp \
    $${PWD}/OAISSHKeyWithUser.cpp \
    $${PWD}/OAITemplate.cpp \
    $${PWD}/OAITemplatesList.cpp \
    $${PWD}/OAITodo.cpp \
    $${PWD}/OAITrigger.cpp \
    $${PWD}/OAITriggerRequest.cpp \
    $${PWD}/OAIUser.cpp \
    $${PWD}/OAIUserBasic.cpp \
    $${PWD}/OAIUserPublic.cpp \
    $${PWD}/OAIUserWithPrivateToken.cpp \
    $${PWD}/OAIVariable.cpp \
# APIs
    $${PWD}/OAIApplicationApi.cpp \
    $${PWD}/OAICiApi.cpp \
    $${PWD}/OAIDeployKeysApi.cpp \
    $${PWD}/OAIDockerfilesApi.cpp \
    $${PWD}/OAIGitignoresApi.cpp \
    $${PWD}/OAIGitlabCiYmlsApi.cpp \
    $${PWD}/OAIGroupsApi.cpp \
    $${PWD}/OAIHooksApi.cpp \
    $${PWD}/OAIInternalApi.cpp \
    $${PWD}/OAIIssuesApi.cpp \
    $${PWD}/OAIKeysApi.cpp \
    $${PWD}/OAILicensesApi.cpp \
    $${PWD}/OAINamespacesApi.cpp \
    $${PWD}/OAINotificationSettingsApi.cpp \
    $${PWD}/OAIProjectsApi.cpp \
    $${PWD}/OAIRunnersApi.cpp \
    $${PWD}/OAISessionApi.cpp \
    $${PWD}/OAISidekiqApi.cpp \
    $${PWD}/OAISnippetsApi.cpp \
    $${PWD}/OAITemplatesApi.cpp \
    $${PWD}/OAITodosApi.cpp \
    $${PWD}/OAIUserApi.cpp \
    $${PWD}/OAIUsersApi.cpp \
    $${PWD}/OAIVersionApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
